### ISSUE TITLE
SharePoint 2016 search service application creation issue.

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#1]
SP 2016 New search service application creation error as following powershell script

Set-SPEnterpriseSearchTopology : Topology activation failed.
At line:1 char:1
+ Set-SPEnterpriseSearchTopology -Identity $newTopology
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (Microsoft.Offic...tSearchTopology:
   SetSearchTopology) [Set-SPEnterpriseSearchTopology], SearchTopologyActivat
  ionException
    + FullyQualifiedErrorId : Microsoft.Office.Server.Search.Cmdlet.SetSearchTopology

----------
⚠ Idea migrated from UserVoice

**Created By:** Mohammedisteyaq Mansuri
**Created On:** 2018/03/06 20:24:50 +0000
**Votes at Migration:** 1
**Supporters at Migration:** 1

**Comment by dend** [comment]
Product feedback not related to docs.microsoft.com. Closing.
