### ISSUE TITLE
Hard to get to Microsoft edge dev site and Dev Dashboard

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#10]
Really hard to get to, it would be nice if it showed those two products.

----------
⚠ Idea migrated from UserVoice

**Created By:** Independent LLC
**Created On:** 2018/03/02 04:39:14 +0000
**Votes at Migration:** 1
**Supporters at Migration:** 1

**Comment by dend** [comment]
Not related to docs.microsoft.com. Closing.
