### ISSUE TITLE
Allow Preview of Build Output for Doc Changes to Outside World

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#100]
I just got a build report, great. There's a preview url, great. When I try to view it though, I get: We are sorry, the page is forbidden

I ***ume it is only accessible to MSFT employees? Can it be opened to all contributors?

https://github.com/aspnet/Docs/issues/4670

----------
⚠ Idea migrated from UserVoice

**Created By:** Mike DePouw
**Created On:** 2017/10/31 14:25:49 +0000
**Votes at Migration:** 1
**Supporters at Migration:** 1

**Comment by spottedmahn** [comment]
>I ***ume it is only accessible to MSFT employees?

😂 I guess the bot thought I was cursing 😜

**Comment by Powerhelmsman** [comment]
The original ticket is closed. So closed it here.
