### ISSUE TITLE
[information] facebook app buttons not working

### ISSUE THREAD

**Issue by jon80** [MicrosoftDocs/feedback#1001]
After I re-installed Visual Studio 2017 [Microsoft.com], not all options within online app [www.facebook.com] are available, the browser [Microsoft Edge] traced this to a javascript file.
Microsoft Windows 10
Microsoft Edge

![scr](https://user-images.githubusercontent.com/719110/50563922-32456000-0d21-11e9-8b74-2d7fe0327c2d.png)

**Comment by jon80** [comment]
![scr01](https://user-images.githubusercontent.com/719110/50564616-9585c100-0d26-11e9-8691-644673ec8b5b.png)
![scr02](https://user-images.githubusercontent.com/719110/50564618-97e81b00-0d26-11e9-929a-cab91ca95e92.png)

**Comment by jon80** [comment]
it looks like a white screen that solved 99% of my privacy issues.

**Comment by nschonni** [comment]
https://developercommunity.visualstudio.com is probably a better place to post this since it's not aimed at a documentation issue
