### ISSUE TITLE
10 Immutable Laws of Security Administration

### ISSUE THREAD

**Issue by usernameisalreadyta** [MicrosoftDocs/feedback#1004]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**. - No comment section in https://docs.microsoft.com/en-us/previous-versions//cc722488(v=technet.10)

**http://www.microsoft.com/technet/security/chklist/default.mspx:**
Not working.

**Problem:**
Broken link

**Comment by Powerhelmsman** [comment]
@usernameisalreadyta Unfortunately, this content is no longer to update due to out of product cycle. I have to close it.
