### ISSUE TITLE
LinkedIn API does not return a person who created the Ad Account

### ISSUE THREAD

**Issue by felicio** [MicrosoftDocs/feedback#1005]
**Describe the bug**
LinkedIn API does not return a person who created the Ad Account.

**To Reproduce**
Sample request:
```text
GET /v2/adAccountsV2?q=search&amp; start=0&amp; count=100 HTTP/1.1
Host: api.linkedin.com
```

Sample response:
```text
{
    "elements": [
        {
            ...
            "changeAuditStamps": {
                "created": {
                    "time": 1536928220000
                },
                "lastModified": {
                    "time": 1536928220191
                }
            },
            ...
        }
    ],
    "paging": {
        "total": 1,
        "count": 100,
        "start": 0,
        "links": []
    }
}
```
**Expected behavior**
As per [sample response](https://docs.microsoft.com/en-us/linkedin/marketing/integrations/ads/account-structure/create-and-manage-accounts#sample-response) (see below), `actor` field should be set to an URN of a person who created the account.

Sample response:
```text
{
    "elements": [
        {
            "changeAuditStamps": {
                "created": {
                    "actor": "urn:li:person:T1xE4HItnJ", 
                    "time": 1479402003000
                }, 
                "lastModified": {
                    "actor": "urn:li:unknown:0", 
                    "time": 1479402004534
                }
            }, 
            ...
    ], 
    "paging": {
        "count": 2147483647, 
        "links": [], 
        "start": 0, 
        "total": 56
    }
}
```

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Powerhelmsman** [comment]
@abarron-linkedin Can you take a look at this issue?

**Comment by abarron-linkedin** [comment]
@felicio Since this is a functionality question rather than docs feedback, can you please submit your request through Zendesk?

**Comment by felicio** [comment]
@abarron-linkedin please, could you provide a link to it?

**Comment by felicio** [comment]
Issue on Zendesk: 
https://linkedin.zendesk.com/hc/en-us/requests/9794
