### ISSUE TITLE
Fail to upload a File using a Shared Access Signature on a Share

### ISSUE THREAD

**Issue by gavinfish** [MicrosoftDocs/feedback#1006]
**Describe the bug**
As described at https://docs.microsoft.com/en-us/rest/api/storageservices/service-sas-examples#example-upload-a-file-using-a-shared-access-signature-on-a-share . I want to use Shared Access Signature to upload a file to Azure share file. But when I send a http request as the article describes. It returns error like:

```
<?xml version="1.0" encoding="utf-8"?>
<Error>
    <Code>InvalidHeaderValue</Code>
    <Message>The value for one of the HTTP headers is not in the correct format.
RequestId:6e8d093b-c01a-00e0-2e32-a32ec7000000
Time:2019-01-03T07:05:10.6116953Z</Message>
    <HeaderName>Content-Length</HeaderName>
    <HeaderValue>12</HeaderValue>
</Error>
```

**To Reproduce**
1. Use sdk to generate a SAS
2. Use http tool like postman to post a PUT http method

**Expected behavior**
File uploaded successfully.

**Comment by Powerhelmsman** [comment]
@dendeli-msft Can you take a look at this question?

**Comment by robinsh** [comment]
@dendeli-msft Just FYI, I haven't worked on Storage in over a year, but @tamram can help.

**Comment by robinsh** [comment]
#reassign @tamram

**Comment by robinsh** [comment]
#please-close
