### ISSUE TITLE
Geofencing example download

### ISSUE THREAD

**Issue by gregarican** [MicrosoftDocs/feedback#1013]
This page --> https://developer.xamarin.com/samples/monodroid/google-services/Location/Geofencing/ contains incorrect information. It specifies the Android target as being 5.0. When in actuality the Xamarin packages are all targeted against Android 8.0 and 8.1. It would be good to update the documentation on this particular download page to reflect the correct version. Especially since compiling Android apps is particular about versioning.

**Comment by Powerhelmsman** [comment]
@gregarican Can you post your feedback in https://forums.xamarin.com/? This document is not host in Docs site.
