### ISSUE TITLE
Cannot Login to Microsoft Learn

### ISSUE THREAD

**Issue by sesoccer911** [MicrosoftDocs/feedback#1014]
I recently changed my Microsoft email a few weeks ago and ever sense then I have been unable to progress in Microsoft Learn courses. Any time I try and start a new course it asks me to either login or continue without saving. I am unsure on how to progress.

Every time that I click on the log on link it takes me to the following page. https://techprofile.microsoft.com/en-US/Error?replyUrl=https://docs.microsoft.com/en-us/learn/browse/&

Profile - https://techprofile.microsoft.com/en-us/sesoccer911

![image](https://user-images.githubusercontent.com/14225480/50711641-b8b0b900-1023-11e9-821a-5a9fb92466f2.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - Browser Chrome
 - Version 71.0.3578.98 (Official Build) (64-bit)

**Comment by Powerhelmsman** [comment]
@saldana Can you take a look at this issue?

**Comment by sesoccer911** [comment]
I have tried to login using another computer, as well as using the browsers Firefox and Edge, I get the same error screen as before. Incognito mode also does not work. 

Any update on a possible solution other than changing my email back?

**Comment by sesoccer911** [comment]
Hello @Powerhelmsman and @saldana, is there any update to this issue?

**Comment by Gamecock** [comment]
I am seeing the similar issue: 
https://techprofile.microsoft.com/en-us/mikefinch87

When I click on signin it takes me to register:
https://techprofile.microsoft.com/en-US/register?replyUrl=https://techprofile.microsoft.com/en-us/mikefinch87&
I can make this a separate issue if you want.

Desktop (please complete the following information):

OS: MacOs 10.12.6
Browser Chrome
Version 71.0.3578.98 (Official Build) (64-bit)

**Comment by sesoccer911** [comment]
> @saldana Can you take a look at this issue?

I hate to be a bother but it has been 20+ days. Is there a more appropriate place that I should be looking for assistance with my issue?

**Comment by saldana** [comment]
Sorry @sesoccer911, it seems that GH notifications were mutes. 

@Sampy can you help troubleshooting this issue? It seems that @sesoccer911 has tried everything.

**Comment by Sampy** [comment]
This is an issue we are aware of (users changing the email used to sign in to their MSA not being able to sign in) and the good news is we have a fix in the works that we are hoping to roll out this week or next.

**Comment by Sampy** [comment]
We have deployed a change that should fix this issue. It may take some time to roll out to you so try it again and let me know if you are still hitting the problem. If so, there may be another cause we need to look into.

**Comment by sesoccer911** [comment]
Thank you for the update, I can report that the issue has been resolved! 
Thanks!

**Comment by mariarev** [comment]
Hi!I am facing a similar connection problem today: in fact, I've changed my password for safety reasons a few hours ago but it's impossible to connect to my Microsoft learn profile. When selecting the "sign in" button on the screen the Microsoft page stays in the same position and do not give me the chance to write down any password etc. It seems that "sign in" is deactivated...Could you please have a look? I don t want to loose my level information and score as well. Thank you so much!

**Comment by mariarev** [comment]
Hi!I am facing a similar connection problem today: in fact, I've changed my password for safety reasons a few hours ago but it's impossible to connect to my Microsoft learn profile. When selecting the "sign in" button on the screen the Microsoft page stays in the same position and do not give me the chance to write down any password etc. It seems that "sign in" is deactivated...Could you please have a look? I don t want to loose my level information and score as well. Thank you so much!

**Comment by saldana** [comment]
@sampy and @jialge can you look at this issue?

**Comment by Sampy** [comment]
Can you share what page you are on when you try to sign in? Please try this in an InPrivate/Incognito mode browser as well which will help isolate the issue.

We are going to be deploying some changes to the way we sign users in over the next few weeks that will be transparent to you but may resolve this issue as well.

**Comment by mariarev** [comment]
My browser is on  [https://docs.microsoft.com/en-us/learn/] page but on any other page I have tried to connect to Microsoft learn it was impossible, too. 
  Thank you! I've just tried the private mode but nothing happened. Still "sign in" choice seems to be totally deactivated...Neither may I achieve a new score since not being able to connect...
