### ISSUE TITLE
I am unable to sign in to Microsoft Learn

### ISSUE THREAD

**Issue by hking19** [MicrosoftDocs/feedback#1015]
**Describe the bug**

**To Reproduce**
1. Go to https://docs.microsoft.com/en-us/learn/paths/azure-fundamentals/
2. In the upper right corner, click on 'Sign In'
3. Presented with the 'Create profile to save progress page'

**Expected behavior**
Expect to be able to enter the Profile I created earlier this week. But the only option I have when I click Sign In is to create a profile, I do not see any way to sign in with an existing profile.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Edge

**Comment by Powerhelmsman** [comment]
@saldana Can you take a look at this issue?

**Comment by monianop** [comment]
I have exactly the same problem.

**Comment by saldana** [comment]
@hking19 this is a known issue when the user might have multiple Microsoft accounts and have used one to sign in MS Learn. There are two possible solutions until we get this fixed:

1. Sign off from your other account first in the other Microsoft Properties that might have, such as Bing/Cortana.
2. Use an InPrivate/Incognito window for MS Learn.

We know this is an inconvenience and not the ideal user experience. This is in our list to fix in Tech Profile.

**Comment by saldana** [comment]
@hking19 and @monianop I am closing this issue as we think this is solved now. Please reactive if you still are experiencing issues. Thank you!
