### ISSUE TITLE
Cleaner overall experience

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#102]
Cleaner experience is a nice way of saying it.  More to point your experience is a convoluted mess with lazy documentation and less than scrupulous deployment.  If I search for information on an update that is taking hours to install I don’t want thousands of whiny opinions and user suggestions from non-Microsoft staff showing off their technical genius or lack thereof. Furthermore, how do you launch a platform to the home and small business market that even allows such a technical background to spend an hour sifting through the fluff. I’m tired of this problem and luckily the budget is there for new systems. What I know about MS windows stems from countless problems and updates not relevant to my set-up much less version.  I have had a Mac in the office for about a year now. I know nothing about macs or apples simply due to the fact that it works. If there is an update it updates, it utilizes the speed of the internet and installs peacefully. Again it just works. I spend no time being frustrated with it and get to focus on my business but the windows system is an expense I do not need nor do I need to spend 50k to have someone else worry about it. If I buy PC’s again it’ll be for a 5-year old so I can just pitch it and start over. You have lost me and I’m convinced your success is tied to how cheap PCs are vs Mac. What I have learned is the time value of money and the need to cut any infringement on that ratio that leans more on time and takes away from money.  Get rid of user supported help groups, or edit it but get back to a ms only supported system. My suggestion to take over the boards to keep costs down and hire an average joe to read anything you post so it’s crystal clear without asking me for my input.  Does it not click that all these users explaining your problems is a failure on your part. Again I know more than I should about windows and nothing about Mac. The latter is the result of a successful well implemented deployment. 

----------
⚠ Idea migrated from UserVoice

**Created By:** Rick
**Created On:** 2017/10/20 15:48:37 +0000
**Votes at Migration:** 2
**Supporters at Migration:** 2

**Comment by dend** [comment]
We've done a number of design changes that make the experience cleaner and easier to read.
