### ISSUE TITLE
Microsoft Learn: centralize all Microsoft Learning

### ISSUE THREAD

**Issue by MVDB1984** [MicrosoftDocs/feedback#1020]
I saw MVA will be decommissioned, and microsoft learn will be introduced.
It would be nice if all gets centralized.

Now I'm following microsoft courses, video's and documentation on several platforms.
This means progress and accomplishments are spread all over the different platforms.

Microsoft Learn is great, certainly the first looks of it.

Wouldn't it be a nice a idea to have all your progress there?
I mean, all certificates off completion and training courses?
- MVA
- Microsoft Partner University
- Pluralsight
- LinkedIN
- ....

**Comment by Powerhelmsman** [comment]
@saldana Can you take a look at this feedback?

**Comment by hcpcrose** [comment]
The situation recently got worse.  Microsoft recently created academy.microsoft.com, and they're deprecating MVA - Microsoft Virtual Academy?  (mva.microsoft.com)?  Apparently if you don't fully complete a course in MVA by Jan 31, your progress will be lost?  

Also, there doesn't appear to be any way to link to the progress you already have in Microsoft Learn.  I have done several course there, and there are similar course in academy.microsoft.com that I now need to do all over again?  This is not good.  

"To simplify your tech training journey, we are consolidating our learning resources and retiring Microsoft Virtual Academy in phases, beginning on January 31, 2019. Complete site retirement is scheduled for later in 2019. Check your MVA Dashboard frequently for courses you have started that are retiring. To earn your certificates of completion, be sure to finish any courses by January 31, 2019. For more learning options, check out Microsoft Learn."

**Comment by johnnystruck** [comment]
@hcpcrose In response to your "linking completed courses" : On MVA you are able to download your transcript. Select the Dashboard at the top right of the MVA home page > Scroll down and select the "accomplishments" tab > From here you are able to download the entire transcript or PDFs of each course completion one by one. I am hoping Microsoft will migrate courses and completions from MVA and Customer Source but only some will be made availble.

**Comment by emiliano84** [comment]
I totally agree,

I just created a similar issue:

There are too many Microsoft video/learning platforms, and instead reduce the number they keep increasing, can you figure it out a way to move everything under one unique platform as you did for docs?

https://developer.microsoft.com/en-us/collective/learning/courses
https://www.linkedin.com/learning/me
https://mva.microsoft.com/
https://channel9.msdn.com/
https://docs.microsoft.com/en-us/learn/

thanks
regards

https://github.com/MicrosoftDocs/feedback/issues/1463
