### ISSUE TITLE
Change "supplant" to "supplement" in "Getting Started with Kusto"

### ISSUE THREAD

**Issue by replogle** [MicrosoftDocs/feedback#1025]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.
(no comment section; no edit button in article)

**Link to article:**
Tell us where exactly a problem occurs.
https://docs.microsoft.com/en-us/azure/kusto/concepts/index
Last sentence of third paragraph.
Text is: "Therefore, it supplants, rather than replaces, traditional RDBMS systems..."

**Problem:**
What's wrong with the article?
The term used is wrong. "Supplant" and "replace" are synonyms. I'm guessing, based on context, that instead of "supplant" the author intended to use the word "supplement", so instead it should read: "Therefore, it supplements, rather than replaces, traditional RDBMS systems..."

**Comment by rootsmusic** [comment]
Fixed.
#please-close
