### ISSUE TITLE
MSBuild Transforms - Transform Modifiers - Example - Description

### ISSUE THREAD

**Issue by jjELT** [MicrosoftDocs/feedback#1028]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.
There is no comment section!?

**Link to article:**
https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/vs-2015/msbuild/msbuild-transforms.md

**Problem:**
The line
`c:\sub0\sub1\sub2\sub3`
should be changed to
`c:\xmake\sub1\sub2\sub3`

**Comment by rootsmusic** [comment]
@jjELT Your link is not found.

**Comment by jjELT** [comment]
I guess this is outdated and can be closed.
