### ISSUE TITLE
Add documentation for TSHELL

### ISSUE THREAD

**Issue by glibnub** [MicrosoftDocs/feedback#103]
Some pages reference TSHELL but I haven't been able to find any documentation about which commands are available on a windows phone when connected to it over USB with TSHELL. For example, this page says "Step 2: Install and configure TShell
TShell is required to run Tracelog." which are very underwhelming instructions.

https://docs.microsoft.com/en-us/windows-hardware/test/mobile-tracing/capture-event-trace-logs-on-windows-phone#step-2-install-and-configure-tshell

----------
⚠ Idea migrated from UserVoice

**Created By:** Rob Meyer
**Created On:** 2017/10/19 23:38:20 +0000
**Votes at Migration:** 3
**Supporters at Migration:** 3

**Comment by dend** [comment]
@EliotSeattle can you help address the issue with this piece of content?

**Comment by EliotSeattle** [comment]
Thanks for finding this, @botcrane 

Added this statement:
TShell is required to run Tracelog. TShell is a part of the Windows Assessment and Deployment Kit (ADK). Instructions for installation are in [Prepare for Windows mobile development](https://docs.microsoft.com/en-us/windows-hardware/manufacture/mobile/preparing-for-windows-mobile-development).

**Comment by EliotSeattle** [comment]
Returning to you, @dend , since I don't think I can close this.

Heheh, I can't assign this either....
PR with the fix = https://github.com/MicrosoftDocs/commercialization-public/pull/131
