### ISSUE TITLE
let me choose a language and maintain it

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#104]
_No details provided._

----------
⚠ Idea migrated from UserVoice

**Created By:** Anonymous
**Created On:** 2017/10/19 12:57:18 +0000
**Votes at Migration:** 2
**Supporters at Migration:** 2

**Comment by dend** [comment]
This functionality is already available - you can just scroll to the bottom of the page and select the language you want to see the documentation in.
