### ISSUE TITLE
Invalid link to C++ tutorial from main page

### ISSUE THREAD

**Issue by gclarkii** [MicrosoftDocs/feedback#1041]
**Describe the bug**
The link to the C++ tutorial comes up 404 if selected from the navigation links.  If selected from the primary page it works.
**To Reproduce**
1. Go to 'https://docs.microsoft.com/en-us/visualstudio/ide/?view=vs-2017'
2. Click on 'C++ tutorial on left side navigation pane.'
It will take you to https://docs.microsoft.com/en-us/cpp/get-started/tutorials/?view=vs-2017
which is 404.

**Expected behavior**
Clicking on the tutorial link should take you to https://docs.microsoft.com/en-us/cpp/get-started/?view=vs-2017 which is where the main page link takes you.

Firefox but Chrome and IE also fail...

**Comment by mairaw** [comment]
I think this has been fixed. Can you confirm @gclarkii?

**Comment by superfon** [comment]
https<https://1drv.ms/u/s!Arn4JlaSt0MdgUc-BMWIoEz57rEm>://1drv.ms/u/s!Arn4JlaSt0MdgUc-BMWIoEz57rEm<https://1drv.ms/u/s!Arn4JlaSt0MdgUc-BMWIoEz57rEm>


Wysłane z aplikacji Outlook Mobile

Wysłane z aplikacji Outlook Mobile<https://aka.ms/blhgte>


________________________________
Od: GB Clark II <notifications@github.com>
Wysłano: czwartek, 14 maja 2020, 3:39 AM
Do: MicrosoftDocs/feedback
DW: Subscribed
Temat: Re: [MicrosoftDocs/feedback] Invalid link to C++ tutorial from main page (#1041)


Closed #1041<https://github.com/MicrosoftDocs/feedback/issues/1041>.
