### ISSUE TITLE
Browse Learning??

### ISSUE THREAD

**Issue by ajulyguy** [MicrosoftDocs/feedback#1045]
Hello???  Why direct people to Browse Learning with there is **NOTHING** there for powerapps - absolutely brilliant!

![image](https://user-images.githubusercontent.com/38598049/51134269-ecda6580-17eb-11e9-89f6-dffe6b8375d7.png)

[https://docs.microsoft.com/en-us/learn/browse/?products=bizapps-power-apps&resource_type=learning%2520path](url)

**Comment by sudeepku** [comment]
@ajulyguy - thanks for your feedback. Could you please try again? There are two modules on powerapps which you should be able to see.
