### ISSUE TITLE
LinkID 834629 is pointing to wrong URL

### ISSUE THREAD

**Issue by MarcLaf** [MicrosoftDocs/feedback#1057]
**Describe the bug**
The link ID 834629 (https://go.microsoft.com/fwLink/?LinkID=834629) is wrong. The current URL it points to is https://docs.microsoft.com/en-us/azure/active-directory/saas-apps/atlassiancloud-tutorial but the proper one is https://docs.microsoft.com/en-us/azure/active-directory/saas-apps/atlassian-cloud-tutorial

**To Reproduce**
1. Go to https://go.microsoft.com/fwLink/?LinkID=834629
2. The expanded URL is https://docs.microsoft.com/en-us/azure/active-directory/saas-apps/atlassiancloud-tutorial

**Expected behavior**
The expanded URL should be https://docs.microsoft.com/en-us/azure/active-directory/saas-apps/atlassian-cloud-tutorial

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 64.0.2

**Comment by dendeli-msft** [comment]
@MarcLaf can you please let us know in what article was this link referenced?

**Comment by MarcLaf** [comment]
I honestly don't remember. I feel like it was from adding an Azure Enterprise Application and a more info link. I wasn't aware that was required because it's not the link text that's wrong it's the expanded URL text that needs fixing.
