### ISSUE TITLE
Error in Microsoft Power Query for Excel Formula Language Specification

### ISSUE THREAD

**Issue by tcrossland** [MicrosoftDocs/feedback#1058]
**Link to article:**
 * https://docs.microsoft.com/en-us/powerquery-m/power-query-m-language-specification
 * https://download.microsoft.com/download/8/1/A/81A62C9B-04D5-4B6D-B162-D28E4D848552/Power%20Query%20Formula%20Language%20Specification%20(October%202016).pdf

**Problem:**
There seems to be a problem with the Microsoft Power Query for Excel Formula Language Specification (downloadable PDF document). According to the specification, there is no way of "reducing" some types of expressions to primitive expressions:

> #### 12.2.3.4 As expression
> as-expression:
> - equality-expression
> - as-expression `as` nullable-primitive-type
> #### 12.2.3.5 Equality expression
> equality-expression:
> - relational-expression
> - relational-expression `=` equality-expression
> - relational-expression `<>` equality-expression
> #### 12.2.3.6 Relational expression
> relational-expression:
> - additive-expression
> - additive-expression `<` relational-expression
> - additive-expression `>` relational-expression
> - additive-expression `<=` relational-expression
> - additive-expression `>=` relational-expression
> #### 12.2.3.7 Arithmetic expressions
> additive-expression:
> - multiplicative-expression
> - multiplicative-expression `+` additive-expression
> - multiplicative-expression `–` additive-expression
> - multiplicative-expression `&` additive-expression
>
> multiplicative-expression:
> - metadata-expression
> - metadata-expression `*` multiplicative-expression
> - metadata-expression `/` multiplicative-expression
> #### 12.2.3.8 Metadata expression
> metadata-expression:
> - as-expression
> - as-expression `meta` unary-expression

These grammar rules are mutually left recursive and non-terminal. Also, there is no way, for example, for the expression `2 + 2` to be interpreted as a valid additive-expression.

**Comment by Minewiskan** [comment]
@tcrossland - Thanks Tom, for pointing this out. The spec has been updated. You can get the new version here. https://docs.microsoft.com/en-us/powerquery-m/power-query-m-language-specification

#please-close

**Comment by tcrossland** [comment]
@Minewiskan great, many thanks for updating the spec!
