### ISSUE TITLE
Sidebar with Table Of Contents covers entire site at width 767px

### ISSUE THREAD

**Issue by SpareNichols** [MicrosoftDocs/feedback#1059]
**Describe the bug**
There is an edge case issue around the breakpoint at 768px width. At 766px and 768px, the site appears to be usable. At 767px width, the sidebar stretches across the whole page with no way to dismiss or see the content underneath it.

**To Reproduce**
1. Navigate to any article where the Table Of Contents sidebar is present. E.g. https://docs.microsoft.com/en-us/azure/devops/boards/get-started/what-is-azure-boards-basic-process?view=vsts
2. Resize window to 767px width. (Using Chrome Developer Tools, click the Toggle device toolbar button, or press Ctrl + Shift + M, and enter 767 for the width.)
3. Compare with widths 766px and 768px.

**Expected behavior**
The sidebar seems it should not be visible until the window has been sized to 768px. But regardless of the technical decision, the site should be viewable at 767px.

**Screenshots**
766px:
![image](https://user-images.githubusercontent.com/30443893/51352744-23c2ac80-1a74-11e9-9af3-b952af8f3e0a.png)

767px:
![image](https://user-images.githubusercontent.com/30443893/51352723-173e5400-1a74-11e9-85ef-f90587e7e1b1.png)

768px:
![image](https://user-images.githubusercontent.com/30443893/51352708-0f7eaf80-1a74-11e9-9575-6d6bc2c0e61e.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 71.0.3578.98

**Additional context**
This is incidentally the width that my browser becomes when I use the Windows "Snap To" feature to make it take up half of my screen (which I ESPECIALLY use with documentation... 😑). I am running at 1920x1080 with 125% scaling being used. (1920 / 1.25 = 768... And I suppose less 1px for the window border?)

**Comment by shirgoldbird** [comment]
@SpareNichols Thanks for reporting this bug, and sorry you ran into it! I've passed this along to our frontend team to investigate.

**Comment by shirgoldbird** [comment]
@SpareNichols This bug should be fixed—please confirm and close this issue out if everything looks good.

**Comment by shirgoldbird** [comment]
@SpareNichols Closing this out. Feel free to reopen if it's not fixed for you.
