### ISSUE TITLE
Make main content column more wide, improve layout of tables.

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#106]
Please, improve the layout for tables.
I'm unable to read content on my notebook. (1920px wide high dpi)
Table on this link is cropped on msbuild properties table:
https://docs.microsoft.com/en-us/visualstudio/msbuild/common-msbuild-project-properties

I'm unable to attach screenshot on this site so I've uploaded it to s3 - https://s3-eu-west-1.amazonaws.com/pic0000/2017/10/zPGGPGc/2017-10-12_23-12-53.png

----------
⚠ Idea migrated from UserVoice

**Created By:** Alexander
**Created On:** 2017/10/12 20:15:17 +0000
**Votes at Migration:** 2
**Supporters at Migration:** 2

**Comment by dend** [comment]
This is now supported, and we have tables that scroll.
