### ISSUE TITLE
There is a sentence translated into the opposite meaning in 中文 (台灣).

### ISSUE THREAD

**Issue by EmmettTsai** [MicrosoftDocs/feedback#1063]
**Link to article:**
https://docs.microsoft.com/zh-TW/windows/uwp/get-started/universal-application-platform-guide

**Problem:**
What's wrong with the article?

There is a sentence translated into the opposite meaning.

Original sentence in English:
Able to use a common API on all devices that run Windows 10.

Wrong translation in (中文 (台灣))
無法在所有執行 Windows 10 的裝置上使用一般的 API。
(written in English: It is not possible to use the generic API on all devices running Windows 10.)

The correct sentence should be in (中文 (台灣)):
在所有能夠執行 Windows 10 的裝置上可以使用通用的API。

**Comment by nokura** [comment]
Hello @EmmettTsai 
Thank you for bringing this to our attention. I am sorry but we most likely need to wait till Mid/March to implement the fix you pointed out as we are in the middle of internal transition of the localization ownership. I will file this issue in the internal tracking system to make sure to be fixed.
Kind regards,
Microsoft DOCS International Team

**Comment by nokura** [comment]
Hello @EmmettTsai
The fix has been published. I am closing this instance.
Thank you again for your feedback.
Kind regards,
Microsoft DOCS International Team

**Comment by EmmettTsai** [comment]
Thanks to Microsoft DOCS International Team.
