### ISSUE TITLE
Certificate Enrollment API docs channel?

### ISSUE THREAD

**Issue by Crypt32** [MicrosoftDocs/feedback#1064]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

**Link to article:**
https://docs.microsoft.com/en-us/windows/desktop/seccertenroll/about-asn-1-type-system

**Problem:**
The article is not formatted and ugly to read.

I would basically find the appropriate channel for certificate enrollment API, because there are a lot of poorly formatted articles and there is no feedback/comment button at the bottom of the article.

**Comment by Crypt32** [comment]
Adding this article as well: 
https://docs.microsoft.com/en-us/windows/desktop/seccertenroll/about-introduction-to-asn-1-syntax-and-encoding

**Comment by ginami** [comment]
Hi @Crypt32 -- thank you for bringing this to our attention! We'll work on improving these docs.

**Comment by Crypt32** [comment]
Another one: https://docs.microsoft.com/en-us/windows/desktop/api/certcli/nf-certcli-icertrequest2-getcapropertydisplayname

The HTML is not properly escaped and part of content is in bold because closing `<b>` tag is escaped as literal, not HTML tag.

**Comment by Crypt32** [comment]
Another one: https://docs.microsoft.com/en-us/windows/win32/api/certcli/nf-certcli-icertconfig-getconfig


The HTML is not properly escaped and part of content is in bold because closing `<b>` tag is escaped as literal, not HTML tag.

**Comment by Crypt32** [comment]
So far so good. Thanks!
