### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by krisrajz** [MicrosoftDocs/feedback#1066]
Both Azure Vidyapeeth and Microsoft's learning has plenty of broken links, wondering someone really cares?! Ex: There is no Azure Vidyapeeth android app but still the portal has link. I request Microsoft to devote sometime to make learning more excited and wonderful.

**Comment by dendeli-msft** [comment]
@krisrajz can you please include links to articles where links are broken?

**Comment by krisrajz** [comment]
https://play.google.com/store/apps/details?id=com.msazurevidyapeeth.msazurevidyapeeth&hl=en

**Comment by sandusun** [comment]
This issue exists now also, please resolve it at the earliest.
Without having an Android App, it is difficult to view the webinar sessions. Hope it will be taken care soon.

**Comment by docs-product** [comment]
Thank you for the feedback! Because this issue is not related to docs.microsoft.com, we cannot address it in this forum.
