### ISSUE TITLE
Return to main site message always shown

### ISSUE THREAD

**Issue by ks74** [MicrosoftDocs/feedback#1067]
Whenever I open a page for JScript documentation, I see the same message over and over again:

>>We're no longer updating this content regularly. Check the Microsoft Product Lifecycle for information about how this product, service, technology, or API is supported.

I do need the manual and I don't want to see the message every time. Once I closed it I want it to never show again. 

Also, the bottom bar (English (United States)) is too high.

**Comment by dendeli-msft** [comment]
Thank you for the feedback - this notification is to make sure that users are aware of the fact that the content is no longer supported, and any practices or code they might take from it might not be the best.
