### ISSUE TITLE
Hyperlink invalid

### ISSUE THREAD

**Issue by waynenus** [MicrosoftDocs/feedback#1070]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

**Link to article:**
Tell us where exactly a problem occurs.
https://docs.microsoft.com/zh-cn/azure/backup/backup-azure-troubleshoot-vm-backup-fails-snapshot-timeout#usererrorstandardssdnotsupported---currently-azure-backup-does-not-support-standard-ssd-disks
**Problem:**
What's wrong with the article?
3 hyperlinks are invalid as below:
![image](https://user-images.githubusercontent.com/35486805/51515598-4592a980-1e4f-11e9-93ea-1929bac124c3.png)

**Comment by mairaw** [comment]
I think there's a new version of the content since then and your issue seems to be resolved:
![image](https://user-images.githubusercontent.com/12971179/51871411-255d6180-230b-11e9-8fb4-2c589a166392.png)

**Comment by dendeli-msft** [comment]
Confirming that this should be resolved.
