### ISSUE TITLE
SQL USAGE API SCRIPT NOT WORKING 

### ISSUE THREAD

**Issue by Siby22071989** [MicrosoftDocs/feedback#1076]
The link: https://docs.microsoft.com/en-us/rest/api/sql/subscriptionusages/listbylocation does not seems to be working when I try to pull up usage of SQL resources. I enter Sub ID and region and click on "RUN" and I get an error as Subscription - Not found ( 404 )

**Comment by dendeli-msft** [comment]
@Siby22071989 can you confirm that the issue is still present? Are you selecting the subscription from the prompted dropdown?

**Comment by Siby22071989** [comment]
This is resolved
