### ISSUE TITLE
Focus mode appears blank in MS Azure Rest API

### ISSUE THREAD

**Issue by AmichaiH** [MicrosoftDocs/feedback#1078]
**Describe the bug**
In Azure rest api reference - for example - [https://docs.microsoft.com/en-us/rest/api/firewall/azurefirewalls/listall] - when pressing on Try-it - I get an empty screen - this worked two days ago
**To Reproduce**
see description
**Expected behavior**
The focus mode should be active and functional

**Screenshots**
![focus mode problem](https://user-images.githubusercontent.com/17567349/51607856-89a0af80-1f1e-11e9-8950-ab2a1c1ad861.PNG)

**Desktop (please complete the following information):**
 - OS: windows
 - Browser checked both on chrome and edge
 - Version 10

**Comment by dendeli-msft** [comment]
This has been addressed, thank you for your feedback!
