### ISSUE TITLE
EM_SETSEL description

### ISSUE THREAD

**Issue by aleaksah** [MicrosoftDocs/feedback#1079]
**Link to article:**
https://docs.microsoft.com/en-us/windows/desktop/Controls/em-setsel

**Problem:**
Error in the description.
Existing text:

> If the start is 0 and the end is 1, all the text in the edit control is selected. If the start is 1, any current selection is deselected.

Should be:

> If the start is 0 and the end is -1, all the text in the edit control is selected. If the start is -1, any current selection is deselected.

**Comment by KalleOlaviNiemitalo** [comment]
This seems a duplicate of #853

**Comment by aleaksah** [comment]
Yes, duplicate. But still unfixed.

**Comment by dendeli-msft** [comment]
Duplicate of #853
