### ISSUE TITLE
Language filter

### ISSUE THREAD

**Issue by 486DX50** [MicrosoftDocs/feedback#1081]
**Is your feature request related to a problem? Please describe.**
Every time I search for something like "azure-docs", it gives me hundreds of results in different language. For example: "azure-docs.zh-cn, azure-docs.zh-tw, azure-docs.es-es, azure-docs.ru-ru, etc"

**Describe the solution you'd like**
I'd like to be able to choose the country and see only results for that code-page, i.e. "China, Japan, South Korea, Russia, Germany, United States, United Kingdom, Australia, etc"

**Describe alternatives you've considered**
Any filter that would filter out other spoken languages would work

**Comment by dendeli-msft** [comment]
@486DX50 can you please let us know where you are searching for `azure-docs`?

**Comment by 486DX50** [comment]
https://github.com/search?q=org%3AMicrosoftDocs+azure-docs

**Comment by docs-product** [comment]
Thank you for the feedback! Because this issue is not related to docs.microsoft.com, we cannot address it in this forum.
