### ISSUE TITLE
navigation content disappeared at document for ASP.NET Core in some asia countries

### ISSUE THREAD

**Issue by occurrent** [MicrosoftDocs/feedback#1085]
**Describe the bug**
it work perfect before 19-01-25,and this issue look like only happened at few asia countries such as zh-cn , zh-tw , zh-hk, ja-jp, ko-kr. and it only happened in ASP.NET Core Document.

**To Reproduce**
1. Go to 'https://docs.microsoft.com/zh-cn/aspnet/core/?view=aspnetcore-2.2' or other countries I been listed

**Screenshots**

> ***abnormal***
> 
> <img width="542" alt="zh-cn" src="https://user-images.githubusercontent.com/46512733/51781249-2185df80-2151-11e9-9eaa-40891759c3d9.png">

> ***normal***
> 
> same language and different page:
> 
> <img width="496" alt="zh-cn" src="https://user-images.githubusercontent.com/46512733/51781331-4169d300-2152-11e9-93f2-e092028f8bd9.png">
> 
> same page and different language:
> 
> <img width="494" alt="asp net core" src="https://user-images.githubusercontent.com/46512733/51782395-59e1e980-2162-11e9-9e9a-c8490199fc5a.png">

**Comment by JasonCard** [comment]
Hi @occurrent,

This issue is now fixed for all languages.
Thank you again for your feedback.

Kind regards,
Microsoft DOCS International Team
