### ISSUE TITLE
Tell readers that the Content Feedback form opens a public GH issue

### ISSUE THREAD

**Issue by guardrex** [MicrosoftDocs/feedback#1092]
Original GitHub issue [aspnet/Docs \#10355](https://github.com/aspnet/Docs/issues/10355#issuecomment-458401320) from @malachib

> I specifically didn't use it [the **Content feedback** button] because I assumed it was a one-way classic "hidden" feedback. Didn't realize it (seems to) produce a discussion.

The text above and below the form is ...

> We'd love to hear your thoughts. Choose the type you'd like to provide:

> Our feedback system is built on GitHub Issues. Read more on our blog.

I recommend adding text to indicate that the form opens an issue on the public GitHub docs repo.

> Our feedback system is built on GitHub Issues. When you submit the feedback form, an issue is opened on our public GitHub documentation repo. Read more on our blog.

**Comment by shirgoldbird** [comment]
Thank you for the feedback! We considered this wording update but are concerned that it adds too much text and mental load to users in an already confusing part of the site. Although it's easy to think that explaining more about what the system does will cut down on user confusion, tests have shown this not to be the case. Longer explainer text doesn't necessarily lead to a better user experience and often causes worse clickthrough rates as users gloss over everything in that section.

We'll continue evaluating the messaging around our feedback system as it evolves, but this isn't something we'll implement at the moment. Please feel free to open another issue if you have additional feedback.
