### ISSUE TITLE
**Unable to Download SQL Server Management Studio 17 from the Doc**

### ISSUE THREAD

**Issue by vigarnyalvarez** [MicrosoftDocs/feedback#1098]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

**Link to article:**
**https://docs.microsoft.com/en-us/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-2017#ssms-180-preview-6**

**https://download.microsoft.com/download/D/D/4/DD495084-ADA7-4827-ADD3-FC566EC05B90/SSMS-Setup-ENU.exe**

**Problem:**
Unable to download Download SQL Server Management Studio 17.9.1

**Comment by MashaMSFT** [comment]
Hi @vigarnyalvarez , since we haven't heard back from you, we will assume your Issue has been resolved. As such, I will proceed with closing out this Git Issue. However, please feel free to reach out to us if you need anything further. Thanks again for contacting Microsoft! #please-close

**Comment by vigarnyalvarez** [comment]
Hi!

Thanks for contacting back. I determined that it was a firewall issue with
the network that I was connected to at that time. Please, close the ticket.

Regards,
Vigarny A.

**Comment by MashaMSFT** [comment]
Hi @vigarnyalvarez , awesome, I'm thrilled to hear you were able to get SSMS downloaded :) thanks for letting us know, and thanks for reaching out to us!

**Comment by stevestein** [comment]
#please-close

**Comment by stevestein** [comment]
@tysonn - not sure how to get this closed.  Thanks!

**Comment by stevestein** [comment]
#please-close

**Comment by MashaMSFT** [comment]
#please-close

**Comment by VanMSFT** [comment]
#please-close
