### ISSUE TITLE
Azure Portal link for Intune Exchange Connector

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#110]
The URL for Learn how to configure your account and server to connect to the Exchange connector in the Azure Portal (https://portal.azure.com/#blade/Microsoft_Intune_DeviceSettings/ExchangeConnectorMenu/connector/connectorType/) takes you to the instructions for the Cl***ic Portal (https://docs.microsoft.com/en-us/intune-cl***ic/deploy-use/intune-on-premises-exchange-connector). 

This should be updated to the Azure Portal information (https://docs.microsoft.com/en-us/intune/exchange-connector-install) 

----------
⚠ Idea migrated from UserVoice

**Created By:** Vanita
**Created On:** 2017/10/09 01:38:25 +0000
**Votes at Migration:** 1
**Supporters at Migration:** 1

**Comment by dend** [comment]
Closing as this is a product issue and we don't have a channel to contact the user to find out where the issue was.
