### ISSUE TITLE
[error message feedback] provide feedback for InvalidFileLink

### ISSUE THREAD

**Issue by sptramer** [MicrosoftDocs/feedback#1100]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

**Problem:**

This error is incorrect, the file which includes `includes/dns-powershell-setup-include.md` is correctly rendered: https://review.docs.microsoft.com/en-us/azure/dns/private-dns-getstarted-powershell?branch=pr-en-us-64565

This needs to be fixed, or at least ignored so that this PR can proceed.

**Log code info**
(This is auto filled, no need to modify)

| Severity   | Type   | Code   | Category   | File   | Message   |  Source  | Line   | Time   |
|------------|--------|--------|------------|--------|-----------|----------|--------|--------|
| Warning | Unspecified | InvalidFileLink | Markdown | includes/dns-powershell-setup-include.md | Invalid file link:(~/includes/requires-azurerm.md). | BuildCore.Build Document.LinkPhaseHandlerWithIncremental.ConceptualDocumentProcessor.Save |17 | 01/30/2019 17:11:13 |

**Link to report**
(This is auto filled, no need to modify)

[report url](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C1%5C30%5C8257e7f2-de62-9622-af05-1281f54738ea%5CPullRequest%5C201901301705284051-64565%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=3t084F36OaDgq4tx9gVEkvA8ws8Xdm3TrTrxZ%2FOr6JM%3D&st=2019-01-30T17%3A10%3A47Z&se=2019-03-02T17%3A15%3A47Z&sp=r)

**Comment by dendeli-msft** [comment]
@cillroy @herohua can you please take a look at this? Seems like a build issue.

**Comment by cillroy** [comment]
thank you for the feedback, we are constantly working on improving our messaging and document for build reports.  Providing this feedback helps us track messaging that requires improvement.
