### ISSUE TITLE
[Question] Facing problems with cognitive text to speech connection 

### ISSUE THREAD

**Issue by LulwahAlshuqair** [MicrosoftDocs/feedback#1101]
Hi, i'm testing a code i found in GitHub to test the text-to-speech. But i think there's a problem with my connection or something else :( there is no compilation errors but there is no sound output either so something must be wrong. 

This is the repository of the code: https://github.com/Azure-Samples/Cognitive-Speech-TTS 
i am using the Android version.

Any help is very much appreciated. Thank you

**Comment by rootsmusic** [comment]
@LulwahAlshuqair Please ask in support forums.
#please-close
