### ISSUE TITLE
SCCM WMI  - EvaluationState

### ISSUE THREAD

**Issue by hypercube33** [MicrosoftDocs/feedback#1103]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

**Link to article:**
https://docs.microsoft.com/en-us/previous-versions/system-center/developer/jj902881(v=cmsdk.12)

**Problem:**
What's wrong with the article?
The WMI for EvaluationState appears to be correct for everything but appears to be completely different state messages for task sequences. For example, a TS running returns 18 when I note that it runs and fails, but the table shows that this is "waiting for user logoff" which does not seem to apply at all.

**Comment by rootsmusic** [comment]
@hypercube33 "We're no longer updating this content regularly."
#please-close
