### ISSUE TITLE
Bad Download Link for article

### ISSUE THREAD

**Issue by kennethhadley** [MicrosoftDocs/feedback#1105]
Article:
https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/ee431701%28v%3dws.10%29

Problem:
Download link to guide and sample (http://go.microsoft.com/fwlink/?linkid=160558) leads to a "We're sorry, this download is no longer available" page.

**Comment by rootsmusic** [comment]
@kennethhadley "We're no longer updating this content regularly."
#please-close
