### ISSUE TITLE
https://docs.microsoft.com/en-us/learn/ not able to log in

### ISSUE THREAD

**Issue by Sam-digitalife** [MicrosoftDocs/feedback#1114]
Each time I'm going on https://docs.microsoft.com/en-us/learn/ and try to sign in with my usual credentials, I'm redirected to the page to register a profile (https://techprofile.microsoft.com/en-us/register?replyUrl=https://docs.microsoft.com/en-us/learn/&).
I have an existing profile, I tried to sign in with different browser (Edge or Firefox), same issue. Thx for the support

samuel

**Comment by Sean84** [comment]
Im having the same issue

**Comment by Sam-digitalife** [comment]
I solved it by using my browser in "private mode".

**Comment by Sean84** [comment]
Didnt work for me but i was able to register using United states rather than Uk

**Comment by rootsmusic** [comment]
#please-close
