### ISSUE TITLE
Return relevant results

### ISSUE THREAD

**Issue by docs-product** [MicrosoftDocs/feedback#112]
As in, for example, when I have the filter for SQL on, and I search for "VALUES", which is a keyword in SQL, return that as the top result, or at least on the first page. At the moment the page for that keyword doesn't even show up on the first 3 pages of results. This is a very common issue for keywords in SQL. 

----------
⚠ Idea migrated from UserVoice

**Created By:** Anonymous
**Created On:** 2017/09/29 17:15:50 +0000
**Votes at Migration:** 1
**Supporters at Migration:** 1

**Comment by presleyy** [comment]
Lack of the search scope, "VALUES" search might return many irrelevant results. We have a feature of adding scopes of document types filters with facets (in planning phase). This feature will help a lot for this scenario once users have chance to filter for SQL scope and language reference document type in search results.

**Comment by Powerhelmsman** [comment]
#log-suggestion @presleyy

**Comment by botcrane** [comment]
🚀 **ATTENTION**: [Internal request](https://ceapex.visualstudio.com/web/wi.aspx?pcguid=7d644393-99ad-41c8-ac53-7fa79294c720&id=25949) logged.

**Comment by presleyy** [comment]
We have a [feature](https://ceapex.visualstudio.com/Engineering/_workitems/edit/25952) about filter and facets. Once the feature would be implemented, the problem of this issue would be resolved.

**Comment by docs-product** [comment]
Closing this issue as we have introduced multiple affordances to get to the right content quickly, including content type filters and a better underlying search engine.
