### ISSUE TITLE
"Leave feedback directly on GitHub" should open a new tab

### ISSUE THREAD

**Issue by wesinator** [MicrosoftDocs/feedback#1126]
**Describe the bug**
Clicking Leave feedback directly on GitHub link opens over the document page

I would submit a PR to fix this if I could find the code for the feedback control section on GitHub.

**To Reproduce**
1. Go to Feedback section 
2. Click on down arrow next to `Sign in to give documentation feedback`
3. Click `directly on GitHub`

**Expected behavior**
Open in new tab

**Desktop (please complete the following information):**
 - Browser Firefox
 - Version 65

**Comment by rootsmusic** [comment]
@wesinator Where's the doc?

**Comment by wesinator** [comment]
the page seems to have changed. This is no longer relevant issue
