### ISSUE TITLE
subscribe to new guides

### ISSUE THREAD

**Issue by docs-product** [MicrosoftDocs/feedback#113]
I'm actively working on Azure AD B2C right now and there are some great guides and the product team is working on more.  The problem is when they post a new guide, how would I know?  I won't unless I poll the site which is not optimal.

I would like to be alert/email/rss-feed about new guides.  I would also like to be alerted about any significant changes in the documentation.

----------
⚠ Idea migrated from UserVoice

**Created By:** Mike DePouw
**Created On:** 2017/09/29 12:41:33 +0000
**Votes at Migration:** 2
**Supporters at Migration:** 2

**Comment by Powerhelmsman** [comment]
Thanks for your suggestion. I've created a work item internally to track your suggestion.

**Comment by Powerhelmsman** [comment]
#log-suggestion

**Comment by botcrane** [comment]
🚀 **ATTENTION**: [Internal request](https://ceapex.visualstudio.com/web/wi.aspx?pcguid=7d644393-99ad-41c8-ac53-7fa79294c720&id=21136) logged.

**Comment by alvinashcraft** [comment]
Adding RSS is a great idea. As many releases are now announced on Docs, it would be great to be able to subscribe to an RSS feed for one of these pages.
For example, VS for Mac just moved their release announcements to a Release Notes page on docs.
https://docs.microsoft.com/en-us/visualstudio/releasenotes/vs2017-mac-relnotes
I would like to subscribe to this to be notified when a new version of VS for Mac is released so I can review the release notes.

**Comment by cconrado** [comment]
Yes huge help it would be

**Comment by docs-product** [comment]
Duplicate of #96
