### ISSUE TITLE
a typo 

### ISSUE THREAD

**Issue by sophiexu** [MicrosoftDocs/feedback#1137]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

**Link to article:**
https://docs.microsoft.com/en-us/power-bi/guided-learning/visualizations?tutorial-step=16 

**Problem:**
a typo: "You can change how **Powwer** BI summarizes the data...."  right before the second screenshot of the bottom

**Comment by mairaw** [comment]
This article no longer exists. Closing.
