### ISSUE TITLE
Include Reactive Extensions documentation for .Net Core in docs.microsoft.com

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#114]
MSDN have documentation on Reactive Extensions (Rx) as can be seen here: https://msdn.microsoft.com/en-us/library/hh242986(v=vs.103).aspx

Microsoft's new docs.microsoft.com lacks the same API documentation. 

Since https://github.com/Reactive-Extensions/Rx.NET is a .Net Foundation project. much like ASP.Net core and others; It's documentation should be included. Especially as it's namespaced under System.

----------
⚠ Idea migrated from UserVoice

**Created By:** Roman Vaughan
**Created On:** 2017/09/29 04:15:33 +0000
**Votes at Migration:** 4
**Supporters at Migration:** 4

**Comment by dend** [comment]
@bartdesmet @mairaw do we have any plans for this request?

**Comment by Powerhelmsman** [comment]
@mairaw @bartdesmet Is there any update here?

**Comment by mairaw** [comment]
@terrajobst @weshaggard @karelz can you comment on this request? It seems this a community-maintained project nowadays, right? This would be a bit different than ASP.NET Core in that sense. But I'm fine adding that if product team decides we should do this.

Also, I think we'd need to have the new feature for documenting NuGet packages that are cross-platform ready in order to do this properly.

/cc @NZSmartie

**Comment by karelz** [comment]
No idea - @terrajobst @weshaggard hopefully know

**Comment by dend** [comment]
Hi folks - unless this is a Microsoft-owned project, we cannot document it in our system at this time.

cc: @mairaw @terrajobst @karelz

**Comment by Powerhelmsman** [comment]
Sent email to @ghuntley and @onovotny to follow up.

**Comment by dend** [comment]
Given that the project is not a Microsoft-shipped entity, we cannot document it on docs.microsoft.com. I am closing this issue for now, but we can resume this conversation once such capabilities are integrated in our platform.

**Comment by ghuntley** [comment]
This is an absolute mess tbh.

**Comment by mairaw** [comment]
The old msdn documentation has been archived on Docs and is no longer being indexed:
https://docs.microsoft.com/en-us/previous-versions/dotnet/reactive-extensions/

**Comment by ghuntley** [comment]
@mairaw can you please release the archived documentation under an open-source compatible license so that the community can use it as a baseline if they so desire?

**Comment by paulomorgado** [comment]
@dend, since the project moved to https://github.com/dotnet/reactive, isn't that a Microsoft-shipped entity?

**Comment by mairaw** [comment]
@ghuntley I'll double check with a few folks if that's possible.

**Comment by ghuntley** [comment]
Thx. Would you consider complete unpublishing of your copy after opensourcing? Ie community hosts it instead.

**Comment by mairaw** [comment]
That copy is not even going to be indexed anymore and only folks hitting old URLs would find that content.

**Comment by NZSmartie** [comment]
I keep finding the old documentation when searching for it. And because there's a lack of official docs, it's hard to not stumble upon. Which is why I raised this issue in the first place.

**Comment by mairaw** [comment]
That documentation set was just archived. It takes a while for search engines to get caught up.

**Comment by tamirdresher** [comment]
+1

**Comment by denisw** [comment]
The original Reactive Extensions documentation is now open-source! 🎉 

https://github.com/MicrosoftDocs/dotnet-archive

Now it would be possible to update it and host it at another location.

**Comment by Dobby007** [comment]
In the documentation of System.Reactive namespaces there is no description of methods of any class. All links lead to the old MSDN site and when redirected there it is shown that page is not found. Do you have any plans to fix it? It's extremely awkward to have this library available for .NET Core while in the meantime not having any documentation for it at all.

Example: https://docs.microsoft.com/en-us/previous-versions/dotnet/reactive-extensions/hh229462%28v%3dvs.103%29
