### ISSUE TITLE
Is Microsoft docs engine open sourced

### ISSUE THREAD

**Issue by peterremote1980** [MicrosoftDocs/feedback#1141]
Hi All
   Is Microsoft docs engine open sourced. If yes, which article talk about embed it in a website? If no, how come https://stackblitz.com/docs can embed microsoft docs engine into their web?
thanks
Peter

**Comment by dendeli-msft** [comment]
It is! You can start using DocFX today: https://dotnet.github.io/docfx/

You can read more about deploying your own docs infrastructure here: https://aka.ms/iwantdocs

**Comment by dcarapic** [comment]
Does DocFX support the same features as the docs.microsoft.com?
I am mainly interested in the 'Edit' feature where the end user can submit his own edits?
