### ISSUE TITLE
Clicking "Getting Started" on Xamarin.Forms main page gives a 404 error

### ISSUE THREAD

**Issue by anapp4that** [MicrosoftDocs/feedback#1146]
**Link to article:**
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/

**Problem:**
Clicking "Getting Started" on the above link gives me a 404 error.

**Comment by conceptdev** [comment]
@anapp4that thanks for letting us know! We recently updated our "Get Started" experience, the correct link is https://docs.microsoft.com/xamarin/get-started/ - I hope you find it useful.

I have just fixed the broken link, which should be published soon.
#please-close

**Comment by anapp4that** [comment]
@conceptdev

Thanks for the quick response. I had already found the correct link, but appreciate it.
