### ISSUE TITLE
tree for sublinks within the page

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#115]
Under the 'in this article' section, only ##'s are shown.  I think all headings should be shown.  I think it should be a collapsible tree that is collapsed by default.

By defaulting the tree to collapsed the UI will still be clean.

By adding all heading, users can more easily navigate larger documents.

----------
⚠ Idea migrated from UserVoice

**Created By:** Mike DePouw
**Created On:** 2017/09/27 16:49:44 +0000
**Votes at Migration:** 1
**Supporters at Migration:** 1

**Comment by Powerhelmsman** [comment]
Thanks for your suggestion. Here is the similar issue:  https://github.com/MicrosoftDocs/feedback/issues/278 
Close as wont-fix.
