### ISSUE TITLE
A number of REST API test pages provide invalid URLs

### ISSUE THREAD

**Issue by DavidR91** [MicrosoftDocs/feedback#1154]
**Link to article:**
https://docs.microsoft.com/en-gb/rest/api/monitor/alertsmanagement/alerts/getall

**Problem:**
The URL is stated as `https:///subscriptions/` and does not work in Try it mode - whereas it is presumably supposed to be `https://management.azure.com/subscriptions/{subscription-id}/resourceGroups/{resource-group-name}/providers/Microsoft.AlertsManagement/alerts`

This typo seems to affect **all** of the alert documentation for the monitor API

This also affects the 'try it' button making the feature completely unusable (and the URL cannot be edited/amended in try it mode)

Worth noting too that this article **doesn't support feedback comments**

**Comment by dendeli-msft** [comment]
Good feedback, @DavidR91 - thank you. I am following-up with the team on this!

**Comment by dendeli-msft** [comment]
Thanks for the report, @DavidR91! This should be fixed.

Den Delimarsky ● Senior PM, docs.microsoft.com ● [@DennisCode](https://twitter.com/DennisCode)
