### ISSUE TITLE
SEO issue: Some Microsoft Docs articles contain low quality links

### ISSUE THREAD

**Issue by shadinamrouti** [MicrosoftDocs/feedback#1157]
Dear Microsoft Docs managers,

Following the advise of @guardrex in https://github.com/aspnet/Docs/issues/10894, I'm writing to you about an SEO issue.

**The story**
When I started studying your docs, I noticed that this article: https://docs.microsoft.com/en-us/aspnet/core/mvc/overview?view=aspnetcore-2.2 and many others has several links to the same external website which I thought is belonging to Microsoft. 

Accordingly I suggested in https://github.com/aspnet/Docs/issues/10661 to add a similar external link to define a jargon mentioned in the article, similar to the trend followed in many articles. 

**The Contradiction**
My request in https://github.com/aspnet/Docs/issues/10661 above was rejected! so I analyzed the situation to conclude that the target website is a private website. In fact, it is the same linked one. 

**Poor quality links**
In [SEO](https://en.wikipedia.org/wiki/Search_engine_optimization), these kinds of links are bad for the ranking of Microsoft docs in search engines unless the target website is reputable, such as encyclopedias, famous universities...etc. 

**Open source**
Do you know that having such poor links in Microsoft Docs is generating traffic and thus profit to the target private website? does open source contributors here know that their efforts are converted to money for the account of a private website? is this why we contribute to your technology here? Alexa shows that the private website has a big upstream from doc.microsoft.com. Please why?

**This is killing the .Net technology**
By lowering the ranking of Microsoft Docs in search engines, why should I bother myself in learning .Net? It will rank low in search engines (or it may be penalized in Google) to the limit that no body will hear about it one day.

**The trend**
Kindly see 
- https://github.com/dotnet/docs/issues/10200,
- https://github.com/aspnet/Docs/issues/10668 and 
- https://github.com/aspnet/Docs/issues/10894

**The no follow solution**
In this article: [All Wikipedia Links Are Now NOFOLLOW](https://www.searchenginejournal.com/all-wikipedia-links-are-now-nofollow/4288/) , Wikipedia decided to use the nofollow solution in the entire encyclopedia. I asked for the same in https://github.com/aspnet/Docs/issues/10894 and I urged your members to read about the importance of the solution here: https://en.wikipedia.org/wiki/Nofollow

**The request**
- To remove all external links or at least use the nofollow solution

**Diversity**
If you don't want to follow SEO and insist in keeping links to the same private website, at least diversify. Why all articles are linked to the **same** private website?

**Comment by presleyy** [comment]
To me, what was described in this issue feedback makes a lot of sense. I don't suggest just adding the nofollow. Scrubbing the external links in the content seems be the better solution.

**Comment by presleyy** [comment]
In some cases, the existing external links still provide the best information, and meanwhile some others are updated. Close this issue for now. Scrubbing the external links is what we do regularly.
