### ISSUE TITLE
msbot clone services issue. 

### ISSUE THREAD

**Issue by skosuriAssocia** [MicrosoftDocs/feedback#1158]
msbot clone services --name "CoreBot1" --luisAuthoringKey #Thisishwereyourkeygoes# --code-dir "." --location westus --sdkLanguage "CSharp" --folder deploymentScripts/msbotClone --verbose

With msbot 4.3.2 and later, the only AZ CLI prerequisite is having an AZ CLI version >= 2.0.53. If you have the botservice extension installed as well, please remove this via "az extension remove --name botservice".

C:\Research\CoreBot1\CoreBot1>msbot -v
4.3.2

C:\Research\CoreBot1\CoreBot1>az -v
azure-cli                         2.0.58

I keep getting this error with CoreBot template. How do I resolve this issue?

**Comment by dendeli-msft** [comment]
Hi @skosuriAssocia - is this related to the documentation hosted on docs.microsoft.com?
