### ISSUE TITLE
Uri is not derived from MarshalByRefObject

### ISSUE THREAD

**Issue by mairaw** [MicrosoftDocs/feedback#1159]
Original GitHub issue https://github.com/dotnet/dotnet-api-docs/issues/1831 from @MarcioAB 

Uri is not derived from MarshalByRefObject as indicated by the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97955623-57f5-f557-7c5a-b5075b17f56e
* Version Independent ID: bd87f79c-646b-41ed-1345-57d2ae7d7ba1
* Content: [Uri Class (System)](https://docs.microsoft.com/en-us/dotnet/api/system.uri?view=netframework-4.7.2)
* Content Source: [xml/System/Uri.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System/Uri.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Not sure if this a dupe of #616 or not because that one is about the inheritance chain changing from one version to the other.

/cc @dendeli-msft @joelmartinez

**Comment by dendeli-msft** [comment]
@mairaw I believe it's the same thing - looking at the [XML](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System/Uri.xml#L30), it seems that `Uri` in an older version of .NET Framework actually was derived from that class, but was later dropped. This will be resolved once we move to SDP.
