### ISSUE TITLE
ReportViewer Code Example in Visual C++

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#116]
You REALLY need to provide example code for C++ in order to use the Microsoft ReportViewer (Microsoft.ReportViewer.WinForms.dll). Providing C# code is NOT the answer for everyone.

Either: 
1. Provide working example code in C++
2. Clearly state on the MSDN website that it can't be done

What do you think?

----------
⚠ Idea migrated from UserVoice

**Created By:** Anonymous
**Created On:** 2017/09/26 19:01:24 +0000
**Votes at Migration:** 1
**Supporters at Migration:** 1

**Comment by dend** [comment]
@mairaw @BillWagner @rpetrusha as FYI.

**Comment by mairaw** [comment]
You might have to just close this one.

This is not handled by our team @dend. This is probably owned by either VS or SQL. Not sure to which exactly content he/she's talking about. It also seems that there's no ReportViewer for VS2017.

Adding @ghogen here.

**Comment by Powerhelmsman** [comment]
Close as lacking of enough information.
