### ISSUE TITLE
Missing export feature in Data Migration Assistant tool

### ISSUE THREAD

**Issue by RushabhK23** [MicrosoftDocs/feedback#1162]
![dmaerror](https://user-images.githubusercontent.com/37142569/52784958-bc047f00-307c-11e9-93e0-981b7c354b63.PNG)
I have found that latest version of DMA v4.2 is lacking export feature of report at end. I have installed and run this tool and found missing button of Export report at the end. Can anyone help me to resolve that ?

**Comment by dendeli-msft** [comment]
Hello! This forum is for feedback on the docs.microsoft.com site. Given that this item is not directly related to our site, we cannot address it here. We recommend that you use the tool feedback channel to communicate your concerns or questions.
