### ISSUE TITLE
Short URLs

### ISSUE THREAD

**Issue by E14** [MicrosoftDocs/feedback#1163]
**Is your feature request related to a problem? Please describe.**
Especially when referencing documentation in source-code comments, the excessively long URLs of docs.microsoft.com either break the link (through line-breaks) or the code formatting, and so making it needlessly cumbersome to add or follow references within source-code documentation.

Example:

    https://docs.microsoft.com/en-us/office365/enterprise/powershell/connect-to-all-office-365-services-in-a-single-windows-powershell-window

This was me not even looking hard

**Describe the solution you'd like**
An alternative short(er) URL for each document, like other documentation solutions provide.

Example:

    https://docs.microsoft.com/fb690e2e-420e-f697-60f2-39520283d385

I chose to use the document_version_independent_id in the example because I want to show that it's not necessary to make tiny URLs, just not excessively long ones.

**Describe alternatives you've considered**
Using URL shortener services is obviously an option, but then documentation relies on two services being available instead of one.

Also, public URL shortener services are notorious for hiding malware, so a solution by MicrosoftDocs would obviously be superior.

**Comment by dendeli-msft** [comment]
Hi @E14 - this is good feedback. For URLs, it's a trade-off between readability and length. Our team chose to make the URLs easy to understand, as that serves for a better customer experience. GUIDs are rarely understood by anyone until they actually navigate to the article - we had that system on MSDN, and it was a constant point of customer paint.

We recommend using one of the many URL shorteners available to the public if you have a requirement to embed short URLs.

**Comment by E14** [comment]
I understand your point, but having the option to also refer to an article by a GUID does not mean that it has to exclude the "normal", supposedly more user-friendly, URLs. My suggestion was to support **both** - They are not mutually exclusive.

However, this is not a solution:

> We recommend using one of the many URL shorteners available to the public if you have a requirement to embed short URLs.

As written above:

> Using URL shortener services is obviously an option, but then documentation relies on two services being available instead of one.
>
> Also, public URL shortener services are notorious for hiding malware, so a solution by MicrosoftDocs would obviously be superior.

both points combine to a non-starter.
