### ISSUE TITLE
Resources api and the other detailed resource api(like blob rest api)

### ISSUE THREAD

**Issue by imeya** [MicrosoftDocs/feedback#1165]
When I'm studying the azure resources api, I found that there are 2 kinds of apis.

one for all resources(link [here](https://docs.microsoft.com/en-us/rest/api/resources/resources/get)), it's used to get a resource, so I can use it to get a blob content.

But there is a blob rest api for get, too(link [here](https://docs.microsoft.com/en-us/rest/api/storageservices/get-blob)). it's also can be used to get the blob.

So I want to know:
1. what's the difference between them? 
2. any advantage or disadvantage for each of them?
3. In which condition, which one I should use? 
4. Do they use same code(same implementation) in the backend?

**Comment by rootsmusic** [comment]
@imeya You should ask product-related questions to product support or in support forums.
#please-close
