### ISSUE TITLE
Error of css

### ISSUE THREAD

**Issue by sushilkumar4051** [MicrosoftDocs/feedback#1168]
https://developer.microsoft.com/en-us/advocates/index.html

Open this page some css error occur on this page 
Check  User 

Ryan Levick
@ryan_levick

Rust / Functional Programming / JavaScript/TypeScript / Architecture

its content showing outside the div

**Comment by mairaw** [comment]
I can't repro this @sushilkumar4051:
![image](https://user-images.githubusercontent.com/12971179/52977884-ea87a000-3383-11e9-8955-934c5b1bf8c0.png)

What's the browser that you're using?

**Comment by sushilkumar4051** [comment]
Hello,

   i used chorme browser and it display like that
[image: image.png]

**Comment by mairaw** [comment]
Attachments unfortunately are not shown when you reply by e-mail 😢

**Comment by mairaw** [comment]
Given we could not reproduce, I'm closing this issue. If you have more information about this, please let us know and we can reopen it.
