### ISSUE TITLE
Include documentation on Master DataServices under SQL Documentation

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#117]
Please include Master Data Services documentation under SQL Documentation

----------
⚠ Idea migrated from UserVoice

**Created By:** Fredrik Rundgren
**Created On:** 2017/09/21 11:59:58 +0000
**Votes at Migration:** 1
**Supporters at Migration:** 1

**Comment by dend** [comment]
@ishasahni1 @sudeepku any plans to implement this request?

**Comment by Powerhelmsman** [comment]
@ishasahni1 @sudeepku is there any update so far?

**Comment by ishasahni1** [comment]
@craigg-msft @sudeepku can you kindly confirm on the above request.
@Powerhelmsman FYI

**Comment by Powerhelmsman** [comment]
Send email to @craigg-msft @sudeepku to follow up.

**Comment by craigg-msft** [comment]
@botcrane I do not understand the question but the MDS content lives with the other SQL server content at https://docs.microsoft.com/en-us/sql/master-data-services/master-data-services-overview-mds?view=sql-server-2017.

@Powerhelmsman please close this issue.
