### ISSUE TITLE
Image Authorization

### ISSUE THREAD

**Issue by dbaid** [MicrosoftDocs/feedback#1170]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

**Link to article:**
https://docs.microsoft.com/en-us/sql/database-engine/log-shipping/media/ls-typical-configuration.gif?view=sql-server-2017

**Problem:**
Do you mind referecing your images in my own website??
like this 
<div class='fp-thumbnail'><a href='featured-post-1-url-here'><img src='https://docs.microsoft.com/en-us/sql/database-engine/log-shipping/media/ls-typical-configuration.gif?view=sql-server-2017'/></a></div>
<h3 class='fp-title'><a href='featured-post-1-url-here'>DR Soulution</a></h3>
<p>Some Descriptions</p>
</div>

**Comment by rootsmusic** [comment]
@dbaid See Terms of Use at https://docs.microsoft.com/en-us/legal/termsofuse

**Comment by dbaid** [comment]
I create one myself. Thank you for your response.

**Comment by dbaid** [comment]
I create one myself. Thank you for your response.
