### ISSUE TITLE
[Question] Layout source code for docs.microsoft.com website

### ISSUE THREAD

**Issue by tb-mtg** [MicrosoftDocs/feedback#1176]
In the spirit of now being open-source i was hoping somebody could share the code and any third-party css & js libraries that may have been used for the template/layout page for the docs.microsoft.com website.  

I love the design and am especially interested in the following work:

* the Left sidebar "Contents" menu and its ability to filter even with sub-navigation menus
* the Right sidebar "In this article" menu
* the Breadcrumbs across the top

**Comment by dendeli-msft** [comment]
@tb-mtg the layout source code is not currently available to the public. However, you can check out the open-source engine that powers docs.microsoft.com - [DocFX](https://dotnet.github.io/docfx/). It has a basic layout that shares some of the fundamental UX behaviors with what you see on our site.
