### ISSUE TITLE
The search seems to be broken today?  I went to the .NET area and did a search for SocketAsyncEventArgs.

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#118]
Search seems to be broken today.  I did a search in the .NET area for SocketAsyncEventArgs.  I expected a link to the main class documentation, possibly with some other stuff, too.  What I actually got was a list of obsolete classes (!) and some overview material.  

I only found the class documentation by going to the obsolete list and clicking from there -- that worked.  But it was a total surprise and can't possibly be what you intend.

----------
⚠ Idea migrated from UserVoice

**Created By:** peterdsmith
**Created On:** 2017/09/19 22:25:21 +0000
**Votes at Migration:** 2
**Supporters at Migration:** 2

**Comment by Powerhelmsman** [comment]
@presleyy Can you take a look at this issue?

**Comment by presleyy** [comment]
Have created a P0 bug to track it.

**Comment by presleyy** [comment]
Content team has fixed the PowerShell repo setting, currently it is set without search scope. So searching for "SilentlyContinue" should be like https://docs.microsoft.com/en-us/search/index?search=silentlycontinue.

**Comment by presleyy** [comment]
For the origin issue, searching "SocketAsyncEventArgs" within .NET scope returns results. @Powerhelmsman shall we close the issue?
