### ISSUE TITLE
Wrong example under self-join explanation section

### ISSUE THREAD

**Issue by EleonoraGrigoryan** [MicrosoftDocs/feedback#1183]
**🛑 IMPORTANT** 
Mistake in the documentation of SQL Server in Books Online

**[Link to article in BOL:](https://docs.microsoft.com/en-us/previous-versions/sql/sql-server-2008-r2/ms177490(v=sql.105))**

**Problem:**
In the second example it is stated that there is a self join but in reality it joins two different tables Sales.SalesPerson and Sales.SalesTerriotory. Self join is about joining the same table to itself.
![image](https://user-images.githubusercontent.com/29795965/53111205-1bb7ca00-3556-11e9-804d-5006056b1fab.png)

Thanks.

**Comment by rootsmusic** [comment]
@EleonoraGrigoryan "This content has been retired and may not be updated in the future."
#please-close
