### ISSUE TITLE
Enable TechProfile Picture

### ISSUE THREAD

**Issue by HansOMartinsen** [MicrosoftDocs/feedback#1186]
I am using a profile picture on all my different webpages out there. I would really like to be able to have one for techprofile also, not just the default icon that is there today.

Kind Regards
Hans O. Martinsen

**Comment by saldana** [comment]
Thank you @HansOMartinsen for the feedback. We are planning to have that capability really soon. I will let you know when it is available.

**Comment by saldana** [comment]
@HansOMartinsen this feature is now released!!
