### ISSUE TITLE
MS Events/Online Sessions

### ISSUE THREAD

**Issue by krisrajz** [MicrosoftDocs/feedback#1188]
Ref:
https://www.microsoftazurevidyapeeth.com/
event.on24.com, vshow.on24.com

Online sessions via azurevidapeeth and pro tech days are always an issue though I appreciate the speaker and spreading technology to the community. Though having good connectivity most of the online sessions are problematic, speakers themselves knew and agreed several times. Requesting MS to find better platform to make learning interesting and trouble free. I no longer attend any of these sessions.

Thank you very much.

**Comment by dendeli-msft** [comment]
Thank you for the feedback! We are working on ensuring that you can always find the most relevant and interesting learning resources on [Microsoft Learn](https://docs.microsoft.com/learn). Let us know what you think about the new site!
