### ISSUE TITLE
TextWriter API page has title with no content 

### ISSUE THREAD

**Issue by ChrisMaddock** [MicrosoftDocs/feedback#1190]
This page has the title "Explicit Interface Implementations", and then no content underneath it.

https://docs.microsoft.com/en-us/dotnet/api/system.io.textwriter?view=netframework-4.7.2#explicit-interface-implementations

Originally posted here: https://github.com/dotnet/dotnet-api-docs/issues/1884

**Comment by ChrisMaddock** [comment]
Quote @mairaw @ https://github.com/dotnet/dotnet-api-docs/issues/1884#issuecomment-464893950

> That's odd @ChrisMaddock. I usually see that behavior when one of the versions has APIs under (which is still a bug), but in this case I don't see any version that has an EII.
> 
> Would you mind opening an issue at https://github.com/MicrosoftDocs/feedback/issues instead? This issue needs to go to the engineering team.

**Comment by mairaw** [comment]
This seems to have been fixed with the latest CI runs

**Comment by ChrisMaddock** [comment]
The title is now gone. 🙂
