### ISSUE TITLE
Broken page style in Chinese version

### ISSUE THREAD

**Issue by inkydragon** [MicrosoftDocs/feedback#1193]
There is no comment section in the article.

**Link to article:**
Not only a page, it seems like many other page also has this problem.
1. [适用于 Windows 的 fluent Design 系统 - UWP app developer | Microsoft Docs](https://docs.microsoft.com/zh-cn/windows/uwp/design/fluent-design-system/index)
2. [通用 Windows 平台 (UWP) 应用设计（Windows 应用）简介 - UWP app developer | Microsoft Docs](https://docs.microsoft.com/zh-cn/windows/uwp/design/basics/design-and-ui-intro)

**Problem:**
Broken page style, shows many `:::row:::`, `:::column:::`, `:::row-end:::`...

English version works well: 
1. [Fluent Design System for Windows - Windows UWP applications | Microsoft Docs](https://docs.microsoft.com/en-us/windows/uwp/design/fluent-design-system/index)

**Comment by mairaw** [comment]
@JasonCard who owns UWP localization? This seems to have been fixed since but this content has no edit button, no breadcrumb, etc.

**Comment by JasonCard** [comment]
@mairaw adding @nokura who owns UWP localization.

**Comment by inkydragon** [comment]
Already fixed.
