### ISSUE TITLE
SPO CSOM needs API guide to be able to document new API added each release

### ISSUE THREAD

**Issue by westleyMS** [MicrosoftDocs/feedback#1195]
**Link to article:**
In the SharePoint online docs, there is no API docs for CSOM even though they are adding API to it on a regular basis. You can see this here-
[https://developer.microsoft.com/en-us/sharepoint/blogs/new-sharepoint-csom-version-released-for-sharepoint-online-november-2018/](https://developer.microsoft.com/en-us/sharepoint/blogs/new-sharepoint-csom-version-released-for-sharepoint-online-november-2018/)

**Problem:**
We need to add documentation on new methods/properties, but there is only an on-prem version of SharePoint docs, and we need an online version.

**Comment by rootsmusic** [comment]
@westleyMS Do you mean https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/sharepoint-net-server-csom-jsom-and-rest-api-index ?

**Comment by mairaw** [comment]
Closing due to the lack of information. @westleyMS if the issue still persists, give us more info and we can reopen it.
