### ISSUE TITLE
Add better overview

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#120]
When looking at the uwp documentation compared to good old MSDN i realized that it is hard to get an overview of apis.
If I want to know the methods of a cl*** for example i often have to scroll a lot just to get an overview what methods are defined. A compact list like we have on Namespaces would help. Also I would love to collapse things like examples. Examples are important but to get an overview of the api they are taking up a lot of scrolling space.

----------
⚠ Idea migrated from UserVoice

**Created By:** Lars
**Created On:** 2017/08/28 18:56:43 +0000
**Votes at Migration:** 4
**Supporters at Migration:** 4

**Comment by Powerhelmsman** [comment]
@kubeaver @ShevaDas Can you take a look at this?

**Comment by Powerhelmsman** [comment]
#log-suggestion

**Comment by botcrane** [comment]
🚀 **ATTENTION**: [Internal request](https://ceapex.visualstudio.com/web/wi.aspx?pcguid=7d644393-99ad-41c8-ac53-7fa79294c720&id=21143) logged.

**Comment by ShevaDas** [comment]
@dend would this fall under your API browser work?

**Comment by dend** [comment]
Closing this as it's a content issue that we are addressing en-masse for API reference.
