### ISSUE TITLE
Syntax is not highlighted

### ISSUE THREAD

**Issue by Hoxni** [MicrosoftDocs/feedback#1201]
**Describe the bug**
Syntax is not highlighted

**To Reproduce**
1. Go to https://docs.microsoft.com/en-us/sql/t-sql/functions/rank-transact-sql?view=sql-server-2017
2. Look at any sample code

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser chrome, edge

**Comment by MashaMSFT** [comment]
Hi @Hoxni , thanks for your feedback! Sorry, would you mind clarifying what you mean by "not highlighted"? Are you referring to the color of the text, in that it's gray, and not multi-colored like typical T-SQL text, or am I misunderstanding something? Thanks!

**Comment by Hoxni** [comment]
Yes, it's about colour of the text

**Comment by MashaMSFT** [comment]
Hi @Hoxni , thanks for bringing this to our attention! Did you know you could modify the text yourself? You can find more information here: http://aka.ms/editsqldocs but basically, you just need to select the "edit" button at the top right of the document, and then select the pencil icon to edit the text. . If you do so, you'll be listed as a contributor to the documentation. It's actually a pretty easy fix:

Right now, the code blocks are like:
```
tsql
```

The only thing you need to add is a "sql" after the ``` so that the code looks like:
```sql
tsql
```

Did you want to make this change yourself? If not, however, I would be happy to do so for you! :) Thanks again!

**Comment by MashaMSFT** [comment]
Hi @Hoxni , I went ahead and made these changes for you :) Thanks again for letting us know! #please-close
