### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by nadotwins** [MicrosoftDocs/feedback#1209]
**Link to article:**
https://docs.microsoft.com/en-us/azure/notification-hubs/notification-hubs-android-push-notification-google-fcm-get-started#configure-firebase-cloud-messaging-settings-for-the-hub

**Problem:**
What's wrong with the article?

Step 3 on this section (**Configure Firebase Cloud Messaging settings for the hub**) has spelling mistake/typo "Selct"

**Comment by dendeli-msft** [comment]
@nadotwins can you please re-open this issue here: https://github.com/MicrosoftDocs/azure-docs/issues? Thank you!
