### ISSUE TITLE
[error message feedback] provide feedback

### ISSUE THREAD

**Issue by Paul-Dempsey** [MicrosoftDocs/feedback#1212]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

**Problem:**
The error message "Metadata rules not available" is unactionable. I have no idea what it means, or what I need to do to recover or fix it.

**Log code info**
(This is auto filled, no need to modify)

| Severity   | Type   | Code   | Category   | File   | Message   |  Source  | Line   | Time   |
|------------|--------|--------|------------|--------|-----------|----------|--------|--------|
| Error | Unspecified |  |  | CTAS/CTAS/UserGuide/Migration/MigratingWorkflows2-8.md | Metadata rules not available | BuildCore.Build Document.CompilePhaseHandlerWithIncremental.ConceptualDocumentProcessor.Build.ValidateConceptualDocumentMetadata | | 02/28/2019 01:57:49 |

**Link to report**
(This is auto filled, no need to modify)

[report url](https://opbuildstorageprod.blob.core.windows.net/report/2019/2/28/95f57156-05cc-2a02-6cf9-fabceec8e05a/Commit/201902280157047411-master/workflow_report.html?sv=2015-02-21&sr=b&sig=J3TRcMT%2FKB0Ej7iKPi9b47pZUvZk560hGQZ2TJPGRy0%3D&st=2019-02-28T01%3A53%3A14Z&se=2019-03-31T01%3A58%3A14Z&sp=r)

**Comment by dendeli-msft** [comment]
@cillroy please take a look.

**Comment by cillroy** [comment]
Thank you for the feedback, we are constantly working on improving the messaging, and documentation around the build messages.
