### ISSUE TITLE
PathSegment.IsSmoothJoin possible error and confusing explanation

### ISSUE THREAD

**Issue by alataffective** [MicrosoftDocs/feedback#1217]
**Link to article:**
https://docs.microsoft.com/en-us/dotnet/api/system.windows.media.pathsegment.issmoothjoin?view=netframework-4.7.2

**Problem 1 (affected join):**
"join between this PathSegment and the previous PathSegment"
In my tests the property value affects this path segment and the _next_ path segment not the previous as stated.

**Problem 2 (corner value and definition):**
Saying that true means it is not treated as a corner. What does treated as a corner mean? When true, the join between this segment and the next is rounded, giving the impression (to me at least) of a corner. So in my mind true means it _is_ treated as a corner, where false means the lines are just drawn one over another. This does depend on the definition of corner (which is not provided).

**Comment by mairaw** [comment]
This issue was moved to dotnet/dotnet-api-docs#3694
