### ISSUE TITLE
LinkedIn v2 API ugcPosts update

### ISSUE THREAD

**Issue by rnnds** [MicrosoftDocs/feedback#1219]
My team and I are migrating to API v2, but we could not find a way to update posts using `ugcPosts` API.

Is it not implemented or just not documented ?

The URN returned from an `ugcPosts` creation follows the pattern `urn:li:share:...`, so I tried to update using `shares` endpoint without success.

**Comment by dendeli-msft** [comment]
@rnnds given that this issue is not related to docs.microsoft.com, we cannot address it in this repository. We would recommend visiting the LinkedIn Developer Support pages for more information: https://developer.linkedin.com/support
