### ISSUE TITLE
help viewer 2.2

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#122]
Why I can't see 
- ASP.Net core
- ASP.Net Core API Reference
- Nuget 
- MVC documentation

in Help viewer, Manage Content ?

----------
⚠ Idea migrated from UserVoice

**Created By:** sn gShadow
**Created On:** 2017/08/15 02:21:01 +0000
**Votes at Migration:** 2
**Supporters at Migration:** 2

**Comment by dend** [comment]
All the information request below is already available in Help Viewer 2.3 with Visual Studio 2017:

![image](https://user-images.githubusercontent.com/1389609/42291606-9ec4c4d8-7f81-11e8-92aa-93a30ebb5fd4.png)
