### ISSUE TITLE
Introduction to C Sharp - explanation of classes

### ISSUE THREAD

**Issue by MEMCD5** [MicrosoftDocs/feedback#1221]
Sorry I'm not sure if I'm flagging this up in the right place but...

I'm new to C Sharp & eager to learn as much as I can. I've tried several on-line tutorials but found that they either bogged me down with too much unnecessary content or they assumed that I was already an experienced object-orientated programmer - which unfortunately I'm not. 

I've recently tried Microsoft's "Introduction to  C Sharp" online tutorials &, up until today, have been pleasantly impressed. They are well-worded, relevant, concise & include good example code. 

I've worked my way up to:

https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/intro-to-csharp/interpolated-strings?tutorial-step=2

but at this stage I hit a block. The chapter was discussing strings, but it used an example which included new classes & enumeration. Given that these - more complex topics - had not yet been discussed in the introduction  I found myself floundering a bit. Unfortunately the example code did not include any comments so it was hard to distinguish the different components (constructors, calling function, etc) & the order in which they would naturally run. 

As a result I found myself guessing & moving backward & forward through other articles trying to make sense of it all, but just ended up getting more confused & disheartened.

Can the tutorial be amended to deal with these topics in the same clear way that it had done with the preceding 'simpler' topics?

I know 'real programmers' will not struggle with this, but new (even though I'm old!) ones like me may not be readily able to. I know Microsoft's goal is to make it's languages accessible to all so do you think it will be possible to include specific, simple to follow sections, on these topics earlier in the series?

Thanks a lot!

**Comment by mairaw** [comment]
@BillWagner can you take a look at this feedback?

**Comment by BillWagner** [comment]
I'll address this as part of the re-organization of the C# Guide.  

In the meantime, I'll move this node to the "explore" section, which assumes more C# knowledge.

**Comment by MEMCD5** [comment]
Thanks a lot for considering my feedback & for offering  to make changes Bill – much appreciated.
Any idea when the re-organized content is likely to be available?
As stated previously the tutorial is really good (best I have seen), but I think this subtle change will make it even better!

Take care,
Martin


________________________________

**Comment by mairaw** [comment]
This was fixed. Can someone please close this @sudeepku @dendeli-msft?
