### ISSUE TITLE
Azure Learning

### ISSUE THREAD

**Issue by PavanDhariwal** [MicrosoftDocs/feedback#1223]
When attempting to sign in for Azure learning, I am prompted to register a profile. 

Linke: https://techprofile.microsoft.com/en-GB/register?replyUrl=https://docs.microsoft.com/en-us/learn/modules/welcome-to-azure/&

I fill in my details, click on register and nothing happens. I took a look at the console and found two errors.

docs.microsoft.com/api/profiles/me:1 Failed to load resource: the server responded with a status of 404 ()
docs.microsoft.com/api/profiles:1 Failed to load resource: the server responded with a status of 400 ()

Please can I have some assistance as I would like to have this account and gain the XP points for my learning development.

Thanks,

Pavan

**Comment by Emmagrabergs** [comment]
when will it be fixed?

**Comment by simondavidhill** [comment]
I have the same issue.

**Comment by simondavidhill** [comment]
Try setting country to US as per this comment: https://github.com/MicrosoftDocs/feedback/issues/1234#issuecomment-469759236

**Comment by PavanDhariwal** [comment]
What an odd bug!

**Comment by stillface** [comment]
not working selecting US

**Comment by dendeli-msft** [comment]
Duplicate of #1234
