### ISSUE TITLE
Unable to locate signup for xamarin newsletter

### ISSUE THREAD

**Issue by jkarlsso** [MicrosoftDocs/feedback#1224]
I am receiving a monthly newsletter (it is great) and I am looking to sign up another email address. But after some Googling and plenty of "smartphone browsing" I can not seem to find where to do this.

My guess is that it comes with my VS account, but when I log in there the box for newsletter is unchecked, so I am unsure.

The latest email read "Welcome to the February 2019 edition of the Xamarin newsletter."... And originated from visualstudio@email2.microsoft.com.

It would be nice to be able to sign up for these xamarin newsletter updates without an account.

Thanks

**Comment by dendeli-msft** [comment]
@jkarlsso given that this is not directly to docs.microsoft.com, we cannot address this issue in this repository. I would recommend reaching out on the Xamarin Forums regarding your questions on the Xamarin platform: https://forums.xamarin.com/
