### ISSUE TITLE
Move the language selection to the top of the page

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#123]
The language selection is currently in the lower left corner. I have to scroll all the way down to change it. Please put it back on top.

----------
⚠ Idea migrated from UserVoice

**Created By:** Anonymous
**Created On:** 2017/08/10 10:45:58 +0000
**Votes at Migration:** 1
**Supporters at Migration:** 1

**Comment by Powerhelmsman** [comment]
Thanks for your feedback. This is Microsoft standard on all pages.
