### ISSUE TITLE
pedagogical strategy

### ISSUE THREAD

**Issue by Jmck2** [MicrosoftDocs/feedback#1237]
What is Microsoft approach to "Just in time learning". Are they modelized to allow focus on just the specific area's needed vs, all lumped together.  

https://www.advantageperformance.com/implementing-just-in-time-learning/
https://www.bing.com/search?q=just+in+time+learning&form=EDNTHT&mkt=en-us&httpsmsn=1&plvar=0&refig=0e25e2e414b74b7aac37f01d7e34f9c3&sp=1&pq=just+in+time+learner&sc=8-20&qs=SC&sk=&cvid=0e25e2e414b74b7aac37f01d7e34f9c3&cc=US&setlang=en-US

**Comment by sudeepku** [comment]
Thanks @Jmck2  for your comment. Please visit https://docs.microsoft.com/en-us/learn/ which is hands-on and a modular approach to learning.
