### ISSUE TITLE
Incorrect rendering of an escaped asterisk within emphasis block

### ISSUE THREAD

**Issue by riverar** [MicrosoftDocs/feedback#1238]
![image](https://user-images.githubusercontent.com/475132/53860095-b2dc4300-3f94-11e9-9988-ea65283045e6.png)
-- https://docs.microsoft.com/en-us/uwp/winrt-cref/winrt-type-system

Markdown and CommonMark specs seem to agree that backslash escapes should work in this case:
- https://daringfireball.net/projects/markdown/syntax#backslash
- https://spec.commonmark.org/0.28/#backslash-escapes

cc @dend @mairaw

**Comment by dendeli-msft** [comment]
@cillroy something you can take a look at?

**Comment by mairaw** [comment]
It seems to have been fixed since then.
