### ISSUE TITLE
How to give credit to code snippets and larger codes?

### ISSUE THREAD

**Issue by AlirezaAlipour** [MicrosoftDocs/feedback#1239]
In Microsoft Docs or in some blogs of Microsoft exist code snippets and larger codes__ I don't know how to name it, for [this example](https://docs.microsoft.com/en-us/aspnet/core/razor-components/layouts?view=aspnetcore-3.0) I named it "code snippet" and [this](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.aescryptoserviceprovider?view=netframework-4.7.2#examples) I named it "larger codes", first of all, is it require to to give credit to copyright owner for used code snippets or larger codes in our projects? If it is require to give credit to copyright owner for those(code snippets or larger codes), how to do it?

Also, as I know, some Microsoft Docs hosted on GitHub, for example as I can see the licence of [this repository](https://github.com/aspnet/Docs) is Attribution 4.0 International, so It need attribution and we need to get credit for codes in Microsoft Docs. My question is for a small codes we need attribution? and how much is small?

As you know, in top of codes in Microsoft Docs exist an "copy" button, I think if attribution is require it is better to specifying it by contributor when they are contributing on docs and adding feature for "copy" button to automatically include attribution to clipboard in addition to codes that we will copying.

**Comment by dendeli-msft** [comment]
@AlirezaAlipour the code in each of the repositories is licensed under the license defined in `LICENSE-CODE` file. Please make sure to follow attribution defined in the license for all code snippets that is used from the documentation for projects that are not built for simple educational purposes (e.g. testing an API, building a sample application for yourself).
