### ISSUE TITLE
Missing SharePoint

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#124]
SharePoint commands would be quite nice ..

----------
⚠ Idea migrated from UserVoice

**Created By:** Marcel
**Created On:** 2017/08/10 06:19:04 +0000
**Votes at Migration:** 1
**Supporters at Migration:** 1

**Comment by dend** [comment]
Related to the PowerShell Module Browser.

**Comment by Powerhelmsman** [comment]
This is the link: https://docs.microsoft.com/en-us/powershell/module/?term=sharepoint
