### ISSUE TITLE
Visual Studio 2013 Content

### ISSUE THREAD

**Issue by IndustrieInformatik** [MicrosoftDocs/feedback#1240]
**Link to article:**
https://docs.microsoft.com/en-us/visualstudio/test/writing-unit-tests-for-c-cpp?view=vs-2017

**Problem:**
There is generally no documentation available for Visual Studio 2013 any more. Is there any way to access the Documentation? Currently there is only the Documentation for Visual Studio 2015 and later available.

Best Regards, Markus

**Comment by dendeli-msft** [comment]
@IndustrieInformatik the Visual Studio 2013 content has been archived, and can be found here: https://docs.microsoft.com/en-us/previous-versions/visualstudio/visual-studio-2013/dd831853(v=vs.120)
