### ISSUE TITLE
the powershell cmdlet Get-AzWebAppMetrics failed with bad request

### ISSUE THREAD

**Issue by imeya** [MicrosoftDocs/feedback#1242]
When I use the cmdlet Get-AzWebAppMetrics, it failed to execute with error message: Get-AzWebAppMetrics : Operation returned an invalid status code 'BadRequest'.

I don't know what's wrong with it. can you please let me know how to correct the error? Thanks.

![error-ps](https://user-images.githubusercontent.com/25738099/53926366-25950d80-40be-11e9-9001-88d63e3907ae.JPG)

**Comment by dendeli-msft** [comment]
Hi @imeya - because this is not a docs.microsoft.com issue, we cannot address the feedback in this repository. Please open the issue in the Azure PowerShell repo: https://github.com/Azure/azure-powershell/.
