### ISSUE TITLE
Sentence formation mistake in line "You can will identify the available..." 

### ISSUE THREAD

**Issue by DebabrataHowlee** [MicrosoftDocs/feedback#1243]
Below is the link.
https://docs.microsoft.com/en-us/partner-center/faq-about-new-billing-features#annualbillingfaq

![image](https://user-images.githubusercontent.com/12857862/53926460-7e0de000-40a9-11e9-979b-6601cfb060f5.png)

**Comment by dendeli-msft** [comment]
@MaggiePucciEvans can you please take a look at this issue?

**Comment by JasonWHowell** [comment]
This page has since been removed. We also are doing a better job to make sure our grammar is improved. 
Thanks for the attention to detail, @DebabrataHowlee 
#please-close
