### ISSUE TITLE
Formulas not rendering anymore on Quantum Computing pages

### ISSUE THREAD

**Issue by dtaflin** [MicrosoftDocs/feedback#1248]
**Describe the bug**
*This is a new issue that only showed up today* When viewing any of the Quantum Computing Concepts pages, e.g. https://docs.microsoft.com/en-us/quantum/concepts/circuits?view=qsharp-preview, the formulas, matrixes, etc. are not rendering, but instead look like raw TeX. I suspect MathJax.js isn't kicking in. Example:
`$$\mathrm{CNOT}_{01}(H\otimes 1)|00\rangle = \frac{1}{\sqrt{2}} \left(|00\rangle + |11\rangle \right),$$`

**To Reproduce**
1. Go to https://docs.microsoft.com/en-us/quantum/concepts/circuits?view=qsharp-preview
2. Start reading

**Expected behavior**
The above formula should render properly, like this:
<img width="292" alt="screen shot 2019-03-07 at 9 40 08 pm" src="https://user-images.githubusercontent.com/5872390/54009938-a802e900-4121-11e9-838b-73c8fcd3d8ba.png">

**Screenshots**
<img width="668" alt="screen shot 2019-03-07 at 9 41 44 pm" src="https://user-images.githubusercontent.com/5872390/54009994-d7b1f100-4121-11e9-8dac-3b71eb30ea75.png">

**Desktop:**
 - OS: OS 10.14 (Mojave)
 - Browser Chrome
 - Version 72

**Comment by sudeepku** [comment]
@dtaflin . Thanks for your feedback. The issue is fixed.
![image](https://user-images.githubusercontent.com/16726119/54061625-856edf80-41b6-11e9-97c9-f537b0d69b45.png)
