### ISSUE TITLE
Expand search scope to the rest of the PowerShell gallery.

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#125]
It would be great to be able to have a version of this tool that could search the PowerShell gallery and include those cmdlets in the result set. This way, if someone wanted to know if a cmdlet existed to do a task, they might be pointed in the direction of a community authored module if Microsoft doesn't offer one of their own.

Ideally the module author could offer their own documentation based on a standard file and folder layout that could be crawled by an analyzer, or if the agreed upon files and folders are not found, regular Get-Help style code analysis could at least be used to stub out things like the cmdlet names and parameter names.

----------
⚠ Idea migrated from UserVoice

**Created By:** Bill
**Created On:** 2017/08/08 19:11:21 +0000
**Votes at Migration:** 1
**Supporters at Migration:** 1

**Comment by Powerhelmsman** [comment]
Thanks for your feedback at this time we don't plan to includes any packages which are not distributed by Microsoft.
