### ISSUE TITLE
 404 Web Site not found.

### ISSUE THREAD

**Issue by samlh** [MicrosoftDocs/feedback#1257]
**Describe the bug**
Cannot view docs.microsoft.com at all, an instead getting an error. Intermittent - 2nd time in the past week.

**To Reproduce**
1. Go to https://docs.microsoft.com/
2. See error

```
404 Web Site not found.

You may be seeing this error due to one of the reasons listed below :

    Custom domain has not been configured inside Azure. See how to map an existing domain to resolve this.
    Client cache is still pointing the domain to old IP address. Clear the cache by running the command ipconfig/flushdns.

Checkout App Service Domain FAQ for more questions.
```

**Expected behavior**
The docs are visible.

**Screenshots**
![image](https://user-images.githubusercontent.com/118173/54160228-3b7f3700-440c-11e9-8508-5e9e8d4624e6.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox 
 - Version: 65.0.2

**Additional context**
`ipconfig /flushdns` did not solve the problem.
Taking the time to fill out this report took long enough the issue stopped reproducing.
However, this is the 2nd time in the past week I've seen this error, so I'm filing regardless.

**Comment by rootsmusic** [comment]
Fixed.
#please-close
