### ISSUE TITLE
What is <%: ... %> in ASP.Net Web Forms

### ISSUE THREAD

**Issue by SimpleSamples** [MicrosoftDocs/feedback#1258]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

[ASP.NET Page Syntax](https://docs.microsoft.com/en-us/previous-versions/dotnet/netframework-4.0/fy30at8h(v=vs.100))

I am not sure if it is the current version. If it is not the current version then I don't know where the current version is. Whether it is current or not, I cannot find something saying what <%: ... %> in ASP.Net Web Forms are. Scott introduces them in [ScottGu's Blog - New <%: %> Syntax for HTML Encoding Output in ASP.NET 4 (and ASP.NET MVC 2)](https://weblogs.asp.net/scottgu/new-lt-gt-syntax-for-html-encoding-output-in-asp-net-4-and-asp-net-mvc-2) but he avoids giving a name. Without a name it is difficult to find the documentation. Are the <%: %> blocks documented?

**Comment by rootsmusic** [comment]
@SimpleSamples "We're no longer updating this content regularly."
#please-close
