### ISSUE TITLE
Searching for phrases including 'C++' is broken

### ISSUE THREAD

**Issue by docs-product** [MicrosoftDocs/feedback#126]
As an example, search for 'c++ linux' on docs. There are 0 results, even though C++ development on Linux is an important new scenario for VS (https://docs.microsoft.com/en-us/cpp/linux/).

----------
⚠ Idea migrated from UserVoice

**Created By:** Aditya Mandaleeka
**Created On:** 2017/08/01 18:57:44 +0000
**Votes at Migration:** 2
**Supporters at Migration:** 2

**Comment by presleyy** [comment]
Convert it to a bug work item in VSTS

**Comment by presleyy** [comment]
Have a [bug](https://mseng.visualstudio.com/CSI/_workitems/edit/1220335) created before which is in active status. Loop @Sampy

**Comment by docs-product** [comment]
This issue is now resolved - searching for C++ should yield correct results.
