### ISSUE TITLE
anonymous spelled wrong

### ISSUE THREAD

**Issue by nerobawz** [MicrosoftDocs/feedback#1261]
Tell us where exactly a problem occurs.
https://docs.microsoft.com/en-us/iis/configuration/system.webserver/security/authentication/anonymousauthentication

under the Configuration this line:
`The <anomymousAuthentication> element is configurable at the site and application level in the Web.config file.`

anonymousAuthentication is spelled as anomymousAuthentication.

**Comment by shirgoldbird** [comment]
Thanks for reporting this! A PR has been opened to fix it [here](https://github.com/MicrosoftDocs/iis-docs/pull/319).

In the future, you can fix typos like this yourself by clicking the edit button at the top of most Docs articles. :)

![image](https://user-images.githubusercontent.com/3937986/54381183-5dfe9380-464a-11e9-8779-de61e593ea83.png)
