### ISSUE TITLE
Typo in SQL documentation: statements

### ISSUE THREAD

**Issue by jssuttles** [MicrosoftDocs/feedback#1265]
**Link to article:**
https://docs.microsoft.com/en-us/sql/t-sql/statements/statements?view=sql-server-2017

**Problem:**
statements is misspelled in the sidebar

![image](https://user-images.githubusercontent.com/8527741/54232850-06ddaf00-44e2-11e9-9e10-9e2759fbac0b.png)

**Comment by mairaw** [comment]
This has been fixed. Closing.
