### ISSUE TITLE
Download link for 'Windows Hello World Sample' does not work

### ISSUE THREAD

**Issue by BissetJ** [MicrosoftDocs/feedback#1269]
**Link to article:**
https://docs.microsoft.com/en-us/windows/desktop/learnwin32/windows-hello-world-sample

**Problem:**
Content:
This sample is available in the MSDN Code Gallery at https://go.microsoft.com/fwlink/p/?linkid=184824.

That link goes to archive.msdn.microsoft.com, which doesn't seem to exist.

**Comment by fido9dido** [comment]
I have the same problem and people asked this from them last year and they did nothing
here's a reference to the older still-open ticket that they didn't solve 
https://github.com/MicrosoftDocs/feedback/issues/799

**Comment by ryanmajidi** [comment]
@GrantMeStrength Can you please take a look at this issue?

**Comment by GrantMeStrength** [comment]
Assigned to correct writer.

**Comment by QuinnRadich** [comment]
Apologies for the much-delayed response on this issue.

The issue on this page was resolved some time ago, along with many similar outdated MSDN Code Gallery links. Thank you for raising it in the first place.
