### ISSUE TITLE
All macros from classic Win32 UI related headers (winuser.h, commctl.h, etc.) are missing return values and parameter types

### ISSUE THREAD

**Issue by BissetJ** [MicrosoftDocs/feedback#1270]
**Link to article:**
Review all macros from these headers list here (though this may not be the full extent of the problem).
https://docs.microsoft.com/en-us/windows/desktop/api/_controls/

**Problem:**
It seems that **all** macros are missing descriptions of their return values, and their parameters are missing type information.  One example:
https://docs.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-makelparam

Compare that against this:
https://msdn.microsoft.com/en-us/data/ms632661(v=vs.90)

**Comment by ryanmajidi** [comment]
@GrantMeStrength Can you please take a look at this issue?

**Comment by GrantMeStrength** [comment]
Investigating

**Comment by GrantMeStrength** [comment]
This is a systemic issue with the publishing tools. A bug has been filed with the engineering team.

**Comment by lmstearn** [comment]
_ListView_GetItemCount_ is anexample, returning 0 instead of the maximum number of columns in a Listview. 
_ListView_GetHeader_ is documented as having no return value, but instead it correctly returns a handle.
Thanks.
