### ISSUE TITLE
VerifyVersionInfo is not documented as depreciated

### ISSUE THREAD

**Issue by Stevoisiak** [MicrosoftDocs/feedback#1272]
**Link to article:**
https://docs.microsoft.com/en-us/windows/desktop/api/Winbase/nf-winbase-verifyversioninfoa

**Problem:**
According to [*Targeting your application for Windows*](https://docs.microsoft.com/en-us/windows/desktop/sysinfo/targeting-your-application-at-windows-8-1), the VerifyVersionInfo function was deprecated in Windows 10. This depreciation is not mentioned in the documentation for [VerifyVersionInfo](https://docs.microsoft.com/en-us/windows/desktop/api/Winbase/nf-winbase-verifyversioninfoa).

Additionally, the documentation for deprecated functions [GetVersion](https://docs.microsoft.com/en-us/windows/desktop/api/sysinfoapi/nf-sysinfoapi-getversion) and [GetVersionExA](https://docs.microsoft.com/en-us/windows/desktop/api/sysinfoapi/nf-sysinfoapi-getversionexa) recommend using the [Version Helper functions](https://docs.microsoft.com/en-us/windows/desktop/SysInfo/version-helper-apis), which make use of the depreciated [VerifyVersionInfo](https://docs.microsoft.com/en-us/windows/desktop/api/Winbase/nf-winbase-verifyversioninfoa).

If VerifyVersionInfo has been depreciated, it should be mentioned on the documentation page.

**Comment by ryanmajidi** [comment]
@GrantMeStrength can you please take a look at this issue?

**Comment by GrantMeStrength** [comment]
Investigating

**Comment by GrantMeStrength** [comment]
Corrections have been submitted. Thank you for this feedback!

**Comment by Stevoisiak** [comment]
@GrantMeStrength The documentation for [GetVersion](https://docs.microsoft.com/en-us/windows/win32/api/sysinfoapi/nf-sysinfoapi-getversion) and [GetVersionExA](https://docs.microsoft.com/en-us/windows/win32/api/sysinfoapi/nf-sysinfoapi-getversionexa) still recommend depreciated functions.
