### ISSUE TITLE
no serach result for short term like "GC"

### ISSUE THREAD

**Issue by sillyousu** [MicrosoftDocs/feedback#1273]
**Describe the bug**
docs.microsoft.com/en-us/dotnet/api/ shows no result for short term like "GC"

**To Reproduce**
search **GC** on https://docs.microsoft.com/en-us/dotnet/api/

https://docs.microsoft.com/en-us/dotnet/api/?term=GC

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: win 10
 - Browser: chrome

**Comment by mairaw** [comment]
@Sampy do you have a minimum of 3 letters for the API browser search?

**Comment by Sampy** [comment]
Yes. You do need to use at least 3 letters but if you are looking for items in a two letter class name you can also type a . after GC and get results that way.

**Comment by sillyousu** [comment]
@Sampy 
Thank you for your workaround. 

I think lifting 'at least 3 letters` restriction for some well-known terms like GC/IO  would provide better experience. 
But I'm OK with your workaround.
So closing.
