### ISSUE TITLE
Is there any example of HttpSendHttpResponse usage of the HTTP_SEND_RESPONSE_FLAG_OPAQUE flag?

### ISSUE THREAD

**Issue by luyaok** [MicrosoftDocs/feedback#1274]
**Link to article:**
https://docs.microsoft.com/en-us/windows/desktop/api/http/nf-http-httpsendhttpresponse

**Problem:**
I am using HttpSendHttpResponse() with the HTTP_SEND_RESPONSE_FLAG_OPAQUE flag, as proposed by Microsoft (only with 101 response status and response headers prepared using the WebSocketBeginServerHandshake() function), but I receive an ERROR_INVALID_PARAMETER error. 

Is there an example of how to use this flag correctly?

The document says that "HttpSendHttpResponse returns ERROR_INVALID_PARAMETER for all other HTTP response types if HTTP_SEND_RESPONSE_FLAG_OPAQUE flag is used." So  it is expected. But I found the way to use HTTP_SEND_RESPONSE_FLAG_OPAQUE flag correctly: it has to be used in conjunction with HTTP_SEND_RESPONSE_FLAG_MORE_DATA flag. Then ERROR_INVALID_PARAMETER error disappears. 

Does the document need to update to mention this?

Related issue: https://stackoverflow.com/questions/54768214/is-there-any-example-of-httpsendhttpresponse-usage-of-the-http-send-response-fla

**Comment by ryanmajidi** [comment]
@GrantMeStrength Can you please take a look at this issue?

**Comment by GrantMeStrength** [comment]
Hi - I'm sorry it has taken us so long to get to this issue. I see the issue has been resolved with an answer of StackOverflow.
