### ISSUE TITLE
OpenMutex hyper link redirects to a 404

### ISSUE THREAD

**Issue by kushal171** [MicrosoftDocs/feedback#1275]
https://docs.microsoft.com/en-us/windows/desktop/api/synchapi/nf-synchapi-releasemutex

The OpenMutex hyperlink takes me to a 404

**Comment by ryanmajidi** [comment]
@GrantMeStrength Can you please take a look at this issue?

**Comment by GrantMeStrength** [comment]
Now pointing to this one. 

https://docs.microsoft.com/en-us/windows/win32/api/synchapi/nf-synchapi-openmutexw

Will make a note to look for openmutexA and why it's missing..
