### ISSUE TITLE
wrong code snippet

### ISSUE THREAD

**Issue by mprevot** [MicrosoftDocs/feedback#1276]
**Describe the bug**
In the page:
https://docs.microsoft.com/en-us/windows/desktop/api/winioctl/ni-winioctl-ioctl_storage_protocol_command

in the code snippet, the following arg was in comment instead of being an argument
`lpInBuffer,      // input buffer`

**Comment by ryanmajidi** [comment]
@GrantMeStrength Can you please take a look at this issue?

**Comment by GrantMeStrength** [comment]
Thank you very much for taking the time to report this. The issue has been corrected.
