### ISSUE TITLE
Incorrect Phone Number

### ISSUE THREAD

**Issue by msmidorii** [MicrosoftDocs/feedback#1277]
On this page (Services Hub) https://serviceshub.microsoft.com/support/create/ 
When we select "Japan" in the country or region list, a wrong Phone numbers are displayed.

[Current/wrong Number for Unified Support Customer] : 0120-07-0196 /+81-120-07-0196
[Right Number for Unified Support Customer]:0120-82-0196 /+81-120-82-0196 

Please fix this.

**Comment by dendeli-msft** [comment]
Hi @msmidorii - because this issue is not related to docs.microsoft.com, we cannot address it in this forum.
