### ISSUE TITLE
Search results back arrow navigation link broken

### ISSUE THREAD

**Issue by sw23** [MicrosoftDocs/feedback#1279]
**Describe the bug**
Search results back arrow navigation broken

**To Reproduce**
1. Start on this page: [Python - Update Package Version](https://docs.microsoft.com/en-us/rest/api/azure/devops/artifactspackagetypes/python/update%20package%20version?view=azure-devops-rest-5.0)
2. In the filter box that says 'Filter by title', type 'promote'
    Filter shows:
> No results for promote
> [Search for "promote" in all REST documentation](https://docs.microsoft.com/search/index?search=promote&scope=REST)

3. Click the `2` navigation link to visit search results page 2
4. Click the `<-` navigation link to go back to page 1
    Page Displays:
> 0 Search results for "promote"
> No results

The URL seems to get corrupted causing the problem, as it ends up as:
https://docs.microsoft.com/en-us/search/index?search=promote&scope=REST%20aria-label=
instead of:
https://docs.microsoft.com/en-us/search/index?search=promote&scope=REST

**Expected behavior**
Should show the same data as [page 1](https://docs.microsoft.com/en-us/search/index?search=promote&scope=REST):

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Microsoft Edge

**Comment by dendeli-msft** [comment]
Thank you for the feedback, @sw23 - this should now be addressed.

Den Delimarsky ● Senior PM, docs.microsoft.com ● [@DennisCode](https://twitter.com/DennisCode)
