### ISSUE TITLE
Add extra docs for InkToolbarPenButton.Palette

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#129]
There is no docs to know what are the brushes contained in IList<Brush>.

Value
IList<Brush> 
A collection of Brush objects that describe various properties of the ink stroke. The default is 0 (empty).

----------
⚠ Idea migrated from UserVoice

**Created By:** Carlos
**Created On:** 2017/07/18 18:59:40 +0000
**Votes at Migration:** 1
**Supporters at Migration:** 1

**Comment by dend** [comment]
@mijacobs @kevinyr - FYI on the request.

**Comment by Powerhelmsman** [comment]
@ginami @laurenhughes Can you take a loot at this.

**Comment by ginami** [comment]
@jwmsft, can you please address this question for https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.inktoolbarpenbutton.palette?

**Comment by jwmsft** [comment]
@Karl-Bridge-Microsoft, this is yours. Thanks

**Comment by Powerhelmsman** [comment]
@Karl-Bridge-Microsoft Is there any updates?

**Comment by Karl-Bridge-Microsoft** [comment]
The Brush object topic that describes the valid brushes is linked directly from the sentence you copied from the Property value description.

**Comment by Powerhelmsman** [comment]
Close as resolved.
