### ISSUE TITLE
Inversion between Close and Stop on HttpListener

### ISSUE THREAD

**Issue by klettier** [MicrosoftDocs/feedback#1290]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

**Link to article:**
https://docs.microsoft.com/en-us/dotnet/api/system.net.httplistener.close?view=netframework-4.7.2
https://docs.microsoft.com/en-us/dotnet/api/system.net.httplistener.stop?view=netframework-4.7.2

**Problem:**
The **Stop** article demonstrate the **Close method call** and the **Close** article demonstrate the **Stop method call**

**Comment by mairaw** [comment]
Thank you @klettier. I've opened the following PR to fix this: https://github.com/dotnet/dotnet-api-docs/pull/2243

**Comment by mairaw** [comment]
@sudeepku @dendeli-msft can you please close this? I don't have permissions.
