### ISSUE TITLE
Missing words in System.Collections.Concurrent description

### ISSUE THREAD

**Issue by kaimikael** [MicrosoftDocs/feedback#1291]
In https://docs.microsoft.com/en-us/dotnet/api/index?view=netframework-4.7.2 the description for System.Collections.Concurrent says ”…should be used in place of the corresponding types in the and namespaces…”.
This should be “…should be used in place of the corresponding types in the System.Collections and System.Collections.Generic namespaces…”

**Comment by dendeli-msft** [comment]
Duplicate of #637
