### ISSUE TITLE
Spelling Mistake

### ISSUE THREAD

**Issue by sanghvikeyur** [MicrosoftDocs/feedback#1293]
**Link to article:**
https://docs.microsoft.com/en-us/aspnet/#pivot=aspnet

**Problem:**
In Real-time section, spelling of Learn is misspelled to Lean.

**Comment by Rick-Anderson** [comment]
@terrimorton can you fix this?

**Comment by terrimorton** [comment]
I've fixed the typo at https://github.com/aspnet/Docs/blob/master/aspnet/index.md and submitted a PR.

**Comment by Rick-Anderson** [comment]
@dendeli-msft  please close

**Comment by Rick-Anderson** [comment]
Thanks @terrimorton

**Comment by terrimorton** [comment]
@Rick-Anderson This issue was resolved and should be closed.

**Comment by Rick-Anderson** [comment]
@alligreubel  do you know who can close this?

**Comment by superfon** [comment]
> 

- [ ] 

- ### 

> ;,>      #1150 
>^^}} 

- [ ] 

- 

> ``
