### ISSUE TITLE
A button to hide sidebar in code example pages

### ISSUE THREAD

**Issue by ward-mattar** [MicrosoftDocs/feedback#1296]
**UI improvement for better code viewing experience on smaller screens**
Sidebar uses screen realstate when viewing code examples that can be better used to view the code in it, for example: [Multithreaded pipe server](https://docs.microsoft.com/en-us/windows/desktop/ipc/multithreaded-pipe-server). 

**A button for hiding the sidebar**
It would be nice to have a button for hiding/showing the sidebar content.

**Comment by dendeli-msft** [comment]
Thank you for the feedback! I've opened an internal issue for us to track.

At this time, we have no concrete timelines or commitments for this change, however we'll make sure that we do our due diligence in assessing the impact and importance of the feature.
