### ISSUE TITLE
Incorrect link for UpdateAssessment structure

### ISSUE THREAD

**Issue by williamklee** [MicrosoftDocs/feedback#1298]
https://docs.microsoft.com/en-us/windows/desktop/sysinfo/update-assessor-structures

On this page, both of the links to the structure descriptions take you to the OSUpdateAssessment structure, but the second one should actually be taking you to this page: https://docs.microsoft.com/en-us/windows/desktop/api/waasapitypes/ns-waasapitypes-tagupdateassessment

**Comment by ryanmajidi** [comment]
@GrantMeStrength Can you please take a look at this issue?

**Comment by GrantMeStrength** [comment]
Now fixed.
