### ISSUE TITLE
WMI MSFT_Disk Location returns strange/undocumented value

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#13]
Described here https://social.technet.microsoft.com/Forums/en-US/90ecb9da-0d94-4f16-a2ef-fe6270a78fe7/wmi-msftdisk-location-returns-strange-value?forum=ITCG

----------
⚠ Idea migrated from UserVoice

**Created By:** Alex P
**Created On:** 2018/03/01 18:22:25 +0000
**Votes at Migration:** 1
**Supporters at Migration:** 1

**Comment by Powerhelmsman** [comment]
This channel is for docs site feedback instead of solving general windows hardware issue. Please try to ask the question in MSDN forum.
