### ISSUE TITLE
Custom PDF based on TOC filters

### ISSUE THREAD

**Issue by docs-product** [MicrosoftDocs/feedback#131]
Certainly, Docs.Microsoft.com is a great things. Because of this I want more: I would like to use Download PDF after applying a filter. Now, it will download PDF without considering applied filter.
For example, I wanted to get PDF for Azure CosmosDB DocumentDB only. I applied filter "DocumentDB", it shows everything just for DocumentDB topics, but downloads entire CosmosDB with 882 pages.

----------
⚠ Idea migrated from UserVoice

**Created By:** Victor
**Created On:** 2017/06/23 14:39:37 +0000
**Votes at Migration:** 1
**Supporters at Migration:** 1

**Comment by dend** [comment]
@dastaffo as the PM picking up PDF work.

**Comment by dastaffo** [comment]
Adding @cillroy here.

**Comment by docs-product** [comment]
At this time, we do not have plans to amend how PDF files are generated.
