### ISSUE TITLE
ImmutableList<T> should documented performance

### ISSUE THREAD

**Issue by briangithex** [MicrosoftDocs/feedback#1311]
**Link to article:**
https://docs.microsoft.com/en-us/dotnet/api/system.collections.immutable.immutablelist-1?view=netcore-2.2

**Problem:**
ImmutableList<T> should have documented performance guarantees for the Item and Add operations.  Note that this information is already formulated in the remarks section of https://docs.microsoft.com/en-us/dotnet/api/system.collections.immutable.immutablearray-1#remarks , so documenting these guarantees will not add new constraints on development of this class.

**Comment by rootsmusic** [comment]
@briangithex Please move this issue to https://github.com/dotnet/dotnet-api-docs/issues

**Comment by briangithex** [comment]
> @briangithex Please move this issue to https://github.com/dotnet/dotnet-api-docs/issues

OK, moved to https://github.com/dotnet/dotnet-api-docs/issues/6958

**Comment by Jasonizback** [comment]
Thanks alot for your help
