### ISSUE TITLE
Error retrieving subscriptions on Sandbox

### ISSUE THREAD

**Issue by andrewhorwood** [MicrosoftDocs/feedback#1312]
**Describe the bug**
When I create a new sandbox I receive the following errors:

Error retrieving subscriptions
There was an error retrieving subscriptions. Please reload the portal to try again.

No subscriptions
You do not have any Azure subscriptions in the learn.docs.microsoft.com directory. Click here to switch to another directory.

**To Reproduce**
1. Create new sandbox
2. Login to sandbox
3. Error appears in azure, unable to complete any learning

**Screenshots**

![image](https://user-images.githubusercontent.com/16756368/54756624-89e8be80-4be0-11e9-9712-b9fafb73f5c1.png)

**Additional context**
I have tried in different browsers / machines / In private Browsing and cache cleared

**Comment by srikanthnd** [comment]
I get the same error now as well

![image](https://user-images.githubusercontent.com/9609176/68182621-2312ec80-ff9a-11e9-85af-46bc395d79c1.png)

Was there a fix for this issue?

**Comment by andrewhorwood** [comment]
@srikanthnd this issue fixed itself over time. I left and returned in 2 weeks and it worked

**Comment by srikanthnd** [comment]
For some reason the sandbox gets corrupted. It started working after 3 days. Not sure if I had to leave it idle to get itself back working again.  But sometimes it can be annoying while following the learning path.

**Comment by isiaq** [comment]
Hello I got the same error. Is there a way to fix. I have been on this for more than 3 days now.
https://drive.google.com/file/d/1Kw9L5RqE8h3IlX9748z2THE-f9iZq98y/view?usp=sharing
