### ISSUE TITLE
Azure Data Lake gen2 APIs - HTTPS

### ISSUE THREAD

**Issue by frvigano** [MicrosoftDocs/feedback#1314]
**Describe the bug**

APIs are defined with HTTP instead of HTTPS
https://docs.microsoft.com/en-us/rest/api/storageservices/datalakestoragegen2/filesystem

This is even kept at the time of testing the APIs as in this page

https://docs.microsoft.com/en-us/rest/api/storageservices/datalakestoragegen2/filesystem/getproperties

**To Reproduce**
1. Go to https://docs.microsoft.com/en-us/rest/api/storageservices/datalakestoragegen2/filesystem/getproperties
2. Click on Try It 
3. Try to configure the call to the API: http is kept (and current call does not raise an error nor does show any result)

**Expected behavior**
HTTP => HTTPS (I had two customers esperiencing issues on this)

**Comment by sudeepku** [comment]
Hi @frvigano , thanks for your feedback. I have opened this issue in the relevant repo. 
https://github.com/Azure/azure-docs-rest-apis/issues/2344
