### ISSUE TITLE
DLP Policy - Client Error

### ISSUE THREAD

**Issue by yoer1** [MicrosoftDocs/feedback#1316]
Can anyone please help me with this kind of error in DLP.. I can't edit the policy settings and I also tried to do this in 3 different tenant. Same result, is this a bug? Please see error below. Thank You in advance.

1. Go to 'https://protection.office.com/?rfr=AdminCenter#/datalossprevention'
2. Click on 'Exisiting DLP Policy'
3. Click on 'Edit'
4. Once editing is done, please see error below

Client Error
Your request couldn't be completed. Please try again, and if the problem persists, contact your administrator.

Request: /api/policy?policyType=Dlp
Status code: 500
Exception message: {"Message":"The DlpComplianceManagementRule type entity does not have the following type command: Update.\r\nParameter name: entityMetadata","DiagnosticContext":"{Version:16.00.2927.001,Environment:EASPROD,DeploymentId:3c31d0adf8964fe5bc51a71de288012e,InstanceId:WebRole_IN_1,SID:63636797-82c2-423f-aa42-fff6e66f129c,CID:99dc3b0e-764a-40bd-9823-ab0da631dcd1}","Time":"2019-03-22T02:42:08.1987091Z","ExceptionType":"System.ArgumentException"}
Diagnostic information: **{Version:16.00.2927.001,Environment:EASPROD,DeploymentId:3c31d0adf8964fe5bc51a71de288012e,InstanceId:WebRole_IN_0,SID:63636797-82c2-423f-aa42-fff6e66f129c,CID:1080593c-9894-4202-b6f9-d11fd0b2abc8}
Time: 2019-03-22T02:42:06.618Z
![Error Msg](https://user-images.githubusercontent.com/48461407/54797523-70eb1680-4c8f-11e9-8f04-97a51d0e92c9.JPG)
![Error Msg](https://user-images.githubusercontent.com/48461407/54797533-7a747e80-4c8f-11e9-81f2-3fb39fa1de02.JPG)

**Comment by sudeepku** [comment]
Hi @yoer1 . Thanks for reaching out to us with your question. I have created an issue in the correct repo.
https://github.com/MicrosoftDocs/OfficeDocs-o365seccomp/issues/532
