### ISSUE TITLE
Cannot Modify Intune Managed Device's Device Category with `deviceCategoryDisplayName`

### ISSUE THREAD

**Issue by nayuta** [MicrosoftDocs/feedback#1317]
At Microsoft Graph API reference, to update Intune managed device's device category, it is specified to use `deviceCategoryDisplayName`. However, it would be failed. We must use @odata.id of Device Category.

https://docs.microsoft.com/en-us/graph/api/intune-devices-manageddevice-update?view=graph-rest-1.0

In this article, at `Request body` -> `deviceCategoryDisplayName`, value type is `String`. At `Example`, the value is a sample string, `"Device Category Display Name value"`. But, to change this property with a string value, we would be got failed.

To change this property, we need to specify @odata.id. Key are not `deviceCategory`, and not `deviceCategoryDisplayName`. Like

```
{ "@odata.id": "https://graph.microsoft.com/beta/deviceManagement/deviceCategories/<device category id>" }
```

Not like

```
{ "deviceCategoryDisplayName":  "Device Category Display Name value" }
```

And not

```
{ "deviceCategory":  { "@odata.id": "https://graph.microsoft.com/beta/deviceManagement/deviceCategories/<device category id>" } }
```

Besides, when we succeeded to update, we will get `204`.

I did not try to update it with other property. Perhaps, we cannot update this value with other values.

See it: https://techcommunity.microsoft.com/t5/Microsoft-Intune/Update-Intune-Managed-Device-Category-with-Microsoft-Graph-were/m-p/324334

**Comment by sudeepku** [comment]
@nayuta - thanks for your feedback. Transferred this issue to the correct repo.
https://github.com/microsoftgraph/microsoft-graph-docs/issues/4306

**Comment by goodman-react** [comment]
Hi. @nayuta 
I tried as your way and get response 204.
But "deviceCategoryDisplayName" field was not updated.
Where can I see the updated value?

**Comment by nayuta** [comment]
@goodman-react Hi, this repository is for document feedback. Check https://techcommunity.microsoft.com/t5/microsoft-intune/update-intune-managed-device-category-with-microsoft-graph-were/m-p/324334
