### ISSUE TITLE
Code does not have correct font size in titles

### ISSUE THREAD

**Issue by fghzxm** [MicrosoftDocs/feedback#1321]
**Describe the bug**
If an article's title contains `code`, the code portion is not rendered in title font size, rather in contents font size.

**To Reproduce**
Visit https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-7.3/indexing-movable-fixed-fields ([as of 3/24/2019 UTC](https://web.archive.org/web/20190324021021/https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-7.3/indexing-movable-fixed-fields)).

**Expected behavior**
"**`fixed`**" has big, title font size.

**Observed behavior**
"**`fixed`**" has small, contents font size.

**Screenshot**
![microsoft-docs-bug](https://user-images.githubusercontent.com/32954258/54874146-7d52a900-4e20-11e9-91d9-6342a2f20d35.png)

**Desktop**
 - OS: Windows
 - Browser: Edge
 - Version: EdgeHTML 18.18361

**Comment by sudeepku** [comment]
Thanks @fghzxm for reporting this issue. I have opened a linked issue https://github.com/dotnet/csharplang/issues/2386 in the correct repository.

**Comment by fghzxm** [comment]
I believe this issue reflects a bug in docs.microsoft.com's Markdown rendering, not errors in a specific Microsoft product documentation.  Please re-open this thread and close dotnet/csharplang#2386.  Also do not open an issue on dotnet/docs.

**Comment by mairaw** [comment]
Just to close the loop here. @fghzxm you're right that this was the right place to open this issue. 

@sudeepku if you can reopen this one, I can then close the one that was later opened on dotnet/docs.

But I managed to get ahold of the dev team internally and we do have an internal work item tracking this fix: https://ceapex.visualstudio.com/Engineering/_workitems/edit/79880.
