### ISSUE TITLE
Documentation for Socket.Receive(Byte[], Int32, Int32, SocketFlags, SocketError)  is lacking specific details w.r.t exceptions

### ISSUE THREAD

**Issue by mfrischknecht** [MicrosoftDocs/feedback#1322]
**Link to article:**
cf. [Socket.Receive(Byte[], Int32, Int32, SocketFlags, out SocketError)](https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.socket.receive?view=netframework-4.7.2#System_Net_Sockets_Socket_Receive_System_Byte___System_Int32_System_Int32_System_Net_Sockets_SocketFlags_System_Net_Sockets_SocketError__)

**Problem:**
The specific overload of `Socket.Receive(...)` returning a `SocketError` via an `out` parameter seems useful in order to explicitly avoid exceptions in a tight loop. Unfortunately, the documentation of this specific overload seems to have been copied and pasted from another, similar overload. The section thus still references `SocketException`s but doesn't mention whether they actually still might occur (and if so, in which edge cases this might be the case).

On a similar note, an overview which `SocketError` codes exactly are to be expected in which cases would be very useful. I encountered a case where said method would return `SocketError.IOPending`, although the socket was used in a purely synchronous fashion on a separate thread. Sadly, most documentation on the topic describes the lower level C API and there is no obvious way to tell which parts of it apply to its managed counterparts and which ones don't.

**Comment by mairaw** [comment]
This issue was moved to dotnet/dotnet-api-docs#3693
