### ISSUE TITLE
Incorrect typedef for DXGI_SWAP_EFFECT

### ISSUE THREAD

**Issue by sagian2005** [MicrosoftDocs/feedback#1324]
**Link to article:**
https://docs.microsoft.com/en-us/windows/desktop/api/DXGI/ne-dxgi-dxgi_swap_effect

**Problem 1**
**_Artcle Reads:_**
```
typedef enum DXGI_SWAP_EFFECT {
   DXGI_SWAP_EFFECT_DISCARD,
   DXGI_SWAP_EFFECT_SEQUENTIAL,
   DXGI_SWAP_EFFECT_FLIP_SEQUENTIAL,
   DXGI_SWAP_EFFECT_FLIP_DISCARD
} ;
```

**_Should Read (per dxgi.h):_**
```
typedef enum DXGI_SWAP_EFFECT {
   DXGI_SWAP_EFFECT_DISCARD = 0,
   DXGI_SWAP_EFFECT_SEQUENTIAL = 1,
   DXGI_SWAP_EFFECT_FLIP_SEQUENTIAL = 3,
   DXGI_SWAP_EFFECT_FLIP_DISCARD = 4
} DXGI_SWAP_EFFECT;
```

**i.e. enumeration is NOT sequential from '0'**

**Problem 2 : 🛑 IMPORTANT** There is no "comment section" available in this article.

**Comment by drewbatgit** [comment]
Hello, thank you for the feedback. This syntax block is autogenerated from the header by our content build system. We are tracking a feature request to add enumeration numerical values to the syntax block. Unfortunately, this can't be updated manually at this time and must wait for the engineering fix.

**Comment by sagian2005** [comment]
If an enum syntax block is going to be presented, copying the enum values from the header seems like it ought to be a given, not to mention necessary for the online documentation to even be considered useful; otherwise, the enums should just be shown without an enum block.  It's misleading.  Let me know if the engineering department needs assistance.  :-)

**Comment by sagian2005** [comment]
So... 2 years and 4 months later the docs are still wrong.

**Comment by drewbatgit** [comment]
Hi there. I'm sorry this has taken so long, but believe it or not, this engineering update to the docs is coming soon! I just checked the internal work item, and the fix is checked into a branch and is in the final testing / deployment phase. I expect you will see it live on the site in the next month or so.

**Comment by sagian2005** [comment]
That's exciting to hear.  The online docs are a disaster right now.  Please leave this issue open until it actually happens.

**Comment by sagian2005** [comment]
There are still many, **many** issues in the documentation where the presented '**typedef enum**' is not explicitly enumerated.  The way it's presents implies that the enumeration starts at default '0', which it does not.  Examples are: D3D11_MAP,  D3D11_BIND_FLAG, D3D11_CPU_ACCESS_FLAG... there are undoubtedly hundreds of other entries like this.

**_This is now a three-year-old problem_**.  It is **very** disappointing that we cannot depend on the documentation to be accurate after a three-year opportunity to fix it.

The on-line documentation faces **millions** of users.  It **must** be accurate.

We would like to know what steps we need to take to escalate this issue.
