### ISSUE TITLE
Dates are in the wrong format

### ISSUE THREAD

**Issue by PeterWone** [MicrosoftDocs/feedback#1326]
ms.date is rendered in American format. 

This is the wrong format for the other sixty English speaking countries. 

If it's too hard to detect the user's locale and render in-browser then the next best option would be either standards compliance (ISO 8601) or using the format preferred by the largest English speaking nation, which is India. They use ISO 8601 format.

**Comment by sudeepku** [comment]
@PeterWone - thanks for your feedback. You can change the language/locale setting by clicking the link in the footer. It should render the date correctly in your preferred locale.
![image](https://user-images.githubusercontent.com/16726119/55427017-f5188600-553a-11e9-8868-f24fb31d19c8.png)

**Comment by RussKie** [comment]
@sudeepku coming from https://github.com/dotnet/docs/issues/14492 it took me awhile to realise I had to actually scroll **all the way down the page** to find the language settings.
It is an accessibility issue.

**Comment by mairaw** [comment]
Pinging @docs-product to review this issue again.
