### ISSUE TITLE
Azure student portal. Fraud I finished education 7 years ago. rhow2010@mail.phoenix.edu is my classroom email address unused since 2012

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/feedback#1327]

**Comment by rhow2010** [comment]
To verify, Twitter copyright violation case. linkedin copyright violation, Microsoft alert#, You Tube branded our sites, Apple security and Philsing, ITA Government privacy shield case. HUD stalking and disability prejudged by manager. Falsifying private accounts as media. 23 miles away, I hear everything.
