### ISSUE TITLE
Make clear that computerName can be used for the FQDN as well

### ISSUE THREAD

**Issue by malachma** [MicrosoftDocs/feedback#1328]
**Link to article:**
https://docs.microsoft.com/en-us/rest/api/compute/virtualmachines/createorupdate#osprofile

**Problem:**
Please extend the docu with the Information that the property "computerName" Can be also used to set the FQDN at creation time. This Information is not directly visible

**Comment by sudeepku** [comment]
@malachma  thanks for your feedback. I have opened a new issue in the relevant repo and linked this issue.
