### ISSUE TITLE
include Yammer link in the (select text, right-click) sharing options

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#133]
Add Yammer to the list of share options (which are available after right-click, 

----------
⚠ Idea migrated from UserVoice

**Created By:** NaRob
**Created On:** 2017/06/21 16:33:18 +0000
**Votes at Migration:** 1
**Supporters at Migration:** 1

**Comment by Powerhelmsman** [comment]
Thanks for the suggestion! Based on the low vote count in the last year, we do not plan on doing this now, but will revisit if it comes up again.
