### ISSUE TITLE
Get-MSOLDomain has an error in Example #2

### ISSUE THREAD

**Issue by marcuslongridge** [MicrosoftDocs/feedback#1330]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

**Link to article:**
https://docs.microsoft.com/en-us/powershell/module/msonline/get-msoldomain?view=azureadps-1.0

**Problem:**
What's wrong with the article?
Example # 2 should read "Get-MsolDomain -Domainname "contoso.com"" Instead of "Get-MsolDomain -Name "contoso.com""

**Comment by sudeepku** [comment]
@marcuslongridge thanks for your feedback. I have transferred (re-created) this issue  in the relevant repo.
https://github.com/Azure/azure-docs-powershell-azuread/issues/280
