### ISSUE TITLE
D3D12_DESCRIPTOR_RANGE structure content has incorrect text

### ISSUE THREAD

**Issue by clandrew** [MicrosoftDocs/feedback#1331]
**Link to article:**
https://docs.microsoft.com/en-us/windows/desktop/api/d3d12/ns-d3d12-d3d12_descriptor_range

**Problem:**
Under the parameter information for "OffsetInDescriptorsFromTableStart", it says
"The offset in descriptors from the start of the root signature"

This is wrong / doesn't make sense. 

It would be better for it to say something like
"The offset in descriptors, from the start of the table. That is, the descriptor table which was set as the root argument value for this parameter slot."

**Comment by drewbatgit** [comment]
The recommended update has been made to the article.

**Comment by clandrew** [comment]
Perfect!! Thank you!

**Comment by clandrew** [comment]
@drewbatgit, could you please link me the PR which fixed it? I want to find out how to make similar doc changes myself going forward.

**Comment by drewbatgit** [comment]
Sure. Here you go: https://cpubwin.visualstudio.com/win32/_git/sdk-api/pullrequest/15053?_a=overview

**Comment by clandrew** [comment]
@drewbatgit Thanks :)
