### ISSUE TITLE
LOST SITE: https://docs.microsoft.com/en-us/cpp/build/unwind-data-for-exception-handling-debugger-support

### ISSUE THREAD

**Issue by pgyzhu** [MicrosoftDocs/feedback#1333]
**Describe the bug**
website "https://docs.microsoft.com/en-us/cpp/build/unwind-data-for-exception-handling-debugger-support" is lost

**To Reproduce**
1. goto https://docs.microsoft.com/en-us/cpp/build/unwind-data-for-exception-handling-debugger-support
2. See error

**Expected behavior**
404

**Desktop (please complete the following information):**
 - OS:windows 7 x64
 - Browser chrome

**Comment by sudeepku** [comment]
@pgyzhu thanks for reporting this issue. I have moved the issue to the correct repository.
https://github.com/MicrosoftDocs/cpp-docs/issues/907
