### ISSUE TITLE
Windows Subsystem for Linux content is not on the Home Page

### ISSUE THREAD

**Issue by SamuelEnglard** [MicrosoftDocs/feedback#1335]
On the docs.microsoft.com homepage WSL is not listed making it hard to find. I more often than not end up having to use a search.

**Comment by GrantMeStrength** [comment]
Unfortunately we can't put a link to everything we would like to on the front page. We do however have plans to update the home page AND add more details on using WSL in specific scenarios in the very near future. The good news is that there is a shortcut you can use in the meantime: aka.ms/wsl

**Comment by SamuelEnglard** [comment]
While I get the space limits, there should be some kind of directory or list of all "top level" content.

Also, that link goes to the uservoice page, not docs
