### ISSUE TITLE
Broken link: "I smell a parameter!"

### ISSUE THREAD

**Issue by tgspacelabs** [MicrosoftDocs/feedback#1348]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

**Link to article:**
Tell us where exactly a problem occurs.
**[ALTER DATABASE SCOPED CONFIGURATION (Transact-SQL)](https://docs.microsoft.com/en-us/sql/t-sql/statements/alter-database-scoped-configuration-transact-sql?view=sql-server-2017)**

**Problem:**
What's wrong with the article?
**Broken link: "I smell a parameter!"**

**Comment by rootsmusic** [comment]
Fixed.
#please-close
