### ISSUE TITLE
Wrong Library and DLL Reference in MFCreateAVIMediaSink

### ISSUE THREAD

**Issue by Drake-Wu** [MicrosoftDocs/feedback#1349]
**Describe the bug**
The Library and DLL Reference are wrong in [MFCreateAVIMediaSink](https://docs.microsoft.com/en-us/windows/desktop/api/mfidl/nf-mfidl-mfcreateavimediasink):
The symbol is actually located in mfsrcsnk.dll but not mf.dll

**Comment by ryanmajidi** [comment]
@GrantMeStrength Can you please take a look at this issue?

**Comment by drewbatgit** [comment]
Thanks for reporting this issue. I've verified that the API is in mfsrcsnk.dll and I've updated the docs. You should see the update on the live site within 24 hours.
