### ISSUE TITLE
Make the methods inherited from object and from base classes more visible.

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#135]
Just group them by inherited from object, inherited from base and others.

----------
⚠ Idea migrated from UserVoice

**Created By:** Lyubomir Parvanov
**Created On:** 2017/06/16 17:21:52 +0000
**Votes at Migration:** 3
**Supporters at Migration:** 3

**Comment by ulln** [comment]
This applies to all inherited members (methods, properties, events, ...)
I would prefer to make them somewhat less visible by separating them from the actual members of the type.

**Comment by dend** [comment]
Duplicate of #581
