### ISSUE TITLE
Content Issue in NetUserGetLocalGroups Function Doc

### ISSUE THREAD

**Issue by BESTRIVENinCN** [MicrosoftDocs/feedback#1351]
**Link to article:**
https://docs.microsoft.com/en-us/windows/desktop/api/lmaccess/nf-lmaccess-netusergetlocalgroups.

**Problem:**
In Parameters description of **username**: "DomainName<i>UserName ", "<i>" is the text format of italic type, and it should not be displayed.

**Comment by ryanmajidi** [comment]
@GrantMeStrength Can you please take a look at this issue?

**Comment by GrantMeStrength** [comment]
Turns out we were rendering slashes incorrectly in many places. Thanks for the heads up! Changes on the way.
