### ISSUE TITLE
Wrong url Github link in Azure Active Directory v2.0 authentication libraries

### ISSUE THREAD

**Issue by panververis** [MicrosoftDocs/feedback#1357]
**Link to article:**
https://docs.microsoft.com/en-us/azure/active-directory/develop/reference-v2-libraries#microsoft-supported-client-libraries

**Problem:**
The link that is supposed to redirect the user to the MSAL.js github page, is instead redirecting the user to the MSAL angularJs page (https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angularjs/README.md)

**Comment by rootsmusic** [comment]
Fixed.
#please-close
