### ISSUE TITLE
Allow doc search by service in the filter box

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#136]
The filter box replaced the search box in the old ACOM documentation, but the filter box only filters by article title. I want to be able to search the contents of the articles for the service I'm viewing using that box.

----------
⚠ Idea migrated from UserVoice

**Created By:** Nicole Berdy
**Created On:** 2017/06/12 21:18:39 +0000
**Votes at Migration:** 2
**Supporters at Migration:** 2

**Comment by dend** [comment]
Duplicate of #148
