### ISSUE TITLE
Machine learning tutorial link not working

### ISSUE THREAD

**Issue by pintedani** [MicrosoftDocs/feedback#1369]
Machine learning tutorial link not working:

When completing the first tutorial, you are redirected to the following link, by pressing the button ML.NET Tutorials

https://dotnet.microsoft.com/learn/machinelearning-ai/ml-dotnet-get-started-tutorial/next

Invalid link:
https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/

**Comment by ryanmajidi** [comment]
@pintedani Looks to be fixed now. If you are still having problems please open a new issue.
