### ISSUE TITLE
Grammatical error in the .NET license document

### ISSUE THREAD

**Issue by ethansudman** [MicrosoftDocs/feedback#1370]
The [.NET License document](https://dotnet.microsoft.com/dotnet_library_license.htm) has a grammatical issue. The following sentence is incorrect:
"You may install and use any number of copies of the software to design, develop and test you’re applications."

"You're" is a contraction of "you are." This should be "your" instead.

**Comment by ryanmajidi** [comment]
@ethansudman thank you for this feedback. The spelling has since been fixed.
