### ISSUE TITLE
Please move the link to change the language to the top.

### ISSUE THREAD

**Issue by DajyarekunSoftware** [MicrosoftDocs/feedback#1372]
I am using Japanese as my native language.
The default language is "English (United States)".
In order to change the language I have to move to the bottom.
Please move the link to change the language to the top.
This is all Microsoft settings.
Be aware of usability outside your home country.

**Comment by ryanmajidi** [comment]
@DajyarekunSoftware thank you for this feedback. This has been added to our internal ticketing system.
