### ISSUE TITLE
Sharing of Badges & Trophies 

### ISSUE THREAD

**Issue by rajmak67** [MicrosoftDocs/feedback#1373]
**Describe the bug**
When I try to Share my Microsoft Learn Badge or Trophy from my profile page via LinkedIn or via email, the course information and link is getting shared but the fact that I've earned a badge or Trophy is not getting shared.
This seems very odd

**Comment by mellondongit** [comment]
Yes I have the same problem. A general link to the learning path, but nothing to indicate I completed it, which defeats the purpose.

**Comment by frederikpedersen** [comment]
Same problem. Would make sense if purpose was to push the certification exams, but since it seems to encourage sharing I really should provide some details as to whether one has actually completed the training course?

**Comment by mrdrwest** [comment]
Sharing Microsoft Learn trophies and badges results in an embedded link to the learning path or module, not the achievement.

Please address this quick-fast-and-in-a-hurry!

**Comment by jialge** [comment]
Thank you for the feedback.  We have been discussing this inside the team recently.   We will revisit this behavior when we bring in certification badges later this year.   For certification badges, we definitely want to have a page that shows 'You' earned it.   It will be the perfect timing for us to redesign the entire badge sharing behavior.

**Comment by ennisa-ire** [comment]
hi folks has this been addressed?

**Comment by mellondongit** [comment]
You know what.... I commented originally here after I'd done a few learning paths at the very beginning of learning Azure. I didn't realise at that point just how many of them I would be doing, and labs, before getting the certification. So I wouldn't suggest sharing at this level to LinkedIn - it's too much white noise, and it doesn't look professional. I think best to leave it until you have the certification, and then share that on LinkedIn (that is supported).

**Comment by ennisa-ire** [comment]
I hear you loud and clear, at the same time a learning path, is something you should be able to demonstrate.
