### ISSUE TITLE
404 Page Not Found - SCCM PowerShell Module

### ISSUE THREAD

**Issue by EmmanuelDefranc** [MicrosoftDocs/feedback#1374]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

**Link to article:**
https://docs.microsoft.com/en-us/powershell/module/configurationmanager/get-cmendpointprotectionpoint?view=sccm-ps

**Problem:**
The link to the Module (upper part of the document) directs to a non-existing page (404 error): https://docs.microsoft.com/en-us/powershell/module/configurationmanager/?view=sccm-ps

I have noticed that many PowerShell modules have the same behavior (cannot remember of other modules), perhaps it is a re-direction issue? (URL rewrite?)

**Comment by ryanmajidi** [comment]
@EmmanuelDefranc Thank you for bringing this to our attention. This has since been fixed.
