### ISSUE TITLE
Is it possible to make the documentation online be available only to certain group of people?

### ISSUE THREAD

**Issue by xiawang** [MicrosoftDocs/feedback#1376]
Currently our team is sending a pdf that contains our API documentation to all partners, since our project is still private right now. We think that maintaining a pdf is not as efficient as expected, for moving towards the MicrosoftDocs though, is it possible to make the documentation only available to certain group of people (such as our partners)?

**Comment by JasonWHowell** [comment]
Yes, it's a good idea. We are tracking the wishlist to share certain docs with certain users, in a private way. 

It's not ready though and may take a while longer.

Another common option besides sharing PDF is to create a Private Github repository, and save your .md markdown files into there, and grant read access to the Github users that you need to share with.  Github's site supports rendering .md files pretty nicely. 

Thanks, Jason

**Comment by JasonWHowell** [comment]
#please-close
