### ISSUE TITLE
Add extra step for specifying private IP for a public Application Gateway

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#138]
As per the documentation, creating a public facing is fine. However, adding a private IP step to support both simultaneously as per FAQ is missing in the documentation at https://docs.microsoft.com/en-us/azure/application-gateway/application-gateway-create-gateway-portal

----------
⚠ Idea migrated from UserVoice

**Created By:** I-van Leong
**Created On:** 2017/06/07 05:27:23 +0000
**Votes at Migration:** 1
**Supporters at Migration:** 1

**Comment by Powerhelmsman** [comment]
This issue is now tracked with https://github.com/MicrosoftDocs/azure-docs/issues/8477
