### ISSUE TITLE
broken href

### ISSUE THREAD

**Issue by lorangelmsft** [MicrosoftDocs/feedback#1380]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

**Link to article:**
Tell us where exactly a problem occurs.

**Problem:**
What's wrong with the article?

**Comment by lorangelmsft** [comment]
broken link on page 
https://docs.microsoft.com/en-us/previous-versions/tn-archive/cc751383(v=technet.10)
please replace <a class="x-hidden-focus" href="http://www.microsoft.com/security/msrc/report.aspx" data-linktype="external">report it</a>
with:
<a class="x-hidden-focus" href="https://msrc.microsoft.com/create-report" data-linktype="external">report it</a>

**Comment by ryanmajidi** [comment]
@lorangelmsft thank you for reporting this. We have fixed the link
