### ISSUE TITLE
.NET API Browser does not work in Internet Explorer

### ISSUE THREAD

**Issue by miloush** [MicrosoftDocs/feedback#1382]
See e.g. https://docs.microsoft.com/en-us/dotnet/api/?view=ml-dotnet in Internet Explorer.

Expected: Actual API reference

Actual: Only welcome to .NET API Browser paragraph

**Comment by ryanmajidi** [comment]
@miloush Thank you for bringing this to our attention. It looks like this was been corrected. Please open a new issue if you are still having problems.
