### ISSUE TITLE
Move my techprofile from my work account to my private account

### ISSUE THREAD

**Issue by w1mm3r** [MicrosoftDocs/feedback#1384]
I would like to move my techprofile from my work account to my private account.

I have not been able to find any way to create a support ticket in regards to microsoft learn / techprofile.
https://support.microsoft.com/en-us/contactus/
Did not give me any possibility to choose to contact microsoft docs / microsoft learn in any way.

So please direct me to some support and make https://support.microsoft.com/en-us/contactus/ direct people that way to.

**Comment by thomasdgillis** [comment]
I am having a similar issue, consolidating my school email account into my personal email account. I see that this is still open. Is there an update?

**Comment by w1mm3r** [comment]
Well I logged on with my work account and deleted the tech account associated.
go to https://techprofile.microsoft.com/en-us/edit
and delete account
