### ISSUE TITLE
Systen [sic] Center Previous Products tree view control

### ISSUE THREAD

**Issue by tofergus** [MicrosoftDocs/feedback#1386]
numerous typos in the menu (attached)
[https://docs.microsoft.com/en-us/previous-versions/system-center/](url)
[](![previous](https://user-images.githubusercontent.com/42045028/56154187-f196ed00-5f85-11e9-8552-1ea22c0d9bd7.png))

**Comment by ryanmajidi** [comment]
@tofergus Thank you for bringing this to my attention
