### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by PanosGeorgiadis** [MicrosoftDocs/feedback#1389]
**Link to article:**
https://docs.microsoft.com/en-us/windows/desktop/api/_automat/

**Problem:**
The link under "For programming guidance for this technology" is https://docs.microsoft.com/en-us/windows/desktop/api/_automat/ and does not work.

**Comment by ryanmajidi** [comment]
@GrantMeStrength Can you please take a look at this issue?

**Comment by GrantMeStrength** [comment]
Very old topic - did the best I could to avoid confusion with other automation tech.

**Comment by PanosGeorgiadis** [comment]
Hey @GrantMeStrength, there were no changes made on the help page and the link remains broken. Please fix. PS: what do you mean 'very old topic'? COM automation is still an active product.
