### ISSUE TITLE
Broken Link on Azure Migration Documentation

### ISSUE THREAD

**Issue by VikramPendse** [MicrosoftDocs/feedback#1390]
Documentation link broken (URL have "link:" keyword which makes redirect fail)

![image](https://user-images.githubusercontent.com/18698652/56196580-badbd800-6054-11e9-8441-21289abc2adc.png)

Steps to Reproduce -
Go to https://azure.microsoft.com/en-in/services/azure-migrate/
Scroll down and check "Resources" section
Click on "Documentation" link and it does not redirect (due to additonal "link:" word in URL)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [chrome]

**Comment by rootsmusic** [comment]
Fixed.
#please-close
