### ISSUE TITLE
Confusing comparison of Azure Migrate and 3rd Party Migration Tools

### ISSUE THREAD

**Issue by VikramPendse** [MicrosoftDocs/feedback#1391]
Source - Visit - https://azure.microsoft.com/en-in/migration/get-started/

Check section "Choose the right tools and partner for your cloud migration plan"

See the comparison Table -
![MigrationCompare](https://user-images.githubusercontent.com/18698652/56197335-3f7b2600-6056-11e9-8b6b-c1b3d5600ef1.png)

In one row it is mentioned Hyper-V is in Preview and in next row again Hyper-V is mentioned. Assessment of VMware mentioned twice. Is it the differentiation in any specific scenario? or its same information shared in both the rows. 

Also if the service is "Non Regional" in nature then why "Service Status" link is given in "Resources" again here at https://azure.microsoft.com/en-in/services/azure-migrate/

**Comment by ryanmajidi** [comment]
@VikramPendse thank you for bringing this to our attention. Doesn't look like this is still included in the current iteration.
