### ISSUE TITLE
Sign In Loop

### ISSUE THREAD

**Issue by FrankWhitePFE** [MicrosoftDocs/feedback#1392]
**Describe the bug**
When attempting to sign in at https://docs.microsoft.com/en-us/learn/ I am taken back to the page without signing in and without an error message.  This behavior is *slightly* different with incognito.  With incognito I'm actually taken to a sign in page.  But, after signing in (with either of my linked accounts), I have the same exact behavior.  The issue is not present on other docs sites.  The issue is not present on the MSFT learning site 'https://www.microsoft.com/en-us/learning/dashboard.aspx'.

**To Reproduce**
1. Go to 'https://docs.microsoft.com/en-us/learn/'
2. Click on 'Sign In'

**Expected behavior**
Expect account to login.

**Desktop (please complete the following information):**
 - OS: Windows 10 1903
 - Browser Edge
 - Version 44.18362.1.0

**Comment by Liebeck** [comment]
I can confirm to have the same issue with the login loop.

**Comment by kaydeeblack** [comment]
Same here.

**Comment by ryanmajidi** [comment]
@FrankWhitePFE are you still having this issue?

**Comment by FrankWhitePFE** [comment]
The issue now seems to be resolved.
