### ISSUE TITLE
Razor components content missing

### ISSUE THREAD

**Issue by kjaleshire** [MicrosoftDocs/feedback#1393]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

**Link to article:**
https://docs.microsoft.com/en-us/aspnet/core/razor-components/

**Problem:**
All of the documentation regarding Razor components is now 404'ing, including suggested links and search results.

**Comment by ryanmajidi** [comment]
@kjaleshire issue looks to be resolved. Please open a new issue if you have further issues.
