### ISSUE TITLE
The sidebar of MSTest doc is empty

### ISSUE THREAD

**Issue by goyzhang** [MicrosoftDocs/feedback#1394]
No content in the sidebar:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.testtools.unittesting?view=mstest-net-1.3.2

**Comment by dendeli-msft** [comment]
This is now fixed, thank you for the report @goyzhang!

Den Delimarsky ● Senior PM, docs.microsoft.com ● [@DennisCode](https://twitter.com/DennisCode)
