### ISSUE TITLE
Outdated information on website

### ISSUE THREAD

**Issue by thomas-krey** [MicrosoftDocs/feedback#1395]
Microsoft already released newer versions of Office (16.24.0 [19041401]), MAU (4.10 [190414]) and Skype for Business (16.25.73) as stated on this website.
Could you please update this website?
Have a nice day!
Kind regards,
Thomas Krey

**Comment by dendeli-msft** [comment]
Hello 👋 Can you please let us know what document this is in relation to?

**Comment by thomas-krey** [comment]
Hello Den,

my issue referred to the information displayed on the website itself (
https://docs.microsoft.com/en-us/officeupdates/update-history-office-for-mac
).

The website has been updated in the meantime, so you may close this thread.

Have a nice day!

Kind regards,

Thomas Krey

Am Di., 23. Apr. 2019 um 00:41 Uhr schrieb Den (Microsoft) <
notifications@github.com>:
