### ISSUE TITLE
Several links on this page fail: https://docs.microsoft.com/en-us/previous-versions/aspnet/hh834436(v=vs.118)

### ISSUE THREAD

**Issue by Zeek2** [MicrosoftDocs/feedback#1396]
Several links on this page fail: https://docs.microsoft.com/en-us/previous-versions/aspnet/hh834436(v=vs.118)

e.g. 
overload:system.net.http.formatting.mediatypeformatter.readfromstreamasync
overload:system.net.http.formatting.mediatypeformatter.getperrequestformatterinstance

![image](https://user-images.githubusercontent.com/22198523/56268720-f4aaee00-60e9-11e9-8ba2-389ba75aaedd.png)

**Comment by dendeli-msft** [comment]
Hello 👋 We are no longer actively updating the content on `/previous-versions` - we understand that in some cases there might be broken links or links pointing to incorrect locations; however we currently are not able to go through the extensive set of archived docs and update those.
