### ISSUE TITLE
Broken links opening Glossary pages

### ISSUE THREAD

**Issue by vCillusion** [MicrosoftDocs/feedback#1397]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

**Link to article:**
https://docs.microsoft.com/en-us/windows/desktop/secauthn/microsoft-ntlm

**Problem:**
Most of the help links open up the glossary page

**Comment by ryanmajidi** [comment]
@GrantMeStrength Can you please take a look at this issue?

**Comment by GrantMeStrength** [comment]
This is by design, as we can't link to specific terms.
