### ISSUE TITLE
Code usage examples for Microsoft Azure

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#14]
All topics on Msdn are having clear code usage examples for any API method or class library method released by Microsoft.NET f\w. 

https://msdn.microsoft.com/en-us/library/d00bd51t(v=vs.110).aspx

Nowadays, this key section is missing on all topics of docs.microsoft.com.

Especially Microsoft Azure based components\ class library are no clear, sometimes buggy. No help links online to get past that error.

Is it planned to take suggestions on improving docs.microsoft.com?

----------
⚠ Idea migrated from UserVoice

**Created By:** Ashokan Sivapragasam
**Created On:** 2018/03/01 05:46:17 +0000
**Votes at Migration:** 5
**Supporters at Migration:** 5

**Comment by Powerhelmsman** [comment]
It is available now. Please use .Net API browser to find the API method or class. It includes code example. 
For your case, please try this link: https://docs.microsoft.com/en-us/dotnet/api/system.threading.thread.sleep?view=netframework-4.7.2#System_Threading_Thread_Sleep_System_Int32_
