### ISSUE TITLE
Please provide a class summary table like MSDN had

### ISSUE THREAD

**Issue by glibnub** [MicrosoftDocs/feedback#140]
Example:
https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Controls.Grid
All the inherited members are just a giant unformatted sea of hyperlinks.  And for everything implemented by the class it's a giant scrolling page trying to find anything.  Old MSDN had a nicely formatted summary table listing all of the cl***'s members, properties, and events, with hyperlinks and a brief description of the member.  It's *incredibly* difficult to now to get an "at a glance" view of what a class actually does.

----------
⚠ Idea migrated from UserVoice

**Created By:** Anonymous
**Created On:** 2017/05/19 21:57:06 +0000
**Votes at Migration:** 18
**Supporters at Migration:** 18

**Comment by chgennar** [comment]
@dend What is the status of this issue?

**Comment by mairaw** [comment]
Isn’t this fixed now @dend?

**Comment by dend** [comment]
@mairaw yes, this is fixed!

**Comment by chgennar** [comment]
@dend @mairaw Is this something that needs to be configured?  How would I show a class summary table for a class such as [Map](https://docs.microsoft.com/en-us/javascript/api/azure-maps-javascript/map?view=azure-iot-typescript-latest)?
