### ISSUE TITLE
Microsoft Learn - Exam references/filtering

### ISSUE THREAD

**Issue by Devvox93** [MicrosoftDocs/feedback#1402]
**Is your feature request related to a problem? Please describe.**
In Microsoft Learn, it's hard to find which learning paths and modules are related to skill required for specific exams/certifications.

**Describe the solution you'd like**
It would be nice if there was a way you could select/filter on a specific exam and you'd get the related learning paths.
On a side note: Even better if you could cluster them in a "favorites" or "todo" section in your profile.

**Describe alternatives you've considered**
Search for exam numbers, selecting a role and use other existing filtering options.

**Additional context**
On the exam description pages, a lot of the time there was a tip "Self-paced training" with a link to a specific MVA (Microsoft Virtual Academy) course. As MVA is being replaced with Microsoft Learn, it'd be nice if learning paths/modules could be linked in a similar way.

**Comment by ryanmajidi** [comment]
@Devvox93 Thank you for this feedback. We have added this to our list of customer suggestions.
