### ISSUE TITLE
TOC filter behaves unexpected for certain characters

### ISSUE THREAD

**Issue by pkulikov** [MicrosoftDocs/feedback#1406]
The TOC filter either ignores certain characters (`<` and `>`) or provides too many entries for others (`&`).

A good test TOC is the one for the C# operators:
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/

The source file of that TOC:
https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/operators/toc.yml

## TOC entries are not shown

When TOC is filtered by the `>` character, the following entries are expected:
- `Bitwise and shift operators` (because of its `displayName` field, which contains `>>` substring)
- `>= operator`
- `> operator`
- `-> operator`
- `=> operator`

Observed behavior:
![image](https://user-images.githubusercontent.com/15279990/56417569-a9810e80-6294-11e9-8087-2a359fa37790.png)

The same is observed for the `<` character.

## Too many TOC entries are shown

When TOC is filterd by the `&` character, the following entries are expected:
- `Boolean logical operators` (because of it `displayName` field)
- `Bitwise and shift operators` (because of it `displayName` field)
- `& operator`
- `&= operator`

Observed behavior:
![image](https://user-images.githubusercontent.com/15279990/56417700-02e93d80-6295-11e9-833d-668006cda5c6.png)

/cc @BillWagner

**Comment by pkulikov** [comment]
@dendeli-msft @shirgoldbird the issue looks to be fixed. Thanks a lot!
Should I close it or you have something else to track here?

**Comment by shirgoldbird** [comment]
@pkulikov Nope, we'll close this out. Happy to help!
