### ISSUE TITLE
Mobile app for microsoft docs

### ISSUE THREAD

**Issue by docs-product** [MicrosoftDocs/feedback#141]
It will be great if we have Mobile app for docs.microsoft.com or different mobile app for different technology like asp.net mvc , asp.net core, etc..

----------
⚠ Idea migrated from UserVoice

**Created By:** Nirav
**Created On:** 2017/05/13 04:05:05 +0000
**Votes at Migration:** 1
**Supporters at Migration:** 1

**Comment by dend** [comment]
#log-suggestion @dastaffo to take a look.

**Comment by botcrane** [comment]
🚀 **ATTENTION**: [Internal request](https://ceapex.visualstudio.com/web/wi.aspx?pcguid=7d644393-99ad-41c8-ac53-7fa79294c720&id=25506) logged.

**Comment by dastaffo** [comment]
@ShevaDas FYI

**Comment by dendeli-msft** [comment]
Closing this item as it's currently not something that we're looking at. The mobile experience with the docs.microsoft.com website should provide all context and functionality.

**Comment by bdibd** [comment]
> It will be great if we have Mobile app for docs.microsoft.com or different mobile app for different technology like asp.net mvc , asp.net core, etc..
> 
> ⚠ Idea migrated from UserVoice
> 
> **Created By:** Nirav
> **Created On:** 2017/05/13 04:05:05 +0000
> **Votes at Migration:** 1
> **Supporters at Migration:** 1
