### ISSUE TITLE
Add a Trascript download option

### ISSUE THREAD

**Issue by shamnadhoh** [MicrosoftDocs/feedback#1411]
**Is your feature request related to a problem? Please describe.**
In the MVA Dashboad the "User" can download a "Transcript" for the "Accomplishments" done in the training

**Describe the solution you'd like**
Add a "Download Transcript" function to Download a PDF file with the list of all the couses completed.

**Additional context**

![Issue_Add_Transcript_PDF_20-04-19](https://user-images.githubusercontent.com/49814175/56458478-60f64d80-6387-11e9-8e55-f4856273c0a0.jpg)

**Comment by dendeli-msft** [comment]
@shamnadhoh is this related to any functionality on docs.microsoft.com?
