### ISSUE TITLE
GPRsop.LoggingComputer Property specified in these formats

### ISSUE THREAD

**Issue by mrchelli** [MicrosoftDocs/feedback#1412]
https://docs.microsoft.com/en-us/previous-versions/windows/desktop/wmi_v2/class-library/gprsop-loggingcomputer-property-microsoft-grouppolicy

Here the articel says: "The computer must be specified in one of the following formats: computer name, domain\computer name or fully qualified DNS computer name"

But that is just partly correct. If you want to address a computer in an other domain the domain\computer name does not work properly. It will take the computer name but just search it in the current domain, found that out by sniffing the packets with Wireshark. The fully qualified DNS computer name worked.

**Comment by dendeli-msft** [comment]
Thank you for the feedback, @mrchelli! The content you are referencing is out of support and might no longer be accurate.
