### ISSUE TITLE
version française 

### ISSUE THREAD

**Issue by Paul-LUMBALA** [MicrosoftDocs/feedback#1413]
https://docs.microsoft.com/en-us/contribute/

problème de traduction pour la langue française pour ce guide de contribution à la documentation.

**Comment by SonjaSaltzman** [comment]
Assigning to @DavidPrio cc: @SunnyDeng

**Comment by Paul-LUMBALA** [comment]
I would like to know what Next step?

**Comment by CeciAc** [comment]
Hello, @Paul-LUMBALA 
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @Paul-LUMBALA
 
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/fr-fr/contribute/

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.
	
Kind regards,
Microsoft DOCS International Team
