### ISSUE TITLE
[error message feedback] provide feedback

### ISSUE THREAD

**Issue by vizhur** [MicrosoftDocs/feedback#1418]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

**Problem:**
What's wrong with the error message? For example,
- Is error message clear and actionable?
- Is there a documentation to provide more information?
- If there is a documentation, is it relavent and helpful?
- Is line number correct?
- etc.

**Log code info**
(This is auto filled, no need to modify)

| Severity   | Type   | Code   | Category   | File   | Message   |  Source  | Line   | Time   |
|------------|--------|--------|------------|--------|-----------|----------|--------|--------|
| Error | System |  |  |  | call W:\twbj-s\.optemp\packages\docfx.console.2.42.0\tools\docfx.exe to get dependency map W:\twbj-log-4196e175\ML-Python\.dependency-map.azure-forecasting-py.json failed | W:\twbj-s\.optemp\packages\opbuild.scripts.1.73.0\tools\opbuild\dependency.resolver.ps1 |72 | 04/22/2019 12:25:04 |

**Link to report**
(This is auto filled, no need to modify)

[report url](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C4%5C22%5Ced72740f-9db8-56fb-e2eb-769d1f65a7dd%5CCommit%5C201904221219219962-dev-azureml%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=auGPWlv4tMzAxIN%2Bk%2BkEmE%2BQZ19ill0oVzOZDT%2FjNUI%3D&st=2019-04-22T17%3A05%3A11Z&se=2019-05-23T17%3A10%3A11Z&sp=r)

**Comment by cillroy** [comment]
thanks for the feedback, we are actively working on improving the reporting and documentation on these issues
