### ISSUE TITLE
MSDN Profile Display Name already in use. ???

### ISSUE THREAD

**Issue by liilipooh** [MicrosoftDocs/feedback#1426]
**Describe the bug**
When I attempt to use my full name "Ed Sponsler" for Display Name in my profile here
https://social.msdn.microsoft.com/Profile/Sponsler/activity

The form replies that I cannot because "This display name is already in use...." See screenshot.

I'm guessing that more than 8 years ago I used to have an MSDN account in which I used my full name. There are few Sponsler's out there and even fewer, if any, Ed Sponslers that I've ever come across.

![Annotation 2019-04-24 141827](https://user-images.githubusercontent.com/468359/56694777-5647fb00-669c-11e9-9bb9-64f48bc2fa29.png)

Is there any way to recover my original MSDN account that uses the "Ed Sponsler" display name?

**Comment by saldana** [comment]
You need to recover the account you used 8 years ago in order to use the same display name. You can try to go to [https://account.live.com/resetpassword.aspx](https://account.live.com/resetpassword.aspx) to recovery your account.

**Comment by saldana** [comment]
I am closing this issue. If you need further help, please reactivate.
