### ISSUE TITLE
Grammatical errors in Direct3D 12 Programming Guide - Memory Management Strategies

### ISSUE THREAD

**Issue by bioglaze** [MicrosoftDocs/feedback#1427]
**Link to article:**
https://docs.microsoft.com/en-us/windows/desktop/direct3d12/memory-management-strategies

**Problem:**
"For discreet adapters" should read "For discrete adapters".
"and do it more strictly then" should read "and do it more strictly than".

**Comment by clandrew** [comment]
I pushed a change to fix this. @stevewhims Could you please close the issue? It appears I don't have permissions to close issues

**Comment by clandrew** [comment]
Thank you for reporting this issue, by the way!

**Comment by stevewhims** [comment]
I don't have perms to close this, either. Lemme send email around internally and see what's up. :)

**Comment by dendeli-msft** [comment]
Closing as this should be resolved.
