### ISSUE TITLE
Typos in the Azure SQL Data Warehouse Page

### ISSUE THREAD

**Issue by SreeVoleti** [MicrosoftDocs/feedback#1428]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

**Link to article:**
 https://azure.microsoft.com/en-in/services/sql-data-warehouse/

**Problem:**
Typos in the content.
1) Error: Lighting-fast performance
    Suggestion: Lightening-fast performance

**Comment by mairaw** [comment]
Closing since this issue no longer repros. The page has probably changed since then.
