### ISSUE TITLE
CTRL + Click on topic places new tab first in order...not last

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#143]
Either a bug or a "not as expected" thing.

In HelpeViewer 2.3.

Lets say I have these books installed:

* Introduction to ASP.NET Core
* .NET Framework 4.6 and 4.5
* Visual Studio 2012.

In the left side...it is just showing the "Manage content" tab.

I do:

CTRL + Left Click on ".NET Framework 4.6"
CTRL + Left Click on "Introduction to ASP.NET Core"

I would have expected the "new tabs" to be displayed on the "right"...after the Manage Content, and in this order:

Manage content
.NET Framework 4.6.
Introduction to ASP.NET Core.

You are displaying them in a back to front order on last selected

----------
⚠ Idea migrated from UserVoice

**Created By:** Anonymous
**Created On:** 2017/05/09 12:31:01 +0000
**Votes at Migration:** 1
**Supporters at Migration:** 1

**Comment by dend** [comment]
At this time there are no plans to address this, therefore closing this item.
