### ISSUE TITLE
Windows Virtual HLK (VHLK), version 1903

### ISSUE THREAD

**Issue by JonasMuraska** [MicrosoftDocs/feedback#1432]
Cannot download the Windows Virtual HLK (VHLK), version 1903

something is wrong with the link
https://software-download.microsoft.com/download/pr/2016DC-18362-1-19h1_release-190318-1202-VS2017Ent-HLK.vhdx

**Comment by dendeli-msft** [comment]
@JonasMuraska is this link made available somewhere in the documentation hosted on docs.microsoft.com?

**Comment by JonasMuraska** [comment]
Yes. I want to download Windows Virtual HLK (VHLK), version 1903 here
https://docs.microsoft.com/en-us/windows-hardware/test/hlk/

**Comment by MikeSNL** [comment]
Same problem with the 1809 download, looks like a complete list of links is broken.

**Comment by ryanmajidi** [comment]
Seems to be working now.
