### ISSUE TITLE
Using special characters on docs.microsoft.com doesn't result in the right characters in the GitHub issues

### ISSUE THREAD

**Issue by patrikhuber** [MicrosoftDocs/feedback#1436]
**Describe the bug** & **To Reproduce**

Open a new issue e.g. on https://docs.microsoft.com/en-us/visualstudio/intellicode/faq and use some special syntax like quoting (`> ...`), e.g. write an issue text like this:

```
Issue text

> This is a quote.

More issue text.
```

Result: The text is not correctly rendered quoted on https://docs.microsoft.com/en-us/visualstudio/intellicode/faq. If you go to the issue on GitHub (e.g. https://github.com/MicrosoftDocs/intellicode/issues/90) and `Edit` there, it shows a `&gt` instead of the `>`. If you then manually replace that with a `>`, it's then rendered correctly both on GitHub as well as on the original docs.microsoft.com page.

**Expected behavior**

If I type a `>` on docs.microsoft.com, it should be correctly rendered as a quote and "become" the `>` character and not `&gt`.

**Desktop (please complete the following information):**

Windows 10, latest Chrome as of today.

**Comment by dendeli-msft** [comment]
Thank you for the feedback! I've opened an internal issue for us to track.

At this time, we have no concrete timelines or commitments for this change, however we'll make sure that we do our due diligence in assessing the impact and importance of the feature.
