### ISSUE TITLE
Appearance on MacOS

### ISSUE THREAD

**Issue by rnserdyuk** [MicrosoftDocs/feedback#1437]
**Describe the bug**
First of all, the webpage (https://docs.microsoft.com/ru-ru/power-bi/guided-learning/) doesn't fit into screen of a laptop. I mean 25% of the webpage. I think, this can be caused by unnecessary filter menu (at least on this particular page). The body of webpage is wider, than a header.

**To Reproduce**
1. Take a MacBook
2. Launch Safari
3. Open the link https://docs.microsoft.com/ru-ru/power-bi/guided-learning/
4. See

**Expected behavior**
In 2019 I expect the page, that fits into the screen.

**Screenshots**
Here could be 2 screenshots, if I understood how to attach it.

**Desktop (please complete the following information):**
 - MacOS 10.14.4
 - Safari 12.1
 - 14607.1.40.1.4

**Additional context**
If I just want to report the issue, why should I sign up on github.com???

**Comment by dendeli-msft** [comment]
Thank you for the feedback! We've recently released a new page design that should address this issue.
