### ISSUE TITLE
provide a tree fullscreen mode

### ISSUE THREAD

**Issue by docs-product** [MicrosoftDocs/feedback#144]
Currently when using HelperViewer 2.3...pressing F11...just toggles maximizing or restoring the window.....the Windows Chrome is still there.

Please provide a "full screen" mode, that removes the distracting chrome, enabling one to concentrate on the topics being read.

----------
⚠ Idea migrated from UserVoice

**Created By:** Anonymous
**Created On:** 2017/05/09 12:24:46 +0000
**Votes at Migration:** 1
**Supporters at Migration:** 1

**Comment by dastaffo** [comment]
@ShevaDas FYI for future offline plans

**Comment by dendeli-msft** [comment]
Closing this item as it's currently not on the radar.
