### ISSUE TITLE
StorageCredential doc

### ISSUE THREAD

**Issue by tonywcchan** [MicrosoftDocs/feedback#1446]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

**Link to article:**
https://docs.microsoft.com/en-us/dotnet/api/microsoft.windowsazure.storage.auth.storagecredentials

**Problem:**
What's wrong with the article?
404 Page Not Found

**Comment by dendeli-msft** [comment]
This is likely related to the fact that the Azure namespaces have changed in the recent package update. We are investigating the issue with documentation.

**Comment by tonywcchan** [comment]
Hello,

Is there any updates?
When I used Bing to search for “StorageCredentials C#”, the link of the top result from Bing is still broken.

Regards,
Tony

**Comment by dendeli-msft** [comment]
Thank you for the report! This is a side-effect of the Azure Storage .NET API introducing a breaking change, that updated the namespaces. The correct API entities will soon start showing up in search results, as the major search engines re-index the content.

Den Delimarsky ● Senior PM, docs.microsoft.com ● [@DennisCode](https://twitter.com/DennisCode)
