### ISSUE TITLE
please bring back the "global" tree hierarchical picture of what content is available...as per the original MSDN

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#145]
In the old MSDN and help days, you always had a "fully populated" tree of the available content. This had several benefits.

a) it gave you a global picture of all available content/section....enabling discovery of new material

b) it enabled you to form a "mental" picture of the whole...enabling you to quickly revisit areas you were "studying"

c) it enabled you to quickly navigate between sections without getting "lost"

You don't have to make it a default....but please please provide that old "tree" style view of content in the right hand pane...it was a delight.....I don't like this "breadcrumb" style one.

----------
⚠ Idea migrated from UserVoice

**Created By:** Anonymous
**Created On:** 2017/05/09 11:56:59 +0000
**Votes at Migration:** 2
**Supporters at Migration:** 2

**Comment by dend** [comment]
Closing this as a `wont-fix` for now - we are working on improving the information architecture on docs all-up.

If there are any issues with a particular article, our recommendation is to use the built-in article feedback capabilities to let content developers know about issues with their content structure.
