### ISSUE TITLE
PT-br - Porque a tradução de application é aplicativo e não aplicação?

### ISSUE THREAD

**Issue by jhomarolo** [MicrosoftDocs/feedback#1453]
**Link to article:**
https://docs.microsoft.com/pt-br/azure/cosmos-db/partitioning-overview

**Problem:**
The translation of the word application throughout the documentation portal is for mobile application (like app) and not for a global application.

The word **application** here in Brazil suggests that it is a mobile application and not a general application. 

It's as if **aplicativo** would be translated to **app** and **aplicação** to application

I would make a general change across the docs platform if possible to fix this term.

**Comment by SonjaSaltzman** [comment]
Assigned to @DavidPrio ; cc @ishasahni1

**Comment by CeciAc** [comment]
Hello, @jhomarolo
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @jhomarolo

Thank you for your linguistic feedback. 
 
Unfortunately, after reviewing your feedback our linguistic team considered it to be not fully aligned with our criteria for acceptance _[Both terms, "aplicativo" and "aplicação" are used in IT as a translation to "application". In Microsoft products we have opted to use "aplicativo" and to maintain consistency, avoiding confusing users, we stick to one  translation for the same term. Your question is valid, as there are both translations in the field, but they both mean the same thing, so be aware that for all MS products you will find "aplicativo" as the chosen translation for this term.]_

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback. 

Kind regards,
Microsoft DOCS International Team
