### ISSUE TITLE
https://docs.microsoft.com/en-us/microsoft-identity-manager/

### ISSUE THREAD

**Issue by PeterGeelen** [MicrosoftDocs/feedback#1457]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

**Link to article:**
Tell us where exactly a problem occurs.
https://docs.microsoft.com/en-us/microsoft-identity-manager/

**Problem:**
What's wrong with the article?
Icons missing, intermediate issues with display of left hand menu.
![MIM_Docs_issue_Capture](https://user-images.githubusercontent.com/16639202/57127469-d226ff00-6d90-11e9-8f71-37e0058991e8.JPG)

**Comment by billmath** [comment]
#please-close
