### ISSUE TITLE
Please provide better navigation of "topics" in both the online "docs" and in the offline HelpViewer

### ISSUE THREAD

**Issue by docs-product** [MicrosoftDocs/feedback#146]
At the moment there is a poor experience when trying to read a large collection of topics in sequence.

As an example...lets say I want to completely digest the "Introduction to ASP.NET Core" "book".

If I go online...to "docs".....I cannot easily move from "page" to "page"...I am to break my concentration and use the mouse to select the next bit to read from the side panel....I also have to contend with mentally expanding as well.

If i use your offline "helper viewer"....then while I can just keep pressing your "Right Arrow" key to move to the next "topic"....this gets "stuck" if it hits a dead end of the tree node......it doesn't "select" the next "topic" in the hierarchy automatically. Also I then have to switch to the SPACE key, or down arrow, to move through "long" topics.

What I suggest is that the "SPACE" key is used to "page down" a topic....and when the end of the topic is reached....SPACE automatically moves on to the next topic in the sequence in the tree hierarchy.

One then doesn't have to play with the mouse....and can fully concentrate/read....and can press just one thing to move onwards e.g. SPACE would be the easiest, most logical.

Lets say my tree hierarchy is like this:

A
   B
       C
       D
       E
   F
   G
H
   I
       J
       K

Lets say I am on topic "C".

Then what you should show me when I say "show next topic" is...this order.

C -> D -> E -> F -> G -> H -> I -> J -> K

----------
⚠ Idea migrated from UserVoice

**Created By:** Anonymous
**Created On:** 2017/05/09 11:44:44 +0000
**Votes at Migration:** 2
**Supporters at Migration:** 2

**Comment by dastaffo** [comment]
@ShevaDas FYI for future offline planning

**Comment by dendeli-msft** [comment]
Closing this item for the time being as it requires some architectural changes to content that are not currently on the radar.
