### ISSUE TITLE
[Content] npapi.h/NPGetCaps (no feedback mechanism)

### ISSUE THREAD

**Issue by kyanha** [MicrosoftDocs/feedback#1461]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

Note: There is no comment section for this article.  I'm sorry for leaving this in general feedback, but I honestly can't figure out where it needs to go.

**Link to article:**
https://docs.microsoft.com/en-us/windows/desktop/api/npapi/nf-npapi-npgetcaps#return-value

**Problem:**
This article has multiple issues.
1. The function prototype specifies the parameter 'ndex', the Parameters section refers to 'ndex', but the Return Value section of the article refers to 'nIndex'.
2. The Return Value section says 'the list below', when the list is above in the Parameters section.
3. There is no information for how to interpret each of the return codes which are bitmasks (which functions are indicated by each bit of the return code).  This is the main thing that I came to this article to find, but it's not here. :)

Thanks for your attention, and thanks for all the work you do to make the documentation awesome!

**Comment by ryanmajidi** [comment]
@GrantMeStrength Can you please take a look at this issue?

**Comment by GrantMeStrength** [comment]
Thanks for report this. A lot of information was accidentally removed. I've submitted the fix to have it returned. In the meantime, here's a link to a topic that has it:

https://msdn.microsoft.com/zh-cn/vstudio/aa378794(v=vs.71)
