### ISSUE TITLE
I want to know when approximately the build 18305 or higher will be available to normal users?

### ISSUE THREAD

**Issue by MichaelIsGreat123** [MicrosoftDocs/feedback#1462]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.
Not applicable as there is no comment section for the article “Windows 10 - release information - Windows Release Information | Microsoft Docs” on https://docs.microsoft.com/en-us/windows/release-information/ 

**Link to article:**
“Windows 10 - release information - Windows Release Information | Microsoft Docs” on https://docs.microsoft.com/en-us/windows/release-information/ 

**Problem:**
Nothing wrong with this article, I just would like to know extra information related to this article.
I want to know when approximately the build 18305 or higher will be available to normal users?

Currently on 05/06/2019, the build is Version 1809 (OS build 17763) according to this article “Windows 10 - release information - Windows Release Information | Microsoft Docs” on https://docs.microsoft.com/en-us/windows/release-information/

Why do I want to know this information? Because I want to know when the Windows 10 Sandbox feature will become available for normal users and I read that it might be approximately around the build 18305 or higher.

Thanks for your feedback on this matter. 

Kind Regards
Michael

**Comment by ryanmajidi** [comment]
@GrantMeStrength Can you please take a look at this?

**Comment by GrantMeStrength** [comment]
We can't release information in advance, unfortunately, as it might be incorrect.
We'll do our best to update that page as soon as we can.
