### ISSUE TITLE
Microsoft learn as unique learning/video platform

### ISSUE THREAD

**Issue by emiliano84** [MicrosoftDocs/feedback#1463]
There are too many Microsoft video/learning platforms, and instead reduce the number they keep increasing, can you figure it out a way to move everything under one unique platform as you did for docs?

https://developer.microsoft.com/en-us/collective/learning/courses
https://www.linkedin.com/learning/me
https://mva.microsoft.com/
https://channel9.msdn.com/
https://docs.microsoft.com/en-us/learn/

thanks
regards

**Comment by ryanmajidi** [comment]
@emiliano84 We are working towards this. Thank you for your feedback.

**Comment by Regenhardt** [comment]
You can add academy.microsoft.com to the list.
