### ISSUE TITLE
A wrong example for the DAX function

### ISSUE THREAD

**Issue by GeoffreyQiao** [MicrosoftDocs/feedback#1464]
**🛑 IMPORTANT**: i think the example for the DAX function has some wrong...

**Link to article:**
[CONTAINSSTRING](https://docs.microsoft.com/zh-cn/dax/containsstring-function-dax#example)

**Problem:**
the "CASE4" in the result for this example, should it be 'False'?
![SharedScreenshot](https://user-images.githubusercontent.com/5956387/57240856-2ae0eb00-7062-11e9-89c6-71db53545d01.jpg)

**Comment by ryanmajidi** [comment]
@Minewiskan Can you please take a look at this?

**Comment by Minewiskan** [comment]
@GeoffreyQiao - Thanks for pointing this out. It is incorrect. It's now fixed in en-us locales. I'm not sure how long it will take to make it to other locales.
https://docs.microsoft.com/en-us/dax/containsstring-function-dax
#please-close
