### ISSUE TITLE
The document of d3d12video is missing

### ISSUE THREAD

**Issue by gongminmin** [MicrosoftDocs/feedback#1465]
**Link to article:**
The Headers list in https://docs.microsoft.com/en-us/windows/desktop/api/index has d3d12.h, but not d3d12video.h. And all interfaces in d3d12video.h are not documented.

**Problem:**
d3d12video.h is in the Windows SDK since RS3. But its document is missing.

**Comment by ryanmajidi** [comment]
@GrantMeStrength Can you please take a look at this?

**Comment by gongminmin** [comment]
Any update? This header file was rolling out for 2 years, still no document.

**Comment by drewbatgit** [comment]
This content has been written and is undergoing a technical review right now. It should be live within the next few weeks.
