### ISSUE TITLE
Filter Page Versions

### ISSUE THREAD

**Issue by spottedmahn** [MicrosoftDocs/feedback#1466]
**Is your feature request related to a problem? Please describe.**
When I visit the ASP.NET Core pages and I try a version that doesn't exist I get:

>The requested page is not available for ASP.NET Core 2.0. You have been redirected to the newest product version this page is available for.

Example: [ASP.NET Core Razor SDK](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/sdk?view=aspnetcore-2.2&viewFallbackFrom=aspnetcore-2.0)

Now I start going through each page version to figure out what versions there is a page for.

**Describe the solution you'd like**
Filter the page versions list on the left so I don't have to figure out the minimum version.

![image](https://user-images.githubusercontent.com/14079228/57248723-14f70a00-7011-11e9-98a4-1a1ae97ea9ce.png)

**Describe alternatives you've considered**
Leave all options but add a label like "Not Available" to the version dropdown entries.

**Comment by ryanmajidi** [comment]
@shirgoldbird Can you please take a look at this issue?

**Comment by dendeli-msft** [comment]
Thank you for the feedback! I've opened an internal issue for us to track.

At this time, we have no concrete timelines or commitments for this change, however we'll make sure that we do our due diligence in assessing the impact and importance of the feature.
