### ISSUE TITLE
Image seems too big

### ISSUE THREAD

**Issue by poldata** [MicrosoftDocs/feedback#1467]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

**Link to article:**
Tell us where exactly a problem occurs.
This page:
https://docs.microsoft.com/en-us/learn/

**Problem:**
What's wrong with the article?
Image looks too big, you have to scroll a lot to get to the next section.

Look at screenshot:
https://www.screencast.com/t/nOBIEOvRNNX

**Comment by clandrew** [comment]
Weird, I don't reproduce this. Could you please confirm which web browser you're using?

**Comment by dendeli-msft** [comment]
I can't reproduce this either. @poldata - can you please provide more context on the browser/resolution you have, as well as on whether this issue still occurs?

**Comment by ryanmajidi** [comment]
Closing this issue. 

@poldata Please open a new issue if this persists.
