### ISSUE TITLE
PDF download not working: Windows Server 2019-Step by Step Installation of Domain Controller

### ISSUE THREAD

**Issue by Loves2Code** [MicrosoftDocs/feedback#1468]
**Describe the bug**
At the URL:
https://gallery.technet.microsoft.com/Windows-Server-2019-Step-4c0a3678
Web site title: Windows Server 2019-Step by Step Installation of Domain Controller
The web site has a button to download as a *.pdf a "Lab" of the same name: Windows Server 2019-Step by Step Installation of Domain Controller.
However, the link does not work. In the Q & A section of the page there are complaints about the download not working as far back as October 20, 2018.

**To Reproduce**
1. Go to https://gallery.technet.microsoft.com/Windows-Server-2019-Step-4c0a3678
2. Click on 'Windows Server 2019-Step by Step Installation of Domain Controller.pdf'
3. Accept the license terms of use by clicking "I agree".
4. Nothing happens.

**Expected behavior**
At Step 4, above, I expected the "File, Save As" dialog to appear with the name of the pdf file in the "File Name" text box.

**Screenshots**
None needed.

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome, and others.
 - Version of Chrome: 74.0.3729.131 (Official Build) (64-bit)

**Additional Information**
Note, in the Q & A there is a link for the actual document. The downloaded *.pdf document appears to be a rough draft. I am assuming there is a more presentable version of this information by now, since Server 2019 has been released.

**Comment by ryanmajidi** [comment]
I can't reproduce this issue. 

@Loves2Code if this still persists please open a new issue.
