### ISSUE TITLE
Make top bar black in dark mode, too

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#147]
_No details provided._

----------
⚠ Idea migrated from UserVoice

**Created By:** Jay Chu
**Created On:** 2017/05/08 20:05:25 +0000
**Votes at Migration:** 2
**Supporters at Migration:** 2

**Comment by Powerhelmsman** [comment]
@ShevaDas Can you follow up with this once the new header is live?

**Comment by spatnaik** [comment]
Wondering when this fix is coming. If not, here is more information on the request:
Update the top banner to match the theme. I'm looking at http://aka.ms/rds and in "Dark" mode, there still is a white banner left at the top of the page. In contrast, Azure documentation doesn't have that (e.g. https://docs.microsoft.com/en-us/azure/virtual-machines/windows/). This request is to adopt the behavior on Azure documentation. Notice that both are on docs.microsoft.com.

**Comment by Powerhelmsman** [comment]
@ShevaDas for your awareness

**Comment by ShevaDas** [comment]
@spatnaik Unfortunately, this isn't something we're able to fix. Docs (excepting the Azure documentation) uses a Microsoft-standard header that doesn't allow for this kind of customization. Sorry we can't be of more help—I'm going to close this out for now.

**Comment by spatnaik** [comment]
@ShevaDas: I was hoping this changed across the board for all pages using dark mode - not just the rds pages.

**Comment by ShevaDas** [comment]
@spatnaik Are you asking about something other than the top-most navbar that contains the navigation around Docs?
