### ISSUE TITLE
CloseReason Enum bad description

### ISSUE THREAD

**Issue by AlexYurkin** [MicrosoftDocs/feedback#1471]
**Link to article:**
https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.closereason?redirectedfrom=MSDN&view=netframework-4.8

**Problem:**
When you describe the fields of this Enumeration you state that the 'UserClosing' happens when: "The user is closing the form through the user interface (UI)". But this also happens when you use 'Close' method for a form in your code.
It would be great to distinguish the UI Closing from the code closing.

**Comment by ryanmajidi** [comment]
@rloutlaw can you please take a look at this issue?

**Comment by mairaw** [comment]
This could be moved to our repo: https://github.com/dotnet/dotnet-api-docs/issues

**Comment by ryanmajidi** [comment]
Moved: https://github.com/dotnet/dotnet-api-docs/issues/2844
