### ISSUE TITLE
Focus skips over nested links in documentation navigation

### ISSUE THREAD

**Issue by spencerudnick** [MicrosoftDocs/feedback#1473]
**Describe the bug**
When using Tab & Shift+Tab to navigate the documentation tree in the sidebar, I'm unable to focus directly on the links to the actual articles.

**To Reproduce**
1. Go to https://docs.microsoft.com/en-us/windows/desktop/accessibility-whatsnew
2. Tab until the "Accessibility" document collection is focused
3. Hit Enter or Return to toggle the state until it is open (child pages are visible).
4. Hit Tab again.

**Expected behavior**
The links inside the "Accessibility" section on the page are focusable, and Tab / Shift+Tab can be used to navigate to the desired link.

**Screenshots**
![Screenshot 2019-05-08 at 12 10 51](https://user-images.githubusercontent.com/3072639/57368345-41369600-718b-11e9-82d5-639c53019d2d.png)
![Screenshot 2019-05-08 at 12 10 59](https://user-images.githubusercontent.com/3072639/57368352-44318680-718b-11e9-9248-1d57355e2dbd.png)

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.x
 - Browser Firefox
 - Version 66

**Comment by shirgoldbird** [comment]
@spencerudnick We just rolled out some new accessibility changes to the TOC. It can now be navigated in compliance with WAI-ARIA guidelines using your arrow keys. Please take a look and close the issue out if it works for you.

**Comment by ryanmajidi** [comment]
Closing this issue.
