### ISSUE TITLE
Visual Studio 2015 with Update 5 - Installation Tool: Modify was running forever. Upon Restart of the System gives misleading message.

### ISSUE THREAD

**Issue by themonkster** [MicrosoftDocs/feedback#1475]
VS 2015 with Update 5 - Installation Tool : Modify was taking Forever.

1. VS 2015 with Update 5 - Installation Tool : Modify was taking Forever.
2. Cancelled the Setup
3. It gives a misleading Message

**Screenshots**
![VSBug](https://user-images.githubusercontent.com/25617696/57445243-8cc27000-726f-11e9-88c5-1d3a5f077480.png)

**Desktop (please complete the following information):**
 - OS: Windows 8

**Comment by ryanmajidi** [comment]
Please submit this issue here: https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019
