### ISSUE TITLE
Validating an XML file with a DTD doesn't appear to work.

### ISSUE THREAD

**Issue by marcslevesque** [MicrosoftDocs/feedback#1476]
The xml file contents (although anything I've tried has not worked, even a simple XHTML document):

```
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE cXML SYSTEM "http://xml.cxml.org/schemas/cXML/1.2.039/cXML.dtd">
<cXML payloadID="9949494" xml:lang="en-US" timestamp="2000-03-12T18:39:09-08:00">
	<Header>
		<From>
			<Credential domain="NetworkID">
				<Identity>something</Identity>
			</Credential>
		</From>
		<To>
			<Credential domain="NetworkID">
				<Identity>something else</Identity>
			</Credential>
		</To>
		<Sender>
			<Credential domain="AribaNetworkUserId">
				<Identity>sysadmin@ariba.com</Identity>
				<SharedSecret>donttellanyone</SharedSecret>
			</Credential>
			<UserAgent>CatalogTester</UserAgent>
		</Sender>
	</Header>
	<Request>
		<ProfileRequest />
	</Request>
</cXML>
```

The code:

```
	    XmlReaderSettings settings = new XmlReaderSettings
            {
                ValidationType = ValidationType.DTD,
                DtdProcessing = DtdProcessing.Parse,
                IgnoreComments = true,
                IgnoreWhitespace = true,
            };

            FileStream stream = new FileStream(@"PathToFile", FileMode.Open);

            XmlReader r = XmlReader.Create(stream, settings);
            try
            {
                Console.Write(string.Format("Validating {0}...", stream.Name));
                while (r.Read())
                {
                }
				Console.WriteLine("Success!");
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
            }
            finally
            {
                r.Close();
            }
```

The result of running the above code is

>  Validating (path to file and filename)...The 'cXML' element is not declared.

As mentioned, I've also tried with a simple XHTML file and that doesn't work either:

```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
    <title>Welcome</title>
</head>
<body>
    <p>Hello World!</p>
</body>
</html>
```

The result is:

> Validating (path to file and filename)...The 'html' element is not declared.

Yet if you paste both documents into the W3C's validator, they are valid:

![image](https://user-images.githubusercontent.com/23728144/57480384-8d5a0700-726d-11e9-8295-5aec2e3be7b2.png)

![image](https://user-images.githubusercontent.com/23728144/57476240-1d934e80-7264-11e9-810f-2427e9545f91.png)

I would rather the case be that I am doing something wrong than there be something wrong with the validation because I don't want to have to wait for an update, but I can't find any examples on the internet that work.

Note that I have tried this in .net core 2.2.106 and .net framework 4.6.1, with the same results.

**Comment by rootsmusic** [comment]
@marcslevesque Where's the doc?

**Comment by marcslevesque** [comment]
Which doc?

**Comment by rootsmusic** [comment]
@marcslevesque Is this issue about a doc?

**Comment by marcslevesque** [comment]
I don't believe so.  It was a couple of years ago, so I don't remember.

It may have been about following some documentation that didn't work, but I don't think so.

I don't remember how or what I clicked on to create this issue.  The real issue wouldn't be about documentation though, but that validation doesn't work (and as I recall, it worked fine in .net 4.7(?).x.

**Comment by rootsmusic** [comment]
@marcslevesque Since this issue isn't about a doc, please ask product support or in product forums if you still need help.
