### ISSUE TITLE
Misleading Description for MvcHtmlString.Create()

### ISSUE THREAD

**Issue by vikscool** [MicrosoftDocs/feedback#1478]
The description of the function [MvcHtmlString.Create()](https://docs.microsoft.com/en-us/dotnet/api/system.web.mvc.mvchtmlstring.create?view=aspnet-mvc-5.2) is misleading as it states that it:

> Creates an HTML-encoded string using the specified text value.

But instead, it is decoding an already HTML-encoded string and if you pass an HTML string to it, it simply outputs its HTML.

For eg:
`@MvcHtmlString.Create("i am &lt;bold&gt;")`
will output an decoded HTML code:
> I am **Bold**
 
and if we input an simple `HTML` string like:
`@MvcHtmlString.Create("I am <b>bold</b>)`
again it is written as a normal HTML code:
> I am **Bold**

instead of `i am &lt;bold&gt;`

Please fix the description as it confuses to whoever is using it.

**Comment by ryanmajidi** [comment]
@vikscool Moved to that repo https://github.com/aspnet/ApiDocs/issues/127
