### ISSUE TITLE
Today we are happy to announce our unified . . . 

### ISSUE THREAD

**Issue by BaruchAtta** [MicrosoftDocs/feedback#1480]
When is "today"?  I wish that the blog posts had dates!

**Comment by BaruchAtta** [comment]
This is the offending post.  (below)  Of course, my comment applies to all of the posts here. 

Announcing a unified .NET reference experience on docs.microsoft.com
•3 minutes to read
• Contributors Jeff Sandquist
 Den Delimarsky

This post was written by Jeff Sandquist, General Manager in the Azure Growth and Ecosystem team.

**Comment by dendeli-msft** [comment]
Hello @BaruchAtta - the date of the post is indicated in the heading!

![Screenshot of the docs.microsoft.com team blog with arrow pointing to date of publishing](https://user-images.githubusercontent.com/33675759/57552251-2c3f3b80-7320-11e9-8933-e5569762853d.png)
