### ISSUE TITLE
404 on SetWaitableTimer function article

### ISSUE THREAD

**Issue by JalxP** [MicrosoftDocs/feedback#1481]
**Link to article:**
https://docs.microsoft.com/en-us/windows/desktop/api/synchapi/nf-synchapi-setwaitabletimer

**Problem:**
The first two links on the description of the first parameter lead to a 404 error (the links "CreateWaitableTimer" and "OpenWaitableTimer").

**Comment by ryanmajidi** [comment]
@GrantMeStrength Can you please take a look at this issue?

**Comment by GrantMeStrength** [comment]
All links to CreateWaitableTimer lead to a 404. Perhaps as CreateWaitableTimer also exists as CreateWaitableTimerExt and other functions? Seems a systemic issue, so assigning to Drew who knows all about this kind of thing. Thanks for reporting!

**Comment by drewbatgit** [comment]
These broken links were due to a site-wide issue that has been resolved. These links are now resolving successfully.
