### ISSUE TITLE
D3D12_RESOURCE_STATE_RAYTRACING_ACCELERATION_STRUCTURE not documented and D3D12_RESOURCE_STATE_SHADING_RATE_SOURCE documentation broken

### ISSUE THREAD

**Issue by Wumpf** [MicrosoftDocs/feedback#1482]
**Link to article:**
https://docs.microsoft.com/en-us/windows/desktop/api/d3d12/ne-d3d12-d3d12_resource_states

**Problem:**
`D3D12_RESOURCE_STATE_RAYTRACING_ACCELERATION_STRUCTURE` is not documented but contains the label and documentation for `D3D12_RESOURCE_STATE_SHADING_RATE_SOURCE` which otherwise does not show up in the table.

**Comment by ryanmajidi** [comment]
@GrantMeStrength Can you please take a look at this issue?

**Comment by GrantMeStrength** [comment]
Assigned to the correct content owner.

**Comment by stevewhims** [comment]
Hi, @Wumpf. I've published a fix to the topic. I'll go ahead and close this issue now, but you can always reopen it if necessary. ~Steve
