### ISSUE TITLE
A number of Microsoft-defined reparse point tags are not listed under Reparse Point Tags

### ISSUE THREAD

**Issue by sba923** [MicrosoftDocs/feedback#1483]
**Link to article:**
https://docs.microsoft.com/en-us/windows/desktop/FileIO/reparse-point-tags

**Problem:**
A number of reparse point tags, notably the IO_REPARSE_TAG_CLOUD* values for OneDrive, are not listed.

**Comment by ryanmajidi** [comment]
@GrantMeStrength Can you please take a look at this issue?

**Comment by GrantMeStrength** [comment]
Sorry for the long delay in dealing with this issue, but it looks like all the tags are listed now. 
If there is more work required, please feel free to re-open this issue - thank you!
