### ISSUE TITLE
Spelling mistake. "Pixelated" spelled as "Pixilated"

### ISSUE THREAD

**Issue by topcat001** [MicrosoftDocs/feedback#1485]
**Link to article:**
https://docs.microsoft.com/en-us/windows/desktop/LearnWin32/dpi-and-device-independent-pixels#dwm-scaling

**Problem:**
In the third item on the bullet list following "If a program does not account for DPI, the following defects might be apparent at high-DPI settings:", "Pixelated" incorrectly spelled as "Pixilated" (the word pixilated is valid and means crazy or confused which is not the intended meaning here; I suspect this is a rogue autocorrect!).

**Comment by ryanmajidi** [comment]
@GrantMeStrength Can you please take a look at this issue?

**Comment by GrantMeStrength** [comment]
Correction submitted. Quite amusing given the actual definition of "pixilated" :-)
