### ISSUE TITLE
Confusing formal definition of the search filter

### ISSUE THREAD

**Issue by survived** [MicrosoftDocs/feedback#1486]
**Link to article:**
https://docs.microsoft.com/en-us/windows/desktop/adsi/search-filter-syntax

**Problem:**
There's no line break in 2nd line of `The formal definition of the search filter is as follows (from RFC 1960)`. `<and> ::= '&' <filterlist>` rule must be in separate line.

**Comment by survived** [comment]
And by the way, why there's a grammar from RFC 1960? It doesn't describe extensible matching that's being used in entire article, but [RFC 2254](https://tools.ietf.org/html/rfc2254) does.

**Comment by ryanmajidi** [comment]
@GrantMeStrength Can you please take a look at this issue?

**Comment by GrantMeStrength** [comment]
Thank for you creating this issue. The corrections have been made in the topic, and should be published shortly.
I'm sorry it took so long for us to get to this issue, but your feedback is still very much appreciated.

-john
