### ISSUE TITLE
Ability to delete my vote.

### ISSUE THREAD

**Issue by alejandraneolopan** [MicrosoftDocs/feedback#1488]
I clicked in the button Vote by error. I wanted to delete my vote but there is no way to do it.

**Describe the solution you'd like**
As others sites I would like an option to clear my vote.

**Describe alternatives you've considered**

**Additional context**
After I reply a question, use has the ability to vote over solutions proposed by community.

**Comment by sudeepku** [comment]
#log-suggestion

**Comment by shirgoldbird** [comment]
@alejandraneolopan Could you please clarify which part of the site you're seeing this on?

**Comment by dendeli-msft** [comment]
Given that we haven't received any additional information on this item, I will go ahead and close it. @alejandraneolopan - please open a new issue if the problem persists.
