### ISSUE TITLE
No document of D3D12_FEATURE_D3D12_OPTIONS4, D3D12_FEATURE_SERIALIZATION, and D3D12_FEATURE_CROSS_NODE

### ISSUE THREAD

**Issue by gongminmin** [MicrosoftDocs/feedback#1489]
In this page: https://docs.microsoft.com/en-us/windows/desktop/api/d3d12/ne-d3d12-d3d12_feature, D3D12_FEATURE_D3D12_OPTIONS4, D3D12_FEATURE_SERIALIZATION, and D3D12_FEATURE_CROSS_NODE are without document. Their correspondent data structures are not documented neither.

**Comment by ryanmajidi** [comment]
@GrantMeStrength Can you please take a look at this issue?

**Comment by stevewhims** [comment]
Thanks for bringing this issue to our attention. The topics have been fixed/restored, and published. 

Thanks again!
Steve
