### ISSUE TITLE
Please support Vietnamese document!

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#149]
Thank you for your develop document its useful but i can't complete understand some part. Please support Vietnamese document

----------
⚠ Idea migrated from UserVoice

**Created By:** Nguyễn Liêm
**Created On:** 2017/05/02 16:26:21 +0000
**Votes at Migration:** 2
**Supporters at Migration:** 1

**Comment by Powerhelmsman** [comment]
As Sonja mentioned, Docs does support Vietnamese, so we will close this issue.
