### ISSUE TITLE
Table of contents not translated in localized docs

### ISSUE THREAD

**Issue by MSDN-WhiteKnight** [MicrosoftDocs/feedback#1490]
**Describe the bug**
In some localized docs, such as [.NET Guide](https://docs.microsoft.com/ru-ru/dotnet/standard/), table of contents are displayed in english, despite its entries are translated in [toc.yml file](https://github.com/dotnet/docs.ru-ru/blob/live/toc.yml)

**To Reproduce**
1. Go to https://docs.microsoft.com/ru-ru/dotnet/standard/ page
2. Table of contents in left panel not translated

**Expected behavior**
Table of contents should be translated into corresponding language

**Screenshots**

![screenshot](https://i.stack.imgur.com/UTUDT.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge
 - Version 42.17134.1.0

**Comment by sudeepku** [comment]
@SonjaSaltzman - could you please review this localization issue?

**Comment by SonjaSaltzman** [comment]
Assigning to @DavidPrio cc: @JasonCard

**Comment by JasonCard** [comment]
@DavidPrio I'm currently following up on this issue, so reassigning to me.

**Comment by CeciAc** [comment]
Duplicate of https://github.com/dotnet/docs.ja-jp/issues/595

**Comment by JasonCard** [comment]
Hi @MSDN-WhiteKnight 
Thank you for reporting this issue.
Table of contents are now displaying localized version in live page, so closing this issue.

Kind regards,
Microsoft DOCS International Team
cc @CeciAc @SonjaSaltzman @sudeepku
