### ISSUE TITLE
The table in Scheduling Priorities doc is not correctly rendered.

### ISSUE THREAD

**Issue by luyaok** [MicrosoftDocs/feedback#1493]
**Link to article:**
https://docs.microsoft.com/en-us/windows/desktop/ProcThread/scheduling-priorities#base-priority

**Problem:**
At this part: "The following table shows the base priority for combinations of process priority class and thread priority value."
But it is not appearing as a table.

**Comment by ryanmajidi** [comment]
@drewbatgit Can you please take a look at this issue?

**Comment by drewbatgit** [comment]
Thanks for calling out this issue. The formatting has been fixed.
