### ISSUE TITLE
No localize repository for "windowsserverdocs"

### ISSUE THREAD

**Issue by ALilyG** [MicrosoftDocs/feedback#1494]
**Link to article:**
original:
https://docs.microsoft.com/en-us/windows-server/get-started-19/whats-new-19
translate:
https://docs.microsoft.com/ja-jp/windows-server/get-started-19/whats-new-19

**Problem:**
I want to fix up translation for Windows Server documents, but no Edit/Feedback button in Japanese pages.
Please Create Japanese repository and another languages for "windowsserverdocs"

https://github.com/MicrosoftDocs/windowsserverdocs

**Comment by ryanmajidi** [comment]
@SonjaSaltzman Could you please take a look at this issue?

**Comment by SonjaSaltzman** [comment]
Assigning to @v-nidolc @DavidPrio

**Comment by CeciAc** [comment]
@nokura user is reporting they cannot edit the translation because there's no edit nor feedback button
how should we proceed?
@DavidPrio

**Comment by SonjaSaltzman** [comment]
We are currently only enabling feedback buttons for human translated content.  This is a project we freshly onboarded in our team, so @v-nidolc can provide an ETA for when we will enable.

**Comment by v-nidolc** [comment]
We plan to do this next by the end of May, after we complete testing the initial localization (currently in progress).

**Comment by CeciAc** [comment]
Hi team 
any update on this?
best

**Comment by CeciAc** [comment]
It looks like this is fixed, please confirm @ALilyG 
@SonjaSaltzman @v-nidolc

**Comment by CeciAc** [comment]
It looks like this is fixed, please confirm @ALilyG 
@SonjaSaltzman @v-nidolc

**Comment by ALilyG** [comment]
I confirmed this. Thanks for handling it.
