### ISSUE TITLE
Tiny Error in doc 

### ISSUE THREAD

**Issue by luyaok** [MicrosoftDocs/feedback#1495]
**Link to article:**
https://docs.microsoft.com/en-us/windows/desktop/ProcThread/creating-a-child-process-with-redirected-input-and-output

**Problem:**
This sentence

Therefore, before creating the child process, the parent process uses the SetHandleInformation function to ensure that the write handle for the child process's standard input and the read handle for the child process's standard **input** cannot be inherited.

Seems to be 

Therefore, before creating the child process, the parent process uses the SetHandleInformation function to ensure that the write handle for the child process's standard input and the read handle for the child process's standard **output** cannot be inherited.

**Comment by ryanmajidi** [comment]
@drewbatgit Can you please take a look at this?

**Comment by drewbatgit** [comment]
Thanks for reporting this issue. The text has been fixed.
