### ISSUE TITLE
Xamarin.Android 'Earlier version archive' link results in 404

### ISSUE THREAD

**Issue by gkarabin** [MicrosoftDocs/feedback#1499]
**Describe the bug**
Clicking on a Xamarin.Android 'Earlier version archive' link results in 404

**To Reproduce**
1. Go to https://docs.microsoft.com/en-us/xamarin/android/release-notes/9/9.3
2. Click on 'Earlier version archive' in the left-hand table of contents.
3. My browser navigates to a page with a 404 content not found error (https://docs.microsoft.com/en-us/xamarin/releases/#android)

**Expected behavior**
My browser navigates to a page with release notes for older versions of Xamarin.Android.

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.5
 - Browser Both chrome and safari
 - Version 74.0.3729 and 12.1.1

**Comment by ryanmajidi** [comment]
@brendanzagaeski Can you please take a look at this issue?

**Comment by brendanzagaeski** [comment]
Thanks for bringing this up! This should be all set now. The link in the side bar now points to a GitHub repository where you can browse the previous release notes in subdirectories corresponding to the past version numbers.

@ryanmajidi, feel free to close this issue now, or if you notice anything I might have missed, feel free to raise follow up questions. Thanks!

**Comment by svick** [comment]
The same problem still occurs for [Xamarin.iOS release notes](https://docs.microsoft.com/en-us/xamarin/ios/release-notes/).

**Comment by brendanzagaeski** [comment]
Tidying up this old resolved issue

#please-close
