### ISSUE TITLE
Broken links on https://docs.microsoft.com/en-us/rest/api/vsts/git/

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#15]
Several links are broken on this page:

https://docs.microsoft.com/en-us/rest/api/vsts/git/

----------
⚠ Idea migrated from UserVoice

**Created By:** Arlo Siemsen
**Created On:** 2018/02/28 20:43:06 +0000
**Votes at Migration:** 1
**Supporters at Migration:** 1

**Comment by dend** [comment]
Content issue so will be closed soon. @erickson-doug @hellosnow - can you please take a look?
