### ISSUE TITLE
font size choices

### ISSUE THREAD

**Issue by docs-product** [MicrosoftDocs/feedback#150]
I've got used to the font size on the usual MSDN docs website.  The docs.ms.com font size (and perhaps line spacing) is different enough to notice.  Could you consider providing a smaller font choice?

----------
⚠ Idea migrated from UserVoice

**Created By:** Caleb D
**Created On:** 2017/05/01 15:30:13 +0000
**Votes at Migration:** 1
**Supporters at Migration:** 1

**Comment by ShevaDas** [comment]
Thanks for the feedback. We're designing for a combination of different screen sizes, resolutions, and devices as well as an optimal easy-to-read line length. Right now, we're at a pretty standard font size when compared to other documentation and long-format sites. However, the designers are considering some updates to the site and will keep this feedback in mind.

**Comment by dend** [comment]
@ShevaDas assigning to you for follow-up once the changes are live.

**Comment by ShevaDas** [comment]
@dend We're not currently planning to make any changes but this will be one of the things we consider as we go through an overall review of site UX over the next few months. I'll keep you updated if we do wind up changing it.

**Comment by dendeli-msft** [comment]
Closing this item as we've made some updates to our site typography.
