### ISSUE TITLE
Same line in article

### ISSUE THREAD

**Issue by egor2116x** [MicrosoftDocs/feedback#1500]
Same line in article

https://docs.microsoft.com/en-us/windows/desktop/api/ole2/nf-ole2-olesetclipboard

![aaa](https://user-images.githubusercontent.com/13168310/57881757-c6c0e280-782a-11e9-9187-d08046ab329d.png)

**Comment by ryanmajidi** [comment]
@drewbatgit Can you please take a look at this issue?

**Comment by drewbatgit** [comment]
Thanks for reporting this issue. The extraneous sentence has been removed.
