### ISSUE TITLE
Edit button missing in localized docs

### ISSUE THREAD

**Issue by MSDN-WhiteKnight** [MicrosoftDocs/feedback#1502]
**Describe the bug**
Localized pages (such as https://docs.microsoft.com/ru-ru/dotnet/framework/wpf/graphics-multimedia/bitmap-effects-overview) does not show "Edit" ("Редактировать") button in upper right panel. 

**To Reproduce**
1. Go to https://docs.microsoft.com/ru-ru/dotnet/framework/wpf/graphics-multimedia/bitmap-effects-overview
2. See that edit button is missing

**Expected behavior**
Edit button should be present (or the text _Вы можете предложить лучший перевод, щелкнув кнопку "Редактировать"... (You can suggest better translation by clicking "Edit" button...)_ should be removed from notice in the top panel, if edit button is removed intentionally).

**Screenshots**

![screenshot](https://i.stack.imgur.com/XRiXJ.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge
 - Version 42.17134.1.0

**Comment by ayatokura** [comment]
The same problem occurs with Japanese localized sites (such as https://docs.microsoft.com/ja-jp/windows/wsl/about) as well.

Desktop (please complete the following information):
    OS: Windows 10 Pro Japanese Version1903 Build18362.113
    Browser: Mozilla firefox 66.0.5

**Comment by ryanmajidi** [comment]
This looks to be similar to #1494. @SonjaSaltzman Can you please take a look and confirm?

**Comment by SonjaSaltzman** [comment]
Assigning to @DavidPrio cc: @JasonCard

**Comment by MSDN-WhiteKnight** [comment]
Just FYI, a localized repository for dotnet docs exists (https://github.com/dotnet/docs.ru-ru). I can even submit pull request manually via GitHub interface. The Edit button in MS Docs interface was present before, it disappeared only recently.

**Comment by nschonni** [comment]
External contributions was turned off in this commit https://github.com/dotnet/docs.ru-ru/commit/928245e63c1e55310195d51c266119d9b53c606a by @lautarol

**Comment by CeciAc** [comment]
Hi @JasonCard can you please check this issue?

**Comment by SonjaSaltzman** [comment]
Hello @MSDN-WhiteKnight !  You are right, localization repositories exist, and you could make a PR there.  We currently discourage users from making PRs on all machine translated content (and have thus turned off the "edit" button for most of this content), as we want to focus on the human translated content.  We can in the future not guarantee that we will process machine-translated content PRs, so it would be best to focus your efforts on the human translated topics, which will have much greater impact.  We use our human translated content to train the machine translation engines, so over time this will improve the quality of **all** translations.

**Comment by MSDN-WhiteKnight** [comment]
Thanks for the explaination. If Edit button is turned off intentionally for machine translated documents, the notice in the top panel should not display _Вы можете предложить лучший перевод, щелкнув кнопку "Редактировать"..._ (_You can suggets better translation by clicking "Edit" button..._)

**Comment by JasonCard** [comment]
Hi @MSDN-WhiteKnight, 

Thank you for pointing out the issue in our disclaimer for machine translated content. 
That's a good point and we are following up to change that disclaimer message.
I will go ahead and close this issue for now.

Kind regards,
Microsoft DOCS International Team
cc @SonjaSaltzman @DavidPrio @CeciAc
