### ISSUE TITLE
Why were english tooltips removed?

### ISSUE THREAD

**Issue by MSDN-WhiteKnight** [MicrosoftDocs/feedback#1503]
Machine-translated localized docs previously displayed english text in tooltips when hovering mouse over translated text, but now they don't. Why was this removed? It was a very useful functionality.

**Comment by ryanmajidi** [comment]
@SonjaSaltzman Can you please take a look at this?

**Comment by SonjaSaltzman** [comment]
@DavidPrio and FYI @bodhigautam

**Comment by CeciAc** [comment]
Hello, @MSDN-WhiteKnight 
If you've used Docs in a language other than English, you may have used a feature that allowed you to hover over phrases in some localized articles to view their English translation. Unfortunately, this feature does not meet accessibility guidelines and has been removed from the site. We're working on an improved and fully accessible replacement, so stay tuned.
Kind regards,
Microsoft DOCS International Team

**Comment by mskQ9** [comment]
I propose that the switch which changing to English fixes to the upper end of a page.
