### ISSUE TITLE
Content issue in RasEnumConnections Doc

### ISSUE THREAD

**Issue by Drake-Wu** [MicrosoftDocs/feedback#1504]
**Link to article:**
https://docs.microsoft.com/en-us/windows/desktop/api/ras/nf-ras-rasenumconnectionsa
https://docs.microsoft.com/en-us/windows/desktop/api/ras/nf-ras-rasenumconnectionsw

**Problem:**
"The most reliable way to enumerate..." Description in code format

**Comment by ryanmajidi** [comment]
@drewbatgit Can you please take a look at this? Seems to be similar to #1505

**Comment by KalleOlaviNiemitalo** [comment]
It seems this was fixed already; "The most reliable way to enumerate" is not formatted as code now.
