### ISSUE TITLE
Content issue in SE_OBJECT_TYPE Doc

### ISSUE THREAD

**Issue by BESTRIVENinCN** [MicrosoftDocs/feedback#1505]
**Link to article:**
https://docs.microsoft.com/zh-cn/windows/desktop/api/accctrl/ne-accctrl-_se_object_type

**Problem:**
"The name string for a directory service object must be ..." Description in code format

**Comment by ryanmajidi** [comment]
@drewbatgit Can you please take a look at this?

**Comment by drewbatgit** [comment]
This issue has been fixed. Note that the URL of this API has changed to: https://docs.microsoft.com/zh-cn/windows/desktop/api/accctrl/ne-accctrl-se_object_type (the underscore between "ne_accctrl-" and "se_object_type" has been removed).
