### ISSUE TITLE
pdf download link broken

### ISSUE THREAD

**Issue by misterpeel** [MicrosoftDocs/feedback#1506]
The link that should allow us to download a PDF version of the Microsoft Azure GxP Guidelines is broken.

### Steps to reproduce the behavior:
1. Go to https://gallery.technet.microsoft.com/Azure-GxP-Guidelines-ab1b98d9
2. Click on 'Download Microsoft Azure GxP Guidelines (April 2018).pdf'
3. License Terms of Use notice appears.
4. Scroll to bottom of Terms of Use
5. Click on 'I agree'
6. Terms of Use notice closes and page reloads. 
7. No file is downloaded

### Expected behavior
A downloadable file should appear.

### Desktop:
I've tried using Windows 10, Windows 2016, Microsoft Edge, Internet Explorer, Google Chrome (and sundry other operating systems and network sites :) )

**Comment by ryanmajidi** [comment]
@misterpeel Is this still an issue? I've tested this on chrome and edge on windows 10 and android 9. In all of those combinations the pdf downloaded after I clicked agree.
