### ISSUE TITLE
Constants SQL_TYPE_UTCDATETIME and SQL_TYPE_UTCTIME aren't declared anywhere

### ISSUE THREAD

**Issue by lsmith999999** [MicrosoftDocs/feedback#1508]
The constants SQL_TYPE_UTCDATETIME and SQL_TYPE_UTCTIME are currently cited here:

SQL Data Types
[https://docs.microsoft.com/en-us/sql/odbc/reference/appendixes/sql-data-types?view=sql-server-2017](url)

But they're not declared in any header I can find, nor can I find any relevant info on them after extensive searching. Why are they documented?

**Comment by ryanmajidi** [comment]
@rloutlaw Can you please take a look at this issue?

**Comment by rloutlaw** [comment]
@ryanmajidi This needs to be assigned to the SQL docs team, who manages their reference docs.

**Comment by ryanmajidi** [comment]
Moving this to the [sql docs repo issue 2248](https://github.com/MicrosoftDocs/sql-docs/issues/2248)
