### ISSUE TITLE
Show entries in a sorted order

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#151]
Show entries in a sorted order

----------
⚠ Idea migrated from UserVoice

**Created By:** Anonymous
**Created On:** 2017/04/27 14:29:34 +0000
**Votes at Migration:** 4
**Supporters at Migration:** 4

**Comment by dend** [comment]
Submitted by anonymous user, so not clear where this is applicable. Closing for now as not enough info was presented.
