### ISSUE TITLE
powershell 5.0 can't download . 

### ISSUE THREAD

**Issue by doudousha** [MicrosoftDocs/feedback#1511]
url: 
https://docs.microsoft.com/en-us/powershell/scripting/install/installing-windows-powershell?view=powershell-6

error: 
https://www.microsoft.com/en-us/download/details.aspx?id=54616

We are sorry, the page you requested cannot be found.
The URL may be misspelled or the page you're looking for is no longer available.

**Comment by ryanmajidi** [comment]
@doudousha This issue seems resolved. Please open a new bug if this is persisting for you.
