### ISSUE TITLE
“Updating Windows Update Agent Header Files” download link broken

### ISSUE THREAD

**Issue by newIDforLOL** [MicrosoftDocs/feedback#1514]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

**Link to article:**
Tell us where exactly a problem occurs.
Updating Windows Update Agent Header Files
https://docs.microsoft.com/en-us/windows/desktop/Wua_Sdk/updating-windows-update-agent-header-files

**Problem:**
What's wrong with the article?
The download link broken
http://go.microsoft.com/fwlink/p/?linkid=185614

**Comment by ryanmajidi** [comment]
@GrantMeStrength can you please take a look at this issue?

**Comment by GrantMeStrength** [comment]
Links have been corrected, thank you.
