### ISSUE TITLE
Learning module "Build a containerized web application with Docker" missing links

### ISSUE THREAD

**Issue by ezfepo** [MicrosoftDocs/feedback#1515]
The first module in "Administer containers in Azure" [link](https://docs.microsoft.com/en-us/learn/paths/administer-containers-in-azure/) which is "Build a containerized web application with Docker" could not be reached; all links are missing.
https://docs.microsoft.com/en-us/learn/modules/intro-to-containers/index
https://docs.microsoft.com/en-us/learn/modules/intro-to-containers/1-introduction
https://docs.microsoft.com/en-us/learn/modules/intro-to-containers/2-deploy-docker-image-locally
https://docs.microsoft.com/en-us/learn/modules/intro-to-containers/3-exercise-deploy-docker-image-locally
https://docs.microsoft.com/en-us/learn/modules/intro-to-containers/4-create-custom-docker-image
https://docs.microsoft.com/en-us/learn/modules/intro-to-containers/5-exercise-create-custom-docker-image
https://docs.microsoft.com/en-us/learn/modules/intro-to-containers/6-deploy-docker-image-to-container-instance
https://docs.microsoft.com/en-us/learn/modules/intro-to-containers/7-exercise-deploy-docker-image-to-container-instance
https://docs.microsoft.com/en-us/learn/modules/intro-to-containers/8-summary

Thanks

**Comment by ezfepo** [comment]
The first module in "Administer containers in Azure" [link](https://docs.microsoft.com/en-us/learn/paths/administer-containers-in-azure/) which is "Build a containerized web application with Docker" could not be reached; all links are missing.
https://docs.microsoft.com/en-us/learn/modules/intro-to-containers/index
https://docs.microsoft.com/en-us/learn/modules/intro-to-containers/1-introduction
https://docs.microsoft.com/en-us/learn/modules/intro-to-containers/2-deploy-docker-image-locally
https://docs.microsoft.com/en-us/learn/modules/intro-to-containers/3-exercise-deploy-docker-image-locally
https://docs.microsoft.com/en-us/learn/modules/intro-to-containers/4-create-custom-docker-image
https://docs.microsoft.com/en-us/learn/modules/intro-to-containers/5-exercise-create-custom-docker-image
https://docs.microsoft.com/en-us/learn/modules/intro-to-containers/6-deploy-docker-image-to-container-instance
https://docs.microsoft.com/en-us/learn/modules/intro-to-containers/7-exercise-deploy-docker-image-to-container-instance
https://docs.microsoft.com/en-us/learn/modules/intro-to-containers/8-summary

Thanks

**Comment by benktesh** [comment]
I also experienced this issue (as of this morning), appears it is resolved now.

**Comment by ryanmajidi** [comment]
@sadadow Can you please take a look at this issue?

**Comment by ezfepo** [comment]
Hello everyone.
It is working now, at least I am able to.

Thanks
