### ISSUE TITLE
Documentation: Example given does not reflect the command Start-AzureRmJitNetworkAccessPolicy or Start-AzJitNetworkAccessPolicy

### ISSUE THREAD

**Issue by huahua82** [MicrosoftDocs/feedback#1520]
**Describe the bug**
Documentation: Example given does not reflect the command Start-AzureRmJitNetworkAccessPolicy or Start-AzJitNetworkAccessPolicy

**To Reproduce**
1. Go to https://docs.microsoft.com/en-us/powershell/module/azurerm.security/start-azurermjitnetworkaccesspolicy?view=azurermps-6.13.0
2. Look at example 1, it is using Set-AzureRmJitNetworkAccessPolicy instead of Start-AzureRmJitNetworkAccessPolicy

Same goes to this link https://docs.microsoft.com/en-us/powershell/module/az.security/start-azjitnetworkaccesspolicy?view=azps-2.1.0

**Expected behavior**
They should be using example of command Start-AzureRmJitNetworkAccessPolicy or Start-AzJitNetworkAccessPolicy respectively

**Screenshots**
- None

**Desktop (please complete the following information):**
- NA

**Smartphone (please complete the following information):**
- NA
**Additional context**

**Comment by ryanmajidi** [comment]
@huahua82 this issue has been moved to [its respective repo](https://github.com/Azure/azure-powershell/issues/9296).
