### ISSUE TITLE
API Browser: APIs for ASP.NET Core 3.0 Preview are missing

### ISSUE THREAD

**Issue by mikeharder** [MicrosoftDocs/feedback#1521]
**Description**
Many APIs appear to be missing from ASP.NET Core 3.0.

**Repro Steps**
1. Search for "httprequest" in ASP.NET Core 2.2
  A. https://docs.microsoft.com/en-us/dotnet/api/?view=aspnetcore-2.2&term=httprequest
  B. Many results, including the second result `Microsoft.AspNetCore.Http.HttpRequest` I was searching for
2. Repeat search in ASP.NET Core 3.0
  A. https://docs.microsoft.com/en-us/dotnet/api/?view=aspnetcore-3.0&term=httprequest
  B. Only 3 results, and `Microsoft.AspNetCore.Http.HttpRequest` is missing

**Comment by ryanmajidi** [comment]
@mikeharder I've moved this topic to the repo for this content.
