### ISSUE TITLE
please delete my MSDN profile

### ISSUE THREAD

**Issue by 3DdeepAI** [MicrosoftDocs/feedback#1526]
I want to delete my MSDN forum profile 
(but not my full account)

I was on this page:
**How do I delete my MSDN profile?**
https://social.microsoft.com/Forums/en-US/24a5346f-e4ab-4153-b044-5232b4343ce7/how-do-i-delete-my-msdn-profile?forum=Profile&irgwc=1&OCID=AID681541_aff_7806_1246483&tduid=(ir__rmhpm6zcmgkfrzjokk0sohz30n2xmeapqdgbi6dv00)(7806)(1246483)(%28633f9562125ed380d55dfa0d6f8dc33c%29%2881561%29%28686431%29%28at103219_a107739_m12_p14530_cDE_sunknown%29%28%29)(633f9562125ed380d55dfa0d6f8dc33c)&irclickid=_rmhpm6zcmgkfrzjokk0sohz30n2xmeapqdgbi6dv00
which gave me a link to:
**Contact Us**
https://technet.microsoft.com/en-us/cc512759.aspx?f=255&MSPPError=-2147217396
which lead me to this page:
https://github.com/MicrosoftDocs/feedback/issues

**Comment by ryanmajidi** [comment]
@saldana Can you please take a look at this?

**Comment by saldana** [comment]
Checking...

**Comment by saldana** [comment]
Hello @3DdeepAI. If you decide to delete your MSDN Profile, you will delete your account for any MSDN social activities as well: Forums, Blogs, Wikis, Galleries. 

To delete your profile:

1. Go to your MSDN Profile page: https://social.msdn.microsoft.com/profile/. Sign in if you have not signed in already.
2. Click on your profile link on the top bar. This will open your profile page with all your activities
3. Click on Privacy tab
4. Scroll all the way down to the Danger Zone, and click on it.
5. Click on Delete your account.

**Comment by 3DdeepAI** [comment]
Thank you very much for your answer
