### ISSUE TITLE
Source code in article "Working with NVMe drives" is wrong

### ISSUE THREAD

**Issue by o0zhhl0o** [MicrosoftDocs/feedback#1527]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

**Link to article:**: https://docs.microsoft.com/zh-cn/windows/desktop/FileIO/working-with-nvme-devices
Tell us where exactly a problem occurs.

**Problem:**
What's wrong with the article?

This article has source code of sending "get log", "get feature" and "identify" command.
The code of "get log" and "get feature" can be used directly, but the code of "identify" can't be used. 
The code of "Example: NVMe Identify query" contains some wrong code:
---------------------------------------------------------------------------------------------------
    ZeroMemory(buffer, bufferLength);
    query = (PSTORAGE_PROPERTY_QUERY)buffer;  
    protocolDataDescr = (PSTORAGE_PROTOCOL_DATA_DESCRIPTOR)buffer;  
    protocolData = (PSTORAGE_PROTOCOL_SPECIFIC_DATA)query->AdditionalParameters;  

    query->PropertyId = StorageDeviceProtocolSpecificProperty;  
    query->QueryType = PropertyStandardQuery;  

    protocolData->ProtocolType = ProtocolTypeNvme;  
    protocolData->DataType = NVMeDataTypeLogPage;  
    protocolData->ProtocolDataRequestValue = NVME_LOG_PAGE_HEALTH_INFO;  
    protocolData->ProtocolDataRequestSubValue = 0;  
    protocolData->ProtocolDataOffset = sizeof(STORAGE_PROTOCOL_SPECIFIC_DATA);  
    protocolData->ProtocolDataLength = sizeof(NVME_HEALTH_INFO_LOG);  

    //  
    // Send request down.  
    //  
    result = DeviceIoControl(DeviceList[Index].Handle,  
                             IOCTL_STORAGE_QUERY_PROPERTY,  
                             buffer,  
                             bufferLength,  
                             buffer, 
                             bufferLength,  
                             &returnedLength,  
                             NULL  
                             );  
-----------------------------------------------------------------------------------------------------
These are the codes of “get log” and should not appear here. When I delete this part of code, the example code of "identify" can work. Maybe the code and document writer just use "ctrl +c" and "ctrl + v" :)
Please delete these codes. Thank you.

**Comment by ryanmajidi** [comment]
@GrantMeStrength Can you please take a look at this issue?

**Comment by GrantMeStrength** [comment]
Assigned to the content owner, thank you!
