### ISSUE TITLE
Dead link to Visual Studio project Download

### ISSUE THREAD

**Issue by OliverZ** [MicrosoftDocs/feedback#1528]
**Link to article:**
https://msdn.microsoft.com/library/ff847525.aspx

**Problem:**
Dead link to: A Visual Studio project with source code is available to accompany this topic: Download. (http://go.microsoft.com/fwlink/?linkid=199841)

**Comment by ryanmajidi** [comment]
@Rick-Anderson Can you please take a look at this issue?

**Comment by Rick-Anderson** [comment]
Correct. The download is no longer available. We state before the article:
 We're no longer updating this content regularly
