### ISSUE TITLE
Add IdentityModel APIs

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#153]
Can't see anything from Microsoft.IdentityModel.Tokens in there. E.g. SecurityKey. How can I find what classes implement this abstract class?

----------
⚠ Idea migrated from UserVoice

**Created By:** Matt Frear
**Created On:** 2017/04/13 13:24:50 +0000
**Votes at Migration:** 3
**Supporters at Migration:** 3

**Comment by Powerhelmsman** [comment]
@dend Can you response to this issue?

**Comment by dend** [comment]
This seems like a missing API, and in this case - targeting AAD. @twitchax - do you happen to know who is responsible for this package: [Microsoft.IdentityModel.Tokens](https://www.nuget.org/packages/Microsoft.IdentityModel.Tokens/)

**Comment by twitchax** [comment]
@skwan may be able to help.  @skwan, do you know who owns this library?

**Comment by dend** [comment]
Ping @skwan on library ownership.

**Comment by dend** [comment]
Following-up here - we aim to publish the APIs for the package later this week.

**Comment by dend** [comment]
The APIs are [now available](https://docs.microsoft.com/en-us/dotnet/api/Microsoft.IdentityModel.Tokens?view=azure-dotnet)
