### ISSUE TITLE
Bing Image API reference document link is broken. 

### ISSUE THREAD

**Issue by themetaschemer** [MicrosoftDocs/feedback#1530]
**Describe the bug**

The link the Image Search API reference is broken on the Bing Image Search API Documentation page. It results in a 404. 

**To Reproduce**
1. Go to https://docs.microsoft.com/en-us/azure/cognitive-services/bing-image-search/
2. Click on Reference, and then click on Bing Image Search API v7
3. See error 
"404 - Page not found
Hmm, we couldn't find this link, but here are some related search results that may be helpful."

**Expected behavior**
I expect to see an API reference document.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Mac OS Mojave
 - Browser [e.g. chrome, safari] Chrome Version 74.0.3729.157 (Official Build) (64-bit)

**Comment by ryanmajidi** [comment]
@rloutlaw Can you please take a look at this issue?

**Comment by rloutlaw** [comment]
This was a problem last week in the content but we've fixed it on the live site now.

**Comment by ryanmajidi** [comment]
Closing this issue then.

@themetaschemer If this persists for you please open a new issue.
