### ISSUE TITLE
Openpublishing bot produces too much notifications

### ISSUE THREAD

**Issue by MSDN-WhiteKnight** [MicrosoftDocs/feedback#1531]
In localized repositories, an Openpublishing bot produces tons of notifications such as:

>The PR is not being built because the target branch live is filtered in .openpublishing.publish.config.json on live branch.

Example: https://github.com/dotnet/docs.ru-ru/pull/193 

And it's unclear what this means and why branch is filtered. Is it bug? Notifications are produced whenever there's any activity in pull request, which is a little annoying.

Are PRs in localized repositories supposed to be built? If yes, could you fix the issue that prevents it. If no, could you get rid of these notifications or at least make them one per PR?

**Comment by ryanmajidi** [comment]
@MSDN-WhiteKnight after every change to a branch in a PR the content needs to be rebuilt. This is why you get a notification every time. Are the subsequent commits relevant to the original PR? If not, one solution is to create a branch specific to the PR. Localized repos are built. 

@Khairunj Do you know what the criteria is for a branch being filtered?

**Comment by MSDN-WhiteKnight** [comment]
Pull request in localized API Docs are now built, but the build fails each time (see https://github.com/MicrosoftDocs/feedback/issues/1679). Pull request in other localized repositories still don't build and generate the same notifiaction.

**Comment by MSDN-WhiteKnight** [comment]
Closing because localized repositories are now closed
