### ISSUE TITLE
ADLS Gen2 REST API - File list - maxResults is not recognized, maxresults is.

### ISSUE THREAD

**Issue by MisiekBest** [MicrosoftDocs/feedback#1532]
**Link to article:**
https://docs.microsoft.com/en-us/rest/api/storageservices/datalakestoragegen2/path/list

**Problem:**
The parameter maxResults in URI Parameters is not recognized by the API.
It throws "Server failed to authenticate the request".

I'm not sure if this is something related to the CanonicalizedResource section and lowercasing or parameter in URI.

**Anyway using lowercased maxresults (instead of maxResults) helps.**

I can provide a code in PowerShell that proves this issue.

**Comment by guntaled** [comment]
I noticed the same and can provide C# code that proves the issue.

I also noticed that Databricks mark this as "known issue":
![image](https://user-images.githubusercontent.com/18587994/58499291-b109c200-8134-11e9-87f9-ce8891abd467.png)
(https://docs.databricks.com/spark/latest/data-sources/azure/azure-datalake-gen2.html)

**Comment by ryanmajidi** [comment]
@rloutlaw can you please take a loot at this issue?

**Comment by guntaled** [comment]
Today and yesterday, documentation page is missing names at all:
![image](https://user-images.githubusercontent.com/18587994/59071327-05b6e680-8873-11e9-9703-7755efa00afd.png)

**Comment by rloutlaw** [comment]
Thanks for the bug report-this is a known issue we'd isolated and we will be pushing a fix shortly.

**Comment by guntaled** [comment]
@MisiekBest, I found that the canonicalized resources have to be lowercased: https://docs.microsoft.com/en-us/rest/api/storageservices/authorize-with-shared-key#constructing-the-canonicalized-resource-string
Doesn't matter in uri itself.

**Comment by MisiekBest** [comment]
Thank you @guntaled . That explains a lot ...
I have not noticed this before :(
In that case, my reported error is not an error, but just a requirement according to the specification.

@ryanmajidi , @rloutlaw 
We can close this issue.

To other users:
In the section "Constructing the Canonicalized Resource String" of the documentation [Authorize with Shared Key](https://docs.microsoft.com/en-us/rest/api/storageservices/authorize-with-shared-key) documentation, there is a point: "4. Convert all parameter names to lowercase.".
So if you will get this error, make sure that you are lowercasing all parameters in your canonicalized resource string.

Thanks!
