### ISSUE TITLE
Content issue in CryptGetProvParam Doc

### ISSUE THREAD

**Issue by BESTRIVENinCN** [MicrosoftDocs/feedback#1534]
**Link to article:**
https://docs.microsoft.com/en-us/windows/desktop/api/Wincrypt/nf-wincrypt-cryptgetprovparam

**Problem:**
"If PP_ENUMALGS, or PP_ENUMALGS_EX is set..." wrong content format in Parameter: pdwDataLen in Note.

**Comment by ryanmajidi** [comment]
@drewbatgit Can you please take a look at this issue?

**Comment by drewbatgit** [comment]
Thanks for reporting this issue. The formatting has been fixed.
