### ISSUE TITLE
Spelling mistake on microsoft site

### ISSUE THREAD

**Issue by monicajagani** [MicrosoftDocs/feedback#1536]
**Link to article:**
https://docs.microsoft.com/en-us/office365/enterprise/

**Problem:**
Spelling of word "intelligence" is incorrect. 
Spelling on page - intellgence 
Correct spelling - intelligence 

> Office 365 Enterprise
> Microsoft Office 365 provides powerful online cloud services that enable collaboration, security and compliance, mobility, and **intellgence** and analytics.

**Comment by ryanmajidi** [comment]
@monicajagani Thank you for bringing this to our attention. I fixed this and it should be live soon.
