### ISSUE TITLE
Documentation link broken for the bing spell check api 404

### ISSUE THREAD

**Issue by zhenyufu** [MicrosoftDocs/feedback#1538]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

**Link to article:**
https://docs.microsoft.com/en-us/azure/cognitive-services/bing-spell-check/
`Bing Spell Check API v7` or `Bing Spell Check API v7 Reference`

**Problem:**
Documentation link broken for the bing spell check api: 
https://docs.microsoft.com/en-us/rest/api/cognitiveservices/docs-ref-conceptual/cognitiveservices-bingsearch/bing-spell-check-api-v7-reference

**Comment by ryanmajidi** [comment]
@zhenyufu Thank you for bringing this to our attention. It looks like the link in the article has been fixed. Here is the correct link:
https://docs.microsoft.com/en-us/rest/api/cognitiveservices-bingsearch/bing-spell-check-api-v7-reference

Please reopen this issue if you are still having issues.
