### ISSUE TITLE
Allow third-party .net libraries (like NHibernate, Castle Windsor, etc) to put their documentation into the API Browser

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#154]
Please, allow popular third-party .net libraries (like NHibernate, Castle Windsor, etc) to put their documentation into the API Browser

----------
⚠ Idea migrated from UserVoice

**Created By:** victor
**Created On:** 2017/04/12 08:46:18 +0000
**Votes at Migration:** 1
**Supporters at Migration:** 1

**Comment by Powerhelmsman** [comment]
Thanks for the idea! We may revisit this in the future, but this is not something we can do right now. For third parties, they can use DocFX, which is open source. Refer to http://dotnet.github.io/docfx/
