### ISSUE TITLE
New Value of '9: Commit Transaction' on ENVCHANGE is correct?

### ISSUE THREAD

**Issue by naoto-ogawa** [MicrosoftDocs/feedback#1540]
**Specifications**
[MS-TDS]: Tabular Data Stream Protocol
2.2.7.8 ENVCHANGE

**Link to article:**
https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-tds/2b3eb7e5-d43d-4d1b-bf4d-76b9e3afc791

**Problem:**
Section 2.2.7.8 ENVCHANGE says 

|Type|Old Value|New Value|
----|----|---- 
|9: Commit Transaction | OLDVALUE = B_VARBYTE | NEWVALUE = "0x00"|
|10: Rollback Transaction | OLDVALUE = B_VARBYTE | NEWVALUE = %x00|
|11: Enlist DTC Transaction | OLDVALUE = B_VARBYTE | NEWVALUE = %x00|

NEWVALUE of No.9 is a string literal (double quoted expression) as oppose to NEWVALUE of No.10 or 11 which is a hexadecimal. Is this true? (It seems to me this is just a typo.)

**Comment by snadendl** [comment]
Hello naoto-ogawa, your observation seems correct. We will verify this and update the specification.

**Comment by mairaw** [comment]
This seems to have been fixed. Closing.
