### ISSUE TITLE
After a system crash the temp content of a message is displayed in html mode

### ISSUE THREAD

**Issue by Trebly** [MicrosoftDocs/feedback#1541]
**Describe the bug**
After a system crash, the temp content of a message is displayed in HTML mode.
I got a system urgency stop (heat).
When the system and browser (chrome) had restarted, I got back the content of the message but with the display "html" of the content (there is no button to return to WYSIWYG mode.
**To Reproduce**
- probably the same context stop the computer without closing applications

**Probable cause** 👍 - the editor configuration is not restored when chrome displays the tab from current dynamic backup and the button to display WYSIWYG is not aéctivated in the restored editor configuration 

**Expected behavior**
Return to the standard configuration of the editor of messages and go on editing

**Screenshots**
view of the display of the message editing after restart (note: a blank line because I have ended the edition encoding directly using HTML)
![B90525-Technet-display_new_message-html-01](https://user-images.githubusercontent.com/1492375/58368949-4702da00-7ef4-11e9-85f7-4c49885ab66a.jpg)

**Desktop (please complete the following information):**
 - OS: [ win10 pro 1803 17134.765]
 - Browser [chrome]
 - Version [Version 74.0.3729.169 (Build officiel) (64 bits)]

Best regards

**Comment by ryanmajidi** [comment]
@saldana can you please take a look at this issue?

**Comment by saldana** [comment]
@Trebly thanks a lot for reporting the bug. Unfortunately, this bug does not meet the bar for us to fix it in the forums today. So I am closing this issue. Thanks.
