### ISSUE TITLE
What is the meaning of the 4 in the upper right corner of the icon?

### ISSUE THREAD

**Issue by newpost** [MicrosoftDocs/feedback#1542]
![image](https://user-images.githubusercontent.com/1679093/58373677-7ea96a80-7f64-11e9-9cac-4938931cf8a6.png)

**Comment by ryanmajidi** [comment]
@newpost What page is this from?

**Comment by newpost** [comment]
when create asp.net mvc project in visual studio 2017.

**Comment by ryanmajidi** [comment]
@newpost Please see [this page for submitting a problem with VS](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019)
