### ISSUE TITLE
GetEnvironmentStrings is pointing to the wrong content

### ISSUE THREAD

**Issue by chuacw** [MicrosoftDocs/feedback#1543]
**Describe the bug**
On this page, https://docs.microsoft.com/en-us/windows/desktop/procthread/environment-variables the link for GetEnvironmentStrings is not pointing to a description of GetEnvironmentStrings.

**To Reproduce**
1. Go to https://docs.microsoft.com/en-us/windows/desktop/procthread/environment-variables
2. Click on 'GetEnvironmentStrings' (which links to [https://msdn.microsoft.com/en-us/library/ms683187(v=VS.85).aspx](https://msdn.microsoft.com/en-us/library/ms683187(v=VS.85).aspx) )
3. See that the newly opened page has nothing on GetEnvironmentStrings

**Expected behavior**
See the newly opened page describes GetEnvironmentStrings.

**Comment by ryanmajidi** [comment]
@drewbatgit Can you please take a look at this?

**Comment by drewbatgit** [comment]
The redirection for this link has been updated and it now points to the GetEnvironmentStrings function. Thanks for your feedback on this issue.
