### ISSUE TITLE
Wrong link in REST operation groups table

### ISSUE THREAD

**Issue by harlecin** [MicrosoftDocs/feedback#1544]
Wrong link in table

Go to:
https://docs.microsoft.com/en-us/rest/api/containerregistry/

In table 'REST operation groups':

- 'Runs' and 'Tasks' both link to 'Runs'

**Comment by ryanmajidi** [comment]
@mmacy Can you please take a look at this issue?

**Comment by mmacy** [comment]
@ryanmajidi Fix is merge, should be live by this afternoon or tomorrow morning at the latest.

@harlecin Thanks for catching and notifying us on this, Christoph! 🥇

**Comment by mmacy** [comment]
@ryanmajidi This fix is live, you may now close this issue.

**Comment by mmacy** [comment]
#please-close

**Comment by harlecin** [comment]
sry:( got redirected into spam for some reason
