### ISSUE TITLE
Deprecation of the File History API

### ISSUE THREAD

**Issue by Fleex255** [MicrosoftDocs/feedback#1547]
**Link to article:**
[File History API](https://docs.microsoft.com/en-us/windows/desktop/devnotes/file-history-api) and all functions and interfaces in that section

**Problem:**
In the Windows 10 build 17134 (and possibly earlier) SDK, `FhCfg.h` has marked all File History COM interfaces `#pragma deprecated`. `FhSvcCtl.h` has notes like these on all File History service functions:

    __declspec(deprecated("FhServiceOpenPipe is deprecated and might not work on all platforms. For more info, see MSDN."))

None of the relevant documentation pages mention the deprecation, nor could I find any information about it on MSDN by searching. Please update the File History API pages to reflect the deprecation and suggest the API that should be used instead.

**Comment by ryanmajidi** [comment]
@drewbatgit Can you please take a look at his?

**Comment by drewbatgit** [comment]
Thanks for the feedback. I have included a deprecation note for all of the APIs labeled as deprecated within the fhcfg.h and fhsvcctl.h headers.

**Comment by User1785604260** [comment]
@drewbatgit, I know this is an old issue, but I came across it trying to find more information on this deprecation. The original issue here mentioned suggesting the API that should be used instead, but I don't see that included in the deprecation notes.

I also couldn't find any information on the deprecation here (not sure if this is the right place to look): https://learn.microsoft.com/en-us/windows/whats-new/deprecated-features

Do you know what are the APIs that should be used instead?
