### ISSUE TITLE
Dead links

### ISSUE THREAD

**Issue by anthonynz** [MicrosoftDocs/feedback#1548]
https://docs.microsoft.com/en-us/previous-versions/dn785092(v=msdn.10)#watch-videos 

Contains links that no longer exists :(

**Comment by anthonynz** [comment]
Master site link - http://microsoft.com/pth
Redirects to https://docs.microsoft.com/en-us/previous-versions/dn785092(v=msdn.10)

**Comment by ryanmajidi** [comment]
@anthonynz Thank you for bringing this to our attention. This is a very old archive topic. Unfortunately those videos are no longer available. We are removing them from this page.
