### ISSUE TITLE
Use short well know type names

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#155]
Right now Monitor.​Wait is displayed as:

Monitor.​Wait(​System.​Object,​System.​Int32,​System.​Boolean)

Much easier to read version would be:
Monitor.​Wait(object, int, bool)

----------
⚠ Idea migrated from UserVoice

**Created By:** Pavel Krymets
**Created On:** 2017/04/11 19:09:44 +0000
**Votes at Migration:** 17
**Supporters at Migration:** 17

**Comment by dend** [comment]
This has been addressed, see:
https://docs.microsoft.com/en-us/dotnet/api/system.threading.monitor.wait?view=netframework-4.7.2#System_Threading_Monitor_Wait_System_Object_System_Int32_System_Boolean_
