### ISSUE TITLE
dead links

### ISSUE THREAD

**Issue by miktuo** [MicrosoftDocs/feedback#1550]
Build a containerized web application with Docker -pages has dead links:
for example: https://docs.microsoft.com/en-us/Azure/containers/1-introduction

**Comment by sudeepku** [comment]
@miktuo thanks for reporting this issue. Could you provide link to the topic where you are seeing the broken link

**Comment by miktuo** [comment]
It was all the subpages in this address:

https://docs.microsoft.com/en-us/learn/paths/administer-containers-in-azure/

But, now they seem to be fixed, they were giving error about week in time before today.
