### ISSUE TITLE
Windows Setup.exe command-line options priority high 

### ISSUE THREAD

**Issue by Karl-WE** [MicrosoftDocs/feedback#1552]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

**Link to article:**
Tell us where exactly a problem occurs.

**Problem:**
What's wrong with the article?

**Comment by ryanmajidi** [comment]
@Karl-WE Can you elaborate on this issue? Are you still having this problem?

**Comment by Karl-WE** [comment]
Ho @ryanmajidi I've created this on my mobile but now I see that all additional information and links are missing in the posting.  I am sorry for this. 


**affected article:** 
https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/windows-setup-command-line-options


**documented command line option:**
/Priority Normal | Tells Windows Setup to increase the thread priority from low to high for feature updates through Windows Update. This option is available in Windows 10, version 1709 and later Note: Media based installations already run at normal priority.



**undocumented command line option:**
/Priority high


**reference:**
https://twitter.com/gwblok/status/1109280203661021184?ref_src=twsrc%5Etfw%7Ctwcamp%5Etweetembed%7Ctwterm%5E1109280203661021184&ref_url=https%3A%2F%2Fwww.borncity.com%2Fblog%2F2019%2F03%2F30%2Fwindows-10-langsame-inplace-upgrade-installation-beschleunigen%2F

**Comment by Karl-WE** [comment]
hi is there any new on this matter @ryanmajidi. Thank you very much. 
I've tried 16+ upgrades to 1903 now with /priority high and all of them worked fine. Have not made any measures if they would be faster with this switch compared to the documented /priority normal switch.

**Comment by ryanmajidi** [comment]
@GrantMeStrength Can you please take a look at this issue?

**Comment by GrantMeStrength** [comment]
I'm sorry, I checked with the feature team and there are no plans to document this at present.
