### ISSUE TITLE
1903 patch release notes are missing (any language)

### ISSUE THREAD

**Issue by Karl-WE** [MicrosoftDocs/feedback#1553]
**🛑 IMPORTANT**: this page has no comment section 
Would be great to have for reporting patch related issues when official reference is given 

**Link to article:**
https://support.microsoft.com/en-us/help/4099479/windows-10-update-history

**Problem:**
The update history is missing 1903 18362.x patch notes as it is officially out of insider now. 
I've checked de-de / en-us.

**Comment by Karl-WE** [comment]
this one is fixed for en-us
https://support.microsoft.com/en-us/help/4099479/windows-10-update-history

de-de still missing 1903 history
https://support.microsoft.com/de-de/help/4099479/windows-10-update-history

**Comment by ryanmajidi** [comment]
@GrantMeStrength Can you please take a look at this issue?

**Comment by Karl-WE** [comment]
This issue is closed. The patch notes are now listed in the update history 
https://support.microsoft.com/de-de/help/4498140/windows-10-update-history
https://support.microsoft.com/en-us/help/4498140/windows-10-update-history
@GrantMeStrength @ryanmajidi
