### ISSUE TITLE
Dead link - Help in SSPR portal

### ISSUE THREAD

**Issue by DustinTroxel** [MicrosoftDocs/feedback#1555]
When you go to the Self Service Password Reset portal (short link https://aka.ms/sspr or https://aka.ms/ssprsetup), click on the '?' in the above right corner and click on help, you are redirected to a page that results in a 404. 

I'm hailing from the Netherlands, so the URL I get directed to is: "https://docs.microsoft.com/nl-nl/azure/active-directory/user-help/myapps-portal-end-user-troubleshoot".

I tried "https://docs.microsoft.com/en-us/azure/active-directory/user-help/myapps-portal-end-user-troubleshoot" as well, but got the same 404 result. 

Can the page please be retrieved or the redirect be changed? 

We're trying to set the SSPR portal live for our customer, but they are complaining that the Help link is dead. We do not like providing 'broken' features to our customers, so please fix this. 
We will try to explain to them that availability of a Microsoft webpage is beyond our control, but I really hope this Bug report will help.

**Comment by ryanmajidi** [comment]
Hi @DustinTroxel, thank you for bringing this to our attention. While we work on fixing this, the correct link is https://docs.microsoft.com/en-us/azure/active-directory/user-help/my-apps-portal-end-user-troubleshoot
