### ISSUE TITLE
wrong link

### ISSUE THREAD

**Issue by hallazzang** [MicrosoftDocs/feedback#1556]
**Link to article:** https://docs.microsoft.com/en-us/windows/desktop/debug/pe-format#coff-file-header-object-and-image

**Problem:** For the field `Characteristics`, link for Characteristics in description points wrong location to [DLL Characteristics](https://docs.microsoft.com/en-us/windows/desktop/debug/pe-format#dll-characteristics), not [Characteristics](https://docs.microsoft.com/en-us/windows/desktop/debug/pe-format#characteristics).

**Comment by ryanmajidi** [comment]
@drewbatgit Can you please take a look at this issue?

**Comment by drewbatgit** [comment]
Thanks for reporting this issue. The link has been fixed.

**Comment by hallazzang** [comment]
@drewbatgit I'll close this issue, thank you.
