### ISSUE TITLE
Problem upload file for Post in LinkedIn V2 API

### ISSUE THREAD

**Issue by adrianlaraperez88** [MicrosoftDocs/feedback#1558]
Problem upload file for Post in LinkedIn V2 API

![Capture](https://user-images.githubusercontent.com/19626181/58496597-92192900-8150-11e9-9a3b-18209a803296.PNG)

My function:
`function registerUpload($organization_id,$type='learning-image',$relationshipType='OWNER',$is_person=false){
		$request = array( 'json' => array('registerUploadRequest' => [
																		'owner' => $is_person ? 'urn:li:person:'.$organization_id :'urn:li:organization:'.$organization_id,
																		'recipes' => [
																						'urn:li:digitalmediaRecipe:'.$type
																					 ],
																		'serviceRelationships' => [	
																									'relationshipType'=> $relationshipType,
																									'identifier'=> "urn:li:userGeneratedContent"
																									
																								   ]
																	 ]));
																	 
																	 
		 return $this->linkedin->post($this->version.'/assets?action=registerUpload', $request);
	}`

**Comment by ryanmajidi** [comment]
@tonyxu-io Can you take a look at this issue?

**Comment by tonyxu-io** [comment]
@chrisou Can you take a look at this issue?

**Comment by chrisou** [comment]
@adrianlaraperez88 the request body format you're providing does not match what we have documented here: https://docs.microsoft.com/en-us/linkedin/consumer/integrations/self-serve/share-on-linkedin?context=linkedin/consumer/context#create-a-text-share

**Comment by adrianlaraperez88** [comment]
@chrisou yes, but the problem is when need upload videos or images,

**Comment by chrisou** [comment]
@adrianlaraperez88 is there a reason you're using the type "learning-image"?

**Comment by adrianlaraperez88** [comment]
I am reading this in the documentation

**Comment by chrisou** [comment]
Can you share a link to the doc you're referring to?

**Comment by adrianlaraperez88** [comment]
https://docs.microsoft.com/en-us/linkedin/marketing/integrations/community-management/shares/vector-asset-api#register-an-upload

**Comment by chrisou** [comment]
Please follow the documentation outlined here: https://docs.microsoft.com/en-us/linkedin/consumer/integrations/self-serve/share-on-linkedin?context=linkedin/consumer/context#create-an-image-share

**Comment by adrianlaraperez88** [comment]
Sorry for the time I waiting for LinkedIn approve APP.

`
	/*	
		@param $type Values= feedshare-video, learning-image(default), ads-video
		@param $relationshipType Values= GENERIC, OWNER(default), CREATOR
		@comments For more inforation please read in: https://docs.microsoft.com/en-us/linkedin/marketing/integrations/community-management/shares/vector-asset-api#register-an-upload
	*/
	function registerUpload($organization_id,$is_person=false,$type='feedshare-image',$relationshipType='OWNER'){
		$request = array( 'json' => array('registerUploadRequest' => [
'owner' => $is_person ? 'urn:li:person:'.$organization_id :'urn:li:organization:'.$organization_id,
'recipes' => [
                   'urn:li:digitalmediaRecipe:'.$type
                 ],
'serviceRelationships' => [	
                                      'relationshipType'=> $relationshipType,	
                                       'identifier'=> "urn:li:userGeneratedContent" ]
		]));
 return $this->linkedin->post($this->version.'/assets?action=registerUpload', $request);
	}
`
Call:

`print_r($linkedIn->registerUpload('39DCQ9_XIs',true));die;`

Error:
`
Array
(
    [serviceErrorCode] => 100
    [message] => Field Value validation failed in REQUEST_BODY: Data Processing Exception while processing fields [/registerUploadRequest/serviceRelationships/$*]
    [status] => 403
)
`

**Comment by adrianlaraperez88** [comment]
![image](https://user-images.githubusercontent.com/19626181/61389080-a941e080-a88e-11e9-95b2-cf60ca9b1581.png)

**Comment by adrianlaraperez88** [comment]
Array
(
    [message] => com.linkedin.publishing.util.common.ResponseException: urn:li:developerApplication:40909954 does not have permission to create ugc posts
    [status] => 401
)

**Comment by chrisou** [comment]
@adrianlaraperez88 please submit a ticket to linkedin.zendesk.com

**Comment by adrianlaraperez88** [comment]
I have sent many emails but they never answer me, they have for me -5 points in support.

**Comment by adrianlaraperez88** [comment]
I send again the email now solicited permission for Video Post. Ty, I fixed the problem.

**Comment by adrianlaraperez88** [comment]
Thank you team at least here they respond. +1
