### ISSUE TITLE
HPC Documentation is horrid

### ISSUE THREAD

**Issue by rphilipak** [MicrosoftDocs/feedback#1560]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

**Link to article:**
all HPC PACK 2016 documentation.

**Problem:**
Every single piece of documentation is crap.  Its obvious that it's generated from code and not one single person cares enough to actually take the time to make the documentation useful.  To add insult to injury, it is impossible to get back to HPC 2012 pack documentation - everything redirects to 2016.  FIX THIS CRAP NOW!  I have been using HPC for many years and you have now completely screwed up the only real source of any useable documentation.

**Comment by ryanmajidi** [comment]
@rphilipak Do you have any specific examples of issues with the current documentation? Are you referring to the reference topics?

@dlepow Can you take a look at the issue of HPC pack 2012 redirecting to 2016?

**Comment by dlepow** [comment]
@rphilipak - Thanks for getting in touch with us. It sounds like your are trying to reach previously published HPC Pack content in the MSDN Library, which now redirects to HPC Pack 2016 documentation on docs.microsoft.com. You don't mention what guidance you were trying to reach. Was it API reference content, conceptual docs, how-to guides? That will help us understand where we might have a gap in the documentation. 

Also adding @coolmay from the HPC Pack team for his insights. Thanks!

**Comment by dlepow** [comment]
@rphilipak - Just to add: There is [archived content](https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/hpc-server-2012-R2-and-2012/jj899572(v%3dws.11)) available for HPC Pack 2012/2012 R2. This content is not regularly maintained but may be what you are looking for?

**Comment by rphilipak** [comment]
Yes, the archived content is usable, but I don’t understand why it isn’t “rolled forward” for HPC 2016?  Many concepts should have stayed the same, therefore the associated documentation should have remained fairly relevant.  I get that the move towards a more cloud centric solution would invalidate some concepts but the majority would still have been usable.

To make matters worse, most searches always redirect to HPCPack 2016 which is devoid of usable documentation.

**Comment by dlepow** [comment]
@rphilipak - We've noted your feedback and will close this issue for now. I agree with many of your observations about opportunities to improve the doc experience. If you have further questions or feedback about HPC Pack, please visit the [Windows HPC forum](https://social.microsoft.com/Forums/en-US/home?category=windowshpc) or email the team at hpcpack@microsoft.com. Thank you!
#please-close

**Comment by dlepow** [comment]
#please-close
