### ISSUE TITLE
Unable to provide page feeback

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/feedback#1566]
**Describe the bug**
In the Streams section at https://docs.microsoft.com/en-us/stream/, none of the pages have the Provide Page Feedback button that I see on many other sections of the site.

**To Reproduce**
Go to any page in the Streams section and look for the feedback buttons, they are missing

**Expected behavior**
I expect to be able to provide feedback to the page authors 

**Screenshots**
![image](https://user-images.githubusercontent.com/4058555/58644539-7720f300-82cf-11e9-89c0-b77ab092b056.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser -any

**Additional context**

**Comment by ryanmajidi** [comment]
@DeanGross feedback is disabled from some repos. In that case please submit feedback here.
