### ISSUE TITLE
'<' and '>' should be '&lt;' and '&gt;'

### ISSUE THREAD

**Issue by oeman** [MicrosoftDocs/feedback#1567]
Less than and greater than signs are not correctly escaped, resulting in text not being displayed correctly.  

1. Go to https://docs.microsoft.com/en-us/windows/desktop/ad/how-a-service-registers-its-spns
2. Search in page for "/".
3. Both current instances are incorrect.  They should be "<service class>"/"<host>".
4. Search in page for "".
5. The single instance should be "<host>".

The problem is obvious from looking at the page source:

`&quot;<service class="">/<host>&quot;`

The <> pairs are being interpreted as html tags by the browser and therefore do not display.

Other pages under https://docs.microsoft.com/en-us/windows/desktop/ad have the same problem, for example, at least:

https://docs.microsoft.com/en-us/windows/desktop/ad/name-formats-for-unique-spns
https://docs.microsoft.com/en-us/windows/desktop/ad/how-a-service-composes-its-spns
https://docs.microsoft.com/en-us/windows/desktop/ad/how-clients-compose-a-serviceampaposs-spn

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 74.0.3729.169

**Comment by ryanmajidi** [comment]
@GrantMeStrength Can you please take a look at this issue?

**Comment by GrantMeStrength** [comment]
Thanks for bringing this to our attention. Looks like it's quite widespread. Our top people are working on a fix!

**Comment by GrantMeStrength** [comment]
Corrected all the topics I could find with this issue.
