### ISSUE TITLE
TechNet Forum Language Support [ Azerbaijani ]

### ISSUE THREAD

**Issue by h-sadeghpour** [MicrosoftDocs/feedback#1569]
**Is your feature request related to a problem? Please describe.**
It is really hard to a country experts whom using Microsoft products and they cannot have support in their own language, also have forum to discussions in TechNet.

**Describe the solution you'd like**
Having a separate forum like other countries forum would be geart for Azerbaijani language speaking Microsoft products fans. I'm MCT Regional Lead for Azerbaijan and I can feel It that It is hard to lost in other forums and finally not to find answer to whom cannot speak or write in english language.

**Comment by ryanmajidi** [comment]
@saldana Can you please take a look at this issue?

**Comment by saldana** [comment]
@h-sadeghpour we thank you for your feedback. I agree with you that not having a forum in a language makes difficult for people to ask and follow questions in English. We do not have any immediate plans to open a forum for Azerbaijani at this moment. We are adding this to our backlog to consider it for the future. Thank you!
