### ISSUE TITLE
Link to reference source code

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#157]
Add a link to reference source code to easily view source of current class/method

----------
⚠ Idea migrated from UserVoice

**Created By:** Giorgi D
**Created On:** 2017/04/06 20:01:40 +0000
**Votes at Migration:** 71
**Supporters at Migration:** 71

**Comment by dend** [comment]
Duplicate of #433

**Comment by gewarren** [comment]
Great news - the core .NET libraries now have links to source code!
Example: https://learn.microsoft.com/dotnet/api/system.string.chars?view=net-8.0
