### ISSUE TITLE
Garbled texts and break link in PowerShell Module Browser

### ISSUE THREAD

**Issue by ToMakeSense** [MicrosoftDocs/feedback#1574]
#### Link to article:
A few garbled texts in below three links:
* [Windows 10 and Windows Server 2016 PowerShell Module Reference](https://docs.microsoft.com/en-us/powershell/module/?view=win10-ps)
* [Windows 8.1 and Windows Server 2012 R2 PowerShell Module Reference](https://docs.microsoft.com/en-us/powershell/module/?view=winserver2012r2-ps)
* [Windows 8 and Windows Server 2012 PowerShell Module Reference](https://docs.microsoft.com/en-us/powershell/module/?view=winserver2012-ps) 

Break link in [Azure Service Management PowerShell Module Reference ](https://docs.microsoft.com/en-us/powershell/module/?view=azuresmps-4.0.0)

#### Problem:
Totally three garbled texts(�) each can be found in `adrms` Module section and `grouppolicy` Module section in the first three links.

Break link can be find for `Azure`(https://docs.microsoft.com/en-us/powershell/module/Azure/?view=azuresmps-4.0.0) Module, the actual URL is: https://docs.microsoft.com/en-us/powershell/azure/servicemanagement/overview?view=azuresmps-4.0.0

**Comment by ryanmajidi** [comment]
@rloutlaw Can you please take a look at this issue?

**Comment by ryanmajidi** [comment]
Moved issue to [powershell repo](https://github.com/MicrosoftDocs/windows-powershell-docs/issues/1100)

**Comment by ToMakeSense** [comment]
@nschonni Hi Nick, I sitll found the garbled texts(�) there even you guys close MicrosoftDocs/windows-powershell-docs/pull/1084 and MicrosoftDocs/windows-powershell-docs/issues/1100

**Comment by nschonni** [comment]
@ToMakeSense I just submitted the PR, I'm not sure how long it takes to publish after it get's merged.
I'd suggest opening a new issue over on that repo for the broken link
