### ISSUE TITLE
Code block's font is not set for ja-jp

### ISSUE THREAD

**Issue by 0giso** [MicrosoftDocs/feedback#1575]
**Describe the bug**
Code block's font is not set for ja-jp. Which font is used depends on the browser.

**To Reproduce**
1. Go to https://docs.microsoft.com/ja-jp/aspnet/core/tutorials/first-mvc-app/details?view=aspnetcore-2.2. (Any pages under https://docs.microsoft.com/ja-jp/ can reproduce.)
2. See code block. Font depends on the browser. (Chrome, Edge, IE).

**Expected behavior**
Use fonts similar to consolas for code blocks in any languages, any browsers.

**Desktop (please complete the following information):**
 - OS: Windows 10 17134.799
 - Browser Edge, IE11

**Additional context**
AWS document use consolas for code blocks in any language, any browsers. This is my expectation for docs.microsoft.com.
https://docs.aws.amazon.com/lambda/latest/dg/lambda-dotnet-coreclr-deployment-package.html
https://docs.aws.amazon.com/es_es/lambda/latest/dg/lambda-dotnet-coreclr-deployment-package.html
https://docs.aws.amazon.com/fr_fr/lambda/latest/dg/lambda-dotnet-coreclr-deployment-package.html
https://docs.aws.amazon.com/it_it/lambda/latest/dg/lambda-dotnet-coreclr-deployment-package.html
https://docs.aws.amazon.com/ja_jp/lambda/latest/dg/lambda-dotnet-coreclr-deployment-package.html
https://docs.aws.amazon.com/de_de/lambda/latest/dg/lambda-dotnet-coreclr-deployment-package.html
https://docs.aws.amazon.com/ko_kr/lambda/latest/dg/lambda-dotnet-coreclr-deployment-package.html
https://docs.aws.amazon.com/pt_br/lambda/latest/dg/lambda-dotnet-coreclr-deployment-package.html
https://docs.aws.amazon.com/zh_cn/lambda/latest/dg/lambda-dotnet-coreclr-deployment-package.html
https://docs.aws.amazon.com/zh_tw/lambda/latest/dg/lambda-dotnet-coreclr-deployment-package.html

**Comment by SonjaSaltzman** [comment]
@DavidPrio cc: @JasonCard

**Comment by Rick-Anderson** [comment]
From @0giso in [this comment](https://github.com/aspnet/AspNetCore.Docs.ja-jp/issues/241#issuecomment-498447382)
@Rick-Anderson @CeciAc Yes, followings are other examples which has same issue.
https://docs.microsoft.com/ja-jp/dotnet/csharp/tour-of-csharp/program-structure
https://docs.microsoft.com/ja-jp/azure/azure-functions/functions-dotnet-dependency-injection

**Comment by 0giso** [comment]
This issue began to occur in late May, 2019. Until then consolas was used for code in ja-jp.

https://docs.microsoft.com/ja-jp/aspnet/core/tutorials/first-mvc-app/details?view=aspnetcore-2.2
![Details](https://user-images.githubusercontent.com/17273712/58884651-c88c1080-871b-11e9-9b01-60946dc94a03.PNG)

https://docs.microsoft.com/ja-jp/dotnet/csharp/tour-of-csharp/program-structure
![ProgramStructure](https://user-images.githubusercontent.com/17273712/58884665-cd50c480-871b-11e9-8b3e-6a34d91582a8.PNG)

**Comment by JasonCard** [comment]
Hi @0giso 
Thank you for reporting this issue and sharing details. 
We are following up on this as engineering issue and will update when resolved.

cc @Rick-Anderson @CeciAc @bodhigautam @SonjaSaltzman

**Comment by bodhigautam** [comment]
@0giso This issue has been fixed. cc @JasonCard @CeciAc @SonjaSaltzman

**Comment by JasonCard** [comment]
@bodhigautam Thank you, I've confirmed this issue is fixed and looks good.
