### ISSUE TITLE
terminal-services-shortcut-keys **Missing keys: **

### ISSUE THREAD

**Issue by nnpcYvIVl** [MicrosoftDocs/feedback#1576]
**Link to article:**
https://docs.microsoft.com/en-us/windows/desktop/termserv/terminal-services-shortcut-keys

**Problem:**
The article starts with these two lines which are confusing.
```
The following is a list of the Remote Desktop Services shortcut keys.

**Missing keys: **
```
The list of shortcut keys should follow the first line and the `**Missing keys: **` section should be moved down to the bottom. The title `Missing keys` should also be rewritten to be more clear e.g. `What to do when your keyboard is missing a required key`.

**Comment by GrantMeStrength** [comment]
Thanks! Correction has been submitted.
