### ISSUE TITLE
Simple bug in Direct2D tutorial that make the demo application crash at runtime.

### ISSUE THREAD

**Issue by ESSONIA** [MicrosoftDocs/feedback#1577]
https://docs.microsoft.com/en-us/windows/desktop/direct2d/direct2d-quickstart

**Describe the bug**
A wrong API call that casting pointer-type(8 bytes) to long(4 bytes).
Bug at SetWindowLongPtrW() in DemoApp::WndProc(...) at <Part 4: Render Direct2D Content>

        if (message == WM_CREATE)
        {
            LPCREATESTRUCT pcs = (LPCREATESTRUCT)lParam;
            DemoApp *pDemoApp = (DemoApp *)pcs->lpCreateParams;

            ::SetWindowLongPtrW(  <------ This API expected a LONG_PTR as third parameter
                hwnd,
                GWLP_USERDATA,
                PtrToUlong(pDemoApp) <------ PtrToUlong() casts pointer to long which causes overflow: replace with (LONG_PTR)(pDemoApp) would be a fix.
                );

            result = 1;
        }

Later call of GetWindowLongPtrW() got invalid pointer of DemoApp* type. Which makes the demo crash when dereference this pointer.

**To Reproduce**
Copy all the data into a new project, then Build and run.

**Expected behavior**
A simple demo window as the tutorial shows at start.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ryanmajidi** [comment]
@GrantMeStrength Can you please take a look at this issue?

**Comment by GrantMeStrength** [comment]
Assigned to content owner, thanks.

**Comment by stevewhims** [comment]
Hi, @ESSONIA! Thanks for filing this issue; a contributor has now fixed the code in the topic via a pull-request.

I'll go ahead and close this issue now. You can always reopen if necessary. ~Steve
