### ISSUE TITLE
Link to PCSC Workgroup is broken

### ISSUE THREAD

**Issue by dev-pete** [MicrosoftDocs/feedback#1578]
**Link to article:**
https://docs.microsoft.com/en-us/windows-hardware/test/hlk/testref/smart-card-reader-testing-prerequisites

**Problem:**
The link to PCSC Workgroup (This card set can be purchased from the [PC/SC website](https://go.microsoft.com/fwlink/?LinkId=228902).) is broken. To get started with WHQL certification for smart card reader driver, the PCSC test cards are needed. But when the site is now offline, how can we purchase the test cards?
Please help. Thanks.

![pcscworkgroup-link](https://user-images.githubusercontent.com/11574791/58798621-ae780280-8635-11e9-950e-f6d655d1065b.png)

**Comment by ryanmajidi** [comment]
@GrantMeStrength Can you please take a look at this?

**Comment by KalleOlaviNiemitalo** [comment]
It  looks like the PC/SC Workgroup moved the page to <https://www.pcscworkgroup.com/specifications/test-cards/>.

**Comment by GrantMeStrength** [comment]
Assigned to hardware team.

**Comment by EliotSeattle** [comment]
This is fixed in the source and will go live when the content rebuilds overnight.

Thanks, @dev-pete for catching this. @ryanmajidi can you please close this?
