### ISSUE TITLE
Won't search short class names

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#158]
Searching for the GC class doesn't return any results  E.g. https://docs.microsoft.com/en-us/dotnet/api/?term=GC If I search https://docs.microsoft.com/en-us/dotnet/api/?term=System.GC does though. This feels closely related to the "Support searching for parts of API names" request though.

----------
⚠ Idea migrated from UserVoice

**Created By:** Chris Klein
**Created On:** 2017/04/06 14:04:04 +0000
**Votes at Migration:** 7
**Supporters at Migration:** 7

**Comment by Powerhelmsman** [comment]
#log-suggestion @dend

**Comment by botcrane** [comment]
🚀 **ATTENTION**: [Internal request](https://ceapex.visualstudio.com/web/wi.aspx?pcguid=7d644393-99ad-41c8-ac53-7fa79294c720&id=26100) logged.

**Comment by dend** [comment]
Given that this item has an internal tracking issue and there is no definitive time frame in which the fix will be deployed, I am going to close this issue for now. We continue to look at how we can improve the API Browser search and integrated API experiences.
