### ISSUE TITLE
UI Automation Error Codes incomplete and invalid for HResults shown

### ISSUE THREAD

**Issue by rbeesley** [MicrosoftDocs/feedback#1580]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

**Link to article:**
https://docs.microsoft.com/en-us/windows/desktop/WinAuto/uiauto-error-codes

**Problem:**
UIA_E_TIMEOUT has the HResult shown of 0x, it should be 0x80131505 as it is the same as COR_E_TIMEOUT, seen in this blog: https://blogs.msdn.microsoft.com/yizhang/2010/12/17/interpreting-hresults-returned-from-netclr-0x8013xxxx/. 0x is just wrong as it isn't a valid HResult.

**Comment by ryanmajidi** [comment]
@GrantMeStrength can you please take a look at this issue?

**Comment by GrantMeStrength** [comment]
Assigned to writer

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks for the head's up, @rbeesley. The topic has been updated with the correct info.

**Comment by rootsmusic** [comment]
#please-close
