### ISSUE TITLE
RSS feed for this?

### ISSUE THREAD

**Issue by xNiklasJern** [MicrosoftDocs/feedback#1581]
Please make it possible to subscribe to a RSS feed for this page.

https://docs.microsoft.com/en-us/windows/release-information/windows-message-center

**Comment by dendeli-msft** [comment]
Given that this is content-related, and is not directly related to functionality on docs.microsoft.com, I will close this item. We are constantly working to make sure that you can better keep track of content and its updates (see: [bookmarks](https://docs.microsoft.com/en-us/teamblog/announcing-bookmarks)). We will continue evolving that functionality in the future, so keep the feedback coming!
