### ISSUE TITLE
I am getting error at &amp in the code I am using windows 10 and visual studio 2017 version

### ISSUE THREAD

**Issue by HemaShalini** [MicrosoftDocs/feedback#1582]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ryanmajidi** [comment]
@HemaShalini Can you provide some more info about the issue you are having? Where is this issue occurring?

**Comment by ryanmajidi** [comment]
Closing issue. @HemaShalini Please open a new issue if this is still a problem.
