### ISSUE TITLE
How to activate ADFv2 trigger via AzureRM template?

### ISSUE THREAD

**Issue by tknerr** [MicrosoftDocs/feedback#1583]
**Link to article:**
https://docs.microsoft.com/en-us/azure/templates/microsoft.datafactory/2018-06-01/factories/triggers

**Problem:**
Whenever I create a scheduled trigger via AzureRM it ends up being deactivated, and I manually have to activate it via the ADFv2 GUI. 

I tried via `"runtimeState": "Started"` but that didn't help either (seems to be a read-only property that is being set on API side but can't be set on client side)

Example AzureRM snippet:
```json
    {
      "name": "[concat(variables('dataFactoryName'), '/nightly-trigger')]",
      "type": "Microsoft.DataFactory/factories/triggers",
      "apiVersion": "2018-06-01",
      "properties": {
        "annotations": [],
        "runtimeState": "Started",
        "pipelines": [
          {
            "pipelineReference": {
              "referenceName": "[variables('pipelineName')]",
              "type": "PipelineReference"
            },
            "parameters": {}
          }
        ],
        "type": "ScheduleTrigger",
        "typeProperties": {
          "recurrence": {
            "frequency": "Hour",
            "interval": 24,
            "startTime": "2019-04-11T01:00:00Z",
            "timeZone": "UTC"
          }
        }
      },
      "dependsOn": [
        "[variables('dataFactoryId')]",
        "[concat(variables('dataFactoryId'), '/pipelines/', variables('pipelineName'))]"
      ]
    },
```

How can it be created in activated state?

**Comment by ryanmajidi** [comment]
@tfitzmac Can you please take a look at this issue?

**Comment by djpmsft** [comment]
Hi there, apologies for the delayed response on this issue. The product team is currently investigating this and will have a response shortly

**Comment by djpmsft** [comment]
After investigating the issue, unfortunately there is no way to create an activated trigger. ARM templates only support PUT actions, but start is a separate POST action. To activate a trigger, you must explicitly call the start API either via UX, Powershell or whatever ADF SDK you are using after creation. This is due to runtime state being a readonly property that a user cannot explicitly set.

**Comment by tknerr** [comment]
Hi @djpmsft, thanks for elaborating!

Are there any plans to change that in the future, or is the current situation how it is intended to be?

I'm asking, because we are trying to do the whole deployment via ARM, but this introduces extra deployment scripts / steps required before and after ARM deployment of datafactories. From our experience so far with deploying Azure resources via ARM this seems to be quite uncommon, as for all other resources no extra steps were needed and they could be deployed just via the template.

**Comment by djpmsft** [comment]
This is intended. Starting and stopping triggers can affect long-running pipelines, we want users to explicitly start and stop them.

**Comment by tknerr** [comment]
Thanks for clarification @djpmsft !

**Comment by ssisjoost** [comment]
You can either use a little [PowerShell](https://microsoft-bitools.blogspot.com/2021/11/adf-release-use-script-to-enable.html)  or set the endTime property via the ARM template to something in the past (but make sure it's not before startTime).

**Comment by sethreidnz** [comment]
> This is intended. Starting and stopping triggers can affect long-running pipelines, we want users to explicitly start and stop them.

While I understand this concern and it makes sense why not expose an ARM resource that lets people explicitly do it like App Service do with swapping slots for example. If the concern is about it being explicit couldn't ADF allow an explicit turning on of triggers via ARM?

Current approach requires a lot of extra work and discourages complete automation of your infrastructure which is presumably not what Azure wants to do?

**Comment by acarter24** [comment]
Discovered this behaviour today, by comparison seems inconsistent with container behaviour.

Containers are created and automatically go into the started state, with no way to to create them in the 'stopped' state.
Triggers are the opposite; created in the 'deactivated' state and no way to created them in the 'active' state.
