### ISSUE TITLE
Author notification bot didn't pick up author name

### ISSUE THREAD

**Issue by MSDN-WhiteKnight** [MicrosoftDocs/feedback#1586]
**Describe the bug**
In pull request https://github.com/MicrosoftDocs/cpp-docs/pull/1052 the author notification bot produced the message

>Thanks for your contribution! The author, @, has been notified to review your proposed change.

The actual author name is missing, despite the [docfx.json](https://github.com/MicrosoftDocs/cpp-docs/blob/master/docs/docfx.json#L149) for that repository does specify the author name for edited article

```
"author": {
...
        "build/**.md": "corob-msft"
```
(The path for the edited article is `build/reference/vmb-vmg-representation-method.md`).
 
**To Reproduce**
No exact steps to reproduce. Only happens in some cases.

**Expected behavior**
Author notification bot should pick up author name if it is present in docfx.json.

**Comment by ryanmajidi** [comment]
@cillroy Can you please take a look at this issue?

**Comment by MSDN-WhiteKnight** [comment]
This seems no longer relevant. Notifications were changed and now request review from authors correctly.
