### ISSUE TITLE
Please provide à custom scrollbar for dark theme

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#159]
The native scrollbar may be light and high contrast with the background. It's quite disturbing.

----------
⚠ Idea migrated from UserVoice

**Created By:** Lionel
**Created On:** 2017/04/06 13:48:43 +0000
**Votes at Migration:** 12
**Supporters at Migration:** 11

**Comment by Powerhelmsman** [comment]
#log-suggestion

**Comment by botcrane** [comment]
🚀 **ATTENTION**: [Internal request](https://ceapex.visualstudio.com/web/wi.aspx?pcguid=7d644393-99ad-41c8-ac53-7fa79294c720&id=20435) logged.

**Comment by ShevaDas** [comment]
Thanks for the feedback! This isn't enough information for us to get started on a solution. Please feel free to reopen this issue with more information about where you see the problem.

**Comment by dend** [comment]
@ShevaDas notice how the scroll bar sticks out in terms of color:

![image](https://user-images.githubusercontent.com/1389609/40813970-6d9addf6-64f2-11e8-807d-9127f1b8b495.png)

**Comment by jdanyow** [comment]
if you're using chrome, here's a workaround:

1. enter `chrome://flags` in chrome's address bar.
2. enable the following features:
    ![chrome flags](https://user-images.githubusercontent.com/1306747/41141872-8b3271e2-6aa8-11e8-90d3-e23d20583c4a.png)

**Comment by ShevaDas** [comment]
We're not looking at providing a custom scrollbar at this time so I'm going to close this out.
