### ISSUE TITLE
expandenvironmentstrings doc page is missing

### ISSUE THREAD

**Issue by namrog84** [MicrosoftDocs/feedback#1594]
**Describe the bug**
If you search the internet for "expandenvironmentstrings" it points to a msdn doc regarding the expandenvironmentstrings api. However it redirects to a IEAPproviderconfig page
https://docs.microsoft.com/en-us/windows/desktop/api/rrascfg/nn-rrascfg-ieapproviderconfig

For example, on this document page, there is a link to expandenvironmentstrings
https://docs.microsoft.com/en-us/windows/desktop/sysinfo/getting-system-information

pointing to 
https://msdn.microsoft.com/en-us/library/ms724265(v=VS.85).aspx
but this brings you to the ieap page

Additionally, I was able to still access the page through google translated cached version here
https://webcache.googleusercontent.com/search?q=cache:6Kv6VP_X6RcJ:https://msdn.microsoft.com/zh-tw/library/windows/desktop/ms724265.ASPx+&cd=2&hl=en&ct=clnk&gl=us
so it once existed, but all the links are broken now. :( 

**To Reproduce**
1. Go to 'https://msdn.microsoft.com/en-us/library/ms724265(v=VS.85).aspx'
2. Click on 'expandenvironmentstrings' url
4. See error by being at the wrong page.

**Expected behavior**
I'd expect to see the ExpandEnvironmentStrings function api page

**Screenshots**

**Desktop (please complete the following information):**
N/A

**Additional context**

**Comment by ryanmajidi** [comment]
@GrantMeStrength Can you please take a look at this issue?

**Comment by mijacobs** [comment]
Is this the page you're looking for?
https://docs.microsoft.com/en-us/windows/win32/api/processenv/nf-processenv-expandenvironmentstringsa

**Comment by mijacobs** [comment]
Here's the URL that's broken:
https://docs.microsoft.com/en-us/windows/win32/api/processenv/_shell_expandenvironmentstringsforuser

**Comment by mijacobs** [comment]
I think these are the URLs you're looking for:
https://docs.microsoft.com/en-us/windows/win32/api/userenv/nf-userenv-expandenvironmentstringsforuserw
https://docs.microsoft.com/en-us/windows/win32/api/userenv/nf-userenv-expandenvironmentstringsforusera

**Comment by namrog84** [comment]
@mijacobs  those look like the right pages to me.

The link is still broken on a few different sites though. e.g.  https://msdn.microsoft.com/en-us/library/ms724265(v=VS.85).aspx
"use the _**ExpandEnvironmentStringsForUser**_ function."

**Comment by mijacobs** [comment]
@namrog84 I fixed the broken link on https://msdn.microsoft.com/en-us/library/ms724265(v=VS.85).aspx

**Comment by namrog84** [comment]
Awesome! Thank you!
