### ISSUE TITLE
Errors with module: Move to a modern desktop with Microsoft 365

### ISSUE THREAD

**Issue by tristanlbailey** [MicrosoftDocs/feedback#1595]
URL: https://docs.microsoft.com/en-au/learn/modules/move-to-modern-desktop-m365/5-o365-proplus-updates
Module: **Move to a modern desktop with Microsoft 365**

I encountered inconsistencies between the learning content for the module, and the self-check at the end. Two questions appear to be incorrect:

Q: Which one of the following Windows 10 update channels doesn't support Office 365 ProPlus?

- Windows Insider
- Semi-Annual Channel
- Long-term Servicing Channel

I thought either the first one (Windows Insider) or last one (Long-term Servicing Channel), as both Windows 10 and Office 365 ProPlus supports the Semi-Annual Channel. Only Monthly, Semi-Annual (targeted), and Semi-Annual channels are mentioned for Office 365 in the module.

Q: What should be included in the group that tests updates for Windows 10 and Office 365 ProPlus?

I used the following answer:

- Only users that have specialized line-of-business apps

I felt that this was the closest answer, as all others don't sound correct, however, the page responds with:

"These kinds of users generally use the LTSC and won't be good SAC test candidates."

What is "SAC"?

Unit 5 states:
"If your organization has line-of-business applications, add-ins, and macros that need to be tested to determine if they work with an updated version of Office 365 ProPlus, then Semi-Annual Channel is probably the right update channel for your organization."

Also:
"Your pilot group might include, for example, some users in the Finance department, because they're probably using specialized line-of-business applications and macros. The pilot group might also include other users in your organization that need to start trying out feature updates in advance, such as application developers or testers, training or help desk staff, or other members of the IT department."

Where "Pilot group" is a small group of devices/users selected to consume the update(s) first, before the rest of the organisation.

I have already used the email link on the page itself almost a week ago, but have not yet received a reply. Please reply as soon as possible, as I feel that I am unable to continue through the course, until I know the correct content to remember.

Thanks,

Tristan Bailey

**Comment by tristanlbailey** [comment]
@ryanmajidi 
I have now finished all modules in the Microsoft 365 Fundamentals learning path. Could someone please get back to me A.S.A.P., so that I can get this problem resolved (or at least looked into)? Then I can move on with the exam.

**Comment by ryanmajidi** [comment]
@tristanlbailey Thank you for this feedback. This has been submitted to our internal ticketing system.

**Comment by tristanlbailey** [comment]
Still waiting for a response. Absolutely useless.
