### ISSUE TITLE
PSAPI structures contain garbage in their description

### ISSUE THREAD

**Issue by MSxDOS** [MicrosoftDocs/feedback#1596]
**Link to article:**
https://docs.microsoft.com/en-us/windows/desktop/api/Psapi/ns-psapi-_psapi_working_set_block
https://docs.microsoft.com/en-us/windows/desktop/api/Psapi/ns-psapi-_psapi_working_set_ex_block

**Problem:**
Members information is filled with same garbage like `__unnamed_union_07fb_2.__unnamed_struct_0` instead of the actual description.

**Comment by ryanmajidi** [comment]
@GrantMeStrength Can you please take a look at this issue?

**Comment by GrantMeStrength** [comment]
The extra strings have been injected due to a bug in our documentation publishing pipeline. A big has been filed against the engineering team. Thanks for bringing this to our attention!
