### ISSUE TITLE
CREDENTIALA structure bold problem

### ISSUE THREAD

**Issue by nnpcYvIVl** [MicrosoftDocs/feedback#1597]
**Link to article:**
https://docs.microsoft.com/en-us/windows/desktop/api/wincred/ns-wincred-_credentiala

**Problem:**
The bottom half of the article is all bold. Looks like there is an unclosed bold tag somewhere.

**Comment by ryanmajidi** [comment]
@GrantMeStrength Can you please take a look at this issue?

**Comment by GrantMeStrength** [comment]
Correction has been submitted. Thank you.
