### ISSUE TITLE
Save Links to profile

### ISSUE THREAD

**Issue by beowulf005** [MicrosoftDocs/feedback#1598]
Would like to be able to save pages to my profile. Basically marking a content page as a favorite.
Being a domian administrator I am spending a lot of time on the docs website getting documentation on various products. But with so many different products sometimes I lose a link of content  I was revewing. Would like to (when logged in) mark pages as a favorite or read later so I have keep a reference library of documention that relates to my job functions.

**Comment by ryanmajidi** [comment]
@shirgoldbird Can you please take a look at this?

**Comment by beowulf005** [comment]
This request can be marked completed. This post meets what I was looking for 
https://docs.microsoft.com/en-us/teamblog/announcing-bookmarks?WT.mc_id=docsmsft-twitter
