### ISSUE TITLE
Please fix TFVC IntelijIdea plugin documentation page

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#16]
Link: https://docs.microsoft.com/en-us/vsts/java/Docs/tools/intelliJ not working

----------
⚠ Idea migrated from UserVoice

**Created By:** Taras
**Created On:** 2018/02/28 15:02:00 +0000
**Votes at Migration:** 2
**Supporters at Migration:** 2

**Comment by dend** [comment]
The link is not found referenced [here](https://docs.microsoft.com/en-us/vsts/java/). Closing for the time being.
