### ISSUE TITLE
Support searching for parts of API names

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#160]
Support searching for parts of API names - e.g. index camel cased word parts.

Currently, there are no Results for "NullOrEmpty" - which is just a full part of "IsNullOrEmpty".

It would also be helpful to fuzzily match up names (better than no results): e.g. "isnowhi" should include "String.IsNullOrWhitespace" in the results (ranked below a possible "IsNowhereIncluded" method).

----------
⚠ Idea migrated from UserVoice

**Created By:** Martin Ullrich
**Created On:** 2017/04/06 12:50:00 +0000
**Votes at Migration:** 40
**Supporters at Migration:** 40

**Comment by dend** [comment]
The .NET API Browser is designed to act almost like IntelliSense in the browser. It's less of a full-text search engine and more of an API graph lookup. As such, at this time this will remain as a `wont-fix`.
