### ISSUE TITLE
Error in the description of the function REPLACE

### ISSUE THREAD

**Issue by GalicinD** [MicrosoftDocs/feedback#1600]
Error in the description of the function REPLACE.
now here  https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/ef/string-functions
is written:

> Repeats a character expression for a specified number of times.

what corresponds to the REPLICATE function

**Comment by ryanmajidi** [comment]
@GalicinD I've moved this issue to the dotnet repo: https://github.com/dotnet/docs/issues/12773
