### ISSUE TITLE
ProcessStartInfo.Arguments and ArgumentList

### ISSUE THREAD

**Issue by ygoe** [MicrosoftDocs/feedback#1601]
Link to the documentation page:
https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.processstartinfo.arguments?view=netstandard-2.1

The following text probably has a typo:

> In include quotation marks in the final parsed argument, triple-escape each mark.

Did you mean "**To** include quotation marks..."? Or is this a rare aspect of the English language I don't know about?

----

Link to the documentation page:
https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.processstartinfo.argumentlist?view=netstandard-2.1

There isn't much of an explanation why I would use `ArgumentList` over `Arguments`. Is there a platform-specific difference? The `Arguments` text only explains the situation on Windows. Is it different in Linux? Where does the string splitting happen? Or the list combination? (Whatever is used on the OS level.)

BTW: The content feedback box on the docs page is still missing.

**Comment by KalleOlaviNiemitalo** [comment]
See the rationale in dotnet/corefx#23592.

**Comment by danmosemsft** [comment]
Thanks! I think feedback on the doc content itself goes in https://github.com/dotnet/dotnet-api-docs (and they take PR'S there to)

**Comment by ygoe** [comment]
I don't know where it goes to. I used my standard web search engine to find a repository that sounds like it has something to do with the reported website.

And while PRs are a great idea (albeit pretty clunky), they assume that the reporter is able to fix the problem themselves and suggest a solution. I don't have this knowledge and need the solution myself, I don't know it yet. So I'm unable to provide a PR in this case.

**Comment by danmosemsft** [comment]
@ygoe understood, it is fine to just open an issue. And yes, our diversity of repos can be pretty confusing. We are considering how we can make it simpler.

**Comment by ygoe** [comment]
There used to be a feedback box right on the docs pages but I haven't seen it in a while. Is it broken, did somebody steal it or was it intentionally removed? I makes reporting content issues so much simpler.

**Comment by mairaw** [comment]
The feedback was turned off for the API docs intentionally @ygoe but you can still open issues at https://github.com/dotnet/dotnet-api-docs. I agree with you that reporting issues was easier with the feedback enabled on the API pages. I'll discuss this with our team.
You can still click edit to suggest changes when you find typos.

**Comment by KalleOlaviNiemitalo** [comment]
> The feedback was turned off for the API docs intentionally

Apparently in dotnet/dotnet-api-docs#1913.

**Comment by ygoe** [comment]
If users are advised to open issues manually in a certain project, that project should be linked somewhere discoverable. Otherwise, people (like me) may find other paths. Meanwhile I'll try to find a place to save that link for myself so I remember to find it again.

**Comment by mairaw** [comment]
Filing here is fine @ygoe. The issues that are filed here get routed to the appropriate team.

**Comment by mairaw** [comment]
Fixed in https://github.com/dotnet/dotnet-api-docs/pull/2611. Closing.
