### ISSUE TITLE
Confusing German translation

### ISSUE THREAD

**Issue by m-do** [MicrosoftDocs/feedback#1603]
Sorry if this is the wrong approach, but I could not find a comment section in the article mentioned below. Furthermore I wanted to just send a quick message to the listed contributors, but also couldn't figure out how to message them. Therefore I'm now here...

**https://docs.microsoft.com/de-de/dynamics365/unified-operations/talent/courses**

**Problem:**
The translation under course types for "track" in this article is "Verlauf", however "Pfad" would be a better and less confusing German translation.
![Kurstypen-Verlauf](https://user-images.githubusercontent.com/16992316/59092780-a5778180-8912-11e9-8b65-1e994b236424.jpg)

**Comment by ryanmajidi** [comment]
@SonjaSaltzman Can you please take a look at this issue?

**Comment by SonjaSaltzman** [comment]
@krisre @vinceno could you please respond to the customer and make necessary fixes? (BTW, I agree the translation is weird).

**Comment by vinceno** [comment]
@MaryHannaD365 will move this forward - thx again

**Comment by MaryHannaD365** [comment]
Hi @m-do -- Thank you for reporting this issue.  We are working to have it addressed and will update you once the fix is live.  Thanks!

**Comment by MaryHannaD365** [comment]
Hi @m-do -- The translation has been corrected as suggested and now available on the live site, https://docs.microsoft.com/de-de/dynamics365/unified-operations/talent/courses.  

Thank you for reporting.

@ryanmajidi -- I dont believe I have the necessary permissions to set Status: closed nor Label: Resolved.  Appreciate if you could address please Ryan.

@vinceno -- fyi

**Comment by m-do** [comment]
Thank you all for correcting the issue! Great first-time-commenting for me :)
