### ISSUE TITLE
Previous Versions TOC does not indicate current topic when URL ends with (v=vs.100) rather than (v%3dvs.100)

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [MicrosoftDocs/feedback#1604]
All four of the following URLs display the same topic "\<xsd:import> Element".  However, the breadcrumb bar and the table of contents indicate the current topic only at the first two URLs, i.e. the ones that contain "%3d". At the last two URLs, which contain "=", the breadcrumb bar shows only "Docs / Previous Versions / .NET", and the table of contents shows only the first-level sections. I think the server should be treating all of these as equivalent or perhaps redirecting to a canonical URL.

* https://docs.microsoft.com/en-us/previous-versions/dotnet/netframework-4.0/ms256480%28v%3dvs.100%29
* https://docs.microsoft.com/en-us/previous-versions/dotnet/netframework-4.0/ms256480(v%3dvs.100)
* https://docs.microsoft.com/en-us/previous-versions/dotnet/netframework-4.0/ms256480(v=vs.100)
* https://docs.microsoft.com/en-us/previous-versions/dotnet/netframework-4.0/ms256480%28v=vs.100%29

Reproduced with Firefox 60.7.0esr and Microsoft Edge 44.17763.1.0.

**Comment by ryanmajidi** [comment]
@v-saambe Can you please take a look at this issue?

**Comment by mairaw** [comment]
I've reported the same issue internally and I just got confirmation that it was fixed. I don't have permissions to close this though.

**Comment by KalleOlaviNiemitalo** [comment]
OK, it's working now.
