### ISSUE TITLE
Unsure where to file site content issue for Microsoft Developer Blogs

### ISSUE THREAD

**Issue by tommai78101** [MicrosoftDocs/feedback#1606]
This is the only place I know where I can ask questions on how to file bug reports and site content issues to Microsoft Docs.

But, I cannot find where to file the same things for Microsoft Developer, especially for Microsoft Developer Blogs. (https://blogs.msdn.microsoft.com)

May I ask where I can file bug reports/site content issues about Microsoft Developer Blogs at?

Thanks.

If this is not the right place, may I request for a Documentation article on where to report site issues for the entire Microsoft sitemaps / domains at?

**Comment by ryanmajidi** [comment]
@tommai78101  Many pages have feedback buttons built into them. For example this is an office page:
![image](https://user-images.githubusercontent.com/7329992/59307834-3a9cb200-8c54-11e9-9d2e-17ca47a3cc7d.png)
You can also click edit on the top right of the page (if it exists) and then open a github issue:
![image](https://user-images.githubusercontent.com/7329992/59307941-84859800-8c54-11e9-96eb-52cf7a5b091e.png)

In the case where there is no such button this is the correct place to submit issues. If need be, we will route the issue to the right place. For blogs issues, please submit them here.
