### ISSUE TITLE
Control Spy has gone missing

### ISSUE THREAD

**Issue by atlight** [MicrosoftDocs/feedback#1607]
https://docs.microsoft.com/en-us/windows/desktop/controls/control-spy

The download link for this tool is broken. The tool is still very relevant in the modern day, and it would be great if this can be rectified.

**Comment by ryanmajidi** [comment]
@GrantMeStrength Can you please take a look at this issue?

**Comment by asklar** [comment]
The page https://docs.microsoft.com/en-us/windows/win32/controls/control-spy also references the tool and the link is broken, please fix the link too.

**Comment by GrantMeStrength** [comment]
There are plans to make ControlSpy available again, probably as a sample.

**Comment by asklar** [comment]
@GrantMeStrength - Please keep this issue open until the links in the pages above are updated
