### ISSUE TITLE
SMO version 150 documentation is missing

### ISSUE THREAD

**Issue by jeffshumphreys** [MicrosoftDocs/feedback#1608]
**Is your feature request related to a problem? Please describe.**
I am trying to use SMO scripter to extract table DDL from source tables.  I am looking for documentation on SMO v 150, which is the minimum version required for connecting to [Azure Managed instances](https://docs.microsoft.com/en-us/azure/sql-database/sql-database-managed-instance-connect-app#required-versions-of-drivers-and-tools)

**Describe the solution you'd like**
I'd like some documentation on the ServerConnection that explains if it is possible in v150 to use Azure Active Directory Authentication to connection to Azure from SMO.   

**Describe alternatives you've considered**
My alternative is to use .NET Sql connections (which support AAD) and try and describe objects through dictionary objects.

**Additional context**

**Comment by ryanmajidi** [comment]
@jeffshumphreys I've moved this issue to that repo: https://github.com/MicrosoftDocs/azure-docs/issues/33135
