### ISSUE TITLE
Dead link on "Developing a Per-Monitor DPI-Aware WPF Application"

### ISSUE THREAD

**Issue by floele-ww** [MicrosoftDocs/feedback#1609]
On https://docs.microsoft.com/en-us/windows/desktop/hidpi/declaring-managed-apps-dpi-aware there is a dead link in the note at the top to https://github.com/Microsoft/WPF-Samples/blob/master/PerMonitorDPI/Developer%20Guide%20-%20Per%20Monitor%20DPI%20-%20WPF%20Preview.docx

**Comment by ryanmajidi** [comment]
@GrantMeStrength Can you please take a look at this issue?

**Comment by KalleOlaviNiemitalo** [comment]
In microsoft/WPF-Samples#70, the document was moved to <https://github.com/microsoft/WPF-Samples/blob/master/PerMonitorDPI/readme.md>.

**Comment by GrantMeStrength** [comment]
Assigned to writer than owns the area.

**Comment by QuinnRadich** [comment]
My apologies for the long delay on responding to this issue. That being said, I'm happy to report that the broken link was resolved quite a while ago - though this issue is stale, the fix has been live for some time.

Many thanks!
