### ISSUE TITLE
Expose information through an API service

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#161]
It would be great if the information could be exposed through some API to be used, for example, on a Visual Studio Code extension.

If we could send the Framework + Version + text and obtain the first 10-20 results it could be useful for an IDE integration.

----------
⚠ Idea migrated from UserVoice

**Created By:** Matías Quaranta
**Created On:** 2017/04/06 12:31:03 +0000
**Votes at Migration:** 2
**Supporters at Migration:** 2

**Comment by dend** [comment]
At this time, we do not have plans to open an API for public consumption for any of the API Browser services.
