### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by strattonn** [MicrosoftDocs/feedback#1613]
**Link to article:**
https://docs.microsoft.com/en-us/sql/integration-services/custom-messages-for-logging?view=sql-server-2014

**Problem:**
The Related Content link...
Blog entry, Logging custom events for Integration Services tasks, on dougbert.com.

Is dead, goes to a Game of Thrones online gaming site.

**Comment by ryanmajidi** [comment]
Moved to https://github.com/MicrosoftDocs/sql-docs/issues/2320
