### ISSUE TITLE
Dead link for Microsoft Azure Compliance

### ISSUE THREAD

**Issue by DevProJC** [MicrosoftDocs/feedback#1616]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

**Link to article:**
Tell us where exactly a problem occurs.

**Problem:**
What's wrong with the article?

**Comment by ryanmajidi** [comment]
@DevProJC Which page is the broken link on? What link is broken?

**Comment by DevProJC** [comment]
@ryanmajidi https://gallery.technet.microsoft.com/Azure-Compliance-in-the-8b936d6a

when click on download link, there is no file.

**Comment by ryanmajidi** [comment]
@DevProJC  When you click the download link there is a Terms of Use. If you click 'I agree' the download starts. is this the experience you are getting?

**Comment by ryanmajidi** [comment]
@DevProJC I'm closing this. Please open another issue if you are still having problems.
