### ISSUE TITLE
Document which ETW providers need NonPagedMemory="true"

### ISSUE THREAD

**Issue by Holo-Krzysztof** [MicrosoftDocs/feedback#1619]
**Link to article:**
https://docs.microsoft.com/en-us/windows-hardware/test/wpt/2-system-and-event-provider-definitions

**Problem:**
The article mentions the `Microsoft-Windows-Win32K` ETW provider as an example that requires non-paged memory. However, I found no info on other providers that require this. From my experience `DxgKrnl` also falls under that category, something that took me a long time to discover because there's no documentation on that matter.

Is it generally true of kernel-level ETW providers that they require non-paged memory? If not, could you document which ones do?

**Comment by ryanmajidi** [comment]
@GrantMeStrength Can you please take a look at this issue?

**Comment by GrantMeStrength** [comment]
Investigating.

**Comment by GrantMeStrength** [comment]
I spoke to the dev team, and they told me:

"Only ETW sessions using non-paged memory can enable kernel mode ETW providers.  There are no exceptions to that.  "

thanks!
