### ISSUE TITLE
Update the Azure Reference page with actual values instead of "value of xyz"

### ISSUE THREAD

**Issue by supernova-eng** [MicrosoftDocs/feedback#162]
If you visit this site: https://docs.microsoft.com/en-us/azure/templates/

And visit one of the templates, for example, Microsoft.Web/Serverfarms.

For SKU\name, the description is "name of resource SKU"

Which doesn't help what so ever. How about including valid values? For e.g. (from the schema JSON) :

type: "string",
pattern: "^[fdbspFDBSP][1-9]$"

That would be much more helpful.

----------
⚠ Idea migrated from UserVoice

**Created By:** Anonymous
**Created On:** 2017/04/03 23:21:05 +0000
**Votes at Migration:** 1
**Supporters at Migration:** 1

**Comment by dend** [comment]
@tfitzmac @tysonn given that this is a content suggestion, it will be closed soon, but I wanted to get it on your radar to make sure that the right content developers are aware.

**Comment by tfitzmac** [comment]
@botcrane - thanks for this feedback. Yes, I agree with you that many of the descriptions are not useful. I am creating a work item for myself to review these descriptions and provide feedback to those services for improving descriptions. Unfortunately, it will take some time, as each team updates its API descriptions on different schedules.

**Comment by dend** [comment]
@tfitzmac was there any progress on this item?

**Comment by Powerhelmsman** [comment]
@tfitzmac Any plan on this item?

**Comment by keziamicro** [comment]
Hello - reviewing and cleaning up some older feedback/issues. Thanks!
