### ISSUE TITLE
Xamarin tutorial

### ISSUE THREAD

**Issue by StevenGranados** [MicrosoftDocs/feedback#1621]
**Link to article:**
https://docs.microsoft.com/en-us/xamarin/get-started/tutorials/entry/?tutorial-step=2&tabs=vswin

**Problem:**
The article references LabelTutorial in section 2 when I believe it should reference EntryTutorial (the current tutorial)

**Comment by ryanmajidi** [comment]
@conceptdev Can you please take a look at this issue?

**Comment by conceptdev** [comment]
Thanks @StevenGranados, could be a typo - we're checking.

**Comment by davidbritch** [comment]
This has now been fixed in a PR that will go live later.
