### ISSUE TITLE
[error message feedback] provide feedback for InvalidExternalBookmark

### ISSUE THREAD

**Issue by vmagelo** [MicrosoftDocs/feedback#1624]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

- Unfortunately, the doc page could not load feedback section at bottom. 

**Problem:**

- Is error message clear and actionable? 
  No. I can't find anything that looks like a bookmark on the referenced pages.

- Is there a documentation to provide more information?
  No. The documentation at https://review.docs.microsoft.com/en-us/help/contribute/links-how-to?branch=master#bookmark-links doesn't help.

- Is line number correct?
  The line number don't seem to relate to anything that makes sense.

**Log code info**
(This is auto filled, no need to modify)

| Severity   | Type   | Code   | Category   | File   | Message   |  Source  | Line   | Time   |
|------------|--------|--------|------------|--------|-----------|----------|--------|--------|
| Warning | Unspecified | InvalidExternalBookmark | Markdown | DataPrep/docs-ref-autogen/azureml-dataprep/azureml.dataprep.api.builders.ColumnTypesBuilder.yml | Illegal link: `<xref:azureml.dataprep.FieldType.DATE>` -- missing bookmark. The file docs-ref-autogen/azureml-dataprep/azureml.dataprep.FieldType.yml doesn't contain a bookmark named date. | Postprocess.HandlePostProcessorsWithIncremental.HandlePostProcessors.Processing html.ValidateBookmark |9 | 06/10/2019 18:06:51 |

**Link to report**
(This is auto filled, no need to modify)

[report url](https://opbuildstorageprod.blob.core.windows.net/report/2019%5c6%5c10%5ced72740f-9db8-56fb-e2eb-769d1f65a7dd%5cPullRequest%5c201906101803118669-298%5cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2BLjWHS5VS68ptfpeIp0sVocFaCSaAYSAt0MmAI5tctM%3D&st=2019-06-10T18:03:09Z&se=2019-07-11T18:08:09Z&sp=r)

**Comment by erhopf** [comment]
@vmagelo can you link me to the PR? I can take a look and maybe help out.

**Comment by vmagelo** [comment]
PR
https://github.com/MicrosoftDocs/MachineLearning-Python-pr/pull/297

Problem file
https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/master/DataPrep/docs-ref-autogen/azureml-dataprep/azureml.dataprep.Dataflow.yml

Rendered page
https://docs.microsoft.com/en-us/python/api/azureml-dataprep/azureml.dataprep.dataflow?view=azure-ml-py
