### ISSUE TITLE
Line wrong on Exercise - Secure webhook payloads with a secret

### ISSUE THREAD

**Issue by gljivar** [MicrosoftDocs/feedback#1626]
**Link to article:**
https://docs.microsoft.com/en-us/learn/modules/monitor-github-events-with-a-function-triggered-by-a-webhook/9-exercise-secure-webhook-payloads-with-secret

**Problem:**
This line is wrong:
var CryptoJS = require('crypto');
It should be:
var Crypto = require('crypto');

Also, in general reporting an issue should be pointing to this site, not opening email client.

**Comment by ryanmajidi** [comment]
@gljivar Thank you for this feedback. We have submitted an internal ticket for this.
