### ISSUE TITLE
typo in "RAWINPUTHEADER structure" page

### ISSUE THREAD

**Issue by VictorL** [MicrosoftDocs/feedback#1627]
**Link to article:**
https://docs.microsoft.com/en-us/windows/desktop/api/winuser/ns-winuser-tagrawinputheader

**Problem:**
typo in line:
"This includes RAWINPUT plus possible extra input reports in the RAWHID variable length array."
should be "extra input records"

**Comment by ryanmajidi** [comment]
@GrantMeStrength Can you please take a look at this issue?

**Comment by VictorL** [comment]
Fix "rePorts" for "reCords".

**Comment by krishty** [comment]
Are you sure this should be reCords?! The data you’re talking about is usually passed on to the HID API for evaluation, and it’s explicitly called *input rePort* there. See especially https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/hidsdi/nf-hidsdi-hidd_getinputreport (which has some typos and formatting errors on its own) or generally https://docs.microsoft.com/en-us/windows-hardware/drivers/hid/obtaining-hid-reports-by-user-mode-applications .

**Comment by GrantMeStrength** [comment]
Decided to keep it as Reports. But thanks for the report!
