### ISSUE TITLE
Correct typo "Get-AzApiManagementAuthrizarionServer".

### ISSUE THREAD

**Issue by nsathyanarayan** [MicrosoftDocs/feedback#1628]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

**Link to article:**
Tell us where exactly a problem occurs.

**Problem:**
What's wrong with the article?

**Comment by popujol** [comment]
It is incomplete. We need to know clearly what features from Dynamics applications are not accessible with a powerapp licence from a model driven app.
See example in my request.
Thank you

**Comment by mairaw** [comment]
I've opened the following PR to fix the issue:
https://github.com/Azure/azure-powershell/pull/9439

If the typo was on a page different than https://docs.microsoft.com/en-us/powershell/module/az.apimanagement/get-azapimanagementauthorizationserver, then please let us know.
