### ISSUE TITLE
Typo in ERROR_NOT_ENOUGH_MEMORY description

### ISSUE THREAD

**Issue by k15tfu** [MicrosoftDocs/feedback#1629]
**Link to article:**
https://docs.microsoft.com/en-us/windows/desktop/debug/system-error-codes--0-499-

**Problem:**
The description for `ERROR_NOT_ENOUGH_MEMORY` says
```
Not enough storage is available to process this command.
```

but I think the problem not in the disk but memory. The correct one is:
```
Not enough memory resources are available to process this command
```

**Comment by ryanmajidi** [comment]
@GrantMeStrength Can you please take a look at this issue?
