### ISSUE TITLE
"Filter" box in dark theme shows Windows background color, not white

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#163]
I do not use white as my Windows Background Color (I use "money green" [192, 220, 192], one of the original 16 Windows colors, which is much easier on the eyeballses).

I noticed that the "Filter" box in the dark theme shows the Windows Background Color.  No doubt the developers were working on systems configured with a white background and thought that the "Filter" background was in fact white.

While I would always prefer a non-white background color, in this case it was clear that the designer didn't intend that CSS in that spot.

----------
⚠ Idea migrated from UserVoice

**Created By:** Wayne Erfling
**Created On:** 2017/04/02 10:48:51 +0000
**Votes at Migration:** 1
**Supporters at Migration:** 1

**Comment by dend** [comment]
@ShevaDas can you take a look at this issue?

**Comment by ShevaDas** [comment]
Thanks for the feedback! I tried changing my Windows background color and wasn't able to reproduce this bug. I also looked at the CSS and it does appear to explicitly have the white background on the Filter box set. Closing this out for now as I can't repro it—feel free to leave a comment with more information if you want me to take another look.
