### ISSUE TITLE
SQL Server 2017 Slow/does not work when importing subpackages for python.

### ISSUE THREAD

**Issue by YizeD** [MicrosoftDocs/feedback#1630]
**Describe the bug**

When I try to run python scripts in SQL server 2017 using revoscalepy, I can import the base packages, but when I try to import a from a subpackage in the py_vollib package (py_vollib.black.implied_volatility), the server will run forever without returning anything. I have checked that py_vollib is installed into the SQL Server list of packages, and py_vollib usually contains the py_vollib.black subpackage, so I'm not sure what the problem is.

**To Reproduce**
1. Install py_vollib to SQL server.
2. Write python script that contains the following import
`from py_vollib.black.implied_volatility import implied_volatility as iv`
3. Query script into SQL server.
4. Server will now run for a long time.

**Expected behavior**
When running script on local machine, it takes 3.5 seconds to run on average.

Thank you in advance.

**Comment by ryanmajidi** [comment]
@YizeD Please contact support: https://support.microsoft.com/en-us
