### ISSUE TITLE
Consider darker "white" text and lighter "black" background in Dark theme

### ISSUE THREAD

**Issue by rummelsworth** [MicrosoftDocs/feedback#1631]
**Is your feature request related to a problem? Please describe.**

I realize Docs' Dark theme doesn't use pure white and pure black for text and background, but the contrast between the two basic text and background colors (as of this writing `#e3e3e3` and `#171717`) still feels a little harsh after a few minutes of usage, especially compared to the _slightly_ different but _much_ gentler (IMO) defaults in Visual Studio's Dark theme (`#dcdcdc` and `#1e1e1e`), which I can use for two or more hours straight without any discomfort.

**Describe the solution you'd like**

I'd like for Dark theme's text and background colors to be slightly less "far apart" than they are now, perhaps using the default colors mentioned above from Visual Studio's Dark theme.

**Describe alternatives you've considered**

I suppose I could try to use a browser add-on that customizes the CSS of configured sites, but I'd rather not install and figure out another add-on.

**Additional context**

Current Docs Dark capture:
![image](https://user-images.githubusercontent.com/3069355/59635495-fb200b00-9116-11e9-908a-08ed7c9f6b0c.png)

VS Dark capture:
![image](https://user-images.githubusercontent.com/3069355/59635454-e6437780-9116-11e9-885a-8a04880e419e.png)

**Comment by ryanmajidi** [comment]
@rummelsworth thank you for the feedback. We have submitted this to our internal ticketing system.

**Comment by reduckted** [comment]
Is there any way to track this issue? I came here to report the same issue, but wasn't expecting to find an issue that was already closed. Can this issue at least be left open until it's either fixed or rejected?

**Comment by VerdonTrigance** [comment]
Can we reopen this issue? I agree with author. This black and white contrast harass my eyes quickly. Make it more soft please. Something in between:
![image](https://user-images.githubusercontent.com/12109173/97170375-a83f7480-179c-11eb-915a-85d4e11421f8.png)
