### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by guardrex** [MicrosoftDocs/feedback#1632]
https://docs.microsoft.com/en-us/healthvault/#pivot=sdkstools&panel=sdkstools-all

The *Download PowerShell* link is broken.

Should it be ... https://github.com/PowerShell/PowerShell#get-powershell

**Comment by mairaw** [comment]
@jhutchings1 can you look at this issue?

**Comment by jhutchings1** [comment]
@mairaw I'm not a maintainer for those docs anymore, although considering [the announcement that support for HealthVault is sunsetting](https://www.neowin.net/news/microsoft-healthvault-to-close-on-november-20), this documentation should will probably go with it. @abhijeett what do you think?

**Comment by guardrex** [comment]
The product (and link) is dead now, so this can be closed.

**Comment by mairaw** [comment]
Really weird experience with this product. Some inner links still work: https://docs.microsoft.com/en-us/healthvault/introduction/introduction
