### ISSUE TITLE
Broken link iot-hub docs

### ISSUE THREAD

**Issue by toledotown** [MicrosoftDocs/feedback#1634]
https://docs.microsoft.com/en-us/azure/iot-hub/

References > IoT device catalog link broken.

**Comment by robinsh** [comment]
I'll fix this. It's actually Resources > IoT device catalog link that's broken. PR is https://github.com/MicrosoftDocs/azure-docs-pr/pull/80099..

**Comment by robinsh** [comment]
Hi @toledotown . Thanks for reporting this. I've fixed it now, it should work. I found it in Resources>IoT device catalog, not in References, so let me know if I fixed the wrong one. This should publish Friday morning.

**Comment by mairaw** [comment]
Closing this since @robinsh has fixed it. Let us know if this is not the broken link you were referring to @toledotown.
