### ISSUE TITLE
Protection support matrix dpm

### ISSUE THREAD

**Issue by LittleGreenBag** [MicrosoftDocs/feedback#1635]
under the support matrix it state that it must run on On-premises Hyper-V virtual machine. but this is not limited to a Hyper-V VM.
people may conclude that the an hyper-v environment is required.
Shouldnt it state that it can run as a "Virtual Machine" either on Hyper-v or VMware.?

Ref:
https://docs.microsoft.com/en-us/system-center/dpm/dpm-protection-matrix?view=sc-dpm-2019

**Comment by ryanmajidi** [comment]
@LittleGreenBag  moved to that repo: https://github.com/MicrosoftDocs/SystemCenterDocs-pr/issues/2552
