### ISSUE TITLE
Remarks are not correct for .NET Core

### ISSUE THREAD

**Issue by RobSiklos** [MicrosoftDocs/feedback#1636]
**Link to article:**
https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.x509certificates.x509certificate2.privatekey?view=netcore-3.0#remarks

**Problem:**
The article says that the property "returns either an RSACryptoServiceProvider or a DSACryptoServiceProvider object". However, for .NET Core, this is not true.

**Comment by mairaw** [comment]
Thanks for your feedback @RobSiklos. I've moved this issue to https://github.com/dotnet/dotnet-api-docs/issues/2685.
