### ISSUE TITLE
Typo on User Interface Principles Page

### ISSUE THREAD

**Issue by pwagle08** [MicrosoftDocs/feedback#1637]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

**Link to article:**
Tell us where exactly a problem occurs.
https://docs.microsoft.com/en-us/windows/desktop/appuistart/-user-interface-principles

**Problem:**
What's wrong with the article?
Under the "Spacing and Positioning" section, extremely is misspelled as "extreemly"

**Comment by ryanmajidi** [comment]
@GrantMeStrength Can you please take a look at this issue?

**Comment by mairaw** [comment]
Thanks @pwagle08 for your feedback. I've opened a PR to fix this:  https://github.com/MicrosoftDocs/win32/pull/421

**Comment by mairaw** [comment]
This is fixed. Thanks!
