### ISSUE TITLE
Tooltip not available for "Feedback" option

### ISSUE THREAD

**Issue by charmaine** [MicrosoftDocs/feedback#1638]
**Describe the bug**
Tooltip not available for "Feedback" option

**To Reproduce**
1. Go to [content page](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/set-your-preferences?view=azure-devops) on docs with an action bar
2. Hover over "Feedback" in the upper right hand corner
4. No tooltip appears due to missing title attribute

**Expected behavior**
"Edit", "Share", and "Theme" in the action bar all have tooltips on hover, but "Feedback" doesn't.

**Comment by ryanmajidi** [comment]
@charmaine Thank you for submitting this issue. We have added it to our internal ticketing system.
