### ISSUE TITLE
increase contrast for typing "Comments" in dark theme

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#164]
When I entered a Comment (the only one I see at the moment!) for the "November update for docs.microsoft.com" (https://docs.microsoft.com/en-gb/teamblog/docs-november-update?hubRefSrc=email&utm_source=lfemail&utm_medium=email&utm_campaign=lfnotification), 

my comment text went in with dark gray text on a black background.

I see other people have commented on the contrast in other areas already.

My only general comment is that the overall trend to low-contrast text and backgrounds is stupid (see... Facebook header, MSDN header, ...)

Maybe a given developer can see low-contrast text with their particular monitors and room lighting and eyesight, but it's almost certain that SOMEBODY is going to find it difficult or impossible to read.

----------
⚠ Idea migrated from UserVoice

**Created By:** Wayne Erfling
**Created On:** 2017/04/02 10:43:03 +0000
**Votes at Migration:** 1
**Supporters at Migration:** 1

**Comment by dend** [comment]
This is no longer applicable as we switched to GitHub issues.
