### ISSUE TITLE
What's new in 1903 ADK is missing

### ISSUE THREAD

**Issue by Karl-WE** [MicrosoftDocs/feedback#1642]
**Link to article:**
https://docs.microsoft.com/de-de/windows-hardware/get-started/adk-install

**Problem:**
What's new in ADK for Windows 10, version **1903** is missing even though it is no longer an insider release.

**Comment by ryanmajidi** [comment]
@GrantMeStrength Can you please take a look at this issue?

**Comment by GrantMeStrength** [comment]
Sorry for the delay. It got added eventually: https://docs.microsoft.com/en-us/windows-hardware/get-started/what-s-new-in-kits-and-tools#whats-new-in-the-windows-adk-for-windows-10-version-1903

**Comment by Karl-WE** [comment]
Thanks for the update. @GrantMeStrength 
For consistency it would be better to merge these two (they have complete different layout though)

![image](https://user-images.githubusercontent.com/45657752/91663739-12b09d00-eaeb-11ea-9d98-2e274eb53950.png)

All changes are listed in the chapter above. Only 1809 has its own.
