### ISSUE TITLE
Microsoft Learn - Sandbox sessions limitation

### ISSUE THREAD

**Issue by akiyoshi** [MicrosoftDocs/feedback#1643]
**Is your feature request related to a problem? Please describe.**
Currently, the number of simultaneous session in the Microsoft Learn sandbox is limited to 150.
I have to reload the sandbox to avoid the limitation.

**Describe the solution you'd like**
It would be necessary to increase the maximum number of the session because the more popular MS learn become, the more people use sandbox simultaneously.

**Additional context**
Thank you all for your effort to create great content and I am sure that more and more people will enjoy Microsoft Learn.

**Comment by ibakirov** [comment]
I agree, faced the same limitation today at #1672

**Comment by ryanmajidi** [comment]
@akiyoshi  Thank you for this feedback. We have added this to our internal bug tracking system.
