### ISSUE TITLE
new comprehensive article about ALL Windows Update (WU & WSUS) releated error codes

### ISSUE THREAD

**Issue by Karl-WE** [MicrosoftDocs/feedback#1644]
**Is your feature request related to a problem? Please describe.**
There are some docs pages that contain error codes für WU / WSUS etc but I feel they could be less cluttered. I guess this was never intended by the authors as they put a lot of work into the individual docs.

Currently the information is spread in old technet, docs, ms answer / community or even MS blog.

**Describe the solution you'd like**
I would like to help gathering the errorcodes from different location that I am aware of (ms docs, MVP Günter Born blog, etc. and help to get them together at one place.

this new docs page should have a github connect so people could easily point missing codes and these could be added by the developers or whoever has internal insights to complete the doc.

this new docs page should be linked as related link on 
https://support.microsoft.com/en-us/help/4099479/windows-10-update-history
as an easy access reference about WU / WSUS error codes.

**Describe alternatives you've considered**
Alternatively we could put backlinks on the pages to other articles.

**Comment by ryanmajidi** [comment]
@GrantMeStrength Can you please take a look at this issue?

**Comment by GrantMeStrength** [comment]
This is an excellent idea. I will create an internal work item to investigate this. Thank you for taking the time to write feedback.
