### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by Necrosys** [MicrosoftDocs/feedback#1647]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

**Link to article:**
Tell us where exactly a problem occurs.
`https://docs.microsoft.com/en-us/windows/desktop/sync/synchronization-and-multiprocessor-issues`

**Problem:**
What's wrong with the article?
InterlockedExchange link is broken.
URL should be 
`https://docs.microsoft.com/en-us/windows/desktop/api/winnt/nf-winnt-interlockedexchange`

**Comment by ryanmajidi** [comment]
@GrantMeStrength Can you please take a look at this issue?

**Comment by GrantMeStrength** [comment]
Thank you! Corrected.
