### ISSUE TITLE
Missing a parameter in the Command-line syntax for SCOM

### ISSUE THREAD

**Issue by LeonLaude** [MicrosoftDocs/feedback#1648]
**Link to article:**
[https://docs.microsoft.com/en-us/system-center/scom/deploy-install-ops-console?view=sc-om-2019](url)

**Problem:**
The problem lies in the bottom section of the documentation "**To install the Operations console from the Command Prompt**".

The syntax is missing a parameter, the provided command will fail, I have tested this and the Operations Manager setup log will complain that the EndUserLicenseAgreement needs to be accepted.

So the following parameter should be added to the command:

`/AcceptEndUserLicenseAgreement:1`

Best regards,
Leon Laude

**Comment by ryanmajidi** [comment]
@LeonLaude moved to that repo: https://github.com/MicrosoftDocs/SystemCenterDocs-pr/issues/2551
