### ISSUE TITLE
This page is not showing the appropriate content

### ISSUE THREAD

**Issue by PeteHaigh-MSFT** [MicrosoftDocs/feedback#1649]
https://docs.microsoft.com/en-nz/windows-server/index
Change to en-us and it all works OK...

**Comment by ryanmajidi** [comment]
@GrantMeStrength Can you please take a look at this issue?

**Comment by GrantMeStrength** [comment]
I think this is all fixed.. if not please re-open! Thanks for taking the time to report it.
