### ISSUE TITLE
The most important topics in the article are translated to the opposite meaning in Japanese

### ISSUE THREAD

**Issue by kefujino** [MicrosoftDocs/feedback#1652]
**Describe the bug**
There is a mistranslation in below article for Japanese.

https://docs.microsoft.com/ja-jp/office365/enterprise/navigation-options-for-sharepoint-online

Non-Recommended feature is translated to the opposite meaning.
So, this mistranslation advocate to use Non-Recommended features for Japanese users.
We should fix it as soon as possible.

At the third paragraph in the overview section.

- Original text
The second option, Structural navigation, is NOT a recommended navigation option in SharePoint Online.

- Japanese text
2番目のオプションである構造ナビゲーションは、SharePoint Online では推奨されていないナビゲーションオプションではありません。

- Amendment
2番目のオプションである構造ナビゲーションは、SharePoint Online で推奨されるナビゲーションオプションではありません。

**Screenshots**
![コメント 2019-06-25 173740](https://user-images.githubusercontent.com/13634805/60083116-0e168900-9770-11e9-8217-36a39ff11cc9.jpg)
![コメント 2019-06-25 173709](https://user-images.githubusercontent.com/13634805/60083129-14a50080-9770-11e9-9046-4f9cba6fd58e.jpg)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kenmoritest** [comment]
Hi, This should be urgently fixed. As this is one of the hottest topics for the regional community.

**Comment by ryanmajidi** [comment]
@SonjaSaltzman Can you please take a look at this issue?

**Comment by SonjaSaltzman** [comment]
This content is from the Office team, assigning to @Soran-M to address

**Comment by SonjaSaltzman** [comment]
also adding @MartineSmets - not sure which team owns this content

**Comment by TinaMcN** [comment]
@officeglobal, please take care of fixing this.  Thanks, Tina
@kefujino thank you for the feedback!

**Comment by kefujino** [comment]
@TinaMcN
@OfficeGlobal

I verified that the article has been fixed.
Thank you!
