### ISSUE TITLE
Embedded link directs to wrong page on DQS tutorial page

### ISSUE THREAD

**Issue by Xceptions** [MicrosoftDocs/feedback#1653]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

**Link to article:**
Tell us where exactly a problem occurs.

**Problem:**
What's wrong with the article?

A wrong link was inserted in a page for learning how to automate DQS cleansing with SSIS.
In this [page](https://docs.microsoft.com/en-us/sql/tutorials/task-6-adding-excel-source-to-the-data-flow?view=sql-server-2014), the link inserted at the bottom is supposed to take us to the next item on the list of learning which is [this](https://docs.microsoft.com/en-us/sql/tutorials/task-7-adding-dqs-cleansing-transform-to-the-data-flow?view=sql-server-2014), but it instead, leads to [here](https://docs.microsoft.com/en-us/sql/integration-services/data-flow/data-flow?view=sql-server-2014).
Please correct it

**Comment by ryanmajidi** [comment]
@Xceptions moved to that repo: https://github.com/MicrosoftDocs/sql-docs/issues/2590
