### ISSUE TITLE
 en-gb Docs (Microsoft Graph) - NO navigation/contents sidebar

### ISSUE THREAD

**Issue by glasco61** [MicrosoftDocs/feedback#1654]
"https://docs.microsoft.com/en-gb/graph/overview" URL does not display the navigation/contents sidebar.

Changing en-gb -> en-us in the URL, does display the pane!

How I got there:

1) Entered "docs.microsoft.com" url in browser
Took me to landing page "https://docs.microsoft.com/en-gb/"

2) Clicked on "Microsoft Graph" hyperlink in Docs Directory list
Took me to "https://docs.microsoft.com/en-gb/graph/overview"

Near the bottom of the page the instruction is:
"Look under Learn in the table of contents to read about services and features that you can use in your scenarios"

With NO table of contents, it's kinda impossible....

I am UK based, so assume the "en-gb" part of the URL is from my regional settings. As @dev-rowbot had noted in their feedback title (displayed in the related issues) that changing the locale in the URL fixed an apparently similar issue, I tried the same & it by-passed the issue for me. Problem being I don't want to have to manually correct an automatic process.

This issue exists on all major browsers I tried:
Firefox 67.0.4 (64-bit)
Chrome 75.0.3770.100 (Official Build) (64-bit)
Edge 44.18362.1.0

I even tried IE 11.116.18362.0 - It's the same

**Comment by ryanmajidi** [comment]
@glasco61 this glitch seems to be fixed.
