### ISSUE TITLE
Get-PartitionSupportedSize Command Misspelling

### ISSUE THREAD

**Issue by h-sadeghpour** [MicrosoftDocs/feedback#1655]
![Capture](https://user-images.githubusercontent.com/49187548/60099326-149d0480-9760-11e9-8bac-66ff4ce6d681.PNG)
![Capture2](https://user-images.githubusercontent.com/49187548/60099376-2b435b80-9760-11e9-9fce-5875ab31e6c2.png)

**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

**Link to article:**
https://docs.microsoft.com/en-us/powershell/module/storage/get-partitionsupportedsize?view=win10-ps#examples

**Problem:**
Get-PartitionSupportedSizes Command must be without "S" at the end, and as refering to images I've attached to this issue MinimumSize and MaxmimumSize must be SizeMin and SizeMax.

Regards
Hamid Sadeghpour Saleh

**Comment by h-sadeghpour** [comment]
https://docs.microsoft.com/en-us/powershell/module/storage/get-partitionsupportedsize?view=win10-ps#examples

**Comment by ryanmajidi** [comment]
@sdwheeler Can you please take a look at this issue?

**Comment by sdwheeler** [comment]
That content is owned by @AndreaBarr.

**Comment by h-sadeghpour** [comment]
It's still not updated!

**Comment by e0i** [comment]
Hello, @h-sadeghpour

The issue has been acknowledged and you'll be notified with relevant updates as content gets updated.

Thank you for providing feedback.

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@h-sadeghpour 

The content has been updated with relevant changes accordingly.

Thank you for taking the time to provide feedback.

@AndreaBarr Recommended closure.

**Comment by mairaw** [comment]
Closing then. I also recommend you to use the feedback button on the bottom of the article when available @h-sadeghpour:
![image](https://user-images.githubusercontent.com/12971179/61553940-8c351b00-aa10-11e9-86e1-f793dff82423.png)

That comment goes directly to the right repository and the author gets notified.
