### ISSUE TITLE
charformat2 - undocumented value

### ISSUE THREAD

**Issue by 2kaud** [MicrosoftDocs/feedback#1657]
For the article https://docs.microsoft.com/en-us/windows/desktop/api/richedit/ns-richedit-charformat2a

the values for the element bUnderlineColor are not defined. It just says 'underline color' without specifying what the available colours and their values. Please would the valid values for this element be documented.

**Comment by ryanmajidi** [comment]
@grantmestrength Can you please take a look at this issue?

**Comment by GrantMeStrength** [comment]
Thanks for highlighting this missing information. I will add it to the docs:

UnderlineColor_Black =      0x00;
UnderlineColor_Blue =       0x01;
UnderlineColor_Aqua =       0x02;
UnderlineColor_Lime =       0x03;
UnderlineColor_Fuchsia =    0x04;
UnderlineColor_Red =        0x05;
UnderlineColor_Yellow =     0x06;
UnderlineColor_White =      0x07;
UnderlineColor_Navy =       0x08;
UnderlineColor_Teal =       0x09;
UnderlineColor_Green =      0x0A;
UnderlineColor_Purple =     0x0B;
UnderlineColor_Maroon =     0x0C;
UnderlineColor_Olive =      0x0D;
UnderlineColor_DkGray =     0x0E;
UnderlineColor_LtGray =     0x0F;
