### ISSUE TITLE
Typo in russian quiz section

### ISSUE THREAD

**Issue by ibakirov** [MicrosoftDocs/feedback#1658]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

**Link to article:**
https://docs.microsoft.com/ru-ru/learn/modules/explore-power-bi-service/6-knowledge-check

**Problem:**
Text has typo and has symbol » instead of "@"
> Можно использовать символ "@»", чтобы упомянуть коллегу в комментарии.

**Comment by ryanmajidi** [comment]
@ibakirov Thank you for submitting this issue. This has been added to our internal issue tracking system.
