### ISSUE TITLE
Add APIversion dropdown for the ARM templates

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#166]
The new ARM documentation is great. Should be nice to add the different api versions per schema (likewhise a dropdown)

----------
⚠ Idea migrated from UserVoice

**Created By:** Anonymous
**Created On:** 2017/03/30 18:05:22 +0000
**Votes at Migration:** 2
**Supporters at Migration:** 2

**Comment by dend** [comment]
@tfitzmac something your team can address?

**Comment by Powerhelmsman** [comment]
@tfitzmac Any updates?

**Comment by Powerhelmsman** [comment]
Send a email to @tfitzmac to follow up.

**Comment by tfitzmac** [comment]
Sorry for the slow response. Yes, I see this as something important to implement, and I have heard feedback from others that is needed. 

We have some changes to the generation process coming up in the next month, so I am hoping to work this in.

**Comment by tfitzmac** [comment]
I still think this is an important addition to the template reference docs, but I haven't had time to work on it. I am hoping to get the time soon.

**Comment by tfitzmac** [comment]
API version selector been added to the template reference.

**Comment by tfitzmac** [comment]
#please-close
