### ISSUE TITLE
Can I translate Microsoft documents into Chinese and put them on my blog?

### ISSUE THREAD

**Issue by laughingliu0603** [MicrosoftDocs/feedback#1662]
Can I translate Microsoft documents into Chinese and put them on my blog?And I will not forget to quote the original link.
like this one,https://docs.microsoft.com/zh-cn/windows/mixed-reality/comfort

**Comment by sudeepku** [comment]
@laughingliu0603  - Microsoft documentation usage is governed by the Terms of use document , https://docs.microsoft.com/legal/termsofuse. Redistribution of Microsoft content is prohibited.
Please refer to the terms of use link above
