### ISSUE TITLE
Project blocked

### ISSUE THREAD

**Issue by unpredictablegourav** [MicrosoftDocs/feedback#1666]
Hi There,

I have published multiple projects on TechNet Gallery related to Azure and SCOM but they all has been blocked by admin now.

Kindly help me with the same.

Thanks,
Gourav Kumar
https://social.technet.microsoft.com/profile/gouravin/

**Comment by unpredictablegourav** [comment]
Hi There,

Do we have any update on it.

Thanks,
Gourav Kumar

**Comment by ryanmajidi** [comment]
@dend Can you please take a look at this issue?

**Comment by docs-product** [comment]
Thank you for the feedback @unpredictablegourav - this likely has something to do with you not having enough reputation in the TechNet Gallery. We recommend you submit your code contributions to one of the official Microsoft code sample repositories for a more collaborative workflow.
