### ISSUE TITLE
Work results banner keeps appearing even clicking on Hide this and then selecting Always

### ISSUE THREAD

**Issue by paulcre99** [MicrosoftDocs/feedback#1667]
**Describe the bug**
Work results banner keeps appearing even clicking on Hide this and then selecting Always

**To Reproduce**
1. Go to bing
2. Search for something
3. See work results banner
4. Click on Hide this
5. Click on Always
6. Banner disappears
7. Continue using your computer for a while (not sure exact time maybe an hour)
8. Go to bing
9. Search for something
10. See work results banner *** this should not be there ****

**Expected behavior**
After clicking on Hide this and clicking on Always. The banner should ALWAYS be HIDDEN

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ryanmajidi** [comment]
@paulcre99 Is this happening with just bing or also with docs.microsoft.com?
