### ISSUE TITLE
A BUG in EntityFramewrokCore about ValueGenerateOnAdd() and ValueGenerateOnAddOrUpdate()

### ISSUE THREAD

**Issue by ym9288** [MicrosoftDocs/feedback#1668]
There are my 2 Properties Sets of my Entity：
 entity.Property(e => e.CreateTime)               
                    .HasColumnName("createTime")
                    .HasColumnType("datetime")
                    .IsRequired(true)
                    .ValueGeneratedOnAdd()
                    .HasDefaultValueSql("getdate()");
 entity.Property(e => e.UpdateTime)
                    .HasColumnName("updateTime")
                    .HasColumnType("datetime")
                    .IsRequired(true)
                    .ValueGeneratedOnAddOrUpdate()
                    .HasDefaultValueSql("(getdate())");
they "createTime" use ValueGeneratedOnAdd  and "updateTime" use ValueGeneratedOnAddOrUpdate
It looks like that whenever my Update on my entity should make the "updateTime" be Updated!,and "createTime" should never be updated when I update my entity.
But,when I update my entity,I got the SQL generated by EFCore:
UPDATE [PatientInfo] SET [address] = @p0, [age] = @p1, [ageStr] = @p2, [patientName] = @p3, [phone] = @p4, [sex] = @p5, [createTime] = @p6
      WHERE [patientId] = @p7;
EFCore  updated the "createTime" column，otherwise,did not update "updateTime" column，

At this time,I changed the "createTime" column's Property Set to use ValueGeneratedOnAddOrUpdate(),
and changed the "updateTime" column's Property to use ValueGenerateOnAdd().
with the same opertion of just now(tips:update entity),
here is the SQL
UPDATE [PatientInfo] SET [address] = @p0, [age] = @p1, [ageStr] = @p2, [patientName] = @p3, [phone] = @p4, [sex] = @p5, [updateTime] = @p6
      WHERE [patientId] = @p7;
You see,"updateTime" was seted but no "createTime".
over... here is my contact,you can ask me some questions.
QQ/Email：280823786@qq.com,

**Comment by ryanmajidi** [comment]
@ym9288 moved to the entity framework core issues: https://github.com/aspnet/EntityFrameworkCore/issues/16434
