### ISSUE TITLE
Bad link on dllmain entry point page

### ISSUE THREAD

**Issue by jasonepperly** [MicrosoftDocs/feedback#1669]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

**Link to article:**
https://docs.microsoft.com/en-us/windows/desktop/Dlls/dllmain

**Problem:**
Towards the bottom of the page reads: 

For information on best practices when writing a DLL, see https://www.microsoft.com/whdc/driver/kernel/DLL_bestprac.mspx.

Should read:

For information on best practices when writing a DLL, see https://docs.microsoft.com/en-us/windows/desktop/Dlls/dynamic-link-library-best-practices.

**Comment by mairaw** [comment]
@GrantMeStrength can you take a look at this issue?

**Comment by GrantMeStrength** [comment]
Thank you, this has been corrected.
