### ISSUE TITLE
Give me the option to hide navigation panes

### ISSUE THREAD

**Issue by docs-product** [MicrosoftDocs/feedback#167]
The current doc format has 2 navigation panes on the sides and the content in the center. I use sometime the nav. pane on the left but never the one on the right so i'd like the option to hide it since it makes the center section (with the core content) too narrow. 
The ideal would be the option to hide both so that if user want he can focus just on the content and have all the space dedicated to it. Thanks

----------
⚠ Idea migrated from UserVoice

**Created By:** Antonio
**Created On:** 2017/03/23 11:04:26 +0000
**Votes at Migration:** 14
**Supporters at Migration:** 14

**Comment by ShevaDas** [comment]
We're investigating providing a chromeless rendering experience for users. I've linked this issue to our internal issue so we can follow up when it's implemented. #in-process

**Comment by mairaw** [comment]
@ShevaDas any progress on this? We keep getting new issues about this.

**Comment by ShevaDas** [comment]
@dastaffo is the PM for chromeless, he could likely provide an update.

**Comment by ShevaDas** [comment]
My bad—apparently this is distinct from our chromeless rendering experience and as such needs separate design and engineering work. This isn't something we'll be able to prioritize this quarter with Ignite coming up but I'll work to get it prioritized for Q2. Could you link me any open issues so I can compile them into the VSTS item?

#log-suggestion @ShevaDas

**Comment by Powerhelmsman** [comment]
@ShevaDas I've already closed other related open issue as duplicate. You can update the status on this issue.

**Comment by Powerhelmsman** [comment]
#log-suggestion @ShevaDas

**Comment by botcrane** [comment]
🚀 **ATTENTION**: [Internal request](https://ceapex.visualstudio.com/web/wi.aspx?pcguid=7d644393-99ad-41c8-ac53-7fa79294c720&id=35118) logged.

**Comment by ShevaDas** [comment]
@Powerhelmsman awesome—could you or @mairaw link me to the related issues that have been opened, so I can make a stronger case for prioritizing this feature?

**Comment by mairaw** [comment]
@ShevaDas we usually link to this one to mark as duplicate, so you can see them listed above.

![image](https://user-images.githubusercontent.com/12971179/44139112-f94631de-a02a-11e8-83ca-dea052e809f3.png)

Let me know if you need anything else.

**Comment by rschindhelm-haba** [comment]
Any update on this one?

I'm using Firefox 45.3.0 to view the docs.  Especially on this page I'm not even able to clearly see the contents because the navigation pane's overlapping with the content:
https://docs.microsoft.com/en-us/sql/t-sql/queries/hints-transact-sql-table?view=sql-server-2017

![docs](https://user-images.githubusercontent.com/26774899/45538266-dce35280-b806-11e8-8f58-bdd6e8d7a3ca.png)

Also, in Chrome v69.0.3497.92 the same site works but I see that there are some of the navgiation links missing that are displayed in Firefox:

![docs2](https://user-images.githubusercontent.com/26774899/45538335-13b96880-b807-11e8-824f-f4f6a37d0578.png)

**Comment by dzsquared** [comment]
in the meantime, if you need to get the table of contents out of the way this will take care of it temporarily:

```
$('#left-container').width(2);
$('#sidebar').hide();
$('.primary-holder').width('80%');
$('#main-column').width('95%');
```

especially useful if you have your browser tiled left or right

**Comment by docs-product** [comment]
Thank you all for the feedback! At this time, this is not something we're considering. We will revisit the conversation in the future.

**Comment by BrunoBlanes** [comment]
I really love the Docs and the best experience is when you get to learn by actually implementing what you've learned. When you have just one monitor sharing the screen is the best option and that is when the index menu comes into trouble. It makes all the relevant text much harder to read, specially code, which now needs to be horizontally scrolled.

![image](https://user-images.githubusercontent.com/28227097/78455132-ecd5b800-7672-11ea-9a64-aa632b364d17.png)

@docs-product, please consider collapsing the index menu on a window width basis. Docs have evolved so much and yet this one little feature was never implemented and would in fact improve the readability a whole lot.

In the meantime, @dzsquared, could you clarify how I can use your workaround?

**Comment by dzsquared** [comment]
@BrunoBlanes I have put the workaround together into an Edge/Chrome extension that is available in this repo: https://github.com/dzsquared/MSDocsSidebarCollapser

as well as published in the Edge marketplace for convenience: https://microsoftedge.microsoft.com/addons/detail/hnjdejdpeeojbipggdjdpfdcononmbpn
