### ISSUE TITLE
NuGet's product logo is invisible in some languages

### ISSUE THREAD

**Issue by shunkino** [MicrosoftDocs/feedback#1671]
**Describe the bug**
The product logo of the NuGet on the top page of the Microsoft Docs is invisible in some languages.
I've experienced the issue by setting ja-jp and zh-cn, but I think issue may occur in other languages too.

Links to pages:
https://docs.microsoft.com/ja-jp/
https://docs.microsoft.com/zh-cn/

**To Reproduce**
1. Go to the top page with language other than en-us. Example links above.
2. Tenth element, link to the NuGet document, is invisible.

**Expected behavior**
User should be able to clearly see NuGet's logo.

**Screenshots**
Screenshot of the issue:
![image](https://user-images.githubusercontent.com/7201054/60317077-5fa95880-99a8-11e9-9ee3-119b735be1f2.png)

en-us version, where problem won't happen
![image](https://user-images.githubusercontent.com/7201054/60317589-b748c380-99aa-11e9-8c39-eefc728bbeed.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome, Edge
 - Version: Chrome 75, Edge 44

**Smartphone (please complete the following information):**
--- NOT TESTED ---

**Additional context**
I think this issue is caused because the `home.css` no longer defines `background-color` for the `nuget` class. Contrary to the products shown in the top page, all pages for multiple languages share the same css file. This issue won't happen in en-us page because it has surface instead of NuGet. 

Either:
1. Change the html and show surface instead of NuGet
2. Add `background-color` definition for the `nuget` class

Should resolve the issue. Thanks.

**Comment by SonjaSaltzman** [comment]
Hi @bodhigautam and @DavidPrio could you please treat this as a high prio issue?

**Comment by CeciAc** [comment]
Hello, @shunkino
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by bodhigautam** [comment]
@SonjaSaltzman @CeciAc we are working on it. cc @DavidPrio

**Comment by bodhigautam** [comment]
@SonjaSaltzman @CeciAc @DavidPrio This is resolved now.

**Comment by shunkino** [comment]
@bodhigautam 
Grad to hear that :) 
I've checked the fix in my language. Thanks.

**Comment by mairaw** [comment]
Thank you @bodhigautam! Closing the issue then.
