### ISSUE TITLE
Tenant Active User Quota Reached

### ISSUE THREAD

**Issue by ibakirov** [MicrosoftDocs/feedback#1672]
**Describe the bug**
Can't activate sandbox because error occur:
`
Requesting a Cloud Shell.Failed to provision a Cloud Shell: {"code":"TenantActiveUserQuotaReached","message":"Tenant '604c1504-c6a3-4080-81aa-b33091104187' has '152' active users in location 'centralindia', which exceeds the active user quota."}
`
**To Reproduce**
1. Go to 'https://docs.microsoft.com/ru-ru/learn/modules/welcome-to-azure/4-create-a-vm?pivots=windows-cloud
2. Click on Activate Sandbox
3. Accept agreement and permissions

**Expected behavior**
Sandbox should be activated without error

**Screenshots**
![изображение](https://user-images.githubusercontent.com/7983476/60324342-6040ef80-99a6-11e9-844b-9f63521cf5b9.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 (OS Build 18362.175)
 - Browser: Firefox
 - Version: 67.0.4 (64-bit)

**Additional context**
Maybe sandbox should be region agnostic or less used one, because 'centralindia' region resides in huge population region.

**Comment by ryanmajidi** [comment]
@ibakirov Thank you for this feedback. We have added this to our internal bug tracking system.

**Comment by Darnley** [comment]
The samething here.
![image](https://user-images.githubusercontent.com/4915497/60905342-3cee2e00-a24b-11e9-951e-8538e0c6274f.png)

**Comment by sudhir007rawat** [comment]
Same issue again.

**Comment by mairaw** [comment]
Some information regarding this can be found at https://twitter.com/docsmsft/status/1159615738568564737

**Comment by darnley** [comment]
> Some information regarding this can be found at https://twitter.com/docsmsft/status/1159615738568564737

@ctkano, I guess it's why you was (or are) not able to access the sandbox through Microsoft Learn.

**Comment by cabhilash** [comment]
Got the same problem @ https://docs.microsoft.com/en-us/learn/modules/access-data-with-cosmos-db-and-sql-api/2-setup-cosmosdb


Requesting a Cloud Shell.Failed to provision a Cloud Shell: {"code":"TenantActiveUserQuotaReached","message":"Tenant '604c1504-c6a3-4080-81aa-b33091104187' has '151' active users in location 'southcentralus', which exceeds the active user quota."}

**Comment by ibakirov** [comment]
@cabhilash very disappointing hear that this problem still exists

**Comment by vagoel** [comment]
I got this problem just now ...
![image](https://user-images.githubusercontent.com/8045008/85741239-d51f4480-b734-11ea-992d-3858ba313e5d.png)

**Comment by gitsme** [comment]
I'm getting the very same issue now, so it's still an ongoing issue.

**Comment by grabadias** [comment]
Yep, happening to me right now:  Failed to provision a Cloud Shell: {"code":"TenantActiveUserQuotaReached","message":"Tenant '604c1504-c6a3-4080-81aa-b33091104187' has '150' active users in location 'westeurope', which exceeds the active user quota."}

**Comment by werenskjold** [comment]
I'm getting the same issue 
{"code":"TenantActiveUserQuotaReached","message":"Tenant '604c1504-c6a3-4080-81aa-b33091104187' has '154' active users in location 'northeurope', which exceeds the active user quota."}

**Comment by basvo** [comment]
Same here

`Requesting a Cloud Shell.Failed to provision a Cloud Shell: {"code":"TenantActiveUserQuotaReached","message":"Tenant'604c1504-c6a3-4080-81aa-b33091104187' has '150' active users in location 'northeurope', which exceeds the active user quota."}`

**Comment by Rahtoken** [comment]
I faced this issue today (August 4, 2020).
```
Requesting a Cloud Shell.Failed to provision a Cloud Shell: 

{
"code":"TenantActiveUserQuotaReached",
"message":"Tenant '604c1504-c6a3-4080-81aa-b33091104187' has '353' active users in location 'southeastasia', which exceeds the active user quota."
}
```

I will retry after few hours and check if it was a temporary issue regarding Sandbox's resources.

**Comment by codeWithUtkarsh** [comment]
Failed to provision a Cloud Shell: {"code":"TenantActiveUserQuotaReached","message":"Tenant '9bc8569b-1f4b-45d0-b9f6-8f8db6ec55b2' has '20' activeusers in location 'centralindia', which exceeds the active user quota."}

I am getting this above exception. Can anyone suggest me a solution?

**Comment by ibakirov** [comment]
@codeWithUtkarsh re-try it for a long period of time. I overcome such this limitations on next days
