### ISSUE TITLE
incorrect system time specification

### ISSUE THREAD

**Issue by ogmoz** [MicrosoftDocs/feedback#1677]
https://docs.microsoft.com/en-us/windows/desktop/api/sysinfoapi/nf-sysinfoapi-getsystemtime
"The system time is expressed in Coordinated Universal Time" - incorrect statement.
correct statement should look like this: "The system time corresponds to Coordinated Universal Time (UTC) and supposed to be sinchronised with it."

**Comment by ryanmajidi** [comment]
@GrantMeStrength can you please take a look at this issue?

**Comment by GrantMeStrength** [comment]
Thank you for the feedback! I have updated the text in the topic.

-john
