### ISSUE TITLE
Technical support is supposed to be opened from 8AM to 9PM and it is closed at 5:30 PM and is not opened at 8:10 AM.

### ISSUE THREAD

**Issue by bchicoye** [MicrosoftDocs/feedback#1678]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by bchicoye** [comment]
Technical support is supposed to be opened from 8AM to 9PM and it is closed at 5:30 PM and 8:10 AM. 

"Support technique:

"Français: Lun-Ven 8 AM-9 PM
"Anglais: 24 heures sur 24, 7 jours sur 7
"Autre numéro de téléphone: 01 57 32 42 97
"Frais d'appels locaux appliqués

**Comment by ryanmajidi** [comment]
Please go here https://support.microsoft.com/fr-fr/contactus/ or https://support.microsoft.com/en-us/help/4051701/global-customer-service-phone-numbers.
