### ISSUE TITLE
Pull request builds fail in localized repositories

### ISSUE THREAD

**Issue by MSDN-WhiteKnight** [MicrosoftDocs/feedback#1679]
Pull requests in localized repositories generate build errors such as:

>Line 117: [Error] Restore nuget package W:\qv0n-s\.optemp\dependentPackages\Microsoft.DocAsCode.ECMA2Yaml\packages.config in folder:W:\qv0n-s\.optemp\packages failed, possibly due to transient errors from nuget servers. Please retry building your content. If the issue still happens, open a ticket in http://SiteHelp and include the build report and the following error message for our team to troubleshoot: Errors in packages.config projects Unable to find version '1.0.458' of package 'Microsoft.DocAsCode.ECMA2Yaml'. D:\Windows\system32\config\systemprofile\.nuget\packages\: Package 'Microsoft.DocAsCode.ECMA2Yaml.1.0.458' is not found on source 'D:\Windows\system32\config\systemprofile\.nuget\packages\'. https://www.myget.org/F/op/api/v2: Package 'Microsoft.DocAsCode.ECMA2Yaml.1.0.458' is not found on source 'https://www.myget.org/F/op/api/v2'.

>Line 290: [Error] Restore of dependent packages failed. Please check your .openpublishing.publish.config.json?on the configuration of the dependent packages or ask for help?in Docs Support teams channel. Please also include the following error code for our team to troubleshoot: 1

Examples:

- https://github.com/dotnet/dotnet-api-docs.ru-ru/pull/27
- https://github.com/dotnet/dotnet-api-docs.ja-jp/pull/99

**Comment by ryanmajidi** [comment]
@SonjaSaltzman Can you please take a look at this issue?

**Comment by SonjaSaltzman** [comment]
@DavidPrio and cc: @JasonCard

**Comment by nogic1008** [comment]
In my PRs, it was only caused at [dotnet/dotnet-api-docs.ja-jp](/dotnet/dotnet-api-docs.ja-jp), not at [dotnet/docs.ja-jp](/dotnet/docs.ja-jp).

**Comment by CeciAc** [comment]
Hello, @MSDN-WhiteKnight 
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @MSDN-WhiteKnight

Thank you for your feedback.

We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Thank you for your feedback. 

Our engineer team reviewed your suggestions and accepted them. 

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback. 

Kind regards, 

Microsoft DOCS International Team
