### ISSUE TITLE
Include a search box with the search query on the search results page

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#168]
After searching on the docs, the search result page doesn't include a search box with the search terms to allow me to fine-tune my search based upon the results. This is contrary to Bing, Google, and search experience standards for many years.

----------
⚠ Idea migrated from UserVoice

**Created By:** Paul
**Created On:** 2017/03/20 14:22:42 +0000
**Votes at Migration:** 2
**Supporters at Migration:** 2

**Comment by presleyy** [comment]
We have the search box with the search terms after searching, though it's not that big.
![image](https://user-images.githubusercontent.com/5718438/38012700-12a1d1f0-3295-11e8-9aaf-7efeb05d2279.png)
We have a feature of adding facets in search page, in which we plan to make the search box bigger and centered in search page.

**Comment by Powerhelmsman** [comment]
@dend Shall we close the issue? How can inform the true user.

**Comment by Powerhelmsman** [comment]
I will close this as can't repro. If you have other question related this, we will reopen the issue and continue the discussion.
