### ISSUE TITLE
Ways to Perform AAM in SP Online

### ISSUE THREAD

**Issue by PremK6969** [MicrosoftDocs/feedback#1680]
Hi, Can you please let me know if there is any alternate way to perform Alternate Access Mapping (AAM) in SharePoint Online ?  
I had a requirement to change the domain name of the Site we are using in Our Company for exmaple  "https://sssoft.sharepoint.com/sites/sss/SitePages/DevHome.aspx"to "www.sssoft.com" like that kind of User friendly URL.
Please suggest me any alternate for this requirement.
Thanks in advance

**Comment by ryanmajidi** [comment]
@PremK6969 The [sharepoint support site](https://support.office.com/en-us/sharepoint) should point you in the right direction.
