### ISSUE TITLE
wrong code 

### ISSUE THREAD

**Issue by workeraccount001** [MicrosoftDocs/feedback#1681]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

**Link to article:**
https://docs.microsoft.com/en-us/windows/desktop/wmisdk/swbemeventsource

**Problem:**
What's wrong with the article?
set svc =
CreateObject("Wbemscripting.SWbemLocator")._
   ConnectServer(,"root\cimv2")
should be
set svc = _
CreateObject("Wbemscripting.SWbemLocator")._
   ConnectServer(,"root\cimv2")

**Comment by ryanmajidi** [comment]
@GrantMeStrength Can you please take a look at this issue?

**Comment by workeraccount001** [comment]
copy code of that page , and run, it will prompt "D:\work\code\WMI\2.vbs(2, 10) Microsoft VBScript 编译器错误: 语法错误"

**Comment by GrantMeStrength** [comment]
Thank you - I added the missing _ in the sample code!
