### ISSUE TITLE
Usage details field definitions Property Type Typo

### ISSUE THREAD

**Issue by jmcbkk** [MicrosoftDocs/feedback#1682]
**Link to article:**
https://docs.microsoft.com/en-us/rest/api/billing/enterprise/billing-enterprise-api-usage-detail#usage-details-field-definitions

**Problem:**
typo -  property "consumedServiceID" should be "consumedServiceI**d**"

**Comment by ryanmajidi** [comment]
@bandersmsft Can you please take a look at this issue?

**Comment by bandersmsft** [comment]
@ryanmajidi Will do. Thanks.
#in-process

**Comment by bandersmsft** [comment]
@jmcbkk Thanks for bringing this to our attention. I've fixed this in the doc source and I expect to article to get refreshed live by tomorrow.
#please-close
@ryanmajidi FYI.
