### ISSUE TITLE
Links are broken for "Interlocked Variable Access"

### ISSUE THREAD

**Issue by oreleraki** [MicrosoftDocs/feedback#1684]
https://docs.microsoft.com/en-us/windows/desktop/sync/interlocked-variable-access

Links are broken

**Comment by ryanmajidi** [comment]
@GrantMeStrength Can you please take a look at this issue?

**Comment by oreleraki** [comment]
Links have been fixed.
https://github.com/MicrosoftDocs/win32/commit/731d8a7d637ebc4ad3dcde6470b3cd6473b2434b#diff-83bf3b12d48f4eb6f3f8aba577fd2c9e
https://github.com/MicrosoftDocs/win32/commit/624cb0bc9471517bfeb9c89af2db85115f4effc6#diff-83bf3b12d48f4eb6f3f8aba577fd2c9e
https://github.com/MicrosoftDocs/win32/commit/00dd4f7acd628c34b5e0ea3ae388f2e6beb1ac9b#diff-83bf3b12d48f4eb6f3f8aba577fd2c9e
https://github.com/MicrosoftDocs/win32/commit/56c70d8eb9245028f2826b69c18f8699705d770c#diff-83bf3b12d48f4eb6f3f8aba577fd2c9e

Closing.
