### ISSUE TITLE
could you please remove us from the blacklist?

### ISSUE THREAD

**Issue by OnRoman** [MicrosoftDocs/feedback#1686]
Hello there!
We are an American service and we send a request to your service
"{"eur.olc.protection.outlook.com":["220 AM5EUR02FT052.mail.protection.outlook.com Microsoft ESMTP MAIL Service ready at Fri, 14 Jun 2019 11:27:45 +0000","HELO app.proofy.io","250 AM5EUR02FT052.mail.protection.outlook.com Hello [134.209.230.122]","MAIL FROM:<>","550 5.7.1 Unfortunately, messages from [134.209.230.122] weren't sent. Please contact your Internet service provider since part of their network is on our block list (S3140). You can also refer your provider to http:\/\/mail.live.com\/mail\/troubleshooting.aspx#errors. [AM5EUR02FT052.eop-EUR02.prod.protection.outlook.com]","QUIT",""]}" -- like this and receive the incorrect answer
could you please remove our IP addresses from your blacklists?

Looking forward 
(you can write an answer to team@proofy.io)

**Comment by OnRoman** [comment]
Hello there!
Could please answer, how we can solve this problem, and what we should do to solve this problem(please explain)?
Our service Proofy.io -- is service for bulk email validation and please help me.
Looking forward

**Comment by nschonni** [comment]
This is a repo for feedback on the documentation site. As the bot mentions their is a page that lists support channels at https://support.microsoft.com/allproducts

**Comment by OnRoman** [comment]
ok, could you please tell me what product I should choose? 
and how can I contact with the right person?

**Comment by OnRoman** [comment]
Is it a problem with servers?
could you please help me with this issue?
Looking forward
