### ISSUE TITLE
Container Recipes Link Broken under Next Steps

### ISSUE THREAD

**Issue by bootsinthecity** [MicrosoftDocs/feedback#1687]
**Describe the bug**
Container Recipes Link is Broekn

**To Reproduce**
1. Go to 'https://docs.microsoft.com/en-us/azure/cognitive-services/cognitive-services-container-support#next-steps'
2. Click on 'container recipes'
3. See 404 error

**Expected behavior**
I expected to see another webpage.

**Comment by ryanmajidi** [comment]
Moved to Azure repo issue: https://github.com/MicrosoftDocs/azure-docs/issues/34481
