### ISSUE TITLE
TechNet site won't let me include links in my posts. Says my account is not verified.

### ISSUE THREAD

**Issue by birds3chas** [MicrosoftDocs/feedback#1688]
I can post things to the the TechNet site but when I try to include a web link it pops up & says I can't because my account is not verified. What do I need to do? I am registered with the TechNet site.

**Comment by ryanmajidi** [comment]
@birds3chas Where are you trying to make a post?

**Comment by birds3chas** [comment]
https://social.technet.microsoft.com/Forums/en-US/939cfd24-a0ea-4ca1-9cbc-92ddd0bea4db/screen-flickers-wildly-only-in-safe-mode?forum=win10itprogeneral

**Comment by MSDN-WhiteKnight** [comment]
See this thread: https://social.technet.microsoft.com/Forums/en-US/dc4002e4-e3de-4b1e-9a97-3702387886cc/verify-account-42?forum=reportabug

**Comment by birds3chas** [comment]
Thank you so much for your help!
Patty 
 
 
 
 
-------Original Message-------
 
From: MSDN.WhiteKnight
Date: Sunday, July 7, 2019 2:24:09 AM
To: MicrosoftDocs/feedback
Cc: birds3chas;  Mention
Subject: Re: [MicrosoftDocs/feedback] TechNet site won't let me include
links in my posts. Says my account is not verified. (#1688)
 
See this thread: https://social.technet.microsoft
com/Forums/en-US/dc4002e4-e3de-4b1e-9a97-3702387886cc/verify-account-42?forum
reportabug

**Comment by ryanmajidi** [comment]
Thank you @MSDN-WhiteKnight
