### ISSUE TITLE
IsDialogMessage § Remarks ¶ 4

### ISSUE THREAD

**Issue by WhiteSmith137** [MicrosoftDocs/feedback#1689]
In the articles for `IsDialogMessageA` and `IsDialogMessageW`, in the "Remarks" section, paragraph 4:
> `IsDialogMessage` sends `WM_GETDLGCODE` messages **to the dialog box procedure** to determine which keys should be processed.

This contradicts the article for `WM_GETDLGCODE`, which (correctly) specifies that the message is sent to a *control*, not the dialog box itself. I believe the correction could be something like this:
> `IsDialogMessage` sends `WM_GETDLGCODE` messages **to the control to which a keyboard message is destined** to determine which keys should be processed.

https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-isdialogmessagew#remarks

**Comment by ryanmajidi** [comment]
@GrantMeStrength Can you please take a look at this issue?

**Comment by GrantMeStrength** [comment]
Thanks for taking the time to let us know about this and I sincerely apologize for the delayed response. This is an older topic, and it's tricky to find a subject matter expert who can provide an authoritative answer.  At this time the best I can do is  redirect you to the  community of experts and Microsoft Engineers over at [Microsoft Q&A](https://docs.microsoft.com

If you do create a thread over at Microsoft Q&A, it would be fantastic if you could share that link here so I can track the progress and potentially incorporate the technical details into our documentation. Though I'm marking this Issue as closed now, please treat this thread as an open thread for follow-ups. Thanks!

-john
