### ISSUE TITLE
Syntax C#

### ISSUE THREAD

**Issue by KislitsynMikhail** [MicrosoftDocs/feedback#1691]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.
kislitsyn19997@gmail.com
kislitsyn97@yandex.ru

**Link to article:**
Tell us where exactly a problem occurs.
https://docs.microsoft.com/en-us/dotnet/api/system.threading.cancellationtokensource?view=netframework-4.8

**Problem:**
What's wrong with the article?
The core syntax of C# language is similar to that of other C-style languages such as C, C++ and Java. But you use javascript-syntax(or other, i don't know exactly) in article. It's not good. We are angry. Please, fix it. Thanks

**Comment by sudeepku** [comment]
@KislitsynMikhail - thanks for your feedback. You can use the programming language selector from the top  to change it to another programming language available.
![image](https://user-images.githubusercontent.com/16726119/60741021-d00e2780-9f1c-11e9-9e2c-8f53be55e0d2.png)

**Comment by sudeepku** [comment]
@mairaw FYI.

**Comment by mairaw** [comment]
I don't understand the original feedback. If you can point out where you think you were seeing syntax that is not C# @KislitsynMikhail, that would help understand if there's really a problem with the page or not. I'm looking at it and when I have C# selected, all I see is C# code.

**Comment by KislitsynMikhail** [comment]
Maybe, I said not clear. I mean that in C# block opens on a new line, and in JavaScript it is not so.For example:C#:void MethodName(){//Code}JS:function funcName () {//Code}I understand that it is not very important, but in C# so accepted. And for me and other people is read a C# code in js-style is very hard. 12:36 AM, July 6, 2019, Maira Wenzel <notifications@github.com>:I don't understand the original feedback. If you can point out where you think you were seeing syntax that is not C# @KislitsynMikhail, that would help understand if there's really a problem with the page or not. I'm looking at it and when I have C# selected, all I see is C# code.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
-- Sent from Yandex.Mail for mobile

**Comment by mairaw** [comment]
The response is not formatted properly @KislitsynMikhail so both C# and JS examples look the same. Are you referring to using [Allman style braces](https://en.wikipedia.org/wiki/Indentation_style#Allman_style)?
That would be our preferred coding style indeed and we could fix that if that's what you're referring to.

**Comment by KislitsynMikhail** [comment]
Thank you. And sorry for my English and not clear sentences. Your site helps me and my colleagues a lot. Thanks. 1:08 AM, July 6, 2019, Maira Wenzel <notifications@github.com>:The response is not formatted properly @KislitsynMikhail so both C# and JS examples look the same. Are you referring to using Allman style braces?
That would be our preferred coding style indeed and we could fix that if that's what you're referring to.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
-- Sent from Yandex.Mail for mobile
