### ISSUE TITLE
Order of code comment is incorrect

### ISSUE THREAD

**Issue by Taylor-Hasterd** [MicrosoftDocs/feedback#1693]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

**Link to article:**
Tell us where exactly a problem occurs.
https://docs.microsoft.com/en-us/windows/win32/xaudio2/how-to--load-audio-data-files-in-xaudio2

**Problem:**
What's wrong with the article?
In the last code example showed in this article:

> buffer.AudioBytes = dwChunkSize;  //buffer containing audio data
buffer.pAudioData = pDataBuffer;  //size of the audio buffer in bytes
buffer.Flags = XAUDIO2_END_OF_STREAM; // tell the source voice not to expect any data after this buffer

the first comment should be swapped with the second one.

**Comment by sudeepku** [comment]
@GrantMeStrength - could you please take a look and assign as appropriate.

**Comment by GrantMeStrength** [comment]
Thank you, fixed!
