### ISSUE TITLE
Identity picker and scroll

### ISSUE THREAD

**Issue by dominionish** [MicrosoftDocs/feedback#1694]
Hello everyone!

I use this react component from azure-devops: https://azdevui.azureedge.net/azure-devops/components/identity-picker and it is great!

But I found one small issue. You can reproduce it right on component page description  (https://developer.microsoft.com/en-us/azure-devops/components/identity-picker)
1. Click on component field
![image](https://user-images.githubusercontent.com/8955774/60717828-6dc51f00-9f3c-11e9-84ba-a68f3c599dc0.png)
2. Suggest list will be open
![image](https://user-images.githubusercontent.com/8955774/60717876-951bec00-9f3c-11e9-87b7-c4e4395750e2.png)
3. Try to scroll browser page down and you will see this picture:
![image](https://user-images.githubusercontent.com/8955774/60717898-a6fd8f00-9f3c-11e9-8da7-5ecad0b8c288.png)
You can see space between component and the list of users. The more you scroll - the more the space.

**Comment by sudeepku** [comment]
@dominionish - thanks for your feedback. Could you please report this issue here https://developercommunity.visualstudio.com/spaces/21/index.html .

**Comment by dominionish** [comment]
https://developercommunity.visualstudio.com/content/problem/636085/identity-picker-and-scroll.html
