### ISSUE TITLE
Typo in docs => Azure Container Service (AKS)

### ISSUE THREAD

**Issue by geirivarjerstad** [MicrosoftDocs/feedback#1695]
Typo in:
https://docs.microsoft.com/en-us/rest/api/containerregistry/

Is:

Azure Container Service (AKS) - Deploy and manage containerized applications in a hosted Kubernetes environment.

Should be:

Azure Kubernetes Service (AKS) - Deploy and manage containerized applications in a hosted Kubernetes environment.

**Comment by sudeepku** [comment]
@geirivarjerstad - thank you for your feedback. I have transferred the issue to  source repo where this topic was written and notified the writers.
