### ISSUE TITLE
.NET API browser: sort order makes no sense

### ISSUE THREAD

**Issue by roji** [MicrosoftDocs/feedback#1699]
When searching for an API in the [.NET API Browser](https://docs.microsoft.com/en-us/dotnet/api/?term=dictionary), results come out in a very odd and unproductive order. For example, searching for Dictionary yields:

```
Java.Util.Dictionary
Foundation.DictionaryContainer
System.Collections.DictionaryBase
System.Collections.DictionaryEntry
ExchangeWebServices.DictionaryURIType
Microsoft.Office.Interop.Word.Dictionary
System.Configuration.DictionarySectionHandler
System.Web.Mvc.DictionaryValueProvider<TValue>
System.Collections.Generic.Dictionary<TKey,TValue>
```

The typical class being searched for - System.Collections.Generic.Dictionary - is in 9th place, after some explicitly obsolete types (Java.Util.Dictionary) and some extremely specific rare ones (ExchangeWebServices.DictionaryURIType).

A simple scheme, such as showing certain prefixes above others (e.g. System), would probably improve the situation considerably. Pushing obsolete results down (and marking them visually) would also help, etc.

**Comment by ryanmajidi** [comment]
@rloutlaw Can you please take a look at this issue?

**Comment by mairaw** [comment]
Tagging @mimisasouvanh as well

**Comment by mimisasouvanh** [comment]
We are tracking this internally. https://github.com/MicrosoftDocs/feedback/issues/224

**Comment by roji** [comment]
@mimisasouvanh feel free to close this if #224 already tracks the problem and this issue brings no extra value.

**Comment by mimisasouvanh** [comment]
@roji Thanks Shay! Unfortunately, I don't have the proper permission level to close this issue.
