### ISSUE TITLE
Typo in Publish and Sharing section

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#17]
Under the section Publish and Sharing there is a typo DAYS: "With Power BI, there are a few days you can make printouts of your visuals" . It should be WAYS.

----------
⚠ Idea migrated from UserVoice

**Created By:** SK
**Created On:** 2018/02/27 01:29:33 +0000
**Votes at Migration:** 1
**Supporters at Migration:** 1

**Comment by dend** [comment]
Related to this:
https://docs.microsoft.com/en-us/power-bi/guided-learning/publishingandsharing#step-3

@kfile - can you help route this to the right person?

**Comment by Powerhelmsman** [comment]
@davidiseminger Can you fix it? @kfile for awareness.

**Comment by kfile** [comment]
@davidiseminger  is the rightful owner. He's now seen this and the email so I expect it will be resolved soon. Thanks.

**Comment by Sampy** [comment]
@davidiseminger has fixed this so thanks for the feedback!
