### ISSUE TITLE
Keep left menu consistent

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#170]
I click on "Getting Started" under the C# Guide heading and all the higher level links in that menu then disappear. If i click on "What's new in C#" then the left menu stays consistent. I can't imagine that is deliberate.

----------
⚠ Idea migrated from UserVoice

**Created By:** James Urry
**Created On:** 2017/03/13 11:31:55 +0000
**Votes at Migration:** 2
**Supporters at Migration:** 2

**Comment by BillWagner** [comment]
There's some ideas in the works here.

TL;DR; version: The .NET guide(s) would have a single TOC that's both too long and too deep to be really useful. As a result, we've gone to local TOCs at a number of levels. The breadcrumbs are the only substitute, and we know it's a poor one.

We're currently looking through all the content, and developing a larger navigation strategy. It will be a while, but it's known.

@Dend This may be wholly a content issue. If so, do you want to close this, and open a corresponding issue on the /dotnet/docs repo?

**Comment by dend** [comment]
@BillWagner agree, a content issue that should be tracked in the content repo. @Powerhelmsman will help with moving the issue there.

**Comment by Powerhelmsman** [comment]
@BillWagner I created a new issue on dotnet/docs repo. here is the link https://github.com/dotnet/docs/issues/4572. Please keep working on the issue there.
