### ISSUE TITLE
.NET API Browser: include nuget package which contains the API

### ISSUE THREAD

**Issue by roji** [MicrosoftDocs/feedback#1700]
On the [.NET API Browser](https://docs.microsoft.com/en-us/dotnet/api/), the namespace and assemblies including APIs are mentioned. However, the nuget package containing the API is arguably much more important than the assembly.

For example, looking at [HttpUtility.ParseQueryString() on .NET Core](https://docs.microsoft.com/en-us/dotnet/api/system.web.httputility.parsequerystring?view=netcore-2.2), nothing tells me which nuget package I need to install in order to get the API (Microsoft.AspNetCore.WebUtilities).

**Comment by ryanmajidi** [comment]
@rloutlaw Can you please take a look at this issue?

**Comment by mairaw** [comment]
I'm closing as duplicate of #72
