### ISSUE TITLE
HLSL sm4 ALM reference for round_ni incorrectly refers to round_ne

### ISSUE THREAD

**Issue by zogi** [MicrosoftDocs/feedback#1701]
**Link to article:**
https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/round-ni--sm4---asm-

**Problem:**
In the Remarks section the article states:
"round_ne rounds toward -infinity, commonly known as floor()."
Should refer to round_ni instead of round_ne (the latter rounds towards nearest even).

![hlsl_asm_round_ni_feedback](https://user-images.githubusercontent.com/2511923/60768781-3b482d00-a0c8-11e9-9685-187f29790136.png)

**Comment by ryanmajidi** [comment]
@GrantMeStrength Can you please take a look at this issue?

**Comment by GrantMeStrength** [comment]
Thanks, fixed!
