### ISSUE TITLE
Throttling limit seems to be 60 minutes and not 60 seconds

### ISSUE THREAD

**Issue by jonathanneo** [MicrosoftDocs/feedback#1704]
**Link to article:**
https://docs.microsoft.com/en-gb/connectors/powerbi/

**Problem:**
Throttling limit seems to be 60 minutes and not 60 seconds. 

Could you please check if it is 60 minutes, and not 60 seconds? And if so, please update documentation to reflect the correct figure. 
![image](https://user-images.githubusercontent.com/16749633/60786428-1e276300-a189-11e9-85f8-15ca28e0b8dc.png)

**Comment by ryanmajidi** [comment]
@miriver can you please take a look at this issue?

**Comment by miriver** [comment]
@ryanmajidi I don't work on the Connectors team anymore. Please email RoAceves / PratikP to find the right owner.

**Comment by revanth1996** [comment]
The throttling limit is for 60 seconds. We allow 100 API calls per connection per 60 seconds
