### ISSUE TITLE
Improperly escaped HTML tags

### ISSUE THREAD

**Issue by Crypt32** [MicrosoftDocs/feedback#1706]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

**Link to article:**
https://docs.microsoft.com/en-us/windows/win32/api/certcli/nf-certcli-icertrequest2-getcapropertydisplayname
https://docs.microsoft.com/en-us/windows/win32/api/certcli/nf-certcli-icertrequest2-getcapropertyflags
https://docs.microsoft.com/en-us/windows/win32/api/certcli/nf-certcli-icertrequest2-getissuedcertificate
https://docs.microsoft.com/en-us/windows/win32/api/certcli/nf-certcli-icertconfig-getconfig
**Problem:**
Improperly escaped HTML tags

**Comment by ryanmajidi** [comment]
@GrantMeStrength Can you please take a look at this issue?

**Comment by GrantMeStrength** [comment]
Thank you! Thanks to this report, I was able to fix broken formatting in over 100 topics!
