### ISSUE TITLE
Suggestion: Implement full exam/certification prep in Microsoft Learn

### ISSUE THREAD

**Issue by weitzhandler** [MicrosoftDocs/feedback#1708]
It would be awesome if Microsoft Learn offered full exam and education path exam prep.

For instance a learning path that takes you through full preparation for the 70-483 C# exam, or even full MCSA/MCSD learning paths.
Turning MS Learn into a full MOOC and offer online exams/prep-exams as well would be even more amazing.

Thank you!

**Comment by ryanmajidi** [comment]
@weitzhandler  Thank you for the feedback, we have submitted this into our internal ticketing system.

**Comment by weitzhandler** [comment]
Thanks for your response!

There are no [courses](https://docs.microsoft.com/en-us/learn/certifications/courses/browse/?roles=developer) about C#, .NET, UWP or anything Microsoft at all.

![image](https://user-images.githubusercontent.com/2716316/79082354-e65bd600-7d2d-11ea-8863-0a5cbe2f1128.png)

Neither are there any developing [exams or certificates](https://docs.microsoft.com/en-us/learn/certifications/browse/?roles=developer):
![image](https://user-images.githubusercontent.com/2716316/79082432-94678000-7d2e-11ea-9f00-3134bd52c891.png).
