### ISSUE TITLE
MVA courses for understanding docs

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#171]
I suggest that you should create some MVA courses which have experts talking about docs.

----------
⚠ Idea migrated from UserVoice

**Created By:** Saalam Zia
**Created On:** 2017/03/11 09:30:33 +0000
**Votes at Migration:** 1
**Supporters at Migration:** 1

**Comment by dend** [comment]
We are generally very open about docs - I will bootstrap a conversation with the team about documentation talks on existing video channels.

cc: @thedanfernandez @mairaw @BillWagner

**Comment by BillWagner** [comment]
Do you have any specifics about what kind of content about docs was requested?

**Comment by dend** [comment]
@BillWagner content that shows how to contribute to docs, intricacies of the platform, etc.

**Comment by dend** [comment]
Closing this issue for now. Please refer to our [contributor guide](https://docs.microsoft.com/en-us/contribute/) to learn more about how to contribute to docs.microsoft.com.

**Comment by mairaw** [comment]
There’s also the streaming that @csharpfritz and I did on Twitch talking about docs:
https://youtu.be/rZj-h9PQsi8
