### ISSUE TITLE
"Recommended Version" banner displays on pages with no newer version

### ISSUE THREAD

**Issue by NReilingh** [MicrosoftDocs/feedback#1710]
**Describe the bug**
When viewing a page of documentation on a supported feature that was last documented in a previous version of windows (and does not have documentation in the current version docs), a banner displays on the page asking the reader to navigate to a "Recommended Version" that does not exist, so the reader is instead navigated to the root of the current version docs.

**To Reproduce**
1. Go to [Configure Firewall Port Requirements for Group Policy](https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-r2-and-2012/jj572986(v%3Dws.11))
2. Click on "Recommended Version"

**Expected behavior**
The "Recommended Version" banner should not display on this doc, because there is no newer version.

OR

The user is navigated to an article titled "Configure Firewall Port Requirements for Group Policy" in the current version Windows Server documentation.

**Actual behavior**
The user is navigated to the root [Windows Server documentation](https://docs.microsoft.com/en-us/windows-server/index) page.

**Platform:**
- All browsers and platforms that run JavaScript

**Additional context**
Issue #1179 speaks to this, but is slightly off in its analysis of the issue since it's not that context is discarded, it's that a newer version of the doc in question _doesn't actually exist_, so the next-contextually-closest page is returned instead.

When no equivalent topic exists (AND the topic is of course still a supported feature of the Windows Server platform), the header/banner should NOT display.

**Comment by ryanmajidi** [comment]
@GrantMeStrength Can you please take a look at this issue?

**Comment by GrantMeStrength** [comment]
Thanks, I understand what you mean. I will follow up with the team who owns the "previous versions" site to see if this experience can be improved. Thank you for taking the time to report it.
