### ISSUE TITLE
Incorrect variable name lpInitData on CreateDCA/CreateDCW

### ISSUE THREAD

**Issue by mjimji** [MicrosoftDocs/feedback#1714]
_**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**._
**I don't see a comment section.**

**Link to article:**
https://docs.microsoft.com/en-us/windows/win32/api/wingdi/nf-wingdi-createdca

**Problem:**
The CreateDCA and CreateDCW functions use the variable name lpInitData but this should be changed to pdm to match the new name of the parameter.

**Comment by drewbatgit** [comment]
Thanks for reporting this issue! The content has been updated with the new param names. You should see it on the live site in ~24 hours.
