### ISSUE TITLE
Winsock Server Code Build Problem

### ISSUE THREAD

**Issue by mhepeyiler** [MicrosoftDocs/feedback#1716]
Hello to everyone, I have been working on Winsock server code. But I have faced up an error, actually many many errors :) I have written complete code which is given in below link. Then, I build it, I have faced up these -some of it- errors. 

`Severity	Code	Description	Project	File	Line	Suppression State
Error	C2568	'=': unable to resolve function overload	Server	c:\users\murat\desktop\programming\cpp\socket\server\server\server.cpp	29	
Error	C2568	'=': unable to resolve function overload	Server	c:\users\murat\desktop\programming\cpp\socket\server\server\server.cpp	51	
Error	C2568	'=': unable to resolve function overload	Server	c:\users\murat\desktop\programming\cpp\socket\server\server\server.cpp	60	
Error	C2568	'=': unable to resolve function overload	Server	c:\users\murat\desktop\programming\cpp\socket\server\server\server.cpp	83	
Error	C2568	'=': unable to resolve function overload	Server	c:\users\murat\desktop\programming\cpp\socket\server\server\server.cpp	94	
Error	C2568	'=': unable to resolve function overload	Server	c:\users\murat\desktop\programming\cpp\socket\server\server\server.cpp	99	
Error	C2446	'==': no conversion from 'int' to 'int (__cdecl *)(SOCKET,int)'	Server	c:\users\murat\desktop\programming\cpp\socket\server\server\server.cpp	71	
Error	C2375	'accept': redefinition; different linkage	Server	c:\program files (x86)\windows kits\10\include\10.0.17763.0\um\winsock2.h	1625	
Error	C2065	'accept': undeclared identifier	Server	c:\users\murat\desktop\programming\cpp\socket\server\server\server.cpp	83	
Error	C2375	'bind': redefinition; different linkage	Server	c:\program files (x86)\windows kits\10\include\10.0.17763.0\um\winsock2.h	1647	
`
[](https://docs.microsoft.com/en-us/windows/win32/winsock/complete-server-code)

But when I remove  `#include <windows.h>` from it. The code can build without any error. What is the problem? Why does this happen? Is it a bug? or it changes due to time?

VS Community 2017 
Version 15.9.7

Windows 10, version 1903

**Comment by ryanmajidi** [comment]
@GrantMeStrength Can you please take a look at this issue?

**Comment by GrantMeStrength** [comment]
Thanks for taking the time to let us know about this and I sincerely apologize for the delayed response. Though the scope of our feedback channel here on GitHub covers specific documentation fixes, I can help redirect you to the right support channel to get an answer to your question. The community of experts and Microsoft Engineers over at [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-uwp.html) offer timely answers to a multitude of technical questions surrounding windows-uwp.

If you do create a thread over at Microsoft Q&A, it would be fantastic if you could share that link here so I can track the progress and potentially incorporate the technical details into our documentation. Though I'm marking this Issue as closed now, please treat this thread as an open thread for follow-ups. Thanks!
