### ISSUE TITLE
the https://docs.microsoft.com/en-us/learn/ is not working

### ISSUE THREAD

**Issue by caseygore** [MicrosoftDocs/feedback#1719]
I keep getting an error 500 message. I even cleared my cookies and cache and I am still getting the error. I have also tried using 3 separate browsers in public and private mode.

**Comment by ryanmajidi** [comment]
@caseygore What page are you trying to view?

**Comment by ryanmajidi** [comment]
Closing. Please open another issue if this is still happening.
