### ISSUE TITLE
Adding Notes & Highlights For Future Reference

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#172]
It would be better if there is an option to add our private notes for reference [like we do in Skillpipe course wares] instead of current side notes feature

----------
⚠ Idea migrated from UserVoice

**Created By:** Abirami Rajendran
**Created On:** 2017/03/09 23:16:31 +0000
**Votes at Migration:** 1
**Supporters at Migration:** 1

**Comment by dend** [comment]
Closing as this is not something our team will be building at this point.
