### ISSUE TITLE
Contrast for highlighted code in Light theme is way too low

### ISSUE THREAD

**Issue by andre-ss6** [MicrosoftDocs/feedback#1722]
**Describe the bug**
There are times when there is a lot of code amidst the important piece of code in a specific example. That code is highlighted so that your attention is drawn to it. However, the contrast is _way_ too low for the Light theme.

For reference, here are some pictures from my screen:

![image](https://user-images.githubusercontent.com/15827357/61155444-5d2a2100-a4c7-11e9-8a49-9cd288bd606f.png)

![image](https://user-images.githubusercontent.com/15827357/61155453-61eed500-a4c7-11e9-9c3b-07abe00c2805.png)

This is a problem with viewing angles. If I look at the screen at an angle, I see the different color. 

In order for this kind of thing to work on every screen (especially LCDs), the contrast has to be higher. With the Dark theme, the contrast is way higher (even a bit distracting, maybe 😁).

**To Reproduce**
1. Use a cheap LCD screen??
2. https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-2.2&tabs=visual-studio
3. Choose Light theme
4. Scroll down to the place shown in the picture above
5. Fail to see the highlight

**Expected behavior**
I can clearly see which lines are highlighted

**Desktop (please complete the following information):**
 - OS: Windows 10 1903
 - Browser: Chrome
 - Version: 73

**Comment by ryanmajidi** [comment]
@andre-ss6 Thank you for the feedback, we have submitted this into our internal ticketing system.

With the current theme it isn't to do with the price of the monitor but primarily with the panel type. There are different types of LCD panels and some of them are better or worse at displaying true colors depending on the viewing angle.
