### ISSUE TITLE
Subject index — an auxiliary index,

### ISSUE THREAD

**Issue by KenyaLS** [MicrosoftDocs/feedback#1725]
> Предметный указатель — вспомпомогательный указатель, в заголовках рубрик которого названы предметы, сведения о них содержатся в тексте издания и могут быть потенциальным объектом поиска.

**Subject index** — an auxiliary index, in the headings of the headings of which the objects are named, information about them is contained in the text of the publication and can be a potential search object.
About(Keywords) :printer: :
1. O - OpenApi page in the book 26
2. @ - @page page in the book 26
3. @ - @model page in the book 56
4. @ - @Html.DisplayFor page in the book 56
5. @ - @RenderBody page in the book 57

And so like that.
The main words in the book it will be quicker to remember the command on the eye when you know the documentation
https://github.com/aspnet/AspNetCore.Docs/issues/13272

![image](https://user-images.githubusercontent.com/20774076/61170080-b05eab00-a57d-11e9-9184-a6cad5cb580a.png)

**Comment by ryanmajidi** [comment]
@KenyaLS thank you for the feedback. We have submitted this in our internal ticketing system.
