### ISSUE TITLE
Learn > Azure > impossible to complete module

### ISSUE THREAD

**Issue by Alexis-Notine** [MicrosoftDocs/feedback#1727]
I've finished the module Core Cloud Services - Introduction to Azure but the sandbox is KO :
![sandboxKO](https://user-images.githubusercontent.com/12659351/61174860-6a6a0d00-a5a6-11e9-8c4f-f10e22aa71fb.png)

I have had to use my live Azure account to test VM, so no problem for learning but; IMPACT : impossible to finish the course.

![modulenotcompleted](https://user-images.githubusercontent.com/12659351/61174863-7229b180-a5a6-11e9-89b9-b11231a6cea7.png)

Is it possible to validate the module and /or delete his dependance in case of a faulty sandbox ?

Thanks for your help :)

**Comment by sereth** [comment]
Also seeing this issue in the Azure DevOps course: https://docs.microsoft.com/en-us/learn/modules/host-build-agent/4-create-build-agent

**Comment by Alexis-Notine** [comment]
Thanks a lot Michael... I hope they fixed it... for everybody :)
Something like service not available => item non mandatory => automatic validation if Knowledge check OK ?

**Comment by hadiulla** [comment]
Same issue for the below URLs as well.
https://docs.microsoft.com/en-us/learn/modules/build-azure-vm-templates/4-deploy-a-vm-quickstart-template?pivots=windows-cloud

https://docs.microsoft.com/en-us/learn/modules/build-azure-vm-templates/6-extend-the-quickstart-template?pivots=windows-cloud

https://docs.microsoft.com/en-us/learn/modules/add-and-size-disks-in-azure-virtual-machines/3-exercise-add-data-disks-to-azure-virtual-machines

....

**Comment by mairaw** [comment]
@markjulmar can you please take a look at the issues reported here?

**Comment by Alexis-Notine** [comment]
@mairaw thank you for your help :)

**Comment by juanfelipebetancur** [comment]
Same issue here. I also get the error message "Unauthorized Sandbox use detected. Your sandbox has been terminated" for Sandbox in this site:
https://docs.microsoft.com/en-us/learn/modules/manage-secrets-with-azure-key-vault/3-creating-vaults-storing-secrets

**Comment by docs-product** [comment]
This is now covered by #1797
