### ISSUE TITLE
Word spelled incorrectly.

### ISSUE THREAD

**Issue by Taylor-Hasterd** [MicrosoftDocs/feedback#1728]
**Link to article:**
https://docs.microsoft.com/en-us/cpp/cpp/stdcall?view=vs-2019

**Problem:**
In the article, the word "caller" is spelled as "callee" in the first sentence of the article.
The sentence is:
> The __stdcall calling convention is used to call Win32 API functions. The callee cleans the stack, so the compiler makes vararg functions __cdecl. Functions that use this calling convention require a function prototype.

**Comment by ryanmajidi** [comment]
@Taylor-Hasterd  Transferred to that repo: https://github.com/MicrosoftDocs/cpp-docs/issues/1410
