### ISSUE TITLE
Make the docs more interactive (as Xamarin workbook)

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#173]
It would be great if the docs could be a little bit more interactive as Xamarin workbooks. Making the documentation exportable to Xamarin workbooks would be interesting for example. 

The nicest thing would be that the examples on the documentation could be directly executed on the website. 

----------
⚠ Idea migrated from UserVoice

**Created By:** Anonymous
**Created On:** 2017/03/09 19:13:02 +0000
**Votes at Migration:** 4
**Supporters at Migration:** 4

**Comment by Powerhelmsman** [comment]
Thanks folks as we shipped it. https://docs.microsoft.com/en-us/learn/intro-to-csharp/hello-world?tutorial-step=1
