### ISSUE TITLE
Website not displayed correctly in any browser on Windows 10 (Firefox/Chrome/InternetExplorer/Edge)

### ISSUE THREAD

**Issue by fun29** [MicrosoftDocs/feedback#1730]
**Describe the bug**
social.technet.microsoft.com looks like a notepad document.

**To Reproduce**
1. Use any browser on Windows 10 to visit: https://social.technet.microsoft.com

**Expected behavior**
A normal functioning website with stylesheets etc.

**Screenshots**
![microsoft](https://user-images.githubusercontent.com/52833515/61184008-ace42600-a648-11e9-9b6c-d6e78f755fca.png)

**Desktop (please complete the following information):**
See screenshot:
Windows 10 Pro 64bit
Internet explorer 11 (the version popup does not allow copy paste so you can type the superlong version yourself.)
Chrome  75.0.3770.100 (Official Build) (64-bit) (cohort: Stable)
Firefox 68.0 (64-bit)

**Comment by Z-Doctor** [comment]
I have windows 10 and tried this site on Google Chrome, Edge and Internet Explorer and all three loaded correctly. I would suggest trying to reset chrome, clear the cache or reinstalling chrome if the issue still persists.

**Comment by fun29** [comment]
![image](https://user-images.githubusercontent.com/52833515/61559676-879d5080-aa6a-11e9-96b3-735cfa89701c.png)

**Comment by sudeepku** [comment]
@fun29 thanks for reporting this. It was likely a temporary glitch. The issue is no longer reproducible.

**Comment by fun29** [comment]
Agreed, no longer reproducible for me either.
