### ISSUE TITLE
typo on Proxies doc

### ISSUE THREAD

**Issue by videlalvaro** [MicrosoftDocs/feedback#1732]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

**Link to article:**
Tell us where exactly a problem occurs.

**Problem:**
What's wrong with the article?

**Comment by ryanmajidi** [comment]
@videlalvaro Please submit this feedback to the article itself. You can do this by using the feedback section at the bottom
![image](https://user-images.githubusercontent.com/7329992/61403141-882ac100-a889-11e9-99e3-12d71f7c193f.png)
