### ISSUE TITLE
docs content doesn't match what happens on Panel 

### ISSUE THREAD

**Issue by videlalvaro** [MicrosoftDocs/feedback#1733]
Article: https://docs.microsoft.com/en-us/azure/azure-functions/functions-proxies

Problem:

The wording `In the left pane, select New proxy.` doesn't reflect the current version of the panel. The plus button for adding a proxy only shows up if you select "Proxies" after you clicked on your function app.

Also in my case Proxies were in read only mode. See answer here: https://stackoverflow.com/questions/53630773/how-to-disable-read-only-mode-in-azure-function-app

**Comment by ryanmajidi** [comment]
@videlalvaro Please submit this feedback to the article itself. You can do this by using the feedback section at the bottom
![image](https://user-images.githubusercontent.com/7329992/61403141-882ac100-a889-11e9-99e3-12d71f7c193f.png)
