### ISSUE TITLE
be explicit that local.settings shouldn't be committed & pushed to GitHub

### ISSUE THREAD

**Issue by videlalvaro** [MicrosoftDocs/feedback#1734]
Article: https://docs.microsoft.com/en-us/azure/azure-signalr/signalr-quickstart-azure-functions-javascript

Problem:

In the article we tell users to set `AzureSignalRConnectionString` in their `local.settings` file. While from info here and there we can piece together that this file shouldn't be committed to git and shared publicly, that's not entirely clear, and I think we should have a call out box explaining the security problem.

For example, see this GitHub search: https://github.com/search?q=AzureSignalRConnectionString+AccessKey&type=Code where people push code with their secret keys.

Concrete example: https://github.com/RachanaBadekar/FlightDataFunnctionApp/blob/c1f2ad52f01e202f33fb42cd890c5388f9b91e28/FlightDataFunnctionApp/local.settings.json

**Comment by ryanmajidi** [comment]
@videlalvaro Please submit this feedback to the article itself. You can do this by using the feedback section at the bottom
![image](https://user-images.githubusercontent.com/7329992/61403141-882ac100-a889-11e9-99e3-12d71f7c193f.png)
