### ISSUE TITLE
Article should give some background behind 'negotiate' & 'messages' SignalR endpoints

### ISSUE THREAD

**Issue by videlalvaro** [MicrosoftDocs/feedback#1735]
Article: https://docs.microsoft.com/en-us/azure/azure-signalr/signalr-quickstart-azure-functions-javascript

Problem: In the article we tell the user to create HTTP triggered functions `negotiate` & `messages`. It's not clear that these names seem to be required endpoints by the SignalR client. 

Right now it seems it's too magic and could lead users to cargo cult these names without know why they are like that.

**Comment by ryanmajidi** [comment]
@videlalvaro Please submit this feedback to the article itself. You can do this by using the feedback section at the bottom
![image](https://user-images.githubusercontent.com/7329992/61403141-882ac100-a889-11e9-99e3-12d71f7c193f.png)
