### ISSUE TITLE
Technet Gallery entry is SPAM

### ISSUE THREAD

**Issue by SasStu** [MicrosoftDocs/feedback#1738]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

**Link to article:**
https://gallery.technet.microsoft.com/Exchange-an-Overview-04684b9a

**Problem:**
The article is spam, some kind of erotic novel.

**Comment by ryanmajidi** [comment]
@SasStu Please submit this abuse [directly through that page](https://gallery.technet.microsoft.com/Account/Login?ReturnUrl=https%3a%2f%2fgallery.technet.microsoft.com%2fExchange-an-Overview-04684b9a%2fview%2fReportAbuse)
