### ISSUE TITLE
Microsoft Learn: sometimes a translated learning path is in progress even if it is completed

### ISSUE THREAD

**Issue by DanteMustCode** [MicrosoftDocs/feedback#1742]
**Describe the bug**
Sometimes a translated learning path is in progress even if it is completed.

**To Reproduce**
Take [Learn the business value of Microsoft Dynamics 365 and the Power Platform](https://docs.microsoft.com/learn/paths/learn-business-value-of-dynamics-365-and-power-platform/) as an example:
* the steps to take for an English speaker:
  * Navigate to the learning path: [Learn the business value of Microsoft Dynamics 365 and the Power Platform](https://docs.microsoft.com/en-us/learn/paths/learn-business-value-of-dynamics-365-and-power-platform/)
  * Complete all the modules of the learning path _except_ the last one: [Dynamics 365 AI - Insights-driven business applications](https://docs.microsoft.com/en-us/learn/modules/dynamics-365-ai-insights-driven-business-applications/)
  * Complete an additional module: [Microsoft runs on trust](https://docs.microsoft.com/en-us/learn/modules/microsoft-runs-on-trust/)
  * Go to Profile
  * Switch the language setting to Simplified Chinese | Substitute `en-us` in the address bar to `zh-cn`
* the original steps:
  * Switch the language setting to Simplified Chinese | Substitute `en-us` in the address bar to `zh-cn`
  * Navigate to the translated learning path: [Learn the business value of Microsoft Dynamics 365 and the Power Platform](https://docs.microsoft.com/zh-cn/learn/paths/learn-business-value-of-dynamics-365-and-power-platform/)
  * Complete _all_ the modules of the learning path
  * Go to Profile
* the common steps:
  * Check that the translated learning path is still listed under in progress
  * Click on the translated learning path to navigate to it
  * Check that the translated learning path is shown as completed
  * Check that the last module is not included in the translated learning path

**Expected behavior**
* the translated learning path is _not_ listed under in progress, or
* the (untranslated, I guess) module is included in the translated learning path

**Screenshots**
N/A

**Desktop**
 - OS: Windows 10
 - Browser: Microsoft Edge
 - Version: latest

**Additional context**
The issue results from the difference in the modules:
* for the English learning path, the last module is [Dynamics 365 AI - Insights-driven business applications](https://docs.microsoft.com/en-us/learn/modules/dynamics-365-ai-insights-driven-business-applications/)
* for the Simplified Chinese learning path, the last module is [Microsoft runs on trust](https://docs.microsoft.com/zh-cn/learn/modules/microsoft-runs-on-trust/)

**Comment by ryanmajidi** [comment]
@DanteMustCode Thank you for submitting this issue. This has been submitted to our internal ticketing system.
