### ISSUE TITLE
Bootrec documenation problems

### ISSUE THREAD

**Issue by voldemarz** [MicrosoftDocs/feedback#1746]
**Is your feature request related to a problem? Please describe.**
This page https://support.microsoft.com/en-us/help/927392/use-bootrec-exe-in-the-windows-re-to-troubleshoot-startup-issues is first hit in online search for "bootrec" and it refers to older version of WIndows according to "Applies To" in header.

Also I find explanation for "/fixboot" option very confusing. It says "This option writes a new boot sector to the system partition by using a boot sector that's compatible with Windows.." but that doesn't seem to make sense for UEFI based systems since there is no boot sectors in that case. So, it's not clear what this actually does in UEFI case. In many places online this is suggested as manual step to attempt to fix booting problems, but I am not seeing any explanation what it actually does.

**Describe the solution you'd like**
- Update documentation according to Windows 10
- Explain what /fixboot does in UEFI system case.

**Comment by ryanmajidi** [comment]
@GrantMeStrength Can you please take a look at this issue?

**Comment by GrantMeStrength** [comment]
Thanks for taking the time to let us know about this and I sincerely apologize for the delayed response. Though the scope of our feedback channel here on GitHub covers specific documentation fixes, I can help redirect you to the right support channel to get an answer to your question. The community of experts and Microsoft Engineers over at [Microsoft Q&A](https://docs.microsoft.com/answers/topics/windows-uwp.html) offer timely answers to a multitude of technical questions surrounding windows-uwp.

If you do create a thread over at Microsoft Q&A, it would be fantastic if you could share that link here so I can track the progress and potentially incorporate the technical details into our documentation. Though I'm marking this Issue as closed now, please treat this thread as an open thread for follow-ups. Thanks! -john

**Comment by voldemarz** [comment]
> windows-uwp

But this issue has nothing to do with UWP ?!
