### ISSUE TITLE
Modify href on GitHub issue titles to point to GitHub issue

### ISSUE THREAD

**Issue by collinstevens** [MicrosoftDocs/feedback#1747]
**Is your feature request related to a problem? Please describe.**
I prefer to open GitHub issues on a docs page in new tabs on GitHub. When opening GitHub issues from a doc page, I have to use the issue number anchor instead of using the issue title anchor because the href on the issue title is "#". The issue title is usually much larger and naturally pulls my attention to click it instead.

**Describe the solution you'd like**
I would like the href on the issue title to be changed from "#" to the GitHub issue.

**Describe alternatives you've considered**
N/A

**Additional context**
https://twitter.com/collinmstevens/status/1151612703707844608
Changing the href still allows the drop down functionality and also allows me to use CTRL + Left Click or Middle Mouse to open the issues in new tabs.

**Comment by ryanmajidi** [comment]
@collinstevens Thank you for the feedback. We have added this to our internal ticketing system.
