### ISSUE TITLE
Incorrect Link to CURSORINFO from GetCursorInfo

### ISSUE THREAD

**Issue by Z-Doctor** [MicrosoftDocs/feedback#1748]
**Link to article:**
https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getcursorinfo

**Problem:**
The link to CURSORINFO directs to https://docs.microsoft.com/windows/desktop/menurc/o instead of https://docs.microsoft.com/en-us/windows/win32/api/winuser/ns-winuser-cursorinfo

**Comment by ryanmajidi** [comment]
@GrantMeStrength Can you please take a look at this issue?

**Comment by GrantMeStrength** [comment]
Thanks for reporting. Correction submitted.
