### ISSUE TITLE
WM_XBUTTONUP refers to a button having been double-clicked

### ISSUE THREAD

**Issue by chrstphrchvz** [MicrosoftDocs/feedback#1749]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

**Link to article:**
Tell us where exactly a problem occurs.

https://docs.microsoft.com/en-us/windows/win32/inputdev/wm-xbuttonup#parameters

**Problem:**
What's wrong with the article?

The verbiage currently in the article refers to a button having been double-clicked:

>## Parameters
>*wParam*
>…
>The high-order word indicates which button was double-clicked. It can be one of the following values.
>
>Value | Meaning
>-- | --
>XBUTTON1<br>0x0001 | The first X button was double-clicked.
>XBUTTON2<br>0x0002 | The second X button was double-clicked.

However, I think it possibly should instead refer to a button having been released, since this is for the WM_XBUTTONUP message rather than WM_XBUTTONDBLCLK; maybe this verbiage was mistakenly copied from https://docs.microsoft.com/en-us/windows/win32/inputdev/wm-xbuttondblclk. I haven't yet found an earlier version of this article to check whether it used to say something different.

**Comment by ryanmajidi** [comment]
@GrantMeStrength Can you please take a look at this issue?

**Comment by chrstphrchvz** [comment]
The version of this article at https://msdn.microsoft.com/en-us/data/ms646246(v=vs.96) appears to also have the "double-clicked" verbiage.

I did find a preview of a rather old (ca. 2001) Visual Basic reference that has different verbiage: https://www.oreilly.com/library/view/subclassing-and-hooking/0596001185/re67.html

>The high-order word contains the x-button that was released

**Comment by GrantMeStrength** [comment]
Investigating.

**Comment by GrantMeStrength** [comment]
You appear to be correct! I am submitting a fix. Thank you.
