### ISSUE TITLE
Show code examples in all support UWP languages (C++, JavaScript)

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#175]
The old MSDN site is really good at showing equivalent code samples in multiple languages (JavaScript, C++, etc). I'm now having a hard time finding JavaScript references, and need to revert to searching through the old docs.

----------
⚠ Idea migrated from UserVoice

**Created By:** Matt Tycholaz
**Created On:** 2017/02/26 00:14:37 +0000
**Votes at Migration:** 1
**Supporters at Migration:** 1

**Comment by ginami** [comment]
Thank you, Matt Tycholaz, for your feedback. I've passed this request to our developer writer team.

**Comment by Powerhelmsman** [comment]
This issue is transferred to author. Currently no plan to create code example in all languages due to resource limitation. But author will keep monitoring the request and get an idea of demand for specific language.
