### ISSUE TITLE
CRITICAL - not possible to login using MS Authenticator iOS 13

### ISSUE THREAD

**Issue by hugo0991** [MicrosoftDocs/feedback#1750]
Describe the bug
I have MS authentication turned on for my Microsoft Account. When I try logging to my apps, it pops up an alert that says " Something went wrong"

To Reproduce
Open a Microsoft app or an app using ADAL, the authenticator opens automatically, tap it on your account, the error pops up, see image attached. 

Try to Login
Expected behavior
User Logged In

iPhone  (please complete the following information):

OS: iOS 13

![image0](https://user-images.githubusercontent.com/49957111/61474019-511de380-a94d-11e9-8e3c-bbbf6fb3e4ce.png)

**Comment by ryanmajidi** [comment]
@hugo0991 Are you still having this issue? If so please contact support here: https://support.microsoft.com/en-us/contactus/
