### ISSUE TITLE
irtual Disk Service is transitioning to Windows Storage Management API layout is broken

### ISSUE THREAD

**Issue by zhoudada** [MicrosoftDocs/feedback#1751]
This webpage has broken table layout:
https://docs.microsoft.com/en-us/windows/win32/w8cookbook/vds-is-transitioning-to-wmiv2-based-windows-storage-management-api

**Comment by ryanmajidi** [comment]
@GrantMeStrength Can you please take a look at this issue?

**Comment by GrantMeStrength** [comment]
Formatting has been corrected. However, as I looked I saw "**Clients** – Windows 8 **Servers** – Windows Server 2012" which isn't right, so I'll check out. Thank you!
