### ISSUE TITLE
Inconsistent answers in Azure HUB faq

### ISSUE THREAD

**Issue by LilacBrandy** [MicrosoftDocs/feedback#1752]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

**Link to article:**
https://azure.microsoft.com/en-us/pricing/hybrid-benefit/faq/

**Problem:**
There's some inconsistency in the Windows Server products that are eligible for Azure HUB. In the 'Which products are eligible for the Azure Hybrid Benefit?' section it states Windows Server Datacenter with Software Assurance is eligible. 
Further down the page under 'Do I need to use Azure Marketplace gallery images or Azure portal images for virtual machines that match my Windows Server Standard edition and Datacenter edition licenses?' It states that you can use your Windows Server Standard edition. This isn't consistent with the first statement that you can only apply HUB to the Datacenter edition with Software Assurance.

**Comment by ryanmajidi** [comment]
@LilacBrandy Please submit this feedback to the [azure general feedback](https://feedback.azure.com/forums/34192--general-feedback)
