### ISSUE TITLE
Incorrect description of LowLevelMouseProc LPRAM.

### ISSUE THREAD

**Issue by Z-Doctor** [MicrosoftDocs/feedback#1753]
**Link to article:**
https://docs.microsoft.com/en-us/windows/win32/winmsg/lowlevelmouseproc

**Problem:**
What's wrong with the article?
In the article the description for the LPRAM says that it is a pointer to a [KBDLLHOOKSTRUCT](https://docs.microsoft.com/en-us/windows/win32/api/winuser/ns-winuser-kbdllhookstruct) despite this being a mouse hook and not a keyboard hook. Even through my own testing the LPRAM seems to be a pointer for a [MSLLHOOKSTRUCT](https://docs.microsoft.com/en-us/windows/win32/api/winuser/ns-winuser-msllhookstruct) as the first two ints of that structure are the screen coordinates of the Mouse Cursor.

**Comment by ryanmajidi** [comment]
@GrantMeStrength Can you please take a look at this issue?

**Comment by GrantMeStrength** [comment]
I agree that it should be MSLLHOOKSTRUCT and I will make the change - thank you for the feedback!
