### ISSUE TITLE
A suggestion for clearer documentation of LowLevelMouseProc

### ISSUE THREAD

**Issue by Z-Doctor** [MicrosoftDocs/feedback#1755]
**Link to article:**
https://docs.microsoft.com/en-us/windows/win32/winmsg/lowlevelmouseproc

**Problem:**
The description for the WPARAM says:
> The identifier of the mouse message. This parameter can be one of the following messages: WM_LBUTTONDOWN, WM_LBUTTONUP, WM_MOUSEMOVE, WM_MOUSEWHEEL, WM_RBUTTONDOWN or WM_RBUTTONUP.

This seems to suggest that these are the only options. Even though you can find a list of all the notifications if you follow one of the links it is not immediately apparent. I would suggest an edit so that it reads something along the lines of:
> The identifier of the mouse message. This parameter can be one of the following messages: WM_LBUTTONDOWN, WM_LBUTTONUP, WM_MOUSEMOVE, WM_MOUSEWHEEL, WM_RBUTTONDOWN, WM_RBUTTONUP or any other Mouse Input Notification.

Where the Mouse Input Notification is a link to https://docs.microsoft.com/en-us/windows/win32/inputdev/mouse-input-notifications

**Comment by ryanmajidi** [comment]
@GrantMeStrength Can you please take  a look at this issue?

**Comment by GrantMeStrength** [comment]
Thank you very much for your feedback on this topic. Unfortunately this topic is rather old, and it's difficult to find a way to verify the corrections you suggest - in fact, I can't even find this in the latest Windows 10 SDK. So while I appreciate that you took the time to write up this feedback, I'm afraid that until I can track down some verification that the extra options are not only allowed but supported, I can't take the suggested fix. Sorry! -john
