### ISSUE TITLE
wrong path for pipes

### ISSUE THREAD

**Issue by krishty** [MicrosoftDocs/feedback#1757]
https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-createnamedpipea (CreateNamedPipeA function)

Parameters -> lpName says: "The unique pipe name. This string must have the following form: \\.\\pipe<i>pipename"

Wrong. The string must have the form \\\\.\\pipe\\pipename, that is two backslashes - dot - backslash - pipe - backslash - pipename.

**Comment by ryanmajidi** [comment]
@GrantMeStrength Can you please take a look at this issue?

**Comment by krishty** [comment]
Same issue with TransactNamedPipe function (https://docs.microsoft.com/en-us/windows/win32/api/namedpipeapi/nf-namedpipeapi-transactnamedpipe), twice in the Remarks section. The Windows 10, version 1709 hint at the end gets it *almost* right, a backslash is missing.

Refer to ConnectNamedPipe function (https://docs.microsoft.com/en-us/windows/win32/api/namedpipeapi/nf-namedpipeapi-connectnamedpipe), Windows 10 hint at the end of the Remarks section for the correct syntax. Throughout that article, however, the links to CreateFile and OVERLAPPED are 404.

**Comment by GrantMeStrength** [comment]
Thank you - the formatting was messed up, and hopefully it is now correct. Thanks for reporting and saving someone a lot of confusion!

**Comment by krishty** [comment]
Great! CreateNamedPipeA is indeed fixed, and so are the links in ConnectNamedPipe.
The three paths in the Remarks section of https://docs.microsoft.com/en-us/windows/win32/api/namedpipeapi/nf-namedpipeapi-transactnamedpipe are still wrong; should I create a new issue for them?
