### ISSUE TITLE
ID3D12CommandList4::BeginRenderpass page missing links 

### ISSUE THREAD

**Issue by DethRaid** [MicrosoftDocs/feedback#1758]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

**Link to article:**
https://docs.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12graphicscommandlist4-beginrenderpass

**Problem:**
The MSDN page for `ID3D12CommandList4::BeginRenderPass` doesn't have links to the structs and enums used by that method

Compare to a page like https://docs.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12graphicscommandlist-iasetindexbuffer where the method parameter descriptions have links to the structs you need to fill out

**Comment by ryanmajidi** [comment]
@GrantMeStrength Can you please take a look at this issue?

**Comment by GrantMeStrength** [comment]
This seems to have been fixed. Thank you for the feedback!
