### ISSUE TITLE
The description of the limit of a message queue may be misleading

### ISSUE THREAD

**Issue by Taylor-Hasterd** [MicrosoftDocs/feedback#1759]
**Link to article:**
Tell us where exactly a problem occurs.
https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-postmessagea
https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-postmessagea
and kindred pages of message posting functions.

**Problem:**
What's wrong with the article?
In these articles, there is a description of the limit of a message queue.

> There is a limit of 10,000 posted messages per message queue. This limit should be sufficiently large. If your application exceeds the limit, it should be redesigned to avoid consuming so many system resources. To adjust this limit, modify the following registry key.

However, I think the first sentence of the description can be misleading. What is "10,000 posted messages"? Does it mean we can only post 10,000 messages to a queue in total, or does it mean that a message queue can contain 10,000 messages? I think it's the latter, and have confirmed it. 
In my opinion, it is better to describe it like "A message queue can contain at most 10,000 messages".

**Comment by ryanmajidi** [comment]
@GrantMeStrength Can you please take a look at this issue?
