### ISSUE TITLE
Enable a user to have her/his own area to collect articles, save reading sessions etc

### ISSUE THREAD

**Issue by docs-product** [MicrosoftDocs/feedback#176]
When I go to docs.microsoft.com I'm usually looking at similar and related things every time. Like for instance I might be looking for reference information on XAML and C++ examples or other very specific areas of interest, and that is what I do every time. 

It would be nice to have your own area that saves recently read articles, save reading sessions and that present related articles that might be of interest to me specifically.

----------
⚠ Idea migrated from UserVoice

**Created By:** Karl Hansson
**Created On:** 2017/02/12 17:30:57 +0000
**Votes at Migration:** 2
**Supporters at Migration:** 2

**Comment by dend** [comment]
@sharriexie probably something in your domain.

**Comment by sharriexie** [comment]
@botcrane ,
Thanks for your feedback. Your suggestion make sense.
I'm PM of DOCS profile, and have logged this request as customer suggestion (ID: 35179) in our system.

Hui Xie

**Comment by weitzhandler** [comment]
Very essential. Please implement this compelling feature, thank you!

**Comment by shrk96** [comment]
Saving documents in the form of a bookmark/starred document, etc. It's truly essential for a good experience. This would be a welcome feature.
Love the recent focus on documentation!

**Comment by weitzhandler** [comment]
I'd even want to be able to group my starred articles under labels/groups.
Anyway, this feature is very essential, please implement this.
Thank you!

**Comment by docs-product** [comment]
We have shipped collections and bookmarks on docs.microsoft.com, where you can store content references you like to refer to in the future!
