### ISSUE TITLE
DateTime.ToString("mm/dd/yyyy") return wrong string value

### ISSUE THREAD

**Issue by toyidong** [MicrosoftDocs/feedback#1761]
**Describe the bug**
DateTime.ToString("mm/dd/yyyy") return wrong string value, not all the time, but observed for several date time, one example listed in the code.

**To Reproduce**
This is the code I tested in .NET 4.6.1, 4.7.2 and .NET core 2.2
I use System.Globalization to construct a DateTime object only, this issue is not related to System.Globalization

using System;
using System.Globalization;
					
public class Program
{
	public static void Main()
	{
		long ticks = new DateTime(2019, 07, 16, 13, 26, 50, new CultureInfo("en-US", false).Calendar).Ticks;
    	DateTime dt = new DateTime(ticks);
		
		Console.WriteLine("July converts to 26");
		Console.WriteLine("{0}", dt);
		Console.WriteLine("{0}", dt.ToString("yyyy/mm/dd"));
		Console.WriteLine("{0}", dt.ToString("mm/dd/yyyy"));
		Console.WriteLine("{0}", dt.ToString("dd/mm/yyyy"));
		
		long ticks1 = new DateTime(2019, 07, 16, 15, 07, 46, new CultureInfo("en-US", false).Calendar).Ticks;
    	DateTime dt1 = new DateTime(ticks1);
		
		Console.WriteLine("July converts to 07");
		Console.WriteLine("{0}", dt1);
		Console.WriteLine("{0}", dt1.ToString("yyyy/mm/dd"));
		Console.WriteLine("{0}", dt1.ToString("mm/dd/yyyy"));
		Console.WriteLine("{0}", dt1.ToString("dd/mm/yyyy"));
	}
}

**Expected behavior**
In above code, July can return as either 26 or 07.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 7 Professional
 - Browser [e.g. chrome, safari] chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by pkulikov** [comment]
@toyidong The [`mm` format specifier](https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings#mmSpecifier) (in general, lowercase "m") represents **minutes**. Use the [`MM` format specifier](https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings#MM_Specifier) (in general, capital "M") to represent **months**.

**Comment by ryanmajidi** [comment]
@mairaw Can you please take a look at this issue?

**Comment by mairaw** [comment]
This has already been answered by @pkulikov (thanks Petr!). Closing.
