### ISSUE TITLE
Linked GitHub Issue(s) Not Showing Up

### ISSUE THREAD

**Issue by spottedmahn** [MicrosoftDocs/feedback#1762]
**Describe the bug**
I just filed an issue on: https://docs.microsoft.com/en-us/dotnet/core/tutorials/cli-templates-create-item-template and it is not showing up after refreshing the page.

![image](https://user-images.githubusercontent.com/14079228/61649821-31095f80-ac80-11e9-8cad-e7cab1ddca97.png)

Also:
![image](https://user-images.githubusercontent.com/14079228/61649535-ae80a000-ac7f-11e9-9820-6b1ca4701da4.png)

Here's the Issue I created: https://github.com/dotnet/docs/issues/13509

**To Reproduce**
1. Go to https://docs.microsoft.com/en-us/dotnet/core/tutorials/cli-templates-create-item-template
2. Create a feedback item on the doc page

**Expected behavior**
Linked to issue(s) like on all other pages

Example: 
![image](https://user-images.githubusercontent.com/14079228/61649713-03241b00-ac80-11e9-9e7f-4515526dfce4.png)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser Chrome
 - Version 75

**Comment by Thraka** [comment]
Github was having a major outtage https://www.githubstatus.com/

**Comment by spottedmahn** [comment]
ah, that makes more sense.

I see it now, thanks!

![image](https://user-images.githubusercontent.com/14079228/61652386-d246e480-ac85-11e9-9d65-8e4f90246237.png)
