### ISSUE TITLE
GetRawInputDeviceInfoA Return Signature 

### ISSUE THREAD

**Issue by AndrewNRe** [MicrosoftDocs/feedback#1763]
The return signature of GetRawInputDeviceInfoA is an unsigned integer.
This function however, can return a signed integer!
Link-
https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getrawinputdeviceinfoa
I would appreciate the change to have this function return a signed integer! Just saves everyone a little bit of time.

**Comment by drewbatgit** [comment]
Hello, thanks for your feedback. It looks like the API is defined in the header as returning an unsigned integer. 

WINUSERAPI
UINT
WINAPI
GetRawInputDeviceInfoA(
    _In_opt_ HANDLE hDevice,
    _In_ UINT uiCommand,
    _Inout_updates_bytes_to_opt_(*pcbSize, *pcbSize) LPVOID pData,
    _Inout_ PUINT pcbSize);


Are you saying that the documentation is wrong and that the function does in fact return a signed integer, or are you requesting that the API be modified to return an unsigned integer?

**Comment by AndrewNRe** [comment]
The documentation (https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getrawinputdeviceinfoa) states that the function can return a signed integer (specifically -1) if pData is not large enough for the data. And it does indeed return the bits in hexadecimal: FFFFFFFF if the buffer supplied to pData is not large enough. But due to the return signature being of UINT, if I were to write code like
if( GetRawInputDeviceInfoA() > 0 ) { do success case } else { failure }
this would not work due to the UINT return signature. Whereas if the function returned a signed integer, it would work without having to do something like if( (signed int)GetRawInputDeviceInfoA() )
So the documentation is correct. And the function does return correct values by the bits. But the way they're interpreted is wrong for the signed case.

**Comment by drewbatgit** [comment]
Ah, I see what you mean. Your request makes sense, but this channel is specifically for documentation feedback, not product feedback. If you are looking for functionality that isn’t currently provided by the product, please use the [Windows developer feedback site](https://wpdev.uservoice.com/). We’d be happy to have this on record, where others can view it and upvote it.

**Comment by AndrewNRe** [comment]
Thank you very much!
