### ISSUE TITLE
Japanese translastion request 

### ISSUE THREAD

**Issue by TakiyaNakano-MSFT** [MicrosoftDocs/feedback#1764]
It would be great if you publish Japanese translation of Get Help + Support article for Power Platfrom Admin Center.
https://docs.microsoft.com/en-us/power-platform/admin/get-help-support

So many Japanese custmoer still submit their service request from Microsoft 365 portal rather than Power Platform Admin center.

**Comment by ryanmajidi** [comment]
@SonjaSaltzman Can you please take a look at this issue?

**Comment by srvbpigh** [comment]
Hello, @TakiyaNakano-MSFT
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello @TakiyaNakano-MSFT 

Thank you for your contribution. 

Contributions on translation problems against machine translated content are currently not accepted. 

We value your feedback and suggestions on human translated content, which is used to train the machine translation engines, so over time, your contributions will improve the quality of both human and machine translations. 

Human translated topics can be distinguished from machine translated topics by the ms.translationtype metadata value “HT” (versus “MT” for machine translated) in the header of each content file. 

Many thanks for your support. 

Microsoft DOCS Global Experience Team

**Comment by SonjaSaltzman** [comment]
@vinceno this one must have somehow fallen through the cracks, I'm really sorry about this. Assigning to you. Not sure if the feedback is still valid, but please take a look.

**Comment by vinceno** [comment]
@SonjaSaltzman thx..,
@gitfrosty this feedback is related to a powerplatform topic

**Comment by gitfrosty** [comment]
Hello @TakiyaNakano-MSFT 

We apologize, but it looks like your feedback was incorrectly handled. I believe that the Japanese translation is now available at https://docs.microsoft.com/ja-jp/power-platform/admin/get-help-support

I apologize that it has taken so long to resolve this issue.

Thanks
John

**Comment by TakiyaNakano-MSFT** [comment]
Hi John,

No problem. I'm fully satisfied with existing Japanese translation article quality. Thanks for letting me know the latest status.

Thanks,
Takiya Nakano

**Comment by SonjaSaltzman** [comment]
I'm closing this; if there are any issues, please don't hesitate to reopen.
thanks,
Sonja
