### ISSUE TITLE
Frensh tlanslation issue in the https://docs.microsoft.com/fr-fr/aspnet/web-api/overview/data/using-web-api-with-entity-framework/part-3 page

### ISSUE THREAD

**Issue by HasdrubalTn** [MicrosoftDocs/feedback#1766]
**Link to article:**
https://docs.microsoft.com/fr-fr/aspnet/web-api/overview/data/using-web-api-with-entity-framework/part-3
![Issue](https://user-images.githubusercontent.com/43700761/61783462-237ee180-ae08-11e9-8880-20be136c24a8.JPG)

**Problem:**
Frensh tlanslation issue, please replace "OBTENIR l’api/authors" by "GET api/authors" in the section "Explorer l’API (facultatif)" just after this sentence : "L’API permet les opérations CRUD sur la base de données. Voici un résumé de l’API."

Thanks

**Comment by HasdrubalTn** [comment]
The issue appear in multiple places (see attachment).
![Issue_2](https://user-images.githubusercontent.com/43700761/61783786-bddf2500-ae08-11e9-9fdb-a91a1dc436ab.JPG)

**Comment by ryanmajidi** [comment]
@SonjaSaltzman Can you please take a look at this issue?

**Comment by SonjaSaltzman** [comment]
cc @JasonCard for awareness; assigned to @DavidPrio

**Comment by CeciAc** [comment]
Hello, @HasdrubalTn
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @HasdrubalTn 
 
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/fr-fr/aspnet/web-api/overview/data/using-web-api-with-entity-framework/part-3 (and in the other locales, too)

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.
	
Kind regards,
Microsoft DOCS International Team

**Comment by HasdrubalTn** [comment]
With pleasure,

Ali MSELMI
