### ISSUE TITLE
sqlsrv support for PHP 7.3 unclear

### ISSUE THREAD

**Issue by camer-on** [MicrosoftDocs/feedback#1767]
I am seeing a discrepancy in documentation.
- https://docs.microsoft.com/en-us/sql/connect/php/system-requirements-for-the-php-sql-driver?view=sql-server-2017 says that SQLSRV v5.6 supports PHP v7.3 and higher. 
- https://www.microsoft.com/en-us/download/details.aspx?id=57916 says that SQLSRV v5.6 supports PHP 7.0, 7.1 and 7.2.

I would be more comfortable downloading SQLSRV v5.6 if the two pages could agree on what versions of PHP it supports. Can someone get this corrected?

**Comment by ryanmajidi** [comment]
@camer-on moved to that repo: https://github.com/MicrosoftDocs/sql-docs/issues/2646
