### ISSUE TITLE
Search Breadcrumbs

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#177]
Expose the existing breadcrumbs to search engines:
https://developers.google.com/search/docs/data-types/breadcrumbs
https://www.bing.com/webmaster/help/markup-breadcrumbs-72419f3f

This clarifies exactly what each page relates to directly from search results, without relying on the URL (which is often truncated) or the page's title.

----------
⚠ Idea migrated from UserVoice

**Created By:** Eli Arbel
**Created On:** 2017/02/10 05:11:36 +0000
**Votes at Migration:** 4
**Supporters at Migration:** 4

**Comment by Khairunj** [comment]
Thanks for the feedback i have added the feedback in the backlog.

**Comment by Khairunj** [comment]
@Eli Arbel Thanks you for the feedback we have added the feature request in the backlog.

**Comment by Khairunj** [comment]
Added the feedback in the backlog.

**Comment by Khairunj** [comment]
I have added the feature in the backlog and currently its not in the priority list.
