### ISSUE TITLE
Every link I click on Google/Bing or in the Doc site forwards/redirects me to Microsoft Home page

### ISSUE THREAD

**Issue by SMHolck** [MicrosoftDocs/feedback#1770]
**Describe the bug**
Clicking Microsoft documentation links somehow lands me on the Microsoft Home page every time.  At first it was just annoying, but now, sometimes, I can't even click back to get to the intended link and I have to search again.  It's a lot of wasted time in my day.

**To Reproduce**
1. Open Chrome or IE 11 (yep, happens on both)
2. Search Google or Bing for a microsoft topic, e.g. "Azure Data Lake" or "Power BI"
3. Click a Microsoft documentation link (I most often right-click and open in new tab, but happens just clicking link too)
4. Half the time you get forwarded/redirected to the MIcrosoft Home page.  It doesn't happen every time, but it happens more than 50% of the time to me.  This has been going on for a month or so, but I used to be able to click the back button ... now it loses the link all together.  Really annoying when you are doing research and opening lots of articles to read trying to find the best ones.

**Expected behavior**
Clicking a link would take me to the documentation page I want

**Screenshots**
The page I don't want
![image](https://user-images.githubusercontent.com/11869380/61924525-6e424b80-af25-11e9-9ef4-ea8dfbc0930f.png)

**Desktop (please complete the following information):**
- OS WIndows 10 Enterprise v1809
 - Browser Chrome 75.0.3770.100 (Official Build) (64-bit) and IE 11.437

**Additional context**
This happens on my desktop and my laptop.  I also asked co-workers and they had noticed it too.

**Comment by docs-product** [comment]
Thank you for the feedback @SMHolck - can you please paste a link (before you navigate to it) that you get from Google or Bing, that we can take a look at?
