### ISSUE TITLE
关于 SQL Server  SSRS  函数表达式文章 内容错误

### ISSUE THREAD

**Issue by chaoxiaole** [MicrosoftDocs/feedback#1771]
在 地址为  https://docs.microsoft.com/zh-cn/sql/reporting-services/report-design/expression-examples-report-builder-and-ssrs?view=sql-server-2014

文章中 关于  lookup函数表达式感觉有错误。
原文如下：
=Lookup(Fields!PID.Value, Fields!ProductID.Value, Fields.ProductName.Value, "Product")
个人感觉是否应该是：
=Lookup(Fields!PID.Value, Fields!ProductID.Value, Fields!ProductName.Value, "Product")

一个关于！的小问题。
如果指出的问题不对，请谅解，刚刚开始学习。

**Comment by ryanmajidi** [comment]
@chaoxiaole moved this issue to that repo: https://github.com/MicrosoftDocs/sql-docs/issues/2619
