### ISSUE TITLE
Content Issue: Docs/Windows/HLSL/Reference for HLSL/Asm Shader Reference/Shader Model 4 Assembly (DirectX HLSL)/ftoi (sm4 - asm) 

### ISSUE THREAD

**Issue by fruityman** [MicrosoftDocs/feedback#1772]
**Link to article:**
https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/ftoi--sm4---asm-

**Problem:**
Wrong Description: dest = src0 - round_ni(src0)
Fixed: dest = round_ni(src0)

**Comment by ryanmajidi** [comment]
@GrantMeStrength Can you please take a look at this issue?

**Comment by stevewhims** [comment]
Hi, @fruityman, and thanks for filing this issue. I've reached out for confirmation and when I get that I'll make the fix. I'll close the issue here for now, I'll track the work internally, and I'll come back here and leave an update when I have one.

Thanks again!
Steve

**Comment by stevewhims** [comment]
**UPDATE**: still pinging for confirmation, internally.

**Comment by stevewhims** [comment]
**UPDATE**: Hi, @fruityman, I have a fix in the publishing pipeline. I'll track that until it makes its way to the live site.

FYI, the conversion uses round_z rather than round_ni.

Thanks again!
-Steve
