### ISSUE TITLE
Sensitive information in comment on Gallery Q and A

### ISSUE THREAD

**Issue by jpetrosek** [MicrosoftDocs/feedback#1775]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

**Link to article:** https://gallery.technet.microsoft.com/Driver-Tool-Automate-9ddcc010/view/Discussions#52814

Tell us where exactly a problem occurs.

**Problem:** I mistakenly left sensitive information in my comment when I posted the log (admin username) and would like to have it removed from the comment, or the comment removed entirely.

What's wrong with the article?

**Comment by ryanmajidi** [comment]
@dend Can you please take a look at this issue?

**Comment by docs-product** [comment]
The comment was removed.
