### ISSUE TITLE
Xaml Controls Gallery not included in Samples Browser

### ISSUE THREAD

**Issue by stmoy** [MicrosoftDocs/feedback#1778]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

**Link to article:**
Tell us where exactly a problem occurs.
https://docs.microsoft.com/en-us/samples/browse/

**Problem:**
What's wrong with the article?
The https://docs.microsoft.com/en-us/samples/browse/ sample browser does not include a link to the Xaml Controls Gallery which demonstrates the latest WinUI features.

https://github.com/Microsoft/Xaml-Controls-Gallery

**Comment by docs-product** [comment]
Thank you for the feedback @stmoy - closing this issue as we are following-up internally.
