### ISSUE TITLE
Icons are misaligned due to incorrect background-position properties

### ISSUE THREAD

**Issue by drewnoakes** [MicrosoftDocs/feedback#1779]
Icons appear incorrectly on https://docs.microsoft.com/en-gb/azure/devops/pipelines/?view=azure-devops

![image](https://user-images.githubusercontent.com/350947/62101050-642e9d00-b2d7-11e9-8b21-cba20a38d112.png)

They appear to have a `background-position` set, which offsets the icons by some percentage. However `background-repeat` is not set to `no-repeat`, so the images wrap around as seen.

**Desktop:**
 - OS: Windows 10
 - Browsers:
   - Edge (dev) 77.0.223.0
   - Chome 75.0.3770.142
   - Firefox 68.0.1

**Comment by dendeli-msft** [comment]
This should now be addressed (new page design is live). Thank you for your feedback!
