### ISSUE TITLE
Add cmd.exe / batch file docs

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#178]
Please add all the old docs for cmd.exe / batch file commands from:
https://technet.microsoft.com/en-us/library/bb490890.aspx
It's only a few pages of very "old & boring" things, but very important and helpful since it's so arcane.

----------
⚠ Idea migrated from UserVoice

**Created By:** Anonymous
**Created On:** 2017/02/09 22:58:07 +0000
**Votes at Migration:** 3
**Supporters at Migration:** 3

**Comment by dend** [comment]
These pages were moved to the docs.microsoft.com archive.
