### ISSUE TITLE
TreeView structure links are dead

### ISSUE THREAD

**Issue by Burtan** [MicrosoftDocs/feedback#1785]
**Link to article:**
https://docs.microsoft.com/en-us/windows/win32/controls/bumper-tree-view-control-reference-structures

**Problem:**
The TreeView structure links are dead.

**Comment by atlerestad** [comment]
It's the same problem with many controls:
https://docs.microsoft.com/en-us/windows/win32/controls/bumper-combobox-control-reference-structures
https://docs.microsoft.com/en-us/windows/win32/controls/bumper-button-control-reference-structures
https://docs.microsoft.com/en-us/windows/win32/controls/bumper-edit-control-reference-structures
https://docs.microsoft.com/en-us/windows/win32/controls/bumper-list-box-control-reference-structures
https://docs.microsoft.com/en-us/windows/win32/controls/bumper-toolbar-control-reference-structures

Seems to be a general problem for tag* structures

**Comment by ryanmajidi** [comment]
@GrantMeStrength Can you please take a look at this issue?

**Comment by GrantMeStrength** [comment]
As far as I can tell, these links have all been repaired. Thanks for report it!
