### ISSUE TITLE
Help me fix SQLSERVER error

### ISSUE THREAD

**Issue by KryCool** [MicrosoftDocs/feedback#1787]
![image](https://user-images.githubusercontent.com/43307723/62210591-b7cbe400-b3c6-11e9-8ec0-f53a916cfdf7.png)

**Problem:**
Image above this is issue. I had found everything on internet by content in error by all not working. I had used repair and reinstall but not effected too
So, I hope somebody can tell me something useful
Thanks for watching,

**Comment by ryanmajidi** [comment]
@KryCool Please contact support: https://support.microsoft.com/en-us
