### ISSUE TITLE
Razor Page Test Sample Missing

### ISSUE THREAD

**Issue by kylejrp** [MicrosoftDocs/feedback#1788]
Hey there,

The [samples announcement article](https://docs.microsoft.com/en-us/teamblog/code-samples) mentioned to create an issue for any missing samples. It looks like the Razor Pages samples are missing, or at least I can't search for them.

**Link to article:**
Here's an example article that references the samples `src/RazorPagesTestSample` and `tests/RazorPagesTestSample.Tests`:
https://docs.microsoft.com/en-us/aspnet/core/test/razor-pages-tests?view=aspnetcore-2.2

**Problem:**
I don't seem to be able to find these samples:
https://docs.microsoft.com/en-us/samples/browse/?term=razor%20pages

I would expect that there would be more samples for Razor Pages, so it's strange that there's no results.

**Comment by ryanmajidi** [comment]
@kylejrp moved to that repo: https://github.com/aspnet/AspNetCore.Docs/issues/13631
