### ISSUE TITLE
An image would make this clearer

### ISSUE THREAD

**Issue by Ma-XX-oN** [MicrosoftDocs/feedback#1789]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.
No comment section.

**Link to article:**
https://docs.microsoft.com/en-us/windows/win32/controls/em-findwordbreak

**Problem:**
Hard to visualize what the different constants mean

Would be helpful if a graphic was added.  Maybe something like:

```
                   +-- starting position
                   v
             blah blah blah
                ^ ^  ^ ^
WB_LEFTBREAK ---+ |  | +--- WB_RIGHT
WB_LEFT ----------+  +----- WB_RIGHTBREAK
```
Could also be added to https://docs.microsoft.com/en-us/windows/win32/api/winuser/nc-winuser-editwordbreakproca and https://docs.microsoft.com/en-us/windows/win32/api/winuser/nc-winuser-editwordbreakprocw with `starting position` being replaced with `ichCurrent`.

**Comment by ryanmajidi** [comment]
@GrantMeStrength Can you please take a look at this issue?

**Comment by Ma-XX-oN** [comment]
I wrote a test app [here](https://github.com/Ma-XX-oN/RichEditDblClkTest.git) and that gave me the following results for the default handler:

![image](https://user-images.githubusercontent.com/10625935/63288074-d583bf00-c289-11e9-95cc-536bc3886297.png)

![image](https://user-images.githubusercontent.com/10625935/63288081-dae10980-c289-11e9-805e-6fff3f173f4e.png)

Excerpt from the [Parameters](https://docs.microsoft.com/en-us/windows/win32/controls/em-findwordbreak#parameters) section of that same page:
> Value | Meaning
> -- | --
> **WB_LEFT** | Finds the nearest character before the specified position that begins a word.
> **WB_LEFTBREAK** | Finds the next word end before the specified position. This value is the same as WB_PREVBREAK.
> **WB_RIGHT** | Finds the next character that begins a word after the specified position.
> **WB_RIGHTBREAK** | Finds the next end-of-word delimiter after the specified position. This value is the same as WB_NEXTBREAK.

Looking at the 2nd diagram, you can see that if starting at a whitespace, WB_LEFT doesn't go to the position that begins a word.  It goes to the first whitespace character after the word. 
 WB_RIGHTBREAK also doesn't goto the "next end-of-word delimiter after the specified position" if starting at a whitespace.

The documentation should be updated with some diagrams and reasoning to help users to understand the behaviour.

**Comment by Ma-XX-oN** [comment]
FYI.  Here is a little comment card that I made up describing the default behaviour, in case you're interested:

```c++
/****************************\
* Default word break handler *************************************************\
*                                 v    *                     |<----->|        *
*                    blah     blah|    *                    blah     blah     *
* *WB_LEFT                       ^|    * WB_RIGHT                    ^        *
*  Note that this anomalous behaviour  ****************************************
*  occurs only when starting from one  *                   |v                 *
*  past end of buffer.                 *                   |blah     blah     *
*                                      * *WB_RIGHTBREAK    |   ^              *
*                           -->| |<--  *  Note that this anomalous behaviour  *
*                    blah     blah     *  occurs only when starting at        *
* WB_LEFT                     ^        *  beginning of buffer.                *
*                                      *                                      *
*                        |<-->|        *                  -->| |<--           *
*                    blah     blah     *                    blah     blah     *
* WB_LEFT                ^             * WB_RIGHTBREAK          ^             *
****************************************                                      *
*                        |<----->|     *                        |<-->|        *
*                    blah     blah     *                    blah     blah     *
* WB_LEFTBREAK           ^             * WB_RIGHTBREAK               ^        *
*******************************************************************************
*                     |<----->|        *                    |<----->|         *
*                    blah     blah     *                    blah     blah     *
* WB_MOVEWORDLEFT    ^                 * WB_MOVEWORDRIGHT            ^        *
\*****************************************************************************/
```

**Comment by GrantMeStrength** [comment]
I agree and thank you for taking the time to file this feedback with helpful diagrams.
This content is a little older and with limited resources it might not meet our criteria for spending time to update, however I will create an internal bug and assign an owner and if it meets their threshold it might appear in a forthcoming update. Again, thanks for spending your time on this. - john
