### ISSUE TITLE
expose an end point so third party (IDE etc) can hook into docs

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#179]
Based on keywords, expose articles in either xml or json so third party apps can integrate documentation.

----------
⚠ Idea migrated from UserVoice

**Created By:** Anonymous
**Created On:** 2017/02/09 16:24:41 +0000
**Votes at Migration:** 19
**Supporters at Migration:** 19

**Comment by dend** [comment]
Closing as `wont-fix` - articles are already in a variety of at-rest formats, available in GitHub repos.
