### ISSUE TITLE
Dead link in the article "HDM_LAYOUT message"

### ISSUE THREAD

**Issue by SweetIceLolly** [MicrosoftDocs/feedback#1791]
**Link to article:**
https://docs.microsoft.com/en-us/windows/win32/controls/hdm-layout

**Problem:**
In the "Parameters" section: the link to "HDLAYOUT" is dead.

**Comment by ryanmajidi** [comment]
@GrantMeStrength Can you please take a look at this issue?

**Comment by GrantMeStrength** [comment]
This is now fixed, thank you for taking the time to report it.
