### ISSUE TITLE
Missing WebException from list of what HttpClient.SendMessage can throw.

### ISSUE THREAD

**Issue by SittenSpynne** [MicrosoftDocs/feedback#1793]
**Link to article:**
https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.sendasync?view=netcore-2.2#System_Net_Http_HttpClient_SendAsync_System_Net_Http_HttpRequestMessage_System_Threading_CancellationToken_

**Problem:**
I read the documentation and assumed any reasonable problem this method would encounter would throw HttpRequestException. So I wrote code to handle that gracefully and proceeded to test.

In a Xamarin Forms project on iOS, if the network is unavailable, this method will throw a WebException. 

All exceptions this method can throw should be listed. If this is a Xamarin bug, they should follow the documentation when implementing their stuff.

**Comment by ryanmajidi** [comment]
@SittenSpynne moved to that repo https://github.com/dotnet/dotnet-api-docs/issues/2920
