### ISSUE TITLE
Menu broken in Microsoft Edge 16 due to use of URLSearchParams

### ISSUE THREAD

**Issue by ManuelRin** [MicrosoftDocs/feedback#1794]
The top menu and left navigation tree of all docs.microsoft.com pages do not load in EdgeHTML version 16 (Microsoft Edge version 41). The areas where the menus used to be remain blank.

**To Reproduce**
1. Either
a. Use a Windows 10 Fall Creators Update running Microsoft Edge 41 / EdgeHTML 16
b. Use a service which provides such a browser (like lambdatest.com)
2. Open Edge and navigate to https://docs.microsoft.com/en-us/aspnet/core/?view=aspnetcore-2.2
3. Problem: see that the top and left menus do not load. Scroll down and see that the Feedback panel also doesn't load
4. Press F12 / open the Dev Tools and go to Console (eventually reload the page)
5. See the script error: SCRIPT5009: 'URLSearchParams' is not defined
6. Check https://caniuse.com/#search=URLSearchParams to see that it's not supported in EdgeHTML 16 yet, but obviously needed/expected by the website.

**Expected behavior**
Microsoft Edge 41 / EdgeHTML 16 from Windows 10 Fall Creators Update is still used by many enterprises which are often not able to upgrade to the latest Windows release quick enough. docs.microsoft.com should use or polyfill features which are not natively supported on older browser versions which are still in support.

**Screenshot**
![image](https://user-images.githubusercontent.com/1999976/62333437-b8967000-b4c3-11e9-8758-eef3a7dc55e5.png)

**Desktop:**
 - OS: Windows 10
 - Browser Microsoft Edge
 - Version 41 / EdgeHTML version 16

**Additional context**
Website seems to render fine in latest Chrome and latest Edge.

**Comment by ryanmajidi** [comment]
@ManuelRin Thank you for the feedback, we have submitted this into our internal ticketing system.
