### ISSUE TITLE
On the https://docs.microsoft.com/en-us/powerapps/ I only see the title no content

### ISSUE THREAD

**Issue by kentjg** [MicrosoftDocs/feedback#1795]
**Describe the bug**

**To Reproduce**
1. Go to 'https://docs.microsoft.com/en-us/powerapps/'
2. It only displays the title "PowerApps Documentation" no other content
**Expected behavior**
See the PowerApps documentation.

**Screenshots**
![image](https://user-images.githubusercontent.com/41167777/62378758-8c0a4480-b513-11e9-8098-92aa6608a986.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge

**Comment by ryanmajidi** [comment]
@kentjg Moved to that repo: https://github.com/MicrosoftDocs/powerapps-docs/issues/556
