### ISSUE TITLE
Basic MVA courses still missing from MS learn

### ISSUE THREAD

**Issue by Regenhardt** [MicrosoftDocs/feedback#1796]
So there's still virtually no MVA content in MS learn besides Azure. I understand MSFT pushing Azure to the max, but this isn't really how you get new developers to use your platform. Before, everyone who asked could have been sent to MVA "Go look for C# fundamentals" and everyone was happy. Now as a developer I'm honestly wondering if I need MS learn at all in its current form.

We seriously need developer ressources. Software development for absolute beginners, C# fundamentals, asp.net (core), visual studio, WPF. All these things are completely missing from MS learn, and MVA is shut down now so you have to find the videos on youtube and hope to find a goo tutorial to accompany it.

**Comment by ryanmajidi** [comment]
@Regenhardt Thank you for your feedback. We have added this to our customer requests.

**Comment by markjulmar** [comment]
@Regenhardt -- Microsoft Learn has a completely different model for training which isn't based on long-form video like MVA was. Instead, it's much smaller, oriented around tasks and scenarios, and tries to be more interactive and hands-on.

A lot of the content from MVA which was current and had an owner moved to Channel9, or got re-created by teams. For example, the C# series was redone and published here [https://channel9.msdn.com/Series/CSharp-101](https://channel9.msdn.com/Series/CSharp-101).

If you prefer straight video-based training, then Channel9 is the place to search.
