### ISSUE TITLE
Some search results contain markup

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#18]
E.g. https://docs.microsoft.com/en-us/dotnet/api/?view=netframework-4.7&term=ImeProcessedKey

shows the following in the description:

Gets the keyboard key referenced by the event, if the key will be processed by an [!INCLUDE[TLA#tla_ime](~/includes/tlasharptla-ime-md.md)].

which includes something I think shouldn't be part of the search result.

----------
⚠ Idea migrated from UserVoice

**Created By:** Anonymous
**Created On:** 2018/02/26 13:30:08 +0000
**Votes at Migration:** 1
**Supporters at Migration:** 1

**Comment by dend** [comment]
#log-suggestion @dend

**Comment by botcrane** [comment]
🚀 **ATTENTION**: [Internal request](https://ceapex.visualstudio.com/web/wi.aspx?pcguid=7d644393-99ad-41c8-ac53-7fa79294c720&id=24040) logged.

**Comment by dend** [comment]
@mairaw can we update the documentation page above to use a string instead of a token?

**Comment by dend** [comment]
Given that there are no immediate plans to change this behavior, I am closing this issue as `by-design`
