### ISSUE TITLE
docs.microsoft.com/aspnet needs update

### ISSUE THREAD

**Issue by Rick-Anderson** [MicrosoftDocs/feedback#1800]
**Link to article:** [docs.microsoft.com/aspnet/](https://docs.microsoft.com/aspnet/)

**Problem:**
What's wrong with the article?

ASP.NET Core is a ~new~ open-source and cross-platform .NET framework for ...

It's not new.

**Comment by Rick-Anderson** [comment]
While you're at it, consider removing

**Find Visual Studio 2015/project.json version of the documentation**

**Comment by mairaw** [comment]
Why don't you fix that @Rick-Anderson?
https://github.com/aspnet/AspNetDocs/blob/master/aspnet/index.md
