### ISSUE TITLE
The Win32 section needs small updates for VS2019 and typo fixes

### ISSUE THREAD

**Issue by KaeLL** [MicrosoftDocs/feedback#1801]
Bigger issue is: why isn't it editable? As in, why can't we at least submit pull requests? https://docs.microsoft.com/en-us/windows/win32/index

**Comment by mairaw** [comment]
@GrantMeStrength can you take a look at this feedback?

**Comment by GrantMeStrength** [comment]
Hi KaeLL. The Win32 section does not _currently_ support PRs. That'll change later this month.
Thank you for your feedback!

is this the typo you refer to?

_Navigate the full Win32 API index for developing desktop and server applications Windows 10 and earlier versions._

I've asked the writer who owns the page to check it.

**Comment by mcleanbyron** [comment]
Thanks for opening this issue, KaeLL. I'm in the process of fixing the typo mentioned in the previous comment (adding the missing "for" before "Windows 10"). Did you have other specific issues/feedback on the https://docs.microsoft.com/en-us/windows/win32/index page?

**Comment by KaeLL** [comment]
> The Win32 section does not _currently_ support PRs. That'll change later this month.
> Thank you for your feedback!

Good and you're welcome.
> is this the typo you refer to?
> 
> _Navigate the full Win32 API index for developing desktop and server applications Windows 10 and earlier versions._

Not particularly. There are a few more in the rest of the tutorial, and the 1st Module 1 example is slightly different from the default one in VS2019 when you create a Win32 Desktop App project. All in all, just small things that PR are a perfect way of addressing.



> I'm in the process of fixing the typo mentioned in the previous comment (adding the missing "for" before "Windows 10").

Thanks.
> Did you have other specific issues/feedback on the https://docs.microsoft.com/en-us/windows/win32/index page?

I've gone through only the Getting Started with Win32 and C++ part, so no feedback on the rest so far. Hopefully by the time I return to it and find an issue should there be any, I'll be able to submit the PR.

**Comment by mcleanbyron** [comment]
Thanks for the additional info. Could you please specify the URL of the tutorial you're referring to?

**Comment by KaeLL** [comment]
https://docs.microsoft.com/en-us/windows/win32/learnwin32/window-messages
-> Last code example is tagged as 'syntax', not C++

https://docs.microsoft.com/en-us/windows/win32/learnwin32/painting-the-window
-> First code example is broken in 2 boxes.

**Comment by mcleanbyron** [comment]
Thanks for the additional details. Both of those particular issues you pointed out are now fixed. Please also note again that we plan to enable public pull requests on this repo within the next few weeks, and at that time you will be able to submit your own fixes.

**Comment by mcleanbyron** [comment]
Hi @KaeLL. Public pull requests for articles in the Win32 conceptual docs repo are now enabled. Thanks for your patience!
