### ISSUE TITLE
Win32 WNDCLASS and WINDCLASSEX articles are missing

### ISSUE THREAD

**Issue by collinstevens** [MicrosoftDocs/feedback#1803]
**Describe the bug**
The WNDCLASS and WNDCLASSEX articles are returning not found for the Win32 API.

**To Reproduce**
1. Go to https://docs.microsoft.com/en-us/windows/win32/winmsg/window-class-structures
2. Click on WNDCLASS or WNDCLASSEX
4. See not found error

**Expected behavior**
I expect to be able to navigate to WNDCLASS and WNDCLASSEX documentation from https://docs.microsoft.com/en-us/windows/win32/winmsg/window-class-structures.

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
The WNDCLASS article is archived at https://web.archive.org/web/20130807025439/https://msdn.microsoft.com/en-us/library/ms633576(v=VS.85).aspx.

The WNDCLASSEX article is archived at https://web.archive.org/web/20190119025017/https://docs.microsoft.com/en-us/windows/desktop/api/winuser/ns-winuser-tagwndclassexa.

**Comment by nakst** [comment]
Possibly related to my issue, https://github.com/MicrosoftDocs/feedback/issues/1781

**Comment by drewbatgit** [comment]
Hello, thanks for your feedback. This does appear to be a similar issue to [#1781](https://github.com/MicrosoftDocs/feedback/issues/1781). Again there are a few things going on. We split the ANSI (*A) and Unicode (*W) versions of these APIs into separate pages. Also, at some point during the migration to docs.microsoft.com, these pages were renamed. But it looks like the redirections from MSDN have not been updated. So when you click the links in the "Window Class Structures" page, which point to the old MSDN pages, you get a 404. So for the short term, these structures are documented here:

https://docs.microsoft.com/en-us/windows/win32/api/winuser/ns-winuser-wndclassa
https://docs.microsoft.com/en-us/windows/win32/api/winuser/ns-winuser-wndclassexa

I have created a work item to track down why these redirects are incorrect and to make sure that users are able to find these APIs. Thanks again for your feedback.
