### ISSUE TITLE
Japanese Translation is incorrect (confusing) in O365 Service Health and Continuity  document 

### ISSUE THREAD

**Issue by keiichim1975** [MicrosoftDocs/feedback#1806]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

**Link to article:**
Tell us where exactly a problem occurs.

https://docs.microsoft.com/ja-jp/office365/servicedescriptions/office-365-platform-service-description/service-health-and-continuity

**Problem:**
What's wrong with the article?

Japanese Translation is incorrect (confusing) in "Recent worldwide uptime"  section in the document.

English Version (Correct) : List is devided by each Quarter like "Q1" to "Q4"

Japanese Version (Incorrect) : A part that shows Quarter is not translated correctly.
In this part, It is no problem to keep "Q1" to "Q4" if in the Japanese document.
(mean no need to translate this table)

A translation results are  incorrect and no meaning in this table , Words like  "おける" "四半期" and it is need to replace Q1,Q2,Q3 to keep correct meanings.

**Comment by TinaMcN** [comment]
@keiichim1975 thank you for reporting the issue.  It is caused by a problem with the machine translation tool.   I sent the article to be translated by a human which will take a few days.  @OfficeGlobal, please let us know when the translation is complete.

**Comment by OfficeGlobal** [comment]
@keiichim1975 , @TinaMcN article was HumanTranslated and published live

**Comment by TinaMcN** [comment]
@keiichim1975, can you please confirm if the issue is fixed and if so, can you close?  Thank you!

**Comment by keiichim1975** [comment]
@TinaMcN  Thank you very much for your action ! I have confirmed to fix correctly. It is  no problem to close !

**Comment by TinaMcN** [comment]
@keiichim1975 thank you for confirming it is fixed.  Is it possible for you to close it?  I don't have the access rights to close it.

**Comment by keiichim1975** [comment]
@TinaMcN  Oh, Sorry.. I have closed a case, Thank you!
