### ISSUE TITLE
DAX NORM.DIST & NORM.S.DIST "probability mass function" mistake

### ISSUE THREAD

**Issue by DubbySlashy** [MicrosoftDocs/feedback#1807]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

**Link to article:**
https://docs.microsoft.com/en-us/dax/norm-dist-dax
https://docs.microsoft.com/en-us/dax/norm-s-dist-dax

**Problem:**
Normal distributions are continuous. The mentions of "probability mass function" should be changed to "probability density function".

**Comment by ryanmajidi** [comment]
@Minewiskan Can you please take a look at this issue?

**Comment by Minewiskan** [comment]
#in-progress

**Comment by DubbySlashy** [comment]
I corrected "cumulative" to "continuous" in my original post.

**Comment by Minewiskan** [comment]
@DubbySlashy  - You are correct. The articles have been updated. Thanks for pointing this out!
#please-close

**Comment by DubbySlashy** [comment]
Thank you for fixing this!
