### ISSUE TITLE
In at least version 2.0 of the richedit control, the cchText parameter is in bytes, not characters.

### ISSUE THREAD

**Issue by Ma-XX-oN** [MicrosoftDocs/feedback#1808]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

**Link to article:**
https://docs.microsoft.com/en-us/windows/win32/api/winuser/nc-winuser-editwordbreakproca

**Problem:**
I wrote a `Editwordbreakproca()` handler and found that, in least version 2.0 of the richedit control, the `cchText` parameter is receiving values in bytes, not characters.

**Comment by ryanmajidi** [comment]
@GrantMeStrength Can you please take a look at this issue?

**Comment by GrantMeStrength** [comment]
This sounds like an issue related to EDITWORDBREAKPROC referring to either the ANSI or UNICODE version of the API. I'm going to close this issue now, but if it's still an issue, please feel free to reopen it or create a new one. Thanks!
