### ISSUE TITLE
Tables formatting broken in socket options page

### ISSUE THREAD

**Issue by BillHoover** [MicrosoftDocs/feedback#1814]
The tables in this article don't render correctly. I tried Chrome, Edge, and IE.

https://docs.microsoft.com/en-us/windows/win32/winsock/using-so-reuseaddr-and-so-exclusiveaddruse

**Comment by mairaw** [comment]
@GrantMeStrength can you take a look at this feedback?

**Comment by GrantMeStrength** [comment]
Assigned to correct writer.

**Comment by stevewhims** [comment]
Thanks for filing the issue, @BillHoover. I believe I've fixed the tables. I'll go ahead and close the issue, but please re-open if you feel I've closed it in error. ~Steve
