### ISSUE TITLE
Infinite body box load untill I tick PC version in Chrome Mobile

### ISSUE THREAD

**Issue by deton24** [MicrosoftDocs/feedback#1819]
I tried to post something on TechNet forums, but I could only write the topic title, and I couldn't write any text below, because it was showing loop of loading icon. 
But when I clicked to show the PC version of the site in Chrome options, it worked normally, and it looks like even page doesn't look different at all at this point.

Android. Chrome 75.0.3770.143 (quite recent version from few days ago).

**Comment by rootsmusic** [comment]
@deton24 TechNet forums have closed at https://docs.microsoft.com/en-us/teamblog/msdn-technet-english-forums-closure
#please-close
