### ISSUE TITLE
ITsSbPlugin Sample Code

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#182]
Please post sample code that can be used as starting point for implementing a remote desktop services connection broker plugin via ITsSbPlugin.  It looks like this code used to be available via http://archive.msdn.microsoft.com/rdsdev/Release/ProjectReleases.aspx?ReleaseId=3480, but that page has been down for quite some time.

----------
⚠ Idea migrated from UserVoice

**Created By:** Marc Klenotic
**Created On:** 2017/01/09 19:00:21 +0000
**Votes at Migration:** 2
**Supporters at Migration:** 2

**Comment by dend** [comment]
It looks like the sample is deprecated and was removed. Author should check out the [RDS content on docs.microsoft.com](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/welcome-to-rds).
