### ISSUE TITLE
links to structure documentation are dead

### ISSUE THREAD

**Issue by Ma-XX-oN** [MicrosoftDocs/feedback#1820]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

**Link to article:**
https://docs.microsoft.com/en-us/windows/win32/controls/bumper-rich-edit-control-reference-structures

And possibly many more structure pages on that site.

**Problem:**
All the links to structures are dead links.  Sometimes gives a potential redirect, but many times it is just guessing and suggesting stuff that isn't related.

**Comment by mairaw** [comment]
@jwmsft can you look at this feedback?

**Comment by drewbatgit** [comment]
Thanks for reporting this. This is a known issue in which an update to the docs on 7/30 caused links to structures throughout the documentation to be broken. We are actively working on fixing all broken links this issue has caused as soon as possible. I apologize for the inconvenience.
