### ISSUE TITLE
You have activated the Sandbox too many times today, please come back and try again tomorrow.

### ISSUE THREAD

**Issue by RobeDevOps** [MicrosoftDocs/feedback#1822]
**Describe the bug**
I was doing several multiple training on the same day a few days ago and I am still getting the message **_You have activated the Sandbox too many times today, please come back and try again tomorrow._**  So I am not able to work on any other training that requires sandbox subscription.

**Expected behavior**
Able to use the sandbox in other training that requires this or in other cases I won't able to complete the module.

**Screenshots**

**Desktop (please complete the following information):**
 - Windows 10
 - Browser Chrome Version 76.0.3809.100 (Official Build) (64-bit)

**Additional context**

**Comment by kchyn-bay** [comment]
I ran into the same issue and hasn't been able to complete materials for the past week, please advise.

**Comment by Frosthage** [comment]
Ran into the same issue as well.

**Comment by Frosthage** [comment]
https://twitter.com/docsmsft/status/1159615738568564737

I guess you can close the issue

**Comment by RobeDevOps** [comment]
Closing the issue cauz they are working on it and I know now the reason. Thank you @Frosthage
