### ISSUE TITLE
Reference page for TOUCHINPUT structure gives a 404

### ISSUE THREAD

**Issue by theres-waldo** [MicrosoftDocs/feedback#1823]
**Link to article:**
https://docs.microsoft.com/en-us/windows/desktop/api/winuser/ns-winuser-tagtouchinput

(As linked to from https://docs.microsoft.com/en-us/windows/win32/wintouch/structures and numerous other places.)

**Problem:**
The article is missing (gives a 404).

This is an important documentation page as it lists the fields of `TOUCHINPUT` and their types.

**Comment by mairaw** [comment]
@Karl-Bridge-Microsoft can you please take a look at this issue?

**Comment by theres-waldo** [comment]
`TOUCHINPUT` is not the only affected structure. For example, RID_DEVICE_INFO also gives a 404:

https://docs.microsoft.com/en-us/windows/desktop/api/winuser/ns-winuser-tagrid_device_info

**Comment by drewbatgit** [comment]
Thanks for providing feedback on the docs. There is a known technical issue across the docs that is causing broken links for many structures. While we are working on fixing the issue, please note that you can get to the target API by removing the last part of the URL, which will direct you to the page for the header that contains the API. We apologize for this disruption.

**Comment by theres-waldo** [comment]
Thanks! I can confirm that the mentioned workaround allows me to reach the correct URLs, which are (for the mentioned examples):

https://docs.microsoft.com/en-us/windows/win32/api/winuser/ns-winuser-touchinput
https://docs.microsoft.com/en-us/windows/win32/api/winuser/ns-winuser-rid_device_info
