### ISSUE TITLE
Current type not on the same line in Inheritance as base types

### ISSUE THREAD

**Issue by svick** [MicrosoftDocs/feedback#1824]
**Describe the bug**

In the Inheritance section, the current type is moved down, relative to its base types.

**To Reproduce**

1. Go to  [`ArgumentException`](https://docs.microsoft.com/en-us/dotnet/api/system.argumentexception).
2. Look at the Inheritance section.

**Expected behavior**

All types are on the same line.

**Screenshots**

![](https://user-images.githubusercontent.com/287848/62820357-7c1de080-bb63-11e9-8cbd-afd9b183f1ad.png)

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox 68, Edge 44

**Comment by mairaw** [comment]
This seems fixed. Can you confirm @svick?

**Comment by svick** [comment]
Yeah, it looks correct now, closing.
