### ISSUE TITLE
Add content for WMI

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#183]
Windows Management Instrumentation has been poorly documented for many years. Please add content for WMI to this site. 

----------
⚠ Idea migrated from UserVoice

**Created By:** Dean Gross
**Created On:** 2016/12/15 14:26:44 +0000
**Votes at Migration:** 1
**Supporters at Migration:** 1

**Comment by dend** [comment]
@kevinyr is your team handling requests as this one?

**Comment by Powerhelmsman** [comment]
Please check here. https://docs.microsoft.com/en-us/windows-hardware/drivers/kernel/implementing-wmi. 
I will now proceed to close this issue. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and I will reopen the issue.
