### ISSUE TITLE
Azure DevOps REST API Documentation for Graph Users is missing

### ISSUE THREAD

**Issue by PerriNelson** [MicrosoftDocs/feedback#1831]
Regardless of which version of the API, clicking on any links under Graph > Users on the site https://docs.microsoft.com/en-us/rest/api/azure/devops/ results in an HTTP 404. Further, clicking on the search links provided also returns an HTTP 404.

**Comment by PerriNelson** [comment]
![404 on users](https://user-images.githubusercontent.com/10645886/62963128-a10d9000-bdbd-11e9-96b5-97beb3315aae.gif)

**Comment by mairaw** [comment]
@elbatk can you please take a look? I can repro this.

**Comment by elbatk** [comment]
Thanks @mairaw and @PerriNelson , adding @wnjenkin to take a look since I moved over to Azure Artifacts :)

**Comment by mairaw** [comment]
Let's have the metadata updated then 😉

**Comment by mairaw** [comment]
@rloutlaw do you know who owns this?
