### ISSUE TITLE
Broken link 

### ISSUE THREAD

**Issue by StefanSchroeder** [MicrosoftDocs/feedback#1833]
On page

https://docs.microsoft.com/de-de/windows-hardware/manufacture/desktop/iot-ent-get-the-tools-you-need

the link 

https://go.microsoft.com/fwlink/p/?linkid=2069623

does not work.

It is anchored in 

"In order to start your journey in manufacturing with Windows 10 IoT Enterprise, you'll need to reach out to a distributor from this list."

**Comment by toneshelby** [comment]
On page: https://docs.microsoft.com/en-us/rest/api/power-bi/
Under Rest Operation Groups, last link titled Users is broken.

**Comment by mairaw** [comment]
Thanks for your feedback @StefanSchroeder. @eliotgra can you look at this feedback?

@toneshelby that issue was reported here already: #1831. Better to track different broken links separate. But thanks for letting us know!

**Comment by EliotSeattle** [comment]
So sorry for the delay. This is fixed. Link points to [https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RE37tp1](https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RE37tp1). Should be live tomorrow.

@mairaw can you please close this?
