### ISSUE TITLE
AD LDS Overview Article Stale

### ISSUE THREAD

**Issue by AMarvosh** [MicrosoftDocs/feedback#1834]
A new article hasn't been created to replace the below.

https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-R2-and-2012/hh831593(v=ws.11)

Now that Windows Server 2019 is released users should be aware that AD LDS (Active Directory Lightweight Directory Services) is supported in Windows Server 2019.

**Comment by rootsmusic** [comment]
@AMarvosh "We're no longer updating this content regularly."
#please-close
