### ISSUE TITLE
Slight CSS bug

### ISSUE THREAD

**Issue by MythreyaK** [MicrosoftDocs/feedback#1836]
**Describe the bug**

CSS for the border is broken, as shown 

![image](https://user-images.githubusercontent.com/26112391/63035635-1e79f300-bed9-11e9-82d2-7e21ed2770a4.png)

**To Reproduce**
1. Go to [this page](https://docs.microsoft.com/en-us/aspnet/core/performance/caching/distributed?view=aspnetcore-2.2#feedback)
2. Scroll down to feedback
3. Expand feedback item and look for those with likes/reactions
4. Observe the line through the emojis

**Desktop (please complete the following information):**
 - OS: Windows 10 1809
 - Browser: 
    * Microsoft Edge (44.18362.267.0) with EdgeHTML (18.18362) 
    * Firefox (68.0.2), 
    * Edge Dev (Chrome build 78.0.244.0)

**Comment by mairaw** [comment]
@adkinn can you take a look?

**Comment by adkinn** [comment]
Thanks for the report, we'll investigate!
