### ISSUE TITLE
TechNet Flash newsletter subscribe page doesn't work

### ISSUE THREAD

**Issue by LKari** [MicrosoftDocs/feedback#1837]
**Subscribe**- and **Sign up and customize your news to stay informed automatically.** -links in https://technet.microsoft.com/en-us/cc543196.aspx leads to error "An unknown error occurred while processing your request. This is most likely due to a connection failure. Please try again. 

R10EXW-c09556bb-0711-475c-b194-141039cd2228 "

**Comment by rootsmusic** [comment]
@LKari  TechNet Newsletters are archived at https://docs.microsoft.com/en-us/archive/newsletter/technet/microsoft-technet-flash-archive
