### ISSUE TITLE
Change location of the offline PDF download link

### ISSUE THREAD

**Issue by supernova-eng** [MicrosoftDocs/feedback#184]
Please move the offline PDF download link on the line next to the Author name, or stack under the blue buttons on the right. Currently the "Download PDF" link shows at bottom left and is not quite visible.

----------
⚠ Idea migrated from UserVoice

**Created By:** Suprotim
**Created On:** 2016/11/22 13:32:51 +0000
**Votes at Migration:** 3
**Supporters at Migration:** 3

**Comment by dend** [comment]
@dastaffo please follow-up on this request.

**Comment by dastaffo** [comment]
Adding @cillroy to evaluate for the future

**Comment by diablodale** [comment]
On portrait-oriented monitors, the `Download PDF` link can not be found or identified.
In addition, this download intent is not clustered in the top nav with the other intents (bookmark, feedback, edit, share, ...)
This led to ambiguity in doc availability with the Kinect team and additional issue churn.

### Repro

1. Windows 10 on a HD display (1920x1080) with **portrait** orientation monitor
2. Install Google Chrome browser
3. Run Chrome and make it fullscreen on your **portrait** orientation monitor
4. Visit https://docs.microsoft.com/en-us/azure/Kinect-dk/

### Result

The 'Download PDF' link is lonely, desolate, and un-findable at the far bottom left of the screen.
This link is not clustered in the top nav with the other intents (bookmark, feedback, edit, share, ...)
Screenshot attached 
![lonely-download-link](https://user-images.githubusercontent.com/679350/75984247-56369f80-5eea-11ea-8557-3524336bb3b6.jpg)


### Expected

Download PDF to be clustered with the other intents in the top nav. For example:
bookmark, feedback, edit, share, download, ...

**Comment by keziamicro** [comment]
Hello - reviewing and cleaning up some older feedback/issues. Thanks!

**Comment by diablodale** [comment]
Hi @keziamicro. I see no progress on this issue. By cleanup, are you actually saying "wont fix"?
The issue continues to reproduce today.

**Comment by keziamicro** [comment]
@diablodale By cleanup I mean I've moved this issue into our internal system _(can't add link here due to permissions)_ so that it can get triaged and prioritized by the team.

**Comment by diablodale** [comment]
Oh, that seems disappointing to me. A lack of visibility, tracking.
How do customers report, track and resolve documentation issues if they are hidden from us?
If customers can't have visibility, then we will generally not participate.

**Comment by diablodale** [comment]
@keziamicro, do you have an update on this issue?
