### ISSUE TITLE
Microsoft Learn: Returning to Profile gets a CORS error

### ISSUE THREAD

**Issue by DanteMustCode** [MicrosoftDocs/feedback#1843]
**Describe the bug**
When a user navigates from **Profile** and back, **Profile** does not fetch the data correctly.

**To Reproduce**
* Go to **Microsoft Learn** > **Profile**
* In **In progress** > **Modules**, click a module to navigate to the page for the module
* Click **Back** of the browser:
    * the page is rendered without any user data
    * a CORS error appears in the console
> SEC7120: [CORS] The origin 'https://techprofile.microsoft.com' did not find 'https://techprofile.microsoft.com' in the Access-Control-Allow-Origin response header for cross-origin  resource at 'https://docs.microsoft.com/api/gamestatus/fac50254-c10a-4855-b9ba-cb2fc1c92ea6'.

**Expected behavior**
The page is rendered as usual

**Screenshots**
![SEC7120](https://user-images.githubusercontent.com/52395211/63136768-1b305580-c006-11e9-8c9e-44b2fda5bca1.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge (or Chrome)
 - Version: latest

**Additional context**
N/A

**Comment by mfilotto** [comment]
I'm facing the same issue, any update on this one ?
