### ISSUE TITLE
Microsoft TechNet - 404 - Page not found

### ISSUE THREAD

**Issue by ClaudioShima** [MicrosoftDocs/feedback#1847]
**Describe the bug**

**To Reproduce**
1. Go to Google Search
2. Search for "Microsoft Tech Net"
3. Select the first link

**Comment by mairaw** [comment]
Which error do you get @ClaudioShima? I didn't see any error when I did that.

**Comment by ClaudioShima** [comment]
[https://docs.microsoft.com/en-us/previous-versions/msdn10/ms376608(v=msdn.10)](url)

**Comment by mairaw** [comment]
Weird. The first link for me is https://technet.microsoft.com/en-us/ms376608.aspx, which opens fine for me.

**Comment by docs-product** [comment]
Same as @mairaw, we are not able to reproduce. @ClaudioShima - can you please post a screenshot of the search results, so that we can see the term and the links shown to you?
