### ISSUE TITLE
Example mentioned in the Remarks section is missing in the  article

### ISSUE THREAD

**Issue by saf-itpro** [MicrosoftDocs/feedback#1848]
Second sentence of the **Remarks** section of the article reads:  

> The following example creates an equation and uses the Microsoft.Office.Interop.Word.OMaths.Buildup method to convert the equation to professional format.

But there is no such example (or any example for that matter) in the entire article.

**Comment by docs-product** [comment]
Issue related to this document: https://docs.microsoft.com/en-us/dotnet/api/microsoft.office.interop.word.omath?view=word-pia

**Comment by davidchesnut** [comment]
Hi @saf-itpro, looks like this is a mistake in the article and there never was any sample added. I'll remove the text that indicates there is a sample and republish it soon. If you are looking for an example, there is a [good sample shown on StackOverflow](https://stackoverflow.com/questions/44456263/microsoft-office-interop-word-omath).

Hope this helps!

**Comment by saf-itpro** [comment]
@davidchesnut Thank you for making the change.
