### ISSUE TITLE
Add unreal engine reference to VS Documentation

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#185]
Well, Unreal Engine already have his documentation page and stuff like that, but in the VS page didn't even mention the option if use UE4 to make games

----------
⚠ Idea migrated from UserVoice

**Created By:** Diego Herrera
**Created On:** 2016/11/22 04:31:52 +0000
**Votes at Migration:** 1
**Supporters at Migration:** 1

**Comment by dend** [comment]
This is a content suggestion, so will be closing soon, but want to make sure this gets on @erickson-doug's radar.
