### ISSUE TITLE
'Sysmon 5.2.0.0 - Deployment issues via SCCM' thread deleted

### ISSUE THREAD

**Issue by MyITGuy** [MicrosoftDocs/feedback#1850]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**. -- Not possible as the thread appears to have been deleted.

**Link to article:**
Tell us where exactly a problem occurs. -- https://social.technet.microsoft.com/Forums/en-US/miscutils/thread/a89efd1d-878d-4b75-ae8e-6daefbcec6cc/

**Problem:**
What's wrong with the article? -- Article now states 'This item has been deleted.'

**Comment by rootsmusic** [comment]
@MyITGuy TechNet forums have closed at https://docs.microsoft.com/en-us/teamblog/msdn-technet-english-forums-closure
