### ISSUE TITLE
LangVersion support for F#

### ISSUE THREAD

**Issue by ShalokShalom** [MicrosoftDocs/feedback#1851]
[It is already implemented for C# and VisualBasic](https://docs.microsoft.com/en-us/search/?search=langversion&category=All), [while F# has this feature as well.](https://github.com/fsharp/fslang-suggestions/issues/243#issuecomment-523106507)

**Comment by mairaw** [comment]
@cartermp can you take a look at this feedback?

**Comment by cartermp** [comment]
This is going to just be a part of the set of docs I'll update/add when F# 4.7 ships, since it's not in any released F# today.

**Comment by mairaw** [comment]
Closing this feedback then since the feature hasn't shipped yet. Thanks!

**Comment by ShalokShalom** [comment]
Oh, I understand. You wrote it like it has already landed, should have read the release notes. 
Thanks :)
