### ISSUE TITLE
PowerShell Docs command syntax not colorization.

### ISSUE THREAD

**Issue by wenmin92** [MicrosoftDocs/feedback#1852]
**Describe the bug**
This page [Updates to our PowerShell Documentation Experience](https://docs.microsoft.com/en-us/teamblog/updated-powershell-experience) said: 
> Improved colorization and formatting  
PowerShell cmdlets are now nicely colorized and formatted for better readability.  
![](https://docs.microsoft.com/en-us/teamblog/media/updated-powershell-experience/powershell-syntax-highlighting.png)

But up to now, there isn't any colorized render.

**To Reproduce**
1. Go to any cmdlet page, like [Clear-Item](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/clear-item?view=powershell-6)
2. Scroll down to Syntax section (on the top)
3. See error

**Expected behavior**
The syntax is hard to read, can't understand quickly. Parameter names and parameter types should be rendered in different colors. Optional parameters also should be different.

**Screenshots**
![image](https://user-images.githubusercontent.com/6901815/63402963-e5c5a680-c40f-11e9-84fb-8a41a0390046.png)

**Desktop (please complete the following information):**
 - OS: Win10 (1903)
 - Browser: chrome
 - Version: 76.0.3809.100

**Comment by rootsmusic** [comment]
@wenmin92 Please move this issue to https://github.com/MicrosoftDocs/azure-docs-powershell/issues

**Comment by rootsmusic** [comment]
@wenmin92 Please move this issue to https://github.com/PowerShell/PowerShell/issues/
