### ISSUE TITLE
Dead link : kb_article

### ISSUE THREAD

**Issue by dechapie** [MicrosoftDocs/feedback#1856]
In "WTSEnumerateSessionsA function" page, there is a dead link in the "Remarks" section.
The link points to https://support.microsoft.com/fr-fr/help/291789 which ends in an 404 error.

**Comment by docs-product** [comment]
Page in question: https://docs.microsoft.com/en-us/windows/win32/api/wtsapi32/nf-wtsapi32-wtsenumeratesessionsa

@GrantMeStrength can you please take a look?

**Comment by GrantMeStrength** [comment]
This paper seems to be very old - not sure if you could trust it. But it's cached here:

https://jeffpar.github.io/kbarchive/kb/291/Q291789/

**Comment by GrantMeStrength** [comment]
Thank you for reporting this!
The link to https://docs.microsoft.com/en-us/windows/win32/intl/conventions-for-function-prototypes is not active.
