### ISSUE TITLE
Links to training resources on System Center docs page don't take you to System Center training

### ISSUE THREAD

**Issue by JamesTStanley** [MicrosoftDocs/feedback#1857]
There are two places on https://docs.microsoft.com/en-us/system-center that suggest that if you click them it'll take you to System Center training - but both go to Microsoft Learn, and there is not any System Center content on that site.

**Comment by rootsmusic** [comment]
@JamesTStanley I believe that doc has been redesigned.  Where to click?

**Comment by JamesTStanley** [comment]
@rootsmusic yeah, it's been almost 2 years since I logged this - The Learn link at the top still takes you to Microsoft Learn, but there are now relevant courses in there for Endpoint Manager so this is ok now.
