### ISSUE TITLE
Report Feedback on MS Learn doesn't work in Firefox

### ISSUE THREAD

**Issue by svick** [MicrosoftDocs/feedback#1858]
**Describe the bug**

At the bottom of the [*Troubleshooting known issues*](https://docs.microsoft.com/en-us/learn/support/troubleshooting) page for MS Learn, there is a *Report feedback* form. When I try to use it from Firefox, it doesn't work.

**To Reproduce**

0. Use Firefox.
2. Go to https://docs.microsoft.com/en-us/learn/support/troubleshooting.
3. Select any of the answers to the question "What's your feedback about?".
4. See that nothing happens:

    ![](https://user-images.githubusercontent.com/287848/63575996-a02de880-c58b-11e9-840b-30ad59220321.png)

**Expected behavior**

The rest of the form opens up, just like in Edge:

![](https://user-images.githubusercontent.com/287848/63576067-c05da780-c58b-11e9-943f-86b745450358.png)

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox 68

**Comment by rootsmusic** [comment]
@svick, I'm browsing with version 90.0.2 (64-bit) and it works for me.

**Comment by svick** [comment]
@rootsmusic Yeah, I can't either, closing. Thanks.
