### ISSUE TITLE
MS Learn docs pages link to a private repo

### ISSUE THREAD

**Issue by svick** [MicrosoftDocs/feedback#1859]
**Describe the bug**

The small number of Docs pages for MS Learn link to https://github.com/MicrosoftDocs/LearnShared in its Contributors section, which seems to be a private repo.

**To Reproduce**

1. Go to https://docs.microsoft.com/en-us/learn/support/troubleshooting.
2. Click on one of the contributor's icons on the top of the page.
3. This leads to https://github.com/MicrosoftDocs/LearnShared/blob/live/LearnShared/support/troubleshooting.md, which shows a 404 error.

**Expected behavior**

Either the Contributors section should not link anywhere, or, even better, the MicrosoftDocs/LearnShared repo should be made public.

**Comment by rootsmusic** [comment]
@svick I can't reproduce step 2.

**Comment by svick** [comment]
@rootsmusic Yeah, I can't either, closing. Thanks for letting me know.
