### ISSUE TITLE
Offer offline documentation in more formats

### ISSUE THREAD

**Issue by docs-product** [MicrosoftDocs/feedback#186]
While the offline viewing option is great, PDF's "baked in" page format makes reading on mobile devices very cumbersome.  I suggest offering downloads in open ePub format for easy reading on mobile devices -- allowing for text reflow, text and margin adjustment, color themes, etc.

----------
⚠ Idea migrated from UserVoice

**Created By:** Craig Forrester
**Created On:** 2016/11/21 19:55:39 +0000
**Votes at Migration:** 31
**Supporters at Migration:** 29

**Comment by dend** [comment]
Assigning to @dastaffo as the PM helping drive offline documentation.

**Comment by dastaffo** [comment]
@cillroy FYI

**Comment by docs-product** [comment]
We are assessing what formats we need to support for offline documentation. In the short-term, we do not plan to implement any additional formats beyond PDF and Offline Help.
