### ISSUE TITLE
I can't insert links or image 

### ISSUE THREAD

**Issue by gautierm78** [MicrosoftDocs/feedback#1860]
Hello and sorry for my poor English.
I have a Microsoft account, only for to find solution or ask on https://social.technet.microsoft.com/Forums

But, if i would like to insret an image or a link, Message say "You can not insert image or link, account not effective

My name on social.technet is GautierMa
Could you say me why i Have this problem or where can i valid my accont (accont is 2014...)
Thank's

**Comment by rootsmusic** [comment]
@gautierm78 TechNet forums have closed at https://docs.microsoft.com/en-us/teamblog/msdn-technet-english-forums-closure
