### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by TerdyTheTerd** [MicrosoftDocs/feedback#1866]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

**Link to article:**
https://docs.microsoft.com/en-us/sharepoint/sites/sites-and-site-collections-overview#overview-of-sharepoint-site-collections

**Problem:**
In the last sentence of the first paragraph under the "Overview of SharePoint site collections" there is a typo of "ahat" instead of "that".

**Comment by mairaw** [comment]
This seems to have been fixed. Closing.
