### ISSUE TITLE
Create a view for Azure Preview features in the documentation

### ISSUE THREAD

**Issue by docs-product** [MicrosoftDocs/feedback#187]
Within the Azure documentation it would be great to be able to find all of the Azure features that are currently in Preview all in one place. Even if the document available just provides a description about what the feature does and a small amount of usage guidance.

I have been looking for information covering a few preview features but there is no mention of them in the documentation currently as far as I have been able to find. I think this would be very helpful

thanks

----------
⚠ Idea migrated from UserVoice

**Created By:** Derek Schauland
**Created On:** 2016/11/21 15:24:51 +0000
**Votes at Migration:** 2
**Supporters at Migration:** 1

**Comment by dend** [comment]
@tysonn who should tackle this item?

**Comment by Powerhelmsman** [comment]
@sarah-barrett Please take a look to see if you can add it to metadata.

**Comment by Powerhelmsman** [comment]
#log-suggestion

**Comment by botcrane** [comment]
🚀 **ATTENTION**: [Internal request](https://ceapex.visualstudio.com/web/wi.aspx?pcguid=7d644393-99ad-41c8-ac53-7fa79294c720&id=20432) logged.

**Comment by Powerhelmsman** [comment]
#log-suggestion

**Comment by botcrane** [comment]
🚀 **ATTENTION**: [Internal request](https://ceapex.visualstudio.com/web/wi.aspx?pcguid=7d644393-99ad-41c8-ac53-7fa79294c720&id=20433) logged.

**Comment by sarah-barrett** [comment]
@tysonn @dastaffo This could be a facet in the product filter area.

**Comment by shirgoldbird** [comment]
We don't plan to handle this on the Docs platform side in the near future. I've passed this along to the content team but am closing this out on our end.
