### ISSUE TITLE
Unable to display description of the Remove_AppxPackage command

### ISSUE THREAD

**Issue by gskoczylas** [MicrosoftDocs/feedback#1873]
I'm at https://docs.microsoft.com/en-us/powershell/module/appx/remove-appxpackage?view=win10-ps webpage. The tree in the left panel shows that I'm on the  `Remove_AppxPackage` item but the website displays description of the `Move_AppxPackage` command.

**Comment by rootsmusic** [comment]
Fixed.
#please-close
