### ISSUE TITLE
Download PDF in other language

### ISSUE THREAD

**Issue by jmroyb** [MicrosoftDocs/feedback#1877]
Hi folks,
I can download as PDF https://docs.microsoft.com/en-us/visualstudio/test/improve-code-quality?view=vs-2019

But PDF link is missing for https://docs.microsoft.com/es-es/visualstudio/test/improve-code-quality?view=vs-2019

Do you plan to allow download this link in other language than English?

Cheers

**Comment by JasonCard** [comment]
@jmroyb Thank you for your feedback and we're sorry for the delay. Download PDF link is now available, so closing this issue.
