### ISSUE TITLE
Wrong return value

### ISSUE THREAD

**Issue by fyurisich** [MicrosoftDocs/feedback#1878]
At page
[https://docs.microsoft.com/en-us/windows/win32/api/uxtheme/nf-uxtheme-isthemeactive](url)
the Syntax sections says that function is defined as "void" but the Return Value section says that the function returns a BOOL.
Thanks, Fernando

**Comment by mairaw** [comment]
@GrantMeStrength can you take a look at this issue?

**Comment by GrantMeStrength** [comment]
Thanks! This topic

https://docs.microsoft.com/windows/win32/api/uxtheme/nf-uxtheme-isthemeactive

has been corrected.
