### ISSUE TITLE
can't login at https://sitehelp.microsoft.com/

### ISSUE THREAD

**Issue by rootsmusic** [MicrosoftDocs/feedback#1879]
Received the following error trying to log into https://sitehelp.microsoft.com/ :
"Selected user account does not exist in tenant 'Microsoft' and cannot access the application 'a86fc59f-9bd6-49db-984f-4c1fbe8861cb' in that tenant. The account needs to be added as an external user in the tenant first. Please use a different account."

**To Reproduce**
1. Go to https://docs.microsoft.com/en-us/learn/support/troubleshooting
2. Next to the last "common issue or error message", click on https://sitehelp.microsoft.com/
3. Try to login.

**Expected behavior**
Logged into my account at https://sitehelp.microsoft.com/

**Desktop (please complete the following information):**
Microsoft Windows 10
Firefox Quantum 68.0.2

**Comment by mairaw** [comment]
Where did you see this link @rootsmusic? That's an internal site.

**Comment by mairaw** [comment]
Ah never mind! Let me follow up with the team responsible for that page.

**Comment by mairaw** [comment]
@Saadad you're listed as the author of that page. Can you make sure that the steps don't include sites that external users can't access?

**Comment by docs-product** [comment]
Taking this offline, thank you for bringing this up! Customers outside of Microsoft should not be using SiteHelp.
