### ISSUE TITLE
Make avatar icons for authors and contributors bigger

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#188]
Avatar icon for authors and contributors are too small. It was possible before to recognize avatars.

----------
⚠ Idea migrated from UserVoice

**Created By:** Aleksandar Nikolic
**Created On:** 2016/11/17 23:49:32 +0000
**Votes at Migration:** 2
**Supporters at Migration:** 2

**Comment by ShevaDas** [comment]
We settled on using the current small size for avatars to keep the focus on the article rather than on the author. I can bring this back up to the design team and see if a size increase makes sense at some point down the line.

**Comment by dend** [comment]
Closing as `wont-fix`.
