### ISSUE TITLE
In Microsoft Learn there are no Security roles listed and content lacking

### ISSUE THREAD

**Issue by gw37** [MicrosoftDocs/feedback#1881]
It is surprising the security related content on Microsoft Learn (https://docs.microsoft.com/en-us/learn/) is sparse and difficult to find. In the Roles pulldown list there should be roles such as Security Engineer, Security Architect and perhaps Compliance Lead, with well organized and *deep* learning content specific to those functional roles. The MPP program for CyberSecurity (https://academy.microsoft.com/en-us/tracks/cyber-security/) has some great content and we encourage the site to migrate that MPP content into MS Learn, as the MPP program is closing.

**Comment by rootsmusic** [comment]
Fixed at https://docs.microsoft.com/en-us/learn/roles/security-engineer
#please-close
