### ISSUE TITLE
Searching in the entire document

### ISSUE THREAD

**Issue by nwipfli** [MicrosoftDocs/feedback#1884]
Let's take the Windows Virtual Desktop documentation as an example (https://docs.microsoft.com/en-us/azure/virtual-desktop/). You have a search box on the top left but it performs a search by title. If I want to perform a search in the entire document, I have to download the PDF documentation and perform a search in it by using my keywords. Is it possible to implement a search function enabling you to use keywords and boolean conditions in order to search in the entire documentation your are currently reading, and not limiting your search to the titles ?

Thanks
Nicolas

**Comment by JasonWHowell** [comment]
Hi @nwipfli The docs Table of contents site now prompts you to do a full search. Good idea . Thanks, Jason #please-close 
![image](https://user-images.githubusercontent.com/5067358/82515487-2c464f80-9acd-11ea-8570-834b3d08cce5.png)
