### ISSUE TITLE
The information for 70-483 is useless

### ISSUE THREAD

**Issue by dinobu** [MicrosoftDocs/feedback#1885]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

**Link to article:**
https://www.microsoft.com/en-us/learning/exam-70-483.aspx?s=SCHEDULE_COMPLETE

**Problem:**
Pretty much everything is wrong starting from useless video to links landing on general microsoft learn page and not to actually related content.  For example, practice test is not taking you to a practice test but the rest of videos are way behind, not even scratching the surface and mainly just a blur of useless chatting and joking rather than valuable information.

**Comment by rootsmusic** [comment]
@dinobu "This exam retired on January 31, 2021."
#please-close
