### ISSUE TITLE
Dead hyperlink

### ISSUE THREAD

**Issue by imalyavskiy** [MicrosoftDocs/feedback#1894]
On the page [Windows Filtering Platform Sample](https://docs.microsoft.com/en-us/samples/microsoft/windows-driver-samples/windows-filtering-platform-sample/) at the string "For more information about using Microsoft Visual Studio to build a driver package, see [Building a Driver](http://msdn.microsoft.com/en-us/library/windows/hardware/ff554644)." The  [Building a Driver](http://msdn.microsoft.com/en-us/library/windows/hardware/ff554644) link is dead. Could you please help?

**Comment by rootsmusic** [comment]
Fixed.
#please-close
