### ISSUE TITLE
Dead/broken link in DX12 docs

### ISSUE THREAD

**Issue by ChuckM2** [MicrosoftDocs/feedback#1898]
**Link to article:**
Tell us where exactly a problem occurs.
https://docs.microsoft.com/en-us/windows/win32/api/d3d12/ns-d3d12-d3d12_descriptor_heap_desc
Under NodeMask it says "See Multi-Adapter." with a broken link.

**Problem:**
Link points to https://docs.microsoft.com/windows/desktop/direct3d12/mulit-engine which no longer works.
New link is https://docs.microsoft.com/windows/desktop/direct3d12/multi-engine I believe.

**Comment by mairaw** [comment]
@GrantMeStrength can you take a look at this feedback?

**Comment by drewbatgit** [comment]
Thanks for reporting this broken link. The link has been fixed in the source. You should see the fix on the live site within ~24 hours.

**Comment by ChuckM2** [comment]
Hi, The web page still has the broken link for me.  Was the changed pushed out?
I also found the same broken link to the old "mulit-engine" location on a few other pages.

**Comment by ChuckM2** [comment]
Link is working for me now.  Thank you.
