### ISSUE TITLE
Article possibly in wrong section (so flagged as 'no longer being updated)

### ISSUE THREAD

**Issue by davidgeary** [MicrosoftDocs/feedback#1899]
**Link to article:**
[HTML Clipboard Format](https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/platform-apis/aa767917(v=vs.85)) - https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/platform-apis/aa767917(v=vs.85)

**Problem:**
This article describes the format required for data that is copied to the clipboard as HTML, which I believe is broadly relevant to Windows applications in general.  However, the article is currently located within the documentation for Internet Explorer and therefore flagged as '_no longer being updated_'.

Unfortunately, I cannot find this information anywhere else in the MS docs; the current documentation for the [Clipboard class](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.clipboard?view=netframework-4.8) indirectly links to this page via the [DataFormats.Html Field](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.dataformats.html?view=netframework-4.8) page, but it would be more appropriate if the article were moved/duplicated in this section of the docs so it doesn't risk being lost as the IE documentation becomes more out-of-date and/or potentially made unavailable.

**Comment by rootsmusic** [comment]
@davidgeary Please open an issue in the appropriate doc repo to duplicate the doc in this issue.

**Comment by davidgeary** [comment]
@rootsmusic No problem, that's done (though it would have been a nice touch if you could have pointed me to the appropriate repo - turns out it's not actually in any of the 1800 repos under this org :confused:).

Now logged under [https://github.com/dotnet/dotnet-api-docs/issues/6950](https://github.com/dotnet/dotnet-api-docs/issues/6950).
