### ISSUE TITLE
Missing description about cmap table of Open Type Font

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#19]
https://docs.microsoft.com/ja-jp/typography/opentype/spec/cmap

"cmap" table starts with the version of table and 
number of the encoding subtables.

But its description is missing.

----------
⚠ Idea migrated from UserVoice

**Created By:** Anonymous
**Created On:** 2018/02/24 11:23:20 +0000
**Votes at Migration:** 1
**Supporters at Migration:** 1

**Comment by dend** [comment]
This should now be fixed.
