### ISSUE TITLE
How to escalate a forum issue and contact the moderator

### ISSUE THREAD

**Issue by klgrube** [MicrosoftDocs/feedback#1900]
Hi!

   I posted a question in the SQL Server Reporting Services forum several days ago and so far, the only response I've gotten was one that just asked another question, which I answered days ago.  Further, there seems to be no link to contact a forum moderator anywhere on the screen.  According to what I read, the only way to escalate a question is by contacting the moderator (in this case, I think it's Dave Patrick, but I'm not sure).  But if you can't contact the moderator, you're STUCK!  Frankly, I'm getting VERY upset about the issue I've reported.  Export from SSRS to Excel has always been buggy, but this is absurd.

   Here's the link to my question . . .

https://social.msdn.microsoft.com/Forums/sqlserver/en-US/9978c722-bb41-413f-ada9-aa70f4bd8bc0/issues-with-excel-export-from-ssrs?forum=sqlreportingservices

   I hope you can help.

Thanks.

**Comment by rootsmusic** [comment]
@klgrube MSDN forums have closed at https://docs.microsoft.com/en-us/teamblog/msdn-technet-english-forums-closure
