### ISSUE TITLE
Broken links on "Internationalization for Windows Applications" page

### ISSUE THREAD

**Issue by nikolodus** [MicrosoftDocs/feedback#1901]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

**Link to article:**
https://docs.microsoft.com/en-us/windows/win32/intl/international-support

**Problem:**
Two hyperlinks lead to invalid URLs:
[Script and Font Support in Windows.](https://msdn.microsoft.com/globalization/mt791278)
[Input Language: Keyboards and IMEs.](https://msdn.microsoft.com/en-US/globalization/mt662332)

**Comment by mairaw** [comment]
@Karl-Bridge-Microsoft can you take a look at this feedback?

**Comment by Karl-Bridge-Microsoft** [comment]
@nikolodus - thanks! Topic has been updated.
