### ISSUE TITLE
Extension methods for IEnumerable<T> seem wrong

### ISSUE THREAD

**Issue by svick** [MicrosoftDocs/feedback#1903]
**Describe the bug**

The [Extension Methods section of the `IEnumerable<T>` page](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.ienumerable-1?view=netcore-2.2#extension-methods) doesn't contain the methods I expect to be there and does contain methods I don't expect to be there.

**Expected behavior**

The Extension Methods section contains commonly used extension methods for the `IEnumerable<T>` interface, especially LINQ extension methods from [the `Enumerable` class](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable?view=netframework-4.8).

The section does not contain domain-specific extension methods, specifically those from LINQ to XML, since those don't apply in most situations.

The current behavior is that many extension methods from LINQ are not shown (e.g. `Contains`), while LINQ to XML extension methods are shown.

**Comment by KalleOlaviNiemitalo** [comment]
dotnet/dotnet-api-docs#1540 is similar.

**Comment by rootsmusic** [comment]
@svick Please subscribe to https://github.com/dotnet/dotnet-api-docs/issues/1540 because that duplicates your issue.
#please-close
