### ISSUE TITLE
[Question] repository

### ISSUE THREAD

**Issue by rootsmusic** [MicrosoftDocs/feedback#1906]
Where are the repositories for [DAX function reference](https://docs.microsoft.com/en-us/dax/dax-function-reference) and [Power Query M function reference](https://docs.microsoft.com/en-us/powerquery-m/power-query-m-function-reference)?  Thanks.

**Comment by mairaw** [comment]
They both come from the same private repo: https://github.com/MicrosoftDocs/query-docs-pr

**Comment by rootsmusic** [comment]
@mairaw Please see [issue #1913](https://github.com/MicrosoftDocs/feedback/issues/1913)
