### ISSUE TITLE
ID2D1Bitmap::CopyFromMemory method Documention Error

### ISSUE THREAD

**Issue by nooobguest** [MicrosoftDocs/feedback#1907]
**Link to article:**
[ID2D1Bitmap::CopyFromMemory method](https://docs.microsoft.com/zh-cn/windows/win32/api/d2d1/nf-d2d1-id2d1bitmap-copyfrommemory)  

**Problem:**
The description of first parameter `dstRect` said  
 ```
In the current bitmap, the upper-left corner of the area to which the region specified by 
srcRect is copied.
````  
however, `dstRect` is a `D2D1_RECT_U` rather than a point type, it seem copied form the description of [ID2D1Bitmap::CopyFromBitmap](https://docs.microsoft.com/zh-cn/windows/win32/api/d2d1/nf-d2d1-id2d1bitmap-copyfrombitmap) method's `destPoint` paramter.

**Comment by drewbatgit** [comment]
Thank you for reporting this issue. The issue has been fixed in the content source and will be published to the live site (en-us locale) within 24 hours.
