### ISSUE TITLE
Typo in XMCOLOR::XMCOLOR function document

### ISSUE THREAD

**Issue by ghoflvhxj** [MicrosoftDocs/feedback#1908]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

**Link to article: https://docs.microsoft.com/en-us/windows/win32/api/directxpackedvector/nf-directxpackedvector-xmcolor-xmcolor%28float_float_float_float%29**
Tell us where exactly a problem occurs.

**Problem: It looks typo, am I right?**
![image](https://user-images.githubusercontent.com/31897380/64538446-995af000-d357-11e9-8899-498e0b5fc0da.png)

**Comment by drewbatgit** [comment]
Thank you for reporting this issue. This has been fixed in the content source. The change should be on the live site within 24 hours.
