### ISSUE TITLE
Add instant search results.

### ISSUE THREAD

**Issue by glibnub** [MicrosoftDocs/feedback#191]
Show search results as they come up from the index, depending on what the user is typing.

----------
⚠ Idea migrated from UserVoice

**Created By:** Den Delimarsky
**Created On:** 2016/11/01 20:02:38 +0000
**Votes at Migration:** 9
**Supporters at Migration:** 8

**Comment by presleyy** [comment]
@botcrane  thank you for the feedback. Just to clarify my understanding first - do you expect something like returning search results instantly when the user is typing? Yes, we have that idea internally and had lots of discussion on it. We have that kind of behavior in [API browser](https://docs.microsoft.com/dotnet/api/). This gives you instant results when you are typing namespace, type, and member name. But in [search page](https://docs.microsoft.com/search/index), users have chance to organize the search query within more terms before hitting the search button, this is more like a search engine behavior. It will be very helpful for us to know if there has any specific scenario in search page can help you if we convert to the instant search behavior. Thanks!

**Comment by presleyy** [comment]
Love the idea of showing search results instantly when user is typing. This has been discussed internally several times whether or not to enable that behavior. Searching from entire documents in Docs every time when user is typing or deleting a single character is challenge to search engine and user experience won't be that good. This can be doable if having a smaller documents set and will have much better user experience. At current phase, we focus on improving search relevance and the experience of presenting the search results. We continue investigating the possibility of enabling instant search results behavior. But it is lower priority than the work of improving the search core.

**Comment by presleyy** [comment]
Created a [customer suggestion](https://ceapex.visualstudio.com/Engineering/_workitems/edit/25944) work item to track this suggestion.

**Comment by docs-product** [comment]
Search suggestions are displayed when the user is attempting to find content from the header.
