### ISSUE TITLE
Shell Clipboard Formats link is pointing to a wrong location.

### ISSUE THREAD

**Issue by HubKing** [MicrosoftDocs/feedback#1911]
**Describe the bug**
Clicking a link like "CF_HDROP" does not jump to the details of CF_HDROP, but to "https://docs.microsoft.com/windows".

**To Reproduce**
1. Go to https://docs.microsoft.com/en-us/windows/win32/shell/clipboard
2. Click on CF_HDROP

**Expected behavior**
Jump to the "CF_HDROP" section on that page.

**Screenshots**
![image](https://user-images.githubusercontent.com/10900489/64585035-25116280-d3d2-11e9-846b-d181cfc6d24f.png)

**Comment by mairaw** [comment]
@mijacobs @mcleanbyron I can repro this. Can you please take a look at this issue?

**Comment by mcleanbyron** [comment]
Thanks for reporting this issue. The anchor links in this article have been fixed.

**Comment by mairaw** [comment]
Thanks @mcleanbyron!
