### ISSUE TITLE
repository for DAX and Power Query M function reference

### ISSUE THREAD

**Issue by rootsmusic** [MicrosoftDocs/feedback#1913]
Repository not found at answer to [issue #1906](https://github.com/MicrosoftDocs/feedback/issues/1906)

**Comment by mairaw** [comment]
@rootsmusic I don't understand this issue. The team has probably opted for working on a private repository only. Is there something wrong that you're seeing with that content?

**Comment by harmenverburg** [comment]
I'd like to contribute as well to the documentation, but I cannot create a PR for this.
