### ISSUE TITLE
Release Note typo for 16.2.5

### ISSUE THREAD

**Issue by mdell-seradex** [MicrosoftDocs/feedback#1914]
**Link to article:**
[https://docs.microsoft.com/en-ca/visualstudio/releases/2019/release-notes#top-issues-fixed-in-visual-studio-2019-version-1625](https://docs.microsoft.com/en-ca/visualstudio/releases/2019/release-notes#top-issues-fixed-in-visual-studio-2019-version-1625)

**Problem:**
In the link text "Visual Studio stops respsonding on creating a new SSIS project" there is an extra "s" in the word "responding".

**Comment by mairaw** [comment]
@JacquelineWiddis I can still see a typo on https://docs.microsoft.com/en-ca/visualstudio/releases/2019/release-notes-v16.2#top-issues-fixed-in-visual-studio-2019-version-1625: "respsonding" 

I'm not really sure how the VS release notes process works, otherwise I'd submit a fix.

**Comment by mdell-seradex** [comment]
I think I had to manually create this doc feedback because they don't give us that option in the release note docs.
I just went to another doc page and started feedback there to get the template and then altered it to point at this doc page.

**Comment by JacquelineWiddis** [comment]
I will have it fixed in a few minutes.

**Comment by mairaw** [comment]
It has been fixed now. Thanks for your feedback @mdell-seradex. I tagged someone from the team earlier who made the change for us.

**Comment by mdell-seradex** [comment]
I saw, thank you.  I actually contacted her directly regarding this after your update.

**Comment by mdell-seradex** [comment]
I saw, thank you.  I actually contacted her directly regarding this after you tagged her.
