### ISSUE TITLE
Windows Runtime C++ reference version of IMetaDataDispenser::OpenScope is missing list of supported IIDs

### ISSUE THREAD

**Issue by poizan42** [MicrosoftDocs/feedback#1918]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem** (if available).

**Link to article:**
https://docs.microsoft.com/en-us/windows/win32/api/rometadataapi/nf-rometadataapi-imetadatadispenser-openscope

**Problem:**
The documentation is useless without knowing which interfaces are supported. The .NET Unmanaged API Reference also contains IMetaDataDispenser, but this instance of the documentation does list the supported IIDs at https://docs.microsoft.com/en-us/dotnet/framework/unmanaged-api/metadata/imetadatadispenser-openscope-method:

> Valid values are IID_IMetaDataEmit, IID_IMetaDataImport, IID_IMetaDataAssemblyEmit, IID_IMetaDataAssemblyImport, IID_IMetaDataEmit2, or IID_IMetaDataImport2.

**Comment by mairaw** [comment]
@GrantMeStrength can someone from your team look at this issue?

**Comment by stevewhims** [comment]
Hi, @poizan42, and thanks for filing this issue. I've reached out for help with the missing IIDs, and when I get those I'll make the fix. I'll close the issue here for now, I'll track the work internally, and I'll come back here and leave an update when I have one.

Thanks again!
Steve

**Comment by stevewhims** [comment]
Hi, @poizan42, the fix is now done, please see the live topic for the list of IIDs.

Thanks!
Steve
