### ISSUE TITLE
docs learn browse link is broken

### ISSUE THREAD

**Issue by jvschoen** [MicrosoftDocs/feedback#1926]
https://docs.microsoft.com/en-us/learn/browse/?roles=data-scientist

The link above brings me to a no results found page. Even If I try typing anything into the search box I get no results. I am brought to the site from:

https://docs.microsoft.com/en-us/learn/?l=ZTStIacZD_6511316548

I click the select my role and choose data scientist, and then I'm directed to that first link to no results.

**Comment by rootsmusic** [comment]
Fixed.
#please-close
