### ISSUE TITLE
I'm having problem seeing the entire table

### ISSUE THREAD

**Issue by ChuckM2** [MicrosoftDocs/feedback#1927]
**Link to article:**
"Tell us where exactly a problem occurs."
https://docs.microsoft.com/en-us/windows/win32/direct3ddxgi/hardware-support-for-direct3d-12-1-formats

**Problem:**
"What's wrong with the article?"
I have a very wide display and I want to view the table on this article, but no matter what I do (using Chrome or IE browser, making window size larger) I only see a small region of the table on screen with scroll bars.  How can I make the table fill the screen so it is easy to read?

**Comment by ChuckM2** [comment]
![image](https://user-images.githubusercontent.com/28119814/65204769-eae33900-da41-11e9-8306-1dc1e20e9f66.png)

**Comment by mairaw** [comment]
That seems like a tough issue to solve. Adding @stevewhims to take a look.

**Comment by stevewhims** [comment]
Yes, this is very tricky. All of the topics in this series of topics have this same problem. This is the only topic in the series that has tried to break a single table down into multiple tables (breaking at arbitrary places in the list of 115 formats) presumably to try and alleviate slightly the scrolling issue. It doesn't alleviate it enough, though.

What I'm inclined to do is this. Break the topic down into 115 sections; one for each format. The "in this article" sidebar on the right will serve as a list of formats with links to the appropriate section. Each section will contain a table with a row per target. None of the tables will need to scroll at all. The entire web page will scroll vertically like all web pages do. I realize it'll mean duplicating the list of targets 115 times, but I see no better alternative. A table with frozen rows/column labels and always onscreen scrollbars would be better than what we have here, but we can't achieve that technically.

I'll add fixing this to my TODO list and get to it asap.

~Steve

**Comment by ChuckM2** [comment]
So my use case is to look up a certain format, like "R10G10B10A2_UNORM", and see all the information about that format, preferably with as much information on screen at once.  Are suggesting making one table per format with all of the information on one or two tall columns, so no horizontal scrolling?  (I think I'm confused when you say "table with a row per target".)

**Comment by ChuckM2** [comment]
This is the result (see attached image) of some hacking and browser extensions.  Is this not possible to achieve on the Microsoft website?  Why is the table width restricted so much?

![image](https://user-images.githubusercontent.com/28119814/65219674-e3d22000-da6d-11e9-8022-f140fcf43c3d.png)

**Comment by stevewhims** [comment]
@ChuckM2, what I'm thinking is that each format would be represented by its own section. Here's what just the first format's section would look like:

The images are broken here, but they won't be in the final topic. And you could then navigate to the topic, search for the format(s) you're interested in, and view the table in that section. As I say, the "in this article" sidebar on the right would serve as a list of formats with links to the appropriate section.

So there would be 115 tables like this, one for each format.

## DXGI_FORMAT_UNKNOWN<sup>L</sup> (0)
|Target|Support|
|-|-|
|Bits Per Element (BPE)|0|
|Format Support|![required](images/letter-r.jpg)|
|Buffer|![required](images/letter-r.jpg)|
|Input Assembler Vertex Buffer|\-|
|Input Assembler Index Buffer|\-|
|Stream Output Buffer|\-|
|Texture1D|\-|
|Texture2D|\-|
|Texture3D|\-|
|TextureCube|\-|
|Shader ld|\-|
|Shader sample (any filter)|\-|
|Shader sample_c (comparison filter)|\-|
|Shader sample (mono 1_bit_filter)|\-|
|Shader gather4|\-|
|Shader gather4_c|\-|
|Mipmap|\-|
|Mipmap Auto- Generation|\-|
|RenderTarget|\-|
|Blendable RenderTarget|\-|
|Output Merger Logic Op|\-|
|Depth/Stencil Target|\-|
|Raw UAV and SRV|\-|
|Structured UAV and SRV|![required](images/letter-r.jpg)|
|Typed UAV|\-|
|UAV Typed Store|\-|
|UAV Typed Load|\-|
|UAV Atomic Add|\-|
|UAV Atomic Bitwise Ops|\-|
|UAV Atomic Cmp&Store/ Cmp&Exch|\-|
|UAV Atomic Exchange|\-|
|UAV Atomic Signed Min/Max|\-|
|UAV Atomic Unsigned Min/Max|\-|
|CPU Lockable|![required](images/letter-r.jpg)|
|4x Multisample RenderTarget|\-|
|8x Multisample RenderTarget|\-|
|Other Multisample Count RT|\-|
|Multisample Resolve|\-|
|Multisample Load|\-|
|Display Scan-Out|\-|
|Cast Within Bit Layout|\-|
|Video Decoder Support|\-|
|Video Processor Input|\-|
|Video Processor Output|\-|
|Shared Resource|\-|
|BackBuffer Castable Even Fully Typed||
|Tiled Resource|![required](images/letter-r.jpg)|

**Comment by stevewhims** [comment]
I'll go ahead and close this GitHub issue now that it's resolved. Thanks, all!

-Steve
