### ISSUE TITLE
Section headers (Parameters, Constructors, etc) need Collapse All

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#193]
Every member has a collapse button, but member groups don't have a Collapse All.

----------
⚠ Idea migrated from UserVoice

**Created By:** Kirill Osenkov
**Created On:** 2016/06/27 19:03:46 +0000
**Votes at Migration:** 9
**Supporters at Migration:** 9

**Comment by dend** [comment]
We are not currently planning to implement this. After the Ignite conference, we will re-assess how we can improve the design of the reference templates, however no immediate functionality will be developed.
