### ISSUE TITLE
signup for technet link is broken

### ISSUE THREAD

**Issue by michaeljones-clearwave-es** [MicrosoftDocs/feedback#1931]
**Describe the bug**
If you click on the link:
Sign up and customize your news to stay informed automatically.
You get an error page that says:
An unknown error occurred while processing your request. This is most likely due to a connection failure. Please try again.

R30EZW-8a6a6995-5df4-4729-b510-6cd357cc9970

**To Reproduce**
1. Go to 'https://technet.microsoft.com/en-us/cc543196'
2. Click on 'Sign up and customize your news to stay informed automatically.'

**Expected behavior**
go to signup page

**Screenshots**
![image](https://user-images.githubusercontent.com/55401811/64973085-4bd40b00-d8a2-11e9-8532-8b147d7c65d8.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by rootsmusic** [comment]
@michaeljones-clearwave-es TechNet has closed at https://docs.microsoft.com/en-us/teamblog/msdn-technet-english-forums-closure
