### ISSUE TITLE
Incorrect (broken) Hyperlinks in Raw Input Reference

### ISSUE THREAD

**Issue by Ry-Fi** [MicrosoftDocs/feedback#1933]
**Describe the bug**
In the Raw Input Reference, links in the left pane to the Raw Input Structures are broken.

Eg. In the left pane, the RAWKEYBOARD link's URL is
https://docs.microsoft.com/en-us/windows/desktop/api/winuser/ns-winuser-tagrawkeyboard
which is a 404.  On the page
https://docs.microsoft.com/en-us/windows/win32/inputdev/raw-input-structures
in the primary pane the RAWKEYBOARD link's URL is
https://msdn.microsoft.com/en-us/library/ms645575(v=VS.85).aspx
which resolves correctly.

**To Reproduce**
1. Go to https://docs.microsoft.com/en-us/windows/win32/inputdev/raw-input-structures
2. Click one of the Raw Input Structures links in the left pane
3. 404 error

**Expected behavior**
No 404 error :-)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Comment by rootsmusic** [comment]
Fixed.
#please-close
