### ISSUE TITLE
Broken link in DX12 doc

### ISSUE THREAD

**Issue by ChuckM2** [MicrosoftDocs/feedback#1934]
**Describe the bug**
https://docs.microsoft.com/en-us/windows/win32/direct3d12/recording-command-lists-and-bundles
On this page, the link to D3D12_COMMAND_LIST_TYPE in the top outline goes to https://docs.microsoft.com/en-us/windows/ instead of someplace within the document.

**To Reproduce**
Open link - https://docs.microsoft.com/en-us/windows/win32/direct3d12/recording-command-lists-and-bundles
Click on link D3D12_COMMAND_LIST_TYPE
Notice you are not on a page related to D3D12_COMMAND_LIST_TYPE.

**Expected behavior**
Jump to information about D3D12_COMMAND_LIST_TYPE

**Desktop (please complete the following information):**
Win10, Chrome browser

**Comment by mairaw** [comment]
@stevewhims I've opened https://github.com/MicrosoftDocs/win32/pull/35 to fix this.

**Comment by ChuckM2** [comment]
Thank you :-)
