### ISSUE TITLE
Search API

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#194]
Would love an API for programmatically searching for content.

----------
⚠ Idea migrated from UserVoice

**Created By:** Lucas Vogel
**Created On:** 2016/05/16 18:56:45 +0000
**Votes at Migration:** 24
**Supporters at Migration:** 24

**Comment by presleyy** [comment]
We have the search API, mainly for site internal use purpose. According to search improvement plan, we are doing the works including improve search relevance and search experience. We will announce the search API after those improvements applied.

**Comment by Powerhelmsman** [comment]
API is there. Please have a try. I will close the issue now.
