### ISSUE TITLE
 Brackets mistakes in Docs of ContainerProperties Class

### ISSUE THREAD

**Issue by artsiomtserashkovich** [MicrosoftDocs/feedback#1942]
**Link to article:**
[https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.containerproperties?view=azure-dotnet#examples](ContainerProperties Docs. Example Section)

**Problem:**
When i've explored docs of ContainerProperties, i noticed that in example section you have few mistakes with brackets. 
Instead of using ``)`` bracket to close signature of method call , you use ``]`` bracket. 
Example:
``
    Container container = client.GetDatabase("dbName"].Containers["MyCollection"];
    await container.DeleteAsync();
``

**Comment by rootsmusic** [comment]
Fixed.
#please-close
