### ISSUE TITLE
Make the system open source

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#195]
..to help improving other documentations as well :)

----------
⚠ Idea migrated from UserVoice

**Created By:** Jens Willmer
**Created On:** 2016/05/06 19:20:36 +0000
**Votes at Migration:** 207
**Supporters at Migration:** 204

**Comment by andrewconnell** [comment]
I'm specifically interested in the GitHub commenting piece. While I'd personally be interested in it, I'm involved in maintaining some Patterns & Practices (PnP) projects within the Office umbrella and we'd love to tie site comments => projects like this.

Really curious to see if you guys will be sharing details or just the source of how any engine / etc works to implement comments with GitHub issues on a site.

**Comment by cillroy** [comment]
@andrewconnell I will talk with the engineering team to see if we can get some specific documentation for you

**Comment by lowellstewart** [comment]
I would also love to see more of the system (besides just DocFX) open-sourced, or at least have some insight into how you recommend combining DocFX with content management, version control, etc. for a more full-featured system.

**Comment by Powerhelmsman** [comment]
@andrewconnell lowellstewart just commented the feedback. Please come back to take a look.

**Comment by jdanyow** [comment]
The open source version is https://utteranc.es

**Comment by dend** [comment]
Additionally, I've [written a blog post](https://dennisdel.com/blog/docs-in-cloud/) that documents what it takes to make an experience like docs run. This should give a good starting point for anyone trying to build documentation infrastructure.
