### ISSUE TITLE
Example for .formulalocal makes no sense with the german laguage settings.

### ISSUE THREAD

**Issue by schoche2** [MicrosoftDocs/feedback#1955]
**Link to article:**
https://docs.microsoft.com/en-us/office/vba/api/excel.range.formulalocal

https://docs.microsoft.com/de-at/office/vba/api/excel.range.formulalocal

**Problem:**
The Example makes no sense if you use the german language settings. 

**Nehmen wir an, Sie geben die Formel =SUM(A1:A10) in Zelle A11 des ersten Arbeitsblatts ein und verwenden dazu die US-Englisch-Version von Microsoft Excel.** Wenn Sie diese Arbeitsmappe auf einem Computer öffnen, auf dem die US-amerikanische Version installiert ist, wird nach Ausführung des folgenden Makros die Formel =SUM(A1:A10) in einem Meldungsfeld angezeigt.

The engish version is fine.

**Assume that you enter the formula =SUM(A1:A10) in cell A11 on worksheet one, using the American English version of Microsoft Excel.** If you then open the workbook on a computer that's running the German version and run the following example, the example displays the formula =SUMME(A1:A10) in a message box.

For the german version it should look something like this: 

**Nehmen wir an, Sie geben die Formel =SUMME(A1:A10) in Zelle A11 des ersten Arbeitsblatts ein und verwenden dazu die Deutsche-Version von Microsoft Excel.** Wenn Sie diese Arbeitsmappe auf einem Computer öffnen, auf dem die US-amerikanische Version installiert ist, wird nach Ausführung des folgenden Makros die Formel =SUM(A1:A10) in einem Meldungsfeld angezeigt.

Hope you understand my point, but bringing an example for .formulalocal with two excel versions with the same language settings makes no sense.

**Comment by rootsmusic** [comment]
@SonjaSaltzman "Provide feedback about an article by using the 'Is this page helpful?' control on the article page."
#please-close
