### ISSUE TITLE
Bookmarking

### ISSUE THREAD

**Issue by krisrajzlive** [MicrosoftDocs/feedback#1956]
There is a Bookmarks in the profile page of learning portal, but not sure how to bookmark a page and bring it to Bookmarks tab.
Any help would be appreciated.

**Comment by jopires0** [comment]
I have the same feedback. I started using Microsoft Learn environment a few days ago and could not find any way to bookmark a module or page for future reference. I had to copy the page URL to a separate document to keep tracking of interesting topics to review later.

**Comment by mairaw** [comment]
@AndrewCook can you take a look at this issue about bookmarks?

**Comment by AndrewCook** [comment]
Friends, bookmarks work on content pages today. (For example: [https://docs.microsoft.com/en-us/azure/azure-functions/]( https://docs.microsoft.com/en-us/azure/azure-functions/)). And we will look into adding the ability to bookmark learn modules.

**Comment by krisrajzlive** [comment]
Awesome, thanks for listening to us. Now I can bookmark learning modules, docs etc.,! Makes learning more easy and more focused!
