### ISSUE TITLE
Suggested content improvement - WAIT_ABANDONED_0 

### ISSUE THREAD

**Issue by ChuckM2** [MicrosoftDocs/feedback#1960]
**Link to article:**
https://docs.microsoft.com/en-us/windows/win32/api/synchapi/nf-synchapi-waitformultipleobjects

**Problem:**
It doesn't clearly describe what WAIT_ABANDONED_0 is.  This is clearly described here: https://docs.microsoft.com/en-us/windows/win32/api/synchapi/nf-synchapi-waitforsingleobject

Either a link to the other document or the full description should be added to the page next to WAIT_ABANDONED_0 . 
The description is:
"The specified object is a mutex object that was not released by the thread that owned the mutex object before the owning thread terminated. Ownership of the mutex object is granted to the calling thread and the mutex state is set to nonsignaled.
If the mutex was protecting persistent state information, you should check it for consistency."

**Comment by mairaw** [comment]
@GrantMeStrength can you look at this feedback?

**Comment by GrantMeStrength** [comment]
Great idea. I added some links.
