### ISSUE TITLE
Open Source WCF Ria Services documentation ?

### ISSUE THREAD

**Issue by Daniel-Svensson** [MicrosoftDocs/feedback#1963]
Hi.

I am the current maintainer/owner of OpenRiaServices which is the open sourced version of WCF Ria Service. The source code was open sourced way back in 2013 but the documentation was not made a

Would it be posible to release the documentation for WCF Ria Services at 
https://docs.microsoft.com/en-us/previous-versions/dotnet/wcf-ria/ee707344(v=vs.91) and nested sites for use by the [OpenRiaServices project](https://github.com/OpenRIAServices/OpenRiaServices) ?

Source code (html, markdown or whatever markup it is would definitely be desired) but permission to copy and use the documentation would also be helpful.

Also I do not see any details about copyright or other license for the contents so I would appreciate  explicit permission to duplicate and edit it, preferably in the form of a pull request with the source on github, but any other kind of written permission or details on license/copyright status would be helpful

**Comment by ryanmajidi** [comment]
@mairaw Can you please take a look at this issue?

**Comment by Daniel-Svensson** [comment]
@mairaw any chance to get an estimate for when anyone can *start* looking at this? (i understand if it will take time to investigate)

**Comment by mairaw** [comment]
Sorry for the delay @Daniel-Svensson. I just saw the issue now.

@terrajobst what do you think? We probably could do the same we did for the Reactive content and move this to https://github.com/MicrosoftDocs/dotnet-archive? 

The source would be in Markdown, Daniel.

**Comment by Daniel-Svensson** [comment]
@terrajobst have you had any time to look at this?
Guess it might have gotten lost during your vacation

The solution proposed by @mairaw looks good to me.

**Comment by Daniel-Svensson** [comment]
Any chance of making some progress on this before summer? It's about 6 months to end of life when everything Silverlight related (downloads and maybe even documentation) is expected to be removed

**Comment by terrajobst** [comment]
@mairaw 

> @terrajobst what do you think? We probably could do the same we did for the Reactive content and move this to https://github.com/MicrosoftDocs/dotnet-archive?

That makes sense, let's do that!

@Daniel-Svensson 

Sorry for the super long delay :-(

**Comment by terrajobst** [comment]
@Daniel-Svensson 

Done. It's a lot of files. Let us know if something seems missing.

**Comment by mairaw** [comment]
It's at https://github.com/MicrosoftDocs/dotnet-archive now.
