### ISSUE TITLE
Incorrect constructor description in the table (section - Instantiating a StringBuilder object)

### ISSUE THREAD

**Issue by SharunasBielskis** [MicrosoftDocs/feedback#1966]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem** (if available).

**https://docs.microsoft.com/en-us/dotnet/api/system.text.stringbuilder?view=netframework-4.8:**
Tell us where exactly a problem occurs.

**Problem:**
What's wrong with the article?

In the article StringBuilder   Class  - https://docs.microsoft.com/en-us/dotnet/api/system.text.stringbuilder?view=netframework-4.8 section - Instantiating a StringBuilder object is the table in which are described six overloaded class constructors. In the last table row constructor StringBuilder(String, Int32, Int32, Int32) description column Maximum capacity is the description - Defined by the maxCapacity parameter, but in this constructor maxCapasity parameter is absent. I have tested it by using the code which is in this article below the mentioned table and  also correct description of this constructor parameters is in the article for this constructor - https://docs.microsoft.com/en-us/dotnet/api/system.text.stringbuilder.-ctor?view=netframework-4.8#System_Text_StringBuilder__ctor_System_String_System_Int32_System_Int32_System_Int32_
As I understand in this constructor mentioned table column must be the same text as is in this table above row  - Int32.MaxValue

**Comment by ryanmajidi** [comment]
@mairaw Can you please take a look at this issue?

**Comment by mairaw** [comment]
This issue was moved to dotnet/dotnet-api-docs#3692
