### ISSUE TITLE
Broken link in WPF desktop documentation

### ISSUE THREAD

**Issue by mirel-spr** [MicrosoftDocs/feedback#1967]
https://docs.microsoft.com/en-gb/dotnet/desktop-wpf/fundamentals/styles-and-templates-overview
The link leads to a 404 page.
I have found this link at the bottom of [this page](https://docs.microsoft.com/en-us/dotnet/framework/wpf/controls/window-styles-and-templates), and it comes up as the fourth link in [this google search](https://www.google.com/search?q=apply+style+to+window+wpf&oq=apply+custom+style+from+source+dictionary+wpf&aqs=chrome..69i57.8424j0j7&sourceid=chrome&safe=active).

I'm using Chrome on Windows 10.

**Comment by ryanmajidi** [comment]
@mairaw Can you please take a look at this issue?

**Comment by mairaw** [comment]
I think we had the wrong redirect there before but now it's fixed. Thanks for letting us know.
