### ISSUE TITLE
Missing "Keyboard Scan Code Specification" document

### ISSUE THREAD

**Issue by ngirard** [MicrosoftDocs/feedback#1968]
The document titled *"Keyboard Scan Code Specification"* and previously available as a file named `scancode.doc`, is unreachable.

It used to be reachable from the following urls:
- http://download.microsoft.com/download/1/6/1/161ba512-40e2-4cc9-843a-923143f3456c/scancode.doc
- http://go.microsoft.com/fwlink/p/?linkid=242210

According to [archive.org](https://web.archive.org/web/20190902190128/http://download.microsoft.com/download/1/6/1/161ba512-40e2-4cc9-843a-923143f3456c/scancode.doc), it was still available as of sept. 2nd, 2019.

As a result, a number of MS Docs pages have a broken link to this document, e.g. [this one](https://docs.microsoft.com/en-us/windows/win32/api/ntddkbd/ns-ntddkbd-keyboard_attributes).

**Comment by NessDan** [comment]
Was just looking for this document, hoping someone finds it soon.

**Comment by GrantMeStrength** [comment]
The links appear to be corrected. Thanks.
