### ISSUE TITLE
Azure CycleCloud Scheduler Integration doc page - multiple bugs in the Python code

### ISSUE THREAD

**Issue by TormodLandet** [MicrosoftDocs/feedback#1971]
**Link to article:**
https://docs.microsoft.com/en-us/azure/cyclecloud/scheduler-integration

**Problem:**
The Python code in "sge_job_handler" is:

- Not syntactically valid Python: `hard_resources {'slot_type': 'gpu'}` (in what version of Python is this a valid line of code?? )
- Contains a large logic bug defeating the purpose of the code (not overriding "slot_type" if already set by the user)

In addition to not being valid Python, the code is also not very Pythonic. The line

```python
if job['job_name'].find('gpu') != -1:
  ...
```

Should ideally be
```python
if 'gpu' in job['job_name'].lower():
  ...
```

if 'job_name' is guaranteed to be present, else
```python
if 'gpu' in job.get('job_name', '').lower():
  ...
```

**Comment by TormodLandet** [comment]
The second line of the function is also wrongly indented, making it two syntax errors in this seven line function ...

**Comment by ryanmajidi** [comment]
@TormodLandet moved to that repo: https://github.com/MicrosoftDocs/cyclecloud/issues/128
