### ISSUE TITLE
Confusing documentation of Trust Anchor tracking (RFC 5011)

### ISSUE THREAD

**Issue by he32** [MicrosoftDocs/feedback#1972]
**Link to article:**
https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-r2-and-2012/dn593672(v%3Dws.11)

**Problem:**
In the **Working with trust anchors** section there is an "information" box which is quite confusing; it says

```Windows Server 2012 and Windows Server 2012 R2 fully support RFC 5011. Support for RFC 5011 is enabled on the authoritative DNS server on a zone-by-zone basis. However, trust anchor updates are only supported for automated key rollover. If you manually re-sign or unsign a zone, or manually roll zone signing keys, trust anchors on validating DNS servers are not automatically updated.```

First off, in my view, RFC 5011 is first and foremost a function performed by a recursive resolver, *not* by an authoritative DNS server.  The rest of the paragraph also seems to talk about the signing status of own signed zones, which again points to the authoritative DNS publisher function.

In my view, the primary use case for RFC 5011 is the ability to automatically track the roll-over of the "secure entry point" for zones, and in particular for the root zone.  In that context the "important information" paragraph is quite confusing, because your own recursive resolvers typically are *not* authoritative for the root zone.

The first sentence in that section is also confusing, it says

```Because trust anchors represent public keys for corresponding zones, trust anchors must be updated if the public keys for a zone change, such as when a zone is re-signed.```

I thought that the normal modus operandi for signing a zone is that you operate with two DNS keys, one "secure entry point", also known as "key signing key", and another "zone signing key".  It's the latter which is normally used when re-signing a zone, and which can be rotated /  replaced without affecting the "trust anchor" (KSK) for the zone, while it's the "KSK" which is tracked by RFC 5011.  So, no, trust anchors typically do *not* have to be updated when a zone is re-signed, they don't even need to be updated when a "zone signing key" is replaced, but they *do* need to be updated when you roll over to using a new KSK.

Also, as far as I can see, this entire section does not really explicitly say if any administrative action is needed to enable RFC 5011 tracking for a given trust anchor, or whether it is automatic for any and all added trust anchors.  I would have thought that detail would be quite important to underline.

**Comment by ryanmajidi** [comment]
@GrantMeStrength Can you please take a look at this?

**Comment by dendeli-msft** [comment]
Thank you for the feedback! Documentation under `/previous-versions` is no longer supported and is provided for reference purposes only.
