### ISSUE TITLE
Wrong url routing

### ISSUE THREAD

**Issue by emreerkoca** [MicrosoftDocs/feedback#1974]
Msdn issue:

https://code.msdn.microsoft.com/LINQ-Element-Operators-0f3f12ce (Element Operators)

Open this page. Scroll down to bottom. Click "Generation Operators" link. It' s routing you 'Element Operators' page.

**Comment by ryanmajidi** [comment]
@v-kents Can you take a look at this?

**Comment by v-kents** [comment]
@ryanmajidi Unfortunately, as code.msdn is going away I can't edit. However, that Generation Operators link should be going to https://code.msdn.microsoft.com/LINQ-Generation-Operators-8a3fbff7
