### ISSUE TITLE
Articles in Russian language are always outdated

### ISSUE THREAD

**Issue by JohnyL** [MicrosoftDocs/feedback#1976]
Information in Russian is always outdated comparing to English one.
**Examples**:
 1. Page in [Russian](https://docs.microsoft.com/ru-ru/dotnet/standard/frameworks)
 2. Page in [English](https://docs.microsoft.com/en-us/dotnet/standard/frameworks)

Compare:

Section | English | Russian
------- | --------- | ---------
NET Standard | netstandard2.1 | netstandard2.0
NET Core | netcoreapp3.0 | netcoreapp2.2

This outdated information is scattered through all documentation.

**Comment by ryanmajidi** [comment]
@SonjaSaltzman Can you please take a look at this issue?

**Comment by mairaw** [comment]
It’s normal to have a delay between English and localized content. @JasonCard can probably comment on this specific page.

**Comment by JasonCard** [comment]
Hi @JohnyL, 
Thank you for your feedback. It can take up to 2 weeks for new/updated articles to be localized and up-to-date with English version. We have a weekly cadence to handoff a batch of new/updated files, and usually takes about one week to translate them. In this case, English version was published live on Mon 9/23, and it was handed off on Sun 9/29, so it all localized languages should be up-to-date by Mon 10/7 or earlier. So this is usual and thank you for your patience and understanding.
cc @mairaw @SonjaSaltzman @ryanmajidi
