### ISSUE TITLE
https://docs.microsoft.com/en-us/users/profile-name/settings/ unable to save ...

### ISSUE THREAD

**Issue by bdcoder2** [MicrosoftDocs/feedback#1977]
**Unable to save email preferences in profile settings**

- When on page: https://docs.microsoft.com/en-us/users/{profile-name}/settings/

where: {profile-name} is your profile name.

**To Reproduce**
1. Log in to your account.
2. Click on profile name (top right corner)
3. Click on "Settings"
4. Under "Manage your email preferences", Select  a country (I selected "Canada" from the "Country/Region" pull-down menu).
5. Click in the checkbox entitled "I agree"
6. Error displayed (beneath email address textbox, which is filled-in with a valid email address):
    Please provide an email address.

The "Save" button is left in a disabled state.

**Expected behavior**
Once an email address is filled-in, a country is selected, and the checkbox is checked, the system should enable the "Save" button so the settings can be saved -- this does not happen.

**Screenshots**
![ms_error](https://user-images.githubusercontent.com/5932728/65824930-e121b880-e22d-11e9-8c68-b15e194d9578.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Chrome (Version 77.0.3865.90 (Official Build) (64-bit))

**Comment by ryanmajidi** [comment]
@jialge Can you please take a look at this issue?

**Comment by jialge** [comment]
Thank you for submitting the issue!  I have reported it to our developers to take care of it.

**Comment by jialge** [comment]
We have shipped the fix.  Please try again. :)  
Thank you again for reporting the problem to us.

**Comment by dendeli-msft** [comment]
Thank you for the feedback! This issue should be addressed.
