### ISSUE TITLE
virus infection

### ISSUE THREAD

**Issue by 201801365** [MicrosoftDocs/feedback#1978]
my computer got infected by a virus that pops up many desktop.ini. i first encountered it when i followed directions to install an automated app to install visual studio on my pc. it says to download and install the desktop app which i did. then it has a pop up cmd window that asks for my password which i find weird. but i thought it's microsoft. so i did. and the app just restarted and restarted my pc in a loop and filled my drive with desktop.ini and fake shortcuts everywhere. i tried doing this twice. so i think it is really a file from chocolatey that is infected. so has... microsoft learn been hacked??? is microsoft learn infected???

**Comment by docs-product** [comment]
Thank you for the feedback! Because this issue is not related to docs.microsoft.com, we cannot address it in this forum.
