### ISSUE TITLE
Dynamics help docs are not working.

### ISSUE THREAD

**Issue by ThatsReallyAnnoying** [MicrosoftDocs/feedback#1979]
**Describe the bug**
When I click on the link to open the Help Docs, it takes me to an empty page (empty except for headers and footers).  The URL is:

https://docs.microsoft.com/en-au/dynamics365/#pivot=business-apps&panel=customer-engagement

**To Reproduce**
1. From Dynamics, click on the ? icon in the top bar.

**Expected behavior**
It should display help docs.

**Screenshots**

![image](https://user-images.githubusercontent.com/55973580/65856687-a0e54600-e3a5-11e9-8383-9a59282f4092.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge
 - Version: I assume its the latest

**Additional context**

**Comment by mairaw** [comment]
@saurabhchoudhury you're listed as the author of that page, Can you look at this feedback?

**Comment by dendeli-msft** [comment]
Thank you for the feedback! The page should be working correctly now.
