### ISSUE TITLE
Spanish - Mexico Version for : https://docs.microsoft.com/es-mx/teamblog/announcing-unified-powershell-experience

### ISSUE THREAD

**Issue by daveRendon** [MicrosoftDocs/feedback#198]
# Spanish  - es-MX version

Here´s the proposed translated version

## Anunciando el navegador del módulo PowerShell

Esta publicación fue escrita por [Jeff Sandquist](https://twitter.com/jeffsand), Gerente General del equipo de Crecimiento y Ecosistema de Azure.

Hoy anunciamos el lanzamiento del [explorador de módulos PowerShell](https://docs.microsoft.com/powershell/module), una manera fácil y predecible de buscar en todos los módulos y cmdlets de Microsoft PowerShell. En abril, lanzamos nuestra primera experiencia en el [navegador API para .NET ](https://docs.microsoft.com/dotnet/api/)y los comentarios de los clientes fueron que les encantaba la capacidad de encontrar y buscar fácilmente las API de .NET. ¡Hemos tomado estos aprendizajes y los hemos aplicado a PowerShell!

## Muchos módulos de PowerShell, una ubicación
Ya no tendrá que pasar decenas de minutos intentando averiguar dónde se encuentra el cmdlet correcto o si un módulo específico es parte del paquete de PowerShell que acaba de instalar. Todo lo que tiene que hacer es abrir el navegador Powershell Module y comenzar a buscar:

![search-powershell-module](https://user-images.githubusercontent.com/1934250/37109172-2bd356a6-2207-11e8-82c7-4e0ea7af4fa8.gif)

O bien, seleccione uno de los paquetes disponibles y busque solo dentro del mismo: 

![search-powershell-module-ver](https://user-images.githubusercontent.com/1934250/37109221-50c4ff64-2207-11e8-89b3-9791946ba97b.gif)

Los resultados de búsqueda abarcarán tanto módulos individuales como cmdlets.

La misma experiencia también se integra en toda la documentación de referencia de PowerShell: el explorador de módulos PowerShell está disponible en la tabla de contenidos izquierda, como se muestra a continuación. A medida que explore la amplitud de diferentes cmdlets y módulos, todo lo que necesita hacer para encontrar un cmdlet diferente es comenzar a escribir su nombre:

![search-powershell-module-ref](https://user-images.githubusercontent.com/1934250/37109245-67864f0a-2207-11e8-9e15-1e8579e8174d.gif)

## La versión correcta al alcance de tu mano

Dado que muchos clientes se estandarizan en una versión específica de PowerShell o una versión específica de un módulo, queríamos asegurarnos de que pueda filtrar fácilmente el explorador de módulos PowerShell a solo las versiones con las que está trabajando:

![version-picker](https://user-images.githubusercontent.com/1934250/37109308-918bd478-2207-11e8-87e1-d28dd7e7257e.png)

## La edición de contenido está a un clic de distancia
Además de agregar una capacidad de búsqueda completamente nueva para los módulos de PowerShell, también nos mantenemos fieles al espíritu de docs.microsoft.com: siempre abiertos a la mejora y a las contribuciones de la comunidad. Al igual que cualquier otro artículo, simplemente haga clic en Editar y agregue sus contribuciones al archivo Markdown alojado en GitHub: una vez que se apruebe su cambio, ¡se publicará en breve!

![edit](https://user-images.githubusercontent.com/1934250/37109339-ab29d1a0-2207-11e8-9c2e-3ce2c2358031.gif)

## Queremos su opinión
Queremos escuchar sus comentarios sobre cómo podemos hacer que nuestra documentación de referencia de PowerShell sea más útil. Visite nuestro sitio de [UserVoice ](https://msdocs.uservoice.com/)y háganos saber cómo podemos mejorar la experiencia de PowerShell Module Browser. También puede comunicarse con nosotros en [Twitter ](https://twitter.com/docsmsft)para obtener actualizaciones y preguntas rápidas.

**Comment by dend** [comment]
Thank you for your contribution, @daveRendon 🎉

This is a content issue, so flagging as such. @SonjaSaltzman @Sara-Nicolini - can we integrate translated versions from the community for existing localization team blog repos?

**Comment by daveRendon** [comment]
Thank you @dend!

**Comment by Sara-Nicolini** [comment]
@daveRendon, we appreciate your contribution to the blog and thanks for providing the translation in Spanish. Our team of linguists will review your proposed translation and ensure that the Spanish version of the blog post is suitable for all Spanish speaking countries. We will update you on the progress.

**Comment by daveRendon** [comment]
Thank you @Sara-Nicolini !

**Comment by Powerhelmsman** [comment]
Sent email to @Sara-Nicolini to follow up

**Comment by Sara-Nicolini** [comment]
@daveRendon, I will notify you as soon as the Spanish version of the blog post has been published. Thank you so much once again for your contribution.

**Comment by v-jacard** [comment]
@daveRendon, we're sorry for the delay. The Spanish version of this blog post has been published:
[https://docs.microsoft.com/es-es/teamblog/announcing-unified-powershell-experience](https://docs.microsoft.com/es-es/teamblog/announcing-unified-powershell-experience)
Closing this issue.
cc @Sara-Nicolini, @Powerhelmsman, @SonjaSaltzman
