### ISSUE TITLE
Xamarin Platforms Overview, iOS and Mac link to the Android docs

### ISSUE THREAD

**Issue by ashleyswanson360** [MicrosoftDocs/feedback#1980]
**Describe the bug**
The main page for Xamarin has the wrong links under the 'Xamarin Platforms Overview' section at the bottom.

**To Reproduce**
1. Go to [Xamarin Documentation](https://docs.microsoft.com/en-us/xamarin/)
2. Scroll down to 'Xamarin platforms overview' at the very bottom
3. Clicking on any link under 'iOS' or 'Mac' takes you to the 'Android' page instead (except for 'Samples')

**Expected behavior**
The links should take you to the 'iOS' or 'Mac' articles.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 77.0.3865.90

**Comment by conceptdev** [comment]
Thanks for letting us know @ashleyswanson360 - definitely an oversight on our part that has been updated immediately. Appreciate your help!
#please-close
