### ISSUE TITLE
Viewing SPNs documentation is incorrect 

### ISSUE THREAD

**Issue by joerod** [MicrosoftDocs/feedback#1981]
**Link to article:**
https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-r2-and-2012/cc731241(v%3Dws.11)

**Problem:**

> For example, to list the SPNs of a computer named WS2003A, at the command prompt, type setspn -l S2003A, and then press ENTER

this should be

>For example, to list the SPNs of a computer named WS2003A, at the command prompt, type setspn -l WS2003A, and then press ENTER

there is a "W" missing from the example

**Comment by dendeli-msft** [comment]
Thank you for the feedback! The content in `/previous-versions` is provided for archival purposes and is no longer supported or updated.
