### ISSUE TITLE
We can’t use Teams microphone and Video when I have a meeting through Windows Virtual Desktop.

### ISSUE THREAD

**Issue by Zanyangwang** [MicrosoftDocs/feedback#1983]
We can’t use Teams microphone and Video when I have a meeting through Windows Virtual Desktop.

**Is your feature request related to a problem? Please describe.**
Our company wants to install WVD, and we are doing some test of it, we found we can’t use Teams microphone and video when we have a meeting.

**Describe the solution you'd like**
We want to use the Teams microphone and video as we usually used at the client PC.

**Additional context**
We think have a meeting through Teams with Microphone and video is very important, so we hope the WVD team can update this issue quickly. 

Thanks

**Comment by ryanmajidi** [comment]
@Zanyangwang Please go here for help: https://support.office.com/en-us/teams
