### ISSUE TITLE
When I login Windows Virtual Desktop through https://rdweb.wvd.microsoft.com/webclient/index.html ,  I found I can’t import text by Japanese and some other language except English.

### ISSUE THREAD

**Issue by Zanyangwang** [MicrosoftDocs/feedback#1984]
When I login Windows Virtual Desktop through https://rdweb.wvd.microsoft.com/webclient/index.html , 
I found I can’t import text by Japanese and some other language except English.
Is it a bug? 
Can you check the issue through your environment and update this issue.

**Comment by dendeli-msft** [comment]
Thank you for the feedback! Because this is not related to docs.microsoft.com, we cannot address the issue in this forum.
