### ISSUE TITLE
Invalid route links on Xamarin.Android documentation page

### ISSUE THREAD

**Issue by MashB** [MicrosoftDocs/feedback#1985]
Invalid route links on Xamarin.Android documentation page

https://docs.microsoft.com/en-us/xamarin/android/index?WT.mc_id=docs-dotnet-xamarin

1. Go to 'https://docs.microsoft.com/en-us/xamarin/android/index?WT.mc_id=docs-dotnet-xamarin'
2. Click on 'User Interface' , 'Platform features' and other hyperlinks under **Guides**.
3. All links navigate to page not found.

**Expected behavior**
Example ,
Actual URL : https://docs.microsoft.com/en-us/xamarin/android/~/android/platform/
Expected URL : https://docs.microsoft.com/en-us/xamarin/android/platform/

**Comment by ryanmajidi** [comment]
@conceptdev Can you please take a look at this issue?

**Comment by davidbritch** [comment]
@ryanmajidi These have been fixed for the Android docs, courtesy of a PR from @MashB 

The same issue exists for our iOS docs, which I'll go and fix now.

This issue can now be closed.

**Comment by MashB** [comment]
Thanks for quick response. Closing the issue.
