### ISSUE TITLE
Auto light/dark mode 

### ISSUE THREAD

**Issue by beeradmoore** [MicrosoftDocs/feedback#1991]
**Is your feature request related to a problem? Please describe.**
Currently changing theme is a manual process. With OS/browsers being able to automatically change from light to dark mode it'd make sense to have MS Docs have an option to follow the same light/dark mode that your browser/OS is in.

**Describe the solution you'd like**
There is a new CSS property to detect what mode your browser is in, https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme. It'd be nice if this was implemented under an "Auto" theme so when the clock strikes 6 and all my windows go dark, that MS Docs will follow.

**Comment by dendeli-msft** [comment]
Thank you for the feedback! This capability has since been implemented, and docs.microsoft.com is now OS theme-aware!
