### ISSUE TITLE
Badges and trophies

### ISSUE THREAD

**Issue by javierbragazzi** [MicrosoftDocs/feedback#1994]
Badges and trophies in the profile are not displayed correctly.

![Trofeos](https://user-images.githubusercontent.com/13878358/66092718-675a3980-e563-11e9-8adb-7aa46818fce2.jpg)

**Comment by mairaw** [comment]
@docs-product who owns profile and can check this issue?

**Comment by jialge** [comment]
Hello.  Thank you for reporting the issue.  We released a new profile design YESTERDAY! :)  Would you like to check again and see if the problem is gone?

**Comment by dendeli-msft** [comment]
Closing this issue as it should now be resolved. Thank you for the feedback, @javierbragazzi!
