### ISSUE TITLE
WMF 5.1 Downloads Page Release Notes Link Broken

### ISSUE THREAD

**Issue by sean-gall-41** [MicrosoftDocs/feedback#1995]
**Describe the bug**
On the WMF 5.1 downloads page underneath 'Install Instructions' the release notes link is broken, sending you to a '404 page not found' page.  

**To Reproduce**
1. Go to https://www.microsoft.com/en-us/download/details.aspx?id=54616
2. Expand 'Install Instructions' section 
3. click on 'release notes' hyperlink 

**Expected behavior**
Expect 'release notes' hyperlink to send user to the WMF 5.1 release notes page

**Screenshots**
Below is the download page, with arrow pointing to broken link
![WMF_51_issue_1](https://user-images.githubusercontent.com/53318510/66094729-a20ba400-e55a-11e9-83c7-aef0a0ddbb52.PNG)
Below is the result after clicking 'release notes' link
![WMF_51_issue_2](https://user-images.githubusercontent.com/53318510/66094730-a20ba400-e55a-11e9-8a1b-68ef812e6112.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 7 Home Premium
 - Chrome Version 77.0.3865.90 64-bit

**Smartphone (please complete the following information):**
- The problem was encountered only on Desktop. (Have not checked mobile)

**Additional context**
 - No other context to note

**Comment by dendeli-msft** [comment]
Thank you for the feedback! Because this does not apply to docs.microsoft.com, we cannot address the issue in this forum.
