### ISSUE TITLE
Expand login-logout idle duration

### ISSUE THREAD

**Issue by weitzhandler** [MicrosoftDocs/feedback#1996]
**Is your feature request related to a problem? Please describe.**
I find myself logging in to the docs website several times a day from the same browser. And no, my browser isn't configured to delete cookies.

**Describe the solution you'd like**
When a user logs in, please keep them logged in for at least several weeks of idle time before logging them out.

**Comment by dendeli-msft** [comment]
@weitzhandler - can you please provide more context as to what browser/OS are you using? I cannot reproduce this issue locally.

Are you logging in with an organizational account or a Microsoft account?

**Comment by weitzhandler** [comment]
Looks like that issue was solved as I'm no longer experiencing this.
I'm gonna close this issue now. Should I encounter the issue again and I'll reopen it.
Thanks!
