### ISSUE TITLE
IBrowserService deprecated in favor of what?

### ISSUE THREAD

**Issue by LoveNy** [MicrosoftDocs/feedback#1997]
Hello there,

You state that IBrowserService (and it's descendants), have been deprecated,
but you fail to mention in favor of what..

**Link to article:**
https://docs.microsoft.com/en-us/windows/win32/api/shdeprecated/nn-shdeprecated-ibrowserservice

**Problem:**
It would be far more useful if you had the foresight to
include a link to whatever the interface was replaced with..
Or, if it was terminally deep-sixed, at least say so.

WBR / Neo

(PS. No need to respond to me on this issue, as I won't be monitoring. DS.)

**Comment by GrantMeStrength** [comment]
Apologies for taking so long to get to this feedback item. With the advent of Microsoft Edge this topic feels older than ever. Unless there is still a need for this information, I'm going to close this item now. If it is still relevant, please feel free to open it or create a new one.
