### ISSUE TITLE
Broken table layout

### ISSUE THREAD

**Issue by hallazzang** [MicrosoftDocs/feedback#1999]
**Link to article:** 
https://docs.microsoft.com/en-us/windows/win32/stg/the-summary-information-property-set

**Problem:**
![broken-table-layout](https://user-images.githubusercontent.com/5072682/66255750-5b1fe780-e7c2-11e9-8b29-47ee83be1d21.png)

**Comment by mairaw** [comment]
@mcleanbyron can you please look at this feedback?

**Comment by mcleanbyron** [comment]
Thanks for bringing this to our attention. The table has been fixed.
