### ISSUE TITLE
https://docs.microsoft.com/fr-fr/azure/cloud-solution-provider/overview/azure-csp-available-services

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#2]
Could you please add a note to say APSS is only for Direct CSP and Indirect CSP Provider and not available for Indirect Resellers, please ?

A lot of partner/ISV are confused by this capability

----------
⚠ Idea migrated from UserVoice

**Created By:** Jean-Robert
**Created On:** 2018/03/05 10:22:07 +0000
**Votes at Migration:** 1
**Supporters at Migration:** 1

**Comment by dend** [comment]
This is content related, so will be closed shortly. @KirillKotlyarenko @isaiahwilliams - can you help address the feedback?

**Comment by KirillKotlyarenko** [comment]
We'll update it in the next version of the page, thank you.

**Comment by dend** [comment]
Thanks @KirillKotlyarenko - please let us know once this is live.

**Comment by dend** [comment]
Ping @KirillKotlyarenko ☺

**Comment by Powerhelmsman** [comment]
Sent a email to  @KirillKotlyarenko to follow up.

**Comment by KirillKotlyarenko** [comment]
Done.

**Comment by Powerhelmsman** [comment]
@KirillKotlyarenko Thanks for follow up. I will close it as resolved.
