### ISSUE TITLE
The search function does not work for guests.

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#20]
The search function does not work for guests. Is it possible to fix this problem please

----------
⚠ Idea migrated from UserVoice

**Created By:** Sylvain Dorais
**Created On:** 2018/02/23 13:57:48 +0000
**Votes at Migration:** 1
**Supporters at Migration:** 1

**Comment by dend** [comment]
Not related to docs.microsoft.com, therefore closing.
