### ISSUE TITLE
Keyboard on search box not work on mobile 

### ISSUE THREAD

**Issue by RobDesideri** [MicrosoftDocs/feedback#2005]
On mobile browser, if you touch on the lens icon, the search box appears and keyboard is showed.
BUT, after few milliseconds, **keyboard disappears and you cannot write anything** .

Tried on:
- Firefox 
- Opera
- Edge.

OS: Android 8.0

**Comment by mairaw** [comment]
@sudeepku can you help route this feedback? Thanks,

**Comment by DuncanmaMSFT** [comment]
This has been resolved, thanks for reporting it @RobDesideri
