### ISSUE TITLE
.NET Compact Framework docs are gone

### ISSUE THREAD

**Issue by KexyBiscuit** [MicrosoftDocs/feedback#2006]
**Link to article:**
[Microsoft .NET Compact Framework Technical Articles](https://docs.microsoft.com/en-us/previous-versions/windows/embedded/aa286583(v=msdn.10))

**Problem:**
All content of .NET Compact Framework other than the link above return not found,

**Comment by mairaw** [comment]
That whole set of content was archived and is no longer available externally.

But you can search the archive for it:
https://docs.microsoft.com/en-us/search/?search=.net+compact+framework&category=All&dataSource=previousVersions

Your best option is probably the docs located at https://docs.microsoft.com/en-us/previous-versions/visualstudio/visual-studio-2008/f44bbwa1(v=vs.90).

Do you mean that the redirection is not working @KexyBiscuit?

**Comment by KexyBiscuit** [comment]
Yes, I did find the .NET CF docs under Visual Studio section but I thought the docs under Mobile and Embedded Development section would be newer...

And yes, the redirection to MSDN is misleading. 

Seems that docs under https://docs.microsoft.com/en-us/previous-versions/dotnet/netframework-4.0/cc656764(v=vs.100) is the latest set.

Thanks for your help!

**Comment by mairaw** [comment]
No problem.
