### ISSUE TITLE
Banned

### ISSUE THREAD

**Issue by bluebaroncanada** [MicrosoftDocs/feedback#2007]
I got banned.  I definitely deserved it.  I felt someone was being abusive to staff, and I wasn't nice to that person.
Just wondering how long I'll be banned for.

**Comment by mairaw** [comment]
Sorry @bluebaroncanada, can you give more details about where you were banned?

**Comment by bluebaroncanada** [comment]
social.msdn.microsoft.com<http://social.msdn.microsoft.com>, but it's not this email address.  Can you PM me somehow or can I send you an email?

On Thu, 10 Oct 2019 at 00:21, Maira Wenzel <notifications@github.com<mailto:notifications@github.com>> wrote:

Sorry @bluebaroncanada<https://github.com/bluebaroncanada>, can you give more details about where you were banned?

**Comment by dendeli-msft** [comment]
Hi @bluebaroncanada - because this issue is not related to docs.microsoft.com, we cannot address it in this forum.
