### ISSUE TITLE
D3D12_HEAP_TYPE doc should mention that textures can't be UPLOAD or READBACK

### ISSUE THREAD

**Issue by clandrew** [MicrosoftDocs/feedback#2009]
**Link to article:**
https://review.docs.microsoft.com/en-us/windows/win32/api/d3d12/ne-d3d12-d3d12_heap_type

**Problem:**
Doc describing heap types should mention that textures can't be UPLOAD or READBACK. Or, maybe Map could say that. Right now you could possibly garner this idea from the docs but it is very subtle.

related debug layer message:
D3D12 ERROR: ID3D12Device::CreateCommittedResource: A texture resource cannot be created on a D3D12_HEAP_TYPE_UPLOAD or D3D12_HEAP_TYPE_READBACK heap. Investigate CopyTextureRegion to copy texture data in CPU accessible buffers, or investigate D3D12_HEAP_TYPE_CUSTOM and WriteToSubresource for UMA adapter optimizations. [ STATE_CREATION ERROR #638: CREATERESOURCEANDHEAP_INVALIDHEAPPROPERTIES]

**Comment by clandrew** [comment]
A fix has been sent out for this as an internal PR.

**Comment by stevewhims** [comment]
This fix is now live; closing.
