### ISSUE TITLE
Update the Filter text box to indicate title only filtering

### ISSUE THREAD

**Issue by derekschauland** [MicrosoftDocs/feedback#201]
# Idea Title
Update the filter text box to indicate Title only search/filter
## Issue Details

The filter box on docs.microsoft.com filters titles in the TOC and is different from search. What if the empty search box was updated to say Title Filter rather than just Filter, or add a tool tip to let users know that they will be filtering TOC titles and not searching.  

The image below shows the filter box for PowerShell on Docs today

<img width="192" alt="image" src="https://user-images.githubusercontent.com/19751585/37168760-8d80faba-22cb-11e8-84a3-84353f6323d9.png">

Simply adding Title to the front of the text box when empty might be helpful to ensure things are more easily and improve UX.

**Comment by dend** [comment]
Assigning to @ShevaDas as the experience PM here.

**Comment by ShevaDas** [comment]
Thank you for the feedback! I agree this is confusing. I've added an issue in our internal tracking system to get it updated.

**Comment by ShevaDas** [comment]
@derekschauland the placeholder text has been updated and now says "Filter by title" on Docs. :) @dend could you close this out?

**Comment by dend** [comment]
@ShevaDas Flagging as resolved. Closing.
