### ISSUE TITLE
It would be nice to get the C# releases in the form of a feed

### ISSUE THREAD

**Issue by BillWagner** [MicrosoftDocs/feedback#2010]
Transferred from dotnet/docs#7048

This way I could have C# releases and their descriptions appear in my news aggregator!

/cc @lfr

**Comment by docs-product** [comment]
Thank you for the feedback, @BillWagner - at this time, we are not doing any product-specific change tracking. We'll keep the community posted as we look at functionality that enables keeping up-to-date with documentation.
