### ISSUE TITLE
Repo enhancements

### ISSUE THREAD

**Issue by aravindvnair99** [MicrosoftDocs/feedback#2011]
Suggestions:

- Images in the repo aren't optimised (Indexed RGB can be used)
- Wordings could be more precise and concise
- Issue link points to issue list instead of the picker
- More tags can be added to the repo apart from just _**feedback**_ such as **_Microsoft, Docs_**

Will send in a pull request for the same.

**Comment by jambanks91** [comment]
[Export-1910190154231820315064419971 (4)(1).zip](https://github.com/MicrosoftDocs/feedback/files/3746454/Export-1910190154231820315064419971.4.1.zip)

**Comment by jambanks91** [comment]
Get Container Metadata  
   GET http://myaccount.blob.core.windows.net/mycontainer?restype=container&comp=metadata
CanonicalizedResource:  
    /myaccount/mycontainer\ncomp:metadata\nrestype:container  
  
List Blobs operation:  
    GET http://myaccount.blob.core.windows.net/container?restype=container&comp=list&include=snapshots&include=metadata&include=uncommittedblobs  
CanonicalizedResource:  
    /myaccount/mycontainer\ncomp:list\ninclude:metadata,snapshots,uncommittedblobs\nrestype:container  
  
Get Blob operation against a resource in the secondary location:  
   GET https://myaccount-secondary.blob.core.windows.net/mycontainer/myblob  
CanonicalizedResource:  
    /myaccount/mycontainer/myblob  Console.WriteLine("Export-1910190154231820315064419971 (1).zip https://pxsprod01.blob.core.windows.net/6cf49368d7ec1b41d23a43feffffffff/Export-1910190154231820315064419971.zip?sv=2018-03-28&sr=b&sig=rnwuBK6EWeMnV7V0SzzzWiiDzOHrghvodkc92CjWyqA%3D&spr=https&se=2019-10-26T01%3A54%3A53Z&sp=r;
Export-SPTagsAndNotesData
      [-Site] <SPSitePipeBind>
      [-FilePath] <String>
      [-AssignmentCollection <SPAssignmentCollection>]
      [<CommonParameters>]
