### ISSUE TITLE
mistranslate "shiftitem" to Japanese

### ISSUE THREAD

**Issue by azusa** [MicrosoftDocs/feedback#2014]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem** (if available).

**Link to article:**
- https://docs.microsoft.com/ja-jp/graph/api/resources/shiftitem?view=graph-rest-beta
- https://docs.microsoft.com/ja-jp/graph/api/resources/shift?view=graph-rest-beta

**Problem:**
In these articles, a word `shiftitem` is  translated to  `佐々木` .
佐々木(Sasaki) is not general terms ,  it is a proper noun(Japanese family name).

# Original
![image](https://user-images.githubusercontent.com/145814/66481488-050db580-eadc-11e9-9b4d-4ba16c82564e.png)
# Japanase
![image](https://user-images.githubusercontent.com/145814/66481464-f2937c00-eadb-11e9-8cd2-9eb3f0724e06.png)

**Comment by mairaw** [comment]
@SonjaSaltzman can your team help with this?

**Comment by SonjaSaltzman** [comment]
@TinaMcN Hi Tina, is this your team's content? cc: @Soran-M

**Comment by TinaMcN** [comment]
@SonjaSaltzman yes, we own the localization for this content.  @OfficeGlobal please uplift this article to human translation for Japanese.  Also Russian as the issue occurs there also.  @azusa thank you for reporting the issue.

**Comment by azusa** [comment]
@TinaMcN Thanks for reply!  I wonder that "uplift" means that this article will update to human translation for Japanese. Is this all right with you?

**Comment by OfficeGlobal** [comment]
Working on a fix

**Comment by OfficeGlobal** [comment]
@azusa articles were HumanTranslated and published live

**Comment by azusa** [comment]
@OfficeGlobal   I got this issue is fixed. Thanks!
