### ISSUE TITLE
Upgradable content

### ISSUE THREAD

**Issue by dechapie** [MicrosoftDocs/feedback#2015]
Link to article:
https://docs.microsoft.com/en-us/windows/win32/cimwin32prov/win32-systemenclosure

Problem:
I read an article (https://blogs.technet.microsoft.com/brandonlinton/2017/09/15/updated-win32_systemenclosure-chassis-types/) which gives more values for the ChassisType than can be found on the documentation.
Is this content reliable or does the documentation need an update ?
(and what about the PCSystemType in the ComputerSystem class ?https://docs.microsoft.com/en-us/windows/win32/cimwin32prov/win32-computersystem)

**Comment by GrantMeStrength** [comment]
Thanks for taking the time to let us know about this and I sincerely apologize for the delayed response. This is an older topic, and it's tricky to find a subject matter expert who can provide an authoritative answer.  At this time the best I can do is  redirect you to the  community of experts and Microsoft Engineers over at [Microsoft Q&A](https://docs.microsoft.com

If you do create a thread over at Microsoft Q&A, it would be fantastic if you could share that link here so I can track the progress and potentially incorporate the technical details into our documentation. Though I'm marking this Issue as closed now, please treat this thread as an open thread for follow-ups. Thanks!

-john
