### ISSUE TITLE
Please delete an old article on blogs.TechNet / blogs.TechNet記事の削除のお願い

### ISSUE THREAD

**Issue by Aframe00** [MicrosoftDocs/feedback#2018]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem** (if available).

**Link to article:**
https://blogs.technet.microsoft.com/bpj/2014/11/26/project-online-3/
のページ内にある、

"２．イーパックシステムズ株式会社様
業務内容；八木ビジネス コンサルタントと出光興産の共同出資により、2001 年に設立。ERP を中心に、IT コンサルティング、開発支援作業、システム保守 (アウトソーシング)、自社開発ソフト販売などを行う。
担当部門；経営企画室、ERP 事業部"

の部分を削除してください。

**Problem:**
当社はイーパック株式会社は既に出光興産との資本関係は解消し、既に社名をエー・フレーム株式会社に変更しています。
また2019年10月からは監査会社グループ傘下となった為、上述の部分は事実を表していないため、削除をお願いします。

**Comment by docs-product** [comment]
Thank you for the feedback! Articles on blogs are point-in-time content that is not intended to be used as reference. At this time, we have no plans around deleting content.
