### ISSUE TITLE
Wrong link in CreateDirect3D11SurfaceFromDXGISurface doc

### ISSUE THREAD

**Issue by mfkl** [MicrosoftDocs/feedback#2019]
**Describe the bug**

Page https://docs.microsoft.com/en-us/windows/win32/api/windows.graphics.directx.direct3d11.interop/nf-windows-graphics-directx-direct3d11-interop-createdirect3d11surfacefromdxgisurface#remarks contains a wrong link. `CreateDirect3DSurface` links to the wrong page.

**To Reproduce**
1. Go to 'https://docs.microsoft.com/en-us/windows/win32/api/windows.graphics.directx.direct3d11.interop/nf-windows-graphics-directx-direct3d11-interop-createdirect3d11surfacefromdxgisurface#remarks'
2. Click on 'CreateDirect3DSurface'
3. End up on https://docs.microsoft.com/en-us/windows/win32/api/d3d11/nf-d3d11-d3d11createdevice instead of https://docs.microsoft.com/en-us/windows/win32/api/windows.graphics.directx.direct3d11.interop/nf-windows-graphics-directx-direct3d11-interop-createdirect3dsurface

**Expected behavior**
Correct link.

**Desktop (please complete the following information):**
 - All

Tried to fix it myself, but that part of the doc is not in https://github.com/MicrosoftDocs/win32/tree/docs and I cannot open an issue on that repo.

**Comment by GrantMeStrength** [comment]
Thank you! Link has been corrected.
