### ISSUE TITLE
I would like to switch easily between own language and original english one

### ISSUE THREAD

**Issue by sandervandevelde** [MicrosoftDocs/feedback#202]
# Idea Title

Please add a button for split screen text so I can see the whole page in both my own language and the original english one.

## Issue Details

The current solution to compare the (machine) translated pages in my own language and the original text is cumbersome. I have to hover over small parts using the mouse pointer makes it like looking through a microscope. Please add a split screen option so I can compare it in whole.

And make it part of my default settings/preferences. My decision to choose the Original or local language should be leading.

**Comment by Powerhelmsman** [comment]
Assign to @ShevaDas as the experience PM

**Comment by ShevaDas** [comment]
Thanks for the feedback! This is a feature our team has been investigating and scoping out for some time. Although we still have a ways to go before we're ready to release a full side-by-side experience, we're working on some temporary measures in the meantime. I'll make sure to follow up as these features are released.

**Comment by ShevaDas** [comment]
@sandervandevelde We're currently piloting a version of this feature on some pages. You can try it out here by clicking the toggle on the right-hand side of the page: https://docs.microsoft.com/pl-pl/dotnet/framework/get-started/the-net-framework-and-out-of-band-releases
 
<img width="207" alt="read-in-english-toggle" src="https://user-images.githubusercontent.com/3937986/38775709-0048400a-403e-11e8-83b2-0103e3f63596.png">

This is a pilot, so it won't appear on all pages or remember your selection. We're hard at work on adding more functionality, so keep an eye out! :)

**Comment by ShevaDas** [comment]
@sandervandevelde As I don't know what languages you speak, I linked you to a random localized page that demonstrates the toggle behavior. Rest assured that the toggle is localized to say "Read in English" in the appropriate language wherever it appears, not just Polish. :)

We work hard to ensure that our localized content is kept in sync with any changes to the English version of the page, so regardless of whether you're reading in English or another language, you should be seeing the most up-to-date content.

Currently the setting isn't stored, but we're in the process of making that update and hope to roll it out soon.

**Comment by ShevaDas** [comment]
Since this was implemented, I'll be closing it out. Feel free to open another issue if you have additional feedback!
