### ISSUE TITLE
Minor typo

### ISSUE THREAD

**Issue by ranma42** [MicrosoftDocs/feedback#2020]
**Link to article:**
https://docs.microsoft.com/en-us/quantum/?view=qsharp-preview
under "Manage machines & drivers"

**Problem:**
Just a minor typo: `QDK full state simlulator` should be `QDK full state simulator`

**Comment by ranma42** [comment]
and just a couple of lines below `Quantum trace similator` should be `Quantum trace simulator` XD

**Comment by mairaw** [comment]
I've opened a pull request to fix that @ranma42. Thanks for reporting.

**Comment by ranma42** [comment]
@mairaw thanks for the prompt reply. Please note that your PR only fixes the first typo

**Comment by mairaw** [comment]
Oh sorry. I missed the second one.

**Comment by mairaw** [comment]
PR opened: https://github.com/MicrosoftDocs/quantum-docs-pr/pull/546

**Comment by ranma42** [comment]
Both PR have been merged, so I believe this issue can be closed. Thank you :)
