### ISSUE TITLE
Broken layout for "Migrate from legacy analysis (FxCop) to source analysis (FxCop analyzers)" docs page, IT localization

### ISSUE THREAD

**Issue by federinik** [MicrosoftDocs/feedback#2021]
[This](https://docs.microsoft.com/it-it/visualstudio/code-quality/fxcop-analyzers?view=vs-2019) page content is mostly html code for IT localization.

![image](https://user-images.githubusercontent.com/7857520/66569866-b5c39580-eb6c-11e9-9da4-177ec39a9a4a.png)

**Comment by docs-product** [comment]
This should now be fixed - thank you for your feedback!
