### ISSUE TITLE
Dummy text shown on site

### ISSUE THREAD

**Issue by orjanb** [MicrosoftDocs/feedback#2026]
At the following url:
https://www.microsoft.com/en-us/evalcenter/evaluate-windows-server-2019-taggingtest
the section "Eval to Azure tagging" has the text "test test test" repeated instead of an actual description. See attached screenshot.
 
![image](https://user-images.githubusercontent.com/422764/66648663-6775cb80-ec2c-11e9-9e55-61d1a9e4998e.png)

**Comment by docs-product** [comment]
Thank you for the feedback! Because this issue is not related to docs.microsoft.com, we cannot address it in this forum.
