### ISSUE TITLE
Can not open the Contents navigation panel in Android Chrome

### ISSUE THREAD

**Issue by wenLiangcan** [MicrosoftDocs/feedback#2027]
Can not open the Contents navigation panel in Android Chrome   

**To Reproduce**
1. Use Android Chrome go to https://docs.microsoft.com/en-us/aspnet/core/?view=aspnetcore-3.0
2. Click on upright `Contents` button
3. The navigation panel appear in a flash and disappeared

**Expected behavior**
The Contents panel keep expanding until loosing focus by the user.

**Smartphone :**
 - Device: One Plus 6T
 - OS: Android 9
 - Browser: Chrome
 - Version: 77

**Comment by mairaw** [comment]
@DuncanmaMSFT can someone on your team please look at this?

**Comment by DuncanmaMSFT** [comment]
We have a fix in progress, should be available soon. Thanks
