### ISSUE TITLE
Error in MessageBoxW documentation

### ISSUE THREAD

**Issue by tparker24** [MicrosoftDocs/feedback#2029]
**Link to article:**
https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-messageboxw

**Problem:**
In the Section under "Return Value", it states:

> If the message box has no **Cancel** button, pressing ESC has no effect.

However, that is not true for MB_OK.  There, ESC is indeed _honored_ (and in fact returns IDOK).

Note: This same issue may apply to other related pages, like "MessageBox function", "MessageBoxA function", etc.

Minor point I guess, but it should be corrected at some point.

HTH, Tom

**Comment by GrantMeStrength** [comment]
Thank you! I wonder how long this had been incorrect? Anyway, fixed now - better late than never. Thank you!
