### ISSUE TITLE
Would you consider adding UnrealEngine development documentation on HoloLens 2?

### ISSUE THREAD

**Issue by zhangypcn** [MicrosoftDocs/feedback#2034]
Dear Microsoft technology developers,
When will there be UnrealEngine development documentation on HoloLens 2? Will there be a corresponding API supporting UE4 to develop MR?
Thank you for your interest!

**Comment by docs-product** [comment]
Thank you for the feedback! Because this issue is not related to docs.microsoft.com, we cannot address it in this forum.
