### ISSUE TITLE
Show raw mark-down code after render

### ISSUE THREAD

**Issue by donhuvy** [MicrosoftDocs/feedback#2035]
At this link https://docs.microsoft.com/en-us/dotnet/api/?view=netcore-3.0

![mark](https://user-images.githubusercontent.com/1328316/66802005-46bbb780-ef45-11e9-8d64-a0cb134cc4f6.png)

**Comment by mairaw** [comment]
Thanks for your feedback @donhuvy. This is a limitation of the API browser but I've opened a PR to remove those Markdown elements from the summary, which would fix this issue on the API browser as well.
