### ISSUE TITLE
Direct3D Diagnostics Capture Interface Reference is a 404

### ISSUE THREAD

**Issue by Holo-Krzysztof** [MicrosoftDocs/feedback#2038]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem** (if available).

**Link to article:**
https://docs.microsoft.com/en-us/windows/win32/direct3dtools/dx-graphics-tools

**Problem:**
The "Direct3D Diagnostics Capture Interface Reference" link is a 404; it should point to https://docs.microsoft.com/en-us/windows/win32/direct3dtools/vspixengine-reference

**Comment by mairaw** [comment]
Thanks for your feedback @Holo-Krzysztof. 
That article is open to contributions. Would you like to submit a fix?
Some information about how to do this:
https://docs.microsoft.com/en-us/contribute/#quick-edits-to-existing-documents

**Comment by Holo-Krzysztof** [comment]
I've opened a PR [here](https://github.com/MicrosoftDocs/win32/pull/80).

**Comment by mairaw** [comment]
Thank you so much. Someone from that team should review it soon.

**Comment by stevewhims** [comment]
Thanks, @Holo-Krzysztof! I approved your PR. :)
