### ISSUE TITLE
Unsubscribe link needed!

### ISSUE THREAD

**Issue by jantheofel** [MicrosoftDocs/feedback#2041]
I git the following message from App Center Team <no-reply@mail.appcenter.ms> and there is no unsubscribe link at all. Please provide an unsubscribe link ASAP!

"A new version of Airmail Beta for macOS is available.

Airmail Beta 
3.7.0 (553)
for macOS

Install

What's new
[...]

VS App Center
(c) 2019 Microsoft"

**Comment by docs-product** [comment]
Thank you for the feedback - given that the issue is not related to docs.microsoft.com, we cannot address it in this forum.
