### ISSUE TITLE
Microsoft Ignite Exam Registration link gives 404

### ISSUE THREAD

**Issue by BradAF** [MicrosoftDocs/feedback#2043]
At https://www.microsoft.com/en-us/ignite, going to Attendee Tools > Register for an exam leads to https://docs.microsoft.com/en-us/learn/certifications/msignite, which gives a 404 error:
![image](https://user-images.githubusercontent.com/11336928/66930480-a62bcd00-f002-11e9-8e30-53b30c420123.png)
![image](https://user-images.githubusercontent.com/11336928/66930506-b04dcb80-f002-11e9-9f69-0da3a102d791.png)

None of the 'search results' seem to lead to the correct site.

**Comment by mairaw** [comment]
Thank you for letting us know @BradAF. I'm trying to see if I can find someone who can fix that.

Tagging @sadadow here.

**Comment by ngschroeder** [comment]
Wondering about this too, hoping registrations aren't closed. Is there an alternate way to register in the meantime?

**Comment by ngschroeder** [comment]
@mairaw The link now goes to the generic exam page without any info on how to register for an exam at Ignite. Don't want to be a pest but I see this ticket still isn't assigned. Any update?

**Comment by mairaw** [comment]
They added a temporary fix so it doesn't 404 but they are working on the appropriate solution. I don't know if the folks working on this have GitHub, but I'll ask them to comment here about this process. Thanks!

**Comment by ngschroeder** [comment]
Thanks, in that case I'll just keep checking!

**Comment by BradAF** [comment]
Hi @mairaw - looks like they have removed the 'Register for an exam' link completely.
![image](https://user-images.githubusercontent.com/11336928/67390267-4f764400-f56a-11e9-8c97-c4c5c86732e0.png)

Have you heard back anymore from them? Will it be possible to register for exams at Ignite?

**Comment by ngschroeder** [comment]
@BradAF Found this in the FAQ, second question:

https://www.microsoft.com/en-us/ignite/faq

Seems like they are trying to keep this hard to find. I was able to go through the registration process on Pearson and when it came to checkout, a 100% discount was applied. Unfortunately, even thought the FAQ makes it sound like you can take as many exams you like as long as they're part of the covered selection, it appears you can only get one free one. I signed up for AZ-400 for free no problem, but trying to add AZ-300 or any of the other exams that should be covered, the discount is not applied.

Hope this helps. Pretty disappointing that this information was so squirreled away and misleading. The amount of time I've wasted trying to figure out what to do plus the limit of one exam has made this arguably even worth the discount.

**Comment by BradAF** [comment]
Thanks, @ngschroeder - I was at least able to get one exam registered!

**Comment by docs-product** [comment]
Given the changes to the navigation, we're closing this issue as it's no longer applicable.
