### ISSUE TITLE
virtualMachines template reference - Incorrect osDisk caching defaults

### ISSUE THREAD

**Issue by liambarnett** [MicrosoftDocs/feedback#2044]
**Link to article:**
https://docs.microsoft.com/en-us/azure/templates/microsoft.compute/2019-03-01/virtualmachines#osdisk-object

**Problem:**
What's wrong with the article?

The OsDisk caching description reads -  "Default: None for Standard storage. **ReadOnly** for Premium storage.

This is incorrect, OS disks are provisioned using **ReadWrite** caching by default, as supported by the below:

By default, this cache setting is set to **Read/Write** for OS disks and ReadOnly for data disks hosted on Premium Storage.

Source - https://docs.microsoft.com/en-us/azure/virtual-machines/windows/premium-storage-performance#disk-caching

**Comment by mairaw** [comment]
Thanks for your feedback. @tfitzmac can you take a look at this issue?

**Comment by tfitzmac** [comment]
The description comes from the [REST API specification for Compute](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/compute/resource-manager/Microsoft.Compute/stable/2019-03-01/compute.json#L6522) so the change would need to happen there. The [REST docs](https://docs.microsoft.com/en-us/rest/api/compute/virtualmachines/createorupdate#definitions) have the same description.

@cynthn - can you check if the default value listed in the REST API specification is wrong? Or, is there something different about the linked conceptual article?

**Comment by docs-product** [comment]
Per product PM, there are no actions that need to be taken on the document. Closing.
