### ISSUE TITLE
add support link in article

### ISSUE THREAD

**Issue by rootsmusic** [MicrosoftDocs/feedback#2046]
In the article to [develop solutions and customize Excel](https://docs.microsoft.com/en-us/office/client-developer/excel/excel-home#support), please link to the [feedback box for Excel developers](https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback?category_id=163563).  Thanks.

**Comment by mairaw** [comment]
@o365devx can you please look at this issue?
