### ISSUE TITLE
GitHub site feedback is not loaded on non en-us pages

### ISSUE THREAD

**Issue by cremor** [MicrosoftDocs/feedback#2047]
**Describe the bug**
It seems like all documentation pages that don't have `en-us` in their URL can't load the linked GitHub issues for site feedback.

**To Reproduce**
1. Go to any doc site, e.g. https://docs.microsoft.com/en-us/dotnet/standard/tour
2. Scroll down to the bottom of the page
3. See that the linked GitHub issues are shown correctly.
4. Change the `en-us` part of the URL to something else, e.g. `en-gb` or `de-de`.
5. Scroll down to the bottom of the page
6. See that the linked GitHub issues are not shown. The "Loading feedback..." (or translated equivalent) indicator never goes away.

**Expected behavior**
The linked GitHub issues should show up for all languages.
For `en-gb` it should also show the exact same issues as `en-us` shows because both redirect to the same GitHub repository for creating issues.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/116314/66981900-6114a300-f0b5-11e9-9795-1db762bd93de.png)

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox, Chrome and Edge
 - Version: Firefox 69.0.3, Chrome 77.0.3865.120, Edge 44.17763.771.0

**Comment by mairaw** [comment]
Unfortunately I can't repro this. en-gb loads the same comments as en-us and other languages are loading just fine for me. I tried in several different browsers. I'm wondering if the system was down or something. Are you still seeing that issue?

**Comment by cremor** [comment]
Yes, I can still reproduce this issue. In fact I first noticed it a few weeks ago, but until today I didn't realize that it depends on the language in the URL.

I've also tried it with a different PC and a different internet access (work vs. home) to rule out any local network issues.

**Comment by mairaw** [comment]
Ok, thanks for confirming. 

@DuncanmaMSFT who can take a look at feedback control problems?

**Comment by cremor** [comment]
Some more information that might help:

When I scroll down on a page that doesn't load the issues, I don't even see a request being made in the Firefox or Edge developer tools.

I see the following error in the console of the Firefox developer tools on initial page load (so even before I scroll down) on pages that don't load the issues. That error is not added to the console on pages that load the issues correctly.

`Loading the <script> with the source "https://c.s-microsoft.com/mscc/statics/mscc-0.4.1.min.js" failed. tour:1:1`
(Manually translated from my localized Firefox, actual english message might be different.)

Opening that script mentioned in the error message works fine, so I don't know why it failed.
But I'm not sure if this error is related because Edge does not show it in its developer tools.

**Comment by docs-product** [comment]
The feedback control should now be correctly loading. Thank you for the feedback, @cremor!

**Comment by cremor** [comment]
@docs-product @mairaw Should the fix already be live? Because I can still reproduce the bug.

**Comment by cremor** [comment]
@docs-product @mairaw I can still reproduce this issue.
