### ISSUE TITLE
HLSL unbounded array resources documentation may be wrong

### ISSUE THREAD

**Issue by nico3000** [MicrosoftDocs/feedback#2051]
https://docs.microsoft.com/en-us/windows/win32/direct3d12/resource-binding-in-hlsl

If I declare an unbounded SRV array in the root signature (by setting `D3D12_DESCRIPTOR_RANGE1.NumDescriptors` to -1) _and_ in HLSL (by having `Texture2D<float4> g_pMaterialTextures[] : register(t0);`) the debug layer will complain with
```
D3D12 ERROR: ID3D12CommandList::DrawIndexedInstanced: Static Descriptor SRV resource dimensions (D3D12_SRV_DIMENSION_UNKNOWN) differs from that expected by shader (D3D12_SRV_DIMENSION_TEXTURE2D) at register 128 space 0. ...
```

However, the documentation clearly states that this is allowed:
> An array resource may have an unbounded size, which is declared by specifying the very first dimension to be empty, or 0:
> `Texture2D<float4> tex1[] : register(t0)`
> The matching descriptor table could be:
> `DescriptorTable( CBV(b1), UAV(u0, numDescriptors = 4), SRV(t0, numDescriptors=unbounded)`

Obviously, the debug layer cannot validate the descriptors as the actual array size is never explicitly set. The descriptors themselves are a sub range (of size 128 in my case) inside a large descriptor heap so the heap size wouldn't be an indicator either.

**Comment by nico3000** [comment]
If `D3D12_DESCRIPTOR_RANGE_FLAG_DESCRIPTORS_VOLATILE` is set no validation errors will occur but it's not stated anywhere that this is needed.

**Comment by mairaw** [comment]
@stevewhims can you please take a look at this feedback? Thanks!

**Comment by stevewhims** [comment]
Hi, @nico3000, and thanks for filing the issue. I've sent out a request for info about this question to determine whether or not the docs are in need of work.

-Steve

**Comment by ryanmatern-chief** [comment]
Was the product issue referred to in the final comment ever fixed publicly?  I am encountering what appears to be the same issue with an unbounded SRV array in HLSL and an unbounded descriptor table range in the root signature.
