### ISSUE TITLE
Console.WriteLine Method. Incorrect examples for valuable types

### ISSUE THREAD

**Issue by DSivtsov** [MicrosoftDocs/feedback#2055]
**Link to article:**
[Console.WriteLine Method](https://docs.microsoft.com/en-us/dotnet/api/system.console.writeline?view=netframework-4.8)

**Problem:**
All examples of usage Console.WriteLine for valuable types, are shown as the Console.WriteLine(String) - Console.WriteLine($"...")

**Comment by mairaw** [comment]
Thanks for your feedback @DSivtsov. I moved this issue to our repo: https://github.com/dotnet/dotnet-api-docs/issues/3691
