### ISSUE TITLE
Remarks missing from Extended Window Style

### ISSUE THREAD

**Issue by krishty** [MicrosoftDocs/feedback#2057]
Article: https://docs.microsoft.com/en-us/windows/win32/winmsg/extended-window-styles

For `WS_EX_COMPOSITED`, it is stated: *For more information, see Remarks.* There are, however, no remarks in the article.

**Comment by mairaw** [comment]
@hickeys can you please take a look at this feedback? Thanks!

**Comment by krishty** [comment]
Found the missing remarks on ´WS_EX_COMPOSITED´ in a different article: CreateWindowEx https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-createwindowexa

**Comment by hickeys** [comment]
I've checked in a fix for this issue. It should be published shortly. Thanks for catching this.

**Comment by krishty** [comment]
Looking great; thank you!
