### ISSUE TITLE
Support site comments on reference documentation pages

### ISSUE THREAD

**Issue by dend** [MicrosoftDocs/feedback#206]
# Idea Title

Reference documentation does not have comments.

## Issue Details

Easier for users to provide feedback for reference documentation if comments are enabled.

**Comment by mairaw** [comment]
Do we want to enable comments or integrated issues like we're doing for articles?

**Comment by dend** [comment]
@mairaw integrated issues. Given that we are moving everything to GitHub, it makes sense to follow the standard pattern.

**Comment by mairaw** [comment]
Is this a generic issue @dend? We've enabled comments on reference but we're still evaluating if it's worth having it or not.

**Comment by dend** [comment]
I can close it for now then 😄 Thanks @mairaw
