### ISSUE TITLE
Technet Subscription Page Not Working - Broken Link

### ISSUE THREAD

**Issue by paulbarrs** [MicrosoftDocs/feedback#2061]
I am on this page  - https://technet.microsoft.com/en-us/cc543196 and use the link to sign up to Technet Flash which takes me to this page - https://profile.microsoft.com/RegSysProfileCenter/ErrorPage.aspx?aspxerrorpath=/RegSysProfileCenter/pplogon.aspx

I am unable to sign up to Technet Flash

Paul.

**Comment by docs-product** [comment]
Please use the following link to sign up for the latest newsletter: https://aka.ms/msdev/dev_newsletter
