### ISSUE TITLE
Problems in TriggerCollection Members page

### ISSUE THREAD

**Issue by yuriy-look** [MicrosoftDocs/feedback#2062]
Two problems with https://docs.microsoft.com/en-us/previous-versions/visualstudio/design-tools/expression-studio-4/ff724858(v=expression.40) page:

1.  Link for the Add method is broken.

2.  The page contains a generic banner about checking the Microsoft Product Lifecycle.  But (a) this banner is not present on other pages of this class( at least those I happened to visit) and (b) it's not clear which product needs to be looked up in [Microsoft Product Lifecycle]( https://support.microsoft.com/en-us/lifecycle/selectindex).

**Comment by docs-product** [comment]
Thank you for the feedback! The content above is archived and is no longer updated.
