### ISSUE TITLE
No top-left menu bar and missing content

### ISSUE THREAD

**Issue by pwm812** [MicrosoftDocs/feedback#2063]
Hello, I have a problem.
On iphone7 with ios 10.2(14c92) , I can't see top-left menu bar on the url of http://docs.microsoft.com, and missing content in other pages, e.g. https://docs.microsoft.com/zh-cn/dotnet/.
![微信图片_20191021113635](https://user-images.githubusercontent.com/32897556/67175157-90018080-f3f7-11e9-9f5b-638cf62af81c.png)
![微信图片_20191021113645](https://user-images.githubusercontent.com/32897556/67175158-909a1700-f3f7-11e9-85cb-2278f955e967.png)

**Comment by pwm812** [comment]
![微信图片_20191021113635](https://user-images.githubusercontent.com/32897556/67175135-7829fc80-f3f7-11e9-811d-ace57c110500.png)

**Comment by mairaw** [comment]
Are you still seeing that issue @pwm812?

**Comment by pwm812** [comment]
yes

[image1.PNG]

P.g

在 2019年10月31日，14:20，Maira Wenzel <notifications@github.com<mailto:notifications@github.com>> 写道：


Are you still seeing that issue @pwm812<https://github.com/pwm812>?

―

**Comment by docs-product** [comment]
@pwm812 can you please update the iOS release, to make sure that you are using the latest browser version? We cannot reproduce the issue on an iPhone device.
