### ISSUE TITLE
Azure Rest API to get resources list(i.e. Name,Resource Type, Resource group & DIagnostics Status) under diagnostics settings in azure portal

### ISSUE THREAD

**Issue by shubham-tokalwad** [MicrosoftDocs/feedback#2068]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem** (if available).

**Link to article:**
I want azure rest api to get list of resources under diagnostics settings in azure portal, I have tried many rest api but i couldn't find accurate API for this. If there is multiple rest API to get this data that will be ok.
![qusetion](https://user-images.githubusercontent.com/56860340/67261534-b4746000-f4be-11e9-97af-bf02f5d7308b.png)

**Problem:**
What's wrong with the article?

**Comment by shubham-tokalwad** [comment]
Hello, waiting for response

**Comment by docs-product** [comment]
Thank you for the feedback! Because this question is not regarding docs.microsoft.com, we cannot address it in this forum. You can use the new [Q&A](https://docs.microsoft.com/answers) site to ask your question.
