### ISSUE TITLE
Please don't remove Visual Basic .NET from list

### ISSUE THREAD

**Issue by ashrafulislambd** [MicrosoftDocs/feedback#2070]
We love VB.NET too much. Nowadays we are missing it from various things like Unity, Xamarin etc. Though it can be used with Xamarin indirectly, you aren't still providing VB.NET support. Visual Basic has a lots of feature which we are missing in C#. Also always give documentation of every code in Visual Basic please.

Dear Microsoft,
If you remember that Visual Basic is the base of your organization. From old VB 1.0 to VB 6.0 and .NET what a revolution it got. But the you are putting focus more on C# than VB. But the idea of WinForms purely came from Visual Basic. Please don't stop support for VB.NET

**Comment by mairaw** [comment]
Adding @KathleenDollard

**Comment by docs-product** [comment]
Thank you for the feedback! Given that this issue is not related to docs.microsoft.com, we cannot address it in this forum.
