### ISSUE TITLE
Extensions link is not working under Changes in SSDT for visual studio 2019

### ISSUE THREAD

**Issue by v-saivp** [MicrosoftDocs/feedback#2071]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem** (if available).

**Link to article:**
https://docs.microsoft.com/en-us/sql/ssdt/download-sql-server-data-tools-ssdt?view=sql-server-ver15#changes-in-ssdt-for-visual-studio-2019

**Problem:**
Extensions link is not working under Changes in SSDT for visual studio 2019
https://docs.microsoft.com/en-us/==visualstudio/ide/finding-and-using-visual-studio-extensions

**Comment by mairaw** [comment]
Thanks @v-saivp! 
I've opened a PR to fix this: https://github.com/MicrosoftDocs/sql-docs/pull/3375

That documentation is open for contribution so you can also submit fixes when you encounter issues like this.

**Comment by v-saivp** [comment]
Will do. Thanks.

Best Regards
Sai Varun Polishetty
Microsoft Business Intelligence
Time Zone:  PST (US & Canada) (UTC -08:00)
Hours: 9 AM – 6 PM
Email: v-saivp@microsoft.com<mailto:v-saivp@microsoft.com>
Manager: Rizwan UL Moin Mohammed (v-momoin@microsoft.com<mailto:v-momoin@microsoft.com>)
[cid:image001.png@01D57D39.8A238850]
In case of any delay in response to your email or immediate assistance needed, kindly notify to the Operations Manager’s team for immediate attention. MT-BAP-OM-TA@microsoft.com<mailto:MT-BAP-OM-TA@microsoft.com>

**Comment by docs-product** [comment]
Closing the issue as the fix has been merged. Thank you @mairaw for your contribution!
