### ISSUE TITLE
Contributing.md in win32 documentation links to inaccessible articles.

### ISSUE THREAD

**Issue by KeyWorksRW** [MicrosoftDocs/feedback#2072]
In the MicrosoftDocs/win32 repository, the [contributing.md](https://github.com/MicrosoftDocs/win32/blob/docs/CONTRIBUTING.md) article has links to "Windows Authoring Guide" and "content quality checklist" with the suggestion to read those articles before submitting any document pull requests. However, those links are to the "https://review.docs.microsoft.com/en-us/" site which denies access to anyone with a standard Microsoft account.

The **contributing.md** article should either include information about how to upgrade an account to be able to access the two articles (if that's actually possible), or better, a copy of the articles should be placed in the actual repository with the link pointing to those articles. Since a user doesn't need a Microsoft account to be able to submit a Pull Request for the documentation set, it would make the most sense not to require a special account to ensure that any documentation changes fit within the Microsoft authoring guidelines.

**Comment by GrantMeStrength** [comment]
Thank you - the link was broken, so I fixed it. By design it requires the user to be signed in with an account. I agree there should be some better not-behind-the-sign-in view, and I will talk to the site team about this. Thanks again.
