### ISSUE TITLE
Power Query (M) and DAX Formual Language Pages

### ISSUE THREAD

**Issue by mebulmer** [MicrosoftDocs/feedback#2073]
Sometime recently, the Power Query M and DAX support pages (Functions, Expressions, Values, etc...) were updated and the "Left Hand Navigation" tree disappeared which makes it very difficult to navigate around to different function pages and find what you need.  The only way to navigate is to either hit the back button or go up to the website address and manually delete the last "section" such as https://docs.microsoft.com/en-us/powerquery-m/time-functions and delete "/time-functions" so that you can get back to the homepage and then go to the functions page and then select another function you want to view.  This makes it really time consuming.  The left hand navigation menu tree that was there made it very easy to navigate around and now that is gone.  Why was this removed?  PLEASE put it back.  It is really painful to navigate now. 

![image](https://user-images.githubusercontent.com/30474104/67419208-49985700-f59a-11e9-8a5e-562340a8f294.png)

**Comment by docs-product** [comment]
The menu should be showing up properly now. Thank you for your feedback!
