### ISSUE TITLE
Redis Cache GET 'Try it' does insert ResourceGroupName into URL

### ISSUE THREAD

**Issue by amunger** [MicrosoftDocs/feedback#2074]
**Describe the bug**
The "Try it" feature in the Redis GET document ends up with a URL that contains resourceGroups/%7BresourceGroupName%7D/ because the resource group name does not get inserted correctly as a parameter.

**To Reproduce**
1. Go to https://docs.microsoft.com/en-us/rest/api/redis/redis/get#code-try-0
2. Fill in the parameters, specifically resourceGroupName
3. Click Run
4. Check the URL

**Expected behavior**
the parameter entered for resourceGroupName should be in the URL

**Actual behavior**
%7BresourceGroupName%7D shows up where the parameter should be.

  "error": {
    "code": "ResourceGroupNotFound",
    "message": "Resource group '{resourceGroupName}' could not be found."
  }

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version 77.0.3865.120 (Official Build)

**Comment by rloutlaw** [comment]
@amunger We pushed a fix a couple of weeks ago that cleared up an issue where the value in the Try-It fields would be considered invalid, and not injected properly into the URL. Please re-try , and if the issue continues then reply here with a sample (not actual ) resrouceGroupName value so I can recreate.
