### ISSUE TITLE
What values are valid for scoringprofile in the search api?

### ISSUE THREAD

**Issue by sharpninja** [MicrosoftDocs/feedback#2075]
**Is your feature request related to a problem? Please describe.**
I am querying the `docs.microsoft.com/api/search` service and would like to know what are valid values for the `scoringprofile` parameter and what type of results do they provide?

**Describe the solution you'd like**
A list of valid values for `scoringprofile` and a description of their functionality.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by docs-product** [comment]
Hello and thank you for raising the question! The search API is not exposed to the public, and we cannot provide support on it as its not intended to be consumed by third-parties.
