### ISSUE TITLE
WHAT A USELESS PAGE!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by MicrosoftSUCKS69** [MicrosoftDocs/feedback#2077]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem** (if available).

**Link to article:**
Tell us where exactly a problem occurs.

**Problem:**
What's wrong with the article?

**Comment by sadadow** [comment]
Hi there,

What page are you referring to? We'd be happy to look into it.

**Comment by docs-product** [comment]
Given that no additional context was provided, closing the issue.
