### ISSUE TITLE
[error message feedback] provide feedback for GetDocumentsFromDHSFailed

### ISSUE THREAD

**Issue by tfosmark** [MicrosoftDocs/feedback#2078]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

**Problem:**
This message is neither clear nor actionable, and provides no link to additional detail. I have no idea if this is possibly a transient error or something I should take action on or alert anyone else.

**Log code info**
(This is auto filled, no need to modify)

| Severity   | Type   | Code   | Category   | File   | Message   |  Source  | Line   | Time   |
|------------|--------|--------|------------|--------|-----------|----------|--------|--------|
| Error | System | GetDocumentsFromDHSFailed |  |  | Getting documents from document hosting service failed with locale: en-us, depot name: Azure.azure-documents, branch name: release-ignite-vpn. Error: A task was canceled. | PublishToDocumentHostingServiceWithUploadingPackage | | 10/25/2019 19:43:13 |

**Link to report**
(This is auto filled, no need to modify)

[report url](https://opbuildstorageprod.blob.core.windows.net/report/2019/10/25/8257e7f2-de62-9622-af05-1281f54738ea/Commit/201910251918521715-release-ignite-vpn/workflow_report.html?sv=2016-05-31&sr=b&sig=5jP1nALB9Eo%2FlrgSu5CqMNquDFjS5wHonNneQVWPt8g%3D&st=2019-10-25T19%3A39%3A16Z&se=2019-11-25T19%3A44%3A16Z&sp=r)

**Comment by mairaw** [comment]
@tfosmark is this about the OPS error message?

**Comment by tfosmark** [comment]
Yes.

**Comment by mairaw** [comment]
Probably better to report that on the internal support channel on Teams. Do you know where that is at?

**Comment by tfosmark** [comment]
Yes, okay. I clicked the link in the build report and it brought me here.

Thanks for the response, Maira!

**Comment by docs-product** [comment]
@tfosmark if the issue still persists, please report it internally through the Docs Support channel.
