### ISSUE TITLE
Linkedin API v1 / v2 permissions transferal issue

### ISSUE THREAD

**Issue by paulsharratt0** [MicrosoftDocs/feedback#2079]
Linkedin forced all devs to switch to API v2 in June, we applied for access at that point and rewrote our integration to work with the new API. 5 months later we still don't have access. We're a production app in use by a number of users to schedule content to most social media platforms, except for Linkedin because the approval process is stalled.

I created a support ticket, which told me no one could talk about the API, and to create a stackoverflow question which linkedin staff would read. I created the question, which was deleted by the community who said (quite rightly) that customer support questions shouldn't be going through stackoverflow.

I'm hoping someone here can help, we're stuck in app review limbo on what should have been a simple transferal of permissions from v1 to v2. 

The app is called "Rivuu", the support case # that I created was 190926-004183, client ID is 75czbnnlekcrt3

**Comment by docs-product** [comment]
Thank you for the feedback! Because this is not related to docs.microsoft.com, we cannot address it in this forum.
