### ISSUE TITLE
https://mkaslann1.visualstudio.com/

### ISSUE THREAD

**Issue by MKaslan1** [MicrosoftDocs/feedback#208]
# Idea Title
$10.00

Be as descriptive as you can with your idea/bug report/question/suggestion.

## Issue Details

Add a detailed explanation of what is wrong or what you want implemented. Images and rich content is welcome!

**Comment by MKaslan1** [comment]
Turkey/Gaziantep

**Comment by dend** [comment]
Hello @MKaslan1 - the issue is not related to docs.microsoft.com, and therefore is closed.
