### ISSUE TITLE
Can't find SaxAppWizard by page discription.

### ISSUE THREAD

**Issue by xuhuoren** [MicrosoftDocs/feedback#2081]
### Background

Creating C++ Applications Using SaxAppWizard

### Problem

I can't find the SaxAppWizard by the page. Why not add a exact hyperlink on it ?

### Artical Link

[Creating C++ Applications Using SaxAppWizard](https://docs.microsoft.com/en-us/previous-versions/windows/desktop/ms763814(v=vs.85))

**Comment by docs-product** [comment]
Thank you for the feedback! The content below is archived for reference purposes and is no longer supported.
