### ISSUE TITLE
Referenced header file is empty

### ISSUE THREAD

**Issue by xuhuoren** [MicrosoftDocs/feedback#2082]
### Artical Link

[Create the Headers and Source Files for SaxJumpStart](https://docs.microsoft.com/en-us/previous-versions/windows/desktop/ms764683(v=vs.85))

### Problem

The content of header file is empty.

**Comment by docs-product** [comment]
Thank you for the feedback! This is content that is no longer supported, therefore we won't be able to make updates to it.
