### ISSUE TITLE
Don't fallback to transliteration when machine-translating

### ISSUE THREAD

**Issue by MSDN-WhiteKnight** [MicrosoftDocs/feedback#2083]
In localized machine-translated docs, in some cases identifiers are translated incorrectly, because translation program transliterates them. If translation program can't translate something, it should leave it as English, not transliterate. For example:

In [C++ Docs](https://docs.microsoft.com/ru-ru/cpp/mfc/reference/cacceleratedeceleratetransition-class?view=vs-2019):

**CAccelerateDecelerateTransition Class** translated as:

>Класс Какцелератедецелератетранситион

should be:

>Класс CAccelerateDecelerateTransition

In [.NET Docs](https://docs.microsoft.com/ru-ru/dotnet/framework/data/transactions/using-system-transactions-in-aspnet#enable-distributedtransactionpermission-in-aspnet):

>Чтобы изменить файлы политики, добавьте элемент секуритикласс

should be 

>Чтобы изменить файлы политики, добавьте элемент SecurityClass 

Because this issue is with many docs sets, probably it's a bug in translation software.

**Comment by mairaw** [comment]
The way that machine translation works, we need to lock the word from translation either by using backticks or the new no-loc feature. 

I think you can file issues for the articles where you find the translaion issues and the loc team can work with us to block those terms. Would that work @JasonCard?

**Comment by MSDN-WhiteKnight** [comment]
>I think you can file issues for the articles where you find the translaion issues and the loc team can work with us to block those terms.

I can, but in C++ docs (and probably some other docs sets), there're a lot of instances where identifiers in headings, links etc. are not backticked. Prevously the system was smart enough not to translate them. Now random parts of them are garbled, and manually reporting all of them would be too hard. Some software support would be needed to fix this. For .NET Docs though there are only few instances of this (i hope) so i can report them manually or just submit pull request myself to add backticks where needed.

**Comment by JasonCard** [comment]
Hi @mairaw, @MSDN-WhiteKnight, 
Our Machine Translation (MT) engine was recently changed, so I believe we should be able to get this issue fixed in the new MT engine as the previous MT engine used. I agree it would not be efficient to use code block or non-loc feature for every instances of identifiers such as class and element names. 
Reassigning this issue to @DavidPrio for follow up. 
+ cc @ishasahni1

**Comment by CeciAc** [comment]
Hello, @MSDN-WhiteKnight,
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @MSDN-WhiteKnight,

We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/ru-ru/cpp/mfc/reference/cacceleratedeceleratetransition-class?view=vs-2019 and https://docs.microsoft.com/ru-ru/dotnet/framework/data/transactions/using-system-transactions-in-aspnet#enable-distributedtransactionpermission-in-aspnet

Also, Loc Issue #135603 was opened by @JasonCard to follow this issue.

Kind regards,
Microsoft DOCS International Team

**Comment by JasonCard** [comment]
Hi @MSDN-WhiteKnight,
We are currently checking if our new MT engine could support the recognition of these identifiers and leave them in English. Tracking in [Loc Issue 135603](https://ceapex.visualstudio.com/CEINTL/_workitems/edit/135603) and will update.
cc @mairaw @CeciAc @ishasahni1

**Comment by JasonCard** [comment]
We have discussed this issue internally and our new MT engine plan to address this issue, but no ETA at this time. Closing this issue for now.
