### ISSUE TITLE
Wrong link to "using c# sdk"

### ISSUE THREAD

**Issue by M-A-JO** [MicrosoftDocs/feedback#2085]
**Describe the bug**
On https://docs.microsoft.com/en-us/azure/cognitive-services/luis/ there is a wrong link to "using c# sdk". It redirects you to "using python library" instead of c#.

**To Reproduce**
1. Go to 'https://docs.microsoft.com/en-us/azure/cognitive-services/luis/'
2. Click on 'using c# sdk' under quickstart

**Expected behavior**
Redirection to using c# sdk

**Desktop (please complete the following information):**
 - OS: win-10
 - Browser chrome, IE, edge, ...

**Comment by docs-product** [comment]
Closing as there is a related issue being tracked on the content side.
