### ISSUE TITLE
Learning Module not working: Create serverless logic with Azure Functions 

### ISSUE THREAD

**Issue by SebastianSchuetze** [MicrosoftDocs/feedback#2086]
**Describe the bug**
I was going through the module ["Create serverless logic with Azure Functions" on Microsoft Learn](https://docs.microsoft.com/en-us/learn/modules/create-serverless-logic-with-azure-functions/3-create-an-azure-functions-app-in-the-azure-portal?pivots=powershell). There I should create a Sandbox, which was done successfully

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'https://docs.microsoft.com/en-us/learn/modules/create-serverless-logic-with-azure-functions/3-create-an-azure-functions-app-in-the-azure-portal?pivots=powershell'
2. Click on 'Activate Sandbox' and follow instructions and go to the Sandbox Azure Tenant
3. Follow the tutorial for creating a serverless function on the consumption plan
4. see that you get denied the creation of the resources by a policy

The following policy error is posted:
```json
{
  "telemetryId": "e531a41c-ef4d-441e-ad99-d63f023825b6",
  "bladeInstanceId": "Blade_c922e6cf0d9d40c2964796537c243e49_6_0",
  "galleryItemId": "MyGalleryItem",
  "createBlade": "DeployToAzure",
  "code": "InvalidTemplateDeployment",
  "message": "The template deployment failed because of policy violation. Please see details for more information.",
  "details": [
    {
      "code": "RequestDisallowedByPolicy",
      "target": "ASP-Learn9ba362f406ed4d6fa0af9b5381-8ba3",
      "message": "Resource 'ASP-Learn9ba362f406ed4d6fa0af9b5381-8ba3' was disallowed by policy. Policy identifiers: '[{\"policyAssignment\":{\"name\":\"AppService-SKU\",\"id\":\"/providers/Microsoft.Management/managementGroups/triplecrown2/providers/Microsoft.Authorization/policyAssignments/7bb64c0aa90247de8b4491c3\"},\"policyDefinition\":{\"name\":\"AppService-SKU\",\"id\":\"/providers/Microsoft.Management/managementGroups/604c1504-c6a3-4080-81aa-b33091104187/providers/Microsoft.Authorization/policyDefinitions/e790fdfe-5672-403f-9a29-e1aa564ac680\"}}]'.",
      "additionalInfo": [
        {
          "type": "PolicyViolation",
          "info": {
            "policyDefinitionDisplayName": "AppService-SKU",
            "evaluationDetails": {
              "evaluatedExpressions": [
                {
                  "result": "True",
                  "expressionKind": "Field",
                  "expression": "type",
                  "path": "type",
                  "expressionValue": "Microsoft.Web/serverfarms",
                  "targetValue": "Microsoft.Web/serverFarms",
                  "operator": "Equals"
                },
                {
                  "result": "False",
                  "expressionKind": "Field",
                  "expression": "Microsoft.Web/serverfarms/sku.name",
                  "path": "sku.name",
                  "expressionValue": "Y1",
                  "targetValue": [
                    "F1",
                    "D1"
                  ],
                  "operator": "In"
                }
              ]
            },
            "policyDefinitionId": "/providers/Microsoft.Management/managementGroups/604c1504-c6a3-4080-81aa-b33091104187/providers/Microsoft.Authorization/policyDefinitions/e790fdfe-5672-403f-9a29-e1aa564ac680",
            "policyDefinitionName": "e790fdfe-5672-403f-9a29-e1aa564ac680",
            "policyDefinitionEffect": "Deny",
            "policyAssignmentId": "/providers/Microsoft.Management/managementGroups/triplecrown2/providers/Microsoft.Authorization/policyAssignments/7bb64c0aa90247de8b4491c3",
            "policyAssignmentName": "7bb64c0aa90247de8b4491c3",
            "policyAssignmentDisplayName": "AppService-SKU",
            "policyAssignmentScope": "/providers/Microsoft.Management/managementGroups/triplecrown2",
            "policyAssignmentParameters": {}
          }
        }
      ]
    }
  ]
}
```

**Expected behavior**
The resource should get created as expected

**Screenshots**
![image](https://user-images.githubusercontent.com/7256168/67686958-ca3ec500-f997-11e9-9852-45ef705d8b49.png)
![image](https://user-images.githubusercontent.com/7256168/67687064-02de9e80-f998-11e9-9baa-24a25cd036a8.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 (Version 1903, Build 18362.449)
 - Browser Chrome
 - Version 78.0.3904.70 (Official Build) (64-bit)

**Comment by SebastianSchuetze** [comment]
The same seems to apply for the following module:
https://docs.microsoft.com/en-us/learn/modules/execute-azure-function-with-triggers/4-create-timer-trigger?pivots=powershell

I can work around this by choosing the F1 or D1 app service plan, but I think the problem would appear on any module for Azure Functions that suggests using the consumption plan.

**Comment by onetalltree** [comment]
I'm having the same problem

**Comment by sadadow** [comment]
Thanks for providing this feedback. We have escalated to the appropriate teams and should resolve this issue shortly.

**Comment by yunyunyunyun** [comment]
@adrianstevens or @jboeshart , can you help check the content instruction?

**Comment by onetalltree** [comment]
this problem seems to be pervasive across multiple exercises and modules

**Comment by jboeshart** [comment]
Thanks for the heads up on this. Currently investigating...

**Comment by jboeshart** [comment]
@SebastianSchuetze, @onetalltree if you have a chance can you give it another try? This should be fixed, you should now be allowed to create consumption tier Functions in our sandbox environment. Apologies for the issues here, but we appreciate you bringing this to our attention, so thank you!

**Comment by onetalltree** [comment]
It seems to be working ... I have done several exercises today and they all work now. Thanks!

**Comment by jboeshart** [comment]
Great, will close this for now but let us know if this pops up again (it shouldn't). Thanks for visiting Microsoft Learn!

**Comment by yunyunyunyun** [comment]
@adrianstevens
