### ISSUE TITLE
WM_PARENTNOTIFY formatting and content issues

### ISSUE THREAD

**Issue by krishty** [MicrosoftDocs/feedback#2088]
WM\\_PARENTNOTIFY https://docs.microsoft.com/en-us/previous-versions/windows/desktop/inputmsg/wm-parentnotify

1. Title (not heading, actual title) has a backslash in it
2. actual text **[!Important]** in 3rd paragraph
3. Contradiction: *Parameters -> LOWORD(wParam) -> WM_CREATE -> Meaning*: *“lParam is a handle to the child window”* contradicts *“Contains the point location of the pointer”*; it was way more clear in the old version (https://docs.microsoft.com/en-us/previous-versions/ms632638(v%3Dvs.85))

**Comment by GrantMeStrength** [comment]
Thanks for bringing this to my attention - although this content is in the section that we don't update very often, I've gone in and made the suggestion corrections. Hopefully they'll show up soon! Thanks again.
