### ISSUE TITLE
DlgDirListA function: Wrong paths; probably formatting issues

### ISSUE THREAD

**Issue by krishty** [MicrosoftDocs/feedback#2089]
DlgDirListA function: https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-dlgdirlista

The paths throughout the article are wrong.

E.g. first paragraph on `lpPathSpec` parameter: *a UNC name (for example, \\ machinename sharename)*. I’m pretty sure UNC paths are in the form (I hope markup does not eat this up) *\\\\machinename\\sharename* instead.

The third paragraph on `lpPathSpec` is screwed up (wildcard character should probably be \* instead of nothing?!)

**Comment by GrantMeStrength** [comment]
Thank you! Corrections have been submitted.

**Comment by krishty** [comment]
When will the changes show? Because the way it is right now, it still cannot be right

![lppathspec](https://user-images.githubusercontent.com/51880096/91843661-68558880-ec56-11ea-9542-b9d0ac55eaf0.png)
