### ISSUE TITLE
Dead links in Dialog Box Programming Considerations

### ISSUE THREAD

**Issue by krishty** [MicrosoftDocs/feedback#2090]
**Dialog Box Programming Considerations:** https://docs.microsoft.com/en-us/windows/win32/dlgbox/dlgbox-programming-considerations

In the overview, all links to *WS_\** and *WM_\** are empty (just a plain https://docs.microsoft.com/en-us/windows/).

Same for almost all links to *WS_TABSTOP* except for the middle of the article.

All links under **Radio Buttons and Check Boxes** are dead.

Same for all links under **List Boxes, Combo Boxes, and Directory Listings**.

Apart from that, the article is excellent and helped me a lot!

**Comment by GrantMeStrength** [comment]
Thank you for reporting this. It's finally been fixed!

**Comment by krishty** [comment]
Only some have been fixed; the links in the **Radio Buttons and Check Boxes** section and in the **List Boxes, Combo Boxes, and Directory Listings** section are still dead for me.
