### ISSUE TITLE
some anchors are not working after translated 

### ISSUE THREAD

**Issue by zeratul1990** [MicrosoftDocs/feedback#2092]
**Describe the bug**
it happens in chinese version,i don't know if the same thing would happen in other language with special letters.

some docs are translated by machine,and the anchors are translated too.the translated anchors don't behave correctly.
if an anchor is translated into chinese ,it just shows the same amount of - instead of chinese letters.many words have the same length after translated,for example,the fields/properties/methods,when those words get translated they are all two letters,so they all become #-- ,then the anchor failed.

**To Reproduce**
1. check out this page: https://docs.microsoft.com/zh-cn/dotnet/api/system.type?view=netframework-4.8
i got a screenshot below
you can compare it with the english version: https://docs.microsoft.com/en-us/dotnet/api/system.type?view=netframework-4.8

**Expected behavior**
the anchors are translated , and the translate results are not legal anchors.
maybe the auto translation should avoid the anchors,then the page should be alright

**Screenshots**
![image](https://raw.githubusercontent.com/zeratul1990/pics/master/20191029095633.png)
if i didn't paste the pic correctly,u can find it here https://github.com/zeratul1990/pics

**Comment by mairaw** [comment]
Thanks for reporting this issue @zeratul1990. @JasonCard @TianqiZhang who could look into this? I can repro the broken behavior.

**Comment by mairaw** [comment]
#log-suggestion @mairaw

**Comment by JasonCard** [comment]
Hi @zeratul1990, 
Thank you for reporting this issue.
I've opened IcM [Incident 155684465](https://icm.ad.msft.net/imp/v3/incidents/details/155684465/home) to follow up.
cc @mairaw @TianqiZhang @bodhigautam

**Comment by JasonCard** [comment]
Hi @zeratul1990, 
This is issue is now fixed.
Please let us know if you still find any issues.

**Comment by zeratul1990** [comment]
well, as far as i can see,the "examples" and "remarks" are not working as they are still "#--","Applies to" and "Thread Safety" are replaced by "-" ,though acting well .maybe the page is cached,i will check out this later



the replacement could happen in japanese version(注釈),korean version(예제),russian version(Примеры),german version(Gilt für:),french version(S’applique à),Czech version(Příklady),and many other versions,but of course in most cases nothing would happen in romance language versions because only several characters are replaced and the full anchor will not conflict with each other easily.maybe most problems are in chinese version,japanese version,korean version,russian version,which are full of special characters

**Comment by JasonCard** [comment]
@zeratul1990 Thank you very much for checking and reporting these details. I've requested for further investigation on this and update.

**Comment by JasonCard** [comment]
Hi @zeratul1990,
Thank you again for reporting this issue.
The issues are now fixed:
https://docs.microsoft.com/zh-cn/dotnet/api/system.type?view=netframework-4.8#examples  
Please let us know if you still find any issues.
