### ISSUE TITLE
No control works

### ISSUE THREAD

**Issue by aureole82** [MicrosoftDocs/feedback#2095]
None of the controls of the site header reacts on touch:
* Menu doesn't open
* No bookmark, no sharing, no dark theme

![wp_ss_20191116_0002](https://user-images.githubusercontent.com/4819891/68992089-e9c66080-0866-11ea-8345-df69fa28618f.png)
![wp_ss_20191116_0003](https://user-images.githubusercontent.com/4819891/68992090-e9c66080-0866-11ea-8260-df51d0cba5b4.png)
![wp_ss_20191116_0004 1](https://user-images.githubusercontent.com/4819891/68992091-e9c66080-0866-11ea-9b36-679b8b626dfc.png)

**Comment by aureole82** [comment]
Sorry, I am unable to attach images because GitHub discriminates older smartphones.

**Comment by aureole82** [comment]
Did you know, that I can't edit my own post?

**Comment by aureole82** [comment]
So, here's some "text" you might consider instead:
Microsoft Edge 40.15254.590.0
Microsoft EdgeHTML 15.15254

**Comment by docs-product** [comment]
@aureole82 could you please give us more details on the device being used and the OS version?

**Comment by aureole82** [comment]
Model: Microsoft Lumia 950
Software: Windows 10 Mobile
RAM: 3 GB
Version: 1709
OS Build: 10.0.15254.597
Firmware Revision: 01078.00053.16236.35026
Hardware Revision: 2.1.1.2

**Comment by docs-product** [comment]
Thank you for the feedback! This is not a device that we support. The official support end-date for Windows 10 Mobile is December 10, 2019 ([see details](https://support.microsoft.com/en-us/lifecycle/search?alpha=Windows%2010%20Mobile)).

**Comment by aureole82** [comment]
So, there are still 10 days left to fix it. :-)

No, I didn't request to support my old Windows Phone. The request was about the Edge inside it:
Microsoft Edge 40.15254.590.0
Microsoft EdgeHTML 15.15254
Where did you announce your Microsoft Docs end of support for this browser?
