### ISSUE TITLE
Add team specific Wikis to Azure DevOps

### ISSUE THREAD

**Issue by qichenxu** [MicrosoftDocs/feedback#2098]
**Is your feature request related to a problem? Please describe.**
When using Azure DevOps the Wikis are only available at the project level. Any member of the project could modify and read all the project wikis.

**Describe the solution you'd like**
It would be nice to have team level wikis, similar to boards and backlogs where only dev team members can have access to (not the whole project members). 

**Describe alternatives you've considered**
Add security settings for wikis on a page by page basis. Only invited members can read or contribute the page, rather than one general security setting for all pages within the same project.

**Additional context**

**Comment by docs-product** [comment]
Thank you for the feedback! Given that this is not related to docs.microsoft.com, we cannot address the issue in this forum.
