### ISSUE TITLE
What does the `bool` return value indicate on `CloudStorageAccount.CreateIfNotExistsAsync()` (and friends)?

### ISSUE THREAD

**Issue by tlycken** [MicrosoftDocs/feedback#210]
On [this page](https://docs.microsoft.com/en-us/dotnet/api/microsoft.windowsazure.storage.table.cloudtable.createifnotexistsasync?view=azure-dotnet#Microsoft_WindowsAzure_Storage_Table_CloudTable_CreateIfNotExistsAsync) (and a bunch of others documenting the same set of classes), the `Returns` declaration just says

> A `Task<T>` of type `bool` that represents the asynchronous operation.

It would be much more helpful if the documentation would also specify in what cases the methods return `true` or `false`. For example, in which of the following cases would the method above return `true`, and for which ones `false`?

* Everything went OK, the table didn't exist before and was created now
* Everything went OK, the table existed before, so nothing more was done now
* Listing tables went OK, the table didn't exist before but something went wrong when trying to create it
* Something went wrong when listing tables

Looking at the `bool` that's returned by these methods, is there any way I can know whether the table exists? Is there any way I can know that I need to try again? The current docs don't help me figure that out.

**Comment by dend** [comment]
@mairaw I believe this is a content issue. Can you help me move it to the correct repo?

**Comment by mairaw** [comment]
@dend indeed looks like a content issue but this is Azure SDK. Not sure who owns it right now. @erickson-doug is listed as the owner.

**Comment by dend** [comment]
@mmacy @twitchax for visibility on the issue.

**Comment by mmacy** [comment]
@tamram for visibility

**Comment by tlycken** [comment]
FWIW, I got here from the "feedback" link by the documentation page. If it points to the wrong place, might be worthwhile looking into fixing that too :)

**Comment by mairaw** [comment]
That's the right spot @tlycken. However, when we identify that the issue being reported is a content issue and not a general site feedback, we try to move the issue to the associated content repo.

**Comment by tamram** [comment]
@tlycken - Thanks for your feedback, you raise a good point. We need to document what the return value for the method means in terms of behavior.

For your own purposes, the asynchronous method always returns the same type as the synchronous method, but as a generic type of a Task object. See https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.task-1 for more information about the Task object.

So the behavior for CloudTable.CreateIfNotExistsAsync is the same as for CloudTable.CreateIfNotExists. That behavior is that the method returns True if the table was created, and False if it was not (that is, if it already exists). If an error occurs, it throws an exception.

@mirobers FYI.

**Comment by tlycken** [comment]
@tamram Thanks for clarifying! :)

**Comment by tamram** [comment]
#please-close

**Comment by jklaus** [comment]
#please-address in the documentation .. still don't see a resolution to this in the assembly's comments nor in the [man page](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.table.cloudtable.createifnotexistsasync?view=azure-dotnet)
