### ISSUE TITLE
Misleading page title

### ISSUE THREAD

**Issue by Errel** [MicrosoftDocs/feedback#2105]
This page is titled Errors 1 - 999.
It actually lists -2 - 999
This wasted 10 minutes of my life. Thanks.

https://docs.microsoft.com/en-us/previous-versions/sql/sql-server-2008-r2/cc645611%28v%3dsql.105%29

**Comment by docs-product** [comment]
Thank you for the feedback! The page you linked to is no longer supported and is not updated.
