### ISSUE TITLE
StringBuilder.AppendFormat doesn't show up as a link on the String.Format page

### ISSUE THREAD

**Issue by GenesisFR** [MicrosoftDocs/feedback#211]
On the "String.Format Q & A" section of the [String.Format](https://docs.microsoft.com/en-us/dotnet/api/system.string.format?view=netframework-4.7.1#stringformat-q--a) page, the StringBuilder.AppendFormat method doesn't show up as a link while Console.WriteLine does.

I tried both on Win10 x64 with Microsoft Edge 41.16299.248.0, Firefox 58.0.2 and Chrome 64.0.3282.186, same problem.

There's also a typo at "The use of mutiple" at the bottom of the screenshot below:
![image](https://user-images.githubusercontent.com/3614449/37280354-e2d129e0-25c3-11e8-8373-23976cc4ddbd.png)

**Comment by mairaw** [comment]
Thank you for reporting this @GenesisFR and @svick for the fix. It's fixed now. 

This issue can be closed. (I don't have write permissions to do it)
