### ISSUE TITLE
unable to use "Submit Feedback" to submit feedback

### ISSUE THREAD

**Issue by onetalltree** [MicrosoftDocs/feedback#2111]
[https://docs.microsoft.com/en-us/learn/modules/execute-azure-function-with-triggers/4-create-timer-trigger?pivots=csharp](url)

![Annotation 2019-10-31 210032](https://user-images.githubusercontent.com/1093148/68001508-9080ef00-fc21-11e9-8cbf-1a372f6e3c78.png)

**Comment by sadadow** [comment]
Hi @onetalltree,

Thanks for reporting this. We are looking into this issue now and will get back to you shortly.

**Comment by sadadow** [comment]
Hi @onetalltree This has been fixed now. We appreciate you helping to submit feedback and making the Learn platform better!
