### ISSUE TITLE
New Feature - Collections

### ISSUE THREAD

**Issue by krisrajz** [MicrosoftDocs/feedback#2113]
Kudos to MicroSoft for the constant endeavour on updating learning portal with new features such as Bookmarks, Collections which makes learning more organized and interesting!

**Comment by sadadow** [comment]
Thanks @krisrajz . We appreciate your awesome feedback and will pass the kudos on to the rest of our team! Thanks for helping us to make Learn better =)

**Comment by docs-product** [comment]
Thank you for the shout-out, @krisrajz!
