### ISSUE TITLE
Sandbox and other issues in Azure fundamentals training on Microsoft Learning

### ISSUE THREAD

**Issue by azure-user** [MicrosoftDocs/feedback#2114]
I've started Azure fundamentals training on Microsoft Learning and run into a problem accessing the sandbox in the following module: https://docs.microsoft.com/en-us/learn/modules/welcome-to-azure/4-exercise-create-website. It told me that sandbox is temporarily not available, at next attempt it told me that I was not able to access the sandbox and could appeal. I clicked on appeal button and waited for several days and then got the following message on that page:
"We have reviewed your appeal and determined that your account has violated our Terms of Use. Your sandbox access will not be reinstated. However, you can continue to access Microsoft Learn's training content. Many module exercises can be completed using your own Azure subscription, but charges may apply, and you may need to modify the instructions to work with your subscription."

My account was recently created, I've never use the sandbox before and did not violate Term of Use. I would expect more clear information about what is wrong, because it was not clear what exactly was wrong from very beginning and what appeal process is.  Could the sandbox be enabled for my account (diakova@mail.ru)?

I see that that entire module could not be competed, because of this issue on this exercise using the sandbox and this affects on training progress.
Also I tried to report this case directly on https://docs.microsoft.com/en-us/learn/modules/welcome-to-azure/4-exercise-create-website using "Report feedback" form, but constantly getting "Something went wrong. Please try again". 

Desktop 
 - OS: MacOS 10.15.1
 - Browsers: Chrome 78.0.3904.70, Safari 13.0.3

**Comment by sadadow** [comment]
Hi there,

Thanks for letting us know about this. We are escalating to the appropriate team and hope to resolve your issue shortly. Thank you for your patience and understanding.

**Comment by yunyunyunyun** [comment]
hi @azure-user , sorry for your trouble. Can you give me your email address so I can escalate to our team to investigate your case again?

**Comment by azure-user** [comment]
Hi, @yunyunyunyun 
it was in my initial post - diakova@mail.ru
Thank you!

**Comment by yunyunyunyun** [comment]
Hey @azure-user , my team has investigated your case and approved your appeal. You should be able to activate sandbox now. Please try again and let me know if that works.

**Comment by azure-user** [comment]
<img width="981" alt="Screen Shot 2019-11-04 at 10 12 56 PM" src="https://user-images.githubusercontent.com/57276624/68175859-9a239300-ff50-11e9-8f8d-f037b3e1e851.png">
Got the following message:
"Unauthorized sandbox use detected. Your sandbox access has been removed.
The sandbox may only be used to complete training on Microsoft Learn. Use for any other reason is prohibited, and may result in permanent loss of access to the sandbox. Please review our Terms of Use.
If you believe this is an error, please submit an appeal."

**Comment by yunyunyunyun** [comment]
Looks like you hit some bug. We tried to unblock you again today, can you try again? Sorry for the trouble.

**Comment by azure-user** [comment]
Hi, @yunyunyunyun 
thank you for looking into my case. It works like a charm now. I confirm that a sandbox has been created and passed to the next step.
Hopefully it will be automatically deactivated.

**Comment by C3st0** [comment]
Hi there,
Facing the same issue, on the "Create a website hosted in Azure" training as well. Here is my message, it does not allow to appeal: 

"Unauthorized sandbox use detected. Your sandbox access has been removed.
The sandbox may only be used to complete training on Microsoft Learn. Use for any other reason is prohibited, and may result in permanent loss of access to the sandbox. Please review our Terms of Use."

My email address is "cesto ( a) hotmail". Extentions is ".com" (I am carefull not to provide my email in plain text).

I have enrolled for an exam this week (AZ-900) and really need to be able and practive before. Thanks for your support.

**Comment by Vic40k** [comment]
Same problem.

**Comment by jlhuo** [comment]
My company require me to finish this Azure fundamental training https://docs.microsoft.com/en-us/learn/paths/azure-fundamentals/ before the end of this month. However, I don't know why my sandbox use has been suspended. Can you guys approve my appeal as soon as possible? My email JUNLI272@towerswatson.com. Thanks a lot.

**Comment by amariant** [comment]
Dear Team,

I faced the same issue during the preparation for AZ-304. Is it possible to activate the sandbox for sheff.10@mail.ru?

**Comment by maximsmd** [comment]
Currently undertaking a training and it seems i have hit the dead end to the ongoing issue. Is there a way to assist in resolving this issue as it seems the learn sandbox is also deactivated for my account. I do not know if this is a general issue or a form or bug from my account

![image](https://github.com/user-attachments/assets/5e884466-994c-4d76-b7c4-0aef3f183488)

Is there a form of help I can get in regard to this
