### ISSUE TITLE
 "Unauthorized Sandbox use detected. Your sandbox has been terminated."

### ISSUE THREAD

**Issue by rng9** [MicrosoftDocs/feedback#2115]
I encountered the error that unauthorized sandbox use was detected and that my sandbox was terminated. I submitted an appeal 3 days ago but I am still unable to access to Learn Sandbox.

Account: rob.goldfinger@outlook.com

**Comment by rng9** [comment]
I can't open a support issue issue on docs.microsoft.com. When reporting feedback I get the error 'something went wrong. Please try again.'

**Comment by sadadow** [comment]
Hi Rob, 

Sorry to hear that your sandbox usage was terminated incorrectly due to unauthorized usage. Thanks for submitting your appeal. We will have our team look into your case and see if we can approve your appeal shortly. We apologize for the inconvenience.

**Comment by yunyunyunyun** [comment]
Hi Rob, 
we have approved your appeal. Please try again let us know if there's still any issue.

**Comment by rng9** [comment]
It works! Thank you very much!
