### ISSUE TITLE
Where's the screen where partners can view and create support tickets ?

### ISSUE THREAD

**Issue by bc-109** [MicrosoftDocs/feedback#2119]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem** (if available).

**Link to article:**
Tell us where exactly a problem occurs.

**Problem:**
What's wrong with the article?

**Comment by bc-109** [comment]
I submitted this comment from the following page : 
https://docs.microsoft.com/fr-fr/partner-center/

**Comment by bc-109** [comment]
I am on a documentation site. I do not want documentation. I want the site real with features. What a mess !

**Comment by bc-109** [comment]
I am on this site :
https://partner.microsoft.com/en-us/support
I click on "submit an incident"
Then, I am forwarded to the documentation site : 
https://docs.microsoft.com/fr-fr/partner-center/
I do not want to read a doc. I want to submit an incident about partnership. But not an incident about the documentation, because I never wanted to b redirected to the documentation site...

**Comment by docs-product** [comment]
@bc-109 - thank you for the feedback! Because this is not related to functionality on docs.microsoft.com, we cannot address the issue within this forum.
