### ISSUE TITLE
Edit links in .Net API reference do not work 

### ISSUE THREAD

**Issue by svick** [MicrosoftDocs/feedback#212]
Edit links in .Net API reference do not work. For example, on [the page for `Int32`](https://docs.microsoft.com/en-us/dotnet/api/system.int32?view=netframework-4.7.1), the Edit link points back to the same page (https://docs.microsoft.com/en-us/dotnet/api/system.int32?view=netframework-4.7.1), when it should link to https://github.com/dotnet/docs/blob/master/xml/System/Int32.xml.

**Comment by dend** [comment]
Thanks for the report @svick - investigating.

**Comment by mairaw** [comment]
Thanks for the reporting the issue @svick. This is now fixed.

**Comment by dend** [comment]
Closing as it is fixed.
