### ISSUE TITLE
Xamarin Profiler 1.6.13 and 1.6.12 Windows download links not working.

### ISSUE THREAD

**Issue by mizukame** [MicrosoftDocs/feedback#2121]
**Links :**
https://docs.microsoft.com/en-us/xamarin/tools/profiler/release-notes/1.6/1.6.13
https://docs.microsoft.com/en-us/xamarin/tools/profiler/release-notes/1.6/1.6.12

**Problem:**
When clicking on the link to download the Xamarin Profiler I receive the following message.

> The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.
> 
> /profiler/XamarinProfiler.Windows.Installer.1.6.12-26.msi not found

> The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.
> 
> /profiler/XamarinProfiler.Windows.Installer.1.6.13-11.msi not found

Also on a side note:

The following link points the user to a very old version of the Xamarin profiler:

https://docs.microsoft.com/en-gb/xamarin/tools/profiler/?tabs=windows

Under the Download and Install section for Windows, version 1.6.1 is served.

**Comment by conceptdev** [comment]
Thanks for highlighting this issue. I've passed it on to the engineering team, and hope to be able to update the docs shortly with working links.

**Comment by conceptdev** [comment]
Thanks again, all the links have been updated. Turns out, the Windows version is not tracking the version shipped on Mac, the latest Windows version is 1.6.10, so the links have all been updated to point to that location.

#please-close

**Comment by mizukame** [comment]
Thank you very much for the assistance. =)
