### ISSUE TITLE
404 errors for python Reference documents

### ISSUE THREAD

**Issue by peterychang** [MicrosoftDocs/feedback#2123]
**Describe the bug**
Multiple pages results in 404 errors in the Python Reference documents. In particular many of the documents pertaining to azure.keyvault

These pages were accessible on Nov 5, and were no longer available as of Nov 6.

**To Reproduce**
1. Go to https://docs.microsoft.com/en-us/python/api/?view=azure-python
2. Click on `azure-keyvault`

Furthermore, documentation for `KeyVaultClient` and related pages (`SecretBundle`, `SecretItem`, `KeyId`, etc) all result in 404

**Comment by Dr-Irv** [comment]
Same thing for https://docs.microsoft.com/en-us/python/api/azure-mgmt-servermanager/index?view=azure-python

I.e., click on `azure-mgmt-servermanager` and you get an error message

**Comment by docs-product** [comment]
Thank you for the feedback - the index should be refreshed and there should be no more 404 links.
