### ISSUE TITLE
NMHDR Structure: in the syntax section, the type of idFrom member is wrong

### ISSUE THREAD

**Issue by jmairboeck** [MicrosoftDocs/feedback#2128]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem** (if available).

**Link to article:**
https://docs.microsoft.com/en-us/windows/win32/api/richedit/ns-richedit-nmhdr

**Problem:**
In the Syntax section, the type of the second member `idFrom` is displayed as `UINT`. The correct type would be `UINT_PTR`.

The Members section shows the correct type.

**Comment by GrantMeStrength** [comment]
Looking at the header file, the syntax block is correct, but the description is incorrect:

typedef struct _nmhdr
{
	HWND	hwndFrom;
	UINT	idFrom;
	UINT	code;
} NMHDR;
#endif	// !WM_NOTIFY 

Thanks for letting us know something was wrong!
