### ISSUE TITLE
Instance methods from object shouldn't show on static classes

### ISSUE THREAD

**Issue by mairaw** [MicrosoftDocs/feedback#213]
Originally reported by @svick at https://github.com/dotnet/docs/issues/4577

API reference for static classes includes instance methods inherited from `object`. They technically do exist on those types (since static classes are actually abstract sealed classes that derive from `object`), but cannot be used in any reasonable way, so I think they shouldn't be shown in API reference.

For example, look at `Console`. Its [list of methods on docs.MS](https://docs.microsoft.com/en-us/dotnet/api/system.console?view=netframework-4.7.1#Methods) contains methods like `GetHashCode()` or `GetType()`:

![](https://user-images.githubusercontent.com/287848/37156823-715547d0-22e7-11e8-8a3a-55dd1e31ed7a.png)

Compare this with [MSDN](https://msdn.microsoft.com/en-us/library/system.console(v=vs.110).aspx#Anchor_3), where these methods are not shown:

![](https://user-images.githubusercontent.com/287848/37156923-b087473c-22e7-11e8-8e2c-7a2e1be31e17.png)

---

Opened internal bug #1203839. Marked as blocking since behavior is correct on MSDN.

**Comment by dend** [comment]
This has been addressed, thank you for the feedback!
