### ISSUE TITLE
Appsource Spelling Issue

### ISSUE THREAD

**Issue by AtomicCons** [MicrosoftDocs/feedback#2133]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem** (if available).

**Link to article:**
https://appsource.microsoft.com/en-us/marketplace/apps?page=1&src=office&industry=government

**Problem:**
More apps for government is spelled wrong at the bottom of the page. 
![image](https://user-images.githubusercontent.com/22971111/68434218-b3595900-0175-11ea-9ebd-3a91cad9d0c9.png)

**Comment by docs-product** [comment]
Thank you for the feedback! Because this is not related to docs.microsoft.com, we cannot address the issue in this forum.
