### ISSUE TITLE
404 on Azure Availability checklist

### ISSUE THREAD

**Issue by Cocoa2014** [MicrosoftDocs/feedback#2134]
I meet 404 on https://docs.microsoft.com/en-us/azure/architecture/reliability
Could you confirm if it's moved to another location?

**Comment by mairaw** [comment]
Do you mean the edit button or somewhere else?

**Comment by mairaw** [comment]
Tagging @david-stanford since I do see a 404 when I try to click edit.

**Comment by david-stanford** [comment]
Hi, I can't seem to duplicate the issue.  The reliability content is moved, but the link should work.

Here is the new place the content is located: https://docs.microsoft.com/en-us/azure/architecture/framework/resiliency/overview

**Comment by docs-product** [comment]
Closing as the issue seems to be resolved.
