### ISSUE TITLE
Link to KB article on Sysinternals JUNCTION page doesn't exist

### ISSUE THREAD

**Issue by yukon-cornelius** [MicrosoftDocs/feedback#2136]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem** (if available).

**Link to article:**
https://docs.microsoft.com/en-us/sysinternals/downloads/junction

**Problem:**
The link for "Please read this [Microsoft KB article](http://support.microsoft.com/?kbid=205524) for tips on using junctions." currently redirects to this page at the MS Support site ... https://support.microsoft.com/en-us/help/205524 ... but that page doesn't exist (404 error).

**Comment by v-kents** [comment]
It seems that particular KB is no longer available/valid. Link has been removed from the page. Thank you for letting us know!
