### ISSUE TITLE
REPL Clear Button

### ISSUE THREAD

**Issue by mairaw** [MicrosoftDocs/feedback#214]
Originally reported by @CliffAgius at https://github.com/dotnet/docs/issues/4493

Completing the C# Getting started "Hello World!" with my son's Yr6 Class (10/11 year olds) and a suggestion from one of the kids was why is there no Clear button to empty the Editor window?

Suggest this would not be a big one to add, also from another child there is a way to copy the code from the code block using the Copy button but no Paste button. I told her she had to type the code which was met with groans...

**Comment by Powerhelmsman** [comment]
@yunyunyunyun This is a suggestion from user about interactive tutorial button. Can you take a look at this?

**Comment by dend** [comment]
@yunyunyunyun can you follow-up?

**Comment by dend** [comment]
@LadyNaggaga is this something that is already on the radar for your team?

**Comment by keziamicro** [comment]
Hello - reviewing and cleaning up some older feedback/issues. Thanks!

**Comment by mairaw** [comment]
@mimisasouvanh this was a good suggestion. Why are we closing still valid feedback?

/cc @BillWagner

**Comment by CliffAgius** [comment]
Also seems a fairly simple fix a clear button can't be that hard to add?

**Comment by keziamicro** [comment]
We are closing the feedback here and migrating it to specific team backlogs so they can be actioned. I've pinged @mimisasouvanh via email for extra awareness.
