### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by adipuscasu** [MicrosoftDocs/feedback#2145]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem** (if available).
Quote : 

> In the .NET Framework Data Provider for SQL Server, data access tracing (Data Access Tracing) has been updated to make it **easier to easier to** correlate client 
> 

**Link to article:**
https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/data-tracing

Tell us where exactly a problem occurs.

**Problem:**
What's wrong with the article?

The words **easier to** are written twice.

**Comment by salmanmkc** [comment]
Fixed, thanks for reporting the issue

**Comment by mairaw** [comment]
Thank you for reporting the issue @adipuscasu and for fixing that @salmanmkc!
