### ISSUE TITLE
Rasterization: Enclosing rectangle does not account for hinting

### ISSUE THREAD

**Issue by thehorseisbrown** [MicrosoftDocs/feedback#2148]
**Describe the bug**
Blackbox values in [GLYPHMETRICS ](https://docs.microsoft.com/en-us/windows/win32/api/wingdi/ns-wingdi-glyphmetrics) don't seem to account for hinting.
The appended image should be illustrative.
I also posted this at [stackoverflow](https://stackoverflow.com/questions/58823986/windows-font-rasterization-blackbox-bug).

**To Reproduce**
1. Look at individual glyph bitmaps drawn with DrawText() using the font Consolas.ttf
2. Look at GLYPHMETRICS data loaded with GetGlyphOutlineA.
3. See that the black box values designate a smaller rectangle than the drawn glyph's rectangle.

**Expected behavior**
The black box values are explicitly said to [enclose ](https://docs.microsoft.com/en-us/windows/win32/api/wingdi/ns-wingdi-glyphmetrics) the glyph.

**Screenshots**
![image](https://user-images.githubusercontent.com/56803787/68697897-08cfa480-0580-11ea-8388-97439869c023.png)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
Hinting is pain.

**Comment by GrantMeStrength** [comment]
Hi - sorry for taking so long to get back to you. Unfortunately this doesn't appear to be a documentation issue. My advice would be to ask on the Microsoft Q&A website. If you still need to resolve the issue, please re-open the bug and we can try and find more answers. https://docs.microsoft.com/en-us/answers/products/
