### ISSUE TITLE
Wrong content in WMI Win32_Printer

### ISSUE THREAD

**Issue by ShadowZzj** [MicrosoftDocs/feedback#2150]
**Link to article:**
https://docs.microsoft.com/en-us/windows/win32/cimwin32prov/win32-printer

**Problem:**
PaperSizesSupported type is not uint16 array, It is uint32 array. It spends me a lot of time to find the bug.

**Comment by GrantMeStrength** [comment]
Hi - sorry for taking so long to get back to you. We checked the header file, it seems it IS uin16[], so maybe the issue lies somewhere else? If you think the doc is still wrong, please re-open the issue and we can dig deeper. Thanks.
