### ISSUE TITLE
Hyperlink to invalid URL on IDvdControl2 documentation

### ISSUE THREAD

**Issue by jacknickles** [MicrosoftDocs/feedback#2154]
Page https://docs.microsoft.com/en-us/windows/win32/api/strmif/nf-strmif-idvdcontrol2-selectvideomodepreference refers to the DVD_PREFERRED_DISPLAY_MODE at https://docs.microsoft.com/previous-versions/windows/desktop/api/strmif/ne-strmif-dvd_preferred_display_mode
This results in a 404 error and should be changed to https://docs.microsoft.com/en-us/windows/win32/api/strmif/ne-strmif-dvd_preferred_display_mode 

To reproduce, navigate to the page above and click on that hyperlink.  The context is Windows 10,0.18362, on a Lenovo Y510p, (PC), Browser is Chrome Version 78.0.3904.97 (Official Build) (64-bit)

I suspect but have not confirmed that when IDvdControl was deprecated and replaced with IDvdControl2 that hyperlinks on each page of the attributes described (I happen to be at SELECT_VIDEO_MODE_PREFERENCE, but there are plenty of others), has links pointing to the previous version.  So it makes sense to follow all links from https://docs.microsoft.com/en-us/windows/win32/api/strmif/nn-strmif-idvdcontrol2 for at least 3 levels to validate validity.     

**Additional context**

**Comment by GrantMeStrength** [comment]
This link has been corrected. Thanks!
