### ISSUE TITLE
Information about BatteryFlag member of SYSTEM_POWER_STATUS incomplete

### ISSUE THREAD

**Issue by german-one** [MicrosoftDocs/feedback#2155]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem** (if available).
No comment section available.

**Link to article:**
[https://docs.microsoft.com/en-us/windows/win32/api/winbase/ns-winbase-system_power_status](https://docs.microsoft.com/en-us/windows/win32/api/winbase/ns-winbase-system_power_status)

**Problem:**
What's wrong with the article?
The information for BatteryFlag states 
> The value is zero if the battery is not being charged and the battery capacity is between low and high.

It's not obvious what the value is if the battery capacity is between low and high and the battery is being charged though. It seems that the value is 8 (for Charging) in this case without any other flag set.

**Comment by GrantMeStrength** [comment]
Hi - I'm sorry we were not able to get back to you in a timely matter. Yes, the value should be 8 as it is charging.
