### ISSUE TITLE
can some article hava some example?

### ISSUE THREAD

**Issue by 1009058470** [MicrosoftDocs/feedback#2156]
some of .net core api's description is not clear. for example ,DbContextOptionsBuilder<TContext>.UseMemoryCache(IMemoryCache) Method just show it parameters ,but i don not know how to make it parameters.
the url is https://docs.microsoft.com/zh-cn/dotnet/api/microsoft.entityframeworkcore.dbcontextoptionsbuilder-1.usememorycache?view=efcore-3.0#Microsoft_EntityFrameworkCore_DbContextOptionsBuilder_1_UseMemoryCache_Microsoft_Extensions_Caching_Memory_IMemoryCache_

**Comment by mairaw** [comment]
@smitpatel this feedback is regarding EF API docs. Can you or your team take a look?

**Comment by smitpatel** [comment]
Opened https://github.com/aspnet/EntityFrameworkCore/issues/18938 to track on EF Core. It can be closed from here.

**Comment by docs-product** [comment]
Closing this issue given that a related one was opened in the product repo.
