### ISSUE TITLE
Typo in xml example @ below link

### ISSUE THREAD

**Issue by mariuselix** [MicrosoftDocs/feedback#2164]
Link to article:
https://docs.microsoft.com/en-us/windows/win32/taskschd/taskschedulerschema-schedulebymonth-calendartriggertype-element

Problem:
There is a typo in the example xml. The Months end tag is missing the slash "/", which will result in a corrupt xml if anyone is copy-pasting it.

**Comment by mairaw** [comment]
Thanks @mariuselix for your feedback. I've opened https://github.com/MicrosoftDocs/win32/pull/141 to fix that. You can also edit topics when you see issues like that. Here's how:
https://docs.microsoft.com/en-us/contribute/#quick-edits-to-existing-documents
