### ISSUE TITLE
Add azure-iot-sdk-node API documentation to docs.microsoft.com/en-us/javascript/api

### ISSUE THREAD

**Issue by YoDaMa** [MicrosoftDocs/feedback#2165]
(filed as member of azure-iot-sdk-node team)

**Link to article:**
https://docs.microsoft.com/en-us/javascript/api/azure-iot-device/

**Problem:**
We need to add API docs. Something's broken with generating the docs to Microsoft Docs.

**Comment by docs-product** [comment]
@YoDaMa - given that this is an internal request, please file an onboarding ticket here: https://aka.ms/publish-on-docs/reference
