### ISSUE TITLE
.NET Version dropdown is inconsistent with displayed content and "Applies to" section

### ISSUE THREAD

**Issue by mairaw** [MicrosoftDocs/feedback#2166]
_From @johndaintree on Tuesday, November 5, 2019 12:56:53 PM_

I suspect that this is a problem with many pages, but, for example, the page:

https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.unmanagedtype

Shows LPUTF8Str as a valid member AND shows Xamarin.iOS in the "Applies to" section. However LPUTF8Str is NOT implemented in Xamarin.

It's only when one selects Xamarin.iOS from the the "Version" drop down that the LPUTF8Str member disappears from the document. 

IMO it would be more helpful/intuitive if the member LPUTF8Str was annotated to indicate that it is NOT available on all platforms.

Similarly:

https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.marshal?view=netcore-3.0

Shows StringToCoTaskMemUTF8 as a member AND includes "Xamarin.iOS" in the "Applies to" section. However this function is NOT in the Xamarin implementation.

_Copied from original issue: dotnet/dotnet-api-docs#3445_

**Comment by mairaw** [comment]
_From @mairaw on Friday, November 15, 2019 10:15:05 PM_

Thanks @johndaintree for your feedback. That's a bit tricky to solve since the information in the Applies to section is about the class and not the individual fields. I'll move this issue to the MicrosoftDocs/feedback for discussion with the engineering team.

**Comment by mairaw** [comment]
I suspect this behavior is by design but I'd like to check how others feel.

@mimisasouvanh @Thraka @BillWagner @tdykstra @gewarren 

Given that selecting the right moniker will show the appropriate APIs for the selected version, I feel like this behavior is by design. We could annotate on a case by case scenario, but it would be hard to do this across the board. Any other ideas or suggestions?

**Comment by tdykstra** [comment]
I think we could annotate on a case-by-case basis without trying to do it across the board, just where it comes up as an issue for people, i.e., where someone brings it to our attention.

**Comment by mimisasouvanh** [comment]
@mairaw We've got a feature open, to fix the Assigned to section, but for now I think it's lower pri. I agree with @tdykstra that if we annotated case-by-case for now would be good.

**Comment by mairaw** [comment]
This is slightly different @mimisasouvanh because the enum fields wouldn't have the Applies to section (or even remarks) with the current design. I agree that we should handle this on a case by case scenario.
