### ISSUE TITLE
Security compliance missing reference to WS 2019

### ISSUE THREAD

**Issue by peterennis** [MicrosoftDocs/feedback#2167]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem** (if available).

**Link to article:**
Tell us where exactly a problem occurs.
https://gallery.technet.microsoft.com/Cybersecurity-Reference-883fb54c#content

**Problem:**
What's wrong with the article?
Security compliance missing reference to WS 2019

![Capture540](https://user-images.githubusercontent.com/140737/68984700-7836d580-07c6-11ea-8e42-a5360a8b96c2.png)

![Capture541](https://user-images.githubusercontent.com/140737/68984704-838a0100-07c6-11ea-883b-c8c7f8c129f6.png)

**Comment by docs-product** [comment]
Thank you for your feedback! Because this is related to content that the author has to modify, we cannot address it in this forum. The Q&A section on the page you linked to should be used for comments pertaining to the document.
