### ISSUE TITLE
[Trivial Issue] Wrong spelling

### ISSUE THREAD

**Issue by AmulyaX** [MicrosoftDocs/feedback#2168]
**Link to article:**
https://docs.microsoft.com/en-us/learn/modules/csharp-if-elseif-else/4-challenge
https://docs.microsoft.com/en-us/learn/modules/csharp-if-elseif-else/5-solution

**Problem:**
If you look at Rule 3 under Step 3, you'll notice in the Output Section that the word expires is wrongly spelt as 'exires'.
Same mistake is made in the solution of that problem, look under 'daysUntilExpiration == 1' condition.

**Comment by mlottner** [comment]
@AmulyaX Thanks so much for taking the time to point out these issues. 

I've forwarded your fixes onto the content developer responsible for the pages. 

Appreciate you taking the time to contribute to our community!
