### ISSUE TITLE
Horizontal scrolling for code snippets with highlights

### ISSUE THREAD

**Issue by guardrex** [MicrosoftDocs/feedback#2170]
Originally reported in aspnet/AspNetCore.Docs by @serpent5 ...

https://github.com/aspnet/AspNetCore.Docs/issues/15715

> Whenever I see a code snippet in a docs page that has a highlight, it has a very wide horizontal scroll. Here's a full screenshot from Chrome:

![image](https://user-images.githubusercontent.com/1622880/68999962-ef836c80-088d-11ea-94f1-35ebe9d9c209.png)

> It seems like this would be a known issue, but I can't find anything that already exists. I've seen it on a couple of different machines I've used and it's present in at least the latest Chrome and Firefox.

**Comment by mlottner** [comment]
@guardrex Thanks for taking the time to report this issue to site feedback.  
I've reassigned the issue to a member of our site experience team to make sure they are aware of the functionality and see if they can help. 

Appreciate your contribution to the docs community!

**Comment by svick** [comment]
@mlottner Why did you also close the issue? Shouldn't the issue stay open until it's resolved?
