### ISSUE TITLE
Azure Dev Ops TestRun - More insight on the API for create

### ISSUE THREAD

**Issue by johnathanseal-enable** [MicrosoftDocs/feedback#2173]
**Link to article:**
https://docs.microsoft.com/en-us/rest/api/azure/devops/test/runs/create?view=azure-devops-rest-5.1

**Problem:**
Hello,

Context:  an automated test that cannot be run in Azure Dev Ops pipeline (for reasons I can not discuss in this forum).
I do want to report on the results of the automated tests.
I suspect the workflow is as follows:

1. create a test plan in azure dev ops (manually)
2. Cite the test plan Azure Dev Ops ticket number.
3. create a test case in the test plan (manually).  
4. Cite the test case Azure Dev Ops ticket number.
5. create a test run (via the test runs _create_ end-point)
6. execute the automated test(s)
7. upload the test results (via the results _add_ end point)
8. update the state of the test run to 'Completed' (via the test runs _update_ end point)

Questions:

1. The above workflow is correct, yes?
2. The sample test documentation for _test run_ gives the following:

`{
  "name": "NewTestRun",
  "plan": {
    "id": "1"
  },
  "pointIds": [
    1,
    1
  ]
}`

The pointIds are the test case Azure Dev Ops ticket numbers?  If not, what are they?
3.  The results _add end point_ has the following:
`[
  {
    "testCaseTitle": "VerifyWebsiteTheme",
    "automatedTestName": "FabrikamFiber.WebSite.TestClass.VerifyWebsiteTheme",
    "priority": 1,
    "outcome": "Passed"
  },
  {
    "testCaseTitle": "VerifyWebsiteLinks",
    "automatedTestName": "FabrikamFiber.WebSite.TestClass.VerifyWebsiteLinks",
    "priority": 2,
    "outcome": "Failed",
    "associatedBugs": [
      {
        "id": 30
      }
    ]
  }
]`
The results are mapped to a Azure Dev Ops Test Case **title** - not an Azure Dev Ops ticket number?  This implies that each test case must be unique, yes?
4.  The test run Azure Dev Ops ticket number is not referenced in the results _Add_, yes?

Thank you for your insights,

**Comment by mlottner** [comment]
@johnathanseal-enable Thanks for taking the time to give us feedback. 
For this specific issue, please use [product feedback](https://developercommunity.visualstudio.com/spaces/21/index.html) to make sure the correct technical contact can respond and clarify. 
Appreciate your contribution to our community.
