### ISSUE TITLE
NETRESOURCE link error in document WNetAddConnection[2|3]

### ISSUE THREAD

**Issue by BESTRIVENinCN** [MicrosoftDocs/feedback#2174]
**Link to article:**
https://docs.microsoft.com/en-us/windows/win32/api/winnetwk/nf-winnetwk-wnetaddconnection2a

**Problem:**
The NETRESOURCE link in WNetAddConnection[2|3] document is linked to the wrong place:
https://docs.microsoft.com/en-us/windows/win32/api/rrascfg/nn-rrascfg-ieapproviderconfig

The NETRESOURCE link should be 
https://docs.microsoft.com/en-us/windows/win32/api/winnetwk/ns-winnetwk-netresourcea

**Comment by mlottner** [comment]
@BESTRIVENinCN Thanks for taking the time to leave us feedback. 
I've flagged your issue to the team responsible for this page for awareness and future resolution. 

Appreciate you taking the time to contribute to our community.
