### ISSUE TITLE
[Feature Request] Add user settings for language and theme

### ISSUE THREAD

**Issue by TechWatching** [MicrosoftDocs/feedback#2175]
I am always frustated when I go to Microsoft Docs and that each time I have to change the language, set my preferred theme ... that is to say each time set the same settings.

What I would want is that, when I connect to Microsoft Docs with my Microsoft account, my theme and language are already the ones that I need because I would have configured them once in my 
profile settings.

Concerning the language, what I mean if even if I am in France and that the google or bing search redirected me to docs.microsoft.com/fr-fr/, if my preferred language is US english because I am more used to english concepts and terms I want to be redirected to docs.microsoft.com/en-us/. I don't know if it's something possible, an alternative would just be to set "Read in English" at true on the page that would just work for english.

**Comment by superfon** [comment]
Pobierz aplikację Outlook dla systemu Android<https://aka.ms/ghei36>
________________________________

**Comment by mlottner** [comment]
@TechWatching Thanks for taking the time to share your feedback. Your experience is important to us. 
I've flagged this issue to the team responsible for user experiences on Docs for awareness and possible future resolution. 
Appreciate your contribution to our community.
