### ISSUE TITLE
 implementation to notice my application when mouse double click file hydration 

### ISSUE THREAD

**Issue by machenghu** [MicrosoftDocs/feedback#2177]
I want to download  file hydration when mouse double click , but in fact it pop-up a form of "This interface is not supported".How  can to notice my application the file hydration is click?
I refer to CloudMirror Sample  link https://github.com/Microsoft/Windows-classic-samples/tree/master/Samples/CloudMirror.

**Comment by machenghu** [comment]
please give some suggest

**Comment by mlottner** [comment]
@machenghu Thanks for taking the time to leave site feedback. 

[Opening an issue](https://github.com/Microsoft/Windows-classic-samples/issues) within the repository is the best way to access support and feedback for the specific product you referenced. 

Appreciate your contribution to our community.
