### ISSUE TITLE
Cortana Skills area should be removed

### ISSUE THREAD

**Issue by ArchieCoder** [MicrosoftDocs/feedback#2178]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem** (if available).

**Link to article:**
https://docs.microsoft.com/en-us/cortana/skills/

**Problem:**
Cortana is shutdown their external services. Keeping the Cortana Skills don't make any sense now. I'm not even sure if it is still working.

**Comment by mlottner** [comment]
@ArchieCoder Thanks for taking the time to give us feedback. 
I've flagged your issue to a member of our Learn team to make sure they are aware of the issue and can take steps to resolve it. 

Appreciate your contribution to our community.
