### ISSUE TITLE
API reference for Xamarin.iOS is severely outdated

### ISSUE THREAD

**Issue by svick** [MicrosoftDocs/feedback#2180]
The API reference seems to contain only information about Xamarin.iOS version 10.8, when the latest version is 13.8. That's severely outdated and should be updated.

**Comment by mlottner** [comment]
@svick Thanks for taking the time to leave Microsoft Docs site feedback. 

To submit specific product feedback, questions or support, please choose the relevant product from the [Microsoft product support directory](https://support.microsoft.com/allproducts) and submit your feedback or question. 

Appreciate your contribution to our community.

**Comment by svick** [comment]
@mlottner I don't understand why this issue was closed, it's not "product feedback, questions or support", it's about a problem with the documentation, specifically, the API reference at https://docs.microsoft.com/en-us/dotnet/api/?view=xamarinios-10.8.

**Comment by mlottner** [comment]
@svick Thanks for pointing out that link. It is directing page feedback to a general site feedback link and not to the a specific .NET framework feedback link. I've reassigned the issue to someone responsible for .NET content.

**Comment by mimisasouvanh** [comment]
@conceptdev Can you take a look?

**Comment by conceptdev** [comment]
Unfortunately it is not very clear that the [link in question](https://docs.microsoft.com/en-us/dotnet/api/?view=xamarinios-10.8) only refers to the BCL (base class library) shipped with Xamarin.iOS. While it may seem outdated compared to Xamarin.iOS 13.8, the BCL actually doesn't change that much between releases. If you find something incorrect on those docs, please use the Feedback button on the page in question to highlight it for us.

The actual iOS APIs supported by Xamarin are available at this link
https://docs.microsoft.com/en-us/dotnet/api/?view=xamarin-ios-sdk-12
the engineering team is aware that it has not yet been updated to iOS 13. For new APIs introduced in iOS 13, the best source of information is [Apple's docs](https://developer.apple.com/documentation)

#please-close

**Comment by mlottner** [comment]
@svick wanted to make sure you saw @conceptdev 's response to your request. Thanks again for taking the time to leave us docs feedback and contribute to our user community.
