### ISSUE TITLE
Description of Windows Mobile Device Center links broken

### ISSUE THREAD

**Issue by DSPatrick** [MicrosoftDocs/feedback#2181]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem** (if available).

**Link to article:**
https://support.microsoft.com/en-us/help/931937/description-of-windows-mobile-device-center

**Problem:**
Links on this page result in 404

**Comment by mlottner** [comment]
@DSPatrick Thanks for taking the time to give us site feedback. 
Please make sure to log the specific link issue directly on the [page feedback option](https://support.microsoft.com/en-us/help/931937/description-of-windows-mobile-device-center) at the bottom of the page, where it asks if the page was helpful. This action ensures the page owner can see and respond to your request.

**Comment by DSPatrick** [comment]
Thanks, but those always seem to be one way black hole type messages. I’ll just skip them from now on I guess.
