### ISSUE TITLE
'See Earlier Issues' Links do not work - instead redirect to docs home page.

### ISSUE THREAD

**Issue by MbrookWork** [MicrosoftDocs/feedback#2182]
https://docs.microsoft.com/en-gb/archive/newsletter/technet/microsoft-technet-flash-archive
'See Earlier Issues' Links do not work - instead redirect to docs home page.

**Problem:**
'See Earlier Issues links seem to be dead - instead redirect to a docs home page.

**Comment by mlottner** [comment]
@MbrookWork Thanks for taking the time to leave us feedback!

The page you referenced is an archive site that is no longer actively updated. Previous links to other articles may be deprecated. Use the [Microsoft Product Lifecycle](https://support.microsoft.com/en-us/lifecycle/selectindex) page for more information about the specific prouct or service you were interested in. 

Appreciate your contribution to our community.
