### ISSUE TITLE
C/C++ Importing WinAPI function with x64 structure parameter inside x86 application

### ISSUE THREAD

**Issue by Mecanik** [MicrosoftDocs/feedback#2183]
I`m opening an issue here with the hope that someone technical can provide me some answers... as to why this works, and if it's stable under windows desktop editions (7/8/8.1 etc)

https://stackoverflow.com/questions/58898815/c-c-importing-winapi-function-with-x64-structure-parameter-inside-x86-applicat

I have received a reply from an MSFT member but totally unrelated to my question.

Can someone provide some clarity please ? I believe I`m not the only one that is interested in this.

Thanks

**Comment by mlottner** [comment]
@Mecanik Thanks for reaching out for product assistance!
Your question is important to us, but docs feedback is the wrong forum for getting technical help with a specific Microsoft product. 
Use the [Microsoft Product support](https://support.microsoft.com/allproducts ) page to request help on your specific product issue. 

Appreciate your contribution to our community.
