### ISSUE TITLE
Missing ability to add Feedback to page

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/feedback#2184]
**Describe the bug**
The ability to add feedback on the product or page page is not available.

**To Reproduce**
1. Go to https://docs.microsoft.com/en-us/sql/reporting-services/report-server-sharepoint/deploy-report-viewer-web-part?view=sql-server-ver15
2. Scroll down to the bottom of the page
4. the option add Feedback to the page is not available.

**Expected behavior**

I should be able to provide Feedback on every page in docs.

**Screenshots**
![image](https://user-images.githubusercontent.com/4058555/69139853-fb864e80-0a86-11ea-87a8-13192928af30.png)

should be something like
![image](https://user-images.githubusercontent.com/4058555/69139885-0ccf5b00-0a87-11ea-901c-e030cc2264e3.png)

**Comment by mlottner** [comment]
@DeanGross Thanks for taking the time to report this issue!
I'm currently researching why the feedback mechanism is not currently available on the docs repository and pages you reported. Agree that consistency across all Microsoft Docs pages is critical to achieving our goal of providing content that is easy to use.

**Comment by maggiesMSFT** [comment]
Hi, @DeanGross -- You're right, feedback is not turned on for the Reporting Services content. I believe you have 2 options.
1. If you'd like to make a comment, under "Is this page helpful?" please select either Yes or No. You then have the option to provide feedback. 
2. I believe you also have an Edit pencil in the upper right corner, right? You can click that to suggest changes to the article.
![image](https://user-images.githubusercontent.com/12401230/69262930-2b158380-0b79-11ea-97d8-b5adc98df975.png)
Hope that helps!
cc @mlottner
