### ISSUE TITLE
How to add an online skype meeting

### ISSUE THREAD

**Issue by davidedironza** [MicrosoftDocs/feedback#2186]
There are only simple examples on how to create an appointment. But I want to create an appointment with an online skype meeting. Is this possible and how?
Thanks in advance for a hint.

**Comment by mlottner** [comment]
@davidedironza Thanks for reaching our to our feedback channel. 

This is the feedback channel specifically for Microsoft Docs. You can use the [Skype product support channel](https://docs.microsoft.com/en-us/skypeforbusiness/skype-for-business-online) to get resolution for Skype product related issues and queries.
