### ISSUE TITLE
bitlocker-auto-unlock commands swapped

### ISSUE THREAD

**Issue by dlwlb** [MicrosoftDocs/feedback#2188]
https://blogs.technet.microsoft.com/dubaisec/2018/07/11/bitlocker-auto-unlock/ needs to be corrected. It says the following but the commands needs swapped. The ones listed for the command prompt are actually for Power Shell and vice versa.
You can enable/disable Auto-unlock protector using:

Command line:
    Enable-BitLockerAutoUnlock
    Disable-BitLockerAutoUnlock
PowerShell:
    manage-bde -autounlock -enable D:
    manage-bde -autounlock -disable D:

**Comment by mlottner** [comment]
@dlwlb Thanks for taking the time to comment on the TechNet blog you referenced 

I've sent the blog author a message with your correction and fix request. 

Appreciate you taking the time to contribute to our feedback community!
