### ISSUE TITLE
Typos on article "Partner security requirements status"

### ISSUE THREAD

**Issue by benjherb** [MicrosoftDocs/feedback#2189]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem** (if available).

No comment section available.

**Link to article:**
Typo 1:
https://docs.microsoft.com/en-us/partner-center/partner-security-compliance#is-mfa-only-required-when-certain-conditions-are-met
Typo 2:
https://docs.microsoft.com/en-us/partner-center/partner-security-compliance#identity-which-users-have-logged-into-partner-center-without-mfa

**Problem:**
I believe there are at least two typos in this article that, while minor, can make the article content a bit harder to comprehend:

Typo 1:
> For partners who have implemented MFA using Azure AD security defaults, it is important to note that for none admin user accounts multi-factor authentication will be enforced based on risk.

I think "non-admin" was meant instead of "none admin"

Typo 2:
> Subsection header "Identity which users have logged into Partner Center without MFA"

I believe "Identify" was meant instead of "Identity"

**Comment by mlottner** [comment]
@benjherb Thanks for taking the time to leave us feedback and proposed fixes. 
Reassigning this to the content owner to address the issues you've raised.

**Comment by mairaw** [comment]
Closing since this seems to be fixed.
