### ISSUE TITLE
Menus should only show top level options on mobile

### ISSUE THREAD

**Issue by mairaw** [MicrosoftDocs/feedback#219]
Originally reported by @ChrisMaddock at https://github.com/dotnet/docs/issues/4075

https://docs.microsoft.com/en-gb/dotnet/csharp/

On the above page - the sidebar menu on the desktop site is hierarchical. 

On mobile however, all menu items are listed in a single list. That's hundreds of items on this page - which makes the menu pretty difficult to use. It would be great if just the current hierarchy level was shown on mobile.

This problem was seen on Chrome 63.0.3239.73 on iPhone, but I can reproduce in [Chrome's device simulator](https://developers.google.com/web/tools/chrome-devtools/device-mode/).

---

From @mairaw: Thanks for the feedback @ChrisMaddock. @adkinn @DuncanmaMSFT [@]EisenbergEffect any input into this issue?

---

From @BillWagner: This also affects how we handle the sub-TOCs. We discussed this briefly last week with @dend in our Friday meeting. There's likely some work on both the content and site engineering side here.

---

From [@]EisenbergEffect:
@ChrisMaddock Thanks for the feedback!

The good news is that we already have a complete revamp of the ToC designed for mobile devices. It needs to go through a final design review still, but it's nearly ready for implementation.

@mairaw I've got this work as part of our FY18Q3 priorities. I'm not sure of the actual timeline just yet though. It's fighting against some other serious hi-pri work that's recently come up. Watch my weekly status update emails for news on progress.

**Comment by Powerhelmsman** [comment]
@ShevaDas Can you take a look at this?

**Comment by ShevaDas** [comment]
This is something we hope to address in our upcoming quarter. I'll keep this issue updated when I have a more firm timeline.

**Comment by ShevaDas** [comment]
This should be fixed with our latest updates to the mobile TOC. Check it out:

![image](https://user-images.githubusercontent.com/3937986/44174759-edce6600-a098-11e8-803a-11925199a1c4.png)

Closing; feel free to open a new issue if needed.

**Comment by ChrisMaddock** [comment]
Awesome, thanks @ShevaDas
