### ISSUE TITLE
CreateWaitableTimer link at the bottom of SetWaitableTimer page is broken

### ISSUE THREAD

**Issue by nikolodus** [MicrosoftDocs/feedback#2190]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem** (if available).

**Link to article:**
https://docs.microsoft.com/en-us/windows/win32/api/synchapi/nf-synchapi-setwaitabletimer

**Problem:**
CreateWaitableTimer link at the bottom of SetWaitableTimer page is broken.

**Comment by mlottner** [comment]
@nikolodus Thanks for taking the time to report the broken link. 
I'll research and reassign to the content owner to make sure it can be fixed.

**Comment by GrantMeStrength** [comment]
Thank you for reporting the link error. This has been fixed. Cheers!
