### ISSUE TITLE
CAPTCHA on senders page doesnt work

### ISSUE THREAD

**Issue by w3corp** [MicrosoftDocs/feedback#2193]
**Describe the bug**
The CAPTCHA on sender.office.com page is not working. It isn't validade anything you put on

**To Reproduce**
Just Go to sender.office.com and try to submit an IP.

**Comment by dendeli-msft** [comment]
Hello! Given that this feedback is not related to docs.microsoft.com, we cannot address it in this forum. Please refer to the product documentation for guidance on how to submit feedback to the right channel.
