### ISSUE TITLE
Can't open Jason.Document and Jason.FromValue when switching language to zh-cn

### ISSUE THREAD

**Issue by Fawziya** [MicrosoftDocs/feedback#2194]
**Describe the bug**
Can't open Jason.Document and Jason.FromValue webpage when switching language to zh-cn

**To Reproduce**
1. Go to https://docs.microsoft.com/zh-cn/powerquery-m/informix-database
2. Click on Jason.Document or Jason.FromValue from the content index on the left
4. See error 404 can't find the link

**Expected behavior**
It looks like a link issue. The link will work find if deleting '.html.opinternal' from the link
https://docs.microsoft.com/zh-cn/powerquery-m/json-document.html.opinternal

**Screenshots**
![Github](https://user-images.githubusercontent.com/6307695/69408029-e3d9ef00-0d40-11ea-963e-045129889205.JPG)

**Comment by mlottner** [comment]
@Fawziya Thanks for taking the time to give us feedback. 
I've reassigned this issue to a member of our localization team for awareness and a potential fix. 
Appreciate your contribution to our community!

**Comment by ishasahni1** [comment]
@alisha-acharya as she is the LOC PM for Powerquery

**Comment by Alisha-Acharya** [comment]
@Fawziya I am looking into it.

**Comment by Alisha-Acharya** [comment]
@mlottner This issue occurred because we were excluding all .json files from localization. Usually we don't see localizable content in .json file format so I had excluded these files but this logic has been modified now. The files are in translation and this issue should resolve in 7 business days at the latest.

**Comment by mlottner** [comment]
@Fawziya Thanks again for taking the time to give us feedback. 
Looks like this issue will be resolved within a week, so I'm closing this issue for now. 
Feel free to reach out to us again if/as you need. 

Appreciate your contribution the Microsoft docs community!
