### ISSUE TITLE
'Polciies' Typo on top level Azure AD Identity Protection documentation

### ISSUE THREAD

**Issue by nchambe** [MicrosoftDocs/feedback#2197]
![tyVB36gS](https://user-images.githubusercontent.com/33632996/69448870-28ed2980-0d1f-11ea-8543-9df9e4416dbb.png)
Typo polciies > policies
https://docs.microsoft.com/en-us/azure/active-directory/identity-protection/

**Comment by mlottner** [comment]
@nchambe Thanks for taking the time to give us feedback. 
I've reassigned this issue to the content owner for awareness and a potential fix. 
Appreciate your contribution to our community!

**Comment by mairaw** [comment]
This has been fixed. Closing.
