### ISSUE TITLE
Broken link in article

### ISSUE THREAD

**Issue by Ronsss** [MicrosoftDocs/feedback#2198]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem** (if available).

**Link to article:**
https://docs.microsoft.com/en-us/previous-versions/sql/sql-server-2008-r2/gg399093%28v%3dsql.105%29 

**Problem:**
The link under this text is broken
 "Links to all of the videos"

**Comment by mlottner** [comment]
@Ronsss Thanks for taking the time to give us your feedback. 

As noted at the top of the page, the content you references has been retired and may not be updated in the future. The product, service, or technology mentioned in the content is no longer supported. Links within the content may or may not be working as related locations may have been changed or moved. 

Make sure to use only supported product versions to ensure the an optimal, secure experience for your users and customers.

**Comment by Ronsss** [comment]
How about adding a link to direct readers to the current version?  Searching your sites is a lost cause.  It is a simple task to provide this trivial customer service.l

On Tue, Nov 26, 2019 at 4:01 AM Miriam Lottner <notifications@github.com<mailto:notifications@github.com>> wrote:

Closed #2198<https://github.com/MicrosoftDocs/feedback/issues/2198>.

**Comment by mlottner** [comment]
@Ronsss 
Unfortunately, these archived sites are no longer editable and are not staffed for updates. 
docs.microsoft.com is fully searchable and our pages have heavy SEO and metadata investment to ensure the most relevant and fresh content is surfaced using any search engine.
