### ISSUE TITLE
Doc obsolescent: Get Started with PowerPivot

### ISSUE THREAD

**Issue by Ronsss** [MicrosoftDocs/feedback#2199]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem** (if available).

**Link to article:**
https://docs.microsoft.com/en-us/previous-versions/sql/sql-server-2008-r2/gg399183(v=sql.105) 

**Problem:**
This whole series of articles is attached to SQL Server 2008 and marked obsolescent.  The page has a redirect to the new "MS SQL Documentation" site, 
https://docs.microsoft.com/en-us/sql/?view=sql-server-ver15 
but I can't find a reference to PowerPivot on that page ...

That link has to be directed to the "right" page for PowerPivot in Excel and/or PowerBI. There needs to be current documentation for the PowerPivot functionality.

**Comment by mlottner** [comment]
@Ronsss Thanks for taking the time to give us your feedback.

As noted at the top of the page, the content you references has been retired and may not be updated or maintained in the future. The product, service, or technology mentioned in the content is no longer supported. Links within the content may or may not be working as related locations may have been changed or moved. 

Make sure to use only supported product versions to ensure the an optimal, secure experience for your users and customers. Supported versions of SQL server link to [updated PowerPivot docs](https://docs.microsoft.com/en-us/analysis-services/power-pivot-for-sharepoint-ssas).

**Comment by Ronsss** [comment]
Thank you for the updated link.

It would help your customers if the old article(s) included links to the current version.

On Tue, Nov 26, 2019 at 4:07 AM Miriam Lottner <notifications@github.com<mailto:notifications@github.com>> wrote:

@Ronsss<https://github.com/Ronsss> Thanks for taking the time to give us your feedback.

As noted at the top of the page, the content you references has been retired and may not be updated or maintained in the future. The product, service, or technology mentioned in the content is no longer supported. Links within the content may or may not be working as related locations may have been changed or moved.

Make sure to use only supported product versions to ensure the an optimal, secure experience for your users and customers. Supported versions of SQL server link to updated PowerPivot docs<https://docs.microsoft.com/en-us/analysis-services/power-pivot-for-sharepoint-ssas>.
