### ISSUE TITLE
BREAK http://go.microsoft.com/fwlink/?LinkID=179557

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#22]
Fix broken link 
http://go.microsoft.com/fwlink/?LinkID=179557

----------
⚠ Idea migrated from UserVoice

**Created By:** Anonymous
**Created On:** 2018/02/23 10:38:13 +0000
**Votes at Migration:** 1
**Supporters at Migration:** 1

**Comment by dend** [comment]
This link seems to point to http://code.msdn.microsoft.com/nclsamples/Wiki/View.aspx?title=FTP%20Client - this page is no longer available and therefore there is no way for us to fix the link to something different.
