### ISSUE TITLE
Broken and incorrect links on Wait Functions page

### ISSUE THREAD

**Issue by sblionel** [MicrosoftDocs/feedback#2200]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem** (if available).

**Link to article:**
https://docs.microsoft.com/en-us/windows/win32/sync/wait-functions

**Problem:**
In the paragraph "Single-object wait functions" the following links have problems:

- Both links for SignalObjectAndWait point to https://docs.microsoft.com/en-us/windows/desktop/api/WinBase/nf-winbase-signalobjectandwait which gets a 404. A correct link would be https://docs.microsoft.com/en-us/windows/win32/api/synchapi/nf-synchapi-signalobjectandwait
- The link for WaitForSingleObject, https://msdn.microsoft.com/en-us/library/ms685061(v=VS.85).aspx , instead redirects to the page for RegisterWaitForSingleObject

I checked some of the remaining links on the page, but not all of them; I did not see further issues.

**Comment by GrantMeStrength** [comment]
Thank you! I've corrected the misdirected topic, and replaced the older MSDN links. Thanks for taking the time to make the docs better.
