### ISSUE TITLE
Link on this page links to a crazypants "all em radiation causes cancer" site.

### ISSUE THREAD

**Issue by stephenrdsi** [MicrosoftDocs/feedback#2201]
The article is at [https://docs.microsoft.com/en-us/previous-versions/windows/desktop/irda/irda-start-page](https://docs.microsoft.com/en-us/previous-versions/windows/desktop/irda/irda-start-page)

What's wrong with the article?

Well, nothing other than the link to [irda.org](https://www.irda.org). Apparently the domain's been taken over by a probably-literally-tinfoil-hat-wearing person.

**Comment by mlottner** [comment]
@stephenrdsi Thanks for taking the time to leave us your feedback. 
Unfortunately, the content in question is archived. I'm researching if updated can be made to remove now suspicious links. 
Appreciate your patience in regards to this issue.

**Comment by mlottner** [comment]
Unfortunately, no updates are currently possibly. I've opened an internal ticket to try to handle it. 
Again, appreciate your letting us know. 
I'm closing this issue for now. Feel free to continue communicating here (even when closed) as needed.
