### ISSUE TITLE
Incorrect example on how to use QueryDosDeviceW

### ISSUE THREAD

**Issue by evilpro** [MicrosoftDocs/feedback#2203]
**Link to article:**
https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-querydosdevicew

**Problem:**
In the description of the first parameter, the following text can be found.

> An MS-DOS device name string specifying the target of the query. The device name cannot have a trailing backslash; for example, use "C:", not "C:".

I think it should say

> ... use "C:", not "C:\\".

This is probably happening because Markdown ignores single backslashes (due to escaping).

I guess that this happened during the migration from the older MSDN documentations over to docs.microsoft.com. If that's the case, other migrated articles are likely to have similar issues.

**Another example:**

https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-querydosdevicew

> This parameter should not be NULL, an invalid string (for example, an empty string or a string that is missing the terminating null character), or end in a trailing backslash ().

> As stated previously, you cannot use a trailing backslash () in the lpFileName input string...

**Comment by GrantMeStrength** [comment]
Thanks for reporting these. I believe they've been resolved.
