### ISSUE TITLE
Download link not working

### ISSUE THREAD

**Issue by ansar7** [MicrosoftDocs/feedback#2204]
Antivirus Sample Application
**https://docs.microsoft.com/en-us/previous-versions/office/developer/exchange-server-2010/bb204055(v%3Dexchg.140)**

**Problem:**
Antivirus sample application has sample download link **http://www.microsoft.com/en-us/download/details.aspx?id=13156**  which is giving 404 error.

I know It's an old article and Microsoft is not maintaining it.

But I need this for testing purpose, would be great If I can get download link for the samples of IOfficeAntivirus  interface. Thanks

**Comment by mlottner** [comment]
@ansar7 Thanks for taking the time to give us feedback. 
With 10's of thousands of pages of documentation and downloads to maintain and secure, docs, links and and downloads for previous versions of our products now without support simply cannot be maintained or serviced. 
We encourage using only officially supported product versions to ensure content accuracy, security and ongoing product support.
