### ISSUE TITLE
Unbulleted lists

### ISSUE THREAD

**Issue by mairaw** [MicrosoftDocs/feedback#221]
Originally requested by @svick at https://github.com/dotnet/docs/issues/2540

I think there are several cases in docs that are semantically lists (possibly nested lists), but shouldn't be displayed as normal Markdown lists (with bullets), so their appearance is maintained manually (often using a generous helping of `&nbsp;`s).

These include:

* See also sections at the end of articles.
* Directory listings (e.g. [here](https://github.com/GuardRex/docs-1/blob/ea66eb3ffe9186d1ecc66ffc2cba3bf54357cc74/docs/core/deploying/runtime-package-store.md)).
* WCF configuration elements hierarchy (e.g. [here](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/wcf/servicediscovery), currently not indented properly).

Would it be worth trying to come up with markdown for those?

I was thinking that this could be done by specifying a custom class for such a list. As far as I can tell, this can be done in DocFX flavored Markdown using `> [!div]`. So, for example, the WCF example would look like this:

```md
> [!div class="unbulleted-list"]
> * \<system.ServiceModel>
>   * \<behaviors>
>     * \<serviceBehaviors>
>       * \<behavior>
>         * \<serviceDiscovery>
```

With a custom style of (I don't know CSS, so this might not be the right way to do it):

```css
.unbulleted-list ul
{ 
    list-style-type: none;
    padding-left: 0;
}

.unbulleted-list ul ul
{ 
    padding-left: 1em;
}
```

This renders as:

![](https://user-images.githubusercontent.com/287848/27771867-cdc53a38-5f57-11e7-9d1e-25bc34720bea.png)

Would this be useful at all? Is the syntax acceptable? Or am I trying to solve a problem that does not exist?

cc: @GuardRex 

---

From @guardrex:
> using a generous helping of `&nbsp;`s

Truly so! :+1: :smile: I think it looks sooooo much better rendered this way under certain circumstances (i.e., *not* in a code block ... yuck!). Yes, as you say, non-breaking spaces aren't the proper way to achieve this rendering. Ugh ... we *hacked it!* lol

> solve a problem that does not exist

IMHO, it's a problem in spots.

* See also sections at the end of articles.

   We have a plan: No bullets and no line spaces between *See also* links. [@]rpetrusha explained how to make it work by placing two spaces at the end of each line (each link). If the two spaces aren't there, the links pile up on the same line. I don't think this will require any changes.

* Directory listings

   *Yes, please. Not a code block, please.*

* WCF configuration elements hierarchy

   *Yes, please. Not a code block, please.* It matches the MSDN way. Looks nice imo.

**Comment by mairaw** [comment]
I'd also say that we'd need to support links in this structure. See here an example of a topic where we got the topic looking the way we wanted by adding a bunch of `&nbsp;`:
https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/add-element-for-custom-2

![image](https://user-images.githubusercontent.com/12971179/37313556-02a2b9e8-260d-11e8-9b66-34a81acc3f58.png)

**Comment by Powerhelmsman** [comment]
@ShevaDas Is there anything you can help here?

**Comment by guardrex** [comment]
I wished for something baked into markdown. Absent that, I hacked it best I could. I was told at one point that there is a **no markup in the markdown** rule, and that the order had come down from APEX managers. However, I even ended up violating that a little bit, because lists don't work in table cells, so I was absolutely forced to use unordered list tags and listitem tags in table cells.

**Comment by mairaw** [comment]
I've done that in other topics too @guardrex. Don't worry. 

I ran QA on our content and there was no forbidden HTML elements found, so I think we're good. The rule is to avoid HTML.

**Comment by ShevaDas** [comment]
Tagging @cillroy who may be able to help with the request for a markdown extension.

**Comment by dend** [comment]
@cillroy any updates on this request?

**Comment by dend** [comment]
Ping @cillroy

**Comment by cillroy** [comment]
This is still in the backlog, with no ETA on implementation

**Comment by mairaw** [comment]
Do you have a tracking work item @cillroy? 

See also sections were fixed manually by using unbulleted lists on dotnet/docs and by the build process for API docs.

**Comment by keziamicro** [comment]
Hello - reviewing and cleaning up some older feedback/issues. Thanks!
