### ISSUE TITLE
Just Put "Every Connected settings on Every Page", A feature request as a partner who has some grasping issue as a beginner in the web

### ISSUE THREAD

**Issue by anilparli** [MicrosoftDocs/feedback#2210]
I mean as the Microsoft Cloud solutions has so much connections in between adding "every" connected settings for a user ( Here user means user may be administrator or user ) on top of the page. You may be unable to understand, but just go through the front end and try to get settings related to a user which can be seen in a chronological order ( I don't know whether that word suits here, But I mean a structured way where the user can see the connections from top level settings related to the current app ). For example Dynamics and for powerapps it will be useful to have these settings and connections related buttons or tabs at each and every pages when a user is logged in with credentials. I don't know the practicality from a developers point of view at the back end, but as I have told as a struggling user to understand on how can I utilise it to promote for getting business , I thought sharing the concept which will enable super speed in "usage" when an ordinary business is onboarded after purchasing from partners and which will ultimately popularise the product due to its usability and GUI which have the roots of the GUI of " Windows Platform".

**Comment by fatso83** [comment]
That is a product enhancement issue, not a documentation issue. It is misplaced.

**Comment by docs-product** [comment]
Thank you for the feedback. Because this suggestion is not related to docs.microsoft.com, we cannot address it in this forum.
