### ISSUE TITLE
MSDN improvement suggestion link sends users the the Docs landing page

### ISSUE THREAD

**Issue by fatso83** [MicrosoftDocs/feedback#2211]
**Describe the bug**
When I am looking at my [MSDN profile](https://social.msdn.microsoft.com/Profile/u/edit) I would like to contribute some feedback. I then press the button at the bottom of the screen called `Help us improve MSDN. Make a suggestion`. That button is a link to a general forwarding address https://aka.ms/msdnfeedback which sends me to the landing page https://docs.microsoft.com/en-us/?redirectedfrom=MSDN. There is no actionable to see at this point, no text input box or similar, so I have nowhere to input my suggestions.

**To Reproduce**
1. Go to https://social.msdn.microsoft.com/Profile/u/edit (login if requested)
2. Scroll down to the bottom of the page
3. Click on 'Make a suggestion'
4. Get forwarded to the docs landing page.

**Expected behavior**
I expected some kind of form for feedback to pop up.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: chrome,
 - Version: 78

**Comment by docs-product** [comment]
Thank you for the feedback! We are no longer updating the MSDN/TechNet sites, and are in the process of migrating the content to docs.microsoft.com.
