### ISSUE TITLE
Account help needed desperately! Cannot access mult forums

### ISSUE THREAD

**Issue by WonderWoman1977** [MicrosoftDocs/feedback#2214]
Hello,
I have a serious problem with my account access.  I posted this problem to technet previously and when I checked my question/topic all I saw was that it was deleted; no reason, no attempt to contact me.  Nothing, just "DELETED" .  This is unacceptable and 100% NOT helpful.
My problem is that on many forums (not only technet) but other forums like ones for Azure, Windows 10 Insider Preview Community I am getting a message for my account that I am a "banned user" (on the browser tab) and on the page area itself it simply says, "user does not have access".  The account that I am having this problem with is Alisa.Klein.Job.Hunt@gmail.com and I need help clearing this problem up permanently 100%.  I do have a separate account which is AmazonPrincessDiana@gmail.com and the reason I have separate account is because I am using the Alisa.Klen.Job.Hunt@gmail.com for a specific purpose; that being updating my professional skills and the other account is just for my general usage in my personal life.
I need a way to contact forum admins through email.  Since the problem is an ACCOUNT problem I cannot be guaranteed to be able to keep any posts on the forum.   (if it was not an automated/algorythmic removal then shame on the person/people that deleted my request for help without giving me correct ways to contact anyone)

Sincerely,

Alisa

**Comment by docs-product** [comment]
Thank you for your feedback! Because this issue is not related to docs.microsoft.com, we cannot address it in this forum. We'd also recommend checking out the [Q&A site](https://docs.microsoft.com/answers) we just launched as a replacement for forums.
