### ISSUE TITLE
HashSet Documentation missing Example

### ISSUE THREAD

**Issue by jorgeparavicini** [MicrosoftDocs/feedback#2219]
**Link to article:**
https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.hashset-1?view=netframework-4.8

In the Examples Section they show an example but it is just an empty Code Block.

**Problem:**
There should be an example showing how to merge two disparate sets. But the Example Block is empty.

**Comment by mairaw** [comment]
This has been fixed. Thanks for your feedback @jorgeparavicini!
