### ISSUE TITLE
Ticket 393053; Security problems in the consultation of workers, in the Human Resources module

### ISSUE THREAD

**Issue by carodas72** [MicrosoftDocs/feedback#2223]
Number of the Quality Report of the Development team. 393053

**Describe the bug**
The employee consultation shows only those who are hired and associated in a legal entity, however the worker consultation shows ALL the workers of the legal entities that have been implemented in Dynamics 365 F&O. This violates the security and confidentiality that certain organizations have in their internal processes, since not necessarily the same team of users, is in charge of the total administration of the human team of an organization, since in occasions it is divided according to needs, In this sense, the Workers 'consultation should comply with the same design of the Employees' consultation.

**To Reproduce**
To replicate the error, the following must be done;

1. Go to the human resources module and select, Human Resources> Workers> Employees.
1.1 Here you can view the employees associated and / or hired for a specific legal entity.
2. Go to the human resources module and select, Human Resources> Workers> Workers.
2.2 Here you can view ALL workers created in Dynamics 365 F&O.

**Expected **behavior****
According to the structure of other modules this should be able to be parameterized, so that at the hierarchy level it can be limited to the legal entities that users can access, as is done in the budget, accounting module, etc.

**Share product design documentation, where you can consult, the requirements taken into account to structure the inquiries of both employees and workers, to show our customer.**

**Comment by dendeli-msft** [comment]
Thank you for the feedback! Because this is not an issue with docs.microsoft.com, we cannot address it in this forum. We recommend that you reach out to the appropriate product support group through the documented channels.
