### ISSUE TITLE
Win32 API documentation missing "Requirements" section data

### ISSUE THREAD

**Issue by lhaley42** [MicrosoftDocs/feedback#2228]
For as many Win32 API Functions as I cared to spot-check - the requirements section was blank.  For example:

https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-createfilea#requirements

In the image below, from the 'wayback machine' - one sees the yellow highlighted information present, whereas, as the time of submission, via the link above, that information is missing.

![image](https://user-images.githubusercontent.com/58484584/70077340-9aa25e80-15ce-11ea-9ee6-0b5514d53536.png)

Thank you.

**Comment by dxgldotorg** [comment]
I have personally seen this issue both on the User32 and DirectDraw documentations.
Also, #652 is still an issue.

**Comment by lhaley42** [comment]
As I (re)check the MSDN Documentation today - I see the Requirement data has been restored.
Thank you.
