### ISSUE TITLE
Array is missing implemented interfaces

### ISSUE THREAD

**Issue by mairaw** [MicrosoftDocs/feedback#223]
Originally reported by @svick at https://github.com/dotnet/docs/issues/2136

[The API reference page for `Array`](https://docs.microsoft.com/en-us/dotnet/api/system.array?view=netframework-4.7) lists its implemented interfaces as: `ICloneable`, `IList`, `IStructuralComparable` and `IStructuralEquatable`.

But that is not all, [as MSDN shows](https://msdn.microsoft.com/en-us/library/system.array(v=vs.110).aspx), `Array` also implements `ICollection` and `IEnumerable`.

I'm assuming that this is an issue with whatever tool is used to generate the XMLs and that a PR fixing this is not the right approach. If I'm mistaken about that, I can submit that PR.

---

From @rpetrusha: Thanks for discovering this issue, @svick. Yes, this is a general reflection issue that applies to additional types, so it can't be fixed with a PR. I haven't looked systematically, but it also applies to List as well -- the same two interfaces are listed on MSDN but not on docs.microsoft.com. I've opened internal CSI bug #996154 to track this issue.

---

From @dend: This is by-design and reflects the .NET model where interface implementations are "collapsed". In this case, if one interface already implements another interface, only the one highest in the chain will be displayed as you only need it to implement both.

---

From @svick: 

@dend That rule doesn't seem to be followed universally. E.g. the implemented interfaces for [`List<T>`](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.list-1) are collapsed only partially:

* `ICollection<T>`, `IEnumerable<T>` and `IList<T>` are all shown, when they could be collapsed to just `IList<T>`.
* `ICollection` and `IEnumerable` are not shown, presumably they are both collapsed into `IList`.

Personally, I think interfaces should not be collapsed. If I'm trying to find out whether a type implements a certain interface, I shouldn't have to go through all of its shown interfaces to find out whether one of them implies indirectly implementing it.

---

From @mairaw: @dend I'm reopening this since we either collapse them all or we don't. My personal preference would also be to show them all.

**Comment by Powerhelmsman** [comment]
@dend Assign this to you so far. Let me if we resolve the issue.

**Comment by dend** [comment]
@joelmartinez tagging you here to see if you have any thoughts why in some cases interface "collapsing" happens, and in others it doesn't.

**Comment by joelmartinez** [comment]
Mdoc (via mono.cecil) literally just read’s the assembly metadata ... so it lists whatever interfaces are explicitly listed by the metadata. Any collapsing is only incidental due to that implementation detail. 

If we want to be explicit, mdoc would simply have to explicitly walk the interface implementation tree to list everything. Please open a GH issue for the enhancement if we want to go down this path :)

**Comment by dend** [comment]
@joelmartinez opened this issue to track the work: https://github.com/mono/api-doc-tools/issues/334

**Comment by dend** [comment]
The documentation has been updated with the fix - all interfaces are now shown! 🎉
