### ISSUE TITLE
API reference search should be smarter for common names

### ISSUE THREAD

**Issue by mairaw** [MicrosoftDocs/feedback#224]
Originally submitted by @svick at https://github.com/dotnet/docs/issues/1908

When using the API reference search for simple, relatively common names, the ordering of the results tends to be pretty bad. The item I am most likely looking for tends to be in the top 10, but I think that's not good enough.

Some specific examples:

| Search term | Expected top result | Actual position |
| --- | --- | --- |
| [dictionary](https://docs.microsoft.com/en-us/dotnet/api/index?view=netframework-4.7&term=dictionary) | `System.​Collections.​Generic.​Dictionary<​TKey,​TValue>` | 5
| [list](https://docs.microsoft.com/en-us/dotnet/api/index?view=netframework-4.7&term=list) | `System.​Collections.​Generic.​List<​T>` | 6
| [regex](https://docs.microsoft.com/en-us/dotnet/api/index?view=netframework-4.7&term=regex) | `System.​Text.​Regular​Expressions.​Regex` | 6

Looking at the results, maybe search should prefer more exact matches (e.g. when searching for "regex" prefer `Regex` over `Reg​Exp​Object`). It could also take popularity into account ([`System.​Text.​Regular​Expressions.​Regex` is used by 27 % of apps](https://apisof.net/catalog/System.Text.RegularExpressions.Regex), [`Microsoft.​JScript.RegExpObject` by 0 %](https://apisof.net/catalog/Microsoft.JScript.RegExpObject)).

---

From @mairaw: Filed internal feature request for this: # 980589

/cc @dend

**Comment by Powerhelmsman** [comment]
@dend Can you take a look to see if we can improve the API search result?

**Comment by dend** [comment]
#log-suggestion @dend 

Given that this issue now has an internal work item, and there is no definitive timeframe in which this change will be implemented, I am going to close the issue for the time being. We will be looking at the API Browser holistically and see how we can improve the fidelity of the search results.

**Comment by botcrane** [comment]
🚀 **ATTENTION**: [Internal request](https://ceapex.visualstudio.com/web/wi.aspx?pcguid=7d644393-99ad-41c8-ac53-7fa79294c720&id=54194) logged.
