### ISSUE TITLE
Typo in DISM documentation - no link to create pull request on page :(

### ISSUE THREAD

**Issue by danijeljw** [MicrosoftDocs/feedback#2248]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem** (if available).

**Link to article:**
https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/dism-image-management-command-line-options-s14#get-imageinfo

**Problem:**
Typo.
This: `...currently mounted, as well s information about...`
Should read like this: `...currently mounted, as well as information about...`
The **s** is mistyped and should read as **as**

**Comment by mairaw** [comment]
Thanks @danijeljw. I've opened a PR to fix this.
