### ISSUE TITLE
Bad translation (ITALIAN)

### ISSUE THREAD

**Issue by EvologicDj** [MicrosoftDocs/feedback#2250]
The italian phrase to enable/disable automatic lock to a Hard Disk Drive in BitLocker is wrong.

Italian:

La frase per bloccare/sbloccare automaticamente un disco su BitLocker è sbagliata: "Attiva/disattiva SBOCCO automatico".

![image](https://user-images.githubusercontent.com/49160975/70527916-4ad31280-1b4d-11ea-861b-7a95cb8aa406.png)

**Comment by mairaw** [comment]
In which docs.microsoft.com article are you seeing this?

**Comment by SonjaSaltzman** [comment]
Hello @EvologicDj - could you please provide the URL with this problem?  we are happy to address it if you could provide the URL.

**Comment by EvologicDj** [comment]
Sorry I meant a bad translation present in the operating system.

Il Sab 11 Apr 2020, 00:10 SonjaSaltzman <notifications@github.com> ha
scritto:

**Comment by SonjaSaltzman** [comment]
Hi @TinaMcN could you please find the software owner? This is a bad localization in the software. Thanks,
Sonja

**Comment by EvologicDj** [comment]
Is in BitLocker

Il Sab 11 Apr 2020, 04:14 SonjaSaltzman <notifications@github.com> ha
scritto:

**Comment by TinaMcN** [comment]
@EvologicDj thank you for reporting this issue, I will pass on to the software translators.   Can you please provide a bit more information:
- Repro steps to where you find the menu
-  Can you clarify that "Attiva sbocco automatico" is the wrong translation and "Attiva/disattiva SBOCCO automatico" is the correct translation?

**Comment by EvologicDj** [comment]
Just the word "sbocco" is wrong, it should be "sblocco". The word "sbocco"
in italian means "I vomit", insted of "sblocco" that means correctly
"unlock".

Il Sab 11 Apr 2020, 22:42 Tina McNaboe <notifications@github.com> ha
scritto:

**Comment by EvologicDj** [comment]
I included in the attachment the image of the english phrase "turn off/on
auto-lock", in the BitLocker menu.

Il Sab 11 Apr 2020, 23:20 Federico Ortu <federicoortu96@gmail.com> ha
scritto:

**Comment by TinaMcN** [comment]
@EvologicDj thank you for the extra information, I passed it on.   Grazie!

**Comment by TinaMcN** [comment]
@EvologicDj the Localization Engineering tells me that this issue is fixed now.   Thanks again for reporting it.

**Comment by TinaMcN** [comment]
@@EvologicDj can you please close this issue?

**Comment by EvologicDj** [comment]
How can I do it?

Il Mer 23 Dic 2020, 02:43 Tina McNaboe <notifications@github.com> ha
scritto:

**Comment by TinaMcN** [comment]
@EvologicDj thank you for closing!  And thanks again for reporting this issue.
