### ISSUE TITLE
Microsoft docs for supported CSP services don't reflect all the available services in CSP

### ISSUE THREAD

**Issue by sayanghosh123** [MicrosoftDocs/feedback#2253]
**Link to article:**
https://docs.microsoft.com/en-us/azure/cloud-solution-provider/overview/azure-csp-available-services

**Problem:**
I am referring to the documentation at https://docs.microsoft.com/en-us/azure/cloud-solution-provider/overview/azure-csp-available-services It does not list all the services available in CSP. We are missing things like Azure Front Door Service, Azure Databricks etc. which are available in CSP and in the CSP catalogue / pricelist, but not listed in the documentation. This is creating issues with our customers who are trying to find these services and are unsure about moving to CSP as a result. Any official word around this will be greatly helpful. There is no comments section directly within the page.

**Comment by sayanghosh123** [comment]
A quick follow up on this please. In addition, we also raised a support ticket to Microsoft support and the feedback received was "The article that you refered to was over a year ago so it is no longer updated. ". Of course, it is a concern if an article on docsmsft is available and is not updated, as partners and customers take important decisions based on this documentation. Please add this to the issue as another dimension.

**Comment by JasonWHowell** [comment]
Hi @sayanghosh123 Thanks for your inquiry. This forum is not monitored very often.

Looks like the original link you pointed to is now defunct and redirects elsewhere.

There is a listing of Azure Services in the CSP program here. https://docs.microsoft.com/en-us/partner-center/azure-plan-available.

Please let us know if you have additional questions. 

CC: @amitravat @LauraBrenner 

Thanks, Jason

**Comment by JasonWHowell** [comment]
#please-close
