### ISSUE TITLE
FileSystemWatcher Class: broken link

### ISSUE THREAD

**Issue by todduk** [MicrosoftDocs/feedback#2260]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem** (if available).

There is no comment section for this page.

**Link to article:**
https://docs.microsoft.com/en-us/dotnet/api/system.io.filesystemwatcher?view=netframework-4.8

**Problem:**
Link to 'Using a FileSystemWatcher Component in a Windows Form' which points to https://code.msdn.microsoft.com/Using-a-FileSystemWatcher-4bc97af4 is not a valid link, it takes you to the generic code samples page.

There is a huge problem with broken links across the entire Microsoft site, probably 80% of the links I follow to there which are more than 12 month old are dead, extremely frustrating.

**Comment by mairaw** [comment]
This issue was moved to dotnet/dotnet-api-docs#3695
