### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by TrainsDontHunt** [MicrosoftDocs/feedback#2267]
**Link to article:**
https://docs.microsoft.com/en-us/aspnet/web-forms/overview/older-versions-getting-started/deployment-to-a-hosting-provider/deployment-to-a-hosting-provider-web-config-file-transformations-3-of-12

**Problem:**
Wording ( two "not"s)
"which does not work not for SQL Server Compact."

**Comment by mairaw** [comment]
This was fixed. Closing.
