### ISSUE TITLE
Right-hand navigation now blocks content 

### ISSUE THREAD

**Issue by mairaw** [MicrosoftDocs/feedback#227]
Originally reported by @cartermp at https://github.com/dotnet/docs/issues/1175

https://docs.microsoft.com/en-us/dotnet/articles/fsharp/language-reference/query-expressions#comparison-of-transact-sql-and-f-query-expressions

<img width="796" alt="screen shot 2016-10-25 at 1 57 42 pm" src="https://cloud.githubusercontent.com/assets/6309070/19704067/24bd1c64-9abb-11e6-9c56-9c347c421421.png">

This is using latest Safari on macOS.

cc @DuncanmaMSFT

**Comment by Powerhelmsman** [comment]
@DuncanmaMSFT Can you take a look at this bug? Let me know if you want to create a bug internally.

**Comment by dend** [comment]
This seems to be working correctly now. @mairaw @cartermp

**Comment by mairaw** [comment]
Content is still covered by the nav bar:
![image](https://user-images.githubusercontent.com/12971179/39602827-385e0aaa-4edb-11e8-81d6-31db0ef23c2d.png)

![image](https://user-images.githubusercontent.com/12971179/39602844-42c234ee-4edb-11e8-9409-ddf32643a2a9.png)

I'm afraid that we might have to rewrite the content to have it looked differently.
