### ISSUE TITLE
The .NET docs homepage became less useful

### ISSUE THREAD

**Issue by matteocontrini** [MicrosoftDocs/feedback#2271]
**Is your feature request related to a problem? Please describe.**

In the past days, the .NET docs homepage has been changed with a new design:

https://docs.microsoft.com/en-us/dotnet/

I used that page as a starting point for reaching products docs in a fast way. Now I find it much harder to use.

For example, often I want to open the first page of the ASP.NET Core docs, so that I can search articles through the sidebar.

In the previous website's version, it was easy to find the ASP.NET Core link in the middle of the screen:

![immagine](https://user-images.githubusercontent.com/2164763/70867979-e7e1e100-1f7b-11ea-8dae-cbcefec55cbe.png)

With the current version, I have to scroll almost to the bottom of the page and then click this link:

![immagine](https://user-images.githubusercontent.com/2164763/70867930-638f5e00-1f7b-11ea-970f-2e12786c73d8.png)

That's not really intuitive.

Previously, there was also a link to the EF Core documentation. It's not there anymore unfortunately.

**Describe the solution you'd like**

The new page design might be good for new users, but it's not helpful for people that already know where they want to go.

There should be more quick links to specific products links. The "Programming languages" section is well designed, so it would be helpful to have a similar thing for products like ASP.NET Core and EF Core.

**Comment by Youssef1313** [comment]
cc: @BillWagner @mairaw

**Comment by mairaw** [comment]
Closing. Fixed by https://github.com/dotnet/docs/pull/16304. Thanks for your feedback @matteocontrini.

**Comment by matteocontrini** [comment]
That was fast, thank you very much!
