### ISSUE TITLE
Typo in VS 2019 16.4 Release Notes

### ISSUE THREAD

**Issue by arfmach** [MicrosoftDocs/feedback#2273]
**Link to article:**
[https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes](https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes)

**Problem:**
In section [Top Issues Fixed in Visual Studio 2019 version 16.4.1](https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes#top-issues-fixed-in-visual-studio-2019-version-1641), the fourth bullet has the following text:
“_TypeScript 3.7.3 is now included by default, which contains several fixes for issues that **effect** the JavaScript and TypeScript editing experience._” (my emphasis)
It should say **_affect_** and not _effect_.

**Comment by mairaw** [comment]
Thank you @arfmach. This has been fixed.
