### ISSUE TITLE
Search doesn't work for symbols

### ISSUE THREAD

**Issue by mairaw** [MicrosoftDocs/feedback#228]
Originally reported by @cartermp at https://github.com/dotnet/docs/issues/1439

Search in the .NET Docs for `||>`.  

Expected: [F# Symbol and Operator Reference](https://docs.microsoft.com/en-us/dotnet/articles/fsharp/language-reference/symbol-and-operator-reference/) is in the results.

Actual: No results.  See: https://docs.microsoft.com/en-us/search/index?search=%7C%7C%3E&scope=.NET

Background:

Someone trying F# for the first time reported in the Functional Programming Slack that they came across some code using `||>` and didn't know what it was.  They tried searching in the docs and got the above results.  I imagine C# would have similar issues with tokens like `??` and `?.`.

---

From @mairaw:
We probably need to file an internal bug for this one.

I've seen other issues with search that would be good to follow-up.

/cc [@]EisenbergEffect @dend [@]bradygaster

---

From  [@]EisenbergEffect: 

I'll create a bug to track this.

--- 

From  [@]EisenbergEffect: 

I've created the bug in our system and alerted the engineering team that works on search of the issue. @cartermp Thanks for alerting us of the issue!

**Comment by Powerhelmsman** [comment]
@presleyy Assign to you. Can you follow up this issue?

**Comment by presleyy** [comment]
@mairaw @Powerhelmsman  Yes, similar case of searching "C++", that doesn't work neither. I've created a bug in VSTS for this.

**Comment by dend** [comment]
@presleyy any updates on this item?

**Comment by presleyy** [comment]
@dend the [bug](https://mseng.visualstudio.com/CSI/_workitems/edit/1220335) still in active status. Will double check the fixing progress and reply here.

**Comment by presleyy** [comment]
It is tracked by the [bug](https://mseng.visualstudio.com/CSI/_workitems/edit/1220335) which is in active status

**Comment by Powerhelmsman** [comment]
@cartermp @mairaw Close this as duplicated with https://github.com/MicrosoftDocs/feedback/issues/126 . We will track the bug there.
