### ISSUE TITLE
Regular Expressions in Transport Rules page does not list '+' as character that needs escaping

### ISSUE THREAD

**Issue by veritablyclean** [MicrosoftDocs/feedback#2284]
You need to escape the plus sign '+' when making regex transport rules. It's not shown as a valid character in MS's specific implementation of regex, thus you wouldn't think to escape it.

https://docs.microsoft.com/en-us/previous-versions/office/exchange-server-2010/aa997187(v=exchg.141)?redirectedfrom=MSDN

**Comment by rootsmusic** [comment]
@veritablyclean "This content has been retired and may not be updated in the future."
#please-close
