### ISSUE TITLE
Regarding C# 9

### ISSUE THREAD

**Issue by zappz88** [MicrosoftDocs/feedback#2285]
I have a suggestion, and even though there may be a way to implement this that I'm not aware of, I'm going to say it anyway. Currently, variables cannot be declared outside of classes in the namespace, but enums can. I don't know why this is other than an a design decision, and my point here is to make an argument for allowing for list types to be made available as an option. Currently, I am a C# developer for a company and we have multiple servers containing multiple databases to access. My program is implemented as such:

public enum ServerEnum { ServerOne, ServerTwo }

public enum DatabaseEnum { DatabaseEnumOne, DatabaseEnumTwo }

public enum TableEnum { TableEnumOne, TableEnumTwo }

I'm using enums because I'm not a fan of magic strings or numbers (like most others) and as a way to restrict the available values in an orderly way. What this does not address really, though, is that these three things can get quite large and also they all have certain relationships with each other (a server contains only certain databases and tables). What I would like to do is have the ability to instantiate a List or Dictionary in a namespace to connect these associations for general use within the program. Example:

var serverDictionary =  new Dictionary<Enum, List<Enum>>()
{
  ServerEnum.ServerEnumOne, new List<Enum>(){ DatabaseEnum.DatabaseEnumOne, etc... , etc... },
  ServerEnum.ServerEnumTwo, new List<Enum>(){ DatabaseEnum.DatabaseEnumTwo, etc... , etc... }
}

Hopefully, this makes sense.

**Comment by mairaw** [comment]
C# language design discussions should be filed as issues in the https://github.com/dotnet/csharplang repo. So closing this feedback. 

/cc @BillWagner
