### ISSUE TITLE
[BUG] - Docs - Windows UWP - Download PDF links not working

### ISSUE THREAD

**Issue by AdnanRamulj** [MicrosoftDocs/feedback#2287]
Hello, I want to report that download links, which are linked to UWP apps development are not working.

Tried to download pdf from [Universal Windows Platform documentation](https://docs.microsoft.com/en-us/windows/uwp/) , also navigating to other pages, results in same, which is that page is not found. 

Steps To Reproduce
1. Navigate to https://docs.microsoft.com/en-us/windows/uwp/
2. Click on Download PDF, located on the left bottom of the page
4. You should get 404 Page not found error

![Screenshot_2019-12-20 404 - Content Not Found](https://user-images.githubusercontent.com/48547314/71255837-57b2eb80-232f-11ea-8ab9-07995da85666.png)

Tested :
OS : win 10 Education; Version 1909
Browsers : Firefox | Chrome

**Comment by rootsmusic** [comment]
Fixed.
#please-close
