### ISSUE TITLE
Tab history behaves strangely in Firefox 

### ISSUE THREAD

**Issue by mairaw** [MicrosoftDocs/feedback#229]
Originally reported by @svick at https://github.com/dotnet/docs/issues/1059

The tab history (what you see when you hold the back button) behaves strangely for me on docs.ms/dotnet in Firefox.

For example, I follow this workflow:
1. Open [the _dotnet command_ article](https://docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet) in a new tab.
2. Click on a link to [the _dotnet-build_ article](https://docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-build).

After opening the _dotnet_ article and waiting for it to fully load, the history already contains two items:
1. dotnet command (current)
2. dotnet command

![](http://imgur.com/1BtRr6z.png)

When I click on the link to _dotnet-build_ and wait for it to load, the history now contains three items:
1. dotnet-build (current)
2. dotnet-build
3. dotnet command

![](http://imgur.com/vjt5lw1.png)

This makes navigation using the back and forward buttons hard.

I can observe this behavior in Firefox 48.0.2 on Windows 10, but Edge 38 or Internet Explorer 11 do not seem to have this issue.

----

From @mairaw:

I managed to repro that. Also if I click on a new link, like dotnet restore, this is what is displayed:
![image](https://cloud.githubusercontent.com/assets/12971179/18730655/4e48e4b0-800c-11e6-9660-4d529ad1c1a3.png)
So it seems it's always the last one that is being displayed twice. This doesn't happen with MSDN for example. 

Chrome for Windows also doesn't have this issue.

@DuncanmaMSFT would this be something for you team to look at?

I've also opened an internal bug (667541) to track this.

**Comment by Powerhelmsman** [comment]
@DuncanmaMSFT Do we have any solution for this bug yet

**Comment by Powerhelmsman** [comment]
Created a internal bug to track this issue. https://icm.ad.msft.net/imp/v3/incidents/details/74046967/home

**Comment by keziamicro** [comment]
Hello - reviewing and cleaning up some older feedback/issues. Thanks!
