### ISSUE TITLE
[LOC] "「こんにちは, World!」" needs to be replaced with "Hello, World!"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/feedback#2296]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem** (if available).
![openxml](https://user-images.githubusercontent.com/40815708/71348521-0d8c6d00-25b0-11ea-951a-f0c418772374.png)

**Link to article:**
Tell us where exactly a problem occurs.
"https://docs.microsoft.com/ja-jp/dotnet/api/documentformat.openxml.wordprocessing.text?view=openxml-2.8.1"

**Problem:**
What's wrong with the article?
[LOC] "「こんにちは, World!」" needs to be replaced with "Hello, World!"

**Comment by Youssef1313** [comment]
@JasonCard, Hello, World is put in double quotes. Shouldn't it be prevented from localization by default ? Or it should be put between back ticks ?

**Comment by JasonCard** [comment]
@Youssef1313 Text within double quotes are localizable by default, so it's currently being over-localized by machine translation. Back ticks are usually use for inline code and not for display text. So I would recommend for content team to use the [no-loc syntax](https://review.docs.microsoft.com/en-us/help/contribute/markdown-reference?branch=master#non-localized-strings) to block to text from being localized. 

@nokura The affected article is from Office API reference, so could you please help to follow up on this feedback when you're back?

**Comment by TinaMcN** [comment]
@OfficeGlobal please uplift this Japanese article to human translation.

**Comment by hyoshioka0128** [comment]
@TinaMcN - Thank you for helping.

**Comment by OfficeGlobal** [comment]
Working on a fix

**Comment by OfficeGlobal** [comment]
@hyoshioka0128 , @TinaMcN the article has been updated and published live

**Comment by hyoshioka0128** [comment]
@TinaMcN @OfficeGlobal - Corrected.
Closed #2296.
Thanks.
