### ISSUE TITLE
[LOC] Back-Translation "try...キャッチ...finally ステートメント"→"Try…Catch…Finally ステートメント"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/feedback#2297]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem** (if available).
![finallystatement](https://user-images.githubusercontent.com/40815708/71348838-c6eb4280-25b0-11ea-84d0-4c6c5a0043b4.png)

**Link to article:**
Tell us where exactly a problem occurs.
"https://docs.microsoft.com/ja-jp/dotnet/api/system.codedom.codetrycatchfinallystatement?view=netframework-4.8"

**Problem:**
What's wrong with the article?
[LOC] Back-Translation "try...キャッチ...finally ステートメント"→"Try…Catch…Finally ステートメント"

**Comment by Youssef1313** [comment]
I've opened a PR in `dotnet/dotnet-api-docs` repo to fix this issue.

**Comment by mairaw** [comment]
Thanks @Youssef1313. It should take a few days until the localized content is updated. /cc @JasonCard

**Comment by JasonCard** [comment]
@hyoshioka0128 Thank you for reporting this issue and it's now fixed.
@Youssef1313 Thank you for addressing this issue with the PR!
@mairaw And thank you for letting me know :)
