### ISSUE TITLE
Deactivate auto translation

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#23]
It's the ****ing worst to read an technical article in broken German. Every **** developer knows how to read English.

There is not even a button for it anymore? Or is the only option just to manually edit every **** URL?

Ah and while I see it. Automatic translation is just bad.

----------
⚠ Idea migrated from UserVoice

**Created By:** Gordon A
**Created On:** 2018/02/22 12:56:09 +0000
**Votes at Migration:** 4
**Supporters at Migration:** 4

**Comment by dend** [comment]
@SonjaSaltzman FYI on the request.

**Comment by SonjaSaltzman** [comment]
@mkozioro and @botcrane you can switch your default language to English using the language picker on the bottom left of the site; this will set a cookie so any new pages will come up in English. 
@SunnyDeng and @dend fyi

**Comment by mkozioro** [comment]
Thanks. That button is in really bad place. My whole team couldn't find it without you. 

But... It still does not work correctly if you are searching azure articles using google.

**Comment by wudip** [comment]
I think there should be no translation at all for some less known languages (less known by the translator).

When I land on documentation translated to Czech (which is my mother tongue) I can't read a single sentence without thinking "What the hell they could say in English so it translated into this gibberish". Often I can't decode it anyway and just look at the english version.

Every Czech who doesn't understand English and tries to read the documentation is lost anyway. The last think he needs is automatically generated dada poetry. (I'm really serious, half of the translated sentences have no meaning at all.)

Please make not translating the default option with (or even without) possibility to turn the translation on.

BTW: @SonjaSaltzman Thanks for the button tip.

**Comment by SonjaSaltzman** [comment]
@wudip Thank you for your feedback.  We will have a new feature on the site in the next few weeks that will provide a very visible button so the user can switch back to english source text.  This will make it easier to switch back and forth. Regarding the quality:  some of our Czech content is fully human translated by native speakers, and some is partially machine translated (the disclaimer on top will state if the content is partially machine translated). If you find quality issues with our human translated content, I would be very interested to hear about it, especially if you could provide examples/explanations, so we can follow up.
@Sara-Nicolini FYI

**Comment by mkozioro** [comment]
Hi @SonjaSaltzman,
Would it be possible to store user preferred language in browser cookie to see pages in preferred language when getting into azure docs from Google search? I don't want to click "show in English" every time.

**Comment by SonjaSaltzman** [comment]
Hi @mkozioro, we understand your request and scenario. I am not sure how complex this is to implement, but we will look into it with our engineering team! 
@Sara-Nicolini FYI

**Comment by SonjaSaltzman** [comment]
@wudip thank you, it's great to know the human translations are of good quality. We will follow up on your request with google search.

**Comment by mkozioro** [comment]
Hi @SonjaSaltzman,
Do yo have any update about button to switch language to english source?
I found some message showing that text was translated by machine, but I'm not sure if this is new.

**Comment by SonjaSaltzman** [comment]
@mkozioro the button just went live :-).  It's on the right hand side, looks like a toggle switch.  It's right below the "Edit" and "Share" links.
FYI @Sara-Nicolini

**Comment by Powerhelmsman** [comment]
@SonjaSaltzman I can't find the switch. Can you paste a picture and sample content link?

**Comment by SonjaSaltzman** [comment]
Here is an example from hungarian; it only shows up on machine-translated content.
![toggle](https://user-images.githubusercontent.com/15201704/38574169-03818770-3cad-11e8-85b6-8074fcacb435.png)
Adding @SunnyDeng to check on the toggle for Azure MT content.

**Comment by SonjaSaltzman** [comment]
@mkozioro see above - if the content is human quality translation the toggle does not show up; it only shows up on machine translated content.  
@SunnyDeng can you please help check? Maybe we need to rebuild?

**Comment by SunnyDeng** [comment]
setting is on the way Loc Issue 15910

**Comment by mkozioro** [comment]
@SonjaSaltzman Hmm. That's funny. I found toggle button on other page (machine translated).  

That means that half pages I thought are machine translated were translated by humans. OMG. It means that after years of working in IT I've lost my ability to read documentation in Polish. At least with understanding :)

So I need to wait for an option to force language whatever language (en-us / pl-pl / etc) is in URL.
