### ISSUE TITLE
Link to Cognitive Services documentation

### ISSUE THREAD

**Issue by satonaoki** [MicrosoftDocs/feedback#230]
# Add a link from to https://docs.microsoft.com/en-us/azure/#pivot=products&panel=ai to https://docs.microsoft.com/en-us/azure/cognitive-services/welcome

## Issue Details

It seems that there is no way to navigate from Azure documentation page (https://docs.microsoft.com/en-us/azure/) to Cognitive Services documentation (https://docs.microsoft.com/en-us/azure/cognitive-services/welcome), although there are links to all services in Cognitive Services.

**Comment by dend** [comment]
@tysonn - how can we address this?

**Comment by tysonn** [comment]
@dend - Please assign to @cjgronlund for evaluation.

**Comment by cjgronlund** [comment]
#in-process

**Comment by cjgronlund** [comment]
@satonaoki - Good catch -- you make a very good point. We're planning a fix for this orphaned content in the very near future.

**Comment by dend** [comment]
This has been implemented.
