### ISSUE TITLE
コレクションをシェアできるようしてほしい

### ISSUE THREAD

**Issue by Mokudai-Masayuki** [MicrosoftDocs/feedback#2301]
作成したコレクションはtwitterやLinkedinでシェア出来ますが、 MS-Learn の中でもシェアできるとステキです。

・他人のコレクションを参考にすることで効率的な学習ができます
・人気度の高いコレクションに選ばれるように自分で厳選したくなります

The created collection can be shared on twitter and LinkedIn, but it is wonderful to be able to share on MS-Learn.

・ Efficient learning can be done by referring to others' collections
・ I want to carefully select myself so that it can be selected for a popular collection

**Comment by rootsmusic** [comment]
@Mokudai-Masayuki Idea adopted at https://techcommunity.microsoft.com/t5/microsoft-learn-blog/microsoft-learn-collections-now-support-docs-and-q-amp-a-content/ba-p/2549380
#please-close
