### ISSUE TITLE
I have some suggestions on C# Documentation about Async Await

### ISSUE THREAD

**Issue by HyVong007** [MicrosoftDocs/feedback#231]
I am learning C# Asynchronous Programming with Unity3D. I have read many times on your Documentation Website. And I think it will be very very easy to understand if you draw more visual Picture aka Info Graphic to help people understand !
Thank you so much for your helpful documentation ! 

Here is My Picture : https://drive.google.com/file/d/1KmNsjf5bQRVwdeqaIKobcdJQGPwP2FnN/view

The attached picture is my code in Unity3D to demo very basic of Async. If anything wrong please let me know. Thank ^_^

**Comment by dend** [comment]
@HyVong007 thank you for the feedback! 🎉

@mairaw thoughts on the above? Should this be moved to the .NET repo?

**Comment by mairaw** [comment]
@BillWagner is thinking about some improvements for the C# async await docs. He would be the best person to answer this.

**Comment by Powerhelmsman** [comment]
This issue is transferred to C# queue.
