### ISSUE TITLE
Power Query not open to pull requests

### ISSUE THREAD

**Issue by ADataGMan** [MicrosoftDocs/feedback#2312]
Please open up the [Power Query documentation](https://docs.microsoft.com/en-us/powerquery-m/) found in https://github.com/MicrosoftDocs/query-docs-pr/blob/live/query-languages/m to pull requests.

The basics are there, but it could benefit from help from the community, especially on the more complex parts of the language. This makes it much easier to champion as a power user when I know newbies can find the help they need.

**Comment by rootsmusic** [comment]
@ADataGMan If you're referring to Power Query documentation (not M), then its repository is at https://github.com/MicrosoftDocs/powerquery-docs/tree/main/powerquery-docs

**Comment by rootsmusic** [comment]
@ADataGMan Please move this issue to https://github.com/MicrosoftDocs/powerquery-docs/issues

**Comment by ADataGMan** [comment]
> @ADataGMan Please move this issue to https://github.com/MicrosoftDocs/powerquery-docs/issues

I don't have write permissions to both repos which [seems to be required](https://docs.github.com/en/issues/tracking-your-work-with-issues/transferring-an-issue-to-another-repository). Or at least I don't see any options for it in the UI to do so.

**Comment by rootsmusic** [comment]
@ADataGMan Since this isn't the right repository, I doubt the Power Query team will ever find this issue.  So you may want to close this issue and open it in https://github.com/MicrosoftDocs/powerquery-docs/issues
