### ISSUE TITLE
[LOC] Back-Translation "新規-ラベル"→"New-Label" 

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/feedback#2314]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem** (if available).
![new-label](https://user-images.githubusercontent.com/40815708/71565571-1bcc1300-2af3-11ea-94cf-2143722dc408.png)

**Link to article:**
Tell us where exactly a problem occurs.
"https://docs.microsoft.com/ja-jp/powershell/module/exchange/policy-and-compliance/new-label?view=exchange-ps"

**Problem:**
What's wrong with the article?
[LOC] Back-Translation "新規-ラベル"→"New-Label"

**Comment by SonjaSaltzman** [comment]
@RyanKing77 could you please take a look? If it's not in your content, let me know, I can provide a contact.

**Comment by SonjaSaltzman** [comment]
@TinaMcN

**Comment by TinaMcN** [comment]
@OfficeGlobal, please uplift this topic to human translation. @Soran-M FYI this is an MT overlocalization issue in PowerShell content.

**Comment by OfficeGlobal** [comment]
Working on a fix

**Comment by OfficeGlobal** [comment]
@hyoshioka0128 , @TinaMcN the article was HumanTranslated and published live

**Comment by hyoshioka0128** [comment]
@OfficeGlobal , @TinaMcN - Fixed.
Closed #2314.
Thanks.
