### ISSUE TITLE
[LOC] Back-Translation "新規-AuthRedirect"→"New-AuthRedirect"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/feedback#2315]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem** (if available).
![new-authredirect](https://user-images.githubusercontent.com/40815708/71565633-e116aa80-2af3-11ea-9330-08ce15909934.png)

**Link to article:**
Tell us where exactly a problem occurs.
"https://docs.microsoft.com/ja-jp/powershell/module/exchange/client-access-servers/new-authredirect?view=exchange-ps"

**Problem:**
What's wrong with the article?
[LOC] Back-Translation "新規-AuthRedirect"→"New-AuthRedirect"

**Comment by SonjaSaltzman** [comment]
@TinaMcN - I think this is in your content?

**Comment by TinaMcN** [comment]
@SonjaSaltzman, yes it is mine.   @OfficeGlobal, please uplift this topic to human translation.  @Soran-M FYI this is an MT overlocalization issue in PowerShell content.

**Comment by OfficeGlobal** [comment]
Working on a fix

**Comment by OfficeGlobal** [comment]
@hyoshioka0128 , @TinaMcN the article was HumanTranslated and published live

**Comment by hyoshioka0128** [comment]
@OfficeGlobal , @TinaMcN - Fixed.
Closed #2315.
Thanks.
