### ISSUE TITLE
[LOC] Back-Translation "新規-Spwork Managementserviceapplication"→"New-Spwork Managementserviceapplication"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/feedback#2317]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem** (if available).
![new-spworkmanagementserviceapplication](https://user-images.githubusercontent.com/40815708/71565697-bda02f80-2af4-11ea-823a-60935d65e659.png)

**Link to article:**
Tell us where exactly a problem occurs.
"https://docs.microsoft.com/ja-jp/powershell/module/sharepoint-server/new-spworkmanagementserviceapplication?view=sharepoint-ps"

**Problem:**
What's wrong with the article?
[LOC] Back-Translation "新規-Spwork Managementserviceapplication"→"New-Spwork Managementserviceapplication"

**Comment by TinaMcN** [comment]
@OfficeGlobal, please uplift this topic to human translation. @Soran-M FYI this is an MT overlocalization issue in PowerShell content.

**Comment by OfficeGlobal** [comment]
Working on a fix

**Comment by OfficeGlobal** [comment]
@hyoshioka0128 , @TinaMcN the article was HumanTranslated and published live

**Comment by hyoshioka0128** [comment]
@OfficeGlobal , @TinaMcN - Fixed.
Closed #2317.
Thanks.
