### ISSUE TITLE
[LOC] Back-Translation "新規作成-AddressList"→"New-AddressList"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/feedback#2319]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem** (if available).
![new-addresslist](https://user-images.githubusercontent.com/40815708/71565790-7bc3b900-2af5-11ea-83fa-0b1cda50e46c.png)

**Link to article:**
Tell us where exactly a problem occurs.
"https://docs.microsoft.com/ja-jp/powershell/module/exchange/email-addresses-and-address-books/new-addresslist?view=exchange-ps"

**Problem:**
What's wrong with the article?
[LOC] Back-Translation "新規作成-AddressList"→"New-AddressList"

**Comment by Youssef1313** [comment]
The header fix is easy using the no-loc syntax.
But localization **inside code block** seems like a bug to me.
/cc @JasonCard

**Comment by JasonCard** [comment]
@RyanKing77 this one is also related to [https://github.com/MicrosoftDocs/feedback/issues/2313](https://github.com/MicrosoftDocs/feedback/issues/2313) for PowerShell loc.

**Comment by SonjaSaltzman** [comment]
@RyanKing77 this may be in @TinaMcN content - please assign to her as needed

**Comment by TinaMcN** [comment]
@SonjaSaltzman, yes it is mine. @OfficeGlobal, please uplift this topic to human translation. @Soran-M FYI this is an MT overlocalization issue in PowerShell content.  We should also log a bug for the MT tool team to look into.

**Comment by OfficeGlobal** [comment]
Working on a fix

**Comment by OfficeGlobal** [comment]
@hyoshioka0128 , @TinaMcN the article was HumanTranslated and published live

**Comment by hyoshioka0128** [comment]
@OfficeGlobal , @TinaMcN - Fixed.
Closed #2319.
Thanks.
