### ISSUE TITLE
404 to access iOS API docs

### ISSUE THREAD

**Issue by spouliot** [MicrosoftDocs/feedback#232]
# Idea Title

https://docs.microsoft.com/en-ca/xamarin/ios/

links to 

https://developer.xamarin.com/404?link=%2Fapi%2Froot%2Fmonotouch-lib%2F

for *iOS API docs* (bottom)

## Issue Details

404

**Comment by spouliot** [comment]
A correct link is https://developer.xamarin.com/api/root/ios-unified/

**Comment by Powerhelmsman** [comment]
@Khairunj Can you correct the link?

**Comment by dend** [comment]
@conceptdev is already on the case! 🎉

Thanks @spouliot for the report 👍

**Comment by conceptdev** [comment]
fixed!

**Comment by Powerhelmsman** [comment]
@conceptdev Thanks for quickly fixing. I verified that it works. So close it. 
@spouliot Again thanks for the report.
