### ISSUE TITLE
[LOC] Back-Translation "新規-AddressRewriteEntry"→"New-AddressRewriteEntry"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/feedback#2320]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem** (if available).
![new-addressrewriteentry](https://user-images.githubusercontent.com/40815708/71565837-d4935180-2af5-11ea-8d4a-4efaab1cfead.png)

**Link to article:**
Tell us where exactly a problem occurs.
"https://docs.microsoft.com/ja-jp/powershell/module/exchange/mail-flow/new-addressrewriteentry?view=exchange-ps"

**Problem:**
What's wrong with the article?
[LOC] Back-Translation "新規-AddressRewriteEntry"→"New-AddressRewriteEntry"

**Comment by TinaMcN** [comment]
@OfficeGlobal, please uplift this topic to human translation. @Soran-M FYI this is an MT overlocalization issue in PowerShell content.

**Comment by OfficeGlobal** [comment]
Working on a fix

**Comment by OfficeGlobal** [comment]
@hyoshioka0128 , @TinaMcN the article was HumanTranslated and published live

**Comment by hyoshioka0128** [comment]
@OfficeGlobal , @TinaMcN - Fixed.
Closed #2320.
Thanks.
