### ISSUE TITLE
[LOC] Back-Translation "新規-SPExcelServiceApplication"→"New-SPExcelServiceApplication"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/feedback#2321]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem** (if available).
![new-spexcelserviceapplication](https://user-images.githubusercontent.com/40815708/71565876-33f16180-2af6-11ea-9da1-2cb5bba145bd.png)

**Link to article:**
Tell us where exactly a problem occurs.
"https://docs.microsoft.com/ja-jp/powershell/module/sharepoint-server/new-spexcelserviceapplication?view=sharepoint-ps"

**Problem:**
What's wrong with the article?
[LOC] Back-Translation "新規-SPExcelServiceApplication"→"New-SPExcelServiceApplication"

**Comment by TinaMcN** [comment]
@OfficeGlobal, please uplift this topic to human translation. @Soran-M FYI this is an MT overlocalization issue in PowerShell content. I logged a bug for the MT team to investigate but as they are unlikely to fix soon we should human translate this.

**Comment by OfficeGlobal** [comment]
Working on a fix

**Comment by OfficeGlobal** [comment]
@hyoshioka0128 , @TinaMcN the article was HumanTranslated and published live

**Comment by hyoshioka0128** [comment]
@OfficeGlobal , @TinaMcN - Fixed.
Closed #2321.
Thanks.
