### ISSUE TITLE
[LOC] Back-Translation "新規-SPExcelBIServer"→"New-SPExcelBIServer"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/feedback#2322]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem** (if available).
![new-spexcelbiserver](https://user-images.githubusercontent.com/40815708/71565966-d578b300-2af6-11ea-9409-77198be159e1.png)

**Link to article:**
Tell us where exactly a problem occurs.
"https://docs.microsoft.com/ja-jp/powershell/module/sharepoint-server/new-spexcelbiserver?view=sharepoint-ps"

**Problem:**
What's wrong with the article?
[LOC] Back-Translation "新規-SPExcelBIServer"→"New-SPExcelBIServer"

**Comment by TinaMcN** [comment]
@OfficeGlobal please human translate the article.  @Soran-M FYI, MT issue in PowerShell content.  @TinaMcN

**Comment by OfficeGlobal** [comment]
Working on a fix

**Comment by OfficeGlobal** [comment]
@hyoshioka0128 article was HumanTranslated and published live. The issue is fixed

**Comment by hyoshioka0128** [comment]
@OfficeGlobal - Fixed.
Closed #2322.
Thanks.
