### ISSUE TITLE
Install the Azure AD Module

### ISSUE THREAD

**Issue by Dird** [MicrosoftDocs/feedback#2324]
https://docs.microsoft.com/en-us/previous-versions/azure/jj151815(v=azure.100)?redirectedfrom=MSDN

It says you need to download the 64 bit option but the link goes to "Microsoft Connect Has Been Retired"

**Comment by mlottner** [comment]
@Dird Thanks for taking the time to give us feedback and contribute to our community. 
As noted, the product page you referenced is no longer being updated or maintained.  Check  [Microsoft Product Lifecycle](https://support.microsoft.com/lifecycle/selectindex) for information about how that product, service, technology, or API is supported.
I'm closing this issue for now as prior versions no longer receive documentation updates.
