### ISSUE TITLE
Azure MXChip IoT DevKit Get Started dead link in Next Steps

### ISSUE THREAD

**Issue by alparamonov** [MicrosoftDocs/feedback#2326]
**Link to article:**
https://docs.microsoft.com/en-us/samples/azure-samples/mxchip-iot-devkit-get-started/sample/

**Problem:**
In the very bottom of the article, the first link in the "Next Steps" section leads to 404.

Connect IoT DevKit to your Azure IoT Central application
https://docs.microsoft.com/en-us/azure/iot-central/howto-connect-devkit

**Comment by mlottner** [comment]
@dominicbetts can you take a look at this?

**Comment by dominicbetts** [comment]
@alparamonov - thanks for reporting this.

I fixed an error in the redirect file: https://github.com/MicrosoftDocs/azure-docs-pr/pull/100165

As soon as the PR is merged the link will be working again.

FYI, the correct link is: https://docs.microsoft.com/azure/iot-central/core/howto-connect-devkit/

**Comment by dominicbetts** [comment]
#please-close
