### ISSUE TITLE
Very minor typo in sGet-AzureADApplicationProxyConnectorGroupMembers

### ISSUE THREAD

**Issue by Zarniwoop42** [MicrosoftDocs/feedback#2334]
Link: 
https://docs.microsoft.com/en-us/powershell/module/azuread/?view=azureadps-2.0#azuread

Problem:
"sGet-AzureADApplicationProxyConnectorGroupMembers" should probably be "Get-AzureADApplicationProxyConnectorGroupMembers"

**Comment by rootsmusic** [comment]
Fixed.
#please-close
