### ISSUE TITLE
MSDN Magazine Archive

### ISSUE THREAD

**Issue by vbjay** [MicrosoftDocs/feedback#2337]
Please provide a master download to download all code and all magazines or even a way to select which issues to download the code and magazines as a zip.  

See https://docs.microsoft.com/en-us/archive/msdn-magazine/msdn-magazine-issues

**Comment by vbjay** [comment]
Or just post on github a repo with all code and all magazines.

**Comment by mlottner** [comment]
@vbjay Thanks for taking the time to reach out and make your request. 
Before closing this issue, I flagged your request internally to a member of our team for awareness, but as the content is no longer under support, dev resources to extract and offer the content in other formats are limited. 
Appreciate your contribution to our community.
