### ISSUE TITLE
The "Field Name" listed in the tables & Screenshots show the name in the wrong case in many areas on https://docs.microsoft.com/en-us/azure/iot-central/core/tutorial-define-device-type

### ISSUE THREAD

**Issue by Jeff-Schafer** [MicrosoftDocs/feedback#2339]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem** (if available).

**Link to article:**
https://docs.microsoft.com/en-us/azure/iot-central/core/tutorial-define-device-type

**Problem:**
When actually running the IoT Central, "**Field Name**" IS case-sensitive & needs to match the "**Display Name**".
Using the wrong case will make it fail.

There are many areas on this page that show the "**Field Name**" has a lowercase first letter & the "**Display Name**" has an uppercase first letter.

There may be many others on this page, but here are 4 of them (in both the table & Screenshot):
 -- temperature
 -- fanmotorerr
 -- fanmode
 -- setTemperature

**Comment by mlottner** [comment]
@dominicbetts Can you take a look?

**Comment by mlottner** [comment]
@Jeff-Schafer Thanks for taking the time to leave us feedback. I've flagged the issue to a member of the IoT docs team for awareness and potential resolution. 

Appreciate your contribution to our community.

**Comment by dominicbetts** [comment]
Hi @Jeff-Schafer - can you clarify where you're seeing an error in your IoT Central application when you follow this tutorial? The **Field Names** are case-sensitive and need to match the field names in any device code - such as the sample code shown in https://docs.microsoft.com/azure/iot-central/core/tutorial-add-device. The **Display Names** are not case-sensitive and are only used as labels in the IoT Central UI.
Thanks, Dominic

**Comment by Jeff-Schafer** [comment]
It was failing to draw the chart.
I was told the Field Name & Display Name fields have to match.
Once I did this, the chart was drawn.

If the Display Name is not case-sensitive, but the Field Name is, the required format should be displayed.

Also, the link you mention is not the correct one.
It is https://docs.microsoft.com/en-us/azure/iot-central/core/tutorial-define-device-type.

If these are User Defined, they should **not** be case-sensitive.

An example from the link above:

Setting | Value
Display Name | Temperature
Field Name | temperature

The Screenshot for this example is https://docs.microsoft.com/en-us/azure/iot-central/core/media/tutorial-define-device-type/temperaturesimulation.png.

There are also many others on this page.

**Comment by dominicbetts** [comment]
Hi @Jeff-Schafer - apologies, I must be missing something. To test things out I created a device template with three telemetry types:

| Display Name | Field Name |
| --------------- | -------------|
| Humidity | Humidity |
| Temperature | temperature |
| External Temperature |  somethingelse |

I then added a chart to the dashboard for the device template to plot the three telemetry values over the last 30 minutes. All three values show up as expected for me, using the display names as labels:
![dashboard](https://user-images.githubusercontent.com/1454644/71890768-eea7e200-313c-11ea-8721-d6db471e358d.png)

If I then skipped ahead to the 5th tutorial [Add a device](https://docs.microsoft.com/en-us/azure/iot-central/core/tutorial-add-device), I would have to make sure that my Node.js code sent three telemetry values called: **Humidity**, **temperature**, and **somethingelse**. It's the names of the fields in the telemetry message sent by a device that must exactly match the field names defined in the device template.

Can you tell me where you heard that the **Display Name** and **Field Name** must match?

**Comment by Jeff-Schafer** [comment]
Hi @dominicbetts - I found out that we are using different IoT Central Sample Apps which have the first letter in uppercase for the "**Field Name**" & that's why it isn't consistent with this tutorial: https://docs.microsoft.com/en-us/azure/iot-central/core/tutorial-define-device-type.

Closing bug.

**Comment by dominicbetts** [comment]
@Jeff-Schafer - thanks for letting me know.
