### ISSUE TITLE
ERROR:  The documentation [1] recommends API version 2018-02-14 but the API returns 'The api-version '2018-02-14' is invalid.'​

### ISSUE THREAD

**Issue by mhunter77** [MicrosoftDocs/feedback#2341]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem** (if available).

**Link to article:**
https://docs.microsoft.com/en-us/rest/api/keyvault/vaults/list​

**Problem:**
What's wrong with the article?

The customer was using the following link to create the "List operation gets information about the vaults associated with the subscription".
     https://docs.microsoft.com/en-us/rest/api/keyvault/vaults/list​
​
​
Vaults - List​
Service:​
Key Vault ​
API Version:​
2018-02-14 ​
The List operation gets information about the vaults associated with the subscription.​
https://docs.microsoft.com/en-us/rest/api/keyvault/vaults/list​
​
​
     GET https://management.azure.com/subscriptions/{subscriptionId}/resources?$filter=resourceType eq 'Microsoft.KeyVault/vaults'&api-version=2018-02-14​
​
​
He replaced subscription value and ran the following rest api​
     GET https://management.azure.com/subscriptions/{65a04671-4180-4c63-b369-b436bf19bafe}/resources?$filter=resourceType eq 'Microsoft.KeyVault/vaults'&api-version=2018-02-14​
​
​
     ERROR:  The documentation [1] recommends API version 2018-02-14 but the API returns 'The api-version '2018-02-14' is invalid.'​
​
​
The customer said that the error then gave some newer valid version of the api.  He changed the command to use the newer version of the api and it worked successfully.​
​
ACTION PLAN ​
----------------​
​
The customer would like me to file a doc bug.​

**RELATED ISSUES**

Documented REST API versions don't match REST API versions the service reports as available #1205 
Open 
amclin opened this issue on Feb 25, 2019
https://github.com/MicrosoftDocs/feedback/issues/1205

Make API documentation more version aware #226
https://github.com/MicrosoftDocs/feedback/issues/226

**Comment by mhunter77** [comment]
Please try the following:  
https://docs.microsoft.com/en-us/rest/api/keyvault/vaults/

**Comment by mhunter77** [comment]
This issue appears to have been fixed.  

a.)  I looked at https://docs.microsoft.com/en-us/rest/api/keyvault/vaults/get and https://docs.microsoft.com/en-us/rest/api/keyvault/vaults/list .   The page and the command reflect the current api-version=2019-09-01

**Comment by rootsmusic** [comment]
#please-close
