### ISSUE TITLE
Wrong macro name in example of "DPI-related APIs and registry settings"

### ISSUE THREAD

**Issue by EmmettTsai** [MicrosoftDocs/feedback#2343]
**Link to article:**
https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/dpi-related-apis-and-registry-settings#primary-display-native-resolution

**Problem:**
What's wrong with the article?
The example in primary-display-native-resolution part display wrong macro name VERZRES, the correct name is VERTRES.

reference:
https://docs.microsoft.com/en-us/windows/win32/api/wingdi/nf-wingdi-getdevicecaps

**Comment by mlottner** [comment]
@EmmettTsai Thanks for taking the time to share your feedback. 
I've flagged this issue to a member of our Windows doc team for awareness and possible resolution. 
Appreciate your contribution to our docs user community. 
@GrantMeStrength Can you please take a look and reassign as/if needed?

**Comment by GrantMeStrength** [comment]
Thank you! I made the correction and the doc should be updated soon. Thanks again for taking the time.

-john
