### ISSUE TITLE
Missing nuget install for required dependency

### ISSUE THREAD

**Issue by markolbert** [MicrosoftDocs/feedback#2346]
This is on https://docs.microsoft.com/en-us/graph/tutorials/dotnet-core?tutorial-step=1

The instructions about installing the various dependencies do not appear to explain how to install Microsoft.Graph.Auth which, as of today, is still in pre-release.

**Comment by mlottner** [comment]
@markolbert Thanks for your feedback. 
Official documentation is typically added when features are released in either public preview or general availability. Is that the scenario you are reporting on?

**Comment by Lauragra** [comment]
@jasonjoh , can you please investigate? @mlottner , please add Jason to the Assigned list. Thanks.

**Comment by markolbert** [comment]
Hi @mlottner. My point is that the instructions, as currently written, are incomplete because they do not describe how to install the Microsoft.Graph.Auth dependency. It is in pre-release but that's not the issue: there are no installation instructions for it. Granted, those instructions are different because it is in pre-release (e.g., if done through the VS nuget package manager you need to tick the pre-release box). But regardless I think there should be some description of what's needed to install the package, even when it is in pre-release.

**Comment by mlottner** [comment]
@markolbert We've assigned a member of that docs team to take a look and investigate your request. They will update here soon. Thanks again for your insights.

**Comment by jasonjoh** [comment]
This tutorial does not use that package, so I'm confused. @markolbert are you hitting an error somewhere?

**Comment by markolbert** [comment]
LOL! No, it turns out it's a superfluous package...which is still referenced in the documentation (green arrow, from Step 1; red arrow shows that the package is not referenced in the package installation instructions):

![graph-auth](https://user-images.githubusercontent.com/9095610/72019654-f8097b00-321e-11ea-9fd4-f243a68e3b8e.png)

But if you slavishly follow the instructions, as I did, you'll find you need to search prerelease packages. From the package's github page:

![auth-prerelease](https://user-images.githubusercontent.com/9095610/72019838-49196f00-321f-11ea-920a-e17cffd9bbd3.png)

You probably just need to delete the reference to the unneeded prerelease package.

**Comment by jasonjoh** [comment]
Doh! Nice catch. Yes that bullet item is indeed unnecessary. I think I copied that block from another tutorial and just never removed it. Filed an issue on the tutorial repo to fix it.

**Comment by mlottner** [comment]
@markolbert @jasonjoh Thank you both for contributions in getting this resolved. 
Closing this issue as it has been flagged internally for a fix. 

Appreciate your help!
