### ISSUE TITLE
appsettings.json must be set to copy

### ISSUE THREAD

**Issue by markolbert** [MicrosoftDocs/feedback#2347]
This is on https://docs.microsoft.com/en-us/graph/tutorials/dotnet-core?tutorial-step=3

The properties of appsettings.json must be set to Copy Always or Copy If Newer. Otherwise when the app runs it won't find the file in the executable directory and it'll abort.

**Comment by mlottner** [comment]
@markolbert 
Thanks for taking the time to share your feedback. 
I've flagged this issue for a member of the Microsoft Graph content owner for awareness and possible adjustment. Appreciate your contribution to our docs community!
@Lauragra Can you please take a look?

**Comment by Lauragra** [comment]
@mlottner , please assign to @jasonjoh .

**Comment by mlottner** [comment]
Thanks @Lauragra! @jasonjoh can you please take a look?

**Comment by jasonjoh** [comment]
@markolbert can you provide more information? I'm not sure where those settings live.

**Comment by markolbert** [comment]
@jasonjoh, when I created the appsettings.json file within VS 2019 (latest stable) using Add Item (note that in the following image the file name is different because I already have an appsettings.json file, but the name should be irrelvant):

![json-file](https://user-images.githubusercontent.com/9095610/72018918-77964a80-321d-11ea-8de0-93996158d28b.png)

the resulting file's properties are default to Do Not Copy:

![do-not-copy](https://user-images.githubusercontent.com/9095610/72018961-8bda4780-321d-11ea-96e1-0e8870e5abf7.png)

which means the file -- appsettings.json -- won't get copied into the bin directory, which causes the app to fail when it runs because there's no appsettings.json file to read for configuration information.

**Comment by jasonjoh** [comment]
Ah ok, interesting. The tutorial uses command line and a text editor (VS Code) and isn't based on Visual Studio, primarily to make it easier to consume cross-platform, so I never ran into this particular problem. I'm happy to add a callout here for folks that use Visual Studio as their editor.

Out of curiosity, did you create the project with the Visual Studio wizard as well?

**Comment by markolbert** [comment]
Nope, I did it the old-fashioned way, manually :)

**Comment by jasonjoh** [comment]
Ok, so dotnet new from the command line, then open the csproj in VS Studio, gotcha. Filed an issue on the tutorial repo to add a callout.

**Comment by markolbert** [comment]
LOL! No, even more old school than that: I created a new, empty project within VS and then added the files to it. I've never used dotnet new SFAIK.

**Comment by jasonjoh** [comment]
I ended up refactoring how the app ID is stored, removing the dependency on appsettings.json. It now stores it in the development secret store (`dotnet user-secrets`). For Visual Studio, there's a "Manage User Secrets" menu option when you right-click the project that let's you add values. Please check out the updated tutorial.

**Comment by markolbert** [comment]
Looks good. Thanx!
