### ISSUE TITLE
Broken format in Calendar(Teams + isOnlineMeeting: true). Create from API

### ISSUE THREAD

**Issue by cln-m4rie** [MicrosoftDocs/feedback#2348]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem** (if available).
correct:
<img width="578" alt="スクリーンショット 2020-01-08 15 20 46" src="https://user-images.githubusercontent.com/16286987/71955020-77e91280-322a-11ea-9c6b-86f0a017bfe1.png">

broken:
<img width="590" alt="スクリーンショット 2020-01-08 15 38 37" src="https://user-images.githubusercontent.com/16286987/71956025-50e01000-322d-11ea-80a8-4e64c51a721c.png">

**Link to article:**
Tell us where exactly a problem occurs.
https://github.com/microsoftgraph/microsoft-graph-docs.ja-JP/blob/master/api-reference/beta/resources/event.md

**Problem:**
What's wrong with the article?

If `"isOnlineMeeting": true` and `body` property not set or
```
"Body": {
    "ContentType": "TEXT",
    "Content": "",
}
```

format is broken.

So, if `"isOnlineMeeting": true`, `"Body.ContentType": "HTML"` property should be required.

**Comment by mlottner** [comment]
@cln-m4rie Thanks for taking the time to share your feedback. I've flagged this issue for a member of our Microsoft Graph docs team for their awareness and possible fix. 
Appreciate your contribution to our community. 
@Lauragra Can you take a look?

**Comment by Lauragra** [comment]
@cln-m4rie , can you please post the issue using the feedback mechanism on the en-us page: https://docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-beta#feedback? @angelgolfer-ms , FYI.

**Comment by mlottner** [comment]
@cln-m4rie I'm closing this issue here. Please re-open the issue it on the [page feedback link](https://docs.microsoft.com/graph/api/resources/event?view=graph-rest-beta#feedback) given above in order to alert the page author and possible resolution. 
Thanks again for your contribution to our docs community!
