### ISSUE TITLE
Need PowerShell code examples in AD LDS Getting Started Step-by-Step Guide

### ISSUE THREAD

**Issue by jwpmacys** [MicrosoftDocs/feedback#235]
Need PowerShell code examples in AD LDS Getting Started Step-by-Step Guide

DSACLS.EXE and LDP.EXE may be deprecated in the future.  PowerShell code examples are needed.

## Issue Details
Example
Step 6: Practice Managing Authorization
https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/cc772541(v%3dws.10)

No PowerShell code examples exist and there is no equivalent doc for Windows 2012, 2012 R2 nor 2016 using PowerShell.

**Comment by dend** [comment]
Hi @jwpmacys - this content is archived and no longer supported. If you have a specific request about samples on content on docs.microsoft.com, make sure to open an issue by using the link to documentation feedback in the article footer.
