### ISSUE TITLE
404, page not found

### ISSUE THREAD

**Issue by sameersayani** [MicrosoftDocs/feedback#2350]
https://docs.microsoft.com/en-us/archive/blogs/b/webdev/archive/sending-webhooks-with-asp-net-webhooks-preview.aspx

**Comment by mlottner** [comment]
@sameersayani Thanks for taking the time to report this issue. 
Unfortunately, broken links in docs and pages like this that are archived and no longer actively maintained are unavoidable as old related pages and links are removed and deprecated. Make sure to use current, maintained product versions with active service to avoid this issue.
