### ISSUE TITLE
Typo of Provisioning Package sample command

### ISSUE THREAD

**Issue by Lapivy** [MicrosoftDocs/feedback#2351]
The sample commands at the following sites use environment-dependent characters and cannot be executed correctly. (typo is "-")

https://docs.microsoft.com/en-us/archive/blogs/beanexpert/how-to-install-office-using-a-provisioning-package

PowerShell.exe –ExecutionPolicy Unrestricted .\Start-ProvisioningCommands.ps1 (from docs)
PowerShell.exe -ExecutionPolicy Unrestricted .\Start-ProvisioningCommands.ps1 (correct command)

**Comment by mlottner** [comment]
@Lapivy Thanks for taking the time to leave your feedback. 
As noted in the page you linked, that version of the site is archived and is no longer under active maintenance or kept updated. 
Make sure to use and refer to active products with current service agreements to ensure you are using our most  accurate content.
