### ISSUE TITLE
Notifications only occur under Modern Standby when the device lid is open, not when it is shut.

### ISSUE THREAD

**Issue by domcote** [MicrosoftDocs/feedback#2353]
https://docs.microsoft.com/en-us/windows-hardware/design/device-experiences/audio-notifications?source=docs States you receive an audio notification while the device is in modern standby. This only  occurs when the device's lid is open, not when it is shut. Same applies to Skype calls, btw. Documentation ought to reflect this.

**Comment by mlottner** [comment]
@domcote Thanks for taking the time to leave docs feedback. 
I've flagged this issue for a member of the Windows docs team for awareness and potential fix. 
Appreciate your contribution to the docs community. 
@GrantMeStrength Please take a look and re-assign as needed.

**Comment by GrantMeStrength** [comment]
The documentation has been updated to reflect this. Thank you!
