### ISSUE TITLE
ipv6

### ISSUE THREAD

**Issue by fragstone** [MicrosoftDocs/feedback#2354]
Hello,

https://social.technet.microsoft.com/ is not available in the "normal" internet.
it has only an ipv4 (lagacy network) availibity.

will you change it?

# host social.technet.microsoft.com
social.technet.microsoft.com is an alias for social.msdn.microsoft.com.edgekey.net.
social.msdn.microsoft.com.edgekey.net is an alias for e10000.g.akamaiedge.net.
e10000.g.akamaiedge.net has address 23.196.245.188

regards
Thomas

**Comment by rootsmusic** [comment]
@fragstone TechNet forums have closed at https://docs.microsoft.com/en-us/teamblog/msdn-technet-english-forums-closure
