### ISSUE TITLE
ClientRolePrincipal listed as IPrincipal implementation in .NET Standard 2.0

### ISSUE THREAD

**Issue by abalaci** [MicrosoftDocs/feedback#2358]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem** (if available).

**Link to article:**
https://docs.microsoft.com/en-us/dotnet/api/system.security.principal.iprincipal?view=netstandard-2.0

**Problem:**
The ```IPrincipal``` interface is described as being implemented by ```ClientRolePrincipal``` in .NET Standard 2.0, but the class is not available in that API version: https://docs.microsoft.com/en-us/dotnet/api/system.web.clientservices.clientroleprincipal?view=netframework-4.8&viewFallbackFrom=netstandard-2.0.

![Screenshot_2020-01-09 ClientRolePrincipal Class (System Web ClientServices)](https://user-images.githubusercontent.com/47945400/72062785-23549e80-32e1-11ea-9733-dec4e28272ab.png)

**Comment by rootsmusic** [comment]
@abalaci Please move this issue to https://github.com/dotnet/dotnet-api-docs/issues

**Comment by abalaci** [comment]
Moved to https://github.com/dotnet/dotnet-api-docs/issues/6948.

**Comment by rootsmusic** [comment]
#please-close
