### ISSUE TITLE
Automatic translation for articles must be optional.

### ISSUE THREAD

**Issue by bkaankose** [MicrosoftDocs/feedback#236]
# Idea Title

Automatic translate of context is redundant or must be optional.

## Issue Details

I am from Turkey and no matter how good the translator translates the article, I want to see the article in English which is the default language of the article most of the time. I had to go to the bottom of the page, change the language and go back to top in order to start reading it.

Also as far as I know this applies all the Microsoft related sites, so Docs is not the only service for this issue. Users must be able to disable this auto translation.

**Comment by dend** [comment]
Duplicate of #23
