### ISSUE TITLE
404 not found

### ISSUE THREAD

**Issue by sameersayani** [MicrosoftDocs/feedback#2363]
https://docs.microsoft.com/en-us/archive/blogs/b/webdev/archive/sending-webhooks-with-asp-net-webhooks-preview.aspx

Above link is not working. Has .NET stopped Webhooks or is there any alternate?

Please update me on this as I need to work on Webhooks.

Regards,
Sameer

**Comment by mairaw** [comment]
I believe this is the blog post you're looking for: https://devblogs.microsoft.com/aspnet/sending-webhooks-with-asp-net-webhooks-preview/

Was this an URL redirection from another URL @sameersayani?

**Comment by sameersayani** [comment]
Absolutely !
Thanks for sharing.

Regards,
Sameer

**Comment by gewarren** [comment]
#please-close
