### ISSUE TITLE
The version drop downs in the breaking changes page are almost invisible in dark theme

### ISSUE THREAD

**Issue by mairaw** [MicrosoftDocs/feedback#2369]
_From @divega on Thursday, September 19, 2019 6:07:49 PM_

Text is black over dark gray background. Only the selection rect is visible.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b0fe0b7-01c9-d11e-a432-b7ac4639f51c
* Version Independent ID: 9e7f5a4a-13dd-dc9a-9ba7-1208bdbe6c4f
* Content: [.NET Core breaking changes](https://docs.microsoft.com/en-us/dotnet/core/compatibility/breaking-changes)
* Content Source: [docs/core/compatibility/breaking-changes.md](https://github.com/dotnet/docs/blob/master/docs/core/compatibility/breaking-changes.md)
* Product: **dotnet-core**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

_Copied from original issue: dotnet/docs#14517_

**Comment by mairaw** [comment]
_From @mairaw on Friday, September 20, 2019 10:40:05 PM_

Good point @divega! I'll send this to our engineering team.

**Comment by mairaw** [comment]
_From @gewarren on Friday, November 1, 2019 4:17:14 PM_

They're unusable in the "high contrast" theme. Black text on a black background.

**Comment by mairaw** [comment]
@adkinn can you look at this issue?

![image](https://user-images.githubusercontent.com/12971179/72190386-400dd680-33b4-11ea-9df4-5e80be8ae204.png)

**Comment by adkinn** [comment]
@mairaw yep, we'll take care of it: https://ceapex.visualstudio.com/Engineering/_workitems/edit/161709

**Comment by mairaw** [comment]
Thank you @adkinn!

**Comment by mairaw** [comment]
Closing this as fixed.
