### ISSUE TITLE
Drive letter change in "Copy partition to network"

### ISSUE THREAD

**Issue by manojpenzlar5** [MicrosoftDocs/feedback#237]
# Idea Title
Drive letter change in "Copy partition to network share"

## Issue Details
![capture](https://user-images.githubusercontent.com/28995661/37511699-d1b5e96a-2925-11e8-9db2-5d6d989b1fbe.JPG)
The "my-windows-partition.wim" file is located in C: dir & is fine. But in the second line for copying "my-system-partition" it is mentioned as C: again. But I think it should be S:/. If it is yes, please change it to S: which will be very helpful for the reader like us :). 

Add a detailed explanation of what is wrong or what you want implemented. Images and rich content is welcome!

**Comment by dend** [comment]
@manojpenzlar5 can you please link to the article that has this issue?

**Comment by dend** [comment]
Ping @manojpenzlar5 - can you clarify where the issue was present?

**Comment by Powerhelmsman** [comment]
Close as no enough information.
