### ISSUE TITLE
Typo in PSMemberTypes Enum page

### ISSUE THREAD

**Issue by eiranling** [MicrosoftDocs/feedback#2373]
**Link to article:**
https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.psmembertypes?view=pscore-6.2.0

**Problem:**
In the NoteProperty description on the PSMemberTypes Enum page in the Fields table, `prorperty` should be `property`

**Comment by mairaw** [comment]
@sdwheeler can you help here?

**Comment by sdwheeler** [comment]
I have copied this issue to https://github.com/MicrosoftDocs/PowerShell-Docs/issues/5704. I will respond to it there.

@mairaw #please-close
