### ISSUE TITLE
Can not register for "Office 365 Champions Program" from Germany

### ISSUE THREAD

**Issue by Frank4CRM** [MicrosoftDocs/feedback#2374]
Hello, wanted register for "Office 365 Champions Program" https://aka.ms/O365Champions. But can not register there when I am living in Germany, cause the country choice list does NOT contain Germany.

from: 
**To Reproduce**
1. Go to 'https://docs.microsoft.com/en-us/office365/customlearning/champ_o365program'
2. Click on 'https://aka.ms/O365Champions'
3. The shorten Link lead to 'https://www.microsoft.com/en-us/microsoft-365/success/champions?rtc=1' 
4. Can not register in that form, cause 'Country*' list NOT contain "Germany"

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by rootsmusic** [comment]
@Frank4CRM Please ask program support or in support forums.  On https://adoption.microsoft.com/become-a-champion/ , there's a light bulb symbol (next to the page slider) to leave feedback.
#please-close
