### ISSUE TITLE
New-AzureRmSqlDatabaseimport, missing values

### ISSUE THREAD

**Issue by JJussi** [MicrosoftDocs/feedback#2375]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem** (if available).

**Link to article:**
https://docs.microsoft.com/en-us/powershell/module/azurerm.sql/new-azurermsqldatabaseimport?view=azurermps-6.13.0

**Problem:**
-Edition parameter description value list don't have all the possibilities. At least "GeneralPurpose" is missing.
-ServiceObjectiveName parameter should have table (or at least link to the table) of possible combinations against -Edition values.

**Comment by rootsmusic** [comment]
@JJussi Please move this issue to https://github.com/Azure/azure-powershell/issues

**Comment by JJussi** [comment]
The AzureRM module has been replaced by the Az module
