### ISSUE TITLE
Decimal: Wrong max values in german translation

### ISSUE THREAD

**Issue by Skosn** [MicrosoftDocs/feedback#2377]
https://docs.microsoft.com/de-de/dotnet/api/system.decimal?view=netframework-4.8#hinweise

First line in Hinweise

Der Decimal Werttyp stellt Dezimalzahlen zwischen positiven 337 und negativen 337 dar.

Should be

Der Decimal Werttyp stellt Dezimalzahlen zwischen positiven 79,228,162,514,264,337,593,543,950,335 und negativen 79,228,162,514,264,337,593,543,950,335 dar.

**Comment by gewarren** [comment]
Oh weird! /cc @jasoncard @carlossanlop

**Comment by JasonCard** [comment]
@DavidPrio @CeciAc Could you please help to look into this?

**Comment by CeciAc** [comment]
Hi @JasonCard 
This issue was already worked on last year: https://github.com/MicrosoftDocs/feedback/issues/2048
Also is MT content so is out of our scope.

@DavidPrio

**Comment by srvbpigh** [comment]
Hello, @Skosn
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by JasonCard** [comment]
@Skosn Thank you again for your feedback. This issue has been fixed and also bug has been opened for MT engine to address the root cause.
cc @gewarren @CeciAc
