### ISSUE TITLE
Visual Studio IDE older version download page and down link not working

### ISSUE THREAD

**Issue by vs5597** [MicrosoftDocs/feedback#238]
Visual Studio IDE older version download page and down link not working

## Issue Details
Sometimes Download page for older version IDE not render , download link is not working.

**Comment by dend** [comment]
Ping @vs5597 - do you happen to have the link handy?

**Comment by Powerhelmsman** [comment]
@vs5597 Sorry for delay. You can find everything here: https://www.visualstudio.com/vs/older-downloads/
Feel free to reopen if it doesn't answer your issue.
