### ISSUE TITLE
"Help us improve MSDN. Make a Suggestion" button is a broken link

### ISSUE THREAD

**Issue by evanderiel** [MicrosoftDocs/feedback#2380]
On the [MSDN forums page](https://social.msdn.microsoft.com/Forums/en-US/home), there is a bar at the bottom with the text "Help us improve MSDN." and a button "Make a suggestion". The button links to aka.ms/msdnfeedback, but that redirects permanently to docs.microsoft.com.

**Comment by docs-product** [comment]
Thank you for the suggestion! The MSDN assets are currently in the process of being retired, with all the content being moved to docs.microsoft.com.
