### ISSUE TITLE
Pointer Ballistics for Windows XP link on Taking Advantage of High-Definition Mouse Movement not working

### ISSUE THREAD

**Issue by nikolodus** [MicrosoftDocs/feedback#2382]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem** (if available).

**Link to article:**
Tell us where exactly a problem occurs.
https://docs.microsoft.com/en-us/windows/win32/dxtecharts/taking-advantage-of-high-dpi-mouse-movement#wm_input

**Problem:**
What's wrong with the article?
The link `Pointer Ballistics for Windows XP` points to an non-existing page that ends up being redirected to https://developer.microsoft.com/en-us/windows/hardware.

**Comment by DJm00n** [comment]
http://web.archive.org/web/20101222190833/http://www.microsoft.com:80/whdc/archive/pointer-bal.mspx

**Comment by mairaw** [comment]
Tagging @stevewhims who seems to be the owner of the article. Should that link be removed or updated?

**Comment by stevewhims** [comment]
Thanks! I've update the link's url so it works now. :)

-Steve
