### ISSUE TITLE
Archived weblog posts need redirects

### ISSUE THREAD

**Issue by JesperTreetop** [MicrosoftDocs/feedback#2384]
The previous developer weblogs have been archived to Docs, but there are a few redirects missing. For example, http://blogs.msdn.com/b/pfxteam/archive/2012/03/05/10278165.aspx redirects to [the main index page](https://docs.microsoft.com/en-us/archive/blogs/). This could be handled much more smoothly. If this is true for all such links, there are millions of links like this out in the wild and used as reference, and they are all broken now.

**Comment by docs-product** [comment]
Thank you for the feedback, @JesperTreetop - most high-volume blogs already have redirects in place. We'll assess whether there are any issues with remaining links.
