### ISSUE TITLE
QnA site email

### ISSUE THREAD

**Issue by DSPatrick** [MicrosoftDocs/feedback#2385]
**Describe the bug**
No notification emails are being sent from site https://docs.microsoft.com/answers/index.html
Last received 1/8/2020

**To Reproduce**
subscribe to some sort of notification

**Expected behavior**
email to be sent when activity on post

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] Edge browser
 - Version [e.g. 22] Microsoft Edge 44.18362.449.0

**Smartphone (please complete the following information):**

**Additional context**

**Comment by saldana** [comment]
@DSPatrick Due to a compliance issue, the mail notifications are not working right now. We are actively working on the issue, although we still do not have an ETA for a resolution.

**Comment by DSPatrick** [comment]
Thanks Sandra

**Comment by DSPatrick** [comment]
Is there an update on this?

**Comment by saldana** [comment]
We are working on a fix and we hope to deploy it by the end of this week.

**Comment by saldana** [comment]
We found additional issues that prevented us from deploying this week. We do not have a new ETA yet. Sorry about this.

**Comment by saldana** [comment]
@DSPatrick we found the issue and we are testing the fix today. We are targetting the deployment of the fix on Tuesday, Feb 18 (as Monday is a holiday for us). Thanks a lot for your patience.

**Comment by jlanter** [comment]
Thank you for looking into this issue.  Here is a link to my profile – if this isn’t what you need just let me know.  Thanks!

https://docs.microsoft.com/en-us/users/lanterjameslsois-9977/


James Lanter  | Cache’ DBA, IS Enterprise Technical Services | tel 503-415-5314

**Comment by saldana** [comment]
@DSPatrick this issue is fixed now and e-mail notifications are working again. We deployed a fix this morning to address this problem.
