### ISSUE TITLE
Download link for Windows Message Analyzer does not work

### ISSUE THREAD

**Issue by uditjainmicrosoft** [MicrosoftDocs/feedback#2391]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem** (if available).

**Link to article:**
On article page: https://docs.microsoft.com/en-us/message-analyzer/installing-and-upgrading-message-analyzer?source=docs , a download link to download Windows Message Analyzer does not work from a long time: http://www.microsoft.com/en-us/download/details.aspx?id=44226

**Problem:**
Download link for Windows Message Analyzer takes me to https://www.microsoft.com/en-us/download/404Error.aspx (404 page)

**Comment by rootsmusic** [comment]
@uditjainmicrosoft "The Microsoft Message Analyzer tool has been retired. We are leaving this page available for those who have downloaded the tool previously."
#please-close
