### ISSUE TITLE
SQL Unit Test Walkthrough Errors

### ISSUE THREAD

**Issue by philhege** [MicrosoftDocs/feedback#2394]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem** (if available).

**Link to article:**
(https://docs.microsoft.com/en-us/sql/ssdt/walkthrough-creating-and-running-a-sql-server-unit-test?view=sql-server-ver15 (Test for uspShowOrderDetails)

**Problem:**
The setup script that creates the sample database assigns two constraints to the order table's order date. The upper bound of the value is 01/01/2020, but the procedures use getdate() to assign order date, which is obviously out-of-bounds. I suggest extending the end date to 2025: 
USE [SimpleUnitTestDB]
GO

ALTER TABLE [Sales].[Orders] DROP CONSTRAINT [CK_Orders_OrderDate]
GO

ALTER TABLE [Sales].[Orders]  WITH CHECK ADD  CONSTRAINT [CK_Orders_OrderDate] CHECK  (([OrderDate]>'01/01/2005' AND [OrderDate]<'01/01/**2025**'))
GO

ALTER TABLE [Sales].[Orders] CHECK CONSTRAINT [CK_Orders_OrderDate]

-----
USE [SimpleUnitTestDB]
GO

ALTER TABLE [Sales].[Orders] DROP CONSTRAINT [CK_Orders_FilledDate]
GO

ALTER TABLE [Sales].[Orders]  WITH CHECK ADD  CONSTRAINT [CK_Orders_FilledDate] CHECK  (([FilledDate]>=[OrderDate] AND [FilledDate]<'01/01/**2025**'))
GO

ALTER TABLE [Sales].[Orders] CHECK CONSTRAINT [CK_Orders_FilledDate]

**Comment by rootsmusic** [comment]
@philhege Please move this issue to https://github.com/MicrosoftDocs/sql-docs/issues

**Comment by philhege** [comment]
> @philhege Please move this issue to https://github.com/MicrosoftDocs/sql-docs/issues

I don't have that option (step 4 of transfer instructions) in my view of the issue. Should I create a new one?
![image](https://user-images.githubusercontent.com/46456822/127522852-bebb2e20-37e9-419d-be5c-f0ea7641d73a.png)

**Comment by rootsmusic** [comment]
Yes @philhege, you can open an issue in https://github.com/MicrosoftDocs/sql-docs/issues and close this one.

**Comment by philhege** [comment]
Done; thanks.
https://github.com/MicrosoftDocs/sql-docs/issues/6651
