### ISSUE TITLE
Remove extra hyphens in XML comments for IE Enterprise Site file

### ISSUE THREAD

**Issue by larslynch** [MicrosoftDocs/feedback#2397]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem** (if available).

**Link to article:**
[https://docs.microsoft.com/en-us/internet-explorer/ie11-deploy-guide/add-multiple-sites-to-enterprise-mode-site-list-using-the-version-2-schema-and-enterprise-mode-tool](https://docs.microsoft.com/en-us/internet-explorer/ie11-deploy-guide/add-multiple-sites-to-enterprise-mode-site-list-using-the-version-2-schema-and-enterprise-mode-tool)

**Problem:**
The XML comments should open and close with two hyphens (--), not three.  Three hyphens will result in an XML parsing error.

This is the correct XML:
`<site-list version="205">
    
    <created-by>
        <tool>EnterpriseSitelistManager</tool>
        <version>10240</version>
        <date-created>20150728.135021</date-created>
    </created-by>
     
    <site url="www.cpandl.com">
        <compat-mode>IE8Enterprise</compat-mode>
        <open-in>MSEdge</open-in>
    </site>
    <site url="www.cpandl.com/images">
        <compat-mode>IE7Enterprise</compat-mode>
        <open-in>IE11</open-in>
    </site>
    <site url="contoso.com">
        <compat-mode>default</compat-mode>
        <open-in>IE11</open-in>
    </site>
</site-list>`

**Comment by rootsmusic** [comment]
Fixed.
#please-close
