### ISSUE TITLE
The MS Help Viewer should not require elevated (admin) rights

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#24]
Currently the MS Help Viewer requires elevated (admin) rights to be able to download (and update) books.
It even requires to sign in as an administrator user to do that. The program can't add a book even when it's started with elevated rights in a normal user account.

It would be much more practical to use the Help Viewer as an ordinary program.
I suggest to download the books in the (normal) user directory, as %localappdata%\VisualStudio\HelpDocs for example.
This way, no elevation would be needed.

----------
⚠ Idea migrated from UserVoice

**Created By:** chrisbertrand.net
**Created On:** 2018/02/21 14:45:26 +0000
**Votes at Migration:** 1
**Supporters at Migration:** 1

**Comment by dend** [comment]
Assigning to myself to follow-up with the product team.

**Comment by dend** [comment]
Quoting the product team:

>The Help Viewer doesn’t require admin privileges, the Help Content Manager does, because it (by default) installs content into an access protected location. This is because the help books are expected to be in a location accessible by all users.
