### ISSUE TITLE
Errors in examples on "Manipulate the Visio file format programmatically" page

### ISSUE THREAD

**Issue by TooManyLeaves** [MicrosoftDocs/feedback#2400]
There are errors in the examples for finding package parts based on relationships on the [Manipulate the Visio file format programmatically](https://docs.microsoft.com/en-us/office/client-developer/visio/how-to-manipulate-the-visio-file-format-programmatically) page. The examples  do not work and cause the code to fail (for a really silly reason):

`// Get a reference to the collection of pages in the document, 
// and then to the first page in the document.
PackagePart pagesPart = GetPackagePart(visioPackage, documentPart, 
    "https://schemas.microsoft.com/visio/2010/relationships/pages");
PackagePart pagePart = GetPackagePart(visioPackage, pagesPart, 
    "https://schemas.microsoft.com/visio/2010/relationships/page");`

What's wrong: **https:** should be **http:**

**Comment by rootsmusic** [comment]
Fixed.
#please-close
