### ISSUE TITLE
Unauthorized sandbox use detected. Your sandbox access has been removed

### ISSUE THREAD

**Issue by Mikatgithub** [MicrosoftDocs/feedback#2401]
Hi, Just doing the Azure Fundamentals training, and I'm trying to do a sandbox exercise located here [https://docs.microsoft.com/en-us/learn/modules/welcome-to-azure/4-exercise-create-website](https://docs.microsoft.com/en-us/learn/modules/welcome-to-azure/4-exercise-create-website)

When I click it, I get this Message
"Unauthorized sandbox use detected" Your sandbox access has been removed
There is no button to appeal it

![image](https://user-images.githubusercontent.com/32026996/72672713-83ea9500-3ab2-11ea-986d-7fd61982c402.png)

**Comment by Mikatgithub** [comment]
#1797

**Comment by bradski77** [comment]
Hi, I see this also and have sent several requests for help on it with no response

**Comment by anabelsi** [comment]
I am not getting any responses either.

**Comment by kalaga20** [comment]
I too am facing the same issue. Let me know for any resolution.

**Comment by Mikatgithub** [comment]
Thank You, my sandbox issue has been resolved

Good luck to the other people, if still nothing happens for you, copy and past my issue
