### ISSUE TITLE
NuGet ID Prefix Reservation

### ISSUE THREAD

**Issue by SoftCircuits** [MicrosoftDocs/feedback#2404]
*Note: This comment is regarding NuGet. I came here after clicking the link to provide feedback on NuGet. If this should be posted elsewhere, please let me know.*

I have twice now followed the [instructions](https://docs.microsoft.com/en-us/nuget/nuget-org/id-prefix-reservation) for reserving an ID prefix to a name that matches the prefix of all 14 of my packages. It is also a name that I hold a federal trademark on. The second time, I also sent an email to an address I had for NuGet saying that it was my second attempt and that I had heard nothing back from the first attempt.

In both cases, I never heard anything back and my ID prefix is still not reserved.

Is this a process that for some reason is normal to take several months? Or is it possible that the request was silently rejected for some reason? What should be my expectations for sending such an email into the void?

**Comment by rootsmusic** [comment]
@SoftCircuits Product support isn't here.  Did you email support@nuget.org ?

**Comment by SoftCircuits** [comment]
@rootsmusic Yes, as described, I emailed them twice. Turned out my emails were going into their spam filter. Resolved now.

**Comment by rootsmusic** [comment]
#please-close
