### ISSUE TITLE
Non Loading of Data in PowerApp

### ISSUE THREAD

**Issue by rawalsagar** [MicrosoftDocs/feedback#2414]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
---------------------------
The Excel table that I connect to works till I am editing the app, but disappears while opening the app next time. The data doesn't get loaded or connection gets broken. At the time of reopening the app, I get the following message:

_### "Failed to load Table1. The specified record was not found. Server response: Failed to read metadata from file source. Response from the end service is : Not Found clientRequestId: 49534c70-00a5-4725-8f87-7add9381ed5e serviceRequestId: 49534c70-00a5-4725-8f87-7add9381ed5e;49534c70-00a5-4725-8f87-7add9381ed5e"_

How do I get out of this blockage & keep the connection working. Tried the saving in personal One Drive as well as Business One drive. Why it is not accepting Access Data Base? It may solve this problem.

This becomes very frustrating as we cant learn the future steps in launching the app successfully.
After numerous efforts I have decided to get help here or uninstall "PowerApp".

**Comment by docs-product** [comment]
Thank you for the feedback! Because this issue is not related to docs.microsoft.com, we cannot address it in this forum.
