### ISSUE TITLE
New-AzSqlDatabaseImport should support -Tags parameter

### ISSUE THREAD

**Issue by JJussi** [MicrosoftDocs/feedback#2415]
**Is your feature request related to a problem? Please describe.**
Billing is base on TAGs and now when I create new DB from .bacpac file, import time (hours) is not included because TAGs are set after import.

**Describe the solution you'd like**
New-AzSqlDatabaseImport powershell command should support -Tags parameter, so newly created DB have right tags, right from the start

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by docs-product** [comment]
Thank you for the feedback! Because this issue is not related to docs.microsoft.com, we cannot address it in this forum.
