### ISSUE TITLE
Editing search text in Safari is weird

### ISSUE THREAD

**Issue by jonpryor** [MicrosoftDocs/feedback#2419]
**Describe the bug**

When editing the search query, if the insertion carrot isn't at the end of the text, typing *appends* to the text.

**To Reproduce**

1. Use macOS Mojave 10.14.6 and Safari 13.0.4.  (May happen on other versions.  I saw it here.)
2. Go to <docs.microsoft.com>
3. Click the **Search** link on the top-left of the page.  A *Search* input field appears.
4. Type a search query containing spaces, such as `Visual Studio`.  Press the `[ENTER]` key on your keyboard.
5. You now see search results.
6. Click the **Search** link on the top-left of the page.  The input field reappears, with the text entered in (4).
7. Click on the space in the query from (4), e.g. the space within `Visual Studio`.  Or, use the keyboard to navigate to the space.
8. Start typing, e.g. `Preview`

**Expected behavior**
Text should appear where the insertion carrot is, e.g. if the insertion carrot is after the space within `Visual Studio`, and I type `Preview `, I should see `Visual Preview Studio`.

**Actual behavior**
After typing the first character, the remaining text is *appended* to the query, regardless of where the insertion carrot is.  For example, I see `Visual PStudioreview`.

**Screenshots**
![docs microsoft com Search](https://user-images.githubusercontent.com/155958/72928089-5d806000-3d25-11ea-9c22-12adf24f934a.gif)

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14.6
 - Browser: Safari 13.0.4

**Additional context**
This doesn't happen with Chrome 79.0.3945.117.

**Comment by docs-product** [comment]
This issue should be addressed - thank you for the flag, @jonpryor!
