### ISSUE TITLE
Site does not honour user locale for dates

### ISSUE THREAD

**Issue by bebobebo** [MicrosoftDocs/feedback#2420]
Getting tired of having to reset the page language from EN-US to EN-AUS with *every* page. If you're not going to honour user or system locales for date rendering, then at least provide a setting in my user account where I can specify a recognisable date format.

See also: https://github.com/MicrosoftDocs/feedback/issues/386

**Comment by SonjaSaltzman** [comment]
Hello @bebobebo - have you tried to set your preferred language to English (Australia) with the language picker at the left bottom of the site?
![image](https://user-images.githubusercontent.com/15201704/79024232-2e64d800-7b37-11ea-8caf-fcfa87d64e6f.png)
This will persist en-AU as your preferred language. However, if your browser returns a link that points to an /en-US page, you will still be served the en-US page format.
Hope this helps for some of your scenarios,
Sonja

**Comment by bebobebo** [comment]
Hi Sonya - that is not how internationally sufficient software works. It
should not require manual intervention from an end-user every time a
measurable quantity needs to be shown with the correct units. The page
should detect the browser's en-au settings automatically and adjust
accordingly. That is not only why browser's have regional settings, but
Windows and other operating systems do also. Having to jump to the bottom
of every page and/or log in to retrieve stored settings is a laborious task
that takes millions of times longer than for a computer to do it
automatically.  (Speaking here as an ex-internationalisation PM in both
Office and Windows teams, and an internal reviewer of Microsoft's own
textbook on this stuff from the 1990s.)

**Comment by SonjaSaltzman** [comment]
Hi again - thank you for the quick response, and nice to virtually speak to an exMSFT internationalization PM! 
You should only have to set the language picker once, and this setting should persist. If you don't use the language picker, the site should use your browser locale. However, many customers google for content, and google will most likely return a link to a topic with /en-US locale. In this case, the site will serve up /en-US :-(.  We have a feature in the backlog to serve the preferred language selected in the language picker (e.g. /en-AU), no matter what locale the link clicked by the user contains, but it is not implemented yet.
copying @dend and @RyanKing77 who are PMs for this feature

**Comment by bebobebo** [comment]
Generally there are no different pages for different locales for a single
language e.g. there are dozens of English locale, but likely only EN-US for
the text. This should not affect rendering of dates (first priority as they
are easiest to confuse), weights and measures, temperatures. Microsoft
should find it trivially easy to do this with its resources, as even small
sites do this automatically. Unfortunately when international issues are so
frequently assigned Pri3 despite them affecting 95% of the planet, it's
hard to see them implemented at Microsoft these days.

**Comment by docs-product** [comment]
This ties into the work we have for #462. I will resolve this as a duplicate, with a reference in the other item to make sure that we're properly accounting for user preferences.
