### ISSUE TITLE
VS2019 16.5 Preview 2 release notes broken image ref

### ISSUE THREAD

**Issue by onchuner** [MicrosoftDocs/feedback#2422]
**Link to article:**
https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes-preview#view-dotnet-object-lock

**Problem:**
<img src="media/16.5/16.5_P2_view-dotnet-object-lock.png" align='bottom' alt="View .NET object lock in Call Stack" instead of image

**Comment by TerryGLee** [comment]
@JacquelineWiddis Please take a look at this? Thanks. :)

**Comment by JacquelineWiddis** [comment]
@TerryGLee This has been fixed.  @onchuner, thank you for submitting the issue.  Happy developing!

**Comment by onchuner** [comment]
thank you for help @JacquelineWiddis
