### ISSUE TITLE
Unable to activate sandbox enviroment

### ISSUE THREAD

**Issue by lechaser** [MicrosoftDocs/feedback#2423]
I recently started one of the tutorials on Microsoft Learn (https://docs.microsoft.com/en-us/learn/modules/welcome-to-azure/4-exercise-create-website) and when I got to step 4, where a sandbox account is required, I was unable to activate the sandbox and was told that the reason was "Unauthorized sandbox use detected" and I can not appeal the issue. Same issue for any other sandbox environment I tried within the same Learning Path.

That happens when I use my personal Microsoft account on Microsoft Learn. If I use my work account, it simply works. Could you please fix my personal account? I use it for my Microsoft Certifications exams so I would like to being able to follow the Learning Paths using the same account.

**Comment by venkatkoka15** [comment]
Helo Team, 

I started one of the tutorials on Microsoft Learn (https://docs.microsoft.com/en-us/learn/modules/welcome-to-azure/4-exercise-create-website) and when I start activating the sandbox I receive the below issue.

"Unauthorized sandbox use detected. Your sandbox access has been removed.

The sandbox may only be used to complete training on Microsoft Learn. Use for any other reason is prohibited, and may result in permanent loss of access to the sandbox. Please review our Terms of Use."

This happens only with my personal Microsoft account. My work account works fine. Request you to please fix my personal account issue? 

Thanks

**Comment by venkatkoka15** [comment]
Is this issues Resolved ? or any updates on this issues resolution?

Thanks

**Comment by Sirlupinwatson1** [comment]
Hi all, 

To resolve this issue in the tutorial you need to choose another user ; 

- See my picture here, you need to choose Microsoft Learnsandbox and not your main user. 
- Then you can proceed to do all the step in the tutoriel and you should be good to go.

_I hard time to get it also._

![gitmicrosoft](https://user-images.githubusercontent.com/55941045/73072552-4a83a200-3e83-11ea-933b-e8355b2857a6.png)

**Comment by Sirlupinwatson1** [comment]
> I recently started one of the tutorials on Microsoft Learn (https://docs.microsoft.com/en-us/learn/modules/welcome-to-azure/4-exercise-create-website) and when I got to step 4, where a sandbox account is required, I was unable to activate the sandbox and was told that the reason was "Unauthorized sandbox use detected" and I can not appeal the issue. Same issue for any other sandbox environment I tried within the same Learning Path.
> 

-------------------------------
 ###  @lechaser 


> That happens when I use my personal Microsoft account on Microsoft Learn. If I use my work account, it simply works. Could you please fix my personal account? I use it for my Microsoft Certifications exams so I would like to being able to follow the Learning Paths using the same account.

**Since 2016 i think, they can't regroup 2 account into 1. I tried it already . Sorry about that.**

**Comment by lechaser** [comment]
@Sirlupinwatson1 

Thanks for your reply, but that´s not what we are talking about. The sandbox environment is not even starting. Therefore we can´t go later to Azure console and switch the subscription.

See a screenshot below

![Sandbox issue](https://user-images.githubusercontent.com/36274203/73072819-3f963500-3eb6-11ea-969f-382c7f068aaa.png)

**Comment by Sirlupinwatson1** [comment]
> @Sirlupinwatson1
> 
> Thanks for your reply, but that´s not what we are talking about. The sandbox environment is not even starting. Therefore we can´t go later to Azure console and switch the subscription.
> 
> See a screenshot below
> 
> ![Sandbox issue](https://user-images.githubusercontent.com/36274203/73072819-3f963500-3eb6-11ea-969f-382c7f068aaa.png)

Not sure to get what you say then. You are not even log in from what i can see on the top right page.

Make sure you have your subscription on either a free tier or a paid tier, Log into your account and activate the sandbox on the tutorial page.

**Comment by lechaser** [comment]
Hi @Sirlupinwatson1 

Thanks again for your comments, I will add more details so you can get the full picture and why there´s an issue.

This is my Learn Portal, on top right you can see I´m logged in.

![Learn Portal](https://user-images.githubusercontent.com/36274203/73074494-14154980-3eba-11ea-99e8-1a75331af9bd.png)

The "free account" it´s just a link to Azure portal. Annyway, If I click there, you can see I´m logged in,too.

![Azure portal](https://user-images.githubusercontent.com/36274203/73074564-36a76280-3eba-11ea-8a1f-576c1b850ab9.png)

In addition, I can still see the "promo info" about creating the account. It´s a marketing page only.

So, If I select going to the portal, you can see that my account is active with a trial already.

![account](https://user-images.githubusercontent.com/36274203/73074664-6a828800-3eba-11ea-8208-fa8997600814.png)

Both logins, Learn portal and Azure portal, are with the same Microsoft account. 

The issue is that if I try to activate the sandbox in the learn portal, it fails and show the error I previously attached. 

I know how it works, because if I use my work microsoft account, it works perfectly,I can go through the sandbox activation and I can see it in my Azure portal using my work account.

**Comment by Sirlupinwatson1** [comment]
Hum that is a technical question that i have no answer then sorry about this.

I am pretty sure this is just a small things but you can ask your question also directly in the feedback from Azure. They reply pretty fast. 

Sorry about this i wish i could have help you.

**Comment by lechaser** [comment]
It seems the issue has been fixed today.

**Comment by Sirlupinwatson1** [comment]
Thanks for the follow up @lechaser .
