### ISSUE TITLE
Wrong year in Visual Studio 2017/2019 Release Notes

### ISSUE THREAD

**Issue by UnsaidAverage** [MicrosoftDocs/feedback#2424]
**Describe the bug**
It is year 2020 now, NO LONGER 2019.

**To Reproduce**
1. Go to
https://docs.microsoft.com/en-us/visualstudio/releasenotes/vs2017-relnotes
https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes
https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes-preview

2. Look at the Release Notes release date, see the error

**Expected behavior**
year 2020.

**Comment by mlottner** [comment]
@UnsaidAverage Thanks for taking the time to give us feedback on this issue. 
Indeed, for some reason the pages you flagged did not update correctly when republished. 
I've flagged this issue for a member of our internal publishing team to review and investigate. 
Appreciate your contribution to our docs community.

**Comment by docs-product** [comment]
This should be fixed - thank you for the feedback!
