### ISSUE TITLE
[error message feedback] provide feedback for committish-not-found

### ISSUE THREAD

**Issue by dan-wesley** [MicrosoftDocs/feedback#2426]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

**Problem:**
What's wrong with the error message? For example,
- Is error message clear and actionable?
- Is there a documentation to provide more information?
- If there is a documentation, is it relavent and helpful?
- Is line number correct?
- etc.

**Log code info**
(This is auto filled, no need to modify)

| Severity   | Type   | Code   | Category   | File   | Message   |  Source  | Line   | Time   |
|------------|--------|--------|------------|--------|-----------|----------|--------|--------|
| Error | User | committish-not-found |  |  | Can't find branch, tag, or commit 'v-danwes-update-edge-edgelegacy' for repo https://github.com/MicrosoftDocs/EdgeEnterprise-pr. |  |0 | 01/23/2020 18:26:26 |

**Link to report**
(This is auto filled, no need to modify)

[report url](https://opbuildstorageprod.blob.core.windows.net/report/2020/1/23/fdb0a94c-f462-0643-9675-783193e54b0e/Commit/202001231826016733-v-danwes-update-edge-edgelegacy-sxs/workflow_report.html?sv=2016-05-31&sr=b&sig=lqo%2Fzmxlb6JFMDzy0TRyWAFWRCcYeLNOaNoGQtxAtXI%3D&st=2020-01-23T18%3A21%3A31Z&se=2020-02-23T18%3A26%3A31Z&sp=r

**Comment by docs-product** [comment]
@dan-wesley - is there a particular issue with the build?
