### ISSUE TITLE
How to generate base64 encoded key for aes256 and SHA -256

### ISSUE THREAD

**Issue by aks-14-89** [MicrosoftDocs/feedback#2427]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem** (if available).

**Link to article:**
Generating base64 encoded key AES256 and SHA-256 in nodejs.
**Problem:**
Generated AES256 base64 Encoded key using this code from npm repository:- 

// generate random passphrase binary data
    var r_pass = crypto.randomBytes(256);
    
    // convert passphrase to base64 format
    var r_pass_base64 = r_pass.toString("base64");
    
    console.log("passphrase base64 format: ");
    console.log(r_pass_base64);

    var CryptoJS = node_cryptojs.CryptoJS;
 
    // custom json serialization format
    var JsonFormatter = node_cryptojs.JsonFormatter;
    
    // message to cipher
    var message = "New Blob Testing";
    // encrypt plain text with passphrase and custom json serialization format, return CipherParams object
    // r_pass_base64 is the passphrase generated from first stage
    // message is the original plain text  
    var encrypted = CryptoJS.AES.encrypt(message, r_pass_base64, { format: JsonFormatter });
    // convert CipherParams object to json string for transmission
    var encrypted_json_str = encrypted.toString();
    console.log("serialized CipherParams object: ");
    console.log(encrypted_json_str);
    aes256encrypted = JSON.parse(encrypted_json_str).ct;

Then done sha256 as :- 
  var hmac = crypto.createHmac("SHA256",aes256encrypted).update(message).digest("base64")
    sha256encrypted = hmac
  console.log("sha256================: ",sha256encrypted)

But when I upload Blob it shows me:-
server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
     message: 'The value for one of the HTTP headers is not in the correct format.\nRequestId:bdc8a7ef-b01e-005b-0c76-d2d107000000\nTime:2020-01-24T05:26:11.2611243Z',
     Code: 'InvalidHeaderValue',
     HeaderName: 'x-ms-encryption-key-sha256',

Tried with different methods but no success. Anyone can help?

**Comment by Trapulo** [comment]
I've tried different methods to generate values, but still I have SHA rejected from azure...
