### ISSUE TITLE
Documentation suggestion

### ISSUE THREAD

**Issue by jchesshir** [MicrosoftDocs/feedback#243]
# Idea Title
https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.testtools.unittesting.dynamicdataattribute.-ctor?view=mstest-net-1.2.0#Microsoft_VisualStudio_TestTools_UnitTesting_DynamicDataAttribute__ctor_System_String_System_Type_Microsoft_VisualStudio_TestTools_UnitTesting_DynamicDataSourceType_

## Issue Details
Would be nice to have more of a description for the 3 arg constructor in the DynamicDataAttribute class.

**Comment by Powerhelmsman** [comment]
@mairaw Can you take a look at this?

**Comment by mairaw** [comment]
This is VS SDK. Tagging @gregvanl and @ghogen instead.

**Comment by gregvanl** [comment]
I think @Mikejo5000 owns the TestTools API.

**Comment by Mikejo5000** [comment]
@gewarren @gregvanl I think Genevieve owns unit testing, but I don't know whether she owns these APIs...

**Comment by gewarren** [comment]
@pvlakshm owns these APIs.

**Comment by dend** [comment]
Ping @pvlakshm

**Comment by Powerhelmsman** [comment]
@jchesshir Your issue is transfered to visual studio team issue queue. https://github.com/MicrosoftDocs/visualstudio-docs/issues/923
