### ISSUE TITLE
Enable-AzSqlServerAdvancedDataSecurity

### ISSUE THREAD

**Issue by sqlworldwide** [MicrosoftDocs/feedback#2430]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem** (if available).

**Link to article:**
[Enable-AzSqlServerAdvancedDataSecurity](https://docs.microsoft.com/en-us/powershell/module/az.sql/enable-azsqlserveradvanceddatasecurity?view=azps-3.3.0)

**Problem:**
In the description, it says 'A new storage account will automatically be created for saving vulnerability assessments. If a storage account was previously created for this purpose, it will be used instead'.  How do I use a storage account that I created for this purpose?

**Comment by rootsmusic** [comment]
@sqlworldwide Please submit a support ticket at https://azure.microsoft.com/en-us/support/options/
