### ISSUE TITLE
Transfer User Reputation

### ISSUE THREAD

**Issue by mfstanton** [MicrosoftDocs/feedback#2432]
I have been a user for a long time I am an insider but my personal membership information does not seem to transfer to my work id.

**Comment by mlottner** [comment]
@mfstanton Thanks for taking the time to give us site feedback. 
What user account are you specifically referring to? A Microsoft account? Git? Something else? 
Let us know how we can try to help.

**Comment by mfstanton** [comment]
I am referring to Microsoft but now that Git is closely linked to Microsoft I suppose I may need both.

**Comment by docs-product** [comment]
@mfstanton - can you clarify what reputation are you referring to?

**Comment by mfstanton** [comment]
I am talking about all the traffic that I generated with my Personal Id (this one) versus my company required Id.  Is there no way to associate the two releative to feedback?

**Comment by mlottner** [comment]
@mfstanton System generated, not that I'm aware of. Short of tagging your other account wherever you want to call attention to yourself in a thread on your other persona. You can always search both of your Git aliases for repos, issues and mentions etc. however any kind of auto-combining of your Git user aliases is out of the scope of the docs.microsoft.com platform. 
I'm closing this issue for now, but feel free to continue to comment here if/as needed in the future.  Thanks again for taking the time to contribute to our community.
