### ISSUE TITLE
Creating User and Group Accounts article

### ISSUE THREAD

**Issue by almaceleste** [MicrosoftDocs/feedback#2435]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem** (if available).
*- this article has no comment section*

**Link to article:**
https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-2000-server/bb726984(v=technet.10)?redirectedfrom=MSDN

**Problem:**
`Rules for Logon Names` in this article has this text: 
>* Logon names can't contain certain characters. Invalid characters are
>   ```
>   ```
>" / \ [ ] : ; | = , + * ? < >

which should look like this, I think:
>* Logon names can't contain certain characters. Invalid characters are
>   ```
>   " / \ [ ] : ; | = , + * ? < >
>   ```

imho, it happens cause `<p>` element fell out of `<pre>` element.

**Comment by mlottner** [comment]
@almaceleste Thanks for taking the time to leave us feedback!
As noted at the top of the docs,microsoft.com page you linked, documentation of previous versions that are outside of Microsoft support can no longer be serviced or updated. 
To ensure the best possible experience for users and customers, make sure to use versions of Microsoft products that have active support. 
I'm closing this issue as the page referenced cannot be updated, but feel free to leave additional feedback for our site here. We do appreciate your contribution to our community.
