### ISSUE TITLE
QueryPerformanceCounter doc dead links

### ISSUE THREAD

**Issue by SpencerSimpson** [MicrosoftDocs/feedback#2438]
The doc for QueryPerformanceCounter 

https://docs.microsoft.com/en-us/windows/win32/api/profileapi/nf-profileapi-queryperformancecounter

has some links that go to the old MSDN page.  The content is no longer there, so you should update the links to go to the new locations. 

Example: https://msdn.microsoft.com/be335927-a78d-4023-bedb-94aaf3a561ae

**Comment by mlottner** [comment]
@SpencerSimpson Thanks for reporting this issue. I've asked a member of our Windows doc team to take a look and help assign the issue for fixing where possible.
We do appreciate you taking the time to contribute to the benefit of our site and community!
@GrantMeStrength  Can you please take a look?

**Comment by GrantMeStrength** [comment]
Hi -

Thanks for bringing this to our attention. I've corrected the links, and they should be re-published soon. Thanks again for taking the time!

-john
