### ISSUE TITLE
Snippet not found message

### ISSUE THREAD

**Issue by Youssef1313** [MicrosoftDocs/feedback#2440]
Regarding the "It looks like the sample you are looking for has moved! Rest assured we are working on resolving this." message:

1. I think the "we are working on resolving this" part tells the reader that the content team already knows about it and is working on fixing it. The content team might not be aware of it, and the reader won't report assuming they're already aware.

2. This message isn't localized.

**Comment by mlottner** [comment]
@Youssef1313 Thanks for taking the time to send us your feedback. 
I've flagged your feedback for a member of our docs site team for awareness and consideration. 
We do appreciate your contribution to our docs community. 
I'm closing this issue as it has been flagged internally, but feel free to add additional feedback here in the future. 
@docs-product Please take a look.
