### ISSUE TITLE
ForceUCI=1 occurring during automation tests

### ISSUE THREAD

**Issue by AliE158** [MicrosoftDocs/feedback#2442]
**Describe the bug**
Trying to run automation tests and it adds forceUCI=1 to URL which means tests fail as the UI is different. Tried different URLs and it keeps adding it to the end

**To Reproduce**
1. Go to https://testfmi.crm.dynamics.com/main.aspx
2. Site will go to https://testfmi.crm.dynamics.com/main.aspx?app=d365default&forceUCI=1&pagetype=apps

**Expected behavior**
App should go to https://testfmi.crm.dynamics.com/main.aspx#276408428

**Screenshots**
![screenshot8239846576851679387](https://user-images.githubusercontent.com/44815403/73274917-4b4b6980-41de-11ea-9c23-058210da9a1f.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome 
 - Version 79

**Additional context**
Selenium 3.141.59

**Comment by mlottner** [comment]
@AliE158 Thanks for sending us your site feedback for docs.microsoft.com
To get product support for a Dynamics issue, open a Dynamics support issue using the [Microsoft product support portal](https://support.microsoft.com/allproducts). 
I'm closing this issue for now as it is related to product support and not site feedback related. However, feel free to send additional site feedback even after the issue has been closed. We appreciate all contributions to enhance our community.
