### ISSUE TITLE
TOM documentation web pages are missing. 

### ISSUE THREAD

**Issue by MurraySargent** [MicrosoftDocs/feedback#2444]
All of a sudden the TOM documentation web pages are missing. Browse for ITextRange2 and you get a 404 message. These are important documentation web pages for the RichEdit control used extensively internally and externally in Windows and Office. Please get them back on line. For example, go to https://docs.microsoft.com/en-us/windows/win32/controls/text-object-model and click on ITextDocument or other interfaces. Up comes the 404 message.

**Comment by GrantMeStrength** [comment]
Hi, thanks for getting in touch. I believe this was a temporary problem and the links are all functional again. If not, please let us know!
