### ISSUE TITLE
Submitting malware and non-malware to Microsoft for analysis

### ISSUE THREAD

**Issue by BugsFinder** [MicrosoftDocs/feedback#2447]
Hi,

Please fix the following link:
https://www.microsoft.com/wdsi/filesubmission

When I tried to open, I got - 403 Page Error.

P.S. I can't submitting a new malware samples.

**Comment by docs-product** [comment]
Thank you for the feedback! Because this is not related to docs.microsoft.com, we cannot address the issue in this forum.
