### ISSUE TITLE
In SQL Server 2012 more than 1 Primary Key is allow on Table when we are going through Right Click->New Table->Design Table

### ISSUE THREAD

**Issue by premlad** [MicrosoftDocs/feedback#2448]
SQL SERVER 2012 BUG:-

1.) When Creating a Table 
2.) Right Click on Table
3.) New Table
4.) Adding Column Name with int Datatype and NOT NULL
5.) Selecting both Column and Adding Primary Key to it.
6.) Primary Key is adding on Both The Table.

Kindly see through This Problem.....!!!

Reply as soon as Possible....!!!!

![PK3](https://user-images.githubusercontent.com/10363766/73333879-282dc200-4291-11ea-87e4-0930f41ff649.png)
![PK](https://user-images.githubusercontent.com/10363766/73333881-282dc200-4291-11ea-8de0-9173ef98373c.png)

**Comment by premlad** [comment]
Please Reply as soon as Possible We are stuck....!!!!

**Comment by docs-product** [comment]
Thank you for the feedback! Because this is not related to docs.microsoft.com, we cannot address the issue in this forum.
