### ISSUE TITLE
"Feedback" option is not provided in Msvm_VirtualSystemMigrationService WMI class

### ISSUE THREAD

**Issue by KrupalJoshi** [MicrosoftDocs/feedback#2449]
Hi, 
I couldn't found "Feedback" option in above mentioned WMI class and its sub components/classes.
Could you please provide the same?

I have some issues/queries regarding these pages. Any workaround you would like to suggest for now? So, i can proceed with my queries.

Thanks,
Krupal

**Comment by KrupalJoshi** [comment]
https://docs.microsoft.com/en-us/windows/win32/hyperv_v2/msvm-virtualsystemmigrationservice
https://docs.microsoft.com/en-us/windows/win32/hyperv_v2/checkvirtualsystemismigratable-msvm-virtualsystemmigrationservice
https://docs.microsoft.com/en-us/windows/win32/hyperv_v2/checkvirtualsystemismigratabletohost-msvm-virtualsystemmigrationservice

**Comment by GrantMeStrength** [comment]
Hi - I'm sorry, it's not possible to provide feedback on some topics in our documentation at this time. If you have a specific question, I can try to connect you to the right person. If it's feedback on the docs, please reply here. If it's a feature related, please use the new Microsoft Q&A Forum - https://docs.microsoft.com/en-us/answers/products/azure?product=all
