### ISSUE TITLE
IISLogCleaner.exe Download Link not working

### ISSUE THREAD

**Issue by kev494** [MicrosoftDocs/feedback#2450]
**Link to article:** https://docs.microsoft.com/en-us/iis/manage/provisioning-and-managing-iis/managing-iis-log-file-storage

**Problem:**
In the IIS Log Cleaner Tool section is the download link broken. Link: http://www.erezbenari.com/IISLogCleaner.exe

The following error code is responded from the site: 

`<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
</Error>`

**Comment by kev494** [comment]
The correct link would be http://www.erezbenari.com/apps/IISLogCleaner.exe

**Comment by Rick-Anderson** [comment]
Any chance you could PR this? At the top right of the article, select the Edit pen icon:

![image](https://user-images.githubusercontent.com/3605364/53368931-11972200-38ee-11e9-86ce-18aaff69c719.png)

Select the pen icon again. Save.

**Comment by kev494** [comment]
I will try do it next week!
