### ISSUE TITLE
Session Issues on Azure Notebooks

### ISSUE THREAD

**Issue by lexvieira** [MicrosoftDocs/feedback#2454]
When you login on Azure Notebooks, after awhile when you set the laptop to sleep or close the windows and reload, looks like you are connected to the Azure Notebooks because you can see your name on the left top, however when you try to load some projects, looks like you are not, you receive a lot of error messages of Notebbok tell you the occured a error while loading the Notebook.

**Comment by docs-product** [comment]
Thank you for the feedback! Because this is not related to docs.microsoft.com, we cannot address the issue in this forum.
