### ISSUE TITLE
"tablular" is a typo

### ISSUE THREAD

**Issue by minestarks** [MicrosoftDocs/feedback#2459]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem** (if available).

**Link to article:**
The leftnav title of https://docs.microsoft.com/en-us/azure/kusto/query/queries

**Problem:**
"tablular" is a typo of "tabular"

**Comment by mairaw** [comment]
It seems this issue was fixed. Closing.
