### ISSUE TITLE
Error in EnvDTE.ToolBoxItems.Add code sample, no way to edit

### ISSUE THREAD

**Issue by dend** [MicrosoftDocs/feedback#246]
In the second code sample under https://docs.microsoft.com/en-us/dotnet/api/envdte.toolboxitems.add#Examples, it has `"C:\Libraries\ADotNetControl.dll("` where I believe it's supposed to just be `"C:\Libraries\ADotNetControl.dll"`.

Why can't I submit a PR for this?

---

Migrated from MicrosoftDocs/Docs

Feedback from @jnm2

**Comment by Powerhelmsman** [comment]
@gregvanl Can you take a look at this issue?

**Comment by dend** [comment]
Ping @gregvanl @ghogen

**Comment by Powerhelmsman** [comment]
@TianqiZhang This is small modification. Can you help fix it?

**Comment by Powerhelmsman** [comment]
Sent a email to @gregvanl to follow up

**Comment by Powerhelmsman** [comment]
@gregvanl @dend Based on Greg's suggestion, I transferred this issue to MicrosoftDocs/visualstudio-docs he will fix it there.

**Comment by Powerhelmsman** [comment]
@dend this issue is fixed. I will close as resolved.
