### ISSUE TITLE
ServerReport.LoadReportDefinition (Stream) documentation does not load

### ISSUE THREAD

**Issue by coreycummings** [MicrosoftDocs/feedback#2462]
The link to the documentation for reportviewer method below does not work and throws an error when clicked.
ServerReport.LoadReportDefinition (Stream)

**Link to article:**
https://msdn.microsoft.com/en-us/library/m:microsoft.reporting.winforms.report.loadreportdefinition(system.io.stream)(v=VS.90)

Link to parent article 
https://docs.microsoft.com/en-us/previous-versions/visualstudio/visual-studio-2008/ms252763(v=vs.90)

**Problem:**
results in a Runtime Error displayed on the web page

**Comment by docs-product** [comment]
Thank you for the feedback! Articles in `/previous-versions` are no longer supported or updated.
