### ISSUE TITLE
QnA moderation

### ISSUE THREAD

**Issue by DSPatrick** [MicrosoftDocs/feedback#2464]
**Describe the bug**
Moderation page show some discrepancy
"There is no reported content waiting moderation"
then to right it shows
"1 post(s) have been reported"
 

**To Reproduce**
visit site https://docs.microsoft.com/answers/moderation/index.html?tab=reported

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/37478978/73583516-498cda80-4458-11ea-9122-7a863b80d8f1.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by DSPatrick** [comment]
Also not technically broke but the dropdown from profile avatar shows "Moderation (0/1)" which actually is Spam/Reported that turns out to be the reverse of the actual order of the tabs over to left.

**Comment by saldana** [comment]
Actually, only items in moderation and reported are included in the avatar's flyout. The first number is for moderation and the second one is for reported. Items in the spam tab are not included there.
