### ISSUE TITLE
Are you sure that we have to pass a DX11 enum into a DX12 function?

### ISSUE THREAD

**Issue by pxbyt** [MicrosoftDocs/feedback#2465]
https://docs.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12graphicscommandlist-resolvesubresource

The explanation of the parameter 'pDstResource' says:<br/>
'Destination resource. Must be a created with the D3D11_USAGE_DEFAULT flag and be single-sampled ...'<br/>
I guess what it really means is the 'D3D12_RESOURCE_FLAG_NONE' of 'D3D12_RESOURCE_FLAGS Flags;'?

**Comment by stevewhims** [comment]
Hi, @pxbyt, and thanks for filing this issue! The topic has now been updated.

By the way, when the specific topic is known, feel free to visit that topic and go to the bottom of the page where there's **Send feedback about** \> **This page**.

Thanks again!
Steve
