### ISSUE TITLE
QnA sign in issue

### ISSUE THREAD

**Issue by DSPatrick** [MicrosoftDocs/feedback#2466]
**Describe the bug**
Clicking Sign in causes page to refresh but does not sign in nor does it provide a login prompt
Edge quite working a few days ago, now IE also produces same result

**To Reproduce**
Navigate to site https://docs.microsoft.com/answers/index.html and click Sign In (screenshot shows the URL redirect to sign-in but for some reason fails)

**Expected behavior**
Either successful sign in or a prompt to provide credentials

**Screenshots**
![image](https://user-images.githubusercontent.com/37478978/73597659-ebadd080-44f3-11ea-8122-00cd16b86d8f.png)

**Desktop (please complete the following information):**
Windows 10 x64 1909 latest build
Microsoft Edge 44.18362.449.0
IE 11.592.18362.0

**Smartphone (please complete the following information):**

**Additional context**

**Comment by saldana** [comment]
Our engineering team is investigating the issue.

**Comment by saldana** [comment]
We are investigating the issue. We will update once we have more information.

**Comment by saldana** [comment]
As a workaround, please clear your cache or work on InPrivate/Incognito. Sorry for the trouble.

**Comment by DSPatrick** [comment]
Thanks, yes for now I've been using incognito

**Comment by DSPatrick** [comment]
Just an FYI, the issue eventually affects an in-private session as well.

**Comment by DSPatrick** [comment]
From Aman's yammer post;
The change has rolled out. Any users affected by the 'Q&A cookie expires before DocsToken' issue will still be affected. They will need to go to https://docs.microsoft.com/learn and explicitly Sign Out (which will clear their DocsToken and Q&A cookie). Then if they go to Docs or Answers, they will be asked to log in and will get a new cookie with the correct lifetime. 
 
Yes this worked.
