### ISSUE TITLE
2019 WPF Tutorial not documented properly

### ISSUE THREAD

**Issue by squin** [MicrosoftDocs/feedback#2469]
There is what looks like a useful tutorial called "Create your first WPF application in Visual Studio 2019". Having worked down through this tutorial I got about halfway down where the users were added in a list, the title is "Add Controls". Scroll down to the next section "Add an image and a title" and the whole section is changed. There are "<Grid.Resources>" added and the names section completely re-worked with no comment as to why. I gave up on using it at this point, what a pity!

**Comment by docs-product** [comment]
@squin - could you please provide a link to the article in question?

**Comment by squin** [comment]
https://docs.microsoft.com/en-us/dotnet/framework/wpf/getting-started/walkthrough-my-first-wpf-desktop-application

Regards.....

**Comment by gewarren** [comment]
@thraka FYI

**Comment by mairaw** [comment]
@gewarren should this be transferred to the dotnet/docs repo instead?

**Comment by Thraka** [comment]
@mairaw Sure!

**Comment by gewarren** [comment]
This issue was moved to dotnet/docs#17726
