### ISSUE TITLE
Prevent Loss of Data on GitHub Issues Feedback System

### ISSUE THREAD

**Issue by dend** [MicrosoftDocs/feedback#247]
If I start a GitHub issue using the [new feedback system](https://docs.microsoft.com/en-us/teamblog/a-new-feedback-system-is-coming-to-docs) and I navigate away or refresh, my post is lost.

Can you this be improved?

- Warn the user
- Preserve the data.  If I refresh the page on an unsubmitted GitHub issue on GitHub.com, nothing is lost.  That is very nice.

---

Migrated from MicrosoftDocs/Docs

Feedback from @spottedmahn

**Comment by spottedmahn** [comment]
Hey @dend - I can't find #65.  Did it get deleted?

**Comment by dend** [comment]
@spottedmahn Issue functionality in the MicrosoftDocs/Docs repo was removed due to the fact that it is not the correct feedback channel for docs.microsoft.com - your issue was migrated over to MicrosoftDocs/feedback (see above).

**Comment by ShevaDas** [comment]
@spottedmahn Thanks for the feedback! I agree we should fix this. :) I've submitted an issue for it in our internal work tracker and will follow up here when it ships.

**Comment by spottedmahn** [comment]
Hi @dend - can you clarify why this issue was closed?  Thanks!
