### ISSUE TITLE
German translation error in Graph Docs

### ISSUE THREAD

**Issue by Steve2105** [MicrosoftDocs/feedback#2470]
**Link to article:**
https://docs.microsoft.com/de-de/graph/

**Problem:**
In the "Supported platforms" section there's a translation error in the German language: Angular is translated to "Winkel" which doesn't make any sense.

**Comment by srvbpigh** [comment]
Hello, @Steve2105
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello @Steve2105 

Thank you for your contribution. 

Contributions on translation problems against machine translated content are currently not accepted. 

We value your feedback and suggestions on human translated content, which is used to train the machine translation engines, so over time, your contributions will improve the quality of both human and machine translations. 

Human translated topics can be distinguished from machine translated topics by the ms.translationtype metadata value “HT” (versus “MT” for machine translated) in the header of each content file. 

Many thanks for your support. 

Microsoft DOCS Global Experience Team
