### ISSUE TITLE
HLSL reference pages use SAL, a C/C++ language feature

### ISSUE THREAD

**Issue by clandrew** [MicrosoftDocs/feedback#2471]
**Link to article:**
https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/structuredbuffer-load-float-uint-

**Problem:**
The method signature includes \_In\_ and \_Out\_, which are SAL- a C/C++ language feature. This page is documenting something in HLSL language and SAL is not really a 'thing' in HLSL.

HLSL has parameter modifiers- e.g., in, out (words by themselves), inout, vertices and indices (for mesh shaders). It might have been that these parameter modifiers were mistakenly identified by the doc system as C++ SAL.

The page linked above is one example, from a quick look around the issue is broader with the system and affects other pages as well

**Comment by KalleOlaviNiemitalo** [comment]
This was partially fixed in <https://github.com/MicrosoftDocs/win32/commit/2d9d99c2b75ccb45c33106850d9e01f4f6fcd873>. However, the code blocks are still tagged as C++ rather than HLSL.

**Comment by stevewhims** [comment]
I've published fixes for the original issue and the additional one. For the latter, since there were some legitimate C++ blocks, I used regex to fix just the incorrect ones.

-Steve
