### ISSUE TITLE
SELECTEDMEASURENAME and SELECTEDMEASURE wrong name shown (includes additional S)

### ISSUE THREAD

**Issue by HurikanLorenzo** [MicrosoftDocs/feedback#2472]
Links contain wrong function name in the scrollbar visible on the left side of the screen for the functions SELECTEDMEASURENAME and SELECTEDMEASURE, i.e. there is letter S after SELECTED.

https://docs.microsoft.com/en-us/dax/selectedmeasure-function-dax
https://docs.microsoft.com/en-us/dax/selectedmeasurename-function-dax

Visible on all browsers.

Regards, Marko.

**Comment by Minewiskan** [comment]
@HurikanLorenzo - Thanks for pointing this out. There were fifteen instances of that typo! it's fixed now.
#please-close
