### ISSUE TITLE
Gamification ideas and other feature suggestions

### ISSUE THREAD

**Issue by ManojG1978** [MicrosoftDocs/feedback#2473]
The new Microsoft Learning content and experience is awesome. I am hooked (I spend a couple of hours on modules every day). One of the reasons for the same is the gamification aspects already built in - badges, levels and trophies. I would suggest add a couple of more features to quantify the progress in learning:
1) Hours Completed, aggregated by month/quarter
2) Percentile for user profile (for e.g: Top 2% among Solution Architects globally)

Other features that would make the experience even more awesome:
1) Notes: Please add a capability to add notes for unit, module and learning path levels.
2) Ability to create and save custom searches at the profile level (instead of using filters all the time).

**Comment by alligreubel** [comment]
#log-suggestion @sadadow

**Comment by alligreubel** [comment]
Thank you for your suggestion! We've logged this internally and will reach out if we have any follow-up questions. In the meantime, this issue will be closed.
