### ISSUE TITLE
Sign-in Looping Issue with Learn and Q&A Site

### ISSUE THREAD

**Issue by jayendranarumugam** [MicrosoftDocs/feedback#2474]
**Describe the bug**
I couldn't able to login to DocsLearn and QA, it always looping and not able to login successfully for my account.

**To Reproduce**
1. Go to [Learn](https://docs.microsoft.com/en-us/learn/?source=learn) or [Q&A](https://docs.microsoft.com/answers/index.html)
2. Click on 'signin'
3. I've entered my credentials 
4.  Page loads and redirecting 

**Expected behavior**
I should able to login successfully 

**Screenshots**
![image](https://user-images.githubusercontent.com/25414541/73759536-1a48d700-4792-11ea-8c47-094010bfe761.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Browser chrome, Edge 
 - Version Chrome  79.0.3945.130 64 bit, Edge Version 79.0.309.71 (Official build) (64-bit)

**Additional context**
Please see that this issue is not related to [this one](https://github.com/MicrosoftDocs/feedback/issues/2466) as I already tried that workaround and it's not working in my case!

**Comment by saldana** [comment]
@jayendranarumugam we fixed the issue yesterday, but we require you to sign out and sign in as per the instructions in this post: https://docs.microsoft.com/answers/questions/8165/qa-sign-in-issues-or-errors.html. Can you try and let us know?

**Comment by jayendranarumugam** [comment]
@saldana , actually my problem is I even couldn't able to successfully sign in to the **https://docs.microsoft.com/en-us/learn/**
As per the link, it mentioned to logout from **learn** in my case sign in to learn itself is not working.

**Comment by jayendranarumugam** [comment]
I can able to login now
