### ISSUE TITLE
Typo in the explanation [RU]

### ISSUE THREAD

**Issue by bin1357** [MicrosoftDocs/feedback#2476]
**Link to article:** https://docs.microsoft.com/ru-ru/dotnet/csharp/tutorials/exploration/interpolated-strings?tutorial-step=3
**Problem:** В пояснении написано "_Задайте строку формата, указав ее после интерполированного выражения через **точку с запятой**._". А в коде используется **_двоеточие_**

**Comment by mairaw** [comment]
@JasonCard?

**Comment by JasonCard** [comment]
@DavidPrio Please help to take a look at this ru-ru HT issue.

**Comment by srvbpigh** [comment]
Hello, @bin1357
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by mairaw** [comment]
Was this fixed?

**Comment by srvbpigh** [comment]
Hello @bin1357:

We are evolving our internal process and engineering pipeline. Unfortunately, this is resulting in delays to processing your feedback.

We truly appreciate your contribution to our articles and we are looking forward to your continuous support and understanding.


Microsoft DOCS Global Experience Team

**Comment by JasonCard** [comment]
@mairaw Thank you for the reminder on this one. I've just requested to implement this feedback as an exception. 
@DavidPrio @CeciAc I've opened [LOC REQUEST 245585](https://ceapex.visualstudio.com/CEINTL/_workitems/edit/245585) for this issue.

**Comment by CeciAc** [comment]
Hello, @bin1357 
 
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/ru-ru/dotnet/csharp/tutorials/exploration/interpolated-strings?tutorial-step=3

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.
	
Kind regards,
Microsoft DOCS International Team
