### ISSUE TITLE
What is the manifest GUID for Windows Server 2019

### ISSUE THREAD

**Issue by Tratcher** [MicrosoftDocs/feedback#2477]
**Link to article:**
https://docs.microsoft.com/en-us/windows/win32/sbscs/application-manifests#supportedos

**Problem:**
What's the GUID that identifies Windows Server 2019 as a supported OS in the manifest? The latest listed server is 2016.

**Comment by mlottner** [comment]
@Tratcher  Thanks for taking the time to give us your feedback. 
We've tagged this issue for a member of the Windows docs team for awareness and research. 
Appreciate your patience and contribution to our docs community!
@GrantMeStrength Can you take a look?

**Comment by mcleanbyron** [comment]
Thanks for submitting your feedback. Windows Server 2019 uses the same GUID as Windows 10 and Windows Server 2016: 8e0f7a12-bfb3-4fe8-b9a5-48fd50a15a9a. We are updating the article accordingly.
