### ISSUE TITLE
Consider Providing Ability to Reference Specific Paragraph of Issue

### ISSUE THREAD

**Issue by dend** [MicrosoftDocs/feedback#248]
First off, amazing -- and clever, really -- work with integrating the documents system with GitHub.  Although I was a fan of using Disqus over LiveFyre when the that decision was made, using GitHub is better than both of them all around.

This request is to ask for the ability to comment/reference a particular paragraph within the document to provide better context between user and authors.  Please see this issue for context of some context: 😆 
https://github.com/MicrosoftDocs/azure-docs/issues/5955#issuecomment-374447456

Additionally, consider somehow making this the Title of the submitted issue (or part of the title at least), so that the user does not have to type in the title for the issue.  In thinking of a commenting system, titles are not used and seem passé in the way of outlook/email, etc.  GitHub is a little more formal than a social media commenting system, but we were all trained as such with the old way of doing things. 😄   In any case, providing the actual paragraph somehow as the starter title would address this issue.

Thank you for any consideration!

---

Migrated from MicrosoftDocs/Docs.

Feedback from @Mike-EEE

**Comment by Powerhelmsman** [comment]
@ShevaDas Can you take a look at Mike-EEE's suggestion about GitHub Issue?

**Comment by ShevaDas** [comment]
Thanks for the feedback, @Mike-EEE! These exact changes are a little out of scope for the near future, but I'll make sure we start evaluating other ways to address the pain points you're bringing up. Be on the lookout for more updates and improvements to the feedback system over the next few months. :)

**Comment by dend** [comment]
Given that this item is a `wont-fix` I am resolving it as such. @ShevaDas @Mike-EEE
