### ISSUE TITLE
QnA moderation 2

### ISSUE THREAD

**Issue by DSPatrick** [MicrosoftDocs/feedback#2481]
**Describe the bug**
QnA site spam detection adds them to Spam tab here https://docs.microsoft.com/answers/moderation/index.html?tab=akismet
but there no method to deal with these here. The only method to get rid of them is to Publish them then navigate to https://docs.microsoft.com/answers/index.html, find them again and Delete

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by DSPatrick** [comment]
Id there an update to this? Starting to be a real problem now that spam has increased

**Comment by saldana** [comment]
I shared with you documentation on how to deal or simply ignore the contents on the spam folder. We will work on improving the experience here.
