### ISSUE TITLE
Broken link on documents

### ISSUE THREAD

**Issue by tvanwijk** [MicrosoftDocs/feedback#2482]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem** (if available).

**Link to article:**
There is a link in this article
https://docs.microsoft.com/en-us/samples/azure-samples/active-directory-aspnetcore-webapp-openidconnect-v2/enable-webapp-signin/

Under the heading `Details of the chapters` There are 3 URL links under point 5 all of the pages references are moved/missing (404)

**Problem:**
Under the heading `Details of the chapters` There are 3 URL links under point 5 all of the pages references are moved/missing (404)
The bad URL reference are: https://docs.microsoft.com/en-us/samples/azure-samples/active-directory-aspnetcore-webapp-openidconnect-v2/enable-webapp-signin/5-WebApp-AuthZ/5-2-Groups/README-incremental-instructions.md
https://docs.microsoft.com/en-us/samples/azure-samples/active-directory-aspnetcore-webapp-openidconnect-v2/enable-webapp-signin/5-WebApp-AuthZ

**Comment by rootsmusic** [comment]
@tvanwijk Please move this issue to https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/issues

**Comment by tvanwijk** [comment]
I'm not sure how to move an issue. This is more of a courtesy ticket because stuff isn't right, than something I'm invested in. Feel free to close or move or whatever.

**Comment by rootsmusic** [comment]
@tvanwijk, you can just close this issue (copy and paste) and open one in https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/issues.  That's the repo where this issue's doc is maintained.  Thanks.

**Comment by tvanwijk** [comment]
Looks like the links were already corrected.
