### ISSUE TITLE
Consider Item-level "View on GitHub"

### ISSUE THREAD

**Issue by dend** [MicrosoftDocs/feedback#249]
There is a "View on GitHub" link for the entire list of issues.  It would be valuable/useful to have this same functionality for each individual item as well.  Thank you for any consideration in having this developed.

---

Migrated from MicrosoftDocs/Docs

Feedback from @Mike-EEE

**Comment by Powerhelmsman** [comment]
@ShevaDas This is one suggestion for GitHub issue feedback. Please take a look at this

**Comment by svick** [comment]
I think this already exists, though it's not quite obvious. For example, consider [this document](https://docs.microsoft.com/en-us/visualstudio/ide/reference/go-to-line#feedback), where I just left feedback:

![](https://user-images.githubusercontent.com/287848/37784259-a1bce340-2df7-11e8-87bd-58c1fa18bec4.png)

It has the big, obvious "View on GitHub" link, which lists all the issues for the page, as you mentioned.

But you can also click on the issue number ("#<span></span>729") to go to the GitHub page for that one issue.

I guess this is something that many people will want to do, so I think it makes sense to somehow make that link more prominent.

**Comment by Mike-EEE** [comment]
Ah!  indeed you are correct @svick!  My impression was that the `#729` was simply bolded and not clickable.  I was looking for something fancy and colorful like the overview `View on GitHub` link as you describe.  So I suppose the ask here is to consider making the `#729` more colorful/obvious that it takes you to the GitHub direct version.

**Comment by Mike-EEE** [comment]
FWIW I think putting that little open new window icon to the left of the issue number will do the trick.  Maybe make it the same color as the issue number text.

**Comment by ShevaDas** [comment]
@Mike-EEE thanks for the feedback—I actually had this thought earlier today about adding an "external window" indicator after spending a little too long trying to figure out how to jump from an issue on Docs to it on GitHub. :) I'll file an issue in our internal work tracker and follow up when it ships.

**Comment by ShevaDas** [comment]
@Mike-EEE I'm happy to report that this work has shipped—we've updated the design to make it clear that both the issue number and issue author are clickable links. I'm going to close this out for now. Thanks again for the feedback, and I hope you enjoy the new experience!

![image](https://user-images.githubusercontent.com/3937986/38589777-e960dfdc-3ce1-11e8-9777-7b17584dd10b.png)
