### ISSUE TITLE
Language redirection

### ISSUE THREAD

**Issue by janhruby** [MicrosoftDocs/feedback#2492]
**Describe the bug**
When browsing online documentation, browser language is always used as display language. Since reading documentation in poorly autotranslated non-english language is next to useless, it would be awesome if English would be default language of all docs and translated articles as second option. Its frustrating to scroll to bottom of every page to select usable language.

**Expected behavior**
Let English be default language and make translated (especially autotranslated) variants optional.

**Comment by docs-product** [comment]
Duplicate of #462
