### ISSUE TITLE
Tile titles on Visual Studio documentation landing page are not translated

### ISSUE THREAD

**Issue by kimadeline** [MicrosoftDocs/feedback#2493]
**Describe the bug**
Hello,

When on the Visual Studio 2019 documentation landing page, the titles for the tiles underneath the Visual Studio documentation banner (`download`, `overview`, `get started` and `learn`) are not translated.

**To Reproduce**
1. Go to https://docs.microsoft.com/zh-tw/visualstudio/windows/?view=vs-2019
2. Observe that the tile titles below the purple banner are not translated

**Expected behavior**

`download`, `overview`, `get started` and `learn` to be translated.

**Screenshots**

![image](https://user-images.githubusercontent.com/51720070/74385273-0b70ae80-4da8-11ea-9598-438f4595620e.png)

**Desktop (please complete the following information):**
 - OS: macOS 10.14 (Mojave)
 - Browsers + versions: 
   - Firefox 72.0.2
   - Edge 79.0.309.71

**Comment by rootsmusic** [comment]
Fixed.
#please-close
