### ISSUE TITLE
PDF generation

### ISSUE THREAD

**Issue by kov-serg** [MicrosoftDocs/feedback#2499]
**Describe the bug**
PDF output is not tested

**To Reproduce**
1. Go to https://docs.microsoft.com/en-us/windows/win32/shell/preview-handlers
or direct link https://opdhsblobprod04.blob.core.windows.net/contents/672ff4a2a66944e1beedf884979d3bae/3d32ebdbe6e41628644b263890643bf0?sv=2015-04-05&sr=b&sig=cIIJgeTBajbdZ3WisMClQqGcasOejXcybeOxwmnRXGw%3D&st=2020-02-13T21%3A24%3A25Z&se=2020-02-14T21%3A34%3A25Z&sp=r
2. Click on Download PDF
3. Scroll down to to page 256 or 781
4. See error. 

**Expected behavior**
Print document should have page numbers and use paper less wastefully.

**Screenshots**
https://i.imgur.com/9q7ypbi.png
https://i.imgur.com/6l2A5su.png

**Comment by rootsmusic** [comment]
@kov-serg In step 4 (to reproduce), I don't see your screenshots when viewing the .pdf.

**Comment by kov-serg** [comment]
If you interesting how it look in 2020 here is screen shots:
![9q7ypbi](https://user-images.githubusercontent.com/5946122/127484540-acaabe00-4a80-4005-808c-253fea451daf.png)
![6l2A5su](https://user-images.githubusercontent.com/5946122/127484543-5e41d7e5-41ec-498f-b262-7529d6229547.png)
But now situation is changed. And pdf generation is much better.

**Comment by rootsmusic** [comment]
#please-close
