### ISSUE TITLE
Improve Machine Translation

### ISSUE THREAD

**Issue by glibnub** [MicrosoftDocs/feedback#25]
In this page:
https://docs.microsoft.com/zh-tw/aspnet/mvc/overview/getting-started/introduction/getting-started

For more natural to native
Please change the translation of the following sentences:

(For example, instead of selecting New Project from the Start page, you can use the menu and select File > New Project.)

the port number is 1234

From Now:

(例如，而不是選取新的專案從啟動 頁面上，您可以使用功能表並選取檔案 > 新專案.)

連接埠號碼是 1234年

To this one:

(例如，您可以使用功能表並選取檔案 > 新專案，而不是從啟動 頁面上選取新的專案.)

連接埠號碼是 1234

----------
⚠ Idea migrated from UserVoice

**Created By:** K.K
**Created On:** 2018/02/21 09:48:54 +0000
**Votes at Migration:** 5
**Supporters at Migration:** 4

**Comment by dend** [comment]
@SonjaSaltzman assigning to you to properly route.

**Comment by SonjaSaltzman** [comment]
@nokura could you please follow up?

**Comment by Powerhelmsman** [comment]
@nokura Is there any update so far?

**Comment by SonjaSaltzman** [comment]
@v-jacard  - Jason, could you please take care of this translation fix?  thanks!

**Comment by v-jacard** [comment]
@SonjaSaltzman, @nokura, I've notified production and feedbacks team to follow up on this and will update.
