### ISSUE TITLE
Dead Link

### ISSUE THREAD

**Issue by BookHsu** [MicrosoftDocs/feedback#250]
I read Docs with this page

https://docs.microsoft.com/zh-tw/visualstudio/productinfo/2017-redistribution-vs

when i click this link

![default](https://user-images.githubusercontent.com/29597478/37692000-dd1e6b14-2cf0-11e8-9ad6-eea756e718b0.png)

redirect like this

![default](https://user-images.githubusercontent.com/29597478/37692017-f99d77d0-2cf0-11e8-8bde-a7ac073dc96b.png)

for English version is the same

![default](https://user-images.githubusercontent.com/29597478/37692038-17d658b6-2cf1-11e8-83c2-5505d0447a8d.png)

Sorry for my pool English...

**Comment by Powerhelmsman** [comment]
@BookHsu Thanks you for reporting this issue. We are investigating now.

**Comment by v-bigrab** [comment]
The URL has been updated and the issue has been resolved. The correct url is:
https://webpifeed.blob.core.windows.net/webpifeed/eula/aspnetcomponent_rtw_ENU.htm
