### ISSUE TITLE
Microsoft Learn - XP not earned although modules are completed

### ISSUE THREAD

**Issue by noxouille** [MicrosoftDocs/feedback#2503]
**Describe the bug**
Completed several learning modules but XP are not being accumulated.

**To Reproduce**
1. start completing any modules
2. XP are not earned

**Expected behavior**
XP should be accumulated. In particular, my XP stuck at 55300 at lv 8.

**Screenshots**
![stuck at level8](https://user-images.githubusercontent.com/1827216/74559903-6a166380-4f33-11ea-8b4f-647746b124c5.png)

**Comment by jlanter** [comment]
I'm having the same problem!!  A similar issue was reported in Post #2500: https://github.com/MicrosoftDocs/feedback/issues/2500

**Comment by baardhermansen** [comment]
I'm experiencing the same. Modules registered as completed and "point bar" (for the lack of a better word) shows as green. 
Also tried to log out and back in again, revisited the modules but they are registered as completed, but still no points awarded.

**Comment by mikelowe983** [comment]
I am having the same issue. Began yesterday afternoon (Thursday February 13, 2020). I *MAY* have been related to backtracking units within a module, but I'm not sure. I can see AJAX calls made to log the progress and XP. 
For example, a call to this URL is made:

`https://docs.microsoft.com/api/learn/units/learn.prepare-azure-dev-environment.3-exercise-set-up-dev-environment/progress?locale=en-ca`

And the browser receives the following response:

```json
{
  "updated": true,
  "passed": true,
  "achievements": [
    {
      "uid": "learn.prepare-azure-dev-environment.3-exercise-set-up-dev-environment",
      "type": "unit",
      "points": [{ "value": 100, "reasonId": "points.unit.basic.completed" }]
    }
  ]
}
```

However, no XP points are ever rewarded.

**Comment by sgstuart** [comment]
I also started having this problem about an hour ago.   It was fine earlier this morning.   I have signed off and signed back in and even restarted the computer.   I have been stuck at the same points from 2 modules ago.   I am on the last part of Azure Fundamentals.

**Comment by docs-product** [comment]
Our engineers are actively looking at resolving the issue. Thank you for the report!

**Comment by docs-product** [comment]
Our engineering team has addressed the issue. Thank you for the feedback!
