### ISSUE TITLE
Cannot Access https://social.microsoft.com/Forums when logged in

### ISSUE THREAD

**Issue by benua74** [MicrosoftDocs/feedback#2506]
**Describe the bug**
Everytime I go to  https://social.microsoft.com/Forums when logged in, I get a "Runtime Error", with this error: **Server Error in '/Forums' Application**.
I can only access theses webpages as an anonymous visitor. I don't know what's wrong.
Thank you for your help.

**To Reproduce**
1. Go to https://social.microsoft.com/Forums
2. Log in successfully with my creds
4. See error below

**Screenshots**
_Browser error:_
![image](https://user-images.githubusercontent.com/41381479/74642442-46d9f700-5173-11ea-8017-66cbef132091.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Edge & Chrome
 - Version: up to date

**Comment by rootsmusic** [comment]
@benua74 It has closed at https://docs.microsoft.com/en-us/teamblog/msdn-technet-english-forums-closure
