### ISSUE TITLE
Typo in the TcpListener Class code snippet 

### ISSUE THREAD

**Issue by Storm312** [MicrosoftDocs/feedback#2509]
https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.tcplistener?view=netframework-4.8

In the code snippet of the example it says

![Typo](https://user-images.githubusercontent.com/31706230/74689988-98b76700-51dd-11ea-947b-ee94c29d8b34.png)

The "user" should probably be replaced with "use"

**Comment by mairaw** [comment]
Thanks for your feedback @Storm312. I've opened a couple of PRs to fix this issue.
