### ISSUE TITLE
Feature request: Display expected REPL output in an optional window

### ISSUE THREAD

**Issue by BillWagner** [MicrosoftDocs/feedback#251]
See dotnet/docs#4571 for background discussion.

This applies to reference, and how-to pages that make use of the C# REPL window. 

Readers want to see the expected results of a block of code to check against what is actually displayed. The ability to show the expected output (not the run output) as a check would aid learning.

**Comment by dend** [comment]
Assigning to @yunyunyunyun as the PM driving interactive.

**Comment by keziamicro** [comment]
Hello - reviewing and cleaning up some older feedback/issues. Thanks!
