### ISSUE TITLE
Sample Download Link is broken

### ISSUE THREAD

**Issue by tugcearar** [MicrosoftDocs/feedback#2516]
**Link to article:**
https://docs.microsoft.com/tr-tr/aspnet/web-forms/overview/data-access/introduction/master-pages-and-site-navigation-vb?source=docs

**Problem:**
Download Sample App link is broken and return a 404 error.

**Comment by gewarren** [comment]
@scottaddie Here's the English page - download sample app link is near the top:

https://docs.microsoft.com/en-us/aspnet/web-forms/overview/data-access/introduction/master-pages-and-site-navigation-vb?source=docs

**Comment by stugcearar** [comment]
Ok, thank you!
