### ISSUE TITLE
Not able to upload to Script Center

### ISSUE THREAD

**Issue by VikasSukhija** [MicrosoftDocs/feedback#2524]
https://gallery.technet.microsoft.com/scriptcenter

Upload option missing so not able to contribute new scripts.

![Capture](https://user-images.githubusercontent.com/49596304/75117870-07ac1a00-563b-11ea-9020-5312ce3459ac.PNG)

**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem** (if available).

**Link to article:**
Tell us where exactly a problem occurs.

**Problem:**
What's wrong with the article?

**Comment by rootsmusic** [comment]
@VikasSukhija, TechNet Gallery has been closed at https://docs.microsoft.com/en-us/teamblog/technet-gallery-retirement
