### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by jt-65** [MicrosoftDocs/feedback#253]
The link to the WsusDBMaintenance script in https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/dd939795(v=ws.10) is broken.

The target of the broken link is http://go.microsoft.com/fwlink/?linkid=87027

There are several TechNet and third-party forums that reference this document.

**Comment by dend** [comment]
@Khairunj can you please help with the link fix? The correct pointer should be: https://gallery.technet.microsoft.com/scriptcenter/6f8cde49-5c52-4abd-9820-f1d270ddea61

**Comment by Khairunj** [comment]
This is Windows content and Tara is fixing it.

**Comment by Khairunj** [comment]
Thank you jt-65 the broken link is now fixed and it points to TechNet gallery,
