### ISSUE TITLE
FileStream IntPtr constructors should be marked obsolete

### ISSUE THREAD

**Issue by binki** [MicrosoftDocs/feedback#254]
I am looking at [the rendered `FileStream` constructors list](https://docs.microsoft.com/en-us/dotnet/api/system.io.filestream?view=netframework-4.7.1#constructors-). I do not see any indication that the `IntPtr` constructors are marked Obsolete. However, in [the MSDN documentation for `FileStream`](https://msdn.microsoft.com/en-us/library/system.io.filestream(v=vs.110).aspx?f=255&mspperror=-2147217396#Anchor_2), the `IntPtr` overloads are very obviously marked obsolete.

## Issue Details

I do not see any indication that the overloads are obsolete. This is what I am seeing in my browser:

![image](https://user-images.githubusercontent.com/82626/37727094-5c0285f2-2d0d-11e8-9709-b79d5356b20a.png)

**Comment by binki** [comment]
I can tell that it is still obsolete in .net-4.7 by running:

```
> typeof(FileStream).GetConstructor(new[]{typeof(IntPtr), typeof(FileAccess)}).GetCustomAttribute<ObsoleteAttribute>()
ObsoleteAttribute { IsError=false, Message="This constructor has been deprecated.  Please use new FileStream(SafeFileHandle handle, FileAccess access) instead.  http://go.microsoft.com/fwlink/?linkid=14202", TypeId=[System.ObsoleteAttribute] }
> using Microsoft.Win32;
> using (var key = RegistryKey.OpenBaseKey(RegistryHive.LocalMachine, RegistryView.Registry32).OpenSubKey("SOFTWARE\\Microsoft\\NET Framework Setup\\NDP\\v4\\Full\\")) { Console.WriteLine(key.GetValue("Release")); }
461805
```

**Comment by dend** [comment]
@mairaw @BillWagner seems like something your team can look into.

**Comment by mairaw** [comment]
@dend this is a difference between how docs and msdn handle APIs. It should be a feature request for the engineering team. Individual APIs are marked obsolete: https://docs.microsoft.com/en-us/dotnet/api/system.io.filestream.-ctor?view=netframework-4.7.1#System_IO_FileStream__ctor_System_IntPtr_System_IO_FileAccess_System_Boolean_System_Int32_System_Boolean_

but that information should be displayed on the members table too like MSDN.

**Comment by Powerhelmsman** [comment]
#log-suggestion @dend

**Comment by botcrane** [comment]
🚀 **ATTENTION**: [Internal request](https://ceapex.visualstudio.com/web/wi.aspx?pcguid=7d644393-99ad-41c8-ac53-7fa79294c720&id=23033) logged.

**Comment by dend** [comment]
Following-up on this issue - given that there is an internal tracking work item, and we don't have a definitive timeframe for the fix, I will close this issue.

We will continue to investigate how we can make the UX and presentation around the overload table better.
