### ISSUE TITLE
Download MBSA (http://www.microsoft.com/en-us/download/details.aspx?id=7558) link broken

### ISSUE THREAD

**Issue by chanmmn** [MicrosoftDocs/feedback#2540]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem** (if available).

**Link to article:**
 https://docs.microsoft.com/en-us/previous-versions/cc184924(v=msdn.10)?redirectedfrom=MSDN&source=docs

**Problem:**
Download MBSA (http://www.microsoft.com/en-us/download/details.aspx?id=7558) link broken at the page https://docs.microsoft.com/en-us/previous-versions/cc184924(v=msdn.10)?redirectedfrom=MSDN&source=docs

**Comment by rootsmusic** [comment]
@chanmmn "We're no longer updating this content regularly."
#please-close
