### ISSUE TITLE
ASP.NET Profile Properties Overview (not fully correct example)

### ISSUE THREAD

**Issue by DSivtsov** [MicrosoftDocs/feedback#2541]
[**Link to article:**](https://docs.microsoft.com/en-us/previous-versions/aspnet/2y3fs9xs(v=vs.100))

**Problem:**
On the Page shown example, which won't work without additional code. Are commonly, when user testing anything features from "Microsoft Doc Site", it used simple Web Site without users authentication. In this case, that example  won't work.

Please add comment regarding that this example will work only if site used by authenticated users, and make link to the [page](https://docs.microsoft.com/en-us/previous-versions/aspnet/ewfkf772(v=vs.100)) "User Identification for ASP.NET Profile Properties", which describing it more detail.

**Comment by gewarren** [comment]
@scottaddie FYI

**Comment by rootsmusic** [comment]
@DSivtsov "We're no longer updating this content regularly."
#please-close
