### ISSUE TITLE
[LOC] Back-Translation "2 行分"→"Double"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/feedback#2543]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem** (if available).
![controlscore_j](https://user-images.githubusercontent.com/40815708/75508924-14f54a00-5a29-11ea-8824-0059f2164cc1.png)

**Link to article:**
Tell us where exactly a problem occurs.
"https://docs.microsoft.com/ja-jp/graph/api/resources/controlscore?view=graph-rest-1.0"

**Problem:**
What's wrong with the article?
[LOC] Back-Translation "2 行分"→"Double"

**Comment by TinaMcN** [comment]
@OfficeGlobal please human translate the article.

**Comment by hyoshioka0128** [comment]
@TinaMcN, related:#7231 | #7232

**Comment by OfficeGlobal** [comment]
@hyoshioka0128 article was HumanTranslated. Data types were reverted to ENG

**Comment by hyoshioka0128** [comment]
@OfficeGlobal @TinaMcN  - "Double" has been Fixed. Thanks.
Closed #2543.
