### ISSUE TITLE
Typo in "Data Platform & Analytics Foundational for Data Platform Competency" module "SQL Server EIM"

### ISSUE THREAD

**Issue by Anjulishankhwar** [MicrosoftDocs/feedback#2544]
**Link to article:**
https://partneruniversity.microsoft.com/?whr=uri:MicrosoftAccount

**Problem:**
Course : Data Platform & Analytics Foundational for Data Platform Competency (MPN14354)
Module from the syllabus : SQL Server EIM
Issue: @0:43 in slide it says EIM improves 
 1. Completeness
 2. Cleanliness
 3. Consistency
 4. “CURRENCY” (where as further in course  (@ 2:38) it is mentioned as “CURRENT DATA”).

It should be “CURRENT DATA” @ 0:43 in slide.

**Comment by rootsmusic** [comment]
@Anjulishankhwar Please contact product support at https://partner.microsoft.com/en-US/support/?stage=1
#please-close
