### ISSUE TITLE
Microsoft Teams product name should not be translated into Hungarian

### ISSUE THREAD

**Issue by kborkowski** [MicrosoftDocs/feedback#2545]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem** (if available).

**Link to article:**
[https://docs.microsoft.com/hu-hu/](https://docs.microsoft.com/hu-hu/)

**Problem:**
Link text to **Microsoft Teams** should remain in English.

![image](https://user-images.githubusercontent.com/24527040/75563943-847c3100-5a4b-11ea-96fa-04099f7856d9.png)

**Comment by rootsmusic** [comment]
Fixed.
#please-close
