### ISSUE TITLE
No path to https://docs.microsoft.com/en-us/windows-hardware/manufacture/

### ISSUE THREAD

**Issue by tofergus** [MicrosoftDocs/feedback#2546]
Why is https://docs.microsoft.com/en-us/windows-hardware/manufacture/ no longer linked from https://docs.microsoft.com/en-us/windows/? There is a fair amount of information in the Desktop section that is relevant to IT pros.

**Comment by rootsmusic** [comment]
@tofergus Please click on "Hardware developers" on https://docs.microsoft.com/en-us/windows/

**Comment by tofergus** [comment]
Yes, thanks. Wasn't there when I originally submitted.
