### ISSUE TITLE
Exchange Online Module

### ISSUE THREAD

**Issue by Sims1990** [MicrosoftDocs/feedback#255]
# Exchange Modules Added to PowerShell Module Browser

Is it possible to add the Exchange Online module into the module browser.

**Comment by Powerhelmsman** [comment]
@EdisonDa Can you take a look this suggestion?

**Comment by EdisonDa** [comment]
Thank you Malcolm for your great suggestion. Yes, we already planned it and it is already in progress. You can try it soon.

**Comment by EdisonDa** [comment]
@Sims1990 Thank you Malcolm for your great suggestion. Yes, we already in progress, and we will let you know once we release it.

**Comment by keziamicro** [comment]
Hello - reviewing and cleaning up some older feedback/issues. Thanks!
