### ISSUE TITLE
I hope that Microsoft Docs can adjust the functions of "Multilingual Display".

### ISSUE THREAD

**Issue by Lingggao** [MicrosoftDocs/feedback#2550]
**Dear Microsoft engineers, hello!**

**Is your feature request related to a problem? Please describe.**
I'm from China, and when I browse the Chinese version of Microsoft Docs, the experience is a bit bad.

**Describe the solution you'd like**
I hope that Microsoft Docs can adjust the functions of "Multilingual Display".

**Describe alternatives you've considered**
1. Add a "language switch" button next to the Microsoft account avatar in the upper right corner of the webpage (for example, added in the red box in screenshot 1). After pressing, I can directly switch between English and the currently selected language. For example, if I am currently viewing a Chinese language document, pressing this button will quickly switch between Chinese and English, so that I can directly view the English document when the Chinese translation is difficult to understand.
2. Improve "language switching" in the lower left corner of the page (the option in the green circle). Currently, after clicking this language switch button, a new page will open. The user needs to click the desired language in the new page to switch. This operation is not very convenient. I hope that after clicking the button to switch languages, a sub-page will pop up on the current page, which is about the size of the blue square in the figure. The user can switch the language directly on the current page without jumping to other web pages, Which can optimize the experience of using this feature.

**Additional context**
Screenshot 1:
![01](https://user-images.githubusercontent.com/49932219/75627496-af14e800-5c0b-11ea-8eba-f5d2de237cdd.png)
Screenshot 2:
![02](https://user-images.githubusercontent.com/49932219/75627690-59413f80-5c0d-11ea-88bd-62bcee162ccc.png)

**Heartfelt thanks to the hard work of Microsoft engineers!**

**Comment by alligreubel** [comment]
#log-suggestion

**Comment by alligreubel** [comment]
Thank you for your suggestion! We've logged this internally and will reach out if we have any follow-up questions. In the meantime, this issue will be closed.
