### ISSUE TITLE
Azure compliance - Documentation typo

### ISSUE THREAD

**Issue by Guillaume-MSFT** [MicrosoftDocs/feedback#2551]
Hello team,

I believe we have an error in our Azure public documentation regarding health sector.
It's in the following document: https://gallery.technet.microsoft.com/Overview-of-Azure-c1be3942.
 
On page 35, section "48 HDS (France)", in the "Services in scope" column (end of paragraph), it mentions "_See ISO 27001 scope statement within the France, Amsterdam, and
Ireland data centers (Azure Region: Central France, South France, North
Europe, and **East Europe**)_".

I believe there is no such "East Europe" azure region, and that it is West Europe region who is covered by the HDS certification (from other docs).

Can we confirm and correct please ?
Thanks.

**Comment by rootsmusic** [comment]
@Guillaume-MSFT TechNet Gallery has closed at https://docs.microsoft.com/en-us/teamblog/msdn-technet-english-forums-closure
