### ISSUE TITLE
DateTime.Subtract Method wrong return value

### ISSUE THREAD

**Issue by Marianna416** [MicrosoftDocs/feedback#2552]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem** (if available).

**Link to article:**
https://docs.microsoft.com/en-us/dotnet/api/system.datetime.subtract?view=netframework-4.8

**Problem:**
In first (but not only this one) sentence is written:
Returns a new **DateTime** that subtracts the specified time or duration from the value of this instance.
But it returns **TimeSpan**.

**Comment by mairaw** [comment]
This has been fixed. Closing.
