### ISSUE TITLE
[LOC]Back-Translation "新しいラベル"→"New Label"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/feedback#2554]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem** (if available).
![new-label_j](https://user-images.githubusercontent.com/40815708/75762453-0935ba80-5d7e-11ea-9656-579ed4a70709.png)

**Link to article:**
Tell us where exactly a problem occurs.
"https://docs.microsoft.com/ja-jp/powershell/module/exchange/policy-and-compliance/new-label?view=exchange-ps"

**Problem:**
What's wrong with the article?
[LOC]Back-Translation "新しいラベル"→"New Label"

**Comment by TinaMcN** [comment]
@OfficeGlobal this article is already human translated.  Please review and fix the issue.  FYI @Soran-M overtranslation in HT powershell article.

**Comment by OfficeGlobal** [comment]
Working on a fix

**Comment by OfficeGlobal** [comment]
@hyoshioka0128 the translation was updated and published live

**Comment by hyoshioka0128** [comment]
@OfficeGlobal - Fixed.
Closed #2554.
Thanks.
