### ISSUE TITLE
Typo "Get-messageclassification"→"New-MessageClassification"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/feedback#2555]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem** (if available).
![Get-messageclassification_1](https://user-images.githubusercontent.com/40815708/75763714-089e2380-5d80-11ea-9fb5-86bbd12a6461.png)

![Get-messageclassification_2](https://user-images.githubusercontent.com/40815708/75763750-1653a900-5d80-11ea-8112-4f671abfcf55.png)

**Link to article:**
Tell us where exactly a problem occurs.
"https://docs.microsoft.com/ja-jp/powershell/module/exchange/policy-and-compliance/new-messageclassification?view=exchange-ps"

**Problem:**
What's wrong with the article?
Typo "Get-messageclassification"→"New-MessageClassification"

**Comment by TinaMcN** [comment]
@OfficeGlobal please human translate the issue.  @Soran-M FYI, MT issue in PowerShell content.

**Comment by OfficeGlobal** [comment]
Working on a fix

**Comment by OfficeGlobal** [comment]
@hyoshioka0128 article was HumanTranslated and published live. The issue is fixed

**Comment by hyoshioka0128** [comment]
@OfficeGlobal - Fixed.
Closed #2555.
Thanks.
