### ISSUE TITLE
SQL technet do not indicate japanese sentense. 

### ISSUE THREAD

**Issue by hiomori** [MicrosoftDocs/feedback#2557]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem** (if available).

**Link to article:**
Fllowings  are SQL technet link. Those of pages are indicated in english wven it is japanese page.
https://docs.microsoft.com/ja-jp/sql/?view=sql-server-ver15
https://docs.microsoft.com/ja-jp/sql/sql-server/what-s-new-in-sql-server-ver15?view=sql-server-ver15
**Problem:**

Every SQL Japanese pages are changed to english. Customer need to fix for this issue

**Comment by rootsmusic** [comment]
@himori Please check your browser's language setting because I see Japanese.
#please-close
