### ISSUE TITLE
[LOC]Back-Translation "新しい ActivityAlert"→"New-ActivityAlert"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/feedback#2558]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem** (if available).
![new-activityalert_j](https://user-images.githubusercontent.com/40815708/75841829-08e6ff00-5e12-11ea-83c4-4a5c2cff1b94.png)

**Link to article:**
Tell us where exactly a problem occurs.
"https://docs.microsoft.com/ja-jp/powershell/module/exchange/policy-and-compliance/new-activityalert?view=exchange-ps"

**Problem:**
What's wrong with the article?
[LOC]Back-Translation "新しい ActivityAlert"→"New-ActivityAlert"

**Comment by TinaMcN** [comment]
@OfficeGlobal please human translate the issue.  @Soran-M FYI, MT issue in PowerShell content.

**Comment by SonjaSaltzman** [comment]
hi @alligreubel - I'd already triaged this and assigned to @TinaMcN (loc contact in Office team, who owns this content). So reassigning it to her again.

**Comment by OfficeGlobal** [comment]
@hyoshioka0128 article was HumanTranslated and published live. The issue is fixed

**Comment by TinaMcN** [comment]
@hyoshioka0128 can you check if the issue is fixed?

**Comment by hyoshioka0128** [comment]
@TinaMcN - Fixed.
Closed #2558.
Thanks.
