### ISSUE TITLE
clumsy coding in MS docs for EqualityComparer<T> Class

### ISSUE THREAD

**Issue by DickBaker** [MicrosoftDocs/feedback#256]
# Idea Title

The coding example is unwieldy and can be improved and simplified

## Issue Details
on page
https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.equalitycomparer-1?view=netframework-4.7.1
there is this ugly code
		if (b1.Height == b2.Height && b1.Length == b2.Length
							&& b1.Width == b2.Width)
		{
			return true;
		}
		else
		{
			return false;
		}
whereas IMHO it should simply read
		return (b1.Height == b2.Height && b1.Length == b2.Length
							&& b1.Width == b2.Width)

however this was an improvement on the previous docs that also wrapped an else clause making that vintage code even worse.

**Comment by dend** [comment]
@mairaw @BillWagner as FYI

**Comment by mairaw** [comment]
@dend that looks like a good suggestion. 

You can move that to our repo if you want.

@DickBaker our documentation is all open source now. Feel free to submit issues and PRs with your suggestions.

If you'd like, you can edit the C# sample here:
https://github.com/dotnet/docs/blob/master/samples/snippets/csharp/VS_Snippets_CLR_System/system.collections.generic.equalitycomparer/cs/program.cs

and usually we keep the samples in sync, so the VB one is here:
https://github.com/dotnet/docs/blob/master/samples/snippets/visualbasic/VS_Snippets_CLR_System/system.collections.generic.equalitycomparer/vb/program.vb

**Comment by mairaw** [comment]
nope @dend. I'll manually copy then.

**Comment by mairaw** [comment]
Moved to https://github.com/dotnet/docs/issues/5158. You can close this one.
