### ISSUE TITLE
Documentation for Powershell for SQL IntegrationServices

### ISSUE THREAD

**Issue by SuperSing** [MicrosoftDocs/feedback#2562]
Hi, where can I find documentation for altering the properties  for SSIS Catalog like "Retention Period (days)","Server-wide Default Logging Level" using powershell ? A link to a powershell documentation will be useful. Thank you !

**Comment by rootsmusic** [comment]
@SuperSing Results at https://docs.microsoft.com/en-us/search/?terms=SSIS%20Powershell&category=Documentation
#please-close
