### ISSUE TITLE
Many pages are broken on WinHTTP docs

### ISSUE THREAD

**Issue by doodleincode** [MicrosoftDocs/feedback#2565]
**Link to article:**
Just to name a few:
https://docs.microsoft.com/en-us/windows/win32/api/winhttp/ns-winhttp-winhttp_autoproxy_options
https://docs.microsoft.com/en-us/windows/win32/api/winhttp/ns-winhttp-winhttp_proxy_info
https://docs.microsoft.com/en-us/windows/desktop/api/winhttp/ns-winhttp-winhttp_current_user_ie_proxy_config

**Problem:**
A bunch of pages are broken in the WinHTTP documentation. They seems to be concentrated on documentation for WinHTTP structures.

Will this be fixed soon? It's pretty annoying to have to look at a Google cached page - which eventually will not work either.

**Comment by rootsmusic** [comment]
@doodleincode Your links aren't broken.

**Comment by doodleincode** [comment]
> @doodleincode Your links aren't broken.

Thanks.
