### ISSUE TITLE
Hardware reserved memory [ Not fixable using Bios ] after version 2004

### ISSUE THREAD

**Issue by 0xAssault** [MicrosoftDocs/feedback#2568]
**Describe the bug**
in previews windows versions i would set up vram in the bios and that's it im good to go all my ram is then usable by windows. But that wasn't the case after i have installed version 2004 20h1 since then windows started taking up 2gb of my ram as Hardware reserved and even if change Bios, its just a matter of a reboot so that windows takes back the 2gb of ram somehow its really buggin me since im very limited in terms of hardware resources and i like to make use of what i got, can't have windows yoinking ram like that, i don't play games and even if did i don't want to have system ram dedicated for the igpu

**Screenshots**
![2](https://user-images.githubusercontent.com/50592071/76161896-815e0080-612f-11ea-8082-597084a20801.PNG)
![Capture](https://user-images.githubusercontent.com/50592071/76161897-828f2d80-612f-11ea-8d5b-11c527e11e35.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10, version 2004 (

**Comment by rootsmusic** [comment]
@0xAssault Please ask product support or in support forums.
#please-close
