### ISSUE TITLE
CspParameters class OS compatibility

### ISSUE THREAD

**Issue by badermessaoudi** [MicrosoftDocs/feedback#2569]
**Link to article:**
https://docs.microsoft.com/fr-fr/dotnet/api/system.security.cryptography.cspparameters?view=netstandard-2.0

**Problem:**

Hello,

I have a question regarding the class CspParameters.

it says on the MSDN page that it's supported in the Net Core and Net Standard, but unfortunately, it's not the case in all the operating systems, it only works in Windows. On Linux, i have an exception saying that it's not supported on the current system, and on Windows, it works correctly without exception.

Why it's not specified on the msdn page ? i thought that the Net Standard library offers a full compatibility in all the systems.

Does this means that there is some classes that are included on the Net standard library and they don't work on all the operating systems ? If so, there is a need to specify it on the class MSDN's page.

**Comment by mairaw** [comment]
@gewarren @BillWagner should probably transfer this into the dotnet-api-docs repo

**Comment by gewarren** [comment]
This issue was moved to dotnet/dotnet-api-docs#4077
