### ISSUE TITLE
Windows CE 5.0 and 6.0 webpages on msdn have disappeared

### ISSUE THREAD

**Issue by arbitraryuser** [MicrosoftDocs/feedback#257]
Example:
https://msdn.microsoft.com/en-us/library/ms889212.aspx
https://msdn.microsoft.com/en-us/library/aa453173.aspx

A lot of us need to support applications on 5.0 and 6.0 and we need this content.

**Comment by dend** [comment]
@Khairunj can you help identify the source of the problem here?

**Comment by dend** [comment]
Thanks for the feedback, @arbitraryuser - the pages have now been moved to docs.microsoft.com.
