### ISSUE TITLE
Support markdown quotes (>) in the Feedback form

### ISSUE THREAD

**Issue by ishepherd** [MicrosoftDocs/feedback#2570]
When logging a piece of feedback about a page, I want to quote the sentence(s) I'm confused about. I do this in the traditional way

```> quote```

which should produce

> quote

But instead the form encodes my input into ```&gt; quote```.

**Describe the solution you'd like**

Do not HTML-encode a ```>``` that is on its own at the start of a line.

**Describe alternatives you've considered**

I usually click through to the underlying Github issue and edit the ```&gt;``` back to a ```>``` for the quote to render correctly back on the page.

**Additional context**

First comment on https://github.com/MicrosoftDocs/azure-docs/issues/49818 and its edit history.

**Comment by rootsmusic** [comment]
@ishepherd When you refer to "the feedback form", are you referring to the [Github form](https://github.com/MicrosoftDocs/azure-docs/issues/new?title=&body=%0A%0A%5BEnter%20feedback%20here%5D%0A%0A%0A---%0A%23%23%23%23%20Document%20Details%0A%0A%E2%9A%A0%20*Do%20not%20edit%20this%20section.%20It%20is%20required%20for%20docs.microsoft.com%20%E2%9E%9F%20GitHub%20issue%20linking.*%0A%0A*%20ID%3A%20f7303812-25be-548c-4f02-1ccd98f122e0%0A*%20Version%20Independent%20ID%3A%2003d6952c-dda5-449f-b8a6-f342dbc876cf%0A*%20Content%3A%20%5BUse%20Application%20Change%20Analysis%20in%20Azure%20Monitor%20to%20find%20web-app%20issues%20-%20Azure%20Monitor%5D(https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fazure%2Fazure-monitor%2Fapp%2Fchange-analysis)%0A*%20Content%20Source%3A%20%5Barticles%2Fazure-monitor%2Fapp%2Fchange-analysis.md%5D(https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fazure-docs%2Fblob%2Fmaster%2Farticles%2Fazure-monitor%2Fapp%2Fchange-analysis.md)%0A*%20Service%3A%20**azure-monitor**%0A*%20Sub-service%3A%20**application-insights**%0A*%20GitHub%20Login%3A%20%40CawaMS%0A*%20Microsoft%20Alias%3A%20**cawa**) that opens when you click on the button at the bottom of the doc linked in this issue?

**Comment by ishepherd** [comment]
@rootsmusic No, I meant the feedback form that was on every page.
It's since been replaced with a link to github.com. That's one way to solve it :-D
