### ISSUE TITLE
Can't create account/username or reply to a thread when logged in

### ISSUE THREAD

**Issue by farmeunit** [MicrosoftDocs/feedback#2576]
**Describe the bug**
Using Firefox and Chrome

**To Reproduce**
1. Go to https://social.technet.microsoft.com/Forums/en-US/ad37cd15-315e-4f9b-ba34-bcbd987981fc/quotan-app-default-was-resetquot-error-newly-sysprep-windows-10-ltsc-2019-enterprise-image?forum=win10itprosetup
2. Click on Reply and it returns to top of the thread with no box for input.

If I don't login BEFORE going to a thread, I get prompted for a Display name, which I can enter, but "Continue" doesn't do anything.

**Expected behavior**
I get a reply box or when I enter a username and click Continue, that it does something.

 - OS: Windows 10 1809
 - Browser Chrome newest, Firefox newest ESR 68.6
 - Version Newest of respective branch

**Comment by TokenRing** [comment]
I think technet is having problems in general - my technet profile is suddenly just flat out gone with no warning as of today. I can sign in with my Microsoft account, but in the technet upper right corner, instead of showing me my username it says "create a profile"

I hope it's just a temporary thing.

**Comment by TokenRing** [comment]
Working for me as of today; my username is back up and the 502 gateway errors present yesterday on the technet forums seem to be resolved. Hope everything works for you now too, @farmeunit .

**Comment by rootsmusic** [comment]
@farmeunit TechNet forums have closed at https://docs.microsoft.com/en-us/teamblog/msdn-technet-english-forums-closure
