### ISSUE TITLE
Microsoft Dynamics 365 for userSettings.securityRolePrivileges

### ISSUE THREAD

**Issue by Saikes** [MicrosoftDocs/feedback#258]
# securityRolePrivileges are missing WebClient, but are existing in new Unified Interface

When calling Xrm.Utility.getGlobalContext().userSettings.securityRolePrivileges in "old" WebClient, the Privileges are not there. When calling them in the new Unified Interface, they are there.

## Issue Details

There is a mismatch of documentation and implementation in Dynamics 365 SDK. See: https://docs.microsoft.com/en-us/dynamics365/customer-engagement/developer/clientapi/reference/xrm-utility/getglobalcontext/usersettings The securityRolePrivileges are not existing in the WebClient. When switching to the Unified interface, the securityRolePriviliges are there. Looks like a bug or a documentation failure. My assumption would be, that WebClient and Unified Interface Javascript should behave the same way, as there is only one Javascript for both Interfaces.

**Comment by Powerhelmsman** [comment]
@KumarVivek Can you double check this?

**Comment by KumarVivek** [comment]
@Saikes Yes, I can repro the issue; have reached out to the feature team to get this investigated. We will update the docs as and if required. Thanks for reporting this.

**Comment by KumarVivek** [comment]
@Saikes I confirmed and this is a bug with the web client. The JavaScript method should return the same result irrespective of the client. You can report this bug at [https://experience.dynamics.com/ideas/](https://experience.dynamics.com/ideas/).
No doc update is required for this issue, and the issue can be closed.
cc: @Powerhelmsman @dend
