### ISSUE TITLE
script error line 49 char 221 failed to load external resource office

### ISSUE THREAD

**Issue by sniper554** [MicrosoftDocs/feedback#2581]
Hello everyone,

I tried to open my account on outlook 2016 and office 365, the following image appears to me and can't login through the web mail on my PC (outlook.office.com) or ( www.office.com) it's appear a blank page
![Untitled](https://user-images.githubusercontent.com/45386360/76703117-a9250980-66d7-11ea-8625-5136a4e8ae4b.jpg)

anyone have solve for that problem

**Comment by docs-product** [comment]
Thank you for the feedback! Because this is not related to docs.microsoft.com, we cannot address it in this forum. We recommend reaching out to the appropriate product support channel for faster resolution.
