### ISSUE TITLE
PDF-Download does not work

### ISSUE THREAD

**Issue by ATR-Master** [MicrosoftDocs/feedback#2583]
Hello
From the Site https://docs.microsoft.com/en-us/windows/uwp/launch-resume/launch-settings-app the Download Ling for the PDF-Document does not work: The related Link is
https://docs.microsoft.com/en-us/windows/uwp/opbuildpdf/toc.pdf?branch=live 
but i get the 404 Error.
The Download-Link for the german Document Version is functionable - what can I do, to get the EN-US Document either?

**Comment by JasonWHowell** [comment]
Looks like it was a transient problem, and the English PDF works again. Sorry for the trouble! Thanks, Jason #please-close
