### ISSUE TITLE
404 Error

### ISSUE THREAD

**Issue by megaritzmom** [MicrosoftDocs/feedback#2585]
**Describe the bug**
On https://docs.microsoft.com/en-us/previous-versions/dotnet/netframework-3.5/ms771314(v=vs.90)
I got a 404 error when I clicked on "Download Sample".

**To Reproduce**
1. Go to https://docs.microsoft.com/en-us/previous-versions/dotnet/netframework-3.5/ms771314(v=vs.90)
2. Click on Download Sample.
3. See error

**Expected behavior**
I expected to download the sample code.

**Screenshots**
![image](https://user-images.githubusercontent.com/4117593/76857283-24df9d00-6823-11ea-8be2-a411158b2c42.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 80.0.3987.132
**Smartphone (please complete the following information):**
N/A

**Additional context**

**Comment by mairaw** [comment]
As the page states, that content is no longer being maintained. Some of the WPF samples can be found at https://github.com/Microsoft/WPF-Samples,
