### ISSUE TITLE
Broken link causing HTTP 404 in "Internet Exporer for IT Pros" docs

### ISSUE THREAD

**Issue by Idris1337** [MicrosoftDocs/feedback#2587]
The hyperlink given in the attribute is incorrect as it is broken and causing HTTP 404 Not Found

This is the following parent link under which there is the content in which there's a broken link:
*https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-it-pro/*

The broken link can be found in the below mentioned content after opening the above link:
For information on Internet Explorer 11 and Microsoft Edge, check out *https://docs.microsoft.com/en-us/microsoft-edge/deploy/.*

The hyperlink given in the above mentioned is broken and it is redirecting it to a non-existing page ie., **[https://docs.microsoft.com/en-us/microsoft-edge/deploy/** and it is expected to have the link ie., **https://docs.microsoft.com/en-us/microsoft-edge/deploy/** without the *square bracket* at the beginning as it is causing the HTTP 404 Not Found.

After removing the square bracket the link working fine and returning HTTP 200 OK

**Comment by rootsmusic** [comment]
@Idris1337 "We're no longer updating this content regularly."
#please-close
