### ISSUE TITLE
Microsoft Visual Studio In general: Performance Needs an Improvement! 

### ISSUE THREAD

**Issue by ahmedAlmutairi05321** [MicrosoftDocs/feedback#2588]
**Is your feature request related to a problem? Please describe.**
I really like MS .NET Platform And Related Products, However; related Xamarin & Android Studio

I really see how important is performance and smoothness , MS Xamarin is working so slowly 
comparing with Android Studio.

**Describe the solution you'd like**
An Ability To emphasize ram memory allocation size for MS Xamarin & all related MS .NET components. 

**Describe alternatives you've considered**
integrate product with Operating System : Windows so that an Effective RAM Memory Allocation Process Could Be done by Default.
 
**Additional context**
i WISH YOU ALL SUCCESS AND HAPPINESS ^_^

**Comment by rootsmusic** [comment]
@ahmedAlmutairi05321 Product feedback is at https://developercommunity.visualstudio.com/home
#please-close
