### ISSUE TITLE
Documentation for IRandomAccessStream is inaccurate

### ISSUE THREAD

**Issue by phraemer** [MicrosoftDocs/feedback#259]
# Close is not available on this interface

https://docs.microsoft.com/en-us/uwp/api/windows.storage.streams.irandomaccessstream

It states that `Close` is a method on this interface but it is not.

## Issue Details

Tested in 
```
Microsoft Visual Studio Enterprise 2017 
Version 15.6.2
VisualStudio.15.Release/15.6.2+27428.2005
Microsoft .NET Framework
Version 4.7.02556
```

**Comment by dend** [comment]
@kevinyr @mijacobs can you help address this?

**Comment by ginami** [comment]
@laurenhughes, can you please respond to this? Thanks!

**Comment by laurenhughes** [comment]
Thanks for the catch! I'll get this updated in the docs. Updates will be available on Monday, 5/21.

**Comment by laurenhughes** [comment]
You can call Close if you're using C++/WinRT, but you don't really need to since the destructor will call it anyway.

**Comment by Powerhelmsman** [comment]
@phraemer Please double check if it answer your question?
