### ISSUE TITLE
Why are localized F# docs so broken?

### ISSUE THREAD

**Issue by MSDN-WhiteKnight** [MicrosoftDocs/feedback#2593]
**Link to article:**
https://docs.microsoft.com/ru-ru/dotnet/fsharp/

**Problem:**
I do realize it's a machine translation, but even the [frontpage](https://docs.microsoft.com/ru-ru/dotnet/fsharp/) has nonsense in headings, missing spaces etc:

![fsharp-docs](https://i.stack.imgur.com/TuUlt.png) 

In some cases the language name itself is garbled: https://docs.microsoft.com/ru-ru/dotnet/fsharp/get-started/install-fsharp

>You can install F# in multiple ways, depending on your environment.

translated as

>Вы можете установить F-образное, в зависимости от среды.

I remember it wasn't that bad before. Could you improve the quality of localization?

**Comment by mairaw** [comment]
@JasonCard can you please check this issue with F# docs localization?

**Comment by srvbpigh** [comment]
Hello, @MSDN-WhiteKnight
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by V-vafune** [comment]
Hello, @MSDN-WhiteKnight, 

Thank you for your feedback. The page in question has been machine-translated, which is not always perfectly understandable. We recently added a "Read in English" option on the right which allows you to switch to the English version without having to change the language settings. 

Kind regards, 

Microsoft DOCS International Team
