### ISSUE TITLE
Learning path listing for DP-100

### ISSUE THREAD

**Issue by pmbrull** [MicrosoftDocs/feedback#2596]
There is a mismatch in the information displayed in the Self-paced learning path for the DP-100 exam.

In the [Spanish version](https://docs.microsoft.com/es-es/learn/certifications/azure-data-scientist) we have different learning paths available to prepare for the certification.

When we go to the [English version](https://docs.microsoft.com/en-us/learn/certifications/azure-data-scientist), only one element appears.

**Comment by rootsmusic** [comment]
Fixed.
