### ISSUE TITLE
Wrong text for Example part

### ISSUE THREAD

**Issue by AnatolyHohuda** [MicrosoftDocs/feedback#2597]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem** (if available).

**Link to article:**
https://docs.microsoft.com/en-us/dotnet/api/system.windows.trigger.property?view=netframework-4.8

**Problem:**
In Example text written that there are 2 triggers in example code, but actually there is a code for only one trigger.

**Comment by mairaw** [comment]
I've opened a PR to fix this.
