### ISSUE TITLE
Access Denied after pressing F1 in Visual Studio

### ISSUE THREAD

**Issue by glibnub** [MicrosoftDocs/feedback#26]
When accessing documentation through Visual Studio 2017 (pressing F1), I get access denied but works in the browser

----------
⚠ Idea migrated from UserVoice

**Created By:** Parag
**Created On:** 2018/02/14 04:02:53 +0000
**Votes at Migration:** 1
**Supporters at Migration:** 1

**Comment by dend** [comment]
This needs more info about the context in which F1 was called.

**Comment by Sahriyaljhee** [comment]
about the context in Which F1

**Comment by Sahriyaljhee** [comment]
about the context in which f1 we called
