### ISSUE TITLE
Bad Numbering

### ISSUE THREAD

**Issue by calbertora** [MicrosoftDocs/feedback#2602]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem** (if available).

**Link to article:**
Tell us where exactly a problem occurs.
https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/inheritance

**Problem:**
What's wrong with the article?
In the section **Running the examples** the number of steps should be 1,2,4,**5** but It restarts after 4 step: 1,2,3,4,**1**

**Comment by mairaw** [comment]
This has been fixed. Closing.
