### ISSUE TITLE
GitHub links broken for translated domains

### ISSUE THREAD

**Issue by LinqLover** [MicrosoftDocs/feedback#2603]
## Describe the bug
On non-english domains such as [here](https://docs.microsoft.com/de-de/dotnet/core/), the `create-issue-on-github` `github-link` at the bottom of the page (originally named "You may also leave feedback directly on <a data-bi-name="create-issue-on-github" class="github-link">GitHub <span class="docon docon-navigate-external" aria-hidden="true"></span></a>.") is broken. A quick look into the HTML sources reveals that the `<a>` tag's `class` is missing on the translated pages. This appears to apply to all non-english domains.

## To Reproduce
1. Go [here](https://docs.microsoft.com/de-de/dotnet/core/#:~:text=Feedback%20geben)
2. In "Sie können Ihr Feedback auch direkt auf GitHub eingeben.", click "GitHub"

## Expected behavior
The browser should navigate to a page like [this](https://github.com/dotnet/docs/issues/new?title=&body=%0A%0A%5BEnter%20feedback%20here%5D%0A%0A%0A---%0A%23%23%23%23%20Document%20Details%0A%0A%E2%9A%A0%20*Do%20not%20edit%20this%20section.%20It%20is%20required%20for%20docs.microsoft.com%20%E2%9E%9F%20GitHub%20issue%20linking.*%0A%0A*%20ID%3A%20d49bc05d-7c8e-5f89-aac5-d133225da4d5%0A*%20Version%20Independent%20ID%3A%202f831fc9-dfe6-15db-4ec6-00f59c2dacc2%0A*%20Content%3A%20%5B.NET%20Core%20guide%5D(https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fdotnet%2Fcore%2F)%0A*%20Content%20Source%3A%20%5Bdocs%2Fcore%2Findex.md%5D(https%3A%2F%2Fgithub.com%2Fdotnet%2Fdocs%2Fblob%2Fmaster%2Fdocs%2Fcore%2Findex.md)%0A*%20Product%3A%20**dotnet-core**%0A*%20GitHub%20Login%3A%20%40richlander%0A*%20Microsoft%20Alias%3A%20**dotnetcontent**).

## Actual behavior
Nothing happens.

## Desktop (please complete the following information)
 - OS: Win 1903
 - Browser Chrome
 - Version 80

**Comment by gewarren** [comment]
It's working for me. I wonder if it was a transient error. Can you try again?

**Comment by LinqLover** [comment]
Alright, today it works for me, too. Glad to see that this was fixed soon!
