### ISSUE TITLE
Three-Character Extension Note Is Incorrect For Directory.EnumerateFiles Method

### ISSUE THREAD

**Issue by RedQuark** [MicrosoftDocs/feedback#2604]
**Link to article:**
https://docs.microsoft.com/en-us/dotnet/api/system.io.directory.enumeratefiles?view=netcore-3.1

**Problem:**
The article states that with a search for files ending in three-character extensions using an asterisk wildcard (e.g. **"*.xls"**) "the method returns files with extensions that _**begin**_ with the specified extension." The example says that the above search term will return both "books.xls" and "books.xlsx".

Although the command `dir ".xls"` does indeed list both files in Windows 10's command prompt, the method `Directory.EnumerateFiles(".", "*.xls") `only returns "books.xls" -- at least when running .NET Core 3.1.2 on WIndows 10 version 1909.

**Comment by gewarren** [comment]
@carlossanlop Can you take a look at this feedback?

**Comment by carlossanlop** [comment]
Thanks for bringing it to my attention, @gewarren.

The documentation is incorrect for this code example.

`EnumerateFiles` will only return files that have the `xls` extension if the `searchPattern` argument is set to `*.xls`.

To enumerate files that end both with `xls` and with `xlsx`, the `searchPattern` argument should be `*.xls*`:

```cs
Directory.EnumerateFiles(".", "*.xls*"))
```

**Comment by gewarren** [comment]
This issue was moved to dotnet/dotnet-api-docs#4052
