### ISSUE TITLE
Windows Update of Windows 10 IoT Core is always failed.

### ISSUE THREAD

**Issue by ahidaka** [MicrosoftDocs/feedback#2609]
I've tried Windows Update many times in the last few days, but it fails and won't boot.
This failure happens at both 17763.107 and 10.0.17763.914.
Note that, in this January, 17763.107 was installed by IoT Dashboard, and it became 10.0.17763.914 by Update well.

**To Reproduce**
1. Go to Windows IoT Dashboard and open in Device Portal.
2. Click on Windows Update and Check Update at web browser.
3. Click Restart Windows at Windows Update menu on Device Portal page at browser. 
4. The device won't start again.

**Expected behavior**
The device will restart with new updated version of Windows.

**Screenshots**
Only dark screen to see. No Screenshots.

**Desktop (please complete the following information):**
 - OS: 10.0.17763.107 and 10.0.17763.914
 - Browser firefox, Microsoft edge
 - Version firefox 74.0 Microsoft Legacy Edge

**Smartphone (please complete the following information):**

**Additional context**

**Comment by rootsmusic** [comment]
@ahidaka Please ask product support or in support forums.
#please-close
