### ISSUE TITLE
Important images are missing from "A Minimal MVVM UWP App"

### ISSUE THREAD

**Issue by LordyHun** [MicrosoftDocs/feedback#2610]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem** (if available).

**Link to article:**
https://docs.microsoft.com/hu-hu/archive/blogs/johnshews_blog/a-minimal-mvvm-uwp-app

**Problem:**
Starting from "Step 4: Build the ViewModels", images are missing from the article; sadly, these are the images which would describe what'd be the whole point of the article.

**Comment by rootsmusic** [comment]
@LordyHun "We're no longer updating this content regularly."
#please-close
