### ISSUE TITLE
Clarity on Open Publishing System (OPS)

### ISSUE THREAD

**Issue by joewood** [MicrosoftDocs/feedback#2613]
**Is your feature request related to a problem? Please describe.**
Some of the documentation mentions **OPS**, but I can't find a reference or more formal definition of this. Was this concept dropped?

**Describe the solution you'd like**
A page outlining what OPS is. Specifically, if any of the docs site and workflows could be used for other documentation sites (e.g. internal company docs etc..)

**Comment by NNITarchitectureQHS** [comment]
Please provide an answer to the original question ...

**Comment by joewood** [comment]
Any update on this?

**Comment by markjulmar** [comment]
OPS is an internal web portal that manages the configuration that maps GitHub repos with Markdown files that end up publishing to <https://learn.microsoft.com>. It allows the owning content team to configure localization, site templates, and the root URL path. Let us know if you spot more references as it's more of an internal detail that is unnecessary for public contribution.
