### ISSUE TITLE
Microsoft.Sql servers/administrators template reference, value wrong case, "activeDirectory" instead of "ActiveDirectory"

### ISSUE THREAD

**Issue by meinradweiss** [MicrosoftDocs/feedback#2615]
**Describe the bug**

**To Reproduce**
1. Go to 'https://docs.microsoft.com/en-us/azure/templates/microsoft.sql/2019-06-01-preview/servers/administrators'
2. Scroll down to 'Code Sample'
3. See error

The sample looks like:

{
  "name": "string",
  "type": "Microsoft.Sql/servers/administrators",
  "apiVersion": "2019-06-01-preview",
  "properties": {
    "administratorType": "activeDirectory",
    "login": "string",
    "sid": "string",
    "tenantId": "string",
    "azureADOnlyAuthentication": "boolean"
  }
}

**Expected behavior**
Correct would be: "administratorType": "ActiveDirectory",

->
{
  "name": "string",
  "type": "Microsoft.Sql/servers/administrators",
  "apiVersion": "2019-06-01-preview",
  "properties": {
    "administratorType": "ActiveDirectory",
    "login": "string",
    "sid": "string",
    "tenantId": "string",
    "azureADOnlyAuthentication": "boolean"
  }
}

**Comment by tfitzmac** [comment]
@meinradweiss - thanks for this feedback. I am looking into this issue.

**Comment by tfitzmac** [comment]
@meinradweiss - I have updated the docs with the correct casing. Thanks again for making me aware of the issue.

**Comment by tfitzmac** [comment]
#please-close

**Comment by meinradweiss** [comment]
@tfitzmac - Thank you.
