### ISSUE TITLE
Please tell me about 429 HTTP error detection

### ISSUE THREAD

**Issue by piyo0320** [MicrosoftDocs/feedback#2618]
I want to retry using the information in the retry-after when an"429 - Too many requests" error occurs in Tasks - List(Security Center).

https://docs.microsoft.com/en-us/rest/api/securitycenter/tasks/list
 
said that when an exception occurs, CloudError is thrown. How is the above retry realized?

※ Since I am not good at English, I am sorry for writing poorly.

**Comment by rootsmusic** [comment]
@piyo0320 Please submit a support ticket at https://azure.microsoft.com/en-us/support/options/
#please-close
