### ISSUE TITLE
microsoft docs "Themes" feature unavailable

### ISSUE THREAD

**Issue by ahamdev** [MicrosoftDocs/feedback#2619]
I noticed the "Theme"  feature missing from .net products documentation I mostly refer. I am a big fan of Theme-Dark mode which was comfortable and less stressful on my eyes. Please bring back this feature.

**Comment by gewarren** [comment]
The Themes chooser is still available, it just moved to the very bottom of the page next to the language chooser.

/cc @dend

**Comment by ahamdev** [comment]
thanks!
