### ISSUE TITLE
Windows previous versions documentation needs to be Bing-able and Google-able

### ISSUE THREAD

**Issue by SusanBradley** [MicrosoftDocs/feedback#262]
It is my understanding that now that all older documentation for Windows 7, 8.1, Server 2008 R2, Server 2012 R2 located here: https://docs.microsoft.com/en-us/previous-versions/windows/  is not searchable using normal standard web tools such as bing or google.  
Given that Windows 7 is still is in it's supported/extended lifecycle, given that documentation is part of support may I respectfully request that normal standard search tools are allowed to search this documentation.

**Comment by SusanBradley** [comment]
And this link is broken:  https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-essentials

**Comment by Powerhelmsman** [comment]
@presleyy Can you take a look at this?

**Comment by dend** [comment]
@Khairunj probably would be the correct driver for this experience.

**Comment by charlespugh** [comment]
Stay on 'em Susan!

**Comment by lizap** [comment]
@SusanBradley - Hi, Susan - thanks for letting us know about the broken Essentials link. It's fixed now. Thanss - Liza

**Comment by gwieder65** [comment]
I just finished implementation of a new Dell server that came preinstalled with Windows Server 2016 Essentials.  It was NOT easy!  The setup and config steps are not clear, and absolutely NONE of the help links work!  They all fail as described here:  https://social.technet.microsoft.com/Forums/en-US/2e1187f8-45e8-4e4d-b64f-8d0548b8f8ca/windows-server-2016-essentials-dashboard-help-links-useless?forum=winserverManagement

After many years of well developed SBS products, this one was very disappointing.  I've finally got everything working, except for Remote Desktop accessed via the Remote Web Access page.

I really wish Microsoft's product engineers would pay a little more attention to detail with this product.

**Comment by Khairunj** [comment]
@gwieder65 I found this page [https://docs.microsoft.com/en-us/windows-server-essentials/manage/manage-remote-web-access-in-windows-server-essentials] that might be helpful.

**Comment by Khairunj** [comment]
the correct link is provided to the customer

**Comment by SusanBradley** [comment]
No one answered my question about the searchability.  Did that get fixed or not?
