### ISSUE TITLE
Broken link on https://docs.microsoft.com/en-us/stream/faq

### ISSUE THREAD

**Issue by nopdotcom** [MicrosoftDocs/feedback#2620]
The page https://docs.microsoft.com/en-us/stream/faq has a hyperlink, "[Office 365 Compliance Framework paper]()" which points to https://go.microsoft.com/fwlink/p/?LinkId=615657, which is a 404.

**To Reproduce**

Navigate to https://docs.microsoft.com/en-us/stream/faq , search for "Office 365 Compliance Framework paper". Click.

**Expected behavior**

I see a document.

**Comment by taralpatel610** [comment]
@nopdotcom The link seems to be working at this point

![image](https://user-images.githubusercontent.com/9837977/79679803-016b9180-81d7-11ea-8e5e-24b941848b7a.png)

**Comment by nopdotcom** [comment]
Works now. Thanks.
