### ISSUE TITLE
Clearer documentation of Microsoft.Web/serverfarms 'reserved' property

### ISSUE THREAD

**Issue by gnovack** [MicrosoftDocs/feedback#2626]
The `reserved` property of [AppServicePlanProperties](https://docs.microsoft.com/en-us/azure/templates/microsoft.web/2019-08-01/serverfarms#appserviceplanproperties-object) has only the following description: "If Linux app service plan `true`, `false` otherwise."

Can the docs be updated to include a better description of this property (i.e. what is means, and why it is required even when `kind` is set to `linux`), and to be clearer that this is a required property when deploying Linux App Service Plans?

Context: 
- I ran into this when attempting to deploy a linux app service plan to a resource group with other existing linux app service plans. My deployment was failing with the below error until I added `"reserved": true` to my resources properties.

```
{
            "code": "WindowsWorkersNotAllowedInLinuxResourceGroup",
            "details": null,
            "message": "The requested app service plan cannot be created in the current resource group because it is hosting Linux apps. Please choose a different resource group or create a new one.",
            "target": null
}
```

**Comment by rootsmusic** [comment]
@gnovack Please move this issue to https://github.com/MicrosoftDocs/azure-docs/issues
