### ISSUE TITLE
Problem in translating certain pages into Japanese

### ISSUE THREAD

**Issue by takatkyu** [MicrosoftDocs/feedback#2628]
#**Problems in translating certain pages into Japanese**
The command certmgr.msc in " https://docs.microsoft.com/ja-jp/skypeforbusiness/set-up-skype-for-business-online/troubleshooting-sign-in-errors-for-admins#update-security-credentials " is misspelled as ertmgr.msc in the Japanese version.　Please correct this.

**Comment by TinaMcN** [comment]
@takatkyu, thank you for reporting the issue.
@OfficeGlobal this is a bug in a human translated article.  please let us know when it's fixed.

**Comment by TinaMcN** [comment]
@OfficeGlobal , can you please provide an update on this.

**Comment by OfficeGlobal** [comment]
@takatkyu , @TinaMcN  I'm sorry for a delay. String is updated at live page

**Comment by takatkyu** [comment]
Thank you so much. I have confirmed that it has been corrected.
