### ISSUE TITLE
Add a web service to download content offline

### ISSUE THREAD

**Issue by tsahi** [MicrosoftDocs/feedback#263]
# Add a web service to download content offline
MSDN has a [web service](http://services.msdn.microsoft.com/ContentServices/ContentService.asmx) which allows downloading content offline, which can then be integrated into the Visual Studio Help Viewer through tools like Package This. This is very helpful if I want instant help on API which is not pre-installed with Visual Studio, such as ASP.NET MVC or Entity Framework, or any of the Azure documentation, or any API published after MSDocs was launched.

It would be great if such a web service will be available for docs.microsoft.com, so future documentation can also be integrated into Help Viewer the same way.

## Issue Details

What is needed is a web service which will allow
1. browsing the content tree.
2. downloading content in a format which can be viewed in Help Viewer.

I know SOAP is out of fashion, and REST is all the rage now, but it may be easier to update existing applications that use the existing SOAP service from MSDN, if you just change the endpoint and maybe something else, and not change the application protocol completely.

Oh, and PDF is not it. I can't press F1 in Visual Studio into a PDF.

**Comment by dend** [comment]
@dastaffo can you please follow-up on this item?

**Comment by dastaffo** [comment]
Adding @cillroy here.

**Comment by keziamicro** [comment]
Hello - reviewing and cleaning up some older feedback/issues. Thanks!
