### ISSUE TITLE
Azure Stack API for Compute Quota should return value for managed disks

### ISSUE THREAD

**Issue by CorneliusWeinschrod** [MicrosoftDocs/feedback#2631]
**Is your feature request related to a problem? Please describe.**
I would like to query the API to get a current list of quotas for all subscriptions.

I can get almost all values, that i can find within the Azure Stack Portal, except for the quotas for Capacity(GB) of (standard/premium) managed disk

This should be added to:
https://docs.microsoft.com/en-us/rest/api/azurestack/quotas%20(compute)/list

Also there is no documentation for the API for Microsoft.Storage.Admin, which exists and works.

**Describe the solution you'd like**
I would like the api to return more values.

Current return: 

virtualMachineCount 
coresLimit 
availabilitySetCount 
vmScaleSetCount

Desired additonal return:

CapacityStandardManagedDisk
CapacityPremiumManagedDisk

**Comment by rootsmusic** [comment]
@CorneliusWeinschrod Your link is not found.

**Comment by CorneliusWeinschrod** [comment]
@rootsmusic yeah, microsoft likes to change it's documentation links

For the issue - by now the values are long being returned by the api, so technically, this feature request is obsolete

**Comment by rootsmusic** [comment]
#please-close
