### ISSUE TITLE
Old InternetExplorer.Application code no longer working, missing howto

### ISSUE THREAD

**Issue by tygrus2** [MicrosoftDocs/feedback#2636]
https://docs.microsoft.com/en-us/previous-versions/windows/desktop/ms763742(v=vs.85)
Coming from VBA in MS Access 2016 or newer and have trouble replacing code that once worked
Set objIE = CreateObject("InternetExplorer.Application")
..
strHTML = objIE.Document.All("content").innerHTML
..

Now they're talking about
Dim xmlhttp As New MSXML2.xmlhttp
xmlhttp.Open "GET", strURL, False
xmlhttp.send

I try to find help docs and code examples and find a long list of libraries, lib versions, coding methods and no VBA code or no VBA code that works. Every few years you change methods and just create a pile of deprecated junk from brain farts along the way. Please slow down the "new way" and try to do it right the first time and then spend the time properly documenting it (accessible from VBA editor).

**Comment by rootsmusic** [comment]
@tygrus2 "We're no longer updating this content regularly."
#please-close
