### ISSUE TITLE
Broken iso

### ISSUE THREAD

**Issue by emolenev** [MicrosoftDocs/feedback#264]
# Broken iso file

There is broken iso-file SSDT https://go.microsoft.com/fwlink/?linkid=863443&clcid=0x419
Send me iso file please.

**Comment by Powerhelmsman** [comment]
@emolenev can you tell us which page in the docs site includes the broken link?

**Comment by emolenev** [comment]
This https://docs.microsoft.com/ru-ru/sql/ssdt/download-sql-server-data-tools-ssdt#ssdt-for-visual-studio-2015

**Comment by emolenev** [comment]
The link is ok, but file is broken.

**Comment by dend** [comment]
@emolenev can you comment on what is wrong with the file, and whether you can still reproduce the issue?

**Comment by Powerhelmsman** [comment]
@emolenev It works now. Close as resolved.
