### ISSUE TITLE
Power Automate Documentation

### ISSUE THREAD

**Issue by ken-afh** [MicrosoftDocs/feedback#2642]
I'm sure the documentation is out there **_somewhere_**. I'll just be damned if I can find it. I have searched using every search box on every page I can find. All I want is the documentation for the HTTP action. How hard can that be?? I search for "HTTP Action" and I get a long list of responses - none of which gives me a simple description of how the parameters are used.

"Headers" - I _think_ I know what that means - but it would be awfully nice if I could find the documentation to verify my knowledge
"Queries" - This ain's SQL. What are "queries?" Are they Query Strings? If so, why don't you call them that?

This is information that REALLY SHOULD BE included in a simple tooltip that I can access from the dialog, but NO! The only contextual help I get is "Choose a REST API to invoke." - that's NOT helpful.

**THIS SHOULDN'T BE SO HARD.**

**Comment by rootsmusic** [comment]
@ken-afh On https://flow.microsoft.com/en-us/ , click on "Learn" at the top to find "Documentation".
#please-close
