### ISSUE TITLE
Title should be "Office 365 API へようこそ".

### ISSUE THREAD

**Issue by ukiuni** [MicrosoftDocs/feedback#2645]
**Describe the bug**
https://docs.microsoft.com/ja-jp/previous-versions/office/office-365-api/ `s title is
"Office 365 APi へようこそ"

"Office 365 API へようこそ"
is better.

**To Reproduce**
1. Go to 'https://docs.microsoft.com/ja-jp/previous-versions/office/office-365-api/'

**Expected behavior**
"Office 365 API へようこそ" shows page title and google search or bing result. 

**Screenshots**
![image](https://user-images.githubusercontent.com/4121348/78514046-54fada00-77ea-11ea-9759-dcc5d96fa350.png)

**Desktop (please complete the following information):**
 - OS: MacOSX, Windows, 
 - Browser chrome, safari, firefox, opera, vivaldi
 - Version unn...

**Smartphone (please complete the following information):**
 - Device: iOS, Android,
 - OS: umm....
 - Browser stock browser, chrome, firefox, safari
 - Version mmm....

**Additional context**
-

**Comment by rootsmusic** [comment]
@ukiuni I see the entire word "API" is capitalized.
#please-close
