### ISSUE TITLE
Wrong and misleading doc for registering Single File Generator on VS 2019

### ISSUE THREAD

**Issue by roit1981** [MicrosoftDocs/feedback#2647]
Hello, this page - https://docs.microsoft.com/en-us/visualstudio/extensibility/internals/registering-single-file-generators?view=vs-2019 reflects the way things worked for VS 2015, its wrong and misleading for VS 2019

**Comment by gewarren** [comment]
This issue was moved to MicrosoftDocs/visualstudio-docs#5224
