### ISSUE TITLE
Unable to search from Firefox on Android

### ISSUE THREAD

**Issue by kevinoid** [MicrosoftDocs/feedback#2650]
**Describe the bug**
Tapping the magnifying glass in the sidebar menu briefly shows the search box with keyboard focus before closing the menu, preventing text entry.

**To Reproduce**
1. Go to https://docs.microsoft.com or a sub-page.
2. Tap on the hamburger button.
3. Tap on the magnifying glass button.
4. Watch the text box and keyboard appear, then immediately disappear along with the menu.

**Expected behavior**
The menu would remain open so that I would be able to enter search terms in the search box.

**Screenshots**
<img src="https://user-images.githubusercontent.com/336433/78596809-ee9ea780-783b-11ea-92c0-6da287af7954.gif" alt="Screen recording of search issue on Firefox Preview" height="400" width="225">

**Smartphone (please complete the following information):**
 - Device: Pixel (Sailfish)
 - OS: Android 10
 - Browsers affected:
[Firefox Preview](https://play.google.com/store/apps/details?id=org.mozilla.fenix) 4.2.0 (Build #20852112)
[Firefox](https://play.google.com/store/apps/details?id=org.mozilla.firefox) 68.7.0

Thanks for considering,
Kevin

**Comment by rootsmusic** [comment]
@kevinoid Is this still an issue in the latest version?

**Comment by kevinoid** [comment]
I'm not able to reproduce the issue with Firefox 90.1.2 nor Firefox Nightly 92.0a1 (Build @2015824779).  Seems fixed to me.  Thanks!
