### ISSUE TITLE
Why notworking with Wacom Intuos Pro

### ISSUE THREAD

**Issue by rebehayan** [MicrosoftDocs/feedback#2652]
**Describe the bug**

cant draw~~~and  everything function~~is notworking~
with Wacom Intuos Pro

other screen pen tool is ok~
photoshop, epic pen~~ etc~

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by rootsmusic** [comment]
@rebehayan Please ask product support or in support forums.
#please-close
