### ISSUE TITLE
Microsoft Learn: Fix TYPO BUG   

### ISSUE THREAD

**Issue by bijoy26** [MicrosoftDocs/feedback#2653]
**Describe the bug**
I noticed an issue while completing my first learning path **Intro To Version Control With Git** on *Microsoft Learn*. 

While executing the given commands on *Azure Cloud Shell* as stated, a specific git command was producing unexpected result.

**To Reproduce**

Platform : Microsoft Learn
Learning Path : Introduction To Version Control With Git
Module ID : 3 
Module Title : Edit code through branching and merging in Git
Unit ID: 5
Unit Title : Exercise - Resolve merge conflicts

1. Go to [This URL](https://docs.microsoft.com/en-us/learn/modules/branch-merge-git/4-exercise-resolve-merge-conflicts) for exact page of the issue
2. Scroll down to **Make a change as Alice** section
3. Go to step 5 with the text "Now commit the changes..." where the first command is "*git add assets*" 
4. If all the previous units (unit 3,4) were followed properly, then pasting the above mentioned git command will produce an error "*fatal : pathspec 'assets' did not match any files*"

**Expected behavior**
The error wasn't supposed to happen because the command should add the specifed directory changes to the staging area. 
The correct command should be "*git add Assets/* as the assets folder title is "Assets".

 **Generating Error**
![generating error](https://user-images.githubusercontent.com/42487891/78666344-0ab44e80-78f9-11ea-8b06-78b1d9147337.png)

**Bug Location**
![bug location](https://user-images.githubusercontent.com/42487891/78666349-0c7e1200-78f9-11ea-9466-a460e46bdfa7.png) 

**Desktop:**
 - OS: [Win-10 64 bit]
 - Browser [Mozilla Firefox]
 - Version [74.0.1]

**Additional context**
I guess fixing up the typo will save a lot of confusion for the first timers while they're learning on this professional platform.

**Comment by mairaw** [comment]
@shanama please take a look at this issue

**Comment by bijoy26** [comment]
Closing this issue since it has been resolved after reporting.
