### ISSUE TITLE
404 Page not found

### ISSUE THREAD

**Issue by mirandtech** [MicrosoftDocs/feedback#2655]
**Describe the bug**
https://docs.microsoft.com/en-us/microsoftteams/platform/redirects/?redirectedfrom=MSDN

page not found.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by gewarren** [comment]
This issue was moved to MicrosoftDocs/msteams-docs#1616
