### ISSUE TITLE
Incorrect Link for 

### ISSUE THREAD

**Issue by Singleton06** [MicrosoftDocs/feedback#2657]
**Describe the bug**
[This page](https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/compatibility/jj676915%28v%3dvs.85%29#understanding-legacy-document-modes) has a link with the text of "IEBlog: HTML5 Quirks mode in IE10" which takes you to the wrong URL.  Currently it just takes you to the "blogs" page instead of taking you to the direct blog page (which I think is [this one](https://docs.microsoft.com/en-us/archive/blogs/ie/interoperable-html5-quirks-mode-in-ie10).

Sorry I didn't fill out the other stuff, I felt it was pretty self explanatory, but if it matters I'm on windows 10 using chrome.

HTML of the link I see:
```html
<a href="http://go.microsoft.com/fwlink/p/?linkid=242172" data-linktype="external">IEBlog: HTML5 Quirks mode in IE10</a>
```

Also wanted to say thank you on how in-depth this documentation is.  Really appreciate all the hard work!

**Comment by rootsmusic** [comment]
@Singleton06 "We're no longer updating this content regularly."
#please-close
