### ISSUE TITLE
ajax.aspnetcdn.com - Knockout JS - blocked due to mime type mismatch

### ISSUE THREAD

**Issue by edwardm** [MicrosoftDocs/feedback#266]
Client in the EAST coast is loading our web service utilizing:
https://ajax.aspnetcdn.com/ajax/knockout/knockout-3.4.2.js

But, all browsers and computers return the same error in the console:
`SEC7112: Script from https://ajax.aspnetcdn.com/ajax/knockout/knockout-3.4.2.js was blocked due to mime type mismatch`

Other clients in the WEST coast, including us, seem unaffected loading the same page.

**Comment by Powerhelmsman** [comment]
@edwardm This channel is for user to provide feedback on docs site and content. Which specific content do you refer to?

**Comment by edwardm** [comment]
@Powerhelmsman Oops, sorry forgot to include the page i was referring to:
https://docs.microsoft.com/en-us/aspnet/ajax/cdn/overview#Knockout_Releases_on_the_CDN_11

**Comment by dend** [comment]
@Rick-Anderson @danroth27 can you help with this ask?

**Comment by ChrisSfanos** [comment]
This should be fixed - Barry provided an update and I pushed it live around 2pm

**Comment by edwardm** [comment]
@ChrisSfanos Thanks! I will try to get the client to test when we get the chance, and I'll let you know

**Comment by Rick-Anderson** [comment]
@Powerhelmsman  can you close this?
