### ISSUE TITLE
typo in https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/modern-authentication/topologies-supported

### ISSUE THREAD

**Issue by bament-hun** [MicrosoftDocs/feedback#2666]
**Describe the bug**
on this page we have a typo which can cause issues:
https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/modern-authentication/topologies-supported

Very last important box:
 Important

Also note that in some cases (Mixed 1, 3, and 5 specifically) an AllowADALForNonLynIndependentOfLync registry key must be set for proper configuration for Windows Desktop Clients.

The proper registry key is AllowADALForNonLyn**c**IndependentOfLync 
the c is missing from the first Lync word.

**To Reproduce**
1. Go to https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/modern-authentication/topologies-supported
2. Scroll down to last important box
4. See typo error in the required registry key

**Expected behavior**
If customer configures this faulty registry key, it won't do the required action.

**Screenshots**
![image](https://user-images.githubusercontent.com/41291287/79208000-c4ec0e80-7e41-11ea-8a07-71a3542422ec.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser EDGE chromium
 - Version 83

appears on every browser

**Comment by mairaw** [comment]
It seems this was fixed. Closing.
