### ISSUE TITLE
Typo "InformationBarrierPolicy"→"New-InformationBarrierPolicy"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/feedback#2669]
🛑 IMPORTANT: You can get your feedback addressed faster if you use the comment section for the article in which you encountered a problem (if available).
![new-informationbarrierpolicy_j](https://user-images.githubusercontent.com/40815708/79321890-fb5f8180-7f46-11ea-8690-1591d6604892.png)

Link to article:
Tell us where exactly a problem occurs.
"https://docs.microsoft.com/ja-jp/powershell/module/exchange/policy-and-compliance/new-informationbarrierpolicy?view=exchange-ps"

Problem:
What's wrong with the article?
Typo "InformationBarrierPolicy"→"New-InformationBarrierPolicy"

**Comment by rootsmusic** [comment]
@hyoshioka0128 Please submit feedback by clicking on the button at the doc's bottom.

**Comment by hyoshioka0128** [comment]
@rootsmusic - Thanks!
Opend https://github.com/MicrosoftDocs/office-docs-powershell/issues/8126 .
Closed #2669 .
