### ISSUE TITLE
technet gallery

### ISSUE THREAD

**Issue by jayp00001** [MicrosoftDocs/feedback#2670]
the gallery should have an option to download the gallery for future reference

**Comment by gewarren** [comment]
@aprilspeight Where should this feedback be directed?

**Comment by jayp00001** [comment]
I think the gallery team?  the issue is that this knowledge is going away completly so there should be some way to either get it all before it goes or some sort of searchable archive

**Comment by aprilspeight** [comment]
Hi @gewarren please direct this feedback to @rloutlaw

**Comment by rootsmusic** [comment]
TechNet Gallery has closed at https://docs.microsoft.com/en-us/teamblog/technet-gallery-retirement

**Comment by gewarren** [comment]
Thanks @rootsmusic. I'll close this issue now since the gallery has already been retired.
