### ISSUE TITLE
Pressing Send Feedback "On this product" ends up at closed uservoice

### ISSUE THREAD

**Issue by birbilis** [MicrosoftDocs/feedback#2673]
**Describe the bug**
the send feedback > On this product doesn't work (sends you to a close UserVoice site)

**To Reproduce**
near the end of the page 
https://docs.microsoft.com/en-us/microsoft-edge/extensions/api-support/supported-manifest-keys
one can select to send feedback and then pick On this product

this takes them to a page that says that UserVoice page is now closed

**Comment by gewarren** [comment]
This issue was moved to MicrosoftDocs/edge-developer#646
