### ISSUE TITLE
Support eml/msg in "Use transport rules to inspect message attachments"

### ISSUE THREAD

**Issue by mrgoos** [MicrosoftDocs/feedback#2674]
**Is your feature request related to a problem? Please describe.**

In transport rules, attachments of types eml/msg aren't supported. It's really frustrating since a raw email is just text and rules can be applied to these kind of types as well and badly needed.

**Describe the solution you'd like**

I would simply like that mail flow rules in attachments will apply to eml/msg types and currently, [they aren't](https://docs.microsoft.com/en-us/exchange/use-transport-rules-to-inspect-message-attachments-exchange-2013-help?redirectedfrom=MSDN).

**Describe alternatives you've considered**

**Additional context**
Doc about supported types is [here](https://docs.microsoft.com/en-us/exchange/use-transport-rules-to-inspect-message-attachments-exchange-2013-help?redirectedfrom=MSDN).
I submitted an issue [here](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/issues/1378) as well.

**Comment by docs-product** [comment]
Thank you for the feedback! Because this is not related to docs.microsoft.com, we cannot address it in this forum. We recommend reaching out to the appropriate product support channel for faster resolution.

**Comment by mrgoos** [comment]
That's a shame that no one in Microsoft can answer my simple feature request or guide me how to make progress with it.
