### ISSUE TITLE
not  meaningful topics

### ISSUE THREAD

**Issue by bergano65** [MicrosoftDocs/feedback#2675]
**Describe the bug**

**To Reproduce**
1. Go to 'https://docs.microsoft.com/en-us/visualstudio/?view=vs-2019'

3. Scroll down to '.vs subscription'
"Portal"," Administration" is not informative

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by gewarren** [comment]
This issue was moved to MicrosoftDocs/visualstudio-docs#5223
