### ISSUE TITLE
main site issues 

### ISSUE THREAD

**Issue by bergano65** [MicrosoftDocs/feedback#2678]
**Describe the bug**

**To Reproduce**
1. Go to 'https://www.microsoft.com/ru-ru'
2. Open 'All products' menu
3 One item isn't  capitalized
![image](https://user-images.githubusercontent.com/17863980/79595220-1cf76f00-80e7-11ea-8b94-e04716d9f436.png)
'
4.  if site doesn't belong to content here where can discuss
https://www.microsoft.com/ru-ru?

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by docs-product** [comment]
Thank you for the feedback! Because this is not related to docs.microsoft.com, we cannot address it in this forum. We recommend reaching out to the appropriate product support channel for faster resolution.
