### ISSUE TITLE
vs docs issue

### ISSUE THREAD

**Issue by bergano65** [MicrosoftDocs/feedback#2680]
**Describe the bug**

**To Reproduce**
1. Go to 'https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes'

3. Scroll down to '.Fixed In This Release of Visual Studio 2019 version 16.5'

Fixed an issue where Goto next/previous entry failed to work in the find results list when "preview selected files in find results" is turned off.
is duplicated and should be emphasized as.
Fixed an issue where "Goto next/previous entry" failed to work in the find results list when "Preview selected files in find results" is turned off.

5.
Fixed an issue where the find list view did not navigate to results when enter was hit.
 should be
Fixed an issue where the find list view did not navigate to results when "Enter" was hit.

**Comment by gewarren** [comment]
This issue was moved to MicrosoftDocs/visualstudio-docs#5222
