### ISSUE TITLE
Hash character in .NET Core CLI syntax highlighting is incorrectly considered a comment

### ISSUE THREAD

**Issue by ChrisMaddock** [MicrosoftDocs/feedback#2681]
**Describe the bug**
The `.NET Core CLI` syntax highlighting incorrectly considers the `#` character to be the start of a comment. This character is a valid character as part of a command, for example when specifiying `-lang c#`

**To Reproduce**
See the "Synopsis" section of the dotnet new docs.
https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-new#synopsis

**Expected behavior**
The hash character should be treated as a normal character and not change the highlighting to the green 'comment' colour.

**Screenshots**
![image](https://user-images.githubusercontent.com/4837132/79639937-9c884b00-8186-11ea-98cb-2fc2678fdb7d.png)

**Comment by Youssef1313** [comment]
It's okay to consider it as a comment in syntax highlighting. Some shells do that.
The fix is to enclose the language between double quotes. That was already fixed in #18454.

**Comment by mairaw** [comment]
Tagging @tdykstra to see if this can be closed

**Comment by tdykstra** [comment]
Yes, this issue has been addressed and can be closed.

**Comment by ChrisMaddock** [comment]
Great - thanks!
