### ISSUE TITLE
QnA site issue unexpected hyperlinks

### ISSUE THREAD

**Issue by DSPatrick** [MicrosoftDocs/feedback#2682]
**Describe the bug**
If I put in the body of post sometext.net or sometext.com it automatically gets hyperlinked

**To Reproduce**
Type in anytext.net or anytext.com and it will automatically gets hyperlinked

**Expected behavior**
should not be linked unless user uses Hyperlink tool from toolbar

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10 x64
 - Browser [e.g. chrome, safari] Edge
 - Version [e.g. 22] Microsoft Edge 44.18362.449.0

**Smartphone (please complete the following information):**

**Additional context**

**Comment by saldana** [comment]
This is pretty standard. We will not fix this. Thanks for the feedback!

**Comment by DSPatrick** [comment]
So you expect "vb.net" to always be hyperlinked?

**Comment by saldana** [comment]
Yes, I tried that in our documentation section and the result is the same. We are consistent across the platform.
