### ISSUE TITLE
bug- get alert related user is not working

### ISSUE THREAD

**Issue by barchen1** [MicrosoftDocs/feedback#2687]
**Describe the bug**
I used this API request lots of time in the past and it always return the user, but now for some reason its not working although I have alerts related to user.

**To Reproduce**
1. send an API request to GET https://api.securitycenter.windows.com/api/alerts/636688558380765161_2136280442/user

2. See error - not found

**Expected behavior**
The API request needs to return the user that related to the given alert

**Desktop (please complete the following information):**
 - OS: [windows10]
 - Browser [chrome]

**Comment by docs-product** [comment]
Thank you for the feedback! Because this is not related to docs.microsoft.com, we cannot address it in this forum. We recommend reaching out to the appropriate product support channel for faster resolution.

**Comment by superfon** [comment]
- 

> #565 
《=?    ^        # ### [₩*1__](### 

>       《[        ((《

)**__**

-`
