### ISSUE TITLE
assignment operators page has unescaped html

### ISSUE THREAD

**Issue by binarycrusader** [MicrosoftDocs/feedback#269]
https://docs.microsoft.com/en-us/cpp/cpp/assignment-operators#comments-container

The |= operator's HTML is not properly escaped and shows as "& # 124 ; = ".

**Comment by Powerhelmsman** [comment]
@mikeblome @ghogen Can you fix the issue?

**Comment by dend** [comment]
@ghogen @mikeblome - can you please take a look?

**Comment by mikeblome** [comment]
Fixed. Thanks @binarycrusader !

**Comment by binarycrusader** [comment]
How long before the change shows up on docs.microsoft.com?

**Comment by mikeblome** [comment]
It's up there now. Thanks again!

**Comment by binarycrusader** [comment]
It’s now fixed, thanks.
