### ISSUE TITLE
Please correct the documentation mistake

### ISSUE THREAD

**Issue by go-shinyashiki** [MicrosoftDocs/feedback#2692]
**Is your feature request related to a problem? Please describe.**
The documentation states that "the app will be restarted if the app's memory quota is exceeded."
But actually it stops without restarting the app

https://docs.microsoft.com/ja-jp/azure/app-service/web-sites-monitor#quota-enforcement

**Describe the solution you'd like**
Please correct to "Stop" without writing "Restart".

**Describe alternatives you've considered**
N/A

**Additional context**
https://icm.ad.msft.net/imp/v3/incidents/details/183974721

**Comment by gewarren** [comment]
This issue was moved to MicrosoftDocs/azure-docs#53857
