### ISSUE TITLE
Azure management libraries for .NET samples for SQL Database link is broken

### ISSUE THREAD

**Issue by tremblaysimon** [MicrosoftDocs/feedback#2693]
**Describe the bug**
In that page, https://docs.microsoft.com/en-us/dotnet/api/overview/azure/sql?view=azure-dotnet, the link Azure management libraries for .NET samples for SQL Database link is broken. 

Click on it and you will get an error 404. 

Maybe it should link to https://github.com/Azure/azure-libraries-for-net/tree/master/Samples/Sql directly?

**Comment by gewarren** [comment]
This issue was moved to Azure/azure-docs-sdk-dotnet#1178
