### ISSUE TITLE
[C# Documentation, Broken] - Global Attributes doesn't exist

### ISSUE THREAD

**Issue by TCLNA** [MicrosoftDocs/feedback#2696]
**Describe the bug**
Hello there,
In the documentation, the drop-down item **Global Attributes** from `Attributes read by the compiler` redirects to microsoft's main page.

I think it's just a relic since when i try to imitate the issue link (`https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/attributes/general/global-attributes`) i fall into a 404 page.

**To Reproduce**
Go to the [CSharp Language Reference page](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/) and click on the `Attributes read by the compiler` on the side panel.

![image](https://user-images.githubusercontent.com/32589981/80229119-4157cc00-8650-11ea-9911-ffc11113dccc.png)

Sorry for bothering,

**Comment by gewarren** [comment]
This issue was moved to dotnet/docs#18212
