### ISSUE TITLE
let me read in english

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#27]
Is very boring the "Este artigo foi traduzido por máquina. Você pode exibir o texto em inglês em uma janela popup movendo o ponteiro do mouse sobre o texto" feature, I want to read in english.

----------
⚠ Idea migrated from UserVoice

**Created By:** Marco Pavanello
**Created On:** 2018/02/06 16:03:19 +0000
**Votes at Migration:** 4
**Supporters at Migration:** 4

**Comment by dend** [comment]
Duplicate of #23

**Comment by gr3ysky** [comment]
So this issue is dublicate and closed. Where is the original issue then? THIS IS SO ANNOYING, IT STILL EXISTS AND NO ONE CARES USER EXPERIENCE?
