### ISSUE TITLE
[Question] possibility to ask something about product/solution on docs product page

### ISSUE THREAD

**Issue by Rutikhal** [MicrosoftDocs/feedback#270]
Hello
Earlier on docs specific product article I could ask something and give some advice or answer on the same page. How about now? I don't want to raise some ideas, just want to clarify something about solution/feature? What do I need to do in that case?

Alexander

**Comment by Powerhelmsman** [comment]
@Rutikhal You still can give some advice or answers on specific page through "Give documentation feedback"
![image](https://user-images.githubusercontent.com/33136632/38047760-5142ae56-3278-11e8-805d-16c591760725.png)

**Comment by Rutikhal** [comment]
Hi

Thanks a lot for fast reply, I will try

//Alexander
