### ISSUE TITLE
Wrong parameter name in Rest API call documentation of Azure DevOps Server

### ISSUE THREAD

**Issue by echalone** [MicrosoftDocs/feedback#2703]
The following page:
https://docs.microsoft.com/en-us/rest/api/azure/devops/security/access%20control%20entries/remove%20access%20control%20entries?view=azure-devops-rest-5.1&source=docs
Wrongly names the parameter for the SecurityTokens as "token", when it should be "tokens" (if you try it with "token" it will throw an error).

**Comment by gewarren** [comment]
@mijacobs Do you know who owns these API docs?

**Comment by echalone** [comment]
Closing this bug because I cannot recreate it myself any more... not sure how I managed to get this error, but now I actually have to use the parameter "token" (not "tokens"), as is currently documented.
