### ISSUE TITLE
顺序写反了

### ISSUE THREAD

**Issue by SuperBeana** [MicrosoftDocs/feedback#2707]
https://docs.microsoft.com/zh-cn/dotnet/csharp/tutorials/intro-to-csharp/branches-and-loops?tutorial-step=2
只有当条件的测试结果为 else 时，才执行 false 关键字后面的语句。 将 if、else 与布尔条件相结合，可以实现所需的一切目标。

**Comment by gewarren** [comment]
This issue was moved to dotnet/docs#18211
