### ISSUE TITLE
顺序写反了 (The order is the opposite.)

### ISSUE THREAD

**Issue by SuperBeana** [MicrosoftDocs/feedback#2708]
https://docs.microsoft.com/zh-cn/dotnet/csharp/tutorials/intro-to-csharp/branches-and-loops?tutorial-step=3
此示例新引入了另外一个运算符。 ++ 变量后面的 counter 是增量运算符。 它负责用计数器值加 1，并将计算后的值存储在计数器变量中。

**Comment by gewarren** [comment]
Translation:

This example introduces another operator. The counter after the variable is the delta operator. It is responsible for adding 1 with the counter value and storing the calculated value in the counter variable.

**Comment by gewarren** [comment]
This issue was moved to dotnet/docs#18210
