### ISSUE TITLE
Issue with CDN

### ISSUE THREAD

**Issue by paulfahrenkrug** [MicrosoftDocs/feedback#271]
"Refused to execute script from 'https://ajax.aspnetcdn.com/ajax/jQuery/jquery-2.2.4.min.js' because its MIME type ('javascript') is not executable, and strict MIME type checking is enabled."

You need to change the content-type
```
content-type: javascript
```

Request URL: https://ajax.aspnetcdn.com/ajax/jQuery/jquery-2.2.4.min.js
Request Method: GET
Status Code: 200  (from memory cache)
Remote Address: 72.21.81.200:443
Referrer Policy: no-referrer-when-downgrade
accept-ranges: bytes
access-control-allow-origin: *
cache-control: public,max-age=31536000
content-length: 85578
content-type: javascript
date: Wed, 28 Mar 2018 18:51:12 GMT
etag: "50d68fcc33d21:0"
last-modified: Mon, 31 Oct 2016 23:11:07 GMT
server: ECAcc (cha/81A8)
status: 200
timing-allow-origin: *
x-cache: HIT
x-content-type-options: nosniff
x-xss-protection: 1; mode=block

**Comment by Powerhelmsman** [comment]
@paulfahrenkrug Can you provide the docs site link includes the js resource?

**Comment by paulfahrenkrug** [comment]
It's on the homepage, I probably came to the wrong place...

<script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-2.2.4.min.js"></script>
