### ISSUE TITLE
Space

### ISSUE THREAD

**Issue by afwn90cj93201nixr2e1re** [MicrosoftDocs/feedback#2717]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

https://docs.microsoft.com/en-us/previous-versions/windows/embedded/ms885627%28v%3dmsdn.10%29
> DWORDGetLastError(void);

**Comment by afwn90cj93201nixr2e1re** [comment]
@alligreubel

**Comment by rootsmusic** [comment]
@afwn90cj93201nixr2e1re "We're no longer updating this content regularly."
#please-close

**Comment by afwn90cj93201nixr2e1re** [comment]
Why would you ask me to close it if it says 'regulary'?

**Comment by afwn90cj93201nixr2e1re** [comment]
#please-open

**Comment by rootsmusic** [comment]
@afwn90cj93201nixr2e1re Please click on "Send feedback" in the doc.

**Comment by afwn90cj93201nixr2e1re** [comment]
I did a long time ago.

**Comment by afwn90cj93201nixr2e1re** [comment]
#please-close
