### ISSUE TITLE
Rest API documentation issue - For Table Connection 

### ISSUE THREAD

**Issue by niteshiosdev** [MicrosoftDocs/feedback#2718]
Hello Support,

I am trying to find the way to connect Table storage using Rest API but didn't find any Proper way for connection.

Apple stop supporting the UIWebview, so we are not able to use client SDK for IOS.
We are trying to find out the way for connection using Rest API.

There is no example using curl so we can use the Postman for connection to check the connection and implement the functionality on Swift.

Thanks

**Comment by rootsmusic** [comment]
@niteshiosdev Please ask product support or in support forums.
