### ISSUE TITLE
Missing documentation on provisioningState parameter in Databricks Workspace

### ISSUE THREAD

**Issue by sdebruyn** [MicrosoftDocs/feedback#2719]
**Is your feature request related to a problem? Please describe.**
The `provisioningState` parameter in the [Databricks Workspace](https://docs.microsoft.com/en-us/rest/api/databricks/workspaces/get#provisioningstate) object is not documented. There are quite a few states and it's not clear what each state means and how they transition to each other.

**Describe the solution you'd like**
Please document the states and explain when/why the workspace transitions to each state.

**Comment by rootsmusic** [comment]
@sdebruyn Please move this issue to https://github.com/Azure/azure-rest-api-specs/issues
