### ISSUE TITLE
"Download PDF" for SharePoint Server website  doesn't work. https://docs.microsoft.com/en-us/SharePoint/sharepoint-server

### ISSUE THREAD

**Issue by frankchen76** [MicrosoftDocs/feedback#272]
"Download PDF" button at left bottom corner for [SharePoint Server](https://docs.microsoft.com/en-us/SharePoint/sharepoint-server) doesn't work. it actually went to a page to show PDF error. can anyone from MS to fix that. a PDF version of document is very helpful for people to read it at offline. 

Thanks

**Comment by Powerhelmsman** [comment]
@dend Can you take a look  at this?

**Comment by frankchen76** [comment]
It has been 14 days since I reported this issue. I saw this issue was tagged as "bug". Can anyone from MS share the ETA when this issue is going to be addressed?
Thanks

**Comment by thedanfernandez** [comment]
@dastaffo - Can you look at this? @frankchen76 - Apologies for the delay!

**Comment by dend** [comment]
@thedanfernandez @dastaffo there was a misconfigured build file - this is being fixed with https://github.com/MicrosoftDocs/OfficeDocs-SharePoint-pr/pull/225. Should be fixed shortly.

**Comment by dend** [comment]
This should be working correctly now @frankchen76
