### ISSUE TITLE
Create Folder With Space(s) At End Of Name

### ISSUE THREAD

**Issue by reinhold1** [MicrosoftDocs/feedback#2721]
The following command creates a folder with spaces at the end of the name which is not allowed following https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#naming-conventions.
mkdir "c:\temp\abcde  \"
The new folder can not so easily be removed. The shortname may be of help (if available on the partition). Even trying to remove the parent folder fails!
rmdir "c:\temp\abcde  \"
does the job.
Looks like there is a bug in the parsing algorithm.
Regards
Reinhold

**Comment by KalleOlaviNiemitalo** [comment]
@reinhold1, did you run the `mkdir "c:\temp\abcde "` command in a Git Bash window? In that case, msys-2.0.dll bypasses the Win32 [CreateFileW function](https://docs.microsoft.com/windows/win32/api/fileapi/nf-fileapi-createfilew) and instead calls the Native API [NtCreateFile function](https://docs.microsoft.com/windows/win32/api/winternl/nf-winternl-ntcreatefile) with `\??\C:\temp\abcde `, so the Win32 parsing algorithm is not involved.

**Comment by reinhold1** [comment]
No, I did not use a special window. Originally it was a buggy piece of ObjectRexx code:
...
out_dir_2 = out_dir || jahr'-'monat || '\'
'mkdir "'out_dir_2'"'
...
where by a result of a typo 'jahr' and 'monat' contained two spaces. The variable 'outdir' contained 'c:\users\Reinhold\documents\'. Thus the command
'mkdir "c:\users\Reinhold\documents\  -  \"'
was handed over to Windows.
You can easily reproduce the problem when you enter the following command in a normal Windows command window:
mkdir "c:\temp\abc  \"
This will create a folder where the name ends with two spaces.

Regards
Reinhold

**Comment by KalleOlaviNiemitalo** [comment]
Can't reproduce with cmd.exe on Windows 10 Version 1909 (OS Build 18363.185).

**Comment by reinhold1** [comment]
Hi!
I am running several Windows 10 systems and I can reproduce the behavior on each system. The following test ran on an Windows 10 Home, 1909, 18363.778:
C:\temp>mkdir "abcdefghijklm  \"
C:\temp>dir
 Datenträger in Laufwerk C: ist Windows
 Volumeseriennummer: 7ED3-113E
 Verzeichnis von C:\temp
15.05.2020  08:47    <DIR>          .
15.05.2020  08:47    <DIR>          ..
15.05.2020  08:47    <DIR>          abcdefghijklm
               0 Datei(en),              0 Bytes
               3 Verzeichnis(se), 23.821.266.944 Bytes frei
C:\temp>rmdir "abcdefghijklm  "
Das System kann die angegebene Datei nicht finden.
C:\temp>rmdir "abcdefghijklm  \"
C:\temp>dir
 Datenträger in Laufwerk C: ist Windows
 Volumeseriennummer: 7ED3-113E
 Verzeichnis von C:\temp
15.05.2020  08:47    <DIR>          .
15.05.2020  08:47    <DIR>          ..
               0 Datei(en),              0 Bytes
               2 Verzeichnis(se), 23.822.626.816 Bytes frei
C:\temp>

Regards 
Reinhold

**Comment by reinhold1** [comment]
Ah! The backslash got removed in my append!
mkdir "abcdefghijk  \"
Before the second " a backslash is necessary. The backslash does the job!

**Comment by KalleOlaviNiemitalo** [comment]
Ah, so the command `mkdir "abcdefghijk \"` creates a directory named "abcdefghijk " with a trailing space.

So does `mkdir "abcdefghijk :$I30:$INDEX_ALLOCATION"`, using the directory stream name from [\[MS-FSCC\]: NTFS Streams](https://docs.microsoft.com/openspecs/windows_protocols/ms-fscc/c54dec26-1551-4d3a-a0ea-4fa40f848eb3).

In the [Naming Files, Paths, and Namespaces - Win32 apps](https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file) documentation, the only mention of spaces is this:

> Do not end a file or directory name with a space or a period. Although the underlying file system may support such names, the Windows shell and user interface does not. However, it is acceptable to specify a period as the first character of a name. For example, ".temp".

That seems correct to me. It does not promise that Win32 would delete trailing spaces from each path component.

**Comment by reinhold1** [comment]
Hi!
But trailing spaces are not allowed (following the link in my first append).
Looks like you call a feature what I would call a tiny bug.
Anyhow, it was an interesting riddle for me.
Have a nice day!
Reinhold
