### ISSUE TITLE
Microsoft Learn: Stuck in a sign in loop

### ISSUE THREAD

**Issue by gb1337** [MicrosoftDocs/feedback#2723]
I can't sign in to https://docs.microsoft.com/en-us/learn/

I get stuck in a loop.

1. I visit https://docs.microsoft.com/en-us/learn/
2. I click "Sign in" in the upper right hand corner.
3. I enter my personal MS account info.
4. I get redirected to https://docs.microsoft.com/en-us/learn/ and I very briefly see the page before being redirected again to the sign in page.
5. Rinse and repeat.

I have tried clearing my cookies, using my MS "Work" account (Office 365 tenant), using Incognito mode, using various browsers. Still the same issue.

Thank you

**Comment by jax214** [comment]
i'm getting the same error :(

**Comment by massiung** [comment]
I'm experiencing the same problem. I'm being redirected back to the sign in page after signing in. Also tried multiple browsers.

**Comment by MatsAnd** [comment]
I'm experiencing the same thing, both with my personal and work/school account. Have tried clearing the cache, and in different browsers.

**Comment by miki9938** [comment]
I'm having the same issue both with my personal and work account. I tried with different browsers but the site keeps me redirecting to sing in page over and over.

**Comment by MatsAnd** [comment]
@mimisasouvanh - Can you escalate this to the right team? 🙂

**Comment by braulston** [comment]
Same here and it's quite irritating. If you close the browser and reopen to docs you are still stuck in the same loop can't even get to the site

**Comment by Yi-Ching-TW** [comment]
Same here. I am in the login-loop with my two work accounts.

**Comment by SteveCT** [comment]
Same. Tried in an InPrivate session but also got stuck in the loop

**Comment by hugopaparazzo** [comment]
same. I have traced http requests in fiddler, and it seems that after authentication, docs.microsoft.com tries to register a new user and then get the profile, which returns 404. 


![image](https://user-images.githubusercontent.com/64968552/81307056-1752d080-9078-11ea-869a-0a593fa50c9d.png)

**Comment by MartinVraspir** [comment]
Same here. Tried in Edge Chromium (latest) and Chrome (latest), even in incognito mode, I got stuck in the loop.

**Comment by zerodev0** [comment]
Thank goodness I found this thread. I was tearing my hair out trying to log in. I've run into the loop on two separate browsers. Wondering what it is and when it will be fixed.

**Comment by garyciampa** [comment]
Ditto...working with a client, ~50 users experiencing the issue... great find...tick tock..waiting on an update to the issue.

**Comment by hb-coder** [comment]
we need to raise msft's attention to this, somehow. I tweeted @docsmsft but with no answer. any clue?

**Comment by garyciampa** [comment]
I have opened an incident with sitehelp.microsoft.com: 187284140

**Comment by gb1337** [comment]
> SEV 1

You mean SEV A?

**Comment by garyciampa** [comment]
UPDATE: Received feedback the issue has been mitigated, please validate and share...
![image](https://user-images.githubusercontent.com/56933939/81352221-04e69000-9094-11ea-8ad8-a8931c76d904.png)

**Comment by gb1337** [comment]
> UPDATE: Received feedback the issue has been mitigated, please validate and share...
> ![image](https://user-images.githubusercontent.com/56933939/81352221-04e69000-9094-11ea-8ad8-a8931c76d904.png)

It's working for me. Thanks for checking in with the business support. A shame MS doesn't check their Git. Only took 24h+ to fix and that was with your intervention ! Not impressed with MS on that one.

**Comment by garyciampa** [comment]
> > UPDATE: Received feedback the issue has been mitigated, please validate and share...
> 
> It's working for me. Thanks for checking in with the business support. A shame MS doesn't check their Git. Only took 24h+ to fix and that was with your intervention! Not impressed with MS on that one.

I happen to work for MS, and had some capability to nudge the issue along on behalf of my user community. We kicked off a Cloud Skills Challenge program today and the issue was blocking for the new user community.   :-)
