### ISSUE TITLE
Page broken : missing part of the content and some interactions

### ISSUE THREAD

**Issue by airmisdata** [MicrosoftDocs/feedback#2728]
**Describe the bug**
The page is broken : some text at the end of the page seem to be missing and some interactions like a toggle button "read in english" are not available

**To Reproduce**
1. Go to https://docs.microsoft.com/fr-fr/dax/new-dax-functions
2. See error

**Expected behavior**
The end of the page should be available and the toggle button to read in english should be available

**Desktop (please complete the following information):**
 - Browser : latest Chrome

**Comment by JasonWHowell** [comment]
Hi @airmisdata The page looks OK on my computer. What does it look like on your screen?  Thx, Jason

![image](https://user-images.githubusercontent.com/5067358/82639384-74dd3600-9bbd-11ea-96c1-f2e71bacf905.png)

**Comment by airmisdata** [comment]
Sorry ! 

May be I was just surprised by the absence of "updated functions"

**Comment by JasonWHowell** [comment]
@airmisdata Yeah, it is a little awkward. Maybe the list changed over time and none are in preview right now, but there will be more added later.

**Comment by airmisdata** [comment]
worksforme
