### ISSUE TITLE
Too much translation : data samples

### ISSUE THREAD

**Issue by airmisdata** [MicrosoftDocs/feedback#2729]
**Describe the bug**
This one is subtle : once the data is translated then the code doesn't reference anymore the correct column name

For example in https://docs.microsoft.com/fr-fr/dax/relatedtable-function-dax#example
there is the following table
  |   |   |  
-- | -- | -- | --
Product Category Key | Product Category AlternateKey | Nom de la catégorie de produits | Ventes sur Internet
1 | 1 | Bikes | $28,318,144.65
2 | 2 | Components |  
3 | 3 | Clothing | $339,772.61
4 | 4 | Accessories | $700,759.96

As you can see the "Sales Amount" is now translated into "Ventes sur Internet"

However, the DAX code says "InternetSales_USD" for the column

> SUMX( RELATEDTABLE('InternetSales_USD')  , [SalesAmount_USD])  

So you cannot link the two 

**To Reproduce**
1. Go to https://docs.microsoft.com/fr-fr/dax/relatedtable-function-dax#example 
2.  See error

**Expected behavior**
You should either
1. keep the name in english for the data
2. or translate also in the DAX formula

**Desktop (please complete the following information):**
 - Browser latest Chrome

**Comment by JasonWHowell** [comment]
@SonjaSaltzman please add Loc label. @Minewiskan can you set the column headings using :::noloc flag https://docs.microsoft.com/en-us/contribute/markdown-reference#non-localized-strings

**Comment by rootsmusic** [comment]
@airmisdata I suggest moving this issue to https://github.com/MicrosoftDocs/powerbi-docs/issues

**Comment by airmisdata** [comment]
Seems to be fixed Thanks !
