### ISSUE TITLE
CreateOrUpdate  Snapshot REST API - No mention of how to specify that the disk is a managed disk

### ISSUE THREAD

**Issue by meetamitbhatia** [MicrosoftDocs/feedback#273]
The REST API documentation for creating disk snapshots can be found at https://docs.microsoft.com/en-us/rest/api/compute/snapshots/createorupdate.  It makes no mention of how to specify that the disk is a managed disk.

**Comment by Powerhelmsman** [comment]
@erickson-doug Can you take a look and see if it can be updated

**Comment by meetamitbhatia** [comment]
Hi Team,

Any update on this?

Regards,
Amit Bhatia

**Comment by dend** [comment]
@erickson-doug can you help address this?

**Comment by Powerhelmsman** [comment]
@erickson-doug Any update?

**Comment by Powerhelmsman** [comment]
Sent email to @erickson-doug to follow up

**Comment by erickson-doug** [comment]
@neilpeterson should be the first contact? Neil, can you connect folks with the VM devs, or the writer who currently owns VMs?

**Comment by neilpeterson** [comment]
@iainfoulds any thoughts on whom to contact here?

**Comment by iainfoulds** [comment]
On the compute side, @singhkays, and on the storage side, @ramankumarlive, should be able to provide assistance. I think this would fall under updates required within the Compute API ref.

**Comment by neilpeterson** [comment]
@Powerhelmsman - can we re-assign this issue? I am not the right person to handle.

Thanks

**Comment by Powerhelmsman** [comment]
@neilpeterson Reassigned to @singhkays and @ramankumarlive

**Comment by Powerhelmsman** [comment]
@meetamitbhatia Your issue is transferred to vsts-rest-api team. They will help you there. I will close as transferred. If you have other question related to this issue, we can reopen it and continue discussion.

**Comment by jason-j-MSFT** [comment]
@meetamitbhatia I do not believe you have to specify the disk you are creating the snapshot of is a managed disk.  I tested this with my own REST call on a managed disk without specifying it was a managed disk, and it worked fine.
