### ISSUE TITLE
GitHub site feedback is not loaded on non en-us pages

### ISSUE THREAD

**Issue by cremor** [MicrosoftDocs/feedback#2730]
**Describe the bug**
It seems like all documentation pages that don't have `en-us` in their URL can't load the linked GitHub issues for site feedback.

**To Reproduce**
1. Go to any doc site, e.g. https://docs.microsoft.com/en-us/dotnet/standard/tour
2. Scroll down to the bottom of the page
3. See that the linked GitHub issues are shown correctly.
4. Change the `en-us` part of the URL to something else, e.g. `en-gb` or `de-de`.
5. Scroll down to the bottom of the page
6. See that the linked GitHub issues are not shown. The "Loading feedback..." (or translated equivalent) indicator never goes away.

**Expected behavior**
The linked GitHub issues should show up for all languages.
For `en-gb` it should also show the exact same issues as `en-us` shows because both redirect to the same GitHub repository for creating issues.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/116314/66981900-6114a300-f0b5-11e9-9795-1db762bd93de.png)

**Desktop:**
- OS: Windows 10
- Browser: I tested Firefox and Edge
- Version: Firefox 76.0.1, Edge 44.18362.449.0
- All browsers without any addons

**Smartphone:**
(not tested)

**Additional context**
I've already reported this in the past in #2047 but that issue was closed although the bug is still reproducible.

**Comment by JasonWHowell** [comment]
@meganbradley do you have a contact for who owns github issues widget? I can repro easily in Edge at https://docs.microsoft.com/en-gb/dotnet/standard/tour. Feedback widget loads in Chrome, but not other browsers.

**Comment by JasonWHowell** [comment]
Tracking this as ICM 189057741 internally.

**Comment by cremor** [comment]
Related: #2791

**Comment by JasonWHowell** [comment]
The feedback control that lists open issues at the bottom of docs pages was removed, and a link is now shown to see those issues. This was implemented in the last month or two.
![image](https://user-images.githubusercontent.com/5067358/88578900-1a69b700-cffe-11ea-8c38-5a45a7099845.png)
#please-close
