### ISSUE TITLE
"Liquid error" displays on some LinkedIn API documentation

### ISSUE THREAD

**Issue by markschn** [MicrosoftDocs/feedback#2731]
Most of the pages under the LinkedIn Consumer Solutions Platform API Reference have the following text next to the date immediately under the page title:

Liquid error: parsing "{0}" - Quantifier {x,y} following nothing.

Example page
https://docs.microsoft.com/en-us/linkedin/shared/integrations/people/profile-api?context=linkedin/consumer/context

**Comment by JasonWHowell** [comment]
Hi @markschn Maybe it was a temporary problem. It looks OK at the moment. 
![image](https://user-images.githubusercontent.com/5067358/82639894-7b1fe200-9bbe-11ea-912a-9003dc44d28b.png)

Do you still see the error? I'll close for now, but please reopen if you still see the problem. Thanks, Jason #please-close

**Comment by markschn** [comment]
Thanks, Jason.  Yes, the problem was there for over a week.  I confirmed that the page looks correct now with the reading time and the contributors icons.
