### ISSUE TITLE
[error message feedback] provide feedback for circular-redirection

### ISSUE THREAD

**Issue by ghogen** [MicrosoftDocs/feedback#2733]
This is a false positive - the redirection file has a version moniker, which makes this redirection a redirection to a previous version, not a circular redirection.

{
      "source_path": "docs/extensibility/accessing-text-layers-by-using-the-legacy-api.md",
      "redirect_url": "/visualstudio/extensibility/accessing-text-layers-by-using-the-legacy-api?view=vs-2015",
      "redirect_document_id": false
    }

**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

**Problem:**
What's wrong with the error message? For example,
- Is error message clear and actionable?
- Is there a documentation to provide more information?
- If there is a documentation, is it relavent and helpful?
- Is line number correct?
- etc.

**Log code info**
(This is auto filled, no need to modify)

| Severity   | Type   | Code   | Category   | File   | Message   |  Source  | Line   | Time   |
|------------|--------|--------|------------|--------|-----------|----------|--------|--------|
| Warning | User | circular-redirection |  | .openpublishing.redirection.json | Build has identified circular redirection: designers/insert-controls-and-modify-their-behavior-in-xaml-designer.md [redirection] --> designers/insert-controls-and-modify-their-behavior-in-xaml-designer.md [redirection] |  |3280 | 05/11/2020 18:23:52 |

**Link to report**
(This is auto filled, no need to modify)

[report url](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C5%5C11%5C0958ce8d-dab2-a371-12d2-9b53956be31b%5CPullRequest%5C202005111821136252-6542%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=jbmmvxs6%2FNn%2FjCLGOQqI8qL3WzbABDAIqRVVA40gzhY%3D&st=2020-05-11T18%3A19%3A48Z&se=2020-06-11T18%3A24%3A48Z&sp=r)

**Comment by JasonWHowell** [comment]
@ghogen Do you probably want to track this internally?  try sitehelp

**Comment by ghogen** [comment]
@JasonWHowell We've worked around it for now.

**Comment by JasonWHowell** [comment]
#please-close
