### ISSUE TITLE
"Account verification failed" when try to activate sandbox

### ISSUE THREAD

**Issue by bukowskm** [MicrosoftDocs/feedback#2745]
**Describe the bug**
When I try to do excercise https://docs.microsoft.com/pl-pl/learn/modules/welcome-to-azure/4-exercise-create-website I get error: "Account verification failed", detailed information: "Your account could not be verified and we've suspended your access to Learn sandbox."

**To Reproduce**
1. Go to 'https://docs.microsoft.com/pl-pl/learn/modules/welcome-to-azure/4-exercise-create-website'
2. Click on 'Activate sandbox'
3. See error "Account verification failed", "Your account could not be verified and we've suspended your access to Learn sandbox."

**Expected behavior**
I would like to finish Azure Fundamentals path https://docs.microsoft.com/pl-pl/learn/paths/azure-fundamentals/

**Screenshots**
![obraz](https://user-images.githubusercontent.com/65335793/81910240-f801f900-95cb-11ea-86a3-0ce28107f598.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox 75 (x64), Edge , IE 11

**Comment by brunoportela** [comment]
I'm having the same problem. Is there any update on this?

- OS: MacOS Mojave
- Browser: Safari 13.0.1, Firefox 76.0.1, Chrome 83.0.4103.61

**Comment by bukowskm** [comment]
@brunoportela 

In may case the solution was to create new Microsoft account using different e-mail.

**Comment by bukowskm** [comment]
In may case the solution was to create new Microsoft account using different e-mail.
