### ISSUE TITLE
search broken - https://businessstore.microsoft.com/en-us/store 

### ISSUE THREAD

**Issue by Ankushamy** [MicrosoftDocs/feedback#2751]
Major issue or bug in search on website 
when you go to https://businessstore.microsoft.com/en-us/store/search?q=one
go to search - it is broken

**To Reproduce**
1. Go to 'https://businessstore.microsoft.com/en-us/store/search?q=one'
2. Click on 'search'
3. Scroll down to 'type anything'
4. See error - it wont let you type -repro on many devices areas networks users -same issue

**Expected behavior**
You can search it
workaround - right click and paste a word you want to search

**Screenshots**
![image](https://user-images.githubusercontent.com/65413145/82073896-eb52d300-96a7-11ea-8fbf-c43cfd873039.png)

go to site , you will see issue repro 
**Desktop 
 - OS: windows 10
 - Browser [e.g. chrome, safari, mozilla, Ie, edge , all tried ]
 - Version [updated]

**Smartphone
iphone 11
safari 

**Additional context**
it need to fixed asap . looks website issue 
but if you are aware share some update on site
![image](https://user-images.githubusercontent.com/65413145/82073886-e7bf4c00-96a7-11ea-9ea1-bc91a42469d8.png)

**Comment by Ankushamy** [comment]
any updates ???

**Comment by JasonWHowell** [comment]
Hi @Ankushamy 
Would you mind filing the bug using the Feedback button on that store page? 
We are MicrosoftDocs, and don't have much access to work on that site. 
![image](https://user-images.githubusercontent.com/5067358/82514030-73324600-9ac9-11ea-848a-34b0fc46224c.png)

Thank you! Jason

**Comment by Ankushamy** [comment]
Many thanks for your email

**Comment by JasonWHowell** [comment]
Thanks for giving feedback! appreciate it #please-close
