### ISSUE TITLE
cannot downlaod **SDelete.zip**

### ISSUE THREAD

**Issue by ishibashi-futos** [MicrosoftDocs/feedback#2753]
**Describe the bug**
can not download SDelete.zip 

**To Reproduce**
1. Go to 'https://docs.microsoft.com/ja-jp/previous-versions/bb897443(v=msdn.10)?redirectedfrom=MSDN'
2. Click on 'SDelete のダウンロード'

**Expected behavior**
SDelete.exe will be downloaded.

**Screenshots**
![image](https://user-images.githubusercontent.com/41904268/82116053-b75bd880-97a1-11ea-96ed-a9d4d7d74ae8.png)

**Desktop (please complete the following information):**
 - OS: Windows10 1909
 - Browser: Microsoft Edge 
 - Version: 81.0.416.72(x64)

**Comment by ishibashi-futos** [comment]
You were able to download it from this URL. 'https://docs.microsoft.com/en-us/sysinternals/downloads/sdelete'
object url: https://download.sysinternals.com/files/SDelete.zip

You were able to download it from this URL.
http://download.sysinternals.com/files/sdelete.zip

**Comment by JasonWHowell** [comment]
Seems like its case sensitive. SDelete.zip instead of sdelete.zip  Looks like you got it to work. Thank you! I will send the problem to the sysinternals admins to be aware and fix. #please-close
