### ISSUE TITLE
A useful additional case for the en dash

### ISSUE THREAD

**Issue by guardrex** [MicrosoftDocs/feedback#2754]
Moving this issue from the style manual repo here to get more management :eyes: on it ...

[A useful additional case for the en dash (MicrosoftDocs/microsoft-style-guide #143)](https://github.com/MicrosoftDocs/microsoft-style-guide/issues/143)

The style manual only permits the en dash for *grammatical* use cases, as a connector of words and phrases. I recommend that you open up the en dash for use in one more scenario. It's useful as a **_layout element_** with definitions and descriptions. For example ...

* Link lists (e.g., topics in an *Additional resources* or other section that require a further remark) ...

  * [Topic title 1](#) &ndash; This is a remark or description about the first topic.
  * [Topic title 2](#) &ndash; This is a remark or description about the second topic.

* Definition lists

  * [System.String](#) &ndash; Represents text as a sequence of UTF-16 code units.
  * [String(SByte\*)](#) &ndash; Initializes a new instance of the String class to the value indicated by a pointer to an array of 8-bit signed integers.

In these cases imo, the en dash looks nicer :eye: than colon-space syntax ...

* Link lists (e.g., topics in an *Additional resources* or other section) ...

  * [Topic title 1](#): This is a remark or description about the first item.
  * [Topic title 2](#): This is a remark or description about the second item.

* Definition lists

  * [System.String](#): Represents text as a sequence of UTF-16 code units.
  * [String(SByte\*)](#): Initializes a new instance of the String class to the value indicated by a pointer to an array of 8-bit signed integers.

If approved, I'll close here and re-open the style manual issue to have the use cases expanded.

**Comment by JasonWHowell** [comment]
Seems like a ton of work for a minor cosmetic benefit. I'm not in favor of spending time on it.

**Comment by guardrex** [comment]
> ton of work

What do you mean? I'm just asking if the use case for the character be expanded so that I can use it in the docs. I'm not implying that everyone should use it for this purpose or that docs should change anywhere. I'm asking here because posting to the style manual repo isn't getting management eyes.

**Comment by guardrex** [comment]
The only potential problem I can think of is localization.

@JasonCard, I assume that the colon is acceptable for loc in this context (see my opening remarks). Do you feel that the en dash used as a layout element would choke loc? Note that I propose to use it with a space before and after, not as a connector (no spaces around it).

**Comment by JasonCard** [comment]
The use of en dash as a layout element should not cause any technical issues for localization. Although, there maybe languages that do not use en dash that way, and language style guides may not have guideline on how it should be localized, so we may need to update the guidelines per language. I'm also not sure Machine Translation engine will handle it. I think it will leave the en dash as is, but we'll have to see how it works.

**Comment by guardrex** [comment]
Thanks @JasonCard ... I'll toss an example in here from a live topic and how it renders in a couple of languages.

Take this one ...

https://docs.microsoft.com/en-us/aspnet/core/blazor/templates?view=aspnetcore-3.1#blazor-project-structure

... a description for each before each of the sub-lists.

That could have been handled by placing the remark on a new line, but that would suffer from additional scrolling by the reader to take in all of the content.

In a language like French, it seems ok ...

https://docs.microsoft.com/fr-fr/aspnet/core/blazor/templates?view=aspnetcore-3.1#blazor-project-structure

[btw -- I know we need to get on the additional code fencing work. I'm [re-pinging the team now](https://github.com/dotnet/AspNetCore.Docs/issues/18372) on it now.]

Looks good in Chinese, too ...

https://docs.microsoft.com/zh-cn/aspnet/core/blazor/templates?view=aspnetcore-3.1#blazor-project-structure

**Comment by JasonWHowell** [comment]
Seems like Japanese localization is most sensitive to spacing, if you could test that too.

We see em-dashes most often when authors copy text from word docs or outlook emails and put into markdown.  Some special characters are automatically replaced by markdown linting configured in the big repos, but I don't see anything configured to auto-replace dashes, so we're probably good there.

**Comment by JasonCard** [comment]
Thank you for the example. Yes, looks like MT engine is leaving them as is. For human translated languages like [German (de-de)](https://docs.microsoft.com/de-de/aspnet/core/blazor/templates?view=aspnetcore-3.1#blazor-project-structure), it was translated as colon (:). [Japanese (ja-jp)](https://docs.microsoft.com/ja-jp/aspnet/core/blazor/templates?view=aspnetcore-3.1#blazor-project-structure) was also human translated as is with en dash. So it looks like there's no issue for localization.

**Comment by guardrex** [comment]
That's one hurdle (probably) passed.

It's not getting a lot of love as a layout element in typography. https://en.wikipedia.org/wiki/Dash It seems like 100% of the references tho are for *grammatical purposes*, not HTML content layout. I admit that there's a very narrow difference.

I suppose given that it isn't common in typography, not an option in style manuals (ours or *Chicago*), and not my place to change the entire industry's mind ... or the **_entire English language_** :smile:, I'm going to have to move to the colon.

I just find it hard to believe that a list of items (nouns) with a space-dash-space plus description construct hasn't been in use for thousands of years in most written languages. It seems very natural to write on paper.

Thanks for the discussion!
