### ISSUE TITLE
Some description on page is not correct enough.

### ISSUE THREAD

**Issue by Ashing27** [MicrosoftDocs/feedback#2759]
On the page:
https://docs.microsoft.com/zh-cn/windows/mixed-reality/unreal-uxt-ch2
the introduction of 7th step is 
"...然后在 DefaultSceneRoot 上单击并拖动 Root...", is to hard to understand.
Root is not on DefaultSceneRoot, and it's also impossible to click or drag anything on it.
it may be a mistake in translation.
It's better to descript it as "...然后单击并拖动Root到DefaultSceneRoot上..."

**Comment by JasonWHowell** [comment]
@suwu please take a look.

**Comment by sw5813** [comment]
Hi @JasonWHowell, I believe the localization for Microsoft docs is done automatically- do you know if there's a way to update a specific section of the translation?

**Comment by JasonWHowell** [comment]
@sw5813 for open source content repos, the change can be submitted to the localized repo and the localization translation team will get the request. A pull request to the file should work. I don't know the specific workflow.
https://github.com/MicrosoftDocs/mixed-reality.zh-cn/blob/live/mixed-reality-docs/unreal-uxt-ch2.md

**Comment by JasonWHowell** [comment]
@SunnyDeng do you know the loc contact for this repo? MicrosoftDocs/mixed-reality

**Comment by SunnyDeng** [comment]
@DavidPrio please take care this feedback. 
@JasonWHowell the loc owner is @nokura. In the meantime, our feedback auto pipeline will pick up this GH if 'Loc' is added in the label. Please check https://review.docs.microsoft.com/en-us/help/contribute/localization-azure-docs?branch=master#wait-this-gh-issue-in-the-english-repo-is-actually-for-another-language. Thanks!

**Comment by DavidPrio** [comment]
Thanks @SunnyDeng for the heads up. @JasonWHowell @nokura Once Loc Label is added, we will be able to import this ticket and start working on it.

**Comment by Ashing27** [comment]
Thanks for your nicely work.
The document become much more easier to understand.
