### ISSUE TITLE
Offline content

### ISSUE THREAD

**Issue by CruzMissile** [MicrosoftDocs/feedback#276]
Can .NET API docs be downloaded for offline use?

**Comment by Powerhelmsman** [comment]
@dend Can you answer the question?

**Comment by CruzMissile** [comment]
I work in areas where sometimes I may access only local content. I could really use the .NET API HTML locally.

**Comment by dend** [comment]
@CruzMissile yes, you can use the Download PDF button under the table of contents! Alternatively, you can also download the .NET reference with the help of [Help Viewer](https://docs.microsoft.com/en-us/visualstudio/ide/microsoft-help-viewer).

**Comment by CruzMissile** [comment]
Thank you!

I searched many pages but saw no PDF down load. May I have the link for
.net fw 4.5.2 and 4.7.1?
