### ISSUE TITLE
SCSM 2019 SQL Requirements

### ISSUE THREAD

**Issue by ubergeek24** [MicrosoftDocs/feedback#2763]
**Describe the bug**
SQL Requirements do not specify that the Full-Text Search feature needs to be installed as part of the initial SQL Server build.  

https://docs.microsoft.com/en-us/system-center/scsm/system-requirements?view=sc-sm-2019

**To Reproduce**
Currently in the Doc:
+--------------------------------------------
Microsoft SQL Server hosts the databases that System Center - Service Manager creates. In addition, System Center 2019 - Service Manager requires SQL Server Analysis Services (SSAS) to work with Microsoft Online Analytical Processing (OLAP) cubes. SQL Server Reporting Services (SSRS) is required to support System Center 2019 - Service Manager reporting.

Use this information to evaluate if your SQL Server environment is ready to support the installation of or upgrade to System Center 2019. Use this information whether you are deploying one or multiple components of System Center.
+--------------------------------------------
If SQL is deployed with only the SQL Engine, Analysis Services and Reporting Services installed the Service Manager Installation will fail wit the error: 

Service  Manager management server
Full text search is not installed on the SQL Server instance XYZ

**Expected behavior**
Successful installation of SCSM Management Server. Based on an older document for SCSM 2012 R2 SQL requirements are as follows:
+--------------------------------------------

SQL Server configuration
Use the following configuration with your version of SQL Server:
•	SQL Server full-text search: Full-text search must be selected during installation on the computers running SQL Server that will host the Service Manager and data warehouse databases.
•	SQL Server configured to use case-insensitive databases.
•	Service Account configured in accordance with your organization’s requirements.
•	The SQL Server Reporting Services (MSSQLSERVER) service, configured and running. For more information about how to configure the MSSQLSERVER service, see How to: Verify a Reporting Services Installation.
•	Ensure that you use the same collation in SQL Server and Analysis Services on the computers that host the Service Manager database, the data warehouse database, and the analysis services database. 

For more information about SQL Server collations, see Using SQL Server Collations.
If your SQL Server installation is using the default collation (SQL_Latin1_General_CP1_CI_AS), a warning message appears, stating that the collation is not one of the supported collations for Service Manager and that an unsupported collation can cause unpredictable behavior in multilingual environments.
 Caution 
Support for languages other than English in Service Manager is not possible when you are using the collation SQL_Latin1_General_CP1_CI_AS. If later you decide to support multiple languages using a different collation, you have to reinstall SQL Server. There are no issues with using the SQL_Latin1_General_CP1_CI_AS collation with the English-only installations of Service Manager. SQL_Latin1_General_CP1_CI_AS is supported despite the warning message in setup. It is generally used for installations where the Service Manager databases will share a SQL Server instance with other System Center components which must be installed on SQL_Latin1_General_CP1_CI_AS, most notably Operations Manager. If Service Manager will be installed on its own SQL Server instance, it is recommended to use the newer and more complete collation Latin1_General_100_CP1_CI_AS. For more information about language support, see Support for languages in addition to English.
You can define the collation when you install SQL Server. During Setup, on the Server Configuration page, click the Collation tab, and then click Customize for both the Database Engine and Analysis Services entries.

https://download.microsoft.com/download/1/F/F/1FF8B3C8-694F-4323-93DE-AA8AC6821949/SC2012R2_SuppMatrix.docx

Attempted upgrade to SCSM 2019 after moving the database from a server that had Full-Text installed to a SQL 2017 server that did not:

**Screenshots**
![image](https://user-images.githubusercontent.com/38093810/82383411-baea9c00-99fb-11ea-8d2d-72709c67021e.png)

**Desktop (please complete the following information):**
 - OS: Windows Server 2019
 - Browser all

**Additional context**
Would like to have the first bullet added to the SQL Requirements Section of the Doc:
+--------------------------------------------
SQL Server full-text search: Full-text search must be selected during installation on the computers running SQL Server that will host the Service Manager and data warehouse databases.
+--------------------------------------------

**Comment by JasonWHowell** [comment]
@JYOTHIRMAISURI could you update the docs page with the SQL Full Text search requirement? 
https://docs.microsoft.com/en-us/system-center/scsm/system-requirements?view=sc-sm-2019

**Comment by JYOTHIRMAISURI** [comment]
@JasonWHowell  thanks for the feedback. Will get back  on this.  Adding Aakash Basavaraj the PM for SM. 

@aakashb01  pls confirm the requested  inclusion.  Thanks.

**Comment by JYOTHIRMAISURI** [comment]
@aakashb01 thanks for the review and confirmation.

@JasonWHowell  We have included a note as requested, the update will be live today PST.

Here is the preview:
https://review.docs.microsoft.com/en-us/system-center/scsm/system-requirements?view=sc-sm-2019&branch=pr-en-us-2872#sql-server-requirements

**Comment by JasonWHowell** [comment]
Looks nice. Thanks for the followup @JYOTHIRMAISURI

**Comment by JasonWHowell** [comment]
#please-close
