### ISSUE TITLE
Broken Web link

### ISSUE THREAD

**Issue by ChuckM2** [MicrosoftDocs/feedback#2765]
**Describe the bug**
Broken Web link

**To Reproduce**
1. Go to https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes#16.6.0
2. Click on 'Known Issues'
3. Goes to https://developercommunity.visualstudio.com/topics/Visual+Studio+2019+Version+16.7.html?
4. See Page not found

**Expected behavior**
Something besides Page not found

**Desktop (please complete the following information):**
Chrome browser

**Comment by JasonWHowell** [comment]
@jawiddis please take a look - there's a broken link on an important release notes page.

**Comment by JacquelineWiddis** [comment]
It is fixed.

**Comment by JasonWHowell** [comment]
Thanks! #please-close
