### ISSUE TITLE
Error in text - password page

### ISSUE THREAD

**Issue by splintercelian** [MicrosoftDocs/feedback#2768]
In following page there is this sentence : "Brute forcing an NTLM hash takes several orders of magnitude longer than brute forcing the NTLM hash of the same password."

I guess what was intended to write was : "Brute forcing an NTLM hash takes several orders of magnitude longer than brute forcing the LM hash of the same password."

https://docs.microsoft.com/en-us/previous-versions/tn-archive/cc875839(v=technet.10)?redirectedfrom=MSDN

**Comment by rootsmusic** [comment]
@splintercelian "We're no longer updating this content regularly."
#please-close
