### ISSUE TITLE
Something is Wrong with CImage Class, Draw Function 

### ISSUE THREAD

**Issue by EdwinIZ8** [MicrosoftDocs/feedback#277]
# Something is Wrong with CImage Class, Draw Function 

## When I want to make a image look smaller than it is, I used 
`BOOL Draw(
 HDC hDestDC,
 int xDest,
 int yDest,
 int nDestWidth,
 int nDestHeight,
 int xSrc,
 int ySrc,
 int nSrcWidth,
 int nSrcHeight) const throw();
`
## This is the link about CImage class below:
[https://docs.microsoft.com/zh-cn/cpp/atl-mfc-shared/reference/cimage-class?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DZH-CN%26k%3Dk(ATLIMAGE%2FATL%3A%3ACImage)%3Bk(ATL%3A%3ACImage)%3Bk(CImage)%3Bk(DevLang-C%2B%2B)%3Bk(TargetOS-Windows)%26rd%3Dtrue#draw](url)

**Comment by dend** [comment]
@EdwinIZ8 unfortunately, we cannot address this feedback in this forum as it does not relate to docs.microsoft.com - we recommend you reach out to [Windows Developer Support](https://developer.microsoft.com/en-us/windows/support).
