### ISSUE TITLE
Links "More" stopped expand yesterday

### ISSUE THREAD

**Issue by AndreyShvidky** [MicrosoftDocs/feedback#2773]
**Describe the bug**
Yesterday I used links "More" often and it worked. Suddenly links "More" stopped expand

**To Reproduce**
1. Go to https://docs.microsoft.com/en-us/dotnet/api/microsoft.sqlserver.transactsql.scriptdom.tablereferencewithalias?view=sql-dacfx-140.3881.1
2. Click on 'More'

Nothing happens

**Expected behavior**
A more derived members to expand

**Screenshots**
![Error](https://user-images.githubusercontent.com/31736985/82732534-7e2de600-9d16-11ea-8907-b5d47bbacd2d.PNG)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Edge (chromium), Chrome
 - Version latest

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mairaw** [comment]
It seems the design has changed since then and the More link is no longer displayed. Closing this. 

/cc @mimisasouvanh @TianqiZhang
