### ISSUE TITLE
Multiple broken links on the main PowerShell Documentation page

### ISSUE THREAD

**Issue by jhoffmann271** [MicrosoftDocs/feedback#2776]
**Describe the bug**
PowerShell Documentation 'More Docs' submenu item 'Windows Management Framework' docs page returns error page not found.

**To Reproduce**
1. Go to 'https://docs.microsoft.com/en-us/powershell'
2. Click on 'More Docs'
3. Click on 'Windows Management Framework'

**Expected behavior**
'More Docs' submenu item 'Windows Management Framework' should link to Windows Management Framework docs page.

**Screenshots**
![More Docs](https://user-images.githubusercontent.com/56080024/82749919-291fbd80-9d72-11ea-8cd3-55575c74b156.png)

**Comment by jhoffmann271** [comment]
All of these links are also broken on the main PowerShell Documentation page:

Section "PowerShell 5.1"
![image](https://user-images.githubusercontent.com/56080024/82761721-395f8900-9dc2-11ea-895b-899b53461340.png)
Both "Install Windows PowerShell" and "What's new in PowerShell 5.x" links are invalid.

Section "Community Resources"
![image](https://user-images.githubusercontent.com/56080024/82761781-a70bb500-9dc2-11ea-8df0-83d3d6b94766.png)
The Community Resources "PowerShell Slack" link returns "This link is no longer active. To join this workspace, you'll need to ask the person who originally invited you for a new link."

Section "Related technologies"
![image](https://user-images.githubusercontent.com/56080024/82761841-12ee1d80-9dc3-11ea-87a3-f6223d4c5e42.png)
"Windows Management Framework" link is broken in this section as well.

**Comment by jhoffmann271** [comment]
Here are the respective valid link paths:

"Windows Management Framework"
https://docs.microsoft.com/powershell/scripting/windows-powershell/wmf/overview

"Install Windows PowerShell"
https://docs.microsoft.com/powershell/scripting/windows-powershell/install/installing-windows-powershell

"What's new in PowerShell 5.x"
https://docs.microsoft.com/powershell/scripting/windows-powershell/whats-new/what-s-new-in-windows-powershell-50

**Comment by jhoffmann271** [comment]
**Update**
The two PowerShell 5.1 links and the WMF link are now fixed. The only invalid link remaining is the expired PowerShell Slack invite link.

**Comment by xtqqczze** [comment]
Fixed in MicrosoftDocs/PowerShell-Docs/pull/6018 / MicrosoftDocs/PowerShell-Docs/pull/6019

**Comment by xtqqczze** [comment]
@jhoffmann271 the slack link at <http://poshcode.org/slack> is maintened by @Jaykul

**Comment by jhoffmann271** [comment]
The Slack invite link works now. I was able to join. The poshcode.org/slack redirect still needs to be fixed.

**Comment by xtqqczze** [comment]
@jhoffmann271 <https://poshcode.org/slack> is fixed, could you close the issue?
