### ISSUE TITLE
add Persian translation

### ISSUE THREAD

**Issue by behroozbc** [MicrosoftDocs/feedback#2778]
hi 
how can add other language to asp.net docs 
i want to help adding Persian

**Comment by SonjaSaltzman** [comment]
@JasonCard

**Comment by JasonCard** [comment]
Hi @behroozbc 

Thank you for your question and interest to contribute to our Docs translation.
Unfortunately, we currently do not have plans to localize into Persian.
Our content is also not open for translation by public, but it's a possibility we are considering for the future. 

Best regards,
Microsoft DOCS Global Experience Team
