### ISSUE TITLE
Tree for Sublinks Within the Page

### ISSUE THREAD

**Issue by spottedmahn** [MicrosoftDocs/feedback#278]
## Issue Details

Under the 'in this article' section, only ##'s are shown. I think all headings should be shown. I think it should be a collapsible tree that is collapsed by default.

By defaulting the tree to collapsed the UI will still be clean.

By adding all heading, users can more easily navigate larger documents.

### Example

![image](https://user-images.githubusercontent.com/14079228/38257964-53f334d4-372f-11e8-81aa-01977b11fec1.png)

[Page reference](https://t.co/4I5VwHF0N0)

[Twitter thread](https://twitter.com/spottedmahn/status/913094191399530497)

**Comment by Powerhelmsman** [comment]
@ShevaDas Is this belong to you as experience PM?

**Comment by spottedmahn** [comment]
Hi @ShevaDas - thanks for taking the time to review and provide your feedback.

>rather than adding UI components to improve navigation, we may need to instead work on creating shorter articles or better h2s

Please make that happen 😁!

**Comment by ShevaDas** [comment]
@spottedmahn We'll do our best!
