### ISSUE TITLE
Power Query's Table.PartitionValues page is copied and pasted from the Table.Partition page

### ISSUE THREAD

**Issue by DubbySlashy** [MicrosoftDocs/feedback#2782]
The [Table.PartitionValues](https://docs.microsoft.com/en-us/powerquery-m/table-partitionvalues) page is largely identical to the [Table.Partition](https://docs.microsoft.com/en-us/powerquery-m/table-partition) page. Please make sure that the content on both of these pages reflects their respective functions.

**Comment by micwebnet** [comment]
Another way to say this is "Table.PartitionValues is undocumented and instead includes documentation of Table.Partition". Please fix. This isn't Pri3.

**Comment by DubbySlashy** [comment]
micwebnet, is that comment directed at me or at Microsoft? Did you mean "please fix the documentation" or "please fix the title of the issue"? If the issue isn't Pri3, what should it be?

**Comment by micwebnet** [comment]
At Microsoft. The docs are clearly a copy paste of Table.Partition. In general I find level of M-language docs appalling. When I need to learn a new M function there are good online sources, and the docs isn't one of them. Not sure why. It's an incredibly powerful and elegant language!

**Comment by shenyqwilliam** [comment]
The official Power Query documentation apparently lacks maintenance, some pages missing details, some just wrong.  And they even hid the Github repo.  
Anyway, you can type `= #shared` in Power Query Editor to find better docs. For example, `= #shared[Table.PartitionValues]`. Same info can be found [here](https://www.powerquery.io/binary-formats/table.partitionvalues).

**Comment by rootsmusic** [comment]
@DubbySlashy Please move this to https://github.com/MicrosoftDocs/powerquery-docs/issues

**Comment by DubbySlashy** [comment]
@rootsmusic I reposted this issue here: https://github.com/MicrosoftDocs/powerquery-docs/issues/153
