### ISSUE TITLE
Power Query's Table.Reverse page is copied and pasted from the Text.Reverse page

### ISSUE THREAD

**Issue by DubbySlashy** [MicrosoftDocs/feedback#2783]
The content of the [Table.Reverse page](https://docs.microsoft.com/en-us/powerquery-m/table-reverse) is identical to the content of the [Text.Reverse page](https://docs.microsoft.com/en-us/powerquery-m/text-reverse). Please correct the documentation for the Table.Reverse page.

**Comment by rootsmusic** [comment]
@DubbySlashy Table.Reverse has been deleted.

**Comment by rootsmusic** [comment]
@DubbySlashy Table.Reverse has been deleted.
