### ISSUE TITLE
Can not access DMA download page.

### ISSUE THREAD

**Issue by hiobay** [MicrosoftDocs/feedback#2788]
**Describe the bug**
We can not access DMA download page with "Gateway timeout".
https://www.microsoft.com/en-us/download/details.aspx?id=53595

**To Reproduce**
See error
Gateway Timeout
The proxy server did not receive a timely response from the upstream server.
Reference #1.bb6e2317.1590461588.1b768896

**Comment by hiobay** [comment]
Thank you.
I can access this site now.

**Comment by rootsmusic** [comment]
@hiobay Download at https://download.microsoft.com/download/C/6/3/C63D8695-CEF2-43C3-AF0A-4989507E429B/DataMigrationAssistant.msi
#please-close
