### ISSUE TITLE
How do i link my Windows Store app with my hardware drivers that i have developed?

### ISSUE THREAD

**Issue by steviehutch** [MicrosoftDocs/feedback#279]
# Idea Title

Be as descriptive as you can with your idea/bug report/question/suggestion.

## Issue Details

Add a detailed explanation of what is wrong or what you want implemented. Images and rich content is welcome!

**Comment by steviehutch** [comment]
Linking a hardware driver to a windows store app.
Back in the day, hardware/software vendors would create an install shield package to install drivers and then install the software for custom hardware for the windows operating system. I am wondering how this mechanism has changed now that we can release an app in the windows store. Can I submit the driver separately to Microsoft as part of the hardware development program so it gets released as a windows update? Then I could safely release my software app in the store without having to worry about the driver being bundled with the app? Is this the best solution?

**Comment by xuanhoang77** [comment]
PAYPAL20

**Comment by xuanhoang77** [comment]
Mình

**Comment by dend** [comment]
@steviehutch given that this is not related to docs.microsoft.com, we cannot address this question in this forum. I recommend you start with [Windows Developer Support](https://developer.microsoft.com/en-us/windows/support).
