### ISSUE TITLE
Have you started to hide open issues?

### ISSUE THREAD

**Issue by Petri-X** [MicrosoftDocs/feedback#2791]
Hi there,

Earlier the latest open issues has been shown on the pages in docs.microsoft.com. But now those are not visible anymore.

![image](https://user-images.githubusercontent.com/43988151/82915780-de709200-9f79-11ea-87a2-aeb8f77771bc.png)

Has this been done by purpose (hide issues) or is this a known issue?

Yes, open issues are visible behind linke: "view all page feedback".

regards
Petri-X

**Comment by JasonWHowell** [comment]
@alligreubel FYI

**Comment by JasonWHowell** [comment]
Yes, this was intentional. Alli has more context if needed. 
![image](https://user-images.githubusercontent.com/5067358/88579265-a2e85780-cffe-11ea-884c-079a0bb659f9.png)
#please-close

**Comment by Petri-X** [comment]
Would you @alligreubel share some thoughts why Microsoft does not want to give an easy view how many issues in certain pages have? In my mind this might increase a risk of having duplicate issues.

Previously it was much more simple for comment these when we could see the topics of open/closed issues on the same page from where you start writing feedback.
