### ISSUE TITLE
IOCSPCAConfiguration::get_ProviderProperties typos in property names

### ISSUE THREAD

**Issue by Crypt32** [MicrosoftDocs/feedback#2792]
Sorry if this is not the right place, but [Win32 SDK Docs)[https://github.com/MicrosoftDocs/sdk-api] don't accept issues.

The bug filed against [IOCSPCAConfiguration::get_ProviderProperties](https://docs.microsoft.com/en-us/windows/win32/api/certadm/nf-certadm-iocspcaconfiguration-get_providerproperties) API documentation.

"Remarks" section contains typos in two property names:

- <...>
- BaseCrlUrl
- DeltaCrlUrl
- <...>

In certadm.h file, they are efined as follows:
```C
<...>
#define wszOCSPREVPROP_BASECRLURLS		L"BaseCrlUrls"
#define wszOCSPREVPROP_DELTACRLURLS		L"DeltaCrlUrls"
<...>
```
For these property names "s" letter is missing in documentation.

Applies to:
- Windows Server 2008 Enterprise, Datacenter edition
- Windows Server 2008 R2 all editions
- Windows Server 2012 all editions
- Windows Server 2012 R2 all editions
- Windows Server 2016 all editions
- Windows Server 2019 all editions

**Comment by drewbatgit** [comment]
Thank you for reporting this issue. The API names have been updated in the source. You should see the changes propagate to the live page in ~24 hours.
