### ISSUE TITLE
English original statement and Japanese translated statement differs each other.

### ISSUE THREAD

**Issue by YoshikaSuzuki** [MicrosoftDocs/feedback#2795]
**Describe the bug**
English original statement and Japanese translated statement differs each other.
Here is the original statement.
https://docs.microsoft.com/en-us/dynamics365/ai/sales/configure-premium-forecasting#forecast-predictions
Consider the following before you start using predictive forecasting, you must have:
- More than 10 closed opportunities with values filled for the fields?Actual Value, Actual Close Date, Estimated Value, and Estimated Close Date.

Here is Japanese translated version and it's different from English original one even though it was published on same day as English one, 2020/02/03. 
https://docs.microsoft.com/ja-jp/dynamics365/ai/sales/configure-premium-forecasting#forecast-predictions
Consider the following before you start using predictive forecasting, you must have:
- At least 200 closed opportunities are required for the forecast proposal model to work. You need at least two years of closed opportunities to get the most accurate forecast.

The conditions are too different, so please correct the Japanese version.

**To Reproduce**
N/A

**Expected behavior**
N/A

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by SonjaSaltzman** [comment]
@vinceno

**Comment by vinceno** [comment]
@YoshikaSuzuki thanks you again for this input - we are dealing with the issue now and will update when complete.

**Comment by vinceno** [comment]
@YoshikaSuzuki apologies for the lateness of response - this issue was addressed back in June

**Comment by vinceno** [comment]
@SonjaSaltzman I don't seem to have permissions to edit the state of this feedback but it can be closed as addressed

**Comment by YoshikaSuzuki** [comment]
@vinceno I confilmed the Japanese article was ｍodified.Thank you for your support.
