### ISSUE TITLE
Czech words in german text

### ISSUE THREAD

**Issue by oo-dev17** [MicrosoftDocs/feedback#2799]
**Describe the bug**
On the page
https://docs.microsoft.com/de-de/dotnet/framework/wpf/controls/how-to-use-selectedvalue-selectedvaluepath-and-selecteditem
suddenly the words "nastaven NA hodnotu" appear, that are not german (but czech)

**To Reproduce**
1. Go to https://docs.microsoft.com/de-de/dotnet/framework/wpf/controls/how-to-use-selectedvalue-selectedvaluepath-and-selecteditem
3. Scroll down to the lower half of the page

**Expected behavior**
The text shoulod be german

**Screenshots**
![image](https://user-images.githubusercontent.com/6067255/83236194-6aa9d180-a193-11ea-9547-bdf3c5b1ce58.png)

**Desktop (please complete the following information):**
 - Browser  chrome 
 - Version 83

**Comment by gewarren** [comment]
This issue was moved to dotnet/docs#18992
