### ISSUE TITLE
"Asymmetric encryption is weaker than symmetric encryption using the same key length, but it is relatively slow."

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#28]
Page 
https://docs.microsoft.com/en/sql/relational-databases/security/encryption/choose-an-encryption-algorithm
has a misleading information.
"Asymmetric encryption is *weaker* than symmetric encryption using the same key length, but it is relatively slow."
Page https://docs.microsoft.com/en/sql/relational-databases/security/encryption/encryption-hierarchy confirmes that I right.

----------
⚠ Idea migrated from UserVoice

**Created By:** Olga Bavchenkova
**Created On:** 2018/02/02 17:35:12 +0000
**Votes at Migration:** 1
**Supporters at Migration:** 1

**Comment by Powerhelmsman** [comment]
@edmacauley @craigg-msft @MightyPen @CarlRabeler Can you update the status?

**Comment by edmacauley** [comment]
Looks like my article(s) I will take a look

**Comment by dend** [comment]
@edmacauley do you happen to have an update on this ask?

**Comment by Powerhelmsman** [comment]
Sent a email to @edmacauley to follow up.

**Comment by CarlRabeler** [comment]
please assign to Craig Guyer - craig-msft
Ed has left the company

**Comment by Powerhelmsman** [comment]
@craigg-msft Assign this issue to you.

**Comment by craigg-msft** [comment]
issues / feedback should be provided directly on the topic, at the bottom.  
https://docs.microsoft.com/en-us/sql/relational-databases/security/encryption/choose-an-encryption-algorithm?view=sql-server-2017

The sql server content currently uses Livefyre for feedback. I see one comment at the bottom of the topic and I will ping the current author. 

please close this issue.
