### ISSUE TITLE
Some documents of Chinese version have no navigation

### ISSUE THREAD

**Issue by ToMakeSense** [MicrosoftDocs/feedback#280]
**English version**
https://docs.microsoft.com/en-us/azure/logic-apps/
![image](https://user-images.githubusercontent.com/6244148/38310138-59607bf0-384e-11e8-8ad5-ad173306abd7.png)

**Chinese version**
https://docs.microsoft.com/zh-cn/azure/logic-apps/
![image](https://user-images.githubusercontent.com/6244148/38310224-9c242dec-384e-11e8-8a49-cdea85174e00.png)

**Comment by Powerhelmsman** [comment]
@SonjaSaltzman Can you take a look at this? Is this by design?

**Comment by SonjaSaltzman** [comment]
@Powerhelmsman Thank you for letting us know, it's definitely a bug; we are looking into it.

**Comment by SonjaSaltzman** [comment]
@SunnyDeng @v-jacard could you please follow up?

**Comment by v-jacard** [comment]
@Powerhelmsman @SonjaSaltzman @SunnyDeng We have taken care of this issue and confirmed the missing TOC is now published live: [https://docs.microsoft.com/zh-cn/azure/logic-apps/](https://docs.microsoft.com/zh-cn/azure/logic-apps/)

**Comment by ToMakeSense** [comment]
It works now, thanks!

**Comment by ToMakeSense** [comment]
@Powerhelmsman @SonjaSaltzman @v-jacard @SunnyDeng  Another similar problem

**English version**
https://docs.microsoft.com/en-us/powershell/azure/overview

**Chinese version**
https://docs.microsoft.com/zh-cn/powershell/azure/overview

**Comment by ToMakeSense** [comment]
It works now.

**Comment by DavidPrio** [comment]
Thank you for your feedback.
 
Our engineering team reviewed your suggestions and accepted them. We implemented your feedback and published to the updated articles on the reported pages. 

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.

Kind regards,
Microsoft DOCS International Team
