### ISSUE TITLE
Cannot view Chloe Intro for Learn TV

### ISSUE THREAD

**Issue by EdwinGomes** [MicrosoftDocs/feedback#2806]
**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'https://docs.microsoft.com/en-us/learn/tv/'
2. Click on 'Chloe Intro'
3. Click on Watch Now'
4. Page redirects to https://docs.microsoft.com/en-us/learn/tv/None
5. Displays 404 - Page not found

**Expected behavior**
View Chloe Intro.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 83

**Comment by rootsmusic** [comment]
@EdwinGomes  Sorry, that was live.
#please-close
