### ISSUE TITLE
Feedback/survey form for Windows release health dashboard broken

### ISSUE THREAD

**Issue by GiantCrocodile** [MicrosoftDocs/feedback#2807]
If you click on the link in the green information box it takes you to a survey where you don't have permissions to. Thus I can't fill in the survey due to lacking permissions.

> The Windows release health dashboard is always evolving. Take our short survey and let us know how we can improve.

Error message: `You are not authorized to display this form.`

See this article: https://docs.microsoft.com/en-us/windows/release-information/status-windows-10-2004

**Comment by rootsmusic** [comment]
Fixed.
#please-close
