### ISSUE TITLE
Dont work DirectX SDK in Visual Studio 2017 Professional

### ISSUE THREAD

**Issue by Lakerovich** [MicrosoftDocs/feedback#281]
# Idea Title

Dont work DirectX SDK in Visual Studio 2017 Professional

## Issue # Details

I compile a my new cheat for CSGO and i gived a log of error
Vector4D, Vector3D, Vector

**Comment by Powerhelmsman** [comment]
@Lakerovich Which Docs site page are you referring to? This channel is for Docs site only. If you can give me more details, I can help you transfer to right channel.

**Comment by dend** [comment]
Closing as this is not related to docs.microsoft.com.
