### ISSUE TITLE
Problems with Speech rate in Speech One Coree

### ISSUE THREAD

**Issue by JuanJo2016** [MicrosoftDocs/feedback#2811]
I am a programmer. When I program (in C #) for Win32 / 64 I lower the voice speed (Speech rate) I have no problems. Staggered up or down and useful. On the other hand, if I do it for UWP, when I go down one step from normal speed, the voice is as if the person was drunk. And when I go up, it does it so fast it's unusable.

I have Windows 10 Pro, version 1909,compilation 18363.836
I use C# in Visual Studio 2019 enterprise version 16.6.0
[TTs.zip](https://github.com/MicrosoftDocs/feedback/files/4711204/TTs.zip)

**Comment by rootsmusic** [comment]
@JuanJo2016 Please ask product support or in support forums.
#please-close

**Comment by JuanJo2016** [comment]
Please, to give an aswer like that, don´t even bother yourself. Shame on you

________________________________
De: rootsmusic ***@***.***>
Enviado: miércoles, 28 de julio de 2021 16:49
Para: MicrosoftDocs/feedback ***@***.***>
Cc: Juanjo ***@***.***>; Mention ***@***.***>
Asunto: Re: [MicrosoftDocs/feedback] Problems with Speech rate in Speech One Coree (#2811)


@JuanJo2016<https://github.com/JuanJo2016> Please ask product support or in support forums.
#please-close
