### ISSUE TITLE
Html bug into section 'Fonts in Xamarin.Forms'

### ISSUE THREAD

**Issue by Nihilem** [MicrosoftDocs/feedback#2816]
All of the page is clickable, there are some problems with <a> tags in  headlines text. 

to Reproduce
Steps to reproduce the behaviour:
Go to  [https://docs.microsoft.com/it-it/xamarin/xamarin-forms/user-interface/text/fonts](url)

Desktop (please complete the following information):
OS: Windows 10
Browser Chrome
Version 83.0.4103.61

**Comment by gewarren** [comment]
This issue was moved to MicrosoftDocs/xamarin-docs#2934
