### ISSUE TITLE
Windows 10 needs to recognize NON-touch screen PCs

### ISSUE THREAD

**Issue by CrystalDawn625** [MicrosoftDocs/feedback#2821]
6-4-2020
**Describe the bug**
Windows 10 requests that I use eye, fingerprint or other types of identification not available on my PC.  My PC is not a touch screen, it is not a phone or a tablet, but this is how Windows 10 identifies my NON-touch screen PC.

**To Reproduce**
1. Boot up PC
2. Currently able to enter PIN
3. Receive message(s) asking if I want new apps for my tablet
4. Receive message(s) asking if I want to change my sign-on to a touch pattern, fingerprint, or retinal identification lock
5. Worry I'll get locked out of my PC because of Windows 10 inability to recognize it as a NON-touch screen PC rather than a phone or tablet

**Expected behavior**
I expect to turn on my PC and use it without interference.  I'm a student at present and I use it for a variety of operations.

**Screenshots**
I don't have screenshots at this time because these actually occur before I'm on the PC - as it's a Windows 10 load up issue, but if I receive any messages about touch screen items going forward I will take a screenshot via print screen or Jing Screencast

**Desktop (please complete the following information):**
 - OS: Windows 10 v1909 64-bit
 - Browser MS Edge, Google Chrome, Opera, Netscape Navigator, Firefox
 - Version 1909

**Additional context**
I have sent this issue to Microsoft probably 5-6 times already over the couple years I've had Windows 10 64-bit, but have never seen a change, received any acknowledgment or seen this issue resolved.  I hope to see the ability of MS Windows to automatically recognize a standard NON-touch screen PC or at the very least some way to provide that identification to the system so that it stops asking me to require impossible security measures.  Thank you so much.

**Comment by rootsmusic** [comment]
@CrystalDawn625 Please ask product support.
#please-close
