### ISSUE TITLE
Broken design on "OneCore.lib umbrella library (by module)" page

### ISSUE THREAD

**Issue by ArmsOfSorrow** [MicrosoftDocs/feedback#2823]
Visible in section: [APIs from api-ms-win-core-com-l1-1-1.dll](https://docs.microsoft.com/en-us/windows/win32/apiindex/umbrella-lib-onecore#apis-from-api-ms-win-core-com-l1-1-1dll)

![umbrellalibpage](https://user-images.githubusercontent.com/5157010/83770548-7c9edf00-a681-11ea-9b42-c5194522d88c.png)

I'm not quite sure what is at fault here, but items from **CoImpersonateClient** are not part of the HTML table. I took a quick look at the [markdown](https://github.com/MicrosoftDocs/win32/blob/docs/desktop-src/apiindex/umbrella-lib-onecore.md), but didn't notice something immediately suspicious.

**Comment by rootsmusic** [comment]
Fixed.
#please-close
