### ISSUE TITLE
Unescaped meta tag content breaking the HTML

### ISSUE THREAD

**Issue by aptwebapps** [MicrosoftDocs/feedback#2829]
**Describe the bug**
The description meta tag's content is not escaped and is creating invalid HTML

**To Reproduce**
1. Go to https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.bindableobject?view=xamarin-forms
2. See meta content along with garbage tag close displayed at top of page

**Expected behavior**
Meta tag content should not be HTML

**Screenshots**
![broken_meta_tag](https://user-images.githubusercontent.com/195165/83967834-a1de5800-a8e2-11ea-84fb-795a61c83597.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Firefox
 - Version: 77

**Smartphone (please complete the following information):**
Untested

**Additional context**
None

**Comment by gewarren** [comment]
This issue was moved to xamarin/Xamarin.Forms-api-docs#203
