### ISSUE TITLE
Incorrect Update Classification names

### ISSUE THREAD

**Issue by bjoernf73** [MicrosoftDocs/feedback#2830]
**Describe the bug**
About "https://docs.microsoft.com/en-us/archive/blogs/dubaisec/windows-update-categories". 
Being a documentation about Update Classifications, the correct names of the update classifications should be used. Instead of "referencing" an update classification by the term "Security Update", which is programmatically unusable and ultimately incorrect, the programmatically correct name "Security Updates" should be used. This is true for almost all update classifications "referenced" in the article. 

**To Reproduce**
1. Go to 'https://docs.microsoft.com/en-us/archive/blogs/dubaisec/windows-update-categories'
2. Read. 

**Expected behavior**
I expected the article to be somewhat correct. 

**Additional context**
This is not in any way nit-picky: the article is useless to an audience writing code, but somewhat useful for an audience seeking "understanding of concept". There is no reason not to target both. This is a key concept in writing useful documentation: never "reference" items by "almost-correct-but-nevertheless-incorrect-names" - always "name" items by their programmatically correct names. That way, audiences unite. World peace? Maybe not. Anyway. Please make an effort to understand the value of this.

**Comment by mlottner** [comment]
@bjoernf73 Thanks for taking the time to leave us site feedback on Docs. 
Unfortunately, as you may have noticed, the content you have referenced is ARCHIVED and therefore unavailable for either fixes or improvements. Make sure to use currently supported products and docs to get the most up-to-date and accurate Microsoft content available. 
I'm closing this issue for now as that content can't be updated, but feel free to continue to comment here as needed. Appreciate your contribution to our community and resources!
