### ISSUE TITLE
WM_RBUTTONUP message

### ISSUE THREAD

**Issue by 1821454893q** [MicrosoftDocs/feedback#2831]
**Describe the bug**
Value | Meaning

MK_CONTROL0x0008 | The CTRL key is down.
MK_LBUTTON0x0001 | The left mouse button is down.
MK_MBUTTON0x0010 | The middle mouse button is down.
MK_RBUTTON0x0002 | The SHIFT key is down.
MK_XBUTTON10x0020 | The first X button is down.
MK_XBUTTON20x0040 | The second X button is down.

**To Reproduce**
MK_RBUTTON0x0002 | The right key is down.

**Comment by mlottner** [comment]
@1821454893q Thanks for taking the time to leave us site feedback on Docs. 
To get the specific product help you need, use the [product support site](https://support.microsoft.com/allproducts) for all of our products. 
I'm closing this site feedback issue in the meantime, feel free to continue to comment here as needed.
