### ISSUE TITLE
Now Playing: Science

### ISSUE THREAD

**Issue by Keith1953** [MicrosoftDocs/feedback#2832]
The video does not load or play. It's dead!

**Comment by mlottner** [comment]
@Keith1953 Thanks for taking the time to leave us site feedback on Docs. Unfortunately, without giving us a page link, it is impossible to know what page you came from or need us to fix. In the future, look for the feedback link at the bottom of the specific page with the issue and report the issue to us there. 
I'm closing this specific issue for now, but feel free to continue to comment here as needed. 
Appreciate your contribution to our community!
