### ISSUE TITLE
Overcomplicating Examples

### ISSUE THREAD

**Issue by Naveenpisher** [MicrosoftDocs/feedback#2834]
Hi MS Team, The String method examples were really complicated, In future make simple example like readable and understandable by everyone. Most of the things in the document were understandable by expirienced ppl only i believe.

**Comment by mlottner** [comment]
@Naveenpisher Thanks for taking the time to give us your feedback. 
In the future, make sure to leave your comments on a specific page of documentation, so we can route your feedback to the correct team for improvement. 
I've posted your request and we'll do our best to make improvements in future documentation releases. 
Closing this issue for now, but feel free to continue commenting here as needed.
