### ISSUE TITLE
I get lost

### ISSUE THREAD

**Issue by pmarcantonio** [MicrosoftDocs/feedback#2835]
I am attempting to learn C sharp and Xanarin, as I follow YOUR build an App documents, I see and understand  what the Microsoft document is saying, but when I go past a chapter or two, the additional code generated by Visual Studio is not explained. such as the project Notes
I have not idea what
async void OnSaveButtonClicked(object sender, EventArgs e)
I have no idea what these are or how to view the content of object sender, EventArgs  or e.

Maybe you can suggest the best method for me to learn

pvmarcantonio@msn.com

**Comment by gewarren** [comment]
This issue was moved to MicrosoftDocs/xamarin-docs#2933
