### ISSUE TITLE
Tutorial / example for stream/byte array for object detection

### ISSUE THREAD

**Issue by hvilppu** [MicrosoftDocs/feedback#2837]
I have really difficulties to convert this great tutorial:
https://docs.microsoft.com/fi-fi/dotnet/machine-learning/tutorials/object-detection-onnx
To consume streams or byte arrays like it uses files from file system now.
Think it is possible via InMemoryImageData?

It is not easy task to convert because "scoring", model.Transform, etc needs filesystem.

So it would be great to step by step tutorial for streams/byte arrays.

Because think this is very common use case and I even think it is possible.

**Comment by gewarren** [comment]
This issue was moved to dotnet/docs#18991
