### ISSUE TITLE
vs do not link ucrt.lib when dllmain exist

### ISSUE THREAD

**Issue by Confucius-Pei** [MicrosoftDocs/feedback#2839]
**Describe the bug**
vs do not link ucrt.lib when dllmain exist.
upgrade from 2010 to vs2017,find link error when dllmain exsits.
![image](https://user-images.githubusercontent.com/5771318/84115917-6f0e9e00-aa61-11ea-8fae-ab964980b1e3.png)

**Expected behavior**
no link error

**Screenshots**
without dllmain,the link output:
![image](https://user-images.githubusercontent.com/5771318/84115823-49819480-aa61-11ea-9e38-3b2eda1b822b.png)
with dllmain,the link output(ucrt.lib is not serached, no pass 2 ):
![image](https://user-images.githubusercontent.com/5771318/84115996-982f2e80-aa61-11ea-9a6f-35782a294c42.png)

**Desktop (please complete the following information):**
 - OS:wn10

**Smartphone (please complete the following information):**

**Additional context**

**Comment by rootsmusic** [comment]
@Confucius-Pei Please ask product support or in support forums at https://visualstudio.microsoft.com/vs/support/
#please-close
