### ISSUE TITLE
Missing blog

### ISSUE THREAD

**Issue by MIJ75** [MicrosoftDocs/feedback#2844]
I'm looking for an article in the "applicationproxyblog" blog,  here is the link:

https://docs.microsoft.com/en-us/archive/blogs/applicationproxyblog/hardware-load-balancer-health-checks-and-web-application-proxy-ad-fs-2012-r2

The link was working some weeks ago, but now the applicationproxy blog is missing.

Is it possible to get back this article?

Thanks

**Comment by rootsmusic** [comment]
Closed in mentioned issue.
#please-close
