### ISSUE TITLE
after logon to technet i get some error msg

### ISSUE THREAD

**Issue by Computer24HR** [MicrosoftDocs/feedback#2845]
Hello, 
i try to logon my account (it's not be use the last year) to technet forums
https://social.technet.microsoft.com/forums/en-us/home

after i try to type my user & password i get some error msg: "The resource you are looking for has been removed, had its name changed, or is temporarily unavailable."

anyone can know how to fix it ?

**Comment by rootsmusic** [comment]
@Computer24HR TechNet forums have closed at https://docs.microsoft.com/en-us/teamblog/msdn-technet-english-forums-closure
