### ISSUE TITLE
System.Windows.Forms DrawBorder Documentation Anomaly

### ISSUE THREAD

**Issue by nick1941** [MicrosoftDocs/feedback#2847]
In the documentation for System.Windows.Forms DrawBorder (https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.controlpaint.drawborder?view=netcore-3.1#System_Windows_Forms_ControlPaint_DrawBorder_System_Drawing_Graphics_System_Drawing_Rectangle_System_Drawing_Color_System_Int32_System_Windows_Forms_ButtonBorderStyle_System_Drawing_Color_System_Int32_System_Windows_Forms_ButtonBorderStyle_System_Drawing_Color_System_Int32_System_Windows_Forms_ButtonBorderStyle_System_Drawing_Color_System_Int32_System_Windows_Forms_ButtonBorderStyle_), the examples shown are for DrawBorder3D(), not DrawBorder().

**Comment by gewarren** [comment]
This issue was moved to dotnet/dotnet-api-docs#4402
