### ISSUE TITLE
page header is not correct 

### ISSUE THREAD

**Issue by behroozbc** [MicrosoftDocs/feedback#2848]
**Describe the bug**
page dont show correct 
**To Reproduce**
1. Search in search engine HasUnevenRows
2. open page of ms docs 
3. See error

**Expected behavior**
show correct like other page

**Screenshots**
![image](https://user-images.githubusercontent.com/20381616/84319654-9bbbd600-ab85-11ea-8743-4ad1b42d2672.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Microsoft edge
 - Version 83

**Comment by gewarren** [comment]
This issue was moved to xamarin/Xamarin.Forms-api-docs#202
