### ISSUE TITLE
No payout received

### ISSUE THREAD

**Issue by SgtGrumbles3rd** [MicrosoftDocs/feedback#2849]
I was sent an email from Microsoft Partner Center on 5/14 that I would be receiving a 63USD payout to my seller account. I have my paypal linked, I have completed all forms. Why have I not received a payment yet?

**Comment by JasonWHowell** [comment]
Hi @SgtGrumbles3rd 

Sorry for the trouble. We can't discuss specific payment issues in a public forum. 

Please use partner support to start a request about your payment at this URL https://partner.microsoft.com/dashboard/support/servicerequests

Thanks, Jason

**Comment by JasonWHowell** [comment]
#please-close
