### ISSUE TITLE
Typo in realease notes

### ISSUE THREAD

**Issue by msivia** [MicrosoftDocs/feedback#2852]
Typo in [Visual Studio 2019 version 16.6 Release Notes](https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes#16.6.2)

Typo in [IntelliSense shows that "tilde-slash" (~/) points to ASP .NET Core 3.1 project root **instread** of wwwroot subfolder after upgrading Visual Studio Enterprise 16.5.6->16.6.0](https://developercommunity.visualstudio.com/content/problem/1043674/intellisense-shows-tha-tilda-points-to-asp-net-cor.html)

**Comment by gewarren** [comment]
This issue was moved to MicrosoftDocs/visualstudio-docs#5494
