### ISSUE TITLE
Incorrect text displayed back to users

### ISSUE THREAD

**Issue by mniem** [MicrosoftDocs/feedback#2853]
Issue is on [this ](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.websites.models.site.clientaffinityenabled?view=azure-dotnet) page.

Gets or sets **&lt;**code**&gt**;true&lt;/code&gt; to enable client affinity; &lt;code&gt;false&lt;/code&gt; to stop sending session affinity cookies, which route client requests in the same session to the same instance. Default is &lt;code&gt;true&lt;/code&gt;.

**Comment by gewarren** [comment]
This issue was moved to Azure/azure-docs-sdk-dotnet#1200
