### ISSUE TITLE
Search results in wrong language

### ISSUE THREAD

**Issue by KFlowerz** [MicrosoftDocs/feedback#2854]
**Describe the bug**
When adding the search term "iot edge" to the Filter by title textbox and searching by all documents.  Search results are displayed in Japanese.  Eventhough, the selected language in the page is English (United States)

**To Reproduce**
1. Go to https://docs.microsoft.com/en-us/previous-versions/azure/digital-twins/tutorial-facilities-setup
2.  Add a search term in: Filter by title: iot edge
3. Select Search for "iot edge" in all documentation
![image](https://user-images.githubusercontent.com/20801651/84457071-53ed8b00-ac27-11ea-9f7d-8adce3c416e1.png)
4. Search results are displayed in Japanese
![image](https://user-images.githubusercontent.com/20801651/84457108-6c5da580-ac27-11ea-9d83-f38fa43b4140.png)

**Expected behavior**
I expected to see results on the language selected on the page (English- United States) or in the OS language (Spanish- Mexico)

**Screenshots**

**Laptop(please complete the following information):**
 - OS: Windows 10
 - Browser - Edge version  83.0.478.45 64 bits
                 - Google Chrome 83.0.4103.97 64 bits

**Additional context**
iot edge and iot edge module gives results in Japanese
This behavior does not match the results when serching on this page: https://docs.microsoft.com/en-us/azure/?product=featured
on the Search filter

**Comment by rootsmusic** [comment]
@KFlowerz I see English (language set in my browser) at https://docs.microsoft.com/en-us/search/?dataSource=previousVersions&terms=iot%20edge

**Comment by KFlowerz** [comment]
Seems the issue was corrected.  👍  Thanks
