### ISSUE TITLE
[MS-DTYP] GUID--RPC IDL representation  -- copied a typo from C706

### ISSUE THREAD

**Issue by blu-base** [MicrosoftDocs/feedback#2855]
The docs on a specific [GUID](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-dtyp/49e490b8-f972-45d6-a3a4-99f924998d97) representation according to [C706](https://publications.opengroup.org/c706) standard contains an error, which is a typo in the C706 standard.

Currently [MS-DTYP] for the respective GUID defines:

```
 typedef struct _GUID {
   unsigned long Data1;
   unsigned short Data2;
   unsigned short Data3;
   byte Data4[8];
 } GUID,
   UUID,
  *PGUID;
```

Reviewing C706, p. 654, table A-1 reads:

![Screenshot_20200612_125204](https://user-images.githubusercontent.com/42077282/84495543-9f497d00-acab-11ea-87ae-923afa2e208c.png)

Here time_low is stated to be unsigned long, just as the [MS-DTYP] GUID--RPC IDL representation.

However, the standard also says the GUID is 128bits long, respectively 16 octets. Moreover, the third column says time_low are the octets at position 0-3. So the field **time_low is actually a unsigned int** (4bytes). This is also in accordance with the [RFC 4122](https://tools.ietf.org/html/rfc4122#section-4.1.2), and all other GUID implementations: [1](https://docs.microsoft.com/en-us/dotnet/api/system.guid), [2](https://docs.microsoft.com/en-us/uwp/api/windows.foundation.metadata.guidattribute)

In C706, page 657, section A.2.5, also states the time_low field is 32bits wide.
Moreover, page 660, section A.4, also explicitly states a width of 32bit for time_low.

### Conclusion

Therefore, i conclude, although the C706 spec states unsigned long... it actually means unsigned int.
Which leads to my proposal to correct the width of Data1 in the _GUID struct to unsigned int.

Additional location with this error: [guiddef.h](https://docs.microsoft.com/en-us/windows/win32/api/guiddef/ns-guiddef-guid)

**Comment by KalleOlaviNiemitalo** [comment]
> Therefore, i conclude, although the C706 spec states unsigned long... it actually means unsigned int.

In C706, the column header says "NDR Data Type", not "C Data Type". Does NDR define an `unsigned int` data type? AFAIK, its integer types are `small`, `short`, `long`, `hyper`, and `unsigned` variants of those.

**Comment by blu-base** [comment]
You are absolutely right, it does define them:
![Screenshot_20200620_102856](https://user-images.githubusercontent.com/42077282/85197404-0afd9c80-b2e1-11ea-8353-43f7256d18b2.png)

So... it's not a typo.

Following up on my misassumption,
I noticed, that MS-DTYP explicitly defines the [unsigned long to be 32-bit](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-dtyp/32862b84-f6e6-40f9-85ca-c4faf985b822). I did not study that part before. This means again, the [GUID](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-dtyp/49e490b8-f972-45d6-a3a4-99f924998d97) page is indeed correctly specified.

This leaves only the [guiddef.h](https://docs.microsoft.com/en-us/windows/win32/api/guiddef/ns-guiddef-guid) which states a C++ snippet and has the size of a c-type unsigned long, which is likely incorrect. Though, i have no idea whether the win32 api has much use left.


i'd propose to close this issue.

**Comment by blu-base** [comment]
The guiddef.h source up to winsdk10, seems to be fallen in same trap i did, because the GUID struct is given as:

```
typedef struct _GUID {
    unsigned long  Data1;
    unsigned short Data2;
    unsigned short Data3;
    unsigned char  Data4[ 8 ];
} GUID;
```

I guess, this is unlikely to be changed

**Comment by KalleOlaviNiemitalo** [comment]
In the Windows API, the C `int` and `long` types are both 32-bit, even if pointers are 64-bit. This makes it more difficult to port source code between Windows and Unix-like operating systems, where `long` usually is the same size as a pointer.

If the guiddef.h header file defined `GUID` with an incorrect size according to Microsoft compilers, that would surely have been corrected decades ago.

**Comment by blu-base** [comment]
Thank you for pointing that out to me!
I did not realize the significantly different conventions.
