### ISSUE TITLE
Forms / Stream Link Concern, Connection Denied

### ISSUE THREAD

**Issue by sigalou** [MicrosoftDocs/feedback#2863]
Good morning all,

After this documentation page
https://docs.microsoft.com/fr-fr/stream/add-forms

I followed everything but there is a problem.

I created a video accessible to my entire organization, I created a form accessible to my entire organization:

![image](https://user-images.githubusercontent.com/26350534/84588947-c16a0900-ae2b-11ea-8034-461c1e1154e0.png)

I have established the link between the two but I have this result:

![image](https://user-images.githubusercontent.com/26350534/84588970-d5ae0600-ae2b-11ea-9a04-c5e2a0d4889a.png)

I can't figure out where my mistake is ?!

Can you complete the documentation?

Thank you

I asked my question here as well:
https://answers.microsoft.com/fr-fr/msoffice/forum/msoffice_sharepoint-mso_win10-mso_o365b/lien-streamforms-connexion-refus%c3%a9e/8610e5f7-24f9-484f-a89b-843236f262a0?tm=1592122814194

**Comment by rootsmusic** [comment]
@sigalou "Cet article a été traduit pour votre marché à partir de l’anglais."
#please-close
