### ISSUE TITLE
https://docs.microsoft.com/ja-jp/microsoftteams/rooms/

### ISSUE THREAD

**Issue by ykasugai** [MicrosoftDocs/feedback#2865]
Microsoft Teams Rooms is translating to Microsoft Teams ミーティング. ミーティング means it is Meeting, the localization is incorrect. Please use "Microsoft Teams Rooms" in ja-jp (Japanese Page) as is. This is URGENT.
https://docs.microsoft.com/ja-jp/microsoftteams/rooms/

**Comment by TinaMcN** [comment]
@ykasugai thank you for the feedback.
@OfficeGlobal please human translate this article and ensure "Microsoft Teams Rooms" is translated correctly.

**Comment by OfficeGlobal** [comment]
Working on a fix

**Comment by OfficeGlobal** [comment]
@ykasugai , @TinaMcN The article was HumanTranslated and published live.
However I can't change translation from "Microsoft Teams ミーティング" to "Microsoft Teams Rooms"
This is an approved translation by Microsoft

![image](https://user-images.githubusercontent.com/47977325/89503322-aa5dec80-d7c6-11ea-94a9-940843873b96.png)

**Comment by ykasugai** [comment]
Microsoft Teams Rooms is one-word as our service name. It's not Rooms using Microsoft Teams. Plus, ミーティング is incorrect as Japanese translation of Rooms. That is, we are delivering incorrect information to the customer. Please reconsider.

**Comment by TinaMcN** [comment]
@OfficeGlobal please open a request for the linguistic experts to review the feedback from @ykasugai.  The approved term may need to be revised.

**Comment by TinaMcN** [comment]
@ykasugai fyi your feedback has been shared with the linguistic experts who will make a decision on the approved term.

**Comment by OfficeGlobal** [comment]
@ykasugai we received a feedback from linguistic expert. The "Microsoft Teams Rooms" was reverted back to ENG and republished at live page

**Comment by ykasugai** [comment]
Confirmed. Thanks!

**Comment by TinaMcN** [comment]
@ykasugai thank you for confirming and many thanks for highlighting this issue.   Can you please close this issue?

**Comment by ykasugai** [comment]
thanks all (*'▽'*)
