### ISSUE TITLE
Portmon compatibility

### ISSUE THREAD

**Issue by PeterMortensen** [MicrosoftDocs/feedback#287]
https://docs.microsoft.com/en-us/sysinternals/downloads/portmon fails to mention on which newer versions of Windows it works, including the bitness of the operating system (e.g. not working on Windows 7 64-bit and Windows 10 64-bit, but working on Windows 7 32-bit, etc. - I am not sure which of these are correct).

It should explicitly list where it works and where it doesn't. A table would be fine.

It seems like the information has not been updated since 2012, and as a result a lot of users end up beeing very frustrated.

E.g. ref.: https://superuser.com/questions/927948/portmon-portmsys-sys-not-found/927969#927969

**Comment by Powerhelmsman** [comment]
@v-kents Can you take a look at the user's feedback?

**Comment by Powerhelmsman** [comment]
@markrussinovich and @lukekim Any update?

**Comment by Powerhelmsman** [comment]
Sent email to @markrussinovich and @lukekim to follow up

**Comment by Powerhelmsman** [comment]
@PeterMortensen Your issue is transferred to sysinternal team. They will help you there. I will close as transferred. If you have other question related to this issue, we can reopen it and continue discussion.
