### ISSUE TITLE
Redirect after login takes me to docs homepage rather than the page I was originally looking for

### ISSUE THREAD

**Issue by noellelc** [MicrosoftDocs/feedback#2870]
**Describe the bug**
Occasionally, I am prompted to log in when I click on a link that sends me to a documentation. When I log in (particularly if I want to switch accounts), after the login is successful, I am never taken to the original page I was trying to reach--instead, I am redirected to the docs homepage.

**To Reproduce**
1. Search for something that could be found on a docs page. Go to any docs page. (I'm not sure what logic initiates the prompt to log in)
2. Click on 'Continue'
3. Realize you're not on the page you were trying to get to

**Expected behavior**
After logging in, I would like to be sent to the page I was originally trying to reach.

**Screenshots**
too late

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge
 - Version 83.0.478.54

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by rootsmusic** [comment]
@noellelc Is this issue still happening in the latest browser?

**Comment by noellelc** [comment]
I haven't noticed it recently!
