### ISSUE TITLE
Thread Ripper Support (Windows server support) deadline by 2021

### ISSUE THREAD

**Issue by simonyee** [MicrosoftDocs/feedback#2871]
Hi,
You make frustrated with how you develop the windows operating system because MS only care for Intel processor?
Stop saying 'wintel'
and say 'winamd'

Development soon for support for Thread Ripper.

Don't want to use INTEL Corp Junk.

All the bells and Whistle for AMD Threadripper Speed and power.
and no cheap tricks

**Comment by rootsmusic** [comment]
#please-close
