### ISSUE TITLE
Wrong language in example

### ISSUE THREAD

**Issue by Savadoras** [MicrosoftDocs/feedback#2875]
https://docs.microsoft.com/en-us/exchange/client-developer/exchange-web-services/how-to-work-with-folders-by-using-ews-in-exchange#get-a-folder-hierarchy-by-using-the-ews-managed-api

C# code marked as XML

**Comment by mairaw** [comment]
Thanks @Savadoras. I've opened a PR to fix this https://github.com/MicrosoftDocs/office-developer-exchange-docs/pull/95

**Comment by rootsmusic** [comment]
Fixed.
#please-close
