### ISSUE TITLE
Link to Privacy Statement not rendered properly

### ISSUE THREAD

**Issue by andreasbenzing** [MicrosoftDocs/feedback#2876]
**Describe the bug**
The settings page shows 

> I would like information, tips, and offers about the Microsoft Docs site and other Microsoft products and services. <a href="https://go.microsoft.com/fwlink/?LinkId=521839">Privacy Statement.</a>

**To Reproduce**
1. Go to 'Profile -> Settings'
2. Scroll down to 'Manage email preferences'
3. See error

**Expected behavior**
Link is rendered as link instead of HTML source.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Chrome
 - Version 83

**Comment by rootsmusic** [comment]
Fixed at https://privacy.microsoft.com/en-us/privacystatement
#please-close
