### ISSUE TITLE
EnumerateDirectories(String, SearchOption) - Error in example

### ISSUE THREAD

**Issue by DSivtsov** [MicrosoftDocs/feedback#2879]
**Describe the bug**
In Example description of **EnumerateDirectories(String, SearchOption)** wrote
> The following example, starting from a specified directory, uses this method and the EnumerateFiles method to enumerate the files and directories within the start directory and display details of any files over 10 MB in size.

The current code
```
                    // Display each file over 10 MB;
                    if (fi.Length > 10000000)
                    {
                        Console.WriteLine($"{fi.FullName}\t\t{fi.Length.ToString("NO")}");
                    }
```
**fi.Length.ToString("NO")** - Doesn't have any correspondence to description, because it will show only NO for every file over 10 MB in size.

**Expected behavior**
The most simple variant is replace **fi.Length.ToString("NO")** on to **fi.Length**  and change description to 

> and **display size** of any files over 10 MB in size.

**Link To article**
[DirectoryInfo.EnumerateDirectories Method](https://docs.microsoft.com/en-us/dotnet/api/system.io.directoryinfo.enumeratedirectories?view=netframework-4.7.2)

**Comment by gewarren** [comment]
This issue was moved to dotnet/dotnet-api-docs#4524
