### ISSUE TITLE
Improve .NET API Browser search for methods on generic types.

### ISSUE THREAD

**Issue by ericmutta** [MicrosoftDocs/feedback#288]
The [API Browser](https://docs.microsoft.com/en-us/dotnet/api/index?view=netstandard-2.0) is really handy when looking up specific methods.

You can search for methods in non-generic types like [File.Delete](https://docs.microsoft.com/en-us/dotnet/api/index?view=netstandard-2.0&term=File.Delete) or [Stream.Close](https://docs.microsoft.com/en-us/dotnet/api/index?view=netstandard-2.0&term=Stream.Close) and it brings the results as expected.

However for methods on a generic type like [`List<T>`](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.list-1?view=netstandard-2.0) the search function shows no results. Example: [List.Add](https://docs.microsoft.com/en-us/dotnet/api/index?view=netstandard-2.0&term=List.Add) **doesn't work**, nor does [`List<>.Add`](https://docs.microsoft.com/en-us/dotnet/api/index?view=netstandard-2.0&term=List%3C%3E.Add). You have to write out the type parameters in full, e.g: [`List<T>.Add`](https://docs.microsoft.com/en-us/dotnet/api/index?view=netstandard-2.0&term=List%3CT%3E.Add) does work (also note that the syntax is biased to C# and the VB syntax [`List(Of T).Add`](https://docs.microsoft.com/en-us/dotnet/api/index?view=netstandard-2.0&term=List(Of%20T).Add) **doesn't work**).

Writing out the type parameters isn't too much of a hassle for types with just one type parameter like `List<T>` but it is a hassle for types like Dictionary where you have to write them out using the exact names. E.g: [`Dictionary<K,V>.Add`](https://docs.microsoft.com/en-us/dotnet/api/index?view=netstandard-2.0&term=Dictionary%3CK%2CV%3E.Add) **doesn't work**, it has be [`Dictionary<TKey,TValue>.Add`](https://docs.microsoft.com/en-us/dotnet/api/index?view=netstandard-2.0&term=Dictionary%3CTKey%2CTValue%3E.Add). If you add a space after the comma and write [`Dictionary<TKey, TValue>.Add`](https://docs.microsoft.com/en-us/dotnet/api/index?view=netstandard-2.0&term=Dictionary%3CTKey%2C%20TValue%3E.Add) it **doesn't work**.

Suggestion: make the search more flexible so that any of these forms will work:

1. `TypeName.MethodName` (where `TypeName` may be a generic type).
2. `TypeName<>.MethodName` or `TypeName(Of ).MethodName`
3. `TypeName<T>.MethodName` or `TypeName(Of T).MethodName`
4. `TypeName<,>.MethodName` (where `TypeName` is expected to have two type parameters).
5. `TypeName<K,V>.MethodName`  (where type parameter names `K` and `V` may not match definition).
6. `TypeName<K, V>.MethodName` (like above but space after comma should not matter).

If you had to do just one, I would ask for the first one: it should be possible to type `TypeName.MemberName` and get results regardless of whether `TypeName` has type parameters :+1:

**Comment by Powerhelmsman** [comment]
@dend Can you work on this suggestion?

**Comment by keziamicro** [comment]
Hello - reviewing and cleaning up some older feedback/issues. Thanks!
