### ISSUE TITLE
Visual Studio 2019 > Publish > "Advanced Precompile Settings" - Help page end at "Unable to Service Request"

### ISSUE THREAD

**Issue by jsnelders** [MicrosoftDocs/feedback#2883]
**Describe the bug**
Trying to view the help page in the "Advanced Precompile Settings" dialogue of Visual Studio 2019 Community (Version 16.6.2) and it leads to an "Unable to Service Request" page.

**To Reproduce**
1. Publish an ASP.NET MVC Framework 4.7.2 page to Azure ("Deploy your app to a folder, IIS, Azure or other destination" profile) [Screenshot 1].
2. In the "Publish" screen, under the "Summary" section, select the pen icon beside "Configuration"  [Screenshot 2].
3. In the "Publish dialogue that opens select "File Publish Options" to expand the options.
4. Select "Configure" beside the second option ("Precompile during publishing").
5. In the "Advanced Precompile Settings" dialogue select the question mark ("?") in the title bar side the close "X" symbol  [Screenshot 3].
6. This seems to initially open a web page at the url "https://msdn.microsoft.com/query/dev16.query?appId=Dev16IDEF1&l=EN-US&k=k(WebApplicationProjects.PublishDlg);k(TargetFrameworkMoniker-.NETFramework,Version%3Dv4.7.2)&rd=true" but finally ends at the page "https://msdn.microsoft.com/Areas/Epx/Content/500.aspx?aspxerrorpath=/query/dev16.query" which with the title "Unable to Service Request"  [Screenshot 4].

**Expected behavior**
I see the documentation I'm expecting

**Screenshots**

Screenshot 1:
![image](https://user-images.githubusercontent.com/8957095/85239340-9ceade00-b476-11ea-9e32-3061656431a6.png)

Screenshot 2:
![image](https://user-images.githubusercontent.com/8957095/85239348-a411ec00-b476-11ea-8f02-98c638cd3a65.png)

Screenshot 3:
![image](https://user-images.githubusercontent.com/8957095/85239352-a83e0980-b476-11ea-8058-ac0b297314ae.png)

Screenshot 4:
![image](https://user-images.githubusercontent.com/8957095/85239356-b0964480-b476-11ea-93ee-ee4da4d44eec.png)

**Desktop (please complete the following information):**
 - Windows 10

**Smartphone (please complete the following information):**
N/A

**Additional context**

**Comment by gewarren** [comment]
This issue was moved to MicrosoftDocs/visualstudio-docs#5593

**Comment by WilliamAntonRohm** [comment]
@jsnelders -- Jason, thank you for your feedback.  Can you provide a docs.microsoft.com article URL to help us chase down this issue?

cc @ghogen for awareness

**Comment by ghogen** [comment]
@WilliamAntonRohm - there's no need here for any further information. The problem is that no docs.microsoft.com topic appeared when one should have appeared.  We either need to change the product to no longer have a ? icon for Help in that dialog, or else create a page for this.

**Comment by WilliamAntonRohm** [comment]
@ghogen -- thank you for clarifying.  To whom should I assign this issue?

**Comment by ghogen** [comment]
We already created an issue for this in our VS repo, so no need to reopen this or assign it.

**Comment by ghogen** [comment]
This issue is now being tracked at 
https://github.com/MicrosoftDocs/visualstudio-docs/issues/5593

**Comment by jsnelders** [comment]
> @jsnelders -- Jason, thank you for your feedback. Can you provide a docs.microsoft.com article URL to help us chase down this issue?
> 
> cc @ghogen for awareness

Sorry, I don't know what docs.microsoft.com URL would be required. All the information I have was provided in the original bug.

**Comment by WilliamAntonRohm** [comment]
@jsnelders -- Jason, thank you for your followup.  This issue is now being tracked here:
- https://github.com/MicrosoftDocs/visualstudio-docs/issues/5593
