### ISSUE TITLE
Release notes for VS 16.5 have 404 error

### ISSUE THREAD

**Issue by ike2016** [MicrosoftDocs/feedback#2884]
**Describe the bug**
Missing page. Noticed [here](https://docs.microsoft.com/en-us/visualstudio/releases/2019/history#installing-an-earlier-release)

**To Reproduce**
1. Go to https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes-v16.5

**Expected behavior**
Proper release notes.

**Comment by gewarren** [comment]
This issue was moved to MicrosoftDocs/visualstudio-docs#5592
