### ISSUE TITLE
Endpoint doesn't exist

### ISSUE THREAD

**Issue by cccs-cat001** [MicrosoftDocs/feedback#2885]
**Describe the bug**
The docs [here](https://docs.microsoft.com/en-us/previous-versions/azure/ad/graph/api/users-operations#get-a-users-thumbnail-photo--) say that if I go to `/thumbnailPhoto` I'll get the photo, but when I do I get 
```
{
    "odata.error": {
        "code": "Request_ResourceNotFound",
        "message": {
            "lang": "en",
            "value": "Resource 'thumbnailPhoto' does not exist or one of its queried reference-property objects are not present."
        },
        "requestId": "93ab54e6-71bc-41f6-af06-b59fb81d9e0d",
        "date": "2020-06-22T13:07:50"
    }
}
```

**To Reproduce**
1. Try to access the /thumbnailPhoto endpoint as stated in the docs

**Expected behavior**
Well I'd expect to either get a thumbnail or for that endpoint to not exist. 

**Desktop (please complete the following information):**
 - OS: centos 7
 - Browser: Firefox
 - Version: 68.60esr

**Comment by rootsmusic** [comment]
@cccs-cat001 "We're no longer updating this content regularly."
#please-close
