### ISSUE TITLE
Permanently archive the TechNet Gallery similarly to CodePlex

### ISSUE THREAD

**Issue by joshieecs** [MicrosoftDocs/feedback#2891]
https://gallery.technet.microsoft.com/

There are over 18 thousand scripts in the TechNet Gallery, with experienced archivers estimating **41 Million** combined total downloads of all scripts and utilities.

I understand wanting to get authors to migrate to GitHub, and I understand wanting to move away from a service originally intended "legacy" technologies like Windows Script Host and VBScript. 

But the TechNet Gallery also contains many modern and functional PowerShell scripts. It remains by far the most comprehensive collection of Windows IT-related code that exists, and alternatives like the excellent [PowerShell Gallery](https://www.powershellgallery.com/) or GitHub-oriented resources like [Awesome PowerShell](https://github.com/janikvonrotz/awesome-powershell) are simply not of the size and scope to fill the void that will be left when the TechNet Gallery goes dark.

As it relates to the MicrosoftDocs project: Some of the best resources for certain topics are still old blog posts [like Dr. Scripto](https://devblogs.microsoft.com/scripting/use-powershell-to-interact-with-the-windows-api-part-3/), _**which have been archived** and migrated_ to docs.microsoft.com as part of the transition. Many of these archived blogs **_link to the TechNet Gallery_** for the example code described in the article. The Gallery should be archived to keep these "docs" healthy as possible, and not full of dead links. They still turn up frequently in web search results.

Some [projects](https://gallery.technet.microsoft.com/SRx-Core-SharePoint-Search-d60113e9) have been published by Microsoft teams to the Gallery (with Microsoft-signed scripts) as recently as mid-2019 as a primary source -- there is no alternative source for these. Will these projects migrate to GitHub? 

How will users locate the new homes for scripts that do migrate, when their TechNet Gallery bookmarks start returning a 404?

When Microsoft shut down CodePlex, it understood the value of keeping the code publicly available [as an archive](https://archive.codeplex.com/). The same is true for projects that were hosted on the now-retired [Google code](https://code.google.com/archive/). 

If the docs.microsoft.com project isn't willing or able to keep the TechNet Gallery around in an archived state like CodePlex, it should consider contributing the data to an organization like the Internet Archive to preserve this unique piece of computer history in a collection.

It would be a travesty to lose all the code hosted on TechNet Gallery, and I hope Microsoft will find some alternative to simply pulling the plug. Not only would that be a blow to the Windows IT ecosystem, but Microsoft should also consider it's commitment to open source: most code hosted in the TechNet Gallery is MIT licensed. By taking TechNet Gallery offline, Microsoft will be responsible for the deaths of thousands of open source programs written for its signature platforms, PowerShell and .NET.

**Comment by fredster33** [comment]
For anyone coming from a search engine, currently Microsoft has all of their TechNet gallery software here: https://github.com/MicrosoftArchive

Many software developers also have archived the Gallery on Internet Archive (Wayback Machine), or moved their software to GitHub.

**Comment by rootsmusic** [comment]
TechNet Gallery has closed at https://docs.microsoft.com/en-us/teamblog/technet-gallery-retirement
