### ISSUE TITLE
Internal Link Missing

### ISSUE THREAD

**Issue by wonderboy703** [MicrosoftDocs/feedback#2895]
Pretty sure this is still a relevant document.. 

https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/how-to-set-up-a-multifunction-device-or-application-to-send-email-using-office-3

**Comment by mairaw** [comment]
Duplicate of https://github.com/MicrosoftDocs/OfficeDocs-Exchange/issues/2079
