### ISSUE TITLE
Documentation examples for C# shows VB code

### ISSUE THREAD

**Issue by duvel3** [MicrosoftDocs/feedback#2896]
**Describe the bug**
The documentation of dotnet Doubles always shows VB code examples. According to the documentationfile, C# examples should be available:
```
:::code language="csharp" source="~/samples/snippets/csharp/VS_Snippets_CLR_System/system.double.equals/cs/equalsoverl.cs" interactive="try-dotnet" id="Snippet2":::
 :::code language="vb" source="~/samples/snippets/visualbasic/VS_Snippets_CLR_System/system.double.equals/vb/equalsoverl.vb" id="Snippet2":::
```

This is also the case in [https://docs.microsoft.com/en-us/dotnet/api/system.double.tryparse?view=netcore-3.1](https://docs.microsoft.com/en-us/dotnet/api/system.double.tryparse), and maybe many more.

**To Reproduce**
1. Go to [https://docs.microsoft.com/en-us/dotnet/api/system.double.equals?view=netframework-4.5.2](https://docs.microsoft.com/en-us/dotnet/api/system.double.equals?view=netframework-4.5.2)
Be sure to select a other language than VB, this also happens with other frameworks.

**Expected behavior**
As of other documentation I would expect C# examples instead of VB.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 2004
 - Browser Chromium based Microsoft Edge
 - Version 84.0.522.20

**Comment by mairaw** [comment]
This was fixed today. Thanks for reporting @duvel3!

/cc @rloutlaw
