### ISSUE TITLE
Unescaped meta tag hides left nav on Windows Virtual Destkop (WVD) Powershell module pages

### ISSUE THREAD

**Issue by lintFan** [MicrosoftDocs/feedback#2897]
**Describe the bug**
The left navigation bar is hidden, also a copy of the description summary is at the very top of the page ending with " />, for example on [Add-RdsAccount](https://docs.microsoft.com/en-us/powershell/module/windowsvirtualdesktop/Add-RdsAccount?view=windows-virtual-desktop-1.0.0-preview) the top of the page has:
```
The Add-RdsAccount cmdlet adds an authenticated account to use for Windows Virtual Desktop cmdlet requests. Upon completion, the context is automatically set to use the "Default Tenant Group" as the tenant group name. You can run the Set-RdsContext cmdlet to change the context.
" />

```
**To Reproduce**
1. Go to https://docs.microsoft.com/en-us/powershell/module/windowsvirtualdesktop/?view=windows-virtual-desktop-1.0.0-preview
2. Click on any cmdlet name, such as Add-RdsAccount https://docs.microsoft.com/en-us/powershell/module/windowsvirtualdesktop/Add-RdsAccount?view=windows-virtual-desktop-1.0.0-preview
3. See the bug as described above

**Expected behavior**
The left navigation should display and the copy of the description summary is at the very top

**Screenshots**
![image](https://user-images.githubusercontent.com/29842134/85628991-eaf21400-b625-11ea-9d36-fcc63f4d2529.png)

**Desktop (please complete the following information):**
Reproduces on these browsers all on Windows 10 Version 1909
- Microsoft Edge 83.0.478.56 (Official build) (64-bit)
- Microsoft Edge 84.0.522.20 (Official build) beta (64-bit)
- Internet Explorer 11 version 11.900.18362.0

**Comment by lintFan** [comment]
This seems to be the same problem described in #2829  which was closed and moved to  [xamarin/Xamarin.Forms-api-docs#203](https://github.com/xamarin/Xamarin.Forms-api-docs/issues/203), except that this isn't under the xamarin docs.

**Comment by lintFan** [comment]
@samhouts this seems to have the same symptoms as [xamarin/Xamarin.Forms-api-docs#197](https://github.com/xamarin/Xamarin.Forms-api-docs/issues/197) that you just fixed. Do you know who this should be assigned to?

**Comment by samhouts** [comment]
@lintFan The issue was with the site template. Triggering a new build should resolve it.

**Comment by lintFan** [comment]
Looks like it is fixed now.
