### ISSUE TITLE
"SFP" is a typo

### ISSUE THREAD

**Issue by iidx** [MicrosoftDocs/feedback#2898]
**Link to article**:
- https://docs.microsoft.com/ko-kr/microsoft-365/security/office-365-security/set-up-spf-in-office-365-to-help-prevent-spoofing?view=o365-worldwide#to-add-or-update-your-spf-txt-record

**Problem**:
The first item's sentence contains a typo. abbreviation for Sender Policy Framework is **SPF**, not **SFP**.
- Original
"Ensure that you're familiar with the SFP syntax in the following table."
- Suggestion
"Ensure that you're familiar with the SPF syntax in the following table."

**Comment by mairaw** [comment]
Thanks @iidx for your comment. I've opened a PR to fix this: https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2282

**Comment by mairaw** [comment]
This is fixed. Thanks!
