### ISSUE TITLE
Windows 10 2004 edition isn't my hardware readiness issue, it's your capability issue

### ISSUE THREAD

**Issue by kellyfirkins** [MicrosoftDocs/feedback#2902]
**Describe the bug**
Microsoft Windows 10 "Windows Update" says that it's waiting for my hardware to be ready... please ask your marketing group to put down their bong pipes. I mean really? Immutable hardware cannot be set in stone such that software is waiting for it to be ready... it's immutable. Maybe marketing team(s?) need to understand technology and the tech team should educate them. (no joking there... marketing needs to understand technology even a bit... 'cause now, they are clueless... 

**To Reproduce**
1. Marketing group stops smoking their pipes and puts down their bongs
2. Marketing group realizes that my hardware is fixed and won't change, but your software can and probably will...
3. Marketing group will realize that it's Windows that needs to adapt, not my relatively standard hardware... Shy of an AMD Ryzen CPU, I have a boring-ass PC. Again time and perhaps better filtering at hiring levels?

**Expected behavior**
Marketing group opens their eyes

**Desktop (please complete the following information):**
 - OS: Windows 10 waiting on 2004 so I can do containerization work and UNIX scripting... not that Marketing cares. 
 - Browser: NA
 - Version: <very negative comment retracted regarding Marketing and version>

**Additional context**
No problem except that I'm waiting on scripting to the point that I may as well buy a mac for the *nix portions. And you can quote me on that to marketing... I'm going to look at other offerings.  

Cheers,
Kelly

PS. I feel I can joke 'cause I was a software architect who started a medical software company and ended up in DevOps then we were acquired before I could automate the whole process... something which Marketing people just fail to understand...

**Comment by rootsmusic** [comment]
@kellyfirkins Microsoft Docs is not involved with marketing.
#please-close
