### ISSUE TITLE
Australia East Availability Zone not shown on map at https://azure.microsoft.com/en-us/global-infrastructure/regions/

### ISSUE THREAD

**Issue by ConcreteGannet** [MicrosoftDocs/feedback#2908]
**Describe the bug**
According to https://docs.microsoft.com/en-au/azure/availability-zones/az-region, the Australia East region has availability zones, but that is not shown on the map at https://azure.microsoft.com/en-us/global-infrastructure/regions/

**Comment by rphoon** [comment]
The documentation mentions that Availability Zone is available in Au East but provisioning of VMs still do not work. Can you please provide an ETA of when it will be GA?

**Comment by ConcreteGannet** [comment]
Now fixed on the new page at https://azure.microsoft.com/en-au/global-infrastructure/geographies/
