### ISSUE TITLE
Kinect 2.0 content broken/missing with "Error  Sorry, this page is unavailable. Please try again later."

### ISSUE THREAD

**Issue by diablodale** [MicrosoftDocs/feedback#2909]
Kinect content is broken/missing on many links. Below I list several.
I recommend a tester use a web crawler to automate the testing of live content to find all the problems.
This is related to issue #1214

### Setup

* Windows 10 x64 build 19041.329
* Chrome 83.0.4103.116

### Repro

1. Visit https://docs.microsoft.com/en-us/previous-versions/windows/kinect/dn772957(v=ieb.10)
2. scroll down to the method `GetActivityDetectionResults`
3. Click on `GetActivityDetectionResults`

### Result

"Error  Sorry, this page is unavailable. Please try again later."
Using developer tools, I can see your server is throwing http error 500 on this page.

### Expected

Content with no error.

### More errors, and workaround

More links and the content on that page have the same errors. This following is a short list manually found:
`GetAppearanceDetectionResults`
`GetExpressionDetectionResults`
`GetJointOrientations`
`GetJoints`

As a workaround, I can click on the `Download PDF` link in the left nav, and within the PDF I *can* read the missing content.

**Comment by rootsmusic** [comment]
@diablodale Fixed at https://docs.microsoft.com/en-us/previous-versions/windows/kinect/dn791158(v=ieb.10)
#please-close

**Comment by diablodale** [comment]
Thanks and verified. All the links on that page work now. I also samples a set of the matching left nav links for this content and they also work.
