### ISSUE TITLE
No information about modification date or history on pages

### ISSUE THREAD

**Issue by JoniLoponen** [MicrosoftDocs/feedback#292]
# Idea Title

Pages should include at least date for last modification. It is hard to know if there has been any modifications if such date is not shown.

## Issue Details

For example page https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/extensibility/extensibility-requests has been modified after it was created. Now it is not shown anywhere on the page. It is more important to know when the page has been modified than the created date. Only the last modification date tells if the page is up to date.

An improvement to this would be possibilty to see modification history so it would be easy to see what has been modified.

**Comment by Powerhelmsman** [comment]
@JoniLoponen Do you see Edit button on the right top corner? Click it and will point you to GitHub repo. there, you can see the history and what has been modified. 
![image](https://user-images.githubusercontent.com/33136632/38508677-b20c9e94-3bd4-11e8-93f7-fd2826782aab.png)

![image](https://user-images.githubusercontent.com/33136632/38508710-c61493ba-3bd4-11e8-8125-02ecf2244017.png)
Let me know if it solves your issue.

**Comment by JoniLoponen** [comment]
@Powerhelmsman Thanks. That helped to see the history through edit, but that was not very intuitive way to get the information.

Anyway would it be possible to get the latest modification date to be shown on the page too? I think showing the created date for page does not have any information value. E.g. some page may be created 10 years ago but knowing that does not tell anything if the page is up to date with changes introduced 1 month ago.

**Comment by Powerhelmsman** [comment]
@ShevaDas Can you work on this part to see if we can add the latest update date on the page?

**Comment by JoniLoponen** [comment]
Ok. Can you check what is the issue with the page I gave as example?

There are many similar pages where an important part of the page has changed but date was not updated.

**Comment by dend** [comment]
@JoniLoponen looking at the reference page, it says it was updated at the very top on 4/10. We will make sure to be more diligent about tracking updated dates, so if you see any specific pages that have had a major overhaul but did not have the updated date modified, please let us know and we will make sure to address that as soon as possible.
