### ISSUE TITLE
QnA forums moderation

### ISSUE THREAD

**Issue by DSPatrick** [MicrosoftDocs/feedback#2920]
**Describe the solution you'd like**
Please sort the **Spam** tab descending so we don't have to page and scroll to bottom to check for new incoming on every visit.
https://docs.microsoft.com/en-us/answers/moderation/index.html?tab=akismet

**Comment by JasonWHowell** [comment]
@saldana do you have a place to track these ideas?

**Comment by rootsmusic** [comment]
> @saldana do you have a place to track these ideas?

Feedback at https://docs.microsoft.com/en-us/answers/content/idea/list.html

**Comment by JasonWHowell** [comment]
@DSPatrick please track your great idea there in the main list. 
https://docs.microsoft.com/en-us/answers/content/idea/list.html

**Comment by JasonWHowell** [comment]
#please-close
