### ISSUE TITLE
Spelling mistake 

### ISSUE THREAD

**Issue by lowkeyboard** [MicrosoftDocs/feedback#2921]
**Describe the bug**
There is a spelling mistake on the official website. 

**To Reproduce**
1. Go to https://docs.microsoft.com/en-gb/samples/microsoft/microsoftteamshealthcarebotapplication/update-this-to-unique-url-stub/
4. See the "Microsift" . 

**Expected behavior**
I suppose it was meant to be "Microsoft".
**Screenshots**

![Adsız](https://user-images.githubusercontent.com/46297574/86611985-1971d680-bfb8-11ea-9e60-41abbde49aae.jpg)

**Comment by rootsmusic** [comment]
@lowkeyboard Your link is not found.

**Comment by gewarren** [comment]
It looks like the sample was deleted, so I'm closing this issue.
