### ISSUE TITLE
Typo in /security/research/project-freta/how-to-capture-an-image

### ISSUE THREAD

**Issue by Sorakurai** [MicrosoftDocs/feedback#2924]
**Describe the bug**
There's a typo in the first paragraph

From a forensics perspective, the less impact made to the running system while snapshotting memory, the better. Best case scenario is to obtain a memory dump from a virtualized machine, in which the host takes a memory dump of a guest without the guest (and any malware running on it) **beging** able to detect it and without any modification to the RAM or file contents. Less ideal are memory dumps of a running system taken from within the system, since this requires code to the run (and potentially the output to be stored) on the machine itself, which modifies the system state and potentially overwrites evidence.

**To Reproduce**
1. Go to 'https://docs.microsoft.com/en-us/security/research/project-freta/how-to-capture-an-image'

**Comment by JasonWHowell** [comment]
This has been fixed by someone. Thanks for the keen eyes!
![image](https://user-images.githubusercontent.com/5067358/87991326-c9f0d780-ca9a-11ea-83aa-87e392c7bdd9.png)
#please-close
