### ISSUE TITLE
API browser search bar does not work with type simple names

### ISSUE THREAD

**Issue by cdmihai** [MicrosoftDocs/feedback#293]
Repro:
1. Go to the API browser: https://docs.microsoft.com/en-us/dotnet/api/system.object?view=netframework-4.7.2
2. In the leftmost search bar right below the target framework moniker, write any type by simple name (e.g. `Task`)

Expected: the page for the searched type is found, like: https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.task?view=netframework-4.7.2
Actual: no search results

If the point of that search bar is search for something else other than Types / Namespaces / Type Members, then UI is misleading, since I have no idea what that search bar is for.

Browser: Chrome 65.0.3325.181

**Comment by Powerhelmsman** [comment]
@mairaw Can you take a look at this?

**Comment by mairaw** [comment]
@Sampy is working on that now.

**Comment by Sampy** [comment]
When we roll out a new version of the .NET documentation, there is a bit of a lag before the API Browser picks it up. This means that you can't find items in the new version (netframework-4.7.2) until they are indexed.

This lag is now passed and I can confirm that you are able to find these items now.

Thank you for reporting this as well as your enthusiasm for our new version of .NET!

**Comment by mairaw** [comment]
Thank you @Sampy!

**Comment by Powerhelmsman** [comment]
@cdmihai Can you verify?

**Comment by cdmihai** [comment]
Yes it works now. :)

Unrelated: Searching for `Task` puts the class as the 7th result. It would be nice if classes took precedence over namespaces and members
