### ISSUE TITLE
Confusing 'In this article' ToC behavior

### ISSUE THREAD

**Issue by guardrex** [MicrosoftDocs/feedback#2931]
**Describe the bug**

When landing in an article at a bookmark, the **In this article** ToC often indicates a different section than the bookmarked section ... it indicates the section in the middle of the screen. This is understandable but confusing behavior.

**To Reproduce**

Navigate to a page with a bookmark to a short section, such as ...

https://docs.microsoft.com/aspnet/core/blazor/webassembly-performance-best-practices#avoid-javascript-interop-to-marshal-data

... which is to the *Avoid JavaScript interop to marshal data* section of the *ASP.NET Core Blazor WebAssembly performance best practices* article in the ASP.NET Core docs.

**Expected behavior**

I would expect the *In this article* ToC to reflect the requested section: *Avoid JavaScript interop to marshal data*.

However, the *In this article* ToC actually indicates the section in the middle of the scrolled page: *Use System.Text.Json*.

**Screenshots**

<img width="1280" alt="Capture" src="https://user-images.githubusercontent.com/1622880/87101956-0e1be680-c216-11ea-9d72-8676e44eaed3.PNG">

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: All (Tested in Firefox and Edge)

**Comment by JasonWHowell** [comment]
@pranavkm in case you have an idea what's causing it. Could be something to do with the code block formatting, but it's not super apparently.

**Comment by guardrex** [comment]
Pranav works on the ASP.NET Core engineering team, so I don't think he'll be able to help.

This might be best for the DocFX team because the behavior of that sidebar ToC might be more DocFX-based.

I have a few minutes right now before wrapping up for the day. I'll run a test here and see if I can determine if this is a general DocFX behavior.

**Comment by guardrex** [comment]
Looks like it's buried in the site's theme ...

https://docs.microsoft.com/_themes/docs.theme/master/en-us/_themes/scripts/55f6956b.index-docs.js

I don't see the behavior (or the code) with OOB DocFx (unthemed).

**Comment by JasonWHowell** [comment]
If its a corner case and doesn't happen much, I don't know that it's worth too much time investigating. I haven't seen this on many pages. Have you seen other examples?

**Comment by guardrex** [comment]
It's *very* common. It happens when landing on any bookmarked short section ...

* https://docs.microsoft.com/en-us/aspnet/core/blazor/?view=aspnetcore-3.1#javascript-interop
* https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/routing?view=aspnetcore-3.1#route-to-components-from-multiple-assemblies
* https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/configuration?view=aspnetcore-3.1#authentication-configuration
* https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/logging?view=aspnetcore-3.1#blazor-webassembly

**Comment by guardrex** [comment]
I was just informed offline that there are no plans to fix this one. I don't understand that at all ... it's bizarre to me that the ToC cue doesn't match the loaded section ... very confusing. Anyway, it's a proverbial **_won't fix_** :smile:.
