### ISSUE TITLE
DAX examples

### ISSUE THREAD

**Issue by AnthonyHKOPT** [MicrosoftDocs/feedback#2932]
HI, I have problem finding the  data for practicing the examples given in the following address
https://docs.microsoft.com/en-gb/dax/filter-function-dax

Can someone offer help please ?

**Comment by JasonWHowell** [comment]
Try either the Power BI MSDN forum or the SQL Server Analysis Services forum for general DAX language questions:
- https://social.msdn.microsoft.com/Forums/sqlserver/en-us/home?forum=sqlkjpowerpivotforexcel
- https://social.msdn.microsoft.com/Forums/en-US/home?forum=sqlanalysisservices

**Comment by JasonWHowell** [comment]
#please-close
