### ISSUE TITLE
DataGridCell.IsReadOnly documentation talks about setting the property while it is readonly.

### ISSUE THREAD

**Issue by kunom** [MicrosoftDocs/feedback#2933]
https://docs.microsoft.com/en-us/dotnet/api/system.windows.controls.datagridcell.isreadonly?view=netframework-4.6.2#System_Windows_Controls_DataGridCell_IsReadOnly

**Describe the bug**
The Remarks section says: _Set the IsReadOnly property to true to make an individual cell read-only_. 

But the property is not assignable: `public bool IsReadOnly { get; }`.

So: either extend the implementation (which would be a good thing) or fix the documentation.

**Comment by gewarren** [comment]
This issue was moved to dotnet/dotnet-api-docs#4522
