### ISSUE TITLE
Error when adding a site to the site list using the [Bulk add from file]

### ISSUE THREAD

**Issue by TakumiKamada** [MicrosoftDocs/feedback#2935]
When we tried to add a site to the site list using the [Bulk add from file] accordingly to the *documentation, the error below showed up.

---
Add multiple websites to your site list
We couldn't open your list. Please check that you've only added URLs and try again.
---

We could solve this by making changings below.
"microsoft.com, bing.com, bing.com/images" -> "http://microsoft.com, http://bing.com, http://bing.com/images"

Please kindly consider revising the documentation.
Thank you very much in advance.

* https://docs.microsoft.com/en-us/internet-explorer/ie11-deploy-guide/add-multiple-sites-to-enterprise-mode-site-list-using-the-version-2-schema-and-enterprise-mode-tool

**Comment by rootsmusic** [comment]
@TakumiKamada Internet Explorer has been retired at https://techcommunity.microsoft.com/t5/windows-it-pro-blog/internet-explorer-11-desktop-app-retirement-faq/ba-p/2366549
#please-close
