### ISSUE TITLE
Search results not shown

### ISSUE THREAD

**Issue by akimusume** [MicrosoftDocs/feedback#2939]
Go to https://docs.microsoft.com/en-us/ and try to search something(or directly go to https://docs.microsoft.com/en-us/search/?category=All&terms=net). You will find that there are many results in the Filter, but it says "No results". Click the "Documentation" and click "All" in the Filter, then the results appear. Notice the difference between the urls.

I found it's difficult to insert screenshots, so no screenshots. Try it yourself.

Win 10 1909.
A brower based on Chromium 78
Edge 44

I don't think there is any relation to the client enviroment

**Comment by eersonmez** [comment]
Same issue here. Tried from my computer in Turkey and vm in the US.  So, it's doesn't seem to be geo isolated.

**Comment by perk737** [comment]
Same issue here. No matter what I search for - C# or dotnet or whatever.

**Comment by gewarren** [comment]
@akimusume I believe this has been fixed. Can you recheck? Thanks for letting us know about this problem.

**Comment by akimusume** [comment]
@gewarren  Yes, it looks normal now. Thanks.

**Comment by perk737** [comment]
OK now. Tanks.
