### ISSUE TITLE
[Suggestion] New custom Markdown extension

### ISSUE THREAD

**Issue by Youssef1313** [MicrosoftDocs/feedback#2941]
In most documentation repositories, usually there are links to other articles that are done by using the normal `[text](relative_link)` markdown syntax. The "text" part is "usually" in most cases the title of the linked article. Some times the title of an article may get updated, that will lead to changes of the link text in other files that references the updated article.

If there is a syntax to reference the article with its relative path only, and the link text shows without being explicitly written, that would be good IMO.

## Limitations

- Works only for markdown files in the same repository.

## Benefits

- Avoids unnecessary changes if a change is done to an article.

**Comment by JasonWHowell** [comment]
@meganbradley is there a good place to record this great suggestion?

**Comment by meganbradley** [comment]
@JasonWHowell you can create a Customer Suggestion here: https://ceapex.visualstudio.com/Engineering

**Comment by JasonWHowell** [comment]
@Youssef1313 I have tracked this idea internally with the right team (id https://ceapex.visualstudio.com/Engineering/_workitems/edit/270611)

In the Visual Studio Code extension called the **Docs Authoring pack**, we offer this feature at the time when the .md file link is inserted (using the command palette).

- Install: https://marketplace.visualstudio.com/items?itemName=docsmsft.docs-authoring-pack
- Works on links to files in the same repo: https://docs.microsoft.com/en-us/contribute/how-to-write-docs-auth-pack#prerequisites-and-assumptions

Example:
![image](https://user-images.githubusercontent.com/5067358/88000783-6d4de680-cab3-11ea-92b4-df0a87173926.png)

![image](https://user-images.githubusercontent.com/5067358/88000808-79d23f00-cab3-11ea-9bd6-c120a99994d3.png)

![image](https://user-images.githubusercontent.com/5067358/88000845-8c4c7880-cab3-11ea-9228-8f3a96cb5295.png)


Thanks! 
#please-close
