### ISSUE TITLE
Include links to implementation on GitHub

### ISSUE THREAD

**Issue by chriskuech** [MicrosoftDocs/feedback#2947]
**Is your feature request related to a problem? Please describe.**
There are many cases where documentation is insufficient to solve a problem, either because of ambiguity or because of bugs.  In these scenarios, we have to look at the source code of the framework on GitHub.  For people unfamiliar with the source code, this can take significant time to figure out, yet is an issue I face a few times every month.

**Describe the solution you'd like**
A clear link/button from a class documentation page to the class's source file on GitHub.

**Describe alternatives you've considered**
N/A.

**Additional context**
N/A.

**Comment by gewarren** [comment]
@mimisasouvanh Here's another request to link from reference docs to the source code.

**Comment by gewarren** [comment]
This is already requested in #233. Looks like a lot of people would appreciate this feature.

**Comment by gewarren** [comment]
Great news - the core .NET libraries now have links to source code!
Example: https://learn.microsoft.com/dotnet/api/system.string.chars?view=net-8.0
