### ISSUE TITLE
Sql Management studio design issue

### ISSUE THREAD

**Issue by arjunsingh123** [MicrosoftDocs/feedback#2949]
Sql Management studio design issue
![sqlmanagement](https://user-images.githubusercontent.com/24517845/87509001-39775900-c68e-11ea-948b-3c6f0356872f.JPG)

**Comment by JasonWHowell** [comment]
@arjunsingh123 can you please clarify what is the problem in the design you pointed out in the screenshot?

Thanks, Jason CC: @markingmyname

**Comment by JasonWHowell** [comment]
@arjunsingh123 we haven't heard back with clarification, so we'll close the issue for now. #please-close
