### ISSUE TITLE
Prematurely removed KB articles

### ISSUE THREAD

**Issue by cheong00** [MicrosoftDocs/feedback#295]
# Prematurely removed KB articles

Not sure if this is the right place to suggest it. Forgive me if this is not a correct place for this issue.

In recent KB article cleanup, KB articles related to "out of support" systems such as WinXP or Win2003 are removed. However there are some KB articles that is still relevant to current Windows version got removed too.

It'd be better if there were a way to "revive" the still-relevant KB articles, and possibly updates the "APPLIES TO" section so it won't be accidentally removed in the future .

## Issue Details

Please refer to [this link](https://social.msdn.microsoft.com/Forums/en-US/f43f4c0e-72f5-43df-aced-723fb07d3e1e/disappeared-kb-articles?forum=suggest) for the discussion on this topic.

**Comment by dend** [comment]
@cheong00 is this related to the removal of the KB article from support.microsoft.com?

**Comment by cheong00** [comment]
Sorry for keep you waiting.

Yes. I'm talking about those KB articles in support.microsoft.com .

**Comment by Powerhelmsman** [comment]
@Jemash Do you have any plan to migrate support.microsoft.com?

**Comment by Powerhelmsman** [comment]
@cheong00 Thanks for your suggestion. Unfortunately, we don't have plan to migrate the support.microsoft.com KB article. As they discussed in linked thread, KB is different document and will stay in support.microsoft.com so far.
