### ISSUE TITLE
Please improve content structure (e.g. headings ranking) to be more distinctive 

### ISSUE THREAD

**Issue by Rick-Anderson** [MicrosoftDocs/feedback#2953]
Moved from https://github.com/dotnet/AspNetCore.Docs/issues/19230 created by @SetTrend 

The ranking of headings in Microsoft Docs very often isn't clear.
<img alt="" align="right" src="https://user-images.githubusercontent.com/9283914/87696415-0c5f9f00-c791-11ea-9d9a-88fa0ef82ac1.png">Reading the docs I often tend to find myself lost in the jungle of: "What does this piece information belong to? What does it pertain to? Where am I?".

### See this sample (from Document Details below)

![MS Docs - 1](https://user-images.githubusercontent.com/9283914/87696770-93ad1280-c791-11ea-9a11-57e916df4cf9.png)

_(I removed much of the paragraph content to give a better overview of the headings I'm referring to.)_

### Here I highlighted all the headings to better demonstrate what I'm referring to

![MS Docs - 2](https://user-images.githubusercontent.com/9283914/87696927-cf47dc80-c791-11ea-90e3-595d78c6a7de.png)
<br/>

From the above example you can see that in the above section there is no meaningful heading ranking whatsoever:

- Why are `macOS` and `Linux` smaller than `Windows`?
   Are they a sub-section of `Windows`?
- Why is `Set the environment in code` next to `Windows`?
   Is `Set the environment in code` a novel OS?
- Why is `Command prompt` and `PowerShell` next to `web.config`?
   They are just two flavors of the same thing and, thus, should be grouped one level down.
<br/>

In the screenshots above I removed much of the text to give a better overview. Yet, reading through the actual text you quickly get lost and forget why you're reading a piece of information anyway. Most importantly: You wouldn't even recall where in particular you found a piece of information trying to figure it out at a daily meeting the other day.

The above is only an example. Misleading formatting can be found at many places in the documentation.
<br/>

Please revise your pages and [improve structure](https://www.userfocus.co.uk/articles/usermanuals.html#Anchor-How-11481).

- https://www.userfocus.co.uk/articles/usermanuals.html#Anchor-How-11481
- https://developers.google.com/tech-writing/one/lists-and-tables#keep_list_items_parallel

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ceffa6a2-770c-1cd9-5145-dcd423f9dd22
* Version Independent ID: 1cb5eb30-dd84-e5e1-5826-d74243fabf04
* Content: [Use multiple environments in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/environments?view=aspnetcore-3.1#development)
* Content Source: [aspnetcore/fundamentals/environments.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/environments.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
The default view makes it obvious where you're at:

![image](https://user-images.githubusercontent.com/3605364/87709663-4c4a6600-c740-11ea-8413-6c65f0f63178.png)

Other questions left at the original issue

**Comment by SetTrend** [comment]
I'm not refering to the page title. I'm refering to where you are in regard to the narrative/cognitive context within approx. 700 lines of code.
