### ISSUE TITLE
OWIN OAuth 2.0 Authorization Server Download the sample code link broken

### ISSUE THREAD

**Issue by chanmmn** [MicrosoftDocs/feedback#2956]
The page.
https://docs.microsoft.com/en-us/aspnet/aspnet/overview/owin-and-katana/owin-oauth-20-authorization-server
The Download the sample code link
https://code.msdn.microsoft.com/OWIN-OAuth-20-Authorization-ba2b8783/file/114932/1/AuthorizationServer.zip

The link is broken.

**Comment by JasonWHowell** [comment]
@hongyes  @Praburaj @Rick-Anderson  are the authors of the page, in case they know of a good replacement link.

**Comment by Rick-Anderson** [comment]
Moved to https://github.com/dotnet/AspNetDocs/issues/415
Please close this issue.

**Comment by JasonWHowell** [comment]
#please-close
