### ISSUE TITLE
[PowerShell Experience] Add RBAC information

### ISSUE THREAD

**Issue by dend** [MicrosoftDocs/feedback#296]
👨‍💻 _Customer Request_

# [PowerShell Experience] Add RBAC information

No RBAC permission information is listed under PowerShell documentation.

## Issue Details

I can’t find this in the docs. Here is an example of the documentation for [Get-AzureRmDatabase](https://docs.microsoft.com/en-us/powershell/module/azurerm.sql/get-azurermsqldatabase?view=azurermps-5.7.0&viewFallbackFrom=azurermps-5.6.0). At least there is no connection between the role permission and the SDK documentations. When I go to the [AAD RBAC documentation for the role called SQL DB Contributor](https://docs.microsoft.com/en-us/azure/role-based-access-control/built-in-roles#sql-db-contributor) I can read the overview of the permissions included in this role. I find that the level of detail is too shallow and I can’t dive deeper. What does `Microsoft.Sql/servers/databases/*` fully entail?

**Comment by Powerhelmsman** [comment]
@log-suggestion @EdisonDa

**Comment by Powerhelmsman** [comment]
#log-suggestion @EdisonDa

**Comment by botcrane** [comment]
🚀 **ATTENTION**: [Internal request](https://ceapex.visualstudio.com/web/wi.aspx?pcguid=7d644393-99ad-41c8-ac53-7fa79294c720&id=23010) logged.

**Comment by EdisonDa** [comment]
Could you please kindly let me know if this resolve your question?

**Comment by Powerhelmsman** [comment]
@dend Who's user? Can you represent him/her to see if this issue is resolved?

**Comment by dend** [comment]
@EdisonDa thanks for the clarification, we should be able to close this issue now.
