### ISSUE TITLE
DFS Cmdlet Docs for Win10/Server2016 include links to outdated docs

### ISSUE THREAD

**Issue by the-m4a** [MicrosoftDocs/feedback#2960]
**Describe the bug**
Various articles covering the PowerShell DFS Cmdlets for Windows 10 and Server 2016 include a link to "Overview of DFS Namespaces", which redirects to the version applying to 2008 R2, 2012, and 2012 R2: 
Link from page: http://technet.microsoft.com/library/cc730736
Technet redirects to: https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/cc730736(v=ws.11)?redirectedfrom=MSDN

Further, that 2008R2/2012/2012R2 page includes a link to "Recommended Version", which redirects the user to https://docs.microsoft.com/windows-server/windows-server

Obviously a less than ideal experience.  I would expect that both the link from the Cmdlet articles and the "Recommended Version" point to: https://docs.microsoft.com/en-us/windows-server/storage/dfs-namespaces/dfs-overview

**To Reproduce**
1. Go to https://docs.microsoft.com/en-us/powershell/module/dfsn/get-dfsnaccess?view=win10-ps
2. Click on 'Overview of DFS Namespaces' in the Description section
3. Note redirect to the "Overview of DFS Namespaces" article applying to Windows Server 2008 R2, Windows Server 2012, Windows Server 2012 R2.
3. Click "Recommended Version" in the banner that appears at the top of the page.
4. Note redirect to the root Windows Server Documentation page (https://docs.microsoft.com/en-us/windows-server/)

**Expected behavior**
When clicking on "Overview of DFS Namespaces in step 2 above, the link followed is https://docs.microsoft.com/en-us/windows-server/storage/dfs-namespaces/dfs-overview

When clicking on "Recommended Version" in step 3 above, the link followed is https://docs.microsoft.com/en-us/windows-server/storage/dfs-namespaces/dfs-overview

**Screenshots**
N/A for simple web redirects

**Desktop (please complete the following information):**
Windows 10, Edge Chromium

**Additional context**
Applies to multiple pages in the DFSN Cmdlet documentation

**Comment by rootsmusic** [comment]
@the-m4a "We're no longer updating this content regularly."
#please-close
