### ISSUE TITLE
Issue with sandbox

### ISSUE THREAD

**Issue by Fazer01** [MicrosoftDocs/feedback#2967]
**Describe the bug**
When I want to start a sandbox the following text appears: _"Your appeal has been received. Appeals are reviewed on a first-come, first-served basis, and may take several days to process. If your appeal is approved, you will regain access to sandboxes and other interactive learning resources.
For more information, please check the troubleshooting guidance page."_

Actually, I never clicked on a button "Appeal" so I have never sent any appeal whatsoever. I also haven't received any response of Microsoft whatsoever. I recently have finished the AZ-900 course which I succesfully concluded on June 1st 2020. Prior to that exam I took the Azure Fundamentals Learning Path where I have used several sandboxes. This worked very nice and okay for me. 
After a few days (after June 1st) I wanted to move along with AZ-204 and to prep myself well, I took the course: _"https://docs.microsoft.com/en-us/learn/modules/create-serverless-logic-with-azure-functions/3-create-an-azure-functions-app-in-the-azure-portal?pivots=javascript"_

After a few days I tried again to enter the sandbox but without any success. I decided to wait until I received a mail from Microsoft explaining this issue. I still haven't received any response from Microsoft whatsoever and I'm starting to get frustrated. 
This is why I'm starting this issue. 

Thanks in advance to look after this issue and respond within a respectable time-frame. 

Regards, 

Tom

**Steps To Reproduce**
I logged in with my microsoft account on which I also took the AZ-900 exam (concluded succesfully) and took the Azure Fundamentals Learning path (for which I have used sandboxes also with success). And navigate to the link in the "description" above and tried starting a sandbox but without any success and also the same text appears on the screen as I also described in the "description" above.

**Expected behavior**
Able to access the sandbox mode with my account.

**Screenshots**
![Microsoft-error](https://user-images.githubusercontent.com/37348010/88222738-abd7d280-cc66-11ea-9190-32991a2b7b2a.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser Chrome (I have also cleared cache, tried Edge, tried FireFox) without success.

**Comment by sadadow** [comment]
Hi @Fazer01 ,

Thanks for raising this issue to us. We have gone ahead and sent your issue to the appropriate team.

Are you now able to access the sandbox again?

**Comment by Fazer01** [comment]
Hi @sadadow ,
Thanks for replying and firwarding the issue to the team. I will let you kniw tomorrow if I am able to access the sandbox again. 

Regards, 
Tom

**Comment by Fazer01** [comment]
> Hi @Fazer01 ,
> 
> Thanks for raising this issue to us. We have gone ahead and sent your issue to the appropriate team.
> 
> Are you now able to access the sandbox again?

I am still not able to access the sandbox. The same error occurrs: 
![image](https://user-images.githubusercontent.com/37348010/89410312-c9577280-d723-11ea-8ec9-8c56078afd70.png)

**Comment by Fazer01** [comment]
Hi @sadadow , 

Any news on this issue?

**Comment by Fazer01** [comment]
I would like to inform that this issue is resolved recently. Issue can be closed!
