### ISSUE TITLE
SQL Server is not capable of sorting Integer JSON Fields

### ISSUE THREAD

**Issue by flash0077** [MicrosoftDocs/feedback#2968]
There exists a column : field_values which contains json data.
The json fields datatype are as as follows: 
name : STRING
id : Integer
quality : STRING

If applied sorting based on "id" then Postgres query provides correct resultset as below,you can see the id sorted correctly
EG:Entries are ordered=>0,1,2,3,4,5,6,7,8,9,10,11........
![PGResult](https://user-images.githubusercontent.com/42997255/88261693-6823ae00-cce4-11ea-8fab-af8c5639bd8c.png)

But when tried the same via SQL Query,then result set is fetched  with respect to "id" field,"id" is treated as text hence resultset obtained is not accurate.
 EG:Entries are ordered as =>0,1,10,11,12,13.......

![SQLResult1](https://user-images.githubusercontent.com/42997255/88269319-6dd3c080-ccf1-11ea-82d4-6758b4988725.png)

It would be very beneficial to get this enhancement on work as I could not find any other alternatives too.
Sometimes JSON Data can be dynamic hence casting into a type is not an option.

Just as Postgres does it,can SQL do it?

Software Details as below:

SQL Server Management Studio						15.0.18131.0
Microsoft Analysis Services Client Tools						15.0.1347.0
Microsoft MSXML						3.0 6.0 
Microsoft Internet Explorer						9.11.17134.0
Microsoft .NET Framework						4.0.30319.42000

**Comment by rootsmusic** [comment]
@flash0077 Please ask product support or in support forums.
#please-close
