### ISSUE TITLE
[PowerShell/CLI Experience] Link to REST APIs called from PowerShell Azure docs

### ISSUE THREAD

**Issue by dend** [MicrosoftDocs/feedback#297]
👨‍💻 _Customer Request_

# [PowerShell/CLI Experience] Link to REST APIs called from PowerShell Azure docs

Be as descriptive as you can with your idea/bug report/question/suggestion.

## Issue Details

Let’s say I’m using PowerShell. If I read about a cmdlet in the docs it should list the REST API methods called and link over to them. Similarly CLI and SDK documentation would do the same. (As we all know the REST API is always called no matter what code or script is called from.) What then follows it that all documentation always points back to REST in case someone wants to read the lower level details. The REST documentation would then become a GREAT place to put information about permissions required to execute said REST API call!

**Comment by Powerhelmsman** [comment]
#log-suggestion @EdisonDa

**Comment by botcrane** [comment]
🚀 **ATTENTION**: [Internal request](https://ceapex.visualstudio.com/web/wi.aspx?pcguid=7d644393-99ad-41c8-ac53-7fa79294c720&id=23008) logged.

**Comment by EdisonDa** [comment]
@dend could you please provide the contact info for this customer? Or you can share more information for what's asking? Each Azure CLI/PowerShell command should have a link for corresponding REST API in our docs?
