### ISSUE TITLE
Questionable links

### ISSUE THREAD

**Issue by ll3v3ll** [MicrosoftDocs/feedback#2973]
The URL docs.microsoft.com/en-us/archive/blogs/jimoneil/http-301-this-is-no-longer-the-blog-you-were-looking-for contains URL links/directs to questionable site (maybe it was okay at the time).

**Comment by gewarren** [comment]
@ll3v3ll Thank you for letting us know! I've asked the appropriate team to remove that page/link.

**Comment by gewarren** [comment]
The page has been taken down. Thanks again for alerting us!
