### ISSUE TITLE
unable to "add account" for profile at http://techprofile.microsoft.com

### ISSUE THREAD

**Issue by rootsmusic** [MicrosoftDocs/feedback#2979]
I'm unsuccessful at adding another account for [my profile](http://techprofile.microsoft.com).

1. Go to http://techprofile.microsoft.com
2. Log into profile.
3. Click on "settings".
4. Scroll down to "Account Management".
5. Click on "add account".
6. Log into account that I want to add.

**Expected behavior**
My profile's settings should show that another account has been successfully added.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 78.0.2

**Comment by Borrelworst** [comment]
Experiencing same issue: When logging in to the second account so it can be added, it just switches to that other account, but does not link the accounts.

**Comment by rootsmusic** [comment]
Try again @Borrelworst, I just successfully linked my profiles.
