### ISSUE TITLE
Attributes missing - (such as SerializableAttribute)

### ISSUE THREAD

**Issue by cnichols1977** [MicrosoftDocs/feedback#298]
# Attributes missing - (such as SerializableAttribute)

Missing Attribute information that is shown in old documentation in the Syntax section at the top.

## Issue Details

**OLD**
https://msdn.microsoft.com/en-us/library/b3h38hb0(v=vs.110).aspx

`<SerializableAttribute>
Public Structure Nullable(Of T As Structure)
`

**New**
https://docs.microsoft.com/en-us/dotnet/api/system.nullable-1?view=netframework-4.7.1

`Public Structure Nullable(Of T)`

**Comment by Powerhelmsman** [comment]
@mairaw Can you take a look at this request?

**Comment by mairaw** [comment]
@dend @joelmartinez can you guys take a look? It seems like an mdoc issue.

I don't see that attribute in the [source XML](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System/Nullable%601.xml) and Serializable is not one of the attributes that we're [filtering out](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/_filter.xml).

**Comment by joelmartinez** [comment]
@mairaw yes, I will review this and see what's up

**Comment by Powerhelmsman** [comment]
@dend Any update?

**Comment by joelmartinez** [comment]
For the sake of completeness ... are there any other .NET attributes that are missing? I've identified the cause, and a fix slated for the next release to add `Serializable`, but if there are more I'd like to address them all at the same time :)

**Comment by dend** [comment]
@joelmartinez `Serializable` is a starter and probably one of the most important ones 😄

**Comment by riverar** [comment]
???

I provided an example earlier, all those attributes are missing values.

**Comment by joelmartinez** [comment]
@riverar apologies for the confusion ... I meant for .NET classes. As @dend mentioned, UWP uses a different pipeline, so the instance value fixes will come from a different source. I work on mdoc (ie. the .NET pipeline), so that's what I was referring to 😄

**Comment by riverar** [comment]
@joelmartinez Got it. Let me hunt around for some more real quick.

**Comment by riverar** [comment]
@joelmartinez 

- ClassInterface https://docs.microsoft.com/en-us/dotnet/api/accessibility.caccpropservicesclass?view=netframework-4.7.1
- InterfaceType https://docs.microsoft.com/en-us/dotnet/api/accessibility.iaccessiblehandler?view=netframework-4.7.1
- SecurityCriticalAttribute https://docs.microsoft.com/en-us/dotnet/api/microsoft.win32.safehandles.criticalhandleminusoneisinvalid?view=netframework-4.7.1
- Microsoft.SharePoint.Client.ClientCallableTypeAttribute Microsoft.SharePoint.Client.SubsetCallableTypeAttribute https://docs.microsoft.com/en-us/dotnet/api/microsoft.sharepoint.spuser?view=sharepoint-server
- ClientCallableTypeAttribute https://docs.microsoft.com/en-us/dotnet/api/microsoft.office.server.social.spsocialfeed?view=sharepoint-server
- DataContractAttribute https://docs.microsoft.com/en-us/dotnet/api/microsoft.xrm.sdk.query.querybyattribute?view=dynamics-general-ce-9
- AttributeUsageAttribute https://docs.microsoft.com/en-us/dotnet/api/microsoft.sharepoint.webpartpages.webpartstorageattribute?view=sharepoint-server

Should I file a separate bug on attribute values having incorrect syntax highlighting/colorization?
![image](https://user-images.githubusercontent.com/475132/43344690-7cb4b44a-919f-11e8-8be9-90175b03badc.png)

**Comment by riverar** [comment]
@joelmartinez Woops, let me filter this list. My language selector got set to C++.

**Comment by riverar** [comment]
@joelmartinez Shortened list above.

**Comment by dend** [comment]
Updating this - the `SerializableAttribute` and others are now being displayed, however not yet available for languages other than C#. This work is tracked in https://github.com/mono/api-doc-tools/issues/274

**Comment by riverar** [comment]
@dend Negative. My test cases above all still fail.

**Comment by mairaw** [comment]
@riverar 
I see SecurityCritical for https://docs.microsoft.com/en-us/dotnet/api/microsoft.win32.safehandles.criticalhandleminusoneisinvalid?view=netframework-4.7.1 for example or am I missing something?
![image](https://user-images.githubusercontent.com/12971179/45017737-42506b80-afdd-11e8-9172-35b16a5e9b6e.png)

**Comment by riverar** [comment]
@mairaw Oh. 😳 I checked the reference source and wasn't aware SecurityCritical had an empty constructor variant.

I looked at some other examples and everything looks good there 🎉
e.g. https://docs.microsoft.com/en-us/dotnet/api/system.security.rightsmanagement.unsignedpublishlicense?view=netframework-4.7.2

**Comment by mairaw** [comment]
I believe this can be closed given that we now have the Serializable attribute showing up. Tonight's build will also fix the issue of the Serializable attribute not working under the Attributes section.

**Comment by riverar** [comment]
Still two more attributes broken per https://github.com/MicrosoftDocs/feedback/issues/298#issuecomment-408528118

**Comment by dend** [comment]
@riverar @mairaw looks like all attributes are now rendered correctly, including the ones in https://github.com/MicrosoftDocs/feedback/issues/298#issuecomment-408528118. Thank you two for sticking through the process! 🎉

**Comment by riverar** [comment]
@dend Um. I'm not seeing that. For example, this page has a ClassInterfaceAttribute with zero parameters https://docs.microsoft.com/en-us/dotnet/api/accessibility.caccpropservicesclass?view=netframework-4.7.1

![image](https://user-images.githubusercontent.com/475132/49604429-b4b94a80-f942-11e8-8cda-008d88a1e8c5.png)

**Comment by mairaw** [comment]
That's a separate issue @riverar. Our system is not version-aware at the moment so it displays all attributes that ever existed across all versions.

@dend do we have an issue tracking that?

**Comment by riverar** [comment]
@mairaw  Are you saying ClassInterfaceAttribute had a parameter-less constructor at some point? That doesn't sound right.

**Comment by mairaw** [comment]
That's what the reflection results are saying. Let me double check with the actual assemblies.

**Comment by riverar** [comment]
Hm print media dating back to 2002 doesn't show this. Also, having two of these attributes on a single object doesn't make a lot of sense either. I guess this bug is closed but the story is still busted. We'll need to turn around and file a new bug.

**Comment by dend** [comment]
That might indeed be a separate issue - we now show the attribute, but we should check that the value for the parameter is different.

**Comment by mairaw** [comment]
@riverar this seems to be a bug with mdoc. I'll file an issue in the appropriate repo and tag you.

This is what's generating:
https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Accessibility/CAccPropServicesClass.xml#L26

This is what the source has:
https://referencesource.microsoft.com/#Accessibility/Accessibility/CAccPropServicesClass.cs,10

/cc @joelmartinez

**Comment by mairaw** [comment]
@dend and what about the version-aware attributes? This is being tracked already right?

For example: https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.safebuffer?view=netframework-4.7.2

**Comment by joelmartinez** [comment]
@mairaw Hmm, yeah … looks like for some reason the formatter is not adding the parameter on some versions of that member definition. Thanks, looking forward to the gh issue on the mdoc repo.

**Comment by dend** [comment]
@mairaw not tracked in a public forum, but that is part of the Schema-based Document Processor migration for .NET

**Comment by mairaw** [comment]
That's what I imagined. Thanks for confirming.
