### ISSUE TITLE
My progress in learning path is completely deleted.I completed almost 60% of my traning.

### ISSUE THREAD

**Issue by vikramarigelaRepo** [MicrosoftDocs/feedback#2981]
![MicrosoftLearn](https://user-images.githubusercontent.com/55822760/88715026-46129d00-d0e3-11ea-8899-001232beb0ec.PNG)

**Comment by IS20068903** [comment]
Hello, I have the same problem. It happened like an hour ago. I raised an issue ticket too.

**Comment by vikramarigelaRepo** [comment]
This issue is fixed now.Thankyou so much for a quick turn around on this.
