### ISSUE TITLE
Course progress delete...

### ISSUE THREAD

**Issue by greg-double** [MicrosoftDocs/feedback#2984]
I was in the middle of a module. When I completed the module, it didn't prompt me for an achievement. I then noticed it wasn't tracking my xp points. 

I logged out, back in. Closed all browsers and restarted. Restarted the machine. Tried different machines. Nothing. All my complted modules are set to 0% complete and completing new own's don't change the xp.

Can some one please take a look to see what happened?

**Comment by IS20068903** [comment]
Same problem here. Hopefully, they'll fix it soon. Greetings.

**Comment by riccireyes** [comment]
Same problem here. Just checked now and it seems the problem may have fixed itself. However, the total XP is not moving still.

**Comment by greg-double** [comment]
Yes, I see the same. The progress is showing correctly now, but the xp is not advancing. 

Thanks for the update.
