### ISSUE TITLE
Regarding getting TFS WorkItems using Ids 

### ISSUE THREAD

**Issue by sangam-sgm** [MicrosoftDocs/feedback#299]
Regarding getting TFS WorkItems using Ids 

I was using rest api for tfs to get workitems details by ids but when i am giving all the ids the api is turning to be very large and hence its not processing and returning internal server error message.
My concern is that can you people make this api as post request as well so that i can pass as many ids as we can.
Thanks,
Sangam

**Comment by sangam-sgm** [comment]
@Powerhelmsman   The doc link i used to get the api is https://docs.microsoft.com/en-us/rest/api/vsts/wit/work%20items/list 
In the api  GET https://{accountName}.visualstudio.com/{project}/_apis/wit/workitems?ids={ids}&api-version=4.1-preview    if i am giving lots of ids comma seperated then its failing because of url length.

Please help me out with some alternate solution

**Comment by sangam-sgm** [comment]
It will be good if api is like getting all the work item details of specific project without specifying one one ids of each work items. We are having python based addon to pull data from tfs account and index it in splunk. This i want basically for Splunk addon.

**Comment by Powerhelmsman** [comment]
@erickson-doug Can you help here?

**Comment by Powerhelmsman** [comment]
@erickson-doug Any update?

**Comment by Powerhelmsman** [comment]
Sent a email to @erickson-doug to follow up

**Comment by Powerhelmsman** [comment]
@wnjenkin @elbatk Can you help assign to the right person?

**Comment by Powerhelmsman** [comment]
@sangam-sgm Your issue is transferred to vsts-rest-api team. They will help you there. I will close as transferred. If you have other question related to this issue, we can reopen it and continue discussion.
