### ISSUE TITLE
Fix "previous-version" documentation pages

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#3]
Pages that contain "previous version" information freeze the browser due to a script executing on multiple devices and browsers. This may be due to ad-blockers or proxy rules, but it does not occur on the main Microsoft Docs pages.

I actually suspect the banner that tells you it's "Previous Versions" and nags you to look at the "recommended version" - if I succeed in closing the banner, the page becomes responsive.

From a professional point of view, the site is unusable at my place of work. We use IE, and while there are fairly restrictive proxy settings, MS sites are all permitted. I have to resort to googling the page link and looking at the Google cache. assuming my IE isn't completely locked (and why can't I kill a single tab)?

While I'm on the topic, and no matter what is causing the page lockup, please remove the nag to look at the "recommended version". A simple highlighted line to say it's an older product with link to the "current version" at the top of the page is sufficient for those who are lost. I know Server 2008 R2 is in extended support - and many of us are still supporting it.

Example page here: https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/dd379509(v=ws.10)

----------
⚠ Idea migrated from UserVoice

**Created By:** TMac
**Created On:** 2018/03/04 01:09:53 +0000
**Votes at Migration:** 1
**Supporters at Migration:** 1

**Comment by dend** [comment]
@Khairunj @DuncanmaMSFT @TaraMeyer this is the performance issue that we discussed with slow TOC load in IE.

**Comment by Jemash** [comment]
@TaraMeyer  was this fixed?

**Comment by TaraMeyer** [comment]
@Jemash  - I'm not able to repo on Chrome or Edge.  @dend @Khairunj @DuncanmaMSFT -Windows Server 2008 R2 and 2008 only contains 31,000 topics - I thought issues crept in at 100,000 +?

**Comment by dend** [comment]
@TaraMeyer this issue is still there in IE.

**Comment by dend** [comment]
@TaraMeyer any updates on this item?

**Comment by Khairunj** [comment]
@TaraMeyer any update on this? Please talk to @Jemash if you don't know what to do.

**Comment by Powerhelmsman** [comment]
@TaraMeyer @Jemash This bug hasn't been fixed for a while. Can you provide the status?

**Comment by dend** [comment]
@Jemash @TaraMeyer do you happen to have any updates on this?

**Comment by dend** [comment]
Ping @Jemash @TaraMeyer

**Comment by Powerhelmsman** [comment]
@Jemash @TaraMeyer I created a bug is sitehelp portal to track the issue. https://icm.ad.msft.net/imp/v3/incidents/details/74044499/home

**Comment by TaraMeyer** [comment]
@dend and @Powerhelmsman - can you please point me to the docs on how to resolve?   Also please be aware, I am rolling off the project as of June 29.

**Comment by TaraMeyer** [comment]
@dend , @Powerhelmsman , @Jemash - I'm blocked.  I've reached out to Zhiliang's team, but received no response over night.  Hoping to hear back next week.

**Comment by TaraMeyer** [comment]
@dend  @Powerhelmsman @Jemash latest update:  @sudeepku and @zhiliangxu have decided to postpone any feature that would help fix.  Please see TEAMS here for the specifics:
  https://teams.microsoft.com/l/message/19:8d13a17fb9874f5baa4fadea0c451a43@thread.skype/1529615221553?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=badf6ba7-296b-4795-9fdd-efb00c99c485&parentMessageId=1529615221553&teamName=MSDN%20and%20TechNet%20Library%20Migration&channelName=Library%20Migration-%20APEX%20Engineering&createdTime=1529615221553

I will assign the open LSI attached to this issue to @sudeepku to manage as my last day is Friday.  Thanks!

**Comment by dend** [comment]
@TaraMeyer @Powerhelmsman given that this is limited impact, with no immediate actions, I will close the issue.
