### ISSUE TITLE
Remove Microsoft Classoom link. Microsoft Classroom does not exist anymore.

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#30]
Under "Get Minecraft: Education Edition" and then "Prerequisites" you refer to Microsoft Classroom. Please remove it. 

----------
⚠ Idea migrated from UserVoice

**Created By:** Stina Biärsjö
**Created On:** 2018/01/31 10:23:08 +0000
**Votes at Migration:** 1
**Supporters at Migration:** 1

**Comment by dend** [comment]
This is in reference to this page:
https://docs.microsoft.com/en-us/education/windows/get-minecraft-for-education

@TrudyHa @nickbrower @brianlic-msft - can you help address this?

**Comment by dend** [comment]
Ping @TrudyHa @nickbrower @brianlic-msft

**Comment by Powerhelmsman** [comment]
This issue is transferred to windows itpro content team.
