### ISSUE TITLE
Incorrect grammatical term used in Guidelines

### ISSUE THREAD

**Issue by kalendelaney** [MicrosoftDocs/feedback#3000]
**Describe the bug**

**To Reproduce**
1. Go to https://review.docs.microsoft.com/en-us/learn-docs/docs/id-guidance-knowledge-check?branch=master
2. Look at first paragraph
  Overview
Knowledge checks can be difficult to write. Should you use True/False questions? How many answers should you have? Should you write in the **first or third person**? Writing good questions is a well-studied problem and we've summarized the most common guidelines in this document.

**Expected behavior**
It should say **second or third person**
First person is "I", "me", "we", "us". Second person is "you". Third person is "he/she/it", "they". All the other examples later on refer to not using "you" so clearly first person is not the issue

**Additional context**
Further down in the article, it says:

8. Use third person, not "you"
The use of "you" becomes too personal to the learner and distracts them.

So clearly the issue is between second and third, NOT first and third.

**Comment by JasonWHowell** [comment]
Hi Kalen! Hope you are doing well. It's been a long time since we bowled at the MVP summit a few years ago.

@HelenMiller is the listed author on that page. Maybe she can help. CC: @marktap

**Comment by HelenMiller** [comment]
Hi Kalen,
 Great catch! Thanks for taking the time to leave the feedback. I've corrected the issue.

**Comment by gewarren** [comment]
Closing.
