### ISSUE TITLE
Revoke Access in App Center

### ISSUE THREAD

**Issue by pranavi9** [MicrosoftDocs/feedback#3003]
Hi,
Few users are rolled off from our Project, I don't find search option to find the users. Adding users is easy but revoking access is difficult. HockeyApp listed all user information and it was easy to use. Please find attached screenshot, I have around 500+ users in each distribution group.

<img width="967" alt="Screen Shot 2020-08-05 at 2 24 57 PM" src="https://user-images.githubusercontent.com/26469510/89455431-f1e16b80-d727-11ea-9a4a-6014a6e5b692.png">

**Comment by rootsmusic** [comment]
@pranavi9 HockeyApp is being retired at https://devblogs.microsoft.com/appcenter/hockeyapp-is-being-retired/
#please-close
