### ISSUE TITLE
Office add-in issue in excel

### ISSUE THREAD

**Issue by Siphenathi-Nathi** [MicrosoftDocs/feedback#3004]
**Is your feature request related to a problem? Please describe.**
I cannot extend the range in excel (office add-in) using js particular react 

**Describe the solution you'd like**
I would like to know which function i can use because i cannot find any.

![Range](https://user-images.githubusercontent.com/51409045/89519637-f6b42700-d7dc-11ea-918f-aded1e46e272.JPG)

**Comment by JasonWHowell** [comment]
This is a docs forum, but your questions is about Excel. Please try asking the question here https://techcommunity.microsoft.com/t5/excel/ct-p/Excel_Cat

Maybe the javascript API would help you: https://docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-ranges#set-the-selected-range
#please-close
