### ISSUE TITLE
FIX ALL GO HELP LINKS

### ISSUE THREAD

**Issue by amommy** [MicrosoftDocs/feedback#3007]

**Comment by amommy** [comment]
It has been a long long time and still none of the error help links work ex  https://go.microsoft.com/fwlink?ProdName=Microsoft+SQL+Server&ProdVer=16.100.37971.0&EvtSrc=Microsoft.SqlServer.Management.Smo.ExceptionTemplates.FailedOperationExceptionText&EvtID=Backup+Server&LinkId=20476
All we get is redirected to the home page. Been like this for eons now. How is this not fixed?

**Comment by JasonWHowell** [comment]
@rothja this might be for someone in your team.

**Comment by rothja** [comment]
@amommy Hello! I am the manager on the SQL Server documentation team, and it looks like the forward link you're referencing is SQL Server / SMO related. Are you getting to this link from a tool / user-interface / F1 help? I'd have to investigate how these should be hooked into our docs and why it is not working. #assign:rothja

**Comment by rothja** [comment]
Adding @markingmyname as well, since it looks like this was F1 help on and SMO error. Mark is investigating F1 help links to our docs, so this might be related to his work.

**Comment by rothja** [comment]
#assign:markingmyname

**Comment by markingmyname** [comment]
@amommy 

Have you had a chance to review @rothja comment?

We would appreciate it if we could have a point of reference from where you are to where the help article is redirecting you.

Please let us know.

Thank you.

**Comment by amommy** [comment]
Sorry I just now saw the emails about this.
Links on all, if not most, SSMS help screens do not work, they just go to
homepage. I have also had the same problem in excel, not sure if all the
links or just some.

Thanks for looking into this.

**Comment by markingmyname** [comment]
Hi, @amommy 

We know that the Help/F1 experience for SSMS is not working as expected for some areas/screens.

As such, we are working on a plan to correct/edit the known miss-redirects for SSMS.

We are also investigating Help/F1 for SSDT and Visual Studio.

However, as for other applications, such as Excel, please visit [Excel help & learning](https://support.microsoft.com/en-us/excel).

Thank you.

**Comment by markingmyname** [comment]
#please-close
