### ISSUE TITLE
Are the graphics on this site still relevant? 

### ISSUE THREAD

**Issue by ps959** [MicrosoftDocs/feedback#3008]
Is the terminology in the charts in this article still relevant in 2020? https://docs.microsoft.com/en-us/archive/blogs/trejo/azure-ad-join-vs-azure-ad-device-registration

**Comment by mlottner** [comment]
@ps959 Thanks for taking the time to give us feedback on docs. You've linked to an archived blog page. As stated on the page, the content is no longer updated. For up to date product content, check the [Microsoft Product Lifecycle site](https://support.microsoft.com/lifecycle/selectindex) for for information about how this product, service, technology, or API is now supported.
I'm closing this issue, but feel free to continue to comment/ask questions here as needed.
