### ISSUE TITLE
Site feedback removed from SQL Server docs?

### ISSUE THREAD

**Issue by brettshearer** [MicrosoftDocs/feedback#3011]
I've previously posted regarding missing documentation, now that option appears to have been removed.
Has the process changed?

**Comment by mlottner** [comment]
@brettshearer On the top right hand side of each docs page page, you should see an evaluation option for the page. Mark your opinion and a comment box option opens for you to leave feedback or suggested changes there. 
Closing this issue for now, but feel free to continue to comment here if/as needed.
