### ISSUE TITLE
Configurations List Api is broken?

### ISSUE THREAD

**Issue by arsunda** [MicrosoftDocs/feedback#302]
# Idea Title

Be as descriptive as you can with your idea/bug report/question/suggestion.

## Issue Details

When using the api specified [here](https://docs.microsoft.com/en-us/rest/api/vsts/policy/configurations/list) , the list api works fine. However, when specifying any scope parameters using the format specified in the page, the value returned is always an empty list 
`{
    "count": 0,
    "value": []
}`

When i have no scope specified, I get a list of policies which have this field 
eg: `"scope": [
                    {
                        "refName": "refs/heads/master",
                        "matchKind": "Exact",
                        "repositoryId": "{repo-id}"
                    }
                ]`

Using the refName or the repository id with wildcards, or using them both to specify the scope always returns the empty value as above. Using the policy parameter works fine

Has anything changes with regards to how this api is documents/set up???

**Comment by Powerhelmsman** [comment]
@erickson-doug Can you take a look at this issue?

**Comment by Powerhelmsman** [comment]
@erickson-doug Any update?

**Comment by Powerhelmsman** [comment]
Sent a email to @erickson-doug to follow up

**Comment by Powerhelmsman** [comment]
@wnjenkin @elbatk Can you help assign to the right person?

**Comment by Powerhelmsman** [comment]
@arsunda Your issue is transferred to vsts-rest-api team. They will help you there. I will close as transferred. If you have other question related to this issue, we can reopen it and continue discussion.
