### ISSUE TITLE
wrong link to Windows Forms Documentation

### ISSUE THREAD

**Issue by traderjoe94** [MicrosoftDocs/feedback#3024]
Starting from https://docs.microsoft.com/de-de/dotnet/framework/ clicking through the Menu to Workloads > Desktop > Windows Forms ends up at https://docs.microsoft.com/de-de/dotnet/framework/windows/ instead of https://docs.microsoft.com/de-de/dotnet/framework/winforms/ which leads to an error 404.

**Comment by mairaw** [comment]
Thank you for your feedback @traderjoe94. I've included this fix along with some other changes I'm making to the .NET menu.
