### ISSUE TITLE
Certain odc.officeapps.live.com links open slowly or redirect to the docs root instead of the expected article

### ISSUE THREAD

**Issue by ogvolkov** [MicrosoftDocs/feedback#3026]
**Describe the bug**
Sporadically, opening certain links from odc.officeapps.live.com subdomain does not lead to the relevant article, but instead opens https://docs.microsoft.com/en-us/ page. Loading time can be quite slow as well (30-60 seconds).

**To Reproduce**
1. Go to 'https://odc.officeapps.live.com/odc/help/clientdeveloper?lcid=1049&syslcid=1049&uilcid=1049&ver=16&helpnamespace=EXCEL&helpid=vbaxl10.chm183085'.
2. Repeat this a dozen of times, as the bug does not manifest itself every time.  
3. Browser redirects to https://docs.microsoft.com/en-us/.

**Expected behavior**
Browser should redirect to https://docs.microsoft.com/ru-ru/office/vba/api/excel.application.cells?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev11.query%3FappId%3DDev11IDEF1%26l%3Dru-RU%26k%3Dk(vbaxl10.chm183085)%3Bk(TargetFrameworkMoniker-Office.Version%3Dv16)%26rd%3Dtrue - which happens in 90% of the cases, but not all the time.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Google Chrome
 - Version 84.0.4147.125 (Official Build) (64-bit)
(Note: also happens with iOS/Safari, looks like a server problem)

**Additional context**
Also happens with https://odc.officeapps.live.com/odc/help/clientdeveloper?lcid=1049&syslcid=1049&uilcid=1049&ver=16&helpnamespace=EXCEL&helpid=vblr6.chm1008897.

**Comment by rootsmusic** [comment]
@ogvolkov Is this still an issue in other browsers?

**Comment by ogvolkov** [comment]
It seems not to happen anymore (well, it’s been almost a year 🙂).
