### ISSUE TITLE
ConfigurationSection.Value docs are incomplete

### ISSUE THREAD

**Issue by MV10** [MicrosoftDocs/feedback#303]
The docs state "Gets or sets the section value." 

This is only accurate if `GetSection` is called on a key that has a single value. If `GetSection` actually returns a configuration section, then `Value` will be `null` and the [`GetChildren`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.configuration.iconfiguration.getchildren?view=aspnetcore-2.0#Microsoft_Extensions_Configuration_IConfiguration_GetChildren) extension method should be used to iterate over configuration contents.

[`ConfigurationSection`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.configuration.configurationsection?view=aspnetcore-2.0)
[`ConfigurationSection.Value`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.configuration.configurationsection.value?view=aspnetcore-2.0#Microsoft_Extensions_Configuration_ConfigurationSection_Value)
[`IConfigurationSection`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.configuration.iconfigurationsection?view=aspnetcore-2.0)
[`IConfigurationSection.Value`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.configuration.iconfigurationsection.value?view=aspnetcore-2.0#Microsoft_Extensions_Configuration_IConfigurationSection_Value)

**Comment by Powerhelmsman** [comment]
@mairaw Can you take a look at this content?

**Comment by mairaw** [comment]
This is ASP.NET Core ref. Tagging @Rick-Anderson and @scottaddie.

**Comment by Rick-Anderson** [comment]
@Powerhelmsman  thanks for the feedback. Per the [README](https://github.com/aspnet/ApiDocs/blob/live/README.md) at https://github.com/aspnet/ApiDocs
API PR's ( api/autoapi/... ) should not be made here. Changes to API documentation should be made in the source repository against the triple slash /// comments.

**Comment by MV10** [comment]
@mairaw `Microsoft.Extensions.Configuration` is not specific to ASP.NET Core. See https://github.com/MicrosoftDocs/feedback/issues/101, for example.

@Rick-Anderson No, this is basically the result of `GetSection`... I am referring to the `Value` property. See the links I provided in the OP.

**Comment by Rick-Anderson** [comment]
@natemcmaster where can we open a bug on `ConfigurationSection.Value`

**Comment by natemcmaster** [comment]
https://github.com/aspnet/configuration

**Comment by Rick-Anderson** [comment]
@MV10  `@haok` answered 
> I'm pretty sure a sections can have children and a value at the same time

@mairaw  can you close this. If needed we can continue at https://github.com/aspnet/Configuration/issues/813
