### ISSUE TITLE
[Typo] "reccomendations" should be spelled "recommendations"

### ISSUE THREAD

**Issue by ianpan870102** [MicrosoftDocs/feedback#3035]
In the documentation for Windows Spotlight: https://docs.microsoft.com/en-us/windows/configuration/windows-spotlight, there's a small typo:

**The word "reccomendations" should be spelled "recommendations".**

**Steps to reproduce**
Go to the website via the link above and Ctrl-F to search for "reccomendations". Notice the typo.

**Comment by JasonWHowell** [comment]
This is resolved Thanks! @gewarren #please-close
