### ISSUE TITLE
you have a dead link on the main page

### ISSUE THREAD

**Issue by brianjsell** [MicrosoftDocs/feedback#3038]
##You have a dead link on main learning page you might want to fix......

![dead link](https://user-images.githubusercontent.com/65693377/90480001-71861780-e0e4-11ea-9752-266bbd377c25.JPG)
that shows you where.. maybe was doing some hot maintenance   IDK.. 
![dead link](https://user-images.githubusercontent.com/65693377/90480239-d2adeb00-e0e4-11ea-98c3-1baa361cb4b9.JPG)

**Comment by JasonWHowell** [comment]
@brianjsell Thanks for reporting the broken link. What URL is that page?

**Comment by JasonWHowell** [comment]
Thanks @Youssef1313 

It could have been a transient problem. Or it is possibly a misunderstanding of the Tab user interface. The tabs are toggling the left and the right slide of the next section, and not opening an outside link.

1. Left tab: Microsoft 365 learning paths
https://docs.microsoft.com/en-us/learn/m365/?tab=tab-start-a-learning-path
![image](https://user-images.githubusercontent.com/5067358/90822345-2557f480-e2e9-11ea-916f-8781aca4fe31.png)

2. Right tab: Hands-on learning
https://docs.microsoft.com/en-us/learn/m365/?tab=tab-hands-on-learning
![image](https://user-images.githubusercontent.com/5067358/90822365-2be66c00-e2e9-11ea-9a67-d00218163b38.png)

It appears to be working on my end, but let us know if you still find a broken link. 

Thanks, Jason
#please-close
