### ISSUE TITLE
Clickable Links in User Story Details Field flicker when hovered

### ISSUE THREAD

**Issue by ahainen** [MicrosoftDocs/feedback#304]
# Clickable Links in User Story Details Field flicker when hovered

Example: https://i.imgur.com/fNy2Wsn.gif
Chrome 65.0.3325.181, Incognito window
macOS 10.13.4

## 
Making something a clickable link in VSTS details field causes bizarre hover issues
![screenflow](https://user-images.githubusercontent.com/972868/38873996-0a7c6fea-4225-11e8-8a51-dea803c1df4b.gif)

**Comment by dend** [comment]
Hey @ahainen - thanks for the feedback! Unfortunately, this doesn't relate to docs.microsoft.com, therefore we cannot address it. Please open a feedback item here: https://visualstudio.uservoice.com/forums/330519-team-services
