### ISSUE TITLE
Wrong return value on tutorial page

### ISSUE THREAD

**Issue by mmenapace** [MicrosoftDocs/feedback#3042]
Go to https://docs.microsoft.com/it-it/dotnet/csharp/tutorials/intro-to-csharp/list-collection?tutorial-step=3
The description of  the return value of the function IndexOf, in case the element is not founded, is indicated as 1 instead of -1 (at least in the italian version of the site)

**Comment by mmenapace** [comment]
Verified with US, an UK English the issue doesn't exist.
It's just an error with the Italian translated page

**Comment by gewarren** [comment]
This has been fixed; closing.
