### ISSUE TITLE
Wrong link to Windows message center

### ISSUE THREAD

**Issue by tamaiyutaro** [MicrosoftDocs/feedback#3045]
**Describe the bug**
Incorrect Windows message center link on Japanese page.
https://docs.microsoft.com/ja-jp/windows/release-information/

**To Reproduce**
1. Go to 'https://docs.microsoft.com/ja-jp/windows/release-information/'
2. Click on 'メッセージ センター'
3. See error '404 - ページが見つかりません' (https://docs.microsoft.com/ja-jp/windows/release-information/windows-message-center.yml)

**Expected behavior**
The page is displayed correctly.

**Screenshots**
![image](https://user-images.githubusercontent.com/30512207/90843209-167e4a00-e39c-11ea-9678-c7d852158f22.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 version 1809 (10.0.17763.1339)
 - Browser: Google Chrome
 - Version: 83.0.4103.106

**Smartphone (please complete the following information):**

**Additional context**

**Comment by JasonWHowell** [comment]
@elizapo could you take a look. The top node of the TOC points to a .yml file which isn't resolving.  Maybe a localization specific issue though. 
![image](https://user-images.githubusercontent.com/5067358/91108233-4e9bbc00-e62c-11ea-8562-382fd894d098.png)

**Comment by tamaiyutaro** [comment]
Do you have any updates on this?
I hope you will deal with it as soon as possible.

**Comment by JasonWHowell** [comment]
@SonjaSaltzman who's the Windows loc contact?

**Comment by SonjaSaltzman** [comment]
@TinaMcN  - Tina, is this in your content?  Could you please follow up?

**Comment by TinaMcN** [comment]
@tamaiyutaro thank you very much for reporting it.  It has been fixed now.  Please let us know if you notice any other issues.

**Comment by tamaiyutaro** [comment]
@TinaMcN Thank you for contacting me.
I'm glad the issue has been fixed.
Thank you for your support!
