### ISSUE TITLE
Compilation not list in API browser search for Roslyn

### ISSUE THREAD

**Issue by svick** [MicrosoftDocs/feedback#3047]
**Describe the bug**

The API browser search for Roslyn does not list [the `Compilation` class](https://docs.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.compilation?view=roslyn-dotnet) in its results.

**To Reproduce**

1. Go to [the API browser for Roslyn](https://docs.microsoft.com/en-us/dotnet/api/?view=roslyn-dotnet) and [search for "Compilation"](https://docs.microsoft.com/en-us/dotnet/api/?view=roslyn-dotnet&term=Compilation).
2. Look for the `Compilation` class among the results, but fail to find it. Though some members of `Compilation` are listed.

**Expected behavior**

`Compilation` is present in the results.

**Comment by gewarren** [comment]
It looks like this is working now:

![image](https://user-images.githubusercontent.com/24882762/93398743-0178c780-f831-11ea-9f41-ddc163db622f.png)
