### ISSUE TITLE
Have list of overloads

### ISSUE THREAD

**Issue by CamSoper** [MicrosoftDocs/feedback#305]
From azure-docs-sdk-dotnet created by [MNF](https://github.com/MNF) : Azure/azure-docs-sdk-dotnet#579  

Previously in msdn there was list of methods  at the top(not individual overloads) and user was able to see individual overloads on separate page when method was selected. The current list of overloads for all methods is huge and hard to read/search

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9507d09-b4c7-9cdb-b19b-975fe27626da
* Version Independent ID: 56602fd3-30d8-255b-5e8a-d32e56899ff7
* Content: [CloudBlockBlob.BeginDownloadText Method (Microsoft.WindowsAzure.Storage.Blob)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.windowsazure.storage.blob.cloudblockblob.begindownloadtext?view=azure-dotnet#Microsoft_WindowsAzure_Storage_Blob_CloudBlockBlob_BeginDownloadText_System_AsyncCallback_System_Object_)
* Content Source: [xml/Microsoft.WindowsAzure.Storage.Blob/CloudBlockBlob.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.WindowsAzure.Storage.Blob/CloudBlockBlob.xml)
* Service: **storage**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by Powerhelmsman** [comment]
@erickson-doug Can you take a look at this request?

**Comment by Powerhelmsman** [comment]
@dend any updates?

**Comment by dend** [comment]
Thank you for the feedback, @MNF and @CamSoper. We are constantly working on evolving our template for .NET API documentation. Currently, we have no plans on changing how we organize methods and overloads, therefore I will close this item - will keep everyone updated on the changes we are making to API doc templates moving forward.
