### ISSUE TITLE
.NET Core Debug incorrect example 

### ISSUE THREAD

**Issue by alet** [MicrosoftDocs/feedback#3050]
Page with info about Debug class contains example with line `Debug.Listeners.Add(new TextWriterTraceListener(Console.Out));` but compiler give error CS0117: '"Debug" не содержит определение для "Listeners". Also description of Debug class does not contain property Listeners. Could you advice article about debug in .NET Core?

**Comment by alet** [comment]
Trace class contains Listeners

**Comment by gewarren** [comment]
It looks like the `Listeners` property is available for .NET Framework only: https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.debug.listeners?view=netframework-4.8#System_Diagnostics_Debug_Listeners. We should update the main example on https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.debug?view=net-5.0 to exclude that line.

**Comment by gewarren** [comment]
This issue was moved to dotnet/dotnet-api-docs#4866
