### ISSUE TITLE
Uri examples broken

### ISSUE THREAD

**Issue by karashiiro** [MicrosoftDocs/feedback#3051]
**Describe the bug**
The examples on the [Uri](https://docs.microsoft.com/en-us/dotnet/api/system.uri) page are missing.

**To Reproduce**
1. Go to page.

**Expected behavior**
The examples would be there.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 x64
 - Browser firefox
 - Version 79

**Additional context**
I don't know how the systems here work, but it may have something to do with https://github.com/dotnet/dotnet-api-docs/pull/4694. The only thing that stuck out to me was that the tags in [~/samples/snippets/csharp/VS_Snippets_Remoting/Classic Uri Example/CS/source.cs](https://github.com/dotnet/dotnet-api-docs/blob/master/samples/snippets/csharp/VS_Snippets_Remoting/Classic%20Uri%20Example/CS/source.cs) were indented, unlike all of the other example snippet files, but I don't know if that actually affects anything or not.

**Comment by karashiiro** [comment]
Main post updated, I accidentally linked an issue instead of a PR.

**Comment by JasonWHowell** [comment]
@gewarren  maybe you could take a look since your PR is linked

**Comment by karashiiro** [comment]
No clue what changed, but the examples aren't broken anymore; closing this issue.
