### ISSUE TITLE
Security Center REST API missing

### ISSUE THREAD

**Issue by martin-nisbet** [MicrosoftDocs/feedback#3053]
**Describe the bug**
This PowerShell script uses an endpoint that is not published in the REST documentation (https://github.com/Azure/Azure-Security-Center/blob/master/Powershell%20scripts/Vulnerability%20Solution/New-ASCVASolution.ps1)

**To Reproduce**
1. Go to 'https://docs.microsoft.com/en-us/rest/api/securitycenter'
2. Look for rest operation group 'Security Solution'
4. See it is missing

**Expected behavior**
I expected to find the API, uriParameters, requestBody and responses that are permitted for this endpoint. I can find External Security Solutions but 

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by rootsmusic** [comment]
@martin-nisbet Please move this issue to https://github.com/Azure/Azure-Security-Center/issues

**Comment by martin-nisbet** [comment]
Closing this and created an updated issue as requested.

https://github.com/Azure/Microsoft-Defender-for-Cloud/issues/808
