### ISSUE TITLE
Typo in the title of the page Export-all-AD-groups-and-3ae6fb42

### ISSUE THREAD

**Issue by prejos** [MicrosoftDocs/feedback#3056]
HI

In this page: 
https://gallery.technet.microsoft.com/scriptcenter/Export-all-AD-groups-and-3ae6fb42

the title is 
"Export all AD groups and thier members to CSV file"

which seems to have a typo: "thier" instead of "their".

Regards

Pablo Rejos

**Comment by rootsmusic** [comment]
@prejos Your link is redirecting now.
