### ISSUE TITLE
Design guidelines on MenuSuites

### ISSUE THREAD

**Issue by MortenKSorensen** [MicrosoftDocs/feedback#306]
# Where to place departments and menu items
Hello,
I have been reading the content regarding Menusuites in the following link:

https://docs.microsoft.com/en-us/previous-versions/dynamicsnav-2013r2/jj128065(v=nav.71)

As I see it the content only explains how to create and modify Menusuites and not design guidelines itself.

I am looking for design guidelines on how to structure and where to place departments and individual menu items. 

Do you have any documentation on this?

Thanks in advance.

**Comment by Powerhelmsman** [comment]
@MortenKSorensen The content has been retired. It will not be updated in the future.

**Comment by MortenKSorensen** [comment]
Thank you for the reply. 

Do Microsoft have any materiales on this? 

Retired or not.

**Comment by Khairunj** [comment]
I am following up with content owner and will get back soon.

**Comment by edupont04** [comment]
Hi @MortenKSorensen - the latest version is published here but might not give you what you're looking for either: https://docs.microsoft.com/en-us/previous-versions/dynamicsnav-2015/jj128067(v%3dnav.80)

The Design team are working on a new version based on the new design that we are rolling out with the next version this Fall. Their key advice is to focus on the Role Center and less on the Menu Suite. That's the thinking behind the design principles here: https://docs.microsoft.com/en-us/previous-versions/dynamicsnav-2015/jj128066(v%3dnav.80)

I'm taking your questions to the team (I'm not a member of that team, but I sit close to them :-)) so they can make clearer recommendations in the update later this year.

I know this probably doesn't answer your question, but it's the best I can do right now. If you have access to the Dynamics Learning Portal, you'll be able to find material about the RoleTailored design that might be closer to your question.
