### ISSUE TITLE
Interpreting Event 153 Errors - wrong offsets

### ISSUE THREAD

**Issue by Eugene-RU** [MicrosoftDocs/feedback#3062]
Article "Interpreting Event 153 Errors" https://docs.microsoft.com/en-us/archive/blogs/ntdebugging/interpreting-event-153-errors says
_In the example above at byte offset 29 is the SCSI status, at offset 30 is the SRB status that caused the retry, and at offset 31 is the SCSI command that is being retried._

But actual offsets are 29, 2A and 2B because they are hexadecimal.
Please change it.

**Comment by rootsmusic** [comment]
@Eugene-RU "We're no longer updating this content regularly."
#please-close
