### ISSUE TITLE
Disable HiddenGroupMembership  in Groups SDS

### ISSUE THREAD

**Issue by AxelRumkorf** [MicrosoftDocs/feedback#3065]
At the start of the school this year we sorted the students with SDS into the new classes. For this purpose new groups were created with SDS. Since not every teacher uses teams, we want to have the teams created by the teachers themselves. But unfortunately the teachers do not see the members of the groups when they create a team. Is there a way to disable the option HiddenGroupMembershipEnabled?

**Comment by rootsmusic** [comment]
@AxelRumkorf Please ask product support or in support forums.
