### ISSUE TITLE
Bug in microsoft support site

### ISSUE THREAD

**Issue by Aryankpoor** [MicrosoftDocs/feedback#3069]
# **Html source code visible in site**
I was just navigating through the microsoft support site when in one page the <p> tag was visible and looked very clumsy.

## **Reproduce**
1. Go to 'microsoft.com'
2. On the navbar Click on **'Windows'**. This should take you to another webpage.
3. Scroll down till you see this - ![img](https://user-images.githubusercontent.com/64773763/91655124-1e409b80-eacc-11ea-9167-2b3155f41ff4.JPG)
4. click on **windows support**
5. This will take you to another web page in which You will be able to see this: ![img](https://user-images.githubusercontent.com/64773763/91655078-bab66e00-eacb-11ea-8302-19f78435669b.JPG)
6. **See the paragraph tags?**

## **Expected behavior**
I would have expected in the purple box the text only not the tags. And the Get The App should have been a link to download the guide to windows 10 app.

## **Screenshots**
Screenshots are above

**Desktop (please complete the following information):**
 - OS: Windows 7 and 10
 - Browser: Chrome
 - Version: Chrome 85

**Smartphone (please complete the following information):**
 - Device: Mi A3
 - OS: Android 9 pie
 - Browser Chrome
 - Version 85

**Comment by rootsmusic** [comment]
Fixed at https://support.microsoft.com/en-us/windows
#please-close

**Comment by Aryankpoor** [comment]
thanks. Waited a year for this
