### ISSUE TITLE
GitHub Web Editor Causes Line Ending Problems

### ISSUE THREAD

**Issue by spottedmahn** [MicrosoftDocs/feedback#307]
I used the GitHub web editor to make [a doc change](https://github.com/MicrosoftDocs/vsts-docs/pull/577) and it introduced some "fake" changes.

I didn't not make these changes:

![image](https://user-images.githubusercontent.com/14079228/38994953-c08c1bdc-43b5-11e8-8492-a3068d70464f.png)

![image](https://user-images.githubusercontent.com/14079228/38994978-cbb380b8-43b5-11e8-88b2-325adfe217ce.png)

**Comment by Powerhelmsman** [comment]
@DuncanmaMSFT Is anyone from your team can answer the question?

**Comment by nschonni** [comment]
This is related to #362

**Comment by spottedmahn** [comment]
Duplicate of #362?  Close this one?
