### ISSUE TITLE
Spelling mistake in Knowledge Base Article "Askbar" instead of "Taskbar"

### ISSUE THREAD

**Issue by Cailsd** [MicrosoftDocs/feedback#3077]
Description of the BUG:
There is mispelling in the article below that showed "Askbar" instead of "Taskbar": 
https://support.microsoft.com/en-us/help/29280/windows-10-how-to-use-the-taskbar

Repro steps:
1. Go to https://support.microsoft.com/en-us/help/29280/windows-10-how-to-use-the-taskbar
2. Scroll down until you see the "Automatically hide the askbar"

Screenshot:
![image](https://user-images.githubusercontent.com/70567871/91821660-41ed1880-ec69-11ea-99d6-6ef938f1ec87.png)

**Comment by rootsmusic** [comment]
Fixed.
#please-close
