### ISSUE TITLE
Please change Azure site  as black theme or white . In amazon site there is option preference white or black text and white or black theme 

### ISSUE THREAD

**Issue by JohnCena710** [MicrosoftDocs/feedback#3079]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by rootsmusic** [comment]
@JohnCena710 Please submit a support ticket at https://azure.microsoft.com/en-us/support/options/
