### ISSUE TITLE
EventWaitHandle names clarification

### ISSUE THREAD

**Issue by rolfik** [MicrosoftDocs/feedback#3087]
https://docs.microsoft.com/en-us/dotnet/api/system.threading.eventwaithandle.-ctor?view=netcore-3.1

Please describe Global\ and Local\ prefixes usable in named EventWaitHandle construction and specify which is default (Local\ one?) and that \ is reserver character.
This information could be shared with other named synchronization types.

Thank you

**Comment by gewarren** [comment]
This issue was moved to dotnet/dotnet-api-docs#4865
