### ISSUE TITLE
Menu Nodes w/o Hyperlinks in Problem

### ISSUE THREAD

**Issue by spottedmahn** [MicrosoftDocs/feedback#309]
When I'm on my iPhone and I pick a menu option that does not have a hyperlink nothing happens, it is confusing IMO.

Please see [this video](https://1drv.ms/v/s!AmsBn7YVdmXPhfMJfBKKDzJpe3PYdg).

![image](https://user-images.githubusercontent.com/14079228/38931702-11f456da-42e2-11e8-9acd-3491b416cd42.png)

---

>Unfortunately, there is nothing that can be done in relation to the referenced article to solve the issue. The choice to use non-linked nodes in the TOC is an organizational decision. 

[Source](https://github.com/MicrosoftDocs/azure-docs/issues/7362#issuecomment-382809147)

[Original issue](https://github.com/MicrosoftDocs/azure-docs/issues/7362)

**Comment by Powerhelmsman** [comment]
This is very interesting finding. @ShevaDas Can you take care the issue?

**Comment by ShevaDas** [comment]
@spottedmahn Thanks for the feedback! I agree this is confusing. We're looking at some big updates to our TOC design and site structure and will make sure this is addressed as those roll out.

**Comment by dend** [comment]
We have released an updated mobile view, that solves this problem.

**Comment by spottedmahn** [comment]
That's great, thanks! 🎉
