### ISSUE TITLE
Bad Link

### ISSUE THREAD

**Issue by ChuckM2** [MicrosoftDocs/feedback#3090]
**Describe the bug**
Methods link is broken

**To Reproduce**
1. Go to "https://docs.microsoft.com/en-us/windows/win32/api/d3d11_3/nn-d3d11_3-id3d11fence"
2. Click on methods link
3. Go to https://docs.microsoft.com/en-us/  which is not all related.

**Expected behavior**
Go to related methods information

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser chrome

**Comment by drewbatgit** [comment]
Thanks for reporting this issue. This is a known issue that is affecting many class and interfaces across the SDK documentation. We have a work item tracking a fix for this issue which requires an update to our production code. The ETA for the fix isn't known for certain, but we will push it out as soon as we can. Thanks again for helping us to improve the docs!
