### ISSUE TITLE
Links broken

### ISSUE THREAD

**Issue by saf-itpro** [MicrosoftDocs/feedback#3091]
Most (if not all) WPF related links seem to be broken - probably because of migrating the content to `WPF-Core`. Here are some of the examples. Your team may want to fix these links ASAP as these broken links are hindering the process of learning/fixing WPF related knowledge or fixing the WPF related issues. Here are some examples:

Following link titled `How to: Detect When Text in a TextBox Has Changed - WPF ...` is broken:

https://docs.microsoft.com/en-us/dotnet/desktop/framework/wpf/controls/how-to-detect-when-text-in-a-textbox-has-changed?view=netdesktop-5.0

This one also broken:
`how-to-implement-binding-validation`: https://docs.microsoft.com/en-us/dotnet/desktop/framework/wpf/data/how-to-implement-binding-validation?view=netdesktop-5.0&redirectedfrom=MSDN

And another one:

`how-to-implement-validation-logic-on-custom-objects`: https://docs.microsoft.com/en-us/dotnet/desktop/framework/wpf/data/how-to-implement-validation-logic-on-custom-objects?view=netdesktop-5.0

And this one:

`commanding-overview`: https://docs.microsoft.com/en-us/dotnet/desktop/framework/wpf/advanced/commanding-overview?view=netdesktop-5.0

`How to: Hook Up a Command to a Control with No Command .Support`:  https://docs.microsoft.com/en-us/dotnet/desktop/framework/wpf/advanced/how-to-hook-up-a-command-to-a-control-with-no-command-support?view=netdesktop-5.0

**Comment by adegeo** [comment]
Sorry for the confusion. I caused this problem and the fix was implemented about 9 days ago. The content moved to a new folder and the redirects created were invalid, so the URLs you were being directed to had the wrong path in them. While the links you reported don't work and won't work, the pages that were linking to them will point you to the correct paths now.

Sorry again!

**Comment by saf-itpro** [comment]
@adegeo Thank you for making the corrections. By searching the titles of the links online (e.g. `How to: Detect When Text in a TextBox Has Changed - WPF ...`) , I've verified that all the broken links in my post above are working now.
