### ISSUE TITLE
The open closed principle in the article isn't exactly true

### ISSUE THREAD

**Issue by y471n** [MicrosoftDocs/feedback#3092]
https://docs.microsoft.com/en-us/archive/msdn-magazine/2008/june/patterns-in-practice-the-open-closed-principle

The Open Closed example, isn't entirely true since the base class is being modified every time a new source is added in Figure 2.

**Comment by JasonWHowell** [comment]
@y471n Thanks for the feedback. That page from June 2008 is no longer being maintained. #please-close
