### ISSUE TITLE
"icacls" command in localized article "Install SQL Server Language Extensions on Windows" is wrong

### ISSUE THREAD

**Issue by JohannWeskandt** [MicrosoftDocs/feedback#3097]
The English article shows this as the 2nd command in paragraph "Grant access to non-default JRE folder" (Give AppContainer permissions):
`icacls "<PATH to JRE>" /grant "ALL APPLICATION PACKAGES":(OI)(CI)RX /T`
While this may work in an English Windows, it won't work on a German Windows, as names of Windows accounts are localised.
But the German article "[Installieren von SQL Server-Spracherweiterungen unter Windows](https://docs.microsoft.com/de-de/sql/language-extensions/install/install-sql-server-language-extensions-on-windows)" shows the exact same command here:
`icacls "<PATH to JRE>" /grant "ALL APPLICATION PACKAGES":(OI)(CI)RX /T`
The above command doesn't work successfully on a German Windows. The command needs to be changed to:
`icacls "<PATH to JRE>" /grant "ALLE ANWENDUNGSPAKETE":(OI)(CI)RX /T`
to work successfully.
I assume, this issue applies to all languages where a localized Windows is available.

**Comment by JasonWHowell** [comment]
@davidph this is a complex doc/OS localization problem for the SQL Server Language Extensions page.

**Comment by JasonWHowell** [comment]
#assign:dphansen

**Comment by dphansen** [comment]
@JohannWeskandt Thank you for the feedback. I will investigate the issue and get back to you.

**Comment by dphansen** [comment]
@JohannWeskandt I have looked into the issue, and as you mention the friendly name is being translated in localized versions of Windows. 

I'm going to update the article to use the computer SID instead, which does not change across different language versions of Windows. The command will then be:

```
icacls “<PATH to JRE>” /grant *S-1-15-2-1:(OI)(CI)RX /T
```

Thank you again for your feedback. The updated article will be published next week.

**Comment by dphansen** [comment]
#please-close
