### ISSUE TITLE
Documentation does not reflect how the rotation of certificate happes in this case

### ISSUE THREAD

**Issue by khandelwalbrijesh** [MicrosoftDocs/feedback#3098]
**Is your feature request related to a problem? Please describe.**
I am following the documentation [here](https://docs.microsoft.com/en-us/aspnet/core/security/docker-compose-https?view=aspnetcore-3.1) which shows how to do https certificate binding in asp.net app inside docker. We are using the same approach in our production containers but It is not explained here what happens when certificate is rotated. What is the best way to configure the rotation here? Will it work by simply updating the certificate at the location ASPNETCORE_Kestrel__Certificates__Default__Path. Or there is something else needs to be done here. 
Internally, does this way of binding certificate uses ServerCertificateSelector while doing the binding so, the certificate can be updated after the owner of the app updates the certificate at the ASPNETCORE_Kestrel__Certificates__Default__Path location?

**Describe the solution you'd like**
Need some guidance on the best way to configure the autorotation here

**Describe alternatives you've considered**
We are considering to bind the certificate from the code and use Server Selector while doing so, the certificate will get updated without crashing.

**Comment by gewarren** [comment]
This issue was moved to dotnet/AspNetCore.Docs#19901
