### ISSUE TITLE
Applies To:  Refers to PC Version Instead Of Server Versions

### ISSUE THREAD

**Issue by BGaudreault-EDR** [MicrosoftDocs/feedback#310]
## Issue Details

Fix "Applies To:" in http://technet.microsoft.com/en-us/library/dd744581(v=ws.10).aspx

Applies To:  Refers to PC Version Instead Of Server Versions.

**Comment by Powerhelmsman** [comment]
@BGaudreault-EDR Thanks for your feedback. This page is for old version. We stop updating the old version.
