### ISSUE TITLE
Link error

### ISSUE THREAD

**Issue by aflant** [MicrosoftDocs/feedback#3100]
**Describe the bug**
Two of different link point to the same page

**To Reproduce**

Go to '**https://docs.microsoft.com/en-us/SharePoint/getting-started?redirectedfrom=MSDN#where-do-i-start**'
Links **[2016 Hardware and software requirements]** and **[2013 Hardware and software requirements]** lead to the same page, '**https://docs.microsoft.com/en-us/SharePoint/install/hardware-and-software-requirements**'

Link **[2013 Hardware and software requirements]** have its own address, '**https://docs.microsoft.com/en-us/SharePoint/install/hardware-and-software-requirements-0**'

**Comment by JasonWHowell** [comment]
Attempting to fix in https://github.com/MicrosoftDocs/OfficeDocs-SharePoint-pr/pull/2730/

**Comment by JasonWHowell** [comment]
@aflant 
This fix has been published. you should see it on the site shortly. Thanks for helping us improve Microsoft documentation! ~Jason

**Comment by JasonWHowell** [comment]
#please-close
