### ISSUE TITLE
Microsoft Virtual Machine Converter - Link Error

### ISSUE THREAD

**Issue by lucafabbri365** [MicrosoftDocs/feedback#3101]
Hello,
I hope this is the right place where to post this issue.

I was trying to download **[Microsoft Virtual Machine Converter](https://www.microsoft.com/download/details.aspx?id=42497)**; but MSFT link doesn't work (Error 404). There are lot of sites referencing to it:

- MicrosoftDocs - [Microsoft Virtual Machine Converter 3.0](https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-r2-and-2012/dn873998(v=ws.11))
- Search engines (Google, Bing)

So I was wondering if it still exist; if not, please, remove any reference to it and what's its substitute (I know it isn't the right place to ask however I give it a try).

Thank you,
Luca

**Comment by JasonWHowell** [comment]
Hi @lucafabbri365

The docs site has a banner at the top to explain the documentation pages are not being maintained. Sorry for the inconvenience. The tool was most likely removed. 

"We're no longer updating this content regularly. Check the Microsoft Product Lifecycle for information about how this product, service, technology, or API is supported."

**Comment by rootsmusic** [comment]
#please-close
