### ISSUE TITLE
Typo in RegGetValueA

### ISSUE THREAD

**Issue by krishty** [MicrosoftDocs/feedback#3102]
Go to https://docs.microsoft.com/en-us/windows/win32/api/winreg/nf-winreg-reggetvaluea
Scroll down to dwFlags

The description of RRF_RT_QWORD reads: Restrict type to 64-bit RRF_RT_REG_BINARY | RRF_RT_REG_DWORD.

I’m sure the end should read QWORD, not DWORD.

**Comment by JasonWHowell** [comment]
Attempting to fix here: https://github.com/MicrosoftDocs/sdk-api/pull/452

**Comment by JasonWHowell** [comment]
We fixed the doc. Thanks for the eagle eyes. ~Jason

**Comment by JasonWHowell** [comment]
#please-close
