### ISSUE TITLE
Pearson Vue exam schedule link stuck in a loop

### ISSUE THREAD

**Issue by Ikem14** [MicrosoftDocs/feedback#3103]
**Describe the bug**
The Pearson Vue exam schedule link stuck in a loop when. This is the link:

https://examregistration.microsoft.com/?locale=en-us&examcode=AZ-900&examname=Exam%20AZ-900:%20Microsoft%20Azure%20Fundamentals&returnToLearningUrl=https%3A%2F%2Fdocs.microsoft.com%2Flearn%2Fcertifications%2Fexams%2Faz-900

**To Reproduce**
1. Go to 'https://docs.microsoft.com/en-us/learn/certifications/exams/az-900'
2. Click on 'Pearson Vue link'

**Expected behavior**
Should take me to site where I can schedule an exam
**Screenshots**

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Safari
 - Version: 13.1.2

**Smartphone (please complete the following information):**

**Additional context**

**Comment by JasonWHowell** [comment]
@Ikem14 most likely the issue is that it's trying to authenticate, but not working. Could be clearing the cookie would help. 
It works on my Safari in iPhone - prompting me to log in at login.live.come 

Try private browsing in Safari to see if the link would work there. 

Thanks, Jason

**Comment by Ikem14** [comment]
@JasonWHowell Thanks for the response. I already used chrome for my exam but still tried out your solution and it worked. Thanks again
