### ISSUE TITLE
page not displaying well

### ISSUE THREAD

**Issue by SONUGUPTAMCA** [MicrosoftDocs/feedback#3105]
I found 2 issues on the page : 

https://docs.microsoft.com/en-us/aspnet/web-forms/overview/deployment/configuring-server-environments-for-web-deployment/configuring-a-web-server-for-web-deploy-publishing-web-deploy-handler

#1
on this address "https://docs.microsoft.com/en-us/aspnet/web-forms/overview/deployment/configuring-server-environments-for-web-deployment/configuring-a-web-server-for-web-deploy-publishing-web-deploy-handler"

"Filter by title" at left side menu is shoing wrongly, its width is not set properly.

![image](https://user-images.githubusercontent.com/14804810/92901138-e0cdfd80-f43d-11ea-8089-5a59a66ce6f8.png)

#2
on same address "https://docs.microsoft.com/en-us/aspnet/web-forms/overview/deployment/configuring-server-environments-for-web-deployment/configuring-a-web-server-for-web-deploy-publishing-web-deploy-handler"

This is also from same page, loot at the bottom of page, the footer is very bad condition.

![image](https://user-images.githubusercontent.com/14804810/92901551-32768800-f43e-11ea-9a85-d735014824cb.png)

**Comment by JasonWHowell** [comment]
@SONUGUPTAMCA  thanks for the feedback. 

Maybe something wrong with the table of contents for these 3 entries. The strings are pretty long, which may be hitting some limit. 
https://github.com/dotnet/AspNetDocs/blob/master/aspnet/toc.yml#L161-L166

@tdykstra could you please advise who works on the Asp.Net docs? This TOC is rendering in a strange way. Maybe the parenthesis or the string length something.

**Comment by tdykstra** [comment]
cc @Rick-Anderson

**Comment by JasonWHowell** [comment]
I got a potential fix thanks to the support channel: https://github.com/dotnet/AspNetDocs/pull/449

**Comment by Rick-Anderson** [comment]
Thanks to @JasonWHowell  for fixing this. I confirmed his update fixed the problem. Will be live in a few minutes.

**Comment by JasonWHowell** [comment]
#please-close
