### ISSUE TITLE
Not enough details for Analysis Services SDK page on Synchronizing tabular models

### ISSUE THREAD

**Issue by djpirra** [MicrosoftDocs/feedback#3106]
On the [Synchronize](https://docs.microsoft.com/en-us/dotnet/api/microsoft.analysisservices.core.server.synchronize?view=analysisservices-dotnet) method of the Server object it explicitly says one of the parameters is a string called source.
What is exactly this string since I have tried multiple alternatives such as IP, server name and it does not work.
The documentation should be a bit more explicit on what exactly is expected to be passed on the parameters.

Thank you

**Comment by JasonWHowell** [comment]
I'm guessing it'd be the server name or FQDN

In the PowerShell equivalent, it is `-Instance` https://docs.microsoft.com/en-us/powershell/module/azurerm.analysisservices/sync-azureanalysisservicesinstance?view=azurermps-5.7.0  With example `Sync-AzureAnalysisServicesInstance -Instance asazure://westus.asazure.windows.net/contoso -Database SalesOrders`

@Minewiskan @jonburchel any ideas?

**Comment by Minewiskan** [comment]
@djpirra - Thank you for your feedback. 
The source object is a valid connection string. Suggest using Profiler to verify connections are attempted and credentials being used. If you continue to have issues, please open a support case. 
#please-close
