### ISSUE TITLE
Spelling error

### ISSUE THREAD

**Issue by atvineeth89** [MicrosoftDocs/feedback#3107]
Hi Microsoft,

While troubleshooting one of my server issue I noticed a spelling error in the below page

https://docs.microsoft.com/en-us/troubleshoot/windows-server/identity/replication-error-5

In the section "Run DCDIAG, DCDIAG /TEST:CheckSecurityError, and NETDIAG" on second point DCDIAG is spelled as DCDAIG.
Please try to correct it as it will be helpful for the users.

Thanks
Vineeth

**Comment by JasonWHowell** [comment]
@Deland-Han please take a look at this spelling typo that needs a quick fix.
#assign:Deland-Han

**Comment by Deland-Han** [comment]
I have corrected it and merge the change to master. the change should be pushed to live soon.

**Comment by JasonWHowell** [comment]
@atvineeth89 thanks for reporting the docs misspelling. We've fixed it and the change will publish soon. Thanks! #please-close
