### ISSUE TITLE
Page from-azure-logic-apps-and-deploy-with-azure-devops-pipelines/ has broken links

### ISSUE THREAD

**Issue by MNF** [MicrosoftDocs/feedback#3108]
**Describe the bug**
Page https://docs.microsoft.com/en-us/samples/azure-samples/azure-logic-apps-deployment-samples/connect-to-azure-service-bus-queues-from-azure-logic-apps-and-deploy-with-azure-devops-pipelines/ has broken links

Concepts https://docs.microsoft.com/en-us/samples/azure-samples/azure-logic-apps-deployment-samples/concept-review.md
Naming convention https://docs.microsoft.com/en-us/samples/azure-samples/azure-logic-apps-deployment-samples/naming-convention.md
Samples file structure and definitions https://docs.microsoft.com/en-us/samples/azure-samples/azure-logic-apps-deployment-samples/file-definitions.md

**ipad**
 - OS: [iOS]
 - Browser [safari]

**Additional context**

**Comment by JasonWHowell** [comment]
@ecfan @scgbear several docs links are broken from this sample 

The correct links are 
https://github.com/Azure-Samples/azure-logic-apps-deployment-samples/blob/master/concepts-review.md
https://github.com/Azure-Samples/azure-logic-apps-deployment-samples/blob/master/naming-convention.md
https://github.com/Azure-Samples/azure-logic-apps-deployment-samples/blob/master/file-definitions.md

**Comment by JasonWHowell** [comment]
#assign:ecfan
#assign:scgbear

**Comment by ecfan** [comment]
@scgbear, I created a PR. If all looks good, please approve. Thanks!

**Comment by ecfan** [comment]
@JasonWHowell: Closed PR https://github.com/MicrosoftDocs/samples/pull/1708 and fixed with this PR instead: https://github.com/Azure-Samples/azure-logic-apps-deployment-samples/pull/13

#please-close
