### ISSUE TITLE
Page logic-apps-and-deploy-with-azure-devops-pipelines/ is not wrapped, too wide.

### ISSUE THREAD

**Issue by MNF** [MicrosoftDocs/feedback#3109]
**Describe the bug**
Page https://docs.microsoft.com/en-us/samples/azure-samples/azure-logic-apps-deployment-samples/set-up-an-azure-function-app-action-for-azure-logic-apps-and-deploy-with-azure-devops-pipelines/ is not wrapped, too wide.

**
**iPAD)
 - OS: [iOS]
 - Browser safari]
 -

**Comment by JasonWHowell** [comment]
@MNF could you please attach a screenshot from you iPAD?

@ecfan @scgbear there may be a formatting issue in this sample that is related to the wide code boxes.

**Comment by JasonWHowell** [comment]
Re: https://github.com/Azure-Samples/azure-logic-apps-deployment-samples/commits/master/function-app-actions

**Comment by ecfan** [comment]
@scgbear, I created a PR. If all looks good, please approve. Thanks!

**Comment by ecfan** [comment]
@JasonWHowell: #please-close
