### ISSUE TITLE
IIS Sysprep Compatibility Needs More Details

### ISSUE THREAD

**Issue by BGaudreault-EDR** [MicrosoftDocs/feedback#311]
## Issue Details

Fix "Applies To:" in http://technet.microsoft.com/en-us/library/dd744581(v=ws.10).aspx

The article says Sysprepping is not supported if there are "encrypted credentials", but there's no reference about how to identify this scenario.  Can this detail be added to the document?  Thanks

**Comment by Powerhelmsman** [comment]
@TaraMeyer Is there anything you can help here?

**Comment by Powerhelmsman** [comment]
@TaraMeyer Can you response if you are the right person to contact? @themar-msft @joshhbax-msft for awareness.

**Comment by TaraMeyer** [comment]
@Powerhelmsman - I'm sorry for my late response, thank you for sending me an email and bringing to my attention.  I'm forwarding you the contact information of the content owner.  You'll need to work with her as to how to get this content updated.  Thanks!

**Comment by lizap** [comment]
Hi @BGaudreault-EDR , thanks for the comment. You can learn about IIS encrypted accounts [here](https://docs.microsoft.com/en-us/iis/manage/configuring-security/using-encryption-to-protect-passwords) - that article includes some ways to validate that passwords are encrypted. Other than that, we'd recommend checking out the [IIS library](https://docs.microsoft.com/en-us/iis/get-started/whats-new-in-iis-10-version-1709/new-features-introduced-in-iis-10-1709) as a whole. Thanks!

**Comment by dend** [comment]
Thanks @lizap! Closing this issue, as the information was provided above.
