### ISSUE TITLE
Cab files giving 404 on Guidance for configuring IPv6 in Windows for advanced users - Page

### ISSUE THREAD

**Issue by gautamhans1** [MicrosoftDocs/feedback#3111]
**Describe the bug**
None of the download links are working on Guidance for configuring IPv6 in Windows for advanced users - Page. 
They all are giving 404 - File or directory not found. 

**To Reproduce**
1. Go to 'https://docs.microsoft.com/en-us/troubleshoot/windows-server/networking/configure-ipv6-in-windows'
2. Click on 'Download - Re-enable IPv6 on all tunnel interfaces'

**Expected behavior**
To be able to download the files

**Screenshots**
https://i.imgur.com/8WotrZc.png

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 85.0.4183.102

**Comment by JasonWHowell** [comment]
@Deland-Han there is a broken link on the Windows Server networking docs page.  Please take a look at this issue for full context.

**Comment by Deland-Han** [comment]
These links expired and there are no new download links for these packages. Therefore, I removed the section.

**Comment by JasonWHowell** [comment]
@gautamhans1 thanks for pointing this out. We've removed the broken links since the tools are no longer available. Have a great day. ~Jason

**Comment by JasonWHowell** [comment]
#please-close

**Comment by gautamhans1** [comment]
Oh! I actually needed one of the files there to fix my Teredo client. Bummer!!

Any other way I can get those files?
