### ISSUE TITLE
automatic check for 404'ing links

### ISSUE THREAD

**Issue by Conan1989** [MicrosoftDocs/feedback#3112]
**Is your feature request related to a problem? Please describe.**
I'm often finding links in the documentation that result in a 404 error

**Describe the solution you'd like**
May i suggest setting up a system that automatically scans the repos for links that 404, and creates tasks to fix

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by JasonWHowell** [comment]
@Conan1989 good idea. Thanks for sharing it.

We actually do have a number of checks and reports that let internal Microsoft docs contributors see broken links. It is hard to stay on top of, but if there is a particular link of interest, let me know. 

Thanks, Jason

**Comment by JasonWHowell** [comment]
#please-close

**Comment by Gov0949** [comment]
H
