### ISSUE TITLE
The article is not displayed in the side menu

### ISSUE THREAD

**Issue by YoshikaSuzuki** [MicrosoftDocs/feedback#3114]
**Describe the bug**
The following pages are not displayed in the side menu.
https://docs.microsoft.com/ja-jp/dynamics365/customer-voice/purchase#enable-dynamics-365-customer-voice-for-a-user-without-a-dynamics-365-enterprise-license

**To Reproduce**
1. Go to 'https://docs.microsoft.com/ja-jp/dynamics365/customer-voice/purchase#enable-dynamics-365-customer-voice-for-a-user-without-a-dynamics-365-enterprise-license'

**Expected behavior**
The subject of the target article is displayed in the side menu
Be published in a state translated into Japanese

**Screenshots**
![image](https://user-images.githubusercontent.com/65008112/93036387-b321c800-f67a-11ea-940a-fc75a2ae5696.png)

**Comment by JasonWHowell** [comment]
@sbmjais this appears to be an issue with the TOC in the Japanese translation of your article. Can you please alert the loc contact for this set of docs?

**Comment by JasonWHowell** [comment]
#assign:sbmjais

**Comment by JasonWHowell** [comment]
@SonjaSaltzman do you know who is the loc contact for Dynamics?

**Comment by SonjaSaltzman** [comment]
@vinceno  - Hi Vince, looks like feedback for your loc'd content

**Comment by vinceno** [comment]
@SonjaSaltzman  thx - @mhogan73 @Dealgan12 - this is for untranslated topics in Customer Voice., can you check into it please.

**Comment by vinceno** [comment]
This looks to be just a timing issue. The files have very recently been translated and are now published.
https://docs.microsoft.com/ja-jp/dynamics365/customer-voice/purchase#enable-dynamics-365-customer-voice-for-a-user-without-a-dynamics-365-enterprise-license

**Comment by vinceno** [comment]
@SonjaSaltzman I don't seen to have sufficient rights to 'close' this item.

**Comment by JasonWHowell** [comment]
@vinceno  the concern was the TOC entry, not the file itself. Is that entry appearing when you view the page?

**Comment by Dealgan12** [comment]
@JasonWHowell @vinceno The TOC entry is there now also for this page. It was missing for the same reason. It was only recently translated and todays publish fixed it also. 

@mhogan73

**Comment by SonjaSaltzman** [comment]
closing per @vinceno request - please reopen if needed
