### ISSUE TITLE
Missing 'upload' button for adding in new contributions on technet dashboard

### ISSUE THREAD

**Issue by e24n1h2** [MicrosoftDocs/feedback#3116]
I am unable to see 'upload' button for adding in contributions on my technet dashboard ( https://gallery.technet.microsoft.com/site/mydashboard )

![technet](https://user-images.githubusercontent.com/45938282/93176491-f3527a80-f74e-11ea-8ca3-4a6421656260.jpg)

**Comment by JasonWHowell** [comment]
The site is retiring. It says "We are retiring the TechNet Gallery. Make sure to back up your code"

**Comment by JasonWHowell** [comment]
Here's the information about the retirement: https://docs.microsoft.com/en-us/teamblog/technet-gallery-retirement

#please-close
