### ISSUE TITLE
Issue with "Get started with Office 365 Management APIs" doc

### ISSUE THREAD

**Issue by singhbrijraj** [MicrosoftDocs/feedback#3123]
**Describe the bug**
Issue with "Get started with Office 365 Management APIs" doc.

Need an update on "Specify the permissions your app requires to access the Office 365 Management APIs" section:
https://docs.microsoft.com/en-us/office/office-365-management-api/get-started-with-office-365-management-apis#specify-the-permissions-your-app-requires-to-access-the-office-365-management-apis 

Step 3: The Office Management APIs now appear in the list of applications to which your application requires permissions. Under both Application Permissions and Delegated Permissions, select the permissions your application requires. Refer to the specific API reference for more details about each permission.

 Note : There are currently four unused permissions related to activity reports and threat intelligence that will be removed in the future. Do not select any of these permissions because they are unnecessary.

![image](https://user-images.githubusercontent.com/33527492/93600527-6cff9800-f9dd-11ea-962c-caea9cb2a7b2.png)

Should be updated as below:

Step 3: The Office Management APIs now appear in the list of applications to which your application requires permissions. Under both Application Permissions and Delegated Permissions, select the permissions your application requires. Refer to the specific API reference for more details about each permission.

Permissions Details:
For Activity Feed (O365 Management Activity API)
ActivityFeed.Read : Read Activity data for your organization.
ActivityFeed.ReadDlp : Read DLP policy events including detected sensitive data.

For Service Health (Service Communication API)
SerivceHealth.Read : Read service health information for your organization. 
![image](https://user-images.githubusercontent.com/33527492/93601021-2bbbb800-f9de-11ea-8c5b-c3b5c52bb343.png)

**Comment by rootsmusic** [comment]
@singhbrijraj Please move this issue to https://github.com/MicrosoftDocs/office-365-management-api/issues

**Comment by singhbrijraj** [comment]
I have logged it @ https://github.com/MicrosoftDocs/office-365-management-api/issues/239
