### ISSUE TITLE
Incorrect characters included in commands on document causing execution errors

### ISSUE THREAD

**Issue by pelon34** [MicrosoftDocs/feedback#3130]
Hello Team,

Recently I detected the following problem while providing support to one of our customers using the following document 
https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/credssp-encryption-oracle-remediation

The commands in this document contain 13 instances of an unnecessary tag value <br/>
 this extra characters are causing problems to our customers since commands executions are failing. ( this tags <br/> should not be part of the commands )
here is an image that shows this problem is present in 13 parts of the document
![image](https://user-images.githubusercontent.com/24233701/93927396-6a06ef00-fcde-11ea-8335-f294ea52b31f.png)

Please help us make sure to remove this characters for all affected commands and make sure to present the commands on their own individual rows.

**Comment by JasonWHowell** [comment]
@genlin @TobyTu can you take a look at this code formatting issue.

**Comment by JasonWHowell** [comment]
#assign:genlin

**Comment by TobyTu** [comment]
@JasonWHowell @genlin I have submitted a https://github.com/MicrosoftDocs/SupportArticles-docs-pr/pull/531 to fix this issue, thanks for pointing out.

**Comment by JasonWHowell** [comment]
Thanks #please-close
