### ISSUE TITLE
Delete query issue 

### ISSUE THREAD

**Issue by MahirMansuri** [MicrosoftDocs/feedback#3134]
Hello Microsoft,

I need to delete the selected data. So, I am executing a delete query but it is not working.
I have faced the same issue in the past.on that time I had deleted data from another table then this query was working.
Now, I have faced the same issue again.

So, can you please send me a solution?

FYI, I have attached a Screen recording.
PFA,

Thanks & Regards,
Mahir Mansuri
mail : mahir.mansuri@ordextechnology.com

[deleteissue_23rd_sep_2020.zip](https://github.com/MicrosoftDocs/feedback/files/5268045/deleteissue_23rd_sep_2020.zip)

**Comment by rootsmusic** [comment]
@MahirMansuri Please ask product support or in support forums.
