### ISSUE TITLE
Larger floating point variables

### ISSUE THREAD

**Issue by PaulDAdamson** [MicrosoftDocs/feedback#3138]
Currently, I'm using javascript to handle my very large and very small numbers.

See these calculators as examples: https://pauldadamson.github.io/TheWholeProcessModel/index

Would it be possible to include a variable type for values representing more significant figures?  I'd like to translate my javascript calculations into an application.  Right now, I'm achieving 86 significant figures in my calculations.  I'd like to reach that in my C# and C++ code.

Thanks

**Comment by rootsmusic** [comment]
@PaulDAdamson Please ask product support or in support forums.
