### ISSUE TITLE
Problem with Azure portal while training

### ISSUE THREAD

**Issue by MichaelErasmus78** [MicrosoftDocs/feedback#3142]
Hi Guys

So i started doing the Azure Training and signed up for free 12 moths on the azure portal , Ive done the first few lessosn without any issue but now whe n I need to do custom deploymnet my subscription went to Concierge Subscription and I am unable to create a resource group with the name "admsdemorg" any ide how do I get rid on the Concierge subscription?
![Conceirge Subscription error](https://user-images.githubusercontent.com/65215485/94458224-f53c2500-01b5-11eb-886d-6bda6088206f.JPG)

**Comment by rootsmusic** [comment]
@MichaelErasmus78 Please submit a support ticket at https://azure.microsoft.com/en-us/support/options/
