### ISSUE TITLE
Typo in SessionsOptions Class page, for the IOTimeout property description

### ISSUE THREAD

**Issue by Kilazur** [MicrosoftDocs/feedback#3145]
In the page https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.builder.sessionoptions?view=aspnetcore-3.1, in the IOTimeout property description, we can read the word "**maximim**", which I assume should be "**maximum**".

![image](https://user-images.githubusercontent.com/7058306/94565774-e9119f80-0269-11eb-8dab-dff8f3a62b40.png)

**Comment by gewarren** [comment]
This issue was moved to dotnet/AspNetApiDocs#165
