### ISSUE TITLE
Add documentation for SQL Server blocked process report

### ISSUE THREAD

**Issue by rjk** [MicrosoftDocs/feedback#3148]
**Is your feature request related to a problem? Please describe.**
Within SQL Server there is a feature to create a 'blocked process report' using Extended Events or similar (e.g. this says how to turn it on https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/blocked-process-threshold-server-configuration-option?view=sql-server-ver15), however there is no documentation for how to interpret the resulting report. The report is complex XML with many non-trivial data fields. 

**Describe the solution you'd like**
I'd like one or more pages documenting all of the fields within the blocked process report plus information about how to interpret them. 

**Describe alternatives you've considered**
I've searched high and low for comprehensive documentation, but all I find is narrowly-focused blog articles & Q&A answers, which are often out of date or wrong. 

**Additional context**
[Here's a question](https://dba.stackexchange.com/questions/276289/where-is-the-documentation-for-sql-servers-blocked-process-report) I asked about this topic, with some related resources there.

**Comment by gewarren** [comment]
FYI @MashaMSFT

**Comment by MashaMSFT** [comment]
Hi @rjk , thanks for contacting Microsoft!

Does this article help? [Blocked Process Report event class](https://docs.microsoft.com/sql/relational-databases/event-classes/blocked-process-report-event-class)

And  you can learn more about the locks here: [Transaction locking and row versioning](https://docs.microsoft.com/sql/relational-databases/sql-server-transaction-locking-and-row-versioning-guide)

Thanks!
Masha from the SQL Docs team

**Comment by rjk** [comment]
Hi Masha,
Thanks for getting in touch. no that article doesn’t cover it, although it
obviously describes some fields. I’ll explain what I mean when I have more
time, just wanted to get you a reply now.

Rory

**Comment by rjk** [comment]
Hi Masha, 

The article you linked to is, I think, documenting event classes for SQL Server Profiler, which is not the recommended way of gathering blocked process reports (right?). In any case, the main thing you get in a blocked process report is an XML report. I'm guessing through SQL Profiler this appears in the 'TextData' field which isn't documented in that article you linked to. With Extended Events this appears in the `blocked_process` field. I can't find documentation on this XML report. 

[Here's a question I asked ](https://dba.stackexchange.com/q/276289/6548) on stackexchange looking for documentation, where I gave some examples of things that'd be good to document, along with a few links to helpful blog articles. 

It would be good to have documentation about:
* overview: what is a blocked process report, how is it triggered, how to configure it, how to capture it (i.e. different options like sql trace & profiler & extended events)
* what are the fields captured when using extended events (like the article you linked to provides for sql trace) and how to interpret them
* what are the fields in the blocked_process XML (see the example below, there's lots of non-obvious fields) and how to interpret them.
* what are the fields in the deadlock XML (is this captured by blocked process report?)

Here's an example report: 

```
<blocked-process-report monitorLoop="373">
 <blocked-process>
  <process id="process1c26e597848" taskpriority="0" logused="0" waitresource="KEY: 6:72057594043301888 (61a06abd401c)" waittime="15424" ownerId="78647" transactionname="SELECT" lasttranstarted="2020-09-29T20:56:29.110" XDES="0x1c28139fbe8" lockMode="S" schedulerid="4" kpid="12044" status="suspended" spid="71" sbid="0" ecid="0" priority="0" trancount="0" lastbatchstarted="2020-09-29T20:56:29.110" lastbatchcompleted="2020-09-29T20:56:29.103" lastattention="1900-01-01T00:00:00.103" clientapp="Microsoft SQL Server Management Studio - Query" hostname="PSSFC07" hostpid="11808" loginname="PSSFC07\roryk" isolationlevel="read committed (2)" xactid="78647" currentdb="6" currentdbname="scratch" lockTimeout="4294967295" clientoption1="671090784" clientoption2="390200">
   <executionStack>
    <frame line="2" stmtstart="4" stmtend="42" sqlhandle="0x02000000faf3b324c012257bed5f9539bf22f13fc9f5995c0000000000000000000000000000000000000000" />
   </executionStack>
   <inputbuf>

select * from tester 
   </inputbuf>
  </process>
 </blocked-process>
 <blocking-process>
  <process status="sleeping" spid="69" sbid="0" ecid="0" priority="0" trancount="1" lastbatchstarted="2020-09-29T20:56:26.203" lastbatchcompleted="2020-09-29T20:56:26.203" lastattention="1900-01-01T00:00:00.203" clientapp="Microsoft SQL Server Management Studio - Query" hostname="PSSFC07" hostpid="11808" loginname="PSSFC07\roryk" isolationlevel="read committed (2)" xactid="78613" currentdb="6" currentdbname="scratch" lockTimeout="4294967295" clientoption1="671090784" clientoption2="390200">
   <executionStack />
   <inputbuf>
begin tran 
insert into tester (id) values (2)
   </inputbuf>
  </process>
 </blocking-process>
</blocked-process-report>

```

Also fwiw on the article you linked to: 

* IndexID documentation is incorrect, the reported value is usually 256 (e.g. see [here](https://social.msdn.microsoft.com/Forums/sqlserver/en-US/614f8061-7fe8-435d-83de-5f8238d88d3d/blocked-process-report?forum=sqldatabaseengine))

thanks,

Rory

**Comment by WilliamDAssafMSFT** [comment]
Hi @rjk! Thanks again for submitting your feedback. Your suggestions help improve our documentation. We're going to put in a work item to expand this content in the future. 
In the meanwhile there are lots of resources online for analyzing deadlock xml, including on microsoft.com: 
https://docs.microsoft.com/en-us/sql/tools/sql-server-profiler/analyze-deadlocks-with-sql-server-profiler?view=sql-server-ver15

We address the xml_deadlock_report Extended Event, which is the recommended way to observe deadlocks, here:
https://docs.microsoft.com/en-us/sql/relational-databases/sql-server-transaction-locking-and-row-versioning-guide?view=sql-server-ver15#deadlock_xevent

**Comment by WilliamDAssafMSFT** [comment]
#reassign:WilliamDAssafMSFT

**Comment by WilliamDAssafMSFT** [comment]
#please-close
