### ISSUE TITLE
Search vs. Filter in API Browser

### ISSUE THREAD

**Issue by BillWagner** [MicrosoftDocs/feedback#315]
Consider this typical [API page](https://docs.microsoft.com/dotnet/api/system.threading.tasks?view=netframework-4.7.2).

The box in the left nav is labelled **Search**, but it functions as **FIlter**. That's misleading.

The **Search** functionality is available from the top bar, but that's scoped to all of .NET docs. I think it would be much more useful to scope the search to the API Browser scope.

**Comment by presleyy** [comment]
Generally the ToC left nav box functions as filter. But for that API page, it functions as search. That's why it is labelled "Search" instead of "Filter by title". @dend to confirm that.

**Comment by dend** [comment]
Can confirm - the page example presented is an API page, therefore the search is API search. It's not quite a filter, because it doesn't just look at the table of contents (TOC) - it does an API index traversal to search for APIs that match the pattern entered.
