### ISSUE TITLE
spelling error

### ISSUE THREAD

**Issue by deonlewisduke** [MicrosoftDocs/feedback#3151]
https://docs.microsoft.com/en-us/windows/windows-10/

Under CONFIGURATION 

How to run a trillion dollar company

Accesability is spelled wrong

**Comment by JasonWHowell** [comment]
@greg-lindsay can you please fix the typo?

@deonlewisduke Thanks for pointing out our mistake. We are just people too, and thanks for calling it out so we can fix it.
