### ISSUE TITLE
Event Grid REST API Overview with broken Links

### ISSUE THREAD

**Issue by jayendranarumugam** [MicrosoftDocs/feedback#3156]
**Describe the bug**
A couple of reference links are not working/invalid in the event grid rest api overview 
https://docs.microsoft.com/en-us/rest/api/eventgrid/#rest-operation-groups
- Topic Types
- Topics 
are not having correct href

**To Reproduce**
1. Go to 'https://docs.microsoft.com/en-us/rest/api/eventgrid/#rest-operation-groups'
2. Click on 'Topic Types' and 'Topics'
![image](https://user-images.githubusercontent.com/25414541/94934995-12406300-04ea-11eb-9fea-4cd27f5aaf92.png)

3. See the links are having an invalid link like below
![image](https://user-images.githubusercontent.com/25414541/94935102-37cd6c80-04ea-11eb-98cc-3f3bfb861e19.png)

```
xref:management.azure.com.eventgrid.version2019-06-01.topictypes
xref:management.azure.com.eventgrid.version2019-06-01.topics
```

**Expected behavior**
Links should be working properly 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 85.0.4183.121

**Comment by rootsmusic** [comment]
@jayendranarumugam Please move this issue to https://github.com/MicrosoftDocs/azure-docs/issues

**Comment by jayendranarumugam** [comment]
As I created this long time since, I can see its  been fixed now
