### ISSUE TITLE
Documentation for System.Web.UrlMappingsModule is missing

### ISSUE THREAD

**Issue by rossmpersonal** [MicrosoftDocs/feedback#3158]
**Describe the bug**
Documentation for System.Web.UrlMappingsModule is missing.

**To Reproduce**
1. Go tohttps://docs.microsoft.com/en-us/dotnet/api/
2. Enter System.Web.UrlMappingsModule in the search box.
3. See No Results returned

**Expected behavior**
Link to documentation for System.Web.UrlMappingsModule appears.

**Screenshots**
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/57814305/94982376-f481f680-0507-11eb-9ab9-8b9646fbc5cf.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - MacBook Pro
 - 10.15.7
 -Safari
 - Version 14.0

**Additional context**

**Comment by gewarren** [comment]
This issue was moved to dotnet/dotnet-api-docs#5020
