### ISSUE TITLE
CMD

### ISSUE THREAD

**Issue by poopbot2** [MicrosoftDocs/feedback#316]
# Idea Title

so whenever i open my cmd it automatically closes withing a split second  
## Issue Details

whenever i open cmd it closes and it doesn't matter what way i open it, weather its in a short cut or as admin even ctrl+r dosn't work nor ctrl+x i have tried millions of virus detectors and nothing works

**Comment by Powerhelmsman** [comment]
@poopbot2 This forum is for docs.microsoft.com site instead of general Microsoft product forum. Sorry can't help you here.
