### ISSUE TITLE
Broken link on Service Bus (classic) REST page 

### ISSUE THREAD

**Issue by chanmmn** [MicrosoftDocs/feedback#3162]
Page:
https://docs.microsoft.com/en-us/previous-versions/azure/hh780717(v=azure.100)?redirectedfrom=MSDN

Broken link at the end of the page. 
Service Bus .NET (https://msdn.microsoft.com/en-us/library/mt419900(v=azure.100))

**Comment by rootsmusic** [comment]
@chanmmn "We're no longer updating this content regularly."
#please-close
