### ISSUE TITLE
MSB3075 the command "C:\Windows\System32\chcp.com 65001 > NUL"

### ISSUE THREAD

**Issue by ravi1323** [MicrosoftDocs/feedback#3166]
**Describe the bug**
MSB3075 the command "C:\Windows\System32\chcp.com 65001 > NUL"

![image](https://user-images.githubusercontent.com/66269113/95205364-e59a8d00-0802-11eb-91d9-f9240982fcbb.png)

**Comment by rootsmusic** [comment]
@ravi1323 Please ask product support or in support forums.
