### ISSUE TITLE
.NET API Browser Page Missing Entry for System Namespace

### ISSUE THREAD

**Issue by zacharylayne** [MicrosoftDocs/feedback#3169]
**Describe the bug**
When browsing namespaces, the list of namespaces on the [.NET API browser](https://docs.microsoft.com/en-us/dotnet/api/?view=net-5.0) page seems to lack an entry linking to [System](https://docs.microsoft.com/en-us/dotnet/api/system?view=net-5.0).

**Additional context**
This appears to be an issue across documentation for all .NET frameworks & versions.

**Comment by rhowell-cis300** [comment]
System.IO also isn't listed.

**Comment by gewarren** [comment]
Thanks for the feedback. I've opened internal bug https://dev.azure.com/ceapex/Engineering/_workitems/edit/325235 to track this.

**Comment by gewarren** [comment]
Closing as duplicate of #3135.
