### ISSUE TITLE
MicrosoftDocs - 404 not found for many pages

### ISSUE THREAD

**Issue by chr1272** [MicrosoftDocs/feedback#317]
Just in case I am the first to report this: there is something seriously wrong with the documentation.
For example this link is - like many others - not working: https://docs.microsoft.com/en-us/aspnet/core/group1-dest/tutorials/razor-pages/?view=aspnetcore-2.1

404
Error - Sorry this document can't be found.

**Comment by Folivi95** [comment]
This happens mostly with asp.net core documentation

**Comment by kobowo** [comment]
Is there a fix for it though? I think it is mostly for aspnet core.. I was browsing through identity just fine yesterday but now I can't use the links on the navigation... the pages still exist though.. I apparently opened the link for one of the topics I wanted to study previously and was able to open it (meaning the links on the navigation might be new but it doesn't route (not sure if this is the right term) to the page properly.

**Comment by Folivi95** [comment]
It's good now

**Comment by chr1272** [comment]
I still get 404 on this link: https://docs.microsoft.com/en-us/aspnet/core/group1-dest/tutorials/razor-pages/?view=aspnetcore-2.1

**Comment by Rick-Anderson** [comment]
@Powerhelmsman  can you close this now?
