### ISSUE TITLE
Bad link in the "Part 3, scaffolded Razor Pages in ASP.NET Core" section

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/feedback#3173]
**Describe the bug**
Clicking the link that redirects you to https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/intro?view=aspnetcore-3.1#asynchronous-code should scroll down to the related header with the id "asynchronous-code", but it doesn't. The reason for that is, the id of the header is "asynchronous-code-1" and not "asynchronous-code".

**To Reproduce**
1. Go to https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/page?view=aspnetcore-3.1&tabs=visual-studio#the-create-delete-details-and-edit-pages
2. Read the paragraph "Razor Pages are derived from PageModel. By convention, the PageModel-derived class is called <PageName>Model. The constructor uses dependency injection to add the RazorPagesMovieContext to the page. All the scaffolded pages follow this pattern. See Asynchronous code for more information on asynchronous programming with Entity Framework."
3. Click on "Asynchronous code"
4. The top of the new page is visible.

**Expected behavior**
The new page should scroll down to the relevant section titled "Asynchronous Code"

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Microsoft Edge
 - Version  85.0.564.70

**Smartphone (please complete the following information):**

**Additional context**

**Comment by gewarren** [comment]
This issue was moved to dotnet/AspNetDocs#459
