### ISSUE TITLE
404 Page not Found

### ISSUE THREAD

**Issue by Cmconnely** [MicrosoftDocs/feedback#3187]
The following URL is broke:  https://blogs.technet.microsoft.com/secguide/2017/06/15/dropping-the-untrusted-font-blocking-setting

Receiving the 404 Page not Found. 

Please help,
Kind Regards

**Comment by rootsmusic** [comment]
@Cmconnely Technet Blogs are closed at https://docs.microsoft.com/en-us/archive/blogs/
