### ISSUE TITLE
Data Mining 2016 Pres Campaign Finance Data - all data moved, thus all data links broken. Still accessable.. 

### ISSUE THREAD

**Issue by Cognitive-dissonance** [MicrosoftDocs/feedback#3189]
**Describe the bug**
On the Experiment page "Data Mining 2016 Presidential Campaign Finance Data" at:
https://gallery.azure.ai/Experiment/Data-Mining-2016-Presidential-Campaign-Finance-Data-1
All links on the FEC web have been re-arranged, breaking all data links to the FEC on the above page.

**To Reproduce**
1. Go to 'above URL'
2. Click on 'committee linkage file, or any other link that links to data on the FEC site'
3. Scroll down to 'no scrolling needed if your browser displays more than about 10 lines..'
4. See error: usual (but custom) 404.

**Expected behavior**
A download of the zip file indicated in all the FEC download links. (which, BTW, are all FTP, and their FTP server is currently not even responding, I'm guessing it's part of the re-arrangement noted in a few text files..

**Screenshots**
Nobody at MS is dense enough to need one.

**Desktop (please complete the following information):**
*****These are of course irrelevant unless the FTP is just failed, but I think it's down intentionally as there are other ways offered
         to access the data. (including an API)
 - OS: Ubuntu LTS 18.04
 - Browser Firefox
 - Version 81.0 (64-bit) (see what happens when you make up your own versioning scheme?)

**Smartphone (please complete the following information):**
Irrelevant also anyway, FTP fails, it fails for everyone.

**Additional context**
OK, so you can get the same data (or make new http links for your page if you're all loaded with free time) by going to:
 https://www.fec.gov/data/browse-data/?tab=bulk-data
and just opening whichever you want, or "Contributions by individuals"
click the 2015-2016 link for that data. All files are obvious by you original (top link above) page's name for the data.

**Comment by rootsmusic** [comment]
@Cognitive-dissonance The experiment isn't a doc.  You can comment below the experiment.
#please-close
