### ISSUE TITLE
There is a typo in the title of Powertoys article in Microsoft docs

### ISSUE THREAD

**Issue by Cortana-117** [MicrosoftDocs/feedback#3192]
https://docs.microsoft.com/en-us/windows-insider/apps/powertoys

the title says PowerToys "Uodates" instead of "Updates"

![fdsfs](https://user-images.githubusercontent.com/72892766/96046940-2b99c580-0e81-11eb-8c25-da9b01981a20.png)

also can be seen in web search:

![ghfhgf](https://user-images.githubusercontent.com/72892766/96047157-8a5f3f00-0e81-11eb-9555-2461a891fd15.png)

**Comment by rootsmusic** [comment]
@Cortana-117 That doc has been redesigned.
#please-close
