### ISSUE TITLE
Default page language

### ISSUE THREAD

**Issue by ABAC699** [MicrosoftDocs/feedback#3196]
Currently the docs are automatically translated based on IP address location. In some cases I have noticed that only some parts (navigation, labels or headers) are translated. I would prefer to have English as the default language, since I (and probably many other developers) are used with the English terminology. Some pages have the option to read the doc in English others do not. 
The issue might be in the way google returns the results, when it gives priority to localized pages, however, I would expect an option on the docs page to change the language of the full page.

**Comment by JasonWHowell** [comment]
The language chooser on docs.microsoft.com is way down on the bottom left. You can change your preferred language, and it should stick. 
![image](https://user-images.githubusercontent.com/5067358/96186073-bdd8b280-0eef-11eb-8a4f-5f79dcc65252.png)

Hope this helps! 
~Jason
#please-close
