### ISSUE TITLE
how to help correct translation

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#32]
I am reading https://docs.microsoft.com/fr-fr/MicrosoftTeams/teams-channels-overview. I can't find any option to leave a comment except this user voice.
So, can we have a feedback/comment section on all docs il help is needed to correct translation.

----------
⚠ Idea migrated from UserVoice

**Created By:** Jean Marie THIA
**Created On:** 2018/01/30 08:19:56 +0000
**Votes at Migration:** 2
**Supporters at Migration:** 2

**Comment by dend** [comment]
@SonjaSaltzman @Sara-Nicolini - would you like to address this question? 😊

**Comment by dend** [comment]
Also adding @samanthaw to comment.

**Comment by dend** [comment]
Ping @SonjaSaltzman @Sara-Nicolini @samanthaw

**Comment by samanthaw** [comment]
@botcrane - the feedback section is now available for this content set

**Comment by Powerhelmsman** [comment]
Feedback is enabled now. So close the issue.
