### ISSUE TITLE
ASP.NET 2.1 Preview the Chinese Edition some codes seems to be missing

### ISSUE THREAD

**Issue by BreakEnder233** [MicrosoftDocs/feedback#320]
https://docs.microsoft.com/zh-cn/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-2.1

The code part of "Add a database context class" seems to be missing in Chinese Edition Pages and is ok in US Edition Pages. Is it a mistake haven't been covered? Plz take a look.

**Comment by Powerhelmsman** [comment]
@SonjaSaltzman Can you take a look?

**Comment by SonjaSaltzman** [comment]
@nokura Nobuko, could you please check and fix? Maybe outdated topic?

**Comment by nokura** [comment]
@BreakEnder233 Thank you for your feedback. We are localizing the latest English files and estimated date of  publishing is 5/16. This should solve the issue. I will come back and check after 5/16.

**Comment by Powerhelmsman** [comment]
@BreakEnder233 It has been resolved. Please double check.
