### ISSUE TITLE
Broken links on "Data Consistency Primer" guidance 

### ISSUE THREAD

**Issue by mrdulin** [MicrosoftDocs/feedback#3200]
**Describe the bug**

Two broken links:
- https://blog.jonathanoliver.com/2010/04/idempotency-patterns/
- https://www.enterpriseintegrationpatterns.com/idempotentreceiver.html

**To Reproduce**
1. Go to https://docs.microsoft.com/zh-cn/previous-versions/msp-n-p/dn589800(v=pandp.10)#retrying-failing-steps
2. Click on 'Idempotent Receiver' and 'Idempotency Patterns'

**Expected behavior**

Update the correct links

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser:  Edge
 - Version:  86.0.622.43

**Comment by rootsmusic** [comment]
@mrdulin "我们将不再定期更新此内容"
#please-close

**Comment by daodennis** [comment]
Jonathan might consider using a 301 to the new link: https://blog.jonathanoliver.com/idempotency-patterns/
