### ISSUE TITLE
Make "Applies To" section in .NET API documentation individual per overload

### ISSUE THREAD

**Issue by GGG-KILLER** [MicrosoftDocs/feedback#3205]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I try to see when a certain overload was added because there is no easy way to obtain that information.

**Describe the solution you'd like**
The "Applies To" information should be per overload instead of per method or type name.

**Describe alternatives you've considered**
1. Check the version of that documentation page for each .NET Core, .NET Framework and .NET Standard version to see which ones have the overload we're looking for and which ones don't;
2. Open Visual Studio, create a project with multi-targeting for all versions we want to check and then pick the highest version and look at the tooltip to see availability of that overload (and this doesn't always work).

**Additional context**
An example of this would be trying to find out when `string.IndexOf(Char, StringComparison)` became available, since the [docs page](https://docs.microsoft.com/en-us/dotnet/api/system.string.indexof) say the entire page is applicable to:

- .NET Framework ≥ 1.1
- .NET Standard
- .NET Core

However if you check that page for any .NET Framework versions or .NET Core versions lower than 2.1 or .NET Standard versions lower than 2.1, you'll see that overload doesn't exist because it was added on .NET Core 2.1 and .NET Standard 2.1.

**Comment by gewarren** [comment]
This issue was moved to dotnet/dotnet-api-docs#5017
