### ISSUE TITLE
Dark mode images/icons not transparent or missing correct color

### ISSUE THREAD

**Issue by geskill** [MicrosoftDocs/feedback#321]
In vs guide the vs logo and the world logo inside the note is styled incorrectly as you can see on the screenshot here:
![image](https://user-images.githubusercontent.com/6826752/39124979-b9ab6d72-46fd-11e8-9c3a-c0dfeb12e377.png)

Tip: There should be a guideline creating images, most from Azure Architecture Guide are not or not completely readable.

**Comment by Powerhelmsman** [comment]
@ShevaDas Can you follow up with UI designer?

**Comment by ShevaDas** [comment]
@geskill thanks for the feedback! Rest assured we do have guidelines for creating images in place—if you see documentation that doesn't have what you feel are usable images, please feel free to open an issue on that piece of content. For images not appearing clearly when using the dark theme, our UI team is investigating the best solution. I'll follow up here once we have something in place.

**Comment by ShevaDas** [comment]
@geskill After talking to our design team, we've determined there isn't a great programatic way to fix this that won't negatively impact the rest of the site look. For example, we could automatically add a white background to all images on dark theme, but that would make many images more difficult to read. Therefore, it's the responsibility of individual content teams to make sure their images are accessible in both modes.

I've reached out to the team who created this content to pass along your feedback. If you notice this issue on other Docs content, please open an issue on the content so the content authors can fix it. Thanks for taking the time to provide feedback!

**Comment by ShevaDas** [comment]
@geskill The content teams have updated the icons on this page to be readable in dark mode. Thanks for the feedback!

**Comment by PatMyron** [comment]
@shirgoldbird I agree that automatically adding a white background to all transparent images could be problematic. However, this problem still seems widespread:
https://github.com/MicrosoftDocs/architecture-center/issues/1203#issuecomment-454950221

I wrote a script that can be used to identify all of the images with transparent backgrounds:
https://github.com/MicrosoftDocs/architecture-center/issues/1203#issuecomment-471245609

Would it make sense to use this script in order for content teams to quickly review their respective transparent background images?
