### ISSUE TITLE
Add the 'Microsoft.EnterpriseManagement.Sql.UserDefinedDataType' in the Optional - Enable CLR strict security section for SCOM on SQL 2017 / 2019

### ISSUE THREAD

**Issue by Brunoga-MS** [MicrosoftDocs/feedback#3211]
**Describe the bug**
A trusted assembly seems to be missing in the public documentation at pages
- https://docs.microsoft.com/en-us/system-center/scom/upgrade-sqlserver-2017-opsmgr?view=sc-om-1807
- https://docs.microsoft.com/en-us/system-center/scom/upgrade-sqlserver-2017-opsmgr?view=sc-om-2019
- https://docs.microsoft.com/en-us/system-center/scom/upgrade-sqlserver-2019-operations-manager?view=sc-om-2019

**A clear and concise description of what the bug is.**
When moving OpsMgr databases to SQL Server 20176 or 2019 the Event Ids **_26319_** and **_33333_** both with **_0x8013150A_** in the description are generated in the OpsMgr Event Log. The events are about the missing assemblies:
- microsoft.enterprisemanagement.sql.userdefineddatatype
- Microsoft.EnterpriseManagement.Sql.DataAccessLayer

Events contain a description similar to this one:
_[Microsoft.EnterpriseManagement.Common.UnknownDatabaseException]: The creator of this fault did not specify a Reason. (Fault Detail is equal to An error occurred in the Microsoft .NET Framework while trying to load assembly id 65537. The server may be running out of resources, or the assembly may not be trusted. Run the query again, or check documentation to see how to solve the assembly trust issues. For more information about this error: 
System.IO.FileLoadException: Could not load file or assembly 'microsoft.enterprisemanagement.sql.userdefineddatatype, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. An error relating to security occurred. (Exception from HRESULT: 0x8013150A)_

The pages are only considering 1 assembly. The other one is not listed. Please update the code to include the following assembly:
set  @Hash = HASHBYTES(N'SHA2_512', 0x4D5A90000300000004000000FFFF0000B800000000000000400000000000000000000000000000000000000000000000000000000000000000000000800000000E1FBA0E00B409CD21B8014CCD21546869732070726F6772616D2063616E6E6F742062652072756E20696E20444F53206D6F64652E0D0D0A2400000000000000504500004C0103006182CF4B0000000000000000E00002210B010800001600000008000000000000BE3400000020000000400000000040000020000000020000040000000000000004000000000000000080000000020000000000000300408500001000001000000000100000100000000000001000000000000000000000006834000053000000004000006004000000000000000000000000000000000000006000000C000000B83300001C0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000200000080000000000000000000000082000004800000000000000000000002E74657874000000C4140000002000000016000000020000000000000000000000000000200000602E7273726300000060040000004000000006000000180000000000000000000000000000400000402E72656C6F6300000C0000000060000000020000001E00000000000000000000000000004000004200000000000000000000000000000000A0340000000000004800000002000500DC250000DC0D00000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000360002731000000A7D010000042A0000133002002D00000001000011000F01281100000A16FE010A062D03002B1A027B010000040F01281200000A6F1300000A1F2C6F1400000A262A5200027B01000004037B010000046F1500000A262A0000133004004C00000002000011007E1600000A0A027B010000042C13027B010000046F1700000A16FE0216FE012B01170C082D1A027B0100000416027B010000046F1700000A17596F1800000A0A06731900000A0B2B00072A133003002900000001000011000314FE0116FE010A062D0B7201000070731A00000A7A02036F1B00000A731C00000A7D010000042A000000133002002A00000001000011000314FE0116FE010A062D0B7205000070731A00000A7A03027B010000046F1D00000A6F1E00000A002A1E02281F00000A2A5602281F00000A000002732100000A7D02000004002A133002002F000000010000110228080000060000032C0E036F2200000A16FE0216FE012B01170A062D0F00027B02000004036F2300000A0000002A001B3003007600000003000011007E1600000A0A00027B020000046F2400000A0D2B1C1203282500000A0B00067209000070076F1D00000A282600000A0A001203282700000A130411042DD7DE0F1203FE160300001B6F2800000A00DC0006282900000A16FE01130411042D09007E1600000A0C2B0B0006176F2A00000A0C2B00082A000001100000020014002D41000F0000000013300200140000000100001100027B020000046F2B00000A16FE010A2B00062A133001000B000000040000110073080000060A2B00062A00133004008100000005000011000F00281200000A0A0F00281100000A2D10066F2C00000A282900000A16FE012B0116130411042D08280C0000060D2B4E06178D2100000113051105161F2C9D1105176F2D00000A0B160C2B1600070807089A6F2C00000A6F2E00000AA2000817580C08078E69FE04130411042DDE07280100002B000773090000060D2B00092A00000013300100110000000600001100027B020000046F2B00000A0A2B00062A0000001B300300560000000700001100160A00027B020000046F2400000A0D2B1F1203282500000A0B0007031B283100000A0A0616FE01130411042D022B0E001203282700000A130411042DD4DE0F1203FE160300001B6F2800000A00DC00060C2B00082A000001100000020010003040000F000000001B300200520000000700001100170A00037B020000046F2400000A0D2B1B1203282500000A0B000207280F0000060A06130411042D022B0E001203282700000A130411042DD8DE0F1203FE160300001B6F2800000A00DC00060C2B00082A000001100000020010002C3C000F0000000013300200170000000800001100020328130000060A066F0B00000616FE010B2B00072A001B300200670000000900001100027B0200000473090000060A00037B020000046F2400000A0D2B261203282500000A0B0006076F0F000006130411042D0F00067B02000004076F3200000A0000001203282700000A130411042DCDDE0F1203FE160300001B6F2800000A00DC00060C2B00082A000110000002001A003751000F000000001B30020064000000090000110073080000060A00037B020000046F2400000A0D2B291203282500000A0B0002076F0F00000616FE01130411042D0F00067B02000004076F3200000A0000001203282700000A130411042DCADE0F1203FE160300001B6F2800000A00DC00060C2B00082A01100000020014003A4E000F0000000013300400410000000A000011000314FE0116FE010C082D0B7201000070731A00000A7A036F1B00000A0A06178D210000010D09161F2C9D09176F2D00000A0B027B02000004076F2300000A002A000000133002002500000001000011000314FE0116FE010A062D0B7205000070731A00000A7A03026F1D00000A6F1E00000A002A00000042534A4201000100000000000C00000076322E302E35303732370000000005006C00000014050000237E000080050000A805000023537472696E677300000000280B00001000000023555300380B0000100000002347554944000000480B00009402000023426C6F6200000000000000020000015717A2090908000000FA01330016000001000000250000000300000002000000150000000F0000000300000032000000110000000A0000000100000002000000020000000300000001000000020000000100000000000A0001000000000006009C0095000A00CA00AF000A00F000DB0006000601FA000A002C01DB0006005B01510106006D0151010600A10186010600B001860106006902570206008002570206009D0257020600BC0257020600D50257020600EE02570206000903570206002403570206005C033D0306007003570206009C0389035300B00300000600DF03BF030600FF03BF0306001D0495000A003304AF000A005404AF0006006C0495000600840495000A00A504AF000600CB0486012300E204000006001705950006004805950006004D05950006006E0595000A007905AF0006008C059500000000000100000000000100010001201000450051000500010001000120100088005100050002000800010014010A000100A8012F00502000000000860027010E00010060200000000086003601120001009920000000008600410118000200B02000000000860047011E000300082100000000E601680123000300402100000000E6017A0129000400762100000000861880010E0005007E2100000000861880010E0005009421000000008618800136000500D02100000000C600BE013F000600642200000000E609C701430006008422000000009608D201470006009C22000000009600DB014C0006002C23000000008600E101530007004C23000000008600E70157000700C023000000008600EB015C0008003024000000008600F4015C0009005424000000009600FD0162000A00D824000000009600030262000C00582500000000E601680123000E00A82500000000E6017A0129000F00000001001902000001001F02000001002502000001002702000001002902000001003102000001003302000001003B02000001004202000001004A02000002005002000001004A020000020050020000010025020000010027020200090003000D0003000900510080017400590080017400610080017400690080017400710080017400790080017400810080017400890080017400910080017900990080017400A10080017E00B10080018400B90080010E00C10080010E00C90080018900210080010E002900C701430029005B043F0021006504F10021006504F700210065040101D900730407012100790453002100BE010A01290080017400E1008001740031009A043F002100800174000900BE013F0039007A017400090080010E00E900800189000C0080010E001400C10453000C00D9044F010C00ED0459011C00FB046801D90007056D011C000E054300010123050E00D9002B057401D900390579010C00C1045300D90043053F00D90060058F01D90066053F00190174059901210180010E00D9009D05DA010C00A405F5012E001B002B022E006B0073022E000B0012022E0013002B022E00230031022E002B0012022E00330040022E003B002B022E004B002B022E005B0061022E0063006A0243007B008F00630003011701C0018301B101E0018301B10100028301B10120028301B101FD0010017E018A01A501D601E301EF01FB0109020300010000000D026B00000014026F0002000B00030002000C0005004301490162010480000001000000B30EF0680000000000005100000002000000000000000000000001008C00000000000200000000000000000000000100A300000000005F00A10100000000003C4D6F64756C653E004D6963726F736F66742E456E74657270726973654D616E6167656D656E742E53716C2E55736572446566696E656444617461547970652E646C6C00436F6E636174656E617465004D6963726F736F66742E456E74657270726973654D616E6167656D656E742E53716C2E55736572446566696E6564446174615479706500536574006D73636F726C69620053797374656D004F626A6563740053797374656D2E44617461004D6963726F736F66742E53716C5365727665722E536572766572004942696E61727953657269616C697A650053797374656D2E446174612E53716C547970657300494E756C6C61626C650053797374656D2E5465787400537472696E674275696C64657200696E7465726D656469617465526573756C7400496E69740053716C537472696E6700416363756D756C617465004D65726765005465726D696E6174650053797374656D2E494F0042696E61727952656164657200526561640042696E617279577269746572005772697465002E63746F720053797374656D2E436F6C6C656374696F6E732E47656E65726963004C6973746031006D656D626572730049436F6C6C656374696F6E603100546F537472696E67006765745F49734E756C6C006765745F4E756C6C00506172736500436F756E740048617300496E636C7564657300496E436F6D6D6F6E00556E696F6E00496E746572736563740049734E756C6C004E756C6C0076616C7565006F7468657200720077006F626A65637473007300656C656D656E740073756273657400616E6F74686572006669727374007365636F6E640053797374656D2E5265666C656374696F6E00417373656D626C795469746C6541747472696275746500417373656D626C794465736372697074696F6E41747472696275746500417373656D626C79436F6E66696775726174696F6E41747472696275746500417373656D626C79436F6D70616E7941747472696275746500417373656D626C7950726F6475637441747472696275746500417373656D626C79436F7079726967687441747472696275746500417373656D626C7954726164656D61726B41747472696275746500417373656D626C7943756C747572654174747269627574650053797374656D2E52756E74696D652E496E7465726F70536572766963657300436F6D56697369626C6541747472696275746500417373656D626C7956657273696F6E4174747269627574650053797374656D2E446961676E6F73746963730044656275676761626C6541747472696275746500446562756767696E674D6F6465730053797374656D2E52756E74696D652E436F6D70696C6572536572766963657300436F6D70696C6174696F6E52656C61786174696F6E734174747269627574650052756E74696D65436F6D7061746962696C6974794174747269627574650053657269616C697A61626C654174747269627574650053716C55736572446566696E656441676772656761746541747472696275746500466F726D6174006765745F56616C756500417070656E6400537472696E6700456D707479006765745F4C656E67746800417267756D656E744E756C6C457863657074696F6E0052656164537472696E670053716C55736572446566696E656454797065417474726962757465006765745F436F756E740049456E756D657261626C6560310041646452616E676500456E756D657261746F7200476574456E756D657261746F72006765745F43757272656E7400436F6E636174004D6F76654E6578740049446973706F7361626C6500446973706F73650049734E756C6C4F72456D70747900537562737472696E67005472696D004368617200537472696E6753706C69744F7074696F6E730053706C697400546F4C6F77657200417272617900536F72740053716C4D6574686F6441747472696275746500537472696E67436F6D70617269736F6E00457175616C730041646400000372000003770000032C0000000000988CD7764C980A49A3DB04E0EFC50A160008B77A5C561934E0890306121103200001052001011115052001011208042000111505200101121905200101121D0606151221010E08200101151225010E0320000E03200002040000120C060001120C111503200008042001020E05200102120C080002120C120C120C03280002040800120C042001010E042001010205200101115504200101080520010111696101000200000004005402124973496E76617269616E74546F4E756C6C73015402174973496E76617269616E74546F4475706C696361746573005402124973496E76617269616E74546F4F726465720054080B4D61784279746553697A65401F000005200112110E0520011211030307010205200112111C02060E0520020E08080607030E1115022B010002000000020054080B4D61784279746553697A65401F000054020D4973427974654F7264657265640105151221010E05151225010E0920010115127901130008200015117D0113000515117D010E04200013000600030E0E0E0E040001020E0420010E080B07050E0E0E15117D010E02040701120C0920021D0E1D0311808907100101011D1E00030A010E0B07060E1D0E08120C021D03240100020054020F497344657465726D696E6973746963015402094973507265636973650103070108080003020E0E1180950B0705020E0215117D010E02050702120C020520010113000D0705120C0E120C15117D010E020807040E1D0E021D031801001355736572446566696E6564446174615479706500000501000000000E0100094D6963726F736F667400002001001B436F7079726967687420C2A9204D6963726F736F6674203230313000000801000701000000000801000800000000001E01000100540216577261704E6F6E457863657074696F6E5468726F7773010000000000006182CF4B000000000200000091000000D4330000D415000052534453E34F9E44F81FB94E95CF281C5235867A01000000443A5C50726F6A656374735C55736572446566696E656444617461547970655C55736572446566696E656444617461547970655C6F626A5C44656275675C4D6963726F736F66742E456E74657270726973654D616E6167656D656E742E53716C2E55736572446566696E656444617461547970652E70646200000000903400000000000000000000AE340000002000000000000000000000000000000000000000000000A034000000000000000000000000000000005F436F72446C6C4D61696E006D73636F7265652E646C6C0000000000FF25002040000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100100000001800008000000000000000000000000000000100010000003000008000000000000000000000000000000100000000004800000058400000080400000000000000000000080434000000560053005F00560045005200530049004F004E005F0049004E0046004F0000000000BD04EFFE0000010000000100F068B30E00000100F068B30E3F000000000000000400000002000000000000000000000000000000440000000100560061007200460069006C00650049006E0066006F00000000002400040000005400720061006E0073006C006100740069006F006E00000000000000B00468030000010053007400720069006E006700460069006C00650049006E0066006F00000044030000010030003000300030003000340062003000000034000A00010043006F006D00700061006E0079004E0061006D006500000000004D006900630072006F0073006F00660074000000500014000100460069006C0065004400650073006300720069007000740069006F006E0000000000550073006500720044006500660069006E006500640044006100740061005400790070006500000040000F000100460069006C006500560065007200730069006F006E000000000031002E0030002E0033003700360033002E00320036003800360034000000000098003B00010049006E007400650072006E0061006C004E0061006D00650000004D006900630072006F0073006F00660074002E0045006E00740065007200700072006900730065004D0061006E006100670065006D0065006E0074002E00530071006C002E00550073006500720044006500660069006E0065006400440061007400610054007900700065002E0064006C006C00000000005C001B0001004C006500670061006C0043006F007000790072006900670068007400000043006F0070007900720069006700680074002000A90020004D006900630072006F0073006F00660074002000320030003100300000000000A0003B0001004F0072006900670069006E0061006C00460069006C0065006E0061006D00650000004D006900630072006F0073006F00660074002E0045006E00740065007200700072006900730065004D0061006E006100670065006D0065006E0074002E00530071006C002E00550073006500720044006500660069006E0065006400440061007400610054007900700065002E0064006C006C0000000000480014000100500072006F0064007500630074004E0061006D00650000000000550073006500720044006500660069006E006500640044006100740061005400790070006500000044000F000100500072006F006400750063007400560065007200730069006F006E00000031002E0030002E0033003700360033002E00320036003800360034000000000048000F00010041007300730065006D0062006C0079002000560065007200730069006F006E00000031002E0030002E0033003700360033002E0032003600380036003400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000003000000C000000C03400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000);
set        @ClrName = CONVERT(NVARCHAR(4000), 'Microsoft.EnterpriseManagement.Sql.UserDefinedDataType');

**To Check/Reproduce**
1. Check the Operations Manager event log on the management server for the presence of event ids 26139 and 33333 both with the above text or the **_0x8013150A_** string in it.
2. From the SQL Server hosting the SQL databases run the following query and check if the above assemblies are present:

> USE Master;
> GO
> SELECT * FROM sys.trusted_assemblies;
> GO

**Comment by gewarren** [comment]
@JYOTHIRMAISURI Can you take a look at this issue?

**Comment by JYOTHIRMAISURI** [comment]
@gewarren thanks for sharing the issue. We have updated the required docs in the recent past to include  detailed script. Here are the docs updated. 

https://docs.microsoft.com/en-us/system-center/scom/upgrade-sqlserver-2019-operations-manager?view=sc-om-2019&branch=master#optional---enable-clr-strict-security 

https://docs.microsoft.com/en-us/system-center/scom/upgrade-sqlserver-2017-opsmgr?view=sc-om-2019&branch=master#optional---enable-clr-strict-security 

https://docs.microsoft.com/en-us/system-center/scsm/system-requirements?view=sc-sm-2019&branch=master#enable-clr-strict-security

https://docs.microsoft.com/en-us/system-center/scom/upgrade-sqlserver-2017-opsmgr?view=sc-om-1807.

Hope this resolves the issue.

#please-close
