### ISSUE TITLE
Broken link to Whitepaper

### ISSUE THREAD

**Issue by oex-pbi** [MicrosoftDocs/feedback#3212]
Broken link on 

https://docs.microsoft.com/en-us/previous-versions/dynamicscrm-2016/developers-guide/gg309524(v=crm.8)

More overview information about security can be found in this white paper: Microsoft Dynamics CRM Online security and compliance planning guide.

**Comment by rootsmusic** [comment]
@oex-pbi "We're no longer updating this content regularly."
#please-close
