### ISSUE TITLE
Remove "or sets" from https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicebus.messaging.brokeredmessage.enqueuedtimeutc?view=azure-dotnet&source=docs

### ISSUE THREAD

**Issue by jaslawinMs** [MicrosoftDocs/feedback#3215]
**Describe the bug**
https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicebus.messaging.brokeredmessage.enqueuedtimeutc?view=azure-dotnet&source=docs describes read only property, but the description reads "Gets or sets"

**To Reproduce**

**Expected behavior**
Remove "or sets"

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by gewarren** [comment]
This issue was moved to Azure/azure-docs-sdk-dotnet#1676
