### ISSUE TITLE
SSIS 2017 package model upgrade failure

### ISSUE THREAD

**Issue by smrtreddyk** [MicrosoftDocs/feedback#322]
# SSIS 2017 Upgrade failed

We are upgrading our ssis packages from 2012 to 2017 and all our script components failing with error "the type or namespace name 'dts' does not exist in the namespace 'microsoft.sqlserver'". which is a generic error which happens when an assembly is missing but i think the root cause is because of inconsistency between the assemblies

## Error:
 "The primary reference "Microsoft.SqlServer.ScriptTask, Version=14.0.0.0, Culture=Neutral, PublicKeyToken=89845dcd8080cc91" could not be resolved because it has an indirect dependency on the assembly "Microsoft.SqlServer.ManagedDTS, Version=14.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91" which was built against the ".NETFramework,Version=v4.5" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.0".

**Comment by dend** [comment]
Hello! Unfortunately, we can't help you with this issue in this forum, as we can only triage docs.microsoft.com-related issues. We recommend starting with [this forum](https://social.msdn.microsoft.com/Forums/sqlserver/en-US/home?forum=sqlintegrationservices) to help address the question.
