### ISSUE TITLE
Reply to archived Technet articles should be possible

### ISSUE THREAD

**Issue by jmbreuer** [MicrosoftDocs/feedback#3225]
**Is your feature request related to a problem? Please describe.**

Often times, when I have a specific problem I'll find articles from other people struggling with the same thing on Technet. More often than not, those are archived, and there's no way to add the solution I eventually find to a place that already comes up to others looking for information on such problems with search engines.

**Describe the solution you'd like**

Some way to "reply" to archived articles / threads. I understand they aren't supposed to be "active", maybe something like:

Every archived thread can have ONE reference to an ACTIVE thread where its discussion is continued. If such an active thread already exists, answers can be added there. If not, it should be possible to attach a new thread to archived articles as a continuation.

**Describe alternatives you've considered**

Simply "not archiving" content certainly also would solve this particular issue. To a limited degree, a function to reach the original authors would also help (them), but not leave the solution for search engines to find.

**Comment by rootsmusic** [comment]
@jmbreuer Technet has closed at https://docs.microsoft.com/en-us/teamblog/msdn-technet-english-forums-closure
