### ISSUE TITLE
Delta does't work in AzureChina

### ISSUE THREAD

**Issue by Vinctor** [MicrosoftDocs/feedback#3228]
in my application, i try to login account with Azure China 21Vianet.
First, i login success with MSAL,
then i try to load data from server with
```
https://microsoftgraph.chinacloudapi.cn/v1.0/me/mailFolders/microsoft.graph.delta
```
later,i get  `400:Bad Request`  error, and the message
```
{
      "error": {
        "code": "ErrorInvalidIdMalformed",
        "message": "Id is malformed.",
        "innerError": {
          "date": "2020-10-28T11:18:25",
          "request-id": "9a6b40af-c64d-4409-b680-6beb6a85d41d",
          "client-request-id": "a9e73033-5341-46f0-a9ce-4fbdc1a8fd3e"
        }
      }
    }
```
Doesn't the AzureChina server support the `mailFolders Delta`?
Or has another  way to make it work?

**Comment by rootsmusic** [comment]
@Vinctor Please ask product support or in support forums.
