### ISSUE TITLE
Windows CE 5.0, 6.0 and compact 7 documents show no figures

### ISSUE THREAD

**Issue by nbkawa-sh** [MicrosoftDocs/feedback#323]
## Issue Details

The following web page says "The following illustration shows the layered NDIS miniport driver architecture." at line 6, but no figures are shown.

https://docs.microsoft.com/en-us/previous-versions/windows/embedded/ee483408%28v%3dwinembedded.60%29

This is not only on this page, but all of windows ce 5.0, 6.0 and compact 7 documents.
Please show figures or back to original MSDN documents.

**Comment by Powerhelmsman** [comment]
@nbkawa-sh I file a internal bug to track it. Will post you the status later.

**Comment by dend** [comment]
Adding @Khairunj who can follow-up on this issue.

**Comment by nbkawa-sh** [comment]
Dear all,
I found the problem in the above URL has been fixed. May I close this issue?

**Comment by dend** [comment]
Absolutely @nbkawa-sh - thanks for the feedback once again!
