### ISSUE TITLE
Missing document or link about Exchange online

### ISSUE THREAD

**Issue by ttkuc1** [MicrosoftDocs/feedback#3237]
**Describe the bug**
The docs about Exchange Online Resource mailbox can not be seen with a 404 error

**To Reproduce**
tried to access below docs but got a 404 error
both English and Japanese version got error
https://docs.microsoft.com/en-us/exchange/recipients-in-exchange-online/manage-room-mailboxes
https://docs.microsoft.com/en-us/exchange/recipients-in-exchange-online/manage-equipment-mailboxes
https://docs.microsoft.com/ja-jp/exchange/recipients-in-exchange-online/manage-room-mailboxes
https://docs.microsoft.com/ja-jp/exchange/recipients-in-exchange-online/manage-equipment-mailboxes

**Expected behavior**
they can be seen

**Desktop (please complete the following information):**
 - OS: Windows 10 pro 1909
 - Browser Microsoft Edge
 - Version 86.0.622.51 (64bit)

**Additional context**

**Comment by Takas0522** [comment]
I reported on the "ja-jp" site, but the "en-us" site was in the same state.
https://docs.microsoft.com/en-us/graph/tutorials/aspnet-core?tutorial-step=1

**Comment by gewarren** [comment]
This issue was moved to MicrosoftDocs/OfficeDocs-Exchange#2357
