### ISSUE TITLE
Ukrainian localization auto-translates to Russian

### ISSUE THREAD

**Issue by Androniq** [MicrosoftDocs/feedback#324]
When I navigate to the page https://docs.microsoft.com/xamarin/cross-platform/app-fundamentals/code-sharing , it correctly detects that I have Ukrainian browser settings (adds uk-ua into the URL), but then it shows me auto-translation to Russian instead of Ukrainian.

Also, probably the language name at the bottom of the page contains a typo: Україньска, should be Українська

**Comment by Powerhelmsman** [comment]
@SonjaSaltzman Can you take a look at this?

**Comment by SonjaSaltzman** [comment]
@Androniq I believe you have your language picker (cookie) set to Russian, and as we do not support Ukrainian localization at this point, it falls back to Russian.  Example: I have selected German with the language picker (bottom left of page) and when I click the link it goes to the German page.  If you do not like the machine translation, you can also quickly switch to English text by clicking the toggle in the right hand navigation:
![image](https://user-images.githubusercontent.com/15201704/39315651-0a97d1a0-492c-11e8-9778-bbaa09675874.png)
@swgupt - Swati, could you please check into the Ukrainian language typo and fix?

**Comment by SonjaSaltzman** [comment]
@swgupt - could you please follow up on this?

**Comment by Powerhelmsman** [comment]
@swgupt The issue still not fixed. Can you double check? @SonjaSaltzman for awareness.

**Comment by DavidPrio** [comment]
Hi @SonjaSaltzman can you please assign the issue to me so we can take care of it? (I do not have access to assign it myself). Thanks!

**Comment by SonjaSaltzman** [comment]
@DavidPrio - done

**Comment by Sara-Nicolini** [comment]
@Powerhelmsman, please assign the issue to @nokura

**Comment by Powerhelmsman** [comment]
@Sara-Nicolini Assigned to @nokura

**Comment by nokura** [comment]
Site engineer is working on fixing typo for Ukrainian language name in the footer.

**Comment by LisandroSu** [comment]
Hi @nokura,

Is there an update for this issue?

Thanks!
