### ISSUE TITLE
Code example for dotnet core library is wrong

### ISSUE THREAD

**Issue by zlidzen** [MicrosoftDocs/feedback#3245]
**Is your feature request related to a problem? Please describe.**
Where : 
https://docs.microsoft.com/en-us/dotnet/core/tutorials/library-with-visual-studio-code#add-a-console-app-to-the-solution
In pp.3 'Open ShowCase/Program.cs and replace all of the code with the following code.'

What : 
Presented code example doesn't compile.

Why :
This method "void ResetConsole()" doesn't contain declaration or input parameter of "row".

**Describe the solution you'd like**
add input parameter in "void ResetConsole()" -> "void ResetConsole(int row)"
update call this method "ResetConsole();" -> "ResetConsole(row)"

**Comment by gewarren** [comment]
This issue was moved to dotnet/docs#21597
