### ISSUE TITLE
Document the use of HTML elements in System.Web.UI.WebControls.TreeNode.Text

### ISSUE THREAD

**Issue by mikebk** [MicrosoftDocs/feedback#325]
# Idea Title

 Document the use of HTML elements in System.Web.UI.WebControls.TreeNode.Text

## Issue Details

The System.Web.UI.WebControls.TreeNode.Text property accepts HTML elements but there appears to be no documentation on the effects of including these html fragments.

There are two problems with this: First, the documentation doesn't include the normal warning about cross Site Scripting vulnerabilities (you'll notice the example below includes some HtmlEncoding). Second, there's no description of how to adjust the visual appearance of the text.

As the property doesn't expose any methods/properties to adjust the visual appearance of the text
there have been quite a number of developers posting inquiries (e.g., [https://forums.asp.net/t/1241062.aspx?TreeNode+text+color], [https://forums.asp.net/t/1342537.aspx?Change+TreeView+treenode+background+color])  about how to set the color of the text. The typical solution is along the lines of 'childNode.Text = "<div style='color:Red'>" + childNode.Text + "&lt;/div>";"

Mike

**Comment by Powerhelmsman** [comment]
close as duplicate with #326
