### ISSUE TITLE
Update PowerShell instructions with correct syntax

### ISSUE THREAD

**Issue by vthn** [MicrosoftDocs/feedback#3250]
**Describe the bug**
https://docs.microsoft.com/en-us/partner-center/revoke-reinstate-csp

Step 5 instructs readers to use:
`New-AzureRoleAssignment`

This results in the following PowerShell error:
```
New-AzureRoleAssignment : The term 'New-AzureRoleAssignment' is not recognized as the name of a cmdlet, function,
script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is
correct and try again.
```

**To Reproduce**
1. Open PowerShell and sign-in to Azure using `Connect-AzAccount`
2. Try to use `New-AzureRoleAssignment`

**Expected behavior**
The correct command is: `New-AzRoleAssignment`
as referenced here: https://docs.microsoft.com/en-us/powershell/module/az.resources/new-azroleassignment?view=azps-5.0.0

**Desktop**
 - OS: Windows 10
 - Client: PowerShell
 - Version: 5.1.19041.546

**Comment by rootsmusic** [comment]
@vthn Please move this issue to https://github.com/MicrosoftDocs/partner-center-docs-powershell/issues

**Comment by vthn** [comment]
> @vthn Please move this issue to https://github.com/MicrosoftDocs/partner-center-docs-powershell/issues

That's the Partner Center PowerShell module documentation, but the issue was related to the general Partner Center docs. I believe the repo for those docs is private. 

At any rate, [it looks to be resolved in the current version](https://docs.microsoft.com/en-us/partner-center/reinstate-csp) (November 11, 2021).
