### ISSUE TITLE
Feedback for one specific article

### ISSUE THREAD

**Issue by teomonda** [MicrosoftDocs/feedback#3261]
**Describe the bug**
Actually i wanted to share feedback on the information on a specific page, where i can no longer find the option to share feedback on the page.
Even if i am logged in as microsoft submitter, i cannot see the contributors of the article.

**To Reproduce**
1. Go to https://docs.microsoft.com/en-us/skypeforbusiness/audio-conferencing-in-office-365/setting-up-the-meeting-migration-service-mms
the first paragraph indicates the Meeting Migration Tool as an alternative when the mailboxes are in Exchange on-premise.

**Expected behavior**
A Note should be added mentioning that this tool will not migrate meetings to Teams but only to Skype online.
AFAIK there is no tool migration from Skype online to Teams, while the mailboxes are on-premise, so these meetings have to be recreated manually unfortunately. Which is not very clear from the article so one may get here with high hopes

**Comment by rootsmusic** [comment]
@teomonda Please move this issue to https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues

**Comment by teomonda** [comment]
hello @rootsmusic , thanks for coming back to me.
In the meantime, i see that the note to the meeting migration tool has been removed so there is no longer a misunderstanding.
I will close this one, as i am not exactly sure how to move the issue to the section you reccomended.
