### ISSUE TITLE
Lesson 5-2: Enable and configure package configurations

### ISSUE THREAD

**Issue by Joseph-McFadden** [MicrosoftDocs/feedback#3264]
**Describe the bug**
https://docs.microsoft.com/en-us/sql/integration-services/lesson-5-2-enabling-and-configuring-package-configurations?view=sql-server-ver15

Visual Studio 2019.  In "Enable package configurations" step 2 to "Convert to Package Deployment Model" dialog fails.  Reason is  the presence of "project connection manager" created in Lesson 1-3.

To proceed with "Convert to Package Deployment Model" the connection manager had to be delete.  After conversion had to manually re-add connections to each OLE DB connection manager.

Is this a bug or work around?  I leave it to you to decide.

**To Reproduce**

**Expected behavior**

**Screenshots**
Project (menu) --> Convert to Package Deployment Model
![image](https://user-images.githubusercontent.com/16122259/98977640-104cc500-24d6-11eb-8e42-9adec28e6310.png)

![image](https://user-images.githubusercontent.com/16122259/98976997-49386a00-24d5-11eb-945e-62fd4304e0ae.png)

Error message preventing conversion to Package Deployment Model
![image](https://user-images.githubusercontent.com/16122259/98977032-581f1c80-24d5-11eb-8644-451a96afd39f.png)

Connection Managers present in Project SSIS Tutorial created in 
![image](https://user-images.githubusercontent.com/16122259/98977327-bc41e080-24d5-11eb-9201-d75c7b0f2dd1.png)

![image](https://user-images.githubusercontent.com/16122259/98978172-cadcc780-24d6-11eb-9f7f-cf105c0a44f7.png)

The lookup transformations and OLE DB destination are subsequently broke.
![image](https://user-images.githubusercontent.com/16122259/98978323-08d9eb80-24d7-11eb-9fe2-39cb87e0a52d.png)

The OLE DB Connection Manager for the three objects had to reset.
![image](https://user-images.githubusercontent.com/16122259/98978479-463e7900-24d7-11eb-8e76-840e652667bb.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by gewarren** [comment]
This issue was moved to MicrosoftDocs/sql-docs#5729
