### ISSUE TITLE
Sample inputfile code has a reference to something called InputFileChangeEventArgs

### ISSUE THREAD

**Issue by DataJuggler** [MicrosoftDocs/feedback#3267]
I am trying to update my BlazorFileUpload component to .Net 5, and use the FileUpload.razor that was listed here:

https://github.com/dotnet/AspNetCore.Docs/tree/master/aspnetcore/blazor/file-uploads/samples/

I copied the code, and I can get everything to compile after adding some additional using statements, but this one I cannot find.

I don't know how to find the listed InputFileChangeEventArgs file.

Please include instructions for this and how to find it.

Your 'How To Download' instructions are not very helpful as a sample project should be a single clonable project, and I haven't found that.

**Comment by gewarren** [comment]
This issue was moved to dotnet/AspNetCore.Docs#20618
