### ISSUE TITLE
Broken file in Ru-version (some codes seems to be missing)

### ISSUE THREAD

**Issue by ccclxv** [MicrosoftDocs/feedback#327]
Go to https://docs.microsoft.com/ru-ru/aspnet/core/tutorials/razor-pages-vsc/model#comments-container

Добавление класса контекста для базы данных
Добавьте следующий производный класс DbContext с именем MovieContext.cs в папку Models: [!code-csharpMain]

This file missing:
https://docs.microsoft.com/ru-ru/aspnet/core/tutorials/razor-pages/razor-pages-start/snapshot_sample/RazorPagesMovie/Models/MovieContext.cs

**Comment by Powerhelmsman** [comment]
@SonjaSaltzman Can you work on this broken link?

**Comment by SonjaSaltzman** [comment]
@nokura could you please check & fix? thanks!

**Comment by ccclxv** [comment]
missing folder snapshot_sample

**Comment by SonjaSaltzman** [comment]
@v-jacard @nokura could you please follow up?

**Comment by v-jacard** [comment]
@ccclxv, cc @nokura, @SonjaSaltzman,
Thank you for reporting this issue.
We found the root cause in en-us source text. 
We are currently localizing the fixed source files and ETA for fix to be live is Tue May 15th, 2018.

**Comment by Powerhelmsman** [comment]
@ccclxv The issue has been resolved. Please double check.
