### ISSUE TITLE
Link to System.Net.Http namespace has been removed from .Net API Browser navigation menu

### ISSUE THREAD

**Issue by LeighHuff** [MicrosoftDocs/feedback#3276]
The link to the System.Net.Http namespace has been removed or omitted from the .[Net API Browser page](https://docs.microsoft.com/en-us/dotnet/api/?view=net-5.0) for both .Net 5.0 and .Net Core 3.1.  

This is a key library so it is troubling that it has been removed.

**Comment by LeighHuff** [comment]
This is the namespace that is missing from the API Browser menu:
[https://docs.microsoft.com/en-us/dotnet/api/system.net.http?view=net-5.0]

**Comment by gewarren** [comment]
Thanks for reporting this. We're tracking it [internally](https://dev.azure.com/ceapex/Engineering/_workitems/edit/325235).

**Comment by gewarren** [comment]
This is fixed now. Please let me know if you are still seeing missing namespaces.
