### ISSUE TITLE
Office previous versions content links, omits OFF2013/OFF2010/OFF2007

### ISSUE THREAD

**Issue by DonPick** [MicrosoftDocs/feedback#329]
# Idea Title

Add links to docs, for the old TN library content please 

## Issue Details

https://technet.microsoft.com/en-us/library/ee460874.aspx

Older Office versions are documented at TNlib. 
Current OFF2016 deployment guidance documentation, is and always has been sadly lacking in technical detail eg OCT and customization, which is fortunately covered in excellent detail in OFF2013 docs, and those are applicable.
https://docs.microsoft.com/en-us/DeployOffice/
https://docs.microsoft.com/en-au/previous-versions/
Please link this documentation so people can find it!  :)
I like docs/GitHub, but this obvious missing content and no link back to TNlib is very frustrating and totally bewilders new ITPros.

Thanks!

**Comment by Powerhelmsman** [comment]
@DonPick Can you provide the docs site page link you refer to?

**Comment by DonPick** [comment]
I have added links within the issue body :)
The most logical navigational flow I can imagine, is that a visit to;
/DeployOffice/  does not offer a tip/link towards TNlib content for OFF2013.
The /previous-versions/ link in the page footer takes us to very old content but misses pointing us to TNlib for the recently-old content.

**Comment by Powerhelmsman** [comment]
@jwhit-MSFT Can you provide support this feedback? Or do you know who is right contact for office deploy?

**Comment by jwhit-MSFT** [comment]
Adding @DHB-MSFT , who's working on an update for this issue.

**Comment by DHB-MSFT** [comment]
The deployment content for Office 2013, Office 2010, and Office 2007 that's currently on TechNet is in the process of being migrated over to https://docs.microsoft.com. Once it's migrated over, links to it will appear on the Previous Versions page. The content is likely to be there before the end of May.

**Comment by Powerhelmsman** [comment]
@DonPick Thanks for your feedback. As DHB-MSFT said that the deployment content for Office 2013, Office 2010, and Office 2007 will be migrated to Docs site soon.
