### ISSUE TITLE
Online learning path - translation into Italian

### ISSUE THREAD

**Issue by fabriziobagala** [MicrosoftDocs/feedback#3294]
**Describe the bug**
The online learning path for the Italian language is not visible, in its place, there are empty grid items.

**To Reproduce**
1. Go to 'https://docs.microsoft.com/it-it/learn/certifications/azure-fundamentals'
2. Scroll down to 'Due modalità per la preparazione'
3. See error

**Expected behavior**
See the list of learning paths.

**Screenshots**
English

![english](https://user-images.githubusercontent.com/62190484/100098012-b0530880-2e5d-11eb-8763-c226a04c5491.png)

Italian

![italian](https://user-images.githubusercontent.com/62190484/100098033-b943da00-2e5d-11eb-9c1c-0d803dbca164.png)

**Desktop:**
 - OS: macOS Catalina 10.15.7
 - Browser: Microsoft Edge
 - Version: 87.0.664.47

**Smartphone:**
 - Device: iPhone 11
 - OS: iOS 14.2
 - Browser: Safari
 - Version: 14

**Comment by markjulmar** [comment]
Localization is about 1-2 weeks behind publishing - this was fixed a long time ago but never closed :)
