### ISSUE TITLE
Docs as a service

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#33]
the docs platform as SaaS service for others to use.

----------
⚠ Idea migrated from UserVoice

**Created By:** Lijins Joseph
**Created On:** 2018/01/25 16:05:32 +0000
**Votes at Migration:** 1
**Supporters at Migration:** 1

**Comment by dend** [comment]
At this time, this is not the functionality we plan to offer.

**Comment by thewabbit0** [comment]
The approach of having documentation in GIT, using extended markdown for formatting and some kind of magic machinery to build a hierarchical site structure is working surprisingly well. We (the central IT of a university with a staff of ~2,0000) would have a use for it to publish our documentation allowing for feedback and community-created content.
Our current situation similar to what the Docs team is [describing in its blog](https://docs.microsoft.com/en-us/teamblog/introducing-docs-microsoft-com) - although we have a publishing system, it is archaic, cumbersome and hard to get to, so nobody really likes to publish content there. OTOH, the IT staff is familiar with markdown as well as GIT use

Having the Microsoft Docs solution as an Azure service or a standalone-product for internal use seems like a good thing, especially for larger organizations. Please feel encouraged to reconsider. We certainly would look into it if something will be published in the future and will be using some cruel GIT hooks for hand-rolled LaTeX scripts in the meantime.
