### ISSUE TITLE
deploy docs.microsoft.com inside the enterprise

### ISSUE THREAD

**Issue by georgeanoop** [MicrosoftDocs/feedback#330]
# deploy docs document management system for internal documentation  inside the enterprise

## Issue Details
I would like to deploy docs.microsoft.com equivalent inside the enterprise for internal documentation.  is that possible?

**Comment by dend** [comment]
Hi @georgeanoop - while you cannot deploy the entire docs.microsoft.com infrastructure, you can leverage the same components that we use and that are open-source.

See: [DocFX](https://dotnet.github.io/docfx/)
