### ISSUE TITLE
Translation Error for German at RESTORE MASTER KEY section

### ISSUE THREAD

**Issue by Ryetschye** [MicrosoftDocs/feedback#3305]
At https://docs.microsoft.com/de-de/sql/t-sql/statements/restore-master-key-transact-sql?view=sql-server-ver15
you have translated
**ENCRYPTION BY PASSWORD ='password'**
twice instead of **DECRYPTION**

**Comment by gewarren** [comment]
This issue was moved to MicrosoftDocs/sql-docs.de-de#137
