### ISSUE TITLE
It will be useful to have algorithmic complexity of standard operations provided by the .NET library

### ISSUE THREAD

**Issue by katoch** [MicrosoftDocs/feedback#3306]
**Is your feature request related to a problem? Please describe.**
I'm surprised that most microsoft references for .NET library do not provide complexity information for standard operations. In comparison the C++ standard library documentation has this for all standard library operations.

**Describe the solution you'd like**
A brief mention of space/time complexity for operations will be useful in determining optimal solutions while writing code in .NET. The references are not complete without this information in my opinion.

**Describe alternatives you've considered**

**Additional context**

**Comment by gewarren** [comment]
This issue was moved to dotnet/dotnet-api-docs#5179
