### ISSUE TITLE
Cookie authentication without ASP.NET Core Identity 400 Error

### ISSUE THREAD

**Issue by gabriel-rod** [MicrosoftDocs/feedback#3308]
**Describe the bug**
The bug it's 400 error when i want to authenticate with this project https://github.com/dotnet/AspNetCore.Docs/tree/master/aspnetcore/security/authentication/cookie/samples/3.x/CookieSample

**To Reproduce**
1. Execute the project
2. Sign In with the suggested information
3. Write in the url the path to sign in (base url + /account/login), go to that url
4. Try to sign in
5. This result in a 400 error

**Expected behavior**
It should go to Login (httpPost) method and sign in.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version 87.0.4280.66 (Build oficial) (64 bits)

**Comment by gewarren** [comment]
This issue was moved to dotnet/AspNetCore.Docs#20968
