### ISSUE TITLE
API browser page looks unresponsive when the search is slower than a second or so.

### ISSUE THREAD

**Issue by ognyandim** [MicrosoftDocs/feedback#331]
# Idea Title

Some kind of progress indicator should be placed at the [API browser page](https://docs.microsoft.com/en-us/dotnet/api) because it looks like the site is unresponsive during search.

## Issue Details

I type for IComparer<T>, press Enter and there are 1-2 seconds in which nothing moves - Looks like the site is unresponsive.

If the result is delayed by more than 0,5 seconds then a progress bar or some other indicator should appear.

**Comment by dend** [comment]
Thanks for the suggestion, @ognyandim - adding this to the backlog.

**Comment by dend** [comment]
There is now a progress indicator for searches.
