### ISSUE TITLE
Sample Refers a project that does not exist

### ISSUE THREAD

**Issue by oscarjaergren** [MicrosoftDocs/feedback#3311]
**Describe the bug**
https://docs.microsoft.com/en-us/previous-versions/azure/app-service-mobile/app-service-mobile-xamarin-forms-get-started-offline-data

The Azure Mobile App Services refers a sample project but there is no link existing.

Either remove the reference to the project or add back the link.

**Comment by rootsmusic** [comment]
@oscarjaergren "This content has been retired and may not be updated in the future."
#please-close
