### ISSUE TITLE
Progress marker overlapping the search suggestions

### ISSUE THREAD

**Issue by gopkumr** [MicrosoftDocs/feedback#3313]
**Describe the bug**
The course progress/complete icon is overlapping the search suggestions box. This is a low impact UI bug, but its still not a very good experience to see UI elements overlapping. Below is the screenshot

**To reproduce**
1. Navigate to: https://docs.microsoft.com/en-us/learn/
2. Use the top right corner search box to search a text that results in suggestions
3. The suggestions box shows but the progress icons from the page shows on top of the suggestions box

**Expected behavior**
The suggestions box should be displayed above the progress icons

**Desktop**
OS: Windows 10
Browser: Chrome Version 85.0.4183.83 (Official Build) (64-bit)
Screen resolution: 1920x1080

**Screenshot**
![image](https://user-images.githubusercontent.com/1662197/101336505-abb33900-38ce-11eb-9880-165dcc7937e7.png)

**Comment by markjulmar** [comment]
Thanks for reporting this issue - we've got an internal bug logged against it and will be addressing in a future release.
