### ISSUE TITLE
Finding how to return an int from EF6 stored proc

### ISSUE THREAD

**Issue by LJ9999** [MicrosoftDocs/feedback#3316]
This is amazing!!!! I spent the better part of an evening trying to figure out how to return an integer from a stored proc using EF 6.

And I couldn't find jackschitt!!!! I found a million assholes with their hairbrained ideas for how to do it. They threw their half-assed untested crap guesses at the wall but none of it works!!!

This is amazing. Something so simple but there are one million answers. AND THEY"RE ALL EFFING WRONG!

Of course Microsoft docs are worthless. You people couldn't teach addition to a Math Major.

This is typical Microsoft bullshit. After 30 years in IT I'm used to it. You people just C A N N O T simply anything. Everything has to have 20 convoluted ways to accomplish something.

The result is millions of confused developers luckily getting your crap to work and then falsely believing they are experts on it so that they can confuse millions more developers with their solutions unique to them.

Anyway, I just got a kick out of it. 'Frustrating as absolute fuck but what's one developer gonna do except spend the next evening looking for information he should already have.

**Comment by gewarren** [comment]
This issue was moved to dotnet/EntityFramework.Docs#2951
