### ISSUE TITLE
Azure DevOps Extensibility points documentation is not available

### ISSUE THREAD

**Issue by pgurbal** [MicrosoftDocs/feedback#3317]
**Describe the bug**
All links, which were pointing to Azure DevOps Extensibility Points are not working.
Link to original page was: https://docs.microsoft.com/en-us/previous-versions/azure/devops/docs/extend/reference/targets/overview

**To Reproduce**
1. Go to https://docs.microsoft.com/en-us/previous-versions/azure/devops/docs/extend/reference/targets/overview
2. Page is not found

**Expected behavior**
The documentation is available again

**Comment by chcomley** [comment]
Hi @pgurbal, Thanks so much for the heads up on this. We've published the fixes. Thanks again.

**Comment by chcomley** [comment]
Hi @gewarren, Can you please close this issue? Thank you!
