### ISSUE TITLE
fix example code for razor-pages-vsc

### ISSUE THREAD

**Issue by ccclxv** [MicrosoftDocs/feedback#332]
Go to https://docs.microsoft.com/ru-ru/aspnet/core/tutorials/razor-pages-vsc/sql
code-csharp on this page for "MvcMovie", need for "RazorPagesMovie"

**Comment by Powerhelmsman** [comment]
@SonjaSaltzman Can you work on this? En-us version is RazorPagesMovie

**Comment by SonjaSaltzman** [comment]
@nokura Nobuko, can you please have this fixed?
@v-jacard FYI

**Comment by Powerhelmsman** [comment]
@ccclxv It is resolved already. Please double check.
