### ISSUE TITLE
Wrong Code Example for MacOS onedrive plist

### ISSUE THREAD

**Issue by Pgilquin** [MicrosoftDocs/feedback#3321]
in https://docs.microsoft.com/fr-fr/onedrive/deploy-and-configure-on-macos,
the example for AllowTenantList doesn't work...
here it is :
`<key>AllowTenantList</key>
<array>
    <dict>
        <key>TenantId1</key>
        <Bool>True</Bool>
        <key>TenantId2</key>
        <Bool>True</Bool>
    </dict>
</array>
`

when using this example in a plist file (replacing tenantIds), intune reports a syntaxe error.

The good example is 
`
<key>AllowTenantList</key>
<array>
    <dict>
        <key>TenantId1</key>
        <true/>
        <key>TenantId2</key>
        <true/>
    </dict>
</array>
`

It should be the same for BlockTenantList example

I don't know if the issue occurs only in intune.

So many time lost to understand the issue ... would be great nobody else stuck on that.

**Comment by gewarren** [comment]
This issue was moved to MicrosoftDocs/OfficeDocs-SharePoint#2498
