### ISSUE TITLE
GetScanStatus API results in 404

### ISSUE THREAD

**Issue by Mimiix** [MicrosoftDocs/feedback#3324]
**Describe the bug**
Wanted to try this new API and see how it goes. However, i am getting a 404 on request. Even from the "try it" on the page itself. Postman/Powershell report 404.  

**To Reproduce**
1. Go to https://docs.microsoft.com/en-us/rest/api/power-bi/admin/workspaceinfo_getscanstatus
2. Click on "Try it"
3. Try the request.
4. Get 404 error on API. Either the URL is wrong or api is not functioning. 

**Expected behavior**
A working API endpoint

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - Browser Chrome
 - Version 87.0.4280.88 

**Smartphone (please complete the following information):**
- 

**Additional context**
-

**Comment by gewarren** [comment]
@eligr Eli can you take a look?

**Comment by cvillegashak** [comment]
I get this same thing for this and GetScanResult. Is this used at all with Azure Purview by any chance to gather data for scan results? If it is I'm wondering if that's partially why my scans are all failing.

**Comment by eligr** [comment]
Looping in the correct team.

**Comment by eisuissa** [comment]
This is the blog describing the scanner API flow: blog describing the scanner API flow: https://powerbi.microsoft.com/en-us/blog/announcing-new-admin-apis-and-service-principal-authentication-to-make-for-better-tenant-metadata-scanning/
In regards to the scan status API, which is part of this flow, we just released a patch, hopefully, it'll resolve your issue.

**Comment by cvillegashak** [comment]
@eisuissa It now seems to work after the patch for the scanstatus and scanresults with no 404! 👍

**Comment by gewarren** [comment]
Closing the issue since the 404 is resolved.
