### ISSUE TITLE
Example for Process.EnableRaisingEvents Property (and for ExitTime) is incorrect, InvalidOperationException is thrown on access to StartTime

### ISSUE THREAD

**Issue by apegushin** [MicrosoftDocs/feedback#3325]
Example for Process.EnableRaisingEvents (and ExitTime) Property shows how to handle 'Exited' event. In the handler process.StartTime is accessed, which throws InvalidOperationException for processes that are not running (which is 100% true for the process that Exited). Examples need to be revised and access to StartTime should be removed. I'm seeing this on WSL2/Ubuntu, but StartTime property documentation suggests that this behavior is consistent across OSes.

**Comment by gewarren** [comment]
This issue was moved to dotnet/dotnet-api-docs#5178
