### ISSUE TITLE
System.Collections.List----fast fill

### ISSUE THREAD

**Issue by DreamEnderKing** [MicrosoftDocs/feedback#3326]
Up to now, if I have to fill a list, the best method is 
A.(short)to write one by one
B.(long)to enumerate
but
 
what will happen 
if I could convert the System.Range into System.Collections.List?
Glad for your reply.

**Comment by svick** [comment]
I don't quite understand what you're trying to say. Could you clarify that? Probably the best option is to include examples of the code that you have to write today and the code that you want to write.

**Comment by DreamEnderKing** [comment]
origin: 
List<int> l = new List<int>(new int[]{1, 2, 3, 4});

updated:
List<int> l = new List<int>([1..4]);

**Comment by svick** [comment]
You can already do `Enumerable.Range(1, 4).ToList()` to do that. I don't think adding a constructor that supports `Range` would be particularly useful, especially considering that `Range` can be from the end. E.g. what would be the result of `new List<int>(1..^1)`?
