### ISSUE TITLE
Document shows a 404

### ISSUE THREAD

**Issue by fullers** [MicrosoftDocs/feedback#333]
# Idea Title

The document https://docs.microsoft.com/en-us/azure/multi-factor-authentication/multi-factor-authentication is not showing up.  We were referencing this document for more technical details about multi-factor authentication.  Currently, I have not found a better document to replace the link.

## Issue Details

Can you either restore this document or point me in the direction of the new document?

**Comment by fullers** [comment]
I found this document https://docs.microsoft.com/en-us/azure/active-directory/authentication/multi-factor-authentication.

**Comment by Powerhelmsman** [comment]
@fullers Where did you find the first link, by search, or somewhere else?

**Comment by fullers** [comment]
@Powerhelmsman I found the first link by a google search.  Same for the second link.

**Comment by Powerhelmsman** [comment]
@tysonn Did this link https://docs.microsoft.com/en-us/azure/multi-factor-authentication/multi-factor-authentication retired? It is broken now.

**Comment by dend** [comment]
Assigning this to @MicrosoftGuyJFlo

**Comment by MicrosoftGuyJFlo** [comment]
Resolved this 404 issue earlier today when I noticed it with https://github.com/MicrosoftDocs/azure-docs-pr/pull/39339

**Comment by dend** [comment]
@MicrosoftGuyJFlo please let us know once the fix is live, so we can close this.

**Comment by MicrosoftGuyJFlo** [comment]
This is resolved #please-close
