### ISSUE TITLE
Microsoft Learn incorrect link

### ISSUE THREAD

**Issue by alaskaranger05** [MicrosoftDocs/feedback#3331]
When on the https://techcommunity.microsoft.com/t5/microsoft-learn-blog/bg-p/MicrosoftLearnBlog page and click Learn dropdown, then the Microsoft 365 link, it takes you to the Power Platform page instead of the 365 page. See pics.

**To Reproduce**
1. Go to https://techcommunity.microsoft.com/t5/microsoft-learn-blog/bg-p/MicrosoftLearnBlog
2. Click on Learn
3. Scroll down to 365 and click
4. goes to wrong page

**Expected behavior**
Link should go to Microsoft 365 page instead of Power Platform.

**Screenshots**
2

<img width="850" alt="Screen Shot 2020-12-14 at 7 07 48 PM" src="https://user-images.githubusercontent.com/60782864/102155154-92673b00-3e40-11eb-9faa-a88239a35393.png">
<img width="445" alt="Screen Shot 2020-12-14 at 7 07 35 PM" src="https://user-images.githubusercontent.com/60782864/102155158-94c99500-3e40-11eb-9ede-954034f64a08.png">

**Desktop (please complete the following information):**
 - OS: latest Big Sur 10.1
 - Browser Safari
 - Version latest

**Comment by rootsmusic** [comment]
Fixed.
#please-close
