### ISSUE TITLE
Error in code sample for Schedule and automate backups of SQL Server databases in SQL Server Express

### ISSUE THREAD

**Issue by cairneym** [MicrosoftDocs/feedback#3334]
There is a code error in Example 1 on the docs page "[Schedule and automate backups of SQL Server databases in SQL Server Express](https://docs.microsoft.com/en-us/troubleshoot/sql/admin/schedule-automate-backup-database)"

The code provided is : 
    `// Sqlbackup.bat`    
    `sqlcmd -S .\EXPRESS -E -Q "EXEC sp_BackupDatabases @backupLocation='D:\SQLBackups\', @backupType='F'"`   

However the documentation steps around this and the subsequent examples are for an instance named "SQLEXPRESS" and not "EXPRESS".

I resolved a question in [StackOverflow](https://stackoverflow.com/questions/65316885/error-when-trying-to-schedule-auto-backup-in-sql-server-express/65317737) where the user had followed the text exactly and had received errors.

The code sample should be 
    `// Sqlbackup.bat`    
    `sqlcmd -S .\SQLEXPRESS -E -Q "EXEC sp_BackupDatabases @backupLocation='D:\SQLBackups\', @backupType='F'"`

**Comment by gewarren** [comment]
This issue was moved to MicrosoftDocs/sql-docs#5817
