### ISSUE TITLE
Win10, 1909 disabling drivers (touchscreen, touchpad mouse etc)

### ISSUE THREAD

**Issue by jiggoonline** [MicrosoftDocs/feedback#3339]
I updated my Win10 to Win10, 1909 (via the Windows Update settings), I noticed that it disabled my touchscreen and touchpad mouse features, amongst other features. Kindly help resolve this issue. There are several drivers that have gone missing since this new update took place. I use HP Elitebook 840 G6.
The only option I have now is to reload the OS that came with the laptop and this would take my time. I feel this issue should be addressed with some patches and all.
Please help.

**Comment by rootsmusic** [comment]
@jiggoonline Please ask product support.
#please-close
