### ISSUE TITLE
.NET API Browser shows nothing for "Socket class" as input

### ISSUE THREAD

**Issue by sandersaares** [MicrosoftDocs/feedback#334]
I want to find documentation of the Socket class, so I type "Socket class" into the search with .NET Core 2.0 selected as the filter: https://docs.microsoft.com/en-us/dotnet/api/?view=netcore-2.0&term=Socket%20class

Expected result: Socket class documentation is referenced.

Actual result: "No results"

**Comment by Powerhelmsman** [comment]
@dend Can you follow up?

**Comment by dend** [comment]
Hi @sandersaares - this is actually by design. The .NET API Browser acts as the "IntelliSense in the browser", so we can't _yet_ identify types (e.g. class, like you specified above). If you just use the term `Socket` (like you would in, say, Visual Studio), it will show you the right results.

**Comment by sandersaares** [comment]
Well that's a rather poor design then - consider this feedback on improving the design.

**Comment by dend** [comment]
@sandersaares The `Socket` class is the third in the list:

![image](https://user-images.githubusercontent.com/1389609/39449247-60ebc428-4c7c-11e8-8c9d-84b5b31623f4.png)

That said, we are working on improving this experience with some extra functionality. Stay tuned!
