### ISSUE TITLE
Many links are missing here: https://docs.microsoft.com/en-us/previous-versions/sql/sql-server-guides/dn135328(v=sql.110)#monitoring-alwayson-availability-groups

### ISSUE THREAD

**Issue by sgireddy** [MicrosoftDocs/feedback#3345]
Many links are broken here: https://docs.microsoft.com/en-us/previous-versions/sql/sql-server-guides/dn135328(v=sql.110)#monitoring-alwayson-availability-groups

**Comment by rootsmusic** [comment]
@sgireddy "We're no longer updating this content regularly."
#please-close
