### ISSUE TITLE
"Availability" and "StatusInfo" have a value 0  but CIM schema only defined +ve values for Win32_Bus profile

### ISSUE THREAD

**Issue by ganeshkamath89** [MicrosoftDocs/feedback#3347]
I am using a Windows 10 system.

When I query the WMI on the system for Win32_Bus, the Availability and StatusInfo attributes are returning 0.

In CIM Schema there is no 0 value corresponding to these attribute accepted values. Can you please check if this is really a behaviour?

URL: https://docs.microsoft.com/en-us/windows/win32/cimwin32prov/win32-bus

OS version Windows 10 - 1909 (18363.1139)

**Comment by gewarren** [comment]
@drewbatgit Can you take a look?

**Comment by drewbatgit** [comment]
Though the scope of our feedback channel here on GitHub covers specific documentation fixes, I can help redirect you to the right support channel to get an answer to your question. The community of experts and Microsoft Engineers over at [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-uwp.html) offer timely answers to a multitude of technical questions surrounding windows-uwp.

If you do create a thread over at Microsoft Q&A, it would be fantastic if you could share that link here so I can track the progress and potentially incorporate the technical details into our documentation. Though I'm marking this Issue as closed now, please treat this thread as an open thread for follow-ups. Thanks!
