### ISSUE TITLE
Bug in sample code for "Multi-Select List Boxes – And More!" tutorial

### ISSUE THREAD

**Issue by ghPaulNeumann** [MicrosoftDocs/feedback#3351]
The sample code does not return the selected items from the Multi-Select List-box control.  The "$x" array is empty after the program has executed.   The "+=" operations executed in the functions has no affect on the global "$x" array.
The url for this tutorial is at "https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-powershell-1.0/ff730950(v=technet.10)?redirectedfrom=MSDN"

I converted the code to use a List collection instead of the "$x" array.  The collection can be appended to with the "Add()" method, even from within the functions.  Here is the adjusted sample code:

$items = New-Object System.Collections.Generic.List[System.Object]

[void] [System.Reflection.Assembly]::LoadWithPartialName("System.Windows.Forms")
[void] [System.Reflection.Assembly]::LoadWithPartialName("System.Drawing")

$objForm = New-Object System.Windows.Forms.Form
$objForm.Text = "Data Entry Form"
$objForm.Size = New-Object System.Drawing.Size(300,200)
$objForm.StartPosition = "CenterScreen"

$objForm.KeyPreview = $True

$objForm.Add_KeyDown({if ($_.KeyCode -eq "Enter")
    {
        foreach ($objItem in $objListbox.SelectedItems)
        {
           $items.Add($objItem)
        }
        $objForm.Close()
    }
    })

$objForm.Add_KeyDown({if ($_.KeyCode -eq "Escape")
    {$objForm.Close()}})

$OKButton = New-Object System.Windows.Forms.Button
$OKButton.Location = New-Object System.Drawing.Size(75,120)
$OKButton.Size = New-Object System.Drawing.Size(75,23)
$OKButton.Text = "OK"

$OKButton.Add_Click(
{
   foreach ($objItem in $objListbox.SelectedItems)
   {
      $items.Add($objItem)
   }
   $objForm.Close()
})

$objForm.Controls.Add($OKButton)

$CancelButton = New-Object System.Windows.Forms.Button
$CancelButton.Location = New-Object System.Drawing.Size(150,120)
$CancelButton.Size = New-Object System.Drawing.Size(75,23)
$CancelButton.Text = "Cancel"
$CancelButton.Add_Click({$objForm.Close()})
$objForm.Controls.Add($CancelButton)

$objLabel = New-Object System.Windows.Forms.Label
$objLabel.Location = New-Object System.Drawing.Size(10,20)
$objLabel.Size = New-Object System.Drawing.Size(280,20)
$objLabel.Text = "Please make a selection from the list below:"
$objForm.Controls.Add($objLabel)

$objListbox = New-Object System.Windows.Forms.Listbox
$objListbox.Location = New-Object System.Drawing.Size(10,40)
$objListbox.Size = New-Object System.Drawing.Size(260,20)

$objListbox.SelectionMode = "MultiExtended"

[void] $objListbox.Items.Add("Item 1")
[void] $objListbox.Items.Add("Item 2")
[void] $objListbox.Items.Add("Item 3")
[void] $objListbox.Items.Add("Item 4")
[void] $objListbox.Items.Add("Item 5")

$objListbox.Height = 70
$objForm.Controls.Add($objListbox)
$objForm.Topmost = $True

$objForm.Add_Shown({$objForm.Activate()})
[void] $objForm.ShowDialog()

Write-Host "`nItems selected from the Multi-Select listbox are:"

$items.ToArray().ForEach({ $ctr=1+$items.IndexOf($_); "$ctr) $_" })

**Comment by rootsmusic** [comment]
@ghPaulNeumann "	We're no longer updating this content regularly."
