### ISSUE TITLE
Floating horizontal scrollbar for tables and content that is too wide

### ISSUE THREAD

**Issue by bombledmonk** [MicrosoftDocs/feedback#336]
# Idea Title

Floating horizontal scrollbar for tables and content that is too wide.

## Issue Details

It's nice to be able to scroll tables, but per [this blog post](https://docs.microsoft.com/en-us/teamblog/release-notes-march-2018#scrolling-tables), having to vertical scroll down to the bottom of the table to horizontal scroll is cumbersome, especially when you lose the headers.  Something similar to https://github.com/Amphiluke/floating-scroll is one example of such functionality.

**Comment by Powerhelmsman** [comment]
@ShevaDas Can you follow up this suggestion?

**Comment by ShevaDas** [comment]
@bombledmonk thanks for the feedback! If you have a trackpad, you should be able to horizontally scroll from anywhere in the table right now. For non-trackpad users, I've filed an issue in our internal work tracker to add horizontal floating scrollbars and will follow up here when it's completed.

**Comment by ShevaDas** [comment]
Also see #406

**Comment by dendeli-msft** [comment]
Thank you for the feedback! I've opened an internal issue for us to track.

At this time, we have no concrete timelines or commitments for this change, however we'll make sure that we do our due diligence in assessing the impact and importance of the feature.
