### ISSUE TITLE
Force Proxy Credentials Popup

### ISSUE THREAD

**Issue by Sdhadmin** [MicrosoftDocs/feedback#3372]
Hi

Can anyone help, please?
On a domain Win 10 device, can the proxy credentials popup be forced to appear if a new internet session is refused?  For instance if a piece of software looks for licence verification. 
Storing credentials in Credentials manager does not help

Many thanks

**Comment by rootsmusic** [comment]
@Sdhadmin Please ask product support or in support forums.
