### ISSUE TITLE
"Get help with this" on Safe Links v2 policy goes to missing page.

### ISSUE THREAD

**Issue by Absoblogginlutely** [MicrosoftDocs/feedback#3376]
Attempting to read the "Get help with this" link when attempting to add blocked urls to the Safe links policy generates a 404

**To Reproduce**
1. Go to https://protection.office.com/safelinksv2
2. Click on Global Settings. Click on Get Help with this.
3. Site links to https://go.microsoft.com/fwlink/?linkid=854401
4. This redirects to a missing page https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/set-up-a-custom-blocked-urls-list-wtih-atp
5. Changing url to https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/set-up-a-custom-blocked-urls-list-with-atp also fails.

**Expected behavior**
Link through to correct page that describes more details on blocked urls and using wildcards in the block list.

**Screenshots**
![image](https://user-images.githubusercontent.com/21364480/104248341-4dcac180-5437-11eb-8ff9-93babf55aae3.png)
![image](https://user-images.githubusercontent.com/21364480/104248365-5cb17400-5437-11eb-91a9-807b4d7e69f1.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - Browser Modern Edge
 - Version 89.0.752.1

**Comment by gewarren** [comment]
@markjjo Can you take a look or transfer the issue to https://github.com/MicrosoftDocs/microsoft-365-docs?

**Comment by markjjo** [comment]
@gewarren Fixed. Updated https://go.microsoft.com/fwlink/?linkid=854401

**Comment by gewarren** [comment]
Thank you Mark!
