### ISSUE TITLE
FONT COLOR IN DARK THEME IS HARD TO SEE

### ISSUE THREAD

**Issue by AnandGanesh7** [MicrosoftDocs/feedback#338]
![bad_ui](https://user-images.githubusercontent.com/10592892/39386649-7767faa4-4a2a-11e8-9977-4c39907ad10b.PNG)

The font of text in dark theme doesn't contrast with background and is hard to see

**Comment by Powerhelmsman** [comment]
@ShevaDas Please follow up with UI designer.

**Comment by ShevaDas** [comment]
@AnandGanesh7 could you please provide a link to the page you're seeing this on?

**Comment by AnandGanesh7** [comment]
https://docs.microsoft.com/en-us/azure/#pivot=products&panel=all

I have a site-wide setting that enables the dark theme automatically for this page. Viewing the above page with the dark theme causes this.

**Comment by ShevaDas** [comment]
Thanks for the info! We're currently in the middle of a hub page redesign and will make sure this gets addressed.

**Comment by ShevaDas** [comment]
cc @dastaffo

**Comment by dend** [comment]
The font color has been modified, therefore closing this issue.
