### ISSUE TITLE
The release date of Visual Studio 2019 version 16.8.4 is incorrect.

### ISSUE THREAD

**Issue by i-annax** [MicrosoftDocs/feedback#3385]
Hi,

In the document:
https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes#visual-studio-2019-version-168-releases

The release date of Visual Studio 2019 version 16.8.4 is incorrect, it should be January 12, 2021. Please correct it.

Thanks.

**Comment by saurabh-biradar** [comment]
Can I fix this issue

**Comment by gewarren** [comment]
@JacquelineWiddis Can you fix this?

**Comment by JacquelineWiddis** [comment]
Fixed.  #please-close
