### ISSUE TITLE
TECHNET MICROSOFT problem

### ISSUE THREAD

**Issue by izmir777** [MicrosoftDocs/feedback#3386]
[](url)
![007](https://user-images.githubusercontent.com/77434781/104565762-345b8c80-5666-11eb-8a75-494f1ff5de42.png)
I cant reply the question in forum.Please give me access. My status is MCP | MCT | MCSA | MCSE | MCEAE | MCSAA | MCAAA | MCASEA | MCAAEA | MCASAE | MCTAA | HCSA | HCSA-NonCCTV | UEWA | RPA | PCNSA | PCNSE.
I want part in forum and answer the question of people.The are drawn castle,and there is not button reply.Please help solve this problem.

**Comment by gewarren** [comment]
I believe that all English TechNet blogs are now read only. See https://docs.microsoft.com/en-us/teamblog/msdn-technet-english-forums-closure. cc @saldana

**Comment by saldana** [comment]
@izmir777 yes, all the English forums are now read only. You can participate in [Microsoft Q&A now](https://docs.microsoft.com/answers). 

Thank you @gewarren for the ping and the link to our blog post!

**Comment by izmir777** [comment]
Thank u very much.

пт, 15 янв. 2021 г. в 22:57, Sandra Aldana <notifications@github.com>:
