### ISSUE TITLE
Microsoft Operating system 12 option to mass convert mass files to e.g. word or excel  

### ISSUE THREAD

**Issue by forozco1** [MicrosoftDocs/feedback#3391]
Wish we have the option to easily future convert mass files (e.g. pdf) into mass files (e.g. word).  instead alternative we could convert on a single unit by single unit conversion.

**Comment by JasonWHowell** [comment]
@forozco1 great idea! Please track it here in the user voice system so you can socialize it and get votes: https://office365.uservoice.com/search?filter=ideas&query=pdf%20conversion

Apparently, others have been discussing this idea as well. Some suggest Acrobat Pro has a feature called Action Wizard. https://community.adobe.com/t5/acrobat/how-do-i-convert-multiple-pdf-to-word-documents/td-p/9262319?page=1
https://community.adobe.com/t5/acrobat/batch-convert-pdf-to-word/td-p/4527671?page=1

#please-close
