### ISSUE TITLE
Windows 10 Insider Preview 21292.1000 (rs_prerelease) Successfully installed on ‎1/‎16/‎2021

### ISSUE THREAD

**Issue by jeland** [MicrosoftDocs/feedback#3393]
**Describe the bug**
Opening Microsoft Solitaire  locks up os on computer that only can be cleared by cycling power on computer and never opening Microsoft Solitaire again.

**To Reproduce**
1. Power on computer and logon.
2. Click on 'Microsoft Solitaire'
3. Can't close app, or do anything on the computer except power cycling and wait for it to come back up.
4. NEVER EVER CLICK ON MICROSOFT SOLITAIRE AGAIN.

**Expected behavior**
I expected the microsoft solitaire to actually work and not bring my computer to its knee's

**Screenshots**
Not going to do it again because it makes you power cycle the computer

**Desktop (please complete the following information):**
 - OS: Windows 10 Insider Preview 21292.1000 (rs_prerelease) Successfully installed on ‎1/‎16/‎2021
 - does not matter
 - does not matter

**Smartphone (please complete the following information):**

**Additional context**
Makes me never upgrade my pc again, or move to a linux base os

**Comment by JasonWHowell** [comment]
@jeland I think the best place to give Windows Insider preview feedback is on their system here https://aka.ms/WIPFeedbackHub/

The docs folks don't have a good way to send it over to them. Thanks for your understand. #please-close
