### ISSUE TITLE
Commercial marketplace certification policies: 'Publisher Attestation' is missing in table of contents

### ISSUE THREAD

**Issue by serverless-me** [MicrosoftDocs/feedback#3396]
**Describe the bug**
Item "1140.6 Publisher Attestation" is missing in table of contents of "Commercial marketplace certification policies"

**To Reproduce**
1. Go to 'https://docs.microsoft.com/en-us/legal/marketplace/certification-policies'
2. Scroll down to 'Teams'
3. See that the item is not in the table of contents
4. Click on 'Teams'
5. Scroll down to 1140.6
6. See that the item exists, but is not in the table of contents

**Expected behavior**
The table of contents should contain "1140.6 Publisher Attestation" 

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - Browser Edge, Chromium

**Smartphone (please complete the following information):**
n/a

**Additional context**
n/a

**Comment by JasonWHowell** [comment]
@anbene @emuench Could you please see if this an easy fix to the top of file TOC on this legal page?

**Comment by JasonWHowell** [comment]
This issue is resolved now. Thanks for bringing it to our attention. 
#please-close 
![image](https://user-images.githubusercontent.com/5067358/106337119-4122d780-6245-11eb-8b12-1f838ef65477.png)
