### ISSUE TITLE
Allow the user to choose locale of help topics to download for offline reading in HelpViewer

### ISSUE THREAD

**Issue by docs-product** [MicrosoftDocs/feedback#34]
Currently (and unless I got it wrong), there is no other way to download content in HelpViewer (for offline reading) in a locale other than the one currently selected in the base product (say VS). That is, if I use the english UI of VS and want to download docs in russian in HelpViewer (HV), I cannot do it. I have to select the russian language for VS, restart VS, then open HV and then I will be able to search for and add the russian conent. 

My suggestion: add a select box for the locale in HV itself and use the chosen locale to connect to the right Web page and download the content in that locale. The locale of the UI in the base product (VS, SQL Server...) should only be used as a proposed default selection in the drop-down list of the select box in HV. 

NOTE: You could use the same select box (this time with multipe choices allowed) to give the user the choice of the locale for the content to display for reading.

----------
⚠ Idea migrated from UserVoice

**Created By:** C.S.
**Created On:** 2018/01/25 06:09:54 +0000
**Votes at Migration:** 1
**Supporters at Migration:** 1

**Comment by Jemash** [comment]
adding @mschulz-msft

**Comment by mschulz-msft** [comment]
Thanks for the feedback. We will look into what the best way would be to implement this feature.

**Comment by Powerhelmsman** [comment]
#log-suggestion @mschulz-msft

**Comment by botcrane** [comment]
🚀 **ATTENTION**: [Internal request](https://ceapex.visualstudio.com/web/wi.aspx?pcguid=7d644393-99ad-41c8-ac53-7fa79294c720&id=22770) logged.

**Comment by mlottner** [comment]
Closing this outstanding issue for now as it was logged and assigned. Feel free to re-open if/as you see a need.
