### ISSUE TITLE
C# interactive tutorials step-advancement doesn't scroll to top

### ISSUE THREAD

**Issue by BillWagner** [MicrosoftDocs/feedback#340]
Go to any of the [C# QuickStarts](https://docs.microsoft.com/en-us/dotnet/csharp/quick-starts/index)

On step 1 of a quick start, scroll to the bottom. Click the next step in the left navigation. The page advances, but the scroll position stays the same. You're not at the top of the page, but rather part way through the content.

**Comment by Powerhelmsman** [comment]
@yunyunyunyun Can you follow up with this issue?

**Comment by barlanmsft** [comment]
@asajohnson @markjulmar heads up

**Comment by dend** [comment]
Ping @yunyunyunyun

**Comment by BillWagner** [comment]
Thanks @Powerhelmsman I verified this is fixed. 🎆
