### ISSUE TITLE
Typo "** AutomaticByPlatform**"→"**AutomaticByPlatform**"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/feedback#3400]
**Link to article:**
 Tell us where exactly a problem occurs.
 "https://docs.microsoft.com/en-us/azure/templates/microsoft.compute/virtualmachinescalesets"

![virtualmachinescalesets](https://user-images.githubusercontent.com/40815708/105151631-865e4f80-5b49-11eb-8f71-1b29f4c16d9c.png)

**Problem:**
What's wrong with the article?
 Typo "** AutomaticByPlatform**"→"**AutomaticByPlatform**"

**Comment by JasonWHowell** [comment]
@tfitzmac could you take a look?

**Comment by tfitzmac** [comment]
#please-close
