### ISSUE TITLE
OpenIdConnect API docs are missing for ASP.NET Core 3.1

### ISSUE THREAD

**Issue by ryanhofdotgov** [MicrosoftDocs/feedback#3402]
**Describe the bug**
The `Microsoft.AspNetCore.Authentication.OpenIdConnect` namespace is missing from the ASP.NET Core 3.1 documentation, as viewed in the [.NET API browser](https://docs.microsoft.com/en-us/dotnet/api/?view=aspnetcore-3.1).

**To Reproduce**
1. Go to https://docs.microsoft.com/en-us/dotnet/api/?view=aspnetcore-3.1
2. Search for `OpenIdConnectHandler` (an example of one specific class in the namespace)
3. Result is error message: `No results`

**Expected behavior**
I would expect similar search results/corresponding documentation that I see when changing the ASP.NET version to other versions. When making the same search query for `OpenIdConnectHandler` while specifying 3.0, I get this [page](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.authentication.openidconnect.openidconnecthandler?view=aspnetcore-3.0). Similarly, when I specify ASP.NET Core 5.0, I get this [page](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.authentication.openidconnect.openidconnecthandler?view=aspnetcore-5.0), respectively.

For ASP.NET 3.1, I've verified that the [corresponding source code for OpenIdConnectHandler exists](https://github.com/dotnet/aspnetcore/blob/1b1646a5a6b6898b0433fd3b7f4f34fbd4b28ef7/src/Security/Authentication/OpenIdConnect/src/OpenIdConnectHandler.cs#L30).

**Desktop:**
 - OS: macOS Mojave
 - Browser: Chrome
 - Version: 87

**Comment by gewarren** [comment]
@jamesnk What is your take on this?

**Comment by gewarren** [comment]
This issue was moved to dotnet/AspNetApiDocs#200
