### ISSUE TITLE
Why in all that is holy is the TechNet site requesting a product name to provide necessary feedback?

### ISSUE THREAD

**Issue by kylemanel** [MicrosoftDocs/feedback#3404]
Why does this site not work when I select 'English (United States);
https://social.technet.microsoft.com/Forums/en-us/newthread?prof=required

When I select 'English (United States)' The 'Forum category' selections disappear, and when I make any other selection, they reappear.

I select 'English (United States)'.

On clicking the 'Submit' button an asterisk appears with the message 'Please select a forum for your thread'; Which cannot be done because this selection explicitly removes them.
PRESENTED OPTIONS: Either select a language I cannot understand, OR not provide a ticket.

**Comment by JasonWHowell** [comment]
The technet forums site is being migrated over to the new Q&A site. 

What forum are you looking for? Odds are there's a tag in this site for that subject matter:

https://docs.microsoft.com/answers/products/

**Comment by rootsmusic** [comment]
@kylemanel TechNet forums are closed at https://docs.microsoft.com/en-us/teamblog/msdn-technet-english-forums-closure

**Comment by JasonWHowell** [comment]
#please-close
