### ISSUE TITLE
null string handling difference between NET Core and NET 5.0

### ISSUE THREAD

**Issue by Ray-Wynn** [MicrosoftDocs/feedback#3406]
parameter null character as string ("\0") allowed in NET Core but not in NET 5.0 as shown below.
``
static void Main(string[] args)
        {            
            byte[] testBytes = { 0x41, 0x42, 0x43, 0x0, 0x0, 0x0, 0x0, 0x0 }; // ABC\0\0\0\0\0
            string testString = Encoding.ASCII.GetString(testBytes);

            int ns = testString.IndexOf("\0");  // .Net Core 3.x = 3 - .Net 5.0 = 0
            int nc = testString.IndexOf('\0');  // .Net Core 3.x = 3 - .Net 5.0 = 3

            Console.WriteLine(string.Format("testString={0}, IndexOf: null string = {1:d} null character = {2:d}", testString, ns, nc));
            Console.ReadKey();
        }
``

**Comment by gewarren** [comment]
This issue was moved to dotnet/docs#22827
