### ISSUE TITLE
Typo in Documentation

### ISSUE THREAD

**Issue by thornsberrysara** [MicrosoftDocs/feedback#3408]
**Problem:** Spacing issue in the following documentation:
https://docs.microsoft.com/en-us/powershell/scripting/dsc/resources/resources?view=powershell-7.1

In the 'Types of Resources' section, there is a missing space between words. 

<img width="789" alt="microsoft-bug-screenshot" src="https://user-images.githubusercontent.com/40149173/105531753-ccd1bc80-5cb7-11eb-86a6-35bafbf3bf07.png">

<br>

**What is _does_ say**
"Windows comes with built in resources and Linux has OS specific resources. There are resources for cross-node dependencies, package management resources, as well ascommunity owned and maintained resources. You can use the above steps to determine the syntax of these resources and how to use them. The pages that serve these resources have been archived under Reference."

<br>

**What it _should_ say**
"Windows comes with built in resources and Linux has OS specific resources. There are resources for cross-node dependencies, package management resources, as well as community owned and maintained resources. You can use the above steps to determine the syntax of these resources and how to use them. The pages that serve these resources have been archived under Reference."

**Comment by JasonWHowell** [comment]
@sdwheeler Maybe you have access to this file or know who does to fix the spacing issue.

**Comment by sdwheeler** [comment]
Copied issue to https://github.com/MicrosoftDocs/PowerShell-Docs/issues/7164. 

#please-close
