### ISSUE TITLE
How to: Restore to a Point in Time - Recommended Version link entirely un-helpful

### ISSUE THREAD

**Issue by engfob** [MicrosoftDocs/feedback#3409]
Starting at https://docs.microsoft.com/en-us/previous-versions/sql/sql-server-2008-r2/ms190982(v=sql.105)?redirectedfrom=MSDN and clicking on **Recommended Version link** brings user to list of generic high level links: https://docs.microsoft.com/en-us/sql/?view=sql-server-ver15.  

Same is true for  Recommended Version links in pages having same banner at top starting with: "This content has been retired and may not be updated in the future."

This on page showing: How to: Back Up a Transaction Log (SQL Server Management Studio):  a common practice

**Comment by JasonWHowell** [comment]
The right link maybe https://docs.microsoft.com/sql/relational-databases/backup-restore/restore-a-sql-server-database-to-a-point-in-time-full-recovery-model?view=sql-server-ver15

@markingmyname @rothja Maybe you could see if this is fixable with a redirect or something.
![image](https://user-images.githubusercontent.com/5067358/105560036-9865fc80-5cc7-11eb-9af4-4d745f164fca.png)

**Comment by rothja** [comment]
#assign:rothja

**Comment by rothja** [comment]
@engfob My apologies for the delay on this. I will be following up soon. Thanks for your patience and your feedback!

**Comment by rothja** [comment]
@engfob I apologize for the very long delay in my follow-up. I did some research on this and found that it seems that "Recommended Version" link is just hard-coded to the current SQL Server documentation set but not specific to this article. That does seem to be confusing, and I will try to share this feedback with our engineering team. In this case, you have to search for the similar article in our current docs. For example, I searched for your first article and found this equivalent in the current SQL Server documentations set [Restore a SQL Server Database to a Point in Time (Full Recovery Model)](https://docs.microsoft.com/en-us/sql/relational-databases/backup-restore/restore-a-sql-server-database-to-a-point-in-time-full-recovery-model?view=sql-server-ver15). I'm sorry for the confusion! 

#please-close

**Comment by engfob** [comment]
Thanks for the reply Jason.  I would call this inaccurate vs. confusing.  I have found this on many pages already.  I would propose a change from ‘Recommended Version’ to ‘General Information’, if these links are not going to be re-directed accurately.

**Comment by rothja** [comment]
@engfob I think this is an excellent suggestion. I will pass this along to our engineering team. Thanks, and sorry again for the confusion!
