### ISSUE TITLE
SQL Server Driver for Linux (Ubuntu 16.04 Xenial) Mirror is DOWN

### ISSUE THREAD

**Issue by covelloz** [MicrosoftDocs/feedback#341]
The following repository mirror that gets added to sources.list is currently down:

https://packages.microsoft.com/config/ubuntu/16.04/prod.list 
https://packages.microsoft.com/ubuntu/16.04/prod/pool/main/m/msodbcsql/

**OS:** Ubuntu 16.04 LTS (Xenial)
**Driver:** Microsoft ODBC Driver 13 for SQL Server

**SQL SERVER DRIVE FOR LINUX DOCUMENTATION PAGE:**
https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-2017

**Comment by Powerhelmsman** [comment]
@Gene Milener @craigg-msft Can you fix it?

**Comment by MightyPen** [comment]
@David-Engel David, can you please take a look at this Issue 341?

**Comment by MightyPen** [comment]
https://icm.ad.msft.net/imp/v3/incidents/details/67755913/home
(Tracked further at this IcM link.)

**Comment by covelloz** [comment]
Thanks, confirming that the issue has been fixed! Feel free to close issue. Thanks for the fast response time!

**Comment by covelloz** [comment]
Sorry, while the mirror is back up online... I'm noticing some packages are missing:

```
: Failed to fetch https://packages.microsoft.com/ubuntu/16.04/prod/pool/main/u/unixodbc-utf16/libodbc1-utf16_2.3.1-2_amd64.deb  404  Not Found

E: Failed to fetch https://packages.microsoft.com/ubuntu/16.04/prod/pool/main/u/unixodbc-utf16/odbcinst1debian2-utf16_2.3.1-2_amd64.deb  404  Not Found

E: Failed to fetch https://packages.microsoft.com/ubuntu/16.04/prod/pool/main/u/unixodbc-utf16/odbcinst-utf16_2.3.1-2_amd64.deb  404  Not Found

E: Failed to fetch https://packages.microsoft.com/ubuntu/16.04/prod/pool/main/u/unixodbc-utf16/unixodbc-utf16_2.3.1-2_amd64.deb  404  Not Found

E: Failed to fetch https://packages.microsoft.com/ubuntu/16.04/prod/pool/main/m/msodbcsql/msodbcsql_13.0.1.0-1_amd64.deb  404  Not Found

E: Failed to fetch https://packages.microsoft.com/ubuntu/16.04/prod/pool/main/m/mssql-tools/mssql-tools_14.0.2.0-1_amd64.deb  404  Not Found

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

**Comment by covelloz** [comment]
@David-Engel Noted thanks! I'll wait it out.

**Comment by dend** [comment]
The packages should now be available! @covelloz
