### ISSUE TITLE
Links to mscat functions broken

### ISSUE THREAD

**Issue by foobar-1024** [MicrosoftDocs/feedback#3410]
**Describe the bug**
A lot of existing pages link to mscat functions are all broken.
E.g. https://docs.microsoft.com/en-us/windows/win32/api/mscat/ 

**To Reproduce**
1. Go to https://docs.microsoft.com/en-us/windows-hardware/drivers/install/installing-a-catalog-file-by-using-cryptcatadminaddcatalog
2. Click on any of the "CryptCATAdminXxx" functions
3. See a page not found error

**Expected behavior**
Expect to see the corresponding documentation for each of the mscat functions

**Desktop (please complete the following information):**
 - OS: Any
 - Browser Any
 - Version N/A

**Comment by johndog** [comment]
All Win32 docs seem to be missing.  Another example:

https://docs.microsoft.com/en-us/windows/desktop/api/handleapi/nf-handleapi-closehandle

Serious problem, probably higher than Pri3

**Comment by JasonWHowell** [comment]
@mcleanbyron do you know who could help fix the broken link/ redirects to the right docs?

**Comment by mcleanbyron** [comment]
Thanks for reporting this issue. My team is investigating. At this point, it does not appear to be all Win32 docs - I just spot-checked a few other areas such as https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-callwindowproca and https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-getcompressedfilesizea, and those are working.

**Comment by mcleanbyron** [comment]
This issue has been resolved. There was a site engineering issue that took down a portion of our Win32 API docs on Friday afternoon, but this was resolved Friday evening.

**Comment by mcleanbyron** [comment]
#please-close
