### ISSUE TITLE
https://docs.microsoft.com/en-us/windows/win32/api/threadpoolapiset/nf-threadpoolapiset-setthreadpooltimer broken

### ISSUE THREAD

**Issue by afilenkov** [MicrosoftDocs/feedback#3415]
Page is shown is search results but points to 404

**Comment by gewarren** [comment]
This is working for me: https://docs.microsoft.com/en-us/windows/win32/api/threadpoolapiset/nf-threadpoolapiset-setthreadpooltimer. Perhaps it was a transient problem. I'll close this issue now, and thanks for reporting.
