### ISSUE TITLE
Class docs - Provide link to source code on GitHub

### ISSUE THREAD

**Issue by robertsundstrom** [MicrosoftDocs/feedback#3416]
As a developer, when viewing the docs for a particular class, I would like to find the source code on GitHub, so that I can easily learn more about the inner workings of the code.

A link to the source file on GitHub.

**Comment by robertsundstrom** [comment]
Just a side note: It would also be nice to see what NuGet package a class is in. Not having to Google the assembly name to find it. You already tell what assembly a class is in.

**Comment by robertsundstrom** [comment]
This is related to or even a duplicate of #433

**Comment by gewarren** [comment]
Since #433 is still open, I'm going to close this as a dupe. Hopefully we can implement this feature.

**Comment by gewarren** [comment]
Great news - the core .NET libraries now have links to source code!
Example: https://learn.microsoft.com/dotnet/api/system.string.chars?view=net-8.0
