### ISSUE TITLE
Sql script is incorrect in tutorial

### ISSUE THREAD

**Issue by IvanKondral** [MicrosoftDocs/feedback#3418]
**Describe the bug**
https://docs.microsoft.com/en-us/sql/integration-services/lesson-1-6-adding-and-configuring-the-lookup-transformations?view=sql-server-ver15
There is a wrong sql query that uses Sales.Currency which has not been described before.
Also in downloaded lesson 1 result this query is different

**Comment by gewarren** [comment]
This issue was moved to MicrosoftDocs/sql-docs#6083
