### ISSUE TITLE
createLink endpoint doesnt work as descriped in the documentation!

### ISSUE THREAD

**Issue by h110m** [MicrosoftDocs/feedback#3419]
**Describe the bug**
If i use the createLink endpoint for drive items (for example '/drives/{driveID}/items/{itemsID}/createLink') with the password flag set in the body of the post request it gives me a invalid request every time (scope and type doesnt matter). I tested this with c# and the graph explorer.

**To Reproduce**
1. Go to 'https://developer.microsoft.com/en-us/graph/graph-explorer'
2. Fill out everything according to the password request in this documentation 'https://docs.microsoft.com/en-us/graph/api/driveitem-createlink?view=graph-rest-1.0&tabs=http#request'
3. Try sending the request and you will get an "invalid request" response along with the status code 400 for bad request

**Expected behavior**
It should create a link for the file with the given password as described in the documentation.

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise
 - Browser: Chrome
 - Version: 87.0.4280.141 (Chrome)

**Additional context**
I dont realy know if this is issue is connected to my account. If so i hope someone could test it and give me feedback on this. I already set the right things in the sharepoint settings so that i can create anonymous links so this shouldn't be the problem. I also already tried it with evry other flag (scope, type, etc.) and with files and folders but none of them did work with the password flag neither in c# or the graph explorer

**Comment by rootsmusic** [comment]
@h110m Please submit feedback by clicking on the button at the doc's bottom (step 2 of this issue).
