### ISSUE TITLE
Cannot Find-Module GroupPolicy

### ISSUE THREAD

**Issue by eljacobsen12** [MicrosoftDocs/feedback#342]
# BUG: Cannot Find-Module GroupPolicy

PowerShell. Unable to Find-Module, Install-Module GroupPolicy. No match was found.

## Issue Details

Trying to find and install the GroupPolicy module on PSGallery and am unable to. Tried to manually find it on the site and it was also missing. Need these cmdlets asap. Tried this from multiple PCs and servers. RSAT are installed and windows features are enabled. PSGallery is a trusted repository. Still no luck.

PackageManagement\Find-Package : No match was found for the specified search criteria and module name 'grouppolicy'. Try 
Get-PSRepository to see all available registered module repositories.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.6.0\PSModule.psm1:1609 char:3
+         PackageManagement\Find-Package @PSBoundParameters | Microsoft ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Microsoft.Power...ets.FindPackage:FindPackage) [Find-Package], Exception
    + FullyQualifiedErrorId : NoMatchFoundForCriteria,Microsoft.PowerShell.PackageManagement.Cmdlets.FindPackage

**Comment by Powerhelmsman** [comment]
@eljacobsen12 Can you provide the page link you refer to?

**Comment by Powerhelmsman** [comment]
Close as no enough information.
