### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by jermy7** [MicrosoftDocs/feedback#3426]
**Describe the bug**
Documentation for OData Client missing https://docs.microsoft.com/en-us/odata/client/getting-started.
I browse OData documentation and when I click OData Client > Getting started I got 404 not found response.

**To Reproduce**
1. Go to 'https://docs.microsoft.com/en-us/odata/webapi/getting-started'
2. Click on 'OData Client > Getting Started'

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Microsoft Edge
 - Version 88.0.705.53 (Official build) (64-bit)

**Comment by JasonWHowell** [comment]
Similar to https://github.com/MicrosoftDocs/feedback/issues/3430

Sorry for the trouble. It looks like it's working again now.

Let us know if you still have trouble with the 404 issues. I'll assume it was a temporary issue and resolve this one.
#please-close

CC: @mumbi-o @habbes
