### ISSUE TITLE
This is an asset that's included in media folder for this article; how do I include it if it's "out of scope"? [error message feedback] provide feedback for v-shtol

### ISSUE THREAD

**Issue by sherrytoly-ms** [MicrosoftDocs/feedback#3428]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

**Problem:**
What's wrong with the error message? For example,
- Is error message clear and actionable?
- Is there a documentation to provide more information?
- If there is a documentation, is it relavent and helpful?
- Is line number correct?
- etc.

**Log code info**
(This is auto filled, no need to modify)

| Severity   | Type   | Code   | Category   | File   | Message   |  Source  | Line   | Time   |
|------------|--------|--------|------------|--------|-----------|----------|--------|--------|
| Warning | User | v-shtol |  | link-out-of-scope | support/previous-versions/winautomation/process-development-tips/databases/how-to-connect-to-a-mongodb-database.md | File 'winautomation/process-development-tips/databases/media/MongoDB.mp4' referenced by link 'media\MongoDB.mp4' will not be built because it is not included in build scope. | | 20, 12 |

**Link to report**
(This is auto filled, no need to modify)

[report url](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C28%5C3b2488b6-5e86-c8af-0c03-e0d9c2cb6ede%5CPullRequest%5C202101281956027084-12%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=BssJbXeF2J0W5rxJK2ISG8VGRJoJx%2BaUlZPfCjxB5gM%3D&st=2021-01-28T19%3A51%3A43Z&se=2021-02-28T19%3A56%3A43Z&sp=r)

**Comment by JasonWHowell** [comment]
.mp4 videos aren't allowed in MicroosftDocs repos at present. You could host them outside and provide a link to the video.

https://review.docs.microsoft.com/en-us/help/contribute/contribute-video-create?branch=master

Hope this helps. Email the contacts in the page if needed.

#please-close
