### ISSUE TITLE
All examples at rest/api/vsts/git/pull%20requests/get%20pull%20requests look the same

### ISSUE THREAD

**Issue by kiewic** [MicrosoftDocs/feedback#343]
# The three examples in the VSTS Pull Requests REST API look the same

The three examples look like this:

![image](https://user-images.githubusercontent.com/874134/39556309-523dbbb6-4e34-11e8-8ea0-85773c7a6403.png)

## Issue Details

I think the *Sample Requests* should be different to accomplish the different examples:

1. Just completed pull requests
2. Pull requests by repository
3. Targeting a specific branch

Though I do not know if the query parameters are supposed to be passed in the query string or as a request payload.

Thanks!

**Comment by dend** [comment]
@erickson-doug @hellosnow can you please take a look?

**Comment by dend** [comment]
@wnjenkin can you please take a look at this item?

**Comment by Powerhelmsman** [comment]
@kiewic Your issue is transferred to vsts-rest-api-specs repo. They will help you there.
