### ISSUE TITLE
404: All documentation under 'https://docs.microsoft.com/en-us/odata/{article}'

### ISSUE THREAD

**Issue by JensWallgren** [MicrosoftDocs/feedback#3430]
All OData client documentation seems to be unreachable.

**Reproduce by:**

1. Navigating to: [https://docs.microsoft.com/en-us/odata/](https://docs.microsoft.com/en-us/odata/)
2. Click on any of the _**"Develop > OData Client"**_ Articles.
3. You reach a 404 page

**Comment by JasonWHowell** [comment]
#asssign:@acangialosi Please take a look at the image which has an issue.

**Comment by JasonWHowell** [comment]
Hi @JensWallgren 
Sorry for the trouble. It looks like it's working again now. 

Let us know if you still have trouble with the 404 issues. I'll assume it was a temporary issue and resolve this one. 
#please-close

**Comment by JensWallgren** [comment]
@JasonWHowell 
Gave it a try now and it's working.
Thanks for me know!
