### ISSUE TITLE
Wrong markings in the documentation

### ISSUE THREAD

**Issue by pengyouak** [MicrosoftDocs/feedback#3431]
**Describe**
page: https://docs.microsoft.com/en-us/visualstudio/extensibility/ux-guidelines/shared-colors-for-visual-studio?view=vs-2019

path:  **“Common shared controls”** - **“Drop-downs and combo boxes”**

Wrongly marked `ComboBoxGlyph` as `ComboBoxGlyphBackground`

**Screenshots**
![image](https://user-images.githubusercontent.com/4636155/106228147-ba123700-6225-11eb-8dab-60d814302c81.png)

**Comment by JasonWHowell** [comment]
@acangialosi please take a look at this image which has an issue.
#assign:acangialosi

**Comment by gewarren** [comment]
This issue was moved to MicrosoftDocs/visualstudio-docs#6381
