### ISSUE TITLE
broken link for server documentation

### ISSUE THREAD

**Issue by seth2740** [MicrosoftDocs/feedback#3435]
go here -> https://docs.microsoft.com/en-us/windows-server/
try to go to the windows insider program for server
returns 404 for https://docs.microsoft.com/en-us/windows-insider/at-work/

**Comment by gewarren** [comment]
@eross-msft Can you fix this link on https://github.com/MicrosoftDocs/windowsserverdocs-pr/blob/master/WindowsServerDocs/index.yml?

**Comment by eross-msft** [comment]
I fixed this link and pushed the change to live. You should see it shortly.

**Comment by eross-msft** [comment]
#please-close
