### ISSUE TITLE
Improving the content of a cmdlet reference article (Stop-SCOMMaintenanceSchedule) for System Center 2019 Operations Manager

### ISSUE THREAD

**Issue by StoyanChalakov** [MicrosoftDocs/feedback#3439]
**Is your feature request related to a problem? Please describe.**
This is a request to correct/update an important article, related to System Center 2019 Operations Manager and setting the Maintenance Mode. The MS Docs article:

**Stop-SCOMMaintenanceSchedule**
https://docs.microsoft.com/en-us/powershell/module/operationsmanager/stop-scommaintenanceschedule?view=systemcenter-ps-2019

which is essential and gives examples on how to stop a maintenance mode schedule in SCOM. 
The problem is that there are no examples and the field is empty (please see the attached screenshot)

**Describe the solution you'd like**
Please make sure there is at least one example and that the example field is not empty. 

**Describe alternatives you've considered**
Enter an example!

**Additional context**
Screenshot is attached
![Capture](https://user-images.githubusercontent.com/25027612/106510264-fddb9980-64ce-11eb-97df-081bd1f3623e.PNG)

**Comment by jpanda11** [comment]
Still no update on this? :(

**Comment by StoyanChalakov** [comment]
> Still no update on this? :(

Unfortunately it looks like this. It seems that all MS Docs improvement suggestion have a pretty low Prio.

**Comment by StoyanChalakov** [comment]
It seems that the issue has been resolved, but this issue has not been updated! Issue is closed now!
