### ISSUE TITLE
Broken links and translation errors in French version of Xamarin Froms Doc

### ISSUE THREAD

**Issue by maeva-rousselot** [MicrosoftDocs/feedback#3442]
On the French version of the Xamarin Forms Doc, several pages have broken links to the dotnet API.

It seems to happen on sub-pages of `https://docs.microsoft.com/fr-fr/xamarin/xamarin-forms` and only on links to sub-pages of `https://docs.microsoft.com/fr-fr/dotnet/api/xamarin.forms`

Also on those pages 'Xamarin Forms' is displayed as `:::no-loc(Xamarin.Forms):::` and the bad link targets looks like `xref::::no-loc(Xamarin.Forms):::.NAME`, so translation issue ?

**To Reproduce**
1. Go to https://docs.microsoft.com/fr-fr/xamarin/xamarin-forms/user-interface/controls/cells
2. First links to ListView and TableView in content are broken, the next links aren't.

**Expected behavior**
First links `ListView `and `TableView ` in the text shoud refer to the API of the corresponding Class (`https://docs.microsoft.com/fr-fr/dotnet/api/xamarin.forms.listview`) as they do in the english version of the page.

Instead the targets are broken (`xref::::no-loc(Xamarin.Forms):::.ListView`)

The second links (`https://docs.microsoft.com/fr-fr/xamarin/xamarin-forms/user-interface/listview/` ) work correctly.

**Desktop :**
 - OS: Win10
 - Browser Chrome , Firefox and Edge
 - Languages :  French + `Čeština`, `日本語`  `레이블` , ... *

**Additional context**
Other pages with this problem * : 
- https://docs.microsoft.com/fr-fr/xamarin/xamarin-forms/user-interface/images
- https://docs.microsoft.com/fr-fr/xamarin/xamarin-forms/user-interface/text/label
- https://docs.microsoft.com/fr-fr/xamarin/xamarin-forms/user-interface/colors
- https://docs.microsoft.com/fr-fr/xamarin/get-started/quickstarts/multi-page

*I did a random quick check, there might be others

**Comment by mairaw** [comment]
There are also some internal configuration that is showing up in the title like no-loc. @JasonCard can you investigate this issue?

**Comment by JasonCard** [comment]
@maeva-rousselot @mairaw Thank you for raising this issue and I'm following up on this.

**Comment by JasonCard** [comment]
@maeva-rousselot These issues are now fixed :)
