### ISSUE TITLE
OOS update unsure procedure

### ISSUE THREAD

**Issue by paololec** [MicrosoftDocs/feedback#346]
# Idea Title
Unsure procedure for security update for Microsoft Office Online Server (example: KB4011023)

## Issue Details

Doc report: "Applying Office Online Server updates or new versions by using the automatic updates process isn't supported with Office Online Server. This is because updates to an Office Online Server must be applied in a specific way, as described in this article"

But on Windows Server 2016 if i click "check update" if download and install security updates automatically without ask nothing !! (very very very bad for production server!!!) So it's seems you can do security update automatically and not is need the procedure in the documentation.
What the right path? And if I do as into doc how I can sure that "check update" non install automatically!?

[https://docs.microsoft.com/it-it/officeonlineserver/apply-software-updates-to-office-online-server#comments-container](url)

**Comment by dend** [comment]
@SerdarSoysal @dstrome can you take a look, please?

**Comment by SerdarSoysal** [comment]
This should really go to @MikePlumleyMSFT .

**Comment by MikePlumleyMSFT** [comment]
Please assign to @lorenahuangliu .

**Comment by lorenahuangliu** [comment]
Hi @paololec currently investigating this issue. Will circle back with details.

**Comment by Powerhelmsman** [comment]
@paololec Is there any updates so far?

**Comment by lorenahuangliu** [comment]
Hi @paololec, I've heard back from the MU team. MU Team has confirmed that the install experience on a server 2016 machine is different than the 2012 R2 server experience.   In this case, the update process automatically installs the updates without any prompt for the user to interact and make the decision to install. They have provided documentation on how to modify this behavior, including disabling (https://docs.microsoft.com/en-us/windows/privacy/manage-connections-from-windows-operating-system-components-to-microsoft-services#bkmk-wu).

**Comment by dend** [comment]
Thanks @lorenahuangliu - will close this issue in the meantime.
