### ISSUE TITLE
Wrong instructions in "Privileged access deployment" documentation for "Create your device use"

### ISSUE THREAD

**Issue by xcabur1** [MicrosoftDocs/feedback#3461]
**Describe the bug**
I think the `name` and probably the `directory role` in the `Create your device user` instruction is wrong because it is exactly the same as in `Create your device administrator user`

**To Reproduce**
1. Go to https://docs.microsoft.com/en-us/security/compass/privileged-access-deployment#azure-ad-users-and-groups
2. Compare the instructions of `Create your device user` and `Create your device administrator user`

**Expected behavior**
`Create your device user`:
`Name` = `Secure Workstation User` not `Secure Workstation Administrator`
`Directory role` = Don't know but `Limited administrator and select the Intune Administrator role` sounds wrong for a user

**Comment by gewarren** [comment]
@kendaleiv Can you take a look at this issue?

**Comment by kendaleiv** [comment]
Good catch @xcabur1 -- it looks like it should be "Secure Workstation User". I don't know what role should be assigned. Maybe @MicrosoftGuyJFlo knows the expected role.

**Comment by MicrosoftGuyJFlo** [comment]
Yeah I guess it is wrong but the UPN is different. These are just test users for you to use. You could call them whatever you want. It doesn't break the scenario. We will update it the next time we go through the docs.

**Comment by MicrosoftGuyJFlo** [comment]
#please-close

**Comment by xcabur1** [comment]
@MicrosoftGuyJFlo have a look at the issue description it's not only about the name, the role looks also wrong. This makes the concept incorrect. Moreover, it is not only a test. The RAMP calls for its implementation.
