### ISSUE TITLE
Broken link in the SF PowerShell doc  

### ISSUE THREAD

**Issue by zhangdingsong** [MicrosoftDocs/feedback#3462]
The link to access Service Fabric PowerShell doc is broken: https://docs.microsoft.com/en-us/powershell/module/servicefabric/?view=azureservicefabricps 

**To Reproduce**
1. Go to 'https://docs.microsoft.com/en-us/powershell/module/servicefabric/?view=azureservicefabricps'
2. See error 404 - Page not found

**Expected behavior**
You should see the list of SF PowerShell commands on the page.

**Additional context**
Workaround: If I add the command into the URL, the link will work. But the reference links on the same page are all broken.
https://docs.microsoft.com/en-us/powershell/module/servicefabric/**get-servicefabricpartitionhealth**?view=azureservicefabricps

**Impact**
Customers cannot use this official document now, this is affecting individual user experience as well. Please fix it ASAP.

**Comment by gewarren** [comment]
@sdwheeler Can you look at this issue?

**Comment by sdwheeler** [comment]
@gewarren I don't own this content. I don't really know who does. @dcaro might know who to contact.

**Comment by dcaro** [comment]
I do not know, @QingChenmsft, @vaishnavk, @juhacket may.

**Comment by sdwheeler** [comment]
The cmdlet reference for this is in Azure/azure-docs-powershell-servicefabric. It appears that @erikadoyle is the owner of that content. It looks like the whole cmdlet reference docset is broken. Probably a configuration problem in the docfx and/or the ops config.

**Comment by erikadoyle** [comment]
This has now been fixed. (The repo had been configured to use our next version build system, however the change in master branch never got merged to live.)

Apologies for the inconvenience! Thanks for reporting the problem.
