### ISSUE TITLE
foreachloop SSIS on azure not reading files from azure file share subdirectory

### ISSUE THREAD

**Issue by khatri034** [MicrosoftDocs/feedback#3465]
I have a SSIS package with For each loop that enumerate on path like C:\folder\folder1\folder2\folder3 and reading all the files from folder3 with search pattern .xlsx and now the same structure is created on azure file share \\storagename\folder\folder1\folder2\folder3 when SSIS package deployed to azure sql Catalog and running same using data factory is not reading the files available at folder3 and saying that foreachloop enumerate empty as I am using UNC path for folder3.

please help me to read files from azure file share subdirectory using SSIS foreach loop.

**Comment by rootsmusic** [comment]
@khatri034 Please ask product support or support forums like https://techcommunity.microsoft.com/t5/sql-server/bd-p/SQL_Server
