### ISSUE TITLE
MSDN search is broken (docs.microsoft.com)

### ISSUE THREAD

**Issue by wilsoncg** [MicrosoftDocs/feedback#3467]
**Describe the bug**
I have tried searching for content on MSDN documentation, but the search seems broken. This used to work correctly, so I'm not sure what's gone wrong.

**To Reproduce**

1. Go to https://docs.microsoft.com/en-us/documentation/
2. Click on 'Search documentation'
3. Type in 'middleware', hit search
4. Receive no results!?

**Expected behavior**
I expected to receive some results

**Screenshots**
![image](https://user-images.githubusercontent.com/1066103/107554528-f6eb1000-6bcd-11eb-9648-a6bb546b8e44.png)

**Desktop (please complete the following information):**
 - OS: Windows10 20H2
 - Browser chrome
 - Version 88

**Comment by makelix** [comment]
See also https://github.com/MicrosoftDocs/feedback/issues/3453

**Comment by gewarren** [comment]
It seems to be working now, so I'll close this issue. Thanks for letting us know. Feel free to comment if you still think it's broken.

**Comment by benghaner** [comment]
Check your Network tab in the browser Dev Tools. For me, this was getting blocked by my ad blocker. 😄
