### ISSUE TITLE
Unable to filter by .Net Framework

### ISSUE THREAD

**Issue by ShawnDigital** [MicrosoftDocs/feedback#347]
# Unable to filter by .Net Framework

Not sure if this is a bug or just an unpleasant UX, but I am unable to properly filter by .Net framework version to see what or if a given type or member is available which seems the likely purpose of browsing a specific api/class version through the tree.

Reproduction:
1. I have netstandard 1.3 selected in the drop down.
2. In the navigation tree I see Environment.UserInteractive which isn't available in 1.3 per intellisense.
3. I click on it and it displays some documentation, however I notice at the top it has switched me to .Net FW 4.7.2 doco with only a nondescript gray/purple bar showing that the requested page is not available in netstandard 1.3 and I've instead been switched to the newest version of the page for the selected element.
4. If I try to change the drop down back to 1.3 it loops me back to the same page due to the same unavailable element being selected. I have to then keep selecting different items in the tree and then changing the drop down until I find one that actually exists in 1.3 in order to go back to netstandard 1.3 doco.

If I select 1.3, I'd expect to see only the 1.3 api in the navigation tree and I certainty don't want to be automatically switched to a different api at all. This is exacerbated by less than obvious warning, and even more so without an easy way to switch back. I also would expect it to update to the nearest neighbor API supporting that element (in this case netstandard 2.0) not the newest one in a completely different API, but that's subjective and really moot because...

If someone was trying to find out where a given class is then they likely are searching by name not browsing the tree and it would be better to implement an 'All Available APIs' option in the drop down for this purpose or maybe a checkbox by the search to include all APIs. Including visual indication in the tree of which APIs it applies to would be helpful too, but since I shouldn't be able to see let alone select an element not my selected API, the only behavior to handle would be if the user changed the API drop down to one that doesn't include the selected tree element. Then changing the selection to to the first available ancestor and displaying the warning would be acceptable behavior.  

![image](https://user-images.githubusercontent.com/8883525/39653712-b877c546-4fb7-11e8-8b55-fcc1c49364ba.png)

**Comment by thedanfernandez** [comment]
@dend Can you take a look?

**Comment by dend** [comment]
@HiGravity thanks for the feedback! What would be your expectation with the page? Since the API is not available in .NET Standard and we don't yet have information on alternative APIs.

**Comment by HiGravity** [comment]
Ideally if I select 1.3, I'd expect to see only the 1.3 api in the navigation tree so all the others points become moot. 
If someone was trying to find out where a given class is then they likely are searching by name not browsing the tree and it would be better to implement an 'All Available APIs' option in the drop down for this purpose or maybe a checkbox by the search box to include all APIs. Theres no visual indication in the tree of which APIs a class applies to and you just in get in a loop of getting switched to a different api, but since I shouldn't be able to see let alone select an element not my selected API, the only behavior to handle would be if the user changed the API drop down to one that doesn't include the selected tree element. Then changing the selection to to the first available ancestor and displaying the warning would be acceptable behavior.

**Comment by dend** [comment]
[Tracking this work internally](https://ceapex.visualstudio.com/Engineering/_workitems/edit/31482).

**Comment by sdmaclea** [comment]
I hit this same issue today.  This current behavior is very annoying.

Here was the issue I was about to write up.

The table of contents is not properly filtered to eliminates API's which are not included in the "Product" I am browsing.

This is irritating when I am trying to write code to conform to a specific API.  Additionally the browser will gratuitously change the API product I am browsing to be "helpful".  This leads to confusion and forces me to constantly reset the Product.

"The requested page is not available for .NET Core 2.1. You have been redirected to the newest product version this page is available for. "

"The requested page is not available for .NET Standard 2.0. You have been redirected to the newest product version this page is available for. "

The redirect banner is also too small.   It happened at least a dozen times until I saw this annoying behavior.

**Comment by sdmaclea** [comment]
> @HiGravity thanks for the feedback! What would be your expectation with the page? Since the API is not available in .NET Standard and we don't yet have information on alternative APIs.

The ideal would be to filter the table of contents.

A temporary solution would be to present a content which said the API was not available for the current product.  It could include a link to manually switch products.  It could include the set of supported products.

**Comment by mairaw** [comment]
@dend @mimisasouvanh @docs-product is there a tracking work item for this?

**Comment by mimisasouvanh** [comment]
@mairaw Yes! We are currently working on this item.

**Comment by keziamicro** [comment]
Hello - reviewing and cleaning up some older feedback/issues. Thanks!
