### ISSUE TITLE
Course Tiles all show blank when loading page.

### ISSUE THREAD

**Issue by drewahearn** [MicrosoftDocs/feedback#3472]
Try to load https://docs.microsoft.com/en-us/learn/ after logging on to my microsoft account.

All Course Tiles on the page are blank and nothing can be selected. See pic:
![BlankLearn](https://user-images.githubusercontent.com/33009623/107718107-0596fd00-6c8a-11eb-8d80-ce3226889011.jpg)

Same result even when trying InPrivate window.

**Comment by StevenPenn** [comment]
I have the same problem too.

**Comment by EvgenSk** [comment]
I have the same issue. And "Browse All" page (https://docs.microsoft.com/en-us/learn/browse/) doesn't have any course and looks blank for about a minute
![image](https://user-images.githubusercontent.com/3060401/107729760-50655300-6d24-11eb-8f6e-44105e76efb5.png)

and then it changes to this:
![image](https://user-images.githubusercontent.com/3060401/107729782-61ae5f80-6d24-11eb-9139-bb9e1e0ad7b4.png)

The same happens in Firefox, Chrome and Opera browsers. Both in standard and private modes.

**Comment by DuncanmaMSFT** [comment]
Hey folks, thanks for the report. This was a temporary outage that has been resolved.
