### ISSUE TITLE
Where is the documentation for VSTS REST API 3.0?

### ISSUE THREAD

**Issue by kiewic** [MicrosoftDocs/feedback#348]
# How to find previous version of VSTS REST API

Recently the VSTS REST API docs were updated to version 4.1, for example: https://docs.microsoft.com/en-us/rest/api/vsts/git/pull%20requests/get%20pull%20requests

Where can I find the version 3.0? I have clicked in the [Previous Version Docs](https://docs.microsoft.com/en-us/previous-versions/) link in the button of the page, but I cannot find the previous versions for VSTS docs. I am guessing there should be a GitHub repository as the [contributing page](https://docs.microsoft.com/en-us/contribute/#quick-edits-to-existing-documents) mentions, but I cannot find the Edit button for these pages. 

Any idea how can I get to the previous _apis/git/repositories/repoId/pullRequests docs?

Thanks!

**Comment by wnjenkin** [comment]
Older versions of our rest apis can be found here https://docs.microsoft.com/en-us/vsts/integrate/legacy-apis/overview?view=vsts .

**Comment by kiewic** [comment]
Hi @wnjenkin , can you help me find the old documentation again? The link now returns 404 Not Found.

**Comment by wnjenkin** [comment]
https://docs.microsoft.com/en-us/vsts/integrate/previous-apis/overview?view=vsts .

**Comment by Powerhelmsman** [comment]
@kiewic Whitney provide a new link. Please take a look.

**Comment by kiewic** [comment]
Nice! Thank you guys

**Comment by dipakdotyadav** [comment]
Hello @wnjenkin, if you can help me with the documentation for below REST API.
`POST https://{accountName}.portalext.visualstudio.com/_apis/continuousdelivery/provisioningconfigurations?api-version=3.2-preview.1`

Thanks
