### ISSUE TITLE
Search is broken (docs.microsoft.com)

### ISSUE THREAD

**Issue by prabhushyja** [MicrosoftDocs/feedback#3487]
**Describe the bug**
When I do a search for "network" in the search bar, I get a message 
"No results
Sorry, we couldn’t find anything that fit your search."

**To Reproduce**
1. Go to 'https://docs.microsoft.com/en-gb/documentation/'
2. Type "network"
3. Click on "Search"
4. The page shows "No results
Sorry, we couldn’t find anything that fit your search."

**Expected behavior**
I would like for search to display results

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise
 - Browser Microsoft Edge (Version 88.0.705.68) /Google Chrome (Version 88.0.4324.150)

**Comment by JHBonarius** [comment]
In my experience everything I try ends up with "No results
Sorry, we couldn’t find anything that fit your search."

**Comment by prabhushyja** [comment]
The search is fixed. Thanks for your help. 
Closing issue.
