### ISSUE TITLE
No long-running scripts

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#35]
You have recently moved a lot of content from TechNet to Docs. The moved pages work unacceptably slowly in IE. It takes a minute or sometimes several minutes for a page to become functional. This doesn't happen if I use Chrome instead. Unless you are trying to force people to move away from IE to Chrome or other 3rd-party browsers, I suggest you fix this issue ASAP.

----------
⚠ Idea migrated from UserVoice

**Created By:** Anonymous
**Created On:** 2018/01/24 15:57:49 +0000
**Votes at Migration:** 1
**Supporters at Migration:** 1

**Comment by dend** [comment]
Duplicate of #3
