### ISSUE TITLE
Where is the documentation for "Widows defender" chrome extension?

### ISSUE THREAD

**Issue by nitin-kau** [MicrosoftDocs/feedback#350]
I would like to see test the extension thoroughly before using it. I would like to know if there is a web API which I can use to get the results.

**Comment by nitin-kau** [comment]
I wanted to test the Windows DefenderBrowser Protection extension given by Microsoft for Google Chrome. The extension provides a facility to know if the website you are visiting is malicious or not.  I wanted to know if there is an API by using which I can know if a particular website is malicious or not. I wanted to test the extension on a big set of urls.

**Comment by dend** [comment]
@nitin-kau I don't believe the team has made any documentation available for that tool, and there are no public announcements about the API.
