### ISSUE TITLE
Poor information for Visual Basic in Microsoft doc.

### ISSUE THREAD

**Issue by chould58** [MicrosoftDocs/feedback#3504]
.
When I search information in Microsoft Doc about Visual Basic, the example in the answer, is often describe with C#.
I check today in the section code example and there is 38 examples pour VB and 1352 examples for C#,
Can you tell me if Microsoft will foresee to discontinue VB in next years ?
Because I wouldn’t arrive face to face with a big wall.
If so, I will begin to translate my code for C#.

**Comment by KalleOlaviNiemitalo** [comment]
From <https://devblogs.microsoft.com/vbteam/visual-basic-support-planned-for-net-5-0/>:

> Going forward, we do not plan to evolve Visual Basic as a language. This supports language stability and maintains compatibility between the .NET Core and .NET Framework versions of Visual Basic. Future features of .NET Core that require language changes may not be supported in Visual Basic.

**Comment by gewarren** [comment]
Thank you @KalleOlaviNiemitalo . I'm going to close this issue now.
