### ISSUE TITLE
WPF Styling with ControlTemplates Sample missing file

### ISSUE THREAD

**Issue by leocb** [MicrosoftDocs/feedback#3506]
In the page [Styling with ControlTemplates Sample](https://docs.microsoft.com/en-us/previous-versions/dotnet/netframework-3.0/ms771597(v=vs.85)) the link `Download Sample` is returning an error 404 - [link here](http://download.microsoft.com/download/f/6/e/f6e32974-726e-4054-96af-9c747bf89a6e/controltemplateexamples.exe)

**Comment by rootsmusic** [comment]
@leocb "We're no longer updating this content regularly."
#please-close
