### ISSUE TITLE
WPF Themed Application Sample missing file

### ISSUE THREAD

**Issue by leocb** [MicrosoftDocs/feedback#3507]
In the page [Themed Application Sample](https://docs.microsoft.com/en-us/previous-versions//ms771613(v=vs.85)?redirectedfrom=MSDN) the link to `Download Sample` is redirecting the the Microsoft download center - [link here](http://go.microsoft.com/fwlink/?linkid=69676&clcid=0x409)

**Comment by rootsmusic** [comment]
@leocb "We're no longer updating this content regularly."
#please-close
