### ISSUE TITLE
Boolean.TrueString french documentation (auto translated) indicates a slighlty wrong value

### ISSUE THREAD

**Issue by Tecknoth** [MicrosoftDocs/feedback#3511]
The french translation of the documentation for Boolean.TrueString is mentioning in Remarks that the field value is equal to "true" ; which is wrong : the value is actually "True". Although not very critical, this might be a bit confusing.

The error doesn't seem to be linked to a particular .NET Version : the page for all versions seems to have the issue.

See https://docs.microsoft.com/fr-fr/dotnet/api/system.boolean.truestring?view=net-5.0

**Comment by gewarren** [comment]
This issue was moved to dotnet/dotnet-api-docs#5432
