### ISSUE TITLE
Download Htmlhelp.exe link broken

### ISSUE THREAD

**Issue by AlexNek** [MicrosoftDocs/feedback#3512]
**Describe the bug**
Download Htmlhelp.exe link broken

**To Reproduce**
1. Go to https://docs.microsoft.com/en-us/previous-versions/windows/desktop/htmlhelp/microsoft-html-help-downloads
2. Click on 'Download Htmlhelp.exe'
3. See error

**Expected behavior**
Download link to Htmlhelp.exe

**Comment by rootsmusic** [comment]
@AlexNek "We're no longer updating this content regularly."
#please-close
