### ISSUE TITLE
Please include C# version numbers for all the operators in the operators section

### ISSUE THREAD

**Issue by FaridAhamat** [MicrosoftDocs/feedback#3513]
**Is your feature request related to a problem? Please describe.**
Sometimes old applications break because I used newer C# syntax out of habit. Would be useful to know which version an operator was introduced. As C# language evolves faster, I think it's useful to know in a glance which version was an operator introduced, rather than read through the lengthy C# changelog.

**Describe the solution you'd like**
Put the C# version it was introduced right after the header text.

Example, in https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/type-testing-and-cast , the explanation is that the "is" operator is introduced from C# 7.0, but it's better to put it on the header next to the text "is operator" to allow for quick glance.

**Describe alternatives you've considered**
No other idea.

**Additional context**

**Comment by gewarren** [comment]
This issue was moved to dotnet/docs#23301
