### ISSUE TITLE
Missing release notes

### ISSUE THREAD

**Issue by amoertlseder** [MicrosoftDocs/feedback#3514]
The link https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes#16.8.6 for the VS update doesn't show any release notes for the given release.

**Comment by JasonWHowell** [comment]
@jawiddis can you please check this issue. 

@amoertlseder I see the release notes here if it helps:
https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes-v16.8#--visual-studio-2019-version-1686-

Thanks, Jason

**Comment by JasonWHowell** [comment]
@JacquelineWiddis  Please take a look PS: your author metadata tag is wrong in the pages above.

**Comment by I-Cat** [comment]
> @jawiddis can you please check this issue.
> 
> @amoertlseder I see the release notes here if it helps:
> https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes-v16.8#--visual-studio-2019-version-
> 
> Thanks, Jason

2019 its 2021 looks out dated

 `Lable: Outdated`

**Comment by JasonWHowell** [comment]
@I-Cat Sorry I don't understand. The product branding is Visual Studio 2019, but the link in question is for a version (16.8.6) that has recent updates in 2021
![image](https://user-images.githubusercontent.com/5067358/110889201-95889080-82a2-11eb-81ac-60a3378012de.png)

**Comment by amoertlseder** [comment]
The release Notes had been added a day after I wrote the issue.
