### ISSUE TITLE
[Question] Where is the "Power Query M formula language" documentation hosted?

### ISSUE THREAD

**Issue by mrlucmorin** [MicrosoftDocs/feedback#3516]
Hi,

I've been trying to locate a GitHub repository for the _Power Query M formula language_ located at:

https://docs.microsoft.com/en-us/powerquery-m/

I want to contribute by fixing small spelling errors.

Is that content maintained on GitHub? Kindly point me to the correct place.

Thank you

**Comment by JasonWHowell** [comment]
@mrlucmorin most reference docs are not open source. What file has the typo?

You can right click > view source in the browser to look for the metadata tag that shows the repo where the files are hosted.

```
<meta name="original_content_git_url" content="https://github.com/MicrosoftDocs/query-docs-pr/blob/live/query-languages/m/index.yml" />
```
The convention is that -pr indicates that the repo is private and is not open source. Sometimes there is a public repo (generally drop the -pr in the repo name). But in this case, there is not: https://github.com/MicrosoftDocs/query-docs/blob/master/query-languages/m/index.yml

@bezhan can you advise further if needed. 

Thanks, Jason
#please-close

**Comment by mrlucmorin** [comment]
> @mrlucmorin most reference docs are not open source. What file has the typo?

Hi Jason,

https://docs.microsoft.com/en-us/powerquery-m/quick-tour-of-the-power-query-m-formula-language

The following sentence:

An M variable can included spaces by using the # character as #"Step Name"

The word "included" should be "include"

As I said, a small typo...

Thanks for the details about the documentation conventions.

Regards.
