### ISSUE TITLE
Link broken in Use hybrid Modern Authentication article

### ISSUE THREAD

**Issue by ptschumi** [MicrosoftDocs/feedback#3518]
Hello

In the article https://docs.microsoft.com/en-us/exchange/clients/outlook-for-ios-and-android/use-hybrid-modern-auth?view=exchserver-2019 the following link is broken:

 "Validating Hybrid Modern Authentication setup for Outlook for iOS and Android" is pointing to https://gallery.technet.microsoft.com/scriptcenter/Validating-Hybrid-Modern-ad4c2b16

Could you make that script available again?

Regards
Philippe

**Comment by MVogwell** [comment]
+1 -- we really need this too please. Thanks, Martin

**Comment by JasonWHowell** [comment]
@msdmaguire Can you take a look at this broken link please? 
#assign:@msdmaguire

**Comment by msdmaguire** [comment]
@ptschumi the link has been fixed and will now work as expected. The change should be published by end of day today. Thanks for pointing this out to us. 

The link will now go here: https://aka.ms/OLHMAScript

**Comment by msdmaguire** [comment]
@JasonWHowell I do not have the ability to close this issue or I would.....

**Comment by JasonWHowell** [comment]
#please-close Thanks for the prompt resolution! Great work
