### ISSUE TITLE
Pages on docs.microsoft.com for the Surface Hub are displayed in Japanese instead of english

### ISSUE THREAD

**Issue by MarcVndrhgn** [MicrosoftDocs/feedback#3523]
When I go to the documentation for the Surface Hub, the language is switching to japanese. (but you can see en-us in the URL). Switching the site to French or Deutsch is OK.
Apparently it is on all the pages under Surface Hub. 
For example, I go to http://docs.microsoft.com and search for Surface Hub, the results are here, in English, https://docs.microsoft.com/en-us/search/?terms=surface%20hub
From there, every links that start with /surface-hub/... are sending you to a page in japanese.
For example :
https://docs.microsoft.com/en-us/surface-hub/differences-between-surface-hub-and-windows-10-enterprise
https://docs.microsoft.com/en-us/surface-hub/install-apps-on-surface-hub
https://docs.microsoft.com/en-us/surface-hub/surface-hub-2s-85
Even tough the url contains en-us, pages are displayed in japanese
I have tried on 5 different machines (work machine, home machine), with different browsers Edge chromium and Firefox.
I also asked a colleague to try and he has the same problem.
![2021-03-02_12-28-59](https://user-images.githubusercontent.com/45348822/109661716-91ee5e80-7b6a-11eb-82a5-1447d1eb40d9.png)

**Comment by JasonWHowell** [comment]
@MarcVndrhgn I wonder if this was a temporary problem. It seems to be rendering in en-us locale now, at least from my machine. Can you test again and let us know?

Thanks, Jason

**Comment by MarcVndrhgn** [comment]
> @MarcVndrhgn I wonder if this was a temporary problem. It seems to be rendering in en-us locale now, at least from my machine. Can you test again and let us know?
> 
> Thanks, Jason

@JasonWHowell it lasted a few days but it seems to be fine now.

Thanks
Marc

**Comment by JasonWHowell** [comment]
@MarcVndrhgn Thanks for reporting this issue. Sorry the site was in the wrong language for a few days. I'll close out the issue as resolved now. Thanks! Jason
#please-close
