### ISSUE TITLE
Link broken

### ISSUE THREAD

**Issue by ratty67** [MicrosoftDocs/feedback#3525]
**Describe the bug**
On page 
https://docs.microsoft.com/en-us/powershell/module/azuread/get-azureaduser?view=azureadps-2.0

the link supplied in the FILTER section is broken
http://www.odata.org/documentation/odata-version-3-0/odata-version-3-0-core-protocol/#queryingcollections

![image](https://user-images.githubusercontent.com/36491286/109726507-949a9380-7bfe-11eb-84ec-01d34e8139ae.png)

**Comment by keziamicro** [comment]
@ratty67 Can you check again please? I was able to click on the link and open it. Regardless, I'll make sure to let the authors know.
