### ISSUE TITLE
Microsoft Learn (User) Public Profile

### ISSUE THREAD

**Issue by MathiasAaron** [MicrosoftDocs/feedback#3528]
Hi,

I noticed the in my personal view of Microsoft Learn Profile, I can see my certifications as well. I can't see the same in the public view of it.

Also if there was an option to publish the public view to LinkedIn, that would also be amazing and attract more users to Microsoft Learn.

Regards,

Aaron.

**Comment by Kcaxtanhu** [comment]
Hi!

Not sure if I need to open another issue or my comment here is fine.
From my Personal Profile I've linked with my email (Microsoft Account) used in my Certification Dashboard but still can't see my certification.

Any suggestion?

Regards,
DS.

**Comment by keziamicro** [comment]
@Kcaxtanhu Thanks for following up. Due to some specific info the team may need to access your profile, could you please submit the Learn profile bug here please https://docs.microsoft.com/en-us/learn/certifications/help#how-to-contact-support
