### ISSUE TITLE
No Official Documentation on Microsoft Planner Limits

### ISSUE THREAD

**Issue by mirlenbrink** [MicrosoftDocs/feedback#3529]
**Is your feature request related to a problem? Please describe.**
We have Power Automate flows that automate the creation of tasks into Planner buckets which started failing recently with the error below error.
`
  "error": {
    "code": "MaximumActiveTasksInProject",
    "message": "The request exceeded allowed limits.",
`
Researching the error there appears to be no official documentation explaining the limits and allocations in Planner.

**Describe the solution you'd like**
Please provide official documentation outlining all Microsoft Planner limits, allocations, or allowances for plans with their licenses.

**Describe alternatives you've considered**
The only alternatives have been to search forum posts or talk with our MS account team to see what others have discovered.  We've found some detail, but the limit numbers don't appear to match with what we are seeing.

**Additional context**
The [Microsoft Planner for admins](https://docs.microsoft.com/en-us/office365/planner/planner-for-admins?source=docs) article seems like a good place to add the official limits for the service.

**Comment by keziamicro** [comment]
@mirlenbrink Thank you for taking the time to write to us. I've let the authors know about your suggestion to add limits to the documentation. Thanks again!
