### ISSUE TITLE
Spelling issue on Visual Studio Documentation Worksloads

### ISSUE THREAD

**Issue by Cerlancism** [MicrosoftDocs/feedback#353]
Node js is described [here](https://docs.microsoft.com/en-us/visualstudio/#pivot=workloads&panel=web )  as "Build scalable network applications using Node.js, an **asnchronous**, event-driven JavaScript runtime."

Is **asnchronous** a new term or a spelling issue of **asynchronous**?

**Comment by Powerhelmsman** [comment]
@erickson-doug Can your team fix it?
