### ISSUE TITLE
When Registering your account for MicrosoftDocs, one of the countries/regions available from the dropdown is "Bahamas, The" 

### ISSUE THREAD

**Issue by Squaduck** [MicrosoftDocs/feedback#3530]
**Describe the bug**
When Registering your account for MicrosoftDocs, one of the countries/regions available from the dropdown is "Bahamas, The" 

**To Reproduce**
Login with an un-registered account
And go through the process until the "Stay up to date" page
In the country/regions dropdown menu one of the options is "Bahamas, The"

**Expected behavior**
For the affected option to be "The Bahamas"

**Screenshots**
![Microsoft Typo](https://user-images.githubusercontent.com/55469508/109875226-2fff2900-7c3e-11eb-96e2-7229f6683694.png)
Personal data blurred for obvious reasons

**Desktop (please complete the following information):**
Windows 10 Pro (Version 20H2 os build 19042.844)
Chrome (Version 88.0.4324.190)

**Comment by keziamicro** [comment]
@Squaduck Thank you for taking the time to report this bug to us. I've let the engineers know and hopefully we will see a fix soon. Thanks again!
