### ISSUE TITLE
Cannot render normal checkbox like GitHub

### ISSUE THREAD

**Issue by Brian-Ding** [MicrosoftDocs/feedback#3531]
**Is your feature request related to a problem? Please describe.**
Is it possible to render a checkbox just like the GitHub does here?

**Describe the solution you'd like**
With markdown code as below
``` md
- [ ] Todo 1
- [x] Todo 2
```
I am expecting 
> - [ ] Todo 1
> - [x] Todo 2

What I really get is
> \- \[ \] Todo 1
> \- \[x\] Todo 2

**Comment by keziamicro** [comment]
@Brian-Ding Thanks for taking the time to write to us. What product/service were you referring to in the example above?.

**Comment by JasonWHowell** [comment]
Docs.microsoft.com does not use GFM (Github flavored markdown) that has the checkmarks. 

Docs uses Commonmark, and changing the language would be a ton of work.  
https://docs.microsoft.com/en-us/contribute/markdown-reference

Other folks have suggested that Commonmark handle checkboxes and it has been rejected before. https://talk.commonmark.org/t/support-for-gfm-like-checkboxes/2007/4

As an alternative, you can use Unicode characters for check and unchecked boxes: ☐ ☑  ☒
