### ISSUE TITLE
Code bug in sample

### ISSUE THREAD

**Issue by westleyMS** [MicrosoftDocs/feedback#3532]
**Problem**
In the sample claim provider for this article-
https://docs.microsoft.com/en-us/archive/blogs/speschka/using-sharepoint-apps-with-saml-and-fba-sites-in-sharepoint-2013?source=docs

The code sample has an error where they attach the SMTP claim to the actor token, instead of just the user token.
Recently (at the end of 2020) there was a security update that blocks user claims on the actor token and customers that used this claim provider code are now failing, and needing to re-write their code.

**To Reproduce**
1. Create a SP high-trust add-in and add the 'SamlAndFbaForApps.zip' code sample to the token helper as outlined in the article/instructions.
2. Set up the Add-in
3. Make sure the user you are testing with has an SMTP address
3. Try to use the add-in

**Error**
 ULS shows an error that the SMTP claim cannot be added to the actor token and rejects the token. This causes an auth failure.

**Expected behavior**
 The add-in should authenticate and work

 - Windows Server (whatever version you are running SP on)
 - Browser - all
 - Version - all

In the code sample the problem code is in ClaimsTokenHelper.cs @line 339-340 as follows:
if (addSamlClaim)
            actorClaims.Add(new JsonWebTokenClaim(samlClaimType, samlClaimValue));

These lines need to be commented to be compliant with the standard, and to work past the SP security updates that broke this.

**Comment by JasonWHowell** [comment]
The article mentioned is archived and not being maintained. Thanks for the feedback though.

**Comment by JasonWHowell** [comment]
#please-close
