### ISSUE TITLE
the link is not valid.

### ISSUE THREAD

**Issue by RikaEndo0** [MicrosoftDocs/feedback#3539]
Hi,

On the page "Available Today! Visual Studio 2019 v16.9 and v16.10 Preview 1"
the link is not valid.

×：https://devblogs.microsoft.com/visualstudio/vs2019-v16-19-and-v16-10-preview-1

〇：https://devblogs.microsoft.com/visualstudio/vs2019-v16-9-and-v16-10-preview-1/

**Comment by JacquelineWiddis** [comment]
This has been fixed.
