### ISSUE TITLE
Link to Cryptographic Development kit download is invalid

### ISSUE THREAD

**Issue by Hiihtaja77** [MicrosoftDocs/feedback#3543]
On page : https://docs.microsoft.com/en-us/windows/win32/seccng/cng-portal
"
If you are developing a CNG cryptographic algorithm provider or key storage provider, you must download the Cryptographic Provider Development Kit from Microsoft.
"
But link to it : https://www.microsoft.com/download/details.aspx?id=30688
show 
"
We're sorry, this download is no longer available.
"

Where I can download Cryptographic Provider Development Kit ?

**Comment by keziamicro** [comment]
@Hiihtaja77 Thank you for taking the time to let us know that link is not working. I've let the authors know.
