### ISSUE TITLE
Tutorial: Customize view for EF Database First with ASP.NET MVC app

### ISSUE THREAD

**Issue by FatWaterAudio** [MicrosoftDocs/feedback#3544]
the page at this link  --> https://docs.microsoft.com/en-us/aspnet/mvc/overview/getting-started/database-first-development/customizing-a-view?source=docs     does not work as described.  Adding the custom code to the Views/Students/Details.cshtml  causes the project to fail with a 400.0 IIS message.  ...basically a bad request. Once the failure occurs, there doesn't seem to be a way to recover without deleting the Views/Students folder and the StudentsController.cs file.  All prior code up to that point in the tutorial is auto-generated.      All prior code up to that point in the tutorial seems to run correctly.     

**To Reproduce**
1. Go to  this page   -->https://docs.microsoft.com/en-us/aspnet/mvc/overview/getting-started/database-first-development/  

2. follow all instructions up to this page  --> https://docs.microsoft.com/en-us/aspnet/mvc/overview/getting-started/database-first-development/customizing-a-view?source=docs

**Expected behavior**
The tutorial exercise where the error occurs is intended to show custom (not auto generated) output in the Views/Students/Details.cshtml page.  

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win10 64 bit
 - Browser Chrome
 - Version 88.0.4324.190

**Additional context**

**Comment by FatWaterAudio** [comment]
@keziamicro thank you for your reply.   In my own continuing efforts, I was able to find a nearly identical tutorial using Razor Pages style development instead of MVC style development.  My current project is a new development effort.  Which of these two approaches should be preferred for new development?

**Comment by keziamicro** [comment]
Looping in @Rick-Anderson for the above ^

**Comment by Rick-Anderson** [comment]
@keziamicro  please transfer to https://github.com/dotnet/AspNetDocs

**Comment by Rick-Anderson** [comment]
@alligreubel who can transfer this issue to https://github.com/dotnet/AspNetDocs ?

**Comment by gewarren** [comment]
This issue was moved to dotnet/AspNetDocs#542
