### ISSUE TITLE
"View in English" checkbox to follow when scrolling

### ISSUE THREAD

**Issue by Chris-DevTeam** [MicrosoftDocs/feedback#3545]
Despite the numerous contributors, automatic translation is not yet natural.

So, I have to read the original English text often for strange interpretations.
In order to view the original text in a state of scrolling down a lot, you have to go back to the top and click the checkbox, which is very inconvenient.

When scrolling, it would be nice if this area of "Bookmark, Feedback, Edit, Share, View English" is fixed at the top.
![2222](https://user-images.githubusercontent.com/23347656/110563260-63860a00-818e-11eb-8965-58a40e083fba.png)

**Comment by keziamicro** [comment]
@Chris-DevTeam Thank you for taking the time to send us this idea. I've shared this with the designer working on this specific section of navigation.
