### ISSUE TITLE
Visibility, automation, and orchestration with Zero Trust

### ISSUE THREAD

**Issue by dkganchev** [MicrosoftDocs/feedback#3546]
**Describe the bug**
Spelling error in the text
"Reactive detection is when incidents are triggered from one of thesix p illars that can be investigated."

**To Reproduce**
1. Go to 'https://docs.microsoft.com/en-us/security/zero-trust/visibility-automation-orchestration'
2. Scroll down to Managing threats includes reactive as well as proactive detection and requires tools that support both.
4. See error in the next sentence

**Expected behavior**
N/A

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10 Professional0
 - Browser Firefox
 - Version

**Comment by keziamicro** [comment]
@dkganchev Thank you for reporting this. I have reached out to the authors for correction. I appreciate you taking the time to let us know.
