### ISSUE TITLE
"Download PDF" link does not work

### ISSUE THREAD

**Issue by gjuwindev** [MicrosoftDocs/feedback#3549]
"Download PDF" link does not work, on the page:

https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/new-field?view=aspnetcore-5.0&tabs=visual-studio

**Comment by JasonWHowell** [comment]
@Rick-Anderson @scottaddie  this is likely a PDF build failure for the repo above.  Check it out in ops to see why PDF builds are failing.

**Comment by Rick-Anderson** [comment]
@JasonWHowell  see [build report](https://ops.microsoft.com/#/sites/Docs/docsets/aspnet-core-conceptual?tabName=builds)
Select PDF build type
![image](https://user-images.githubusercontent.com/3605364/110996973-cf987780-8320-11eb-8d1a-a4a75ccf01c0.png)

1 error(s) (1 System), 0 warning(s). An exception occurred during the build process. Please check the raw log and retry building your content again. If the issue persists, please open a ticket in https://SiteHelp and include the URL of publishing report as well as below information: ***Error occurred when accessing GitHub. Details: (Unauthorized) Bad credentials.***

**Comment by Rick-Anderson** [comment]
@JasonWHowell  that might be a transient error as it occured on 03/10/2021 11:54:08 with successful builds after that. I'm guessing the pdf is built off live, so I'll merge to live now and see what happens.
--

**Comment by Rick-Anderson** [comment]
> I'm guessing the pdf is built off live,
Nope, looks like it's main.

**Comment by JasonWHowell** [comment]
You can issue a manual PDF build if needed. Ping me on email if you need more details.

**Comment by gjuwindev** [comment]
> You can issue a manual PDF build if needed. Ping me on email if you need more details.

no need, thanks...  I just tried to create a PDF while reading that page, that failed failed and I reported it, for somebody should probably have to fix this, for users that will come after me :-)

**Comment by JasonWHowell** [comment]
@gjuwindev Thanks for pointing out the issue!

**Comment by JasonWHowell** [comment]
#please-close
