### ISSUE TITLE
2018 Security Advisories Missing

### ISSUE THREAD

**Issue by JaredShaver** [MicrosoftDocs/feedback#355]
The Security Advisories for 2018 are missing from https://docs.microsoft.com/en-us/security-updates/SecurityAdvisories/securityadvisories

An advisory was published on May 8, 2018 links to https://docs.microsoft.com but it is a 404.

Text of advisory email:

********************************************************************
Title: Microsoft Security Advisory Notification
Issued: May 8, 2018
********************************************************************

Security Advisories Released or Updated on May 8, 2018 ===================================================================

* Microsoft Security Advisory 4092731

 - Title: Update to Azure Guest OS Machine Key Generation Algorithm
 - https://docs.microsoft.com/en-us/security-updates/
   securityadvisories/2018/4092731
 - Reason for Revision: Microsoft is releasing this security advisory 
   to provide information related to an update in the way the 
   Azure Guest OS generates machine keys. This scenario may affect 
   customers who are using Azure Cloud Services Web Roles. 
   The machine keys on existing deployments have been generated 
   with insufficient entropy and using deprecated cryptographic 
   algorithms.
 - Originally posted: May 8, 2018
 - Version: 1.0

**Comment by Powerhelmsman** [comment]
@BetaFred Can you take a look at this issue?

**Comment by dend** [comment]
@v-hearya can you please take a look at this issue?
