### ISSUE TITLE
Typo in documentation

### ISSUE THREAD

**Issue by mrlucmorin** [MicrosoftDocs/feedback#3551]
**Describe the bug**
The page:

https://docs.microsoft.com/en-us/powerquery-m/quick-tour-of-the-power-query-m-formula-language

contains a typo. In this sentence:

_An M variable can included spaces by using the # character as #"Step Name"_

"included" should be "include".

**To Reproduce**
1. Go to the page
2. Search for the sentence. It is the first item in the first bullet list.

**Comment by JasonWHowell** [comment]
It's an easy fix. I'll try to do it.

**Comment by rootsmusic** [comment]
> It's an easy fix. I'll try to do it.

@JasonWHowell #please-close

**Comment by mrlucmorin** [comment]
Yes, I would have done it myself if I had access :-)

Thanks
