### ISSUE TITLE
Table headers offset by 1 column on doc page "Authorize requests to Azure Storage"

### ISSUE THREAD

**Issue by EricHindrichsen** [MicrosoftDocs/feedback#3558]
On [https://docs.microsoft.com/en-us/rest/api/storageservices/authorize-requests-to-azure-storage](https://docs.microsoft.com/en-us/rest/api/storageservices/authorize-requests-to-azure-storage) the headers of the first table are all offset by one column to the left.

**Comment by JasonWHowell** [comment]
@tamram could you take a look please?

**Comment by tamram** [comment]
@JasonWHowell @EricHindrichsen - This has already been reported and fixed, thanks!

**Comment by JasonWHowell** [comment]
#please-close  Thanks for the quick fix @tamram
