### ISSUE TITLE
https://docs.microsoft.com/en-us/javascript/api/location-based-services-javascript?view=azure-iot-typescript-latest

### ISSUE THREAD

**Issue by HowardEdidin** [MicrosoftDocs/feedback#356]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
![404](https://user-images.githubusercontent.com/19954905/39878485-19eff41c-543e-11e8-8bab-fd26964b792d.png)

**Additional context**
Error - Sorry this document can't be found.

**Comment by dend** [comment]
Thanks for bringing this up to our attention, @HowardEdidin - working on getting this resolved.

**Comment by dend** [comment]
The correct location for this page is:
https://docs.microsoft.com/en-us/javascript/api/azure-maps-javascript/?view=azure-iot-typescript-latest
