### ISSUE TITLE
How can I remove my old MSDN profile on social.msdn.microsoft.com without access to it?

### ISSUE THREAD

**Issue by aloshak** [MicrosoftDocs/feedback#3561]
I have a Developer profile on social.msdn.microsoft.com. Created long time ago, not used for a long time, no access to the email used to create it. It has outdated personal information. I need help of administrator to update or remove this information.
Here is the link: https://social.msdn.microsoft.com/Profile/artem%20loshak

**Comment by rootsmusic** [comment]
@aloshak  That site has closed at https://docs.microsoft.com/en-us/teamblog/msdn-technet-english-forums-closure
