### ISSUE TITLE
TechNet Gallery - move to GitHub

### ISSUE THREAD

**Issue by Rvvhub** [MicrosoftDocs/feedback#3565]
Hi there,

any news on the move of the TechNet Scriptcenter content to GitHub?
Countless docs and pages link to the ScriptCenter and we get questions from many customers on where the scripts have gone.

Kind regards,

Ruud

**Comment by rootsmusic** [comment]
@Rvvhub, I suggest opening an issue by submitting feedback on https://docs.microsoft.com/en-us/teamblog/technet-gallery-retirement
