### ISSUE TITLE
DAX Doc: the ISEmpty() function's example data and formula has a not match column name

### ISSUE THREAD

**Issue by Zongrenfeng** [MicrosoftDocs/feedback#3566]
url: https://docs.microsoft.com/zh-cn/dax/isempty-function-dax?source=docs

Like the screenshot below, the column "County" should be "Count".
![image](https://user-images.githubusercontent.com/46955844/111282454-fc2df580-8678-11eb-8e64-eabbbb59e1ca.png)

**Comment by JasonWHowell** [comment]
@Minewiskan DAX feedback

**Comment by Minewiskan** [comment]
@Zongrenfeng - Thanks for letting us know. This has been corrected in the EN-US locale. https://docs.microsoft.com/en-us/dax/isempty-function-dax
It will take a few weeks for this to appear in localized versions.
#please-close
