### ISSUE TITLE
SignalR Blazor turorial

### ISSUE THREAD

**Issue by georgait** [MicrosoftDocs/feedback#3568]
**Describe the bug**
I have copied this sample https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/signalr-blazor/samples/5.x/BlazorServerSignalRApp and i can't compile it properly. Everytime i run it i get back this exception: System.ObjectDisposedException: 'Cannot process pending renders after the renderer has been disposed.
ObjectDisposed_ObjectName_Name'. This exception was originally thrown at this call stack:
    [External Code]
    Messenger.Pages.Index.OnInitializedAsync.AnonymousMethod__5_0(string, string) in Index.razor
    [External Code]

 If i run it in release mode it works fine. Am i missing something or it's a bug?

**Comment by rootsmusic** [comment]
@georgait Please move this issue to https://github.com/dotnet/AspNetCore.Docs/issues
