### ISSUE TITLE
Azure IoT Hub TypeScript SDK

### ISSUE THREAD

**Issue by HowardEdidin** [MicrosoftDocs/feedback#357]
**Describe the bug**

Does not exist on Github

**To Reproduce**

**Expected behavior**
![2018-05-10_10-44-20](https://user-images.githubusercontent.com/19954905/39878926-276ee9bc-543f-11e8-9d3e-6fad233232b6.png)

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by dend** [comment]
Hi @HowardEdidin - what is the concrete issue? You might be looking for the SDK here: https://github.com/Azure/azure-iot-sdk-node/tree/master/service

**Comment by HowardEdidin** [comment]
I am trying to use the IoT Map Service 
The sample https://github.com/Azure-Samples/azure-maps-samples/blob/master/src/interactiveSearch.html doesn't exist. from https://docs.microsoft.com/en-us/azure/azure-maps/quick-demo-map-app

The azure-iot-sdk-node does not contain the Typescript sdk.

**Comment by kgremban** [comment]
@HowardEdidin and @dend I've updated the azure-maps-samples repo and the above link does work now.
