### ISSUE TITLE
Error in Code Example of Navigation view Page

### ISSUE THREAD

**Issue by crashmit** [MicrosoftDocs/feedback#3576]
**Describe the bug**
The C# Code Example on the [Navigation view doc page](https://docs.microsoft.com/de-de/windows/uwp/design/controls-and-patterns/navigationview#code-example) has an error in the c# example in the second last method:
`private bool TryGoBack();
{`
There is a semicolon after TryGoBack() that isn't supposed to be there

**To Reproduce**
1. Go to [Navigation view doc page](https://docs.microsoft.com/de-de/windows/uwp/design/controls-and-patterns/navigationview#code-example)
2. Scroll down to 'private boolean TryGoBack()'

**Comment by gewarren** [comment]
@crashmit Thanks for letting us know. It looks like this was fixed by https://github.com/MicrosoftDocs/windows-uwp/commit/3d602eafe1492eb28ead94b706040576eec21153.
