### ISSUE TITLE
CALENDARAUTO() DAX function example

### ISSUE THREAD

**Issue by vashchenkova** [MicrosoftDocs/feedback#3582]
The second example of CALENDARAUTO() DAX function is wrong.
![image](https://user-images.githubusercontent.com/33933512/112121930-d2bd1e80-8bd0-11eb-819a-2c0d56599106.png)

1. Go to 'https://docs.microsoft.com/en-us/dax/calendarauto-function-dax#example'
2. Click on 'Examples'
3. Or Scroll down to 'Examples'

CALENDARAUTO() DAX function takes [**fiscal_year_end_month**] as parameter.
In the second example [**fiscal_year_end_month**] = **3** 

**In this case the example should be**:
CALENDARAUTO(**3**) will return all dates between **April 1, 2010** and **March 31, 2012**.

**But in the example we see** 
CALENDARAUTO(**3**) will return all dates between **March 1, 2010** and **February 28, 2012** - that is wrong.

**The example needs to be changed to be**:
CALENDARAUTO(**3**) will return all dates between **April 1, 2010** and **March 31, 2012**
OR
CALENDARAUTO(**2**) will return all dates between **March 1, 2010** and **February 28, 2012** 

Thank you!

**Comment by JasonWHowell** [comment]
@Minewiskan this might be feedback for the DAX reference.

**Comment by Minewiskan** [comment]
#in-progress
