### ISSUE TITLE
Descriptions are not shown when @override tag is used

### ISSUE THREAD

**Issue by chgennar** [MicrosoftDocs/feedback#359]
All descriptions of properties on the following page do not display.  I believe it is because of the @override tag used in the comment block.

https://docs.microsoft.com/en-us/javascript/api/azure-maps-javascript/circlelayeroptions?view=azure-iot-typescript-latest

**Comment by pierreca** [comment]
errr I'm not sure who maintains this package but not me ;) @cmpendleton maybe?
In any case, it looks like an error with the docs parser, not with the package itself. maybe @dend can help?

**Comment by Powerhelmsman** [comment]
@dend @cmpendleton Can you double check if it is a site parse issue?

**Comment by cmpendleton** [comment]
I don't have oversight of the parsing input for our javascript docs. @dend was the last person we worked with on publishing our JS map control docs.

**Comment by dend** [comment]
@chgennar can you point to the source repo from where that content is generated? Feel free to shoot an internal email.

**Comment by chgennar** [comment]
sent an internal email

**Comment by dend** [comment]
Closing this issue as we follow-up internally.
