### ISSUE TITLE
"The name 'Host' does not exist in the current context"

### ISSUE THREAD

**Issue by OddEyesMage** [MicrosoftDocs/feedback#3594]
When I tried to follow the tutorial and right when I get to where I need to setup the add scaffold I see that in my Program.cs I have an error saying that 'the name "Host" does not exist in the current context'. I do not understand what I am doing wrong, I have retried this numerous times, I have followed the tutorial, yet I keep getting this error the only difference is that I am using NET Core 2.2 instead of 5.0. If anyone can tell me why this issue is happening it would be much appreciated. For context im referring to this https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/intro?view=aspnetcore-2.1

**Comment by gewarren** [comment]
This issue was moved to dotnet/AspNetCore.Docs#22046
