### ISSUE TITLE
Make Tables More Mobile Friendly

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#36]
On my phone, the table layouts can become unusable. Forcing me to wait until next I'm at a computer.
The words end up squished where only a few letters per line will show on larger tables. 

In some tables where it's giving a line of code in a column, the code ends up written vertically which requires a LOT of scrolling. Meanwhile, the other columns are often blank space.

I have no suggestions on what could be changed to make it better. Microsoft Magic?

----------
⚠ Idea migrated from UserVoice

**Created By:** Paul Shell
**Created On:** 2018/01/24 00:06:17 +0000
**Votes at Migration:** 1
**Supporters at Migration:** 1

**Comment by Powerhelmsman** [comment]
#log-suggestion @ShevaDas

**Comment by botcrane** [comment]
🚀 **ATTENTION**: [Internal request](https://ceapex.visualstudio.com/web/wi.aspx?pcguid=7d644393-99ad-41c8-ac53-7fa79294c720&id=22771) logged.

**Comment by dend** [comment]
We've made significant improvements to how we handle tables on mobile devices, therefore closing this item.
