### ISSUE TITLE
Markdown inline code visualization is distracting

### ISSUE THREAD

**Issue by jakrams** [MicrosoftDocs/feedback#360]
The visualization of code embedded into text using backquotes is "functional" but very distracting. When you write code documentation where you need to mark a lot of words in a sentence as code, the result becomes very noisy to look at.

Here is how it looks on docs.microsoft.com:

![code-docs](https://user-images.githubusercontent.com/36191331/39916495-e7d341be-550a-11e8-9be0-b8aa0d8e6bb1.png)

This is how `embedded code` looks like `on GitHub`. It's better, but that `grey background box` is also a bit too much.

Here is the same thing in the Markdown preview of Visual Studio Code:

![code-vsc](https://user-images.githubusercontent.com/36191331/39916513-fa4fa5c6-550a-11e8-82d2-1d921483cd07.png)

I think the latter is less annoying to look at. If on docs.ms.com the box around the text could be removed and it would just render with a monospace font and a slightly different color than regular text it would look nicer and be less distracting.

As it stands now, I do not mark everything up as code, that I would normally do, to reduce visual clutter in the final output.

Here is a contrived example that highlights why the current visualization can be very distracting:

To implement the `BaseClass` interface, derive `YourClass` from it and implement `someFuncA`, `someFuncB` and `someFuncC`. Mark them as `virtual` and `override`. Calling `ptr->someFuncA()` will now call `YourClass::someFuncA`.

**Comment by Powerhelmsman** [comment]
@kubeaver @ShevaDas This is good suggestion. I am also distracted by inline code. Do you have any suggestion or do we have any guideline?

**Comment by kubeaver** [comment]
@Powerhelmsman @ShevaDas we're planning on making some design updates to the site in the near future. The goal will be to bring it inline with other Microsoft products. We've heard this feedback before as well as the opposite feedback, and one of our designers has explored a handful of options. We'll keep this in mind as we work on updates.

**Comment by keziamicro** [comment]
Hello - reviewing and cleaning up some older feedback/issues. Thanks!
