### ISSUE TITLE
ClipSVC Introuvable

### ISSUE THREAD

**Issue by Kazuto12307** [MicrosoftDocs/feedback#3601]
Bonjours,j'ai un windows 10 famille mais mon microsoft store ne marche pas l'installation d'application non plus à cause du service.

Alors ça fait 3 jours que j'ai ça je sais pas pourquoi j'active le service et là  
file:///C:/Users/Maria/OneDrive/Imagens/Capturas%20de%20Ecr%C3%A3/Capture%20d%E2%80%99%C3%A9cran%20(1).png
fichier introuvable.... une solution ? Merci d'avance.

**Comment by rootsmusic** [comment]
@Kazuto12307 Please ask product support or in support forums at https://support.microsoft.com/en-us/office/troubleshoot-repair-ceaa4aee-fa3b-4ca4-9ddb-bde4dc310dc9?ui=en-US&rs=en-US&ad=US
#please-close
