### ISSUE TITLE
Open Publishing redirects doesn't work for GH content

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/feedback#361]
**Is your feature request related to a problem? Please describe.**
When adding redirects in a doc repo to the openpublishing config, the website is fixed, but when you're working on editing or navigating in GH, the hyperlink navigation remains broken.

**Describe the solution you'd like**
Update the links at the same time as adding in the redirect. This might partially defeat the purpose of the redirect.

**Describe alternatives you've considered**
Leave a placeholder file in the old location with the redirect information. This would likely confilct with the real openpublishing redirect

**Additional context**
I've been trying to run some link validators like https://github.com/tcort/markdown-link-check, but they get confused because these redirects are virtual.
I did chat with some of the @thedanfernandez at MSBuild about this, so maybe there is already an internal ticket.

**Comment by Powerhelmsman** [comment]
@thedanfernandez Have we already opened a internal ticket?

**Comment by dend** [comment]
@nschonni what repo are you working with where you are trying to set up redirects?

**Comment by nschonni** [comment]
Mostly I've been chipping in a bit of stuff on VSTS-docs, but the issue is a general one about using the openpublishing.redirect.json means the GitHub naviation/linking doesn't work unless the Markdown files are also updated.

**Comment by dend** [comment]
I am going to go ahead and open an internal ticket for this - thanks for the suggestion, @nschonni 👏

**Comment by dend** [comment]
#log-suggestion

**Comment by botcrane** [comment]
🚀 **ATTENTION**: [Internal request](https://ceapex.visualstudio.com/web/wi.aspx?pcguid=7d644393-99ad-41c8-ac53-7fa79294c720&id=21157) logged.

**Comment by PRMerger9** [comment]
GitHub user thedanfernandez has been removed from the MicrosoftDocs organization, so they were automatically removed as an assignee.

**Comment by keziamicro** [comment]
Hello - reviewing and cleaning up some older feedback/issues. Thanks!

**Comment by nschonni** [comment]
@keziamicro was the internal ticket raised ever resolved?

**Comment by meganbradley** [comment]
@keziamicro @nschonni the internal ticket was resolved As Designed. The process for redirecting files includes manually updating links as the writer's responsibility. We have a backlog Epic to completely redo the redirection tooling to make it more automated, but it hasn't been committed to a quarter yet and we don't plan to make incremental improvements to the current system before then.
