### ISSUE TITLE
Grammar error

### ISSUE THREAD

**Issue by Cortana-117** [MicrosoftDocs/feedback#3617]
https://docs.microsoft.com/en-us/windows-hardware/customize/enterprise/service-uwf-protected-devices

Normally, when the Unified Write Filter (UWF) is active, system updates are disabled, as they would **use** be erased when the overlay is cleared.

There is a grammar error in this sentence in that page. the word "use" is unnecessary there.

**Comment by gewarren** [comment]
Thank you @Cortana-117
