### ISSUE TITLE
Typo "**@mention**"→"**\@mention**"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/feedback#3623]
**Describe the bug**
A clear and concise description of what the bug is.:
 Typo "\*\*@mention**"→"\*\*\\@mention**"(Bold with escape characters)

en-es:"https://docs.microsoft.com/en-us/business-applications-release-notes/october18/microsoft-flow/post-richer-messages-in-microsoft-teams"
![post-richer-messages-in-microsoft-teams_e](https://user-images.githubusercontent.com/40815708/117409683-6a41bb00-af4c-11eb-9c6a-0100dea27cf4.png)

#PingMSFTDocs

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by rootsmusic** [comment]
@hyoshioka0128 This issue is about a release note, which is blogged at https://flow.microsoft.com/en-us/blog/adaptive-cards-for-microsoft-teams-microsoft-flow-us-government-now-available/

**Comment by hyoshioka0128** [comment]
@rootsmusic - Thanks!
Closed #3623 .
