### ISSUE TITLE
Typo "**@sync～**"→"**\@sync～**"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/feedback#3624]
**Describe the bug**
A clear and concise description of what the bug is.:
Typo "\*\*@sync～**"→"\*\*\\@sync～**"(Bold with escape characters)

en-es:"https://docs.microsoft.com/en-us/previous-versions/sql/synchronization/sync-framework-1.0/bb686941(v%3Dsql.100)"
![bb686941_e](https://user-images.githubusercontent.com/40815708/117412150-66fbfe80-af4f-11eb-9531-c834eb8515d8.png)

#PingMSFTDocs

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by rootsmusic** [comment]
@hyoshioka0128 "We're no longer updating this content regularly."
#please-close
