### ISSUE TITLE
Azure Templates property does not indicate available values

### ISSUE THREAD

**Issue by techthoughts2** [MicrosoftDocs/feedback#3628]
**Describe the bug**
This Azure templates doc page: [Microsoft.Web serverfarms](https://docs.microsoft.com/en-us/azure/templates/microsoft.web/serverfarms?tabs=bicep) indicates the ```kind``` Property but does not articulate the accepted values for this Property. As such I can't populate this field with a degree of confidence that will result in a successful deployment. My only recourse that I have found to date is to deploy the resource manually via the portal in different configurations and manually look up the various values for ```kind``` which is not an ideal experience.

**To Reproduce**
1. Go to [Microsoft.Web serverfarms](https://docs.microsoft.com/en-us/azure/templates/microsoft.web/serverfarms?tabs=bicep)
2. Scroll down to Property values
4. Reference the ```kind``` property.

**Expected behavior**
When referencing this docs page I should be setup for success and armed with accepted values for the ```kind``` property.

**Additional context**
In some cases intellisense in various editors can help populate this field, but in some cases - like this one, it does not.

**Comment by rootsmusic** [comment]
@techthoughts2 Please move this issue to https://github.com/MicrosoftDocs/azure-docs/issues

**Comment by techthoughts2** [comment]
Moved to https://github.com/MicrosoftDocs/azure-docs/issues/79793
