### ISSUE TITLE
Enable hyperlinks of properties in Azure Templates docs

### ISSUE THREAD

**Issue by techthoughts2** [MicrosoftDocs/feedback#3629]
Often when I am referencing an Azure Template doc I am looking to evaluate a specific property. To that end, it would enhance the user experience if hyperlinks were added to the various properties in the JSON/Bicep output.

Example page: [Microsoft.Web serverfarms](https://docs.microsoft.com/en-us/azure/templates/microsoft.web/serverfarms?tabs=bicep)
```
resource symbolicname 'Microsoft.Web/serverfarms@2020-12-01' = {
  name: 'string'
  kind: 'string'
}
```

For example, in the above ```kind``` would be hyperlinked and would take me down the ```kind``` Property values section below.

This would enable users to quickly scan the template for the property they are interested in, and engage it.

**Comment by rootsmusic** [comment]
@techthoughts2 Please move this issue to https://github.com/MicrosoftDocs/azure-docs/issues

**Comment by techthoughts2** [comment]
Move to https://github.com/MicrosoftDocs/azure-docs/issues/79792
