### ISSUE TITLE
Pin this repo in the GH Org

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/feedback#363]
**Is your feature request related to a problem? Please describe.**
The MicrosoftDocs organization has 800 public repos now so finding this repo can be difficult if trying to find it directly on GitHub.

**Describe the solution you'd like**
Adding feedback is an important aspect so this repo should be one of the pinned repos when viewing https://github.com/MicrosoftDocs

**Comment by Powerhelmsman** [comment]
@nschonni Thanks for you great suggestion. I will create a internal ticket to organize pinned repos

**Comment by Powerhelmsman** [comment]
#log-suggestion

**Comment by botcrane** [comment]
🚀 **ATTENTION**: [Internal request](https://ceapex.visualstudio.com/web/wi.aspx?pcguid=7d644393-99ad-41c8-ac53-7fa79294c720&id=20472) logged.

**Comment by Powerhelmsman** [comment]
@nschonni This issue is resolved. Please double check.
