### ISSUE TITLE
Wrong Command Posted on an SQL Database Properties MS Docs Site

### ISSUE THREAD

**Issue by StoyanChalakov** [MicrosoftDocs/feedback#3632]
**Is your feature request related to a problem? Please describe.**
This is a request to correct/update certain article, related to SQL Server Database Properties and in particular to Auto Update Statistics. 
The article references a wromng command and article (CREATE STATISTICS (Transact-SQL)) when it comes to the Auto Update Statistics (should be Update STATISTICS (Transact-SQL))

**Describe the solution you'd like**
Under the section Auto Update Statitstics replace (CREATE STATISTICS (Transact-SQL)) with (UPDATE STATISTICS (Transact-SQL))

**Describe alternatives you've considered**
No alternatives, the procedure should be corrected/updated. 

**Additional context**
Linkl to the article:
https://docs.microsoft.com/en-us/sql/relational-databases/databases/database-properties-options-page?view=sql-server-ver15

**Comment by rootsmusic** [comment]
@StoyanChalakov Please move this issue to https://github.com/MicrosoftDocs/sql-docs/issues

**Comment by StoyanChalakov** [comment]
> @StoyanChalakov Please move this issue to https://github.com/MicrosoftDocs/sql-docs/issues

Hi @rootsmusic , will gladly do, just not sure how :(

**Comment by rootsmusic** [comment]
@StoyanChalakov You can submit feedback by clicking on the button at the doc's bottom.

**Comment by StoyanChalakov** [comment]
Hi @rootsmusic, done :) Thanks for the guidance!

**Comment by rootsmusic** [comment]
You're welcome @StoyanChalakov.  You can close this old issue now.

**Comment by StoyanChalakov** [comment]
This issue will be closed now. The duplicate issue, opened under SQL has already been commented and will be fixed:

https://github.com/MicrosoftDocs/sql-docs/issues/6699

**Comment by StoyanChalakov** [comment]
This issue will be closed now. The duplicate issue, opened under SQL has already been commented and will be fixed:

MicrosoftDocs/sql-docs#6699
