### ISSUE TITLE
 The syntax highlighting for VBA codes is incorrect

### ISSUE THREAD

**Issue by narrowei** [MicrosoftDocs/feedback#3638]
# **Describe the bug**

The syntax highlighting for VBA codes is incorrect. In the VBA code, it only takes a single quotation for a comment. However, in the MicrosoftDocs it considered a pair of single quotation as a comment like the following screenshot: </br>
![image](https://user-images.githubusercontent.com/9133886/119600666-de280280-be2a-11eb-922f-7de88a88bc66.png)

# **To Reproduce**
1. Go to https://docs.microsoft.com/en-us/office/vba/language/concepts/getting-started/declaring-arrays

# **Expected behavior**
In the Github, it rendered VBA codes correctly.
``` VBA
' Integer array uses 22 bytes (11 elements * 2 bytes). 
ReDim MyIntegerArray(10) As Integer 
 
' Double-precision array uses 88 bytes (11 elements * 8 bytes). 
ReDim MyDoubleArray(10) As Double 
 
' Variant array uses at least 176 bytes (11 elements * 16 bytes). 
ReDim MyVariantArray(10) 
 
' Integer array uses 100 * 100 * 2 bytes (20,000 bytes). 
ReDim MyIntegerArray (99, 99) As Integer 
 
' Double-precision array uses 100 * 100 * 8 bytes (80,000 bytes). 
ReDim MyDoubleArray (99, 99) As Double 
 
' Variant array uses at least 160,000 bytes (100 * 100 * 16 bytes). 
ReDim MyVariantArray(99, 99) 
```

**Comment by adegeo** [comment]
I filed an internal bug about this about half a month ago: https://dev.azure.com/ceapex/Engineering/_workitems/edit/424711/ but it hasn't been triaged yet 😢

**Comment by gewarren** [comment]
This has also been reported a couple times on the dotnet/dotnet-api-docs repo. For example: https://github.com/dotnet/dotnet-api-docs/issues/6777.

**Comment by gewarren** [comment]
This has been fixed.
