### ISSUE TITLE
Expose the template repo on MicrosoftDocs org

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/feedback#364]
**Is your feature request related to a problem? Please describe.**
The openpublishing.config files seem to list https://github.com/Microsoft/templates.docs.msft which doesn't appear to be a public repo (currently

**Describe the solution you'd like**
If this repo is used by the documention generation process, please transfer it from the Microsoft org to MicrosoftDocs org and set it to public.

**Describe alternatives you've considered**
This may just be outdated metadata attribute or a schema I'm just not understanding. Maybe the repo is also just not ready for prime-time right now.

**Additional context**
Here is an example of the line i'm describing https://github.com/MicrosoftDocs/docs-powershell/blob/a689cf4f9621b4be7bca9ec88e5d2f273f62fa46/.openpublishing.publish.config.json#L28 but I believe it is in most repos, even if they have local template MD files.

**Comment by dend** [comment]
@nschonni currently, we do not expose our templates to the public. Those are not intended for consumption outside docs.microsoft.com. The files you are referencing are also used for internal configuration and are not meant to be used to create other environments.

**Comment by nschonni** [comment]
No problem, is there any documentation around the actual openpublishing schema anywhere? I'm sure some of my questions are answerable if I just RTFM

**Comment by dend** [comment]
@nschonni not at this time. The [DocFX pipeline](https://dotnet.github.io/docfx/) is the public project you can follow for the same purpose!
