### ISSUE TITLE
dot.net URL redirection

### ISSUE THREAD

**Issue by WeihanLi** [MicrosoftDocs/feedback#3644]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when I wanna download dotnet installer or try to access the docs, currently, it seemed we already have a URL redirection, when I access <https://dot.net> it would redirect to <https://dotnet.microsoft.com>，but when I try to access <https://dot.net/download>, it would be redirected to <https://dotnet.microsoft.com>, not <https://dotnet.microsoft.com/download> as I expected, this is not so convenient for users.

**Describe the solution you'd like**

Since we could change the redirect rules, maybe we could update the redirect policy like follows:

- Let <https://dot.net/docs> redirects to <https://docs.microsoft.com/dotnet/>
- Let <https://dot.net/download> redirects to <https://dotnet.microsoft.com/download>
- Let <https://dot.net/learn> redirects to <https://dotnet.microsoft.com/learn>

**Describe alternatives you've considered**

Maybe for common request, `https://dot.net/$path` should be simply redirected to `https://dotnet.microsoft.com/$path`, and we could add some other policies for some useful links like <https://docs.microsoft.com/dotnet/> to make it easier for users to access dotnet related things

**Additional context**

Maybe this is not the correct place to feedback, please let me know if I should provide feedback somewhere else.

**Comment by gewarren** [comment]
@mairaw Can you take a look at this issue?

**Comment by mairaw** [comment]
Thanks for the feedback @WeihanLi. Yeah, we can configure those individual redirects, not sure if we should/can do the blanketed `https://dot.net/$path`. @ChrisSfanos can you request those redirects for us?

**Comment by ChrisSfanos** [comment]
These have been submitted - these will roll out mid next week on the regular redirect system publishing schedule

**Comment by gewarren** [comment]
Thanks Maira and Chris. I'll close out this issue now.

**Comment by WeihanLi** [comment]
Works now, thanks everyone
