### ISSUE TITLE
Cleanup dev/testing repos left in the org

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/feedback#365]
**Is your feature request related to a problem? Please describe.**
There appears to be a bunch of repos created for the devs to test out the open publishing platform.
I was looking through https://opensource.microsoft.com/  and opening up repos that seemed to have dev github handles, "Sandbox", "Playground", or "Test" in the name and opened some issues. Here are the ones I found/opened
https://github.com/search?utf8=%E2%9C%93&q=org%3AMicrosoftDocs+author%3Anschonni+Delete+this+repo&type=Issues but I didn't make it through the list before stopping (around 27/40 pages)

**Describe the solution you'd like**
Give your developers a method of tagging the testing repos so a bot can come around and clean them out periodically. The repos probably shouldn't show up in the opensource.microsoft.com feed if they have been tagged as a test repo

**Describe alternatives you've considered**
Prevent repo creation to specific people and have people work from their own accounts if the publishing platform build supports that.

**Comment by dend** [comment]
@cillroy can you please follow-up here?

**Comment by dend** [comment]
#log-suggestion

**Comment by botcrane** [comment]
🚀 **ATTENTION**: [Internal request](https://ceapex.visualstudio.com/web/wi.aspx?pcguid=7d644393-99ad-41c8-ac53-7fa79294c720&id=20733) logged.

**Comment by cillroy** [comment]
we are not going to auto delete repo's due to the potential implication... we are working on a reporting method to nag owners of a repo to manage their repo's... but this will not happen for a long time.  I have noted this suggestion for a future feature

**Comment by nschonni** [comment]
Here is another one https://github.com/MicrosoftDocs/OfficeDocs-SfBLocTest-pr
There are still 19 that I originally flagged too

**Comment by Powerhelmsman** [comment]
@cillroy for you awareness.

**Comment by nschonni** [comment]
So there are now 148 test repos that have been made public https://github.com/MicrosoftDocs?utf8=%E2%9C%93&q=test&type=&language=

**Comment by cillroy** [comment]
Thanks for the update, we are still evaluating how we can address this with a long term vision that can be automated
