### ISSUE TITLE
Update docs for AssemblyBuilder for net core, net standard, net 5 and higher

### ISSUE THREAD

**Issue by snaulX** [MicrosoftDocs/feedback#3655]
All of this docs of [AssemblerBuilder](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.emit.assemblybuilder) for .NET Core and higher contains info that you can **save** assembly using `AssemblyBuilderAccess.RunAndSave` or `AssemblyBuilderAccess.Save`. But these access modes supports only in .NET Framework. So fix sample and remove or edit information about saving assemblies on platforms that higher than .NET Framework.

**Comment by gewarren** [comment]
This issue was moved to dotnet/dotnet-api-docs#6889
