### ISSUE TITLE
Links in document don't work, the ones in sidebar do work

### ISSUE THREAD

**Issue by JeroenOortwijn** [MicrosoftDocs/feedback#3656]
**Describe the bug**
The links in a document that point to another section in that document don't work. When you click on it, nothing happens.
The same links in the `In this article` sidebar do work. When you click on it, you go to the relevant section.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://docs.microsoft.com/en-us/dotnet/api/system.string.split
2. Click on the `Split(Char[])` link in the `Overloads` section.
3. You will notice that the page stays the same and doesn't jump to the `Split(Char[])` section.
---
4. Click on the `Split(Char[])` link in the `In this article` sidebar.
5. You will notice that the page jumps to the `Split(Char[])` section.

**Expected behavior**
In both cases it should jump to the `Split(Char[])` section.

**Additional context**
Note that the link at step 2 is:
`https://docs.microsoft.com/en-us/dotnet/api/system.string.split?view=net-5.0#system-string-split(system-char-)`
And the link at step 4 is:
`https://docs.microsoft.com/en-us/dotnet/api/system.string.split?view=net-5.0#System_String_Split_System_Char___`

**Comment by gewarren** [comment]
Thank you for letting us know. This has been fixed now.
