### ISSUE TITLE
[LOC]Over Translation (ja-jp)

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/feedback#3659]
ja-jp:"https://docs.microsoft.com/ja-jp/sharepoint/administration/configure-usage-and-health-data-collection"
![configure-usage-and-health-data-collection_j](https://user-images.githubusercontent.com/40815708/126319767-89d1f2d3-e137-4d32-813e-168c2177ee26.png)

en-us:"https://docs.microsoft.com/en-us/sharepoint/administration/configure-usage-and-health-data-collection"
![configure-usage-and-health-data-collection_e](https://user-images.githubusercontent.com/40815708/126319796-e91f9b34-a3a1-41d6-9efa-072fab09e2b0.png)

#PingMSFTDocs

**Comment by rootsmusic** [comment]
@hyoshioka0128 Please move this issue to https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/issues

**Comment by hyoshioka0128** [comment]
@rootsmusic  - Thanks!
Opened https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/issues/2887 .
Closed #3659 .
