### ISSUE TITLE
Showing "[!div class="mx-tdCol2BreakAll"]"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/feedback#3663]
https://docs.microsoft.com/en-us/azure/rtos/netx-duo/chapter2

![netx-duo_chapter2_e](https://user-images.githubusercontent.com/40815708/127139910-2fec4625-999f-4094-bc27-18f2ea11b83b.png)

#PingMSFTDocs

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by rootsmusic** [comment]
@hyoshioka0128 Please move this issue to https://github.com/MicrosoftDocs/azure-docs/issues

**Comment by hyoshioka0128** [comment]
@rootsmusic - Thanks!
Opened https://github.com/MicrosoftDocs/azure-docs/issues/79080 .
Closed #3663 .
