### ISSUE TITLE
[LOC]Unnecessary asterisks are displayed (ja-jp)

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/feedback#3664]
https://docs.microsoft.com/ja-jp/azure/rtos/netx-duo/chapter2

![netx-duo_chapter2_j](https://user-images.githubusercontent.com/40815708/127140385-dc191109-e0d0-41ee-a147-4894b9c25e44.png)

#PingMSFTDocs

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by rootsmusic** [comment]
@hyoshioka0128 Please move this issue to https://github.com/MicrosoftDocs/azure-docs/issues

**Comment by hyoshioka0128** [comment]
@rootsmusic - Thanks!
Opened https://github.com/MicrosoftDocs/azure-docs/issues/79081 .
Closed #3664 .
