### ISSUE TITLE
[LOC]Unnecessary asterisks are displayed (ja-jp) 

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/feedback#3665]
ja-jp:"https://docs.microsoft.com/ja-jp/azure/rtos/threadx-modules/chapter3"
![chapter3_j](https://user-images.githubusercontent.com/40815708/127257994-bb03eb11-af03-4c2d-b3e0-d7fed9aae681.png)

en-us:"https://docs.microsoft.com/en-us/azure/rtos/threadx-modules/chapter3"
![chapter3_e](https://user-images.githubusercontent.com/40815708/127257999-3bae3872-af07-4a11-b6e1-521a1e2e8324.png)

#PingMSFTDocs

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by rootsmusic** [comment]
@hyoshioka0128 Please move this issue to https://github.com/MicrosoftDocs/azure-docs/issues

**Comment by hyoshioka0128** [comment]
@rootsmusic - Thanks!
Opened https://github.com/MicrosoftDocs/azure-docs/issues/79083 .
Closed #3665 .
