### ISSUE TITLE
Descriptor Table's Overview figure is misleading, textures in upload heaps

### ISSUE THREAD

**Issue by FreakingBarbarians** [MicrosoftDocs/feedback#3669]
In the doc here, there is a figure showing descriptors in a table referencing textures in an upload heap.
AFAIK you can't have texture resources in an upload heap (in the discrete gpu case at least).
 
https://docs.microsoft.com/en-us/windows/win32/direct3d12/descriptor-tables-overview

![image](https://user-images.githubusercontent.com/7800721/127686113-2f6544e1-8c99-4ae6-b17b-122772a8c71b.png)

**Comment by FreakingBarbarians** [comment]
I should also point out the figure description is also misleading

"The image below shows these concepts: the descriptor table pointers from the Root Signature and the descriptors within the descriptor heap **referencing the full texture or buffer data in an upload heap**."

**Comment by stevewhims** [comment]
Thanks for the issue. I'm making enquiries about the technicalities here. Once I'm certain of the situation, I'll let you know, and if necessary I'll make corrections to the topic.

-Steve

**Comment by stevewhims** [comment]
**UPDATE**: I've confirmed that the content and image were incorrect, just as you said! The fix is now live.

Thanks again!
-Steve

**Comment by Jasonizback** [comment]
Thx this is a start
