### ISSUE TITLE
Add repo description and website url for repos in this org

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/feedback#367]
**Is your feature request related to a problem? Please describe.**
When looking at the list of repos in the [MicrosoftDocs organization](https://github.com/MicrosoftDocs) most don't have descriptions or the URLs set. I'm not sure if that information also populates https://opensource.microsoft.com/ or if that is something else.

**Describe the solution you'd like**
Add a small blurb and the public website URL for the particular docs.microsoft.com subsite.

**Comment by Powerhelmsman** [comment]
@nschonni Thanks for your suggestion. I will bring it to the team to discuss.

**Comment by Powerhelmsman** [comment]
#log-suggestion

**Comment by botcrane** [comment]
🚀 **ATTENTION**: [Internal request](https://ceapex.visualstudio.com/web/wi.aspx?pcguid=7d644393-99ad-41c8-ac53-7fa79294c720&id=20746) logged.

**Comment by meganbradley** [comment]
Internal guidance is available, but enforcing it with automation is not a priority at this time.
