### ISSUE TITLE
bug in migration Inheritance 

### ISSUE THREAD

**Issue by soufianeBenRahim** [MicrosoftDocs/feedback#3670]
hi
Thank you for your tremendous efforts in clarifying dotnet
in the Project of  ContosoUnivercity :https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/data/ef-rp/intro/samples/cu50/Data/SchoolContext.cs
The code in SchoolContext in methode OnModelCreating is incorrect after the modification related to Inheritance migration because studen corresponds to Steuden's table and instrector is to Instrector's table, while they should be to Pearson's table
![capture bug migration inirutance](https://user-images.githubusercontent.com/32791470/127754134-574b9ab5-fd0f-4b0b-a478-bef80dc92e9a.png)

The solution you applied is 
![capture bug migration inirutance 2](https://user-images.githubusercontent.com/32791470/127754186-03d88e73-a5fc-4ac0-974e-0b82df1ab971.png)

**Comment by rootsmusic** [comment]
@soufianeBenRahim Please move this issue to https://github.com/dotnet/AspNetCore.Docs/issues
