### ISSUE TITLE
Fed up withy GitHub, unable to download any of these ASP.NET Sample code

### ISSUE THREAD

**Issue by Johnvan** [MicrosoftDocs/feedback#3672]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by gewarren** [comment]
@Johnvan Can you provide a link to the page you were trying to download sample code from?

**Comment by Johnvan** [comment]
I was doing a step by step procedure by Microsoft, where in the old days I would click on their link to download, with no problems, their example code.
But now when I click that link I get sent to GitHub where, as far as I can see, there is no way, even when logging in, to download the files. In fact the files don’t seem to have anything to do with my subject.
The URL is as follows:
https://github.com/dotnet/AspNetCore.Docs/tree/main/aspnetcore/tutorials/razor-pages/razor-pages-start/sample/RazorPagesMovie50
It is all so confusing, he subject is correct “RazorPageMovie50” but the files !!!!!. and there is no way of downloading anything.
Kind regards,

John van der Linden
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by gewarren** [comment]
@wadepickett Could you take a look at this feedback?

**Comment by gewarren** [comment]
This issue was moved to dotnet/AspNetCore.Docs#23043

**Comment by Johnvan** [comment]
I have reported my problems to Microsoft and will let them sort it out.

John van der Linden
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
