### ISSUE TITLE
can't access Q&A forums

### ISSUE THREAD

**Issue by rootsmusic** [MicrosoftDocs/feedback#3679]
**Describe the bug**
I wanted to change the email address for my username.  So I changed my old account's username (in order to make it available again).  Then I created a new account for a new email address.  In my new account's Settings, I changed its username to my old account's old username.

I'm trying to access Q&A forums with my new account, but it won't let me access.

**To Reproduce**
1. Sign-in at https://docs.microsoft.com/en-us/learn/
2. Click on [Q&A](https://docs.microsoft.com/en-us/answers/products/)
3. Click on [Feedback](https://docs.microsoft.com/en-us/answers/content/idea/list.html)

**Expected behavior**
I'm expecting to see list of posts in the Feedback forum.

**Screenshots**
https://docs.microsoft.com/en-us/answers/products/ reloads without any error.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge 92.0.902.78

@saldana

**Comment by v-navelu** [comment]
@rootsmusic - Looks like your email ID is no longer valid so our mails failing to deliver to you.

As mentioned earlier in my previous mails, The profile [rootsmusic | Microsoft Docs](https://docs.microsoft.com/en-us/users/rootsmusic/) linked to [rootsmusic-5221 | Microsoft Docs](https://docs.microsoft.com/en-us/users/rootsmusic-5221/). As soon as the profile link is completed, we delete the source profile to comply with user privacy policy. 
I remember you were able to login after changing your profile name from rootsmusic to  rootsmusic-5221. Did you changed the profile name back by any chance?

cc: @saldana

**Comment by rootsmusic** [comment]
@v-navelu This issue is fixed!  Thanks!
