### ISSUE TITLE
Error creating key file...: The network name cannot be found.

### ISSUE THREAD

**Issue by enzedonline** [MicrosoftDocs/feedback#3683]
**Describe the bug**
Running psexec (or psexec64) on local machine with -i and -s switch. Process fails with the error:

**To Reproduce**
eg `psexec64.exe -i -s %windir%\system32\mmc.exe /s taskschd.msc`
 
Output:
```
PsExec v2.34 - Execute processes remotely
Copyright (C) 2001-2021 Mark Russinovich
Sysinternals - www.sysinternals.com

Error creating key file on [[local machine name]]:
The network name cannot be found.
```

**Expected behavior**
Pre 2.3, this would run normally.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Microsoft Windows NT 10.0.19043.0
 - Browser n/a

**Comment by claudiamendez** [comment]
.

**Comment by gewarren** [comment]
This issue was moved to MicrosoftDocs/sysinternals#442
