### ISSUE TITLE
Show imports for code snippets in the documentation

### ISSUE THREAD

**Issue by orjandh** [MicrosoftDocs/feedback#3686]
**Is your feature request related to a problem? Please describe.**
When using code snippets from, for example, the .Net core documentation, I often have to do some light detective work to find which packages the different classes comes from.

**Describe the solution you'd like**
I would like the information about which packages the different classes used in the code snippets to also be present on the documentation page.

**Describe alternatives you've considered**
One alternative could be to have a tab in the code snippet that shows the imports.
Another alternative can be to have hyperlinks to the class reference when you click or hover over them in the code snippet,

**Comment by gewarren** [comment]
This issue was moved to dotnet/docs#26108
