### ISSUE TITLE
rendering issue with a Windows page layout

### ISSUE THREAD

**Issue by WilliamAntonRohm** [MicrosoftDocs/feedback#3687]
There is a rendering problem on this page
- [Mt.exe](https://docs.microsoft.com/en-us/windows/win32/sbscs/mt-exe)

as described in this issue
- https://github.com/MicrosoftDocs/visualstudio-docs/issues/7049

![mt](https://user-images.githubusercontent.com/27738025/133333126-866c08d6-d4f3-44a8-b670-81e70e7426a9.png)

**Comment by mcleanbyron** [comment]
WE have fixed the formatting issues in the article: https://docs.microsoft.com/en-us/windows/win32/sbscs/mt-exe

**Comment by WilliamAntonRohm** [comment]
#please-close
