### ISSUE TITLE
Move the OpenPublish Build to the new GitHub Checks API

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/feedback#370]
**Is your feature request related to a problem? Please describe.**
GitHub released the Checks API (with Micrsoft as a launch partner) https://blog.github.com/2018-05-07-introducing-checks-api/
This allows inline comments to the PRs, and would remove the build comments on PRs that trigger GitHub notifications.

**Describe the solution you'd like**
Leverage the Checks API like the App Center group has https://github.com/marketplace/app-center

**Describe alternatives you've considered**
Since this is requires a Marketplace published App, this might not work with your current Status API based setup.

**Comment by dend** [comment]
Thanks @nschonni - great idea! We are investigating this internally.

**Comment by cillroy** [comment]
We are investigating this as an option, but due to limitations in the current integration between Docs and GitHub we will have to hold off until the next version of Docs build

**Comment by nschonni** [comment]
It it's still being working (rather than not happening ever), does it make sense to leave the ticket open so others don't open another one?
