### ISSUE TITLE
404 - Page not Found hmm, we could not find this link.

### ISSUE THREAD

**Issue by stpetrus27** [MicrosoftDocs/feedback#3708]
**Describe the bug**
Hello, my account is stpetrus@live.co.kr. I logged in docs.microsoft.com then clicked the Q&A link, the site display following error message then banned(log out). But, if I log out from docs.microsoft.com then click the Q&A link, it works fine.

**To Reproduce**
1. Go to 'docs.microsoft.com', then login "stpetrus@live.co.kr"
2. Click on 'Q&A'

404 - Page not found
Hmm, we could not find this link. If you feel you are seeing this page in error, please enter a Site feedback and tell us which page you expected to find.

**Expected behavior**
I want to use the Q&A.

**Screenshots**
![image](https://user-images.githubusercontent.com/93641012/140022439-0f09e084-6451-4f76-917c-2507f56c6629.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge
 - Version: 95.0.1020.40

**Smartphone (please complete the following information):**

**Additional context**
I cannot use the Q&A From 2021-05.

**Comment by gewarren** [comment]
Tagging @saldana

**Comment by saldana** [comment]
@stpetrus27 somehow your account in Q&A was suspended. I lifted the suspension, so you should be able to see the site again. Please confirm that is the case once you have the chance.

**Comment by stpetrus27** [comment]
Thank you...I got it.
