### ISSUE TITLE
Repeated typo in PropertyAccessMode Enum documentation

### ISSUE THREAD

**Issue by yoizfefisch** [MicrosoftDocs/feedback#3714]
This document has a typo: https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.propertyaccessmode?view=efcore-5.0
The typo is repeated in the definition of the following fields: PreferField, PreferFieldDuringConstruction, PreferProperty

"in which as" should be "in which case".

**Comment by gewarren** [comment]
This issue was moved to dotnet/EntityFramework.ApiDocs#103
