### ISSUE TITLE
Typo in "Speech Service API Documentation"

### ISSUE THREAD

**Issue by shivang-g** [MicrosoftDocs/feedback#372]
**The bug**
There's a typo on one of the pages in the "Speech Service Documentation"

**To Reproduce**
1. Go to https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/
2. Scroll down to '[10-Minute Quickstarts - New SDKs](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/#10-minute-quickstarts---new-sdks)'
3. See the text just below the heading

**Expected behavior**
The line under the heading reads "_Learn how to install and use the **Speeck** SDK with our quickstarts_" where as it should be "_Learn how to install and use the **Speech** SDK with our quickstarts_" (presumably).

**Screenshots**
Please see attached screenshot.

![bug](https://user-images.githubusercontent.com/35758446/40119690-f36ac900-593a-11e8-86cd-3da0400fa73e.png)

**Comment by dend** [comment]
@wiazur can you please help here?

**Comment by wiazur** [comment]
Thanks for letting us know @dend !

**Comment by nschonni** [comment]
This is fixed now
