### ISSUE TITLE
Enumerable.MaxBy should describe behavior of throw Sequence contains no elements InvalidOperationException for empty primitive type enumerables

### ISSUE THREAD

**Issue by Smoovsky** [MicrosoftDocs/feedback#3721]
**Describe the bug**
I noticed new Sytem.Linq.Enumrable.MaxBy method provided in .NET 6.0:
[doc](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.maxby?view=net-6.0)
The documentation states two types of exception ArgumentException and ArgumentNullException to be expected.
But InvalidOperationException may also be thrown for empty primitive type enumerables, see the example below.

**To Reproduce**
Snippet:
```
void Main()
{
	var test1 = new Test[] { }.MaxBy(x => x.MyProperty); // no problem
	var test2 = new Test[] { new Test { MyProperty = 1 }, new Test { MyProperty = 1 } }.MaxBy(x => x.MyProperty); // no problem
	var test3 = new int[] { }.MaxBy(x => x); // exception here
}

public class Test
{ 
	public int MyProperty { get; set; }
}
```
Run result:
![image](https://user-images.githubusercontent.com/34542126/144364210-26543990-4609-4bbc-ad41-21912e6446de.png)

**Comment by gewarren** [comment]
This issue was moved to dotnet/dotnet-api-docs#7461
