### ISSUE TITLE
API Browser documentation contains links to Reference Source

### ISSUE THREAD

**Issue by cdanek** [MicrosoftDocs/feedback#3724]
**Is your feature request related to a problem? Please describe.**

When diving into a specific API call in the .NET ecosystem, I often find myself (for various reasons: curiosity included) diving into the reference source, which was made open in 2014 - a move that is widely considered to be a positive one. That being said, there is a workflow hiccup in this process, which typically involves some fumbling through code on https://referencesource.microsoft.com/ to find the actual external/public method after reading about it on https://docs.microsoft.com/. 

**Describe the solution you'd like**

I would like to see the addition of a new section in the "In This Article" with links to relevant reference source directly. 

I do understand the impact of this request, but I would like to humbly submit it nonetheless. I'll leave the discussion of policy impact to those with a pay grade that exceeds mine.

**Comment by gewarren** [comment]
This issue was moved to dotnet/dotnet-api-docs#7460
