### ISSUE TITLE
PDF Download link broken

### ISSUE THREAD

**Issue by Nathan-Tarin** [MicrosoftDocs/feedback#373]
The link that should allow us to download a PDF version of the Visual Studio Subscriptions docs is broken.

1. Go to 'https://docs.microsoft.com/en-us/visualstudio/subscriptions/'
2. Scroll down to 'Download PDF'
3. Click on 'Download PDF'

**Expected behavior**
A downloadable file should appear.

**Desktop (please complete the following information):**
 - OS: [Windows 10 Fall Creators Edition]
 - Browser [EDGE]

**Comment by dastaffo** [comment]
@adkinn Can you help investigate here?

**Comment by dastaffo** [comment]
@Nathan-Tarin This should be working now. Let me know if you still have issues.
