### ISSUE TITLE
Possible Errors in System.Security.AccessControl Documentation

### ISSUE THREAD

**Issue by nick1941** [MicrosoftDocs/feedback#3735]
In the .NET 6 documentation for System.Security.AccessControl in the topic on FileSystemRights Enum (https://docs.microsoft.com/en-us/dotnet/api/system.security.accesscontrol.filesystemrights?view=net-6.0) in the Fields list, there are a number of duplicate values.
    AppendData and CreateDirectories both have a value of 4
    CreateFiles and WriteData both have a value of 2

**Comment by gewarren** [comment]
@nick1941 This appears to be by design: https://github.com/dotnet/runtime/blob/513fe2863ad5ec6dc453d223d4b60f787a0ffa78/src/libraries/System.IO.FileSystem.AccessControl/src/System/Security/AccessControl/FileSystemRights.cs#L16.

**Comment by gewarren** [comment]
This issue was moved to dotnet/dotnet-api-docs#7587
