### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by instrumentalwithabhi** [MicrosoftDocs/feedback#3737]
There is a broken link on this page: https://docs.microsoft.com/en-us/learn/modules/get-started-ai-fundamentals/8-understand-responsible-ai. Kindly check.

Further resources
For more resources to help you put the responsible AI principles into practice, see https://www.microsoft.com/ai/responsible-ai-resources --> Broken link

![Err](https://user-images.githubusercontent.com/94283265/147662365-d0103893-52a2-48e1-bb8d-bd3d6e2583c1.JPG)

**Comment by gewarren** [comment]
@jonburchel Can you take a look?

**Comment by Rick-Anderson** [comment]
The link works for me.

**Comment by gewarren** [comment]
Thanks @instrumentalwithabhi. Looks like this has been addressed.
