### ISSUE TITLE
CA2254 404 Not Found

### ISSUE THREAD

**Issue by pcartwright81** [MicrosoftDocs/feedback#3740]
**Describe the bug**
CA2254 404 Not Found

**To Reproduce**
1. Have VS get a CA2254 message.
2. Click on CA2254

**Expected behavior**
Navigate to a page that works.

**Screenshots**
![image](https://user-images.githubusercontent.com/2352477/147880646-694c9447-e3fc-4296-99de-210f29bc4f28.png)
![image](https://user-images.githubusercontent.com/2352477/147880677-4ec7dae2-dc30-411d-867b-1789d8794f3a.png)

**Desktop (please complete the following information):**
All

**Comment by gewarren** [comment]
This issue was moved to dotnet/docs#27857
