### ISSUE TITLE
Yu

### ISSUE THREAD

**Issue by FrankW68** [MicrosoftDocs/feedback#3748]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by gewarren** [comment]
@FrankW68 What exactly is the bug?

**Comment by FrankW68** [comment]
Hi Genevieve,

I think it is a mistake from my side. I don’t have bugs / problems with Microsoft.

Met vriendelijke groet / Mit freundlichen Grüßen / With kind regards,

Frank Westervoorde

***@***.***




www.smartfactory.nl<http://www.smartfactory.nl>
+31 53 89 00 250
+31 6 53 32 32 89

Op 16 feb. 2022, om 22:51 heeft Genevieve Warren ***@***.******@***.***>> het volgende geschreven:



@FrankW68<https://github.com/FrankW68> What exactly is the bug?
