### ISSUE TITLE
Discourage use of `~/` linking in docs

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/feedback#375]
**Is your feature request related to a problem? Please describe.**
This style of linking is supported by DocFx, but produces invalid links when navigating the documentation on GitHub. EX: On https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/analytics/event-metrics.md, the link `~/sdk/index.md` resolves to an invalid page https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/analytics/%7E/sdk/index.md

**Describe the solution you'd like**
Update your styleguides to discourage the use of these links and update https://github.com/Microsoft/vscode-docs-authoring to help authors re-write their links to regular relative markdown links

**Describe alternatives you've considered**
Maybe GitHub navigation isn't a primary use case for the docs published here.

**Comment by BillWagner** [comment]
@dend This can be closed. It was fixed in microsoftDocs/Contribute#29

**Comment by nschonni** [comment]
Thanks!
