### ISSUE TITLE
Using .. in DOS device path works in cmd.exe even though shouldn't according to documentation

### ISSUE THREAD

**Issue by Wallby** [MicrosoftDocs/feedback#3752]
**Describe the bug**
At https://docs.microsoft.com/en-us/dotnet/standard/io/file-path-formats there is text.. "_DOS device paths are fully qualified by definition. Relative directory segments (. and ..) are not allowed._". However, in cmd.exe the following works..
```
\\.\..\UNC\..\UNC\Maarten-PC\c$\Windows\System32\..\notepad.exe
\\.\C:\Windows\..\Windows\notepad.exe
```

**To Reproduce**
See description

**Expected behavior**
Not sure.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 21H2

**Comment by gewarren** [comment]
This issue was moved to dotnet/docs#28279
