### ISSUE TITLE
Missing image

### ISSUE THREAD

**Issue by alswl** [MicrosoftDocs/feedback#376]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

**Link to article:**
Tell us where exactly a problem occurs.

https://docs.microsoft.com/en-us/previous-versions/sql/sql-server-2008/dd266396(v=sql.100)#configuration-of-the-capture-job

**Problem:**
What's wrong with the article?

This article contains serverl images original, but all of images is lost after MSDN upgraded.

One of the image is like this: 
https://img.scoop.it/bT3HxbvXBSdoHvXYl9vY5Tl72eJkfbmt4t8yenImKBVvK0kTmF0xjctABnaLJIm9

**Comment by alswl** [comment]
After hours searching, I found a copy of this article.

[Tuning-the-Performance-of-Change-Data-Capture-in-SQL-Server-2008.zip](https://github.com/MicrosoftDocs/feedback/files/2012014/Tuning-the-Performance-of-Change-Data-Capture-in-SQL-Server-2008.zip)

**Comment by Khairunj** [comment]
Thank you alswl for reporting this issue we are working on restoring the images in the article.

**Comment by alswl** [comment]
It is fixed, thanks.
