### ISSUE TITLE
System.Xml.XPath documentation for Extensions.CreateNavigator displays wrong example

### ISSUE THREAD

**Issue by nick1941** [MicrosoftDocs/feedback#3760]
The example for System.Xml.XPath.Extensions.CreateNavigator() at site https://docs.microsoft.com/en-us/dotnet/api/system.xml.xpath.extensions.createnavigator?view=net-6.0#system-xml-xpath-extensions-createnavigator(system-xml-linq-xnode) shows an example.  However, it does not actually show an example for the use of Extensions.CreateNavigator(XNode).  It is showing an example for the use of XDocument.CreateNavigator().  Note that the call to CreateNavigator() shown in the example has no XNode parameter and there is no reference to an XNode in the example.

**Comment by gewarren** [comment]
This issue was moved to dotnet/dotnet-api-docs#7860
