### ISSUE TITLE
How does docs.microsoft.com work?

### ISSUE THREAD

**Issue by rm234179** [MicrosoftDocs/feedback#3761]
I am building an ASP.NET Core application for my company and would like to implement a help site to explain the pages and workflows . I like the look and feel of does docs.microsoft.com and would like to replicate something like it for my site. What tools does this site use? 

Note, I have seen references to Westwind.AspNetCore.Markdown and would like to know if it is something people would recommend.

I clicked on the feedback to get to this page. I realize it isn't a bug or official issue. Please let me know if there is somewhere better to post.

**Comment by PaulDempsey-ms** [comment]
The site is based on [DocFx](https://dotnet.github.io/docfx/), with extensive docs-specific extensions and modifications. There's also a lot of dedicated internal infrastructure and tools required by a system as huge as docs.microsoft.com. For a single application, DocFx is a great way to stand up a good-looking and functional documentation site quickly. DocFx is pluggable if you need to add capabilities (and have the engineering skills).

**Comment by rm234179** [comment]
@PaulDempsey-ms thank you for the link and info.
