### ISSUE TITLE
Asp.Net core document sidebar translation does not work

### ISSUE THREAD

**Issue by xxxxue** [MicrosoftDocs/feedback#3762]
**Describe the bug**
On the "asp.net core MVC" page in Chinese, the sidebars are all in English,
I remember it was in Chinese before,
It seems that pages in other languages also have this problem

**To Reproduce**
1. [Click this link to enter the relevant Chinese page](https://docs.microsoft.com/zh-cn/aspnet/core/tutorials/first-mvc-app/start-mvc?view=aspnetcore-6.0&tabs=visual-studio)

**Expected behavior**
Sidebar restore previous Chinese

**Screenshots**
![image](https://user-images.githubusercontent.com/32764266/155870650-be31930e-6825-4360-bf49-8631b5131e5b.png)
![image](https://user-images.githubusercontent.com/32764266/155870709-315ac2de-4530-4893-8b13-b04e1fb8302d.png)

**Desktop (please complete the following information):**
 - OS: [ PC ]
 - Browser [ Edge ]
 - Version [ 98.0.1108.62]

**Comment by gewarren** [comment]
@khoiph1 Do you know about this?
