### ISSUE TITLE
Setting Attribute Typo (SQLSetConnectAttr)

### ISSUE THREAD

**Issue by dhurley28** [MicrosoftDocs/feedback#377]
**Link to article:**
https://docs.microsoft.com/en-us/sql/relational-databases/native-client-odbc-api/sqlsetconnectattr?view=sql-server-2017#sqlcoptssmultisubnetfailover

**Problem:**
Incorrect setting attribute within the example code section - 

SQLSetConnectAttr(hdbc, **SQL_COPT_SS_MULTISUBMIT_FAILOVER**, SQL_IS_ON, SQL_IS_INTEGER) 

Should read - 

SQLSetConnectAttr(hdbc, **SQL_COPT_SS_MULTISUBNET_FAILOVER**, SQL_IS_ON, SQL_IS_INTEGER)

**Comment by dend** [comment]
@nschonni wow, thanks for the PR! 🔥

@MightyPen should be able to help here.

**Comment by nschonni** [comment]
This is fixed now

**Comment by Powerhelmsman** [comment]
Thanks  @nschonni for help. @dhurley28 Close as resolved.
