### ISSUE TITLE
B2B end point 404 for all links

### ISSUE THREAD

**Issue by phmayer67** [MicrosoftDocs/feedback#378]
# Idea Title

https://docs.microsoft.com/en-us/azure/active-directory/b2b/what-is-b2b.md is missing. All links under b2b are now gone.

**Comment by nschonni** [comment]
You've got `md` at the end of the URL, should be https://docs.microsoft.com/en-us/azure/active-directory/b2b/what-is-b2b but that does sound like a build error if it didn't fix that when publishing

**Comment by dend** [comment]
@phmayer67 can you let us know where you got that link?

**Comment by Powerhelmsman** [comment]
Closed as no enough information.
