### ISSUE TITLE
Remove an obsoleted article https://docs.microsoft.com/en-us/archive/blogs/xiangwu/azure-vm-storage-performance-and-throttling-demystify#how-azure-throttles

### ISSUE THREAD

**Issue by xiangwuxw** [MicrosoftDocs/feedback#3780]
**Describe the bug**
Remove a blog I wrote 5 years ago which is no longer appliable to Azure storage. Due to it's migrated to archive, I no longer have permission to remove it myself.

**Comment by gewarren** [comment]
@xiangwuxw Do you want to remove the whole article, or just the section How Azure Throttles?

**Comment by xiangwuxw** [comment]
Let's remove the whole article. Thank you Genevieve.

**Comment by xiangwuxw** [comment]
@gewarren Let's remove the whole article. Thank you!

**Comment by gewarren** [comment]
It should be gone in the next hour or two. BTW, if you view the source for the page, you can find the location of the file from the `original_content_git_url` metadata.

**Comment by gewarren** [comment]
It's gone now, so I'm going to close this issue.
