### ISSUE TITLE
Two-column tables not displaying properly -- right column is cut off at right page content margin

### ISSUE THREAD

**Issue by WilliamAntonRohm** [MicrosoftDocs/feedback#3785]
**Describe the bug**
This Azure DevOps article shows the behavior described in this issue's title:
- [Use predefined variables](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables)

**To reproduce**
Go to the [Agent variables (DevOps Services)](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#agent-variables-devops-services) section to see this behavior.

**Expected behavior**
Right column properly sized, with text wrapping.

**Screenshots**
![snap00498](https://user-images.githubusercontent.com/27738025/166610826-cad22880-995d-420d-910b-84d1e6c47394.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge
 - Version 102.0.1235.1 (Official build) dev (64-bit)

**Smartphone (please complete the following information):**
N/A

**Additional context**
Created from https://github.com/MicrosoftDocs/azure-devops-docs/issues/12149

**Comment by chipplyman** [comment]
There is a horizontal scrollbar at the bottom of that table.  I just filed https://github.com/MicrosoftDocs/feedback/issues/3903 with a more general description of this specific issue.
