### ISSUE TITLE
Please add default/min/max value to parameter and type info for REST documentation

### ISSUE THREAD

**Issue by chgennar-zz** [MicrosoftDocs/feedback#379]
Many parameters in REST APIs have default, minimum and maximum values which are not currently displayed in the parameter table.  This makes using the APIs difficult.  Please add this information to the parameter table in some way.

**Comment by Powerhelmsman** [comment]
@hellosnow Can you take a look at this?

**Comment by Powerhelmsman** [comment]
#log-suggestion

**Comment by botcrane** [comment]
🚀 **ATTENTION**: [Internal request](https://ceapex.visualstudio.com/web/wi.aspx?pcguid=7d644393-99ad-41c8-ac53-7fa79294c720&id=21262) logged.

**Comment by hellosnow** [comment]
@Powerhelmsman thanks I'll follow up on this

**Comment by hellosnow** [comment]
@Powerhelmsman @dend please help to triage the issue and find the right assignee in case you miss it 😄

**Comment by keziamicro** [comment]
Hello - reviewing and cleaning up some older feedback/issues. Thanks!
