### ISSUE TITLE
Microsoft blog serie pages wrongly refer to each other.

### ISSUE THREAD

**Issue by yletallec** [MicrosoftDocs/feedback#3794]
**Describe the bug**
These blog serie pages:
https://docs.microsoft.com/en-us/archive/blogs/csharpfaq/parallel-programming-in-net-framework-4-getting-started
https://docs.microsoft.com/en-us/archive/blogs/csharpfaq/parallel-programming-task-schedulers-and-synchronization-context
https://docs.microsoft.com/en-us/archive/blogs/csharpfaq/parallel-programming-task-cancellation
https://docs.microsoft.com/en-us/archive/blogs/csharpfaq/blocking-collection-and-the-producer-consumer-problem
wrongly refer to each other:
https://review.docs.microsoft.com/archive/blogs/csharpfaq/parallel-programming-in-net-framework-4-getting-started
https://review.docs.microsoft.com/archive/blogs/csharpfaq/parallel-programming-task-schedulers-and-synchronization-context
https://review.docs.microsoft.com/archive/blogs/csharpfaq/parallel-programming-task-cancellation
https://review.docs.microsoft.com/archive/blogs/csharpfaq/blocking-collection-and-the-producer-consumer-problem

**To Reproduce**
1. Go to the page listed above
2. Examine any link on the page, the targets all start with review.docs.microsoft.com/*****
3. Clicking on the link, you are not allowed to acces the page

**Expected behavior**
I find the appropriate intended documentation.

**Screenshots**
![image](https://user-images.githubusercontent.com/9073846/167586808-a56c6ddf-22d9-43e4-b20c-c580dffc39a1.png)

**Comment by gewarren** [comment]
Thank you @yletallec. The fix should be live in the next 2 hours.
