### ISSUE TITLE
Wrong syntax highlights in MSDN Magazine Archive

### ISSUE THREAD

**Issue by masaru-iritani** [MicrosoftDocs/feedback#3797]
**Describe the bug**
C++ code samples in MSDN Magazine Archive are syntax-highlighted as XML.

**To Reproduce**
1. Go to [C++ - From Algorithms to Coroutines in C++ | Microsoft Docs](https://docs.microsoft.com/en-us/archive/msdn-magazine/2017/october/c-from-algorithms-to-coroutines-in-c).
3. Scroll down to the first code block.
4. See the code block is syntax-highlighted as XML.

**Expected behavior**
The code block is syntax-highlighted as C++.

**Screenshots**
![A screenshot of the code block syntax-highlighted as XML](https://user-images.githubusercontent.com/25241373/168098030-e92a75f1-b2d2-40e5-9b4f-b067b02096ff.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Edge
 - Version: 103.0.1253.0

**Smartphone (please complete the following information):**
 - Device: Pixel 5a
 - OS: Android 12
 - Browser: Firefox
 - Version: 100.1.1

**Additional context**
N/A

**Comment by gewarren** [comment]
Thank you - this has been fixed and the fix should be live in ~2 hours.
