### ISSUE TITLE
Search results should show technical area and should include filtering / sorting

### ISSUE THREAD

**Issue by supernova-eng** [MicrosoftDocs/feedback#38]
Problem: Search results are a mixed bag. Even when larger search queries are used and searching only happens within one area of the docs, the results often span many technologies within that area.

Solution: Search results should be filterable, sortable, and should display what area or technology the result comes from.

Examples: For example, what if I want info on how to create stored procedures in SQL server? searching for 'stored procedure' yields 5,293 results. I'm not going to page through those. What area of the docs do the links point to? The only way to tell is by clicking the link, or maybe hovering over to see the url. Once I click on the top link, there is no clear way to tell how to create the stored procedure.

The situation is even worse with other keywords that are fundamental to SQL Server. Searching for 'cursor' yields plenty of results, but when searching for how to use a cursor in SQL Server 2008 the old docs were a generation better for finding or navigating to the info I need.

The new docs overall are pretty sweet on the actual pages - much better than the old docs. However, the search functionality as it currently stands is harmful to the UX.

----------
⚠ Idea migrated from UserVoice

**Created By:** Aaron
**Created On:** 2018/01/18 17:09:36 +0000
**Votes at Migration:** 1
**Supporters at Migration:** 1

**Comment by dend** [comment]
#log-suggestion @presleyy

**Comment by botcrane** [comment]
🚀 **ATTENTION**: [Internal request](https://ceapex.visualstudio.com/web/wi.aspx?pcguid=7d644393-99ad-41c8-ac53-7fa79294c720&id=21334) logged.

**Comment by brikeler** [comment]
The 'Filter by Title' is about worthless.  This box should a 'Search within Document'.  Once you are on the documentation for the product, usually you are searching for key words within the document.  This is a rudimentary requirement.  Kudos for coming so far with the Azure Documentation, but a better search mechanism is mandatory.

**Comment by ADataGMan** [comment]
If I ever need to search Microsoft Docs I know not to use the search bar because at best the result is tangentially related. When I'm in a section like SQL, I see a filter option but that only works if the content is in the title. I need a search bar. And I need that search bar to be scopable by the breadcrumb level I'm in. If I'm searching at SQL, give me all related content there. If I'm searching for something within the functions, give me results only from the function section of the SQL Server docs.

**Comment by keziamicro** [comment]
Hello - reviewing and cleaning up some older feedback/issues. Thanks!

**Comment by ADataGMan** [comment]
This was closed but was it addressed anywhere? All the links I've followed are locked to me or closed as duplicate of this.

**Comment by keziamicro** [comment]
@ADataGMan We've moved this feedback over to the search team's backlog (cannot link to that due to permissions issues). But the team lead @sudeepku has been looped in.
