### ISSUE TITLE
Link to Windows 8 app development is broken

### ISSUE THREAD

**Issue by wldevries** [MicrosoftDocs/feedback#380]
**Link to article:**
https://docs.microsoft.com/en-us/previous-versions/windows/

**Problem:**
The link 'Windows 8' in the 'Windows app development' section is broken. Instead of browsing to the Windows 8 API documentation the current page just reloads

In addition I'm missing any reference to Windows 8.1 API in the previous versions documentation overview.

**Comment by dend** [comment]
@Khairunj can you help investigate this, please?

**Comment by Khairunj** [comment]
The Windows 8 link is now fixed thanks for reporting the issue.
