### ISSUE TITLE
bug issues, resolve immediately please

### ISSUE THREAD

**Issue by Irobert12** [MicrosoftDocs/feedback#3806]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Rick-Anderson** [comment]
This should be closed but there are no humans to contact.

**Comment by Rick-Anderson** [comment]
@gewarren do you know how to close issues in this repo?
@Irobert12 can you close this issue?
