### ISSUE TITLE
[error message feedback][TEST] provide feedback

### ISSUE THREAD

**Issue by erjain** [MicrosoftDocs/feedback#3807]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

**Problem:**
Getting Validation status: errors

**Log code info**
(This is auto filled, no need to modify)

| Severity   | Type   | Code   | Category   | File   | Message   |  Source  | Line   | Time   |
|------------|--------|--------|------------|--------|-----------|----------|--------|--------|
| Error | System |  |  |  |  |  | |  |

**Link to report**
(This is auto filled, no need to modify)

[report url](https://buildapi.docs.microsoft.com/Output/PullRequest/2d47196d-f150-fa9e-a72a-8e0ea5140215/202206061236013840-27297/BuildReport?accessString=8eb0a83bb704632ec5fd2a73c9ed83aaab374553d45294205c7c915b30d26546

**Comment by Rick-Anderson** [comment]
Per the report
Some unexpected errors happened when running build, please open a ticket in https://aka.ms/SiteHelp and include the error report for our team to troubleshoot

You can usually fix the build problem by closing and reopening the PR. This is the wrong place to report OPS build issues. Please close this issue.

**Comment by Rick-Anderson** [comment]
@erjain how did you create this issue?

**Comment by erjain** [comment]
There was a link on the build report, which redirected me to submit the issue here. Though the issue is resolved now, so I am closing it.
