### ISSUE TITLE
How to build these docs?

### ISSUE THREAD

**Issue by SeaDude** [MicrosoftDocs/feedback#381]
**Is your feature request related to a problem? Please describe.**
Microsoft does not have a static site generator product. Its a large gap in your offerings. I'd like to understand how you build the docs at https://docs.microsoft.com/en-us/azure/cognitive-services/QnAMaker/quickstarts/create-publish-knowledge-base and deploy this model at my own org.

**Describe the solution you'd like**
I'd like to know the workflow used to create the docs at https://docs.microsoft.com/en-us/azure/cognitive-services/QnAMaker/quickstarts/create-publish-knowledge-base. I'd like to write instructions for others to use this workflow. 

**Describe alternatives you've considered**
MANY alternatives have been investigated (Gitbook, Confluence Wiki, etc). Since my org is a Microsoft shop, non-ms tools are tough to stand up. 

**Additional context**
I want to understand how you build the docs at https://docs.microsoft.com/en-us/azure/cognitive-services/QnAMaker/quickstarts/create-publish-knowledge-base. I'm hoping, in spirit of Microsoft's newer Open Source attitude and actions, that this workflow and the build tools are open source and free to tinker with. 

I look forward to a response. Thank you very much.

**Comment by dend** [comment]
@SeaDude we use DocFX - it's free and open source! You can learn more here: https://dotnet.github.io/docfx/

**Comment by SeaDude** [comment]
Thank you for the prompt reply @dend. I will investigate the DocFX tool. Please send a link to the template used to build the docs at https://docs.microsoft.com/en-us/azure/cognitive-services/QnAMaker/quickstarts/create-publish-knowledge-base.
