### ISSUE TITLE
How to update item on home page of .NET API browser

### ISSUE THREAD

**Issue by smitpatel** [MicrosoftDocs/feedback#3810]
**Describe the bug**
Link https://docs.microsoft.com/en-us/dotnet/api/ has quick filters which mentions entity framework core 5.0 but latest version is 6.0. How to update it?

**Screenshots**
![image](https://user-images.githubusercontent.com/1528107/173414331-bd622c1c-ad7c-4f6d-8f0f-fefb16c16b9b.png)

**Comment by Rick-Anderson** [comment]
@smitpatel  you need to open an OPS issue and ask them to update that.  See [Moniker / version selector changes](https://github.com/Rick-Anderson/Report/blob/master/kt.md#moniker--version-selector-changes) and ping me if you get stuck.

**Comment by poojabhoi1l** [comment]
@smitpatel .NET 7.0.0-preview.5 is available for preview at https://dotnet.microsoft.com/en-us/download/dotnet/7.0
