### ISSUE TITLE
The Welcome Bot's Support Link is Wrong

### ISSUE THREAD

**Issue by aisgbnok** [MicrosoftDocs/feedback#3813]
### Bug Description

The welcome bot's support link is wrong. For example, click the welcome bot support link under this issue.

### Steps to Reproduce

1. Open a new first issue at [MicrosoftDocs/feedback](https://github.com/MicrosoftDocs/feedback)
2. Wait for the welcome bot to comment.
3. Click on https://support.microsoft.com/allproducts in the comment.
4. Get a `404` error.

### Expected Behavior

Welcome bot's support link should be https://support.microsoft.com/all-products

**Comment by Rick-Anderson** [comment]
<img width="416" alt="image" src="https://user-images.githubusercontent.com/3605364/174229637-d98dea89-9ce1-4cfd-82dd-b319b10d4765.png">

Confirmed.

**Comment by poojabhoi1l** [comment]
![13](https://user-images.githubusercontent.com/106469400/174966911-a7b36afc-0b13-4a09-ace5-ae465a3f50f6.PNG)


![12](https://user-images.githubusercontent.com/106469400/174966507-1a9555e8-446d-43b9-a6e1-b4b8e3bcb4e2.PNG)

The correct support link should be https://support.microsoft.com/all-products
