### ISSUE TITLE
D365FO: Edit invoice IDs on sales orders for Eastern Europe

### ISSUE THREAD

**Issue by mrsalonen** [MicrosoftDocs/feedback#3815]
The Docs page https://docs.microsoft.com/en-us/dynamics365/finance/localizations/emea-edit-invoice-id-sales-orders tells that an option exists, but pretty much nothing else. I'm interested in knowing how it works, code-wise, can it be extended etc.

**Comment by gewarren** [comment]
There's a "Feedback" section directly on that page. It would be better to log your issue that way as it will go directly into the https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public repo and contain metadata about the article.

**Comment by mrsalonen** [comment]
Thank you for the tip @gewarren, I logged the question there too.

**Comment by gewarren** [comment]
Thanks @mrsalonen. Closing in favor of https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/issues/4055.
