### ISSUE TITLE
Improve PDF file name

### ISSUE THREAD

**Issue by dend** [MicrosoftDocs/feedback#382]
**Is your feature request related to a problem? Please describe.**
Today, PDFs are created in a way that sets their name to be a very generic one.

**Describe the solution you'd like**
Use a name that follows the content it's presented for.

**Describe alternatives you've considered**
_N/A_

**Additional context**
Submitted based on [feedback on Twitter](https://twitter.com/eHougaard/status/998287790314942464).

**Comment by dend** [comment]
#log-suggestion @dastaffo

**Comment by botcrane** [comment]
🚀 **ATTENTION**: [Internal request](https://ceapex.visualstudio.com/web/wi.aspx?pcguid=7d644393-99ad-41c8-ac53-7fa79294c720&id=21461) logged.

**Comment by hougaard** [comment]
Great idea :)
