### ISSUE TITLE
You appear to have dropped some special characters

### ISSUE THREAD

**Issue by 9072997** [MicrosoftDocs/feedback#3824]
**Describe the bug**
Some special characters are not displayed inside the linked note

**To Reproduce**
1. Go to https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-r2-and-2012/hh945104(v=ws.11)
2. Search for "You must type the name exactly as it appears in the Subject field"
3. Notice that the same note text appears 3 times. It is displayed correctly once, and incorrectly twice.

**Expected behavior**
`*` is displayed in all notes

**Screenshots**
Good:
![image](https://user-images.githubusercontent.com/1310772/178124942-578cf26d-e725-43d6-9d68-be053cd40131.png)

Bad:
![image](https://user-images.githubusercontent.com/1310772/178124959-64d3d6ee-0043-424c-a9e0-1cde96cb7f15.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 102

**Additional context**
To further add to the confusion the example given `nps*.example.com` is not a regular expression (well, technically it is, but it matches things like `npnexample.com` and `npsssssxexamplexcom` not `nps1.example.com`. Proof [here](https://regexr.com/6pe1r).). It is a glob pattern. The dialogue itself contains an example that uses real regular expressions, so it is very unclear weather I should use glob patterns or real regular expressions.
![image](https://user-images.githubusercontent.com/1310772/178125027-cfce8f1d-9dff-4cdb-95ec-10a23c63a106.png)

**Comment by samyun** [comment]
Thanks for the report. That link is an outdated one that is archived. I have updated the links in the current documentation to point to the updated documentation (https://learn.microsoft.com/en-us/windows-server/networking/technologies/extensible-authentication-protocol/network-access) that we're still working on updating. 

As that your point on the confusing regex - thanks! You're correct, it should be regex, not glob patterns. I will get that updated too.
