### ISSUE TITLE
Doc pages should link to the relevant page for referenced types

### ISSUE THREAD

**Issue by baldurk** [MicrosoftDocs/feedback#3825]
**Is your feature request related to a problem? Please describe.**
Many function parameters or struct members do not link to their types in the parameter/member description.

**Describe the solution you'd like**
Ideally all cases where a parameter or member is mentioned there should be a link to its type (if there is a page for that type, basic types not counted).

**Describe alternatives you've considered**
You can copy-paste the type from the text and input it into the search bar, which works but is quite a clumsy way to navigate especially for when you are following a chain of references.

**Additional context**
Examples (non-exhaustive) include [ID3D12GraphicsCommandList4::EmitRaytracingAccelerationStructurePostbuildInfo](https://docs.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12graphicscommandlist4-emitraytracingaccelerationstructurepostbuildinfo) which doesn't link to the type of `pDesc` and [D3D12_RAYTRACING_ACCELERATION_STRUCTURE_POSTBUILD_INFO_DESC](https://docs.microsoft.com/en-us/windows/win32/api/d3d12/ns-d3d12-d3d12_raytracing_acceleration_structure_postbuild_info_desc) which doesn't link to the type of `InfoType`.

**Comment by stevewhims** [comment]
Thanks, @baldurk. I made the changes you mentioned. The more general updates will take longer.
