### ISSUE TITLE
ResourceBarrier doesn't mention restrictions on RTAS state

### ISSUE THREAD

**Issue by baldurk** [MicrosoftDocs/feedback#3826]
**Is your feature request related to a problem? Please describe.**
[ID3D12GraphicsCommandList::ResourceBarrier](https://docs.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12graphicscommandlist-resourcebarrier) doesn't mention any restriction on using D3D12_RESOURCE_STATE_RAYTRACING_ACCELERATION_STRUCTURE when listing what makes a barrier valid. There is an important restriction mentioned [in the spec](https://microsoft.github.io/DirectX-Specs/d3d/Raytracing.html#acceleration-structure-memory-restrictions) which is that resources to be used for ASs must be created in this state and cannot ever be transitioned out of it (nor resources created without this state transitioned into it).

For redundancy it would probably be a good idea to mention this on the [D3D12_RESOURCE_STATES](https://docs.microsoft.com/en-us/windows/win32/api/d3d12/ne-d3d12-d3d12_resource_states) page as well.

**Describe the solution you'd like**
I would like to have this restriction mentioned and explained on the docs page.

**Describe alternatives you've considered**
I did find this information by consulting the spec as well, but I think the docs should be complete in themselves too.

**Comment by stevewhims** [comment]
Thanks, @baldurk. I've published those changes.

-Steve
