### ISSUE TITLE
API Doc Hyperlink Issue

### ISSUE THREAD

**Issue by JessieWang76** [MicrosoftDocs/feedback#3831]
**Describe the bug**
The hyperlink under the remark leads to an empty page. 
**To Reproduce**
1. Go to 'https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.relationalqueryableextensions.fromsqlraw?view=efcore-6.0'
2. Scroll down to 'Remark'
3. Click on [Executing raw SQL commands with EF Core](https://aka.ms/efcore-docs-efcore-docs-raw-sql)
4. an empty page

**Expected behavior**

Potentially a page with some content

**Comment by JessieWang76** [comment]
same thing for https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.relationalqueryableextensions.fromsqlinterpolated?view=efcore-6.0
this page, the remark hyperlink doesn't work

**Comment by gewarren** [comment]
Thanks @JessieWang76. I'm going to close this since it seems to be working now. If you disagree, please let us know!
