### ISSUE TITLE
How can I find System.Windows.Documents.dll ?

### ISSUE THREAD

**Issue by jesus10005** [MicrosoftDocs/feedback#384]
# Idea Title

How can I find System.Windows.Documents.dll ??

## Issue Details

I have installed Framework 4.7.2. but I cannot find the reference System.Windows.Documents in reference Manager.

**Comment by jesus10005** [comment]
I have installed Framework 4.7.2. but I cannot find the reference System.Windows.Documents in reference Manager.

**Comment by Powerhelmsman** [comment]
@jesus10005 Can you try this page: https://docs.microsoft.com/en-us/dotnet/api/system.windows.documents?view=netframework-4.7.2
