### ISSUE TITLE
Stray space in section title leads to unexpected section links

### ISSUE THREAD

**Issue by ChrisMaddock** [MicrosoftDocs/feedback#385]
**Describe the bug**
On the API pages - the Enum fields section title has a stray space at the end. This was only noticed as it meant links to `#fields` do not work - the link must instead go to `#fields-`.

This is of course very minor - but hopefully a simple fix as well!

**To Reproduce**
1. Go to https://docs.microsoft.com/en-us/dotnet/api/system.genericuriparseroptions?view=netframework-4.7.2
2. Click on the "link button" besides the "Fields" title

**Expected behavior**
Created link should be https://docs.microsoft.com/en-us/dotnet/api/system.genericuriparseroptions?view=netframework-4.7.2#fields

**Actual behavior**
Created link is https://docs.microsoft.com/en-us/dotnet/api/system.genericuriparseroptions?view=netframework-4.7.2#fields-

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version:  66.0.3359.181 (Official Build) (64-bit)

**Comment by Powerhelmsman** [comment]
@ChrisMaddock Your issue is transferred to .Net team issue queue.

**Comment by mairaw** [comment]
Please reopen this here @Powerhelmsman. Those sections are auto-generated and I cannot control that from the content side. /cc @adkinn @dend

**Comment by adkinn** [comment]
@mairaw thanks for passing this along. We've created an internal work item to fix it.

**Comment by mairaw** [comment]
It seems this was fixed already. Can you confirm @adkinn?

**Comment by adkinn** [comment]
@mairaw yes, we fixed this! Apologies for not bubbling back up to this issue.

**Comment by mairaw** [comment]
I don't have write permissions, so somebody other than me has to close this. 😄

**Comment by Powerhelmsman** [comment]
@ChrisMaddock Close as it is resolved.

**Comment by ChrisMaddock** [comment]
Thanks! 😃
