### ISSUE TITLE
Why did the report on github button disappear?

### ISSUE THREAD

**Issue by Rand-Random** [MicrosoftDocs/feedback#3856]
I am not sure how the button was actually called, but on all (maybe) msdn pages (now learn.microsoft.com) there used to be a button where you could directly report the msdn page, it seems to be gone.

Is there a reason behind this, or is there a bug?

The page I want to give feedback is this:
https://learn.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.dllimportattribute?view=net-6.0

With this button I was able to create those issues
https://github.com/dotnet/docs/issues/21674
https://github.com/MicrosoftDocs/windowsserverdocs/issues/6231
https://github.com/MicrosoftDocs/windows-dev-docs/issues/2740

I hope by sharing those issue it gets clearer about which button I am talking about.

**Comment by gewarren** [comment]
@Rand-Random The feedback button is still present on some/most articles. We did disable it a couple years ago for the .NET API reference as there were simply too many incoming issues for us to even respond to. That said, you can log an issue for the DllImportAttribute Class directly at https://github.com/dotnet/dotnet-api-docs/issues.

**Comment by Rand-Random** [comment]
Okay, thanks.
