### ISSUE TITLE
Use an unambiguous date format 

### ISSUE THREAD

**Issue by SimonCropp** [MicrosoftDocs/feedback#386]
You currently use mm/dd/yyyy

![image](https://user-images.githubusercontent.com/122666/40340334-c7a5552a-5dc1-11e8-9db1-0daf6581140d.png)

while this make sense in the US, for the vast majority of the world it is wrong 

![image](https://user-images.githubusercontent.com/122666/40340489-7ae079d0-5dc2-11e8-8924-b3a2141eb7bc.png)

source: https://en.wikipedia.org/wiki/Date_format_by_country

I would like to suggest moving to yyyy/mm/dd or yyyy mmm dd. since both are unambiguous irrespective of country

I know some people will suggest region detection and localisation. I would prefer this option was not taken. the reason being people regularly move between multiple different devices, multiple different server in diff locals, and multiple diff MS sites/pages. localisation will not consistently solve the problem.

**Comment by botcrane** [comment]
Failed to submit internal item.

**Comment by dend** [comment]
#log-request @ShevaDas

**Comment by dend** [comment]
#log-suggestion @ShevaDas

**Comment by botcrane** [comment]
Failed to submit internal item.

**Comment by dend** [comment]
#log-suggestion @ShevaDas

**Comment by botcrane** [comment]
Failed to submit internal item.

**Comment by dend** [comment]
#log-suggestion @ShevaDas

**Comment by botcrane** [comment]
Failed to submit internal item.

**Comment by dend** [comment]
#log-suggestion @ShevaDas

**Comment by botcrane** [comment]
🚀 **ATTENTION**: [Internal request](https://ceapex.visualstudio.com/web/wi.aspx?pcguid=7d644393-99ad-41c8-ac53-7fa79294c720&id=22011) logged.

**Comment by ShevaDas** [comment]
@SimonCropp thanks for the feedback! I'll discuss it with the team and get back to you.

**Comment by SimonCropp** [comment]
@ShevaDas thanks

**Comment by AlanMcBee** [comment]
I feel like this is well-known, but as I don't see it in the comments: ISO 8601 solved this problem a long time ago. YYYY-MM-DD format all around the world.

**Comment by ShevaDas** [comment]
Just to clarify, Docs currently changes the date format based on the user locale (see images). I'm investigating if we can use ISO 8601 for clarity, but our current solution does take different date formats used around the world into account.

![tr-tr-turkey](https://user-images.githubusercontent.com/3937986/43114803-c162658e-8ece-11e8-96a0-a7bbcbe9b5c9.PNG)

![ja-jp](https://user-images.githubusercontent.com/3937986/43114800-bd074d06-8ece-11e8-902f-9f74b4738459.PNG)

**Comment by SimonCropp** [comment]
> Just to clarify, Docs currently changes the date format based on the user locale (see images). I'm investigating if we can use ISO 8601 for clarity, but our current solution does take different date formats used around the world into account.

that may be the case. unfortunately that is not consistent over all websites, let alone all MS websites. so whenever someone see a 1/12/yyyy there is no way they can tell if this is one of the sites that localises dates.

**Comment by AlanMcBee** [comment]
I agree with @SimonCropp. 
It would be fine to have localized dates for non-technical content (commercial, media, educational, etc.) But in the technical world, where nearly everybody should used to having solutions to disambiguate data (like a date format), it seems like a real step backward to purposely introduce a known ambiguity in the format just to suit an aesthetic.
At the very least, please provide an alternate title that either displays the date in a localized and unambiguous full-form (like "Monday, September 21, 2018"), else put the ISO 8601 version as the alternate title.

**Comment by svick** [comment]
@ShevaDas 

> Just to clarify, Docs currently changes the date format based on the user locale (see images).

As far as I can tell, it does not. It changes based on the language which I selected, not based on the locale configured on my computer.

And considering that en-US always contains the best content, many users (including me), prefer to use the en-US version of docs, even though they're not used to the US date format.

**Comment by AlanMcBee** [comment]
Wondering why you closed it? I still thought it was a good idea.

**Comment by SimonCropp** [comment]
Figured if it hadn’t been actioned in 9 months, then it prob never would be
