### ISSUE TITLE
Big Bitch

### ISSUE THREAD

**Issue by sugarbush1111** [MicrosoftDocs/feedback#3867]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by clandrew** [comment]
I'm closing this because the repro steps don't describe something actionable.

**Comment by sugarbush1111** [comment]
Someone is sharing my operating system emails cellphone number they are attached to all my devices tv's cars phone laptops tablets spyware projecting recording listening devices software Xbox gaming in my home and cars they even took a class on GitHub under my account through yahoo a while back. I have about 85 emails because everyone says to make a new one to recover the other, where it makes no sense if they changed the information in it. There has to be a point of recovery. Day Date one can’t be changed deleted foot print I need to find a team 
I have 000 privacy for the pat 3 1/2 years 24/7 going to identify theft
Im ready to create something they will never for get. 
I need a team that thinks in out under onto checking all triangle circle square possibilities are endless open minded 
Any ideas thoughts 
Im truly open

**Comment by clandrew** [comment]
Hello, thank you for the update and it sounds like you are working through some data privacy concerns. I am keeping the status of this bug as-is since I am still not seeing the repro steps as reflecting something our documentation team can take action on.
