### ISSUE TITLE
D3D_SHADER_MODEL enumeration page misstates SM 6.7 support

### ISSUE THREAD

**Issue by clandrew** [MicrosoftDocs/feedback#3869]
**Describe the bug**
The text on the page says
Shader model 6.7 support was added in Windows 11, Version 22H2 and the DirectX 12 Agility SDK v1.6. 

It shouldn't say that shader model is available in 22H2, since that isn't true and isn't in the linked blog post either.

**To Reproduce**
1. Go to [D3D_SHADER_MODEL](https://learn.microsoft.com/en-us/windows/win32/api/d3d12/ne-d3d12-d3d_shader_model)
2. Scroll down to D3D_SHADER_MODEL_6_7
4. See incorrect text

**Expected behavior**
Text should not refer to 22H2.

**Comment by stevewhims** [comment]
Thanks, @clandrew. The description now says "Shader model 6.7 support was added in the DirectX 12 Agility SDK v1.6. See [Agility SDK 1.606.3: Shader Model 6.7 is now publicly available!](https://devblogs.microsoft.com/directx/shader-model-6-7/) on the DirectX developer blog."

I'll be happy to make further changes if you shoot me an email.

-Steve
