### ISSUE TITLE
Searching in PowerShell Module Browser

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/feedback#387]
**Is your feature request related to a problem? Please describe.**

When I search in the PowerShell Module Browser it is hard to find modules unless you already know their name.\
**Describe the solution you'd like**

If i search the Powershell Module browser for AD or Active, i should be shown the Azure AD modules. currently, we have to search for AzureAD. 

**Describe alternatives you've considered**
Using Bing to Google the site.

**Additional context**

**Comment by Powerhelmsman** [comment]
#log-suggestion @presleyy

**Comment by botcrane** [comment]
🚀 **ATTENTION**: [Internal request](https://ceapex.visualstudio.com/web/wi.aspx?pcguid=7d644393-99ad-41c8-ac53-7fa79294c720&id=22065) logged.

**Comment by presleyy** [comment]
I believe the request is talking about the [PowerShell API Browser](https://docs.microsoft.com/en-us/powershell/module/). Is only the module name indexed? @dend

**Comment by EdisonDa** [comment]
@DeanGross Thank you for your reporting and waiting for so long time. This module browser is different from search function - if you have no context about the module or cmdlets, we suggest you to try "search" function. In current module browser, you can try "active" in your example, however, the 'ad" could not return your expected result.
