### ISSUE TITLE
Download .NET API documentation for offline purposes

### ISSUE THREAD

**Issue by RukkaPlus** [MicrosoftDocs/feedback#3876]
**Is your feature request related to a problem? Please describe.**
I want to download the _.NET API documentation_ for offline cases, like other languages such as [Java](https://www.oracle.com/java/technologies/javase-jdk17-doc-downloads.html). Because, some people needs this information in a offline context, and can be more productive without need to install _Visual Studio_ entire IDE (plus, this IDE is Windows only, lol)

**Describe the solution you'd like**
I find the C# offline pdf documentation; I think this can be a solution. Also, the example of [Java](https://www.oracle.com/java/technologies/javase-jdk17-doc-downloads.html) will be better

**Describe alternatives you've considered**
For now, we have [devdocs.io](https://devdocs.io) and [Zeal](https://zealdocs.org)

> Edit: _devdocs.io_ don't have _.NET API Documentation_ available. And _Zeal .NET API Documentation_ is broken in various aspects

**Additional context**
Please, add the "Download PDF" option in _.NET API Documentation_, or a autogenerated `.zip` with the docs in `.md` or in `.html` format

**Comment by gewarren** [comment]
cc @kexugit

**Comment by kexugit** [comment]
PDF download is currently only enabled for conceptual content on Learn. Support for reference content, including .NET APIs, is currently planned for the current quarter.
