### ISSUE TITLE
Exhange Module not available

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/feedback#388]
**Describe the bug**
The PowerShell Module browser list Exchange, but does not have any content

**To Reproduce**
1. Go to 'https://docs.microsoft.com/en-us/powershell/module/
2. Click on Exchange
3. Choose latest version
4. no results are returned

**Expected behavior**
I expect to see the modules for Exchange

**Screenshots**
![image](https://user-images.githubusercontent.com/4058555/40380009-cf90da9e-5dc5-11e8-9df4-0a77051bb799.png)

**Desktop (please complete the following information):**
 - Browser [Edge]

**Comment by Powerhelmsman** [comment]
@dend Can you take a look at this issue?

**Comment by dend** [comment]
We are investigating this, thank you for the report, @DeanGross!

**Comment by keziamicro** [comment]
Hello - reviewing and cleaning up some older feedback/issues. Thanks!
