### ISSUE TITLE
Correction under Files created and updated heading "The scaffold process adds the following highlighted code to the Startup.cs file"  under 

### ISSUE THREAD

**Issue by abhiroy4** [MicrosoftDocs/feedback#3892]
**Describe** the bug**
Correction of file name as Startup.cs under Part 2, add a model to a Razor Pages app in ASP.NET Core section => "Files created and updated" heading wherever Program.cs filename is mentioned. Below is the correction;

- The scaffold process adds the following highlighted code to the **Startup**.cs file:

- The **Startup**.cs changes are explained later in this tutorial.

**Comment by gewarren** [comment]
This looks to be about https://learn.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-7.0&tabs=visual-studio.

**Comment by gewarren** [comment]
This issue was moved to dotnet/AspNetCore.Docs#28357
