### ISSUE TITLE
Grammar mistake at 'keywords/volatile' docs

### ISSUE THREAD

**Issue by MrYotic** [MicrosoftDocs/feedback#3895]
**Describe the bug**
*https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/volatile?source=docs*
There is a grammatical error in the Russian version of the documentation, a letter is missing.
English version: "There is no guarantee of a single total ordering of volatile writes as seen from all threads of execution"
English version: "Нет никакой гарантии единого общего **прядка** временных записей во всех потоках выполнения"
Mistake at "прядка", correctly "порядка".
There is no word "прядка", but has word "порядка (declination from порядок)" - order, when the original word is "ordering", it turns out everything converges

**To Reproduce**
1. Go to 'https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/volatile?source=docs'
2. Change language on 'Russian'
4. See error at first paragraph

**Screenshots**
![image](https://user-images.githubusercontent.com/55879406/216476907-106e7355-b20a-483d-8c81-7b4bc87ab8c3.png)

**Desktop:**
 - OS: Windows 22H2
 - Browser: Chrome 109.0.5414.120
 - Version: 22

**Comment by gewarren** [comment]
This issue was moved to dotnet/docs#33976
