### ISSUE TITLE
more images to explain the process on each step

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#39]
not able to understand exact meaning of doc

----------
⚠ Idea migrated from UserVoice

**Created By:** shoeb ahmed
**Created On:** 2018/01/18 11:47:02 +0000
**Votes at Migration:** 1
**Supporters at Migration:** 1

**Comment by dend** [comment]
Please leave the feedback directly under the document where you need images - that way the content author is able to address it quicker.
