### ISSUE TITLE
Learning Paths

### ISSUE THREAD

**Issue by rvwilliams88** [MicrosoftDocs/feedback#3902]
'Browse all learning paths and modules' doesn't display any useful data when used with Microsoft Edge Version 110.0.1587.63 (Official build) (64-bit).  It does display Products etc. when used with Mozilla Firefox.  I would prefer to use Edge but cannot for this page.
To reproduce, go to https://learn.microsoft.com.  Click the link for Training and then select Learning Paths.  The only information on the screen is
![image](https://user-images.githubusercontent.com/112261322/223446368-67d77981-0b20-4026-bd97-78770216cc51.png)

**Comment by gewarren** [comment]
It's working for me on Edge. Can you still reproduce the issue?
