### ISSUE TITLE
False positive broken link

### ISSUE THREAD

**Issue by AlexJerabek** [MicrosoftDocs/feedback#3906]
Build report: https://buildapi.docs.microsoft.com/Output/Commit/918d1c35-f3a4-631b-1edf-a1a2af22eee5/202303142151582236-AlexJ-Connectivity/BuildReport?accessString=9f97c7117825ef87ad720aa07b2fea3970f8968804b749034b5f27a6382c5289

The report is claiming the link, https://www.linkedin.com/in/lesblackconsultant/, points to a page that doesn't exist. That page does exist.

**Comment by herohua** [comment]
Opened internal work item https://dev.azure.com/ceapex/Engineering/_workitems/edit/807162 for investigation.
