### ISSUE TITLE
Power BI Guided Learning Download PDF not working

### ISSUE THREAD

**Issue by aHorton22** [MicrosoftDocs/feedback#391]
**Describe the bug**
The download PDF from the Power BI Guided Learning section of the website only includes a table of contents and when clicking the links in the TOC it attempts to take me to a file location outside my network. 

**To Reproduce**
1. Go to 'https://docs.microsoft.com/en-us/power-bi/guided-learning/'
2. Click on 'Download a PDF'

**Expected behavior**
I expected a PDF file with more than one page including the Guided Learning for Power BI, similar to the Download a PDF link on the SQL Management Server page at the following link.
https://docs.microsoft.com/en-us/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-2017

**Desktop (please complete the following information):**
 - OS: [Win10]
 - Browser [Edge]

**Comment by Powerhelmsman** [comment]
@guyinacube @mgblythe Can you guys take a look at this?

**Comment by dastaffo** [comment]
@adkinn Can you help figure out why this is only the ToC?

**Comment by Powerhelmsman** [comment]
@adkinn I create a bug on sitehelp: https://icm.ad.msft.net/imp/v3/incidents/details/74003033/home. I will monitor the status and inform user when it is resolved.

**Comment by maggiesMSFT** [comment]
@mgblythe -- How is a person supposed to print PDFs of Guided Learning?

**Comment by adkinn** [comment]
@maggiesMSFT @Powerhelmsman @mgblythe @dastaffo The problem is the content is using the Tutorial page type, which is not currently supported for PDFs.

**Comment by Powerhelmsman** [comment]
@maggiesMSFT @mgblythe @dastaffo @adkinn May I suggest to remove the PDF download from this page to avoid confusion.

**Comment by maggiesMSFT** [comment]
@adkinn -- Do you mean "ms.topic = tutorial"? or is "Tutorial page type" something else? 
@Powerhelmsman @dastaffo @mgblythe
I ask because we have other articles with "ms.topic = tutorial", and they support PDFs.

**Comment by adkinn** [comment]
@maggiesMSFT I mean the page type, defined like this: https://github.com/MicrosoftDocs/powerbi-docs-pr/blob/4dd0c6bfa86fdda531ebcd80c91e7f4e83297ba8/powerbi-docs/guided-learning/gettingstarted.yml#L1

**Comment by maggiesMSFT** [comment]
@adkinn -- Got it. 
I assume the Download to PDF is in a footer, not in the YML file itself? 
Including @davidiseminger and @mgblythe, who know more about the Guided Learning than I do.
@Powerhelmsman @dastaffo

**Comment by mgblythe** [comment]
@adkinn -- We need to keep the page type b/c it's set up as an interactive tutorial. It seems that if interactive tutorials don't support PDF rendering then the site shouldn't include that option.

**Comment by keziamicro** [comment]
Hello - reviewing and cleaning up some older feedback/issues. Thanks!
