### ISSUE TITLE
The PDF Downloaded is still in English when access from zh-cn

### ISSUE THREAD

**Issue by casperlw** [MicrosoftDocs/feedback#392]
e.g. https://docs.microsoft.com/zh-cn/azure/virtual-network/

click the Download PDF, the pdf downloaded is still in English, do we have a plan to support Chinese content for the downloaded PDF? Thanks

**Comment by Powerhelmsman** [comment]
@SonjaSaltzman Can you take a look at this request?

**Comment by Powerhelmsman** [comment]
@casperlw The PDF download button is disabled. Thanks for you feedback.
