### ISSUE TITLE
Missing the using System

### ISSUE THREAD

**Issue by Tuturado** [MicrosoftDocs/feedback#3929]
**Describe the bug**
In the Objects - create instances of types part, when I clicked to run the first available code snippet, it gives an error, because the using System.

**To Reproduce**
1. Go to https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/object-oriented/objects#code-try-0'
2. Click to execute the first or second section
3. The output will indicate the error

**Expected behavior**
I hoped that I didn't need to add anything for the code to work correctly, considering that I'm still a beginner in the language.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Google Chrome
 - Version 114.0.5735.134

**Comment by gewarren** [comment]
This issue was moved to dotnet/docs#35940

**Comment by Tuturado** [comment]
@gewarren I know, but the point is that it shouldn't miss by default, someone more beginner than me might give up using the site for reasons like this.
