### ISSUE TITLE
Has MTPS been discontinued?

### ISSUE THREAD

**Issue by SoronelHaetir** [MicrosoftDocs/feedback#393]
I have used MTPS for a long while now for feeding MSDN content to a custom help viewer application (I am blind and I don't care for either the distributed viewer or the web interface, both are simply too busy for my tastes), 

recently when I try a request to https://services.msdn.microsoft.com/ContentServices/ContentService.asmx I have been getting an "Unable to connect" error so I have to wonder has MTPS been discontinued? And if it has is there any plan to make the content that was available through MTPS available through docs.microsoft.com (particularly the windows API docs, which right now on docs.microsoft.com points to MSDN).

**Comment by Powerhelmsman** [comment]
@SoronelHaetir  Thanks for your feedback. I will bring your question to team to confirm if we have any plan to make content available.

**Comment by Powerhelmsman** [comment]
#log-suggestion

**Comment by botcrane** [comment]
🚀 **ATTENTION**: [Internal request](https://ceapex.visualstudio.com/web/wi.aspx?pcguid=7d644393-99ad-41c8-ac53-7fa79294c720&id=22695) logged.

**Comment by SoronelHaetir** [comment]
An update, I have since found that using http instead of https still works.

**Comment by Khairunj** [comment]
@SoronelHaetir Hi there, we are in the process of moving content from MTPS to docs.microsoft.com site for latest versions but for older version of the content please search on https://docs.microsoft.com/en-us/search/index?search=Windows+API&dataSource=previousVersions and you should be able to find what you are looking for and we also we have a capability to turn on Download PDF if that's better for you for any site section you are interested. Please let us know.  Thank you for the feedback.

**Comment by Powerhelmsman** [comment]
@SoronelHaetir May I close the issue now.

**Comment by SoronelHaetir** [comment]
You may.

Not what I wanted to hear but it is what it is.
