### ISSUE TITLE
.NET Editor will stack when use dynamic type variable and Console.WriteLine

### ISSUE THREAD

**Issue by 1234567Yang** [MicrosoftDocs/feedback#3932]
**Describe the bug**
.NET Editor will stack when use dynamic type variable and Console.WriteLine.
Example:
dynamic a = "1";
Console.WriteLine(a);

**To Reproduce**
1. Go to 'https://learn.microsoft.com/en-us/dotnet/csharp/how-to/parse-strings-using-split#code-try-0'
2. Open .NET Editor
3. Use both dynamic keyword and Console.WriteLine();
4. Click 'run'
5. See error

**Expected behavior**
The output will stack and continue loading.

**Screenshots**
![image](https://github.com/MicrosoftDocs/feedback/assets/113082249/a762511a-ee53-4eb6-a970-4d32022d2fcb)

**Desktop (please complete the following information):**
 - OS: Chromebook(Google Chrome OS Version 114.0.5735.119 (Official Build) (64-bit))
 - Browser: Chrome
 - Version 114.0.5735.119 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
Not tested

**Additional context**
No.

**Comment by gewarren** [comment]
This seems to be an issue with Try.NET. @BillWagner any thoughts how to route this issue?

**Comment by jonsequitur** [comment]
dotnet/interactive is the appropriate repo. 

I'm guessing that `dynamic` doesn't work generally in the version of the Blazor WASM engine we're using. This may have been resolved in more recent versions of .NET's WASM support. If not, then dotnet/interactive will also not be the appropriate repo, but we can move it there and look into it.

**Comment by gewarren** [comment]
This issue was moved to dotnet/interactive#3134
