### ISSUE TITLE
Failure to clone the repository `https://github.com/azure/azureml-examples#vijetajo-patch-2` 

### ISSUE THREAD

**Issue by akashraokm** [MicrosoftDocs/feedback#3934]
Facing an issue in validation with the following error for the [PR#242345](https://github.com/MicrosoftDocs/azure-docs-pr/pull/242345)
Failure to clone the repository `https://github.com/azure/azureml-examples#vijetajo-patch-2` 

I did not  face this error during the itinial merges, I think this might be a build issue.
We are planning to annonuce this feature by tomorrow so this is a little time sensitive.

Thanks in advance!

**Comment by gewarren** [comment]
Looks like the PR was merged and the error resolved, so I'm going to close this.
