### ISSUE TITLE
[error message feedback] build report error unhelpful

### ISSUE THREAD

**Issue by danmoseley** [MicrosoftDocs/feedback#3935]
[report url](https://buildapi.docs.microsoft.com/Output/PullRequest/fdbc5ac2-aabf-05a3-19a6-1c598e35d7ce/202306221552228489-111282/BuildReport?accessString=c254581bd15eb5e18dd5f946a9d80e4d380fb90e861a4140dfcce526376162cf)

this report just says "Failure to clone the repository `https://github.com/azure/azureml-examples#vijetajo-patch-2` because" which could be more helpful

![image](https://github.com/MicrosoftDocs/feedback/assets/6385855/2a2bfb57-79ba-4e05-a19c-559b80b86b4a)

**Comment by gewarren** [comment]
<img width="580" alt="image" src="https://github.com/MicrosoftDocs/feedback/assets/24882762/85367b8f-4575-4e43-9d8e-67a6479bef2a">

According to this, the error message has been fixed, so I'll close this issue. Thanks for opening it!
