### ISSUE TITLE
Little misbeahvior in code example for SpinWait

### ISSUE THREAD

**Issue by pomatuchto** [MicrosoftDocs/feedback#3946]
Code example for SpinWait: https://learn.microsoft.com/en-us/dotnet/standard/threading/how-to-use-spinwait-to-implement-a-two-phase-wait-operation#example

In the method Latch.Wait(int timeout) Stopwatch uses to measure amount of time elapsed during the first phase of wait operation. Then in the second phase  timeout passed to this method decreases by this measured timelapse. 

The problem: stopwatch is reinitialized every iteration of outer while cycle. Thus by the start of second phase we  didn't  actually measured elapsed time at all.

**Comment by gewarren** [comment]
This issue was moved to dotnet/docs#36678
