### ISSUE TITLE
ILoggingBuilder.AddConsole 's FormatterOptions.IncludeScopes false does not work

### ISSUE THREAD

**Issue by SudipShresthaCiena** [MicrosoftDocs/feedback#3951]
**To Reproduce**
1. In a .net core 7.0 Console App, I added console logging.
2. appsettings.json file
`
{
"Logging": {
    "LogLevel": {
      "Default": "Information"
    },
    "Console": {
      "LogLevel": {
        "Default": "Information"
      },
      "FormatterName": "consoleLogFormatter",
      "FormatterOptions": {
               "SingleLine": true,
                "IncludeScopes": false,
                "TimestampFormat": "HH:mm:ss ",
                "UseUtcTimestamp": true
      }
    }
}
`
3. Program.cs
`
using var loggerFactory = LoggerFactory.Create(loggingBuilder =>
{
    loggingBuilder.AddConfiguration(Configuration.GetSection("Logging"));
    loggingBuilder.AddConsole();
    
}
`
4. In the console, this is what I see:
`20:08:29 info: AppName.Class1Name[0] Some Message Here 1
20:08:33 info: AppName.Class2Name[0] Some Message Here 2
20:08:33 info: Program[0] Some Message Here 3

**Expected behavior**
I was expecting not to see "AppName.Class1Name[0]" etc.
I know the section is being read because UseUtcTimestamp, TimestampFormat, and SingleLine are working.

**Desktop:**
 - OS: Windows 10
 - Browser NA

**Additional context**

**Comment by gewarren** [comment]
This issue was moved to dotnet/docs#37026
