### ISSUE TITLE
API docs missing for GetResourceAllocationInfo and some Vb features

### ISSUE THREAD

**Issue by clandrew** [MicrosoftDocs/feedback#3953]
I'm seeing we have some missing docpages for
* ID3D12Device::GetResourceAllocationInfo and GetResourceAllocationInfo1

And these Vb features:
* ID3D12GraphicsCommandList6
* DispatchMesh
* CreateSamplerFeedbackUnorderedAccessView

**Comment by stevewhims** [comment]
Let's close this, and track it via the email thread. :)
