### ISSUE TITLE
Share code for your GitHub app integration for utteranc.es

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/feedback#396]
**Is your feature request related to a problem? Please describe.**
I believe you're running a version of https://github.com/utterance/utterances for your comments, but using a custom GitHub bot/app for the integration.
It would be nice to share the code used for that GitHub App because your additional metadata and linking used in your version adds a bunch of value beyond the basic bot. Also makes it easier for a user to trust a specific bot for an organization rather than a general bot.

**Describe the solution you'd like**
The code used to create https://github.com/apps/docs-microsoft-com is shared

**Describe alternatives you've considered**
Maybe it is open somewhere or has some hidden sauce that can't be shared.

**Comment by EdisonDa** [comment]
#log-suggestions @Powerhelmsman

**Comment by dend** [comment]
@nschonni @jdanyow closing this particular issue as it is external and will be addressed in the `utterance.es` repo.

**Comment by nschonni** [comment]
Can I update the description and title a bit to get this reopened? I was looking for the comment system setup code, which I thought was based on utteranc.es :stuck_out_tongue_winking_eye:

**Comment by jdanyow** [comment]
@nschonni there's no docs secret sauce- the docs code and the utterances code are very similar.  The main difference I described above (multiple issues per page vs single issue per page).  Neither docs nor utterance have a server-side component other than the [oauth related code](https://github.com/utterance/utterances-oauth) which have similar implementations.

**Comment by luzlab** [comment]
Any update on releasing the documentation issue tracking used on the Microsoft Docs sites? I'd like to the same for our documentation.
