### ISSUE TITLE
Azure confidential ledger API documentation hyperlinks return 404

### ISSUE THREAD

**Issue by jboyda** [MicrosoftDocs/feedback#3969]
**Describe the bug**
The Azure confidential ledger API documentation hyperlinks are now broken and return 404 errors. 

**To Reproduce**
1. Go to 'https://learn.microsoft.com/en-us/rest/api/confidentialledger/'
2. Click on 'Create Ledger Entry' or any other documentation hyperlink
3. See error

**Expected behavior**
Hyperlinks used to direct to page with information about request and response payload JSON structure for given topic.

**Desktop (please complete the following information):**
 - OS: Mac OSx 14.1
 - Browser: Firefox
 - Version 119.0.1

**Additional context**
Hyperlinks worked properly in September but now no longer work.

<img width="2557" alt="Screenshot 2023-11-29 at 10 32 33 AM" src="https://github.com/MicrosoftDocs/feedback/assets/22417604/fac3e3aa-6e9c-4e11-a170-90baa0495ccb">

**Comment by gewarren** [comment]
cc @msmbaldwin

**Comment by gewarren** [comment]
Thanks for reporting! It looks like this has been fixed by @PallabPaul. Let us know if you are still seeing broken links.
