### ISSUE TITLE
https://dotnet.microsoft.com/ SSL certificate mismatch

### ISSUE THREAD

**Issue by DevDengChao** [MicrosoftDocs/feedback#3970]
**Describe the bug**

![image](https://github.com/MicrosoftDocs/feedback/assets/16363180/39134a48-c9df-4bcf-88ae-93c0b1f2696e)

**To Reproduce**
1. Go to https://developer.microsoft.com/zh-cn/
2. Click on 
![image](https://github.com/MicrosoftDocs/feedback/assets/16363180/553059e6-9d3c-45b5-9143-767343122610)
3. See error

**Expected behavior**

https://dotnet.microsoft.com/ should have valid SSL cert

**Additional context**

```
> dig dotnet.microsoft.com
;; communications error to 172.23.32.1#53: timed out

; <<>> DiG 9.18.12-0ubuntu0.22.04.2-Ubuntu <<>> dotnet.microsoft.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 59473
;; flags: qr rd ad; QUERY: 1, ANSWER: 6, AUTHORITY: 0, ADDITIONAL: 0
;; WARNING: recursion requested but not available

;; QUESTION SECTION:
;dotnet.microsoft.com.          IN      A

;; ANSWER SECTION:
dotnet.microsoft.com.   0       IN      CNAME   dotnetwebsite.azurefd.net.
dotnetwebsite.azurefd.net. 0    IN      CNAME   firstparty-azurefd-prod.trafficmanager.net.
firstparty-azurefd-prod.trafficmanager.net. 0 IN CNAME shed.dual-low.part-0045.t-0009.t-msedge.net.
shed.dual-low.part-0045.t-0009.t-msedge.net. 0 IN CNAME part-0045.t-0009.t-msedge.net.
part-0045.t-0009.t-msedge.net. 0 IN     A       13.107.213.73
part-0045.t-0009.t-msedge.net. 0 IN     A       13.107.246.73

;; Query time: 0 msec
;; SERVER: 172.23.32.1#53(172.23.32.1) (UDP)
;; WHEN: Wed Dec 20 10:07:38 CST 2023
;; MSG SIZE  rcvd: 424
```

**Comment by gewarren** [comment]
It seems to be working now, so I'll close this issue. Let us know if it's still an issue for you. cc @mairaw.

**Comment by DevDengChao** [comment]
![image](https://github.com/MicrosoftDocs/feedback/assets/16363180/bf95f0cf-0817-4965-9915-5adeb41baee4)

No, it still not works.

**Comment by DevDengChao** [comment]
![image](https://github.com/MicrosoftDocs/feedback/assets/16363180/308aa1e2-fcb8-419b-ae1b-5a2d3af88af7)

I can visit the website now, thanks.
