### ISSUE TITLE
Ambiguity in description of .NET regular expression source generators

### ISSUE THREAD

**Issue by SetTrend** [MicrosoftDocs/feedback#3977]
In section [Source generation](https://learn.microsoft.com/en-us/dotnet/standard/base-types/regular-expression-source-generators#source-generation), the documentation states:

> The generated implementation of `AbcOrDefGeneratedRegex()` similarly caches a singleton `Regex` instance, so no additional caching is needed to consume code.

… but right below that you're providing a screenshot that's manually caching the generated `RegEx()` result in user code:

![cached instance](https://learn.microsoft.com/en-us/dotnet/standard/base-types/media/regular-expression-source-generators/cached-instance.png)

**What's true?** — Do we need to cache the result in a `static readonly` variable or can we call `RegEx()` repeatedly without penalty to runtime execution time?

<br/>

https://learn.microsoft.com/en-us/dotnet/standard/base-types/regular-expression-source-generators#source-generation

**Comment by gewarren** [comment]
This issue was moved to dotnet/docs#39299
