### ISSUE TITLE
AutoML Experiment example fails 

### ISSUE THREAD

**Issue by Elantonio** [MicrosoftDocs/feedback#3979]
I'm following the example code on:
_https://learn.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/how-to-use-the-automl-api_

```
MyMLContext = new MLContext();
ColumnInferenceResults columnInference =
  MyMLContext.Auto().InferColumns(TrainFilePath, labelColumnName: LabelColumnName, groupColumns: false);

TextLoader loader = MyMLContext.Data.CreateTextLoader(columnInference.TextLoaderOptions);

// Load data into IDataView
IDataView data = loader.Load(TrainFilePath);

TrainTestData trainValidationData = MyMLContext.Data.TrainTestSplit(data, testFraction: 0.2);

SweepablePipeline pipeline =
  MyMLContext.Auto().Featurizer(data, columnInformation: columnInference.ColumnInformation)
      .Append(MyMLContext.Auto().Regression(labelColumnName: columnInference.ColumnInformation.LabelColumnName));

AutoMLExperiment experiment = MyMLContext.Auto().CreateExperiment();

experiment
  .SetPipeline(pipeline)
  .SetRegressionMetric(RegressionMetric.RSquared, labelColumn: columnInference.ColumnInformation.LabelColumnName)
  .SetTrainingTimeInSeconds((uint)Math.Max(seconds, 10))
  .SetDataset(trainValidationData);

TrialResult experimentResults = experiment.Run();
```
But it gives an error on experiment.Run();
Error = "_One or more errors occurred. (Could not find feature column 'Features' (Parameter 'inputSchema')_"

I can't seem to find what I'm missing here. 
Anyone an idea, and if so should the docu be updated?

**To reproduce**

-in vs2022 create a project
-Add nuget Microsoft.ML.AutoML 0.21.1
-create a class Predictor
-add an instantiator with the above code;
-Build
-Instantiate the class

**Expected behavior**
Run without error

Environment
Desktop OS: Win11 .
Visual Studio Community 2022 (64-bit) -17.6.4

**Comment by gewarren** [comment]
This issue was moved to dotnet/docs#39298
