### ISSUE TITLE
Merge Microsoft/VSProjectSystem content into MicrosoftDocs/visualstudio-docs

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/feedback#398]
**Is your feature request related to a problem? Please describe.**
The content for this currently sits in https://github.com/Microsoft/VSProjectSystem relates to extending Visual Studio so the content probably belongs with the other VS extensiblity docs.

**Describe the solution you'd like**
Move the content into the MicrosoftDocs/visualstudio-doc repo and convert to DocFx/OpenBuild

**Describe alternatives you've considered**
Maybe not targeted at the same audience as the visualstudio-docs content.

**Comment by EdisonDa** [comment]
#log-suggestions @dend

**Comment by dend** [comment]
@Jemash - looks like something your team can help address.

**Comment by kexugit** [comment]
@mcleblanc how in VS content team should take a look at this?

**Comment by mcleblanc** [comment]
It's my understanding the VS Extensibility docs are not owned or managed by the VS content team. It's the PM team that owns and manages them: @madskristensen

**Comment by keziamicro** [comment]
Hello - reviewing and cleaning up some older feedback/issues. Thanks!
