### ISSUE TITLE
C# Compiler Error CS1009 description should mention C#'s Unicode escape sequences 

### ISSUE THREAD

**Issue by RexJaeschke** [MicrosoftDocs/feedback#3980]
**Describe the bug**

The C# Compiler Error CS1009 is raised by ill-formed C# Unicode escape sequences, but the error description does not mention that possibility, which may well prohibit the reader from understanding the error message.

The help text says

> An unexpected character follows a backslash (\) in a [string](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/reference-types#the-string-type). ...

It should also mention character literals as well as strings.

Consider the following C# expressions:

```csharp
'\u0061'   // OK; well formed
'\u061'     // CS1009; a lowercase \u-style Unicode escape sequence *must* have *exactly* 4 hex digits
'\x061'      // well formed as a hexadecimal escape sequence (not a Unicode one)
'\X061'     // CS1009; a hex escape sequence *must* start with \x *not* \X
'\U0061'   // CS1009; an uppercase \U-style Unicode escape sequence *must* have *exactly* 8 hex digits
'\U00000061'      // OK; well formed
```

**Comment by RexJaeschke** [comment]
One more thing to consider:

```csharp
string s1a = "\U0010FFFF";  // OK
string s1b = "\U00110000";  // (previous value + 1)  CS1009 unrecognized escape sequence
```

While the Unicode escape sequence in the second string *is* well formed, values above U+10FFFF are not supported.

**Comment by gewarren** [comment]
@BillWagner Not sure if this issue is with the docs or the error message itself.

**Comment by BillWagner** [comment]
@gewarren 

Let's add it to the docs. The message can't cover those examples well. Are you going to move it to our repo?

**Comment by gewarren** [comment]
This issue was moved to dotnet/docs#39301
