### ISSUE TITLE
Mention `ParameterInfo.Name` is null when inspecting optimized assembly

### ISSUE THREAD

**Issue by elringus** [MicrosoftDocs/feedback#3981]
Currently, docs for `ParameterInfo.Name` mention that the value is null when accessed from a return parameter: https://learn.microsoft.com/en-us/dotnet/api/system.reflection.parameterinfo.name?view=net-8.0#remarks

I've spent quite some time debugging before stumbled upon this issue: https://github.com/dotnet/runtime/issues/73188#issuecomment-1201715264 Which explains that it's also null when inspecting an optimized assembly.

Please add a remark to the docs about this corner case.

**Comment by gewarren** [comment]
This issue was moved to dotnet/dotnet-api-docs#9579
