### ISSUE TITLE
Single method interfaces include method parameters in title

### ISSUE THREAD

**Issue by svick** [MicrosoftDocs/feedback#399]
**Describe the bug**

It seems that pages in the .Net API reference for interfaces that have a single method include the types of parameters of this method in their title.

**To Reproduce**
1. Go to [the API reference page for `IComparer`](https://docs.microsoft.com/en-us/dotnet/api/system.collections.icomparer?view=netframework-4.7.2).
2. Look at the title of the page (usually visible in the tab for the page or in the page info window), notice that it's "IComparer(Object, Object) Interface (System.Collections) | Microsoft Docs" and that it contains the types of the parameters of the interface's single method, [`Compare(Object, Object)`](https://docs.microsoft.com/en-us/dotnet/api/system.collections.icomparer.compare?view=netframework-4.7.2).

**Expected behavior**

The title is "IComparer Interface (System.Collections) | Microsoft Docs"

**Screenshots**

![](https://user-images.githubusercontent.com/287848/40623062-3873c830-62a5-11e8-8e58-0122f429d9e8.png)

![](https://user-images.githubusercontent.com/287848/40623073-4a027e52-62a5-11e8-8b60-0aa141c1df7e.png)

**Comment by EdisonDa** [comment]
@dend could you please take a look? This is related to .Net API docs.

**Comment by dend** [comment]
#log-suggestion @dend

Yup, that needs to be addressed. Opening an internal ticket to track the work.

**Comment by dend** [comment]
Looking closely at this, I am trying to understand what is the underlying reason for which we should remove the existing parameter markup. As is, it matches the title of the page, and is therefore consistent with the rest of pages on [docs.microsoft.com](https://docs.microsoft.com). @svick - can you please elaborate?

@mairaw @BillWagner - any thoughts on the feedback above?

**Comment by mairaw** [comment]
@dend it doesn't make any sense to show the parameters on the title for the interface page. This page is not consistent with the rest of docs. Its title should be IComparer Interface (System.Collections). Look at the title right above this one for the ICollection interface and you'll see there are no parameters in the title.

**Comment by dendeli-msft** [comment]
This has since been addressed, thank you @svick and @mairaw 🎉
