### ISSUE TITLE
Duplicated snippet in tour-of-csharp/types chapter beside English version

### ISSUE THREAD

**Issue by aaa913121** [MicrosoftDocs/feedback#3992]
**Describe the bug**
During reading the `Classes and objects` paragraph, I found that error happens.
The `The memory occupied by...` and `Applications or tests for...` should be consecutive from the markdown file, while  there would be a duplicated `CreatePoints` snippet in versions besides English.
I encountered this error while reading zh-tw version, and tested some other like Japanese and Deutsch.

**To Reproduce**
1. Go to `dotnet/csharp/tour-of-csharp/types` chapter in learn.microsof.com
2. Select languages besides English to compare
3. See error

**Expected behavior**
Only one snippet would be present

**Screenshots**
![截圖 2024-03-07 下午3 31 51](https://github.com/MicrosoftDocs/feedback/assets/37338160/e753d802-bf1c-433f-9476-983c4b46e20b)
This is the zh-tw version

![截圖 2024-03-07 下午3 32 03](https://github.com/MicrosoftDocs/feedback/assets/37338160/eed58705-9a19-41d9-9577-c57104b78b23)
This is the English version like markdown file

**Comment by aaa913121** [comment]
Also see that `numberOfPoints` would be translated to `numPoints` automatically in version besides English from screenshots.

**Comment by gewarren** [comment]
Thanks @aaa913121. I logged an internal issue for this but will keep this issue open.

**Comment by gewarren** [comment]
The page has been completely redesigned, so I'll close this issue. Please let me know if you see this issue again.
