### ISSUE TITLE
Unable to find Mobile Network Policies

### ISSUE THREAD

**Issue by khattartarun** [MicrosoftDocs/feedback#3993]
**Describe the bug**
I have added new built-in policies with category "Mobile Network" which is available here https://github.com/Azure/azure-policy/tree/master/built-in-policies/policyDefinitions/Mobile%20Network but same is not available in the document https://learn.microsoft.com/en-us/azure/governance/policy/samples/built-in-policies.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by gewarren** [comment]
@davidsmatlak Can you help?

**Comment by davidsmatlak** [comment]
The [Mobile Network](https://learn.microsoft.com/azure/governance/policy/samples/built-in-policies#mobile-network) policy definitions were published on March 14, 2024. The content is generated by scripts from source code. But it's a manual process to run the scripts **after** the updates are merged into the Azure/azure-policy GitHub repository.

**Comment by davidsmatlak** [comment]
@gewarren Please close this issue.
