### ISSUE TITLE
Create a .NET class library using Visual Studio, Visual Basic Build Error

### ISSUE THREAD

**Issue by james-a-maher** [MicrosoftDocs/feedback#3994]
Good afternoon,

When following [this tutorial](https://learn.microsoft.com/en-us/dotnet/core/tutorials/library-with-visual-studio?pivots=dotnet-8-0) using the Visual Basic option, I have received the following error in building the solution:

BC30456: 'StartsWithUpper' is not a member of 'String'

I have pasted the code in from the tutorial, therefore the function has been defined as an extension. I have also added the library as a project reference in the application.

I am working in Visual Studio 2022, in Windows 11, in Parallels, on an M1 MacBook Air.

To reproduce this error, simply follow the Visual Basic version of the tutorial. This seems to be the same problem as was reported in [#12517](https://github.com/dotnet/docs/issues/12517).

Please find attached screenshots of the state of play.

Any help which you can provide would be much appreciated, and I apologise in advance if there is any error on my part.

Yours faithfully,
James Maher

<img width="1440" alt="Screenshot 2024-03-14 at 11 40 57" src="https://github.com/MicrosoftDocs/feedback/assets/163415634/38544f5f-318d-4d0f-8571-d5e18af8b27f">
<img width="1440" alt="Screenshot 2024-03-14 at 11 41 22" src="https://github.com/MicrosoftDocs/feedback/assets/163415634/a3bf5fdc-1001-40bc-9922-d4ebee2abac7">

**Comment by kamalkimo887** [comment]
Hello I have many problems and the main account is stolen please help

**Comment by kamalkimo887** [comment]
Can I help retrieve the main emails, knowing more than the emails, I was not able to retrieve it

**Comment by james-a-maher** [comment]
> Can I help retrieve the main emails, knowing more than the emails, I was not able to retrieve it

Regrettably, I don't understand what you mean. Have you replied to the right thread?

**Comment by gewarren** [comment]
This issue was moved to dotnet/docs#40155
