### ISSUE TITLE
Ability to share/highlight/embed parts of doc.

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#4]
Github allows to share/highlight a particular. (Eg: #L45). 
 
It would be great if docs support a similar feature.

----------
⚠ Idea migrated from UserVoice

**Created By:** Rajiv Kumar
**Created On:** 2018/03/02 21:21:15 +0000
**Votes at Migration:** 1
**Supporters at Migration:** 1

**Comment by dend** [comment]
Related to #172

**Comment by dend** [comment]
Closing as `wont-fix` at this time.
