### ISSUE TITLE
Update conent for Help Viewer

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#40]
1- In Help Viewer offline content, I can't find SIMD-Enabled Types and many new features.
2- It doesn't conatan Entity Framework.
3- Where is Framework 7.1 documents?
4- Whey there is still options for Framework 3.5, 4.0. 4.5 and 4.6? This can duplicate the content beacuse most topics are the same. It should be only one Framework reference that contains the shared features and what's new in each version.
The Help Viewer content is a mess, and I don't rely on it for the last year!

----------
⚠ Idea migrated from UserVoice

**Created By:** M. Hamdy
**Created On:** 2018/01/13 02:07:35 +0000
**Votes at Migration:** 1
**Supporters at Migration:** 1

**Comment by Jemash** [comment]
Adding @mschulz-msft

**Comment by dend** [comment]
@mschulz-msft have you had a chance to take a look at this?

**Comment by mschulz-msft** [comment]
Didn't see the previous notification. Will take a look at this.

**Comment by Rick-Anderson** [comment]
[In addition, System.Numerics.Vectors, the SIMD-enabled library of vectory types, was released as a NuGet package.](https://docs.microsoft.com/en-us/dotnet/standard/numerics)

**Comment by Rick-Anderson** [comment]
>Where is Framework 7.1 documents?
@botcrane  can you supply a URL for that?

**Comment by Powerhelmsman** [comment]
@Rick-Anderson Botcrane is not a real user. We use this account to migrate the ticket from old User Voice platform to current GitHub issue.

**Comment by dend** [comment]
@Rick-Anderson there is no URL - notice that the content relates to Offline Help Viewer.

**Comment by Rick-Anderson** [comment]
@dend  I meant the URL to the online version so we know what to look for. AFAIK, there's no such thing as  Framework 7.1 documents

**Comment by dend** [comment]
@Rick-Anderson I think the user meant 4.7.1. I am assuming the documents referenced are here: https://docs.microsoft.com/en-us/dotnet/standard/numerics

If we can't repro, we can close.

**Comment by Powerhelmsman** [comment]
@mschulz-msft do you have any update on this issue? Can you repro it?

**Comment by mschulz-msft** [comment]
#4 is something we can't change as there are people still relying on the content. 
#3 is probably as @dend says
#2 I did see some EF content when searching for it
#1 No answer

**Comment by Powerhelmsman** [comment]
We will now proceed to close this issue. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
