### ISSUE TITLE
Add license implication notice to Azure Datacenter Migration technical guidance

### ISSUE THREAD

**Issue by extcon** [MicrosoftDocs/feedback#400]
# Idea Title

License compliance awareness as part of migration or transformation projects to Azure

## Issue Details
Although the Azure Virtual Datacenter consists of mainly technical documentation it would be helpful for a number of reasons to at least provide a notice that you would want to make a licensing implication analysis when transforming workloads. E.g. a customer transformed a SQL cluster to several Windows VMs with SQL Server installed which cascaded the need to purchase more SQL Server licenses to stay compliant but perhaps choose a more positive example where license requirements would drop eg transformation to Azure SQL.

**Comment by Powerhelmsman** [comment]
@extcon Which content page are referring to?

**Comment by Powerhelmsman** [comment]
@extcon I will close it due to no enough information. If you have further question regarding to this, please reopen it. We will continue the discussion.
