### ISSUE TITLE
Document the legacy project upgrade breaking changes

### ISSUE THREAD

**Issue by JanKrivanek** [MicrosoftDocs/feedback#4009]
### Background

As part of MSBuild deprecated code removal effort (https://github.com/dotnet/msbuild/issues/8826) an upgrade support from pre-MSBuild projects (and pre-MSBuild webprojects) will be dropped in dev17.12

### The document to be updated

https://learn.microsoft.com/en-us/visualstudio/releases/2022/port-migrate-and-upgrade-visual-studio-projects

### Previous behavior

When encountered those legacy project types (from .NET 1.1 and prior), Visual Studio was able to automatically run upgrade wizard to make the necessary one-way changes in order to open the projects.

### New behavior

Upgrade wizard will run, but it will not be able to convert those old project types (rest of the upgrade will run successfuly).
Conversion upgrade log will display a clear customized error, that will provida an aka.ms link for more details:

<img width="1876" alt="ConversionFailure2" src="https://github.com/MicrosoftDocs/feedback/assets/3809076/7331ae43-7905-4b05-8d3c-a5170f1267ac">

Once the microsoft.learn article is properly updated (anchor should be added as well) - the aka.ms link will be pointed to the article.

### Workaround

Older VS version can be used to run the conversion, after which the upgraded project can be saved and then opened in the new VS version.

### Envisioned Timeline

The change is planned for dev17.12 P1

### Required changes
 * Add section for 'Unsupported upgrade scenarios' - describing the above described behavior and workaround.
 * The added section should be directly linkable (so that we can direct to it via the aka.ms link)

**Comment by gewarren** [comment]
FYI @ghogen @anandmeg

**Comment by ghogen** [comment]
This can be assigned to me.

**Comment by JanKrivanek** [comment]
**UPDATE 8/23:** 
* The conversion functionality of pre-MSBuild projects is going to be removed in 17.13 (for other project types it will continue to exist going forward)
* We should explicitly guide users to save & commit the converted projects - as the original formats might not be convertible in future VS versions. This will be messaged by curred wording:
  ![image](https://github.com/user-attachments/assets/0a0be716-9bdb-4b69-9fd5-d1aba67d1919)

  and
  
  
  ![image](https://github.com/user-attachments/assets/2cb19732-e0d0-4a40-90df-6d9b5f9dbfb1)

* We should have that information in the documentation document pointed by this bug (the dialog 'More information' hyperlink will point to it)
* This documentation should be bit more explicit - informing that pre-MSBuild project formats (replaced with MSBuild project format about 20 years ago) will be convertible only up to Visual Studio version 17.12 and won't be convertible from Visual Studio version 17.13 - so users should store the converted results. The other project formats will continue to be convertible for now and older Visual Studio versions will continue to convert even pre-MSBuild project files going forward. But the advise to store the converted results applies globaly - as in future versions of Visual Studio or future updates of previous releases of Visual Studio (2019, 2017) additional restrictions of upgrade functionality can apply.

**Comment by ghogen** [comment]
This was done a while ago.

https://learn.microsoft.com/en-us/visualstudio/releases/2022/port-migrate-and-upgrade-visual-studio-projects#pre-msbuild-projects

**Comment by ghogen** [comment]
#please-close
