### ISSUE TITLE
Tutorial by Upload files MVC core

### ISSUE THREAD

**Issue by grosvinsanchez** [MicrosoftDocs/feedback#401]
I am folowing tutorial about https://docs.microsoft.com/es-es/aspnet/core/tutorials/razor-pages/uploading-files?view=aspnetcore-2.0, I have a problem, I've trying to fix it , but I've cannot do it, on the section Upload file when I run app, than I do click on pages Schedule shows the next error:

(https://user-images.githubusercontent.com/39742973/40693657-d33d1364-6375-11e8-8e29-f18d31080576.png)

I am needing your help please.

Thanks for all.

**Comment by Powerhelmsman** [comment]
@grosvinsanchez Your issue is transferred to asp.net team. They will figure out the root cause for you.

**Comment by grosvinsanchez** [comment]
Thank you so much!!!
