### ISSUE TITLE
SQL Server 2005 database samples are no longer available on CodePlex

### ISSUE THREAD

**Issue by IanKemp** [MicrosoftDocs/feedback#402]
I guess this isn't really a docs.microsoft.com issue, so if you could tell me where I should report this so it doesn't get lost in the noise it would be great, or maybe if you good gents could just pass it along to the appropriate peeps. :)

Anyhow, if you go to https://www.microsoft.com/en-za/download/details.aspx?id=10679 to download the SQL 2005 sample databases, it redirects you to a project on the now-defunct CodePlex... Chrome is flagging CodePlex as a malicious site at this time, and the referenced project doesn't exist, so there's no apparent way to get hold of these samples.

I eventually managed to find out that the samples are now hosted at https://github.com/Microsoft/sql-server-samples/ - but the newest available samples there are only for SQL 2008, not 2005, so I have [opened an issue there](https://github.com/Microsoft/sql-server-samples/issues/415) to get this addressed.

**Comment by Powerhelmsman** [comment]
@IanKemp Please try https://docs.microsoft.com/en-us/previous-versions/sql/sql-server-2005/ms124501%28v%3dsql.90%29.
