### ISSUE TITLE
Windows Server 2016: Logical processor limit  (MAX) discrepancies and errors

### ISSUE THREAD

**Issue by lagriz** [MicrosoftDocs/feedback#403]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

**Link to article:**
https://www.microsoft.com/en-us/cloud-platform/windows-server-comparison
https://docs.microsoft.com/en-us/windows-server/get-started/2016-edition-comparison

**Problem:**

The Windows Server 2016 processor limits do not match  - and do not correspond to the tested values -

-On one site we can find this table :

Feature description | Windows Server 2012/2012 R2 Standard and Datacenter | Windows Server 2016 Standard and Datacenter
Physical (host) logical processor support|   Up to 320 LPs | Up to 512 LPs

- On another site, we can read

Maximum number of 64-bit sockets | 64 | 64
Maximum number of cores | unlimited | unlimited

Our testing shows that Windows Server 2016 - supports up to 640 logical processors ( this corresponds to Intel cores with Hyper Threading) above this value, logical processors are not reported.
To my knowledge also 2016 is limited to 20 NUMA nodes, that would be 20 sockets, right?

Is there a way to have matching limits?
I need to update our white papers and would like to reference Microsoft pages, but I find it hard for the reader to understand the right number.

Thank you.
Regards. 
Laurence Grizaud

**Comment by Powerhelmsman** [comment]
@lagriz Your issue is transferred to the author team. They will address your question there.

**Comment by lagriz** [comment]
Since the thread is closed, how do I know what the outcome is?

**Comment by Powerhelmsman** [comment]
@lagriz under your original issue, there is a link to transferred issue. You can click open it and it will redirect you to new issue page. Meanwhile, I am still monitoring the status of your transferred issued. If they resolved it but not inform you, I will inform you.
