### ISSUE TITLE
Aspire.Hosting.AWS Links Broken

### ISSUE THREAD

**Issue by mehalick** [MicrosoftDocs/feedback#4031]
**Describe the bug**

On https://learn.microsoft.com/en-us/dotnet/aspire/fundamentals/integrations-overview, the two links to AWS's Aspire.Hosting.AWS repository are broken. AWS recently moved this repository into their own GitHub account and these links need to be updated.

**To Reproduce**

1. Go to 'https://learn.microsoft.com/en-us/dotnet/aspire/fundamentals/integrations-overview#amazon-web-services-aws-hosting-integrations'
2. See two Aspire.Hosting.AWS links in section 'Amazon Web Services (AWS) hosting integrations'
3. Click them
4. See 404 error

**Expected behavior**

I expect the links to load the correct GitHub repositories.

**Comment by gewarren** [comment]
This seems to be fixed, so closing it.
