### ISSUE TITLE
Version switcher shows irrelevant versions and redirects to latest if I choose an inapplicable version

### ISSUE THREAD

**Issue by binki** [MicrosoftDocs/feedback#404]
**Describe the bug**
If I click in the dropdown to choose the .net version, it shows a bunch of versions which do not apply to the current page I’m on. On the old docs site, only versions applicable to the current API are shown. On docs.microsoft.com, it shows inapplicable versions. If I click on an inapplicable version, it redirects me to the latest version.

**To Reproduce**
1. Go to https://docs.microsoft.com/dotnet/api/system.valuetuple-1?view=netframework-4.7
2. Click on the “.NET Framework 4.7” dropdown.
3. Scroll down to 4.6.2 in the Version column.
4. Click on 4.6.2.
5. Observe that the page redirects to the same API but for “.NET Framework 4.7.2” (or whatever is latest at the time).

The user, at the end, may not notice that the redirect happened and think they are looking at 4.6.2 docs. Then they will wonder why they can’t use ValueTuple even though it seemed to them that it was in the docs for 4.6.2.

**Expected behavior**
I expect one of two things when opening the dropdown:

* Omit inapplicable versions, like the dropdown in the old MSDN site. In this case, only 4.7 and newer would show up under “.NET Framework”.
* Show old versions but show them as greyed out and not clickable.

Either of these changes would prevent the user from even getting to the confusing “redirect to latest version” behavior.

Another option would be to, instead of redirecting, show the user a page which explains that the API is not applicable to the version they chose. In fact, maybe this should be done as well so that people manually typing URIs get informed that they tried to exist an API that doesn’t exist for a particular version instead of being redirected. But the dropdown should never send the user to that page because doing so wastes the user’s time.

**Screenshots**

![image](https://user-images.githubusercontent.com/82626/40724877-17164bbc-63f0-11e8-9c54-e88d19a59a9e.png)
![screenshot_20180530-100232](https://user-images.githubusercontent.com/82626/40725174-bde530fc-63f0-11e8-8a51-58197484534e.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10 Version 1803 OS Build 17677.1000
 - Browser Firefox
 - Version 61.0b9

**Smartphone (please complete the following information):**
 - Device: OnePlus5
 - OS: OxygenOS-5.1.1, Android-8.1.0
 - Browser Firefox
 - Version 60.0.1

**Additional context**

**Comment by Powerhelmsman** [comment]
@binki Thanks for your detailed feedback. I will open an internal work item to track it.

**Comment by Powerhelmsman** [comment]
#log-suggestion @dend

**Comment by botcrane** [comment]
🚀 **ATTENTION**: [Internal request](https://ceapex.visualstudio.com/web/wi.aspx?pcguid=7d644393-99ad-41c8-ac53-7fa79294c720&id=23607) logged.

**Comment by dend** [comment]
Thanks for the feedback, @binki - the version switcher shows all versions for a product family, in this case - the .NET Platform. We have another bug tracking the showing of items in the table of contents (TOC) here - #347.
