### ISSUE TITLE
MSDN formatting: missing horizontal scroll

### ISSUE THREAD

**Issue by mairaw** [MicrosoftDocs/feedback#406]
From @rangercej 

Some of the lines in this page are really rather long, and when the right-hand side-bar (Feedback, Edit, Share, change theme, etc) are displayed, it's not possible to see entire code snippets nor all descriptions in the attributes table as they scroll underneath the right-hand side-bar. There appears no way to hide the side-bar. Browser: Vivaldi, with vertical tab-bar.

* Content: [\<security> of \<customBinding>](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/wcf/security-of-custombinding#feedback)
* Content Source: [docs/framework/configure-apps/file-schema/wcf/security-of-custombinding.md](https://github.com/dotnet/docs/blob/master/docs/framework/configure-apps/file-schema/wcf/security-of-custombinding.md)

**Comment by mairaw** [comment]
@adkinn moved the issue here since the content isn't resizing as I resize my browser window.

![image](https://user-images.githubusercontent.com/12971179/40803055-591fcb64-64cc-11e8-8439-64b61651abf1.png)

**Comment by adkinn** [comment]
@mairaw there should be a horizontal scroll bar at the bottom of the table. If you don't see that please let me know the browser and os you are running.

Additionally we do have some work planned to improve the experience for scrolling table that are taller than the viewport like this one.

**Comment by mairaw** [comment]
@adkinn this issue was actually reported by a customer. I've included his GH user here and he does mention he's using a browser called Vivaldi.

**Comment by mairaw** [comment]
BTW, I do see the scrollbar on the bottom of the table but because the table is large, I cannot see it and it's hard to read the text of the cells if you have to go up and down on the page to find the scroll. (I'm aware I can use keys or mouse to scroll as well)

**Comment by rangercej** [comment]
Hiya, browser is Vivaldi. Uses gecko as the rendering engine (like Chrome), however the same issue exists in Chrome. I missed the horizontal scroll in the first instance, but as @mariaw says, it's not particularly usable for this piece of documentation (and wasn't immediately discoverable as it was off screen). If the right-hand side-bar could be collapsed, it would make the documentation more readable/usable.

For compleness, Vivaldi browser details:

Vivaldi | 1.15.1147.36 (Stable channel) (32-bit)
Revision | 166efd59c7aba158f456fc82eabf5d0dffdc41f5-
OS | Windows
JavaScript | V8 6.5.254.41
Flash | (Disabled)
User Agent | Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.183 Safari/537.36 Vivaldi/1.96.1147.36

**Comment by Powerhelmsman** [comment]
@ShevaDas Can you take user's concern under consideration on improving scroll bar experience?

**Comment by Powerhelmsman** [comment]
#log-suggestion @ShevaDas

**Comment by botcrane** [comment]
🚀 **ATTENTION**: [Internal request](https://ceapex.visualstudio.com/web/wi.aspx?pcguid=7d644393-99ad-41c8-ac53-7fa79294c720&id=24064) logged.

**Comment by ShevaDas** [comment]
@rangercej Thanks for the feedback! I'm going to consolidate this issue with #336 and close this one out.
