### ISSUE TITLE
页面展示有问题，请尽快修复！！

### ISSUE THREAD

**Issue by gebiWangshushu** [MicrosoftDocs/feedback#407]
**.net core 文档 页面展示有问题**

**重现步骤**
1、https://docs.microsoft.com/zh-cn/aspnet/core/tutorials/first-web-api?view=aspnetcore-2.1#comments-container

2、页面下面很多代码都显示为 “[!code-csharp]”，请尽快修复！！

**Comment by Powerhelmsman** [comment]
@SonjaSaltzman Some sample code display as “[!code-csharp]”. English version is good. 
![image](https://user-images.githubusercontent.com/33136632/40851529-8750460c-657c-11e8-842c-c29bc5d60c86.png)

**Comment by SonjaSaltzman** [comment]
@nokura @DavidPrio Could you please investigate and fix?

**Comment by gebiWangshushu** [comment]
感谢回复！

**Comment by CeciAc** [comment]
你好，@gebiWangshushu
 
感谢你的反馈。 
 
我们正在积极查看你的评论，并会很快地再次和你取得联系。 
 
深深的祝福， 
Microsoft DOCS International Team

**Comment by Powerhelmsman** [comment]
@CeciAc Any update? The issue is still not resolved.

**Comment by SonjaSaltzman** [comment]
@DavidPrio for awareness, issue is still open?

**Comment by DavidPrio** [comment]
@gebiWangshushu 感谢你的反馈。 

我们的工程团队已评审并接受你的建议。我们已实施你的反馈，并将更新后的文章发布到 Docs 站点上的以下页面：https://docs.microsoft.com/zh-cn/aspnet/core/tutorials/first-web-api?view=aspnetcore-2.1#comments-container。  

非常感谢你对我们的文章作出的贡献，欢迎继续提供宝贵的反馈。 

深深的祝福， 
Microsoft DOCS International Team
