### ISSUE TITLE
将鼠标悬停在文本上，可在弹出窗口中显示英语文本。

### ISSUE THREAD

**Issue by douglasgdy** [MicrosoftDocs/feedback#408]
建议将技术文档页面顶部的“将鼠标悬停在文本上，可在弹出窗口中显示英语文本。【启用/禁用】”这句描述或按钮放置于页面右部，如“反馈”、“编辑”、“共享”等按钮显示于页面右部。这样，在文档很长时，方便操作。

**Comment by Powerhelmsman** [comment]
@douglasgdy On the right navigation, there is one switch. You can use it to switch to English. The right navigation will keep when you scroll down the long document. 
![image](https://user-images.githubusercontent.com/33136632/40927499-baf01b50-67d3-11e8-8c26-1fafda7a5516.png)
Let me know if it helps you.

**Comment by Powerhelmsman** [comment]
@douglasgdy I will close the issue now. Let me know if you have any concern on this so we can reopen the issue.
