### ISSUE TITLE
TrustCenter links don't redirect to language specific urls

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/feedback#409]
**Describe the bug**
Any links to https://www.microsoft.com/trustcenter/ and below without the language identifer `en-us` do not seem to work.
I realize this isn't a docs site page, but is linked to quite a bit from the docs, and is likely easier for you to address internally.

**To Reproduce**
1. Go to https://docs.microsoft.com/en-ca/azure/analysis-services/analysis-services-overview
2. Click on "Microsoft Trust Center"
3. The page loads https://www.microsoft.com/trustcenter/Security/AzureSecurity
4. Manually add `en-us/` after microsoft.com/ to be forwarded to https://www.microsoft.com/en-us/trustcenter/security/azure-security

**Expected behavior**
Language detection to work

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Powerhelmsman** [comment]
Close as transferring the issue to Azure team
