### ISSUE TITLE
Include a section on literals in VB.NET documentation

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#41]
The VB.NET documentation does not seem to have any information about how to provide literal values (numbers, characters, strings etc.). A new section is badly needed. It's taken me about 1/2 hour to not find the correct syntax for an unsigned 32-bit integer in hexadecimal.

----------
⚠ Idea migrated from UserVoice

**Created By:** PeterT
**Created On:** 2018/01/03 16:42:30 +0000
**Votes at Migration:** 1
**Supporters at Migration:** 1

**Comment by dend** [comment]
@mairaw @rpetrusha @BillWagner let me know what you think of this

**Comment by rpetrusha** [comment]
Each of the numeric types discuss literal assignments in a Literal Assignments section of that type's documentation; see, for example, the [Integer data type](https://docs.microsoft.com/dotnet/visual-basic/language-reference/data-types/integer-data-type). What search keywords were you using to find information on assigning a literal to an integer, @botcrane?

**Comment by mairaw** [comment]
We won't be able to get a response from @botcrane 😄. Those are the old UserVoice comments that got ported. @dend can you please close this?

**Comment by rpetrusha** [comment]
Thanks; I didn't realize @botcrane was a bot, though it's pretty obvious. I agree; I think that the documentation is thorough, so the issue can be closed, @dend.
