### ISSUE TITLE
Azure Detect faces API,how to change the URL picture to a local picture?

### ISSUE THREAD

**Issue by dapsjj** [MicrosoftDocs/feedback#410]
This [link](https://docs.microsoft.com/en-us/azure/cognitive-services/face/quickstarts/python)

I use azure Detect faces API But I find image_url is a picture of a network. Now I want to use my local picture,how to change the URL picture to a local picture?

Can you give me code?I use python 3.6

**Comment by Powerhelmsman** [comment]
Close as transferring the issue to Azure team.
