### ISSUE TITLE
SQL Database Threat Detection policies api

### ISSUE THREAD

**Issue by shouru** [MicrosoftDocs/feedback#411]
I want to use api to get the policies, but I don't know what the policies name are. Is it possible to get the policies name by API ?

This is used in my program. I hope I can get all info about the threat detection policies of the server.
Like get server information, I can use List operation rest api to get all. But Database Threat Detection Policies doesn't have. How can I get all policies information?
https://docs.microsoft.com/zh-tw/rest/api/sql/databasethreatdetectionpolicies

**Comment by Powerhelmsman** [comment]
@shouru This channel is for docs site's bug, feedback and suggestion instead of general coding questions. Please try SQL Server forum. Sorry can't help you find the right person to answer your question.
