### ISSUE TITLE
API Browser: System.Configuration.KeyValueConfigurationCollection does not show up in the list of supported APIs in DotNet Core 2.1 

### ISSUE THREAD

**Issue by yvinap** [MicrosoftDocs/feedback#412]
**Link to article:**
https://docs.microsoft.com/en-us/dotnet/api/?view=netcore-2.1

**Problem:**
System.Configuration namespace and types does not show up for .Net Core 2.1. They does show up for .Net Core 2.0. Can you clarify?

**Comment by Powerhelmsman** [comment]
@dend Can you take a look at this issue?

**Comment by yvinap** [comment]
Same observation for System.Configuration.ConfigurationManager

**Comment by dend** [comment]
@mairaw @BillWagner @terrajobst - can you confirm whether the API is available in the new release of .NET Framework or not?

**Comment by dend** [comment]
Bringing this to the top @mairaw @terrajobst - looks like it has to do with `System.Configuration.ConfigurationManager`, an assembly that we looked at excluding from the reflection.

**Comment by mairaw** [comment]
The plan is to remove those from the 2.0 docs because they're not part of the core of .NET Core. We can then add those later once we support the NuGet packages story.

**Comment by dend** [comment]
Thanks @mairaw. As such, closing this issue as a `wont-fix` for now.
