### ISSUE TITLE
PR Merge Bot should pick up #sign-off comment in PR Review response

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/feedback#413]
**Is your feature request related to a problem? Please describe.**
It seems like the "PRMerger" account doesn't pick up your control comments like `#sign-off` if they are embeded in the PR approval text.
EX: working for "issue comment" https://github.com/MicrosoftDocs/azure-docs/pull/9637#issuecomment-394444816
EX: not working for "pull request review" https://github.com/MicrosoftDocs/azure-docs/pull/9610#pullrequestreview-125692618

**Describe the solution you'd like**
The PR merger bot should also trigger when the sign off message is given in a PR review.

**Describe alternatives you've considered**
Maybe there is a separate bot that runs on a cron job to handle this case.

**Comment by Powerhelmsman** [comment]
@dend Can you take a look at this issue?

**Comment by dend** [comment]
This would be an ask for @meganbradley

**Comment by nschonni** [comment]
Thanks for following up 👍 
The second PR has also been merged now manually, but the bot didn't clear the tag. This is still an issue AFAIK

**Comment by nschonni** [comment]
Could this get bumped up the priority a bit. I've hit this in a few PRs on the Azure docs already, and I'm guessing that there might be other PRs that don't get landed in some of the larger repos for the same reason

**Comment by Powerhelmsman** [comment]
@nschonni Thanks for your feedback. I've initiated a internal item to track it. Will let you know the status.

**Comment by keziamicro** [comment]
Hello - reviewing and cleaning up some older feedback/issues. Thanks!
