### ISSUE TITLE
 Left menu and right menu taking too much space

### ISSUE THREAD

**Issue by mairaw** [MicrosoftDocs/feedback#414]
Original issue: https://github.com/dotnet/docs/issues/5781

From @rosdi:

Please allow us to toggle these left and right side bars... especially the right now... it is taking too much space...

Love the dark theme btw.

* Content: [Enumeration Format Strings](https://docs.microsoft.com/en-us/dotnet/standard/base-types/enumeration-format-strings#feedback)
* Content Source: [docs/standard/base-types/enumeration-format-strings.md](https://github.com/dotnet/docs/blob/master/docs/standard/base-types/enumeration-format-strings.md)

**Comment by dend** [comment]
@ShevaDas is the PM who can help here.

**Comment by Powerhelmsman** [comment]
#log-suggestion @ShevaDas

**Comment by botcrane** [comment]
🚀 **ATTENTION**: [Internal request](https://ceapex.visualstudio.com/web/wi.aspx?pcguid=7d644393-99ad-41c8-ac53-7fa79294c720&id=24681) logged.

**Comment by Powerhelmsman** [comment]
Close it as duplicate with https://github.com/MicrosoftDocs/feedback/issues/167. We will track it on the early issue.

**Comment by Powerhelmsman** [comment]
@rosdi @mairaw for your awareness.
