### ISSUE TITLE
DocFX styling hides content

### ISSUE THREAD

**Issue by mairaw** [MicrosoftDocs/feedback#415]
Original GitHub issue: https://github.com/dotnet/docs/issues/5779

From @florinciubotariu:

The website that DocFX is serving is not showing the content correctly. 

For example, if I navigate to:

`http://localhost:8080/standard/choosing-core-framework-server.html`

the [following](https://imgur.com/a/zzIzbuJ) page is displayed.

If I delete the `<div>` that is having the `container` class, then the content is displayed correctly, as you can see [here](https://imgur.com/a/ytr2DbW).

**Comment by dend** [comment]
@mairaw this also feels like something that should probably go into the DocFX repo instead: https://github.com/dotnet/docfx/issues

**Comment by Powerhelmsman** [comment]
This issue is transferred to docfx issues queue.
