### ISSUE TITLE
The "Try it" in "apimanagement/tenantaccess/update" is incorrect

### ISSUE THREAD

**Issue by norshtein** [MicrosoftDocs/feedback#416]
**Describe the bug**
In [https://docs.microsoft.com/en-us/rest/api/apimanagement/tenantaccess/update](https://docs.microsoft.com/en-us/rest/api/apimanagement/tenantaccess/update), in the "Try it" page, header "Content-Type: application/json" is absent, which causes the http response to be "415 Unsupported media type" even though all configuration is correct.

**To Reproduce**
1. Go to https://docs.microsoft.com/en-us/rest/api/apimanagement/tenantaccess/update
2. Click on 'Try it'
3. Fill in blank field using any valid value
4. Click "Run"
5. You will get response "415 Unsupported media type"

**Expected behavior**
If the input is valid, the response code should be "204" instead of "415"

**Screenshots**
![capture](https://user-images.githubusercontent.com/12193736/40955371-3e179d8a-68bc-11e8-95bc-b4a233efaf5f.PNG)

**Comment by Powerhelmsman** [comment]
@erickson-doug Can you take a look this content issue? @hellosnow for awareness.

**Comment by hellosnow** [comment]
@Powerhelmsman Doug may focus on VSTS content, so please involve me first. Thanks! 😄

**Comment by Powerhelmsman** [comment]
@hellosnow Can you update the status?

**Comment by hellosnow** [comment]
@Powerhelmsman this is tracked by bug https://ceapex.visualstudio.com/Engineering/_workitems/edit/26092 and may need @adkinn 's help on this.

**Comment by hellosnow** [comment]
@norshtein please have a try, our engineering made some fix already, let us know if any other issues.
