### ISSUE TITLE
中英文模式下，导航的页面显示有问题

### ISSUE THREAD

**Issue by HaoLife** [MicrosoftDocs/feedback#417]
https://docs.microsoft.com/zh-cn/windows/uwp/get-started/universal-application-platform-guide

英文的内容，中文的导航
中文的内容，英文的导航。

**Comment by Powerhelmsman** [comment]
@HaoLife Can you provide more detail about this issue?

**Comment by ToMakeSense** [comment]
related to #280 #392  #407

**Comment by ToMakeSense** [comment]
@Powerhelmsman I found the Chinese version document has English navigation, and the navigation is different, Chinese version has less Items than the English version
![image](https://user-images.githubusercontent.com/6244148/41477242-44c50e46-70f6-11e8-9b87-adf73bee0518.png)
![image](https://user-images.githubusercontent.com/6244148/41477281-5ba32b70-70f6-11e8-8931-9d3120644154.png)

**Comment by Powerhelmsman** [comment]
@SonjaSaltzman Can you take a look at this localization issue?

**Comment by SonjaSaltzman** [comment]
@elizatobias -- is this from your content set? Could you please follow up?

**Comment by elizatobias** [comment]
Yes I'm actively addressing this.

**Comment by Powerhelmsman** [comment]
@elizatobias What's the status?

**Comment by SonjaSaltzman** [comment]
@dongmicro could you please follow up on this?

**Comment by SonjaSaltzman** [comment]
@nokura and @v-nidolc as the content has been moved to our team, could you please follow up?

**Comment by srvbpigh** [comment]
Hello, @HaoLife
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by v-cakoll** [comment]
This does not repro. The navigation is translated and there seems to be the same number of topics (it has grown quite a bit).

**Comment by srvbpigh** [comment]
Hello, @HaoLife
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by SonjaSaltzman** [comment]
Closing this issue as it no longer exists. If you find this in error, please reopen.
Thank you,
Sonja
