### ISSUE TITLE
traffic Manager overview have some issues

### ISSUE THREAD

**Issue by hylinux** [MicrosoftDocs/feedback#418]
here's the document link:
https://docs.microsoft.com/en-us/azure/traffic-manager/traffic-manager-overview

there's a example for Corp Contoso ,  the example want to explain how to use traffic manager route request to url: https://partners.contoso.com/login.aspx. but all picture is saying how to route www.contoso.com to correct service, make people confuse, what's related between www and partner.

thanks

**Comment by Powerhelmsman** [comment]
@hylinux Your issue is transferred to Azure team. They will help you on the specific content issue there.

**Comment by hylinux** [comment]
@Powerhelmsman  sure. thanks
