### ISSUE TITLE
Add an "As at" or "Updated on" date near the Download PDF button

### ISSUE THREAD

**Issue by docs-product** [MicrosoftDocs/feedback#42]
Since the documentation is constantly being updated, for those who download the PDF, it would be helpful to know when the documentation was last updated indicated near the Download PDF button.

----------
⚠ Idea migrated from UserVoice

**Created By:** Ken
**Created On:** 2018/01/01 14:50:34 +0000
**Votes at Migration:** 1
**Supporters at Migration:** 0

**Comment by Powerhelmsman** [comment]
#log-suggestion @dastaffo

**Comment by botcrane** [comment]
🚀 **ATTENTION**: [Internal request](https://ceapex.visualstudio.com/web/wi.aspx?pcguid=7d644393-99ad-41c8-ac53-7fa79294c720&id=22772) logged.

**Comment by dastaffo** [comment]
Adding @cillroy to evaluate for the future.

**Comment by mlottner** [comment]
Closing this outstanding issue for now as the request was logged and assigned. Of course, work can and will continue on closed Git issues and commenting/discussion capabilities remain intact.
