### ISSUE TITLE
Request single page for `Action` and `Func` declarations

### ISSUE THREAD

**Issue by mairaw** [MicrosoftDocs/feedback#421]
@BillWagner commented on [Thu Feb 18 2016](https://github.com/dotnet/docs/issues/261)

The API docs have individual pages for all the Action delegate types (https://docs.microsoft.com/en-us/dotnet/core/api/system.action to https://docs.microsoft.com/en-us/dotnet/core/api/system.action-16) and all the Func Types (https://docs.microsoft.com/en-us/dotnet/core/api/system.func-1 to https://docs.microsoft.com/en-us/dotnet/core/api/system.func-17) When writing about the concepts (in articles about generics, delegates, events, and covariance), it would be great to have one link that would list all the variations of Action and Func. Can that be generated from the source?

---

@mairaw commented on [Wed Apr 26 2017](https://github.com/dotnet/docs/issues/261#issuecomment-297623135)

@BillWagner have we ever filed a feature request for this?

---

@BillWagner commented on [Wed Jun 06 2018](https://github.com/dotnet/docs/issues/261#issuecomment-297721515)

I could not find one.  I created item [#16418](https://ceapex.visualstudio.com/Engineering/_workitems/edit/16418) Feel free to edit.

**Comment by Powerhelmsman** [comment]
#log-suggestion @dend

**Comment by botcrane** [comment]
🚀 **ATTENTION**: [Internal request](https://ceapex.visualstudio.com/web/wi.aspx?pcguid=7d644393-99ad-41c8-ac53-7fa79294c720&id=24682) logged.

**Comment by mairaw** [comment]
@Powerhelmsman note that an internal request already existed: https://ceapex.visualstudio.com/Engineering/_workitems/edit/16418

I'm just moving things that are not content fixes our team can do out of our repo.

**Comment by Powerhelmsman** [comment]
@mairaw Thanks for note. I added this link to work item. Den will update the status later.

**Comment by dend** [comment]
Following-up on the item. Given that there is an internal item tracking the work for this enhancement, and there is currently no definitive timeframe for the implementation, I will close this issue. We will continue looking at what is the best way for us to implement this in the .NET API documentation experience.
