### ISSUE TITLE
Internal DevDiv work item edit link in VS 15.7.3 release notes

### ISSUE THREAD

**Issue by nCastle1** [MicrosoftDocs/feedback#422]
Link: https://docs.microsoft.com/en-us/visualstudio/releasenotes/vs2017-relnotes#15.7.3 

Problem: "UWP XAML is very slow to open" links to https://devdiv.visualstudio.com/DevDiv/_workitems/edit/615696 instead of a description of the issue. 

Note: Visiting that page seemed to auto-enroll me somehow, possibly through IWA? You might want to delete my devdiv vsts account.

**Comment by Powerhelmsman** [comment]
@erickson-doug Can you take a look at this issue?

**Comment by nCastle1** [comment]
Forgot to mention, the created account is aee6e3c9-711e-4c7c-bd27-04f2307db20d\nath9278@esri.com.

**Comment by dend** [comment]
Thanks for the feedback, @nCastle1 - I've raised this with our team.

**Comment by dend** [comment]
This is now resolved!
