### ISSUE TITLE
Search for F# yields no results

### ISSUE THREAD

**Issue by jongalloway** [MicrosoftDocs/feedback#426]
**Describe the bug**
Searching for "F#" yields no results. Searching for "C#" has a lot of results. F# search should at least bring up https://docs.microsoft.com/en-us/dotnet/fsharp/

**To Reproduce**
1. Go to 'docs.microsoft.com'
2. Search for 'F#'
3. Observe that there are no results found

**Expected behavior**
Some results for F#, especially https://docs.microsoft.com/en-us/dotnet/fsharp/

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Edge

**Additional context**
This was raised by a viewer on @csharpfritz's Twitch stream.

**Comment by presleyy** [comment]
Created a [bug](https://ceapex.visualstudio.com/Engineering/_workitems/edit/25941) to track that issue

**Comment by dend** [comment]
@presleyy @Sampy was there any progress on this issue?

**Comment by keziamicro** [comment]
Hello - reviewing and cleaning up some older feedback/issues. Thanks!

**Comment by jongalloway** [comment]
Just tested, it looks like this has been fixed.

https://docs.microsoft.com/search/?terms=F%23
