### ISSUE TITLE
Unable to see @ symbol

### ISSUE THREAD

**Issue by nitu1702** [MicrosoftDocs/feedback#427]
Using Version 15.117.27414.0
I created some tasks in TFS and assigned to my team members.

Team member could see it in his list and change status, update comments.

But the team member cannot see '@' for tagging. Because of this, I as a manager do not get mails on what he has updated.

What could be the reason that he cannot tag people in discussions ?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Powerhelmsman** [comment]
@nitu1702 This channel is for Docs site related feedback. So I transferred your issue to Visual Studio team issue channel. They will help you there.
