### ISSUE TITLE
Typo on Azure for Python developers page

### ISSUE THREAD

**Issue by rogererens** [MicrosoftDocs/feedback#428]
**https://docs.microsoft.com/en-us/python/azure/?view=azure-python:**

**Problem:**
One of the 5-Minute Quickstarts has a title
"Build a Comos DB SQL API app"
which should be
"Build a Co**s**mos DB SQL API app"

**Comment by Powerhelmsman** [comment]
@lisawong19 @dend Can you quickly fix it?

**Comment by dend** [comment]
Thanks @nschonni - resolving this issue. i18n versions will be updated automatically.
