### ISSUE TITLE
Cortana Background Problem

### ISSUE THREAD

**Issue by superkid200** [MicrosoftDocs/feedback#429]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

**Link to article:**
The article that cause this problem is at https://docs.microsoft.com/en-us/cortana/voice-commands/launch-a-background-app-with-voice-commands-in-cortana

**Problem:**
The App Service name in Package.appxmanifest and the App Service name in the VCD file is not the same. I think this may cause Cortana can't contact with the App Service.

**Comment by superkid200** [comment]
And Cortana UI won't work but spoken message still be spoken.

**Comment by Powerhelmsman** [comment]
@Karl-Bridge-Microsoft Can you take a look at the issue?

**Comment by Karl-Bridge-Microsoft** [comment]
@superkid200 @Powerhelmsman - The snippet has been fixed. Please be sure to check the related sample for the most up to date code (linked from the doc). It sees regular updates and maintenance.
