### ISSUE TITLE
Add documentation for System.Threading.Channels

### ISSUE THREAD

**Issue by kdelorey** [MicrosoftDocs/feedback#430]
# System.Threading.Channels Documentation

With the release of .NET Core 2.1 came a new assembly [System.Threading.Channels](https://www.nuget.org/packages/System.Threading.Channels/). This assembly is dependent on [Microsoft.AspNetCore.App](https://www.nuget.org/packages/Microsoft.AspNetCore.App/) via. the dependent SignalR package.

Information about this assembly should be generated and added to the docs.microsoft.com website.

**Comment by Powerhelmsman** [comment]
@mairaw @dend Can you take a look at this request?

**Comment by mairaw** [comment]
We don't currently support adding docs for specific .NET NuGet packages. We only have the platform docs now.
There's a feature request that @dend is working on to enable that in the future.

**Comment by dend** [comment]
Closing this request for now, as this is not a scenario currently supported. Any core types that are shipped with the platform will always be documented, however extensions are currently not included. This will be addressed in the future.

**Comment by kdelorey** [comment]
So even though is `System.Threading.Channels` is apart of [`corefx`](https://github.com/dotnet/corefx/tree/master/src/System.Threading.Channels), it's not apart of the core platform? I guess I'm just confused as to where this assembly lands in the ecosystem.

**Comment by mairaw** [comment]
It's not part of the shared framework that ships with the .NET Core runtime and instead is released as a NuGet package. What you see in corefx is .NET Core + extensions.
