### ISSUE TITLE
ListItem oListItem = oList.Items.GetById(3); will not run

### ISSUE THREAD

**Issue by chanmmn** [MicrosoftDocs/feedback#431]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

**Link to article:**
https://github.com/MicrosoftDocs/feedback/issues/new?template=Custom.md

**Problem:**
ListItem oListItem = oList.Items.GetById(3); will not run. 
I change it to 
ListItem oListItem = oList.GetItemById(2);
it is running fine.

**Comment by Powerhelmsman** [comment]
@chanmmn Can you tell us which page you refer to?

**Comment by dend** [comment]
Given that this is a technical question related to content that is archived, we cannot address it in this repo. Please start a thread in the [SharePoint forum](https://social.msdn.microsoft.com/Forums/sharepoint/en-US/home?category=sharepoint).

**Comment by chanmmn** [comment]
dend, I have put it in the forum https://social.msdn.microsoft.com/Forums/sharepoint/en-US/17c7adc6-cc00-4fd0-81a8-ad84c703d4ff/listitem-olistitem-olistitemsgetbyid3-will-not-run?forum=sharepointdevelopment.
