### ISSUE TITLE
PowerPivot for Excel Tutorial Sample Data – Version 2

### ISSUE THREAD

**Issue by BeginBI** [MicrosoftDocs/feedback#435]
**Link to article:**
https://docs.microsoft.com/en-gb/previous-versions/sql/sql-server-2012/gg413497%28v%3dsql.110%29

**Problem:**
Could not access the web site to download the files "PowerPivot for Excel Tutorial Sample Data – Version 2. "
http://go.microsoft.com/fwlink/?linkid=164474

**Comment by Powerhelmsman** [comment]
@BeginBI Thanks for your feedback. The page is no longer updating. But you can try https://archive.codeplex.com/?p=powerpivotsdr to download archive sample data.

**Comment by BeginBI** [comment]
Hello,
Thanks your feedback, but after download, it open the folder, 
I could not open the file, because it not Extension.

\PowerPivotSDR.zip\releases\0\e41b9cc6-d500-4a95-a212-67a9909acbb4

**Comment by BeginBI** [comment]
@Powerhelmsman 
Hello,
Thanks your feedback, but after download, it open the folder,
I could not open the file, because it not Extension.

\PowerPivotSDR.zip\releases\0\e41b9cc6-d500-4a95-a212-67a9909acbb4

**Comment by Powerhelmsman** [comment]
@BeginBI Actually the file is out of our scope:) But I did some investigation. Actually the sample data is a Contoso database. You can use this link to download https://www.microsoft.com/en-us/download/details.aspx?id=18279, the SQL server version instead of Access version.

**Comment by BeginBI** [comment]
@Powerhelmsman 
thank you , it so kind of you.
