### ISSUE TITLE
Bots should handle notifying mulitple authors when a PR touches multiple files

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/feedback#436]
**Is your feature request related to a problem? Please describe.**
When a PR touches multiple documents, only a single author is notified. I had a large but simple PR https://github.com/MicrosoftDocs/visualstudio-docs/pull/1119 and I can't tell how the bot choose the single author it did.

**Describe the solution you'd like**
The bot should notify all authors with impacted documents in a PR

**Describe alternatives you've considered**
Contributors shouldn't be touching multiple articles at once 😜 . If the bot doesn't like it, it could also suggest splitting a PR so only a single author is impacted.

**Comment by Powerhelmsman** [comment]
@meganbradley Can you take a look at this suggestion?

**Comment by nschonni** [comment]
Looks like this is working as of this week on some repos, so I guess the bots have been updated

**Comment by meganbradley** [comment]
@nschonni yes - thanks again for the feedback!
