### ISSUE TITLE
SEO for particular APIs has decreased since the move to docs.microsoft.com

### ISSUE THREAD

**Issue by davkean** [MicrosoftDocs/feedback#437]
**Describe the bug**
I'm used to typing an API into google, and automatically have the first hit be that API on MSDN. Since the move to docs.microsoft.com this is no longer the case.

An example is EnvDTE.Project.

**To Reproduce**
1. In Google, search for "EnvDTE.Project"

**Expected behavior**
First hit to be https://docs.microsoft.com/en-us/dotnet/api/envdte.project?view=visualstudiosdk-2017

**Actual behavior**
Zero hits for that page.

**Screenshots**
The first hits are languages Spanish and Italian pages on MSDN for EnvDTE.Project. The next hit is "EnvDTE.Projects", which is not the same API.

![image](https://user-images.githubusercontent.com/1103906/41404468-a62f1ae2-700a-11e8-8692-81f0064717fd.png)

**Comment by Powerhelmsman** [comment]
@presleyy Can you take a loot at this issue?

**Comment by presleyy** [comment]
Need SEO for that reference content. @Khairunj could you please take a look?

**Comment by dend** [comment]
@erickson-doug @ghogen ping on this issue.

**Comment by ghogen** [comment]
@dend It sounds like we need to request redirection for the VS SDK reference pages from MSDN to Docs for non-ENU languages.  That may help by addressing the appearance of the non-ENU pages as top search results.  I'm not totally sure that solves the problem completely, but it certainly seems like a first step.  I'll get that request set up.

**Comment by erickson-doug** [comment]
@dend @ghogen I'd work with someone in International, but I don't know how. They will need to update our openpublishing.redirects.json in their loc repos accordingly.

**Comment by ghogen** [comment]
This is related to the archiving work that was done recently with Jenny Mashkowski.  The loc redirects should have been set up by that team.  The English MSDN page for this API is redirecting as expected, but the Italian should direct to https://docs.microsoft.com/it-it/previous-versions/visualstudio/visual-studio-2013/k3dys0y2(v%3dvs.120)

**Comment by Khairunj** [comment]
@ghogen @dend @erickson-doug I have sent a note to Jenny to find out why localized content is not redirected yet.  It seems like Loc content is orphan and not in TOC.

**Comment by Khairunj** [comment]
@davkean  
Can you try to search again it seems like now the api documentation on Google is coming as third result?
![image](https://user-images.githubusercontent.com/18732564/43350390-9037ebb0-91bb-11e8-8608-62914677d344.png)

**Comment by davkean** [comment]
@Khairunj Can you please reopen this bug? My issue is not resolved.

**Comment by Powerhelmsman** [comment]
@davkean Reopened.

**Comment by mairaw** [comment]
It seems this issue is now solved and the expected result is ranked #1: 

![image](https://user-images.githubusercontent.com/12971179/66987585-ee380780-f075-11e9-81ca-7970ac921fda.png)
