### ISSUE TITLE
Examples are too large

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#44]
The examples in many of your pages are too large. One such is https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.ienumerable-1?view=netframework-4.7.1

Examples should be as small as possible to show the functionality and use of the subject, not complete programs involving other concepts (such as LINQ in this example). That way, far less scrolling is needed, and the principles can be grasped far quicker.

----------
⚠ Idea migrated from UserVoice

**Created By:** PeterT
**Created On:** 2017/12/28 12:08:18 +0000
**Votes at Migration:** 1
**Supporters at Migration:** 1

**Comment by Powerhelmsman** [comment]
Thanks for your suggestion. I will bring it to the team to advocated your suggestion.

**Comment by Powerhelmsman** [comment]
#log-suggestion

**Comment by botcrane** [comment]
🚀 **ATTENTION**: [Internal request](https://ceapex.visualstudio.com/web/wi.aspx?pcguid=7d644393-99ad-41c8-ac53-7fa79294c720&id=20956) logged.
