### ISSUE TITLE
More resources for the azure-docs repo

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/feedback#440]
**Is your feature request related to a problem? Please describe.**
This is probably the largest set of docs, and currently has more than 200 open PRs, can more resources be aligned to triage that repo?

**Describe the solution you'd like**
Maybe some dedicated resources to grooming and landing simple PRs

**Describe alternatives you've considered**
Everyone is heads down writing good stuff :shipit:

**Comment by Powerhelmsman** [comment]
@nschonni This issue is related to azure-docs repo, I transfer you issue to the team so they can follow up.
