### ISSUE TITLE
YouTube continues playing with "Next" tab in the PowerBI "Getting Started" guide

### ISSUE THREAD

**Issue by brbro** [MicrosoftDocs/feedback#442]
**Describe the bug**
Audio from YouTube continues playing if you click the "Next ->" section. This creates overlapping audio with no way to silence the previous tab.

**To Reproduce**
1. Go to https://docs.microsoft.com/en-us/power-bi/guided-learning/gettingdata?tutorial-step=3
2. Click on a YouTube video
3. Scroll down to 'Next ->'
4. Play a YouTube video on the next tab.

**Expected behavior**
Audio should stop when moving to a new tab.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: IE 10
 - Version: 11.431.16299.0

**Comment by brbro** [comment]
This bug also occurs on Microsoft Edge v. 41.16299.402.0

**Comment by Powerhelmsman** [comment]
@brbro I open a internal bug to track it. I will let you know once the bug is fixed.

**Comment by brbro** [comment]
:thumbs up:


________________________________

**Comment by Powerhelmsman** [comment]
@brbro This bug is fixed now. Please double check. I will closed as resolved so far. if you have other question related to this we reopen it and continue the discussion.
