### ISSUE TITLE
Korean Translation on IoT Central

### ISSUE THREAD

**Issue by AhnMkt** [MicrosoftDocs/feedback#443]
**🛑 IMPORTANT**: 

**Link to article:**
https://docs.microsoft.com/ko-kr/azure/iot-fundamentals/

**Problem:**
What's wrong with the article?
![iotcentral](https://user-images.githubusercontent.com/40348316/41517659-91fe890a-72f7-11e8-9c47-96c9310ed955.png)
Korean translation 'IoT 중부' on the document should be 'IoT Central' as it is in English. The other pages of IoT Central are fine but only this page need to change.
Can I please get it fixed then Korean users won't be confused?

Thank you very much in advance.
Ahn

**Comment by nschonni** [comment]
Looks like there are a few hits in different docs https://github.com/search?q=org%3AMicrosoftDocs+IoT+%EC%A4%91%EB%B6%80&type=Code

**Comment by SonjaSaltzman** [comment]
@DavidPrio could you please fix?

**Comment by CeciAc** [comment]
Hello, @AhnMkt,
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by AhnMkt** [comment]
Hello,
Thank you for your reply.
Hopefully I’ve found the right way to request.

Best,
Ahn

**Comment by AhnMkt** [comment]
Hello,
It’d be great if you could tell me if it’s going to be fixed soon, or I should find another way to request.
Thank you in advance.

Kind Regards,
Ahn
From: Hyungchoul Ahn (Adecco Korea)
Sent: Thursday, June 21, 2018 9:54 AM
To: 'MicrosoftDocs/feedback' <reply@reply.github.com>; MicrosoftDocs/feedback <feedback@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [MicrosoftDocs/feedback] Korean Translation on IoT Central (#443)

Hello,
Thank you for your reply.
Hopefully I’ve found the right way to request.

Best,
Ahn

**Comment by DavidPrio** [comment]
Hi @AhnMkt We are sorry about the delay on this feedback. We are actively working on this and should have a resolution by the end of the week. Thank you for your contribution.
Kind regards,

Microsoft DOCS International Team

**Comment by DavidPrio** [comment]
Hello, @AhnMkt , 
 
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to pages https://docs.microsoft.com/ko-kr/azure/iot-fundamentals/. 

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.

Kind regards,
Microsoft DOCS International Team

**Comment by AhnMkt** [comment]
Hello David,
Thanks a lot. Really appreciate it.

Kind Regards,
Ahn
________________________________
