### ISSUE TITLE
Clarify Top Navigation Bar

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/feedback#447]
**Is your feature request related to a problem? Please describe.**
On the PowerApps page, I'm already logged in, but there is still a prompt to Sign In and another to Sign up Free.  This is confusing. Clicking on the Sign in link opens PowerApps in the same window and i'm sent out of Docs.microsoft.com unexpectedly

If I'm not signed in, it is not clear which sign-in link i should use. 

**Describe the solution you'd like**
There should be only one Sign In link or the  Sign In text should be clarified to clearly indicate that this is to sign in to PowerApps in our own tenant and has nothing to do with being signed in to docs.microsoft.com. The Signup free link should not be shown to us when we already have signed up.

**Additional context**
![image](https://user-images.githubusercontent.com/4058555/41661684-41555ba6-746d-11e8-97c5-3d0471885b55.png)

![image](https://user-images.githubusercontent.com/4058555/41661533-fc4cb126-746c-11e8-80cf-92f26587a325.png)

**Comment by Powerhelmsman** [comment]
@DeanGross Thanks for your suggestion. We are designing the new universal head foot, which will resolve the confusion. Once it is deployed, I will inform you.

**Comment by Powerhelmsman** [comment]
@kubeaver for your awareness.

**Comment by ShevaDas** [comment]
@DeanGross I agree this is confusing. Unfortunately, what goes in the PowerApps header is a choice made by the PowerApps team. I'll pass along your feedback to them but as this isn't something the Docs team controls I'm going to close this out for now. Thanks for taking the time to let us know!
