### ISSUE TITLE
sdg.RentBroker.Data or one of its dependencies not found

### ISSUE THREAD

**Issue by nediyadath** [MicrosoftDocs/feedback#448]
I created a webapi project and hosted it in everleap.com.

**To Reproduce**
1. I created a register.cshtml page in the home controller of the application and directed the button click to the register method in the api.  I passed the post data through the registerbindingmodel
2. When I click on the register button I get the above mentioned error.

**Comment by dend** [comment]
Hello! Given that this issue is not related to docs.microsoft.com, we cannot address it in this forum.
