### ISSUE TITLE
When viewing VisualStudioHelp it would be nice to see the applicable version of the target programming language

### ISSUE THREAD

**Issue by docs-product** [MicrosoftDocs/feedback#45]
and instead show which version of C# it is. Like Version C# 7.1.

----------
⚠ Idea migrated from UserVoice

**Created By:** cristadli
**Created On:** 2017/12/22 16:54:45 +0000
**Votes at Migration:** 1
**Supporters at Migration:** 1

**Comment by Powerhelmsman** [comment]
@dastaffo Is this belong to your area?

**Comment by dastaffo** [comment]
@ShevaDas FYI for future offline plans

**Comment by dendeli-msft** [comment]
Closing this item as it's mostly related to content, that can be addressed by the respective authors.
