### ISSUE TITLE
Add direct link to ReferenceSource from .NET API docs

### ISSUE THREAD

**Issue by ChrisMaddock** [MicrosoftDocs/feedback#451]
**Is your feature request related to a problem? Please describe.**
Whilst the API docs are brilliant in so many ways, there are odd places where they're incomplete, or outdated. In these cases - I still need to find the answer I came looking for, so want to be able to look at the actual source code to check out what's going on.

**Describe the solution you'd like**
On each API page - it would be great if we could have a direct link to the exact line number of that method signature on https://referencesource.microsoft.com.

cc @mairaw @rpetrusha @BillWagner - this needs no action, but I'd be interested in your thoughts!

**Comment by svick** [comment]
One question is: to which source to link to? Specifically:

* .Net Core and .Net Framework APIs are documented together. Should the link point to the source for one of them or should there be two links?
* Should the link point to [SourceBrowser](https://github.com/KirillOsenkov/SourceBrowser)-based sites or to GitHub?
    * With SourceBrowser, you get nice navigation, but you don't get a choice to which version to link to (and with .Net Core or Roslyn SourceBrowser, you get access to latest code, which doesn't correspond to any released version).
    * With GitHub, you could link to the exact code for any specific version, using tags (or commit IDs). But you don't get any special navigation support.

Of course, the ideal solution would be to add some versioning support to SourceBrowser, but I'm not sure how likely that is.

**Comment by Powerhelmsman** [comment]
@dend Can you follow up?

**Comment by mairaw** [comment]
It's a tricky ask for the .NET docs, easier for other .NET based products with a single source like ASP.NET Core. Even for .NET Core, we have the problem of partial implementations for each OS for the same API on the same product.

**Comment by ChrisMaddock** [comment]
> .Net Core and .Net Framework APIs are documented together. Should the link point to the source for one of them or should there be two links?

Aren’t you always browsing the API in the context of a certain framework? Should be possible to generate links appropriately in that case.

> Should the link point to SourceBrowser-based sites or to GitHub?

Wasn’t aware sourcebrowser was unversioned...that’s sad. #net40forlyfe

**Comment by svick** [comment]
@ChrisMaddock 

> Aren’t you always browsing the API in the context of a certain framework? Should be possible to generate links appropriately in that case.

That's a good point. I guess that means that if you're viewing the API reference for .Net Standard, there would be no reference source link.

**Comment by ChrisMaddock** [comment]
Good point.

**Comment by Powerhelmsman** [comment]
#log-suggestion @dend

**Comment by botcrane** [comment]
🚀 **ATTENTION**: [Internal request](https://ceapex.visualstudio.com/web/wi.aspx?pcguid=7d644393-99ad-41c8-ac53-7fa79294c720&id=26681) logged.

**Comment by dend** [comment]
Closing this in favor of #433 - let's keep the conversation there!

**Comment by gewarren** [comment]
Great news - the core .NET libraries now have links to source code!
Example: https://learn.microsoft.com/dotnet/api/system.string.chars?view=net-8.0
