### ISSUE TITLE
VSTS build badge by repo does not work (with YAML definitions?)

### ISSUE THREAD

**Issue by BenjaminAbt** [MicrosoftDocs/feedback#452]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

There is no comment section on that page

**Link to article:**

https://docs.microsoft.com/en-us/rest/api/vsts/build/badge/get%20build%20badge%20data?view=vsts-rest-4.1

**Problem:**
* The parameter `branchName` is required, too.
Otherwise you get the following error:
```json
{
"$id": "1",
"innerException": null,
"message": "Value cannot be null.\r\nParameter name: branchName",
"typeName": "System.ArgumentNullException, mscorlib",
"typeKey": "ArgumentNullException",
"errorCode": 0,
"eventId": 0
}
```

* There is no hint where I can find the project Id. I use https://{myworkspace}.visualstudio.com/_apis/projects

* Even with correct parameters I just get a `setup now` badge: 
![badge](https://user-images.githubusercontent.com/6189336/41790988-a6eceab8-7654-11e8-8612-19591068392b.png)

I think this is because I am using YAML build definitions.

**Comment by Powerhelmsman** [comment]
@wnjenkin Can you take a look at this REST API question?

**Comment by ericsciple** [comment]
badges arent supported yet for yaml definitions https://github.com/Microsoft/vsts-agent/blob/master/docs/preview/yamlgettingstarted-features.md

**Comment by moswald** [comment]
If you can use the new 5.0 (preview) API, there is a new, preferred endpoint for displaying the badge that will work for yaml definitions as well:

https://docs.microsoft.com/en-us/rest/api/vsts/build/status/get?view=vsts-rest-5.0

Note that if your project is not marked "public", then the user will be required to log in to see the badge.

**Comment by BenjaminAbt** [comment]
Thank you @moswald , this works fine!
