### ISSUE TITLE
Display issues on page Bob Deinterlacing Algorithm

### ISSUE THREAD

**Issue by drmandarin** [MicrosoftDocs/feedback#453]
# Idea Title

Display issues on page Bob Deinterlacing Algorithm

## Issue Details

On this page:
https://docs.microsoft.com/en-us/windows-hardware/drivers/display/bob-deinterlacing-algorithm

Multiple display issues in formulae in the text, e.g:
0 <= i <= Mâˆ’1
0 <= j <=Nâˆ’1
(9*(b+c)âˆ’(a+d)+8)>>4

Please fix these issues.

**Comment by Powerhelmsman** [comment]
@drmandarin Thanks for your finding. Your issue is transferred to author's team. They will help you there.
