### ISSUE TITLE
Dark theme makes some columns hard to read

### ISSUE THREAD

**Issue by supereddie** [MicrosoftDocs/feedback#455]
In the [VSTS Features Timeline](https://docs.microsoft.com/en-gb/vsts/release-notes/index#current-features) and using the Dark theme, the column 'Server' contains white background with light gray text, making it hard to read.

A bit further down that page, under 'Server Build Numbers', the same happens with the 'Release' column

**Comment by Powerhelmsman** [comment]
@ShevaDas Can you take a look at this? I am not sure if this is a bug by site or by author.

**Comment by ShevaDas** [comment]
@supereddie Thanks for the feedback! This is a content bug, so I'll reach out to the author and ask them to investigate.

**Comment by alexcnichols** [comment]
As the author of the page, rather than figure out some elaborate new scheme to replace the colors there, I'm planning to remove the colors today. I'll revert back once it's done. Thanks for reaching out.

**Comment by alexcnichols** [comment]
The features timeline has been updated to be clear in the Dark theme too. 

![image](https://user-images.githubusercontent.com/19493383/42115796-54576828-7ba9-11e8-8f0b-5030b1285ba4.png)

**Comment by Powerhelmsman** [comment]
@alexcnichols Thanks for quickly fixing the issue. @supereddie Please double check the result. I will close the issue so far. If you have any other question related to the issue, we can reopen and continue the discussion.
