### ISSUE TITLE
Remove estimated read times from docs.microsoft pages

### ISSUE THREAD

**Issue by mairaw** [MicrosoftDocs/feedback#457]
Original GitHub issue from @edfallin at https://github.com/dotnet/docs/issues/6111

The estimated read times for docs articles are all absurdly low.  The effect is either to make a reader feel like an idiot because they can't read 1,000-plus words in 3 minutes **(!)**, or to make the reader suspect that it's all marketing to keep TL;DR-type people at the site.  Both bad.<p>

Instead of making these times more realistic, I suggest they be dropped completely, or that a click-once, cookie-after setting be arranged to hide them for those of us who are driven to distraction by them.<p>

I'm not complaining particularly about the _3-D Graphics Overview_, though it is a clear example of a reading time that is far too small.  Rather, I'm saying that **_all_** docs sites have bad estimated times.<p>

BTW, I regret that there's no more sensible place to register this complaint than here, but every other online avenue I tried led nowhere.<p>

**Comment by Powerhelmsman** [comment]
@ShevaDas Can you take a look at this suggestion?

**Comment by Powerhelmsman** [comment]
@log-suggestion @ShevaDas

**Comment by ShevaDas** [comment]
@edfallin Thanks for the feedback! Estimated reading time isn't something we're looking at removing at this time but we'll keep it in mind. I'll reopen this issue if we start to investigate changes.

**Comment by ShevaDas** [comment]
@edfallin I've opened a ticket with our engineering team to update the reading times to use a more accurate formula (probably something similar to [Medium's](https://blog.medium.com/read-time-and-you-bc2048ab620c)).

**Comment by edfallin** [comment]
Thanks, that's something.  Too bad they can't just be hidden and a cookie remembering it, you know?  It's not like they help anyone.
