### ISSUE TITLE
All "See also" refs on 'GetDlgItemInt function' page are unworkable

### ISSUE THREAD

**Issue by BugsDigger** [MicrosoftDocs/feedback#458]
**Link to article:**
GetDlgItemInt function
https://docs.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-getdlgitemint

**Problem:**
Scroll to "See also" section and click any reference.
Expected: appropriate page is opened.
Actually: "We're sorry, the page you requested cannot be found."

BTW, all items in "See also" can be succesfully found and opened with Google.

**Comment by dend** [comment]
@mijacobs do you happen to know who is the best person on the Windows content side who can help address this?

**Comment by GrantMeStrength** [comment]
The API docs have only _just_ been ported, and there are bound to be some issues. I will pass this onto the right team to investigate.

**Comment by ginami** [comment]
@BugsDigger--thank you for letting us know. Our team is working through issues with the content we recently moved to docs.microsoft.com and we'll have the problem fixed as quickly as we can.

**Comment by BugsDigger** [comment]
All refs are workable now except of one small thing: "Dialog Boxes" reference shows old msdn article with message: "The topic you requested is included in another documentation set. For convenience, it's displayed below. Choose Switch to see the topic in its original location." Also this "switch" does not work for me ("We're sorry, the page you requested cannot be found.").

**Comment by ginami** [comment]
Thanks @BugsDigger . The reference link fix is complete, and the switch option you mention above brings up two options-- one works and the other doesn't. Thank you for bringing this to our attention--we've added it to our migration issue list and will get it fixed when we can.

**Comment by keziamicro** [comment]
Hello - reviewing and cleaning up some older feedback/issues. Thanks!
