### ISSUE TITLE
Typo in article "CB_SETCURSEL message"

### ISSUE THREAD

**Issue by BugsDigger** [MicrosoftDocs/feedback#459]
**Link to article:**
CB_SETCURSEL message
https://docs.microsoft.com/en-us/windows/desktop/Controls/cb-setcursel

**Problem:**
1) In "Parameters" section: instead of "If this parameter is 1" must be "-1";
2) In "Return value" section: instead of "if wParam is 1" must be "-1".

 (Compare with https://msdn.microsoft.com/ru-ru/library/ms928526.aspx).

**Comment by dend** [comment]
@GrantMeStrength @mijacobs please take a look.

**Comment by ginami** [comment]
@msatranjr , can you please respond to this feedback? Thank you!

**Comment by mairaw** [comment]
This has been fixed. Closing.
