### ISSUE TITLE
Provide a landing page of consolidated product docs URL list and their related Github repo links

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#46]
Currently, the default landing page of docs.microsoft.com only list the products/frameworks/topics of the documentations. For example: the main landing page only list links of .NET docs, ASP.NET Core docs, EF, SQL Server, Azure.
As far as I know, the github repo of those topics/products are not maintained in a single locations or under a single organizations, they have their own different github repo under different organizations.
Unfortunately, there's no easy way to directly go to github link of the product/topic from landing page. For example: to know the Github repo of .NET docs, you have to select .NET on landing page first, then click Edit on any page inside the .NET docs. This goes the same for ASP.NET Core, and other topics/products as well.

----------
⚠ Idea migrated from UserVoice

**Created By:** Eriawan Kusumawardhono
**Created On:** 2017/12/22 04:31:23 +0000
**Votes at Migration:** 1
**Supporters at Migration:** 1

**Comment by Powerhelmsman** [comment]
Thanks for your feedback. I will bring this back to the team as suggestion.

**Comment by Powerhelmsman** [comment]
#log-suggestion

**Comment by botcrane** [comment]
🚀 **ATTENTION**: [Internal request](https://ceapex.visualstudio.com/web/wi.aspx?pcguid=7d644393-99ad-41c8-ac53-7fa79294c720&id=20993) logged.

**Comment by dend** [comment]
You can use the Edit button on pages that accept community contributions to get to the GitHub repository.
