### ISSUE TITLE
ComboBox_GetCurSel is documented as void

### ISSUE THREAD

**Issue by BugsDigger** [MicrosoftDocs/feedback#460]
**Link to article:**
https://docs.microsoft.com/en-us/windows/desktop/api/windowsx/nf-windowsx-combobox_getcursel
ComboBox_GetCurSel

**Problem:**
The document states that function returns nothing:

"void ComboBox_GetCurSel(hwndCtl);
...
Return Value
None"

But this is nonsense: how can Get function return ... nothing?..

In windowsx.h (quite old, "Copyright (c) 1992-1999, Microsoft Corp.") I see

#define ListBox_GetCurSel(hwndCtl)  ((int)(DWORD)SNDMSG((hwndCtl), LB_GETCURSEL, 0L, 0L))

where SNDMSG is actually SendMessage which returns required value.

The same issue with ListBox_SetCurSel which also is "void" according to documentation but as we know "CB_SETCURSEL message <...> returns the index of the item selected. If wParam is greater than the number of items in the list or if wParam is -1, the return value is CB_ERR".

As I can see in windowsx.h

#define ListBox_SetCurSel(hwndCtl, index)           ((int)(DWORD)SNDMSG((hwndCtl), LB_SETCURSEL, (WPARAM)(int)(index), 0L))

ListBox_SetCurSel returns value (as expected).

**Comment by dend** [comment]
@GrantMeStrength @mijacobs is there anyone on your team who can help here?

**Comment by ginami** [comment]
@TimShererAtAquent, can you please respond to this issue? Thanks!

**Comment by TimShererWithAquent** [comment]
We're looking into this. The original MSDN topic had an int return value. The docs.microsoft.com documentation shows it as void. This might be a migration issue or it might be an issue with how we parse the header files.

We should also keep an eye out for other issues like this.

**Comment by ginami** [comment]
Hi @BugsDigger--this is on our list of known migration issues. We don't have a fix yet, but I wanted to let you know that it is on our radar.

**Comment by keziamicro** [comment]
Hello - reviewing and cleaning up some older feedback/issues. Thanks!

**Comment by BugsDigger** [comment]
I see no changes on mentioned pages.
If you really think that GetXXX function should return nothing then "Closed" is correct status.
But IMHO this is utter nonsense.

**Comment by keziamicro** [comment]
@BugsDigger I `closed` this issue versus `won't fix `because it logged and moved to the team's internal backlog _(cannot link to it due to permissions issue)_ so that it can be triaged and prioritized. I've also emailed the specific team for extra awareness.

**Comment by jwmsft** [comment]
Thanks for raising this issue. I'll investigate what's happening with the bug and try to get some progress toward a resolution.
