### ISSUE TITLE
In section 'Queued & running' I did not see running builds

### ISSUE THREAD

**Issue by bayanistka** [MicrosoftDocs/feedback#461]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Build and release'
2. Click on 'Feature branch build'
3. In section 'Queued & running' I see 'No builds queued or running at the moment'
4. But, after refreshing this page I see, that there are running builds

https://screencast-o-matic.com/watch/cF1OjNFYn6

**Expected behavior**
When I click 'Feature branch build' I see the list of running builds
**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - Browser Google Chrome
 - Version 67.0.3396.87 (Official Build) (64-bit)

**Comment by dend** [comment]
@bayanistka is this related to any documentation on docs.microsoft.com?

**Comment by dend** [comment]
Given that we haven't heard anything for more than a week on this, I will close the issue. If we get more details, we will re-open.
