### ISSUE TITLE
Cipher command - What standard is Wipe run at

### ISSUE THREAD

**Issue by Ronsss** [MicrosoftDocs/feedback#463]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.
There is no "comment" or "feedback" (I don't think) on that page/ site

I have NEVER seen and reply to feedback I've submitted to other MS documentation! I've submitted a LOT.

**Link to article:**
https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-xp/bb490878(v=technet.10)

**Problem:**
The section about the /W (Wipe) parameter does not mention what security standard, if any, the wipe operates at, ie:
https://www.lifewire.com/dod-5220-22-m-2625856

**Comment by dend** [comment]
@mijacobs do you happen to know who on the Windows content site would be the best person to address this?

**Comment by mijacobs** [comment]
@dend @Powerhelmsman I'm not sure owns this documentation, and it looks like we no longer support it. Can you assign this back to triage? Thanks!

**Comment by Ronsss** [comment]
How can it not be supported. It is part of the command window commands.

as well this cipher page was last updated this year:
https://support.microsoft.com/en-us/help/814599/how-to-use-cipher-exe-to-overwrite-deleted-data-in-windows-server-2003

On Thu, Jun 28, 2018 at 4:44 PM, Mike Jacobs <notifications@github.com<mailto:notifications@github.com>> wrote:

@dend<https://github.com/dend> @Powerhelmsman<https://github.com/Powerhelmsman> I'm not sure owns this documentation, and it looks like we no longer support it. Can you assign this back to triage? Thanks!

**Comment by Powerhelmsman** [comment]
@Ronsss Thanks for your feedback. The article with previous-version in URL means we're no longer updating this content regularly. Author are focus on more up to date version. I find Gina to help follow up here. See if she can find someone has bandwidth to add it.

**Comment by ginami** [comment]
@Ronsss, thank you for taking the time to send us feedback. Unfortunately, at this time we don't have resources to update this page.

**Comment by Ronsss** [comment]
You don't have resources? With a market value of $760 BILLION you don't have resources?

If expect me to believe that I have some gold bricks I can sell you.  Corporately MS resources are effectively unlimited. No money ... really

On Fri, Jun 29, 2018 at 5:29 PM, Gina P. <notifications@github.com<mailto:notifications@github.com>> wrote:

@Ronsss<https://github.com/Ronsss>, thank you for taking the time to send us feedback. Unfortunately, at this time we don't have resources to update this page.

**Comment by Powerhelmsman** [comment]
@Ronsss I have to close this issue because author's team has no plan to fix it.
