### ISSUE TITLE
Dead link for sysinternals pdf

### ISSUE THREAD

**Issue by TomRuark** [MicrosoftDocs/feedback#464]
This link is not working:

https://docs.microsoft.com/en-us/sysinternals/opbuildpdf/toc.pdf?branch=live

**Comment by dend** [comment]
@TomRuark can you share the link for the content page where you got the PDF link?

**Comment by TomRuark** [comment]
https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/-memusage

**Comment by Powerhelmsman** [comment]
@TomRuark Do you mean the download PDF button? 
![image](https://user-images.githubusercontent.com/33136632/42054264-c16b73e6-7ac8-11e8-8619-da7ad7fc349e.png)
I can't repro the issue. On my side the download button works fine. Can you double check?

**Comment by TomRuark** [comment]
Yes. Working for me now. Thanks!

**Comment by JeffSmalley** [comment]
I am having an issues downloading as a PDF...   This issues seems to be a problem again...

https://docs.microsoft.com/en-us/sysinternals/

https://docs.microsoft.com/en-us/sysinternals/opbuildpdf/TOC.pdf?branch=live  

Using Windows 10 and tried IE, Edge and Chrome. All have the same issue..

Regards,
Jeff Smalley

**Comment by Powerhelmsman** [comment]
@dastaffo Can you take a look at this bug?

**Comment by dastaffo** [comment]
I'll track this one down.

**Comment by keziamicro** [comment]
Hello - reviewing and cleaning up some older feedback/issues. Thanks!
