### ISSUE TITLE
Wrong data in CB_FINDSTRING article

### ISSUE THREAD

**Issue by fyurisich** [MicrosoftDocs/feedback#465]
This page
https://docs.microsoft.com/es-es/windows/desktop/Controls/cb-findstring
says
If wParam is 1, the entire list box is searched from the beginning.
and I think it should be
If wParam is -1, the entire list box is searched from the beginning.
Thank you

**Comment by Powerhelmsman** [comment]
@GrantMeStrength @mijacobs please take a look.

**Comment by mijacobs** [comment]
Please assign this to @ginami--she triages our GitHub issues. Thanks!

**Comment by ginami** [comment]
@msatranjr, can you please respond to this feedback? Thank you!

**Comment by BissetJ** [comment]
See the related issues #853 and #1035 for many more pages with this same flaw.

**Comment by clandrew** [comment]
This looks to be a systemic issue rather than a few isolated instances. 
I don't have the right background to get into the wider issue, but as a temporary measure I've merged a PR which fixes all the instances that were reported in #853 and #1035 and the one in this issue.

**Comment by jwmsft** [comment]
Thanks for pointing out this bug. I'll investigate and try to get a resolution for the broader problem.

**Comment by keziamicro** [comment]
@jwmsft I'm closing this issue but feel free to reopen it when you have an update.
