### ISSUE TITLE
Typo on https://docs.microsoft.com/en-us/power-bi/guided-learning/exploringdata?tutorial-step=1

### ISSUE THREAD

**Issue by kasavin** [MicrosoftDocs/feedback#466]
There is a typo on this page:

https://docs.microsoft.com/en-us/power-bi/guided-learning/exploringdata?tutorial-step=1

"In the following topics, we'll explore the Power BI service, and show you how it can turn your business intelligence data into data insights and a collaborative decision-driving **envrionment**."

**Comment by Powerhelmsman** [comment]
@kasavin thanks for your finding. I created a pull request to change it. https://github.com/MicrosoftDocs/powerbi-docs-pr/pull/815 Let us wait it for several hours to merge the PR.

**Comment by dend** [comment]
The PR was merged to `master`, and will make it to `live` once the content team executes their regular content publish. Thanks for the suggestion, @kasavin!

**Comment by Powerhelmsman** [comment]
@kasavin the PR is merged. This issue is resolved. Please verify.
