### ISSUE TITLE
Pull the description from the articles into the 404 page

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/feedback#467]
**Is your feature request related to a problem? Please describe.**
When you hit a typo or dead page (EX: purposely added a 1) https://docs.microsoft.com/en-ca/vsts/pipelines/test/continuous-test-selenium1?view=vsts you get a nice 404 page with suggested corrections. In some cases this produces several titles that are the same or very similar.

**Describe the solution you'd like**
If the `description` metadata could be pulled into the suggestion results (like https://github.com/MicrosoftDocs/vsts-docs/blame/0d3078d52f0db50a48c77505297c4c315f470b55/docs/build-release/test/continuous-test-java.md) it may help users find the correct article

**Comment by Powerhelmsman** [comment]
@meganbradley Is this in your area?

**Comment by meganbradley** [comment]
@Powerhelmsman no, @ShevaDas is the PM for 404s

**Comment by ShevaDas** [comment]
@nschonni Thanks for the feedback! I'll look into it.

**Comment by ShevaDas** [comment]
#log-suggestion

**Comment by dend** [comment]
#log-suggestion @ShevaDas

**Comment by botcrane** [comment]
🚀 **ATTENTION**: [Internal request](https://ceapex.visualstudio.com/web/wi.aspx?pcguid=7d644393-99ad-41c8-ac53-7fa79294c720&id=29035) logged.

**Comment by dendeli-msft** [comment]
Thank you for the feedback! I've opened an internal issue for us to track.

At this time, we have no concrete timelines or commitments for this change, however we'll make sure that we do our due diligence in assessing the impact and importance of the feature.
