### ISSUE TITLE
Please create a search box on the blog page of power bi

### ISSUE THREAD

**Issue by glibnub** [MicrosoftDocs/feedback#47]
The Power BI page needs to be able to let me search the entire blog.  The current search box is only on the documentation page.

----------
⚠ Idea migrated from UserVoice

**Created By:** Collin
**Created On:** 2017/12/21 16:16:30 +0000
**Votes at Migration:** 1
**Supporters at Migration:** 1

**Comment by Powerhelmsman** [comment]
Thanks for the suggestion. Power BI blog is not in docs.microsoft.com site yet. @dend Do we have any plan to migrate Power BI blog site?
