### ISSUE TITLE
some docs lost

### ISSUE THREAD

**Issue by CaliforniaChao** [MicrosoftDocs/feedback#470]
# Idea Title

some docs lost

## Issue Details

https://docs.microsoft.com/zh-cn/windows/uwp/audio-video-camera/transcode-media-files#encode-a-metadata-stream

at the end of the page, "Encode a metadata stream“ part does not exist

**Comment by Powerhelmsman** [comment]
@CaliforniaChao Your issue is transferred to content team. They follow up with you there.
