### ISSUE TITLE
Add view + edit + copy usings to snippet links

### ISSUE THREAD

**Issue by SimonCropp** [MicrosoftDocs/feedback#472]
Currently docs has a "Copy" for snippets

![image](https://user-images.githubusercontent.com/122666/42006981-880bdaa8-7ac0-11e8-8806-f7cc37e8ce2e.png)

But there is more value that can be added to that context.

If you look here https://docs.particular.net/nservicebus/messaging/attachments-sql

Note the `Actions` button on the snippets:

![image](https://user-images.githubusercontent.com/122666/42006858-bcbfe236-7abf-11e8-9982-07a03f02ffe1.png)

it provides actions that are contextual to the snippet.

 * edit (online or local). See [Add edit local links](https://github.com/MicrosoftDocs/feedback/issues/473)
 * copy (usings or code):

![image](https://user-images.githubusercontent.com/122666/42006865-c68f021a-7abf-11e8-9018-ea9d4251356f.png)

Would be nice if MS docs had these

cc @mimig1 if u want to discuss on our call

**Comment by Powerhelmsman** [comment]
#log-suggestion

**Comment by botcrane** [comment]
🚀 **ATTENTION**: [Internal request](https://ceapex.visualstudio.com/web/wi.aspx?pcguid=7d644393-99ad-41c8-ac53-7fa79294c720&id=27624) logged.

**Comment by Powerhelmsman** [comment]
@ShevaDas Is this belong to your area?

**Comment by ShevaDas** [comment]
@Powerhelmsman @dend is the PM for samples.

**Comment by mimig1** [comment]
Thanks for the suggestion @SimonCropp!
