### ISSUE TITLE
Add edit local links

### ISSUE THREAD

**Issue by SimonCropp** [MicrosoftDocs/feedback#473]
Currently ms docs has edit. So on this page https://docs.microsoft.com/en-us/ef/core/ the edit links points to https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/index.md

But you can also use the `github-windows://openRepo/` prefix to open in [GitHub Desktop](https://desktop.github.com/)

So the above link would be 

```
github-windows://openRepo/https://github.com/aspnet/EntityFramework.Docs?branch=master&filepath=entity-framework%2Fcore%2Findex.md
```

If not cloned it will clone the repo, then open the code location in explorer.

if they dont have it installed. u can detect that it failed to open locally, and prompt them to install using js similar to 

```
    var elements = $("a[href*='github-windows://']");
    elements.click(function (e) {
        var subElement = $(this);
        var href = subElement.attr("href");
        timeout = setTimeout(function () {
            if (confirm("GitHub Desktop not installed.\nNavigate to download page?") === true) {
                window.location = "https://desktop.github.com/";
            }
        },
            5000);

        window.location = href;
        e.preventDefault();
    });
```

cc @mimig1 if u want to discuss on our call

**Comment by Powerhelmsman** [comment]
#log-suggestion @ShevaDas

**Comment by botcrane** [comment]
🚀 **ATTENTION**: [Internal request](https://ceapex.visualstudio.com/web/wi.aspx?pcguid=7d644393-99ad-41c8-ac53-7fa79294c720&id=27626) logged.

**Comment by Powerhelmsman** [comment]
@ShevaDas Can you take a look at this suggestion?

**Comment by svick** [comment]
You can already get to GitHub desktop from the GitHub page, so this would effectively be just about saving one click. Given that, do you still think this would be worth it?

**Comment by ShevaDas** [comment]
Thanks for the feedback, @SimonCropp! 

I'm not sure that this suggestion aligns with the ideal user experience. Many first timer contributors are unaware that clicking "Edit" will take them to GitHub to begin with, so adding additional layers of unexpected behavior may be more confusing than helpful. Additionally, editing in the browser is quicker and more accessible for everyone than prompting to open in/download GitHub Desktop. There are many cases in which users are unwilling or unable to install GitHub Desktop on their local machine. Finally, as @svick mentions, you can get to GitHub Desktop easily from the GitHub page.

I'll be closing this issue out as it's not something we plan to implement. Thanks again for the feedback, and don't hesitate to open new issues if you have more :)
