### ISSUE TITLE
Error PowerApps move fields

### ISSUE THREAD

**Issue by GozuDark** [MicrosoftDocs/feedback#474]
good afternoon, a few days ago I could move the fields in the form developed with powerapps, currently it is not possible. to. form of 2 columns. b. I tried disabling the automatic adjustment and did not solve the problem. Confirm if you have removed the functionality of freely moving through the fields form?

**Comment by Powerhelmsman** [comment]
@GozuDark This is a channel about Docs site related feedback and content issues. Can you go to PowerApps forum or search the answers? I will close it as no related to Docs site.
