### ISSUE TITLE
Scope tagging is broken in the search functionality

### ISSUE THREAD

**Issue by paddymcd-MSFT** [MicrosoftDocs/feedback#475]
**Describe the bug**
If the scope is set in the search URL e.g. &scope=Desktop it incorrectly returns zero results in more than one case

**To Reproduce**
https://docs.microsoft.com/en-us/search/index?search=GetTraceLoggerHandle&scope=Desktop 
returns no results

but https://docs.microsoft.com/en-us/search/index?search=GetTraceLoggerHandle returns many

when you click through to https://docs.microsoft.com/en-us/windows/desktop/etw/gettraceloggerhandle is reapplies the Desktop scope tag.

**Expected behavior**
Both queries should return links to at all relevant desktop documentation about this API - at the very least https://docs.microsoft.com/en-us/windows/desktop/etw/gettraceloggerhandle should be returned

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10, 17134_rs4_release
 - Browser Edge, FireFox
 - Version latest

**Comment by Powerhelmsman** [comment]
@presleyy Can you follow up this issue?

**Comment by Powerhelmsman** [comment]
@paddymcd-MSFT I can't repro this issue. When I click https://docs.microsoft.com/en-us/search/index?search=GetTraceLoggerHandle from result page, Scope tag didn't applied. I use Edge browser.

**Comment by paddymcd-MSFT** [comment]
No the tag isn't applied on the search results page, it is applied when you click through to the API documentation on https://docs.microsoft.com/en-us/windows/desktop/etw/gettraceloggerhandle - even if you simply navigate to the API doc page from a fresh session the tag will be applied in the search window.

But the bug is that with the tag you can't find items that appear to be tagged that way

**Comment by nschonni** [comment]
Here is another repro where the spaces/multiple tags results in now results.
1. Search for a result that exists in the docset, but not the current scope. EX: "agent" from https://docs.microsoft.com/en-ca/vsts/integrate/?view=vsts
1. This will offer the following search URL (with un-escaped spaces, Chrome seems to escape them, but still has no results) https://docs.microsoft.com/en-ca/search/index?search=agent&scope=VSTS,%20Visual%20Studio%20Team%20Services,%20TFS,%20Team%20Foundation%20Server
1. Replace other tags with just the single tag `VSTS` and results are returned https://docs.microsoft.com/en-ca/search/index?search=agent&scope=VSTS

Sorry, if this is actually a separate search bug but it sounded pretty similar to what I've seen

**Comment by presleyy** [comment]
@paddymcd-MSFT I tried the https://docs.microsoft.com/en-us/search/index?search=GetTraceLoggerHandle&scope=Desktop (with "Desktop" scope) at both Edge and Chrome. They work and have results returned.

These are what I saw:
![image](https://user-images.githubusercontent.com/5718438/42141134-b362dec4-7dd9-11e8-80df-397e2a526bbe.png)
![image](https://user-images.githubusercontent.com/5718438/42141164-d5ac6bee-7dd9-11e8-83eb-db1ea6b5e583.png)

Could you please try it again? Thanks.

**Comment by presleyy** [comment]
@nschonni the behaviors from my browser seems be different from your description.
1. I opened https://docs.microsoft.com/en-ca/vsts/integrate/?view=vsts, the scope at top right search box shows "Team Foundation Server".
2. I searched "agent" from that page with the scope. Then it turns to https://docs.microsoft.com/en-ca/search/index?**search=agent&scope=Team+Foundation+Server**. The scope is different from your description. And it returns search results.
![image](https://user-images.githubusercontent.com/5718438/42141311-f3d2c176-7dda-11e8-96b5-c4bbf9ba35ec.png)
3.  I changed the URL to make the scope to "VSTS". It also returned results.
![image](https://user-images.githubusercontent.com/5718438/42141348-31f72154-7ddb-11e8-9666-662dee38bb3e.png)

**Comment by nschonni** [comment]
@presleyy sorry, I'm taking about the search built into the right hand navigation rather than the global search
<img width="299" alt="screen shot 2018-07-03 at 12 33 37 am" src="https://user-images.githubusercontent.com/1297909/42198907-094cfc32-7e59-11e8-9804-be69499176cb.png">

**Comment by presleyy** [comment]
@nschonni thanks. That explains a lot and I reproduced the problem. I will file a bug for it.

**Comment by presleyy** [comment]
[Bug](https://ceapex.visualstudio.com/Engineering/_workitems/edit/28187) is created for tracking the fixing effort.

**Comment by presleyy** [comment]
The bug was fixed. @nschonni please let us know if you would still see any issue on such scope tagging. Thanks again!
![image](https://user-images.githubusercontent.com/5718438/42957633-2426387a-8b38-11e8-8bae-aee9a5959137.png)

**Comment by nschonni** [comment]
@presleyy I don't get the error anymore thanks!
It appears the fix was to just change everything to use the "Team Foundation Server" tag instead of the product (VSTS vs TFS) tag. It seems like multiple scopes don't work (or never did)

**Comment by presleyy** [comment]
@nschonni the multiple scopes currently is for defining the documents. If a document is defined for multiple scopes like A,B, and C. Searching with either scope would be able to find out that document. But current search action only supports having one scope. We understand that there could have needs to search out documents cross multiple scopes. This could be a new feature for our search engine.
