### ISSUE TITLE
Typos on description of MSDN licence types

### ISSUE THREAD

**Issue by OraDotNetDev** [MicrosoftDocs/feedback#476]
https://docs.microsoft.com/en-us/rest/api/vsts/memberentitlementmanagement/members/get?view=vsts-rest-4.1#accesslevel

Very minor typo on _Licence Type_ property  Description lists example licence types as  _**"... Visual Studio Profession, Visual Studio Enterprize"**_

No edit/comment option on the page for me to flag/update directly, as far as I could see?

**Comment by nschonni** [comment]
Looks like that is over on the MicrosoftDocs/vsts-rest-api-specs repo
https://github.com/search?q=org%3AMicrosoftDocs+Enterprize&type=Code

**Comment by EdisonDa** [comment]
@tedchamb would you want to fix the typo? Seems there are multiple pages for "Enterprize" issues.

**Comment by OraDotNetDev** [comment]
Ah right @EdisonDa + @tedchamb - I created a  [PR](https://github.com/OraDotNetDev/vsts-rest-api-specs/pull/1) have I done that correctly?

**Comment by EdisonDa** [comment]
Thank you @OraDotNetDev for your passion and contribution. Would you mind me to close this issue now? I believe the product team will review the PR and follow up with you.

**Comment by OraDotNetDev** [comment]
Sure no worries, happy to help :+1:

**Comment by tedchamb** [comment]
Unfortunately we can not take a PR for this fix, because the swagger is generated and the source of the text comes from code that is not yet open sourced.   I appreciate you pointing out the typo, and I will get this fixed up.

**Comment by Powerhelmsman** [comment]
@tedchamb Please inform us when the bug is fixed. I reopen the issue until it is truly fixed.
