### ISSUE TITLE
Missing documentation for System.IO.Pipelines.Pipe

### ISSUE THREAD

**Issue by pjmlp** [MicrosoftDocs/feedback#477]
Steps to reproduce,

1. Go to https://docs.microsoft.com/en-us/dotnet/api/
1. Type System.IO.Pipelines.Pipe
1. Documentation expected to be shown, nothing appropriate gets displayed

Documentation is available from third party blogs, https://blog.marcgravell.com/2018/07/pipe-dreams-part-1.html

**Comment by dend** [comment]
@mairaw @terrajobst @BillWagner I am assuming this is coming from a different NuGet package, that we haven't onboarded yet?

**Comment by mairaw** [comment]
apisof.net (https://apisof.net/catalog/System.IO.Pipelines.Pipe) indicates this is part of .NET Core + extensions, so yes.

**Comment by dend** [comment]
@mairaw thanks for the confirmation! This is likely part of the work that we have to do for hybrid content onboarding. I will leave this open for now, as that's something we know we need to work on.

**Comment by dend** [comment]
Documentation should [now be available](https://docs.microsoft.com/en-us/dotnet/api/?term=System.IO.Pipelines)!

![image](https://user-images.githubusercontent.com/1389609/47597140-e9e47d00-d940-11e8-991f-bdd12fd5185b.png)
