### ISSUE TITLE
Online help for Get-ChildItem returns 404

### ISSUE THREAD

**Issue by EGobi** [MicrosoftDocs/feedback#478]
**Describing the bug**
In PowerShell, running `Get-Help Get-ChildItem -Online` opens `https://docs.microsoft.com/en-us/powershell/module/4.0/microsoft.powershell.core/providers/FileSystem-Provider/Get-ChildItem-for-Filesystem` (404). This is a terrible UX for any newcomer.

**To reproduce**
1. Open PowerShell
2. Run `Get-Help -Get-ChildItem -Online`
3. See error

**Desktop:**
 - OS: Windows 10
 - Browser: Microsoft Edge
 - Version: 42.17134.1.0

**Comment by EdisonDa** [comment]
Hi @sdwheeler, I can repro with this steps. Looks like this is for PowerShell Core, let me know if you are not the right person to contact.

**Comment by sdwheeler** [comment]
This issue was moved to PowerShell/PowerShell-Docs#2647

**Comment by sdwheeler** [comment]
@EdisonDa I have moved this issue to the Docs repo. We will work it from there. Please close this issue.

**Comment by EdisonDa** [comment]
@EGobi would you mind me to close this one? I found the issue tracked in source repo is visible to you.

**Comment by EGobi** [comment]
Yes, please!
