### ISSUE TITLE
Broken Learn More Link (Cortana SDK)

### ISSUE THREAD

**Issue by maschmid-MSFT** [MicrosoftDocs/feedback#479]
Element Text: Learn More
Source: https://developer.microsoft.com/en-us/cortana/devices
Target: https://docs.microsoft.com/en-us/windows-hardware/design/device-experiences/cortana

The target location navigated to when I click the Learn More link on the source page is broken and leads to a 404.

maschmid@microsoft.com

**Comment by EdisonDa** [comment]
The page https://docs.microsoft.com/en-us/windows-hardware/design/device-experiences/cortana does not exist in docs, so the source page may need to update the proper link. @maschmid-MSFT , Mark, could you please follow up with Cortana team?

**Comment by EdisonDa** [comment]
@maschmid-MSFT could you please contact "Cortana" team to fix the issue on the site https://developer.microsoft.com/en-us/cortana/devices, we only handle the feedback for our Docs.
