### ISSUE TITLE
Improve cross-referencing

### ISSUE THREAD

**Issue by docs-product** [MicrosoftDocs/feedback#48]
The wealth of information in this library is hard to mine, as cross-referencing between pages is haphazard. I came up against this when trying to find out about asynchronous programming in VB. There are two trails: one in the .NET documentation (https://docs.microsoft.com/en-us/dotnet/standard/async) and one in the VB documentation (https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/concepts/async/) The former has links to the latter, but not the other way round. 

I agree that this is an almost impossible task - the number of potentially missing cross-references must run into the millions. It's possible someone could write a program which examines all of the pages, searches for cross-references and checks that reverse references are also present. I'm not volunteering!

May I suggest that when pages are added or modified their cross-referenced pages are examined to make sure that the reverse link also exists, or that there is a reverse link to a parent page (if you see what I mean).

----------
⚠ Idea migrated from UserVoice

**Created By:** PeterT
**Created On:** 2017/12/21 09:32:59 +0000
**Votes at Migration:** 1
**Supporters at Migration:** 1

**Comment by dend** [comment]
@mairaw @BillWagner @rpetrusha FYI on the ask.

**Comment by presleyy** [comment]
@dend is this something related to validation rules in OPS that we can add a cross-reference check rule? Add @meganbradley for idea

**Comment by dend** [comment]
I think this relates more to the idea that we generate good "See Also" links in documentation, to make sure that customers are never lost.

**Comment by presleyy** [comment]
That's a good point. I think generating "See Also" recommendation links might help. But from the way we design the recommendation model, we can't guarantee that all cross-referencing will be populated from the recommended articles, unless there really have many users view this and then view that. If cross-referencing check is a must have, still suggest putting something in validation rules.

**Comment by Powerhelmsman** [comment]
#log-suggestion @presleyy

**Comment by botcrane** [comment]
🚀 **ATTENTION**: [Internal request](https://ceapex.visualstudio.com/web/wi.aspx?pcguid=7d644393-99ad-41c8-ac53-7fa79294c720&id=22775) logged.

**Comment by docs-product** [comment]
We are constantly working to improve the discoverability of content. We'll ensure that as we design new experiences, we maintain proper links between content sets and related articles.
