### ISSUE TITLE
Broken link on "Azure for Java Developers" page

### ISSUE THREAD

**Issue by ksurendra** [MicrosoftDocs/feedback#480]
**Describe the bug**
The link to "Azure Libraries for Java" on page https://docs.microsoft.com/en-us/java/azure/?view=azure-java-stable is broken.

**To Reproduce**
1. Go to https://docs.microsoft.com/en-us/java/azure/?view=azure-java-stable
2. Click on "Azure Libraries for Java"
3. We can see a 404 - Page not found

**Expected behavior**
The page at https://docs.microsoft.com/en-us/java/api/overview/azure?view=azure-java-stable open with content and not a 404

**Screenshots**
![screen shot 2018-07-03 at 1 01 17 pm](https://user-images.githubusercontent.com/902972/42236709-405a94e2-7ec1-11e8-8e97-8d4321f10834.png)

**Desktop (please complete the following information):**
 - OS: Mac Os
 - Browser : All browsers
 - Version : latest

**Comment by EdisonDa** [comment]
@rloutlaw could you please take a look at this issues, seems the link for "Azure Libraries for Java" in hub page was out of date.

**Comment by dend** [comment]
We are currently investigating this issue.

**Comment by dend** [comment]
The fix is gated behind this PR: https://github.com/Azure/azure-docs-sdk-java/pull/525

**Comment by dend** [comment]
This has been addressed.
