### ISSUE TITLE
Broken link to "Read the full Azure SDK for Java documentation" on page https://azure.microsoft.com/en-us/develop/java/ 

### ISSUE THREAD

**Issue by ksurendra** [MicrosoftDocs/feedback#481]
**Describe the bug**
Broken link to "Read the full Azure SDK for Java documentation" on page https://azure.microsoft.com/en-us/develop/java/ 

**To Reproduce**
1. Go to https://azure.microsoft.com/en-us/develop/java/  
2. Scroll to the bottom of the page and click on "Read the full Azure SDK for Java documentation"
3. Will see a 404 error page

**Expected behavior**
Working page for the link "Read the full Azure SDK for Java documentation" 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser: All

**Comment by EdisonDa** [comment]
@rloutlaw Hi Robert, the link for Java Azure is out of date. We should update the link in azure.microsoft.com. Could you please assign this to proper person?

**Comment by dend** [comment]
Duplicate of #480
