### ISSUE TITLE
Allow me to sign in with Organisational account

### ISSUE THREAD

**Issue by calway** [MicrosoftDocs/feedback#483]
**Is your feature request related to a problem? Please describe.**
To comment on the Docs you have to sign in. But the Docs only allow me to sign in with a Microsoft account, I cannot use my Organisational account. This transition is going on for years and still a lot of services don't allow the Organisational accounts, please add this here as well

**Describe the solution you'd like**
Support Organisational accounts for Sign in

**Describe alternatives you've considered**
There is no alternative unless you count keep using any of the other account options, such as Microsoft account. 

**Additional context**
This would greatly help in phasing out old Microsoft accounts in favor of the Organisational accounts.

**Comment by dend** [comment]
Hello! Given that we are moving away from LiveFyre, this is not something that we will be implementing in the near-term. Content teams will switch to GitHub comments shortly, and once that is done, you will be able to authenticate with your standard GitHub credentials.
