### ISSUE TITLE
No search results for common classes

### ISSUE THREAD

**Issue by jsmarsch** [MicrosoftDocs/feedback#484]
**Problem:**
I cannot find many classes that used to be commonly searchable and easily found via google.

I went to the document search here: https://docs.microsoft.com/en-us/dotnet/api/?term=ActionFilter&view=netframework-4.7.2

Because I need help with WebAPI ActionFilter (I'm not using .net core)

The documentation simply doesn't exist:  No Results, unless I search under core, but I'm not using core.

![image](https://user-images.githubusercontent.com/3780199/42288522-a11f16c6-7f80-11e8-9524-1defe6d9b085.png)

**Comment by jsmarsch** [comment]
I like the new format of the doc browser, but it used to be that one of the coolest things about .net documentation was that if I just put the class name into google, the first or second hit would be the documentation for it.  

Nowadays, I have to search all over for the api docs.

**Comment by jsmarsch** [comment]
Pressing F-1 within Visual Studio leads me to the image below.  
Note:   the "no longer updated" message
Note: It's dos for VS 2013 (I'm using 2017)
Note: there is no version switcher option
Note: clicking "return to main site", just returns me to the home page for docs, where I do a search, and get the results that I posted into the description of the issue above.

![image](https://user-images.githubusercontent.com/3780199/42288688-641b07ac-7f81-11e8-8357-1bc0f87ff805.png)

**Comment by dend** [comment]
Thanks for the feedback, @jsmarsch - we are currently working on onboarding ASP.NET APIs to docs (see #90 for details).
