### ISSUE TITLE
Change dark colors

### ISSUE THREAD

**Issue by alferovvictor** [MicrosoftDocs/feedback#485]
Change dark colors:

background-color: #353131;
color: #8a93a0;

[https://ic.pics.livejournal.com/alferovvictor/57387100/160176/160176_original.png](https://ic.pics.livejournal.com/alferovvictor/57387100/160176/160176_original.png)

**Comment by ShevaDas** [comment]
Hi @alferovvictor—thanks for the feedback! We aren't looking at changing our dark theme colors at this time, but will keep your suggestion in mind for the future.
