### ISSUE TITLE
Not urgend: Username is shown wrong

### ISSUE THREAD

**Issue by Ka-Lai** [MicrosoftDocs/feedback#487]
**Describe the bug**
I logged in with my account. My firstname has a space in between. On top right, where the username is shown, I only see the first part of my firstname.

**To Reproduce**
1. Go to 'sign in'
2. Log in with username and password
4. See only the first part of firstname

**Expected behavior**
Your page take the first space to separate the name. That doesn't work with asian names, which have more than one space.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox 61.0

**Comment by Powerhelmsman** [comment]
@sharriexie Can you take a look at this suggestion?

**Comment by sharriexie** [comment]
@Ka-Lai ,

I'm PM of DOCS profile.
Thanks for reporting this.
A ticket is created internally to track this: 80363249.
I'll update this thread if there's any progress.

Regards,
Hui Xie

**Comment by sharriexie** [comment]
Hi @Ka-Lai ,

The problem is fixed.
Now we show full name instead.
Thanks again for reporting this to us.

Regards,
Hui Xie

**Comment by Ka-Lai** [comment]
Thanks for solving.
Have a nice day.
Kind regards
Ka Lai
