### ISSUE TITLE
s/maniacal/excited/ for phrase about inclusivity "for developers of all backgrounds"

### ISSUE THREAD

**Issue by celiala** [MicrosoftDocs/feedback#488]
Link: https://developer.microsoft.com/en-us/advocates/index.html

Phrase: "Our global team is **maniacal** about making the world amazing for developers of all backgrounds."

Issue: "maniacal" is an exclusionary term, which feels in conflict with the sentence being about inclusion for all developers, regardless of background (including mental illness).

More context:
For people with mental illness, they internalize the suggested meaning of the word “crazy” (or synonyms, like "maniacal") from the context that it’s used. If you would not feel comfortable using the meaning of the word in the context that you’re using it for someone who has mental illness, that’s a really good indication that you shouldn’t be using it in this context.

Alternative language to use instead:
Say what you mean! This is broad because “crazy” terms (or synonyms, like "maniacal") are used in a lot of different situations, but alternatives for this particular instance could be are wild, excited, ecstatic, etc.

Thank you! <3

**Comment by dend** [comment]
Thanks for the feedback, @celiala - I am following up with the team on this.

**Comment by Powerhelmsman** [comment]
@celiala Thanks for you feedback. The "maniacal" was changed to "focused on".  Please take a look.
