### ISSUE TITLE
Allow removal of "my feedback"

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#49]
Checking my feedback item, I click "My feedback". Now I want to see everyone's ideas, but there's no way of cancelling out the "my feedback" setting.

----------
⚠ Idea migrated from UserVoice

**Created By:** PeterT
**Created On:** 2017/12/19 19:31:51 +0000
**Votes at Migration:** 1
**Supporters at Migration:** 0

**Comment by dend** [comment]
@ShevaDas - is your team handling the UX for the feedback control?

**Comment by ShevaDas** [comment]
@dend I'm not sure which feedback system this is referring to. It's not the anonymous feedback control. Is it UserVoice or LiveFyre?

**Comment by Powerhelmsman** [comment]
@botcrane Can you give us more specific senario? which feedback are you referring to?

**Comment by dend** [comment]
@ShevaDas @Powerhelmsman actually, looking at this more, it's UserVoice related and I am closing this as Invalid.
