### ISSUE TITLE
wifi/bt enble disable interface can only work in X64

### ISSUE THREAD

**Issue by luohao1220** [MicrosoftDocs/feedback#490]
hi Microsoft，
Currently We use modern  Radio interface to enable/disable wifi/bt device, get wifi/bt status, monitor wifi/bt status change.
The Radio interface is work good in X64, but not ok in x86.
Is there any interface can support such function in x86? 
thanks

Modern::Windows::Devices::Radios:: Radio
Radio->SetStateAsync(RadioState::On)
Radio->SetStateAsync(RadioState::Off)
Radio->StateChanged(&Callback)
Radio->State()

**Comment by Powerhelmsman** [comment]
@luohao1220 This is a channel to raise question or feedback about Docs site and content instead of the general technical question. Are you referring to any doc site content page?

**Comment by luohao1220** [comment]
@Powerhelmsman ，
this is the doc site。
https://docs.microsoft.com/en-us/uwp/api/windows.devices.radios.radio.setstateasync

**Comment by Powerhelmsman** [comment]
@luohao1220 You issue is transferred to uwp team. They will help you there.
