### ISSUE TITLE
Issue about Text Services Framework

### ISSUE THREAD

**Issue by hjlpbbs** [MicrosoftDocs/feedback#491]
Hi !
I have two question to need your help !

Issue 1: When I use Text Services Framework in my software development，I find that it can only provide 10 candidates per page. I can not choose how many candidates per page by myself. Can you give me some method to solve the problem?
Issue 2: the  Microsoft input method show only 9 keyboard shortcuts of the candidates using number from 1-9 in keyboard, can you tell me the 10th candidate's keyboard shortcuts or provide some other suggestions ?

Thank you!

**Comment by Powerhelmsman** [comment]
@hjlpbbs This is a channel to raise question or feedback about Docs site and content instead of the general technical question. Are you referring to any doc site content page?

**Comment by hjlpbbs** [comment]
@Powerhelmsman 
this is the doc site：
https://docs.microsoft.com/en-us/windows/desktop/api/msctf/nf-msctf-itfcandidatelistuielement-getcurrentpage

**Comment by Powerhelmsman** [comment]
@ginami Can you take a look at this issue?

**Comment by ginami** [comment]
Hi @hjlpbbs -- thanks for your feedback. Unfortunately our document authors can't answer these questions. Please visit our Windows developer support page for support options: https://developer.microsoft.com/windows/support.
