### ISSUE TITLE
Many wingdi.h functions has one or more missing parameter descriptions

### ISSUE THREAD

**Issue by Derpalus** [MicrosoftDocs/feedback#493]
Examples:

- https://docs.microsoft.com/sv-se/windows/desktop/api/wingdi/nf-wingdi-getstockobject
- https://docs.microsoft.com/en-us/windows/desktop/api/wingdi/nf-wingdi-createdibsection
- https://docs.microsoft.com/sv-se/windows/desktop/api/wingdi/nf-wingdi-stretchdibits
- https://docs.microsoft.com/sv-se/windows/desktop/api/wingdi/nf-wingdi-createdibitmap
- https://docs.microsoft.com/sv-se/windows/desktop/api/wingdi/nf-wingdi-getenhmetafilebits
- https://docs.microsoft.com/sv-se/windows/desktop/api/wingdi/nf-wingdi-maskblt

I think that many if not all the wingdi.h functions has this issue of descriptions for parameters missing. You also often see the last part of the remarks section being turned into a window of source code for some reason.
Makes the documentation very hard to use.

**Comment by Powerhelmsman** [comment]
@ginami Can you help find a right person to fix the issue?

**Comment by ginami** [comment]
Hi @Derpalus -- thank you for the feedback! We've just recently migrated this content to the docs platform and we're still working through some issues. We'll get these issues resolved as soon as we can. Thanks again for letting us know.

**Comment by ginami** [comment]
Hi @Derpalus -- the TBDs on the pages you listed above have all been fixed. Thanks again for bringing this issue to our attention.
