### ISSUE TITLE
Incorrect rendering of an escaped pipe character inside a code block on a table

### ISSUE THREAD

**Issue by mairaw** [MicrosoftDocs/feedback#497]
Original GitHub issue https://github.com/dotnet/docs/issues/6335 from @HankiDesign

In the [Expressions](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/introduction#expressions) section, there's a table of C# operators with a rendering issue related to escaping the pipe character with a backslash.

<img width="687" alt="Incorrect pipe character rendering inside a table on Docs" src="https://user-images.githubusercontent.com/1816448/42350797-4b96487c-80b2-11e8-820b-c2808cd2ae49.png">

As seen on the above picture, pipe characters for the _Logical OR_ and _Conditional OR_ are escaped because they're inside a table. The same characters render correctly on GitHub as seen on the picture below:

<img width="894" alt="Correct pipe character rendering inside a table on GitHub" src="https://user-images.githubusercontent.com/1816448/42350890-bdcd6d62-80b2-11e8-87e8-5424c01135f6.png">

I assume that the problem occurs due to the escaped pipe characters residing inside a code block and Docs not supporting it properly.

**Comment by dend** [comment]
@TianqiZhang - would this be solved if we switch the `dotnet-api-docs` repo to MarkDig?

cc: @cillroy

**Comment by bannus** [comment]
My team also noticed this issue. GitHub's Markdown handles this correctly. The same markdown shows `URL1|URL2|URL3` on [GitHub](https://github.com/MicrosoftDocs/IntuneDocs/blob/master/intune/app-configuration-managed-browser.md#how-to-specify-allowed-and-blocked-urls-for-the-managed-browser) but shows `URL1\|URL2\|URL3` on [Microsoft Docs](https://docs.microsoft.com/en-us/intune/app-configuration-managed-browser#how-to-specify-allowed-and-blocked-urls-for-the-managed-browser). 

The following table should be a pretty minimal repro:

```
pipe|
-|
`\|`
```

pipe |
-|
`\|`

**Comment by cillroy** [comment]
This is a bug with Docs, markdig will not resolve the issue at this point.  I will get it filed with the markdig team to resolve.

**Comment by cillroy** [comment]
At this point, the solution is moving to markdig... as it will respect and render any content with a backtick " ` " verbatim... in the example below markdig will render the pipes correctly

| __Category__                     | __Expression__    | __Description__ |
|----------------------------------|-------------------|-----------------|
| Logical OR                       | `x | y`           | Integer bitwise OR, boolean logical OR   |
| Conditional OR                   | `x || y`          | Evaluates `y` only if `x` is `false`     |
