### ISSUE TITLE
Dark Mode color matches font on profile

### ISSUE THREAD

**Issue by dc995** [MicrosoftDocs/feedback#499]
**Describe the bug**

**To Reproduce**
1) Browse to https://docs.microsoft.com/en-us/profile
2) Login - use MSA or corp id microsoft.com
3) Click the drop down at profile

**Expected behavior**
You should be able to read the labels or words such as Logout etc but the font matches the background rendering it unreadable

**Screenshots**
![docbug](https://user-images.githubusercontent.com/2014485/42478203-d14a6b46-83a1-11e8-956d-08092f5f8fd5.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10, 1803
 - Browser: Microsoft Edge 42.17134.1.0
 - Version: Microsoft EdgeHTML 17.17134

**Comment by Powerhelmsman** [comment]
@sharriexie @ShevaDas  Can you take a look at this bug?

**Comment by ShevaDas** [comment]
I'll leave this one to @sharriexie :)

**Comment by sharriexie** [comment]
Update: the engineering team is working on this. @dc995

**Comment by sharriexie** [comment]
@dc995 , the problem is solved and deployed.
Thanks again for reporting this to us.
