### ISSUE TITLE
The translate is bad,I can help to improve the translation

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#5]
_No details provided._

----------
⚠ Idea migrated from UserVoice

**Created By:** Anonymous
**Created On:** 2018/03/02 20:15:29 +0000
**Votes at Migration:** 1
**Supporters at Migration:** 1

**Comment by dend** [comment]
Closing as there is no contact information or details. Translations can be improved via the standard Pull Request process for documentation that enables community contributions. For all other documentation, it's best to leave a comment under it for writers to address.
