### ISSUE TITLE
Redirect .NET API content from MSDN to docs.microsoft.com

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#50]
Move APIs from MSDN to docs.microsoft.com.

----------
⚠ Idea migrated from UserVoice

**Created By:** Anonymous
**Created On:** 2017/12/19 06:33:20 +0000
**Votes at Migration:** 1
**Supporters at Migration:** 1

**Comment by dend** [comment]
Currently working on this. Pages are not indexed, as we are still working on the MSDN redirection prep.

**Comment by Powerhelmsman** [comment]
@dend any update?

**Comment by dend** [comment]
**Update:** We are preparing to redirect content from MSDN to docs.microsoft.com in the coming weeks, so this issue will be resolved.

**Comment by dend** [comment]
⚠ NOTE: The process is currently underway!

**Comment by dend** [comment]
This has now been addressed - check out our blog post: https://docs.microsoft.com/en-us/teamblog/dotnet-content-migration

**Comment by yumetodo** [comment]
@dend link broken

**Comment by Powerhelmsman** [comment]
@yumetodo It works now.

**Comment by yumetodo** [comment]
![image](https://user-images.githubusercontent.com/10869046/46103131-0c348f00-c20b-11e8-9c8f-65761aba0928.png)

**Comment by Powerhelmsman** [comment]
@yumetodo please use this link https://docs.microsoft.com/en-us/teamblog/dotnet-content-migration

**Comment by svick** [comment]
@Powerhelmsman That link does not work for me:

![](https://user-images.githubusercontent.com/287848/46103524-5567ed00-c1d1-11e8-8b2d-ad62fea437ab.png)

**Comment by dend** [comment]
Hi folks - updated link: https://docs.microsoft.com/en-us/teamblog/dotnet-api-docs-migration
