### ISSUE TITLE
Dark Mode Transparent Graphics with black font become unreadable

### ISSUE THREAD

**Issue by dc995** [MicrosoftDocs/feedback#500]
**Describe the bug**
Transparent images with black font become unreadable with dark mode

**To Reproduce**
1. Go to [https://docs.microsoft.com/en-us/azure/iot-edge/how-to-ci-cd](url)

**Expected behavior**
Should be able to read legend and other text on the graphic

**Screenshots**
![darkimage](https://user-images.githubusercontent.com/2014485/42483297-ad7adc28-83ba-11e8-8d5d-e09e66b5f0e3.jpg)
See readable below
![lightimage](https://user-images.githubusercontent.com/2014485/42483300-b16016c8-83ba-11e8-90cb-a166c7c9bc0c.jpg)

**Desktop (please complete the following information):**
-OS: Windows 10, 1803
-Browser: Microsoft Edge 42.17134.1.0
-Version: Microsoft EdgeHTML 17.17134

**Comment by dend** [comment]
@kgremban @robinsh can you please take a look at this item?

**Comment by kgremban** [comment]
Image updated to have a white background instead of transparent in PR https://github.com/MicrosoftDocs/azure-docs-pr/pull/46371
