### ISSUE TITLE
Typo in URL text

### ISSUE THREAD

**Issue by nishanthmahe** [MicrosoftDocs/feedback#501]
Typo in URL text

Typo in URL text in the below mentioned site:

[https://docs.microsoft.com/en-us/xamarin/android/app-fundamentals/services/foreground-services](https://docs.microsoft.com/en-us/xamarin/android/app-fundamentals/services/foreground-services)

Screenshot attached:

![image](https://user-images.githubusercontent.com/29800673/42507472-f0e1d43c-8462-11e8-94da-36797eae22d8.png)

**Comment by Powerhelmsman** [comment]
@nishanthmahe Thanks for your feedback. I transferred it to Xamarin team. They will track and fix the typo there.
