### ISSUE TITLE
Hide/Collapse Menu Usability Feature Request

### ISSUE THREAD

**Issue by mattferderer** [MicrosoftDocs/feedback#503]
When reading the documentation, going through a tutorial especially, it would be nice to hide or collapse the menu on the left. It makes it easier to read, especially when increasing the font size.

Since you're using JQuery & have the layout setup nicely, it is easy for a developer reading it to just do $('#sidebar').hide() and $('#sidebar').show() so it's not a huge deal.

**Comment by Powerhelmsman** [comment]
@mattferderer thanks for your feedback. We had a similar feedback in queue already. Our team will track there. https://github.com/MicrosoftDocs/feedback/issues/167

**Comment by Powerhelmsman** [comment]
close as duplicate with #167
