### ISSUE TITLE
Provide a way to generally apply fixes to the publishing platform

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/feedback#504]
**Is your feature request related to a problem? Please describe.**
The working in the open stuff is :100: awesome. There are some common/machine fixable issues in the deployment process that I manually point out/fix, but I can be automated out of a (non)job 😜 
- BOMs in markdown docs that break GH page rendering
- Dead links. Working on (and mostly off) with @DavidAnson to put that into Markdownlint
- Document encoding issues (partially addressed in #362 but not pushed out to repos)
- Adding very light Markdownlint rules (that don't apply to styling)

**Describe the solution you'd like**
Provide a why to propose general publishing fixes to the "OpenPublishing" platform base used by all docs repos. I've found the NuGet package published accidentally before on NuGet and MyGet, and it seems like something that could accept community contributions (for the PowerShell parts).

**Describe alternatives you've considered**
There is a ton of internal i18n and server-side stuff that isn't ready for prime-time/general consumption but you're working on it ❤️ ❤️ ❤️ 

**Additional context**
I like poke at these repos when I'm not sleeping well, but I could be listening to an audiobook instead

**Comment by Powerhelmsman** [comment]
@dend can you take a look at this issue?

**Comment by DavidAnson** [comment]
Shoot me an email at work? I can probably send the code for a basic link checker rule in a week or so.

**Comment by nschonni** [comment]
@DavidAnson I'm still going to try an get the Markdownlint rule worked out (just got self-tripped by test first), but super happy if this gets sorted out here in parallel

**Comment by dend** [comment]
Thanks for the desire to help, @nschonni! Unfortunately, at this time, we are not yet ready to make the entire pipeline open. As you mentioned, there are a lot of moving parts that currently are simply not designed to work with systems outside docs.microsoft.com, and would be of little value in the open, given the volume of change that is happening and the overall dependency on internal tools. Select plugins are open-source, and can be accessed by the community not only on NuGet, but also on GitHub.

We can re-assess this ask in the future, however there are no immediate plans to open the entire platform.
