### ISSUE TITLE
Unrendered markdown in article

### ISSUE THREAD

**Issue by SujeathPareddy** [MicrosoftDocs/feedback#507]
**Link to article:**
https://docs.microsoft.com/en-us/windows/desktop/WinAuto/uiauto-uiautomationoverview

**Problem:**
Unrendered markdown.

`
[!Note]
The functions described in [Deprecated Control Pattern Functions](uiauto-entry-cpfunctions.md) and [Deprecated Node Functions](uiauto-entry-uianodefunctions.md) are deprecated. Instead, client applications should use the UI Automation COM interfaces described in [UI Automation Element Interfaces for Clients](uiauto-entry-uiautoclientinterfaces.md).
`

**Comment by Powerhelmsman** [comment]
@ginami Can you find author to modify it?

**Comment by ginami** [comment]
Hi @SujeathPareddy  -- thank you for your feedback! I think this problem is a result of the migration process; I'll confirm that is on our list of known migration issues.

**Comment by ginami** [comment]
Hi @SujeathPareddy -- this issue is now fixed. Thanks again for bringing it to our attention.

**Comment by SujeathPareddy** [comment]
Welcome!
