### ISSUE TITLE
Typo in Visual Studio 15.7.5 release notes.

### ISSUE THREAD

**Issue by robindegen** [MicrosoftDocs/feedback#509]
**Link to article:**
https://docs.microsoft.com/en-us/visualstudio/releasenotes/vs2017-relnotes#15.7.5

**Problem:**
```Exception block is optmized away causing a crash.```. Should be ```optimized```

**Comment by Powerhelmsman** [comment]
@robindegen Thanks for your feedback. One engineer is working on that, It will be fixed very soon.

**Comment by Powerhelmsman** [comment]
@robindegen The issue is fixed.
