### ISSUE TITLE
Image not loading on 'How to Create Cascading Menus with the ExtendedSubCommandsKey Registry Entry' page.

### ISSUE THREAD

**Issue by xenomancer** [MicrosoftDocs/feedback#510]
**Describe the bug**
The [How to Create Cascading Menus with the ExtendedSubCommandsKey Registry Entry](https://docs.microsoft.com/en-us/windows/desktop/shell/how-to-create-cascading-menus-with-the-extendedsubcommandskey-registry-entry#comments-container) page is not loading an image in the [Remarks](https://docs.microsoft.com/en-us/windows/desktop/shell/how-to-create-cascading-menus-with-the-extendedsubcommandskey-registry-entry#remarks) section.

**To Reproduce**
1. Go to [How to Create Cascading Menus with the ExtendedSubCommandsKey Registry Entry](https://docs.microsoft.com/en-us/windows/desktop/shell/how-to-create-cascading-menus-with-the-extendedsubcommandskey-registry-entry#comments-container)
2. Scroll down to the [Remarks](https://docs.microsoft.com/en-us/windows/desktop/shell/how-to-create-cascading-menus-with-the-extendedsubcommandskey-registry-entry#remarks) section
3. See missing image

**Expected behavior**
An image is expected to show up on the web page.

**Screenshots**
![capture10356](https://user-images.githubusercontent.com/1974682/42574001-98beae36-84eb-11e8-9bac-0996e489575e.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise v1803 b17134.137
 - Browser: Chrome
 - Version: 67.0.3396.99 (Official Build) (64-bit)

**Comment by Powerhelmsman** [comment]
@ginami Can you find the right person to fix it?

**Comment by ginami** [comment]
Hi @xenomancer -- thank you for your feedback! I think this problem is a result of the migration process; I'll confirm that is on our list of known migration issues.

**Comment by ginami** [comment]
Hi @xenomancer -- this issue is now fixed. Thanks again for bringing it to our attention.
