### ISSUE TITLE
DomainContext Class ValidateMethod Method page is missing

### ISSUE THREAD

**Issue by danielanywhere** [MicrosoftDocs/feedback#512]
In the System.ServiceModel.DomainServices.Client Namespace.DomainContext class page, clicking on the ValidateMethod method link is broken.

**Link to article:**
Base Page: https://docs.microsoft.com/en-us/previous-versions/dotnet/wcf-ria/ff422732(v%3dvs.91)
Broken Link: https://msdn.microsoft.com/en-us/library/m:system.servicemodel.domainservices.client.domaincontext.validatemethod(system.string%2csystem.collections.generic.idictionary%7bsystem.string%2csystem.object%7d)(v=VS.91)

**Problem:**
Broken link to member.

**Comment by Powerhelmsman** [comment]
@danielanywhere Thanks for your feedback. Unfortunately, the content is no longer updating due to out of product lifecycle.
