### ISSUE TITLE
Including Mono in the .NET API Browser

### ISSUE THREAD

**Issue by polarapfel** [MicrosoftDocs/feedback#513]
Hi there,

I love the .NET API browser at https://docs.microsoft.com/en-us/dotnet/api/,

Unfortunately, it does not expose APIs from Mono. That's a real shame!

thanks,

Tobias W.

**Comment by Powerhelmsman** [comment]
@dend @mairaw Can you take a look this requirement?

**Comment by joelmartinez** [comment]
Hi @polarapfel ... can you give me a few extra details on which Mono APIs you're referring to? Do you mean the BCL APIs that Mono ships?

**Comment by polarapfel** [comment]
@joelmartinez This: http://docs.go-mono.com/

**Comment by joelmartinez** [comment]
@polarapfel ahh I see. Revamping the Mono API docs browser using the same open open source tools that power docs.microsoft.com is definitely on the roadmap. 

Though I don’t have an exact ETA, it’s a big goal ... so stay tuned!

**Comment by dend** [comment]
Given that there are no immediate plans to address this, I am going to close the item for now. @polarapfel thank you for the feedback and we appreciate your patience as we work through all of the existing content!

**Comment by RevZero** [comment]
Since this issue has been closed as "won't fix" for over a year, I assume this is permanent? Just asking because it was commented with "going to close the item **for now**". @dend
