### ISSUE TITLE
Console goes to bing search

### ISSUE THREAD

**Issue by j0hnsm1thj4cks0n** [MicrosoftDocs/feedback#514]
https://docs.microsoft.com/en-us/windows/desktop/apiindex/windows-api-list

Under the windows environment shell when you click consoles the link goes to a bing search.. is this expected?

**Comment by Powerhelmsman** [comment]
@ginami Can you find the right person to answer?

**Comment by ginami** [comment]
Hi @j0hnsm1thj4cks0n -- I'll find an author to look into this. Thank you for the feedback!

**Comment by ginami** [comment]
Hi @j0hnsm1thj4cks0n -- the link is fixed! Thanks again for letting us know about this issue.
