### ISSUE TITLE
'Try it' for for Graph RBAC is acquiring token from wrong source

### ISSUE THREAD

**Issue by RobCannon** [MicrosoftDocs/feedback#515]
**Describe the bug**

**To Reproduce**
1. Go to 'https://docs.microsoft.com/en-us/rest/api/graphrbac/applications/list'
2. Click on 'Try It'
3. Sign in
4. Enter a valid tenant id
5. Click Run
6. See error:
```
{
  "odata.error": {
    "code": "Authentication_MissingOrMalformed",
    "message": {
      "lang": "en",
      "value": "Access Token missing or malformed."
    },
    "date": "2018-07-12T01:08:12",
    "requestId": "27d9f790-d642-430b-8d46-892654731fa4",
    "values": null
  }
}
```

**Expected behavior**
The Body should contain a list of application from Azure AD

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge and Chrome

**Additional context**
If you decode the token, you will see this in the header:
```
"aud": "https://management.core.windows.net/",
```

The token should be acquired from https://graph.windows.net

**Comment by dend** [comment]
@hellosnow to investigate.

**Comment by hellosnow** [comment]
I opened one bug to track, our engineering team will help there.

**Comment by hellosnow** [comment]
@Powerhelmsman @dend please help to triage the issue and find the right assignee in case you miss it 😄

**Comment by dendeli-msft** [comment]
Looks like this page is no longer available. @RobCannon - can you update this issue with the link to the page that you intended to use "Try It" on?

**Comment by RobCannon** [comment]
It looks like the "Try It" feature is no longer in docs.  Sorry to see it go, it would have been useful. I guess I will close the issue.
