### ISSUE TITLE
"Azure DevOps Project for AKS" URL redirects to 404-Content/Page Not Found

### ISSUE THREAD

**Issue by SunnyOswal** [MicrosoftDocs/feedback#516]
"Azure DevOps Project for AKS" URL redirects to 404-Content/Page Not Found

**To Reproduce**

1. Go to 'https://docs.microsoft.com/en-us/azure/aks/'
2. Click on 'How-to guides'
3. Under that click on "DevOps on AKS"
4. Under that click on "Azure DevOps Project for AKS"

URL Broken:
https://docs.microsoft.com/en-us/vsts/pipelines/actions/azure-devops-project-aks?toc=%2Fen-us%2Fazure%2Faks%2FTOC.json&bc=%2Fen-us%2Fazure%2Fbread%2Ftoc.json

**Expected behavior**
Url loads fine.

**Desktop (please complete the following information):**
 - OS: windows
 - Browser: chrome

**Comment by Powerhelmsman** [comment]
@SunnyOswal Thanks for your feedback. Your issue is transferred to Azure team. They will help you there.
