### ISSUE TITLE
No Content for SharePoint

### ISSUE THREAD

**Issue by eugene-palacios** [MicrosoftDocs/feedback#517]
There's no content for SharePoint 

![image](https://user-images.githubusercontent.com/14924565/42626652-74de634a-85fd-11e8-92af-4811da68a9a8.png)

**Comment by Powerhelmsman** [comment]
@presleyy Is this by design?

**Comment by presleyy** [comment]
This is .NET API browser, add @dend

**Comment by dend** [comment]
We are investigating this, thanks for the feedback!

**Comment by littlejon** [comment]
Hi Guys, also missing all of the Microsoft.SharePoint.Client and Microsoft.Online.SharePoint.Client.Tenant namespaces for the Client-Side Object Model.

Is there a way to access the content on MSDN without it redirecting to the new API Browser?

Kind regards

**Comment by Webtyven** [comment]
Thanx

**Comment by dend** [comment]
We've added the SharePoint Server APIs, and are working on making sure others are showing up as well.

**Comment by fowl2** [comment]
[CSOM content](https://msdn.microsoft.com/en-us/library/microsoft.sharepoint.client.listitem.aspx) now appears to redirecting to [Sharepoint PnP content](https://docs.microsoft.com/en-us/dotnet/api/microsoft.sharepoint.client?redirectedfrom=MSDN&view=sharepointpnpcoreonline-2.18.1709.0) instead. (they are not equivalent)

**Comment by dend** [comment]
The Server APIs should be available. We are investigating why other APIs are not yet available.

**Comment by dend** [comment]
Following up with the engineers on the work - looks like some redirects were setup incorrectly.

**Comment by VesaJuvonen** [comment]
We are aware of this issue and redirection has been now moved to get access to the old content. There are unfortunate delays in getting SP2013, SP2016, SP2019 and SP Online CSOM reference APIs to the new platform, but we are working on it.

**Comment by brannmar** [comment]
Any update regarding this issue? Still experiencing redirects...

**Comment by dend** [comment]
The content for SharePoint Server is [now available](https://docs.microsoft.com/en-us/dotnet/api/?view=sharepoint-server). All other redirections are in the process of being rolled back until we can offer a high fidelity experience on docs.microsoft.com.
