### ISSUE TITLE
Incorrect escaping of ampersands in the code samples

### ISSUE THREAD

**Issue by alegrigoriev** [MicrosoftDocs/feedback#519]
**Describe the bug**
Ampersand characters in the code samples are shown as escaped characters: "&amp;amp;". At the same time, "less" and "greater" characters are shown correctly/

**To Reproduce**
1. Go to 'https://docs.microsoft.com/en-us/windows/desktop/gdi/scaling-an-image' (pretty much any page)
3. Scroll down to 'a code sample.

**Expected behavior**
Ampersand characters must be shown as is

**Screenshots**
<img width="414" alt="capture" src="https://user-images.githubusercontent.com/27784853/42639373-b89c1180-85a4-11e8-9412-bc535a80cc36.PNG">

**Desktop (please complete the following information):**
 - Windows 10
 - Browser: Chrome, IE 10

**Comment by Powerhelmsman** [comment]
@alegrigoriev Thanks for your finding.  @misatran @ginami can you take a look at this issue?

**Comment by ginami** [comment]
Hi @alegrigoriev -- thank you for your feedback. I believe this is a migration issue; I'll confirm that this is on our list of known migration issues.

**Comment by ginami** [comment]
Hi @alegrigoriev -- this issue is now fixed. Thanks again for brining it to our attention.
