### ISSUE TITLE
Trust Centre is not coming up on well selecting the Trust Centre button

### ISSUE THREAD

**Issue by Crlangfo** [MicrosoftDocs/feedback#521]
**Describe the bug**
Trust Centre is not coming up on well selecting the Trust Centre button

**To Reproduce**
1. Go to 'https://docs.microsoft.com/en-us/dynamics365/ '
2. Click on 'Trust Centre.'
3. See error "No Page"

**Expected behavior**
Trust Centre to show

**Comment by dend** [comment]
@Crlangfo can you please point us to the exact button you have in mind?

**Comment by Powerhelmsman** [comment]
@Crlangfo Trust Center works well. We can't repro the issue. I will close it so far. We can reopen it if you have other question related to it.
