### ISSUE TITLE
I could not find the API for Project Server 2010

### ISSUE THREAD

**Issue by parthrawal** [MicrosoftDocs/feedback#524]
# Idea Title

Project Server 2010 API, does not come in search

## Issue Details

even if i try google search and i can see the link and documentation in preview, i am continuously being redirect to unified API page, which is not working and i cant seems to find Resource.asmx, CustomField.asmx etc.

**Comment by dend** [comment]
The .NET API for Project Server is [available here](https://docs.microsoft.com/en-us/dotnet/api/microsoft.office.interop.msproject?view=office-project-server).
