### ISSUE TITLE
Can't find content of e.g. Microsoft.Office.Server.Search.Administration namespace in docs; missing from migration from msdn?

### ISSUE THREAD

**Issue by franzmiltner** [MicrosoftDocs/feedback#525]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

**Link to article:**
https://msdn.microsoft.com/library/Microsoft.Office.Server.Search.Administration.SearchServiceApplication.aspx

**Problem:**
When I search for e.g. SearchServiceApplication with a search engine, I still find the link above. When clicking I get redirected to the new .Net API browser, but when I search there for SearchServiceApplication it just shows "no results"

**Comment by Powerhelmsman** [comment]
@dend Can you take a look at this issue?

**Comment by parthrawal** [comment]
It has become extremely difficult to search the Project Online Content/Documentation for reference. It's almost non working and Project Server Category Leads to MSProject Documentation which is totally wrong. How MS can do such a stupid thing is beyond my comprehension

**Comment by dend** [comment]
We have removed the bad redirects temporarily, until a better solution is available.
