### ISSUE TITLE
Bring back the old MSDN, your new API Browser search sucks, it is UNUSABLE (slow and no significant results)

### ISSUE THREAD

**Issue by frevds** [MicrosoftDocs/feedback#527]
Seriously, I have no further comments - the whole MSDN is just gone for good. 
The next time you try to reinvent a search engine do that as an alternative. 
Google works, but all links are broken, so MSDN is effectively dead for me. I'll have to go to find the content in the web archive. 
No opt-in, no opt-out, no or not enough testing, just dumb switching to a new system without respecting the user's preferences? Harsh words are not enough to punish you for that move.

**Comment by dend** [comment]
@frevds could you please add more info about the APIs that you are searching?

**Comment by frevds** [comment]
In my case it's SharePoint, which (I know by now) is missing, but this is not the point of this issue. 
The issue is, that you broke a perfectly functional solution which was not just some thing under your control but a major resource on the web, and replaced it by something on force. I DO NOT WANT your new solution, why are you _forcing_ me to use a new API browser? Where is my opt-out? At least I want to be given a choice to use the old site while your new site is suboptimal. This same pattern of subpar renewal of software is already annoying enough to have with all Windows 10 apps where a new generation of inexperienced developers seem to know it better and destroy my productivity.

**Comment by chaselal** [comment]
I can't find any documentation on reactive extensions (Rx) with the new API browser. Searching for [System.Reactive](https://docs.microsoft.com/en-us/dotnet/api/?term=system.reactive) produces no results. System.Reactive was well-documented in the old MSDN pages.

**Comment by dend** [comment]
@frevds we are working on ensuring content redirects work properly - our team is currently in the process of putting the correct redirects in place.

**Comment by prasadu-microsoft** [comment]
Related to this: Try searching for something as basic as Enumerable.Except in the top search. Even scoped to .NET it returns irrelevant results (note the scope query parameter that's automatically added):
https://docs.microsoft.com/en-us/search/index?search=Enumerable.Except&scope=.NET. This returned no relevant results in the first page.

**Comment by dend** [comment]
@prasadu-microsoft Regarding search in the site search, this is covered by #50.

@svick we are tracking that request with #583.

@frevds closing this issue as the original issue was addressed. We are gradually moving content to docs.microsoft.com and have accidentally enabled redirects before the full content migration is complete. That is work in progress, and we will enable the redirects again once the content makes it over. Thanks for the feedback!
