### ISSUE TITLE
Can not find "CalendarCreationInformation" from Unified API Page

### ISSUE THREAD

**Issue by parthrawal** [MicrosoftDocs/feedback#528]
**Describe the bug**
CalendarCreationInformation

**To Reproduce**
1.https://www.google.co.in/search?ei=HZVNW5PrNYz0vgTpl7XgDw&q=%22CalendarCreationInformation%22&oq=%22CalendarCreationInformation%22&gs_l=psy-ab.3..35i39k1.2772260.2772860.0.2773344.3.3.0.0.0.0.440.440.4-1.1.0....0...1.1.64.psy-ab..2.1.439....0.2sDICJFGdaE
2. Click on first link
3. Redirects to Unified API Page
4. When we put "CalendarCreationInformation" for Project Online, Nothing comes

**Expected behavior**
Link should come for the "CalendarCreationInformation" documentation

**Comment by Powerhelmsman** [comment]
@dend Can you take a look at this issue?

**Comment by dend** [comment]
This is addressed for now - we removed the bad redirect.
