### ISSUE TITLE
No return type for RouteValueDictionary.GetEnumerator 

### ISSUE THREAD

**Issue by svick** [MicrosoftDocs/feedback#529]
**Describe the bug**

[The API reference page for `RouteValueDictionary.GetEnumerator`](https://docs.microsoft.com/en-us/dotnet/api/system.web.routing.routevaluedictionary.getenumerator?view=netframework-4.7.2) does not show its return type in the Returns section.

**Screenshots**

![](https://user-images.githubusercontent.com/287848/42834635-77c0f494-89f7-11e8-9917-f68aee894d83.png)

Compare this with e.g. [`Dictionary<TKey,TValue>.GetEnumerator`](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.dictionary-2.getenumerator?view=netframework-4.7.2), which shows the return type correctly:

![](https://user-images.githubusercontent.com/287848/42834673-95221874-89f7-11e8-9848-da983ef2eb85.png)

**Comment by dend** [comment]
@TianqiZhang are we missing anything in the data model that we need to investigate? looks like the data is in the XML.

**Comment by dend** [comment]
#log-suggestion @dend

**Comment by botcrane** [comment]
🚀 **ATTENTION**: [Internal request](https://ceapex.visualstudio.com/web/wi.aspx?pcguid=7d644393-99ad-41c8-ac53-7fa79294c720&id=36139) logged.

**Comment by dend** [comment]
This is now addressed, and the return type is properly displayed. Thank you for the feedback, @svick!
