### ISSUE TITLE
Add a floating horizontal scrollbar to code

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#53]
When a page contains a segment of code that is longer than the page the end of the page is outside the window, then the horizontal scrollbar (for the code segment) is also outside the window.
It would be handy to have a floating scrollbar at the bottom of the page in this case.

----------
⚠ Idea migrated from UserVoice

**Created By:** Dirk Jan D.
**Created On:** 2017/12/14 12:20:01 +0000
**Votes at Migration:** 1
**Supporters at Migration:** 1

**Comment by Powerhelmsman** [comment]
Can't repo. Do you have any example page?

**Comment by dend** [comment]
Closing as this has been addressed with the new template and horizontal scrolling.
