### ISSUE TITLE
Microsoft.SharePoint.Client missing classes

### ISSUE THREAD

**Issue by jspadeaMH** [MicrosoftDocs/feedback#531]
Can't find the File class in Microsoft.SharePoint.Client namespace
Google caches have the info but clicking on the search results redirects you to a generic page with no info.
Searching using the API browser returns no results

To reproduce:
Search the API browser for Microsoft.SharePoint.Client.File does not find the class
Search the API browser for Microsoft.SharePoint.Client.File.MoveToUsingPath finds no results at all

MicrosoftDocs is not ready for production, stop the redirects from TechNet please!!!!!!!

**Comment by Powerhelmsman** [comment]
@jspadeaMH Thanks for your feedback. This is a known issue, we will track it on #517. I will close it as duplicated.
