### ISSUE TITLE
Could review.docs.microsoft.com become public? 

### ISSUE THREAD

**Issue by mairaw** [MicrosoftDocs/feedback#533]
Original GitHub issue https://github.com/dotnet/docs/issues/1827 from @svick 

As far as I can tell, CI in this repo publishes each PR to https://review.docs.microsoft.com/, where it presumably looks the same as it will look on https://docs.microsoft.com/. This would be especially useful, since building with `docfx` locally has issues (the template is very different; getting API reference right is hard; it's slow).

But, it's not accessible to me (and I assume everyone else outside MS): when I try to access it, I get a 403 error (after logging in).

A recent example where I would use this are [changes to package.md](https://github.com/dotnet/docs/pull/1825/files#diff-d250c069c8de97e94a2a93f8feef136c) in https://github.com/dotnet/docs/pull/1825. I suspect it has issues, but it's hard for me to check, since I can't access https://review.docs.microsoft.com/en-us/dotnet/articles/core/packages?branch=pr-en-us-1825 (I found the URL in [the publicly accessible CI log](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C3%5C30%5Ca3bda507-3390-de91-8f7f-26f90f4e5fc8%5CPullRequest%5C201703300314080611-1825%5Cworkflow_report.html)).

Another reason why this is annoying is that CI sends emails to the PR author, containing links to https://review.docs.microsoft.com/, effectively saying "hey, come check that your PR looks okay", which the author is unable to do, if they are not from MS.

Since I don't see any reason for this limitation (all the information in the PRs is public anyway), could https://review.docs.microsoft.com/ become public?

**Comment by Powerhelmsman** [comment]
@mairaw @svick Thanks for you feedback. After discussed with the team, 1) we do have a future roadmap item to figure out a way to review a PR from a non-Microsoft user that doesn’t require an @microsoft.com address.  2) We’ll look at adding messaging to the PRs to warn people that the review links will not work for them at this time.

**Comment by Gnbrkm41** [comment]
Wonder if there was any progress to this? Being able to verify changes would be great since we don't have ways to check the pages until the PR is merged and the changes are reflected to the website.
