### ISSUE TITLE
Typo on web page for Power BI REST APIs 

### ISSUE THREAD

**Issue by hugotoledo** [MicrosoftDocs/feedback#535]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.
There is no comment section on the page where this defect exists.

**Link to article:**
https://docs.microsoft.com/en-us/rest/api/power-bi/ 

**Problem:**
This word is misspelled: 

> administation

It should be 

> administration

**Comment by Powerhelmsman** [comment]
@hugotoledo Thanks for your feedback. I submitted a PR to correct. It should be merged very soon.

**Comment by Powerhelmsman** [comment]
@hellosnow Do you have permission to merge the PR? https://github.com/MicrosoftDocs/powerbi-rest-api-docs-pr/pull/13 .

**Comment by hellosnow** [comment]
@Powerhelmsman I merged the PR, and this issue could be closed.
