### ISSUE TITLE
Azure-All Translator Speech API link returns a 404

### ISSUE THREAD

**Issue by JonathanPalmerGD** [MicrosoftDocs/feedback#536]
**Describe the bug**
When you click [Translator Speech API] option, it takes you to a non-secure blue 404 page.

**To Reproduce**
1. Go to https://docs.microsoft.com/en-us/azure/#pivot=products&panel=all
2. Click on [Translator Speech API]
3. Get a 404 page. that is not secure (which might give a Chrome/other 'dont go here' page)

**Expected behavior**
Getting to the documentation.

**Screenshots**
![404error](https://user-images.githubusercontent.com/2644214/42963623-984c46ac-8b49-11e8-8833-e4ffc099f9e6.PNG)

**Desktop (please complete the following information):**
 - OS: Win 10 Enterprise: Build 17134
 - Browser Chrome
 - Version [67.0.3396.99]

**Additional context**
The URL: https://docs.microsofttranslator.com/speech-translate.html returns a 404.

**Comment by Powerhelmsman** [comment]
@JonathanPalmerGD Thanks for your feedback. Your issue is transferred to Azure content team. They will help you there.
