### ISSUE TITLE
&20 rather than %20 in example request

### ISSUE THREAD

**Issue by Pharabus** [MicrosoftDocs/feedback#537]
https://docs.microsoft.com/en-ca/rest/api/maps/search/getsearchaddressstructured

&20 is used to represent spaces in the example request rather than %20

**Comment by Powerhelmsman** [comment]
@hellosnow Can you take a look at this issue?

**Comment by hellosnow** [comment]
@Pharabus thanks for your feedback, I'm connecting Azure Maps team to improve the examples.

**Comment by chgennar** [comment]
I can fix this, thanks for the feedback!

**Comment by Pharabus** [comment]
just to add detail, below is the example request, you can see streetName is including &20 where %20 woul d be more appropriate, you still get results using this but as streetName is excluded in the query it is less precise, the response example reflects the lack of streetName in teh query (Thats how I stumbled on it, my query that correctly used %20 returns a specific single response unlike the example response)

GET https://atlas.microsoft.com/search/address/structured/json?subscription-key=[subscription-key]&api-version=1.0&countryCode=US&streetNumber=15127&streetName=NE**&20**24th**&20**Street&municipality=Redmond&countrySubdivision=WA&postalCode=98052

**Comment by Powerhelmsman** [comment]
@Pharabus The issue is resolved.
