### ISSUE TITLE
please archive draft version article

### ISSUE THREAD

**Issue by TakiyaNakano-MSFT** [MicrosoftDocs/feedback#538]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

**Link to article:**
https://docs.microsoft.com/ja-jp/dynamics365/customer-engagement/admin/security-roles-automatically-assigned-apps

**Problem:**
This article is Japanese translated version, and English original version is missing. Moreover, English article was draft version and it was translated to Japanese unintentionally. Therefore, Japanese version should be archived.

**Comment by Powerhelmsman** [comment]
@TakiyaNakano-MSFT Thanks for your feedback. @SonjaSaltzman Can you take a look at this issue?

**Comment by SonjaSaltzman** [comment]
@krisre @vinceno This is an Issue related to Dynamics content; could you please follow up?

**Comment by krisre** [comment]
Removed now for all languages.
