### ISSUE TITLE
Xamarin doc - gyroscope spelled gyrpscope

### ISSUE THREAD

**Issue by Pooglz** [MicrosoftDocs/feedback#539]
gyrpscope >> gyroscope
axis >> axes. 

https://docs.microsoft.com/en-us/dotnet/api/xamarin.essentials.gyroscope

_Gyrpscope data of the rotation around the device's three primary axis._

should be

Gyroscope data of the rotation around the device's three primary axes.

**Comment by Powerhelmsman** [comment]
@Pooglz Thanks for you feedback. I submitted a PR to fix it. Let us wait for merger.

**Comment by Powerhelmsman** [comment]
@Pooglz The issue is fixed.
