### ISSUE TITLE
Move the "Is this page useful" to the top and show up/down ratio

### ISSUE THREAD

**Issue by user135711** [MicrosoftDocs/feedback#542]
If you go to docker's documentation you can see the number of thumbs up and thumbs down. It would be very useful if the thumbs up vs down ratio was displayed at the top of all ms docs, kind of like stack exchange voting. In the documentation some of the documents are extremely useful and have to be read word for word, while others are extremely long and wordy but contain no useful information. It might save time if you could look at the top to see which to skip and which to read since there are tens of thousands of pages in the docs and no time to read all of it.

**Comment by Powerhelmsman** [comment]
@user135711 Thanks for your feedback. We have a new design in progress. I don't have a timeline for this work yet, but I'll update the issue when I do.

**Comment by ShevaDas** [comment]
Hi @user135711. This specific feature isn't something we're looking at implementing for general Docs content, so I'm going to close this out. We may add it in the future for specific content types such as tutorials. Please feel free to open another issue if you have additional feedback!
