### ISSUE TITLE
Need Rest API to get the availability zones information on the basis of Object selected in a particular region

### ISSUE THREAD

**Issue by surajmuthreja** [MicrosoftDocs/feedback#544]
**Is your feature request related to a problem? Please describe.**
It would be better if we can get the availability zones available in a particular region based on object selected.
Right now it is mentioned that only below regions support the availability zones:

Central US
France Central
East US 2 (Preview)
West Europe
Southeast Asia (Preview)

If we can get the information using Rest API that weather selected region supports the availability zone or not? If it does, how many zones are there.
Basically to get the supported availability zones based on region and selected resource.

For example:
While creating the VM using Portal, if we select the region as Central US which supports availability zones, it does enable the Availability Zone option in Portal UI.
And If user selects the Size as "Standard_DS3" which supports only Zone "3".

Similar support required from Rest API, is there a way we can get the supported list of Availability Zone(s) based on Region, Resource etc.

**Describe the solution you'd like**
Need a Get API call to get the list of Supported Availability Zones based on Region and Resource selected.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by hellosnow** [comment]
@surajmuthreja thanks for the feedback, I'll need to sync with Azure REST API team on this question.

**Comment by hellosnow** [comment]
@surajmuthreja from Azure team, we got the information that there's  SKUs API which give availability zone information: https://docs.microsoft.com/en-us/rest/api/compute/virtualmachinesizes/list 

Check the `Locations` from following example:

```json
ResourceType     : virtualMachines
Name             : Standard_D4_v2
Tier             : Standard
Size             : D4_v2
Family           : standardDv2Family
Locations[0]     : eastus2
LocationInfo[0]  :
  Location       : eastus2
  Zones[0]       : 1
  Zones[1]       : 2
  Zones[2]       : 3
Capabilities[0]  :
  Name           : MaxResourceVolumeMB
  Value          : 409600
Capabilities[1]  :
  Name           : OSVhdSizeMB
  Value          : 1047552
Capabilities[2]  :
  Name           : vCPUs
  Value          : 8
Capabilities[3]  :
  Name           : MemoryGB
  Value          : 28
Capabilities[4]  :
  Name           : MaxDataDiskCount
  Value          : 32
Capabilities[5]  :
  Name           : LowPriorityCapable
  Value          : True
Capabilities[6]  :
  Name           : PremiumIO
  Value          : False
```

**Comment by surajmuthreja** [comment]
@hellosnow  Thanks!
But when I am using this API, I am getting limited information. I am not seeing detailed information like the one you demonstrated above..

API Used:

GET https://management.azure.com/subscriptions/{subscriptionId}/providers/Microsoft.Compute/locations/eastus2/vmSizes?api-version=2017-12-01

Response sample below:

{
  "value": [
    {
      "name": "Standard_A0",
      "numberOfCores": 1,
      "osDiskSizeInMB": 1047552,
      "resourceDiskSizeInMB": 20480,
      "memoryInMB": 768,
      "maxDataDiskCount": 1
    },
    {
      "name": "Standard_D1_v2",
      "numberOfCores": 1,
      "osDiskSizeInMB": 1047552,
      "resourceDiskSizeInMB": 51200,
      "memoryInMB": 3584,
      "maxDataDiskCount": 4
    },
    {
      "name": "Standard_D2_v2",
      "numberOfCores": 2,
      "osDiskSizeInMB": 1047552,
      "resourceDiskSizeInMB": 102400,
      "memoryInMB": 7168,
      "maxDataDiskCount": 8
    },
    {
      "name": "Standard_D3_v2",
      "numberOfCores": 4,
      "osDiskSizeInMB": 1047552,
      "resourceDiskSizeInMB": 204800,
      "memoryInMB": 14336,
      "maxDataDiskCount": 16
    },
    {
      "name": "Standard_D4_v2",
      "numberOfCores": 8,
      "osDiskSizeInMB": 1047552,
      "resourceDiskSizeInMB": 409600,
      "memoryInMB": 28672,
      "maxDataDiskCount": 32
    },
    {
      "name": "Standard_D5_v2",
      "numberOfCores": 16,
      "osDiskSizeInMB": 1047552,
      "resourceDiskSizeInMB": 819200,
      "memoryInMB": 57344,
      "maxDataDiskCount": 64
    },
    {
      "name": "Standard_D11_v2",
      "numberOfCores": 2,
      "osDiskSizeInMB": 1047552,
      "resourceDiskSizeInMB": 102400,
      "memoryInMB": 14336,
      "maxDataDiskCount": 8
    },
    {
      "name": "Standard_D12_v2",
      "numberOfCores": 4,
      "osDiskSizeInMB": 1047552,
      "resourceDiskSizeInMB": 204800,
      "memoryInMB": 28672,
      "maxDataDiskCount": 16
    },
    {
      "name": "Standard_D13_v2",
      "numberOfCores": 8,
      "osDiskSizeInMB": 1047552,
      "resourceDiskSizeInMB": 409600,
      "memoryInMB": 57344,
      "maxDataDiskCount": 32
    },
    {
      "name": "Standard_D14_v2",
      "numberOfCores": 16,
      "osDiskSizeInMB": 1047552,
      "resourceDiskSizeInMB": 819200,
      "memoryInMB": 114688,
      "maxDataDiskCount": 64
    }

Can you please confirm if I am missing something here.

**Comment by hellosnow** [comment]
@surajmuthreja I transfer this issue to Azure swagger repo https://github.com/Azure/azure-rest-api-specs/issues/3594, hope some one from Azure team would have an answer there.

**Comment by hellosnow** [comment]
@Powerhelmsman @dend please help to triage the issue and find the right assignee in case you miss it 😄

**Comment by dendeli-msft** [comment]
Closing the issue as @hellosnow already has a product issue open 😄 This ask does not relate to documentation infrastructure, but rather the Azure REST APIs.

Den Delimarsky ● Senior PM, docs.microsoft.com ● [@DennisCode](https://twitter.com/DennisCode)

**Comment by surajmuthreja** [comment]
> Closing the issue as @hellosnow already has a product issue open 😄 This ask does not relate to documentation infrastructure, but rather the Azure REST APIs.
> 
> Den Delimarsky ● Senior PM, docs.microsoft.com ● [@DennisCode](https://twitter.com/DennisCode)

@dendeli-msft / @hellosnow  -- Can you please update that product issue ID or mark this Bug as dependent of that issue or add some keyword for reference so that I can track that issue.
