### ISSUE TITLE
More Information on R Packages Supported by Power BI Service

### ISSUE THREAD

**Issue by enterprisecommunity-dsa** [MicrosoftDocs/feedback#545]
In the article "R packages in the Power BI service", can the list of supported packages be improved to give more information? I am attempting to browse the list to find a package which has functionality similar to the package I have been using in development, but with no information other than a package name and version number, this is a tiresome exercise. 

A list of package names with their subtitles as published to CRAN (see link) is much much easier to read to find an appropriate alternative package. 

[https://cran.r-project.org/web/packages/available_packages_by_name.html](url)

**Comment by Powerhelmsman** [comment]
@enterprisecommunity-dsa Thanks for your feedback. I transferred you issue to powerbi-docs repo. They will help you there.
