### ISSUE TITLE
Quantum pages: 'Is this helpful?' comment disappears after 10s no matter what!

### ISSUE THREAD

**Issue by flagrange** [MicrosoftDocs/feedback#548]
Hello,
On the new pages about Q# and it's concepts, there is a little 'Is this page helpful? [Yes/No]' popup on the bottom right. When clicking Yes or No, one gets the option to leave textual feedback 'Tell us here'. This opens a small dialog where a comment can be typed in.

Unfortunately, that box vanishes after 10s _whether text is being typed or not_.  This makes it impossible to type in a feedback... unless one is really fast. Tried on Chrome, Win7 and Win10.

[https://docs.microsoft.com/en-us/quantum/quantum-concepts-1-intro?view=qsharp-preview](https://docs.microsoft.com/en-us/quantum/quantum-concepts-1-intro?view=qsharp-preview)
and underlying pages.

Also, on many Microsoft Docs pages there is a 'Save as PDF' possibility, in the left titles column. This is not (yet?) possible here.

**Comment by Powerhelmsman** [comment]
@ShevaDas Can you follow up this issue?

**Comment by ShevaDas** [comment]
@flagrange I can't repro this on the latest version of Chrome on OSX. The box stays open indefinitely. However, I'll pass your report along to the engineering team. 

Tagging @dastaffo for your "Save as PDF" question.

**Comment by flagrange** [comment]
You guys are amazing!

@ShevaDas  I did a few more tests:
Note that you really have to click _Yes_, then _Tell us here_. Then type a few letters in the comment box and wait 10s (actually, rather about 6s). The box vanishes - even if you typed letters. I tried on different pages on that topic.

- Closed and reopened Chrome Version 67.0.3396.99 (Official Build) (64-bit) on Win 7: confirmed
- On IE 11.0.9600.19002 on Win 7: confirmed
(This is a self made PC)
- On a Lenovo X1 Carbon, Chrome same version on Win 10 Pro version 1803: confirmed.
- On a (not-Apple-supported) macOS (OSX) 10.12 High Sierra running in a VMWare, with Safari 11.1 (13605.1.33.1.2) - about the closest I have to your MacBook: confirmed also. This OSX, although in a VM, works perfectly well, including Visual Studio Code etc.

Someone else should try and report if they see the same.
Thank you,

**Comment by flagrange** [comment]
Hello,

I noticed this morning, doing some coding for fun, that I have the same behavior on other doc pages as well, like [here](https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/statements/removehandler-statement).

Just FYI.
F>

**Comment by dastaffo** [comment]
@flagrange Thanks for the feedback on PDF! Unfortunately, we don't support the formulas yet in PDF, which is why it's not available here, but we will add it as something to consider for future release.

**Comment by ShevaDas** [comment]
#log-suggestion @ShevaDas

**Comment by ShevaDas** [comment]
@flagrange The fix for this should have shipped today. Please confirm it works for you and then close the issue out if all is well. :)

**Comment by flagrange** [comment]
@shevadas It is fixed when using IE (on Win 7, version reference above), but on Chrome, the 'Is this helpful' question does not appear at all any more. I could check later today on Win 10 (but the same version of Chrome).
In that sense, the problem disappeared, but maybe not in the way you intend it to.

**Comment by DuncanmaMSFT** [comment]
@flagrange are you trying on a page where you already rated the page? Can you try on a different page that you haven't visited before instead, like https://docs.microsoft.com/en-us/contribute/how-to-write-use-markdown as an example?

We tried in Chrome on both Windows 10 and Windows 7 and are seeing the box

**Comment by flagrange** [comment]
@DuncanmaMSFT You are right, and I should have thought about it: these pages were probably still cached. Weird is though that I'm unable to force a refresh or to make it work on the first five pages (Welcom upto The Qubit), no matter what I try. Beyond that, it's all OK.
But anyway, I think this is on my side now, so I've closed it.
Thank you for all these wonderful pages, by the way and for the work you do.
