### ISSUE TITLE
Edit Link on Sharepoint PnP leads to Github 404

### ISSUE THREAD

**Issue by fowl2** [MicrosoftDocs/feedback#549]
The edit link on https://docs.microsoft.com/en-us/dotnet/api/microsoft.sharepoint.client (which is showing the wrong content fwiw #517) goes to https://github.com/SharePoint/sp-dev-docs-pnp-ref-dotnet/blob/live/dotnet/xml/ns-Microsoft.SharePoint.Client.xml, which is 404.

**Comment by Powerhelmsman** [comment]
@mairaw @dend Can you take a look at this issue? Click Edit return 404.

**Comment by dend** [comment]
That is caused by the fact that the repo behind the content is private, and the **Edit** button should not be shown to begin with. We are working on addressing that.

**Comment by dend** [comment]
Following-up here - we are investigating the root cause of a tangential bug, that is preventing a content re-build right now.

**Comment by dend** [comment]
Thanks again for the feedback, @fowl2 - the team has decided that community contributions are not necessary in that particular repo, hence why the repo was private. As such, we removed the Edit button for the time being.
