### ISSUE TITLE
Add literal search option using quotes

### ISSUE THREAD

**Issue by supernova-eng** [MicrosoftDocs/feedback#55]
Can you add a literal search function using quotes around the search text?

When I enter "System.Windows.Application" and open the page of the first search result and search for "System.Windows.Application" I don't find a hit. Quotes around search text is so common in search engines that I'm supprised that it is not supported here.

----------
⚠ Idea migrated from UserVoice

**Created By:** Dirk Jan D.
**Created On:** 2017/12/14 10:45:15 +0000
**Votes at Migration:** 1
**Supporters at Migration:** 1

**Comment by presleyy** [comment]
This is true that search engine currently doesn't think the "System.Windows.Application" as a whole. Created a feature work item for enabling this function. Also search System.Windows.Application in .NET API browser could have much better results

**Comment by presleyy** [comment]
Migrated from legacy VSTS work item to the [customer suggestion](https://ceapex.visualstudio.com/Engineering/_workitems/edit/25953)

**Comment by keziamicro** [comment]
Hello - reviewing and cleaning up some older feedback/issues. Thanks!
