### ISSUE TITLE
How to create SharedAccessSignature for API Management REST APIs(v.2018-06-01-preview)

### ISSUE THREAD

**Issue by vetrivelmp** [MicrosoftDocs/feedback#550]
https://docs.microsoft.com/en-us/rest/api/apimanagement/user/get

From this document, no information about how to create SharedAccessSignature (Accesstoken) for accessing API Management REST APIs. I dont see latest document for this. Please give me details how to create SharedAccessSignature (Accesstoken) for API Management REST APIs(v.2018-06-01-preview)??.

**Comment by Powerhelmsman** [comment]
@hellosnow Can you follow up this question?

**Comment by hellosnow** [comment]
@mmacy and @rloutlaw do you have any guidance on this question? Or could help to find someone to answer? Thanks.

**Comment by vetrivelmp** [comment]
For a long time i dont see proper response... It is urgent for our product development please

**Comment by hellosnow** [comment]
@vetrivelmp I'm writing letter to seek help from @mmacy and @rloutlaw to accelerate this. 

By the way, does this page https://docs.microsoft.com/en-us/rest/api/apimanagement/apimanagementrest/azure-api-management-rest-api-authentication help?

**Comment by mikebudzynski** [comment]
As @hellosnow  mentioned, instructions for generating a SAS token, along with the code for that, are included in the documentation:
https://docs.microsoft.com/en-us/rest/api/apimanagement/apimanagementrest/azure-api-management-rest-api-authentication#ProgrammaticallyCreateToken

Is this what you were looking for?

**Comment by vetrivelmp** [comment]
Hello @mikebudzynski ,

The above given link talks about previous version of SAS token. For latest version(2018-06-01-preview) of SAS token it is different. Actually the above given link is obsolete for latest API (v.2018-06-01-preview). Please read comments section on the page. So every body is looking latest SAS token generation including me.

**Comment by mikebudzynski** [comment]
@vetrivelmp , you are right, thanks for pointing this out. I will update the docs this week.

For the time being, please navigate to your API Management instance in Azure and select _Management API_ from the menu on the left. You can generate the SAS token from there.

**Comment by vetrivelmp** [comment]
Hello mikebudzynski,

We are trying Microsoft.Azure.Management.ApiManagement 4.0.4-preview to  implement api mangement apis. this dll is using azure resource server format of apis not direct access calls. To use Microsoft.Azure.Management.ApiManagement 4.0.4-preview, i have to know how to generate authorize token programatically. whether Microsoft.Azure.Management.ApiManagement 4.0.4-preview will accept SAS token or Bearer token?

**Comment by vetrivelmp** [comment]
you are talking about direct access call. but the page https://docs.microsoft.com/en-us/rest/api/apimanagement/user/get  try now is using bearer token. how to programatically generate this bearer jwt token?

**Comment by Powerhelmsman** [comment]
@mikebudzynski vetrivelmp response your answer, please take a look at this. Let me know if I can close this issue.

**Comment by mikebudzynski** [comment]
Auth instructions for direct access API are here: https://docs.microsoft.com/en-us/rest/api/apimanagement/apimanagementrest/azure-api-management-rest-api-authentication
If you want to use Azure Resources Manager calls, just acquire the AAD token for ARM.
