### ISSUE TITLE
Links broken 

### ISSUE THREAD

**Issue by mixfede** [MicrosoftDocs/feedback#553]
**Link to article:**
Tell us where exactly a problem occurs.
https://docs.microsoft.com/en-us/previous-versions/dotnet/netframework-1.1/w4hk59ha%28v%3dvs.71%29

**Problem:**
In This Section. Links redirect to wrong page.

    Implementing a Simple Web Forms Control Designer      **<----- !!!!**
    Describes the key steps in implementing a designer that governs the design-time HTML rendered by an ASP.NET server control.
    Implementing a Web Forms Data-Bound Control Designer    <----- !!!!
    Describes how to implement a designer that provides design-time data binding for a data-bound control.
    Implementing a Web Forms Template Editor <----- !!!!
    Describes how to implement a template editor for a templated ASP.NET server control.
    Web Forms Templated Data-Bound Control Designer Sample   <----- !!!!
    Provides a sample of a designer that enables template editing and design-time data binding for a templated data-bound control.

**Comment by Powerhelmsman** [comment]
@mixfede Thanks for your feedback. Currently the page is no longer updating due to out of production lifecycle. Please try to use the up to date version .NET Framework.
