### ISSUE TITLE
Localized or original Feedback form needs more information above input field.

### ISSUE THREAD

**Issue by Makopo** [MicrosoftDocs/feedback#554]
**Is your feature request related to a problem? Please describe.**

Original page has [our blog post](
https://docs.microsoft.com/teamblog/a-new-feedback-system-is-coming-to-docs) link which leads the page explaining where your post will go. 

![en](https://user-images.githubusercontent.com/303874/43266796-426fa678-9127-11e8-971b-52abbffda6b9.png)

Whereas, some localized pages, e.g. Japanese, have no links nor explanation. No word of **GitHub** on it.

![ja](https://user-images.githubusercontent.com/303874/43266815-48f103c0-9127-11e8-93d0-2b912e3f4bb0.png)

I believe that leads confusion to submitters such like [some comments in this issue](https://github.com/dotnet/docs.ja-jp/issues/118) who upset after they know that their post was automatically transmitted to the **public** GitHub instead of Microsoft internal QA system. We naturally assume that what we wrote in *feedback* form goes to its vendor's internal QA system, not to public.

It might be dup of [Suggestion for displaying an issue template #136](https://github.com/dotnet/docs.ja-jp/issues/136). Though I posted here since it should be considered globally rather than in one region.

**Describe the solution you'd like**

Feedback forms on all localized pages need simple descriptions like that:

* Your post will go to **public** GitHub.
   * Better if it has link to target issues list page.
* You may get feedback in English rather than page language.

Or, original template can have such descriptions so that each localized templates can be easily translated.

**Comment by Powerhelmsman** [comment]
@SonjaSaltzman Can you identify if this is a localization issue?

**Comment by SonjaSaltzman** [comment]
@bodhigautam could you please follow up? We need to make sure the localized feedback control displays the same information as en-US feedback control. 
@Sara-Nicolini FYI

**Comment by bodhigautam** [comment]
Thanks @SonjaSaltzman . I am following it up with the appropriate team to get this resolved. Will update as soon as its done .

**Comment by Makopo** [comment]
@bodhigautam @SonjaSaltzman The page linked from the original form is not localized to Japanese. Maybe that's why the localization team decide not to include that link. So, I suspect that writing short explanation instead of including a link might be better solution.

![targetpage](https://user-images.githubusercontent.com/303874/43288114-e79ed8b4-9161-11e8-98f7-dac3a3a9e9e1.png)

**Comment by bodhigautam** [comment]
@Makopo We have worked on it . The feedback message for github is appearing now. Please close this issue.
