### ISSUE TITLE
Signing in to post comments does not work

### ISSUE THREAD

**Issue by arjenkrap** [MicrosoftDocs/feedback#555]
**Describe the bug**
As a visitor of docs.microsoft.com I want post a comment to ask questions. I am already signed in. I see my name and avatar in the top right corner. Below the textbox is a button called 'Post comment as...'. When I click the button a popup appears asking me to sign in using a form or using a Microsoft account, Facebook account, etc. Please note that I am already signed in. Trying to sign in using the form results into an 'Invalid username or password' error. Trying to sign in using a Microsoft account results into an blank popup.

**To Reproduce**
1. Go to https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/clr-strict-security?view=sql-server-2017
2. Verify that you are already signed in by looking at the top right corner. It does not matter the behavior is the same if you are signed in or not.
2. Scroll down to the textbox.
3. Type or paste the comment.
4. Click on the button called 'Post comment as...'
5. Try to sign in using the form. It fails. ('Invalid username or password')
6. Try to sign in using the Microsoft button. It fails. (blank popup with window title 'Autorization complete')

**Expected behavior**
I can posts comments since I am already signed in.

**Screenshots**
![signin](https://user-images.githubusercontent.com/7942715/43303025-27837794-916e-11e8-9e9c-1e836d94f853.PNG)
![authorization-complete-blank](https://user-images.githubusercontent.com/7942715/43303026-279addbc-916e-11e8-8aae-48c82105f02f.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10 1803
 - Browser Chrome 67, Edge

**Comment by arjenkrap** [comment]
I just realized that starting the subject with logging might be confusing. So changed al use of words like logging in to signing in. This also makes the story more consistent with the screenshots and the actual website.

**Comment by dend** [comment]
We are actually moving away from LiveFyre in favor of GitHub issues. @sudeepku - can you help us work with the content partners to move the content to the new feedback system?

**Comment by ShevaDas** [comment]
@sudeepku Please feel free to reach out or direct the SQL team to me if they need help getting it set up!

@arjenkrap I'm going to close this issue out as Livefyre is no longer a supported comment mechanism on our platform and we won't be fixing this. Please open a new issue on this repo if you have additional feedback.
