### ISSUE TITLE
Discoverability of https://docs.microsoft.com/azure/templates/

### ISSUE THREAD

**Issue by jtuliani** [MicrosoftDocs/feedback#556]
**Is your feature request related to a problem? Please describe.**
https://docs.microsoft.com/azure/templates/ is awesome.
But I just found out about it by chance
I can't find a link to it anywhere. It's completely undiscoverable!

**Describe the solution you'd like**
Link to https://docs.microsoft.com/azure/templates/ clearly from the main Azure docs pages somewhere.
I suggest putting a link on https://docs.microsoft.com/azure/index#pivot=sdkstools similar to the existing REST API reference link

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by dend** [comment]
@tfitzmac can you help look into this?

**Comment by tfitzmac** [comment]
@jtuliani - thanks for the feedback.  I agree that discoverability has been a problem. Your suggestion about adding it to the index page makes sense. I'll see if it can be added to that page. I just recently embedded the whole template reference TOC under the Resource Manager TOC. I've noticed that change has helped a bit.
![template-toc](https://user-images.githubusercontent.com/4007949/43544253-2f18840a-9587-11e8-9517-1131ddf82830.png)

**Comment by Powerhelmsman** [comment]
@jtuliani I will close the issue since tfizmac provides a solution. We can reopen it if you have other question related to this.

**Comment by tfitzmac** [comment]
@jtuliani - although this issue has been closed, I am still pursuing adding the template reference link to the index page for SDKs/tools.

**Comment by tfitzmac** [comment]
@jtuliani - Links for Azure Resource Manager (including the template reference docs) have been added to the SDKs/Tools page. It is listed under Tools & Extensions.

**Comment by jtuliani** [comment]
Super! I see it. One suggestion: the link to the templates just says 'Reference'. It might be more discoverable if it said 'Template reference'?  I know it's under 'Azure Resource Manager', but that supports more than one type of reference (e.g. template reference, REST API reference). And I just think the word 'template' is fundamental to discoverability and needs to be included.

**Comment by Powerhelmsman** [comment]
@tfitzmac Jtuliani reply your message. Please take a look at it.
