### ISSUE TITLE
SharePoint Server API Documentation Rendered Incorrectly

### ISSUE THREAD

**Issue by bloudraak** [MicrosoftDocs/feedback#559]
**Describe the bug**
Many of the SharePoint Server API documentation is rendered incorrectly. The bug report is for one page, but they are too numerous to create one for each page.

**To Reproduce**
1. Go to https://docs.microsoft.com/en-us/dotnet/api/microsoft.sharepoint.taxonomy.termstore?view=sharepoint-server
2. Observe that content is rendered incorrectly.

**Expected behavior**
Expecting the source code to be rendered as source code, and other contents are rendered as HTML

**Screenshots**

![image](https://user-images.githubusercontent.com/622724/43359758-fe76dd92-925c-11e8-80c5-8efd89d6755a.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Version 1803
 - Browser: Firefox
 - Version: 61.0.1 (64-bit)

**Additional context**
Many of the SharePoint API sites seems to be rendered incorrectly

**Comment by Powerhelmsman** [comment]
@bloudraak Thanks for your feedback. Your issue is transferred to SharePoint team. They will help you there.

**Comment by dend** [comment]
@Powerhelmsman I am re-opening this one as it likely has to do with our rendering infrastructure. Will follow-up to test.

**Comment by dend** [comment]
The likely cause is that the content is using an older parser. I've [opened a PR](https://github.com/SharePoint/sp-dev-docs-2013-server-ref-dotnet/pull/5) to fix this.

**Comment by dendeli-msft** [comment]
This has been addressed.
