### ISSUE TITLE
Add search match highlighting in output

### ISSUE THREAD

**Issue by supernova-eng** [MicrosoftDocs/feedback#56]
Can you add highlighting of words that match the search criteria?

----------
⚠ Idea migrated from UserVoice

**Created By:** Dirk Jan D.
**Created On:** 2017/12/14 10:37:42 +0000
**Votes at Migration:** 1
**Supporters at Migration:** 1

**Comment by presleyy** [comment]
Thanks. We have a feature work item (planning phase) exactly same with this suggestion.

**Comment by presleyy** [comment]
Have the [feature](https://ceapex.visualstudio.com/Engineering/_workitems/edit/15880) exactly about this.

**Comment by keziamicro** [comment]
Hello - reviewing and cleaning up some older feedback/issues. Thanks!
