### ISSUE TITLE
Images are not clear. Words are blurry.

### ISSUE THREAD

**Issue by mohsin1811** [MicrosoftDocs/feedback#562]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

**Link to article:**
Tell us where exactly a problem occurs.
https://docs.microsoft.com/en-us/sql/relational-databases/backup-restore/complete-database-restores-full-recovery-model?view=sql-server-2017

https://docs.microsoft.com/en-us/sql/relational-databases/sql-server-transaction-log-architecture-and-management-guide?view=sql-server-2017

**Problem:**
What's wrong with the article?
The images embedded in this page and many others are not clear. The words are looking blurry. Please upload clear images. Thanks!

**Comment by mohsin1811** [comment]
Hi @Powerhelmsman, @MikeRayMSFT,

I just found that the image looks very clear in light background however when I change it to dark, the image turns blurry. I can switch the backgrounds for viewing the images however it will be nice to have the images look crisp in dark background as well. Hopefully you can repro that on your side. 

I am copying a screenshot here showing the html inspection and color of the words in image when the background is dark vs light.

![image](https://user-images.githubusercontent.com/39417049/43376461-b3bc25f0-936f-11e8-9e92-c65964617caf.png)


![image](https://user-images.githubusercontent.com/39417049/43376495-f60bd086-936f-11e8-86f3-81be36599ad0.png)


Thanks guys!
Mohsin

**Comment by Powerhelmsman** [comment]
@mohsin1811 Yes, you are right. the image doesn't work in dark mode. I will let author know.

**Comment by mohsin1811** [comment]
Thanks! @Powerhelmsman

**Comment by Powerhelmsman** [comment]
@rothja The picture in dark mode is still blur.  When can fix it?

**Comment by rothja** [comment]
@Powerhelmsman @mohsin1811 , So sorry for the unacceptable delay on this issue. I will work on this today. Thank you.

**Comment by rothja** [comment]
I have a PR submitted that should fix theses (and other) articles when publishing happens today. Thank you!

**Comment by MilindGour9869** [comment]
Trick : 
Just take a Screenshot , crop it , re-upload
