### ISSUE TITLE
Missing features in the Twitter Connector Documentation for Microsoft Flow

### ISSUE THREAD

**Issue by Timothep** [MicrosoftDocs/feedback#568]
Hi, got the hint (via @MicrosoftFlow [on Twitter](https://twitter.com/MicrosoftFlow/status/1021381023215603713)) that there is a way to search for a specific user in the Twitter Flow Connector using the following as a search text:

> from:@username

Unfortunately this is mentionned nowhere on the connector documentation page: https://docs.microsoft.com/de-de/connectors/twitter

I've seen this question asked a few times on UserVoice and the PowerUsers Forums and people using very weird workaround for it.

I think it should be added to the documentation... well as other hidden features if there are some ;)

Thanks!

**Comment by Powerhelmsman** [comment]
@miriver Can you follow up the user's suggestion?

**Comment by Powerhelmsman** [comment]
@theresapalmer Can you help here?

**Comment by theresapalmer** [comment]
This is a reasonable suggestion, I've filed a bug to track adding this to the documentation. I'm also no longer working on connectors but assigned the bug to @schabungbam

**Comment by v-sefedo** [comment]
Created [pull request](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/pull/268) with an updated description

**Comment by Powerhelmsman** [comment]
@v-sefedo Your PR is closed without merge. Can you response if your team will add some examples?

**Comment by Powerhelmsman** [comment]
@theresapalmer For your reference

**Comment by theresapalmer** [comment]
@schabungbam would own this from the PM side.

**Comment by v-sefedo** [comment]
@Powerhelmsman, @theresapalmer , Documentation was updated recently, I have added search term `from:@username` as an example how to search for tweets. I think we can resolve this issue now.

**Comment by Powerhelmsman** [comment]
@Timothep The issue is resolved. Please take a look.
