### ISSUE TITLE
Spanish instead of english

### ISSUE THREAD

**Issue by cfwicks** [MicrosoftDocs/feedback#569]
# Idea Title
Change communication language to English instead of Spanish

I signed up for email notifications and the system is sending the Spanish version.

## Issue Details

Add a detailed explanation of what is wrong or what you want implemented. If reporting a bug on an existing page, make sure to include a link.

**Comment by Powerhelmsman** [comment]
@cfwicks Can you provide more detail information? What page link do you refer to?

**Comment by cfwicks** [comment]
The newsletter comes to my account in Spanish. I want to change the language to English. I will see if I can find an old email.

**Comment by Powerhelmsman** [comment]
@cfwicks Do you find the old email yet? We need it to figure out if the letter are from Docs site.

**Comment by cfwicks** [comment]
I deleted the emails and unsubscribed from the mailing list. Sorry.

**Comment by Powerhelmsman** [comment]
@cfwicks I have to close this issue as no enough information. Please let us know if you find the similar issue so we can reopen it to continue the discussion.

**Comment by cfwicks** [comment]
No problem.
