### ISSUE TITLE
Unable to comment on Partner Center REST API docs

### ISSUE THREAD

**Issue by cjmod** [MicrosoftDocs/feedback#570]
**Describe the bug**
Unable to login or comment on Partner Center REST API docs

**To Reproduce**
1. Go to 'https://docs.microsoft.com/en-us/partner-center/develop/azure-rate-card'
2. Click on 'Feedback'
3. Click on 'Sign in'
5. Follow on screen prompts to authenticate with Microsoft, Facebook, Google
6. Successful auth is not processed to complete the login process
7. Click on 'Create New Account'
8. Popup box from Step 3 goes blank
9. Note that no option for 'Content Feedback' (aka. auth via Github) is present

**Expected behavior**
Expect to be able to login and leave a comment on the doc to report an issue with CSP margin being applied twice to the Rate property.

**Screenshots**
Successful auth (Step 6)
![image](https://user-images.githubusercontent.com/885570/43542017-dcf0d3a4-9599-11e8-99d7-a343d400fcc7.png)

Blank popup after Create New Account (Step 8)
![image](https://user-images.githubusercontent.com/885570/43542041-ead19206-9599-11e8-90d1-ce14e061bdeb.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome (v68.0.3440.84) and Edge (v41.16299.492.0)
 - Version [see above]

**Smartphone (please complete the following information):**
 - Device: N/A
 - OS: N/A
 - Browser: N/A
 - Version: N/A

**Additional context**
Pretty straight forward. I'm trying to login / leave a comment and none of the options available work.

**Comment by Powerhelmsman** [comment]
@cjmod The comment will be removed from docs site eventually, which will be replaced by GitHub issue. So if you have any feedback or issue, you can create issue in this channel or if you see the picture like 
![image](https://user-images.githubusercontent.com/33136632/43542588-47878626-9582-11e8-83b2-66ff0b1c47f7.png)
on the bottom of page. You can click content feedback and create feedback.

**Comment by cjmod** [comment]
@Powerhelmsman: Does that mean I should create an issue here for the Partner Center Rate Card API? I'm trying to make sure the feedback makes it to the API developers.
