### ISSUE TITLE
Improvement of feedback form

### ISSUE THREAD

**Issue by GlassGrass** [MicrosoftDocs/feedback#571]
This issue may be related to #554 or MicrosoftDocs/Contribute#46.

## background

Recently, there were a little unfortunate accident caused by misunderstanding in a ja-jp docs feedback issue.

I don't touch it to prevent re-flaming, but I think there are some factor such as followings.

- Currently ja-jp docs feedback form does not seem obvious that the new issue will be opened on github when feedback are submitted.

- For feedbacking, there is no guideline or it is difficult to find such a guideline.

## proposal

I propose followings.

- to inform clearly that github issue will be opened by your feedback in any languages.

- to formulate a feedback guideline summary simpler than full style contributing guideline.

- to be able to select feedback category, for example such as "information lack," "mistranslation," "sample code improvement."

**Comment by Powerhelmsman** [comment]
@GlassGrass Thanks for your feedback. This is related to #554. I will close this feedback and track the status there.
