### ISSUE TITLE
Error clicking on link

### ISSUE THREAD

**Issue by Zio3D** [MicrosoftDocs/feedback#572]
1. Go to on "https://docs.microsoft.com/it-it/windows/#pivot=developer&panel=developer-all"
2. Click on 'Informazioni di base' in "Desktop" section of "Sviluppatore" page.
3. The link go to "https://developer.microsoft.com/windows/desktop/getstarted" page.
4. This page redirect automatically to "https://developer.microsoft.com/it-it/windows/desktop" page.
5. This page has the error: "'alt' is a duplicate attribute name. Line 83, position 170.".

**Desktop (please complete the following information):**
 - OS: Microsoft Windows 10 1803 (17134.165) Italian
 - Browser: Firefox Quantum
 - Version: 60.0.2 64 bit
![immagine1](https://user-images.githubusercontent.com/42025157/43570444-ad819eea-963a-11e8-82af-7f3741e71552.png)

Thanks
Davide

**Comment by Powerhelmsman** [comment]
@jialge Can you take a look at this issue?

**Comment by Powerhelmsman** [comment]
@Zio3D the issue is fixed. I will closed so far.
