### ISSUE TITLE
Add Powershell to Syntax examples in framework documentation on MSDN

### ISSUE THREAD

**Issue by pinecones-sx** [MicrosoftDocs/feedback#574]
# Add PowerShell to Syntax examples in framework documentation on MSDN

This is a request / suggestion to add Syntax examples for PowerShell to framework documentation on MSDN / docs.

**Comment by EdisonDa** [comment]
Thank you @pinecones-sx for your suggestion. Could you please share me a link as an example we can get evaluate more?

**Comment by pinecones-sx** [comment]
Sure!  If you go to this link
https://msdn.microsoft.com/en-us/library/system.windows.forms.form(v=vs.110).aspx

there should be a "syntax" section.  my ask is to have PowerShell syntax
examples added.

**Comment by dend** [comment]
Given that this is .NET-related, re-assigning to myself 😄 @pinecones-sx we are moving away from MSDN, therefore no features will be added there. That said, it's fair game to suggest changes for docs.microsoft.com!

Regarding PS syntax, can you provide some examples of what you have in mind (e.g. what the signature would look like)?

**Comment by dend** [comment]
Given that we have not obtained any clarifying information, I am going to close this issue. @pinecones-sx - feel free to comment with details, when you have the time, and we will re-assess re-opening the feedback item.

**Comment by pinecones-sx** [comment]
I DID respond.  I did not receive a response back.  So why are you closing this?

**Comment by pinecones-sx** [comment]
@dend

**Comment by Powerhelmsman** [comment]
@dend I reopen the issue since user provide the more information now.

**Comment by dend** [comment]
#log-suggestion @dend 

Following-up on this item - I am opening an internal issue to track the request for future experience considerations. Given that the work is currently not planned, I am closing this public issue. @pinecones-sx - appreciate your detailed breakdown of the problem at hand!

**Comment by botcrane** [comment]
🚀 **ATTENTION**: [Internal request](https://ceapex.visualstudio.com/web/wi.aspx?pcguid=7d644393-99ad-41c8-ac53-7fa79294c720&id=54180) logged.
