### ISSUE TITLE
Azure API reference for Reserved Instances is missing 'write' operations

### ISSUE THREAD

**Issue by jtuliani** [MicrosoftDocs/feedback#576]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.
Understood. This issue relates to the Azure REST API reference, which doesn't (yet) have a comments section.

**Link to article:**
https://docs.microsoft.com/en-us/rest/api/reserved-vm-instances/

**Problem:**
Look at the various sub-pages for resources/operations relating to Reserved Instances.
All I can see are 'Read' operations. Where is the API reference for the 'Write' operations? How do I use the REST API to create a Reserved Instance?

According to the sample output at https://docs.microsoft.com/en-us/rest/api/reserved-vm-instances/operation/list there should be write operations on 'reservations' and 'reservationOrders'.

**Comment by Powerhelmsman** [comment]
@hellosnow Can you find the right person to follow up?

**Comment by hellosnow** [comment]
@jtuliani I transferred the issue to https://github.com/Azure/azure-rest-api-specs/issues/3574, please check update there.
