### ISSUE TITLE
REST API and template reference documentation for Management Groups is missing

### ISSUE THREAD

**Issue by jtuliani** [MicrosoftDocs/feedback#577]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.
Understood. This issue relates to the Azure REST API and Azure template references, which don't (yet) have a comments section.

**Link to article:**
https://docs.microsoft.com/rest/api/?view=Azure
https://docs.microsoft.com/azure/templates

**Problem:**
Azure Management Groups are now GA: https://azure.microsoft.com/en-us/blog/azure-management-groups-now-in-general-availability/

However, I can't find any REST API or template reference documentation for Management Groups.

**Comment by Powerhelmsman** [comment]
@jtuliani Thanks for your feedback. Your issue is transferred to Azure/azure-rest-api-specs. They will help you there.
