### ISSUE TITLE
Please translate https://docs.microsoft.com/en-us/dynamics365/customer-engagement/admin/manage-updates

### ISSUE THREAD

**Issue by TakiyaNakano-MSFT** [MicrosoftDocs/feedback#578]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

**Link to article:**
English (original)
https://docs.microsoft.com/en-us/dynamics365/customer-engagement/admin/manage-updates

Japanese (tranlsated)
https://docs.microsoft.com/ja-jp/dynamics365/customer-engagement/admin/manage-updates

**Problem:**
English (original) version was updated on July 31st, and Japanese version wasn't tranlslated yet.

**Request:**
Please translate English aticle to Japanese ASAP,

**Justification:**
Recentry, Dynamics 365 has changed the policy regarding online service upgrade. (see https://cloudblogs.microsoft.com/dynamics365/2018/07/06/modernizing-the-way-we-update-dynamics-365/). And, MIcrosoft Dynamics 365 operation team asked to book the upgrade schedule by Aug. 16th. 

> ACTION NEEDED: This is a reminder to schedule an update for your organization by August 16, 2018.
> The date for the update should be on or before January 31, 2019. You can find instructions on 
> how to schedule and approve updates here. 

All Japanese Dynamics 365 administrators need to fully understand new upgrade policy, then book the upgrade schedule. This doc.ms.com artcile explaines latest upgrade policy and ease to book the schedule.

**Comment by Powerhelmsman** [comment]
@SonjaSaltzman Can you follow up this suggestion?

**Comment by SonjaSaltzman** [comment]
@krisre @vinceno could you please respond?

**Comment by vinceno** [comment]
@SonjaSaltzman, as this is for Customer Engagement, @krisre will look into it

**Comment by krisre** [comment]
@SonjaSaltzman -Thanks!  @TakiyaNakano-MSFT - There is a delta between the English topic update and the publishing of the localized version of the topic.  Our next handoff for content translation is next week.  I confirmed that this topic update will be included.

**Comment by krisre** [comment]
@TakiyaNakano-MSFT - I've also confirmed that we've requested this topic to be prioritized by our vendor.

**Comment by SonjaSaltzman** [comment]
@krisre this has been open for a long time - can you please comment and close it (assuming it is resolved)?

**Comment by krisre** [comment]
Note:  The localized versions will lag behind English updates.  Changes to the English topic will be picked up in the hand off to Localization the following month.
