### ISSUE TITLE
Indicate static members

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#58]
.NET, C#
- Indicate which members are static
- Consider grouping of of static/non-static members

----------
⚠ Idea migrated from UserVoice

**Created By:** dev
**Created On:** 2017/12/13 11:36:39 +0000
**Votes at Migration:** 7
**Supporters at Migration:** 7

**Comment by dend** [comment]
#log-suggestion @dend

**Comment by botcrane** [comment]
🚀 **ATTENTION**: [Internal request](https://ceapex.visualstudio.com/web/wi.aspx?pcguid=7d644393-99ad-41c8-ac53-7fa79294c720&id=25942) logged.

**Comment by dend** [comment]
Duplicate of #469
