### ISSUE TITLE
The search box with title “Filter by title” has a white background

### ISSUE THREAD

**Issue by spatnaik** [MicrosoftDocs/feedback#580]
**Describe the bug**
The search box with title “Filter by title” has a white background. Please consider this an accessibility issue for people with sensitive eyes.

**To Reproduce**
1. Go to 'https://aka.ms/rds'
2. Switch to Dark mode
3. Notice that the search box (top left of the page) with title “Filter by title” has a white background. 

**Expected behavior**
The search box has a gray background. The color should preferably be same as the address bar on Microsoft Edge in dark mode (see attachment)

**Screenshots**
![edge address bar in dark mode](https://user-images.githubusercontent.com/8322635/43664764-d3e886be-9722-11e8-8a1c-e2b106344af1.png)

**Desktop (please complete the following information):**
 - OS: All
 - Browser: All
 - Version: All

**Smartphone (please complete the following information):**
 - Device: All
 - OS: All
 - Browser: All
 - Version: All

**Additional context**
None

**Comment by Powerhelmsman** [comment]
@ShevaDas Can you follow up this suggestion?

**Comment by ShevaDas** [comment]
@spatnaik Thanks for reporting this. I'll work with our engineering team to get it resolved.

#log-suggestion @ShevaDas

**Comment by Powerhelmsman** [comment]
#log-suggestion @ShevaDas

**Comment by botcrane** [comment]
🚀 **ATTENTION**: [Internal request](https://ceapex.visualstudio.com/web/wi.aspx?pcguid=7d644393-99ad-41c8-ac53-7fa79294c720&id=35350) logged.

**Comment by ryzngard** [comment]
I believe this can be closed. Here's current screenshot from today: 

![image](https://user-images.githubusercontent.com/475144/53454393-d83ce000-39db-11e9-956b-a84f903c9c37.png)

**Comment by dendeli-msft** [comment]
Closing this issue as the box is now theme-aware.
