### ISSUE TITLE
Open-source the documentation under MIT or CC0 for System.Reactive

### ISSUE THREAD

**Issue by ghuntley** [MicrosoftDocs/feedback#583]
Howdy Folks

I'm opening this again as https://github.com/MicrosoftDocs/feedback/issues/114#issuecomment-399601350 was prematurely closed. 

**Problem:**

See stream at 2h 22 minute mark at https://twitter.com/GeoffreyHuntley/status/1026413749819691009

The guidance provided by Microsoft is as `System.Reactive` (even though it's in the system namespace) isn't produced by Microsoft then documentation cannot exist on docs.microsoft.com.  Historically this was not the case and all of the MSDN documentation since 2009 has been archived and unlisted from google.

See https://github.com/MicrosoftDocs/feedback/issues/114#issuecomment-398951559

**Request:**

Please release the documentation that has been archived to the community under an open-source license.

**Comment by ghuntley** [comment]
The scope of this request is _just_ system.reactive MSDN documentation.

**Comment by phenomx2** [comment]
Any news about this ?

**Comment by nhwilly** [comment]
As someone waaaay down the food chain, this would be a huge help.

**Comment by dend** [comment]
Hi folks,

We are looking at what is the correct path with this specific request - we will update this thread once more information becomes available from various teams that are part of the conversation.

**Comment by cabauman** [comment]
Thanks, I would love for this to happen as well.

**Comment by dend** [comment]
Closing this item, as we collaborate with @terrajobst and got it done 🎉

https://github.com/MicrosoftDocs/dotnet-archive

Thank you all!

**Comment by ghuntley** [comment]
Thankyou @dend
