### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by tshaiman** [MicrosoftDocs/feedback#584]
**Describe the bug**
The links at : 
https://docs.microsoft.com/en-us/azure/app-service/containers/
are broken when you try to click on 
.NET Core with Azure SQL DB
or
Node.js with MongoDB tutorials
you get 404 Page not found

**To Reproduce**
1. Go to 'https://docs.microsoft.com/en-us/azure/app-service/containers/'
2. Click on item #1 on the list '.NET Core with Azure SQL DB'
3. you are getting 404 Error

**Expected behavior**
Directing to the right Tutorial URL

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by EdisonDa** [comment]
@dend assign this one to you, and we should update the link "azure/app-service/containers/tutorial-dotnetcore-sqldb-app" to "tutorial-dotnetcore-sqldb-app".

**Comment by dend** [comment]
@EdisonDa this is related to App Service, therefore the correct owner here is @cephalin

**Comment by cephalin** [comment]
@EdisonDa This is fixed now. Thank you for reporting. #please-close

**Comment by EdisonDa** [comment]
Thank you @dend and @cephalin. Please @tshaiman verify, thank you for your reporting. I am close the issue now.
