### ISSUE TITLE
Typo in SCOM documentation

### ISSUE THREAD

**Issue by Ten-Aus** [MicrosoftDocs/feedback#586]
There appears to be a typo here: https://docs.microsoft.com/en-us/system-center/scom/manage-console-standard-views?view=sc-om-1807

Under the Microsoft Audit collection Services (folder) subheading.

The word 'vew' is used twice which I believe should be view.

Regards,

Ten

**Comment by EdisonDa** [comment]
@sudeepku, do you know who is working on this?  I created a PR for this typo change, could you please review?

**Comment by EdisonDa** [comment]
My PR has been accepted, and the issue get fixed. Thank you @Ten-Aus for your reporting. I am closing the issue now.
