### ISSUE TITLE
Replace hardcoded en-us links with language neutral versions

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/feedback#587]
**Is your feature request related to a problem? Please describe.**
Because the language code is hard coded in many links (EX: https://github.com/search?q=org%3AMicrosoftDocs+docs.microsoft.com%2Fen-us%2F&unscoped_q=docs.microsoft.com%2Fen-us%2F) users don't get redirected to their localizations

**Describe the solution you'd like**
Do a simple find/replace of `https://docs.microsoft.com/en-us/` with `/` and update your styleguide to discourage the use of language IDs in URLs

**Describe alternatives you've considered**
Doing the replacement of `https://docs.microsoft.com/en-us/` with `https://docs.microsoft.com/` will also work and enable clicking links on GitHub

**Additional context**
There are probably other hard coded language IDs that need to be replaced like `en-gb` and `en-in` that I've come across.

**Comment by EdisonDa** [comment]
@ShevaDas is this your area?

**Comment by dend** [comment]
This is great feedback. @EdisonDa I believe this is more of a content ask, and we need to make sure that we loop in content owners to address this. The locale requirement is clarified [here](https://docs.microsoft.com/en-us/contribute/how-to-write-links).
