### ISSUE TITLE
Some image links contain machine generated title attributes

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/feedback#588]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

**Link to article:**
Originally posted [here](https://github.com/MicrosoftDocs/vsts-docs/issues/1439), but this seems to be a general onboarding & cleanup issue so I've copied it to this repo

**Problem:**
The importer appears to add/keep poor/automated `title` attributes for image links

```markdown
 ![Toolbar for Query Results Web Part](_img/procguid_dashboardworkbook_toolbar.png "ProcGuid_DashboardWorkbook_Toolbar")  
```

Renders to 
```html
<img src="_img/procguid_dashboardworkbook_toolbar.png?view=tfs-2017" alt="Toolbar for Query Results Web Part" title="ProcGuid_DashboardWorkbook_Toolbar" data-linktype="relative-path" class="x-hidden-focus">
```
Note the `ProcGuid_DashboardWorkbook_Toolbar`

**Comment by dend** [comment]
@ShevaDas anything on the radar to use titles? If that's not the case, we should likely close this for now as I wouldn't expect many writers working in this area.

**Comment by ShevaDas** [comment]
Nothing on the radar right now that will utilize image titles. Lightboxed images on Docs are "titled" with the alt text. I'm going to close this for now, but thanks for the keen eye, @nschonni!

**Comment by nschonni** [comment]
OK, I think there is still probably a bug here for your importer scripts that will impact other repos onboarding, even if you're not going to cleanup the existing content.
