### ISSUE TITLE
Add the XML schema for VSCT files to the docs

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#59]
I can no longer find the schema for VSCT files in the docs

----------
⚠ Idea migrated from UserVoice

**Created By:** Paul van Brenk
**Created On:** 2017/12/12 19:33:51 +0000
**Votes at Migration:** 1
**Supporters at Migration:** 1

**Comment by Powerhelmsman** [comment]
Please go https://docs.microsoft.com/en-us/visualstudio/extensibility/vsct-xml-schema-reference
