### ISSUE TITLE
Long attribute is making API reference page too wide

### ISSUE THREAD

**Issue by svick** [MicrosoftDocs/feedback#590]
When I visit [the `AssemblyBuilder` page](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.emit.assemblybuilder?view=netframework-4.7.2) in .Net API reference, the page is too wide to fit into my non-fullscreen browser window because of the `[System.Runtime.InteropServices.ClassInterface(System.Runtime.InteropServices.ClassInterfaceType.None)]` attribute:

![](https://user-images.githubusercontent.com/287848/43858579-b08ce428-9b4e-11e8-804b-c3a893a4d241.png)

Notice the horizontal scrollbar and that the right-hand TOC is not fully visible.

I think this should be fixed.

**Comment by dend** [comment]
Thanks for the feedback, @svick - for longer attributes, this is a by-product of us not splitting them due to how they are structured. We'll take a look at how we can make this better.

**Comment by svick** [comment]
I also noticed a similar problem on [the `ArraySegment<T>` page](https://docs.microsoft.com/en-us/dotnet/api/system.arraysegment-1?view=netframework-4.7.2), where it seems to be caused by the code in the Example. I think such code used to show a horizontal scrollbar before, but not anymore.

Is that actually related, or should I open a new issue about that?

**Comment by dend** [comment]
Thanks again for the feedback, @svick - this bug should be now addressed.
