### ISSUE TITLE
Incorrect result in example

### ISSUE THREAD

**Issue by angelshrestha** [MicrosoftDocs/feedback#591]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

**Link to article:**
https://docs.microsoft.com/en-us/sql/t-sql/functions/charindex-transact-sql?view=sql-server-2017

**Problem:**
Result for section E should be 11 and not 13
******************************************************************************************
E. Performing a case-insensitive search
This example shows a case-insensitive search for the string 'TEST' in 'This is a Test'.

SQL

Copy

USE tempdb;  
GO  
SELECT CHARINDEX ( 'TEST',  
       'This is a Test'  
       COLLATE Latin1_General_CI_AS);  
GO  
Here is the result set.

Copy
-----------
13
**************************************************************************************

**Comment by EdisonDa** [comment]
Thank you @angelshrestha for your reporting. Verified the index function return 11 on my side too. Creating the PR to update the doc.

**Comment by EdisonDa** [comment]
Hi @angelshrestha , I am closing this issue now since it will be fixed when we have the fix.
