### ISSUE TITLE
Links not showing right

### ISSUE THREAD

**Issue by Giovasdf** [MicrosoftDocs/feedback#592]
the links dont show correctly in this page https://docs.microsoft.com/es-es/dynamics365/customer-engagement/gamification/help-hub

**Comment by EdisonDa** [comment]
Hi @Giovasdf , we have transferred the issue to https://github.com/MicrosoftDocs/dynamics-365-customer-engagement-pr.es-es/issues/13. Closing this one now.

**Comment by nschonni** [comment]
@EdisonDa that isn't a public repo

**Comment by Giovasdf** [comment]
@EdisonDa my area is es-es
