### ISSUE TITLE
Autoruns version listed incorrectly

### ISSUE THREAD

**Issue by ptilsen** [MicrosoftDocs/feedback#593]
**Link to article:**
https://docs.microsoft.com/en-us/sysinternals/downloads/autoruns

**Problem:**
Autoruns 13.90 is listed as the version, but the link is actually version 13.91.

**Comment by EdisonDa** [comment]
Hi @v-kents do you know who can help to confirm this content issue?

**Comment by EdisonDa** [comment]
Thank you @ptilsen . We have transferred the issue to https://github.com/MicrosoftDocs/sysinternals/issues/107. Closing this now.
