### ISSUE TITLE
Question: How can someone easily find the docs.microsoft.com link from a GitHug page?

### ISSUE THREAD

**Issue by rajbos** [MicrosoftDocs/feedback#594]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I am on the GitHub repo and cannot find the document on docs.microsoft.com. This happened again this week and even resulted in me opening an issue that wasn't really an [issue](https://github.com/MicrosoftDocs/azure-docs/issues/12769)

Somehow I find the GitHub repo first and then want to view it on docs.microsoft.com. Maybe there already is a faster way to accomplish this? 

**Describe the solution you'd like**
Include a link in the yaml(?) header of the md files? 

**Describe alternatives you've considered**
None, really

**Comment by EdisonDa** [comment]
Hi @rajbos , normally the docs in GitHub has a ReadMe.md which provide the docs link. Also you can go to docs.microsoft.com for searching. Hope this helps.
