### ISSUE TITLE
"In this article" list limited to window height

### ISSUE THREAD

**Issue by chrullrich** [MicrosoftDocs/feedback#595]
**Describe the bug**
The "In this article" TOC does not scroll with the page. This is helpful for pages with few headings, but makes it useless in large parts on pages with many headings.

**To Reproduce**
1. Go to https://docs.microsoft.com/en-us/cpp/mfc/reference/cwnd-class .
2. Click on the link for `CWnd::OnCreate` in the "In this article" column.
3. Let me have whatever screen you are using, because it is awesome.

**Expected behavior**
The TOC should scroll with the page like any normal content, rather than staying nailed to the top of the viewport and limiting its usefulness to the links that fit into the window.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 68

**Comment by EdisonDa** [comment]
@ShevaDas , is this your area?

**Comment by ShevaDas** [comment]
Yes, this is my area. I'll file a bug with our engineering team. 

#log-suggestion

**Comment by Powerhelmsman** [comment]
#log-suggestion @ShevaDas

**Comment by botcrane** [comment]
🚀 **ATTENTION**: [Internal request](https://ceapex.visualstudio.com/web/wi.aspx?pcguid=7d644393-99ad-41c8-ac53-7fa79294c720&id=35008) logged.

**Comment by dend** [comment]
The fix to this item has shipped! Thank you for the feedback, @chrullrich!
