### ISSUE TITLE
Search Broken for Uppercase Characters

### ISSUE THREAD

**Issue by fallingfrog** [MicrosoftDocs/feedback#599]
# Search Broken for EConnect Documentation

Using the search box on this page: 
https://docs.microsoft.com/en-us/previous-versions/dynamicsgp/developer/hh686187(v%3dgp.20)

only gives results if all your search terms are lowercase, even when the matches are uppercase or mixed case.

**Comment by Powerhelmsman** [comment]
@presleyy Can you take a look at this issue?

**Comment by presleyy** [comment]
Yes, I'm aware of this. Actually we had a [bug](https://ceapex.visualstudio.com/Engineering/_workitems/edit/33226) created for the same problem. The fixing is waiting to be deployed and verified. I will update it here.

**Comment by presleyy** [comment]
The bug has been fixed. @fallingfrog would you please double check it in your environment? Thanks in advance!
