### ISSUE TITLE
Give full documentation for the different versions of bitmap headers

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#60]
As a bitmap management library developer, it would be extremely useful to have access to clear documentation describing the BITMAPV2INFOHEADER and BITMAPV3INFOHEADER. The current documentation seems to skip it for no obvious reason: https://msdn.microsoft.com/en-us/library/dd183376(VS.85).aspx

----------
⚠ Idea migrated from UserVoice

**Created By:** Careful Now
**Created On:** 2017/12/12 02:19:09 +0000
**Votes at Migration:** 1
**Supporters at Migration:** 1

**Comment by Powerhelmsman** [comment]
@ginami Is this something you can help?

**Comment by Powerhelmsman** [comment]
Close as no longer maintenance.

**Comment by SamB** [comment]
<https://docs.microsoft.com/en-us/windows/desktop/api/wingdi/ns-wingdi-bitmapinfoheader> seems like it probably *ought* to be the successor of <https://msdn.microsoft.com/en-us/library/dd183376(VS.85).aspx>, based on it's path and location in the outline, but for some reason it's actually using content that appears to have come from DirectShow documentation.  Maybe after you fix *that* issue (apparently, there's no repository for us to submit a fix to?) you could (beg one of the old-timers to) fix this one?
