### ISSUE TITLE
"WSL docs" and "WSL learning resources page" links point to the same place

### ISSUE THREAD

**Issue by FonzieBear** [MicrosoftDocs/feedback#600]
# Idea Title

Doc URL: https://docs.microsoft.com/en-us/windows/wsl/initialize-distro

## Issue Details

Both links (which are side-by-side) point to https://blogs.msdn.microsoft.com/commandline/learn-about-windows-console-and-windows-subsystem-for-linux-wsl/

**Comment by EdisonDa** [comment]
@bitcrazed is this your area?

**Comment by bitcrazed** [comment]
It is - thanks for the ping @EdisonDa, and for filing this @FonzieBear - just submitted a PR to fix.

**Comment by Powerhelmsman** [comment]
@FonzieBear The issue is resolved.
