### ISSUE TITLE
VSTS API Create BuildProcess

### ISSUE THREAD

**Issue by abbgrade** [MicrosoftDocs/feedback#603]
In the [VSTS API documentation, at Build/Definition/Create](https://docs.microsoft.com/en-us/rest/api/vsts/build/definitions/create?view=vsts-rest-4.1#buildprocess) the BuildProcess type is incomplete.

In the documentation it has only one property: type.
On calling POST https://xy.visualstudio.com/ab/_apis/build/definitions?api-version=4.1
The result is "The array must contain at least one element.\r\nParameter name: phases".
The phases and steps are undefined.

Thanks
Steffen

**Comment by wnjenkin** [comment]
@abbgrade I've transfered this issue to the VSTS docs repo. Please track updates using this link - https://github.com/MicrosoftDocs/vsts-rest-api-specs/issues/78

**Comment by Powerhelmsman** [comment]
@abbgrade I will close it as transferred.
