### ISSUE TITLE
Global Bookmarks for Docs

### ISSUE THREAD

**Issue by DenBir** [MicrosoftDocs/feedback#604]
Unfortunately, I did not find any other way for feedback for Docs. That's why the GitHub entry.

I missed in Docs the bookmark function. I read the docs for several products.
It would be great if you could put bookmarks in the docs. Ideally with its own comment function. So one could fall back quickly and purposefully on important Docs articles.

**Comment by Powerhelmsman** [comment]
@DenBir Thanks for your suggestion.  @ShevaDas is this your area?

**Comment by ShevaDas** [comment]
@DenBir Thanks for the feedback. Could you clarify why browser bookmarks aren't sufficient for this purpose?

**Comment by DenBir** [comment]
@ShevaDas 

I would think of Docs as a large interactive library. Of course you can simply set the bookmarks via the browser and I would probably have done so 10 years ago. But as a current Microsoft Docuemntationsplatform I imagine more of it.

Examples:
I log in with my Microsoft account and very directly all the bookmarks that I put in the most diverse Docs articles. There I would also recognize when the articles were revised. From there I can jump directly into the respective docs article.
I can put or mark comments for me that are very important to me and that I can quickly find right back in my Docs area.
I can rate the articles.
I see a ranking, which article I like the most.
I see a ranking which is the most popular article currently.

That would be so spontaneous a few approaches.

**Comment by ShevaDas** [comment]
We've put that request into our internal backlog. (Internal ID for VSTS is 35179)

tag @sharriexie

**Comment by DenBir** [comment]
I'm curious to see what happens.

**Comment by shirgoldbird** [comment]
Hi @DenBir, I'm pleased to announce that this feature has been added: https://docs.microsoft.com/en-us/teamblog/announcing-bookmarks

Hope you enjoy!
