### ISSUE TITLE
Set favorites web page is not available. (404)

### ISSUE THREAD

**Issue by BoiarynovQA** [MicrosoftDocs/feedback#606]
Description
as a user, i can't start using your tutorials ((( set favorites tab is not available 

STR:
1. Go to https://docs.microsoft.com/en-us/vsts/user-guide/?view=vsts and navigate to Step-by-Step Tutorials article 
2. Click on link 'Set favorites'

Expected behavior
web page with content is opened.

Screenshot
![404](https://user-images.githubusercontent.com/28347256/44138913-21dbfbbc-a07e-11e8-8522-3992edfa18eb.png)

Desktop
 - OS: [Windows]
 - Browser [chrome]
 - Version [latest]

stranges:
this web page is opened in ru locale, but i use en-us locale.

**Comment by Powerhelmsman** [comment]
@BoiarynovQA Your issue is transferred to vsts team. They will help you there.
