### ISSUE TITLE
Spell check on Write Filters

### ISSUE THREAD

**Issue by agamagtdM10102148** [MicrosoftDocs/feedback#608]
**Link to article:** 
https://docs.microsoft.com/en-us/previous-versions/windows/embedded/ff769914(v%3dwinembedded.60)

**Problem:**
Spell of EWFMGR.ESE should be EWFMGR.EXE in the "File-Based Write Filter (FBWF)" paragraph.

**Comment by Powerhelmsman** [comment]
@agamagtdM10102148 Thanks for your feedback. Unfortunately the content is no longer updating due to out of project lifecycle.
