### ISSUE TITLE
Scrollbar not visible API reference product selector for .Net Framework

### ISSUE THREAD

**Issue by svick** [MicrosoftDocs/feedback#609]
On my non-fullscreen browser window, when I use the product/version selector on an API reference page for .Net Framework (e.g. [`System.String`](https://docs.microsoft.com/en-us/dotnet/api/system.string?view=netframework-4.7.2)), the whole selector does not fit in the space it has, which means its scrollbar for versions is not shown. This makes it hard to figure out that more versions are actually available and to select them.

A screenshot:

![](https://user-images.githubusercontent.com/287848/44205560-15840380-a157-11e8-9ff5-5238e65a5312.png)

It works fine on a fullscreen window:

![](https://user-images.githubusercontent.com/287848/44205601-33516880-a157-11e8-87dc-c436fa5bb068.png)

I'm using Firefox 61 on Windows 10.

**Comment by Powerhelmsman** [comment]
@hellosnow moniker is your area, right? Can you follow up this bug?

**Comment by dend** [comment]
I'll take this, @Powerhelmsman 👍

**Comment by dend** [comment]
Thanks for the feedback, @svick - I've opened an [internal ticket](https://ceapex.visualstudio.com/Engineering/_workitems/edit/36132) to track this work.

**Comment by dend** [comment]
Thanks again for the feedback, @svick - this has been resolved.
