### ISSUE TITLE
Improvements to Product selector for .Net API browser

### ISSUE THREAD

**Issue by svick** [MicrosoftDocs/feedback#610]
I think there are several things in the Product selector in [the .Net API browser](https://docs.microsoft.com/en-us/dotnet/api/) that could be improved:

1. Using it should not cause overflow:

    ![](https://user-images.githubusercontent.com/287848/44205774-d7d3aa80-a157-11e8-9c18-a63d2a726171.png)

    Notice that there is plenty of space below, so there is no need for the scrollbar.

2. There are many Products in the list, there should be at least some form of search for the right product.

3. If a Product has only one version (e.g. Roslyn only has Latest), I shouldn't have to select that version. It's an unnecessary click.

**Comment by Powerhelmsman** [comment]
@dend Can you take a look at this suggestion?

**Comment by dend** [comment]
#log-issue @dend

Good feedback, thanks @svick!

**Comment by dend** [comment]
#log-suggestion @dend

**Comment by botcrane** [comment]
🚀 **ATTENTION**: [Internal request](https://ceapex.visualstudio.com/web/wi.aspx?pcguid=7d644393-99ad-41c8-ac53-7fa79294c720&id=36131) logged.

**Comment by dend** [comment]
Following-up on the item - given that we are tracking the item internally, and there is no definitive timeline assigned to the improvement, I am going to resolve the issue. We will continue working with our engineering team to make sure that the improvements are accounted for in our planning cycle.

@svick as always, appreciate your detailed and on-point suggestions!
