### ISSUE TITLE
Document ENABLE_PARALLEL_PLAN_PREFERENCE

### ISSUE THREAD

**Issue by MitchMcBride** [MicrosoftDocs/feedback#611]
Microsoft support has stated that it officially supports the ENABLE_PARALLEL_PLAN_PREFERENCE query hint, which was released with SQL Server 2016 SP1 CU2, but its usage is not documented.  Please consider adding it to https://docs.microsoft.com/en-us/sql/t-sql/queries/hints-transact-sql-query

**Comment by Powerhelmsman** [comment]
@MitchMcBride Your issue is transferred to comments on the bottom of the content. SQL team now use comment to triage the feedback. They will help you there.

**Comment by moh-hassan** [comment]
It's not documented yet since Aug 2018 and four years passed !!!.

check the page: [Hints (Transact-SQL) - Query](https://docs.microsoft.com/en-us/sql/t-sql/queries/hints-transact-sql-query?view=sql-server-2016)
