### ISSUE TITLE
Some wrong lines in the last changelog page (15.8 update)

### ISSUE THREAD

**Issue by Ci5co** [MicrosoftDocs/feedback#613]
NOTE: I did not find the **comment section for the article** even after logging in with my Microsoft Account

After reading most of the changes from the last update for VS 2017 CE ([15.8](https://docs.microsoft.com/en-us/visualstudio/releasenotes/vs2017-relnotes#whats-new-in-158)), I found 2 wrong descriptions:

1. under the [productivity](https://docs.microsoft.com/en-us/visualstudio/releasenotes/vs2017-relnotes#productivity) changes, it is mentioned the way to access _two new keyboard profiles for keybindings_ through  

> Tools > Options > General > Keyboard and the top drop-down menu. 

but instead of that the correct route is 

> Tools > Options > Environment > Keyboard

![vs2017 15 8 - access two new keybinding schemas](https://user-images.githubusercontent.com/23027643/44257722-3018b400-a20d-11e8-976b-8a77a025d5cf.png)

2. under the [ESLint Improvements](https://docs.microsoft.com/en-us/visualstudio/releasenotes/vs2017-relnotes#eslint-improvements), it was written a word twice:

> We reimplemented ESLint support for this release. ESLint has the **following following** improvements and enhancements:

**Comment by Powerhelmsman** [comment]
@Ci5co Thanks for your feedback. I sent email to author. She will response it ASAP.

**Comment by Powerhelmsman** [comment]
@Ci5co The issue is fixed. Please double check.

**Comment by Ci5co** [comment]
Yes, both of them are fixed.
