### ISSUE TITLE
"In this article" links do not work in Edge

### ISSUE THREAD

**Issue by bogdan-mabo** [MicrosoftDocs/feedback#614]
"In this article" links do not work in Edge browser

1. Go to 'https://docs.microsoft.com/en-us/dotnet/csharp/' [or similar]
2. Try to click on the links in "In this article" section

The links should scroll to the corresponding section in the document

 - OS: Windows 10 Pro 1803
 - Browser: Edge
 - Version: 42.17134.1.0

**Comment by Powerhelmsman** [comment]
@bogdan-mabo I can't repro your issue.  In the csharp page, "How the C# guide is organized" and "See also" can be clickable.

**Comment by bogdan-mabo** [comment]
Now it works for me too.
I am pretty sure I tried several time, I reloaded the page, restarted the browser and tried to use DevTools to see if there is anything on top of that list. Nothing worked.

But now it works as expected.
So sorry for wasting your time.
