### ISSUE TITLE
ASP.Net Core Tutorial Missing code sample in localization version

### ISSUE THREAD

**Issue by EdisonDa** [MicrosoftDocs/feedback#619]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

**Link to article:**
Tell us where exactly a problem occurs.
1. Go to page https://docs.microsoft.com/zh-cn/aspnet/core/tutorials/razor-pages/new-field?view=aspnetcore-2.1

**Problem:**
What's wrong with the article?
No C# code found in zh-cn, see screenshot. But it exists in en-us.
![capture](https://user-images.githubusercontent.com/10289595/44304978-e3fd7900-a39e-11e8-8eda-0d65fe16bc36.PNG)

More information: 
When switching to en-us, it was "razor-pages-start/sample/RazorPagesMovie21/Models/MovieDateRating.cs?highlight=13&name=snippet" in content page. However, it was "razor-pages-start/sample/RazorPagesMovie/Models/MovieDateRating.cs?highlight=11&range=7-18" in zh-cn.

**Comment by Powerhelmsman** [comment]
@SonjaSaltzman Can you follow up this localization issue?

**Comment by SonjaSaltzman** [comment]
@nokura could you please follow up?

**Comment by SonjaSaltzman** [comment]
@nokura @JasonCard has this been addressed? Please comment and close.

**Comment by JasonCard** [comment]
@EdisonDa @Powerhelmsman @SonjaSaltzman @nokura 
Confirmed this issue has been resolved, so closing.
