### ISSUE TITLE
Ansible

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#62]
Add some documentation around configuring windows with Ansible and DSC

----------
⚠ Idea migrated from UserVoice

**Created By:** Phillip Skentelbery
**Created On:** 2017/12/09 14:53:20 +0000
**Votes at Migration:** 1
**Supporters at Migration:** 0

**Comment by Powerhelmsman** [comment]
Please use Docs site search function to find Ansible and DSC related documentation.
