### ISSUE TITLE
DAX section started but incomplete

### ISSUE THREAD

**Issue by residentx10** [MicrosoftDocs/feedback#620]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

**Link to article:**
https://msdn.microsoft.com/en-us/query-bi/dax/dax-error-the-calculation-could-not-be-completed

**Problem:**
Article was started but not completed.

**Comment by Powerhelmsman** [comment]
@residentx10 Thanks for your feedback. Your article is MSDN site, in stead of Docs site. Is this link from one page of Docs content? If yes, can you provide the Docs site link?

**Comment by Powerhelmsman** [comment]
@residentx10 I will close this issue so far due to without enough information. If you have other question related to this we can reopen it to continue the discussion.
