### ISSUE TITLE
wrong word in regex documentation

### ISSUE THREAD

**Issue by dmparrishphd** [MicrosoftDocs/feedback#621]
**Link to article:**
https://docs.microsoft.com/en-us/previous-versions/visualstudio/design-tools/expression-studio-3/cc295435(v=expression.10)

**Problem:**
The number sign (#) is mistakenly called the "sharp sign." The number sign is also called the "pound sign" or "hash tag," but the best name for it in the context of these regular expressions is the "number sign," since it refers to a count. See also https://en.wikipedia.org/wiki/Number_sign .

**Comment by Powerhelmsman** [comment]
@dmparrishphd Thanks for your feedback. Unfortunately the content is no longer updating due to out of product lifecycle.

**Comment by dmparrishphd** [comment]
Ok. I actually stumbled upon the site looking for a complete description of the regex for Word (Office 365). Do you know where I can find that?

Thanks,

Michael
D. Michael Parrish, PhD, PE | Engineering Specialist 4 | Water Supply Bureau, Resource Evaluation Section, Groundwater Modeling Unit | x2815

**Comment by Powerhelmsman** [comment]
@dmparrishphd I often refer to https://docs.microsoft.com/en-us/dotnet/standard/base-types/regular-expression-language-quick-reference to get the full regular expression reference.

**Comment by dmparrishphd** [comment]
Thanks,

Michael

D. Michael Parrish, PhD, PE | Engineering Specialist 4 | Water Supply Bureau, Resource Evaluation Section, Groundwater Modeling Unit | 561-682-2815
Florida enjoys a broad public records law—any emails sent to or from this address are subject to review by the public at any time.
