### ISSUE TITLE
 H1 title overlap with in-page navigation column 

### ISSUE THREAD

**Issue by mairaw** [MicrosoftDocs/feedback#622]
Original GitHub issue https://github.com/dotnet/docs/issues/7175 from @zhiliangxu

https://docs.microsoft.com/en-us/dotnet/api/system.func-17?view=netframework-4.7.2
Title is long: Func&lt;T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14,T15,T16,TResult&gt;
It overlaps with "in this article"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d95cd525-746d-313d-b7f9-4d442d2319df
* Version Independent ID: 930861a9-778b-7428-f582-58043958e890
* Content: [Func&lt;T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14,T15,T16,TResult&gt; Delegate (System)](https://docs.microsoft.com/en-us/dotnet/api/system.func-17?view=netframework-4.7.2)
* Content Source: [xml/System/Func`17.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System/Func`17.xml)
* Product: **dotnet-api**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by dend** [comment]
#log-suggestion

**Comment by botcrane** [comment]
🚀 **ATTENTION**: [Internal request](https://ceapex.visualstudio.com/web/wi.aspx?pcguid=7d644393-99ad-41c8-ac53-7fa79294c720&id=36436) logged.

**Comment by dend** [comment]
@mairaw the bug should be fixed - I triggered a full content rebuild to validate that.

**Comment by Powerhelmsman** [comment]
@dend it works fine on Chrome browser but doesn't work on Edge.

**Comment by dend** [comment]
@Powerhelmsman the content is still being re-built on the live branch, so I can't tell yet whether the fix is propagated.

**Comment by dend** [comment]
This issue has been fixed, and the header renders properly. Thank you all for the feedback!
