### ISSUE TITLE
Improve documentation for RequestHeaders.Get(String) Method

### ISSUE THREAD

**Issue by StevenLiekens** [MicrosoftDocs/feedback#626]
I couldn't find the comment section for this article so consider this a comment.

**Link to article:**
https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.headers.requestheaders.get?view=aspnetcore-2.1#Microsoft_AspNetCore_Http_Headers_RequestHeaders_Get__1_System_String_

**Problem:**
There is no good documentation for `RequestHeaders.Get<T>(string): T`. I tried using it and thought I could substitute `T` with anything I want, like `string`. That turned out not to work.

`var myHeader = requestHeaders.Get<string>("X-My-Header");`

I found out the hard way that there is an implicit constraint on `T`: it needs to be a type with a static `TryParse` method.

> System.NotSupportedException: 'The given type 'T' does not have a TryParse method with the required signature 'public static bool TryParse(string, out T).'

That should be documented.

**Comment by dend** [comment]
This should be addressed by the ASP.NET team - FYI @danroth27 @Rick-Anderson

**Comment by StevenLiekens** [comment]
@Rick-Anderson 

```md
I couldn't find the comment section for this article so consider this a comment.

**Link to article:**
https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.headers.requestheaders.get?view=aspnetcore-2.1#Microsoft_AspNetCore_Http_Headers_RequestHeaders_Get__1_System_String_

**Problem:**
There is no good documentation for `RequestHeaders.Get<T>(string): T`. I tried using it and thought I could substitute `T` with anything I want, like `string`. That turned out not to work.

`var myHeader = requestHeaders.Get<string>("X-My-Header");`

I found out the hard way that there is an implicit constraint on `T`: it needs to be a type with a static `TryParse` method.

> System.NotSupportedException: 'The given type 'T' does not have a TryParse method with the required signature 'public static bool TryParse(string, out T).'

That should be documented.
```

**Comment by Powerhelmsman** [comment]
@StevenLiekens @Rick-Anderson This issue is transferred to aspnet/home repo. Please go there to track the status.
