### ISSUE TITLE
Spelling mistake. Word **improvement** spelled as improvment.

### ISSUE THREAD

**Issue by madiathomas** [MicrosoftDocs/feedback#627]
# Spelling mistake. Word improvement spelled as improvment

Spelling mistake. Word **improvement** spelled as improvment.

## Issue Details

Spelling mistake on the visual Studio roadmap page -> https://docs.microsoft.com/en-us/visualstudio/productinfo/vs2018-roadmap.

![spelling mistake](https://user-images.githubusercontent.com/24851445/44524172-c1d86380-a6dc-11e8-89d8-4502d9de8e8e.JPG)

**Comment by Powerhelmsman** [comment]
@madiathomas Thanks for your feedback. I've informed the author. They will fix it ASAP.

**Comment by Powerhelmsman** [comment]
@madiathomas The issue is fixed.
