### ISSUE TITLE
404 for the Set-AddressList Exchange Powershell documentation

### ISSUE THREAD

**Issue by kamackill** [MicrosoftDocs/feedback#628]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

**Link to article:**
https://docs.microsoft.com/en-us/powershell/module/exchange/email-addresses-and-address-books/set-addresslist

**Problem:**
404 error when visiting this page

**Comment by Powerhelmsman** [comment]
@kamackill Thanks for reporting the issue. May I know where do you get the link?

**Comment by kamackill** [comment]
I got a 404 error being referred from Google Search results to multiple docs pages earlier today. The links seem to be working now. Thanks for the response.
