### ISSUE TITLE
The image have an unrelated text.

### ISSUE THREAD

**Issue by blackfoxsar** [MicrosoftDocs/feedback#629]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

**Link to article:**
https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/overview/whats-new-active-directory-federation-services-windows-server

**Problem:**
The image have an unrelated text.

![adfs_itpro4](https://user-images.githubusercontent.com/15705262/44567759-dd13a380-a7ae-11e8-8157-14aa56dd49c1.png)

There have a "Text". (*^_^*)

**Comment by Powerhelmsman** [comment]
@billmath Can you take a look at this issue?

**Comment by Powerhelmsman** [comment]
@blackfoxsar I transferred this issue to windowsserverdocs team. They will help you there.
