### ISSUE TITLE
[Question] Information on what powers the overall docs site?

### ISSUE THREAD

**Issue by bestekov** [MicrosoftDocs/feedback#630]
The docs.microsoft.come site has a pretty slick integration with github! Is there a repo for the overall wrapper site and/or information about how one could replicate a similar kind of documentation website? I'm interested in using this sort of approach in an internal company documentation library.

**Comment by dend** [comment]
Hi @bestekov - the entire infrastructure is not currently available for consumption, however you can get pretty close by creating your own DocFX-based environment. I've written a [blog post](https://aka.ms/iwantdocs) on this topic, that hopefully unblocks you.
