### ISSUE TITLE
NetHttpBinding shown as available for Xamarin, but it is not implemented. 

### ISSUE THREAD

**Issue by jgold6** [MicrosoftDocs/feedback#633]
Using the [.NET API Browser](https://docs.microsoft.com/en-us/dotnet/api/), if you select Xamarin.Android, Xamarin.iOS, or Xamarin.Mac and [search for NetHttpBinding](https://docs.microsoft.com/en-us/dotnet/api/?view=xamarinios-10.8&term=NetHttpBinding), it will show as available, but this is [not implemented in Mono ](https://github.com/mono/mono/blob/master/mcs/class/System.ServiceModel/System.ServiceModel/NetHttpsBinding.cs) and since Xamarin platforms are based n the [silverlight subset of .NET, which does not have NetHttpBinding available](https://docs.microsoft.com/en-us/previous-versions/windows/silverlight/dotnet-windows-silverlight/ms195526%28v%3dvs.95%29), it is expected that it should not be available in Xamarin.iOS, etc. 

**Link to article:**
https://docs.microsoft.com/en-us/dotnet/api/?view=xamarinios-10.8&term=NetHttpBinding
https://docs.microsoft.com/en-us/dotnet/api/?view=xamarinandroid-7.1&term=NetHttpBinding
https://docs.microsoft.com/en-us/dotnet/api/?view=xamarinmac-3.0&term=NetHttpBinding

**Problem:**
NetHttpBinding class shown as available in Xamarin.iOS, Xamarin.Android, and Xamarin.Mac when it is not.

**Comment by dend** [comment]
@joelmartinez @conceptdev can you comment on this? Is this something that we need to address?

**Comment by conceptdev** [comment]
Interesting case - the class [_exists_](https://github.com/mono/mono/blob/master/mcs/class/System.ServiceModel/System.ServiceModel/NetHttpBinding.cs) , and the [ecmaxml exists](https://github.com/mono/mono/blob/master/mcs/class/System.ServiceModel/Documentation/en/System.ServiceModel/NetHttpBinding.xml#L2), so I can see why the tooling emitted docs.

However, the class throws `NotImplemented` and has a [`MonoTODO` attribute](https://github.com/mono/mono/blob/master/mcs/class/System.ServiceModel/System.ServiceModel/NetHttpBinding.cs#L30). Maybe something we need to special-case?

I tested about a dozen other random classes adorned with that attribute, but none of them exist in the reference docs (probably relating to other ways mono code is excluded from Xamarin SDKs?), so it's unclear to me how this slipped through.

**Comment by absinghal** [comment]
Can we implement the class in line with the content?

Here's the case for implementing NetHttpBinding:
https://github.com/mono/mono/issues/10344

Thanks

**Comment by Powerhelmsman** [comment]
@dend @conceptdev Please take a look at users' response.

**Comment by joelmartinez** [comment]
There's another issue (here: https://github.com/mono/api-doc-tools/issues/147) that loosely deals with this same issue of some functionality being unavailable on some platforms/frameworks. Although that particular issue is slightly different, I think it might be related in that we should consider adding some tooling to indicate when an API's implementation will raise either an `PlatformNotSupportedException`, or `NotImplementedException`. 

If/When the Xamarin engineering team addresses that implementation is a separate matter ... but at least this way, the tooling can deal with this scenario.

**Comment by dendeli-msft** [comment]
Going to close the issue for now, since at least from the documentation infrastructure perspective, we are correctly identifying the entity.

Den Delimarsky ● Senior PM, docs.microsoft.com ● [@DennisCode](https://twitter.com/DennisCode)
