### ISSUE TITLE
In .Net API Browser allow to give feedback for individual pages

### ISSUE THREAD

**Issue by michael-freidgeim-webjet** [MicrosoftDocs/feedback#634]
Some time ago most of MS docs pages were enhanced with links in the footer "Product Feedback"/  "Content Feedback".
However articles in .Net API Browser (e.g.
https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.logging.debugloggerfactoryextensions.adddebug?view=aspnetcore-2.1#Microsoft_Extensions_Logging_DebugLoggerFactoryExtensions_AddDebug_Microsoft_Extensions_Logging_ILoggingBuilder_) do not have such footer.

It will be better to have the ability in .Net API Browser to provide feedback for individual pages.

**Comment by Powerhelmsman** [comment]
@michael-freidgeim-webjet Thanks for your feedback. No feedback section under .Net API rerence is by design so far due to resource limitation temporary. When the team has enough resource, we do recommend them to enable it.
