### ISSUE TITLE
A typo error in https://docs.microsoft.com/en-us/rest/api/compute/virtualmachines/listall?

### ISSUE THREAD

**Issue by celinama** [MicrosoftDocs/feedback#635]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

**Link to article:**
https://docs.microsoft.com/en-us/rest/api/compute/virtualmachines/listall
**Problem:**
Specifies the size of an empty data disk in gigabytes. This element can be used to overwrite the name of the disk in a virtual machine image. 

Should it be overwrite the size of the disk instead of the name of the disk?

**Comment by Powerhelmsman** [comment]
@erickson-doug @hellosnow  Can you take a look at this typo?

**Comment by hellosnow** [comment]
@celinama thanks for the feedback, I open an issue on Azure swagger repo https://github.com/Azure/azure-rest-api-specs/issues/3756 to check their update, the sentense comes from https://github.com/Azure/azure-rest-api-specs/blob/master/specification/compute/resource-manager/Microsoft.Compute/stable/2017-12-01/compute.json#L5406.
