### ISSUE TITLE
Microsoft Docs site does not work with javascript disabled and previous version now has a 404 error

### ISSUE THREAD

**Issue by jlagden** [MicrosoftDocs/feedback#638]
Not sure if this is really a bug or a feature, but the site will not work at all with javascript disabled.

To reproduce go to https://docs.microsoft.com/en-gb/ and select a section of the docs

I would have expected the site to use a [Progressive enhancement](https://en.wikipedia.org/wiki/Progressive_enhancement) strategy so you would to be able to search the APIs without javascript and just have the extra features like autocomplete disabled.

![docs1](https://user-images.githubusercontent.com/23438837/44710483-c1084e80-aa9b-11e8-84c7-8d1cad302639.png)
![docs2](https://user-images.githubusercontent.com/23438837/44710488-c36aa880-aa9b-11e8-850e-5044cad4f99b.png)

**Comment by Powerhelmsman** [comment]
@dastaffo Can you take a look at this issue?

**Comment by Jemash** [comment]
@jlagden -  Asp.NET landing page was taken down as the content is not ready. Are you having the same issues on other pages from https://docs.microsoft.com/en-us/previous-versions/ ?

**Comment by jlagden** [comment]
Ah, ok - The other pages on previous versions seem fine
