### ISSUE TITLE
az aks create is case sensitive when is comes to VM sku

### ISSUE THREAD

**Issue by sprab** [MicrosoftDocs/feedback#639]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

**Link to article:**
https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest#az-aks-create
Tell us where exactly a problem occurs.

**Problem:**
What's wrong with the article?
az aks create is case sensitive to the VM sku mentioned.
When we mention the vm size in all lower cases, it returns with the following error:

Error occurred in request., RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/615ff5fc-44cd-4e81-b419-47cad6ae2a4d/resourceGroups/aks5/providers/Microsoft.ContainerService/managedClusters/aks5?api-version=2018-03-31 (Caused by ResponseError('too many 500 error responses',))
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/requests/adapters.py", line 445, in send
    timeout=timeout

The documentation should clearly mention that the value passed in --node-vm-size is case sensitive.

**Comment by Powerhelmsman** [comment]
@EdisonDa Can you follow up this suggestion?

**Comment by Powerhelmsman** [comment]
@sprab Thanks for your suggestion. Your issue is transferred to author's team. They will follow up with you there.
