### ISSUE TITLE
Move all the categories to Hamburger to reduce scrolling on mobile

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#64]
I would suggest to move  all categories (windows, azure...) to a hamburger menu with a search bar on the top in the mobile version of the website.

----------
⚠ Idea migrated from UserVoice

**Created By:** Karthik Rao
**Created On:** 2017/12/09 00:20:46 +0000
**Votes at Migration:** 1
**Supporters at Migration:** 1

**Comment by kubeaver** [comment]
@Powerhelmsman this issue will be resolved when we launch the new single-stack UHF in a few months.
