### ISSUE TITLE
The Code  Cannot be downloaded

### ISSUE THREAD

**Issue by ZhouHelen** [MicrosoftDocs/feedback#640]
On this web page(https://docs.microsoft.com/zh-cn/aspnet/web-forms/overview/data-
access/introduction/creating-a-data-access-layer-cs),
 I want to download the code by clicking the link("下载示例应用程序或下载 PDF"),
 but it is not successful. What should I do?

**Comment by Powerhelmsman** [comment]
@ZhouHelen Thanks for your feedback. Your issue is transferred to Asp.Net team repo. They will help you there.
