### ISSUE TITLE
Python API Docs not working

### ISSUE THREAD

**Issue by michalmar** [MicrosoftDocs/feedback#643]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

**Link to article:**
https://docs.microsoft.com/en-us/python/api/overview/azure-machine-learning/textanalytics

**Problem:**
"404 not found" page appears

**Comment by Powerhelmsman** [comment]
@michalmar Thanks for your feedback. May I know where you get the link?

**Comment by dend** [comment]
This should now be addressed, apologies for the inconvenience!
