### ISSUE TITLE
Include UWP APIs in the .NET API Browser

### ISSUE THREAD

**Issue by ahidaka** [MicrosoftDocs/feedback#644]
**Describe the bug**
"Windows.Devices" is not included at ".NET API Browser".

**To Reproduce**
1. Go to https://docs.microsoft.com/en-us/dotnet/api/
2. Input 'Windows.Devices' into Search window with All APIs option.
3. No results found.

**Expected behavior**

**Screenshots**
![docs](https://user-images.githubusercontent.com/10113490/44852479-49eed800-ac9e-11e8-80bc-45911da2d134.png)

**Comment by Powerhelmsman** [comment]
@dend Can you take a look at this request?

**Comment by dend** [comment]
Yes, that is a known issue - the `Windows.Devices` namespace is part of UWP APIs, that are not included in the .NET API Browser. It is instead available [here](https://docs.microsoft.com/en-us/uwp/api/windows.devices).

There is already a feature request for UWP APIs to be included in the API Browser, tracked internally. I will rename this issue to be more descriptive of that goal.

**Comment by dend** [comment]
Following-up here - to make sure that the APIs are onboarded to the .NET API Browser, the UWP content engineering team needs to make some changes to the underlying content YAML, to ensure that we are able to distinguish between different content versions.

Given that we are not able to provide a concrete timeframe for this work at this time, I will resolve the issue as `by-design`. Please be assured that we are tracking the implementation of this feature internally.
