### ISSUE TITLE
Xamarin.Android in .Net API Browser isn't actual

### ISSUE THREAD

**Issue by ticotaco72** [MicrosoftDocs/feedback#645]
**Link to article: https://docs.microsoft.com/pl-pl/dotnet/api/?view=xamarinandroid-7.1**

Version 8.0 is already available for devs, but there's no documentation for it.

**Comment by conceptdev** [comment]
Answered in https://github.com/MicrosoftDocs/xamarin-docs/issues/726

**Comment by Powerhelmsman** [comment]
@ticotaco72 Since the issue is answered. I will close it here.
