### ISSUE TITLE
Text Analytics API

### ISSUE THREAD

**Issue by chandrapadil** [MicrosoftDocs/feedback#646]
Microsoft Azure Text Analytics API does not return the keyword **Angered**  in the Input text.

**Comment by Powerhelmsman** [comment]
@chandrapadil Can you provide the page link you refer to?

**Comment by chandrapadil** [comment]
Page Link : https://azure.microsoft.com/en-us/services/cognitive-services/text-analytics/

Input Text : almost a week broke my heart and angered me at the same time

Key-phrases returned by the API : week, heart, time

Issue : Key-phrase angered is not returned

**Comment by Powerhelmsman** [comment]
@chandrapadil Thanks for your feedback. This is not a Docs site issue. I created a feedback on feedback.azure.com https://feedback.azure.com/forums/34192--general-feedback/suggestions/35262409-text-analytics-api Please track the status there.
