### ISSUE TITLE
Microsoft.Extensions.Configuration.ConfigurationBuilder bad link

### ISSUE THREAD

**Issue by JonnMsft** [MicrosoftDocs/feedback#649]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

**Link to article:**
https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.configuration.configurationbuilder

**Problem:**
Searching for ConfigurationBuilder returns this link, but it is a bad link.

**Comment by Powerhelmsman** [comment]
@JonnMsft Where did you search the term, Docs site search, or API browser?

**Comment by dend** [comment]
@JonnMsft - this has now been addressed, and the link works as expected.
