### ISSUE TITLE
Add documentation for Microsoft Robotics Studio

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#65]
_No details provided._

----------
⚠ Idea migrated from UserVoice

**Created By:** Vincent Nwonah
**Created On:** 2017/12/09 00:14:40 +0000
**Votes at Migration:** 1
**Supporters at Migration:** 1

**Comment by dend** [comment]
#log-suggestion

**Comment by botcrane** [comment]
🚀 **ATTENTION**: [Internal request](https://ceapex.visualstudio.com/web/wi.aspx?pcguid=7d644393-99ad-41c8-ac53-7fa79294c720&id=20414) logged.

**Comment by dend** [comment]
Closing as this will be part of the migration.
