### ISSUE TITLE
API browser: navigating to an overload from search result is difficult 

### ISSUE THREAD

**Issue by mairaw** [MicrosoftDocs/feedback#650]
Original GitHub issue https://github.com/dotnet/docs/issues/7413 from @dasMulli 

Navigating to an overload that only exists in .NET Core 2.1 is impossible from search result as the framework switches from "all" in search to .NET 4.7.2 in the API browser.

Scenario:
* Search for Path.GetFullPath
* Click on the (String, String) overload
* Be disappointed that you get to a page that doesn't contain the (String, String) overload
* Know that this is only available in .NET Core 2.1 -> Switch the framework
* Now the entry for that method.

![getfullpath-search-ux](https://user-images.githubusercontent.com/6129250/44897546-5c97fa00-acfc-11e8-9e3d-ff5fce262158.gif)
PS: For some reason this gif doesn't play in Safari, but should play in Chrome.

**Comment by Powerhelmsman** [comment]
@dend Can you take a look at this issue?

**Comment by docs-product** [comment]
Thank you for the feedback! After assessing this request, we have decided that at this time we will not be implementing changes to overload navigation in the **All APIs** selection in the .NET API Browser. Given that this is non-blocking and the user can still reliably navigate to the overload from the page discovered through the API Browser, this will be a `wont-fix`.
