### ISSUE TITLE
是否可以提供其他开发语言（如csharp）的tsf输入法开发示例代码

### ISSUE THREAD

**Issue by am420250899a** [MicrosoftDocs/feedback#653]
现在的tsf框架示例项目 SampleIME是用c++开发的，但是c++的学习成本比较高，让有心从事输入法开发和创新的人们很难入门。如果可以提供一份其它语言的示例项目，如csharp项目，或者只将输入法核心功能部分独立出来，用其它更热门的语言来实现，我认为会促进输入法的发展。我也在做这方面的学习，但是c++成了我最大的障碍。

**Comment by dend** [comment]
Thank you for the feedback! Given that this feedback is related to content recommendations and not site functionality, the best way to address is to open a suggestion directly under the article to which it relates to - this ensures that the content owners can address it directly and in a timely manner.
