### ISSUE TITLE
XML documentation generated from docs should not contain docs-relative URLs

### ISSUE THREAD

**Issue by svick** [MicrosoftDocs/feedback#659]
**Describe the bug**

When looking at the XML documentation for an API that seems to have been generated from .Net API reference, such as netstandard.xml, I can see docs-relative URLs such as `~/docs/standard/base-types/regular-expression-options.md`, while I think it should point to the live URL for the article: https://docs.microsoft.com/dotnet/standard/base-types/regular-expression-options.

Specifically, netstandard.xml (from version 2.0.3 of the NETStandard.Library package) contains (reformatted):

```xml
<member name="F:System.Text.RegularExpressions.RegexOptions.Singleline">
  <summary>
    Specifies single-line mode. Changes the meaning of the dot (.) so it matches every
    character (instead of every character except \n). For more information, see the
    &quot;Single-line Mode&quot; section in the
    <see cref="~/docs/standard/base-types/regular-expression-options.md">
      Regular Expression Options</see> topic.</summary>
  <returns></returns>
</member>
```

Notice how the `<see cref>` contains a URL that does not make sense outside of the docs repo.

This content seems to come from [this line in dotnet/dotnet-api-docs](https://github.com/dotnet/dotnet-api-docs/blob/e60e235/xml/System.Text.RegularExpressions/RegexOptions.xml#L432).

**Expected behavior**

XML documentation contains links to live versions of linked articles.

Note that while there doesn't seem to be spec-approved way provide HTTP links in XML documentation, [ReSharper/Rider seems to accept `<a href>`](https://stackoverflow.com/a/32712435/41071), and there is a proposal to adopt `<see href>`: https://github.com/dotnet/csharplang/issues/1764, [which is also used by Sandcastle](http://ewsoftware.github.io/XMLCommentsGuide/html/983fed56-321c-4daf-af16-e3169b28ffcd.htm#ExternalRef).

**Screenshots**

This is how the XML documentation is currently presented in Rider, where the link is not very useful:

![](https://user-images.githubusercontent.com/287848/45046353-2f3daa00-b076-11e8-8003-a6c183b4d23b.png)
![](https://user-images.githubusercontent.com/287848/45046355-31076d80-b076-11e8-853c-ce28308ca520.png)

**Comment by Powerhelmsman** [comment]
@dend Can you take a look at this suggestion?

**Comment by Powerhelmsman** [comment]
@svick Your issue is transferred to .Net team. They will help you there.

**Comment by mairaw** [comment]
I'll check if this still repros on the latest builds but this is not a content issue but an engineering issue. So this is the correct repo for this if it's still an issue.
