### ISSUE TITLE
Allow searches via URL

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#66]
Allow searches via short URLs, e.g. docs.ms/IDisposable would trigger a search for IDisposable.

----------
⚠ Idea migrated from UserVoice

**Created By:** Eddy Young
**Created On:** 2017/12/08 23:48:23 +0000
**Votes at Migration:** 1
**Supporters at Migration:** 1

**Comment by dend** [comment]
This is already possible - simply use **docs.microsoft.com/dotnet/api/{your_fully_qualified_type}**
