### ISSUE TITLE
I see some [!code-csharp] error instead of example code 

### ISSUE THREAD

**Issue by de-elebit** [MicrosoftDocs/feedback#660]
**Describe the bug**

**To Reproduce**
1. Go to 'https://docs.microsoft.com/ko-kr/aspnet/core/tutorials/razor-pages/new-field?view=aspnetcore-2.1#adding-a-rating-property-to-the-movie-model'
2. See error where below title

**Expected behavior**
The error shows up that [!code-csharp] instead code.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser : chrome

**Additional context**

**Comment by SonjaSaltzman** [comment]
@nokura could you please follow up?

**Comment by nokura** [comment]
Thank you so much for your feedback @de-elebit. We are fixing the issue and get back to you when it is published.
Kind regards,
Microsoft DOCS International Team

**Comment by de-elebit** [comment]
@nokura Thank You!!

**Comment by nokura** [comment]
Hello @de-elebit 
We have published the fixed page to live. 
Thank you for your contribution to improve the content!
![gh-issue660-fix](https://user-images.githubusercontent.com/13804190/45642631-9d6a6f80-ba6d-11e8-8d45-7799b6bab816.PNG)

Microsoft C&E Localization Team
