### ISSUE TITLE
Some important files not found

### ISSUE THREAD

**Issue by gauravitm** [MicrosoftDocs/feedback#661]
TriviaDbContext was not found in the source due to which microsoft.data was not accesible in the entire project

**Comment by Powerhelmsman** [comment]
@gauravitm Can you provide more detail on what you are looking for, which page you are referring to?

**Comment by Powerhelmsman** [comment]
@gauravitm I will close this issue due to lack of enough information. If you have any other question related to this, we can reopen it and continue the conversation
