### ISSUE TITLE
Server Azure AD Administrators documentation incorrect.

### ISSUE THREAD

**Issue by r-fennell** [MicrosoftDocs/feedback#662]
**Describe the bug**
The REST API documentation for retrieving [Server Azure AD Administrators](https://docs.microsoft.com/en-us/rest/api/sql/serverazureadadministrators/listbyserver) states that the response expected is JSON format. However, unless the HTTP `Accept: application/json` Header is included the default response is actually XML.

I see in the [azure-sdk-for-ruby](https://github.com/Azure/azure-sdk-for-ruby/blob/f1160ec0e3193c0e1a1066776b415ee009f655a7/management/azure_mgmt_sql/lib/2014-04-01/generated/azure_mgmt_sql/server_azure_adadministrators.rb#L511) the `Content-Type` header is added.

**To Reproduce**
1. Perform API call to [GET Server Azure AD Administrators](https://docs.microsoft.com/en-us/rest/api/sql/serverazureadadministrators/listbyserver)

**Expected behavior**
Expected response format, per documentation, is JSON. Otherwise Documentation should be updated to detail default response as XML.

**Screenshots**
- N/A

**Desktop (please complete the following information):**
- N/A

**Smartphone (please complete the following information):**
 - N/A

**Additional context**

**Comment by Powerhelmsman** [comment]
@erickson-doug Can you take a look at this suggestion?

**Comment by erickson-doug** [comment]
this is for the aad devs. i don't own these docs; i'm just a placeholder name for the api doc autogen tooling. @Mike Tillman<mailto:Michael.Tillman@microsoft.com>  might know who to contact...

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by Powerhelmsman** [comment]
@erickson-doug Thanks for quick response. I sent a email to him to follow up.

**Comment by mtillman** [comment]
@Powerhelmsman This is in the SQL database REST API, which I don't own. I think your best bet will be @craigg-msft who manages the SQL doc team.

**Comment by Powerhelmsman** [comment]
@craigcaseyMSFT Can you response to the feedback?

**Comment by craigcaseyMSFT** [comment]
@Powerhelmsman  - I don't work in this space. Perhaps you were trying to message @craigg-msft?

**Comment by Powerhelmsman** [comment]
@craigg-msft Can you take a look at this issue?

**Comment by MightyPen** [comment]
@GithubMirek Hi Mirek, Have you any idea which PM/Dev team owns the REST APIs for "Azure AD Administrators"?

If yes, who?  We need them to consider this minor documentation change for the API.  Only the Dev can make this change.

Thanks.  MightyPen on GitHub (GeneMi at Msft).  2019/03/18

**Comment by MightyPen** [comment]
#please-close

I do not have a way of discovering who generates the underlying .DLL.

**Comment by craigg-msft** [comment]
@tysonn can you please close this?

**Comment by craigg-msft** [comment]
@Powerhelmsman please close
