### ISSUE TITLE
Add links to current documentation on msdn.microsoft.com

### ISSUE THREAD

**Issue by spottedmahn** [MicrosoftDocs/feedback#663]
**Is your feature request related to a problem? Please describe.**

I just Google `create dacpac` and the top result goes to MSDN 😢

![image](https://user-images.githubusercontent.com/14079228/45167336-f3fec080-b1c6-11e8-9b28-6377f56bf1a6.png)

Then when I'm on the page it says:

![image](https://user-images.githubusercontent.com/14079228/45167358-05e06380-b1c7-11e8-8a8e-1e9101d5a38f.png)

Ok, np, show the current documentation 😊  There's no link to the "maintained" documentation.

**Describe the solution you'd like**

- Help me get to the maintained version of the documentation
  - Give me a link
  - or some text on how to find the maintained version
- Improve SEO so the maintained documentation is the top Google link!

**Comment by Powerhelmsman** [comment]
@spottedmahn please try this link: https://docs.microsoft.com/en-us/sql/relational-databases/data-tier-applications/data-tier-applications?view=sql-server-2017  This one is in People also ask section. and the third link is Docs site. In the future, MSDN will shut down and majority of document will be migrated to Docs site. So please try docs.microsoft.com first.
