### ISSUE TITLE
"Net" command

### ISSUE THREAD

**Issue by l1coder** [MicrosoftDocs/feedback#667]
I cannot easily find any references to the "net" command on the Microsoft Docs site. I get much more results and easier to use reference material from a google search and other sites. To ensure no ambiguity, I am referring to the "net" command which can take as arguments the following, which is a small sample:

- account
- use
- user
- computer

Its a command/utility still available on Windows 10 and I believe it should be searchable via Microsoft Docs, even as a reference for older versions of Windows.

**Comment by Powerhelmsman** [comment]
@l1coder Can you tell us how you search the Net command? Using Docs site search, other search engineer? If you can provide snapshot, that would be great for us to identify the issue?

**Comment by l1coder** [comment]
Hey Jian,

No problem, let me do a search and give you the result shortly, thanks.

Regards,
Charles Lee Ying | Manager | Operations


Solutions In Motion Limited |
Unit 1A, 142 Belmont Circular Road, Belmont, Port of Spain, Trinidad |
Phone: (868) 621-2746 | e-mail: charles.leeying@sim-tt.com
<cbleeyin@tstt.co.tt>
