### ISSUE TITLE
Documentation missing for Predefined sets of computers in Advanced Firewall

### ISSUE THREAD

**Issue by CajH** [MicrosoftDocs/feedback#669]
**Link to article:**
The feature is mentioned in the old article http://technet.microsoft.com/en-us/library/ee806447.aspx.

**Problem:**
It is unclear how the pre-defined sets are defined. It appears as if the groups can be edited. This needs documentation.

The issue is discussed here along with screenshots:
https://social.technet.microsoft.com/Forums/office/en-US/26125329-e4a6-4bdf-996d-8e69674056a4/firewall-how-to-defined-predefined-set-of-computers
https://serverfault.com/questions/773529/predefined-set-of-computers-where-to-define

**Comment by Powerhelmsman** [comment]
@CajH Thanks for your feedback on content. I transferred your issue to window/Itpro repo. See if there are someone can help you.

**Comment by Justinha** [comment]
@CajH I don't think the list can be edited but I've asked our engineering team to confirm.

**Comment by LeeiFrankJaw** [comment]
> @CajH  The values are predefined according to https://msdn.microsoft.com/en-us/library/cc231500.aspx

You reply seems to imply that I have to write a C program in order to add a set of computer into the firewall.  That might be too much for average administrators and even too much for average programmers.

**Comment by LeeiFrankJaw** [comment]
https://github.com/MicrosoftDocs/windows-itpro-docs/issues/1613#issuecomment-662618892

After reading the API, my conclusion is that it is not possible to add a predefined set of computers to Windows Firewall even by writing a C program.  It is really just predefined and hard-coded list of options to select from.
