### ISSUE TITLE
[UWP] appxmanifest -> App capability -> Appointment is translated diffrentely in Korean

### ISSUE THREAD

**Issue by ingyeoking13** [MicrosoftDocs/feedback#670]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

**Link to article:**
Tell us where exactly a problem occurs.
[docs](https://docs.microsoft.com/ko-kr/windows/uwp/packaging/app-capability-declarations)

**Problem:**
What's wrong with the article?

in docs and in Visual studio, Appointments is translated in Korean **"약속"**.  
but the real app "Appointment",which user can use from their own PC, is translated in **"일정"**.   
I think it is quite confusing until Korean user see English word "Appointment".  
Especially, Visual studio has no undo-translation functionality. If Korean developer see **"약속"** word in appxmanifest, then at first, he don't understand that It really means **"일정"** App which MS provide.      

Best Regards,

**Comment by SonjaSaltzman** [comment]
@nokura @JasonCard could you please address this one?

**Comment by elizatobias** [comment]
Acknowledging feedback. We'll address

**Comment by Powerhelmsman** [comment]
@elizatobias any updates?

**Comment by SonjaSaltzman** [comment]
@elizatobias left the team, this should be assigned to @dongmicro but she is not part of this GitHub org?

**Comment by Powerhelmsman** [comment]
@dend Can you add dongmicro in the GitHub org?

**Comment by SonjaSaltzman** [comment]
@nokura & @v-nidolc could you please check into this?
