### ISSUE TITLE
404 on link to Java DevOps on Azure from Java with VSTS page

### ISSUE THREAD

**Issue by rppowell-lasfs** [MicrosoftDocs/feedback#673]
**Link to article:** https://docs.microsoft.com/en-us/vsts/java/?view=vsts

## Description
On page `Working with Visual Studio Team Services (VSTS) and Java` ( https://docs.microsoft.com/en-us/vsts/java/?view=vsts ), under `5-Minute Quickstarts` section, the link for `Java DevOps with Azure` ( https://docs.microsoft.com/en-us/azure/devops-project/azure-devops-project-java.md?toc=/vsts/java/toc.json&bc=/vsts/java/breadcrumb/toc.json ) returns `404 - Content Not Found` - missing.

**Comment by dend** [comment]
Thanks for the feedback, @rppowell-lasfs - this has now been fixed, and the link points to the correct location.
