### ISSUE TITLE
Co-management documentation to support moving off Configuration Manager 

### ISSUE THREAD

**Issue by patster23** [MicrosoftDocs/feedback#674]
We would like to see new documentation developed to address a customers looking to move off Configuration Manager after enabling co-management and moving all workloads to the cloud. What is the process to remove the agent from the device using Intune? How do you remove the device from the local domains so it is fully cloud managed?

**Comment by aczechowski** [comment]
Oops, this is for SCCMDocs. I'll work with @patster23 to get this refiled in the right spot. 😄 
You can close docs feedback issue #674.
