### ISSUE TITLE
Typo in IPv4 Addressing article

### ISSUE THREAD

**Issue by NorthYork** [MicrosoftDocs/feedback#677]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

Typo in IPv4 Addressing article

**Link to article:**

https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/dd379547(v=ws.10)

**Problem:**
What's wrong with the article?

In Modern Internet Addresses in Host IDs Needed and CIDR-based Prefix Lengths table there is a typo:
1,02**1**–2,046 | /21 | 255.255.248.0. It should be 1,02**3**–2,046 | /21 | 255.255.248.0.

**Comment by Powerhelmsman** [comment]
@NorthYork Thanks for you feedback. Unfortunately this page is no longer to maintain due to out of product lifecycle. Please refer to the similar document for new version.
