### ISSUE TITLE
Get confirmation of customer acceptance of Microsoft Cloud agreement

### ISSUE THREAD

**Issue by mgroos16** [MicrosoftDocs/feedback#678]
Dear,
We have some doubts about this request.

At the moment we have a document of Terms and conditions and from what I understand this is a new requirement that the final client will have to validate to be able to acquire or modify new licenses of Office.

My query is where it would have to be added in the existing Terms and Conditions?

The client could do it from the Office portal, will there be any option?

In the case that is added in the current Terms and Conditions as it would be to automate it and that this is saved in the CSP portal referring to each client?

Thank you
regards
Marcelo Groos

**Comment by Powerhelmsman** [comment]
@mgroos16 Can you tell us which page you are referring to?

**Comment by Powerhelmsman** [comment]
@mgroos16 I will close it so far. If you can provide more details later, we can reopen it and continue the discussion.
