### ISSUE TITLE
No content in Azure top page for Japanese

### ISSUE THREAD

**Issue by satonaoki** [MicrosoftDocs/feedback#679]
In the top page of Azure documentation for Japanese does not show main content:

https://docs.microsoft.com/ja-jp/azure/

Same page for English (or any other languages) does not have this issue:

https://docs.microsoft.com/en-us/azure/

![azure](https://user-images.githubusercontent.com/240055/45467092-c2eb3680-b758-11e8-8af7-74bc9d821b1f.png)

**Comment by satonaoki** [comment]
And the Japanese page does not show the Microsoft logo, the Azure.com top menu and the search box.

**Comment by Powerhelmsman** [comment]
@satonaoki I can't repro the issue from my end. Do you still have this issue?

**Comment by satonaoki** [comment]
Now it works for Japanese. Thanks!
