### ISSUE TITLE
Linking back to Docs Home page

### ISSUE THREAD

**Issue by docs-product** [MicrosoftDocs/feedback#68]
Make linking back to Docs homepage more consistent. For example the Azure landing (https://docs.microsoft.com/en-us/azure/) has no link in main nav to bring user back to the Docs landing page.

----------
⚠ Idea migrated from UserVoice

**Created By:** Karega Anglin
**Created On:** 2017/12/08 15:09:38 +0000
**Votes at Migration:** 1
**Supporters at Migration:** 1

**Comment by Powerhelmsman** [comment]
Thanks for your great suggestion. @kubeaver @ShevaDas Can you consider the user suggestion on new site header?

**Comment by Powerhelmsman** [comment]
#log-suggestion

**Comment by botcrane** [comment]
🚀 **ATTENTION**: [Internal request](https://ceapex.visualstudio.com/web/wi.aspx?pcguid=7d644393-99ad-41c8-ac53-7fa79294c720&id=21083) logged.

**Comment by kubeaver** [comment]
@Powerhelmsman this is also something we're working with the UHF team to resolve in the next round of updates.

**Comment by shirgoldbird** [comment]
This will be resolved with the new UHF work across this/next quarter.. Closing.
