### ISSUE TITLE
Escaped, open square bracket '[[' not decoded - Microsoft.SqlServer.TransactSql.ScriptDom.Identifier.DecodeIdentifier()

### ISSUE THREAD

**Issue by Niklas-Peter** [MicrosoftDocs/feedback#682]
**Describe the bug**
Actually it is not a documentation bug, but an implementation bug, but I do not know where to report it.
Expected behavior is:

Actual behavior: 
`Microsoft.SqlServer.TransactSql.ScriptDom.Identifier.DecodeIdentifier("[[[As]]]", out _) == "[[As]"`

**Expected behavior**
`Microsoft.SqlServer.TransactSql.ScriptDom.Identifier.DecodeIdentifier("[[[As]]]", out _) == "[As]"`

Obviously `Replace("[[", "[")` is missing when decoding an identifier with `QuoteType.SquareBracket`

 - Microsoft.SqlServer.TransactSql.ScriptDom 14.0.3811.1

**Comment by Powerhelmsman** [comment]
@craigg-msft Is this something you can help?

**Comment by craigg-msft** [comment]
apologies for the delay but we do not monitor this issue area for SQL content, rath the issues in the sql-docs repo.  with that said, product issues can be reported to the engineering team via user voice. https://feedback.azure.com/forums/908035-sql-server #please-close

**Comment by craigg-msft** [comment]
@Mike-Ubezzi-MSFT do you have the permission to close?

**Comment by Niklas-Peter** [comment]
As you suggested I reported it here:
https://feedback.azure.com/forums/908035-sql-server/suggestions/37220824-escaped-open-square-bracket-not-decoded-mi
