### ISSUE TITLE
Missing document that is linked in Powershell error message

### ISSUE THREAD

**Issue by gitsno** [MicrosoftDocs/feedback#683]
**Link to article:**
http://go.microsoft.com/fwlink/?LinkID=135170

**Problem:**
It's not found

This article is referenced by the Powershell error that occurs when you try to execute a script and do not have the execution policy correctly set, so it is pretty important that the link works.

**Comment by Powerhelmsman** [comment]
@gitsno Can you provide which page include this link?

**Comment by gitsno** [comment]
It's not a page, it's in Powershell itself, I've attached a screenshot, note that the link appears twice at different times - first in the confirmation message when changing execution policy and then again in the error message when the execution fails.

![powershellbadlink](https://user-images.githubusercontent.com/11527628/45509474-47d84f00-b75d-11e8-9c5f-11ba636fe512.PNG)

**Comment by EdisonDa** [comment]
Hi @gitsno, thank you for your reporting. I tried the link http://go.microsoft.com/fwlink/?LinkID=135170, and it goes to https://technet.microsoft.com/zh-CN/library/hh847748.aspx, it shows the "about_Execution_Policies" which consist to the page in docs https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_execution_policies. 

Could you please share me the screenshot when you click the link http://go.microsoft.com/fwlink/?LinkID=135170, is it a 404?

**Comment by gitsno** [comment]
When I go to that link I get a 404 and the URL is
https://docs.microsoft.com/en-us/powershell/module/5.1/Microsoft.PowerShell.Core/about/about_Execution_Policies
I've attached screenshots of the page and also of the Network tab showing the redirect.
![ps 404](https://user-images.githubusercontent.com/11527628/45557546-76a90080-b803-11e8-8ecb-61330bc3422b.PNG)
![ps redirect](https://user-images.githubusercontent.com/11527628/45557547-76a90080-b803-11e8-9d69-c707cc85383a.PNG)

**Comment by EdisonDa** [comment]
@sdwheeler I created an issue https://github.com/PowerShell/PowerShell-Docs/issues/2925. would you want to track here?

**Comment by Powerhelmsman** [comment]
@gitsno @EdisonDa I will close this issue as transferred. You guys can go PowerShell/PowerShell-Docs#2925. to track the status.
