### ISSUE TITLE
Website issue when 100%zoom

### ISSUE THREAD

**Issue by vivekpatel19** [MicrosoftDocs/feedback#685]
https://docs.microsoft.com/en-in/windows/uwp/get-started/?ocid=WinClient_Ver1703_Settings_TipCreateApp
![screenshot 76](https://user-images.githubusercontent.com/30730410/45582319-141b3780-b8cb-11e8-8c78-ad186314476c.png)

**Comment by Powerhelmsman** [comment]
@ShevaDas Can you take a look at this issue?

**Comment by ShevaDas** [comment]
Duplicate of #655, closing.
