### ISSUE TITLE
Missing documentation for `GlobalFilterCollection`

### ISSUE THREAD

**Issue by ite-klass** [MicrosoftDocs/feedback#686]
I am [searching for `GlobalFilterCollection` across all APIs](https://docs.microsoft.com/en-us/dotnet/api/?term=GlobalFilterCollection), but that does not return a result.

Inspecting in Visual Studio I can see it is a sealed class in the `System.Web.Mvc` namespace, assembly `System.Web.Mvc` version `5.2.3.0`.

[It does exist on MSDN.](https://msdn.microsoft.com/en-us/library/system.web.mvc.globalfiltercollection(v=vs.118).aspx)

([Searching on referencesource yields no results either](https://referencesource.microsoft.com/#q=GlobalFilterCollection), but I guess that does not include MVC?)

As I am still using it on an MVC project I would expect documentation to be available on the docs page. I am now confused as to whether this has been replaced, removed, made obsolete, or what. The MSDN page does not mention anything of the sort either.

**Comment by Powerhelmsman** [comment]
@sudeepku Do we migrate it or not?

**Comment by ite-klass** [comment]
Looks like it was migrated, looks like it does exist now?

https://docs.microsoft.com/en-us/dotnet/api/system.web.mvc.globalfiltercollection?view=aspnet-mvc-5.2

**Comment by mairaw** [comment]
Closing since this issue is now fixed.
