### ISSUE TITLE
Add Code Formatting

### ISSUE THREAD

**Issue by spottedmahn** [MicrosoftDocs/feedback#687]
**Is your feature request related to a problem? Please describe.**

It would be handy if I add code, with the language tag, that the code was formatted as such.

## Not formatted

![image](https://user-images.githubusercontent.com/14079228/45646988-c51ffe80-ba92-11e8-8c54-e8cc4784266a.png)

**Describe the solution you'd like**
Please format it like on GitHub:

![image](https://user-images.githubusercontent.com/14079228/45647001-cb15df80-ba92-11e8-867f-a22b83a24575.png)

**Comment by Powerhelmsman** [comment]
@ShevaDas Please take a look at this suggestion.

**Comment by ShevaDas** [comment]
@jialge is handling GitHub Issues now, assigned to him.

**Comment by spottedmahn** [comment]
hello 👋 - any updates?  thanks!

**Comment by spottedmahn** [comment]
I guess we can close this feature request as we can [no longer fill out issues](https://github.com/MicrosoftDocs/azure-devops-docs/issues/9107#issuecomment-676547953) directly anymore; is there a GitHub issue for that change?
