### ISSUE TITLE
Broken table formatting in 'ACE Strings' documentation

### ISSUE THREAD

**Issue by mspncp** [MicrosoftDocs/feedback#690]
**Link to article:**
https://docs.microsoft.com/en-us/windows/desktop/SecAuthZ/ace-strings

**Problem:**
The table formatting of the field  **rights** in the **Fields** section is broken. All entries appear below each other. (Verified with Microsoft Edge and Chrome.)

**Comment by Powerhelmsman** [comment]
@ginami Can you assign it to right person to fix it?

**Comment by ginami** [comment]
Hi @mspncp -- thanks for letting us know about this issue! We're working on getting the table fixed.

**Comment by mspncp** [comment]
Hi @ginami, how are you doing? I just checked the table and itis still broken.

**Comment by mspncp** [comment]
Hi @ginami, what's the current state of this ticket? The table formatting still seems to be  broken.

**Comment by mspncp** [comment]
> Hi @mspncp -- thanks for letting us know about this issue! We're working on getting the table fixed.

Hi @ginami, will the table be fixed before a year has passed?  ;-)

**Comment by drewbatgit** [comment]
This issue has been fixed in the source file. You should see the changes update on the live site in ~24 hours.  Thanks!

**Comment by mspncp** [comment]
Thank you, too. I checked and it's fixed now.
