### ISSUE TITLE
Microsoft

### ISSUE THREAD

**Issue by IntelOSt** [MicrosoftDocs/feedback#691]
We discussed again about the problem of software piracy and microchip processor and MSD, please immediately resolve the case in our country. Our Indonesian ID.or has been incorporated We have joined the inter-national police

**Comment by Powerhelmsman** [comment]
@IntelOSt Thanks for your feedback. The channel is only for Docs site. Giving your feedback is not related to Docs site. There is nothing we can help here. If you have any concern or suggest about the Docs site, we can reopen the issue and continue discussion.
