### ISSUE TITLE
Cannot log into comment sections even though I'm logged into MS Account

### ISSUE THREAD

**Issue by AOvermyer** [MicrosoftDocs/feedback#692]
**Describe the bug**
Even though I have logged into the MS Docs site using one of my MS Accounts, The comments section still requires me to log-in before posting. I have attempted to sign in multiple times, and each time the website does not respond. When I enter valid MS Account details, the logon box simply dissapears and the page does not refresh or show that I've logged in. Clicking on the Sign-In link again treats it as if I never signed in to begin with.

**Screenshots**
I added a PSR Recording of me duplicating the issue.

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Chrome
 - Version: Version 69.0.3497.100 (Official Build) (64-bit)

[Failed to Login to Comments.zip](https://github.com/MicrosoftDocs/feedback/files/2397403/Failed.to.Login.to.Comments.zip)

**Comment by Powerhelmsman** [comment]
@ShevaDas Is this your area to help?

**Comment by ShevaDas** [comment]
@AOvermyer I can't open that file—could you provide a link to the page that this is happening on?

**Comment by AOvermyer** [comment]
Hello - 

Apologies for delayed response.
Here is the page I'm having the issue with.

https://docs.microsoft.com/en-us/sql/relational-databases/security/sql-vulnerability-assessment?view=sql-server-2017
