### ISSUE TITLE
404

### ISSUE THREAD

**Issue by MikalaKennell** [MicrosoftDocs/feedback#696]
This page isn't working: https://docs.microsoft.com/en-us/azure/devops/user-guide/what-is-vsts?view=vsts

**Comment by mairaw** [comment]
Where are you seeing this link @MikalaKennell? I imagine the correct link would be https://docs.microsoft.com/en-us/azure/devops/user-guide/what-is-azure-devops-services?view=vsts. 

/cc @erickson-doug

**Comment by Powerhelmsman** [comment]
@MikalaKennell Is this help you? I will close this feedback so far. If you can provide more details later, we can reopen it and continue the discussion.
