### ISSUE TITLE
DriveInfo (and other System.IO classes) should be explicit about their thread-safety. 

### ISSUE THREAD

**Issue by mairaw** [MicrosoftDocs/feedback#697]
Original GitHub issue https://github.com/dotnet/docs/issues/7809 by @ericmutta 

Since I/O is the type of thing that you would expect to be done from multiple threads, it would be very handy to know the thread-safety guarantees (if any) of the various `System.IO` classes.

For example, what happens if two threads read the `DriveInfo.AvailableFreeSpace` property? Though the property is read-only, the information it returns is constantly changing as threads create/delete files, so what does one need to keep in mind about this fact when writing portable multi-threaded I/O code?

I was hoping to see something similar to the [thread safety information](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.dictionary-2?view=netstandard-2.0#thread-safety) for the `Dictionary<K,V>` class. In fact I seem to remember the "thread safety" section being a standard part of all (if not most) documentation similar to the very important "Applies To" section which lists applicable platforms.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b18f2264-6230-68d2-98d2-4c3c7210c4a7
* Version Independent ID: 94faff8f-a332-cbfd-ddc4-7d2214ef7f01
* Content: [DriveInfo Class (System.IO)](https://docs.microsoft.com/en-us/dotnet/api/system.io.driveinfo?view=netstandard-2.0#definition)
* Content Source: [xml/System.IO/DriveInfo.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.IO/DriveInfo.xml)
* Product: **dotnet-api**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
@ericmutta is right. All types on MSDN would have a default thread safety text that we could override if needed. 

The overriding part is working, but we don't have the default case covered.

The text that we had for DriveInfo was 
![image](https://user-images.githubusercontent.com/12971179/45850972-4b378180-bced-11e8-97ea-5d4b806bfe31.png)

**Comment by dend** [comment]
@mairaw can you confirm that the ask is to blanket-apply a **Thread Safety** string to all .NET content?

**Comment by mairaw** [comment]
Adding @rpetrusha here to comment as well. I believe the boilerplate should appear in all classes and structures unless overridden.

**Comment by ericmutta** [comment]
@dend having that blanket thread-safety string would be a start but the more ideal case would be to more detailed about the thread-safety of types that invoke system calls.

In the past .NET was just a Windows thing so you could view the source of any time, discover the related Win32 API and then read up on it for thread-safety guarantees.

But now with .NET Standard 2.0, types like `DriveInfo` work on Android, iOS, MacOS, Linux and Windows. Without thread-safety rules being part of the spec for types like `DriveInfo` it becomes pretty hard to write portable multi-threaded code that is reliable. For example I am guessing that the `AvailableFreeSpace` property is thread-safe but there is no statement to that effect anywhere that I can find.

Ultimately one either ends up paranoid and does defensive locking (which introduces complexity and may affect performance) or one is optimistic and ends up with potential race conditions on platforms that don't share that optimism!

The big picture question is this: with .NET going/being cross platform, what is the behavior of types that require system calls when those calls ultimately get serviced by different operating systems?

**Comment by dend** [comment]
Following-up on the request - thank you @ericmutta for the detailed explanation. The work is tracked [here](https://ceapex.visualstudio.com/Engineering/_workitems/edit/53469/) internally. Given that this work does not yet have a definitive timeframe, I am resolving this issue. 

We will start by applying boilerplate **Thread Safety** information, and @mairaw and the content team can determine what supporting content needs to be introduced.

I'd like to re-iterate that closing this issue merely means that we are aware of the problem and will be addressing it according to our planning process.

**Comment by ericmutta** [comment]
> @dend: I'd like to re-iterate that closing this issue merely means that we are aware of the problem and will be addressing it according to our planning process.

Many thanks for following up, I look forward to any announcements on this whenever they may come in the future :+1:
