### ISSUE TITLE
Wrong URL links in Windows Embedded Compact 7 Docs

### ISSUE THREAD

**Issue by nbkawa-sh** [MicrosoftDocs/feedback#698]
**Link to article:**
Here is a sample page which has problem. The links in the "Reference" section of the page are linked to "Windows Embedded CE 6.0" pages, but the page content is for Windows Embedded Compact 7 (WEC7).
https://docs.microsoft.com/en-us/previous-versions/windows/embedded/ee489554(v%3dwinembedded.70)

**Problem:**
The all links in the page are linked to "Windows Embedded CE 6.0" pages, but the page content is about WEC7.
This is inconvenient to check WEC7 documents, because if I click the link then the page is navigated to CE 6.0 documents.

I guess the server automatically adds the CE 6.0 signature to the links in the page, such as below strings.
[ https://docs.microsoft.com/en-us/previous-versions/windows/embedded/ee490438 _**%28v%3dwinembedded.60%29**_ ](https://docs.microsoft.com/en-us/previous-versions/windows/embedded/ee490438%28v%3dwinembedded.60%29)

"%28v%3dwinembedded.60%29" means Windows CE 6.0.

The expected link is as below:
[ https://docs.microsoft.com/en-us/previous-versions/windows/embedded/ee490438 _**(v%3dwinembedded.70)**_ ](https://docs.microsoft.com/en-us/previous-versions/windows/embedded/ee490438(v%3dwinembedded.70))

"(v%3dwinembedded.70)" means WEC7.

I can go to WEC7 document pages to change the last strings to "(v%3dwinembedded.70)" manually, but please fix the link to smooth document reading.

Please check all the pages for the WEC7 documents.

**Comment by Powerhelmsman** [comment]
@nbkawa-sh Thanks for your feedback. All pages with previous-versions in URL are no longer updated due to out of production lifecycle. Do you see any pages without previous-versions have wrong links?

**Comment by nbkawa-sh** [comment]
@Powerhelmsman Thank you for your comment. I don't see pages which is not prebious-versions, because WinCE docs have already become previous versions docs. But I didn't see such wrong links the documents were on the "MSDN".

I know your support life cycle policy, but I think Microsoft took some mistakes to port the docs from MSDN, such as the following issue that I reported.
https://github.com/MicrosoftDocs/feedback/issues/323

Could you consider this problem again?

**Comment by nbkawa-sh** [comment]
Here is additional infomation:

At the below URL (compact 2013, WEC2013), it seems to become a same behavior as WEC7 page.

https://docs.microsoft.com/en-us/previous-versions/windows/embedded/gg154201(v%3dwinembedded.80)

If you click the "What's New" link in the page (blue square), you will be navigated to "What's New (Compact 7)" page.
But if you click the "What's New" link in the left sidebar, you will be navigated to "What's New (Compact 2013)" page.

Is it right?

Therefore, I know another workaround of this problem now, but I'd like you to fix it.

**Comment by Powerhelmsman** [comment]
@nbkawa-sh Currently we don't have resource to update the previous-versions pages. I have to close it so far.
