### ISSUE TITLE
I can not sign into my account, even when providing information.

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#7]
I think its ridiculous, I now have over three accounts.
That I don't even know why I need them....?
It's becoming harder to remember all the safety "back-up account's" passwords etc.
...Then the safety precaution in the start 
...like the account I am about to enter... I can't even access.

----------
⚠ Idea migrated from UserVoice

**Created By:** B
**Created On:** 2018/03/02 15:37:36 +0000
**Votes at Migration:** 1
**Supporters at Migration:** 1

**Comment by dend** [comment]
Not related to docs.microsoft.com. Closing.
