### ISSUE TITLE
The Azure pricing//sizing calculator guide is missing ... One of the most important tool while working on a BOQ and should be merged with r

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#70]
The Azure pricing//sizing calculator guide is missing ... One of the most tool while working with Bill of Material and should be linked to every Ref Architecture.

----------
⚠ Idea migrated from UserVoice

**Created By:** Anonymous
**Created On:** 2017/12/08 03:47:37 +0000
**Votes at Migration:** 1
**Supporters at Migration:** 1

**Comment by Powerhelmsman** [comment]
Transfer the issue to Azure team issue queue.
