### ISSUE TITLE
Oi

### ISSUE THREAD

**Issue by helenkashmiraqueen** [MicrosoftDocs/feedback#700]
Meu nome é Helen dos Reis Silva Freire de Sena, e estou tentando recuperar a minha conta que mais uma vez foi roubada. Já tive outros e-mails, que vocês não me deixaram recuperar(helen.cherrie@gmail.com e helen.kashmiraqueen@gmail.com). Eu conheço meus direitos como usuária e sei que estão roubando diversas vezes minha conta, e essa empresa nunca me permite recuperar meus cadastros e e-mails. Mesmo oferecendo dados, e todos os alicerces possíveis para recuperá- la. Estou indignada e revoltada como cliente, pois é uma vergonha para vcs um tipo de violação como esse. Vcs deveriam se envergonhar com a falta de ética profissional, falta de profissionalismo, incapacidade intelectual, censura e violação dos direitos humanos.

Atenciosamente.

Helen dos Reis Silva Freire de Sena
CPF 78655170500
RG 0754615014
Endereço: Rua Padre Feijó, 06, Edf. Amsterdam, Apt. 303, Canela, Salvador, Bahia, Brazil. CEP> CODE POST 40110170
E-mail que desejo recuperar:< helen.kashmiraqueen@gmail.com>,<helen.cherrie@gmail.com>,<helen.kashmiraqueen@gmail.com>
e <helen.fairyqueen@gmail.com>

**Comment by Powerhelmsman** [comment]
@helenkashmiraqueen  This channel is only for Docs site itself. I read your feedback through translation tool. Maybe I am wrong.  Your issue seems not to relate to our site. If you have any concern and more detail information, we can reopen it and continue the discussion.
