### ISSUE TITLE
Fabric UI Content no longer rendering

### ISSUE THREAD

**Issue by gcrockenberg** [MicrosoftDocs/feedback#701]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

**Link to article:**
https://developer.microsoft.com/en-us/fabric

**Problem:**
The Fabric UI pages all render a spinning, "busy" placeholder.  No content appears.  Testing using Chrome, Edge and IE11.
![fabric content issue](https://user-images.githubusercontent.com/2053387/45918143-653da500-be50-11e8-9907-bcdaec35d459.PNG)

**Comment by KirbyMcKenzie** [comment]
`Uncaught TypeError: i.createContext is not a function` is being thrown in the console.

**Comment by KirbyMcKenzie** [comment]
Hey @gcrockenberg,

I'm getting the same problem. I had a look in the console and there is the following error:
 `Uncaught TypeError: i.createContext is not a function` which may be preventing the page from loading.

**Comment by Powerhelmsman** [comment]
@jialge Can you help here or who is the right person to contact?

**Comment by gcrockenberg** [comment]
It is working today.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Powerhelmsman** [comment]
@gcrockenberg Thanks for letting us know the status. I will close this issue now. But if it doesn't work again, we can reopen the issue and continue the discussion.

**Comment by herkyjerky** [comment]
it's dead again.  linked to from this page: https://docs.microsoft.com/en-us/office/dev/add-ins/design/using-office-ui-fabric-react#see-also
