### ISSUE TITLE
Error Message after (successful) Logon

### ISSUE THREAD

**Issue by MarkowEduard** [MicrosoftDocs/feedback#702]
As the title says ...

I have screenshot, but it seems that I cannot attach it.

**Comment by Powerhelmsman** [comment]
@MarkowEduard Maybe it is because we are publishing new features today. Do you still have the similar problem?

**Comment by Powerhelmsman** [comment]
@MarkowEduard Do you still have the issue? Didn't get your response for a while. I will close it so far. If you can provide more details later, we can reopen it and continue the discussion.
