### ISSUE TITLE
Integrate notebook for F#

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#71]
It's awesome that F# is supported on Jupyter notebooks. It could be really beneficial to integrate that into the F# guide (maybe even create the whole guide as a notebook) in order to enable people to run the examples in the browser.

----------
⚠ Idea migrated from UserVoice

**Created By:** Kristijan Vulinovic
**Created On:** 2017/12/07 21:55:34 +0000
**Votes at Migration:** 1
**Supporters at Migration:** 1

**Comment by Powerhelmsman** [comment]
The issue is transferred to F# issue queue.
