### ISSUE TITLE
SQL Restore points => dates incorrect

### ISSUE THREAD

**Issue by roldengarm** [MicrosoftDocs/feedback#711]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

**Link to article:**
https://docs.microsoft.com/en-us/rest/api/sql/restorepoints/listbydatabase

**Problem:**
It says:

> properties.earliestRestoreDate | string | Earliest restore time (ISO8601 format). Populated when restorePointType = DISCRETE. Null otherwise.
> 
> properties.restorePointCreationDate | string | Restore point creation time (ISO8601 format). Populated when restorePointType = CONTINUOUS. Null otherwise.

But in my case, it's exactly the opposite.

![image](https://user-images.githubusercontent.com/37638588/46184214-9a526780-c328-11e8-8cb7-06c00db26982.png)

So in my opinion the documentation should be:

> properties.earliestRestoreDate | string | Earliest restore time (ISO8601 format). Populated when restorePointType = CONTINUOUS. Null otherwise.
> 
> properties.restorePointCreationDate | string | Restore point creation time (ISO8601 format). Populated when restorePointType = DISCRETE. Null otherwise.

**Comment by Powerhelmsman** [comment]
@erickson-doug @craigg-msft Can you take a look at this suggestion?

**Comment by craigg-msft** [comment]
unfortunately this is not a git repo / issues collection that is monitored by the content teams, so apologies.  Creating a tracking Azure Boards item to fist see if the issue still exists.  closing this git issue. #please-close   azure boards item is https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1709824
