### ISSUE TITLE
Please change the text from "機能" to "Functions".

### ISSUE THREAD

**Issue by ReinaSakai** [MicrosoftDocs/feedback#712]
**Describe the bug**
Please change the text from "機能" to "Functions" on the left navigation.

**To Reproduce**
1. Go to 'https://docs.microsoft.com/ja-jp/learn/browse/'
2. Click on 'Products' on the left navigation.
3. Scroll down to '機能'
4. See error. Please do not translate it because It is a service name of Azure.

**Expected behavior**

**Screenshots**
![functions](https://user-images.githubusercontent.com/10412917/46188747-04b5d880-c326-11e8-9678-bae055235513.PNG)

**Desktop (please complete the following information):**
 - OS: [Windows 10 Enterprise Edition]
 - Browser [chrome]
 - Version [69.0.3497.100]

**Additional context**

**Comment by thedanfernandez** [comment]
@SonjaSaltzman  - Can you take a look at this?

**Comment by SonjaSaltzman** [comment]
@SunnyDeng could you please address & close?

**Comment by SonjaSaltzman** [comment]
@ishasahni1 assigning to you

**Comment by DavidPrio** [comment]
Hi @ishasahni1 The issue does not seem to repro any longer, as you can see in SS below:
![image](https://user-images.githubusercontent.com/35581209/49760321-faf40e00-fca2-11e8-954c-c8c2ca8ac88e.png)
Also, please remember to assign the issues to me so we can import them and work on the accordingly.
@SonjaSaltzman @Sara-Nicolini FYI
