### ISSUE TITLE
docs.microsoft.com/dotnet/xrefmap.yml is missing very many dotnet APIs

### ISSUE THREAD

**Issue by bitbonk** [MicrosoftDocs/feedback#713]
**Describe the bug**

docs.microsoft.com/dotnet/xrefmap.yml is missing **a lot** of APIs that are actually available under https://docs.microsoft.com/dotnet/api How am I supposed to permalink from my docfx documentation if they are missing there? For example I cannot link to https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.servicedescriptor because none of the `Microsoft.Extensions.*`  APIs are listed in the xrefmap.

**To Reproduce**
1. Download docs.microsoft.com/dotnet/xrefmap.yml
2. Open the file and Search for Microsoft.Extensions

**Expected behavior**
All types from the `Microsoft.Extensions*` namespaces should be listed

**Actual behavior**
No types from the `Microsoft.Extensions*` namespaces are listed.

**Comment by Powerhelmsman** [comment]
@mairaw @dend Can you take a look at this feedback?

**Comment by dend** [comment]
Hi @bitbonk - the `xrefmap.yml` file is actually not intended to be a file that is covering the entire .NET API surface. We can't recommend others consume it because it's not intended for public consumption at this time, and is likely used internally for one of the repos.

Even on docs.microsoft.com, we are using an xref service that does not rely on mapping files like the YAML file above and instead maintains its own index.

I will follow-up with engineering to see _where_ that file originates from, however at this time I do not expect us to make any significant changes to it.

**Comment by bitbonk** [comment]
So maybe that xref service you are speaking of is available for public consumption? There should be a canonical way to reference to all the APIs on https://docs.microsoft.com/dotnet/api from our docs.

Oh and while we are at it: It would be cool, if we could have an offline cache. So building our API docs doesn't always require internet access. Previously we just kept a copy of docs.microsoft.com/dotnet/xrefmap.yml around for fallback.

**Comment by dend** [comment]
@bitbonk interestingly enough, the service is mentioned in the issue you referenced 😁

**Comment by bitbonk** [comment]
@dend I have been trying to use it and failed, so I was assuming it‘s not yet available. What are those tags for?

**Comment by svick** [comment]
@bitbonk I am getting a response for the first type I tried: https://xref.docs.microsoft.com/query?uid=System.Object. (I haven't checked Microsoft.Extensions.)

And I think tags are for specifying target frameworks, e.g.: https://xref.docs.microsoft.com/query?uid=System.Object&tags=netcore-2.1.

**Comment by superyyrrzz** [comment]
@bitbonk The API you mentioned exists in xref service: https://xref.docs.microsoft.com/query?uid=Microsoft.Extensions.DependencyInjection.ServiceDescriptor

**Comment by bitbonk** [comment]
Although that API service works (thank you for clearing things up for me), I would like to reiterate that we really need a caching or offline version. Having to make a lot of web request during the build of our documentation may significantly increase the build time or may break the build completely if the internet is not available.
I really liked the idea of having a [nuget package](https://www.nuget.org/packages/msdn.4.5.2/0.1.0-alpha-1611021200) that contains all the xfres.

**Comment by dend** [comment]
@bitbonk yes, absolutely, given that the request for a feature is going to be quite a bit different. I am going to close this issue for now.
