### ISSUE TITLE
Unify all learning platforms into one? 

### ISSUE THREAD

**Issue by rajanikanthr** [MicrosoftDocs/feedback#714]
Microsoft virtual academy, Microsoft learn?

Also LinkedIn learning, may be it is different completely

**Comment by Powerhelmsman** [comment]
@rajanikanthr Thanks for you feedback. We are working on to unify all learning platform. It is in our backlog but it may take a while to make it happened. So I will close this issue now. Please monitor our blog site: https://docs.microsoft.com/en-us/teamblog/ for updates.
