### ISSUE TITLE
Application Owner can not be group object

### ISSUE THREAD

**Issue by bachoang** [MicrosoftDocs/feedback#718]
Group object is not allowed to be an Application's owner per https://developer.microsoft.com/en-us/graph/docs/api-reference/beta/resources/application. Trying to make a Group object to be an owner will result in error
The reference target 'Group_xxx' of type 'Group' is invalid for the 'owners' reference.',
The following documentation on this is wrong:
https://docs.microsoft.com/en-us/rest/api/graphrbac/Applications/AddOwner

Name | Required | Type | Description
-- | -- | -- | --
url | True | string | A owner object URL, such as "https://graph.windows.net/0b1f9851-1bf0-433f-aec3-cb9272f093dc/directoryObjects/f260bbc4-c254-447b-94cf-293b5ec434dd", where "0b1f9851-1bf0-433f-aec3-cb9272f093dc" is the tenantId and "f260bbc4-c254-447b-94cf-293b5ec434dd" is the objectId of the owner (user, application, servicePrincipal, **group)** to be added.

**Comment by dend** [comment]
@bachoang given that this is a Graph issue, we'd recommend you open the issue in the Graph documentation repository - https://github.com/microsoftgraph/microsoft-graph-docs
