### ISSUE TITLE
Show location for each Type (Framework or NuGet PackageId) for each target framework.

### ISSUE THREAD

**Issue by glibnub** [MicrosoftDocs/feedback#72]
Lots of APIs used to be part of the framework and available as an ***embly reference. Now each framework version may have differences on location, whether it is an included ***embly or included in a NuGet package. Please show which it is for that moniker and if NuGet which package and minimum version.

----------
⚠ Idea migrated from UserVoice

**Created By:** Ovan Crone
**Created On:** 2017/12/07 21:01:25 +0000
**Votes at Migration:** 1
**Supporters at Migration:** 1

**Comment by dend** [comment]
@Powerhelmsman yes, I will take this.

**Comment by dend** [comment]
#log-suggestion

**Comment by botcrane** [comment]
🚀 **ATTENTION**: [Internal request](https://ceapex.visualstudio.com/web/wi.aspx?pcguid=7d644393-99ad-41c8-ac53-7fa79294c720&id=21135) logged.
