### ISSUE TITLE
Example Code is Improperly Highlighted in Razor Pages Tutorial

### ISSUE THREAD

**Issue by RyanLilla** [MicrosoftDocs/feedback#720]
**Link to article:**
https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/new-field?view=aspnetcore-2.1

**Problem:**
The issue is in the code snippet on the page where you are told where to add the `Rating` field to the _Pages/Movies/Index.cshtml_ file. The section of the code where you are supposed to add the field is improperly highlighted. 

![image](https://user-images.githubusercontent.com/7048518/46318930-0503dd00-c58d-11e8-9417-6d52e2344880.png)

**Comment by Powerhelmsman** [comment]
@RyanLilla Thanks for you feedback. I transferred you feedback to aspnet team. They will help you there.
