### ISSUE TITLE
Print version of .Net API reference pages contain too much cruft

### ISSUE THREAD

**Issue by svick** [MicrosoftDocs/feedback#722]
**Describe the bug**

When I print a .Net API reference article such as [`Void`](https://docs.microsoft.com/en-us/dotnet/api/system.void?view=netcore-2.1) in Edge, the first page of the result seems to contain only the Product selector, which is useless when printed:

![](https://user-images.githubusercontent.com/287848/46346998-4c9c6e80-c64a-11e8-9ae5-609177b28665.png)

Also, the result seems to contain an empty last page.

**Expected behavior**

The printed article contains only useful information, if possible.

**Desktop:**
 - OS: Windows 10
 - Browser: Edge
 - Version: 42.17134.1.0

**Comment by dend** [comment]
@dastaffo works on PDF and chromeless functionality, therefore I would defer to him on the request.

**Comment by dastaffo** [comment]
Moving over to @cillroy

**Comment by DuncanmaMSFT** [comment]
Not seeing this in Edge, possibly fixed over the past year

![image](https://user-images.githubusercontent.com/18338424/69678665-10e91300-105b-11ea-9dd0-7cd8524699ac.png)
