### ISSUE TITLE
Printing in Firefox only prints the first page

### ISSUE THREAD

**Issue by svick** [MicrosoftDocs/feedback#723]
**Describe the bug**

When I print a docs article in Firefox, the result always seems to contain only one page. This is especially problematic when combined with https://github.com/MicrosoftDocs/feedback/issues/722, because then the result of printing in Firefox does not contain any useful information:

![](https://user-images.githubusercontent.com/287848/46347310-638f9080-c64b-11e8-8941-884c94596bd2.png)

It's possible that this is a bug in Firefox, but I thought it would be better to report it here.

**Expected behavior**

Printing in Firefox prints all pages of the article.

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 62.0.2

**Comment by dend** [comment]
@dastaffo would probably be the right person to take a look at this 😄

**Comment by dastaffo** [comment]
Adding @cillroy on this one.

**Comment by dend** [comment]
#log-suggestion @cillroy

**Comment by docs-product** [comment]
This experience is currently working as-expected. Testing this with the latest version of Firefox seems to be produce the right output.
