### ISSUE TITLE
aka.ms link redirecting to microsoft.com

### ISSUE THREAD

**Issue by archieag** [MicrosoftDocs/feedback#725]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

**Link to article:**
Tell us where exactly a problem occurs.
https://docs.microsoft.com/en-us/connectors/kusto/

**Problem:**
What's wrong with the article?
This article points to Read more: http://aka.ms/kdocs and this link redirects to microsoft.com

**Comment by Powerhelmsman** [comment]
@archieag Can you try one more time? It works fine from my end.

**Comment by Powerhelmsman** [comment]
@archieag Didn't get your response for a while. I will close it so far. If you can provide more details later, we can reopen it and continue the discussion.
