### ISSUE TITLE
Documentation link is out of date.

### ISSUE THREAD

**Issue by kgreed** [MicrosoftDocs/feedback#726]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

**Link to article:**
Tell us where exactly a problem occurs.
https://marketplace.visualstudio.com/items?itemName=VisualStudioClient.MicrosoftVisualStudio2017InstallerProjects

**Problem:**
What's wrong with the article?
This contains a link to https://aka.ms/vdproj-docs  but that link is about 2012 and is formatted to apply to older Visual Studio

**Comment by Powerhelmsman** [comment]
@kgreed Thanks for your feedback. visualstudio.com is out of our scope. This channel is for docs site only. So I create a Q&A on the page to see if they will fix the problem. https://marketplace.visualstudio.com/items?itemName=VisualStudioClient.MicrosoftVisualStudio2017InstallerProjects#qna
