### ISSUE TITLE
Index out of bound

### ISSUE THREAD

**Issue by NguyenChiCao** [MicrosoftDocs/feedback#727]
**Describe the bug**
Index out of bound

**To Reproduce**
https://docs.microsoft.com/en-us/visualstudio/ide/step-3-assign-a-random-icon-to-each-label?view=vs-2015
Label iconLabel = control as Label;
if (iconLabel != null)
{
    int randomNumber = random.Next(icons.Count);
    iconLabel.Text = icons[randomNumber];
    // iconLabel.ForeColor = iconLabel.BackColor;
    icons.RemoveAt(randomNumber);
}
**Expected behavior**
icons.Count will return 16.
That mean random.Next(icons.Count) could be 16.
Then: iconLabel.Text = icons[randomNumber];
Will return an exception in case randomNumber = 16
**Screenshots**
No

**Desktop (please complete the following information):**
 - OS: Windows
 - 10 Profesionnal

**Comment by Powerhelmsman** [comment]
@NguyenChiCao Thanks your feedback. I transferred your feedback to visual studio team. They will help you there.
