### ISSUE TITLE
Wrong title in browser tab

### ISSUE THREAD

**Issue by MortenKJ** [MicrosoftDocs/feedback#731]
**Link to article:**
https://docs.microsoft.com/da-dk/windows-server/windows-server

**Problem:**
The page title is incorrect, it says "Widows" instead of "Windows" (see screenshot)

![image](https://user-images.githubusercontent.com/3501177/46463646-aa54c600-c7c4-11e8-9a8c-b91150f0bded.png)

**Comment by jasongroce** [comment]
@coreyp-at-msft This looks like the redirect issue we discussed a couple of days ago.

**Comment by coreyp-at-msft** [comment]
Fixed

**Comment by EdisonDa** [comment]
I am closing this one since this already get fixed. @MortenKJ could you please verify?

**Comment by MortenKJ** [comment]
@EdisonDa done
