### ISSUE TITLE
[Accessibility]A11y_.NET Online REPL View_Keyboard: Focus is not properly visible on "Enter focus mode" and "Run" buttons #104 

### ISSUE THREAD

**Issue by LadyNaggaga** [MicrosoftDocs/feedback#735]
Is this an accessibility bug your team can address? This does fall out the Try .NET editor. 

https://github.com/dotnet/try/issues/104

**Comment by Powerhelmsman** [comment]
@dend Can you take a look at this issue?

**Comment by dend** [comment]
#log-suggestion @dend 

@LadyNaggaga @Powerhelmsman I can take this, as it's a bug on our side.

**Comment by botcrane** [comment]
🚀 **ATTENTION**: [Internal request](https://ceapex.visualstudio.com/web/wi.aspx?pcguid=7d644393-99ad-41c8-ac53-7fa79294c720&id=47399) logged.

**Comment by nschonni** [comment]
https://w3c.github.io/aria-practices/#TreeView might be helpful, but I'm not sure if those examples are still being tested

**Comment by dend** [comment]
This is now resolved @LadyNaggaga @nschonni 🎉
