### ISSUE TITLE
Missing diagrams for Windows Imaging Component

### ISSUE THREAD

**Issue by jasonoverland** [MicrosoftDocs/feedback#737]
See e.g. https://docs.microsoft.com/en-us/windows/desktop/wic/-wic-decoderinterfaces. The image url goes to a 404.

There are multiple pages in WIC that are missing these.

**Comment by ginami** [comment]
Thank you @jasonoverland for letting us know! We're working on fixing this issue.

**Comment by jasonoverland** [comment]
FYI: When running a recursive wget on 
https://docs.microsoft.com/en-us/windows/desktop/wic, I got a 404 (Not Found) error for the following links.

https://docs.microsoft.com/en-us/windows/desktop/wic/graphics/progressive-jpeg-comparison.jpg
https://docs.microsoft.com/en-us/windows/desktop/wic/graphics/png-progressive-comparison.jpg
https://docs.microsoft.com/en-us/windows/desktop/wic/graphics/ycbcr1.png
https://docs.microsoft.com/en-us/windows/desktop/wic/graphics/ycbcr2.png
https://docs.microsoft.com/en-us/windows/desktop/wic/graphics/ycbcr3.png
https://docs.microsoft.com/en-us/windows/desktop/wic/graphics/ycbcr4.png
https://docs.microsoft.com/en-us/windows/desktop/wic/graphics/ycbcr5.png
https://docs.microsoft.com/en-us/windows/desktop/wic/graphics/jpeg.png
https://docs.microsoft.com/en-us/windows/desktop/wic/graphics/jpegwithcallouts.png
https://docs.microsoft.com/en-us/windows/desktop/wic/graphics/jpgvstiff.png
https://docs.microsoft.com/en-us/windows/desktop/wic/graphics/wicinterfaces.png
https://docs.microsoft.com/en-us/windows/desktop/wic/graphics/wicencoderinterfaces.png
https://docs.microsoft.com/en-us/windows/desktop/wic/graphics/scaledregion.png
https://docs.microsoft.com/en-us/windows/desktop/wic/graphics/cliparegion-axisalignedclip.png
https://docs.microsoft.com/en-us/windows/desktop/wic/graphics/fliphorizontal.png

**Comment by Powerhelmsman** [comment]
@ginami for your awareness.

**Comment by stevewhims** [comment]
Hi, @jasonoverland, sorry about the delay here, I just noticed this issue. I've located the images and restored them to the master branch of the repo. However, it might take a few days for them to appear on the live site, so I'll monitor them until they're published, and then I'll report back here. Thanks for filing this issue! ~Steve

**Comment by stevewhims** [comment]
UPDATE: the images are now live, so this issue is ready to be closed. Again, thanks for identifying this issue, @jasonoverland. ~Steve
