### ISSUE TITLE
The link to the Azure document page in Japan is Italian (it-it)

### ISSUE THREAD

**Issue by hiobay** [MicrosoftDocs/feedback#739]
The link to the Azure document top page in Japan is Italian (it-it)
![image](https://user-images.githubusercontent.com/20063695/46518762-e49b9180-c8b0-11e8-911f-ec3c7b3cf42f.png)

**Comment by Powerhelmsman** [comment]
@hiobay This issue is duplicated with #738 . We will track it there.
