### ISSUE TITLE
Please provide an example of the disable function of Add-AzureRmWebtestAlertRule cmdlet.

### ISSUE THREAD

**Issue by imeya** [MicrosoftDocs/feedback#744]
link to this [article](https://docs.microsoft.com/en-us/powershell/module/azurerm.insights/add-azurermwebtestalertrule?view=azurermps-6.9.0)

I wanna disable the web test by using the `disable ` parameter, but not success. Could you please provide an example for it? thanks.

**Comment by EdisonDa** [comment]
@sptramer I logged a request https://github.com/Azure/azure-powershell/issues/7486 here. Do you have example for user?

**Comment by sptramer** [comment]
No, I do not have an example offhand. This issue will need to be handled by the reference documentation team.

**Comment by imeya** [comment]
@EdisonDa @sptramer , could you please help route to the related team? thank you very much.

**Comment by imeya** [comment]
ok, thanks.
