### ISSUE TITLE
Broken links in BCDEDIT

### ISSUE THREAD

**Issue by theking2** [MicrosoftDocs/feedback#746]
**Link to article:**
https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/bcdedit-command-line-options

**Problem:**
Link to examples is broken.

**Comment by EdisonDa** [comment]
@theking2 have you checked the URL I shared?

**Comment by theking2** [comment]
Thanks for fixing the link

**Comment by EdisonDa** [comment]
@theking2 then I will close this issue. Thank you for your reporting.
