### ISSUE TITLE
Link Docs articles to Certification or Exam Numbers and Make it searchable

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#75]
If we can tag/link the articles in the docs to a Microsoft Certificate or an Exam number and make that searchable, it will be easy for developer to gather the necessary content and prepare for certification

----------
⚠ Idea migrated from UserVoice

**Created By:** Vijaya Malla
**Created On:** 2017/12/07 19:59:18 +0000
**Votes at Migration:** 2
**Supporters at Migration:** 2

**Comment by Powerhelmsman** [comment]
Thanks for your suggestion. I've created a internal work item to track it.

**Comment by Powerhelmsman** [comment]
#log-suggestion

**Comment by botcrane** [comment]
🚀 **ATTENTION**: [Internal request](https://ceapex.visualstudio.com/web/wi.aspx?pcguid=7d644393-99ad-41c8-ac53-7fa79294c720&id=21103) logged.

**Comment by thedanfernandez** [comment]
Thanks for the feedback, I'm going to close this as documentation doesn't always fit or match with certification and resources like Microsoft Virtual Academy are a better resource for certification preparedness.
