### ISSUE TITLE
on-premise vs on-premises

### ISSUE THREAD

**Issue by jocasti** [MicrosoftDocs/feedback#750]
There is currently no comment section for this article.

**Link to article:**
https://docs.microsoft.com/en-us/system-center/scom/plan-mgmt-group-design?view=sc-om-1807

**Problem:**
What's wrong with the article?
There are two instances of "on-premise". Suggest this be corrected to "on-premises". Thanks.

**Comment by EdisonDa** [comment]
@sudeepku could you please review this user feedback?

**Comment by jocasti** [comment]
Created PR https://github.com/MicrosoftDocs/SystemCenterDocs-pr/pull/2050 for this issue.

**Comment by jocasti** [comment]
Closing issue. Created PR https://github.com/MicrosoftDocs/SystemCenterDocs-pr/pull/2050
