### ISSUE TITLE
This website is really terrible. There are a lot of invalid links in old documents.

### ISSUE THREAD

**Issue by he852100** [MicrosoftDocs/feedback#752]
http://go.microsoft.com/fwlink/?LinkId=xxxxxx
for example
http://go.microsoft.com/fwlink/?LinkId=82954
In fact, after your website is revised, old documents are almost impossible to read.
Where can I get valid documents?

**Comment by he852100** [comment]
https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/ee431701(v%3dws.10)
![image](https://user-images.githubusercontent.com/26913892/46715083-0d48d000-cc91-11e8-92ac-31dbf7145408.png)
https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/cc753977(v=ws.10)
![image](https://user-images.githubusercontent.com/26913892/46715142-53059880-cc91-11e8-8154-3f783a7296c2.png)
![image](https://user-images.githubusercontent.com/26913892/46715164-6fa1d080-cc91-11e8-88c2-67fa3522f27e.png)

**Comment by EdisonDa** [comment]
@he852100 thank you for your detailed information. So you mean the fwlink will go to invalid page, right? I will confirm with some others and get back to you. Here are some suggestions:

1. We suggest you to use latest docs
2. The fwlink 108180/143364 goes to invalid page, but 89051 goes to https://docs.microsoft.com/zh-cn/previous-versions/windows/.

@Jemash could you please confirm if we still maintain these previous version docs?
