### ISSUE TITLE
Remove references to UserVoice for "suggestions"

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/feedback#754]
**Link to article:**
An example, but there are more
https://docs.microsoft.com/en-us/visualstudio/releasenotes/vs2017-relnotes#feedback

**Problem:**
The feedback section says to use UserVoice, but UserVoice says use devcomm. 

The page also does not have a specific feedback section for itself.

**Comment by EdisonDa** [comment]
Thank you for your feedback @StingyJack . Yes, you can use UserVoice https://visualstudio.uservoice.com/forums/121579-visual-studio-ide to submit any suggestion for VS, also you can create bug at dev community site. This feedback channel to is to accept user feedback for docs.microsoft.com. What kind of feedback do you want to submit?

**Comment by StingyJack** [comment]
Big note at the top of the UserVoice page says dont use it anymore. 
![image](https://user-images.githubusercontent.com/15381181/46804006-9282c200-cd2f-11e8-9935-ee8053a3582a.png)

**Comment by EdisonDa** [comment]
@StingyJack Thank you for your detailed info. This is the user voice managed by VS team, it's not in docs and out of control. I can try to contact with their team offline, but you can also submit your feedback in the VS developer community, very appreciate.

**Comment by svick** [comment]
@EdisonDa I'm confused. As far as I can tell, this issue is about the fact that [this Docs page](https://docs.microsoft.com/en-us/visualstudio/releasenotes/vs2017-relnotes#feedback) links to the deprecated VS UserVoice:

![](https://user-images.githubusercontent.com/287848/46863533-ff718700-ce17-11e8-9a5a-cc229bf2d59d.png)

I think that's something that's in your control and should be fixed.

**Comment by svick** [comment]
@EdisonDa 

> We don't manage their user voice site and their community site.

But you do manage https://docs.microsoft.com/en-us/visualstudio/releasenotes/vs2017-relnotes#feedback, right? Which is the page that I think should be updated.

**Comment by StingyJack** [comment]
> @StingyJack Thank you for your detailed info. This is the user voice managed by VS team, it's not in docs and out of control. I can try to contact with their team offline, but you can also submit your feedback in the VS developer community, very appreciate

@EdisonDa - [I did. that a year and a half ago](https://developercommunity.visualstudio.com/content/problem/56328/get-rid-of-uservoice.html). I'm now asking Docs (you, this page, your team) to correct its links to match.
