### ISSUE TITLE
Cloud Shell in Microsoft Learn - Intialization Problem

### ISSUE THREAD

**Issue by TanvirShah** [MicrosoftDocs/feedback#755]
![azure](https://user-images.githubusercontent.com/32184263/46776503-5185b000-cd25-11e8-93b8-1f7fc029f89d.JPG)

Hi,

Hope you and family are fine.

With reference to the image I have attached I am stuck at this point. Cant't seem to enter any command into the shell and also clicking on Report an issue does nothing.

Kindly help.

Regards,

Tanvir.

**Comment by EdisonDa** [comment]
@TanvirShah thanks for your reporting. Have you accepted the sandbox invitation? Or click "Check your work again", or refresh your page to see if it work? I could not reproduce the issue on my side.

**Comment by TanvirShah** [comment]
@EdisonDa thanks for your reply. Done all that. I am working in the field of IT since 1989. DOS 3.3 era :-) and after exhausting all I can do I wrote here. 

Without being able to enter any commands I thought clicking "Check your work" won't help but I did try that as well (Check the image attached).

![aaaa](https://user-images.githubusercontent.com/32184263/46795228-0c806e80-cd63-11e8-9264-4c60db172b7b.JPG)

**Comment by TanvirShah** [comment]
@EdisonDa Sandbox is activated. Just cant run any commands on it.

![aaaa](https://user-images.githubusercontent.com/32184263/46795445-9defe080-cd63-11e8-8b7d-af881a6f9445.JPG)

**Comment by EdisonDa** [comment]
@dend this is related to cloud shell, could you please take a look?

**Comment by TanvirShah** [comment]
@dend thank you in advance.

**Comment by TanvirShah** [comment]
@EdisonDa kindly remove tag "need more info" I think I have provided as much info as possible. Thanks.

**Comment by TanvirShah** [comment]
@EdisonDa and @dend still waiting......

**Comment by TanvirShah** [comment]
Sad indeed.

**Comment by dend** [comment]
@TanvirShah what browser are you using? Are you signing in with an organization (AAD) or personal (MSA) account?

**Comment by dend** [comment]
Closing this issue as no additional information was provided. @TanvirShah - feel free to add more information, when available, and we can re-assess the experience impact here.
