### ISSUE TITLE
Please open the english/source security-updates repo

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/feedback#756]
**Is your feature request related to a problem? Please describe.**
There are minor content issues seen in the localization repos that are open like https://github.com/MicrosoftDocs/security-updates.zh-tw that should be fixed at the original location

**Describe the solution you'd like**
Make the https://github.com/MicrosoftDocs/security-updates repo public (assuming that is the right url/repo)

**Describe alternatives you've considered**
Maybe it's open under a different name, or isn't something you'd take PRs to

**Comment by EdisonDa** [comment]
Thank you @nschonni for your suggestion, we will consider it. If you found any localization issues, we appreciate you can create PR and contribute there.

**Comment by nschonni** [comment]
The localization issues are with English words like "Widow" instead of "Windows" that need to be fixed in the source repo

**Comment by EdisonDa** [comment]
@nschonni thank you for the info, could you please kindly share me the link so we can fix that on our side?

**Comment by nschonni** [comment]
@EdisonDa I opened https://github.com/MicrosoftDocs/security-updates.zh-tw/issues to try and fix the main issue I came across, but I'm not sure if that repo is actually maintained

**Comment by EdisonDa** [comment]
Thank you @nschonni for your contribution and passion . The team will triage the PR and get back to you!
