### ISSUE TITLE
Profile creation impossible

### ISSUE THREAD

**Issue by RemiLELONG** [MicrosoftDocs/feedback#757]
Hello Community,

In order to progress in the Azure trainning (Microsoft learn), I have to create a profile on http://techprofile.microsoft.com. It is mandatory to get a sand box!

But the registration process don't accept my username
![annotation](https://user-images.githubusercontent.com/44053124/46791090-a97de000-cd40-11e8-8fad-aabeace0fd7f.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser : Edge or Firefox

thanks in advance for you help

**Comment by EdisonDa** [comment]
@RemiLELONG could you please share what's the username you are filling? It needs to start with a letter or number, and larger than 3 but less than 40.

**Comment by RemiLELONG** [comment]
Thanks for your reply @EdisonDa, 

I tried different usernames : remi, Remi, Rémi, remilelong and also my e-mail address but any of them seems to be accepted.
Regards 
Remi Lelong

**Comment by bergmike** [comment]
I have the same problem.  I tired many different combinations and none worked.

I tried berg12345, michaelberg, michaelbergthomsonreuters, all failed.  The only error message I get is right below the blue "register" button that says, "Something went wrong. Please try again later."

OS: Windows 7
Browers: Chrome

**Comment by EdisonDa** [comment]
Creating a bug for tracking https://ceapex.visualstudio.com/Engineering/_workitems/edit/44643

**Comment by RemiLELONG** [comment]
Thanks,

but i'am not authorized to access this page :-(
![annotation1](https://user-images.githubusercontent.com/44053124/46853391-2f139580-cdfe-11e8-89de-cbb20f966cf6.png)

**Comment by RemiLELONG** [comment]
Hello, On the Azure doc page (https://docs.microsoft.com/fr-fr/learn/paths/azure-fundamentals/), when I click on Connect, I came back on the page I'm stuck with (on techprofile).
So I tried to put the same value on te URL field than the Display Name field and now I could go through the process.
So it's Ok for me now.

Thanks for your help @EdisonDa 

Regards,
Rémi LELONG

**Comment by EdisonDa** [comment]
Good to know it works. Thank you @RemiLELONG. We will track the bug, and definitely we will improve the error message, it's confusing somehow. Would you mind me to close this issue now?
