### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by andreyzapt** [MicrosoftDocs/feedback#758]
**Describe the bug**
Here is the wrong description:
  - Converts a point in a window from logical coordinates into physical coordinates, regardless of the dots per inch (dpi) awareness of the caller. For more information about DPI awareness levels....

it should be: physical to logical.

**To Reproduce**
Open page:
 - https://docs.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-physicaltologicalpointforpermonitordpi

**Comment by prankshaw** [comment]
Cannot find the document file on GitHub.
Can someone please share the repo in which following docs file is present. Also, please assign this issue to me

**Comment by Powerhelmsman** [comment]
@ginami Can you help here? This is a windows content issue.

**Comment by ginami** [comment]
Thank you @andreyzapt for letting us know--we're working on the issue!

**Comment by mairaw** [comment]
This has been fixed. Closing.
