### ISSUE TITLE
When users enter a new comment in a doc topic, Microsoft engineers that own the topic should be notified

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#76]
I’m raising a flag as a developer. Do you remember few months ago that I raised the flag that some developers wrote questions in an article at docs.microsoft.com and there were no answers by your engineers? I don’t remember the subject, but one of you forwarded my email.

This week, I was in discussion with one of the PM in the Windows team and I was pointing it out that I posted a question on an article and if he could get the answer by one of the contributors of the article (if any of them would still be in the team or at msft). I was quite surprised by his answer: “we don’t get notifications when somebody comments on the doc pages, so replies there may be (very) slow. We would prefer if the docs team would disable those comments and instead go to our support system (Intercom), but they are not able to do this. Sorry about that.”

As a developer, waiting for an answer sometimes is very important and we mostly want the answer yesterday. That’s being said, I do think that it is an issue if your engineers cannot get a notification. If this is really impossible to achieve (hmm), there should be a note at the bottom on each article that warn that questions might not be answered in a timely fashion (or not even an answer) or contact the support directly. 

----------
⚠ Idea migrated from UserVoice

**Created By:** Sébastien Lachance
**Created On:** 2017/12/07 19:51:53 +0000
**Votes at Migration:** 1
**Supporters at Migration:** 1

**Comment by Powerhelmsman** [comment]
Understand your pain point. So Docs site just release new feedback system. On the bottom of every content page, you can choose to provide product feedback or content feedback. If you choose to provide product feedback, it will go to specific product internal support system. If you choose content feedback, your question is in the content team queue, they will triage your question very quickly.
