### ISSUE TITLE
DISM /Online /Cleanup-Image /RestoreHealth /source:

### ISSUE THREAD

**Issue by gmgj** [MicrosoftDocs/feedback#760]
on this page https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-8.1-and-8/hh825020(v=win.10)
it talks about repair source

it talks about this:

You can use a running Windows installation as a source to restore optional features by sharing the c:\Windows folder on your network.

You can use a Windows side-by-side folder from a network share or from a removable media, such as the Windows DVD, as the source of the files. For example, z:\sources\SxS.

You should list the requirements for these sources.

? does it have to be the same windows type / Home / Pro / Enterprise
? what about versions?  I see some stuff on the web about you can't use a newer version?

All of these articles on DISM need to be reviewed by someone who is not a DISM expert.  

The online help for DISM is sad.  No mention of a lot of the sub options

Like these:

 Examples:
    DISM.exe /Mount-Wim /?
    DISM.exe /ScratchDir /?
    DISM.exe /Image:C:\test\offline /?
    DISM.exe /Online /?

---------------
C:\ma>dism /?

Deployment Image Servicing and Management tool
Version: 10.0.17134.1

DISM.exe [dism_options] {Imaging_command} [<Imaging_arguments>]
DISM.exe {/Image:<path_to_offline_image> | /Online} [dism_options]
         {servicing_command} [<servicing_arguments>]

DESCRIPTION:

  DISM enumerates, installs, uninstalls, configures, and updates features
  and packages in Windows images. The commands that are available depend
  on the image being serviced and whether the image is offline or running.

GENERIC IMAGING COMMANDS:

  /Split-Image            - Splits an existing .wim file into multiple
                            read-only split WIM (SWM) files.
  /Apply-Image            - Applies an image.
  /Get-MountedImageInfo   - Displays information about mounted WIM and VHD
                            images.
  /Get-ImageInfo          - Displays information about images in a WIM, a VHD
                            or a FFU file.
  /Commit-Image           - Saves changes to a mounted WIM or VHD image.
  /Unmount-Image          - Unmounts a mounted WIM or VHD image.
  /Mount-Image            - Mounts an image from a WIM or VHD file.
  /Remount-Image          - Recovers an orphaned image mount directory.
  /Cleanup-Mountpoints    - Deletes resources associated with corrupted
                            mounted images.

WIM COMMANDS:

  /Apply-CustomDataImage  - Dehydrates files contained in the custom data image.
  /Capture-CustomImage    - Captures customizations into a delta WIM file on a
                            WIMBoot system. Captured directories include all
                            subfolders and data.
  /Get-WIMBootEntry       - Displays WIMBoot configuration entries for the
                            specified disk volume.
  /Update-WIMBootEntry    - Updates WIMBoot configuration entry for the
                            specified disk volume.
  /List-Image             - Displays a list of the files and folders in a
                            specified image.
  /Delete-Image           - Deletes the specified volume image from a WIM file
                            that has multiple volume images.
  /Export-Image           - Exports a copy of the specified image to another
                            file.
  /Append-Image           - Adds another image to a WIM file.
  /Capture-Image          - Captures an image of a drive into a new WIM file.
                            Captured directories include all subfolders and
                            data.
  /Get-MountedWimInfo     - Displays information about mounted WIM images.
  /Get-WimInfo            - Displays information about images in a WIM file.
  /Commit-Wim             - Saves changes to a mounted WIM image.
  /Unmount-Wim            - Unmounts a mounted WIM image.
  /Mount-Wim              - Mounts an image from a WIM file.
  /Remount-Wim            - Recovers an orphaned WIM mount directory.
  /Cleanup-Wim            - Deletes resources associated with mounted WIM
                            images that are corrupted.

FFU COMMANDS:

  /Capture-Ffu            - Captures a physical disk image into a new FFU file.
  /Apply-Ffu              - Applies an .ffu image.
  /Split-Ffu              - Splits an existing .ffu file into multiple read-only
                            split FFU files.

IMAGE SPECIFICATIONS:

  /Online                 - Targets the running operating system.
  /Image                  - Specifies the path to the root directory of an
                            offline Windows image.

DISM OPTIONS:

  /English                - Displays command line output in English.
  /Format                 - Specifies the report output format.
  /WinDir                 - Specifies the path to the Windows directory.
  /SysDriveDir            - Specifies the path to the system-loader file named
                            BootMgr.
  /LogPath                - Specifies the logfile path.
  /LogLevel               - Specifies the output level shown in the log (1-4).
  /NoRestart              - Suppresses automatic reboots and reboot prompts.
  /Quiet                  - Suppresses all output except for error messages.
  /ScratchDir             - Specifies the path to a scratch directory.

For more information about these DISM options and their arguments, specify an
option immediately before /?.

  Examples:
    DISM.exe /Mount-Wim /?
    DISM.exe /ScratchDir /?
    DISM.exe /Image:C:\test\offline /?
    DISM.exe /Online /?

C:\ma>dism /online /?

Deployment Image Servicing and Management tool
Version: 10.0.17134.1

Image Version: 10.0.17134.345

The following commands may be used to service the image:

OS UNINSTALL SERVICING COMMANDS:

  /Set-OSUninstallWindow  - Sets the OS Uninstall Window.
  /Get-OSUninstallWindow  - Gets the OS Uninstall Window.
  /Remove-OSUninstall     - Remove the OS Uninstall.
  /Initiate-OSUninstall   - Initiates the OS Uninstall

WINDOWS EDITION SERVICING COMMANDS:

  /Optimize-Image         - Performs specified configurations to an offline
                            image.
  /Set-ProductKey         - Sets the product key of the offline image.
  /Get-TargetEditions     - Displays a list of Windows editions that an image
                            can be upgraded to.
  /Get-CurrentEdition     - Displays the edition of the current image.
  /Set-Edition            - Upgrades an image to a higher edition.

DEFAULT ASSOCIATIONS COMMANDS:

  /Remove-DefaultAppAssociations - Removes the default application associations
                            from a Windows image.
  /Import-DefaultAppAssociations - Imports a set of default application
                            associations to a Windows image.
  /Get-DefaultAppAssociations - Displays the list of default application
                            associations from a Windows image.
  /Export-DefaultAppAssociations - Exports the default application associations
                            from a running operating system.

PROVISIONING PACKAGE SERVICING COMMANDS:

  /Get-ProvisioningPackageInfo - Gets the information of provisioning package.
  /Add-ProvisioningPackage - Adds provisioning package.

APPX SERVICING COMMANDS:

  /Optimize-ProvisionedAppxPackages - Optimizes provisioned appx footprint by
                            hard-linking identical files across appx packages.
  /Set-ProvisionedAppxDataFile - Places custom data into the specified app
                            package (.appx or .appxbundle). The specified
                            application package must already be in the image.
  /Remove-ProvisionedAppxPackage - Removes app packages (.appx or .appxbundle)
                            from the image. App packages will not be installed
                            when new user accounts are created.
  /Add-ProvisionedAppxPackage - Adds app packages (.appx or .appxbundle) to the
                            image and sets them to install for each new user.
  /Get-ProvisionedAppxPackages - Displays information about app packages
                            (.appx or .appxbundle) in an image that are
                            set to install for each new user.

UNATTEND SERVICING COMMANDS:

  /Apply-Unattend         - Applies an unattend file to an image.

DRIVER SERVICING COMMANDS:

  /Remove-Driver          - Removes driver packages from an offline image.
  /Add-Driver             - Adds driver packages to an offline image.
  /Get-DriverInfo         - Displays information about a specific driver
                            in an offline image or a running operating system.
  /Get-Drivers            - Displays information about all drivers in
                            an offline image or a running operating system.
  /Export-Driver          - Export all third-party driver packages from an
                            offline image or a running operating system.

INTERNATIONAL SERVICING COMMANDS:

  /Set-LayeredDriver      - Sets keyboard layered driver.
  /Set-UILang             - Sets the default system UI language that is used
                            in the mounted offline image.
  /Set-UILangFallback     - Sets the fallback default language for the system
                            UI in the mounted offline image.
  /Set-UserLocale         - Sets the user locale in the mounted offline image.
  /Set-SysLocale          - Sets the language for non-Unicode programs (also
                            called system locale) and font settings in the
                            mounted offline image.
  /Set-InputLocale        - Sets the input locales and keyboard layouts to
                            use in the mounted offline image.
  /Set-TimeZone           - Sets the default time zone in the mounted offline
                            image.
  /Set-AllIntl            - Sets all international settings in the mounted
                            offline image.
  /Set-SKUIntlDefaults    - Sets all international settings to the default
                            values for the specified SKU language in the
                            mounted offline image.
  /Gen-LangIni            - Generates a new lang.ini file.
  /Set-SetupUILang        - Defines the default language that will be used
                            by setup.
  /Get-Intl               - Displays information about the international
                            settings and languages.

APPLICATION SERVICING COMMANDS:

  /Check-AppPatch         - Displays information if the MSP patches are
                            applicable to the mounted image.
  /Get-AppPatchInfo       - Displays information about installed MSP patches.
  /Get-AppPatches         - Displays information about all applied MSP patches
                            for all installed applications.
  /Get-AppInfo            - Displays information about a specific installed MSI
                            application.
  /Get-Apps               - Displays information about all installed MSI
                            applications.

PACKAGE SERVICING COMMANDS:

  /Add-Package            - Adds packages to the image.
  /Remove-Package         - Removes packages from the image.
  /Enable-Feature         - Enables a specific feature in the image.
  /Disable-Feature        - Disables a specific feature in the image.
  /Get-Packages           - Displays information about all packages in
                            the image.
  /Get-PackageInfo        - Displays information about a specific package.
  /Get-Features           - Displays information about all features in
                            a package.
  /Get-FeatureInfo        - Displays information about a specific feature.
  /Cleanup-Image          - Performs cleanup and recovery operations on the
                            image.
  /Export-Source          - Export a set of capabilities into a new repository.
  /Add-Capability         - Add one or more capabilities to an image.
  /Remove-Capability      - Remove a capability from one image.
  /Get-Capabilities       - Get capabilities in the image.
  /Get-CapabilityInfo     - Get information of a capability in the image.

For more information about these servicing commands and their arguments,
specify a command immediately before /?.

     Examples:
         DISM.exe /Image:C:\test\offline /Apply-Unattend /?
         DISM.exe /Image:C:\test\offline /Get-Features /?
         DISM.exe /Online /Get-Drivers /?

C:\ma>dism /online /cleanup-image /?

Deployment Image Servicing and Management tool
Version: 10.0.17134.1

Image Version: 10.0.17134.345

/Cleanup-Image /RevertPendingActions

  WARNING! You should use the /RevertPendingActions option only in a
  system-recovery scenario to perform recovery operations on a Windows image
  that did not boot.

    Example:
      DISM.exe /Image:C:\test\offline /Cleanup-Image /RevertPendingActions

/Cleanup-Image /spsuperseded [/hidesp]
  Use /SPSuperseded to remove any backup files created during the installation
  of a service pack. Use /HideSP to prevent the service pack from being listed
  in the Installed Updates for the operating system.

  WARNING! The service pack cannot be uninstalled after the /SPSuperseded
  operation is completed.

    Example:
      DISM.exe /Image:C:\test\offline /Cleanup-Image /spsuperseded /hidesp

/Cleanup-Image {/CheckHealth | /ScanHealth | /RestoreHealth}
  Use /CheckHealth to check whether the image has been flagged as corrupted
  by a failed process and whether the corruption can be repaired.
  Use /ScanHealth to scan the image for component store corruption.
  Use /RestoreHealth to scan the image for component store corruption, and
  then perform repair operations automatically.
  Use /Source with /RestoreHealth to specify the location of known good
  versions of files that can be used for the repair. For more information on
  specifying a source location, see
  https://go.microsoft.com/fwlink/?LinkId=243077.
  Use /LimitAccess to prevent DISM from contacting WU/WSUS.

    Example:
      DISM.exe /Online /Cleanup-Image /ScanHealth

      DISM.exe /Image:c:\offline /Cleanup-Image /RestoreHealth
      /Source:c:\test\mount

/Cleanup-Image /StartComponentCleanup [/ResetBase [/Defer]]
  Use /StartComponentCleanup to clean up the superseded components and reduce
  the size of the component store. Use /ResetBase to reset the base of
  superseded components, which can further reduce the component store size.
  Use /Defer with /ResetBase to defer long-running cleanup operations to the
  next automatic maintenance.

  WARNING!  The installed Windows Updates cannot be uninstalled after the
  /StartComponentCleanup with /ResetBase operation is completed.

    Example:
      DISM.exe /Image:C:\test\offline /Cleanup-Image /StartComponentCleanup

/Cleanup-Image /AnalyzeComponentStore
  Use /AnalyzeComponentStore to create a report of the WinSxS component store.
  For more information about the WinSxS report and how to use the information
  provided in the report, see
  https://go.microsoft.com/fwlink/?LinkId=293367.

    Example:
      DISM.exe /Image:C:\test\offline /Cleanup-Image /AnalyzeComponentStore

C:\ma>

**Comment by Powerhelmsman** [comment]
@gmgj Thanks for your feedback. Unfortunately this content is no longer to update due to out of product lifecycle.
