### ISSUE TITLE
Remove locale from link to Docs PR validation service

### ISSUE THREAD

**Issue by ChrisMaddock** [MicrosoftDocs/feedback#762]
The new Docs PR validation service is super-cool, I love it! ✨ 

A request - the "View more details on Docs Content Validation" link on pages such as https://github.com/dotnet/docs/runs/23537546 is hardcoded to the en-US locale - can the locale be removed?

I only noticed as I was trying to work out when it was introduced, and according to my poor British brain, the pages were written in the future! 😅 

![image](https://user-images.githubusercontent.com/4837132/46904776-6ad35b80-cee1-11e8-8874-cc6e58672c17.png)

**Comment by mairaw** [comment]
I think the current link now goes to https://github.com/apps/docs-content-validation

e.g. 
https://github.com/dotnet/docs/pull/16866/checks?check_run_id=413939138

should this be closed @ChrisMaddock?

**Comment by ChrisMaddock** [comment]
Hi Maira. It does - but not sure why a ‘view more details’ link prompts you to install the app? Now seems like the test is wrong, rather than the link? Unless there’s more info on the desktop version of the site than the mobile.

There’s another link on the same page to “details of what’s validated” which is what I’d be expecting from this first link. Unfortunately that one 404s though.

**Comment by ChrisMaddock** [comment]
I guess solving those are a different issue from this one, however. 😊

**Comment by mairaw** [comment]
@meganbradley are we supposed to uninstall the app now from our repos? I remember us discussing some of that, although the docs validation catches different things.
