### ISSUE TITLE
Missing Character.

### ISSUE THREAD

**Issue by fearless-hasan** [MicrosoftDocs/feedback#763]
**Link to article:**
https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/nbtstat

**Problem:**
In this page, first example on the Examples section, the command should be "nbtstat /a CORP07"
rather than "btstat /a CORP07".
Simply it should add a single "n" in the beginning of the command.

**Comment by sark01** [comment]
Can I work on this?

**Comment by Powerhelmsman** [comment]
@fearless-hasan Your issue is transferred to windows server team. They will help you there.
