### ISSUE TITLE
.Net API reference search should ignore type parameter names

### ISSUE THREAD

**Issue by svick** [MicrosoftDocs/feedback#764]
When I use the .NET API Browser and search for e.g. `Task<T>`, [I get no results](https://docs.microsoft.com/en-us/dotnet/api/?term=Task%3CT%3E). This is because the type I'm loooking for is actually called [`Task<TResult>`](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.task-1).

I think this happens fairly often, because when using the type, it doesn't matter whether it's called `Task<T>` or `Task<TResult>`, both would be used in exactly the same way.

Because of this, I think the search should be smart about type parameters and ignore their names, at least to some degree.

**Comment by Powerhelmsman** [comment]
@dend @presleyy Can you take a look at this feedback?

**Comment by dend** [comment]
#log-suggestion @dend 

I am going to go ahead and log an internal suggestion for this, to make sure that we are tracking this work. However, in the bigger scope of things that we are doing for API documentation, this would be relatively low-priority, therefore at this time I am closing the issue.

**Comment by botcrane** [comment]
🚀 **ATTENTION**: [Internal request](https://ceapex.visualstudio.com/web/wi.aspx?pcguid=7d644393-99ad-41c8-ac53-7fa79294c720&id=54142) logged.
