### ISSUE TITLE
.Net API Reference search should ignore punctuation

### ISSUE THREAD

**Issue by svick** [MicrosoftDocs/feedback#765]
When I use the .NET API Browser and search for e.g. `console writeline`, [I get no results](https://docs.microsoft.com/en-us/dotnet/api/?term=console%20writeline). When I separate the two words with a period instead, [I get the results I expect](https://docs.microsoft.com/en-us/dotnet/api/?term=console.writeline).

I think the search should be more lenient about requiring the correct punctuation, to make it easier to use.

**Comment by Powerhelmsman** [comment]
@dend @presleyy This is similar with #764 . Can you please take a look at this.

**Comment by dend** [comment]
@svick the intent behind the API Browser is to be "IntelliSense in the browser" - we never intended for it to be a generic search mechanism. As such, we want to make sure that we are strictly following language fully qualified name patterns for discovery.
