### ISSUE TITLE
DWLoader for Linux

### ISSUE THREAD

**Issue by dstroyrofworlds** [MicrosoftDocs/feedback#769]
**Link to article:**
https://docs.microsoft.com/en-us/sql/tools/overview-sql-tools?view=sql-server-2017

**Problem:**
There is no pointer to how to install DWLoader on linux, if at all possible.

**Comment by dstroyrofworlds** [comment]
It is a dotnet application - can it be run on linux dotnet ?
I downloaded the dotnet docker images for linux, but it fails to run with error:

```bash
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The system cannot find the file specified.
```

**Comment by stevestein** [comment]
@yualan - can you verify if this should work or not? Thanks.

**Comment by yualan** [comment]
@mzaman1 may have more context on this

**Comment by mzaman1** [comment]
DWLoader cannot be installed on Linux. The doc doesn't point to DWLoader which is a specialized tool for loading data into APS only.

**Comment by stevestein** [comment]
@mzaman1 - Thanks for clarifying.

**Comment by stevestein** [comment]
#please-close
