### ISSUE TITLE
For some code snippets, would be cool to run them live using hacker rank or something

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#77]
For some code snippets, I wish I could run them live right there for quick tests and to confirm that the code works. This is useful when I'm on my phone and I'm not actually able to run the code on my computer. 

----------
⚠ Idea migrated from UserVoice

**Created By:** Daniel
**Created On:** 2017/12/07 19:51:03 +0000
**Votes at Migration:** 2
**Supporters at Migration:** 2

**Comment by Powerhelmsman** [comment]
Docs site just release a bunch of contents with "Try it" button. If you click "Try it" button, you will have a environment on the right with the code snippet, you can run it to test if it works. this is an example: https://docs.microsoft.com/en-us/rest/api/appservice/webapps/listbyresourcegroup. We will bring more content page with "Try it" experience soon.
