### ISSUE TITLE
Contrast in code blocks and inline code is too weak in Dark theme in Safari on macOS and iOS

### ISSUE THREAD

**Issue by mrlife** [MicrosoftDocs/feedback#771]
**Describe the bug**
When using Microsoft Docs with the Dark theme, code blocks and inline code use a light gray text on a near-white background. This is difficult to read due to the weak contrast between those two colors.

Also note that it doesn't meet the web accessibility contrast ratio requirements: https://webaim.org/resources/contrastchecker/?fcolor=CCCCCC&bcolor=F3F3F3

**To Reproduce**
1. Go to https://docs.microsoft.com/en-us/aspnet/core/mvc/views/overview?view=aspnetcore-2.1
2. Click on the "Dark" link in the top right, if the Light theme is currently enabled.
3. Scroll down to the "Creating a view" section.
4. Observe the CSHTML code block, as well as the handful of inline code instances in the subsequent paragraph, and notice the weak contrast.

**Expected behavior**
The contrast of the code background and foreground colors should be stronger. Since this is a dark theme, I would expect the background to be dark and the text to be light, like the rest of the theme. The near-white background used for code is jarring when reading the inline code instances.

**Screenshots**
Here is a screenshot of the section referred to in Step 3.

<img width="904" alt="screen shot 2018-10-16 at 11 00 36 am" src="https://user-images.githubusercontent.com/213164/47026146-c8121b80-d132-11e8-9a5f-da908c4474c8.png">

**Desktop**
 - OS: macOS
 - Browser: Safari
 - Version: 12.0

**Comment by Powerhelmsman** [comment]
@ShevaDas @kubeaver Can you take a look at this feedback?

**Comment by ShevaDas** [comment]
Adding @dend for code samples

**Comment by mrlife** [comment]
@kubeaver I don't have access to that page; will it be fixed relatively soon?

**Comment by kubeaver** [comment]
@mrlife it's in the queue. Checking on it now. I don't yet have an exact ETA as there are a few other things before it.

**Comment by dend** [comment]
@mrlife the link points to an internal bug tracker, so you won't be able to access it. We are working on getting this fixed. I will update the issue once we resolve the underlying bug.

**Comment by mrlife** [comment]
Looks fixed, thank you!

**Comment by ShevaDas** [comment]
@mrlife Thanks for the report! I'll close this out now. Feel free to open a new issue if other things crop up.
