### ISSUE TITLE
Azure Media Services REST API - Create Channel JSON Inaccurate

### ISSUE THREAD

**Issue by cmelliso** [MicrosoftDocs/feedback#772]
Attempting to use the "live encoding" Create Channel JSON example from https://docs.microsoft.com/en-us/rest/api/media/operations/channel#create_channels results in a 400 Bad Request with the following response body:

{
    "odata.error": {
        "code": "",
        "message": {
            "lang": "en-US",
            "value": "Parsing request content failed due to: Make sure to only use property names that are defined by the type"
        }
    }
}

Note:  To get this Bad Request response, you first have to fix the missing comma on line 32.

Additionally, more complete documentation on the semantics of the JSON parameters (both for this request and for things like the List Channels response) would be really helpful.

The non-live-encoding example works as is.

**Comment by Powerhelmsman** [comment]
@dend Can you take a look at this issue?

**Comment by dend** [comment]
Assigning to @Juliako for follow-up, as the content driver for Media Services.
