### ISSUE TITLE
.NET API browser: extraneous comma in the "Applies to" section

### ISSUE THREAD

**Issue by pkulikov** [MicrosoftDocs/feedback#773]
Framework versions in the **Applies to** section of the .NET API articles are separated by *two* commas:
![image](https://user-images.githubusercontent.com/15279990/47034630-37f6c500-d178-11e8-8864-46c862ebad92.png)

Check any API page:
https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.task.yield?view=netcore-2.1
https://docs.microsoft.com/en-us/dotnet/api/system.text.encoderfallback.createfallbackbuffer?view=netcore-2.1

**Comment by mairaw** [comment]
Thanks @pkulikov. I was about to file the same issue. 😄 

/cc @dend

**Comment by Powerhelmsman** [comment]
@pkulikov It seems resolved already.

**Comment by pkulikov** [comment]
@Powerhelmsman cool! Thanks!
