### ISSUE TITLE
Typo Error in your Azure Learn website

### ISSUE THREAD

**Issue by manickmalai** [MicrosoftDocs/feedback#774]
**Link to article:**
https://docs.microsoft.com/en-us/learn/modules/tour-azure-services-and-features/2-tour-of-azure-services

**Problem:**
I was learning Azure via Microsoft Learn and came across a documentation error where it says
"**Azure Database for MariaDB**" is a "Fully managed and scalable **MySQL** relational database". This is misleading and causes confusion. Should it not be "Fully managed and scalable MariaDB" ?

If I am wrong, please correct me.
![azure mariadb error](https://user-images.githubusercontent.com/44144679/47046209-8ca43b00-d18c-11e8-917c-1fe74b024a9f.JPG)

**Comment by Powerhelmsman** [comment]
@manickmalai This issue is fixed. Can you double check?
