### ISSUE TITLE
Allow quick access to examples in other languages

### ISSUE THREAD

**Issue by Damien-The-Unbeliever** [MicrosoftDocs/feedback#776]
I predominantly work in C#. I want that to be my #1 language preference within the documentation.

But I also help others who may not be working in C#. So, at the moment, if I'm helping somebody else who is working in, say, VB, my process is something like:

- locate the relevant sample
- sigh wistfully remembering that the old documentation had language selectors immediately above each example block
 - scroll to the top, change my language preference to VB
 - scroll back down and relocate the relevant sample
 - use it to answer the other person's question
 - (optional, I don't always remember to do this, and end up irked next time I freshly visit the documentation site) scroll back up and reset my language preference to C#

I'd like to be able to, from the location of the sample, find out what other languages the sample is available in and switch to viewing that example. Preferably without permanently changing my language preferences.

In the alternative, offer me the ability to pick and prioritise languages, so that I can say "I always want to see it in C# first but should also have X, Y or Z samples easily accessible if they're available".

[Recent SO question](https://stackoverflow.com/a/52850132/15498) where I ended up having to switch back and forth several times.

**Comment by Powerhelmsman** [comment]
@ShevaDas Is this your area?

**Comment by ShevaDas** [comment]
Code samples is (at least to some extend) @dend.

@Damien-The-Unbeliever we're looking into a couple options for making the code language selector easier to use and will definitely take this into account!

**Comment by dendeli-msft** [comment]
As a follow-up, we are currently working on improving how we handle language switching for code examples.

**Comment by dendeli-msft** [comment]
Thank you for the feedback! I've opened an internal issue for us to track.

At this time, we have no concrete timelines or commitments for this change, however we'll make sure that we do our due diligence in assessing the impact and importance of the feature.
