### ISSUE TITLE
Edit link for Powershell Core SDK methods is broken

### ISSUE THREAD

**Issue by JoBrad** [MicrosoftDocs/feedback#778]
I found some formatting issues with the pages listed below, and thought I would submit an edit to correct the issue. However the Edit button references the `powershell-docs-sdk-dotnet` repo, which doesn't actually exist. 

**Link to articles:**
https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.cmdlet.shouldcontinue
https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.cmdlet.shouldprocess

**Problem:**
I checked out quite a few articles in this section, and could not find one where the edit button didn't reference the repo above. 
Formatting issue: the Examples section in the referenced pages is not formatted using a code block, so the code does not contain line breaks or code formatting niceties, making it difficult to read.

**Comment by Powerhelmsman** [comment]
@dend Can you take a look at this issue?

**Comment by prasadu-microsoft** [comment]
Any update on this issue? The Edit link is still broken for these pages.

**Comment by mairaw** [comment]
The Edit button takes me to a private repo.

**Comment by prasadu-microsoft** [comment]
This is the link generated for me: https://github.com/MicrosoftDocs/powershell-docs-sdk-dotnet/blob/live/dotnet/xml/System.Management.Automation/Cmdlet.xml and this gives a 404 from GitHub.

**Comment by joeyaiello** [comment]
The edit button was removed as these are supposed to be fixed in [PowerShell source code](https://github.com/powershell/PowerShell) (from which they're reflected against).

@Powerhelmsman can you please close this issue? Thanks!
