### ISSUE TITLE
Content area is cut off in Docs Tutorials

### ISSUE THREAD

**Issue by jasonjgeiger** [MicrosoftDocs/feedback#779]
**Describe the bug**
Width of #main-column inherits min-width:100vh from body resulting in the main content to overflow off the right edge of the browser.

**To Reproduce**
1. Go to https://docs.microsoft.com/en-us/azure/functions/tutorial-static-website-serverless-api-with-database?tutorial-step=1
2. Click "Exit focus mode"
3. Try to read everything
4. Or navigate to next step

**Expected behavior**
All content should be visible.

**Screenshots**
<img width="1277" alt="content-cut-1" src="https://user-images.githubusercontent.com/448523/47101379-c27a0b80-d1ee-11e8-96a5-4497544a0afa.png">
<img width="1224" alt="content-cut-2" src="https://user-images.githubusercontent.com/448523/47101406-d7569f00-d1ee-11e8-83cd-3b3e66af5c31.png">

**Desktop**
 - OS: macOS 10.13.6 - resolution 1280x900
 - Browser: Chrome
 - Version: 69.0.3497.100

**Comment by Powerhelmsman** [comment]
@ShevaDas Can you take a look at this bug?

**Comment by ShevaDas** [comment]
We have a bug filed for this that is being worked on. Thanks for the report @jasonjgeiger!

Internal tracking link: https://ceapex.visualstudio.com/Engineering/_workitems/edit/46804

**Comment by ShevaDas** [comment]
@jasonjgeiger This should be fixed. Closing it out.
