### ISSUE TITLE
Typo in TSql Microsoft Docs

### ISSUE THREAD

**Issue by JosieBigler** [MicrosoftDocs/feedback#780]
In the [URL](https://docs.microsoft.com/en-us/sql/relational-databases/stored-procedures/execute-a-stored-procedure?view=sql-server-2017) there is a typo.

Under the Recommendations header, first full Paragraph, 2nd sentence: 

> "Because they logically appear in all user- and system- defined databases, they can be executed from any database without having to fully **quality** the procedure name." 

quality should be qualify.

![image](https://user-images.githubusercontent.com/34112636/47102201-adf33e80-d201-11e8-8387-86bbd0d6eef4.png)

**Comment by Powerhelmsman** [comment]
@stevestein Can you take a look at this issue?

**Comment by stevestein** [comment]
@JosieBigler - thanks for pointing this out. The typo has been fixed.
