### ISSUE TITLE
Too many broken links!

### ISSUE THREAD

**Issue by shomavg** [MicrosoftDocs/feedback#782]
**Describe the bug**

**To Reproduce**
1. Go to 'https://docs.microsoft.com/en-gb/learn/'
2. Click on 'Introduction to Containers on Azure' it shows a 404 page.
There are many such links that are giving a 404 on the same site.

**Comment by Powerhelmsman** [comment]
@shomavg Thanks for reporting this bug. I create a internal issue to track it.  https://icm.ad.msft.net/imp/v3/incidents/details/88647986/home Once it is fixed, I will let you know.

**Comment by Powerhelmsman** [comment]
@shomavg All the broken links are fixed. Please double check.
