### ISSUE TITLE
Highlight Modules already taken

### ISSUE THREAD

**Issue by neilhamshaw** [MicrosoftDocs/feedback#783]
**Is your feature request related to a problem? Please describe.**
After taking modules, you have to click on a module to see whether you have completed it or part completed it.

**Describe the solution you'd like**
When looking at the solution track or the tile view of modules available, I would like to see a green or amber tick (and maybe accompanied by a 'Complete' or 'In Progress' in the top corner so I can visually see my progress. Especially useful if a module is part of several tracks.

**Describe alternatives you've considered**
Nothing else considered.

**Additional context**
![image](https://user-images.githubusercontent.com/19870922/47157769-f7b35600-d2e1-11e8-9f68-18d033f0834e.png)
Hopefully the attached image has uploaded correctly. I have completed the Pillars of Great Architecture and the Design for Security in Azure modules, but there is no way to visually see that quickly.

Thanks.

**Comment by Powerhelmsman** [comment]
@ShevaDas Can you follow up this suggestion?

**Comment by ShevaDas** [comment]
@neilhamshaw Thanks for the feedback! This is one of the team's top priorities to implement. Hopefully I'll have a more concrete update soon. :)

**Comment by ShevaDas** [comment]
Merging this with #717
