### ISSUE TITLE
.NET local docs Edit button targets to live-sxs branch.

### ISSUE THREAD

**Issue by imba-tjd** [MicrosoftDocs/feedback#789]
https://docs.microsoft.com/zh-cn/dotnet/welcome
![default](https://user-images.githubusercontent.com/24759802/47274134-e1541580-d5d3-11e8-9cba-2343133ba6b1.png)
This button now targets to live-sxs branch in some local repos, for example zh-cn and ja-jp. ~~But some repos like zh-tw doesn't have this issue.~~ Now all of them have this issue.
I only see this issue in .NET docs.

**Comment by Powerhelmsman** [comment]
@imba-tjd I can't repro your issue. It is pointing to repo dotnet/docs.zh-cn from my side.

**Comment by imba-tjd** [comment]
@Powerhelmsman I know it is pointing to dotnet/docs.zh-cn, but now th `Edit` button points to `live-sxs` **branch** which I suppose should be `live`

**Comment by Powerhelmsman** [comment]
@dend Do you know if there are any changes recently?

**Comment by imba-tjd** [comment]
@CeciAc @JasonCard Hi, Would you mind helping to investigate this?

**Comment by JasonCard** [comment]
@imba-tjd Thank you for reporting this issue. I will look into this and get back to you.
cc @Powerhelmsman @CeciAc

**Comment by JasonCard** [comment]
Hi @imba-tjd This issue has been fixed, so Edit button now got to live branch.
Thank you again for reporting this issue.
cc @Powerhelmsman @CeciAc
