### ISSUE TITLE
Make Azure Doc Issue Backlog Open

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#79]
The Azure Doc community involvement at this time is limited to fixing typos/etc with existing docs. It would be great to have a similar experienc to dotnet and aspnet docs where the backlog is open to the community for contribution.

----------
⚠ Idea migrated from UserVoice

**Created By:** Isaac Levin
**Created On:** 2017/12/07 19:44:51 +0000
**Votes at Migration:** 1
**Supporters at Migration:** 1

**Comment by Powerhelmsman** [comment]
@mairaw Do your team have any plan on this?

**Comment by mairaw** [comment]
I'm on the team that had the backlog open for contribution. But Azure docs has issues open now:
https://github.com/MicrosoftDocs/azure-docs/issues

@isaac2004 was it you who submitted this UserVoice?

**Comment by isaac2004** [comment]
@mairaw it was! I have complained about this for a bit, mostly before I was an FTE. I think the community would love the chances to provide more thoughtful experiences to the Azure docs. IMOP with a heavy dose of salt :)

**Comment by dend** [comment]
Going to close this issue, as @mairaw stated - the issue tracker is already open 😄
