### ISSUE TITLE
Some local .NET docs Edit button targets to live-sxs branch.

### ISSUE THREAD

**Issue by imba-tjd** [MicrosoftDocs/feedback#790]
https://docs.microsoft.com/zh-cn/dotnet/welcome
![default](https://user-images.githubusercontent.com/24759802/47274203-32b0d480-d5d5-11e8-9f7e-65c272d9fd33.png)
Some repos like zh-cn and ja-jp have this issue, while some like zh-tw don't.
I only see this issue in .NET docs.

**Comment by Powerhelmsman** [comment]
duplicated with #789
