### ISSUE TITLE
Typo in windows desktop iphlpapi GetAdaptersAddresses

### ISSUE THREAD

**Issue by Ilya33** [MicrosoftDocs/feedback#792]
**Link to article:**
[Link](https://docs.microsoft.com/en-us/windows/desktop/api/iptypes/ns-iptypes-_ip_adapter_addresses_lh)

**Problem:**
Typo in an example at line 67

`// Make a second call to GetAdapters Addresses to get the` should be `// Make a second call to GetAdaptersAddresses to get the`

without external space between `GetAdapters` and `Addresses` like in comment  at line 55

**Comment by Powerhelmsman** [comment]
@ginami Can you follow up?

**Comment by ginami** [comment]
Hi @Ilya33 -- thank you for your feedback! We're working on the issue.

**Comment by mairaw** [comment]
Article is now at https://docs.microsoft.com/en-us/windows/win32/api/iptypes/ns-iptypes-ip_adapter_addresses_lh

I've opened a PR to fix this: https://github.com/MicrosoftDocs/sdk-api/pull/343
