### ISSUE TITLE
Access Denied

### ISSUE THREAD

**Issue by v-kydela** [MicrosoftDocs/feedback#793]
When I go to any page on https://docs.microsoft.com it says 'Access Denied' and 'You don't have permission to access "http://docs.microsoft.com/" on this server.'

[Screenshot][1]

That's a bit curious for a few reasons. I understand the docs are supposed to be public so why would anyone need permission to access them on any server? Also, the URL it says I can't access is http even though it clearly says https in the address bar.

I'm connected to MSFTCORP (corp.microsoft.com). The problem occurs in both Chrome and Edge. I've tried signing in to different accounts on microsoft.com and it makes no difference. Clearing my browsing data makes no difference.

I've found one thing that fixes it temporarily. After I go to https://myaccess then docs.microsoft.com becomes available again. I'm guessing the myaccess authentication process somehow refreshes my permissions or something. Could there be an authentication bug?

EDIT: Since posting this issue I have lost the ability to fix it by going to the myaccess portal. However, I discovered that the issue is only present when I'm connected to MSFTCORP and not other networks.

  [1]: https://i.stack.imgur.com/ZM9xl.jpg

**Comment by jdhuntington** [comment]
Getting this as well. HTTP response included, as Akami is mentioned and is interesting.

```
curl -v 'https://docs.microsoft.com/en-us/'

# [... snip ...]
< HTTP/1.1 403 Forbidden
< Server: AkamaiGHost
< Mime-Version: 1.0
< Content-Type: text/html
< Content-Length: 282
< Cache-Control: max-age=0
< Expires: Mon, 22 Oct 2018 23:01:17 GMT
< Date: Mon, 22 Oct 2018 23:01:17 GMT
< Connection: close
< x-cache-hit: false
```

**Comment by Powerhelmsman** [comment]
@v-kydela I submitted a internal ticket to report this issue. We will inform you the latest status.

**Comment by v-kydela** [comment]
Docs is working for me today, but I encourage the investigation to continue if a cause hasn't been found

**Comment by Powerhelmsman** [comment]
@v-kydela Thanks for noticing us the issue is fixed. We will keep monitoring the issue.
