### ISSUE TITLE
The TOC tree accessibility is not fully implemented

### ISSUE THREAD

**Issue by Menelion** [MicrosoftDocs/feedback#794]
**Describe the bug**
The TOC tree at docs.microsoft.com is represented as a tree view, and screen reader reports it as such. However, there is no possibility to navigate the tree with arrow keys, like, say, in File Explorer on Windows. This is doable as other websites have this functionality.

**To Reproduce**
1. Install [JAWS for Windows](http://freedomscientific.com/downloads/JAWS), restart your PC and let JAWS launch itself.
2. Go to a Microsoft Docs page, such as [this one](https://docs.microsoft.com/en-us/windows/desktop/http/using-http-server-api).
3. click the TOC button or navigate to it with your keyboard (JAWS announces it as "Contents") and press Enter.
4. when a tree appears, navigate to it and press Enter to go to the forms mode.

**Expected behavior**
When in forms mode, you should be able to expand and collapse branches with right and Left arrows and go up and down the siblings with your Up and Down arrows.. Actually, only Tab works here which is not very comfortable since, if you need something towards the end of the section, you have to tab multiple times.

**Desktop (please complete the following information):**
 - OS: Windows 10 build 1803; Windows 7
 - Browser: Chrome Canary; tested also on IE 11
 - Version: 72.0.3589.0

**Additional context**
I would like to send a PR to DocFX (?) and fix it myself, however since I'm new to DocFX, I couldn't find the tree implementation itself. The fix is quite straightforward, it's just quite a big work with WAI-ARIA.

**Comment by Powerhelmsman** [comment]
@ShevaDas Is this your area?

**Comment by ShevaDas** [comment]
https://ceapex.visualstudio.com/Engineering/UX%20Team/_workitems/edit/46829 for internal tracking

**Comment by Menelion** [comment]
@ShevaDas Sorry, isn't that part open-source? :)

**Comment by ShevaDas** [comment]
@Menelion I don't believe our TOC UX is open-source. Apologies!

**Comment by shirgoldbird** [comment]
@Menelion This work is underway as part of a full engineering effort to make our TOC more usable and accessible. I'll leave another comment once the work ships.

**Comment by shirgoldbird** [comment]
@Menelion this work has shipped as part of a full rewrite of our TOC to be accessible and performant. Please take a look!

I'm going to close out this issue—feel free to open another one if you have additional feedback.
