### ISSUE TITLE
'Sign out' button throws 'Uncaught TypeError'

### ISSUE THREAD

**Issue by IshamMohamed** [MicrosoftDocs/feedback#795]
**Bug description**
"REST API Try It" functionality in https://docs.microsoft.com/en-us/rest/api/azure/ is a great functionality but the 'Sign out' button does not work. This causes confusions at situations where I change IAM of some users in subscriptions.

**To Reproduce**
1. Go to 'https://docs.microsoft.com/en-us/rest/api/consumption/usagedetails/list'
2. Click on 'Try It' button on any HTTP calls
3. Login and select the tenant
4. After you are successfully logged-in, click on 'Sign out' - It will not work
5. Open developer tools > Console to diagnose the problem

**Expected behavior**
It must sign out the current user without any exception

**Screenshots**
![image](https://user-images.githubusercontent.com/2231923/47353959-12c20380-d6f0-11e8-8ad3-028521a0285e.png)

**Desktop :**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 69.0.3497.100

**Comment by Powerhelmsman** [comment]
@dend @sharriexie Can you take a look at this bug?

**Comment by dend** [comment]
#log-suggestion

**Comment by botcrane** [comment]
🚀 **ATTENTION**: [Internal request](https://ceapex.visualstudio.com/web/wi.aspx?pcguid=7d644393-99ad-41c8-ac53-7fa79294c720&id=47102) logged.

**Comment by dend** [comment]
This is now fixed, thanks for the feedback @IshamMohamed!
