### ISSUE TITLE
Typo on Dynamics365 V9 release notes.

### ISSUE THREAD

**Issue by Alex-Collins** [MicrosoftDocs/feedback#796]
**Link to article:**
[Link](https://docs.microsoft.com/en-us/dynamics365/get-started/whats-new/customer-engagement/new-in-version-9-for-developers#pubic-preview-dynamics-365-channel-integration-framework)

**Problem:**
Typo in the first sub-heading. Presumably should read **Public Preview** but currently reads **Pubic Preview**

**Comment by Powerhelmsman** [comment]
@KumarVivek Can you take a look at this issue?

**Comment by KumarVivek** [comment]
Fixed.
