### ISSUE TITLE
message read notification

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#8]
After I send a message from my Outlook account, it is better to report it as read - if the other party reads my message.

For example: I sent a CV to my company looking for workers by making a job application. I'm wondering if you read it. I think sending the question message to the company for the second time is not correct. I would like to report this offer more alternativ. Thank you.

----------
⚠ Idea migrated from UserVoice

**Created By:** Elchin
**Created On:** 2018/03/02 11:03:37 +0000
**Votes at Migration:** 1
**Supporters at Migration:** 1

**Comment by dend** [comment]
Not related to docs.microsoft.com. Closing.
