### ISSUE TITLE
Link PowerShell Gallery module page to the corresponding docs.microsoft.com page

### ISSUE THREAD

**Issue by glibnub** [MicrosoftDocs/feedback#80]
If PowerShell module created by Microsoft is on PowerShell Gallery, it would be useful to have a link on that module's page pointing to a module documentation on docs.microsoft.com.

----------
⚠ Idea migrated from UserVoice

**Created By:** Aleksandar Nikolic
**Created On:** 2017/12/07 11:02:17 +0000
**Votes at Migration:** 1
**Supporters at Migration:** 1

**Comment by dend** [comment]
#log-suggestion

**Comment by botcrane** [comment]
🚀 **ATTENTION**: [Internal request](https://ceapex.visualstudio.com/web/wi.aspx?pcguid=7d644393-99ad-41c8-ac53-7fa79294c720&id=21078) logged.

**Comment by dend** [comment]
@EdisonDa something to think about in terms of PowerShell improvements.

**Comment by EdisonDa** [comment]
Thank you for your suggestion. We will be reviewing it as part of upcoming gallery changes.

**Comment by EdisonDa** [comment]
Thank you for your suggestion, and we will consider your suggestion in upcoming change. Currently, you can go to [PowerShell Module browser](https://docs.microsoft.com/en-us/powershell/module) and search the module name, then you can find its corresponding page in docs.
