### ISSUE TITLE
Incorrect link to view of doc for older version of SQL Server

### ISSUE THREAD

**Issue by vyuschuk** [MicrosoftDocs/feedback#801]
This page indicates clicking a link will take the user to documentation for SQL Express 2014 but it just brings up the same page for SSE 2017.
https://docs.microsoft.com/en-us/sql/database-engine/install-windows/install-sql-server-using-a-configuration-file?view=sql-server-2017

source:
<p>This article is specifically updated for SQL Server 2016 and SQL Server 2017. For older versions of SQL Server, see <a href="install-sql-server-2016-using-a-configuration-file?view=sql-server-2017" data-linktype="relative-path">Install SQL Server 2014 Using a Configuration File</a>.</p>

The link should probably be
https://docs.microsoft.com/en-us/sql/database-engine/install-windows/install-sql-server-using-a-configuration-file?view=sql-server-2014

**Comment by craigg-msft** [comment]
#please-close @Powerhelmsman 
This is fixed in the Pr https://github.com/MicrosoftDocs/sql-docs-pr/pull/9448

**Comment by craigg-msft** [comment]
@tysonn can you please close this

**Comment by craigg-msft** [comment]
fyi @Jemash

**Comment by craigg-msft** [comment]
#please-close
