### ISSUE TITLE
Sample Files

### ISSUE THREAD

**Issue by AnthonyHKOPT** [MicrosoftDocs/feedback#803]
**Is your feature request related to a problem? Please describe.**
I want to practice with samples that Will explained in the video.
Where can I download those files ?
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by dend** [comment]
@AnthonyHKOPT could you please give us some more information on what article this refers to?

**Comment by AnthonyHKOPT** [comment]
I am referring to Will's presentation.

--- 原始郵件 ---

寄件者： "Den Delimarsky" <notifications@github.com>
已傳送： 2018年10月27日 00:14
收件者： "MicrosoftDocs/feedback" <feedback@noreply.github.com>
副本： "AnthonyHKOPT" <minghinghk@outlook.com>, "Mention" <mention@noreply.github.com>
主旨： Re: [MicrosoftDocs/feedback] Sample Files (#803)



@AnthonyHKOPT<https://github.com/AnthonyHKOPT> could you please give us some more information on what article this refers to?

**Comment by Powerhelmsman** [comment]
@dend please take a look at AnthonyHKOPT's response.

**Comment by Powerhelmsman** [comment]
@dend Do you still need more clarification?
