### ISSUE TITLE
Too much content causing DownloadPDF not respond

### ISSUE THREAD

**Issue by acpsa** [MicrosoftDocs/feedback#804]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

**Link to article:**
Download PDF Link on
https://docs.microsoft.com/en-us/aspnet/web-api/overview/getting-started-with-aspnet-web-api/tutorial-your-first-web-api#

**Problem:**
Browser not responding after i try to download the pdf in complete. There should be an option to partially download sections as well

**Comment by dend** [comment]
@naveenchauhanctae can you please provide more information on what the browser and OS is that you are encountering issues with?

**Comment by naveenchauhanctae** [comment]
Hi

The main problem is  the size of Pdf created for the article. Its 300 MB. I cant find option to sub-section creating smaller pdf files.

I am using Google chrome on windows 10.

Thanks 🙂
Naveen Chauhan

On 27-Oct-2018, at 1:21 AM, Den Delimarsky <notifications@github.com<mailto:notifications@github.com>> wrote:


@naveenchauhanctae<https://github.com/naveenchauhanctae> can you please provide more information on what the browser and OS is that you are encountering issues with?

**Comment by Powerhelmsman** [comment]
@dend For your awareness.

**Comment by Powerhelmsman** [comment]
@cillroy Can you take a look at this PDF issue?

**Comment by u100009** [comment]
This is completely true for many other Docs information.. I'm a partner and active in the ERP area.. For years we used to have all the user guides and system documentation in PDF format that could be handed out to the clients (and partly it was installed along the product itself). 
In Dynamics GP, once or twice a year there are Tax Updates release by Microsoft and accordingly a documentation that goes along. This was usually a 15-20 page PDF file that you could send to the clients.. 
This year's 2019/2020 Tax update section is falsely filed under can18yetax which is missleading, and on top of it, when you try to use 'Download PDF' to get the pages, you end up with a 2500+ pages document that contains the entire Dynamics GP documentation.. Not something you want to hand over to the client.  The worst is that you can't even select a section only of the document to get printed. It's all or nothing!
Here's the example I'm talking about : 
https://docs.microsoft.com/en-us/dynamics-gp/payroll/can18yetax

**Comment by JasonWHowell** [comment]
Chrome and Edge both support printing a single page to PDF that should be sufficient for most simple scenarios.

Chrome:
![image](https://user-images.githubusercontent.com/5067358/90088131-25e20100-dcd3-11ea-85eb-36fdb9c93f6c.png)

Edge:
![image](https://user-images.githubusercontent.com/5067358/90088225-5164eb80-dcd3-11ea-8111-f20af1b2656b.png)

Thanks, Jason
