### ISSUE TITLE
Direct link to GitHub for Content feedback is broken

### ISSUE THREAD

**Issue by mairaw** [MicrosoftDocs/feedback#807]
Original GitHub issue https://github.com/dotnet/docs/issues/8676 from @Structed 

On [this documentation page](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.dataannotations.datatype?view=netframework-4.7.2), the direct link to leave feedback on GitHub is broken.

![image](https://user-images.githubusercontent.com/29922/47593493-d56fa700-d977-11e8-82e6-aeb7d8964a97.png)

Instead, it points to `https://docs.microsoft.com/en-us/dotnet/api/%7B0%7D`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71654f5f-8c0e-87c9-8b8c-ad17f578d427
* Version Independent ID: ab6d5a69-3cbc-fcf7-10f2-6e2deb1ed30c
* Content: [DataType Enum (System.ComponentModel.DataAnnotations)](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.dataannotations.datatype?view=netframework-4.7.2)
* Content Source: [xml/System.ComponentModel.DataAnnotations/DataType.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.ComponentModel.DataAnnotations/DataType.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **riande**

**Comment by mairaw** [comment]
It might be due to the fact that are issues from dotnet-api-docs are configured to go to dotnet/docs. But still this should work given we tell the target repo for issues: https://github.com/dotnet/dotnet-api-docs/blob/master/docfx.json#L53

**Comment by Powerhelmsman** [comment]
@jialge Can you take a look at this bug?

**Comment by nschonni** [comment]
This appears to be affecting a lot of repos not just dotnet

**Comment by jialge** [comment]
I am looking at this now.

**Comment by mairaw** [comment]
This seems to be fixed now, correct?

**Comment by Powerhelmsman** [comment]
@mairaw Yes, this is fixed. I will update the status.
