### ISSUE TITLE
APIs for ASP.NET Core 2.2 Preview 3 are missing

### ISSUE THREAD

**Issue by johnduhart** [MicrosoftDocs/feedback#809]
**Describe the bug**
No APIs for ASP.NET Core 2.2 Preview 3 are available.

**To Reproduce**
1. Go to https://docs.microsoft.com/en-us/dotnet/api/index?view=aspnetcore-2.2
2. See "No Namespaces"

**Expected behavior**
I should see a list of available namespaces to browse.

**Comment by dend** [comment]
Thanks for the report, @johnduhart - we will get this addressed shortly.

**Comment by abuassar** [comment]
> 
> 
> Thanks for the report, @johnduhart - we will get this addressed shortly.

ASP.NET 2.2 has been releases officially yet its api still missing from the api browser

**Comment by guardrex** [comment]
Cross-link: https://github.com/MicrosoftDocs/feedback/issues/930 ... it's prob a dup of this issue.

**Comment by dendeli-msft** [comment]
This is already resolved 😄 Thank you for the feedback @johnduhart!
