### ISSUE TITLE
Xamarin Forms  platform control mappings

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#81]
Provide detailed documentation for Xamarin Forms including which native controls each maps to with links to the appropriate UWP/Xamarin Android/iOS etc APIs. Include information on any implementation differences or properties unsupported on specific platforms

----------
⚠ Idea migrated from UserVoice

**Created By:** Peter Foot
**Created On:** 2017/12/07 09:53:54 +0000
**Votes at Migration:** 1
**Supporters at Migration:** 1

**Comment by dend** [comment]
This documentation is now available:
https://docs.microsoft.com/en-us/xamarin/#pivot=platforms&panel=XamarinForms
