### ISSUE TITLE
Spelling Error in Syntax

### ISSUE THREAD

**Issue by s3cur17y15m34n1ngl355** [MicrosoftDocs/feedback#813]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

**Link to article:**
https://docs.microsoft.com/en-us/sql/t-sql/statements/add-sensitivity-classification-transact-sql?view=azuresqldb-current

**Problem:**
In the #Remarks section of the article, the following syntax has an error in it: "ADD SENSITIVITY CLASSIFICTION". I'm reasonably sure this is supposed to be C-L-A-S-S-I-F-I-C-**A**-T-I-O-N.

**Comment by Powerhelmsman** [comment]
@craigg-msft Can you take a look at this content issue?

**Comment by C-Lion** [comment]
It seemed clear from the rest of the document that it is a typos & it was repeated in one other location as well. I just submitted a PR to fix those 2 typos in the repo: https://github.com/MicrosoftDocs/sql-docs/pull/1195

**Comment by craigg-msft** [comment]
@Powerhelmsman to the best of my knowledge, this old issue is resolved.  Can you please close?
