### ISSUE TITLE
Microsoft servicebus and app.config

### ISSUE THREAD

**Issue by ccav01** [MicrosoftDocs/feedback#817]
Please stop f**king up my config files.  1) We don't need your 'help' with config, if you are going to insist on appending stuff to the config, please wrap it all as a comment so I don't end up with bug just because I added/updated servicebus

**Comment by Powerhelmsman** [comment]
@ccav01 Where is your app.config, and who modify your file? Is this Docs site issue?

**Comment by Powerhelmsman** [comment]
@ccav01 I will close this issue so far due to lack of enough information.
