### ISSUE TITLE
Cluster API links are broken

### ISSUE THREAD

**Issue by b-ammons** [MicrosoftDocs/feedback#818]
https://docs.microsoft.com/en-us/previous-versions/windows/desktop/mscs/standard-order-of-preference
https://docs.microsoft.com/en-us/previous-versions/windows/desktop/mscs/general-utility-functions
https://docs.microsoft.com/en-us/previous-versions/windows/desktop/mscs/property-list-parsing-functions
https://docs.microsoft.com/en-us/previous-versions/windows/desktop/mscs/cluster-registry-access-functions

The above are pages that I explicitly seen issues with. All pages associated with Cluster API have the issue.

All links that I have attempted to use that should have taken me to the function information have been broken. I am taken to the 404 page.

Some examples of links that do not work:
https://docs.microsoft.com/en-us/previous-versions/windows/desktop/api/ResApi/nc-resapi-presutil_find_binary_property
https://docs.microsoft.com/en-us/previous-versions/windows/desktop/api/ResApi/nc-resapi-presutil_find_dword_property
https://docs.microsoft.com/en-us/previous-versions/windows/desktop/api/ClusAPI/nf-clusapi-clusterregsetvalue
https://docs.microsoft.com/en-us/previous-versions/windows/desktop/api/ClusAPI/nf-clusapi-clusterresourcecontrol
https://docs.microsoft.com/en-us/previous-versions/windows/desktop/api/ClusAPI/nc-clusapi-pcluster_reg_batch_add_command
https://docs.microsoft.com/en-us/previous-versions/windows/desktop/api/ClusAPI/nc-clusapi-pcluster_reg_create_batch_notify_port
https://docs.microsoft.com/en-us/previous-versions/windows/desktop/api/ClusAPI/nf-clusapi-clusterregcreatekey

**Comment by Powerhelmsman** [comment]
@b-ammons Thanks for your feedback. Unfortunately all the above contents are no longer updated due to out of product lifecycle. Please go to newer version to find up to date document.

**Comment by b-ammons** [comment]
I cannot find a newer version. When I click on the "Recommended Version" button at the top of these pages I am taken to a generic page.

Where is the newer version page?
