### ISSUE TITLE
Build a Win32 API browser

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#82]
I work with Win32 APIs day in and day out. It'd be really handy to have a site similar to the .NET API browser that allows for the browsing and searching of Win32 APIs.

The Windows API Index does a decent job at this (https://msdn.microsoft.com/en-us/library/windows/desktop/ff818516(v=vs.85).aspx) but it's unclear when this has been last updated.

The browser could also offer clear guidance, perhaps via a flag or icon of sorts, of which APIs are deprecated, not-recommended, and direct users elsewhere quickly and easily.

Some potential ideas for bucketing (like Quick Filters on the .NET page?):
- Operating System version minimum applicability
- SKU applicability (e.g. Nano Server APIs are a small fraction)
- API Sets (e.g. core-localization-l1-2-1)

----------
⚠ Idea migrated from UserVoice

**Created By:** [Rafael Rivera](https://github.com/riverar)
**Created On:** 2017/12/07 09:16:38 +0000
**Votes at Migration:** 2
**Supporters at Migration:** 2

**Comment by dend** [comment]
Original idea submitted by @riverar

**Comment by dend** [comment]
Thanks for the feedback, @riverar - there is a significant amount of work that we would need to do to make the existing C/C++ content structured first before we could implement any rich search layer on top of that. At this time, we have no concrete plans to do so, therefore I am closing this issue as we don't expect a Win32 API Browser implemented in the near future.
