### ISSUE TITLE
EFCore API Reference contains test assemblies

### ISSUE THREAD

**Issue by johnduhart** [MicrosoftDocs/feedback#824]
Example: https://docs.microsoft.com/en-us/ef/core/api/microsoft.entityframeworkcore.sqlserver.design.tests.apiconsistencytest

**Comment by dend** [comment]
@divega @Rick-Anderson this looks like legacy API that needs to be redirected to the modern docs: https://docs.microsoft.com/en-us/dotnet/api/?view=efcore-2.1

Can you confirm?

**Comment by divega** [comment]
@dend yes, that is correct. Issue https://github.com/aspnet/EntityFramework.ApiDocs/issues/9 is about setting up redirects and clearing it up, but I don't think it is in anyone's plate to do this. Would it help to track it here?

**Comment by divega** [comment]
@johnduhart If you remember how you reached that page, that would be great. I want to make sure we don't have any links to the old API reference in our conceptual docs.

**Comment by johnduhart** [comment]
@divega iirc it was a google search that landed me on those pages.

**Comment by divega** [comment]
Thanks @johnduhart. Good to know. Once the redirects are in place, that shouldn’t be a problem anymore.

**Comment by dendeli-msft** [comment]
Thanks folks for the feedback - this should be resolved! The new EF Core reference is located [in the .NET API Browser](https://docs.microsoft.com/en-us/dotnet/api/?view=efcore-2.1).

Den Delimarsky ● Senior PM, docs.microsoft.com ● [@DennisCode](https://twitter.com/DennisCode)

**Comment by divega** [comment]
@dendeli-msft is it expected that links to the old API (e.g. https://docs.microsoft.com/ef/core/api/microsoft.entityframeworkcore) return 404? I was expecting it to redirect, but perhaps it is really supposed to fail...

cc @mairaw

**Comment by mairaw** [comment]
I had a redirect request that kept getting closed as done and I kept reopening. Let me see if I can find that again.

**Comment by smitpatel** [comment]
@mairaw - The link Diego posted above does not give 404 now and redirect to .NET API browser. Should this be marked as closed?

**Comment by mairaw** [comment]
Yes, I believe you worked with Alma to remove those test packages from the docs reflection, correct?

**Comment by smitpatel** [comment]
Yes, they are removed.
