### ISSUE TITLE
Enable multi-factor authentication

### ISSUE THREAD

**Issue by Akhil2817** [MicrosoftDocs/feedback#826]
I was just going through the following weblink on  Enable multi-factor authentication

https://docs.microsoft.com/en-us/partner-center/develop/enable-multi-factor-authentication#security-requirements-faq

Under the Security requirements FAQ , the link provided is broken 

However on the extreme  right there are few hyperlinks where the Security requirement FAQ is accessible.

Please have this fixed.

regards,
Anjali

**Comment by Powerhelmsman** [comment]
@Xansky Can you take a look at this content issue?

**Comment by Xansky** [comment]
Thanks for catching this! The link has been fixed.
