### ISSUE TITLE
404 Not found on some pages

### ISSUE THREAD

**Issue by GZibrat** [MicrosoftDocs/feedback#827]
https://docs.microsoft.com/en-us/windows/desktop/secauthn/authentication-functions#functions-implemented-by-sspaps

The links under  "Functions Implemented by SSP/APs" throw 404 errors.

For example:
https://docs.microsoft.com/en-us/windows/desktop/api/Ntsecpkg/nc-ntsecpkg-lsa_ap_logon_user_ex2

**Comment by EsaHeinonen** [comment]
I ran into the same issue on the DirectShow reference pages. For example, none of the links (that I tried) on the "Alphabetical List of DirectShow Interfaces" are working:
[https://docs.microsoft.com/en-us/windows/desktop/directshow/alphabetical-list-of-directshow-interfaces](https://docs.microsoft.com/en-us/windows/desktop/directshow/alphabetical-list-of-directshow-interfaces)

**Comment by Powerhelmsman** [comment]
@ginami Can you take a look at this issue?

**Comment by GZibrat** [comment]
Update here?

**Comment by ginami** [comment]
Hi @GZibrat -- thanks for letting us know about this! We'll get the page updated.

**Comment by carter-musick** [comment]
I'm getting a 404 for pretty much all of the VSTS API documentation
https://docs.microsoft.com/en-us/rest/api/vsts/wit/queries/get - even the "search results that may be helpful" all have 404s

**Comment by GregDomzalski** [comment]
@ginami Any update on this? 25 days and most of the links on https://docs.microsoft.com/en-us/windows/desktop/SecAuthN/authentication-functions under the "Functions implemented by SSP/APs" still are throwing 404s. Additionally, if I get lucky and am able to find the old page in Google's cache or archive.org, all of the linked enumeration / structure definition pages seem to be broken / missing as well.

**Comment by TimShererWithAquent** [comment]
The issue with the "Functions Implemented by SSP/APs" topics looks like a migration issue. I've updated a bunch of these topics to migrate and the changes should go live soon. 

I think the DirectShow topics have a different cause. I'll see if I can find out more.

**Comment by TimShererWithAquent** [comment]
@GZibrat The topics you found in your original post are working. Well, I checked a bunch, but not all, and go no 404s.

**Comment by antlhuede** [comment]
All azure documentation pages are resulting in the same. I used to be able to just spam refresh on the page and it would redirect to an aspnetcore 2.1/2.2 version of the page that was valid. Now refreshing the page does not cause any redirects and I have no idea how to access ANY azure documentation pages.

**Comment by antlhuede** [comment]
The original posters URL is also 404 not found for me.

**Comment by mairaw** [comment]
Closing this one since the original problem seemed to be fixed. I got no hits on the referenced page:
![image](https://user-images.githubusercontent.com/12971179/66987922-7dddb600-f076-11e9-9830-4803ea9ed904.png)

Please report other pages with 404 links separately since different teams own different content.
