### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by birbilis** [MicrosoftDocs/feedback#829]
**Link to article:**
https://docs.microsoft.com/el-gr/previous-versions/windows/desktop/mstv/about-the-dvr-ms-file-format 

**Problem:**
the link to
https://support.microsoft.com/el-gr/help/329979
is broken

I didn't see any comments section btw so posting issue here

**Comment by Powerhelmsman** [comment]
@birbilis Thanks for your feedback. The page is no longer to update due to out of product lifecycle. Please go to the newer version.
