### ISSUE TITLE
Link github or gitbucket for sample code

### ISSUE THREAD

**Issue by docs-product** [MicrosoftDocs/feedback#83]
More sample on those web which can host the code.

----------
⚠ Idea migrated from UserVoice

**Created By:** Richie
**Created On:** 2017/12/07 03:50:39 +0000
**Votes at Migration:** 1
**Supporters at Migration:** 1

**Comment by cillroy** [comment]
We are currently working on exposing more sample code snippets and full sample projects.  I am working with the different content authors to get this readily available.

**Comment by docs-product** [comment]
This is now available: https://docs.microsoft.com/samples
