### ISSUE TITLE
Missing ADK for Windows 10 LTSB 2015

### ISSUE THREAD

**Issue by proof85** [MicrosoftDocs/feedback#831]
Following site does not contain a link for the Windows 10 LTSB 2015 ADK

https://docs.microsoft.com/en-us/windows-hardware/get-started/adk-install

Can you fix this, please?

**Comment by Powerhelmsman** [comment]
@dawnwood Can you take a look at this feedback?

**Comment by dawnwood** [comment]
Yes, @Powerhelmsman I will look into this.

**Comment by dawnwood** [comment]
Hi @proof85 There is no specific ADK for the Windows 10 2015 LTSB, however, that branch is based on Windows 10, version 1507, and can use the equivalent ADK or later, which means you can use any of the Windows 10 ADKs. 
Hope this helps!
Dawn

**Comment by proof85** [comment]
Hi, thank you for the information. Is it possible to include the ADK 1507 on the mentioned site.

(I need to customize the windows recovery environment for Windows 10 LTSB 2015. This is can be done exclusively using the 1507 ADK - adding PE-packages, for example)

**Comment by Powerhelmsman** [comment]
@dawnwood for your awareness.

**Comment by dawnwood** [comment]
I'm looking into it now, stay tuned!!

**Comment by dawnwood** [comment]
Hi @proof85 Thank you very much for your patience. I talked with the engineering team that is responsible for the ADK and the ADK version 1507 is no longer available and is no longer supported. I am sorry that I was not able to help more.
