### ISSUE TITLE
Request docs/Surface Ko-kr Repository

### ISSUE THREAD

**Issue by parkpc** [MicrosoftDocs/feedback#832]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

**Link to article:**
https://docs.microsoft.com/ko-kr/surface/deploy-the-latest-firmware-and-drivers-for-surface-devices

**Problem:**
Korean grammar and translation errors are serious. There are also a lot of grammatical errors in the docs / Surface document itself, so I would like to suggest fixes with Github.

**Comment by Powerhelmsman** [comment]
@SonjaSaltzman Can you take a look at this localization issue?

**Comment by SonjaSaltzman** [comment]
Assigning to @ndolci whose team is in charge of localizing Surface.  Nicola, could you please follow up?

**Comment by Powerhelmsman** [comment]
@ndolci Any updates?

**Comment by SonjaSaltzman** [comment]
@Powerhelmsman @ndolci  has left the team, this should also go to DongMicro

**Comment by srvbpigh** [comment]
Hello, @parkpc
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by SunnyDeng** [comment]
@DavidPrio can you check on this again?

**Comment by srvbpigh** [comment]
Hello, @parkpc
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello @parkpc 

Thank you for your contribution. 

Contributions on translation problems against machine-translated content are currently not accepted. 

We value your feedback and suggestions on human translated content, which is used to train the machine translation engines, so over time, your contributions will improve the quality of both human and machine translations. 

Human translated topics can be distinguished from machine-translated topics by the ms.translationtype metadata value “HT” (versus “MT” for machine translated) in the header of each content file. 

Many thanks for your support. 

Microsoft DOCS Global Experience Team
