### ISSUE TITLE
Administrator left the company and I don't know how to get into company account

### ISSUE THREAD

**Issue by Abraxsys** [MicrosoftDocs/feedback#835]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Powerhelmsman** [comment]
@Abraxsys Sorry to hear that. This is about user privacy. Microsoft has very strict user privacy protection. There is no way for us to let you get into company account.

**Comment by sietec** [comment]
> @Abraxsys Sorry to hear that. This is about user privacy. Microsoft has very **_strict user privacy protection_**. There is no way for us to let you get into company account.

That gave me a great laugh! Thanks:-)
