### ISSUE TITLE
404 Not found on some pages

### ISSUE THREAD

**Issue by ickacn** [MicrosoftDocs/feedback#838]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

**Link to article:**
http://msdn.microsoft.com/en-us/library/windowsazure/dn451351.aspx

**Problem:**
What's wrong with the article?

Windows Azure Desktop Hosting - Reference Architecture and Deployment Guides.  404 not found

**Comment by Powerhelmsman** [comment]
@ickacn When I click the above link. It works now, and the page said: "This information has been moved to the Windows Server library on TechNet. You can find the information at https://technet.microsoft.com/library/mt404690(WS.11).aspx"
