### ISSUE TITLE
Content type link is broken

### ISSUE THREAD

**Issue by alexxn** [MicrosoftDocs/feedback#839]
Page: https://docs.microsoft.com/en-us/previous-versions/dotnet/netframework-4.0/ydy4x04a(v=vs.100)

See description of Content-Type field.

It has a link to MSDN which leads to nowhere
http://go.microsoft.com/fwlink/?linkid=37118

**Comment by Powerhelmsman** [comment]
@alexxn This page is no longer to update due to out of product lifecycle. Please go to the newer version.
