### ISSUE TITLE
Bring the editor for documentation inside vs.net and vscode

### ISSUE THREAD

**Issue by docs-product** [MicrosoftDocs/feedback#84]
Enable to easily bring into the editor a documentation page's source and submit the change, without the need to engage github, fork, clone, PR, etc.

----------
⚠ Idea migrated from UserVoice

**Created By:** Peter Smulovics
**Created On:** 2017/12/07 03:32:16 +0000
**Votes at Migration:** 1
**Supporters at Migration:** 1

**Comment by dend** [comment]
#log-suggestion

**Comment by botcrane** [comment]
🚀 **ATTENTION**: [Internal request](https://ceapex.visualstudio.com/web/wi.aspx?pcguid=7d644393-99ad-41c8-ac53-7fa79294c720&id=21077) logged.

**Comment by meganbradley** [comment]
This is not a priority at this time. Most pages provide an Edit link for lightweight editing, and cloning the repo locally is considered an acceptable process for more in-depth editing.
