### ISSUE TITLE
Filtering on Microsoft Flow or Flow

### ISSUE THREAD

**Issue by JerryCRMI** [MicrosoftDocs/feedback#840]
I was checking out the learn site for Flow cause I was going to do a blog post.

The search function needs some more help or better metadata tagging?

If you search on Flow you get some training that uses the phrase ‘data flow’ in their course bullets.

![image](https://user-images.githubusercontent.com/19864267/48143182-df48b280-e273-11e8-9b22-c14bb4b3278b.png)

But if you search on Microsoft Flow, you get rid of the IoT courses but you also loose one of the real Flow courses.
![image](https://user-images.githubusercontent.com/19864267/48143204-ea034780-e273-11e8-9568-14e153fdf9d6.png)

**Comment by Powerhelmsman** [comment]
@presleyy Can you take a look at this suggestion?

**Comment by presleyy** [comment]
Loop @dastaffo for this learn browse filter suggestion
