### ISSUE TITLE
maximum recursion depth exceeded in  azureml.deploy.DeployClient.service

### ISSUE THREAD

**Issue by Mary268** [MicrosoftDocs/feedback#841]
Hi there, when I am passing a model to deployclient, it gave back an error 'maximum recursion depth exceeded' in the server (show blow). **Could you please advise how to increase the 'maximum recursion depth' in the server ???** (e.g. if it happened in my local, it can be solved as simple as run python code: sys.setrecursionlimit(50000))
Thank you

ValueError: Error serializing clf_NB
Pipeline(steps=[('SnowbStemed_TF', StemmedCountVectorizer(analyzer='word', binary=False, decode_error='strict',
            dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
            lowercase=True, max_df=1.0, max_features=None, min_df=1,
            ngram_range=(1, 1), preprocessor=None, s...e, use_idf=True)), ('NB_Classifier', MultinomialNB(alpha=0.0001, class_prior=None, fit_prior=True))])
RecursionError
maximum recursion depth exceeded

**Comment by Powerhelmsman** [comment]
@Mary268 This channel is about Docs site feedback and content issue instead of Q/A forum. Can you go to https://azure.microsoft.com/en-in/support/community/ to seek the help?
