### ISSUE TITLE
Missing docs for BITMAPV4HEADER and BITMAPV5HEADER

### ISSUE THREAD

**Issue by SlyEcho** [MicrosoftDocs/feedback#842]
**Link to articles:**
https://docs.microsoft.com/en-us/windows/desktop/api/Wingdi/ns-wingdi-bitmapv4header
https://docs.microsoft.com/en-us/windows/desktop/api/Wingdi/ns-wingdi-bitmapv5header

**Problem:**
Articles are missing.

They are linked from https://docs.microsoft.com/en-us/windows/desktop/gdi/bitmap-header-types for example.

**Comment by Powerhelmsman** [comment]
@ginami Can you take a look at this issue?

**Comment by ginami** [comment]
Hi @SlyEcho --thank you for letting us know! We'll investigate and get back to you.

**Comment by drewbatgit** [comment]
These links are resolving correctly now.

**Comment by SlyEcho** [comment]
Yes, they are working now.
