### ISSUE TITLE
Auto-translate of the website translates also commands

### ISSUE THREAD

**Issue by patrickemmerich** [MicrosoftDocs/feedback#843]
Your auto-translate feature of the website translates also commands, e.g. the pretty useful linux command 'export' to german 'exportieren'. Unfortunately, my linux system does not speak german and hence translating that command renders it pretty useless.

**Comment by Powerhelmsman** [comment]
@SonjaSaltzman Can you take a look at this feedback?

**Comment by SonjaSaltzman** [comment]
@patrickemmerich, thank you for your feedback. Could you please provide a couple sample URLs, and we'll try to fix that problem!

**Comment by patrickemmerich** [comment]
See https://docs.microsoft.com/de-de/sql/connect/odbc/linux-mac/installing-the-driver-manager?view=sql-server-2017, Manuelle Installation, 6.:

"Führen Sie an einer Eingabeaufforderung den Befehl: exportieren CPPFLAGS."

"exportieren" ist translation of "export", but should not be translated, since it is a Linux command.

**Comment by SonjaSaltzman** [comment]
thank you @patrickemmerich for the quick reply!
Adding @nokura to follow up on the feedback for SQL.

**Comment by nokura** [comment]
Hello @patrickemmerich 
Thank you for your feedback. 
We are looking into the issue you brought and will get back to you when we make the decision. 
Best Regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hi @patrickemmerich 
Thank you for your feedback.
 
Our engineer team reviewed your suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/de-de/sql/connect/odbc/linux-mac/installing-the-driver-manager?view=sql-server-2017. 

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.

Kind regards,
Microsoft DOCS International Team
