### ISSUE TITLE
Code snippet is commented out by mistake

### ISSUE THREAD

**Issue by fame** [MicrosoftDocs/feedback#844]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

**Link to article:**
https://docs.microsoft.com/en-us/previous-versions/msp-n-p/dn589799%28v%3dpandp.10%29

**Problem:**
Notice in the Example section, C# code snippet's are completely commented out

**Comment by Powerhelmsman** [comment]
@fame Unfortunately, the content is no longer to update due to out of product lifecycle. Please go to the newer version.
