### ISSUE TITLE
Error in text in Russian tutorial

### ISSUE THREAD

**Issue by LadyNaggaga** [MicrosoftDocs/feedback#849]
Hello we received the issue below on try .net repo. Could you please have a look ?
https://github.com/dotnet/try/issues/140

> https://docs.microsoft.com/ru-ru/dotnet/csharp/quick-starts/list-collection?tutorial-step=3
> Text:
> 
> > Если он имеет значение 1, элемент не найден
> 
> Correct version:
> Если он имеет значение -1, элемент не найден

**Comment by Powerhelmsman** [comment]
@SonjaSaltzman Can you take a look at this issue?

**Comment by JasonCard** [comment]
@DavidPrio Could you please help to move this issue to Russian loc repo and follow up?
Russian translation is missing minus sign "-" before 1 as mentioned in first comment.

**Comment by CeciAc** [comment]
Hi @JasonCard 
I can't find the ru-ru repo to move this issue in the zenhub list (confirm I'd be https://github.com/dotnet/docs.ru-ru) but we can work it from here, would that be ok?

Kind regards
Microsoft DOCS International Team
@DavidPrio

**Comment by JasonCard** [comment]
Hi @CeciAc 
Yes, please help to manually move this issue to [https://github.com/dotnet/docs.ru-ru](https://github.com/dotnet/docs.ru-ru).
I also tried ZenHub, but maybe it cannot handle moving issues between repos in different orgs.

**Comment by DavidPrio** [comment]
Hi @JasonCard @CeciAc can you try with https://help.github.com/articles/transferring-an-issue-to-another-repository/ 
This is new feature coming directly from GitHub, just shared by @Sara-Nicolini this week. Thanks!

**Comment by CeciAc** [comment]
Hi @JasonCard 
I created a new issue manually here: https://github.com/dotnet/docs.ru-ru/issues/150 

@DavidPrio I tried but couldn't use that feature either, I even temporally deactivate ZenHub but the mentioned option did not appear. Let me know if we may be missing anything

![imagen](https://user-images.githubusercontent.com/26746247/48284309-cc81d980-e43d-11e8-9875-21c3b5810119.png)
