### ISSUE TITLE
Add a way to view API diffs between versions

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#85]
Add a way to see added / removed / changed API signatures for Frameworks, .NET Standard and Windows 10 SDK versions.

----------
⚠ Idea migrated from UserVoice

**Created By:** Adam Hill
**Created On:** 2017/12/07 03:32:06 +0000
**Votes at Migration:** 1
**Supporters at Migration:** 1

**Comment by dend** [comment]
#log-suggestion

**Comment by botcrane** [comment]
🚀 **ATTENTION**: [Internal request](https://ceapex.visualstudio.com/web/wi.aspx?pcguid=7d644393-99ad-41c8-ac53-7fa79294c720&id=21076) logged.

**Comment by dend** [comment]
Thank you for the feedback! At this time, we have no plans on implementing this functionality on docs.microsoft.com.
