### ISSUE TITLE
https://docs.microsoft.com/de-de/windows-server/index

### ISSUE THREAD

**Issue by UdoBross** [MicrosoftDocs/feedback#850]
The Website is not reachable

https://docs.microsoft.com/de-de/windows-server/index

Error 404

Thanks
Udo

**Comment by Powerhelmsman** [comment]
@SonjaSaltzman When I click the above link, it always redirect to en-us page. Can you take a look at this?

**Comment by SonjaSaltzman** [comment]
@ndolci - is this your content set? Could you please follow up?  thanks!

**Comment by UdoBross** [comment]
hi, when i open the page from de-de the error is 404. But it is ok for me when i can open the en-us page directly.
but for all users from Germany it is a bad thing that the forwarding does not work.

**Comment by SonjaSaltzman** [comment]
@dongmicro looks like another one

**Comment by srvbpigh** [comment]
Hello, @UdoBross
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by SonjaSaltzman** [comment]
This is fixed, closing this issue.
