### ISSUE TITLE
Microsoft MCA Agreement

### ISSUE THREAD

**Issue by HitechCFO** [MicrosoftDocs/feedback#851]
Our customers are all very large, very sophisticated customers with very large legal departments. We are an ISV and a CSP. Our application is available only on Azure. 
- do we have to present the MCA to our customers? We are not sure if the communication from Microsoft on mandatory acceptance applies to us and our application. With whom can we check to see if it applies or not ? 
- When we present the MCA and they take issue with it, please advise to whom we are to direct their comments and queries to get resolution. 

Thank you

**Comment by Powerhelmsman** [comment]
@HitechCFO This is a channel for Docs site feedback and site issue only. You probably can go to https://partner.microsoft.com/en-us/support to seek answer.
