### ISSUE TITLE
Enable FOR JSON feature in Azure SQL Data Warehouse

### ISSUE THREAD

**Issue by furia10** [MicrosoftDocs/feedback#855]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by furia10** [comment]
Hi,

FOR clause is not supported yet in Azure SQL Data Warehouse:
https://docs.microsoft.com/en-us/sql/t-sql/queries/select-for-clause-transact-sql?view=sql-server-2017

Please add support for this feature so that we can generate JSON and XML code through FOR JSON and FOR XML:
https://docs.microsoft.com/en-us/sql/relational-databases/json/format-query-results-as-json-with-for-json-sql-server?view=sql-server-2017

This is a must to integrate Azure SQL Data Warehouse with several NoSQL databases and other Big Data technologies,

Thank you.

**Comment by Powerhelmsman** [comment]
@furia10 this is a product feedback instead of content issue. please go to https://feedback.azure.com/forums/34192--general-feedback
