### ISSUE TITLE
Auto-translate make the formatting is off

### ISSUE THREAD

**Issue by abc1236762** [MicrosoftDocs/feedback#858]
**Describe the bug**
Some page shows `:::column-end:::`, `:::row-end:::`, etc and the formatting is off when it is auto-translated from English.
You can see the problem at [XAML 佈景主題資源](https://docs.microsoft.com/zh-tw/windows/uwp/design/controls-and-patterns/xaml-theme-resources), [色彩](https://docs.microsoft.com/zh-tw/windows/uwp/design/style/color), etc.

**To Reproduce**
Use document `XAML theme resources` to explain the problem:
1. Go to [XAML 佈景主題資源](https://docs.microsoft.com/zh-tw/windows/uwp/design/controls-and-patterns/xaml-theme-resources)
2. You can see 'This article was translated by machine.', so this page is auto-translated from English.
3. Scroll down to 'Light theme'.
4. See `:::row::: :::column:::`, `:::row-end:::`, etc.
5. Scroll down to 'Base', '清單', 'Chrome'.
6. Compare with [XAML theme resources](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/xaml-theme-resources), see the formatting is off on each `Dark theme` image and `Light theme` image.
7. Switch `閱讀英文` to see the English version, the problem also exists.

**Screenshots**
![default](https://user-images.githubusercontent.com/11353779/48411252-f9a2f480-e77b-11e8-96e6-97bff741805e.png)

![default](https://user-images.githubusercontent.com/11353779/48411212-daa46280-e77b-11e8-91a9-d0022b5cd8d0.png)

![default](https://user-images.githubusercontent.com/11353779/48411652-1855bb00-e77d-11e8-9899-7b6d127ee63b.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 1809
 - Browser: Firefox 63.0.1 and Google Chrome 70.0.3538.102

**Additional context**

**Comment by Powerhelmsman** [comment]
@SonjaSaltzman Can you take a look at this issue. It looks like localization issue.

**Comment by SonjaSaltzman** [comment]
@dongmicro, could you please take a look, this looks like Windows content

**Comment by SonjaSaltzman** [comment]
@nokura & @v-nidolc could you please check into this?

**Comment by srvbpigh** [comment]
Hello, @abc1236762
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by v-cakoll** [comment]
This topic is no longer translated by machine. The issue no longer occurs.

**Comment by srvbpigh** [comment]
Hello, @abc1236762
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team
