### ISSUE TITLE
https://docs.microsoft.com/en-us/system-center/vmm/upgrade

### ISSUE THREAD

**Issue by kaliyan** [MicrosoftDocs/feedback#859]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kaliyan** [comment]
VMM Deploy page error 404

**Comment by Powerhelmsman** [comment]
@kaliyan Where did you get the link?

**Comment by Powerhelmsman** [comment]
@kaliyan I will close this issue so far due to lack of enough information.
