### ISSUE TITLE
I get dizzy when I see your documents

### ISSUE THREAD

**Issue by linghuchong123** [MicrosoftDocs/feedback#862]
**🛑** **🛑** **🛑**
**Link to article:**
[https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.requestformlimitsattribute.multipartbodylengthlimit?view=aspnetcore-2.1](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.requestformlimitsattribute.multipartbodylengthlimit?view=aspnetcore-2.1)

**Problem:**
in Mb? in Gb? or in Tb? or in Pb? or it's Eb???? I get dizzy when I read your documents

**Comment by ibakirov** [comment]
> **Problem:**
> in Mb? in Gb? or in Tb? or in Pb? or it's Eb???? I get dizzy when I read your documents
None of them, because value can long = System.Int64 (eg: 1024, 2048 and etc.)

**Comment by linghuchong123** [comment]
@ibakirov  I don't know if it's in byte or others, I'd like to make sure, can you put it in more  detail?

**Comment by ibakirov** [comment]
@linghuchong123 the value is represented in **B (bytes)**. I agree that documentation should clarify the unit. MultipartBodyLengthLimit property is used to set the maximum length for multipart body length for the used form (example: file upload forms)

**Comment by linghuchong123** [comment]
thank you @ibakirov
