### ISSUE TITLE
Broken format in "GetClassName function" documentation

### ISSUE THREAD

**Issue by stephen9357** [MicrosoftDocs/feedback#866]
**Link to article:**
https://docs.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-getclassname

**Problem:**
Format of description for _nMaxCount_ param is broken.

**Comment by Powerhelmsman** [comment]
@ginami Can you take a look at this issue?

**Comment by ginami** [comment]
Thank you @stephen9357 for letting us know! We'll work on fixing the formatting.
