### ISSUE TITLE
Filter out completed modules at Microsoft Learn

### ISSUE THREAD

**Issue by kmsft** [MicrosoftDocs/feedback#869]
**Is your feature request related to a problem? Please describe.**
It is not easy to tell which modules I have already completed out of the 100+ modules.  

**Describe the solution you'd like**
- I want an easy way to filter out the modules that I have already completed
- A visual indicator to show that I already have completed a module is another option, but this doesn't completely replace the ability to filter out completed modules

**Describe alternatives you've considered**
- rely on my memory
- if my memory is not good, then I click into each module and look for the completion status (via the XP points)

**Additional context**

**Comment by lkuhn65** [comment]
I agree with this suggestion.  Show me a checkmark when browsing on the modules I have already completed and/or allow me to filter out the ones I have already done.

**Comment by kmsft** [comment]
thanks @Powerhelmsman !
