### ISSUE TITLE
"Secure your Azure SQL Database" doesn't show up in "SQL Database" filter at Microsoft Learn

### ISSUE THREAD

**Issue by kmsft** [MicrosoftDocs/feedback#870]
**Describe the bug**
Filtering by Azure --> SQL Database, does not list all SQL related training modules

**To Reproduce**
1. Go to 'https://docs.microsoft.com/en-us/learn/browse/'
2. Click on 'SQL Database'
3. Only 4 results are found, "Secure your Azure SQL Database" is not among the 4 results returned
4. Uncheck 'SQL Database'
5. The first training module is "Secure your Azure SQL Database"

**Expected behavior**
Filtering by Azure --> SQL Database should list the learning module "Secure your Azure SQL Database" 
https://docs.microsoft.com/en-us/learn/modules/secure-your-azure-sql-database

**Screenshots**

![Uploading image.png…]()

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version 70

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Powerhelmsman** [comment]
@jboeshart Can you take a look at this suggestion? It can solved by adding a SQL database in meta data of yml file.

**Comment by markjulmar** [comment]
This sounds like we just missed the metadata tags. Is it something bigger than that @jboeshart ?

**Comment by jboeshart** [comment]
Issue is now resolved, fix merged in #3075 and confirmed that it now shows up with the SQL Database product filter.

Please close.
