### ISSUE TITLE
Hardware and Software Requirements for Installing SQL Server "2014" version mismatch

### ISSUE THREAD

**Issue by chanmmn** [MicrosoftDocs/feedback#873]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.
Hardware and Software Requirements for Installing SQL Server 2014 but I am actually looking for Hardware and Software Requirements for Installing SQL Server 2016.

**Link to article:**
Tell us where exactly a problem occurs.
https://docs.microsoft.com/en-us/sql/2014/sql-server/install/hardware-and-software-requirements-for-installing-sql-server?view=sql-server-2016

**Problem:**
What's wrong with the article?
When I choose SQL Server 2016 from the left pane somehow he title show "Hardware and Software Requirements for Installing SQL Server 2014".
Screen capture is here https://1drv.ms/u/s!AlUZkNIm6J4hgj0k_0NepJ-JUrnD

**Comment by Powerhelmsman** [comment]
@MightyPen @craigg-msft Can you take a look at this issue?

**Comment by MightyPen** [comment]
@Powerhelmsman Hi Jian, can you please remove Craigg-msft from this Issue 873.  I will handle it.

**Comment by MightyPen** [comment]
@chanmmn Hello Chanmmn, There seems to be a bug in our "Versioning" system, or in how we are implementing the system in our repo 'MicrosoftDocs/sql-docs'.  This might take a few days to figure out.
Thank you for bringing this concern to Microsoft's attention.
Meanwhile, the work-around is to manually remove the '2014/' node from the Https URL.....
.
UNWANTED URL NODE '/2014/':
https://docs.microsoft.com/sql/2014/sql-server/install/hardware-and-software-requirements-for-installing-sql-server?view=sql-server-2016
.
WORK-AROUND IS TO ERASE THE '/2014/' NODE, REPLACING WITH JUST '/':
https://docs.microsoft.com/sql/sql-server/install/hardware-and-software-requirements-for-installing-sql-server?view=sql-server-2016
.
To clarify, the '2014/' node is needed IF but only if, the goal is to view content for version SQL Server 2014.
Thanks, GeneMi

**Comment by MightyPen** [comment]
@chanmmn Hello Chanmmn, with our private repo PR 8173, we are optimistic that we have a fix for the error you found in our Versioning implementation.
I expect to test the fix this week, and I will update the status of this Issue 873 then.
Thanks!
.
https://github.com/MicrosoftDocs/sql-docs-pr/pull/8173 
https://ceapex.visualstudio.com/Engineering/_workitems/edit/51470
.
