### ISSUE TITLE
How to create parameters and use them in calculation of measures and columns in DAX

### ISSUE THREAD

**Issue by rehamt** [MicrosoftDocs/feedback#876]
I need to know how to add an interval from date to date in DAX, and then to include the values 
entered in the calculation of other measures or columns.

Example : 
I have a list of requests will be retrieved based on a selected period of time 
(from 1/1/2018 to 6/1/2018)
for each selected row if the request date > end of the period (in this example 6/1/2018) then 
var = end of the period (6/1/2018)
else
var = request date
 
Thanks

**Comment by Powerhelmsman** [comment]
@rehamt This is a channel for Docs site feedback instead of general questions. Can you go https://community.powerbi.com/t5/Forums/ct-p/Forums to post your question?
