### ISSUE TITLE
Missing a backslash in pipe name

### ISSUE THREAD

**Issue by xiaoyinl** [MicrosoftDocs/feedback#877]
**Link to article:**
https://docs.microsoft.com/en-us/windows/desktop/api/winbase/nf-winbase-createnamedpipea
https://docs.microsoft.com/en-us/windows/desktop/api/Winbase/nf-winbase-createmailslota

**Problem:**
The article says the pipe name must have the form `\.\pipe<i>pipename`. It should be `\\.\pipe\pipename`. Similar for CreateMailslotA.

**Comment by Powerhelmsman** [comment]
@ginami Can you take a look at this feedback?

**Comment by ginami** [comment]
HI @xiaoyinl --thank you for letting us know. We'll work on updating the page.

**Comment by seltzy** [comment]
I just ran into this. It was very misleading.

**Comment by xiaoyinl** [comment]
Fixed by MicrosoftDocs/sdk-api#76
