### ISSUE TITLE
Members section missing in _SECURITY_DESCRIPTOR structure article

### ISSUE THREAD

**Issue by xiaoyinl** [MicrosoftDocs/feedback#879]
**Link to article:**
https://docs.microsoft.com/en-us/windows/desktop/api/winnt/ns-winnt-_security_descriptor

**Problem:**
The **Members** section is empty. There's no explanation of the fields of the `_SECURITY_DESCRIPTOR` structure.

**Comment by Powerhelmsman** [comment]
@ginami Can you take a look at this issue?

**Comment by xiaoyinl** [comment]
Close issue since this is an undocumented internal structure anyway.
