### ISSUE TITLE
.Net API Browser

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#88]
In the .Net API Browser, it would be helpful in resolving NuGet screwups if the docs show the assembly containing the namespace/API

----------
⚠ Idea migrated from UserVoice

**Created By:** Anonymous
**Created On:** 2017/11/23 10:43:23 +0000
**Votes at Migration:** 1
**Supporters at Migration:** 1

**Comment by dend** [comment]
Duplicate of #72
