### ISSUE TITLE
Japanese Translation of "deprecated" is incorrect.

### ISSUE THREAD

**Issue by DaisukeEda** [MicrosoftDocs/feedback#881]
**Link to article:**
Title: Organization data service
URL(en) : https://docs.microsoft.com/en-us/dynamics365/customer-engagement/developer/developer-resources-page#organization-data-service
URL(jp) : https://docs.microsoft.com/ja-jp/dynamics365/customer-engagement/developer/developer-resources-page#organization-data-service

English Version :
The Organization Data service has been deprecated and replaced by the Web API. For more information about the Web API see Use the Dynamics 365 Web API.

Japanese Version :
組織のサービスは、廃止され、Web API に置き換えられました。 Web API の詳細については、Dynamics 365 Web API の使用 を参照してください。

**Problem:**
The expression " 廃止され" means "has been removed". People who read this article believe that the feature is already removed. "Deprecated" should transrate to "廃止予定" in Japanese. So that please change it as below.

組織のサービスは、廃止予定となり、Web API に置き換えられました。 Web API の詳細については、Dynamics 365 Web API の使用 を参照してください。

**Comment by Powerhelmsman** [comment]
@SonjaSaltzman Can you take a look at this localization issue?

**Comment by SonjaSaltzman** [comment]
@krisre and @vinceno can you please follow up? thanks!

**Comment by vinceno** [comment]
This is 'Customer Engagement' developer content, so will leave to @krisre and @mhogan73

**Comment by mhogan73** [comment]
Hi- we will investigate the issie. Thx.

**Comment by yumetodo** [comment]
ref: #602

**Comment by mhogan73** [comment]
I have reviewed this issue again with the localization suppliers and some internal Japanese speakers and they have all agreed that the translation online is correct. The Organization Data Service was deprecated in CRM 2016 (version 8.x) and this has been reflected in the translation. 

Please note the current translation is following the source correctly.  " 廃止され" means "has been deprecated" , while the suggested translation of "廃止予定となり​” means "planned to be deprecated".

**Comment by yumetodo** [comment]
move to #602.

**Comment by SonjaSaltzman** [comment]
@mhogan73 could you please follow up?

**Comment by mhogan73** [comment]
We are making a change to the topic, this should be published live soon. I will update you when the topic is Live. Thanks.

**Comment by mhogan73** [comment]
@yumetodo PLease note the topic has been updated. Can you please review ? Thx, https://docs.microsoft.com/ja-jp/dynamics365/customer-engagement/developer/developer-resources-page#organization-data-service
