### ISSUE TITLE
Articel about custom SSMS RDL reporting templates

### ISSUE THREAD

**Issue by Proavtor** [MicrosoftDocs/feedback#883]
**Link to article:**
https://docs.microsoft.com/en-us/sql/ssms/object/add-a-custom-report-to-management-studio?view=sql-server-2014

**Problem:**
Tis is very useful article but is has broken link to samles of standard SSMS RDL templates. Here is this link http://go.microsoft.com/fwlink/?LinkId=81792
Please update this link. Developers should have samles to develop new nice reports!

**Comment by Powerhelmsman** [comment]
@Proavtor The page is under migration:  "THE BLOG YOU ARE ATTEMPTING TO ACCESS IS SCHEDULED FOR MIGRATION, PLEASE CHANGE YOUR URL TO GO TO HTTP://BLOGS.MSDN.COM/ OR HTTP://BLOGS.TECHNET.COM/, ONCE THE BLOG IS MIGRATED, YOU WILL AUTOMATICALLY GET REDIRECTED TO THE NEW BLOG SITE" Please check it later.
