### ISSUE TITLE
Please, do not localize docs in Russian on the site automatically. Translations full of bugs. It's impossibleто read.

### ISSUE THREAD

**Issue by p1eXu5** [MicrosoftDocs/feedback#885]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

**Link to article:**
everywhere on the site.

**Problem:**
Your Russian eto pizdec!

**Comment by yumetodo** [comment]
I just remembered https://github.com/dotnet/docs.ja-jp/issues/118.

**Comment by Powerhelmsman** [comment]
@SonjaSaltzman Can you follow up this concern?

**Comment by SonjaSaltzman** [comment]
Hi @p1eXu5, thank you for giving feedback. Could you please explain exactly the steps/URLs you are looking at? We have a mix of human-translated and translation memory + machine-translated content on the site, so it would be very helpful to us to know some of the bad sample pages.  Thanks for your help!

**Comment by p1eXu5** [comment]
for example. if I forgot term name and typing some like "c# семафор" I get a links to "https://docs.microsoft.com/ru-ru/dotnet/api/system.threading.semaphore?view=netframework-4.7.2". I would like to get link to english page, because "позволяя трех потоков в семафор." and "Каждый раз, когда выпускается семафора, счетчик семафора предыдущих отображается." causes wtf questions.

**Comment by SonjaSaltzman** [comment]
Adding @JasonCard. I believe this content is a mix of human and machine translated content.  @p1eXu5 has actually helped us find a bug - the page should have the machine-translation disclaimer, we will work on a fix for this.
@p1eXu5, for the mean time, if you do not want to see any Russian content at all, you can switch your language picker (bottom left of the site) to English.  
![image](https://user-images.githubusercontent.com/15201704/49409037-ca94f880-f713-11e8-8706-0d0b6d84f12b.png)
Or, if it is just certain pages you would prefer to see a topic in English while staying in the localized site chrome, you can use the "Read in English" toggle on the top right of the page.
![image](https://user-images.githubusercontent.com/15201704/49409059-dc769b80-f713-11e8-922b-c7c2bf52edf1.png)

**Comment by JasonCard** [comment]
@p1eXu5 @SonjaSaltzman I confirm this content is a mix of human and machine translation, which is not always perfectly understandable. As Sonja mentioned, please use the "Read in English" option on the right which allows you to switch to the English version without having to change the language settings.
We will be working on a fix to have the machine-translation disclaimer even when the article is mix of human and machine translation.

Kind regards,
Microsoft DOCS International Team
