### ISSUE TITLE
Control version of Power BI Documentation

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#89]
At the Speed of evolution of Power BI,  Control version is Needed...  At Best there would be a score Card of each logged user, with what he read and/or Was since updated... 
At least Implement an email notice of news and updates to the documentation. 

----------
⚠ Idea migrated from UserVoice

**Created By:** Anonymous
**Created On:** 2017/11/20 16:51:40 +0000
**Votes at Migration:** 1
**Supporters at Migration:** 1

**Comment by dend** [comment]
This is related to PowerBI product feedback, hence cannot be addressed in this forum.
