### ISSUE TITLE
Set up DKIM so that a third-party service can send, or spoof, email on behalf of your custom domain

### ISSUE THREAD

**Issue by DrupalLT** [MicrosoftDocs/feedback#892]
on https://docs.microsoft.com/en-us/office365/SecurityCompliance/use-dkim-to-validate-outbound-email#DKIMMultiDomain  in article  "Set up DKIM so that a third-party service can send, or spoof, email on behalf of your custom domain"   is written "2. Contoso published the DKIM key to its DNS record." . 
BUT HAW to make it for third-party domain?

**Comment by Powerhelmsman** [comment]
@DrupalLT Your issue is transferred to office365 team. They will help you there.
