### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by LiHanGod** [MicrosoftDocs/feedback#894]
Fedora-29
[root@Fedora-Server yum.repos.d]# sudo curl -o /etc/yum.repos.d/mssql-server.repo https://packages.microsoft.com/config/rhel/7/mssql-server-preview.repo
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   240  100   240    0     0    895      0 --:--:-- --:--:-- --:--:--   895
[root@Fedora-Server yum.repos.d]# yum install -y mssql-server
packages-microsoft-com-mssql-server-preview                                                                                           231 kB/s | 1.7 MB     00:07    
Last metadata expiration check: 0:00:06 ago on Mon 26 Nov 2018 04:41:00 PM CST.
Dependencies resolved.
======================================================================================================================================================================
 Package                          Arch                       Version                            Repository                                                       Size
======================================================================================================================================================================
Installing:
 mssql-server                     x86_64                     15.0.1100.94-1                     packages-microsoft-com-mssql-server-preview                     217 M

Transaction Summary
======================================================================================================================================================================
Install  1 Package

Total download size: 217 M
Installed size: 217 M
Downloading Packages:
mssql-server-15.0.1100.94-1.x86_64.rpm                                                                                                273 kB/s | 217 MB     13:34    
----------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                                 273 kB/s | 217 MB     13:34     
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                                                              1/1 
Installed: mssql-server-15.0.1100.94-1.x86_64
  Running scriptlet: mssql-server-15.0.1100.94-1.x86_64                                                                                                           1/1 
  Installing       : mssql-server-15.0.1100.94-1.x86_64                                                                                                           1/1 
  Running scriptlet: mssql-server-15.0.1100.94-1.x86_64                                                                                                           1/1 
Installed: mssql-server-15.0.1100.94-1.x86_64
  Verifying        : mssql-server-15.0.1100.94-1.x86_64                                                                                                           1/1 

Installed:
  mssql-server-15.0.1100.94-1.x86_64                                                                                                                                  

Complete!
[root@Fedora-Server yum.repos.d]# /opt/mssql/bin/mssql-conf setup
Choose an edition of SQL Server:
  1) Evaluation (free, no production use rights, 180-day limit)
  2) Developer (free, no production use rights)
  3) Express (free)
  4) Web (PAID)
  5) Standard (PAID)
  6) Enterprise (PAID)
  7) Enterprise Core (PAID)
  8) I bought a license through a retail sales channel and have a product key to enter.

Details about editions can be found at
https://go.microsoft.com/fwlink/?LinkId=852748&clcid=0x409

Use of PAID editions of this software requires separate licensing through a
Microsoft Volume Licensing program.
By choosing a PAID edition, you are verifying that you have the appropriate
number of licenses in place to install and run this software.

Enter your edition(1-8): 2
The license terms for this product can be found in
/usr/share/doc/mssql-server or downloaded from:
https://go.microsoft.com/fwlink/?LinkId=855862&clcid=0x409

The privacy statement can be viewed at:
https://go.microsoft.com/fwlink/?LinkId=853010&clcid=0x409

Enter the SQL Server system administrator password: 
Confirm the SQL Server system administrator password: 
Configuring SQL Server...

This is an evaluation version.  There are [159] days left in the evaluation period.
ForceFlush is enabled for this instance. 
ForceFlush feature is enabled for log durability.
Created symlink /etc/systemd/system/multi-user.target.wants/mssql-server.service → /usr/lib/systemd/system/mssql-server.service.
Setup has completed successfully. SQL Server is now starting.
[root@Fedora-Server yum.repos.d]# systemctl status mssql-server
● mssql-server.service - Microsoft SQL Server Database Engine
   Loaded: loaded (/usr/lib/systemd/system/mssql-server.service; enabled; vendor preset: disabled)
   Active: active (running) since Mon 2018-11-26 16:57:06 CST; 24s ago
     Docs: https://docs.microsoft.com/en-us/sql/linux
 Main PID: 12608 (sqlservr)
    Tasks: 135
   Memory: 703.8M
   CGroup: /system.slice/mssql-server.service
           ├─12608 /opt/mssql/bin/sqlservr
           └─12637 /opt/mssql/bin/sqlservr

Nov 26 16:57:10 Fedora-Server sqlservr[12608]: [145B blob data]
Nov 26 16:57:10 Fedora-Server sqlservr[12608]: [62B blob data]
Nov 26 16:57:10 Fedora-Server sqlservr[12608]: [61B blob data]
Nov 26 16:57:11 Fedora-Server sqlservr[12608]: [96B blob data]
Nov 26 16:57:11 Fedora-Server sqlservr[12608]: [66B blob data]
Nov 26 16:57:11 Fedora-Server sqlservr[12608]: [75B blob data]
Nov 26 16:57:11 Fedora-Server sqlservr[12608]: [96B blob data]
Nov 26 16:57:11 Fedora-Server sqlservr[12608]: [100B blob data]
Nov 26 16:57:11 Fedora-Server sqlservr[12608]: [71B blob data]
Nov 26 16:57:11 Fedora-Server sqlservr[12608]: [124B blob data]
[root@Fedora-Server yum.repos.d]# sudo curl -o /etc/yum.repos.d/msprod.repo https://packages.microsoft.com/config/rhel/7/prod.repo
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   193  100   193    0     0    215      0 --:--:-- --:--:-- --:--:--   215
[root@Fedora-Server yum.repos.d]# sudo yum remove unixODBC-utf16 unixODBC-utf16-devel
No match for argument: unixODBC-utf16
No match for argument: unixODBC-utf16-devel
Error: No packages marked for removal.
[root@Fedora-Server yum.repos.d]# sudo yum install -y mssql-tools unixODBC-devel
packages-microsoft-com-prod                                                                                                           2.5 kB/s | 2.9 kB     00:01    
Package unixODBC-devel-2.3.7-1.fc29.x86_64 is already installed.
Dependencies resolved.
======================================================================================================================================================================
 Package                              Arch                            Version                              Repository                                            Size
======================================================================================================================================================================
Installing:
 mssql-tools                          x86_64                          17.2.0.2-1                           packages-microsoft-com-prod                          254 k

Transaction Summary
======================================================================================================================================================================
Install  1 Package

Total download size: 254 k
Installed size: 254 k
Downloading Packages:
mssql-tools-17.2.0.2-1.x86_64.rpm                                                                                                     194 kB/s | 254 kB     00:01    
----------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                                 193 kB/s | 254 kB     00:01     
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                                                              1/1 
Installed: mssql-tools-17.2.0.2-1.x86_64
  Running scriptlet: mssql-tools-17.2.0.2-1.x86_64                                                                                                                1/1 
The license terms for this product can be downloaded from
http://go.microsoft.com/fwlink/?LinkId=746949 and found in
/usr/share/doc/mssql-tools/LICENSE.txt . By entering 'YES',
you indicate that you accept the license terms.

Do you accept the license terms? (Enter YES or NO)
YES
  Installing       : mssql-tools-17.2.0.2-1.x86_64                                                                                                                1/1 
Installed: mssql-tools-17.2.0.2-1.x86_64
  Verifying        : mssql-tools-17.2.0.2-1.x86_64                                                                                                                1/1 

Installed:
  mssql-tools-17.2.0.2-1.x86_64                                                                                                                                       

Complete!
[root@Fedora-Server yum.repos.d]# sqlcmd -S localhost -U SA -P 'LiHan_950325'
Sqlcmd: Error: Microsoft ODBC Driver 17 for SQL Server : TCP Provider: Error code 0x2746.
Sqlcmd: Error: Microsoft ODBC Driver 17 for SQL Server : Client unable to establish connection.

**Comment by Powerhelmsman** [comment]
@LiHanGod This channel is for Docs site feedback and content issue instead of answering the general questions. Is your issue related to any specific content?

**Comment by LiHanGod** [comment]
I had a problem during the installation process. According to the tutorials on the official website, they all succeeded, but the connection was an error report.
[root@Fedora-Server yum.repos.d]# sqlcmd -S localhost -U SA -P 'LiHan_950325'
Sqlcmd: Error: Microsoft ODBC Driver 17 for SQL Server : TCP Provider: Error code 0x2746.
Sqlcmd: Error: Microsoft ODBC Driver 17 for SQL Server : Client unable to establish connection.

**Comment by Powerhelmsman** [comment]
@LiHanGod Could you provide the site link?

**Comment by LiHanGod** [comment]
This is the link to this page.
https://docs.microsoft.com/zh-cn/sql/linux/quickstart-install-connect-red-hat?view=sql-server-ver15
My system is Fedora，Version 29。Unable to connect，but installation is successful.

**Comment by Powerhelmsman** [comment]
@MightyPen Can you help the user on this question?

**Comment by MightyPen** [comment]
@Powerhelmsman Please reAssign this item 894 to MikeRayMSFT, who handles some of our docs/linux/ content.  Thank you.  (GeneMi)
CC: @MikeRayMSFT , @rothja , @LiHanGod

**Comment by LiHanGod** [comment]
Is there any progress on this issue?

**Comment by rothja** [comment]
@LiHanGod Hello, and sorry for the delay. I will try out these steps in a clean Red Hat 7.4 machine this morning to see if I get the same error. Just to let you know, if we can't see the same problem, then we won't be able to troubleshoot with you to figure it out in this content feedback item. But we can redirect you to support or forums for that assistance. 

One thing you can look at is the troubleshooting article for Linux. The first item is on troubleshooting connection failures. https://review.docs.microsoft.com/en-us/sql/linux/sql-server-linux-troubleshooting-guide?view=sqlallproducts-allversions&branch=release-sqlseattle One thing to try would be to connect directly to your IP address rather than using localhost.

**Comment by LiHanGod** [comment]
1. running state
```bash
[root@Fedora-Server ~]# systemctl status mssql-server.service 
● mssql-server.service - Microsoft SQL Server Database Engine
   Loaded: loaded (/usr/lib/systemd/system/mssql-server.service; disabled; vendor preset: disabled)
   Active: active (running) since Sat 2018-12-01 16:54:16 CST; 6s ago
     Docs: https://docs.microsoft.com/en-us/sql/linux
 Main PID: 1079 (sqlservr)
    Tasks: 1
   Memory: 821.0M
   CGroup: /system.slice/mssql-server.service
           └─1079 /opt/mssql/bin/sqlservr

Dec 01 16:54:16 Fedora-Server systemd[1]: Started Microsoft SQL Server Database Engine.
```

2. Installed package
```bash
[root@Fedora-Server ~]# dnf list unixODBC
Last metadata expiration check: 0:15:29 ago on Sat 01 Dec 2018 04:53:57 PM CST.
Installed Packages
unixODBC.x86_64                                                               2.3.7-1.fc29                                                                @fedora-opsx

[root@Fedora-Server ~]# dnf list unixODBC-devel
Last metadata expiration check: 0:18:34 ago on Sat 01 Dec 2018 04:53:57 PM CST.
Installed Packages
unixODBC-devel.x86_64                                                            2.3.7-1.fc29                                                             @fedora-opsx

[root@Fedora-Server ~]# dnf list mssql-tools
Last metadata expiration check: 0:19:34 ago on Sat 01 Dec 2018 04:53:57 PM CST.
Installed Packages
mssql-tools.x86_64                                                       17.2.0.2-1                                                       @packages-microsoft-com-prod

[root@Fedora-Server zFiles]# dnf list msodbcsql17
Last metadata expiration check: 0:22:03 ago on Sat 01 Dec 2018 04:53:57 PM CST.
Installed Packages
msodbcsql17.x86_64                                                       17.2.0.1-1                                                       @packages-microsoft-com-prod
```
3. Environmental  
```bash
[root@Fedora-Server zFiles]# cat /etc/profile
#SQLServer-Environment
PATH=$PATH:/opt/mssql-tools/bin
[root@Fedora-Server zFiles]# vi ~/.bashrc 
export PATH="$PATH:/opt/mssql-tools/bin"
```
4. Connect
```bash
[root@Fedora-Server zFiles]# ifconfig -a
eno1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.200  netmask 255.255.255.0  broadcast 192.168.1.255
        inet6 fe80::932c:f2a4:fb73:ce93  prefixlen 64  scopeid 0x20<link>
        ether d4:3d:7e:54:7c:7f  txqueuelen 1000  (Ethernet)
        RX packets 35631  bytes 49992044 (47.6 MiB)
        RX errors 0  dropped 1  overruns 0  frame 0
        TX packets 19640  bytes 1588009 (1.5 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device interrupt 20  memory 0xf7c00000-f7c20000  

[root@Fedora-Server zFiles]# sqlcmd -S 192.168.1.200 -U SA -P 'LiHan_950325'
Sqlcmd: Error: Microsoft ODBC Driver 17 for SQL Server : TCP Provider: Error code 0x2746.
Sqlcmd: Error: Microsoft ODBC Driver 17 for SQL Server : Client unable to establish connection.
```

Is this an installation problem or a package problem?
I also tried to download unixODBC-utf16-2.3.1-1.x86_64 and unixODBC-utf16-devel-2.3.1-1.x86_64.Again, this problem arises.
Is there anything else to offer?

**Comment by rothja** [comment]
@LiHanGod I'm sorry, I don't see why this is failing unless it is something unique to Fedora. There is one fool-proof way that you get use SQL on Fedora through Docker containers. If you can install Docker on Fedora, then you can use the docs to spin up a docker container with SQL in it (https://review.docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-docker?view=sqlallproducts-allversions&branch=release-sqlseattle). You'll want to look at the docker configuration article to use persistence with your container (https://review.docs.microsoft.com/en-us/sql/linux/sql-server-linux-configure-docker?view=sqlallproducts-allversions&branch=release-sqlseattle). If you map port 1433:1433 for your container, then all you have to do is run sqlcmd the same way you are doing here.

Before trying this, uninstall SQL Server locally first (do not uninstall the tools, because you can use those to connect to SQL Server in the container). 

Let me know if this might be an option to get SQL up and running on your system.

**Comment by LiHanGod** [comment]
Okay, I'll use mysql.
I look forward to the next update being used successfully on Fedora.
If you can, please give me a notice.
My mailbox is 568117769@qq.com.

**Comment by rothja** [comment]
@LiHanGod I apologize that we could not find a solution for you. If we come out with full support for Fedora, I will try to let you know. Thank you for reaching out to us.

#please-close

**Comment by MikeRayMSFT** [comment]
#please-close

**Comment by rothja** [comment]
@Powerhelmsman Can you help us close this issue? Thank you!
