### ISSUE TITLE
 Wrong Links when you download PDF

### ISSUE THREAD

**Issue by mairaw** [MicrosoftDocs/feedback#895]
Original GitHub issue https://github.com/dotnet/docs/issues/7925 from @n1v3k

Hello guys love the work on this documentation, I used to had a copy of this documentation, but lost that pdf, now that im trying to download again, the bookmark section all links takes you to the incorrect pages, anyway great material especially in pdf form where i can make annotations and whatnot.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3dff5a94-d9cd-e31b-4056-362abbe8d782
* Version Independent ID: cfb1ad21-e822-4075-2726-bd130ec2358d
* Content: [C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/)
* Content Source: [docs/csharp/index.md](https://github.com/dotnet/docs/blob/master/docs/csharp/index.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Powerhelmsman** [comment]
@dastaffo Can you take a look at this bug?

**Comment by Powerhelmsman** [comment]
@cillroy Can you follow up this issue?

**Comment by cillroy** [comment]
bug has been resolved and closing
