### ISSUE TITLE
download pdf option is showing all data if we require only particular data the option for that is not avail to download so better to provide

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#9]
download pdf option is showing all data if we require only particular data the option for that is not avail to download so better to provide

----------
⚠ Idea migrated from UserVoice

**Created By:** Anonymous
**Created On:** 2018/03/02 06:53:27 +0000
**Votes at Migration:** 1
**Supporters at Migration:** 1

**Comment by Powerhelmsman** [comment]
#log-suggestion

**Comment by Powerhelmsman** [comment]
#log-suggestion

**Comment by botcrane** [comment]
🚀 **ATTENTION**: [Internal request](https://ceapex.visualstudio.com/web/wi.aspx?pcguid=7d644393-99ad-41c8-ac53-7fa79294c720&id=20431) logged.

**Comment by Powerhelmsman** [comment]
@dastaffo Is there any update on this issue?

**Comment by dastaffo** [comment]
There's not enough information to make this particular issue actionable, so I'm closing it out.
