### ISSUE TITLE
is HttpContext Bug? in PageModel

### ISSUE THREAD

**Issue by xyz20533** [MicrosoftDocs/feedback#900]
**Describe the bug**
HttpContext.Session.SetString is always appearing NullReferenceException.

The example code  is HttpContext.Session.SetString("Test","test") that is PageModel's member.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Powerhelmsman** [comment]
@xyz20533 Can you provide the page link you refer to?

**Comment by Powerhelmsman** [comment]
@xyz20533 I have to close this issue so far due to lack of enough information.
