### ISSUE TITLE
Exchange Session Limits page

### ISSUE THREAD

**Issue by ericcox** [MicrosoftDocs/feedback#902]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**. (Which doesn't exist)

**Link to article:**
https://docs.microsoft.com/en-us/previous-versions/office/exchange-server-2010/ff477612(v=exchg.141)

**Problem:**
1. Where it says:

> Disable Session Limit   This limit disables session limits. Set the value to 0 to turn off session limits. Set the value to 1 to turn on session limits.

This seems backwards.  If it's truly this way, you might want to emphasize that the logic is actually backwards, or many will assume the document is wrong, not the code.  Considering the intermittent nature of users hitting these limits (AFAICT there's no way to tell how many objects are actually being opened by users), this will be very frustrating for an IT admin.

2. In that same section: are the registry value names ("Disable Session Limit", "Maximum Allowed Sessions Per User", etc) supposed to have spaces in them? None of the other registry key/value names have spaces.

**Comment by Powerhelmsman** [comment]
@ericcox Thanks for you feedback. Unforturnately, the content is no longer to update due to out of product lifecycle.

**Comment by ericcox** [comment]
Oops, thought I was looking at the 2013 docs. My mistake. But note that point #2 also applies to the 2013 docs: https://docs.microsoft.com/en-us/exchange/managed-store-limits-exchange-2013-help#configure-session-limits
