### ISSUE TITLE
Incorrect syntax in X++ statement

### ISSUE THREAD

**Issue by marcslevesque** [MicrosoftDocs/feedback#903]
Note there is no space for a comment on the page.

On the page https://docs.microsoft.com/en-us/previous-versions/dynamics/ax-2012/reference/aa548209%28v%3dax.60%29 the following statement syntax (at the bottom of the page) is incorrect:

select * from %1 where %2.Name=='Axapta' AND %3.JobID=='1234'

"AND" is not valid X++.

It should be:

select * from %1 where %2.Name=='Axapta' && %3.JobID=='1234'

**Comment by Powerhelmsman** [comment]
@marcslevesque Unfortunately this content is no longer to update due to out of product lifecycle. Can you go to new version of document?
