### ISSUE TITLE
Page overflow bug

### ISSUE THREAD

**Issue by mairaw** [MicrosoftDocs/feedback#905]
Original GitHub issue https://github.com/dotnet/docs/issues/8978 by @Damilope 

The page overflows, especially in focus mode and hides the overflowed parts making me have to switch between modes to read or copy content to test.
I added, "overflow-x: auto" to the styles in the "tutorial-row-main" class and it seems to fix everything. Even the overflowing of the whole page outside of focus mode.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1eb6b35f-44b4-b377-7e41-b865aa29d09e
* Version Independent ID: 35a57251-54ec-8ea9-298f-3033beca7731
* Content: [String interpolation - C# interactive tutorial](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/intro-to-csharp/interpolated-strings?tutorial-step=5)
* Content Source: [docs/csharp/tutorials/intro-to-csharp/interpolated-strings.yml](https://github.com/dotnet/docs/blob/live/docs/csharp/tutorials/intro-to-csharp/interpolated-strings.yml)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Powerhelmsman** [comment]
@dend can you take a look at this issue?

**Comment by dend** [comment]
@Damilope @mairaw could you please provide more information, along with a screenshot and browser information, if possible? Doesn't seem like I can repro.

**Comment by Damilope** [comment]
Here are the screenshots. And the browser is  Chrome version 70.0.3538.110.

**Comment by mairaw** [comment]
@Damilope attachments don't work via email response. Please come to the GitHub UI to attach them.

**Comment by Damilope** [comment]
Okay.
![01](https://user-images.githubusercontent.com/13324524/49413881-583a0d80-f73f-11e8-98de-c65c66b72b35.PNG)
![02](https://user-images.githubusercontent.com/13324524/49413882-583a0d80-f73f-11e8-8a0d-d58882ecc63a.PNG)

**Comment by Damilope** [comment]
@mairaw is there anything I can do?

**Comment by dend** [comment]
@Damilope @mairaw I cannot repro this on the latest version of Chrome, Firefox and Edge. Can you please clear the cache and try loading the page again?

**Comment by mairaw** [comment]
Yep, I can't repro either on Chrome.

**Comment by mairaw** [comment]
Can you confirm your browser and version? 

I am using version Version 70.0.3538.110 (Official Build) (64-bit) of Chrome for Windows.

**Comment by Damilope** [comment]
Mine is Chrome Version 70.0.3538.110 (Official Build) (64-bit) on Windows.

**Comment by dendeli-msft** [comment]
This should be fixed, thanks folks for the feedback!

Den Delimarsky ● Senior PM, docs.microsoft.com ● [@DennisCode](https://twitter.com/DennisCode)
