### ISSUE TITLE
Cannot able to open Remote Assist using ms-voip-video protocol

### ISSUE THREAD

**Issue by irfanIshakhan** [MicrosoftDocs/feedback#906]
I am writing an Unity3D application which open Remote assist using ms-voip-video. But not able to launch Remote Assist.

**To Reproduce**
1) Start unity3D 
2) Create a function to execute below code to start remote Assist Application
       string uriToLaunch = @"ms-voip-video:?contactids=ba65f699-sdfsdfsdfsdfsdfe37d5ad3b3a5";
       await Windows.System.Launcher.LaunchUriAsync(uri);
3) Build a solution for visual studio
4) Run it in Hololens device

**Expected behavior**
- Remote Assist application should open. 

**Hardware ans Device
 - Hololens

**Desktop (please complete the following information):**
 - Windows10
 - Chrome
 
** Software and versions
 - Unity3D 2017.4.15f1
 - Visual studio 2017 v15.8

**Comment by HosseinArabbeigi** [comment]
Same problem

**Comment by irfanIshakhan** [comment]
Hi @HosseinArabbeigi 

Please go through the comments on this article
https://blogs.msdn.microsoft.com/appconsult/2018/10/05/call-remote-assist-from-your-hololens-app/

**Comment by HosseinArabbeigi** [comment]
Thanks for your response @irfanIshakhan, i have imported sample code namespaces but still doesn't work.

**Comment by irfanIshakhan** [comment]
Unity is not handling the situation when there are more then one viop application installed in the hololens. Protocol "ms-voip-video" is used by other application like Skype. Try keeping only one voip application in device and launch again.

I have created an xamarin application to launch Remote Assist, here it will prompt you a list of voip application installed to choose.
