### ISSUE TITLE
Danish translation

### ISSUE THREAD

**Issue by HekiShavik** [MicrosoftDocs/feedback#907]
Hello. The "x minutes to read" currently is translated to "x minutter til læsning", which says something on the order of "x minutes until reading".

I would suggest "x minutters læsning" because it conveys the intended meaning.

**Comment by Powerhelmsman** [comment]
@SonjaSaltzman Can you take a look at this localization issue?

**Comment by SonjaSaltzman** [comment]
@bodhigautam - could you please follow up? Sounds like a bad translation on the template?

**Comment by bodhigautam** [comment]
@Powerhelmsman thanks for looping us in.
@SonjaSaltzman Yes, I am working on it.

**Comment by HekiShavik** [comment]
I like the new "Læsetid: x minutter". It is a Little more formal though, but it is much better than the previous "x minutter til læsning".

**Comment by SonjaSaltzman** [comment]
Great, thanks for letting us know @HekiShavik :-)
