### ISSUE TITLE
List Method Overview at Top of Documentation Pages

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#91]
When accessing cl*** or interface documentation, I am most interested in seeing a summary of available methods first.

In the new layout, I either have to scroll past a lengthy example block, or click a link in the sidebar to jump to the method summary.

Please restore the method overview to its location at the top of documentation pages.

Old Style Example (Preferred): https://msdn.microsoft.com/en-us/library/5y536ey6(v=vs.110).aspx

New Style Example: https://docs.microsoft.com/en-us/dotnet/api/system.collections.ilist?view=netframework-4.7.1

----------
⚠ Idea migrated from UserVoice

**Created By:** Michael
**Created On:** 2017/11/17 14:20:20 +0000
**Votes at Migration:** 2
**Supporters at Migration:** 2

**Comment by dend** [comment]
There are currently no plans to change this layout - method summaries are still available after the main class summary.
