### ISSUE TITLE
Customer Service Training Links

### ISSUE THREAD

**Issue by JerryCRMI** [MicrosoftDocs/feedback#912]
On this page https://docs.microsoft.com/en-us/learn/browse/?products=bizapps-d365

there are two Working with Customer Service Courses
Get started with managing cases in Dynamics 365 for Customer Service
Get started with Dynamics 365 for Customer Service

They take you to the same url
https://docs.microsoft.com/en-us/learn/modules/get-started-with-cases-for-dynamics-365-customer-service/

![image](https://user-images.githubusercontent.com/19864267/49250401-593c0980-f3e4-11e8-97ad-8cedab48d3db.png)

Jerry Weinstock
Microsoft Business Applications MVP

**Comment by Powerhelmsman** [comment]
@JerryCRMI It seems resolved already.
