### ISSUE TITLE
Link to Windows server 2016 docs does not work

### ISSUE THREAD

**Issue by Skymit** [MicrosoftDocs/feedback#913]
**Describe the bug**

**To Reproduce**
1. Go to 'https://docs.microsoft.com/ru-ru/windows/#pivot=it-pro' 
Go to 'https://docs.microsoft.com/en-us/windows-server/windows-server-2016'
![1](https://user-images.githubusercontent.com/6419191/49277299-3ff19680-f492-11e8-8690-cd99c43782c0.jpg)

3. See error 'https://docs.microsoft.com/windows-server/index'
![2](https://user-images.githubusercontent.com/6419191/49277300-3ff19680-f492-11e8-9bc5-2d30d5182d4b.jpg)

![3](https://user-images.githubusercontent.com/6419191/49277301-3ff19680-f492-11e8-8220-00471c21a32f.jpg)

![4](https://user-images.githubusercontent.com/6419191/49277302-408a2d00-f492-11e8-8dcd-962a633f9ab2.jpg)

**Comment by Powerhelmsman** [comment]
@SonjaSaltzman Can you take a look at this issue?

**Comment by SonjaSaltzman** [comment]
@nokura @v-cakoll not sure if this is from our content, can you please check if this is still an issue and if not, close this?

**Comment by v-cakoll** [comment]
@SonjaSaltzman @nokura I'm not able to repro this issue.

**Comment by nokura** [comment]
@Skymit 
I am sorry for the late reply.
The issue was reported in 2018 but the landing page design has been updated. Now it does not re-produce the issue. Will you please close this feedback?

Kind regards,
Microsoft DOCS International Team

**Comment by superfon** [comment]
W dniu piątek, 10 kwietnia 2020 Carolyn <notifications@github.com>
napisał(a):

**Comment by SonjaSaltzman** [comment]
Closing this issue as not repro; if there are any concerns, please don't hesitate to reopen.
Thank you,
Sonja
