### ISSUE TITLE
MS Learn Progression

### ISSUE THREAD

**Issue by joshuaboys** [MicrosoftDocs/feedback#919]
Currently it isn't very intuitive as to where you are in a learning path. (ie current progression) This is more pronounced for total beginners who when navigating back to the main docs site can and do choose the first in the list which isnt necessarily what they are working on. 
Your profile includes completed but not in progress plus the fact your profile has this info isnt intuitive.

**Comment by Powerhelmsman** [comment]
@yunyunyunyun Can you take a look at this suggestion?

**Comment by johnnystruck** [comment]
To add to @joshuaboys comment. This enhancement is a must for such an "e-learning" site.  Currently to find any in progress courses you must browse all courses from the ML home page or remember each course you are currently working on. From the home page you only can view/access your level (not that it matters) and access to your profile with completed courses  (badges) and completed learning paths (trophies).

**Comment by Regenhardt** [comment]
Seems MSFT kinda forgot about this issue.
The MS-learn profile page also has paths/modules in prgoress. Not sure for how long, but definitely since I started using it like a month ago.
