### ISSUE TITLE
Make it easier to find pages using Google search

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#92]
Usually when I'm looking for information I'll do a search on Google. For instance when searching a method in the framework API, like "Convert.ChangeType". Currently it will always point to msdn.microsoft.com and it is impossible for me to find the page I want at docs.microsoft.com even when using "site:". It either just doesn't find it or it will be a page not in English. Bing also doesn't show docs.microsoft.com on the first search page.

The API pages on msdn.microsoft.com have a link to docs.microsoft.com but then I have to type the search query again, which is not a good experience.

----------
⚠ Idea migrated from UserVoice

**Created By:** Herman Eldering
**Created On:** 2017/11/16 08:08:32 +0000
**Votes at Migration:** 2
**Supporters at Migration:** 2

**Comment by dend** [comment]
Work in progress as we are migrating content from MSDN to docs.

**Comment by dend** [comment]
Let's log a suggestion here #log-suggestion @dend @botcrane

**Comment by dend** [comment]
#log-suggestion @dend @botcrane

**Comment by dend** [comment]
#log-suggestion @dend @botcrane

**Comment by botcrane** [comment]
Failed to submit internal item.

**Comment by dend** [comment]
#log-suggestion @dend @botcrane

**Comment by botcrane** [comment]
Failed to submit internal item.

**Comment by dend** [comment]
#log-suggestion @dend @botcrane

**Comment by botcrane** [comment]
Failed to submit internal item.

**Comment by dend** [comment]
#log-suggestion @dend @botcrane

**Comment by botcrane** [comment]
Failed to submit internal item.

**Comment by dend** [comment]
#log-suggestion @dend @botcrane

**Comment by botcrane** [comment]
🚀 **ATTENTION**: [Internal request](https://ceapex.visualstudio.com/web/wi.aspx?pcguid=7d644393-99ad-41c8-ac53-7fa79294c720&id=21332) logged.

**Comment by dend** [comment]
#log-suggestion @botcrane

**Comment by botcrane** [comment]
🚀 **ATTENTION**: [Internal request](https://ceapex.visualstudio.com/web/wi.aspx?pcguid=7d644393-99ad-41c8-ac53-7fa79294c720&id=21333) logged.

**Comment by dend** [comment]
test

**Comment by dend** [comment]
Duplicate of #50
