### ISSUE TITLE
'Try It' Console within ALL 'KEYVAULT API 7.0' docs is wrongly coded

### ISSUE THREAD

**Issue by chungsu** [MicrosoftDocs/feedback#922]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

**Link to article:**
**All article for Key Vault API Version 7.0**
https://docs.microsoft.com/en-us/rest/api/keyvault/

**Problem:**
What's wrong with the article?

Issue : 'Request' url in 'Try It' Console is not correct. -> If triggered try with required information, it failed with 404 Error (Page Not Found)

> https://docs.microsoft.com~' is wrongly included in 'Request URL'. 

<Example : Get Certificate - Get Certificate>
https://docs.microsoft.com/en-us/rest/api/keyvault/getcertificate/getcertificate

1. Template
Current : 

GET https://docs.microsoft.com/en-us/rest/api/keyvault/getcertificate/%7BvaultBaseUrl%7D/certificates/%7Bcertificate-name%7D/%7Bcertificate-version%7D?api-version=7.0

Should be fixed to: 

GET https://%7BvaultBaseUrl%7D/certificates/%7Bcertificate-name%7D/%7Bcertificate-version%7D?api-version=7.0
Authorization: Bearer <bearer token>

2. API Tested with another application (POSTMAN)
Used Request URL within docs api (7.0) :
GET https://docs.microsoft.com/en-us/rest/api/keyvault/keyvault7.0/getcertificatecontacts/newkeyvaultcs.vault.azure.net/certificates/cscsc/6e70f1c8e07546b68befc1e0c46d351a?api-version=7.0

Removed wrong code -> it works
GET https://newkeyvaultcs.vault.azure.net/certificates/cscsc/6e70f1c8e07546b68befc1e0c46d351a?api-version=7.0

 

Please check this :)

**Comment by Powerhelmsman** [comment]
@dend Can you take a look at this feedback?

**Comment by dend** [comment]
#log-suggestion @dend

**Comment by botcrane** [comment]
🚀 **ATTENTION**: [Internal request](https://ceapex.visualstudio.com/web/wi.aspx?pcguid=7d644393-99ad-41c8-ac53-7fa79294c720&id=54131) logged.

**Comment by dend** [comment]
Thank you for the report, @chungsu - we're investigating the root cause.

**Comment by dendeli-msft** [comment]
@chungsu we have determined that the current implementation of the "Try It" experience on docs does not support custom base URLs. We are working with the team to add support for such capabilities in the future.

**Comment by dendeli-msft** [comment]
We're disabling Try It for Key Vault REST API docs for the time being, until we're able to support custom URLs. Thanks again for the feedback @chungsu!

Den Delimarsky ● Senior PM, docs.microsoft.com ● [@DennisCode](https://twitter.com/DennisCode)
