### ISSUE TITLE
Sample data on the design surface on the UWP does not take effect

### ISSUE THREAD

**Issue by HaoLife** [MicrosoftDocs/feedback#924]
**Describe the bug**
I used sample data on the design surface during the development of the UWP app, but found no effect, and it was effective for me to use the method in WPF with the same example, which should be a bug for the UWP app

**To Reproduce**
1.Add to xmlns:ds="using:Designs.Homes"
2.Add to d:DataContext="{d:DesignInstance Type=ds:MainDesign, IsDesignTimeCreatable=True}"
3. Add class MainDesign  and add Mock data.
4. Has no effect

**Expected behavior**

**Screenshots**
This place needs to show MainDesign Mock data.

**Desktop (please complete the following information):**
 - OS: windows10
 - Version 16299

**Additional context**
This question I do not know where to feedback, if the problem is not handled by you, whether you can tell where to feedback the problem

**Comment by Powerhelmsman** [comment]
@HaoLife Can you provide the page link you refer to?

**Comment by HaoLife** [comment]
https://docs.microsoft.com/zh-cn/windows/uwp/data-binding/displaying-data-in-the-designer

**Comment by Powerhelmsman** [comment]
@HaoLife Your issue is transferred to UWP team. They will help you there.
