### ISSUE TITLE
Download offline pdf of git with docs of git Command Line

### ISSUE THREAD

**Issue by glibnub** [MicrosoftDocs/feedback#93]
When downloading git documentation from https://docs.microsoft.com/en-us/vsts/git/tutorial/cherry-pick?tabs=command-line, I cannot see documentation for command line options on the PDF. Is it possible to include docs from both tab i.e. 'Visual Studio' and 'Command Line' on the pdf one after another. That would be great.

----------
⚠ Idea migrated from UserVoice

**Created By:** Suraj Kumar Shrestha
**Created On:** 2017/11/14 17:52:06 +0000
**Votes at Migration:** 2
**Supporters at Migration:** 2

**Comment by dend** [comment]
The PDF is generated from a single documentation set, therefore if the command line content is not in the table of contents, it will not be presented.

@dastaffo and @erickson-doug as FYI on this.
