### ISSUE TITLE
choosing ASP.Net Core version 2.2 produce no content in .NET API Browser

### ISSUE THREAD

**Issue by abuassar** [MicrosoftDocs/feedback#930]
**Describe the bug**
no content is showing if we choose version 2.2 of asp.net core

**To Reproduce**
1. Go to https://docs.microsoft.com/en-us/dotnet/api/?view=aspnetcore-2.2
2. See error "No namespaces"
3. Type "usermanager" in search box
4. See error "No results"

**Expected behavior**
A list of apis should show

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser: firefox
 - Version: 63

**Comment by Powerhelmsman** [comment]
@dend Can you take a look at this issue?

**Comment by stamminator** [comment]
ASP .NET Core 2.2 has been live for two weeks now, and there's still no public API documentation for it yet.

**Comment by guardrex** [comment]
Is there any status to report on this one?

**Comment by dendeli-msft** [comment]
This is now resolved, and the documentation shows up correctly.

**Comment by xinpingOnly** [comment]
hehe
