### ISSUE TITLE
Microsoft.AspNetCore.Authorization namespace missing

### ISSUE THREAD

**Issue by idealser** [MicrosoftDocs/feedback#932]
Microsoft.Aspnetcore.Authorization namespace is missing when using .NET Core 2.2

**To Reproduce**
1. Set TargetFramework of .csproj file to "netcoreapp2.2"
2. Set RuntimeFrameworkVersion to "2.2.0"
2. Include PackageReference "Microsoft.AspNetCore.App"
3. Try to use Authorize attribute or to Microsoft.AspNetCore.Authorization namespace in any controller.
4. Namespace is not found.

**Expected behavior**
Running the same project with net core 2.1 works fine. Tried to include Microsoft.AspNetCore.Authorization package explicitly using nuget with no success. Error appears to be the same.

**Screenshots**
![image](https://user-images.githubusercontent.com/28928275/49615480-58900e00-f9b6-11e8-8a22-e9b12631073d.png)

**Desktop:**
 - OS: Windows 10 x64
 - IDE: Visual Studio 15.9.3

**Comment by Powerhelmsman** [comment]
@idealser This channel is for Docs site feedback instead of product issue. Can you go to https://forums.asp.net/ to ask your question?
