### ISSUE TITLE
Learn experience points not calculating 

### ISSUE THREAD

**Issue by alexclowe** [MicrosoftDocs/feedback#935]
We have a few users with an experience point total that is actually going down as they complete more modules. https://techprofile.microsoft.com/en-us/pehrenreich is the user and their profile currently reads 1,725 XP when they clearly have more.

https://techprofile.microsoft.com/en-us/pehrenreich
https://techprofile.microsoft.com/en-us/Tawze
https://techprofile.microsoft.com/en-us/hulkrules
https://techprofile.microsoft.com/en-us/kristenmerritt
https://techprofile.microsoft.com/en-us/mbagley
https://techprofile.microsoft.com/en-us/lrudin
https://techprofile.microsoft.com/en-us/supersteve

**Comment by Powerhelmsman** [comment]
@saldana  Can you take a look at this issue?

**Comment by Sampy** [comment]
My team is taking a look now

**Comment by AndrewCook** [comment]
@alexclowe I researched this issue and it appears to be, that your points are showing a decrease each time you achieve a higher level. However, on your profile page when you go from level 8 to level 9 it will only show the points needed to complete the level and not your overall points. I'm hoping you can either confirm my hypothesis or provide some more information, so I may research this further.

**Comment by saldana** [comment]
@alexclowe we are closing this issue as we think @AndrewCook answered the question. Please reactivate if not. Thank you!
