### ISSUE TITLE
Remarks before Examples in Documentation

### ISSUE THREAD

**Issue by mairaw** [MicrosoftDocs/feedback#937]
Original GitHub issue https://github.com/dotnet/dotnet-api-docs/issues/1301 from @NetMage

In general, it seems to me that Remarks should precede Examples in the documentation, as without the Remarks explaining the background and purpose of classes, the Examples aren't always meaningful. Possibly after the members documentation as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b66ab1a-35aa-1bba-388c-30d698c1f50c
* Version Independent ID: d7dde1b9-fd16-dd30-6622-a15836579a9c
* Content: [HashSet&lt;T&gt; Class (System.Collections.Generic)](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.hashset-1?view=netframework-4.7.2)
* Content Source: [xml/System.Collections.Generic/HashSet`1.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Collections.Generic/HashSet`1.xml)
* Product: **dotnet-api**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by svick** [comment]
I suspect this is about deciding to which target audience to cater to.

Personally, I am, like you, @NetMage, usually looking for Remarks, to understand the details of how a member works.

But I think that many people are usually looking for a good Example, to understand how to use the member in the first place.

MSDN used to focus on the first group of people, by putting Remarks first. Docs.MS focuses on the second group, by putting Examples first.

I don't think there's a good way to satisfy both groups (one of the two sections has to go first). But what can be done is to make getting to the content you're looking for easy. And I think that's the case here: the In this article section at the right edge of the page lets you get to Remarks in one click.

Though I do wish it was that easy even for overloaded members, but that has been denied (see https://github.com/MicrosoftDocs/feedback/issues/446).

**Comment by NetMage** [comment]
That's why I picked a class's documentation instead of a member. Perhaps class documentation is best served Remarks first, and member documentation Example first.

**Comment by Powerhelmsman** [comment]
@dend Can you take a look at this suggestion?

**Comment by dendeli-msft** [comment]
Thanks folks for the feedback! After conducting research on the subject, we have concluded that at this time examples will remain in their current location, ahead of remarks.

Den Delimarsky ● Senior PM, docs.microsoft.com ● [@DennisCode](https://twitter.com/DennisCode)
