### ISSUE TITLE
Provide Code Samples (Especially Key Offerings Like Windows API / Univeral / Azure) In VB.Net

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#94]
Please consider spending less time embracing the Linux community and consider embracing your own instead. I've read the Microsoft "party-line" that VB.Net isn't dead, that it's developed a bit more slowly than C#, that Microsoft mistakenly believes that only Enterprise LOHB devs use VB.Net, etc etc..

It's a nice story, but as I look to adopt key bits of Azure, .Net Core, .Net Standard and UWP, it becomes clear that it's nothing more than a story. I just downloaded the UWP samples master from GitHub with an interest in 10-15 different samples. 0 were made available in VB.Net. The same goes for many Azure technologies that I might have subscribed to. In all honesty, I'm far more likely to find VB.Net samples in the documentation of 3rd party library developers than I am at Microsoft. Do you think that VB.Net devs will not be bitter about being abandoned after the sales pitch Microsoft gave that got us oboard with VB.Net in the first place. What you sold and what you're delivering differ greatly. Before begrudgingly going down the path of C#, I find it prudent to look for the first time at non-Microsoft options for development tools, SAAS platforms and operating systems. On one hand, I'm excited to see what I may have been missing with Google, Amazon, and other languages. On the other, I remain miffed at Microsoft for tricking me into drinking your "VB.Net / C# on even footing" KoolAide.

----------
⚠ Idea migrated from UserVoice

**Created By:** Berney Villers
**Created On:** 2017/11/14 10:39:22 +0000
**Votes at Migration:** 1
**Supporters at Migration:** 1

**Comment by Powerhelmsman** [comment]
#log-suggestion

**Comment by botcrane** [comment]
🚀 **ATTENTION**: [Internal request](https://ceapex.visualstudio.com/web/wi.aspx?pcguid=7d644393-99ad-41c8-ac53-7fa79294c720&id=21116) logged.

**Comment by Powerhelmsman** [comment]
I've created internal work item to track your requirement.

**Comment by dend** [comment]
Closing this issue as it's not something we can address on the docs.microsoft.com infrastructure side. Providing samples in different languages would be something content team can address individually - please leave feedback on specific articles about sample availability.
