### ISSUE TITLE
typo - Power Query M

### ISSUE THREAD

**Issue by gabrielsroka** [MicrosoftDocs/feedback#943]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

**Link to article:**
https://docs.microsoft.com/en-us/powerquery-m/quick-tour-of-the-power-query-m-formula-language

**Problem:**
change
```
Let  
   Variablename = expression,  
   #"Variable name" = expression2  
In   
   Variablename
```
to
```
let  
   Variablename = expression,  
   #"Variable name" = expression2  
in   
   Variablename
```

`let` and `in` should be lowercase.

**Comment by Powerhelmsman** [comment]
@Minewiskan Can you take a look at this typo?

**Comment by Minewiskan** [comment]
@gabrielsroka - Thank you for catching this! Now fixed. Your contribution to improving docs is much appreciated.

**Comment by Minewiskan** [comment]
#please-close
