### ISSUE TITLE
typos: Power Query - comments

### ISSUE THREAD

**Issue by gabrielsroka** [MicrosoftDocs/feedback#944]
**Link to article:**
https://docs.microsoft.com/en-us/powerquery-m/comments

**Problem:**
the comments are formatted wrong (they were erroneously escaped):
change `\/\/` to `//` 
change `\/\*` to `/*`, etc
also `\[`, `\#`, `\=`, etc. need to be unescaped

**Comment by Powerhelmsman** [comment]
@Minewiskan Can you take a look at this issue?

**Comment by Minewiskan** [comment]
@gabrielsroka - Thank you for catching this! This likely happened in a recent markdown conversion. I've updated them. Again, thank you for contributing.

**Comment by Minewiskan** [comment]
#please-close
