### ISSUE TITLE
email adress not valid

### ISSUE THREAD

**Issue by m123j123** [MicrosoftDocs/feedback#946]
If you want to write an email to request a new supported R package in Power BI, there is always an email coming back that it is not allowed to send emails to powerbiai@microsoft.com. my email I sent out gone to rinpbifb@microsoft.com but there seems to be a forwarding to the powerbiai@microsoft.com.

Soo: Where shall I write to to get my request placed?

**Comment by Powerhelmsman** [comment]
@m123j123 Can you go to https://community.powerbi.com/ to provide your request for product feedback?
