### ISSUE TITLE
Microsoft.Insights/components - Template Reference Missing

### ISSUE THREAD

**Issue by danstis** [MicrosoftDocs/feedback#951]
**Link to article:** 
https://docs.microsoft.com/en-gb/azure/templates/microsoft.insights/allversions

**Problem:**
The template reference for Microsoft.Insights/components is missing since the last update of the azure/templates section.

**Comment by Powerhelmsman** [comment]
@tomfitz Can you take a look at this feedback?

**Comment by tfitzmac** [comment]
@danstis - thanks for this feedback. Components has been added back to the template reference.

**Comment by tfitzmac** [comment]
#please-close

**Comment by danstis** [comment]
Thanks @tfitzmac, much appreciated!
