### ISSUE TITLE
Product Page needs branding update for Azure Monitor

### ISSUE THREAD

**Issue by nromyn** [MicrosoftDocs/feedback#953]
On this page, a link is provided to Log Analytics. https://docs.microsoft.com/en-ca/azure/#pivot=products&panel=mgmt

The page that is linked is to is branded Azure Monitor. This is confusing for users who may not be aware of re-branding/re-labelling efforts. https://docs.microsoft.com/en-ca/azure/azure-monitor/overview

**Comment by Powerhelmsman** [comment]
@tysonn Can you take a look at user's feedback?

**Comment by tysonn** [comment]
Reported internally, thanks for the report.

**Comment by dendeli-msft** [comment]
Closing the issue, as this is expected at this time. See [FAQ](https://docs.microsoft.com/en-us/azure/azure-monitor/platform/log-faq).
