### ISSUE TITLE
Article only refers to old versions and seems to have no link to similar documentation for newer versions.

### ISSUE THREAD

**Issue by pabrams** [MicrosoftDocs/feedback#955]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.
There's already a comment in there dated two weeks ago.  I upvoted it.

**Link to article:**
https://docs.microsoft.com/en-us/tfs/server/admin/move-clone-hardware?view=tfs-2013
https://docs.microsoft.com/en-us/tfs/server/admin/move-clone-hardware?view=tfs-2015
https://docs.microsoft.com/en-us/tfs/server/admin/move-clone-hardware?view=tfs-2017
https://docs.microsoft.com/en-us/tfs/server/admin/move-clone-hardware?view=tfs-2018

**Problem:**
The only versions of TFS mentioned are TFS 2015 and TFS 2013.  What about TFS 2017?  Where is the article for that?  Please link to it somehow, or at least mention recent versions.  How do I Clone TFS 2017 from the command line?  I know the wizard is supposed to take care of stuff we previously had to do manually, like PrepareClone and ChangeServerId commands (not sure how I figured that out, since I now cannot find the documentation), but it seems like installing from the command line (using TFSConfig's `unattend` parameter) does not.

**Comment by Powerhelmsman** [comment]
@pabrams Your feedback is transferred to the content team. They will address there. @elbatk Can you response it ASAP?

**Comment by pabrams** [comment]
Were the articles updated or something? I can't figure out what the original issue was anymore.  I do see that all of the articles linked above seem to be identical  - the paths seem to all contain "12.0", and the "Note" in the Prepare Clone section is incorrect for [TFS 2013](https://docs.microsoft.com/en-us/azure/devops/server/admin/move-clone-hardware?view=tfs-2013#clone-option-reconfigure-server-ids-and-remap-databases) and [TFS 2015](https://docs.microsoft.com/en-us/azure/devops/server/admin/move-clone-hardware?view=tfs-2015#clone-option-reconfigure-server-ids-and-remap-databases).
