### ISSUE TITLE
Translation in french is wrong

### ISSUE THREAD

**Issue by cherrierj** [MicrosoftDocs/feedback#958]
**Link to article:**
https://docs.microsoft.com/fr-fr/azure/cloud-solution-provider/overview/azure-csp-available-services

**Problem:**
The translation in french is wrong, it says excatly the contrary of the english text. 

what is written in english : keep in mind that not all Azure services are currently available in the CSP program.

what is written in french : n’oubliez pas que tous les services Azure sont actuellement disponibles dans le programme CSP.

what the french says in english : keep in mind that all Azure services are currently available in the CSP program.

**Comment by Powerhelmsman** [comment]
@SonjaSaltzman Can you take a look at this issue?

**Comment by SonjaSaltzman** [comment]
@DavidPrio can you please follow up and fix the translations? cc @ishasahni1

**Comment by CeciAc** [comment]
Hello, @cherrierj 
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @cherrierj 
 
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/fr-fr/azure/cloud-solution-provider/overview/azure-csp-available-services. 

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.
	
Kind regards,
Microsoft DOCS International Team
