### ISSUE TITLE
Subscribe to updates for a particular article or topic area

### ISSUE THREAD

**Issue by supernova-eng** [MicrosoftDocs/feedback#96]
Subscribe to updates for a particular article or topic area. Receive notification whenever an article or set of articles changes.

----------
⚠ Idea migrated from UserVoice

**Created By:** Tom Resing
**Created On:** 2017/11/09 00:04:13 +0000
**Votes at Migration:** 6
**Supporters at Migration:** 6

**Comment by Powerhelmsman** [comment]
Thanks for your suggestion. I've created a internal work item to track your request.

**Comment by Powerhelmsman** [comment]
#log-suggestion

**Comment by botcrane** [comment]
🚀 **ATTENTION**: [Internal request](https://ceapex.visualstudio.com/web/wi.aspx?pcguid=7d644393-99ad-41c8-ac53-7fa79294c720&id=21120) logged.

**Comment by keziamicro** [comment]
Hello - reviewing and cleaning up some older feedback/issues. Thanks!
