### ISSUE TITLE
AzureMaps API + PowerApps Custom Connector = Token keeps expiring

### ISSUE THREAD

**Issue by SeaDude** [MicrosoftDocs/feedback#961]
**Describe the bug**

**To Reproduce**
1. Create an Azure Maps Service
2. Create a Custom Connector in PowerApps
3. Click "Test" in PA Custom Connector Area
4. Receive a 400 error with the message: "...token has expired"
5. Issue happens after an unknown period. 
![image](https://user-images.githubusercontent.com/8636973/49973552-75629f00-feea-11e8-8181-5f8cfd0739d7.png)

**Expected behavior**
Some way to submit a token expiration period as part of the API Request.

**Screenshots**
See above

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 70.0.3538.110 (Official Build) (64-bit)

**Comment by Powerhelmsman** [comment]
@SeaDude What's content page link you refer to?

**Comment by SeaDude** [comment]
@Powerhelmsman : https://docs.microsoft.com/en-us/rest/api/maps/ and all Maps subpages.

**Comment by Powerhelmsman** [comment]
@sethmanheim Can you take a look at this feedback?

**Comment by sethmanheim** [comment]
@Powerhelmsman I'm sorry, I don't work on this area.

**Comment by Powerhelmsman** [comment]
@dendeli-msft Can you assign it to the right person?

**Comment by SeaDude** [comment]
To be clear, I'm looking for the Azure Maps API (and likely ALL Azure API docs) to include information about Token Expiration. The current Azure Maps API Docs DO NOT specify token expiration. I'm unsure whether the other Azure API docs specify this parameter.
Thank you.

**Comment by SeaDude** [comment]
@Powerhelmsman : https://docs.microsoft.com/en-us/rest/api/maps/ and all Maps subpages.

**Comment by dendeli-msft** [comment]
The person with the most context here would be @chgennar

**Comment by chgennar** [comment]
@SeaDude -  Azure Maps currently performs authorization using subscription keys that need to be manually rotated

**Comment by SeaDude** [comment]
Hi @chgennar. Thanks for the response. I understand the use of subscription keys. I'm using said subscription keys in creation of the Custom Connect**or**. The issue lies with the Connect**ion** used by the Custom Connector. It seemed to time out every now and then giving the above error message. 
The Custom Connector is working now, so I'm not sure what changed. Anyway. I'll close the issue.
