### ISSUE TITLE
How do I edit Microsoft Docs articles that do not have the Edit button that redirects to Github?

### ISSUE THREAD

**Issue by gansopro** [MicrosoftDocs/feedback#965]
Hello guys! I want to contribute to Microsoft Docs by editing this series of articles, but none of them have the Edit button at the top.

https://docs.microsoft.com/pt-br/windows/desktop/ - Develop Windows desktop applications

I also did not find the repository of these articles here on Github. How do I in these cases?

**Comment by Powerhelmsman** [comment]
@ginami Can you take a look at this issue?

**Comment by gansopro** [comment]
> @ginami Can you take a look at this issue?

I did not understand.

**Comment by mairaw** [comment]
@gansopro eles estão contatando uma das pessoas responsáveis por aquele conteúdo para tentar entender porque o botão de Editar não está presente. Algumas documentações no docs não estão abertas a contribuições. Eu acredito que o repositório desse conteúdo específico seja só interno.

**Comment by gansopro** [comment]
> @gansopro eles estão contatando uma das pessoas responsáveis por aquele conteúdo para tentar entender porque o botão de Editar não está presente. Algumas documentações no docs não estão abertas a contribuições. Eu acredito que o repositório desse conteúdo específico seja só interno.

Então quer dizer que não há nada que eu possa fazer para editar este repositório?

**Comment by ginami** [comment]
Hi @gansopro -- thank you for your question. Our Desktop docs are not currently open for public edits. I'll check to see if we have a plan to change that. Thank you!

**Comment by ginami** [comment]
Hi @gansopro -- we do plan to open the desktop docs to public edit in the near future, but I don't have a specific date. Please keep an eye on the docs. Thank you!

**Comment by gansopro** [comment]
> Hi @gansopro -- we do plan to open the desktop docs to public edit in the near future, but I don't have a specific date. Please keep an eye on the docs. Thank you!

Thanks for the answer, I will wait patiently for you to open this repository for me to edit.
