### ISSUE TITLE
Microsoft Graph - Angular Tutorial - Missing install command, Typo in Typescript code

### ISSUE THREAD

**Issue by turbolego** [MicrosoftDocs/feedback#968]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

Page has no comment section.

**Link to article:**
https://docs.microsoft.com/en-us/graph/tutorials/angular?tutorial-step=1

**Problem:**

**Missing**
(ERROR in src/app/app.module.ts(1,27): error TS2307: Cannot find module '@ng-bootstrap/ng-bootstrap'.):

`npm install --save @ng-bootstrap/ng-bootstrap`

**Typo**
(AppRoutingModule is written twice):

`imports: [
  BrowserModule,
  AppRoutingModule
  AppRoutingModule,
  NgbModule,
  FontAwesomeModule
]`

Should be:

`imports: [
    BrowserModule,
    AppRoutingModule,
    NgbModule,
    FontAwesomeModule
  ]`

**Typo**
(In both _nav-bar.component.ts_ and _home.component.ts_, tslint wants ' rather than "):

`  signIn(): void {
    // Temporary
    this.authenticated = true;
    this.user = {
      displayName: "Adele Vance",
      email: "AdeleV@contoso.com"
    };
  }`

Should be:

`  signIn(): void {
    // Temporary
    this.authenticated = true;
    this.user = {
      displayName: 'Adele Vance',
      email: 'AdeleV@contoso.com'
    };
  }`

**Comment by jasonjoh** [comment]
Hi guys, sorry for the delay, I was out on extended vacation for the holidays. Thanks for the feedback @turbolego! I've opened an issue on the content repository (https://github.com/microsoftgraph/msgraph-training-angularspa/issues/2) to track this. @Powerhelmsman you can close this.
