### ISSUE TITLE
Improve readability

### ISSUE THREAD

**Issue by docs-product** [MicrosoftDocs/feedback#97]
The readability of the api page is MUCH worse than the old page. Comparing:
https://msdn.microsoft.com/enus/library/system.timespan.days(v=vs.110).aspx
to: 
https://docs.microsoft.com/en-us/dotnet/api/system.timespan.days?view=netframework-4.7.1#System_TimeSpan_Days

There's to much distraction for the eyes when reading the text in the body. The sidebar and the actions div intrude on the visual space of the body too much - there needs to more margin to the text in the body. The eyes / the focus is drawn to the left, maybe because the scrollbar has the same/similar color as the background of the code.text, drawing the eyes to the left. 
This really takes too much effort to read currently. 

----------
⚠ Idea migrated from UserVoice

**Created By:** Mikael
**Created On:** 2017/11/06 09:08:54 +0000
**Votes at Migration:** 1
**Supporters at Migration:** 1

**Comment by Powerhelmsman** [comment]
@kubeaver Can you take a look at this suggestion?

**Comment by kubeaver** [comment]
@Powerhelmsman We've recorded all of these same items and are working through a redesign to tone down the page chrome so that the content is easier to focus on.

**Comment by Powerhelmsman** [comment]
#log-suggestion @ShevaDas

**Comment by botcrane** [comment]
🚀 **ATTENTION**: [Internal request](https://ceapex.visualstudio.com/web/wi.aspx?pcguid=7d644393-99ad-41c8-ac53-7fa79294c720&id=26023) logged.

**Comment by dendeli-msft** [comment]
Closing this item, as we've done a number of improvements that make the overall page readability better.
