### ISSUE TITLE
LinkedIn API returns comments without an author

### ISSUE THREAD

**Issue by felicio** [MicrosoftDocs/feedback#971]
**Describe the bug**
LinkedIn API returns comments without an author. Specifically, `https://api.linkedin.com/v2/socialActions/{shareUrn|ugcPostUrn|commentUrn}/comments` endpoint does not return `actor` field.

`actor` is described like so:
>Entity which authored the comment – [source][1]

**To Reproduce**
```
GET /v2/socialActions/urn%3Ali%3Aactivity%3A6479385795177259008/comments
Host: api.linkedin.com
X-Restli-Protocol-Version: 2.0.0
```

```
{
  "elements": [
    {
      "created": {
        "time": 1545044917660
      },
      "lastModified": {
        "time": 1545044917660
      },
      "id": "6480388078321045504",
      "message": {
        ...
      },
      "$URN": "urn:li:comment:(urn:li:activity:6479385795177259008,6480388078321045504)",
      "object": "urn:li:activity:6479385795177259008"
    },
    ...
  ],
  "paging": {
    "total": 3,
    "count": 10,
    "start": 0,
    "links": []
  }
}
```

**Expected behavior**
As per docs, comment objects should have `actor` field set to the URN of author of the comment.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
API Version: LinkedIn API v2, Social Actions API

[1]: https://docs.microsoft.com/en-us/linkedin/marketing/integrations/community-management/shares/network-update-social-actions

**Comment by felicio** [comment]
@Powerhelmsman it's quoted above, [here](https://docs.microsoft.com/en-us/linkedin/marketing/integrations/community-management/shares/network-update-social-actions).

**Comment by Powerhelmsman** [comment]
@abarron-linkedin Can you take a look at this feedback?

**Comment by abarron-linkedin** [comment]
@felicio Since this is a functionality question rather than docs feedback, can you please submit your request through Zendesk?

**Comment by felicio** [comment]
Issue on Zendesk: 
https://linkedin.zendesk.com/hc/en-us/requests/9792
