### ISSUE TITLE
LinkedIn API returns less shares than requested

### ISSUE THREAD

**Issue by felicio** [MicrosoftDocs/feedback#972]
**Describe the bug**
LinkedIn API returns less shares (46) than requested (50). Specifically, `count` is not equal to `elements.length` despite more shares being available. Instead, next `start` parameter is overridden in `paging.links`.

>We recommend setting the sharesPerOwner to 1,000 and count to 50, which means the endpoint returns up to 1,000 shares per owner, while the total elements returned per response is 50. – [source][1]

**To Reproduce**
```
GET /v2/shares?q=owners&amp; owners=urn:li:organization:2056516&amp; sharesPerOwner=1000&amp; count=50&amp; start=0
Host: api.linkedin.com
X-Restli-Protocol-Version: 2.0.0
```

```
{
  "elements": [
    ...
    {
      "owner": "urn:li:organization:2056516",
      "activity": "urn:li:activity:6480468120329809920",
      "edited": false,
      "created": {
        ...
        "time": 1545064001085
      },
      "serviceProvider": "LINKEDIN",
      "id": "6480468119964913664",
      "lastModified": {
        ...
        "time": 1545064273553
      },
      "text": {
        ...
      },
      "distribution": {
        "linkedInDistributionTarget": {
          "visibleToGuest": true
        }
      },
      "content": {
        ...
      }
    },
    ...
  ],
  "paging": {
    "total": 2230,
    "count": 50,
    "start": 0,
    "links": [
      {
        "rel": "next",
        "href": "/v2/shares?count=50&owners=urn%3Ali%3Aorganization%3A2056516&q=owners&sharesPerOwner=1000&start=46",
        "type": "application/json"
      }
    ]
  }
}
```

**Expected behavior**
As per docs, total elements returned per response should be equal to requested `count`.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
API Version: LinkedIn v2, Shares API

[1]: https://docs.microsoft.com/en-us/linkedin/marketing/integrations/community-management/shares/share-api

**Comment by felicio** [comment]
@Powerhelmsman it's quoted above, [here](url
https://docs.microsoft.com/en-us/linkedin/marketing/integrations/community-management/shares/share-api).

**Comment by Powerhelmsman** [comment]
@abarron-linkedin Can you take a look at this feedback?

**Comment by abarron-linkedin** [comment]
@felicio Since this is a bug report rather than docs feedback, can you please submit your request through Zendesk?

**Comment by abarron-linkedin** [comment]
@Powerhelmsman Can you please help close this out? I don't have the ability to close issues within this space.

**Comment by felicio** [comment]
Issue on Zendesk: 
https://linkedin.zendesk.com/hc/en-us/requests/9793
