### ISSUE TITLE
Azure Pricing site has a retired link in section If my deployed instance says "stopped,” am I still getting billed?

### ISSUE THREAD

**Issue by jdickson289** [MicrosoftDocs/feedback#974]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

**Link to article:**
https://azure.microsoft.com/en-us/pricing/details/virtual-machines/linux/
If my deployed instance says "stopped,” am I still getting billed?
Full details on virtual machine states are available here.

**Problem:**
Here link https://msdn.microsoft.com/library/dn763934.aspx is broken as the article has been retired.  Need to update the link to point directly to Azure Virtual Machines FAQ https://azure.microsoft.com/documentation/articles/virtual-machines-questions/

**Comment by Powerhelmsman** [comment]
@jdickson289 Can you try the link https://feedback.azure.com/forums/34192--general-feedback?query=Azure%20Pricing%20site%20has%20a%20retired%20link%20in%20section%20If%20my%20deployed%20instance%20says%20%22stopped%2C%E2%80%9D%20am%20I%20still%20getting%20billed%3F
There are a lot of related question and answers. If you can't find the answer, please submit your feedback there.
