### ISSUE TITLE
Module Browsing Page User Experience

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#98]
https://docs.microsoft.com/en-us/powershell/module/
The 'All Packages" drop down list closes when user attempts to scroll down. The list items at the bottom of the list are not selectable because the drop down list closes.

----------
⚠ Idea migrated from UserVoice

**Created By:** Lyle Snodgrass
**Created On:** 2017/11/05 16:51:49 +0000
**Votes at Migration:** 1
**Supporters at Migration:** 1

**Comment by dend** [comment]
This has now been addressed.
