### ISSUE TITLE
Cannot edit powerquery-m docs

### ISSUE THREAD

**Issue by greijer** [MicrosoftDocs/feedback#980]
I cannot edit details in technical documentation for  power query m language at this address
https://docs.microsoft.com/en-us/powerquery-m/table-distinct
The missing edit button may indicate that the contribution isnt enabled for this sub-site yet.
Am I correct?

**Comment by Powerhelmsman** [comment]
@greijer Yes, if the edit button is not enable, that means it is not open for public edit.
