### ISSUE TITLE
Provide mechanism to download sample without downloading entire repo

### ISSUE THREAD

**Issue by Rick-Anderson** [MicrosoftDocs/feedback#982]
Currently you need to download an entire repo to get access to a sample. This is a copy of https://github.com/aspnet/Docs/issues/8967

@TXX-JSR wrote: 

It takes too long to download 800MB - how can I download just the project I need ?

There is CHROME a plugin to do this: chrome.google.com/webstore/detail/gitzip-for-github/ffabmkklhbepgcgfonabamgnfafbdlkn

I believe it exists for Firefox as well

**Comment by Powerhelmsman** [comment]
@dendeli-msft Can you take a look at this request?

**Comment by dendeli-msft** [comment]
The work on functionality that will improve this experience is currently in progress!

**Comment by dendeli-msft** [comment]
Updating this issue - we are currently in the process of rolling out the new experience for code samples, that should enable this functionality.

**Comment by docs-product** [comment]
The new experience is out: https://docs.microsoft.com/samples, and supports downloading a specific samples instead of cloning the entire repository.
