### ISSUE TITLE
Spelling issue

### ISSUE THREAD

**Issue by uc-ojv** [MicrosoftDocs/feedback#985]
![2018-12-21_1515](https://user-images.githubusercontent.com/10045552/50336156-66579e80-0533-11e9-8057-2ea2b086a762.png)
**Link to article:**
https://docs.microsoft.com/en-us/system-center/vmm/network-pool?view=sc-vmm-1807

**Problem:**
Spelling mistake, instead of site, stie is written https://www.screencast.com/t/RMTPqm2H

**Comment by rayne-wiselman** [comment]
Please assign to @JYOTHIRMAISURI who handles System Center documentation

**Comment by JYOTHIRMAISURI** [comment]
@rayne-wiselman 

Thanks, Rayne. Will look into this.

**Comment by JYOTHIRMAISURI** [comment]
@uc-ojv 

Thanks for bringing this to our notice. Will fix this. Currently we have a publishing holiday, this fix will be available in January first week. Will keep you posted.

**Comment by rayne-wiselman** [comment]
@JYOTHIRMAISURI please fix and then mark this as #please-close

**Comment by JYOTHIRMAISURI** [comment]
@rayne-wiselman and @uc-ojv 

Hi Rayne,

This is fixed and live.  

https://docs.microsoft.com/en-us/system-center/vmm/network-pool?view=sc-vmm-1807

![image](https://user-images.githubusercontent.com/23717548/50843394-9a81ea80-138e-11e9-8013-129e8016f914.png)

**Comment by JYOTHIRMAISURI** [comment]
#please-close

**Comment by uc-ojv** [comment]
Thanks a lot Jyothi and Microsoft Team to take issue into your consideration
