### ISSUE TITLE
Command Option Name is wrong on the Functions Tutorial doc in Japanese

### ISSUE THREAD

**Issue by yoichiro** [MicrosoftDocs/feedback#988]
**🛑 IMPORTANT**: In the Functions Tutorial doc in Japanese, the option name of the `az functionapp config appsettings` command sample is wrong. Therefore, the result of the command execution must be an error.

**Link to article:**
https://docs.microsoft.com/ja-jp/azure/functions/tutorial-static-website-serverless-api-with-database?tutorial-step=2

**Problem:**
To configure the `FUNCTIONS_EXTENSION_VERSION` value, the tutorial introduces the following command:

```bash
az functionapp config appsettings set --name <function app name> --g first-serverless-app --settings FUNCTIONS_EXTENSION_VERSION=~1
```

However, the `--g` option name is wrong. Therefore, the following error occurs at executing the command above:

`az: error: unrecognized arguments: --g first-serverless-app`

The correct option name is `-g` (the count of the `-` characters must be 1, not 2). That is, the correct command is as the following:

```bash
az functionapp config appsettings set --name <function app name> -g first-serverless-app --settings FUNCTIONS_EXTENSION_VERSION=~1
```

When I checked the page in English, I noticed that the correct option `-g` is used. I guess that this issue is only in the Japanese page. For many Japanese developers, I expect that this issue should be fixed quickly.

**Comment by Powerhelmsman** [comment]
@SonjaSaltzman Can you take a look at this localization issue?

**Comment by SonjaSaltzman** [comment]
@DavidPrio  could you please take care of this one?

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs.ja-jp #1590](https://github.com/MicrosoftDocs/azure-docs.ja-jp/issues/1590) via [**ZenHub**](https://www.zenhub.com/)

**Comment by yoichiro** [comment]
@CeciAc Ok, I see. Thank you  for handling this issue!
