### ISSUE TITLE
Make fonts for ## H2 vs ### H3 more or qualitatively different from each other.

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#99]
When I scroll through an article, sometimes I see both a ## H2 header and a ### H3 header in the display pane at the same time. In these cases I can perceive that one of the two headers is slightly smaller than the other, enabling me to understand which is H2 vs H3. However, depending on current vertical scroll location...
Often there is only one header in the current display, either an H2 or H3. The problem is I struggle to be sure which header type it is, H2 or H3. There are actions I can take to gain certainty, but having to take any such action is a h***le and distraction.
Please make ## H2 navyBlue, or implement some other *qualitative* distinction between the H2 vs H3 font. Thanks. GeneMi 2017/11/03

----------
⚠ Idea migrated from UserVoice

**Created By:** GeneMi
**Created On:** 2017/11/03 16:58:42 +0000
**Votes at Migration:** 1
**Supporters at Migration:** 1

**Comment by Powerhelmsman** [comment]
@kubeaver Can you take a look at this?

**Comment by kubeaver** [comment]
@Powerhelmsman we're working through new header stack now. This should be updated in the coming months.

**Comment by Powerhelmsman** [comment]
#log-suggestion

**Comment by botcrane** [comment]
🚀 **ATTENTION**: [Internal request](https://ceapex.visualstudio.com/web/wi.aspx?pcguid=7d644393-99ad-41c8-ac53-7fa79294c720&id=21144) logged.

**Comment by dend** [comment]
We've done some improvements to the UX, where the headings are much better presented.
