### ISSUE TITLE
Fix the code example wrongly separated

### ISSUE THREAD

**Issue by KaeLL** [MicrosoftDocs/feedback#990]
https://docs.microsoft.com/en-us/windows/desktop/learnwin32/your-first-windows-program

Code example seems to be separated by nested < code > tags or something.

**Comment by Powerhelmsman** [comment]
@ginami Can you take a look at this issue?

**Comment by ginami** [comment]
Hi @KaeLL -- thank you for letting us know! We'll work on updating the page.
