### ISSUE TITLE
code does not compile

### ISSUE THREAD

**Issue by bugaevski** [MicrosoftDocs/feedback#991]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

**Link to article:**
https://docs.microsoft.com/en-us/dotnet/framework/security/how-to-build-claims-aware-aspnet-web-forms-app-using-wif

**Problem:**
code does not compile

**Comment by Powerhelmsman** [comment]
@bugaevski Your issue is transferred to the team. They will help you there.
