### ISSUE TITLE
Wrong name of function in date.endofweek in text

### ISSUE THREAD

**Issue by donsvensen** [MicrosoftDocs/feedback#995]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

**Link to article:**
https://docs.microsoft.com/en-us/powerquery-m/Date-EndOfWeek

**Problem:**
The syntax refers to the function 
Date.StartOfWeek

should the 

Date.EndOfWeek

/Erik Svensen

**Comment by Powerhelmsman** [comment]
@Minewiskan @mikekinsman Can you take a look at this issue?

**Comment by Minewiskan** [comment]
@donsvensen  Thanks for catching. It has been corrected.
#please-close

**Comment by Minewiskan** [comment]
#please-close
